<?php

$Definition['%1$s "%2$s" not found.'] = '%1$s "%2$s" nerasta.';
$Definition['%1$s Version %2$s'] = '%1$s Versija %2$s';
$Definition['%1$s version %2$s is available.'] = '%1$s versija %2$s prieinama.';
$Definition['%s is not a valid email address'] = '%s neteisingas el. pašto adresas';
$Definition['%s item in queue'] = '%s įrašų eilėje';
$Definition['%s level'] = '%s lygis';
$Definition['%s levels'] = '%s lygiai';
$Definition['%s site(s) found.'] = 'aptikta %s svetainė(-ių)';
$Definition['%s sources(s) found.'] = 'rasti(-as) %s šaltiniai(-is).';
$Definition['%s times'] = '%s kartų';
$Definition['%s unavailable'] = '%s neįmanoma';
$Definition['%s user(s) found.'] = 'rasti(-as) %s vartotojai(-s).';
$Definition['%s user(s) will be affected by this action.'] = '%s naudotojas(-ų) bus paveikti šio veiksmo.';
$Definition['%s years.'] = '%s metai.';

$Definition['(less)'] = '(mažiau)';
$Definition['(more)'] = '(daugiau)';

$Definition['1 day'] = '1 diena';
$Definition['1 hour'] = '1 valanda';
$Definition['1 month'] = '1 mėnuo';
$Definition['1 month after being sent'] = '1 mėnuo nuo išsiuntimo';
$Definition['1 week'] = '1 savaitė';
$Definition['1 week after being sent'] = '1 savaitė nuo išsiuntimo';
$Definition['2 weeks after being sent'] = '2 savaitės nuo išsiuntimo';
$Definition['4 hours'] = '4 valandos';
$Definition['5 minutes'] = '5 minutės';
$Definition['15 minutes'] = '15 minučių';

$Definition['[%s] Confirm Your Email Address'] = '[%s] Patvirtinti savo el. pašto adresą';
$Definition['[%s] Invitation'] = '[%s] Pakvietimas';
$Definition['[%s] Password Reset'] = '[%s] Slaptažodžio keitimas';
$Definition['[%s] Password Reset Request'] = '[%s] Slaptažodžio keitimo prašymas';

$Definition['a Badge'] = 'Medalis';
$Definition['Abilites'] = 'Galimybės';
$Definition['Abilities'] = 'Galimybės';
$Definition['Above Main Content'] = 'Virš pagrindinio turinio';
$Definition['Account Sync Failed'] = 'Paskyros sinchronizavimas nepavyko';
$Definition['Action'] = 'Veiksmas';
$Definition['Actions Based on Votes'] = 'Veiksmai pagrįsti balsais';
$Definition['Activity Item'] = 'Aktyvumo įrašas';
$Definition['Activity item not found.'] = 'Aktyvumo įrašas nerastas.';
$Definition['Add Category'] = 'Įdėti kategoriją';
$Definition['Add Connection'] = 'Sukurti sujungimą';
$Definition['Added By'] = 'Sukurė';
$Definition['Add Info &amp; Create Account'] = 'Patalpinti informaciją ir sukurti naudotoją';
$Definition['Adding & Editing Categories'] = 'Kategorijų kūrimas ir redagavimas';
$Definition['Add Item'] = 'Sukurti įrašą';
$Definition['Addons'] = 'Priedai';
$Definition['Add Role'] = 'Pridėti rolę';
$Definition['Add User'] = 'Sukurti naudotoją';
$Definition['Advanced Category Settings'] = 'Išplėstiniai kategorijų nustatymai';
$Definition['Advanced Embed Settings'] = 'Išplėstiniai įterpimo nustatymai';
$Definition['Advanced Forum Settings'] = 'Išplėstiniai forumo nustatymai';
$Definition['Advanced Options'] = 'Išplėstinės parinktys';
$Definition['Advanced Settings'] = 'Išplėstiniai nustatymai';
$Definition['After'] = 'Po';
$Definition['a full year.'] = 'visi metai.';
$Definition['Alive'] = 'Įjungtas';
$Definition['All %1$s'] = 'Visi %1$s';
$Definition['All Dashboard Pages'] = 'Visi įrankių panelės puslapiai';
$Definition['All Forum Pages'] = 'Visi forumo puslapiai';
$Definition['Allow embedded content'] = 'Įgalinkite įterptinį turinį';
$Definition['Allow images'] = 'Įgalinkite paveikslus';
$Definition['Allow new users to be registered through email.'] = 'Leisti naujus naudotojus užsiregistruoti per el. paštą.';
$Definition['All Pages'] = 'Visi puslapiai';
$Definition['API Status'] = 'API būsena';
$Definition['Applicant'] = 'Prašytojas';
$Definition['Applicant Role'] = 'Select the role that should be applied for new applicants. This only applies if you have the <b>approval</b> registration method.';
$Definition['Application'] = 'Programa';
$Definition['Application ID'] = 'Programos ID';
$Definition['Applications'] = 'Programos';
$Definition['Application Secret'] = 'Programos paslaptis';
$Definition['Applied by Administrator'] = 'Pritaikyta administratoriaus';
$Definition['Applied Manually'] = 'Pritaikytas rankiniu būdu';
$Definition['Applied On'] = 'Data';
$Definition['Approval'] = 'Patvirtinimas';
$Definition['Archive Discussions'] = 'Archyvuoti diskusijas';

$Definition['Background Color'] = 'Užnugario spalva';
$Definition['Badge Name'] = 'Vardas';
$Definition['BadgeRecipientsHeading'] = 'Most recent recipients';
$Definition['Badge Requests'] = 'Medalių prašymai';
$Definition['Ban Item'] = 'Įrašas';
$Definition['Ban List'] = 'Blokuojamų narių sąrašas';
$Definition['Banner'] = 'Reklamjuostė';
$Definition['Banner Logo'] = 'Reklamjuostės logotipas';
$Definition['Banner Title'] = 'Reklamjuostės pavadinimas';
$Definition['Banning'] = 'Blokavimas';
$Definition['Banning Options'] = 'Blokavimo nustatymai';
$Definition['Ban Type'] = 'Tipas';
$Definition['Basic Information'] = 'Pagrindinė informacija';
$Definition['Before'] = 'Prieš';
$Definition['Begin At'] = 'Pradėti nuo';
$Definition['Below Sidebar'] = 'Žemiau šoninės panelės';
$Definition['Blocked'] = 'Blokuotas';
$Definition['Blog Comments'] = 'Tinklaraščio komentarai';
$Definition['Bookmark a discussion using its star icon.'] = 'Pasižymėkite svarstymus pasinaudodami jos žvaigždutės paveklsiuku';
$Definition['Browse Addons'] = 'Peržiūrėti priedus';
$Definition['Button Background Color'] = 'Mygtuko užnugario spalva';
$Definition['Button Text Color'] = 'Mygtuko užrašo rašalo spalva';

$Definition['Categories &amp; Discussions'] = 'Kategorijos ir diskusijos';
$Definition['Categories are used to organize discussions.'] = 'Skirsniai naudojami sudėlioti lankytojams savo svarstymus prasminga Jūsų bendruomenei tvarka.';
$Definition['Categories Layout'] = 'Kategorijų išdėstymas';
$Definition['Category Page Layout'] = 'Kategorijos puslapio išdėstymas';
$Definition['Category Url:'] = 'Kategorijos nuoroda:';
$Definition['Censored Words'] = 'Cenzūruoti žodžiai';
$Definition['Change Log'] = 'Pakeitimų žurnalas';
$Definition['Change the look of All Categories'] = 'You can change the look of the <b>All Categories</b> page <a href="%s">here</a>.';
$Definition['Check out the new community forum I\'ve just set up.'] = 'Sveikas, drauguži!


Apsilankyk mano naujoje bendruomenės svarstymų aikštėje, kurią ką tik įrengiau. Tai puiki vieta mudviem paplepėti tinkle.';
$Definition['Choose Avatar'] = 'Pasirinkti avatarą';
$Definition['Clean Spam'] = 'Išvalyti brukalus';
$Definition['comment(s)'] = 'komentaras(-ai)';
$Definition['Comment  Body'] = 'Komentaras | Pranešimo tekstas';
$Definition['Comment Settings'] = 'Komentarų nustatymai';
$Definition['Comments Page'] = 'Komentarų puslapis';
$Definition['Comments per Page'] = 'Komentarai viename puslapyje';
$Definition['Comment  Subject'] = 'Komentaras | Tema';
$Definition['Condition'] = 'Sąlyga';
$Definition['Condition Expression'] = 'Reikšmė';
$Definition['Condition Field'] = 'Laukelis';
$Definition['Conditions'] = 'Sąlygos';
$Definition['Condition Type'] = 'Tipas';
$Definition['Confirmation  Body'] = 'Patvirtinimas | Pranešimo tekstas';
$Definition['Confirm email addresses'] = 'Require users to confirm their email addresses (recommended)';
$Definition['Conversation Messages'] = 'Žinutės';
$Definition['Conversations'] = 'Pokalbiai';
$Definition['Conversations Setup'] = 'Pokalbių nustatymai';
$Definition['Could not find a theme identified by \'%s\''] = 'Tema \'%s\' nerasta';
$Definition['CreateFile'] = 'Sukurti';
$Definition['Criteria'] = 'Kriterijus';
$Definition['Current File:'] = 'Esamas failas:';
$Definition['Current Theme'] = 'Esama tema';

$Definition['Decline'] = 'Atmesti';
$Definition['Default  Category'] = 'Numatyta | Kategorija';
$Definition['Default Locale'] = 'Numatytoji lokalė';
$Definition['Default Roles'] = 'Numatytosios rolės';
$Definition['default type'] = 'numatytasis';
$Definition['Delete Badge'] = 'Pašalinti medalį';
$Definition['Delete Category'] = 'Ištrinti kategoriją';
$Definition['Delete Role'] = 'Pašalinti rolę';
$Definition['Delete User'] = 'Ištrinti vartotoją';
$Definition['Delete User: %s'] = 'Ištrinti vartotoją : %s';
$Definition['Deleting category...'] = 'Trinama kategorija ...';
$Definition['Description'] = 'Aprašymas';
$Definition['Did You Know?'] = 'Ar tu žinojai?';
$Definition['Disable'] = 'Išjungti';
$Definition['Disabled'] = 'Išjungtas';
$Definition['Disable Signatures'] = 'Išjungti parašus';
$Definition['discussion(s)'] = 'diskusija(-os)';
$Definition['Discussion  Body'] = 'Diskusija | Pranešimo tekstas';
$Definition['Discussions Layout'] = 'Diskusijų išdėstymas';
$Definition['Discussion  Subject'] = 'Diskusija | Tema';
$Definition['Download Locale List'] = 'Atsiųsti lokalių sąrašą';
$Definition['DownloadLocalePack'] = 'Atsiųsti';
$Definition['Download Locale Pack'] = 'Atsiųsti lokalės paketą';

$Definition['Edit Category'] = 'Koreguoti kategoriją';
$Definition['Edit CSS'] = 'Koreguoti CSS';
$Definition['Edit HTML'] = 'Taisyti nuorodų žymėjimo kalba, HTML\'u';
$Definition['Edit Message'] = 'Koreguoti žinutę';
$Definition['Edit User'] = 'Koreguoti vartotoją';
$Definition['Email Styles'] = 'Laiškų išvaizdos';
$Definition['Enable'] = 'Įgalinti';
$Definition['Enable/Disable'] = 'Įgalinti/Apriboti';
$Definition['Enabled %1$s'] = 'Įgalinta %1$s';
$Definition['Enable embedding to use blog comments.'] = 'In order for this to work, you will need to enable embedding.';
$Definition['Encourage your friends to join your new community!'] = 'Padrąsink draugus prisijungti prie naujos bendruomenės!';
$Definition['Error sending email. Please review the addresses and try again.'] = 'Išsiunčiant laišką, įvyko klaida. Prašome pasitikrinti, ar teisingai nurodyta pašto dėžutė, o tada bandykite dar karta.';
$Definition['Every %s hour'] = 'Every hour';
$Definition['Every %s minute'] = 'Every minute';
$Definition['Every %s second'] = 'Every second';
$Definition['Every 1 minute'] = 'Kas 1 minutę';
$Definition['Every Page'] = 'Kiekvienas puslapis';
$Definition['Everything is ok.'] = 'Viskas yra gerai.';
$Definition['Exit Preview'] = 'Uždaryti peržiūrą';

$Definition['Facebook Settings'] = 'Facebook nustatymai';
$Definition['Failure'] = 'Gedimas';
$Definition['FaviconBrowse'] = 'Browse for a new favicon if you would like to change it:';
$Definition['FaviconDescription'] = 'Your site\'s favicon appears in your browser\'s title bar. It will be scaled to 16x16 pixels.';
$Definition['FileUpload is currently OFF'] = 'Dokumentų įkėlimas išjungtas';
$Definition['FileUpload is currently ON'] = 'Dokumentų įkėlimas įjungtas';
$Definition['Finished'] = 'Baigta';
$Definition['First Visit'] = 'Pirmasis apsilankymas';
$Definition['Forum Settings'] = 'Forumo nustatymai';
$Definition['Frequency'] = 'Dažnis';

$Definition['Generate'] = 'Generuoti';
$Definition['Generate Client ID and Secret'] = 'Generuoti kliento ID ir paslaptį';
$Definition['Get More Applications'] = 'Rasti daugiau programų';
$Definition['Get More Plugins'] = 'Rasti daugiau įskiepių';
$Definition['Get More Themes'] = 'Rasti daugiau temų';
$Definition['give'] = 'suteikti';
$Definition['Give a Badge'] = 'Skirti apdovanojimą.';
$Definition['Guest roles'] = 'Check all roles that should be applied to guests.';

$Definition['Hash Algorithm'] = 'Maišos algoritmas';
$Definition['HeadlineFormat.AddUser'] = '{ActivityUserID,user} added an account for {RegardingUserID,user}.';
$Definition['HeadlineFormat.PictureChange'] = '{RegardingUserID,You} changed {ActivityUserID,your} profile picture.';
$Definition['HeadlineFormat.RegistrationApproval'] = '{ActivityUserID,user} approved the applications for {RegardingUserID,user}.';
$Definition['HeadlineFormat.Status'] = '{ActivityUserID,user}';
$Definition['HeadlineFormat.WallPost'] = '{RegardingUserID,you} &rarr; {ActivityUserID,you}';
$Definition['Hide from the recent discussions page.'] = 'Pasislėpti paskutinių diskusijų puslapyje.';
$Definition['Hide signatures for guests'] = 'Paslėpkite svečių pasirašymus.';
$Definition['Hide signatures on embedded comments'] = 'Paslėpkite pasirašymus įterptiems atsiliepimams.';
$Definition['Homepage'] = 'Pradžios tinklapis';
$Definition['Homepage Title'] = 'Pradžios tinklapio pavadinimas';
$Definition['How to use themes'] = 'Kaip naudoti temas';
$Definition['Html'] = 'Nuorodų ženklinimo kalba, HTML\'as';
$Definition['HTML Emails'] = 'Laiškai su įgalinta žymių ženklinimo kalba';

$Definition['Indexes'] = 'Indeksai';
$Definition['Information'] = 'Informacija';
$Definition['Invitation Code'] = 'Pakvietimo kodas';
$Definition['InvitationMessage'] = 'Hi Pal!

Check out the new community forum I\'ve just set up. It\'s a great place for us to chat with each other online.

Follow the link below to log in.';
$Definition['Invitations per month'] = 'Pakvietimų per mėnesį';
$Definition['Invitations will expire'] = 'Pakvietimai nustos galioti';
$Definition['Invited by'] = 'Pakvietė';

$Definition['jsConnect Client Libraries'] = 'jsConnect kliento bibliotekos';
$Definition['jsConnect Documentation'] = 'jsConnect dokumentacija';

$Definition['Key Type'] = 'Rakto tipas';
$Definition['Key Value'] = 'Rakto reikšmė';

$Definition['Large images will be scaled down.'] = 'Dideli paveikslai bus sumažinti iki galimo didžiausio ploto %s bei galimo didžiausio aukščio %s, nurodyta vaizduoklio taškais. ';
$Definition['Last Visit'] = 'Paskutinis prisijungimas';
$Definition['Level'] = 'Lygis';
$Definition['Likes'] = 'Patinka';
$Definition['Locale Name'] = 'Lokalės vardas';
$Definition['Locales'] = 'Lokalės';
$Definition['Location'] = 'Vieta';
$Definition['LogoBrowse'] = 'Browse for a new banner logo if you would like to change it:';

$Definition['Manage'] = 'Valdyti';
$Definition['Manage Applicants'] = 'Tvarkyti pareiškėjus';
$Definition['Manage Applications'] = 'Tvarkyti programas';
$Definition['Manage Badges'] = 'Tvarkyti medalius';
$Definition['Manage Categories'] = 'Tvarkyti kategorijas';
$Definition['Manage Messages'] = 'Tvarkyti žinutes';
$Definition['Manage Plugins'] = 'Tvarkyti papildinius';
$Definition['Manage Roles & Permissions'] = 'Tvarkyti taisykles ir leidimus';
$Definition['Manage Spam'] = 'Tvarkyti šlamštą';
$Definition['Manage Themes'] = 'Tvarkyti temas';
$Definition['Manage Users'] = 'Tvarkyti vartotojus';
$Definition['Managing Categories'] = 'Tvarkyti kategorijas';
$Definition['Manual'] = 'Rankinis';
$Definition['Max %s length'] = 'Galimas didžiausias ilgis %s';
$Definition['Max Comment Length'] = 'Maksumalus komentaro ilgis';
$Definition['Max height of %s'] = 'Galimas didžiausias aukštis %s';
$Definition['Max height of %s in pixels'] = 'Galimas didžiausias aukštis %s, nurodyta vaizduoklio taškais';
$Definition['Max number of %s'] = 'Galimas didžiausias skaičius %s';
$Definition['Member roles'] = 'Check all roles that should be applied to new/approved users.';
$Definition['Message ID'] = 'Žinutės ID';
$Definition['Method'] = 'Metodas';
$Definition['Mixed Layout'] = 'Mišrus išdėstymas';
$Definition['Modern Layout'] = 'Modernus išdėstymas';
$Definition['My Invitations'] = 'Mano pakvietimai';

$Definition['Need More Help?'] = 'Reikia daugiau pagalbos?';
$Definition['never'] = 'niekada';
$Definition['NewApplicantEmail'] = 'New applicant:';
$Definition['No drafts.'] = 'Nėra juodraščių';
$Definition['No results for %s.'] = 'No results for <b>%s</b>.';
$Definition['Note:'] = 'Pastaba:';
$Definition['Notes'] = 'Pastabos';
$Definition['Notifications will appear here.'] = 'Perspėjimai atsidurs čia.';
$Definition['NotifyApplicant'] = 'Notify me when anyone applies for membership.';
$Definition['Not Spam'] = 'Ne brukalas';

$Definition['On'] = 'Įjungti';
$Definition['Operation By'] = 'Nuo';
$Definition['Organize'] = 'Tvarkyti';
$Definition['Organize Categories'] = 'Tvarkyti kategorijas';
$Definition['Original Version'] = 'Originali versija';
$Definition['Or select an image on your computer (2mb max)'] = 'Arba pasirinkti paveiksliuką iš kompiuterio (2mb max)';
$Definition['Other Themes'] = 'Kitos temos';
$Definition['Outgoing Email Address'] = 'Išsiunčiamasis el. paštas';

$Definition['Page Color'] = 'Tinklalapio spalva';
$Definition['Password Options'] = 'Slaptažodžio nustatymai';
$Definition['Permission'] = 'Leidimas';
$Definition['Permission.Category'] = 'Kategorija';
$Definition['Permissions'] = 'Leidimai';
$Definition['Please Confirm'] = 'Prašau patvirtinti';
$Definition['Plugin'] = 'Įskiepis';
$Definition['Plugins'] = 'Įskiepiai';
$Definition['Polls'] = 'Apklausos';
$Definition['Post Format'] = 'Įrašo formatas';
$Definition['Preview Colors'] = 'Iš anksto peržiūrėkite spalvas';
$Definition['Private Key'] = 'Privatus raktas';
$Definition['Provider'] = 'Tiekėjas';
$Definition['Public Key'] = 'Viešas raktas';

$Definition['Ranks'] = 'Rangai';
$Definition['Reaction Types'] = 'Reakcijos tipas';
$Definition['Recent News'] = 'Paskutinės naujienos';
$Definition['Record Content'] = 'Turinys';
$Definition['Refresh Comments'] = 'Atnaujinti komentarus';
$Definition['Register Url'] = 'Registracijos nuoroda';
$Definition['Registration'] = 'Registracija';
$Definition['Remove Email Logo'] = 'Pašalinkite laiško ženklą';
$Definition['Repeat'] = 'Kartoti';
$Definition['Replace Image'] = 'Pakeisti paveiksliuką';
$Definition['Reply  To'] = 'Atsakyti | Kam';
$Definition['Request'] = 'Užklausa';
$Definition['Reveal Password'] = 'Parodyti slaptažodį';
$Definition['Role'] = 'Rolė';
$Definition['Roles determine user\'s permissions.'] = 'Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.';

$Definition['Save Colors'] = 'Išsaugokite spalvas';
$Definition['Search by user or role.'] = 'Narių galima ieškoti naudojant slapyvardį arba el. pašto adresą. Taipogi galima ieškoti pagal naudotojo ID, rolės pavadinimą, arba &ldquo;banned&rdquo;.';
$Definition['Security'] = 'Saugumas';
$Definition['Select'] = 'Pažymėti';
$Definition['Send %s a Message'] = 'Išsiųsti %s žinutę';
$Definition['Send a confirmation email when people ask a question or start a discussion over email.'] = 'Išsiųsti priminimą el. paštu kuomet žmogus užduodą klausimą arba pradeda naują diskusiją el. paštu.';
$Definition['Send Again'] = 'Siųsti dar kartą';
$Definition['Send a Test Email'] = 'Išsiųskite bandomąjį laišką';
$Definition['Send Invitations!'] = 'Siųsti pakvietimus!';
$Definition['SignedOut'] = 'You are signed out.';
$Definition['Sign In Url'] = 'Prisijungimo nuoroda';
$Definition['Site Description'] = 'Svetainės aprašymas';
$Definition['Site Name'] = 'Svetainės pavadinimas';
$Definition['Slug'] = 'Šūkis';
$Definition['SMTP Password'] = 'SMTP slaptažodis';
$Definition['SMTP User'] = 'SMTP naudotojas';
$Definition['Spoof'] = 'Apsimesti';
$Definition['Start Discussions'] = 'Pradėti diskusiją';
$Definition['Statistics'] = 'Statistika';
$Definition['Styles'] = 'Stiliai';

$Definition['Table Layout'] = 'Lentelės išdėstymas';
$Definition['take away'] = 'atimti';
$Definition['Test Email'] = 'Bandomasis laiškas';
$Definition['Test email from %s'] = 'Patikrinkite laišką iš %s';
$Definition['Test Email Message'] = '<p>Tai bandomasis laiškas.</p>

<p>Jūs galite pakeisti savo svarstymų aikštės laiškų išvaizdą, nuėję į laiškų tinklalapį savo valdymo lentoje.</p> ';
$Definition['Test Mode'] = 'Test Mode: The pocket will only be displayed for pocket administrators.';
$Definition['Text Color'] = 'Užrašo rašalo spalva';
$Definition['TextEnterEmails'] = 'Type email addresses separated by commas here';
$Definition['The client ID uniqely identifies the site.'] = 'The client ID uniqely identifies the site. You can generate a new ID with the button at the bottom of this page.';
$Definition['The email has been sent.'] = 'Laiškas jau išsiųstas,';
$Definition['The homepage title is displayed on your home page.'] = 'The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.';
$Definition['Theme Options'] = 'Temos parinktys';
$Definition['Themes'] = 'Temos';
$Definition['There\'s been an error uploading the image. Your email logo can uploaded in one of the following filetypes: gif, jpg, png'] = 'Įvyko klaida įkeliant paveikslą. Jūsų laiškų ženklas turėtų būti vieno iš galimų rinkmenų pavidalo: gif, jpg ar png.';
$Definition['The secret secures the sign in process.'] = 'The secret secures the sign in process. Do <b>NOT</b> give the secret out to anyone.';
$Definition['The site description usually appears in search engines.'] = 'The site description usually appears in search engines. You should try having a description that is 100–150 characters long.';
$Definition['The specified url code is already in use by another category.'] = 'Nurodytas nuorodos kodas jau yra naudojamas kitoje kategorijoje.';
$Definition['This connection is in test-mode.'] = 'Šis sujungimas yra bandymo režime.';
$Definition['This Database'] = 'Ši duomenų bazė';
$Definition['This page requires Javascript.'] = 'Šiam puslapiui reikalingas Javascript.';
$Definition['This pocket is an ad.'] = 'Ši kišenė yra vilioklis.';
$Definition['This theme has additional options.'] = 'This theme has additional options on the %s page.';
$Definition['This theme has customizable text.'] = 'This theme has text that you can customize.';
$Definition['Thumbnails'] = 'Miniatiūros';
$Definition['Titles'] = 'Pavadinimai';
$Definition['Turn OFF'] = 'Išjungti';

$Definition['Universal Code'] = 'Universalus kodas';
$Definition['Universal Forum Embed Code'] = 'Plačiai tinkamas svarstymų aikštės įterptinis užrašas';
$Definition['Unlimited'] = 'Neribota';
$Definition['Upload New Email Logo'] = 'Įkelkite naują laiško ženklą';
$Definition['Use an SMTP server to send email'] = 'Naudoti SMTP serverį siųsti laiškus';
$Definition['Use asterisks for wildcards'] = 'Naudokitės žvaigždutėmis galimiems platesniems išrinkimams, pvz.: &lsquo;*@hotmail.com&rsquo;';
$Definition['Use Categories'] = 'Naudoti kategorijas';
$Definition['User Count'] = 'Naudotojai';
$Definition['UserDelete'] = 'Pašalinti naudotojo turinį';
$Definition['User Deleted'] = 'Naudotojas pašalintas';
$Definition['UserDeleteMessage'] = 'Delete the user and completely remove all of the user\'s content. This may cause discussions to be disjointed. Best option for removing spam.';
$Definition['UserDeletionPrompt'] = 'Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).';
$Definition['UserKeep'] = 'Palinkti vartotojo turinį';
$Definition['UserKeepMessage'] = 'Delete the user but keep the user\'s content.';
$Definition['User Registration Settings'] = 'Naudotojo registracijos nustatymai';
$Definition['User Summary'] = 'Naudotojo reziumė';
$Definition['Users with the no ads permission will not see this pocket.'] = 'Lankytojai, neturintys leidimo dėti vilioklius, nematys šios kišenės. ';
$Definition['UserWipe'] = 'Blank User Content';
$Definition['UserWipeMessage'] = 'Delete the user and replace all of the user\'s content with a message stating the user has been deleted. This gives a visual cue that there is missing information.';
$Definition['Use the content at this url as your homepage.'] = 'Choose the page people should see when they visit: <strong style="white-space: nowrap;">%s</strong>';

$Definition['Vanilla.Archive.Description'] = 'You can choose to archive forum discussions older than a certain date. Archived discussions are effectively closed, allowing no new posts.';
$Definition['Vanilla.Categories.MaxDisplayDepth'] = 'Place nested categories in a comma-delimited list when they are %1$s';
$Definition['Vanilla is installed!'] = 'Vanilla įdiegta!';
$Definition['Verified!'] = 'Patikrinta!';
$Definition['Version'] = 'Versija';
$Definition['Version %s'] = 'Versija %s';
$Definition['version %s'] = 'versija %s';
$Definition['View Page'] = 'Rodyti puslapį';

$Definition['Warning: deleting is permanent'] = 'WARNING: deleted items are removed from this list and cannot be brought back.';
$Definition['Welcome to Vanilla!'] = 'Sveiki atvykę į Vanilla!';
$Definition['WordPress Plugin'] = 'WordPress įskiepis';

$Definition['You can also ban the users that posted the spam and delete all of their posts.'] = 'Check the box next to the user that posted the spam to also ban them and delete all of their posts. <b>Only do this if you are sure these are spammers.</b>';
$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'If you are ever locked out of your forum you can always log in using your original Vanilla email and password at <a href="%1$s">%1$s</a>';
$Definition['You can make the categories page your homepage.'] = 'You can make your categories page your homepage <a href="%s">here</a>.';
$Definition['You can send emails in plain text by disabling the toggle below.'] = 'Išjungę perjungiklį apačioje, Jūs galite siųsti laiškus kaip paprastus užrašus.';
$Definition['You must manually apply this rank.'] = 'Tu turi rankiniu būdu pritaikyti šį rangą.';
$Definition['Your default locale won\'t display properly'] = 'Your default locale won\'t display properly until it is enabled below. Please enable the following: %s.';
$Definition['Your inbox is empty.'] = 'Jūs neturite atsiųstų laiškų.';
