<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s ha accettato l\'invito di %4$s per diventare membro.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s ha cambiato i permessi di %4$s.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s ha cambiato l\'immagine del profilo di %6$s.';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s ha commentato %4$s di %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s ha creato un account per %4$s.';
$Definition['%1$s joined.'] = '%1$s si è registrato.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s ha citato %3$s in %8$s.';
$Definition['%1$s on %2$s'] = '%1$s il %2$s';
$Definition['%1$s signed in.'] = '%1$s si è autenticato.';
$Definition['%1$s to %2$s'] = '%1$s a %2$s';
$Definition['%1$s to %2$s of %3$s'] = 'Da %1$s a %2$s di %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s ha aggiornato il profilo di %6$s.';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s è stato aggiunto alle %2$s di %3$s  .';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s è stato rimosso dalle %2$s di %3$s  .';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s è stato rimosso dalle %2$s %3$s ed aggiunto alle %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s ha scritto su %5$s %4$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s ha approvato la richiesta di %2$s per diventare membro.';
$Definition['%3$s created an account for %1$s.'] = '%3$s ha creato un account per %1$s.';
$Definition['%s$1 to %s$2'] = 'Da %s$1 a %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = 'Da %s$1 a %s$2 di %s$3';
$Definition['%s (Current)'] = '%s (Corrente)';
$Definition['%s Agrees'] = '%s È d\'accordo';
$Definition['%s and you'] = '%s e te';
$Definition['%s Awesomes'] = '%s Mi piace';
$Definition['%s by %s'] = '%s da %s';
$Definition['%s changed %s\'s permissions.'] = '%s ha cambiato i permessi per %s.';
$Definition['%s Comment'] = '%s Commento';
$Definition['%s comment'] = '%s commento';
$Definition['%s Comments'] = '%s Commenti';
$Definition['%s comments'] = '%s commenti';
$Definition['%s Connect'] = '%s Accedi';
$Definition['%s day'] = '%s giorno';
$Definition['%s days'] = '%s giorni';
$Definition['%s deleted this conversation.'] = '%s ha eliminato questa conversazione.';
$Definition['%s discussion'] = '%s discussione';
$Definition['%s discussions'] = '%s discussioni';
$Definition['%s has been Jailed.'] = '%s è stato bloccato';
$Definition['%s has left this conversation.'] = '%s ha lasciato questa conversazione.';
$Definition['%s hour'] = '%s ora';
$Definition['%s hours'] = '%s ore';
$Definition['%s Insightfuls'] = '%s Interessante';
$Definition['%s level deep'] = '%s livelli di profondità';
$Definition['%s levels deep'] = '%s livelli di profondità';
$Definition['%s Likes'] = '%s Mi piace';
$Definition['%s LOLs'] = '%s LOL';
$Definition['%s member'] = '%s membro';
$Definition['%s members'] = '%s membri';
$Definition['%s mentioned %s in a %s.'] = '%s ha menzionato %s in %s.';
$Definition['%s message'] = '%s messaggio';
$Definition['%s messages'] = '%s messaggi';
$Definition['%s minute'] = '%s minuto';
$Definition['%s minutes'] = '%s minuti';
$Definition['%s month'] = '%s mese';
$Definition['%s months'] = '%smesi';
$Definition['%s New'] = '%s Nuovo';
$Definition['%s new'] = '%s nuovo';
$Definition['%s new comment since you last read this.'] = '%s commento nuovo presente dall\'ultima volta che hai letto questa discussione.';
$Definition['%s new comments since you last read this.'] = '%s commenti nuovi presenti dall\'ultima volta che hai letto questa discussione.';
$Definition['%s New Plural'] = '%s Nuovo Plurale';
$Definition['%s new plural'] = '%s nuovo plurale';
$Definition['%s Not Found'] = '%s Non Trovato';
$Definition['%s Point'] = '%s Punto';
$Definition['%s point'] = '%s punto';
$Definition['%s Points'] = '%s Punti';
$Definition['%s points'] = '%s punti';
$Definition['%s result'] = '%s risultato';
$Definition['%s results'] = '%s risultati';
$Definition['%s said'] = '%s ha detto';
$Definition['%s said:'] = '%s ha detto:';
$Definition['%s tag(s) found.'] = '%s tag trovato(i)';
$Definition['%s tags in the system'] = '%s tag nel sistema';
$Definition['%s Up Votes'] = '%s Voti Su';
$Definition['%s view'] = '%s visualizzazione';
$Definition['%s views'] = '%s visualizzazioni';
$Definition['%s votes'] = '%s voti';
$Definition['%s was removed from the %s and added to the %s'] = '%s è stato rimosso da %s ed aggiunto a %s';
$Definition['%s week'] = '%s settimana';
$Definition['%s weeks'] = '%s settimane';
$Definition['%s WTFs'] = '%s WTF';
$Definition['%s year'] = '%s anno';
$Definition['%s years'] = '%s anni';

$Definition['(All)'] = '(Tutti)';
$Definition['(empty message)'] = '(messaggio vuoto)';

$Definition['+%s Guests'] = '+%s Ospiti';

$Definition[' - Page %s'] = '- Pagina %s';

$Definition['1 message'] = '1 messaggio';

$Definition['<General Error>'] = '<Errore Generale>';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Registrazione Approvata';
$Definition['[%s] Welcome Aboard!'] = '[%s] Benvenuto/a a bordo!';
$Definition['[Deleted User]'] = '[Utente Cancellato]';

$Definition['About'] = 'Informazioni';
$Definition['AboutToDelete'] = 'Stai per cancellare %s.';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Stai per eliminare %1$s delle %2$s discussioni selezionate.';
$Definition['Abuse'] = 'Abusa';
$Definition['Accept'] = 'Accetta';
$Definition['Accept this answer.'] = 'Accetta questa risposta.';
$Definition['Account Options'] = 'Opzioni Account';
$Definition['Activate'] = 'Attiva';
$Definition['Active'] = 'Attivato';
$Definition['Active Users'] = 'Utenti Attivi';
$Definition['Activity'] = 'Attività';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s ha accettato %4$s nella %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s ha commentato nella tua %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s ha commentato nella tua %8$s.';
$Definition['Activity.Comment'] = 'Commento';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s ha citato %3$s in %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s ha citato %3$s in %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s ti ha inviato un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s ti ha inviato un %8$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s si è unito/a.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s si è unito/a.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s ha cambiato l\'immagine del profilo di %6$s.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s ha cambiato l\'immagine del profilo di %6$s.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s ha risposto alla %4$s di %8$s.';
$Definition['Add'] = 'Aggiungi';
$Definition['Add a Comment'] = 'Aggiungi un Commento';
$Definition['Add a Message'] = 'Aggiungi un Messaggio';
$Definition['Add another poll option ...'] = 'Aggiungi un\'altra opzione al sondaggio ...';
$Definition['Add a Profile Picture'] = 'Aggiungi un\'Immagine del Profilo';
$Definition['Add a Warning'] = 'Aggiungi un Avviso';
$Definition['Add Badge'] = 'Aggiungi un Emblema';
$Definition['Add Comment'] = 'Aggiungi un Commento';
$Definition['Add Cost'] = 'Aggiungi il Costo';
$Definition['Add Image'] = 'Aggiungi un\'Immagine';
$Definition['Add Message'] = 'Aggiungi Avviso';
$Definition['Add Note'] = 'Aggiungi Nota';
$Definition['Add People to this Conversation'] = 'Aggiungi Persone a questa Conversazione';
$Definition['Add Route'] = 'Aggiungi Percorso';
$Definition['Admin'] = 'Amministratore';
$Definition['Administrator'] = 'Amministratore';
$Definition['Administrator Activity'] = 'Attività dell\'Amministratore';
$Definition['administrators'] = 'amministratori';
$Definition['Advanced Stuff'] = 'Strumenti Avanzati';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Si è verificato un errore fatale durante l\'elaborazione della richiesta. <br /> Il server ha resituito la seguente risposta: %s';
$Definition['Agree'] = 'Concordo';
$Definition['Alert'] = 'Avvertimento';
$Definition['All %s'] = 'Tutte le %s';
$Definition['All %s...'] = 'Tutti %s...';
$Definition['All Bookmarks'] = 'Tutti i Preferiti';
$Definition['All Categories'] = 'Tutte le Categorie';
$Definition['all categories'] = 'tutte le categorie';
$Definition['All Conversations'] = 'Tutte le Conversazioni';
$Definition['All Discussions'] = 'Tutte le Discussioni';
$Definition['All Events'] = 'Tutti gli eventi';
$Definition['All members'] = 'Tutti i membri';
$Definition['Allow'] = 'Consenti';
$Definition['Allow other members to see your email?'] = 'Vuoi consentire agli altri membri di visualizzare il tuo indirizzo e-mail?';
$Definition['All Time Leaders'] = 'Leader di Sempre';
$Definition['Ancient Membership'] = 'Membro Anziano';
$Definition['An invitation has already been sent to the email you entered.'] = 'Un invito è stato già inoltrato all\'indirizzo e-mail che hai inserito.';
$Definition['Announce'] = 'Annuncia';
$Definition['Announce...'] = 'Annuncia...';
$Definition['Announcement'] = 'Annuncio';
$Definition['Announcements'] = 'Annunci';
$Definition['Announce this discussion'] = 'Annuncia questa discussione';
$Definition['Answer'] = 'Risposta';
$Definition['answer'] = 'risposta';
$Definition['Answers'] = 'Risposte';
$Definition['answers'] = 'risposte';
$Definition['Applicant'] = 'In attesa';
$Definition['Applicants'] = 'Candidato';
$Definition['Applicants & Invitations'] = 'Candidati & Inviti';
$Definition['Apply Changes'] = 'Applica le modifiche';
$Definition['Apply for Membership'] = 'Registrati';
$Definition['Apply for membership'] = 'Inoltra la domanda d\'iscrizione';
$Definition['Approve'] = 'Approva';
$Definition['Approve Applicant'] = 'Approva';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Sei ASSOLUTAMENTE certo di voler intraprendere quest\'azione?';
$Definition['Are you sure you want to delete this %s?'] = 'Sei certo di voler eliminare questa %s?';
$Definition['Are you sure you want to do that?'] = 'Sei certo di voler fare questo?';
$Definition['Are you sure you want to do this?'] = 'Sei certo di voler fare questo?';
$Definition['Are you sure you want to join this group?'] = 'Sei sicuro di volerti unire a questo gruppo?';
$Definition['Are you sure you want to leave this group?'] = 'Sei sicuro di voler lasciare questo gruppo?';
$Definition['Are you sure you wish to continue?'] = 'Sei certo di voler proseguire?';
$Definition['Ask a Question'] = 'Fai una Domanda';
$Definition['Ask Question'] = 'Fai una Domanda';
$Definition['Attach a file'] = 'Allega un file';
$Definition['Attach image/file'] = 'Allega file/immagine';
$Definition['Attachments'] = 'Allegati';
$Definition['Attach this warning to the %s.'] = 'Allega quest\'avviso al %s.';
$Definition['AttemptingSignOut'] = 'Stai tentando di uscire. Sei sicuro di volerlo %s?';
$Definition['Authenticate URL'] = 'URL di Autenticazione';
$Definition['Author'] = 'Autore';
$Definition['available'] = 'disponibile';
$Definition['Awaiting Moderation'] = 'In Attesa di Moderazione';
$Definition['Awesome'] = 'Mi piace';

$Definition['Back to Discussions'] = 'Torna alle Discussioni';
$Definition['Back to Profile'] = 'Torna al Profilo';
$Definition['Badge'] = 'Emblema';
$Definition['Badge404'] = ' Emblema non trovato.';
$Definition['Badges'] = 'Emblemi';
$Definition['BadgesModuleTitle'] = 'Nome Emblema';
$Definition['BadgesNobody'] = 'Nessuno ancora ha ottenuto questo emblema.';
$Definition['Banned'] = 'Bannato';
$Definition['Banned for being abusive.'] = 'Bannato per essere stato offensivo.';
$Definition['Banned for spamming.'] = 'Bannato per spamming.';
$Definition['Banned users can no longer access the site.'] = 'Gli utenti bannati non possono più accedere al sito.';
$Definition['Ban User'] = 'Banna Utente';
$Definition['Ban Value'] = 'Valore del Ban';
$Definition['Best Answer'] = 'Miglior Risposta';
$Definition['Best Answers'] = 'Migliori Risposte';
$Definition['Best Of'] = 'Il meglio di';
$Definition['Best Of...'] = 'Il meglio di...';
$Definition['Blank Discussion Topic'] = 'Discussione Vuota';
$Definition['Blank Message'] = 'Messaggio vuoto';
$Definition['Blogs'] = 'Blog';
$Definition['Body'] = 'Corpo';
$Definition['Bold'] = 'Grassetto';
$Definition['Bookmark'] = 'Preferito';
$Definition['Bookmarked Discussions'] = 'Discussioni Preferite';
$Definition['Bookmarks'] = 'Preferiti';
$Definition['bookmarks'] = 'preferiti';
$Definition['By'] = 'Da';
$Definition['by'] = 'da';
$Definition['by Date'] = 'per Data';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Caricando un file certifichi che possiedi i diritti per la distribuzione di questa immagine e che non viola in alcun modo i Termini di Servizio.';

$Definition['Cancel'] = 'Annulla';
$Definition['Casual'] = 'Casuale';
$Definition['Categories'] = 'Categorie';
$Definition['CategoriesShowFollowed'] = 'Mostra solo le categorie che segui';
$Definition['CategoriesShowUnfollowed'] = 'Mostra le categorie nascoste';
$Definition['CategoriesViewingAll'] = 'Attualmente stai visualizzando tutte le categorie';
$Definition['CategoriesViewingFollowed'] = 'Attualmente stai visualizzando solamente le categorie che segui';
$Definition['Category'] = 'Categoria';
$Definition['Category Filter'] = 'Filtro per Categoria';
$Definition['CategoryID'] = 'Categoria';
$Definition['Category Management'] = 'Gestione delle Categorie';
$Definition['Category Notifications'] = 'Notifiche delle Categorie';
$Definition['Category to Use'] = 'Categoria da Utilizzare';
$Definition['Change'] = 'Cambia';
$Definition['Change language'] = 'Cambia lingua';
$Definition['Change My Password'] = 'Cambia la Mia Password';
$Definition['Change My Picture'] = 'Cambia la Mia Immagine';
$Definition['Change Password'] = 'Cambia la Password';
$Definition['Change Picture'] = 'Cambia l\'Immagine';
$Definition['Check all roles that apply to this user:'] = 'Controlla tutti i ruoli applicati a questo utente:';
$Definition['Child Categories'] = 'Sottocategorie';
$Definition['Child Categories:'] = 'Sottocategorie:';
$Definition['Choose a name to identify yourself on the site.'] = 'Scegli un nome per identificarti sul sito.';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Scegli la discussione principale dove tutti i commenti verranno unificati:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Scegli se desideri fare una domanda oppure iniziare una discussione.';
$Definition['Clear'] = 'Pulisci';
$Definition['clear'] = 'pulisci';
$Definition['Clear Conversation History'] = 'Pulisci la Cronologia delle Conversazioni';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Clicca <a href="%s">qui</a> per tornare alla discussione.';
$Definition['Click accept or reject beside an answer.'] = 'Clicca accetta o rifiuta accanto ad una risposta.';
$Definition['clicking here'] = 'cliccando qui';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Clicca la %s accanto alle discussioni per inserirle tra i preferiti.';
$Definition['Close'] = 'Chiudi';
$Definition['Closed'] = 'Chiusa';
$Definition['Close this discussion'] = 'Chiudi questa discussione';
$Definition['Color'] = 'Colore';
$Definition['Combo Breaker'] = 'Interruttore Combinato';
$Definition['Comment'] = 'Commenta';
$Definition['comment'] = 'commenta';
$Definition['Comment As ...'] = 'Commenta come...';
$Definition['Comment by %s'] = 'Commento di %s';
$Definition['Commenting as %1$s (%2$s)'] = 'Stai commentando come %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Commenti non consentiti';
$Definition['Comments'] = 'Commenti';
$Definition['comments'] = 'commenti';
$Definition['Comments are between {UserID,you}.'] = 'Commenti tra {UserID,you}.';
$Definition['Community'] = 'Comunità';
$Definition['Community Guidelines'] = 'Linee Guida della Community';
$Definition['Completely delete the warning.'] = 'Rimuovi completamente l\'avviso.';
$Definition['Confirm'] = 'Conferma';
$Definition['Confirm Email'] = 'Conferma E-Mail';
$Definition['Confirm Password'] = 'Conferma Password';
$Definition['Connect'] = 'Accedi';
$Definition['ConnectAccountExists'] = 'Possiedi già un account qui.';
$Definition['ConnectChooseName'] = 'Scegli un nome per identificarti sul sito.';
$Definition['ConnectCreateAccount'] = 'Aggiungi Informazioni &amp; Crea Account';
$Definition['Connected'] = 'Connesso';
$Definition['ConnectExistingPassword'] = 'Inserisci la password del tuo account esistente.';
$Definition['Connecting...'] = 'Collegamento...';
$Definition['Connection'] = 'Connessione';
$Definition['ConnectLeaveBlank'] = 'Lascialo vuoto a meno che non si stia accedendo ad un account esistente.';
$Definition['ConnectName'] = 'Nome utente';
$Definition['ConnectRegisteredName'] = 'Il tuo nome utente registrato è: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Collega il tuo profilo ai social network per ricevere notifiche delle attività che si realizzano qui e condividi la tua attività con i tuoi amici e i tuoi followers.';
$Definition['Contact Us'] = 'Contattaci';
$Definition['conversation'] = 'conversazione';
$Definition['Core'] = 'Nucleo';
$Definition['Created'] = 'Creato';
$Definition['Create Discussions'] = 'Crea Discussioni';
$Definition['Create One.'] = 'Creane Uno';
$Definition['Current'] = 'Corrente';
$Definition['Currently: '] = 'Correntemente:';
$Definition['Custom Information'] = 'Informazioni Personalizzate';
$Definition['Customize'] = 'Personalizza';
$Definition['customize your profile now'] = 'personalizza il tuo profilo adesso';
$Definition['Customize your Public Profile'] = 'Personalizza il tuo Profilo Pubblico';
$Definition['Custom Profile Fields'] = 'Campi del Profilo Personalizzati';
$Definition['Custom Profile Field Settings'] = 'Impostazioni dei Campi del Profilo Personalizzati';

$Definition['Dashboard'] = 'Cruscotto';
$Definition['Dashboard Home'] = 'Home del Cruscotto';
$Definition['Dashboard Summaries'] = 'Sommario del Cruscotto';
$Definition['Date'] = 'Data';
$Definition['Date.DefaultDayFormat'] = '%e %B';
$Definition['Date.DefaultFormat'] = '%e %B, %1:M%p %Y';
$Definition['Date Added'] = 'Data Aggiunta';
$Definition['Date Examples'] = 'Esempi: Lunedì, oggi, ultima settimana, 26 Mar, 26/3/04';
$Definition['Date within'] = 'Data entro';
$Definition['days'] = 'giorni';
$Definition['Define Thumbnail'] = 'Clicca e trascina sull\'immagine per definire la tua miniatura.';
$Definition['Delete'] = 'Elimina';
$Definition['Delete %s'] = 'Elimina %s';
$Definition['Delete Account'] = 'Elimina Account';
$Definition['Delete Conversation'] = 'Elimina Conversazione';
$Definition['Delete Discussion'] = 'Elimina Discussione';
$Definition['Delete Group'] = 'Cancella Gruppo';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Elimina l\'utente e tutti i suoi contenuti. Questo causerà incoerenza nelle conversazioni in cui l\'utente era intervenuto, facendo apparire come se le persone rispondano ad un contenuto che non c\'è. Questa opzione è ideale per rimuovere i contenuti degli spammer.';
$Definition['Delete User Content'] = 'Elimina Contenuti Utente';
$Definition['Delete User Forever'] = 'Elimina Utente per Sempre';
$Definition['Deny'] = 'Nega';
$Definition['Deny Applicant'] = 'Nega';
$Definition['Did this answer the question?'] = 'Questo risponde alla domanda?';
$Definition['Disagree'] = 'Disapprovo';
$Definition['Discussion'] = 'Discussione';
$Definition['discussion'] = 'discussione';
$Definition['Discussions'] = 'Discussioni';
$Definition['discussions'] = 'discussioni';
$Definition['Discussions Page'] = 'Pagina delle Discussioni';
$Definition['Discussion Title'] = 'Titolo della Discussione';
$Definition['Dislike'] = 'Non mi piace';
$Definition['Dismiss'] = 'Respingi';
$Definition['Don\'t announce.'] = 'Non annunciare.';
$Definition['Don\'t fold quotes'] = 'Non ripiegare le citazioni';
$Definition['Don\'t have an account? %s'] = 'Non hai un account? %s';
$Definition['Do you want to expire or delete this warning?'] = 'Vuoi far scadere o eliminare questo avviso?';
$Definition['Draft saved at %s'] = 'Bozza salvata alle %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Trascina e ridimensiona il quadrato in basso per definire l\'icona della tua miniatura.';
$Definition['Drop image/file'] = 'Spostare immagine/file';

$Definition['Earned'] = 'Ottenuto';
$Definition['Edit'] = 'Modifica';
$Definition['Edit Account'] = 'Modifica Account';
$Definition['Edit Comment'] = 'Modifica Commento';
$Definition['Edit Discussion'] = 'Modifica Discussione';
$Definition['edited %s'] = 'modificato %s';
$Definition['Edited %s by %s.'] = 'A cura %s di %s.';
$Definition['Edit My Account'] = 'Modifica il Mio Account';
$Definition['Edit My Profile'] = 'Modifica il Mio Profilo';
$Definition['Edit My Thumbnail'] = 'Modifica la Mia Miniatura';
$Definition['editor.BBCodeHelpText'] = 'Nel tuo post puoi usare <a href="http://en.wikipedia.org/wiki/BBCode"; target="_new">BBCode</a>';
$Definition['editor.HtmlHelpText'] = 'Nel tuo post puoi usare <a href="http://htmlguide.drgrog.com/cheatsheet.php"; target="_new">Simple Html</a>.';
$Definition['editor.MarkdownHelpText'] = 'Nel uoi post puoi usare  <a href="http://en.wikipedia.org/wiki/Markdown"; target="_new">Markdown</a>.';
$Definition['editor.TextHelpText'] = 'Nel tuo post stai usando testo semplice.';
$Definition['editor.WysiwygHelpText'] = 'Nel tuo post stai usando  <a href="https://en.wikipedia.org/wiki/WYSIWYG"; target="_new">Wysiwyg</a>.';
$Definition['Edit Preferences'] = 'Modifica Preferenze';
$Definition['Edit Profile'] = 'Modifica Profilo';
$Definition['Edit Tag'] = 'Modifica Tag';
$Definition['Edit Thumbnail'] = 'Modifica Miniatura';
$Definition['Eighth Anniversary'] = 'Ottavo Anniversario';
$Definition['Email'] = 'E-mail';
$Definition['Email/Username'] = 'E-mail/Nome utente';
$Definition['EmailConfirmEmail'] = 'Hai bisogno di confermare il tuo indirizzo e-mail prima di poter continuare. Conferma l\'indirizzo e-mail cliccando sul link seguente: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '
Buona giornata!';
$Definition['EmailHeader'] = 'Ciao {User.Name}!
';
$Definition['EmailInvitation'] = 'Ciao!

%1$s ti ha invitato ad iscriverti su %2$s. Se vuoi unirti, puoi farlo cliccando sul seguente link:

  %3$s';
$Definition['EmailMembershipApproved'] = 'Ciao %1$s,
La tua richiesta d\'iscrizione è stata approvata. Accedi ora al seguente link:


  %2$s';
$Definition['EmailNotification'] = '%1$s

Segui il link in basso per dare uno sguardo:
%2$s

Buona giornata!';
$Definition['Email Notifications'] = 'Notificahe E-mail';
$Definition['Email Or Username'] = 'E-Mail o Nome utente';
$Definition['EmailPassword'] = '%2$s ha reimpostato la tua password su %3$s. Le tue credenziali di accesso adesso sono:

  E-Mail: %6$s
  Password: %5$s
  Url: %4$s';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Le email inviate dall\'applicazione verranno inviate con il seguente nome ed indirizzo';
$Definition['Email Source'] = 'E-Mail';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Segui il link in basso per dare uno sguardo:
%2$s

Buona giornata!';
$Definition['Email Unavailable'] = 'E-Mail Non Disponibile';
$Definition['Email visible to other users'] = 'E-Mail visibile agli altri utenti.';
$Definition['EmailWelcome'] = '%2$s ha creato un account per te su %3$s. Le tue credenziali di accesso sono:

  E-Mail: %6$s
  Password: %5$s
  Url: %4$s';
$Definition['EmailWelcomeConnect'] = 'Ti sei autenticato con successo su {Title}. Ecco le tue informazioni:
  
  Nome utente: {User.Name}
  Connesso con: {ProviderName}
  
Puoi accedere al sito da {/,url,domain}.';
$Definition['EmailWelcomeRegister'] = 'Ti sei registrato con successo sul {Title}. Ecco le tue informazioni:

  Nome utente: {User.Name}
  E-Mail: {User.Email}
  
  Puoi accedere al sito da {/,url,domain}.';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Leggi l\'articolo completo qui</a></p><div class="ClearFix"></div></div>';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Leggi l\'articolo completo qui</a></p><div class="ClearFix"></div></div>';
$Definition['English'] = 'Inglese';
$Definition['Enter your Email address'] = 'Inserisci il tuo indirizzo E-Mail';
$Definition['Enter your email address'] = 'Inserisci il tuo indirizzo e-mail';
$Definition['Enter your Email address or username'] = 'Inserisci il tuo indirizzo E-Mail oppure il nome utente';
$Definition['Enter Your OpenID Url'] = 'Inserisci il tuo Url OpenID';
$Definition['Erase User Content'] = 'Elimina Contenuti Utente';
$Definition['Error'] = 'Errore';
$Definition['ErrorBadInvitationCode'] = 'Errore: Il codice d\'invito che ci hai fornito non è valido.';
$Definition['ErrorCredentials'] = 'Siamo spiacenti, non è stato trovato alcun account relativo all\'e-mail e password che hai inserito.';
$Definition['ErrorPermission'] = 'Siamo spiacenti, permesso negato.';
$Definition['ErrorPluginDisableRequired'] = 'Non puoi disattivare il plugin {0} perché il plugin {1} è richiesto per funzionare.';
$Definition['ErrorPluginEnableRequired'] = 'Questo plugin richiede l\'attivazione del plugin {0} prima di poter essere attivato.';
$Definition['ErrorPluginVersionMatch'] = 'Il plugin attivato {0} (versione {1}) ha fallito nel soddisfare i requisiti della versione ({2}).';
$Definition['ErrorRecordNotFound'] = 'Il documento richiesto non è stato trovato.';
$Definition['ErrorTermsOfService'] = 'Devi accettare i termini di servizio.';
$Definition['Event'] = 'Evento';
$Definition['Events'] = 'Eventi';
$Definition['everyone'] = 'tutti';
$Definition['Everything'] = 'Tutto';
$Definition['Expired'] = 'Scaduto';
$Definition['Expires'] = 'Scadenza';

$Definition['Failed to delete group.'] = 'Impossibile eliminare il gruppo.';
$Definition['Failed to find discussion for commenting.'] = 'Impossibile trovare la discussione per commentare.';
$Definition['Failed to load the poll.'] = 'Impossibile caricare il sondaggio.';
$Definition['Female'] = 'Femmina';
$Definition['Fifth Anniversary'] = 'Quinto Anniversario';
$Definition['FileName'] = 'Nome del File';
$Definition['Filename'] = 'Nome del file';
$Definition['File Size'] = 'Dimensioni del File';
$Definition['FileSize'] = 'Dimensioni del File';
$Definition['First Anniversary'] = 'Primo Anniversario';
$Definition['First Comment'] = 'Primo Commento';
$Definition['Flag'] = 'Segnala';
$Definition['Follow'] = 'Segui';
$Definition['Follow %s'] = 'Segui %s';
$Definition['Followed by %d people'] = 'Seguito da %d persone';
$Definition['Followed by %d person'] = 'Seguito da %d persona';
$Definition['followed categories'] = 'mostra solo le categorie che segui';
$Definition['Following %d people'] = 'Seguendo %d persone';
$Definition['Following %d person'] = 'Seguendo %d persona';
$Definition['FollowOnly'] = 'Segui il link qui sotto per controllarla:';
$Definition['Follows'] = 'Ti seguono';
$Definition['Forgot?'] = 'Dimenticato?';
$Definition['Forgot your password?'] = 'Dimenticato la tua password?';
$Definition['Format'] = 'Formato';
$Definition['Format his'] = 'suo';
$Definition['Format their'] = 'loro';
$Definition['Format You'] = 'Tu';
$Definition['Format you'] = 'tu';
$Definition['Format Your'] = 'Tuo';
$Definition['Fourth Anniversary'] = 'Quarto Anniversario';
$Definition['Friends'] = 'Amici';
$Definition['Full Site'] = 'Sito Completo';

$Definition['Garden.Email.SupportAddress'] = 'E-Mail di supporto';
$Definition['Garden.Email.SupportName'] = 'Nome del Supporto';
$Definition['Garden.Registration.DefaultRoles'] = 'ruolo di default';
$Definition['Garden.Title'] = 'Titolo delBanner';
$Definition['Gender'] = 'Sesso';
$Definition['General'] = 'Generale';
$Definition['Generate import SQL only'] = 'Genera solo l\'importazione SQL';
$Definition['Generate Password'] = 'Genera Password';
$Definition['Give'] = 'Dai';
$Definition['Give a Badge to %s'] = 'Dai un Emblema a %s';
$Definition['Give Badge'] = 'Dai un Emblema';
$Definition['Given'] = 'Dato';
$Definition['Go'] = 'Vai';
$Definition['Group'] = 'Gruppo';
$Definition['group'] = 'gruppo';
$Definition['GroupEmptyAnnouncements'] = 'Qui un giorno ci saranno cose importanti.';
$Definition['GroupEmptyDiscussions'] = 'Terribilmente tranquillo qui, non è vero?';
$Definition['GroupEmptyEvents'] = 'Oh cavoli, non ci sono eventi prossimamente.';
$Definition['Group Info'] = 'Informazioni sul Gruppo';
$Definition['Group Leaders'] = 'Leader';
$Definition['Group Members'] = 'Membri';
$Definition['GroupMembersEmpty'] = 'Non si è ancora unito nessuno. Spargi la voce!';
$Definition['Groups'] = 'Gruppi';
$Definition['groups'] = 'gruppi';
$Definition['Guest'] = 'Visitatore';
$Definition['GuestModule.Message'] = 'Sembra che tu sia nuovo da queste parti. Se vuoi partecipare, accedi con le tue credenziali, oppure utilizza il modulo di registrazione!';

$Definition['Hang on a sec while we sign you out.'] = 'Attendi qualche secondo per essere disconnesso.';
$Definition['he'] = 'lui';
$Definition['Heading %s'] = 'Intestazione %s';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} hai ottenuto un <a href="{Url,html}">{Data.Name,text}</a> emblema.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} sei stato/a bannato {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} ha commentato su <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} Cominciato una nuova discussione. <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} ti ha citato/a su <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} cambiato l\'immagine del profilo per {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} ti sei unito/a.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} sei stato riammesso/a {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} sei stato avvisato/a {RegardingUserID,you}.';
$Definition['her'] = 'sua';
$Definition['Hide'] = 'Nascondi';
$Definition['Hide my online status from other members'] = 'Nascondi il mio status online agli altri membri';
$Definition['Hide signatures?'] = 'Nascondi le firme?';
$Definition['Hide signatures always'] = 'Nascondi sempre le firme';
$Definition['Hide signatures on my mobile device'] = 'Nascondi le firme sul mio dispositivo mobile';
$Definition['his'] = 'suo';
$Definition['hours'] = 'ore';
$Definition['Howdy, Stranger!'] = 'Salve, Straniero!';
$Definition['How long do you want this warning to last?'] = 'Per quanto tempo desideri che duri questo avviso?';
$Definition['How many levels deep should we start folding up quote trees?'] = 'Dopo quanti livelli di profondità dovremmo iniziare a ripiegare gli alberi di citazioni?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Dichiaro di accettare i <a id="TermsOfService" class="Popup" target="terms" href="%s">termini di servizio</a>';
$Definition['Icon'] = 'Icona';
$Definition['Ignore'] = 'Ignora';
$Definition['Ignore List'] = 'Ignora elenco';
$Definition['Ignore Someone'] = 'Ignora Qualcuno';
$Definition['Image'] = 'Immagine';
$Definition['Image URL'] = 'URL immagine';
$Definition['In <b>%s.</b>'] = 'Nella <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'Nella <b>%s</b> e discussioni recenti.';
$Definition['Inbox'] = 'Ricevuti';
$Definition['Indent'] = 'Inserisci rientro';
$Definition['In recent discussions.'] = 'Nelle recenti discussioni.';
$Definition['In seconds'] = 'In secondi';
$Definition['Insert Image'] = 'Inserisci Immagine';
$Definition['Insightful'] = 'Interessante';
$Definition['Internal'] = 'Interno';
$Definition['In this Conversation'] = 'In questa Conversazione';
$Definition['Invalid password.'] = 'La password inserita non è valida. Ricorda che le password sono sensibili alle maiuscole (case-sensitive).';
$Definition['Invitations'] = 'Inviti';
$Definition['Invite'] = 'Invita';
$Definition['InviteErrorPermission'] = 'Siamo spiacenti, permesso negato.';
$Definition['Invite Friends'] = 'Invita Amici';
$Definition['Invite friends'] = 'Invita gli amici';
$Definition['IPAddress'] = 'Indirizzo IP';
$Definition['IP Address'] = 'Indirizzo IP';
$Definition['I remember now!'] = 'Ora ricordo!';
$Definition['Italic'] = 'Corsivo';
$Definition['Item'] = 'Elemento';
$Definition['item'] = 'elemento';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Sembra che tu sia nuovo qui. Se vuoi partecipare, clicca uno dei seguenti pulsanti!';

$Definition['Jail'] = 'Imprigiona';
$Definition['Jailed users have reduced abilities.'] = 'Gli utenti imprigionati hanno abilità ridotte.';
$Definition['Joined'] = 'Si è unito';
$Definition['Joined %s'] = 'Entrati %s';
$Definition['Join this Group'] = 'Entra in questo Gruppo';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Elimina solamente l\'utente, mantieni tutti i suoi contenuti';
$Definition['Just expire the warning.'] = 'Appena scade l\'avviso.';
$Definition['Just you!'] = 'Solo tu!';

$Definition['Keep me signed in'] = 'Mantienimi connesso';
$Definition['Keep User Content'] = 'Mantieni Contenuti Utente';

$Definition['Label'] = 'Etichetta';
$Definition['Last Active'] = 'Ultima Attività';
$Definition['Last IP'] = 'Ultimo IP';
$Definition['lasts %s'] = 'ultimi %s';
$Definition['Latest %1$s'] = 'Ultimo %1$s';
$Definition['Latest Post'] = 'Ultimo Commento';
$Definition['Leaders'] = 'Leader';
$Definition['Leave a Comment'] = 'Lascia un Commento';
$Definition['Leave a comment'] = 'Lascia un Commento';
$Definition['Leave a redirect link.'] = 'Indica un link per il redirect.';
$Definition['Leave blank unless connecting to an exising account.'] = 'ConnectLeaveBlank';
$Definition['Leave Comments'] = 'Lascia Commenti';
$Definition['Leave Group'] = 'Lascia Gruppo';
$Definition['Length'] = 'Lunghezza';
$Definition['Level %s'] = 'Livello %s';
$Definition['Like'] = 'Mi piace';
$Definition['Link to content:'] = 'Link al contenuto:';
$Definition['Locale'] = 'it-IT';
$Definition['Login with Facebook'] = 'Accedi con Facebook';

$Definition['Major'] = 'Maggiore';
$Definition['Make me invisible? (Will not show you on the list)'] = 'Ti rendo invisibile? (Non verrai mostrato nella lista)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Rendi questo sondaggio anonimo (i voti degli utenti non verranno resi pubblici).';
$Definition['Male'] = 'Maschio';
$Definition['Mark All Viewed'] = 'Segna Tutti come Letti';
$Definition['Mark as Troll'] = 'Segnala come Troll';
$Definition['Marking as spam cannot be undone.'] = 'Segnalando qualcosa come SPAM ne causerà la cancellazione permanente. Eliminare è un buon modo per mantenere il forum pulito.';
$Definition['Mark Read'] = 'Segna come letto';
$Definition['Member Count'] = 'Membri';
$Definition['Members'] = 'Membri';
$Definition['Merge'] = 'Unisci';
$Definition['Merge Discussions'] = 'Unisci Discussioni';
$Definition['Message'] = 'Messaggio';
$Definition['message'] = 'messaggio';
$Definition['Messages'] = 'Messaggi';
$Definition['messages'] = 'messaggi';
$Definition['Message to User'] = 'Messaggio a Utente';
$Definition['Minor'] = 'Minore';
$Definition['minutes'] = 'minuti';
$Definition['Moderation'] = 'Moderazione';
$Definition['Moderation Queue'] = 'Coda di Moderazione';
$Definition['Moderator'] = 'Moderatore';
$Definition['Moderator Activity'] = 'Attività del Moderatore';
$Definition['Moderators'] = 'Moderatori';
$Definition['moderators'] = 'moderatori';
$Definition['months'] = 'mesi';
$Definition['More'] = 'Ancora';
$Definition['More About %s'] = 'Di più su %s';
$Definition['More Comments'] = 'Altri Commenti';
$Definition['More Discussions'] = 'Altre discussioni';
$Definition['More Information'] = 'Altre Informazioni';
$Definition['More Results'] = 'Altri Risultati';
$Definition['More…'] = 'Ancora...';
$Definition['Most Recent'] = 'Più Recenti';
$Definition['Most recent:'] = 'Più Recenti:';
$Definition['Most recent: %1$s by %2$s'] = 'Più recente: %1$s di %2$s';
$Definition['Most recent by %1$s'] = 'Più recente di %1$s';
$Definition['Most Recent Comment'] = 'Commenti Più Recenti';
$Definition['Move'] = 'Sposta';
$Definition['MyBadgesModuleTitle'] = 'Miei Emblemi';
$Definition['My Bookmarks'] = 'I Miei Preferiti';
$Definition['My Discussions'] = 'Le Mie Discussioni';
$Definition['My Drafts'] = 'Le Mie Bozze';
$Definition['My Forums'] = 'I Miei Forum';
$Definition['My Groups'] = 'I Miei Gruppi';
$Definition['My Preferences'] = 'Le Mie Preferenze';

$Definition['n/a'] = 'non disponibile';
$Definition['Name'] = 'Nome';
$Definition['Name Dropper'] = 'Nome Contagocce';
$Definition['Name the Group'] = 'Dai un Nome al Gruppo';
$Definition['Name Unavailable'] = 'Nome Non Disponibile.';
$Definition['new'] = 'nuovo';
$Definition['New %s'] = 'Nuovo %s';
$Definition['New Conversation'] = 'Nuova Conversazione';
$Definition['New Discussion'] = 'Nuova Discussione';
$Definition['new discussion'] = 'nuovo';
$Definition['New Event'] = 'Nuovo Evento';
$Definition['New Group'] = 'Nuovo Gruppo';
$Definition['New Groups'] = 'Nuovi Gruppi';
$Definition['New Message'] = 'Nuovo Messaggio';
$Definition['New Password'] = 'Nuova Password';
$Definition['New Poll'] = 'Nuovo Sondaggio';
$Definition['Next'] = 'Successivo';
$Definition['Ninth Anniversary'] = 'Nono Anniversario';
$Definition['NoBadgesEarned'] = 'Da un momento all\'altro&hellip;';
$Definition['No badges yet.'] = 'Ancora nessun emblema.';
$Definition['No default roles.'] = 'Nessun ruolo di default';
$Definition['No discussions were found.'] = 'Non è stata trovata alcuna discussione .';
$Definition['No items tagged with %s.'] = 'Non è stato trovato alcun elemento con il tag %s.';
$Definition['NoPermissionToDeleteDiscussions'] = 'Non hai l\'autorizzazione per eliminare %1$s delle discussioni selezionate.';
$Definition['No results for \'%s\''] = 'Nessun risultato per \'%s\'';
$Definition['No Roles'] = 'Nessun Ruolo';
$Definition['Not Authorized (401)'] = 'Non Autorizzato (401)';
$Definition['Not Found (404)'] = 'Non Trovato (404)';
$Definition['Notice'] = 'Notifica';
$Definition['Notification'] = 'Notifica';
$Definition['Notification Preferences'] = 'Preferenze delle Notifiche';
$Definition['Notifications'] = 'Notifiche';
$Definition['Notifictions'] = 'Notifiche';
$Definition['Notify'] = 'Notifica';
$Definition['Notify me of private messages.'] = 'Comunicami i messaggi privati.';
$Definition['Notify me when a badge is requested.'] = 'Comunicami quando viene richiesto un emblema.';
$Definition['Notify me when a comment is flagged.'] = 'Comunicami quando viene segnalato un commento.';
$Definition['Notify me when I am added to private conversations.'] = 'Comunicami quando vengo aggiunto in conversazioni private.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Inviami una notifica quando le persone commentano discussioni a cui ho partecipato.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Comunicami quando le persone commentano sulle mie discussioni preferite.';
$Definition['Notify me when people comment on my discussions.'] = 'Comunicami quando le persone commentano sulle mie discussioni.';
$Definition['Notify me when people mention me.'] = 'Comunicami quando le persone mi citano.';
$Definition['Notify me when people mention me in comments.'] = 'Comunicami quando le persone mi citano nei commenti';
$Definition['Notify me when people reply to my wall comments.'] = 'Comunicami quando le persone rispondono ai commenti della mia bacheca.';
$Definition['Notify me when people write on my wall.'] = 'Comunicami quando le persone scrivono sulla mia bacheca.';
$Definition['Not much happening here, yet.'] = 'Non c\'è nulla di nuovo qui, per ora...';
$Definition['Not Verified'] = 'Non verificato';

$Definition[' now.'] = ' ora';

$Definition['of'] = 'di';
$Definition['Okay'] = 'Confermo';
$Definition['OldPassword'] = 'Vecchia password';
$Definition['Old Password'] = 'Vecchia Password';
$Definition['on'] = 'su';
$Definition['Online Preferences'] = 'Preferenze Online';
$Definition['Only show followed categories'] = 'Mostra solamente le categorie che seguo';
$Definition['OpenID Settings'] = 'Impostazioni OpenID';
$Definition['Optional Description'] = 'Descrizione Opzionale';
$Definition['Options'] = 'Opzioni';
$Definition['or'] = 'oppure';
$Definition['Ordered list'] = 'Elenco ordinato';
$Definition['Organize discussion categories'] = 'Organizza le categorie delle discussioni';
$Definition['Organize your Categories'] = 'Organizza le tue Categorie';
$Definition['Original'] = 'Originale';
$Definition['Or you can...'] = 'Oppure...';
$Definition['Other Records'] = 'Altri Documenti';
$Definition['Outdent'] = 'Elimina rientro';
$Definition['Owner'] = 'Proprietario';

$Definition['PageDetailsMessage'] = '%1$s a %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s a %2$s di %3$s';
$Definition['Page Not Found'] = 'Pagina Non Trovata';
$Definition['Participated'] = 'Partecipato';
$Definition['ParticipatedHomepageTitle'] = 'Discussioni Partecipate';
$Definition['PasswordRequest'] = 'Qualcuno ha richiesto la reimpostazione della tua password su %2$s. Per reimpostare la tua password, sequi questo link:
  
  %3$s
  
Se non hai effettuato questa richiesta, ignora questa e-mail.';
$Definition['Passwords don\'t match'] = 'Le password non coincidono';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Incolla l\'URL di un\'immagine per incorporarla velocemente.';
$Definition['Permanent (301)'] = 'Permanente (301)';
$Definition['PermissionErrorMessage'] = 'Non hai i permessi per farlo.';
$Definition['PermissionErrorTitle'] = 'Problema di Permessi';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Devi essere un moderatore per farlo.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Devi essere un amministratore per farlo.';
$Definition['PermissionRequired.Javascript'] = 'Devi abilitare lo Javascript per farlo.';
$Definition['Photogenic'] = 'Fotogenico';
$Definition['Picture'] = 'Immagine';
$Definition['Pin'] = 'Fissa';
$Definition['Pinned'] = 'Fissato';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Ti preghiamo di attendere durante il reindirizzamento. Se non vieni reindirizzato, clicca <a href="%s">qui</a>.';
$Definition['Poll'] = 'Sondaggio';
$Definition['Poll Options'] = 'Opzioni del Sondaggio';
$Definition['Poll Question'] = 'Domanda del Sondaggio';
$Definition['Popular'] = 'Popolare';
$Definition['Popular Discussions'] = 'Discussioni Popolari';
$Definition['Popular Groups'] = 'Gruppi popolari';
$Definition['Popular Tags'] = 'Tag Popolari';
$Definition['Popup'] = 'Pop-up';
$Definition['Position'] = 'Posizione';
$Definition['Post'] = 'Pubblicazione';
$Definition['Post Comment'] = 'Pubblica commento';
$Definition['Post Discussion'] = 'Fai una Domanda';
$Definition['Post edited by %1$s at %2$s'] = 'Pubblicazione modificata da %1$s a %2$s';
$Definition['Posts'] = 'Pubblicazioni';
$Definition['Posts.Plural: %s'] = 'Pubblicazioni: %s';
$Definition['Posts.Singular: %s'] = 'Pubblicazioni: %s';
$Definition['Posts: %s'] = 'Pubblicazioni: %s';
$Definition['Post this anonymously'] = 'Pubblica questo commento anonimamente';
$Definition['PreferenceBadgeEmail'] = 'Comunicami quando ottengo un emblema.';
$Definition['PreferenceBadgePopup'] = 'Comunicami quando ottengo un emblema.';
$Definition['Preview'] = 'Anteprima';
$Definition['Previous'] = 'Precedente';
$Definition['Privacy Settings'] = 'Impostazioni della Privacy';
$Definition['Private group.'] = 'Tutti possono vedere il gruppo, ma solo i membri possono vederne il contenuto. Le persone devono richiedere l\'accesso o essere invitate per unirsi.';
$Definition['Private Note for Moderators'] = 'Nota Privata per i Moderatori';
$Definition['Problem with credentials.'] = 'Problema con le credenziali.';
$Definition['Proceed'] = 'Procedi';
$Definition['Profile'] = 'Profilo';
$Definition['Profile  Fields'] = 'Campi del Profilo';
$Definition['Profile Fields'] = 'Campi del Profilo';
$Definition['ProfileFieldsCustomDescription'] = 'Utilizza questi campi per creare informazioni del profilo personalizzate. Puoi inserire cose del tipo "Stato Sentimentale", "Skype", oppure "Giochi Preferiti". Usa la tua creatività!';
$Definition['Profile Page'] = 'Pagina del Profilo';
$Definition['Profile Picture'] = 'Immagine del Profilo';
$Definition['Profiles'] = 'Profili';
$Definition['Promote'] = 'Promuovi';
$Definition['Public'] = 'Pubblico';
$Definition['Public group.'] = 'Tutti possono vedere il gruppo e il suo contenuto. Tutti possono unirsi.';

$Definition['Q&A Accepted'] = 'Risposta ✓';
$Definition['Q&A Answered'] = 'Risposta';
$Definition['Q&A Options'] = 'Opzioni Q&A';
$Definition['Q&A Question'] = 'Domanda';
$Definition['QnA Accepted Answer'] = 'Risposta ✓';
$Definition['QnA Rejected Answer'] = 'Risposta respinta';
$Definition['Question'] = 'Domanda';
$Definition['question'] = 'domanda';
$Definition['Questions'] = 'Domande';
$Definition['questions'] = 'domande';
$Definition['Question Title'] = 'Titolo Discussione';
$Definition['Quote'] = 'Cita';
$Definition['Quote Folding'] = 'Cartella delle Citazioni';
$Definition['Quote on'] = 'attiva';
$Definition['Quote Settings'] = 'Impostazioni delle Citazioni';
$Definition['Quote wrote'] = 'ha scritto';

$Definition['Rank'] = 'Grado';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were} promosso/a a {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = 'Congratulazioni! Sei stato promosso/a a {Data.Name,plaintext}.';
$Definition['Re: %s'] = 'Re: %s ';
$Definition['Reactions'] = 'Reazioni';
$Definition['Real Name'] = 'Nome Reale';
$Definition['Reason'] = 'Motivazione';
$Definition['Reason (optional)'] = 'Motivazione (opzionale)';
$Definition['Recent Activity'] = 'Attività Recente';
$Definition['Recent Admin Activity'] = 'Attività Recente dell\'Amministratore';
$Definition['Recent Discussions'] = 'Discussioni Recenti';
$Definition['recently'] = 'recentemente';
$Definition['Recent Moderator Activity'] = 'Attività Recente del Moderatore';
$Definition['Recent Tutorials'] = 'Guide Recenti';
$Definition['Recipients'] = 'Destinatari';
$Definition['RecipientUserID'] = 'destinatario';
$Definition['Redirecting...'] = 'Reindirizzamento...';
$Definition['Refetch Page'] = 'Ricarica pagina';
$Definition['Register'] = 'Registrati';
$Definition['Register IP'] = 'Registro IP';
$Definition['Register with %s'] = 'Registrati';
$Definition['Registration  Fields'] = 'Campi di Registrazione';
$Definition['Registration URL'] = 'URL di Registrazione';
$Definition['Reject'] = 'Respingi';
$Definition['Reject this answer.'] = 'Respingi questa risposta';
$Definition['Remember me'] = 'Ricordami';
$Definition['Remember me on this computer'] = 'Ricordami su questo computer';
$Definition['Remote Configuration'] = 'Configurazione Remota';
$Definition['Remove'] = 'Rimuovi';
$Definition['Removed by'] = 'Rimosso da';
$Definition['Remove from %s'] = 'Rimuovi da %s';
$Definition['Remove Invitation'] = 'Cancella Invito';
$Definition['Remove My Picture'] = 'Rimuovi la Mia Immagine';
$Definition['Remove Picture'] = 'Rimuovi Immagine';
$Definition['Remove Warning'] = 'Rimuovi Avviso';
$Definition['Rename Forum'] = 'Rinomina Forum';
$Definition['Reopen'] = 'Riapri';
$Definition['Replies'] = 'Risposte';
$Definition['Reply'] = 'Rispondi';
$Definition['ReplyOnly'] = 'Puoi rispondere a questa e-mail direttamente per continuare. Inviato da {/,exurl}.';
$Definition['ReplyOrFollow'] = 'Rispondi a questa email direttamente o segui il link qui sotto per controllarla:';
$Definition['Report'] = 'Segnala';
$Definition['Report %s'] = 'Rapporto %s ';
$Definition['Reported by: '] = 'Segnalato da: ';
$Definition['Reported Posts'] = 'Post Riportati';
$Definition['Report Reason'] = 'Motivazione';
$Definition['Request a new password'] = 'Richiedi una nuova password';
$Definition['Request a new password →'] = 'Richiedi una nuova password →';
$Definition['Reset Password'] = 'Reimposta Password';
$Definition['Restored'] = 'Ripristinato';
$Definition['reverse'] = 'inverti';
$Definition['Revoke'] = 'Revoca';
$Definition['Revoked'] = 'Revocato';
$Definition['Revoked badge.'] = 'Emblema revocato.';
$Definition['role'] = 'ruolo';
$Definition['RoleID'] = 'ruolo';
$Definition['Roles'] = 'Ruoli';
$Definition['roles'] = 'ruoli';

$Definition['Save'] = 'Salva';
$Definition['Save Comment'] = 'Salva Commento';
$Definition['Save Draft'] = 'Salva Bozza';
$Definition['Save Poll'] = 'Salva Sondaggio';
$Definition['Save Preferences'] = 'Salva Preferenze';
$Definition['Save your password'] = 'Salva la tua password';
$Definition['Search'] = 'Cerca';
$Definition['Search %s'] = 'Ricerca %s';
$Definition['search archived'] = 'cerca nell\'archivio';
$Definition['SearchBoxPlaceHolder'] = 'Cerca';
$Definition['Search for a tag.'] = 'Cerca per tutto oppure una parte del tag.';
$Definition['Search results for \'%s\''] = 'Risultati della ricerca per \'%s\'';
$Definition['search subcategories'] = 'cerca nelle sottocategorie';
$Definition['Second Anniversary'] = 'Secondo Anniversario';
$Definition['Secret'] = 'Segreto';
$Definition['Sections'] = 'Sezioni';
$Definition['Security Check'] = 'Controllo di Sicurezza';
$Definition['Select an image on your computer (2mb max)'] = 'Selezione un un\'immagine dal tuo computer (max. 2MB).';
$Definition['Select one of the following avatars:'] = 'Seleziona uno tra i seguenti avatar:';
$Definition['Send a New Message'] = 'Invia un Nuovo Messaggio';
$Definition['Send Message'] = 'Invia Messaggio';
$Definition['Send Report'] = 'Invia Rapporto';
$Definition['Send report'] = 'Invia rapporto';
$Definition['sep and'] = 'e';
$Definition['Set a New Warning Level'] = 'Imposta un Nuovo Livello di Avviso';
$Definition['Set A Password'] = 'Imposta Una Password';
$Definition['Setting'] = 'Opzione';
$Definition['Settings'] = 'Opzioni';
$Definition['Seventh Anniversary'] = 'Settimo Anniversario';
$Definition['Severity'] = 'Severità';
$Definition['Share'] = 'Condividi';
$Definition['Shared Accounts'] = 'Account Condivisi';
$Definition['she'] = 'lei';
$Definition['Shown only on mobile'] = 'Mostra solo su mobile';
$Definition['Show unfollowed categories'] = 'Mostra le categorie non seguite';
$Definition['Sign-In URL'] = 'URL Sign-In';
$Definition['Sign-Out URL'] = 'URL Sign-Out';
$Definition['Signature Code'] = 'Codice della Firma';
$Definition['Signature invalid.'] = 'Firma non valida.';
$Definition['Signatures'] = 'Firme';
$Definition['Signature Settings'] = 'Impostazioni della Firma';
$Definition['SignIn'] = 'Accedi';
$Definition['Sign In'] = 'Accedi';
$Definition['SigningOut'] = 'Attendi un secondo mentre ti disconnettiamo.';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Accedi</a> oppure <a href="{RegisterUrl,html}">Registrati</a> per commentare.';
$Definition['Sign in to vote!'] = 'Accedi per votare!';
$Definition['Sign In with %s'] = 'Accedi con %s';
$Definition['Sign In with Disqus'] = 'Accedi con Disqus';
$Definition['Sign In with Facebook'] = 'Accedi con Facebook';
$Definition['Sign In with Google'] = 'Accedi con Google';
$Definition['Sign In with OpenID'] = 'Accedi con OpenID';
$Definition['Sign In with Twitter'] = 'Accedi con Twitter';
$Definition['Sign Out'] = 'Esci';
$Definition['sign out'] = 'esci';
$Definition['Sign Up'] = 'Iscriviti';
$Definition['Sink'] = 'Declassa';
$Definition['Sink this discussion'] = 'Declassa questa discussione';
$Definition['Sitemap Settings'] = 'Impostazioni Sitemap';
$Definition['Sixth Anniversary'] = 'Sesto Anniversario';
$Definition['somebody'] = 'qualcuno';
$Definition['Some Code'] = 'Qualche Codice';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Qualcuno ha risposto al tuo quesito. Hai bisogno di accettare/rigettare la risposta.';
$Definition['sorted by'] = 'ordinate per';
$Definition['Source:'] = 'Sorgente:';
$Definition['Source Code'] = 'Codice';
$Definition['Spam Queue'] = 'Coda di Spam';
$Definition['Split'] = 'Dividi';
$Definition['Split Comments'] = 'Dividi Commenti';
$Definition['Spoof User'] = 'Utente Fasullo';
$Definition['Start'] = 'Inizia';
$Definition['Start a New Conversation'] = 'Nuova Conversazione';
$Definition['Start a New Discussion'] = 'Nuova Discussione';
$Definition['Start Conversation'] = 'Crea Conversazione';
$Definition['Started By'] = 'Cominciata da';
$Definition['Started by %1$s'] = 'Cominciata da %1$s';
$Definition['Start your First Discussion'] = 'Apri la tua Prima Discussione';
$Definition['Stop following'] = 'Smetti di seguire';
$Definition['Strikethrough'] = 'Barrato';
$Definition['Strip images out of signatures'] = 'Tolgo le immagini dalle firme';
$Definition['Strip images out of signatures?'] = 'Tolgo le immagini dalle firme?';
$Definition['Subject'] = 'Soggetto';
$Definition['Suggested Value'] = 'Valore Suggerito';

$Definition['Tagged'] = 'Taggata';
$Definition['Tagged with '] = 'Taggata con ';
$Definition['Tagged with "%s"'] = 'Taggata con "%s"';
$Definition['Tagging'] = 'Sistema di Tag';
$Definition['Tag Name'] = 'Nome del Tag';
$Definition['Tags'] = 'Tag';
$Definition['tags'] = 'tag';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'I Tag sono parole chiave che gli utenti possono assegnare alle discussioni per favorirne la categorizzazione delle loro domande con quesiti simili.';
$Definition['Take Action'] = 'Prendi Provvedimenti';
$Definition['Take Action:'] = 'Prendi Provvedimenti:';
$Definition['Target'] = 'Obiettivo';
$Definition['Tell the user why you\'re warning them'] = 'Spiega all\'utente perchè lo stai avvisando';
$Definition['Tell us why you want to join!'] = 'Spiegaci perché vuoi partecipare!';
$Definition['Tenth Anniversary'] = 'Decimo Anniversario';
$Definition['Terms'] = 'Termini';
$Definition['TermsOfService'] = 'Termini di Servizio';
$Definition['Terms of Service'] = 'Termini di Servizio';
$Definition['TermsOfServiceText'] = 'Accetti, attraverso l\'uso di questo servizio, che non utilizzerai questa
comunità per pubblicare materiale riconosciuto come falso e/o diffamatorio,
inesatto, abusivo, volgare, odioso, molesto, osceno, profano, sessualmente
orientato, minaccioso, invasivo della privacy di una persona, o che violi
qualsiasi legge. Accetti di non inviare alcun materiale coperto da copyright
a meno che non ne detenga il diritto d\'autore.

Noi di questa comunità ci riservano anche il diritto di rivelare la tua identità (o
tutte le informazioni che sappiamo di te) in caso di reclamo o di azione legale
derivante da qualsiasi messaggio inviato da te. Noi registriamo tutti gli indirizzi
dei protocolli internet che accedono a questo sito.

Si prega di notare che i messaggi pubblicitari, lettere a catena, schemi piramidali, e
sollecitazioni sono inappropriati in questa comunità.

Ci riserviamo il diritto di rimuovere qualsiasi contenuto per qualsiasi motivo o senza alcun
motivo. Ci riserviamo il diritto di terminare qualsiasi iscrizione per qualsiasi motivo o senza
alcuna ragione.

Devi aver compiuto almeno 13 anni per utilizzare questo servizio.';
$Definition['Text  Max  Length'] = 'Lunghezza Massima Testo';
$Definition['the category'] = 'la categoria';
$Definition['The conversation has been cleared.'] = 'La conversazione è stata pulita.';
$Definition['The email you entered in use by another member.'] = 'L\'e-mail inserita è già in uso da un altro membro.';
$Definition['The email you have entered is already related to an existing account.'] = 'L\'e-mail inserita è già collegata con un account esistente.';
$Definition['The file failed to upload.'] = 'Caricamento del file fallito.';
$Definition['their'] = 'loro';
$Definition['The name you entered is already in use by another member.'] = 'Il nome inserito è già in uso da un altro membro.';
$Definition['The page you were looking for could not be found.'] = 'La pagina che stavi cercando non è stata trovata.';
$Definition['The quote had to be converted from %s to %s.'] = 'La citazione doveva essere convertita da %s in %s. Qualche formattazione potrebbe essere andata persa.';
$Definition['There are no tags in the system yet.'] = 'Non ci sono ancora tag nel sistema.';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'Il valore reCAPTCHA non è stato inserito correttamente. Si prega di riprovare.';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Esiste già un account con lo stesso nome utente (%1$s) oppure e-mail (%2$s) come te. Puoi creare un nuovo account, oppure introdurre le credenziali di accesso per il tuo esistente account del forum.';
$Definition['The response was not in the correct format.'] = 'La risposta non era nel formato corretto.';
$Definition['There was an error connecting to Disqus'] = 'Si è verificato un errorre di connessione a Disqus';
$Definition['There was an error connecting to Facebook'] = 'Si è verificato un errorre di connessione a Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Si è verificato un errore caricando il file. È molto probabile che il file sia troppo grande.';
$Definition['The site is currently undergoing maintenance.'] = 'Il sito è attualmente in manutenzione.';
$Definition['The uploaded file was too big (max %s).'] = 'Il file caricato era troppo grande (max %s).';
$Definition['they'] = 'essi';
$Definition['Third Anniversary'] = 'Terzo Anniversario';
$Definition['This answer was %s.'] = 'Questa risposta è stata %s.';
$Definition['This answer was Accepted.'] = 'Questa risposta è stata Accettata.';
$Definition['This discussion has been closed.'] = 'Questa discussione è stata chiusa.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Questa discussione è correlata a una fonte indefinita di contenuti estera.';
$Definition['This discussion was created from comments split from: %s.'] = 'Questa discussione è stata creata dai commenti divisi da: %s.';
$Definition['This discussion was merged into %s'] = 'Questa discussione è stata unita in %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'L\'immagine è stata ridimensionata per adattarsi alla pagina. Clicca per ingrandire.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Questo è un sondaggio privato: nessuno potrà vedere cosa hai votato.';
$Definition['This is a public poll: others will see what you voted for.'] = 'Questo è un sondaggio pubblico: gli altri potranno vedere cosa hai votato.';
$Definition['This is a system account and does not represent a real person.'] = 'Questo è un account di sistema e non rappresenta una persona reale.';
$Definition['This Month\'s Leaders'] = 'Leader di Questo Mese';
$Definition['This question\'s answer has been accepted.'] = 'La risposta di questa domanda è stata accettata.';
$Definition['This user has been verified as a non-spammer.'] = 'Questo utente è stato verificato come non-spammer';
$Definition['This user has not been verified as a non-spammer.'] = 'Questo utente non è stato ancora verificato come non-spammer.';
$Definition['This user has not commented yet.'] = 'Questo utente non ha ancora commentato.';
$Definition['This user has not made any discussions yet.'] = 'Questo utente non ha iniziato ancora alcuna discussione.';
$Definition['This user is verified as a non-spammer'] = 'Questo utente è stato verificato come non-spammer';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Questo avviso è scaduto. Desideri eliminarlo completamente?';
$Definition['This Week\'s Leaders'] = 'Leader di Questa Settimana';
$Definition['Thumbnail'] = 'Miniatura';
$Definition['Title'] = 'Titolo';
$Definition['Toggle full page'] = 'Passa alla visualizzazione pagina intera';
$Definition['Toggle HTML view'] = 'Passa alla visualizzazione HTML';
$Definition['Toggle lights'] = 'Accendere/spegnere le luci';
$Definition['Topic'] = 'Argomento';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'Per inviare un\'altra e-mail di conferma clicca <a href="%s">qui</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'Per utilizzare reCAPTCHA è necessario ottenere una chiave API da %s';
$Definition['Transport error: %s'] = 'Un errore irreversibile si è verificato durante l\'elaborazione della richiesta.<br />Il server ha restituito la seguente risposta: %s';
$Definition['Turn ON'] = 'Attiva';
$Definition['Twitter Settings'] = 'Impostazioni di Twitter';
$Definition['Type'] = 'Tipo';

$Definition['Unable to send message, %s is ignoring you.'] = 'Impossibile inviare il messaggio, %s ti sta ignorando.';
$Definition['Unannounce'] = 'Togli Annuncio';
$Definition['Unanswered'] = 'Senza risposta';
$Definition['Unanswered Questions'] = 'Senza risposta';
$Definition['unavailable'] = 'non disponibile';
$Definition['Unban User'] = 'Togli Ban Utente';
$Definition['Unbookmark'] = 'Togli preferito';
$Definition['Undefined discussion body.'] = 'Corpo della discussione non definito.';
$Definition['Undefined discussion subject.'] = 'Oggetto della discussione non definito.';
$Definition['Undefined foreign content'] = 'Contenuto estero indefinito';
$Definition['Undo Follow'] = 'Annulla Segui Follow';
$Definition['Unfollow'] = 'Non seguire';
$Definition['Unhide'] = 'Non nasschondere';
$Definition['Unignore'] = 'Non ignorare';
$Definition['UniqueID'] = 'ID Univoco';
$Definition['Unknown'] = 'Sconosciuto';
$Definition['Unknown client: %s.'] = 'Cliente sconosciuto: %s.';
$Definition['Unordered list'] = 'Elenco non ordinato';
$Definition['Unread'] = 'Non lette';
$Definition['Unread Discussions'] = 'Discussioni Non lette';
$Definition['Unsink'] = 'Riclassifica';
$Definition['Unspecified'] = 'Non specificato';
$Definition['Upcoming Events'] = 'Eventi Futuri';
$Definition['Update'] = 'Aggiorna';
$Definition['Updated badge'] = 'Aggiorna Emblema';
$Definition['Upload'] = 'Carica';
$Definition['Uploading...'] = 'Caricamento...';
$Definition['UrlCode'] = 'codice Url';
$Definition['Use My Current Password'] = 'Usa la Mia Password Corrente';
$Definition['User "%s" does not exist.'] = 'L\'utente "%s" non esiste.';
$Definition['Username'] = 'Nome utente';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Il nome utente può contenere solo lettere, numeri o trattini bassi.';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'Il nome utente può contenere solo lettere, numeri o trattini bassi, e deve essere compresa tra 3 e 20 caratteri.';
$Definition['UsernameError'] = 'Il nome utente può contenere solo lettere, numeri o trattini bassi, e deve essere compresa tra 3 e 20 caratteri.';
$Definition['Username or email'] = 'Nome utente oppure e-mail';
$Definition['User not found.'] = 'Spiacente, non è stato trovato alcun account collegato al nome utente/e-mail inserito.';
$Definition['Users Count'] = 'Contatore Utenti';

$Definition['ValidateBanned'] = 'Questo %s non è autorizzato.';
$Definition['ValidateBoolean'] = '%s non è un valore booleano valido.';
$Definition['ValidateConnection'] = 'I parametri di connessione che hai specificato non sono riusciti a stabilire una connessione con il database. Il database ha restituito il seguente errore: <code>%s</code>';
$Definition['ValidateDate'] = '%s non è una data valida.';
$Definition['ValidateDecimal'] = '%s non è un valore decimale valido.';
$Definition['ValidateEmail'] = '%s non sembra essere valido.';
$Definition['ValidateEnum'] = '%s non è valido.';
$Definition['ValidateFormat'] = 'Non sei autorizzato a pubblicare codice HTML.';
$Definition['ValidateInteger'] = '%s non è un valore intero valido.';
$Definition['ValidateIntegerArray'] = '%s dovrebbe essere un elenco di numeri separati da virgole.';
$Definition['ValidateLength'] = '%1$s è troppo lungo di %2$s caratteri.';
$Definition['ValidateMatch'] = 'Il campo %s non corrisponde.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Devi selezionare almeno una %s.';
$Definition['ValidateRegex'] = '%s sembra non essere nel formato corretto.';
$Definition['ValidateRequired'] = '%s è richiesto.';
$Definition['ValidateRequiredArray'] = 'Devi selezionare almeno una %s.';
$Definition['ValidateTag'] = 'I tag non possono contenere gli spazi.';
$Definition['ValidateTime'] = '%s non è un tempo valido.';
$Definition['ValidateTimestamp'] = '%s non è un formato di tempo valido.';
$Definition['ValidateUrlStringRelaxed'] = '%s non può contentere slas, virgolette caratteri tag.';
$Definition['ValidateUsername'] = 'Il nome utente deve essere lungo 3-20 caratteri e composto da lettere, numeri e trattini bassi';
$Definition['ValidateVersion'] = 'Il campo %s non contiene un numero di versione valido. Visualizza la funzione php version_compare() per avere esempi di numeri di versione validi.';
$Definition['Value'] = 'Valore';
$Definition['Vanilla Statistics'] = 'Statistiche Vanilla';
$Definition['Vanilla Statistics Plugin'] = 'Plugin Statistiche Vanilla';
$Definition['Verified'] = 'Verificato';
$Definition['Verifying your credentials...'] = 'Verifico le tue credenziali...';
$Definition['Video embedding has been disabled.'] = 'La possibilità di includere video è stata disabilitata. Gli URL non si trasformeranno nel loro equivalente incluso.';
$Definition['View Badge'] = 'Visualizza Emblema';
$Definition['Viewing'] = 'Visualizzazione';
$Definition['Views'] = 'Visualizzazioni';
$Definition['Visible'] = 'Visibile';
$Definition['Visits'] = 'Visite';
$Definition['Visit Site'] = 'Visita Sito';
$Definition['Vote'] = 'Vota';
$Definition['Vote Down'] = 'Vota Giù';
$Definition['Votes'] = 'Voti';
$Definition['Vote Up'] = 'Vota Su';

$Definition['wall'] = 'bacheca';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Vuoi partecipare a questa discussione? Clicca uno di questi:';
$Definition['Warn'] = 'Avvisa';
$Definition['Warn %s'] = 'Avviso %s';
$Definition['Warned for'] = 'Segnalato per';
$Definition['Warning'] = 'Attenzione';
$Definition['Warnings'] = 'Avvertimenti';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} avvisato {WarnUserID,User} per {Points,plural,%s points}.';
$Definition['was'] = 'era';
$Definition['Website'] = 'Sito web';
$Definition['weeks'] = 'settimane';
$Definition['Welcome Aboard!'] = 'Benvenuto a bordo!';
$Definition['were'] = 'erano';
$Definition['What\'s This?'] = 'Che cos\'è questo?';
$Definition['What to search'] = 'Cosa cercare';
$Definition['Where do you want to announce this discussion?'] = 'Dove vuoi annunciare questa discussione?';
$Definition['Who\'s Online'] = 'Chi c\'è Online';
$Definition['Whoops! You\'ll need to register before you can email our site.'] = 'Ops! Dovrai registrarti prima di poter inviare email al nostro sito.';
$Definition['Whos Online'] = 'Chi c\'è Online';
$Definition['Why are you Banning this user?'] = 'Perché stai Bannando questo utente?';
$Definition['Write a comment'] = 'Scrivi un commento';
$Definition['Write Comment'] = 'Scrivi Commento';
$Definition['Write something about yourself...'] = 'Scrivi qualcosa su di te...';

$Definition['Yes'] = 'Si';
$Definition['You'] = 'Tu';
$Definition['you'] = 'tu';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">Hai posto delle domande che ora hanno delle risposte</a>. Assicurati di accettare/rifiutare le risposte.';
$Definition['You\'ve been Jailed.'] = 'Sei stato Imprigionato.';
$Definition['You already have an account here.'] = 'Possiedi già un account qui.';
$Definition['You are about to ban {User.UserID,user}.'] = 'Stai cercando di bannare {User.UserID,user}.';
$Definition['You are about to move %1$s of the %2$s of the selected discussions.'] = 'Stai per spostare %1$s delle %2$s delle discussioni selezionate.';
$Definition['You are about to move %s.'] = 'Stai per spostare %s.';
$Definition['You are about to unban {User.UserID,user}.'] = 'Stai cercando di togliere dal ban {User.UserID,user}.';
$Definition['You are allowed to create %s groups.'] = 'Puoi creare %s gruppi';
$Definition['You are connected as %s through %s.'] = 'Sei connesso come %s attraverso %s.';
$Definition['You are connected through %2$s.'] = 'Sei connesso attraverso %2$s.';
$Definition['You are currently only viewing categories that you follow.'] = 'Attuatlmente stai visualizzando solo le categorie che segui';
$Definition['You are currently viewing all categories.'] = 'Attualmente stai visualizzando tutte le categorie';
$Definition['You are editing %s\'s signature'] = 'Stai modificando la firma di %s';
$Definition['You are limited to %s recipient.'] = 'Hai un limite di %s destinatari.';
$Definition['You are limited to %s recipients.'] = 'Hai un limite di %s destinatari.';
$Definition['You can\'t leave the group you started.'] = 'Non puoi lasciare il gruppo che hai creato.';
$Definition['You can either ask a question or start a discussion.'] = 'Puoi sia fare una domanda che iniziare una discussione. Seleziona quello che vuoi fare in basso.';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Puoi seguire le singole categorie e ricevere una notifica per ciascuna pubblicazione che verrà effettuata al loro interno.';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Non puoi modificare la miniatura di un\'immagine del profilo collegata esternamente.';
$Definition['You can only specify up to %s tags.'] = 'Puoi specificare solo fino a %s tag.';
$Definition['You can remove or ban this member from the group.'] = 'Puoi rimuovere o bandire questo membro dal gruppo. I membri banditi non potranno più entrare nel gruppo.';
$Definition['You can use HTML in your signature.'] = 'Puoi utilizzare <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">HTML Semplice</a></b> nella tua firma.';
$Definition['You don\'t have permission to do that.'] = 'Non hai permessi sufficienti per fare questo';
$Definition['You do not have any %s yet.'] = 'Non hai ancora alcun %s.';
$Definition['You do not have any bookmarks.'] = 'Non hai alcun preferito.';
$Definition['You do not have any conversations.'] = 'Non hai alcuna conversazione';
$Definition['You do not have any drafts.'] = 'Non hai alcuna bozza';
$Definition['You do not have any notifications yet.'] = 'Non hai ancora alcuna notifica.';
$Definition['You do not have enough invitations left.'] = 'Non hai abbastanza inviti a disposizione.';
$Definition['You do not have permission to move %1$s of the selected discussions.'] = 'Non hai l\'autorizzazione per spostare %1$s delle discussioni selezionate.';
$Definition['You do not have permission to write new comments.'] = 'Non hai i permessi per scrivere nuovi commenti.';
$Definition['YouEarnedBadge'] = 'Hai ottenuto questo emblema';
$Definition['You have answered questions'] = 'Hai risposto alle domande';
$Definition['You have entered an invalid discussion title'] = 'Hai inserito un titolo non valido per la discussione';
$Definition['You haven\'t read this yet.'] = 'Non l\'hai ancora letto';
$Definition['You have not started any discussions.'] = 'Non hai ancora iniziato alcuna discussione.';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Hai pubblicato %1$s volte nell\'arco di %2$s secondi. Un sistema anti-spam è stato attivato sul tuo account. Dovrai attendere almeno %3$s secondi prima di tentare nuovamente la pubblicazione.';
$Definition['You have selected %1$s.'] = 'Hai selezionato %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Hai selezionato %1$s in questa discussione.';
$Definition['You have to select at least 2 discussions to merge.'] = 'Devi selezionare almeno 2 discussioni da unire.';
$Definition['You must agree to the terms of service.'] = 'Devi accettare i termini di servizio.';
$Definition['You need to confirm your email address.'] = 'Devi confermare il tuo indirizzo e-mail. Clicca <a href="{/entry/emailconfirmrequest,url}">qui</a> per rinviare l\'email di conferma.';
$Definition['You need to sign in before you can do this.'] = 'Devi effettuare l\'accesso prima di poterlo fare.';
$Definition['your'] = 'tuo';
$Definition['Your changes have been saved.'] = 'Le tue modifiche sono state salvate.';
$Definition['Your changes have been saved successfully.'] = 'Le tue modifiche sono state salvate con successo.';
$Definition['Your changes were saved.'] = 'Le tue modifiche siono state salvate.';
$Definition['Your email has been successfully confirmed.'] = 'La tua e-mail è stata confermata con successo.';
$Definition['Your invitation has been sent.'] = 'Il tuo invito è stato inviato.';
$Definition['Your old password was incorrect.'] = 'La tua password vecchia non è corretta.';
$Definition['Your password has been changed.'] = 'La tua password è stata modificata.';
$Definition['Your picture has been removed.'] = 'La tua immagine è stata rimossa.';
$Definition['Your post will appear once it\'s been approved.'] = 'La tua pubblicazione verrà visualizzata una volta eseguita l\'approvazione.';
$Definition['Your preferences have been saved.'] = 'Le tue preferenze sono state salvate';
$Definition['Your private conversations with other members.'] = 'Le tue conversazioni private con altri membri.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Il tuo nome utente registrato: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'La tua richiesta è stata inviata. Controlla la tua e-mail per ulteriori istruzioni.';
$Definition['Your settings have been saved.'] = 'Le tue impostazioni sono state salvate.';
$Definition['Your settings have been saved successfully.'] = 'Le tue impostazioni sono state salvate con successo.';
$Definition['Your warning was added.'] = 'Il tuo avvisto è stato aggiunto.';

$Definition[' You should '] = 'Dovresti';

$Definition['You were added to a conversation.'] = '{InsertUserID,user} aggiunto {NotifyUserID,you} alla <a href="{Url,htmlencode}">conversazione</a>.';
$Definition['You wrote:'] = 'Hai scritto:';

$Definition['↳ No results for \'%s\''] = '↳ Nessun risultato per \'%s\'';
$Definition['↳ Search results for \'%s\''] = '↳ Cerca risultati per \'%s\'';
$Definition['↳ Show All'] = '↳ Mostra Tutto';
