<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Advertencia: al activar esta función, puede que se produzcan errores en tu página web.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>¡Atención!</strong> Si eliminas un rol, los usuarios podrían no tener acceso a la aplicación.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>¡Cuidado!</strong> Mover debates a una categoría de repuesto puede hacer que estos desaparezcan (o aparezcan) si la categoría de repuesto tiene permisos distintos de la categoría que se va a eliminar.';

$Definition['About.DisableStatistics'] = 'Si tienes que deshabilitar la creación de informes de estos datos por algún motivo de negocios, puedes hacerlo añadiendo la siguiente línea al archivo de configuración de instalación: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Es muy importante para la continuación de este software de código abierto gratuito que midamos el alcance y eficacia de Vanilla con precisión. Te pedimos que, por favor, no deshabilites la creación de informes de estos datos.';
$Definition['AboutCommentEmbedding'] = 'Vanilla puede reemplazar de forma inmediata tu sistema de comentarios original. De hecho, puede usarse para añadir comentarios a cualquier página de la web.';
$Definition['AboutEmbedding'] = 'Las incrustaciones permiten que toda o parte de tu comunidad pueda incrustarse en otras aplicaciones y páginas web.';
$Definition['About Vanilla Statistics'] = 'Acerca de las Estadísticas Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Accede al foro de tu comunidad haciendo clic en el enlace "Visita el sitio" en la parte superior de esta página, o <a href={/,url}> haciendo clic aquí </a>. El foro de la comunidad es lo que todos los usuarios y clientes verán cuando visiten <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Añade límites a las dimensiones de carga de imagenes en en las discusiones y comentarios.';
$Definition['AddonProblems'] = '<h2>¿Problemas?</h2><p> Si algo va mal con un complemento y no puedes usar tu sitio web, puedes deshabilitarlos manualmente editando: </p>%s';
$Definition['AddressBarColorDescription'] = 'Algunos buscadores permiten un color para la barra de dirección. Solo móvil.';
$Definition['Alert users if they click external link.'] = 'Alerta a los usuarios si hacen clic en un enlace a una publicación que les alejará del foro. No se alertará a los usuarios cuando sigan enlaces que coincidan con un Dominio seguro';
$Definition['Alignment'] = 'Alineación';
$Definition['Alignment (Mobile)'] = 'Alineación (Móvil)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Todas las categorías enumeradas con una selección de 5 discusiones recientes debajo de cada una';
$Definition['Allow links to be transformed'] = 'Permite que los enlaces se conviertan en representaciones incrustadas en discusiones y comentarios. Por ejemplo, un enlace a YouTube se convertirá en un vídeo incrustado.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Permite a los usuarios con permiso %s cambiar sus propios avatares desde sus páginas de perfiles en Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Anonimizar direcciones IP';
$Definition['ApplicationHelp'] = 'Las aplicaciones te permiten añadir largos grupos de funcionalidad a tu sitio. <br /> Una vez que una aplicación ha sido añadida a la carpeta %s, puedes activarlas o desactivarlas aquí.';
$Definition['Apply Layout'] = 'Aplicar diseño';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = '¿Estás seguro de querer borrar este tema? Se borrará de forma permanente.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = '¿Estas seguro de haber ingresado el nombre correcto del servidor? ¿Quizá te equivocaste? La base de datos reporto: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Se requiere un rol con el tipo predeterminado "sin confirmar" para usar la confirmación por correo electrónico.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Guarde automáticamente borradores de debates, preguntas, ideas y comentarios no publicados.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Los avatars se reducirán si superan esta altura.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Los avatars se reducirán si superan este ancho.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Las miniaturas de los avatares se guardarán a este tamaño.';

$Definition['Background'] = 'Fondo';
$Definition['Background Image'] = 'Imagen de fondo';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = '¡Se creativo! Intenta dar a tus categorías nombres de cosas que comenta la comunidad.';
$Definition['Bordered'] = 'Bordeado';
$Definition['Bordered (Unified)'] = 'Bordeado (unificado)';
$Definition['Borderless'] = 'Sin borde';
$Definition['Border Radius'] = 'Radio del borde';
$Definition['Brand Color'] = 'Color de la marca';
$Definition['Buttons'] = 'Botones';
$Definition['Buttons & Inputs'] = 'Botones y entradas';
$Definition['Button Type'] = 'Tipo de botón';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Al hacer clic en el botón de más abajo, se eliminará la cuenta de usuario de %s definitivamente.';

$Definition['Center Aligned'] = 'Centro alineado';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Los cambios solo se aplicarán a los avatares recién cargados.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Cambiar el tamaño al que se guardan las imágenes de los avatares.';
$Definition['Change the way your community works with plugins.'] = 'Cambia la forma en la que tu comunidad trabaja con complementos. Hemos agrupado complementos populares con el software, y hay más disponibles en línea.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Las casillas de comprobación te permiten llevar a cabo acciones por lotes en una serie de discusiones o comentarios al mismo tiempo.';
$Definition['Check out our %s'] = 'Comprueba nuestro %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Consulta nuestra <0>documentación</0> o pregunta en nuestra <1>comunidad de expertos</1>.';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla es la plataforma comunitaria más sencilla y poderosa del mundo. Es facilísima de usar. Comienza con este vídeo introductorio y continua con los pasos mostrados más abajo. ¡Disfruta!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Elige la función que se asignará a los usuarios huérfanos:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Elige un tema para esta subcomunidad. <0>Leer más</0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Elige cómo gestionar todo el contenido relacionado con la cuenta de usuario de %s (comentarios, mensajes, etc.).';
$Definition['Choose Image'] = 'Cambiar imagen';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Puedes seleccionar un algoritmo de hash personalizado para firmar tu petición. El algoritmo de hash también debe usarse en tu biblioteca de cliente. Elige "md5" si no estás seguro.';
$Definition['Choose the order items are sorted.'] = 'Elija el orden en que se ordenan los artículos.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Elija la página que las personas deben ver cuando visiten <0 />';
$Definition['Choose the preferred layout for lists of categories.'] = 'Elije el diseño preferido para las listas de categorías.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Elija el diseño preferido para las listas de categorías. Puede editar el diseño en mosaico.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Elije el diseño preferido para las listas de discusiones.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Elige el diseño preferido para las listas de conversaciones. Puedes editar el diseño de la base.';
$Definition['Color Overlay'] = 'Superposición de colores';
$Definition['Continue Import'] = 'Continuar';
$Definition['Could not parse import file. The problem is near line %s.'] = 'No se pudo analizar el archivo de importación. El problema se encuentra cerca de la línea %s.';
$Definition['Create a localization CSV'] = 'Crear una localización CSV';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Los Temas personalizados son los temas que creaste. Puedes editarlos, renombrarlos o hacer una copia.';

$Definition['Dark'] = 'Oscuro';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Determina quién puede subir y gestionar archivos en la página de <a href="%s">Funciones y permisos</a>';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Determina la página principal de tu foro, sube tu logotipo y más...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Al eliminar una función, los usuarios podrían no tener acceso a la aplicación.';
$Definition['Deleting forever cannot be undone.'] = 'Eliminar es una buena forma de mantener tu foro limpio. ';
$Definition['Disable Google Sign In'] = 'Desactivar Google Sign In';
$Definition['Disable OpenID'] = 'Desactivar OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Deshabilita la prueba "Nuevo sistema de inserción" en la <0>página de Vanilla Labs</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Las categorías de discusiones se usan para ayudar a tus usuarios a organizar sus discusiones de manera que sean importantes para tu comunidad.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'No insertes el panel administrador de tu foro (ponlo en pantalla completa)';
$Definition['Don\'t use too many reactions.'] = 'No utilices demasiadas reacciones. No quieres ofrecer a tus usuarios una sobrecarga de información.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Coge y suelta las categorías de abajo para ordenarlas y agruparlas.';

$Definition['EditContentTimeout.Notes'] = 'Nota: Si un usuario tiene un rol que tiene permisos para editar contenido, esos permisos serán anulados por cualquier valor seleccionado aquí.';
$Definition['Edit Route'] = 'Editar Ruta';
$Definition['Edits to this theme apply to:'] = 'Los cambios de este tema se aplican a:';
$Definition['Embed Settings'] = 'Configuración de inserción';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Insertar su foro comunidad a tu sitio web para incrementar la participación...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Habilite y pruebe las últimas funciones de Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Permite la edición avanzada de publicaciones en varios formatos, incluidos WYSIWYG, HTML simple, Markdown, y BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Habilita el editor de diseño para aplicar un diseño personalizado a las páginas de tu comunidad. Utiliza nuestro nuevo editor para incluir contenido, con nuestro catálogo de controles disponibles.';
$Definition['Enter a descriptive name.'] = 'Introduce un nombre descriptivo para el pocket. Este nombre no aparecerá en ningún sitio excepto cuando gestiones tus pockets aquí, por lo que solo se usará para ayudarte a recordar el pocket.';
$Definition['Enter a short name for the site.'] = 'Introduce un nombre corto para este sitio web. Se mostrará en los botones de registro.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Introduce la dirección de tu blog WordPress y lo extraeremos desde allí.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Introduce la configuración de conexión para tu servidor Sphinx más abajo.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Aquí se registran todas las ediciones y eliminaciones. Usa ‘Restaurar’ para deshacer cualquier cambio.';
$Definition['Everyone who signs up gets a profile page.'] = 'Todo aquel que se inscriba en tu comunidad recibe una página de perfil pública donde pueden subir una foto suya, gestionar sus preferencias de perfil y seguir cosas interesantes que suceden en la comunidad. Deberías <a href="{/profile,url}">personalizar tu perfil ahora</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Cada usuario del sitio es asignado al menos a un rol. Los Roles se utilizan para determinar qué se le permite hacer a los usuarios.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect permite a los usuarios conectarse usando su cuenta de Facebook. <b> Debes registrar tú aplicación con Facebook para que este plugin funcione.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'No se pudo conectar con la base de datos con el nombre de usuario y clave de acceso que has introducido. ¿Los has escrito mal? La base de datos ha creado un informe: <code>%s</code>';
$Definition['Font'] = 'Fuente';
$Definition['Font Name'] = 'Nombre de la fuente';
$Definition['Font URL'] = 'URL de la fuente';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Haz que el panel solo sea accesible a través de esta URL <em>(no recomendado)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Por ejemplo, puedes restringir a todos los usuarios con direcciones de correo electrónico de "example.com" añadiendo una restricción de tipo de correo electrónico con el valor "*@example.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Por motivos de SEO, a las arañas de motores de búsqueda no se les obliga a ver el foro de la URL remota.';
$Definition['Foundation Layout'] = 'Disposición de la base';
$Definition['Full Anonymization'] = 'Anonimización total';
$Definition['FullAnonymization.Description'] = '<strong>Anonimización Completa</strong> reemplaza cada dirección IP con 0.0.0.0 denegando de forma efectiva a la aplicación cualquier acceso para trabajar con direcciones IP. Las reglas de prohibición de IP no funcionarán en absoluto en este caso.';
$Definition['Full Bleed'] = 'Sangría completa';

$Definition['Garden.Import.Complete.Description'] = 'Has completado una importación correctamente. Haz clic en <b>Finalizado</b> cuando hayas acabado.';
$Definition['Garden.Import.Continue.Description'] = 'Parece que estás en medio de una importación. Elije una de las siguientes opciones.';
$Definition['Garden.Import.InputInstructions'] = 'Introduce el email y la contraseña del usuario administrador de los datos que se importan';
$Definition['Garden.Privacy.IPs.Description'] = 'Las direcciones IP de los usuarios normalmente se recopilan para las reglas de bloqueo automático, moderación y prevención de correo no deseado. La activación de la anonimización de IP hará que todas las direcciones IP rastreadas en el sitio sean anónimas para cualquier propósito, y reducirá la eficacia de estas herramientas. Los cambios en esta configuración no serán retroactivos.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Permiso Jardín.Perfiles.Editar para cambiar sus propios avatares de sus páginas de perfil en Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Usted ha deshabilitado específicamente Estadísticas Vanilla en su archivo de configuración.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Este foro parece estar funcionando en periodo de pruebas o tiene una identificación privada. Por defecto, los foros que funcionan mediante identificación privada no se rastrean.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Si estás seguro de que tu foro es accesible a través de Internet, puedes hacer que emita informes estadísticos aquí:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Tu archivo config.php parece ser de solo lectura. Esto significa que Vanilla no podrá registrar automáticamente el InstallationID del foro ni el InstallationSecret.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Para resolver este problema, asigna el modo de archivo 777 a tu archivo conf/config.php.';
$Definition['Global Styles'] = 'Estilos globales';

$Definition['Heads Up!'] = '¡Levanta la cabeza!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = '¡Atención! Esta es una función especial que no permite sesiones activas. Por ello las opciones de permiso se han limitado para solo "ver" permisos.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Aquí están todas las reacciones que puedes emplear en este sitio.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Aquí están las categorías que los usuarios pueden conseguir en este sitio. Puedes personalizar estas categorías e incluso añadir otras nuevas. Aquí van algunas pistas.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Si se sube el logotipo de un banner, éste sustituirá al título del banner en las páginas de foros interactivos.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Si un usuario no visita el sitio dentro de ese periodo de tiempo, será automáticamente desconectado.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Si está desactivado, todo el contenido de las publicaciones se enviará a los usuarios en notificaciones de correo electrónico.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Si eres nuevo en HTML o CSS, aquí hay algunos tutoriales para que puedas empezar:';
$Definition['If you have an old theme'] = 'Si tienes un tema viejo o necesitas configurar un tema diferente para escritorio y móvil, puedes hacerlo con la vieja interfaz de temas.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Si quieres disminuir el nivel de advertencia, debes eliminar una advertencia.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Si deseas incrustar tu foro o utilizar los comentarios de Vanilla en tu blog, tendrás que activar la incrustación. Si no estás utilizando la incrustación, recomendamos dejar esta configuración inactiva.';
$Definition['Image (Mobile)'] = 'Imagen (móvil)';
$Definition['Import'] = 'Importar';
$Definition['Importing to Vanilla'] = 'Importar a Vanilla';
$Definition['In additon to the widgets there are also'] = 'Además de las miniaplicaciones, también hay <0>Estilos globales</0>. Para editar los estilos globales haz clic en cualquier otro lugar de la página, como este texto.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integre las páginas y los componentes de la base en su tema';
$Definition['Internationalization & Localization'] = 'Internacionalización y localización';
$Definition['Invalid URL'] = 'URL inválida';
$Definition['Invitation email failed to send: %'] = 'Aunque la invitación se creó con éxito, no se pudo enviar el correo electrónico. El servidor informó del siguiente error: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Cuando usas el registro por invitación, los usuarios tendrán un enlace llamado <a href="%s" class="Popup">Mis Invitaciones</a> en su página de perfil.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Parece que la base de datos que has especificado no existe todavía. ¿La has creado ya? ¿Has escrito mal el nombre? La base de datos ha creado un informe: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Es una buena idea mantener el número máximo de caracteres permitidos en un comentario a un tamaño razonable';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Es buena idea mantener el número máximo de caracteres permitidos en una publicación a un tamaño razonablemente bajo.';

$Definition['Kick-start your community and increase user engagement.'] = 'Activa tu comunidad y aumenta la participación de los usuarios.';

$Definition['Labs'] = 'Laboratorios';
$Definition['Layout Editor'] = 'Editor de diseño';
$Definition['Learn about custom routing.'] = 'Más información sobre rutas personalizadas.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Aprenda a cambiar completamente el aspecto de tu foro: cargando su logotipo, pon tu página de inicio, seleccione un tema y personalizarlo.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Aprenda a utilizar las funciones básicas de su foro.';
$Definition['Left Aligned'] = 'Alineación izquierda';
$Definition['Light'] = 'Iluminación';
$Definition['Links'] = 'Enlaces';
$Definition['Locales allow you to support other languages on your site.'] = 'Los locales te permiten establecer otros idiomas en tu sitio. Habilita y deshabilita los locales que quieras que estén disponibles aquí.';
$Definition['Lockout Time (seconds)'] = 'Duración del bloqueo (segundos)';
$Definition['LogoDescription'] = 'El logotipo del banner aparece en la parte superior de su sitio.';
$Definition['LogoDisclaimer'] = 'Los temas creados con el editor de temas y algunos temas personalizados no utilizan esta configuración.';
$Definition['Looking for the Old Embed System?'] = '¿Buscas el antiguo sistema de inserción?';

$Definition['Make sure you click View Page'] = 'Haz clic en <a href="%s">Ver página</a> para ver cómo queda tu página de categorías después de guardarla.';
$Definition['Manage Routes'] = 'Gestionar Rutas';
$Definition['Managing Users'] = 'Administrar usuarios';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Marcar cosas como NO spam las pondrá de nuevo en tu foro. ';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Marcar cosas como no spam las pondrá de nuevo en tu foro. ';
$Definition['Messages can appear anywhere in your application.'] = 'Los mensajes pueden aparecer en cualquier parte de tu aplicación, y pueden ser utilizados para informar a los usuarios de noticias y eventos. Utiliza esta página para reorganizar tus mensajes arrastrándolos hacia arriba o hacia abajo.';
$Definition['MobileLogoDescription'] = 'El logotipo del banner móvil aparece en la parte superior de su sitio.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Los temas móviles te permiten cambiar el aspecto y percepción de tu sitio en dispositivos más pequeños.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'Nota: el nuevo editor de diseño heredará el conjunto de temas de tu Guía de estilo (formalmente, editor de temas). <1>Más información</1>';
$Definition['Need More Help?'] = '¿Necesitas más ayuda?';
$Definition['Need more help?'] = 'Necesitas más ayuda?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Las categorías anidadas a mayor profundidad se pondrán en una lista separada por comas.';
$Definition['New Embed System'] = 'Nuevo sistema de inserción';
$Definition['New Quick Links'] = 'Nuevos enlaces rápidos';
$Definition['New Search Page'] = 'Nueva página de búsqueda';
$Definition['No Anonymization'] = 'Sin anonimización';
$Definition['Not getting what you expect when you preview your theme?'] = '¿No obtienes lo que esperas al hacer una vista previa de tu tema?';
$Definition['Notify me when people comment on my addons.'] = 'Notificarme cuando la gente comenta en mis extensiones. 

';
$Definition['No unconfirmed role available for email confirmation.'] = 'El sitio necesita un rol con el tipo predeterminado "sin confirmar" para usar la confirmación por correo electrónico. Por favor, agregue uno para habilitar esta configuración.';

$Definition['Old Theming UI'] = 'Vieja interfaz de temas';
$Definition['Once enabled, only members will see inside your community.'] = 'Una vez habilitado, solo los miembros podrán ver el interior de tu comunidad.';
$Definition['OrgDescription'] = 'El nombre de tu organización está en uso para microdatos SEO y JSON+LD';
$Definition['Outline'] = 'Descripción';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Las vistas anuladas o los ganchos de temas pueden tener efectos secundarios no intencionados y no se mostrarán en la vista previa.';

$Definition['Partial Anonymization'] = 'Anonimización parcial';
$Definition['PartialAnonymization.Description'] = '<strong>Anonimización Parcial</strong> anonimiza únicamente el último octeto de la dirección IP. Por ejemplo 254.230.05.153 se convertiría en 254.230.05.0. Esto proporciona un cierto anonimato al tiempo que permite el funcionamiento de las reglas de bloqueo de IP.';
$Definition['Password.MinLength'] = 'Tamaño mínimo permitido para las contraseñas de los usuarios en las páginas de creación y restablecimiento de contraseñas.';
$Definition['Please choose an authenticator to configure.'] = 'Por favor elige un autenticador para configurar.';
$Definition['PluginHelp'] = 'Los plugins te permiten añadir funcionalidad a tu sitio.<br />Una vez añadido un plugin a la carpeta %s, puedes activarlo o desactivarlo aquí.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'El pocket se muestra entre cada una de las discusiones de la lista principal de discusiones. Como las discusiones están normalmente <li>..</li> etiquetadas, tendrás que etiquetar también tus pockets.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Los bolsillos te permiten añadir formularios HTML gratuitos a varios lugares de la aplicación.';
$Definition['Preset'] = 'Predeterminado';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Evita el spam en tu foro limitando el número de discusiones y comentarios que los usuarios pueden enviar dentro de un periodo de tiempo dado.';
$Definition['Primary Button'] = 'Botón principal';
$Definition['Primary Buttons'] = 'Botones principales';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Guía rápida para crear plantillas para Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Los enlaces rápidos es un componente predeterminado en las páginas de la comunidad. Habilite nuestro nuevo componente de Vínculos Rápidos para agregar, editar u ocultar vínculos de este menú usando nuestro editor de temas.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Complemento de comentarios de Vanilla ya creados para WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Complemento de foro Vanilla ya creado para WordPress';
$Definition['Realtime progress bars: %s'] = 'Barras de progreso en tiempo real: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Es buena idea tener categorías especiales para los moderadores y administradores para que tu comunidad pueda ver fácilmente quién está a cargo.';
$Definition['Recommend starting with five ranks.'] = 'No quieres tener demasiados rangos. Recomendamos empezar con cinco. Puedes añadir más si tu comunidad es verdaderamente grande.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Elimina los enlaces de discusión y categorías de los menús. Configure las páginas relacionadas con la discusión y la categoría para devolver la página 404 no encontrada.';
$Definition['Requires “Flag” reaction permission.'] = 'Requiere permiso de reacción "Etiquetar"';
$Definition['Requires “Negative” reaction permission.'] = 'Requiere permiso de reacción "Negativa".';
$Definition['Requires “Positive” reaction permission.'] = 'Requiere permiso de reacción "Positiva"';
$Definition['Restoring your selection removes the items from this list.'] = 'Al realizar la restauración, los artículos de esta lista serán eliminados y recolocados en el sitio web.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Utiliza la siguiente opción para activar citas para el Editor enriquecido. Esto solo funcionará si el formateo por defecto es "Enriquecido".';
$Definition['Route Expression'] = 'Expresión de Ruta';
$Definition['Routes are used to redirect users.'] = 'Las rutas se usan para redirigir a usuarios en función de la URL solicitada.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Busca usuarios por nombre o ingresa el nombre de un rol para ver todos los usuarios con ese rol.';
$Definition['Secondary Button'] = 'Botón secundario';
$Definition['Secondary Buttons'] = 'Botones secundarios';
$Definition['Security.Hsts.HTTPSWarning'] = 'Atención: habilite esta opción solo si sabe con seguridad que todos sus subdominios están configurados para HTTPS con certificados válidos.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Cuando está habilitada, esta regla se aplica también a todos los subdominios de su página.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Recomendamos que comience con un periodo máximo de una semana, luego aumente a un mes y finalmente a un año una vez compruebe que su página funciona según lo esperado.';
$Definition['Security.Hsts.SubmitWarning'] = 'Atención: forma parte de las buenas prácticas ofrecer compatibilidad con la precarga HSTS. Sin embargo, debe presentar su página a hstspreload.org para asegurarse de que se precarga correctamente (es decir, para obtener protección completa según la configuración deseada).';
$Definition['See the documentation'] = 'Ver la documentación';
$Definition['Select the default type for this role, if any.'] = 'Elije el tipo por defecto para este rol, si lo hay.';
$Definition['Select the import source'] = 'Selecciona la fuente de importación';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'No se pudieron convertir las columnas seriadas "%s" en no seriadas.';
$Definition['Session Timeout'] = 'Tiempo de espera de cierre de sesión';
$Definition['Shadowed'] = 'Sombreado';
$Definition['ShareImageDescription'] = 'Cuando alguien comparte un enlace desde tu sitio, intentamos tomar una imagen de la página. Si no hay ninguna imagen en la página, utilizaremos esta imagen en su lugar. La imagen debería ser de al menos 50 x 50 , pero recomendamos 200 x 200.';
$Definition['Show all possible pocket locations.'] = 'Activa esta opción para mostrar todas las ubicaciones de pockets posibles. Al activar esta opción, solo se mostrarán las ubicaciones a los usuarios que puedan gestionar pockets.';
$Definition['SignIn.LockoutTime'] = 'La cantidad de tiempo que un usuario está bloqueado para iniciar sesión después de exceder el número de intentos de acceso.';
$Definition['Solid'] = 'Sólido';
$Definition['Some browsers support a color for the address bar.'] = 'Algunos navegadores admiten un color para la barra de direcciones.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Algunos temas más antiguos no soportan la capacidad de edición completa. Para ver lo que un tema soporta, puedes pasar el cursor sobre su nombre para ver donde los cambios tendrán efecto.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Es posible que algunos temas deban actualizarse para trabajar con la categoría siguiente. Puedes desactivar la función mientras actualizas tu tema.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Quizá quieras integrar tu web de Vanilla dentro de otra. El sistema de inserción de Vanilla es un modo fácil de hacerlo. Hay costes de rendimiento al usar un sitio integrado, consulta la documentación para conocer las alternativas y los casos prácticos ideales.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Restricción especial: Solo los usuarios con permiso Jardín.Curación.Gestionar pueden usar esta reacción.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Al crear la restricción, especifica una correspondencia parcial o total.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Invierte un poco de tiempo pensando en cómo describirías tu sitio. Dando a tu sitio un título significativo y descripción concisa puede ayudar a su posición en los motores de búsqueda.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Dale un toque a tus correos electrónicos añadiendo un logotipo y personalizando los colores.';
$Definition['Start Import'] = 'Iniciar Importación ';
$Definition['Start the first discussion.'] = 'Pon la maquinaria de tu comunidad en marcha <a href="{/post/discussion,url}">empezando la primera discusión</a> ahora.';
$Definition['Subcommunities'] = 'Subcomunidades';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'El etiquetado permite a los usuarios añadir una etiqueta a las discusiones que éstos inician para hacerlas más reconocibles.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Las plantillas son temas estándar. Para personalizarlas, tienes que crear una copia.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'El Autenticador %s no tiene opciones de configuración propia.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB El laboratorio <0 /> debe configurarse para que coincida con su tema personalizado. Esto se puede hacer usando nuestro nuevo editor de temas. <1> Obtenga más información.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'El addon podría no estar habilitado porque generó un error fatal: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'El complemento ya ha sido descargado.';
$Definition['The banner logo appears at the top of your forum.'] = 'El logo aparece en la parte superior de su foro.';
$Definition['The banner title appears on the top-left of every page.'] = 'El título del banner aparece en la parte superior izquierda de cada página.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'El título del banner aparece en el banner de tu sitio web y en la barra de título del navegador. Debe tener menos de 20 caracteres. Si se sube el logotipo de un banner, éste reemplzará el título del banner en las páginas de foros interactivos. También ten en cuenta que algunas plantillas podrían ocultar este título.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>El formulario básico de registro exige</strong> que los nuevos usuarios copien texto de una imagen CAPTCHA para mantener a los anunciantes fuera del sitio. Necesitas una cuenta en <a href="http://recaptcha.net/"> recaptcha.net </a>. La inscripción es GRATUITA y fácil. Una vez que te hayas registrado, vuelve aquí e introduce los siguientes valores:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'El usuario de la base de datos que has especificado no tiene permiso para acceder a la misma. ¿Ya la has creado? La base de datos ha creado un informe: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Los siguientes cambios en la estructura son requeridos por tu base de datos. ';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'El título de la página principal se muestra en tu página principal. Elige el título que te gustaría que apareciera en los motores de búsqueda.';
$Definition['The import file does not contain any data.'] = 'El archivo importado no contiene información. ';
$Definition['The import file is not in the correct format.'] = 'El archivo importado no esta en el formato correcto. ';
$Definition['The location of the authentication endpoint.'] = 'La ubicación del punto final de autenticación.';
$Definition['ThemeHelp'] = 'Los Temas te permiten cambiar el look & feel de tu sitio.<br />Una vez que un tema ha sido añadido a la carpeta %s, puedes habilitarlo aquí.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'La vista previa del tema se limita a mostrar la plantilla y CSS del tema.';
$Definition['Theming Guide'] = 'Guia de temas';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'El logotipo móvil aparece en la parte superior de su sitio. Los temas creados con el editor de temas y algunos temas personalizados no utilizan esta configuración.';
$Definition['The New Embed System'] = 'El nuevo sistema de inserción';
$Definition['The new embed system has improved performance.'] = 'El nuevo sistema de inserción tiene mayor rendimiento, un desplazamiento mejorado y un comportamiento más consistente que el anterior. Por el momento, no es compatible la inserción de comentarios y contenido de Wordpress con el nuevo sistema.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'El autentificador de la contraseña no tiene ninguna opción de configuración personalizada.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'No hay cambios de estructura de base de datos requeridos. Sin embargo, puede haber cambios de información.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Hay dos tipos de botones en la aplicación: principal y secundario.';
$Definition['The route was saved successfully.'] = 'La ruta se ha guardado correctamente.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'La descripción del sitio suele aparecer en los motores de búsqueda. Debe intentar tener una descripción que tenga entre 100 y 150 caracteres.';
$Definition['The text of the pocket.'] = 'Introduce el texto del pocket. Éste aparecerá tal y como lo escribas, así que asegúrate de poner un HTML válido.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'El icono táctil aparece cuando marcas un sitio web en la pantalla de inicio de un dispositivo móvil. Suelen ser de 152 píxeles.';
$Definition['The user table was not in the import file.'] = 'La table de usuario no estaba en el archivo importado.';
$Definition['The Vanilla 2 Exporter'] = 'El exportador Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Las estadísticas vainilla convierte el panel de tu foro en una herramienta de informe de datos, permitiéndote revisar la actividad en tu foro en períodos de tiempos concretos. Puedes <a href="http://vanillaforums.org/docs/vanillastatistics"> leer más sobre las estadísticas vainilla </a> en nuestra documentación.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Funcionan como los temas normales. Una vez que se han añadido a la carpeta de temas, puedes activarlo aquí.';
$Definition['This is a style guide of your theme.'] = 'Esta es una guía de estilo para tu tema. Contiene ejemplos de los elementos visuales utilizados en toda la aplicación. Puedes hacer clic en las distintas miniaplicaciones como <0>Barra del título</0> o <1>Anuncio</1> para editar sus propiedades en este panel.';
$Definition['This is the administrative dashboard for your new community.'] = 'Este es el panel de control administrativo para tu nueva comunidad. Echa un vistazo a las opciones de configuración que aparecen a un lado. Desde allí puedes configurar el funcionamiento de tu comunidad. <b>De forma predeterminada, solo los usuarios con el rol "Administrador" pueden ver esta parte de tu comunidad.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Aquí es donde puede habilitar y probar nuevas funciones, páginas y componentes de Vanilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'No se puede deshabilitar esta prueba porque usa un diseño personalizado.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Este laboratorio no se puede inhabilitar porque el tema actual lo requiere.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Este logotipo aparece en la parte superior de su sitio. Los temas creados con el editor de temas y algunos temas personalizados no utilizan esta configuración.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Esta opción muestra/oculta las ubicaciones a donde pueden ir los pockets, pero solo para los usuarios con permiso para añadir/editar pockets. Prueba a mostrar las ubicaciones y luego visita tu sitio.';
$Definition['This page lists the endpoints of your API.'] = 'Esta página lista los puntos finales de comunicación de tu API. Haz clic en los puntos finales de comunicación para más información. Puedes hacer llamadas en directo a la API desde esta página o externamente utilizando un identificador de acceso.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Este rol es información personal. Solo será visible para usuarios con permiso para ver información personal.';
$Definition['This setting loads the page before executing Javascript.'] = 'Esta configuración carga la página antes de ejecutar Javascript, lo cual puede mejorar tu SEO.<br><strong>**Advertencia: Habilitar esta función puede causar errores de Javascript en tu sitio web.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Esta configuración carga la página antes de ejecutar Javascript, lo que puede mejorar su SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Este tema no se puede eliminar porque es el que está actualmente en uso.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Este título aparece en el banner de su sitio y en la barra de título de su navegador. Debe tener menos de 20 caracteres. Si se carga un logotipo, reemplazará este título en las páginas del foro orientadas al usuario. Además, tenga en cuenta que algunos temas pueden ocultar este título.';
$Definition['Tiled Layout'] = 'Disposición en mosaico';
$Definition['Title Bar'] = 'Barra del título';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Para insertar tu foro Vanilla en tu sitio web, usa el siguiente código. ';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = '¡Demasiadas direcciones! Enviaremos un máximo de %s cada vez.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Para evitar abusos, algunas herramientas esconden contenidos automáticamente y los registran aquí hasta que sea aprobado manualmente por un moderador.';
$Definition['TouchIconDescription'] = 'El icono Touch aparece cuando marcas un sitio web en la pantalla principal de un dispositivo Apple. Normalmente son 152 píxeles. Apple añade bordes redondeados y efecto aclarador automáticamente';
$Definition['Transparent'] = 'Transparente';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect permite a los usuarios iniciar sesión con su cuenta de Twitter. <b>Debes registrar tu aplicación con Twitter para que este plugin funcione.</b>';

$Definition['Usercards'] = 'Tarjetas de usuario';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Las tarjetas de usuario te permiten obtener un vistazo rápido en línea de la información de un usuario. Al visualizar publicaciones y clasificaciones, haz clic en el nombre de usuario para ver una tarjeta que muestra la información básica del perfil del usuario sin tener que salir de la página. Activa esta función para añadir tarjetas de usuario a tu tema personalizado.';
$Definition['User inputs are based on the global background and text colors.'] = 'Las entradas de los usuarios se basan en el fondo global y en los colores del texto.';
$Definition['User Profile'] = 'Perfil del usuario';
$Definition['Users may sign into your site using their Twitter account.'] = 'Los usuarios pueden iniciar sesión en tu sitio utilizando su cuenta de Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Usa el botón en la parte superior de la página para crear una regla de prohibición.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Usa el plugin de WordPress para instalar los Comentarios Vanilla en tu blog, o usa el código universal para instalar Comentarios Vanilla en otra plataforma. ';

$Definition['Vanilla\'s new search service is finally here.'] = 'El nuevo servicio de búsqueda de Vanilla finalmente está aquí. Activa nuestra nueva interfaz de usuario de página de búsqueda para tener acceso a las últimas funciones de búsqueda como Búsqueda de Miembros, ordenación de búsqueda y destacado de términos.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Exportar Vanilla: %s, Fuente: %s';
$Definition['Vanilla Labs'] = 'Laboratorios de vainilla';
$Definition['Vanilla Statistics are currently disabled'] = 'Las estadísticas vainilla están desactivadas actualmente';
$Definition['Verify and restore'] = 'Verificar y restaurar';
$Definition['VerifyUser'] = 'Marque la casilla junto al usuario para marcarlo como <b>verificado</b> para que sus publicaciones no se marquen como spam nuevamente. Esto también restaurará todas sus publicaciones pendientes.';
$Definition['Video tutorial on advanced settings'] = 'Video tutorial en configuración avanzada ';
$Definition['Video tutorial on finding &amp; managing users'] = 'Vídeo tutorial sobre cómo encontrar y gestionar usuarios';
$Definition['Video tutorial on managing appearance'] = 'Vídeo tutorial sobre cómo gestionar la apariencia';
$Definition['Video tutorial on managing categories'] = 'Video Turorial para gestionar las categorías. ';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Vídeo tutorial sobre cómo gestionar funciones y permisos';
$Definition['Video tutorial on user registration'] = 'Video Tutorial para el registro de usuarios. ';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Advertencia: al habilitar esta función puede que ocurran errores Javascript en tu sitio.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Advertencia</b>: La configuración de tu servidor no es compatible con la carga rápida de datos. Si estás importando un archivo muy grande (p. ej., con más de 200 000 comentarios) puede que quieras cambiar tu configuración. Haz clic <a href="http://vanillaforums.com/porter">aquí</a> para más información.';
$Definition['Warning: This is for advanced users.'] = '<b>Advertencia</b>: Esto es para usuarios avanzados y requiere hacer cambios adicionales en el servidor de tu web. Normalmente está disponible solo si tienes un alojamiento VPS o dedicado. No intentes esto si no sabes lo que estás haciendo.';
$Definition['Welcome to Labs!'] = '¡Bienvenido a Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Bienvenido a la interfaz de usuario de temas de Vanilla. Esta página lista todos tus temas disponibles, permitiéndote copiarlos o editarlos.';
$Definition['Welcome To Your Theme'] = 'Bienvenido a tu tema';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Recomendamos reacciones mayoritariamente positivas para animar a la participación.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Cuando se activa, puedes gestionar productos y agrupar las subcomunidades por esos productos.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Cuando alguien comparte un enlace desde tu sitio, intentamos tomar una imagen de la página. Si no hay ninguna imagen en la página, utilizaremos esta imagen en su lugar. La imagen debería ser de al menos 50 x 50 , pero recomendamos 200 x 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Cuando eliges sangría completa, tu fondo será transparente.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Si los campos de perfil interno se incluirán o no en este webhook.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Si los campos de perfil privado se incluirán o no en este webhook.';
$Definition['Which reactions you use really depends on your community.'] = 'Las reacciones que puedes utilizar dependen de tu comunidad, pero recomendamos tener en cuenta algunos puntos.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Está a punto de aplicar una nueva opción de diseño. Esto se puede personalizar y previsualizar usando nuestro Editor de temas. <0> Más información</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Puedes restringir a todos los usuarios con direcciones IP con prefijo "111.111.111" añadiendo una restricción de tipo de IP con el valor "*111.111.111*".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Puedes restringir direcciones IP o de correo electrónico y nombres de usuarios.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Puedes elegir entre uno de los diferentes estilos que ofrece este tema.';
$Definition['You can configure some values differently for different screensizes.'] = 'Puedes configurar algunos valores distintos para distintos tamaños de pantalla.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Puedes conectarte en múltiples sitios que suporten jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Si tu archivo es demasiado grande para subirlo directamente a esta página puedes subirlo a la carpeta /uploads. Asegúrate de que el nombre de archivo empieza con <b>export</b> y termina con <b>.txt</b> ó <b>.gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Puedes especificar una longitud mínima de la publicación para desincentivar las publicaciones cortas.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Puedes subir una fuente personalizada en tu sistema de temas. Solo copia y pega la URL en el campo';
$Definition['You must select a file to import.'] = 'Debes seleccionar un archivo para importar.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Debe agregar el dominio de la URL de la fuente a <0> dominios permitidos </0> en la configuración del sitio. <1> Obtenga más información sobre las fuentes personalizadas. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Su tema móvil será deshabilitado. Para configurar un tema móvil y de escritorio diferente, use la vieja IU the temas.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'El nombre de tu organización está en uso para microdatos SEO y JSON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'El favicono de tu sitio aparece en la barra de título del navegador. Se reducirá según corresponda.';
