<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s aceptó la invitación de %4$s para unirse';
$Definition['%1$s changed %4$s permissions.'] = '%1$s cambió los permisos de %4$s ';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s cambió %6$s foto de perfil.';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s comentó los %4$s de %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s creada una cuenta para %4$s.';
$Definition['%1$s joined.'] = '%1$s se registró.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s mencionó %3$s en un %8$s.';
$Definition['%1$s on %2$s'] = '%1$s sobre %2$s';
$Definition['%1$s signed in.'] = '%1$s ha iniciado sesión.';
$Definition['%1$s to %2$s'] = '%1$s a %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s a %2$s de %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s perfil %6$s actualizado.';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s fue agregado al %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s fue eliminado de %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s fue eliminado de %2$s %3$s y agregado al %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s escrito en %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s aprobó%2$s la solicitud de membresía.';
$Definition['%3$s created an account for %1$s.'] = '%3$s creada una cuenta para %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 a %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 a %s$2 de %s$3';
$Definition['%s (Current)'] = '%s (Actual)';
$Definition['%s Agrees'] = '%s Acepta';
$Definition['%s and you'] = '%s y tú';
$Definition['%s Awesomes'] = '%s Impresionante';
$Definition['%s by %s'] = '%s por %s';
$Definition['%s changed %s\'s permissions.'] = '%s cambió los permisos de%s ';
$Definition['%s Comment'] = '%s Comentario';
$Definition['%s comment'] = '%s comentario';
$Definition['%s comment html'] = '%s comentario';
$Definition['%s Comments'] = '%s Comentarios';
$Definition['%s comments'] = '%s comentarios';
$Definition['%s comments html'] = '%s comentarios';
$Definition['%s Connect'] = '%s Conectar';
$Definition['%s day'] = '%s día';
$Definition['%s days'] = '%s días';
$Definition['%s deleted this conversation.'] = '%s eliminado esta conversación.';
$Definition['%s discussion'] = '%s discusión';
$Definition['%s discussion html'] = '%s discusión ';
$Definition['%s discussions'] = '%s discusiones';
$Definition['%s discussions html'] = '%s discusiones ';
$Definition['%s has been Jailed.'] = '%s ha estado en la cárcel.';
$Definition['%s has left this conversation.'] = '%s ha dejado a esta conversación.';
$Definition['%s hour'] = '%s hora';
$Definition['%s hours'] = '%s horas';
$Definition['%s Insightfuls'] = '%s Perspicaces';
$Definition['%s level deep'] = '%s profundiad de nivel';
$Definition['%s levels deep'] = '%s profunidad de niveles';
$Definition['%s Likes'] = '%s Me gusta';
$Definition['%s LOLs'] = '%s jaja';
$Definition['%s member'] = '%s miembro';
$Definition['%s members'] = '%s miembros';
$Definition['%s mentioned %s in a %s.'] = '%s mencionado %s en un %s.';
$Definition['%s message'] = '%s mensaje';
$Definition['%s messages'] = '%s mensajes ';
$Definition['%s minute'] = '%s minuto';
$Definition['%s minutes'] = '%s minutos';
$Definition['%s month'] = '%s meses';
$Definition['%s months'] = '%s meses';
$Definition['%s New'] = '%s Nuevo';
$Definition['%s new'] = '%s nuevo';
$Definition['%s new comment since you last read this.'] = '%s nuevos comentarios desde la ultima vez que leiste esto.';
$Definition['%s new comments since you last read this.'] = '%s nuevos comentarios desde la ultima vez que leiste esto.';
$Definition['%s New Plural'] = '%s Nuevos';
$Definition['%s new plural'] = '%s nuevo';
$Definition['%s Not Found'] = '%s No Encontrado';
$Definition['%s not found.'] = '%s no encontrado.';
$Definition['%s Point'] = '%s punto';
$Definition['%s point'] = '%s punto';
$Definition['%s Points'] = '%s puntos';
$Definition['%s points'] = '%s puntos';
$Definition['%s result'] = '%s resultado';
$Definition['%s results'] = '%s resultados';
$Definition['%s said'] = '%s dijo';
$Definition['%s said:'] = '%s dijo:';
$Definition['%s tag(s) found.'] = '%s tag(s) encontrados.';
$Definition['%s tags in the system'] = '%s tags en el sistema';
$Definition['%s Up Votes'] = '%s Votos a favor';
$Definition['%s view'] = '%s vista';
$Definition['%s view html'] = '%s vista';
$Definition['%s viewing'] = '%s viendo';
$Definition['%s views'] = '%s vistas';
$Definition['%s views html'] = '%s vistas';
$Definition['%s votes'] = '%s votos';
$Definition['%s was removed from the %s and added to the %s'] = '%s fue eliminado del %s y agregado al %s';
$Definition['%s week'] = '%s semana';
$Definition['%s weeks'] = '%s semanas';
$Definition['%s year'] = '%s año';
$Definition['%s years'] = '%s años';

$Definition['(All)'] = '(Todos)';
$Definition['(empty message)'] = '(mensaje vacío)';

$Definition['+%s Guests'] = '+%s Invitados';

$Definition[' - Page %s'] = ' - Página %s';

$Definition['1 message'] = '1 mensaje';

$Definition['<General Error>'] = '<Error General>';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Miembro aprobado';
$Definition['[%s] Welcome Aboard!'] = '[%s] ¡Bienvenido a bordo!';
$Definition['[Deleted User]'] = '[Usuario Eliminado]';

$Definition['About'] = 'Acerca de';
$Definition['AboutToDelete'] = 'Estás a punto de suprimir %s.';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Estás a punto de borrar %1$s de las %2$s discusiones seleccionadas.';
$Definition['Abuse'] = 'Abuso';
$Definition['Accept'] = 'Aceptar';
$Definition['Accept this answer.'] = 'Aceptar esta respuesta';
$Definition['Account Options'] = 'Opciones de cuenta';
$Definition['Activate'] = 'Activar';
$Definition['Active'] = 'Activo';
$Definition['Active Users'] = 'Usuarios activos';
$Definition['Activity'] = 'Actividad';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s aceptado %4$s %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s comentó en tu %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s comentó en tu %8$s.';
$Definition['Activity.Comment'] = 'Comentar';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s mencionó %3$s en un %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s mencionó %3$s en un %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s the ha enviado un %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s the ha enviado un %8$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s se registró.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s se registró.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s cambió %6$s foto de perfil.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s cambió %6$s foto de perfil.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s respondido %4$s %8$s.';
$Definition['Add'] = 'Añadir';
$Definition['Add %s'] = 'Añadir %s';
$Definition['Add a Comment'] = 'Añadir un Comentario';
$Definition['Add a Message'] = 'Agregar un Mensaje ';
$Definition['Add another poll option ...'] = 'Añadir otra opción a la encuesta';
$Definition['Add a Profile Picture'] = 'Añadir Imagen de Perfil';
$Definition['Add a time?'] = '¿Añadir un momento?';
$Definition['Add a Warning'] = 'Añadir Alerta';
$Definition['Add Badge'] = 'Añadir Medalla';
$Definition['Add Comment'] = 'Añadir Comentario';
$Definition['Add Cost'] = 'Añadir costo';
$Definition['Add Image'] = 'Añadir Imagen';
$Definition['Add Message'] = 'Añadir Mensaje';
$Definition['Add Note'] = 'Añadir nota';
$Definition['Add People to this Conversation'] = 'Añadir gente a esta Conversación';
$Definition['Add Route'] = 'Añadir Ruta';
$Definition['Admin'] = 'Administrador';
$Definition['Administrator'] = 'Administrador';
$Definition['Administrator Activity'] = 'Administrador de Actividad';
$Definition['administrators'] = 'administradores';
$Definition['Advanced Stuff'] = 'Cosas Avanzadas ';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Un error grave ocurrió mientras se procesaba esta petición.<br />El servidor devolvió la siguiente respuesta: %s';
$Definition['Agree'] = 'De acuerdo';
$Definition['Alert'] = 'Alerta';
$Definition['Align center'] = 'Centrar';
$Definition['Align left'] = 'Alinear a la izquierda';
$Definition['Align right'] = 'Alinear a la derecha';
$Definition['All %s'] = 'Todo %s';
$Definition['All %s...'] = 'Todos %s...';
$Definition['All Bookmarks'] = 'Todos los Marcadores';
$Definition['All Categories'] = 'Categorías';
$Definition['all categories'] = 'todas las categorías';
$Definition['All Conversations'] = 'Todas las Conversaciones';
$Definition['All Discussions'] = 'Todas las Discusiones';
$Definition['All Events'] = 'Todos los eventos';
$Definition['All Members'] = 'Todos los miembros';
$Definition['All members'] = 'Todos los miembros';
$Definition['Allow'] = 'Permitir';
$Definition['Allow other members to see your email?'] = '¿Permitir a otros miembros ver tu email?';
$Definition['All Time Leaders'] = 'Lideres de tiempo completo';
$Definition['Already Warned'] = 'Ya advertido';
$Definition['Ancient Membership'] = 'Membresia antigua';
$Definition['An invitation has already been sent to the email you entered.'] = 'Una invitación ha sido enviada al email que escribiste ';
$Definition['Announce'] = 'Anunciar';
$Definition['Announce...'] = 'Anuncio...';
$Definition['Announcement'] = 'Anuncio';
$Definition['Announcements'] = 'Anuncios';
$Definition['Announce this discussion'] = 'Anunciar esta discusión';
$Definition['Answer'] = 'Responde';
$Definition['answer'] = 'respuesta';
$Definition['Answers'] = 'Respuestas';
$Definition['answers'] = 'respuestas';
$Definition['Applicant'] = 'Solicitante';
$Definition['Applicants'] = 'Solicitantes';
$Definition['Applicants & Invitations'] = 'Solicitantes & Invitaciones';
$Definition['Apply Changes'] = 'Aplicar Cambios';
$Definition['Apply for Membership'] = 'Registrarse';
$Definition['Apply for membership'] = 'Solicitar la participación en';
$Definition['Approve'] = 'Aprobar';
$Definition['Approve Applicant'] = 'Aprobar';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = '¿Estas ABSOLUTAMENTE seguro que quieres realizar esta acción?';
$Definition['Are you attending this event?'] = '¿Está asistiendo a este evento?';
$Definition['Are you sure you want to delete this %s?'] = '¿Estás seguro que quieres eliminar esto %s?';
$Definition['Are you sure you want to do that?'] = '¿Estás seguro de que quieres hacerlo?';
$Definition['Are you sure you want to do this?'] = '¿Seguro que quieres hacer esto?';
$Definition['Are you sure you want to join this group?'] = '¿Estás seguro de querer unirte a este grupo?';
$Definition['Are you sure you want to leave this group?'] = '¿Estás seguro de querer dejar el grupo?';
$Definition['Are you sure you wish to continue?'] = '¿Seguro que deseas continuar?';
$Definition['Ask a Question'] = 'Pregunta';
$Definition['Ask Question'] = 'Enviar Discusión';
$Definition['Attach a file'] = 'Adjuntar archivo';
$Definition['Attach image/file'] = 'Adjuntar imagen/archivo';
$Definition['Attachments'] = 'Adjuntos';
$Definition['Attach this warning to the %s.'] = 'Adjunta esta advertencia a %s.';
$Definition['AttemptingSignOut'] = 'Estás intentando desconectarte. ¿Estás seguro que quieres %s?';
$Definition['Attending'] = 'Asistir';
$Definition['Attending (%s)'] = 'Asistirán (%s)';
$Definition['Authenticate URL'] = 'Autenticidad del URL';
$Definition['Author'] = 'Autor';
$Definition['available'] = 'disponible';
$Definition['Awaiting Moderation'] = 'Esperando Moderación';
$Definition['Awesome'] = 'Grandioso';

$Definition['Back to Discussions'] = 'Volver a Discusiones';
$Definition['Back to Profile'] = 'Volver al Perfil';
$Definition['Badge'] = 'Medalla';
$Definition['Badge404'] = 'Medalla no encontrada.';
$Definition['Badges'] = 'Medallas';
$Definition['BadgesModuleTitle'] = 'Medallas';
$Definition['BadgesNobody'] = 'Nadie ha conseguido aún esta medalla.';
$Definition['Ban'] = 'Bloquear';
$Definition['Ban.Action'] = 'Expulsar';
$Definition['Banned'] = 'Baneado';
$Definition['Banned for being abusive.'] = 'Prohibido por ser abusiva.';
$Definition['Banned for spamming.'] = 'Prohibido para el envío de correo basura.';
$Definition['Banned users can no longer access the site.'] = 'Los usuarios bloqueados ya no pueden acceder al sitio. ';
$Definition['Banner'] = 'Cartel';
$Definition['Ban User'] = 'Ban usuario';
$Definition['Ban Value'] = 'Valor del bloqueo';
$Definition['Best Answer'] = 'Mejor respuesta';
$Definition['Best Answers'] = 'Mejores respuestas';
$Definition['Best Of'] = 'Mejor De';
$Definition['Best Of...'] = 'Lo Mejor de...';
$Definition['Blank Discussion Topic'] = 'Vacío';
$Definition['Blank Message'] = 'Mensaje en blanco';
$Definition['Body'] = 'Cuerpo';
$Definition['Bold'] = 'Negrita';
$Definition['Bookmark'] = 'Marcador';
$Definition['bookmarked discussion'] = 'discusión marcada';
$Definition['Bookmarked Discussions'] = 'Discusiones Marcadas';
$Definition['Bookmarks'] = 'Marcadores';
$Definition['bookmarks'] = 'favoritos';
$Definition['Browse Groups'] = 'Buscar en los grupos';
$Definition['Browse popular groups.'] = 'Buscar grupos conocidos.';
$Definition['By'] = 'Por';
$Definition['by'] = 'por';
$Definition['by Date'] = 'por Fecha';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Al subir el archivo certificas que tienes los derechos para distribuir la imagen y a su vez no viola los Términos de Servicio.';

$Definition['Cancel'] = 'Cancelar';
$Definition['Casual'] = 'Informal';
$Definition['Categories'] = 'Categorías';
$Definition['CategoriesShowFollowed'] = 'Solo mostrar categorías seguidas';
$Definition['CategoriesShowUnfollowed'] = 'Mostrar categorías ocultas';
$Definition['CategoriesViewingAll'] = 'Estas viendo todas las categorías. ';
$Definition['CategoriesViewingFollowed'] = 'Actualmente estas viendo las categorías que sigues ';
$Definition['Category'] = 'Categoría';
$Definition['Category Filter'] = 'Filtro de categorías';
$Definition['CategoryID'] = 'Categoría';
$Definition['Category Management'] = 'Gestión de Categorías';
$Definition['Category Notifications'] = 'Notificaciones Categoría';
$Definition['Category to Use'] = 'Categoría a usar ';
$Definition['Change'] = 'Cambiar';
$Definition['Change language'] = 'Cambiar idioma';
$Definition['Change My Password'] = 'Cambiar mi Contraseña';
$Definition['Change My Picture'] = 'Cambiar mi Fotografía';
$Definition['Change Password'] = 'Cambiar Contraseña';
$Definition['Change Picture'] = 'Cambiar Fotografía';
$Definition['Check all roles that apply to this user:'] = 'Revisar todos los roles que se le aplican a este usuario:';
$Definition['Child Categories'] = 'Sub-categorías';
$Definition['Child Categories:'] = 'Sub-categorías';
$Definition['Choose a name to identify yourself on the site.'] = 'Elige un nombre para identificarte en el sitio';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Elige la discusión principal en la cual todos los comentarios serán unidos:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Elige si quieres preguntar algo o iniciar una discusión ';
$Definition['Clear'] = 'Limpiar';
$Definition['clear'] = 'limpiar';
$Definition['Clear Conversation History'] = 'Limpiar Historial de Conversación';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Clic <a href="%s">here</a> para regresar a la discusión. ';
$Definition['Click accept or reject beside an answer.'] = 'Pulsar aceptar o rechazar a lado de la respuesta';
$Definition['clicking here'] = 'Dar click aquí';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Pulsar el %s a lado del tema para marcarlo.';
$Definition['Click to re-attach'] = 'Pincha para volver a adjuntar';
$Definition['Close'] = 'Cerrar';
$Definition['Closed'] = 'Cerrado';
$Definition['Close this discussion'] = 'Cerrar esta discusión ';
$Definition['Combo Breaker'] = 'Combo breaker';
$Definition['Comment'] = 'Comentario';
$Definition['comment'] = 'comentario';
$Definition['Comment As ...'] = 'Comentar como...';
$Definition['Comment by %s'] = 'Comentario por %s';
$Definition['Comment in'] = 'en';
$Definition['Commenting as %1$s (%2$s)'] = 'Comentando como %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'No está permitido comentar.';
$Definition['Comments'] = 'Comentarios';
$Definition['comments'] = 'comentarios';
$Definition['Comments are between {UserID,you}.'] = 'Los comentarios están entre {UserID,you}.';
$Definition['Community'] = 'Comunidad';
$Definition['Community Guidelines'] = 'Manual de la comunidad';
$Definition['Completely delete the warning.'] = 'Eliminada completamente la advertencia. ';
$Definition['Confirm'] = 'Confirmar';
$Definition['Confirmed email address'] = 'Correo electrónico confirmado';
$Definition['Confirm Email'] = 'Confirmar Email';
$Definition['Confirm Password'] = 'Confirmar Contraseña';
$Definition['Connect'] = 'Conectar';
$Definition['ConnectAccountExists'] = 'Ya tienes una cuenta aquí. ';
$Definition['ConnectChooseName'] = 'Elige un nombre para identificarte en el sitio ';
$Definition['ConnectCreateAccount'] = 'Añadir Info &amp; Crear Cuenta';
$Definition['Connected'] = 'Conectado';
$Definition['ConnectExistingPassword'] = 'Introduce to contraseña de cuenta.';
$Definition['Connecting...'] = 'Conectando...';
$Definition['Connection'] = 'Conexión ';
$Definition['ConnectLeaveBlank'] = 'Dejar en blanco a menos que se conecte a una cuenta existente.';
$Definition['ConnectName'] = 'Nombre Usuario';
$Definition['ConnectRegisteredName'] = 'Registraste el nombre de usuario: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Conecta tu perfil a las redes sociales para que se te notifique de la actividad de este lugar y para compartir lo que haces con amigos y seguidores.';
$Definition['Contact Us'] = 'Contacte con nosotros';
$Definition['conversation'] = 'conversación';
$Definition['Core'] = 'Núcleo';
$Definition['Created'] = 'Creado';
$Definition['Create Discussions'] = 'Crear Discusiones ';
$Definition['Create One.'] = 'Créate una cuenta.';
$Definition['Current'] = 'Actual';
$Definition['Currently: '] = 'Actualmente: ';
$Definition['Custom Information'] = 'Información Personalizada ';
$Definition['Customize'] = 'Personalizar ';
$Definition['customize your profile now'] = 'Personalizar tu perfil ahora';
$Definition['Customize your Public Profile'] = 'Personaliza tu Perfil Público';
$Definition['Custom Profile Fields'] = 'Campos personalizados del perfil';
$Definition['Custom Profile Field Settings'] = 'Configuración personalizada del perfil ';

$Definition['Dashboard'] = 'Panel';
$Definition['Dashboard Home'] = 'Panel de Inicio';
$Definition['Dashboard Summaries'] = 'Resumen del panel';
$Definition['Date'] = 'Fecha';
$Definition['Date.DefaultDateTimeFormat'] = '%B %e, %Y %l:%M%p';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Date. Expects \'mm/dd/yyyy\'.'] = 'Fecha. Espera \'mm / dd / aaaa\'.';
$Definition['Date Added'] = 'Fecha Agregada';
$Definition['Date Examples'] = 'Ejemplos: lunes, hoy, la semana pasada, Mar 26, 26/3/04';
$Definition['Date within'] = 'Fecha en';
$Definition['days'] = 'días';
$Definition['Define Thumbnail'] = 'Haz clic y arrastra la imagen para definir la miniatura.';
$Definition['Delete'] = 'Borrar';
$Definition['Delete %s'] = 'Eliminar %s';
$Definition['Delete Account'] = 'Eliminar Cuenta';
$Definition['Delete Conversation'] = 'Eliminar Conversación';
$Definition['Delete Discussion'] = 'Eliminar Discusión';
$Definition['Delete Group'] = 'Borrar Grupo';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Eliminar al usuario y todo su contenido. Esto causara discusiones fuera de control, apareciendo como si personas estuvieran respondiendo a un contenido que no existe. Esta es una buena opción para remover spam.';
$Definition['Delete User Content'] = 'Eliminar el contenido del usuario';
$Definition['Delete User Forever'] = 'Eliminar Usuario para siempre';
$Definition['Deny'] = 'Denegar';
$Definition['Deny Applicant'] = 'Denegar';
$Definition['Did this answer the question?'] = '¿Estos respondió la pregunta?';
$Definition['Disagree'] = 'Desacuerdo ';
$Definition['Discussion'] = 'Discusión';
$Definition['discussion'] = 'discusión';
$Definition['Discussion Board'] = 'Tablón de discusión';
$Definition['Discussions'] = 'Discusiones';
$Definition['discussions'] = 'discusiones';
$Definition['Discussions Page'] = 'Pagina de discusión';
$Definition['Discussion Title'] = 'Título de la Discusión';
$Definition['Dislike'] = 'No me gusta';
$Definition['Dismiss'] = 'Descartar';
$Definition['Documentation'] = 'Documentación';
$Definition['Don\'t announce.'] = 'No anunciar';
$Definition['Don\'t fold quotes'] = 'No archive citas';
$Definition['Don\'t have an account? %s'] = '¿No tienes cuenta? %s';
$Definition['Download'] = 'Descarga';
$Definition['Download the sounds as MP3'] = 'Descarga los sonidos como MP3';
$Definition['Do you want to expire or delete this warning?'] = '¿Quieres expirar o eliminar esta advertencia? ';
$Definition['Draft saved at %s'] = 'Borrador guardado en %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Arrastra y cambia el tamaño del cuadrado sobre la foto para definir tu icono thumbnail.';
$Definition['Drop image/file'] = 'Deposita imagen o archivo';

$Definition['Earned'] = 'Ganado';
$Definition['Edit'] = 'Editar';
$Definition['Edit %s'] = 'Editar %s';
$Definition['Edit Account'] = 'Editar Cuenta';
$Definition['Edit Comment'] = 'Editar Comentario';
$Definition['Edit Discussion'] = 'Editar Discusión';
$Definition['edited %s'] = 'editado %s';
$Definition['Edited %s by %s.'] = 'Editado %s por %s.';
$Definition['Edit My Account'] = 'Editar mi Cuenta';
$Definition['Edit My Profile'] = 'Editar mi Perfil';
$Definition['Edit My Thumbnail'] = 'Editar mi Thumbnail';
$Definition['editor.BBCodeHelpText'] = 'Puedes usar <a href="http://en.wikipedia.org/wiki/BBCode" target="_new">BBCode</a> en tu mensaje.';
$Definition['editor.HtmlHelpText'] = 'Puedes usar <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple Html</a> en tu menaje';
$Definition['editor.MarkdownHelpText'] = 'Puedes usar <a href="https://es.wikipedia.org/wiki/Markdown" target="_new">Rebajas</a> en tu mensaje.';
$Definition['editor.TextHelpText'] = 'Estás usando texto plano en el mensaje';
$Definition['editor.WysiwygHelpText'] = 'Estás usando <a href="https://en.wikipedia.org/wiki/WYSIWYG" target="_new">Wysiwyg</a> en tu mensaje.';
$Definition['Edit Preferences'] = 'Editar Preferencias';
$Definition['Edit Profile'] = 'Editar Perfil';
$Definition['Edit Tag'] = 'Editar Etiqueta';
$Definition['Edit Thumbnail'] = 'Editar Thumbnail';
$Definition['Eighth Anniversary'] = 'Octavo Aniversario ';
$Definition['Email'] = 'Correo Electrónico';
$Definition['Email/Username'] = 'Email/Nombre de usuario';
$Definition['EmailConfirmEmail'] = 'Necesitas confirmar tu dirección de email antes de poder continuar. Por favor confirma tu dirección de email dando clic en el siguiente enlace: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '¡Que tengas un buen día!';
$Definition['EmailHeader'] = '¡Hola {User.Name}!
';
$Definition['EmailInvitation'] = '¡Hola!

%1$s te ha invitado a unirte a %2$s. Si quieres, puedes hacerlo pinchando en el siguiente enlace:

  %3$s

¡Qué tengas un buen día!';
$Definition['EmailMembershipApproved'] = 'Hola %1$s,

Has sido aprobado como miembro. Conéctate ahora con el siguiente enlace:

  %2$s
  
¡Qué tengas un buen día!';
$Definition['EmailNotification'] = '%1$s

Sigue el enlace de abajo para echarle un vistazo:
%2$s

¡Qué tengas un buen día!';
$Definition['Email Notifications'] = 'Notificaciones por Email';
$Definition['Email Or Username'] = 'Correo o Usuario';
$Definition['EmailPassword'] = 'Hola %1$s,

%2$s ha reseteado tu contraseña en %3$s. Ahora tus credenciales de acceso son:

  Correo electrónico: %6$s
  Contraseña: %5$s
  Url: %4$s

¡Qué tengas un buen día!';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Los correos electrónicos enviados desde la aplicación serán enviados con el Nombre y Dirección siguientes';
$Definition['Email Source'] = 'Correo Electrónico';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Sigue el enlace de abajo para echarle un vistazo:
%2$s

¡Qué tengas un buen día!';
$Definition['Email Unavailable'] = 'Email No Disponible';
$Definition['Email visible to other users'] = 'Email visible para otros usuarios';
$Definition['EmailWelcome'] = 'Hola %1$s,

%2$s ha creado una cuenta para ti en %3$s. Tus credenciales de acceso son:

  Correo electrónico: %6$s
  Contraseña: %5$s
  Url: %4$s

¡Qué tengas un buen día!';
$Definition['EmailWelcomeConnect'] = 'Hola {User.Name},

Te has conectado exitosamente a {Title}. Aquí están tus datos de acceso:

  Nombre de usuario: {User.Name}
  Conectado con: {ProviderName}

Puedes acceder al sitio en {/,url,domain}.

¡Qué tengas un buen día!';
$Definition['EmailWelcomeRegister'] = 'Hola {User.Name},

Has registrado una cuenta en {Title}. Aquí están tus datos de acceso:

  Nombre de Usuario: {User.Name}
  Correo electrónico: {User.Email}

Puedes acceder al sitio en {/,url,domain}.

¡Qué tengas un buen día!';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Lee la historia completa aquí</a></p><div class="ClearFix"></div></div>';
$Definition['EmbeddedNoBodyFormat'] = '{Url}';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Lee la historia completa aquí</a></p><div class="ClearFix"></div></div>';
$Definition['Emoji'] = 'Texto ininteligible';
$Definition['End time?'] = '¿Fin del tiempo?';
$Definition['English'] = 'Inglés';
$Definition['Enter your Email address'] = 'Introduce tu dirección de correo electrónico';
$Definition['Enter your email address'] = 'Ingresa tu dirección de email';
$Definition['Enter your Email address or username'] = 'Ingresa tu correo electrónico o nombre de usuario';
$Definition['Enter Your OpenID Url'] = 'Ingresa tu url de OpenID';
$Definition['Erase User Content'] = 'Eliminar el contenido del usuario ';
$Definition['ErrorBadInvitationCode'] = 'El código de invitación que ingresaste no es válido. ';
$Definition['ErrorCredentials'] = 'Lo siento, no existe ninguna cuenta relacionada con el correo electrónico y la contraseña que ingresaste.';
$Definition['ErrorPermission'] = 'Lo siento, permiso denegado.';
$Definition['ErrorPluginDisableRequired'] = 'No puedes des-habilitar el plugin {0}  ya que el plugin {1} lo requiere para su función.';
$Definition['ErrorPluginEnableRequired'] = 'Este plugin requiere que el plugin {0} este habilitado antes de que se habilite por si solo.';
$Definition['ErrorPluginVersionMatch'] = 'El plugin {0} habilitado (version {1}) no cumplió con los requisitos de la version ({2}).';
$Definition['ErrorRecordNotFound'] = 'No se pudo encontrar el registro solicitado.';
$Definition['ErrorTermsOfService'] = 'Debes aceptar los términos de servicio.';
$Definition['Event'] = 'Evento';
$Definition['Event Details'] = 'Detalles del evento';
$Definition['Events'] = 'Eventos';
$Definition['everyone'] = 'todos';
$Definition['Everything'] = 'Todo';
$Definition['Expired'] = 'Expirado';
$Definition['Expires'] = 'Expira';

$Definition['Failed to delete group.'] = 'Fallo al borrar el grupo.';
$Definition['Failed to find discussion for commenting.'] = 'Error en encontrar el tema por comentario.';
$Definition['Failed to load the poll.'] = 'Error al cargar la encuesta ';
$Definition['Feedback'] = 'Retroalimentación';
$Definition['Female'] = 'Mujer';
$Definition['Fifth Anniversary'] = 'Quinto Aniversario ';
$Definition['FileName'] = 'Nombre de archivo';
$Definition['Filename'] = 'Nombre de archivo';
$Definition['FileSize'] = 'Tamaño de archivo';
$Definition['File Size'] = 'Tamaño de archivo';
$Definition['First Anniversary'] = 'Primer Aniversario ';
$Definition['First Comment'] = 'Primer Comentario';
$Definition['Flag'] = 'Reportar';
$Definition['Folder'] = 'carpeta';
$Definition['Folders'] = 'Carpetas';
$Definition['Follow'] = 'Seguir';
$Definition['Follow %s'] = 'Seguir %s';
$Definition['Followed by %d people'] = 'Seguido por %d personas';
$Definition['Followed by %d person'] = 'Seguido por %d personas';
$Definition['followed categories'] = 'categorías que sigo';
$Definition['Following %d people'] = 'Siguiendo %d personas';
$Definition['Following %d person'] = 'Siguiendo a %d';
$Definition['FollowOnly'] = 'Accede al vínculo siguiente para verlo:';
$Definition['Follows'] = 'Seguidores';
$Definition['Forgot?'] = '¿La olvidaste?';
$Definition['Forgot your password?'] = '¿Olvidaste tu contraseña?';
$Definition['Format'] = 'Formato';
$Definition['Format his'] = 'su';
$Definition['Format their'] = 'sus';
$Definition['Format You'] = 'Tú';
$Definition['Format you'] = 'tú';
$Definition['Format Your'] = 'tus';
$Definition['Forum'] = 'Foro';
$Definition['Forums'] = 'Foro';
$Definition['Forum Signature Settings'] = 'Configurar firma del foro';
$Definition['Fourth Anniversary'] = 'Cuarto Aniversario ';
$Definition['Friends'] = 'Amigos';
$Definition['From'] = 'Desde';
$Definition['Full Site'] = 'Sitio completo';

$Definition['Garden.Email.SupportAddress'] = 'Email de soporte';
$Definition['Garden.Email.SupportName'] = 'Nombre de apoyo';
$Definition['Garden.Registration.DefaultRoles'] = 'Papel por defecto';
$Definition['Garden.Title'] = 'Título del Banner';
$Definition['Gender'] = 'Género';
$Definition['Generate import SQL only'] = 'Generar sólo importación de SQL';
$Definition['Generate Password'] = 'Generar clave';
$Definition['Get an audio challenge'] = 'Acepta un desafío de audio';
$Definition['Get a new challenge'] = 'Acepta un nuevo desafío';
$Definition['Get a visual challenge'] = 'Acepta un desafío visual';
$Definition['Give'] = 'Dar';
$Definition['Give a Badge to %s'] = 'Dar una medalla a %s';
$Definition['Give Badge'] = 'Dar Insignia';
$Definition['Given'] = 'Dados';
$Definition['Go'] = 'Ir';
$Definition['Group'] = 'Grupo';
$Definition['group'] = 'grupo';
$Definition['GroupEmptyAnnouncements'] = 'Habrá cosas importantes aquí un día';
$Definition['GroupEmptyDiscussions'] = 'Extremadamente tranquilo aquí, ¿verdad?';
$Definition['GroupEmptyEvents'] = 'Ay no, no hay próximos eventos.';
$Definition['Group Info'] = 'Información de grupo';
$Definition['Group Leaders'] = 'Líderes de grupo';
$Definition['Group Members'] = 'Miembros del Grupo';
$Definition['GroupMembersEmpty'] = 'Todavía nadie se ha unido ¡Extiende la palabra!';
$Definition['Group Options'] = 'Opciones de grupo';
$Definition['Groups'] = 'Grupos';
$Definition['groups'] = 'grupos';
$Definition['Guest'] = 'Invitado';
$Definition['GuestModule.Message'] = 'Pareces nuevo por aquí. Si quieres participar, ¡pulsa uno de estos botones!';

$Definition['Hang on a sec while we sign you out.'] = 'Espera unos segundos mientras que te desconectas. ';
$Definition['he'] = 'El';
$Definition['Heading'] = 'Título';
$Definition['Heading %s'] = 'Encabezado %s';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} adquirido la <a href="{Url,html}">{Data.Name,text}</a> insignia.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} bloqueado {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} ha comentado en <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} te mencionó en <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} cambió la foto de perfil por
 {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} ingresado.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} desbloqueado {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} advirtió a {RegardingUserID,you}.';
$Definition['Help'] = 'Ayuda';
$Definition['her'] = 'su';
$Definition['Hide'] = 'Ocultar';
$Definition['Hide my online status from other members'] = 'Ocultar mi estado online a otros miembros';
$Definition['Hide signatures?'] = '¿Firmas Ocultas?';
$Definition['Hide signatures always'] = 'siempre ocultar firmas';
$Definition['Hide signatures on my mobile device'] = 'ocultar firmas en mi dispositivo móvil';
$Definition['his'] = 'su';
$Definition['Home'] = 'Inicio';
$Definition['hours'] = 'horas';
$Definition['Howdy, Stranger!'] = '¡Hola Forastero!';
$Definition['How long do you want this warning to last?'] = '¿Cuánto tiempo quiere que dure este aviso?';
$Definition['How many levels deep should we start folding up quote trees?'] = '¿En cuantos niveles de profundidad deberíamos empezar a archivar los árboles de citas?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Estoy de acuerdo con <a id="TermsOfService" class="Popup" target="terms" href="%s">los términos de servicio</a>';
$Definition['Icon'] = 'Icono';
$Definition['Ignore'] = 'Ignorar';
$Definition['Ignore List'] = 'Lista de ignorados';
$Definition['Ignore Someone'] = 'Ignorar a alguien';
$Definition['Image'] = 'Imagen';
$Definition['images'] = 'Imágenes';
$Definition['Images not allowed'] = 'Imágenes no permitidas';
$Definition['Image URL'] = 'URL de imagen';
$Definition['in'] = 'en';
$Definition['In <b>%s.</b>'] = 'En <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'En <b>%s</b> y discusiones recientes. ';
$Definition['Inbox'] = 'Bandeja de Entrada';
$Definition['Incorrect. Try again.'] = 'Incorrecto. Inténtalo de nuevo.';
$Definition['Indent'] = 'Sangría';
$Definition['In recent discussions.'] = 'En discusiones recientes.';
$Definition['In seconds'] = 'En segundos';
$Definition['Insert Image'] = 'Insertar imagen';
$Definition['Insightful'] = 'Perspicaz';
$Definition['Internal'] = 'Interno';
$Definition['In this Conversation'] = 'En esta Conversación';
$Definition['Invalid password.'] = 'La contraseña que ingresaste es incorrecta. Recuerda que las contraseñas son sensibles a las mayúsculas y minúsculas.';
$Definition['Invitations'] = 'Invitaciones ';
$Definition['Invite'] = 'Invitar';
$Definition['InviteErrorPermission'] = 'Lo siento, permiso denegado.';
$Definition['Invite Friends'] = 'Invitar a amigos';
$Definition['Invite friends'] = 'Invitar a amigos';
$Definition['Invite one or more people to join this group.'] = 'Invite a una o más personas a unirse a este grupo.';
$Definition['IPAddress'] = 'Dirección IP';
$Definition['IP Address'] = 'Dirección IP ';
$Definition['I remember now!'] = '¡Acabo de recordarla!';
$Definition['Italic'] = 'Inclinado';
$Definition['Item'] = 'Articulo';
$Definition['item'] = 'artículo';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Pareces nuevo por aquí. Si quieres participar, ¡pulsa uno de estos botones!';

$Definition['Jail'] = 'Cárcel ';
$Definition['Jailed users have reduced abilities.'] = 'Los usuarios encarcelados tiene habilidades reducidas.';
$Definition['Join %s'] = 'Unirse %s';
$Definition['Joined'] = 'Registrado el';
$Definition['Joined %s'] = 'Unido %s';
$Definition['Join this Group'] = 'Únete a este Grupo';
$Definition['Join this group to view its content.'] = 'Únete a este grupo para ver su contenido.';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Solo eliminar el registro del usuario y mantén el contenido del usuario';
$Definition['Just expire the warning.'] = 'Acaba de expirar la advertencia';
$Definition['Just you!'] = '¡Solo tu! ';

$Definition['Keep me signed in'] = 'Mantenerme conectado';
$Definition['Keep User Content'] = 'Mantén el contenido del usuario';

$Definition['Label'] = 'Etiqueta';
$Definition['Last Active'] = 'Último Activo';
$Definition['Last IP'] = 'Última IP';
$Definition['lasts %s'] = 'dura %s';
$Definition['Latest %1$s'] = 'Últimos %1$s';
$Definition['Latest Post'] = 'Últimas Publicaciones ';
$Definition['Leaders'] = 'Líderes';
$Definition['Leave %s'] = 'Abandonar %s';
$Definition['Leave a Comment'] = 'Deja un comentario';
$Definition['Leave a comment'] = 'Deja un comentario';
$Definition['Leave a redirect link.'] = 'Deja un vínculo para redireccionar.';
$Definition['Leave blank unless connecting to an exising account.'] = 'Dejar en blanco a menos que se conecte a una cuenta existente.';
$Definition['Leave Comments'] = 'Deja Comentarios';
$Definition['Leave Group'] = 'Dejar Grupo';
$Definition['Length'] = 'Longitud';
$Definition['Level %s'] = 'Nivel %s';
$Definition['Like'] = 'Me gusta';
$Definition['Link to content:'] = 'Ligar al contenido:';
$Definition['Locale'] = 'Lugar';
$Definition['Log'] = 'Registro';
$Definition['log'] = 'registro';
$Definition['Login with Facebook'] = 'Acceder con Facebook';
$Definition['LOL'] = 'jajaja';

$Definition['Major'] = 'Principal';
$Definition['Make me invisible? (Will not show you on the list)'] = '¿Ser invisible? (No aparecerás en la lista)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Hacer esta encuesta anónima (Los votos no se hacen públicos)';
$Definition['Male'] = 'Hombre';
$Definition['Mark All Viewed'] = 'Marcar todo como visto';
$Definition['Mark as Troll'] = 'Marcar como trol';
$Definition['Mark Category Viewed'] = 'Marcar Categoría Vista';
$Definition['Marking as spam cannot be undone.'] = 'Marcar algo como SPAM causará su eliminación para siempre. Eliminar es una buena forma de mantener limpio el foro';
$Definition['Mark Read'] = 'Marcar como leído ';
$Definition['Maybe'] = 'Quizás';
$Definition['Maybe (%s)'] = 'Quizás (%s)';
$Definition['Member Count'] = 'Miembros';
$Definition['Members'] = 'Miembros';
$Definition['Merge'] = 'Unir';
$Definition['Merge Discussions'] = 'Unir Discusiones';
$Definition['Message'] = 'Mensaje';
$Definition['message'] = 'mensaje';
$Definition['Messages'] = 'Mensajes';
$Definition['messages'] = 'mensajes';
$Definition['Message to User'] = 'Mensaje a usuario';
$Definition['Minor'] = 'Menor';
$Definition['minutes'] = 'minutos';
$Definition['Moderation'] = 'Moderación ';
$Definition['Moderation Queue'] = 'Cola de moderación';
$Definition['Moderator'] = 'Moderador';
$Definition['Moderator Activity'] = 'Actividad del moderador';
$Definition['Moderators'] = 'Moderadores ';
$Definition['moderators'] = 'moderadores';
$Definition['months'] = 'meses';
$Definition['More'] = 'Más';
$Definition['More About %s'] = 'Más sobre %s';
$Definition['More Comments'] = 'Más Comentarios';
$Definition['More Discussions'] = 'Más Discusiones ';
$Definition['More Information'] = 'Más Información';
$Definition['More Results'] = 'Más Resultados';
$Definition['More…'] = 'Más...';
$Definition['Most Recent'] = 'Más Recientes';
$Definition['Most recent:'] = 'Más recientes:';
$Definition['Most recent: %1$s by %2$s'] = 'Más reciente: %1$s por %2$s';
$Definition['Most recent by %1$s'] = 'Más reciente por %1$s';
$Definition['Most Recent Comment'] = 'Comentario más reciente';
$Definition['Move'] = 'Mover';
$Definition['MyBadgesModuleTitle'] = 'Mis Insignias ';
$Definition['My Bookmarks'] = 'Marcadores';
$Definition['My Discussions'] = 'Mis Discusiones';
$Definition['My Drafts'] = 'Mis Borradores';
$Definition['My Forums'] = 'Mis Foros';
$Definition['My Groups'] = 'Mis grupos';
$Definition['My Preferences'] = 'Editar mis Preferencias';
$Definition['My Signature'] = 'Mi firma';

$Definition['n/a'] = 'no disponible';
$Definition['Name'] = 'Nombre';
$Definition['Name Dropper'] = 'Cita de usuario';
$Definition['Name of the Event'] = 'Nombre del Evento';
$Definition['Name the Group'] = 'Nombre del grupo';
$Definition['Name Unavailable'] = 'Nombre no disponible';
$Definition['new'] = 'nuevo';
$Definition['New %s'] = 'Nuevo %s';
$Definition['New Announcement'] = 'Nuevo Anuncio';
$Definition['New Conversation'] = 'Iniciar Nueva Conversación';
$Definition['New Discussion'] = 'Nueva Discusión';
$Definition['new discussion'] = 'nuevo';
$Definition['New Event'] = 'Nuevo evento';
$Definition['New Group'] = 'Nuevo grupo';
$Definition['New Groups'] = 'Nuevos Grupos';
$Definition['New Message'] = 'Iniciar Nueva Conversación';
$Definition['New Password'] = 'Nueva Contraseña';
$Definition['New Poll'] = 'Nueva Encuesta';
$Definition['Next'] = 'Siguiente';
$Definition['Ninth Anniversary'] = 'Noveno Aniversario';
$Definition['NoBadgesEarned'] = 'Cualquier minuto ahora';
$Definition['No badges yet.'] = 'No Insignias todavía. ';
$Definition['Nobody has confirmed their attendance yet.'] = 'Nadie ha confirmado su presencia todavía.';
$Definition['Nobody has declined the invitation so far.'] = 'Nadie ha declinado la invitación hasta el momento.';
$Definition['Nobody is on the fence right now.'] = 'Nadie está en la cerca en estos momentos.';
$Definition['No default roles.'] = 'No hay roles predeterminados.';
$Definition['No discussions were found.'] = 'No se encontraron discusiones.';
$Definition['No items tagged with %s.'] = 'No items etiquetados con %s.';
$Definition['NoPermissionToDeleteDiscussions'] = 'No tienes permiso para borrar %1$s de las discusiones seleccionadas.';
$Definition['No results for \'%s\''] = 'No resultado para \'%s\'';
$Definition['No Roles'] = 'No hay funciones.';
$Definition['Not Attending (%s)'] = 'No asistirán (%s)';
$Definition['Not Authorized (401)'] = 'No autorizado (401)';
$Definition['Not Found (404)'] = 'No encontrado (404)';
$Definition['Notice'] = 'Aviso';
$Definition['Notification'] = 'Notificación';
$Definition['Notification Preferences'] = 'Notifación de preferencias';
$Definition['Notifications'] = 'Notificaciones';
$Definition['Notifictions'] = 'Notificciones';
$Definition['Notify'] = 'Notificar';
$Definition['Notify me of private messages.'] = 'Notificarme de mensajes privados.';
$Definition['Notify me when a badge is requested.'] = 'Notifíquenme cuando me pidan una medalla';
$Definition['Notify me when a comment is flagged.'] = 'Notifíquenme cuando un comentario sea reportado';
$Definition['Notify me when I am added to private conversations.'] = 'Notificarme cuando sea añadido a una conversación privada.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Notifícame cuando haya comentarios en discusiones en las que participé.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Notificarme cuando la gente comente mis discusiones Marcadas.';
$Definition['Notify me when people comment on my discussions.'] = 'Notificarme cuando la gente comente mis discusiones.';
$Definition['Notify me when people mention me.'] = 'Notifícame cuando alguien me mencione.';
$Definition['Notify me when people mention me in comments.'] = 'Notificarme cuando la gente me mencione en comentarios.';
$Definition['Notify me when people reply to my wall comments.'] = 'Notificarme cuando la gente conteste mis mensajes en el muro.';
$Definition['Notify me when people write on my wall.'] = 'Notificarme cuando la gente escriba en mi muro.';
$Definition['Notify me when there is event activity.'] = 'Notifícame cuando haya eventos en actividad.';
$Definition['Notify me when there is group activity.'] = 'Notifícame cuando haya actividad en el grupo.';
$Definition['Not much happening here, yet.'] = 'No esta pasando mucho aquí, aún.';
$Definition['Not Verified'] = 'No Verificado';

$Definition[' now.'] = 'ahora';

$Definition['Null Date'] = '-';

$Definition['of'] = 'de';
$Definition['Off Topic'] = 'Fuera de tema';
$Definition['OK'] = 'De acuerdo';
$Definition['Okay'] = 'Ok';
$Definition['OldPassword'] = 'Antigua contraseña';
$Definition['Old Password'] = 'Contraseña antigua';
$Definition['on'] = 'en';
$Definition['Online Preferences'] = 'Preferencias online';
$Definition['Only show followed categories'] = 'Solo mostrar categorías que sigo ';
$Definition['OpenID Settings'] = 'Configuración OpenID';
$Definition['Optional Description'] = 'Descripción Opcional';
$Definition['Options'] = 'Opciones';
$Definition['or'] = 'o';
$Definition['Ordered list'] = 'Lista ordenada';
$Definition['Organize discussion categories'] = 'Organizar las categorías de discusión';
$Definition['Organizer'] = 'Organizador';
$Definition['Organize your Categories'] = 'Organiza tus Categorías';
$Definition['Or you can...'] = 'O puedes...';
$Definition['Other Records'] = 'Otros registros ';
$Definition['Outdent'] = 'Quitar sangría';
$Definition['Owner'] = 'Propietario';

$Definition['PageDetailsMessage'] = '%1$s a %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s a %2$s de %3$s';
$Definition['Page Not Found'] = 'Página no encontrada';
$Definition['Participated'] = 'Participado';
$Definition['ParticipatedHomepageTitle'] = 'Discusiones en las que se participaron';
$Definition['Password'] = 'Contraseña';
$Definition['Password Contains Username'] = 'Contiene nombre de usuario';
$Definition['Password Good'] = 'Bien';
$Definition['Password Ok'] = 'Ok';
$Definition['PasswordRequest'] = 'Hola %1$s,

Alguien ha solicitado resetear tu contraseña en %2$s. Para resetearla, sigue este enlace:

  %3$s

Si tu no hiciste esta solicitud, ignora esta solicitud.';
$Definition['Passwords don\'t match'] = 'Las contraseñas no coinciden.';
$Definition['Password Strong'] = 'Fuerte';
$Definition['Password Too Short'] = 'Demasiado corto';
$Definition['Password Very Weak'] = 'Muy débil';
$Definition['Password Weak'] = 'Débil';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Pegar la URL de una imagen para incrustarla rápidamente.';
$Definition['Permalink'] = 'Enlace Permanente';
$Definition['permalink'] = 'enlace permanente';
$Definition['Permanent (301)'] = 'Permanente (301)';
$Definition['PermissionErrorMessage'] = 'No tienes permiso para hacer eso';
$Definition['PermissionErrorTitle'] = 'Problema de permisos';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Necesitas ser moderador para hacer eso.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Necesitas ser administrador para hacer eso.';
$Definition['PermissionRequired.Javascript'] = 'Necesitas habilitar javascript para hacer eso';
$Definition['Photogenic'] = 'Fotogénica';
$Definition['Picture'] = 'Imagen';
$Definition['Pinned'] = 'Prendido';
$Definition['Play the sound again'] = 'Reproduce el sonido de nuevo';
$Definition['Please join my group.'] = 'Por favor, únete a mi <a href="{Url,html}">grupo</a>.';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Por favor espera mientras te redireccionamos. Si no eres redireccionado, haz click <a href="%s">aquí</a>.';
$Definition['Points'] = 'Puntos ';
$Definition['Poll'] = 'Encuesta';
$Definition['Poll Options'] = 'Opciones de la encuesta';
$Definition['Poll Question'] = 'Pregunta de la encuesta';
$Definition['Popular Discussions'] = 'Discusiones Populares';
$Definition['Popular Groups'] = 'Los grupos más populares';
$Definition['Popular Tags'] = 'Tags Populares';
$Definition['Popup'] = 'Ventana ';
$Definition['Position'] = 'Posición';
$Definition['Post'] = 'Publicación ';
$Definition['post'] = 'entrada';
$Definition['Post Comment'] = 'Enviar Comentario';
$Definition['Post Discussion'] = 'Enviar Discusión';
$Definition['Post edited by %1$s at %2$s'] = 'Publicación editada por %1$s en %2$s ';
$Definition['Posts'] = 'Publicaciones';
$Definition['Posts.Plural: %s'] = 'Publicaciones: %s';
$Definition['Posts.Singular: %s'] = 'Publicaciones: %s';
$Definition['Posts: %s'] = 'Publicaciones: %s';
$Definition['Post this anonymously'] = 'Publicar esto anónimamente ';
$Definition['Powered by %s'] = 'Desarrollado por %s';
$Definition['Powered by Vanilla'] = 'Desarrollado por Vanilla';
$Definition['PreferenceBadgeEmail'] = 'Notificarme cuando obtenga una insignia.';
$Definition['PreferenceBadgePopup'] = 'Notificarme cuando obtenga una insignia.';
$Definition['Preview'] = 'Previsualizar';
$Definition['Previous'] = 'Anteriores ';
$Definition['Privacy'] = 'Privacidad';
$Definition['Privacy Settings'] = 'Configuración Privada ';
$Definition['Private'] = 'Privado';
$Definition['Private group.'] = 'Todos pueden ver el grupo pero solo los miembros pueden ver su contenido. Para unirse, se necesita registrarse o ser invitado.';
$Definition['Private Note for Moderators'] = 'Nota privada a los moderadores';
$Definition['Problem with credentials.'] = 'Problemas con credenciales.';
$Definition['Proceed'] = 'Proceder';
$Definition['Profile'] = 'Perfil';
$Definition['Profile Fields'] = 'Campos de Perfil ';
$Definition['Profile  Fields'] = 'Perfil  Campos';
$Definition['ProfileFieldsCustomDescription'] = 'Usa estos campos para personalizar la información del perfil. Puedes agregar cosas como "Estado Civil", "Skype" o "Tu Favorito Dinosaurio". ¡Se creativo!';
$Definition['Profile Page'] = 'Pagina de Perfil';
$Definition['Profile Picture'] = 'Fotografía del perfil';
$Definition['Profiles'] = 'Perfiles';
$Definition['Promote'] = 'Promocionar';
$Definition['Public'] = 'Público';
$Definition['Public group.'] = 'Todos pueden ver el grupo y su contenido. Todos pueden unirse.';

$Definition['Q&A'] = 'Preguntas y respuestas';
$Definition['Q&A Accepted'] = 'Respondida ✓';
$Definition['Q&A Answered'] = 'Respondida';
$Definition['Q&A Options'] = 'Opciones de preguntas y respuestas';
$Definition['Q&A Question'] = 'Pregunta';
$Definition['QnA Accepted Answer'] = 'Respuesta ✓';
$Definition['QnA Rejected Answer'] = 'Respuesta Rechazada ';
$Definition['Question'] = 'Pregunta';
$Definition['question'] = 'pregunta';
$Definition['Questions'] = 'Preguntas';
$Definition['questions'] = 'preguntas';
$Definition['Question Title'] = 'Título de la Discusión';
$Definition['Quote'] = 'Citar';
$Definition['Quote Folding'] = 'Desplegado de la cita';
$Definition['Quote on'] = 'en';
$Definition['Quote Settings'] = 'Opciones de citado';
$Definition['Quote wrote'] = 'escribió ';

$Definition['Rank'] = 'Clasificación';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were} promocionado a  {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = '¡Felicidades! Has sido promocionado a {Data.Name,plaintext}.';
$Definition['Re: %s'] = 'ref.: %s ';
$Definition['Reactions'] = 'Reacciones';
$Definition['Real Name'] = 'Nombre Real';
$Definition['Reason'] = 'Razón';
$Definition['Reason (optional)'] = 'Razón (opcional)';
$Definition['Recent'] = 'Reciente';
$Definition['Recent Activity'] = 'Actividad Reciente';
$Definition['Recent Admin Activity'] = 'Actividad Reciente del Administrador ';
$Definition['Recent Discussions'] = 'Conversaciones recientes';
$Definition['Recent Events'] = 'Eventos Recientes';
$Definition['recently'] = 'recientemente';
$Definition['Recent Moderator Activity'] = 'Actividad Reciente del Moderador ';
$Definition['Recent Tutorials'] = 'Recientes Tutoriales';
$Definition['Recipients'] = 'Destinatarios';
$Definition['RecipientUserID'] = 'Recipiente';
$Definition['Redirecting...'] = 'Redireccionando...';
$Definition['Refetch Page'] = 'Repondrá la página';
$Definition['Register'] = 'Registrarse';
$Definition['Register IP'] = 'Registrar IP';
$Definition['Register with %s'] = 'Registrarse';
$Definition['Registration  Fields'] = 'Registro  Campos';
$Definition['Registration URL'] = 'URL de regristro';
$Definition['Reject'] = 'Rechazar';
$Definition['Reject this answer.'] = 'Rechazar esta respuesta. ';
$Definition['Remember me'] = 'Recuérdame';
$Definition['Remember me on this computer'] = 'Recordarme en este ordenador';
$Definition['Remote Configuration'] = 'Configuración Remota ';
$Definition['Remove'] = 'Eliminar';
$Definition['Removed by'] = 'Eliminado por';
$Definition['Remove from %s'] = 'Eliminar desde %s';
$Definition['Remove Invitation'] = 'Eliminar invitación';
$Definition['Remove My Picture'] = 'Eliminar mi Fotografía';
$Definition['Remove Picture'] = 'Eliminar Fotografía';
$Definition['Remove Warning'] = 'Eliminar Advertencia ';
$Definition['Rename Forum'] = 'Renombrar Foro';
$Definition['Reopen'] = 'Reabrir';
$Definition['Replies'] = 'Respuestas';
$Definition['Reply'] = 'Responder';
$Definition['ReplyOnly'] = 'Para seguir, puedes contestar directamente a este e-mail. Enviado desde {/,exurl}.';
$Definition['ReplyOrFollow'] = 'Contesta este mensaje directamente o usa el siguiente enlace para verlo:';
$Definition['Report'] = 'Informe';
$Definition['Report %s'] = 'Informe %s';
$Definition['Reported by: '] = 'Reportado por:';
$Definition['Reported Posts'] = 'Envíos reportados';
$Definition['Report Notes'] = 'Notas';
$Definition['Report Reason'] = 'Razón';
$Definition['Request a new password'] = 'Solicitar una nueva contraseña';
$Definition['Request a new password →'] = 'Solicita una nueva contraseña →';
$Definition['Reset Password'] = 'Resetear Contraseña';
$Definition['Restored'] = 'Restaurado';
$Definition['reverse'] = 'inverso';
$Definition['Revoke'] = 'Rovocar';
$Definition['Revoked'] = 'Rechazado';
$Definition['Revoked badge.'] = 'Revocar insignia.';
$Definition['role'] = 'rol';
$Definition['RoleID'] = 'rol';
$Definition['Roles'] = 'Papeles';
$Definition['roles'] = 'papeles';

$Definition['Save'] = 'Guardar';
$Definition['Save Comment'] = 'Guardar Comentario';
$Definition['Save Draft'] = 'Guardar Borrador';
$Definition['Save Poll'] = 'Guardar Encuesta';
$Definition['Save Preferences'] = 'Guardar Preferencias';
$Definition['Save your password'] = 'Guarda tu contraseña';
$Definition['Search'] = 'Buscar';
$Definition['Search %s'] = 'Buscar %s';
$Definition['search archived'] = 'buscar archivado';
$Definition['SearchBoxPlaceHolder'] = 'Buscar';
$Definition['Search for a tag.'] = 'Buscar en general o por parte de una etiqueta';
$Definition['Search results for \'%s\''] = 'Buscar resultados para \'%s\'';
$Definition['search subcategories'] = 'buscar subcategorías';
$Definition['Second Anniversary'] = 'Segundo Aniversario ';
$Definition['Secret'] = 'Secreto';
$Definition['Sections'] = 'Secciones ';
$Definition['Security Check'] = 'Revisión de Seguridad';
$Definition['Select an image on your computer (2mb max)'] = 'Selecciona una imagen de tu ordenador (2MB máx)';
$Definition['Select one of the following avatars:'] = 'Seleccionar uno de los siguientes avatares:';
$Definition['Send a New Message'] = 'Enviar un nuevo mensaje';
$Definition['Send Message'] = 'Enviar Mensaje';
$Definition['Send Report'] = 'Enviar informe';
$Definition['Send report'] = 'Enviar un informe';
$Definition['sep and'] = 'y';
$Definition['Set a New Warning Level'] = 'Colocar un nuevo nivel de Advertencia ';
$Definition['Set A Password'] = 'Colocar una Contraseña';
$Definition['Setting'] = 'Configuración ';
$Definition['Settings'] = 'Configuración';
$Definition['Seventh Anniversary'] = 'Séptimo Aniversario ';
$Definition['Severity'] = 'Severidad';
$Definition['Share'] = 'Compartir';
$Definition['Shared Accounts'] = 'Cuentas Compartidas';
$Definition['she'] = 'ella';
$Definition['Shown only on mobile'] = 'Solo aparece en dispositivo móvil';
$Definition['Show unfollowed categories'] = 'Mostrar categorías sin seguir ';
$Definition['Sign-In URL'] = 'URL de Inicio de sesión';
$Definition['Sign-Out URL'] = 'URL de cerrar la sesión';
$Definition['Signature'] = 'Firma';
$Definition['Signature Code'] = 'Código firma';
$Definition['Signature invalid.'] = 'Firma inválida.';
$Definition['Signatures'] = 'Firmas';
$Definition['Signature Settings'] = 'Preferencias de firma';
$Definition['SignIn'] = 'Iniciar sesión';
$Definition['Sign In'] = 'Acceder';
$Definition['SigningOut'] = 'Espera un segundo mientras te desconectas. ';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Accede</a> o <a href="{RegisterUrl,html}">Regístrate</a> para comentar.';
$Definition['Sign in to vote!'] = '¡Ingresa para votar!';
$Definition['Sign In with %s'] = 'Iniciar Sesión con %s';
$Definition['Sign In with Disqus'] = 'Iniciar Sesión con Disqus';
$Definition['Sign In with Facebook'] = 'Iniciar Sesión con Facebook';
$Definition['Sign In with Google'] = 'Acceder con Google';
$Definition['Sign In with OpenID'] = 'Acceder con OpenID';
$Definition['Sign In with Twitter'] = 'Acceder con Twitter';
$Definition['Sign Out'] = 'Desconectarse';
$Definition['sign out'] = 'Cerrar Sesión ';
$Definition['Sign Up'] = 'Registrarse';
$Definition['Sink'] = 'Hundir';
$Definition['Sink this discussion'] = 'Hundir esta discusión';
$Definition['Site'] = 'Sitio';
$Definition['Sitemap Settings'] = 'Configuración del Mapa del Sitio';
$Definition['Sites'] = 'Sitios';
$Definition['Sixth Anniversary'] = 'Sexto Aniversario';
$Definition['somebody'] = 'alguien';
$Definition['Some Code'] = 'Algún codigo';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Alguien respondió tu pregunta. Necesitas aceptar/rechazar la respuesta. ';
$Definition['sorted by'] = 'ordenados por';
$Definition['Source:'] = 'Fuente:';
$Definition['Source Code'] = 'Código';
$Definition['Spam'] = 'Correo basura';
$Definition['Spam Queue'] = 'Cola de SPAM';
$Definition['Split'] = 'Dividir';
$Definition['Split Comments'] = 'Dividir Comentarios ';
$Definition['Spoiler'] = 'Destripe';
$Definition['Spoof User'] = 'Suplantar usuario';
$Definition['Start'] = 'Inicio';
$Definition['Start a Group'] = 'Inicia un grupo';
$Definition['Start a New Conversation'] = 'Iniciar Nueva Conversación';
$Definition['Start a New Discussion'] = 'Nueva Discusión';
$Definition['Start Conversation'] = 'Iniciar Conversación';
$Definition['Started By'] = 'Iniciado Por';
$Definition['Started by'] = 'Iniciado por';
$Definition['Started by %1$s'] = 'Iniciado por %1$s';
$Definition['Start your First Discussion'] = 'Comienza tu primera Discusión';
$Definition['Stop following'] = 'Dejar de seguir';
$Definition['Strikethrough'] = 'Tachar';
$Definition['Strip images out of signatures'] = 'Retirar imágenes de las firmas';
$Definition['Strip images out of signatures?'] = '¿Quitar las imágenes de las firmas?';
$Definition['Subject'] = 'Asunto';
$Definition['Suggested Value'] = 'Valor sugerido ';

$Definition['Tagged'] = 'Etiquetado';
$Definition['Tagged with '] = 'Etiquetado con';
$Definition['Tagged with "%s"'] = 'Etiquétame con "%s"';
$Definition['Tagging'] = 'Etiquetando';
$Definition['TagHint'] = 'Comience a escribir ...';
$Definition['Tag Name'] = 'Nombre de etiqueta';
$Definition['Tags'] = 'Etiquetas ';
$Definition['tags'] = 'etiquetas';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Las etiquetas son palabras claves que los usuarios pueden asignar a las discusiones para ayudar a categorizar su pregunta con otras preguntas similares. ';
$Definition['Take Action'] = 'Tomar acción';
$Definition['Take Action:'] = 'Tomar acción:';
$Definition['Target'] = 'Objetivo';
$Definition['Tell the user why you\'re warning them'] = 'Decirle al usuario porqué les estas advirtiendo';
$Definition['Tell us why you want to join!'] = '¡Dinos porque quieres unirte!';
$Definition['Tenth Anniversary'] = 'Décimo Aniversario';
$Definition['Terms'] = 'Términos';
$Definition['TermsOfService'] = 'Términos de Servicio';
$Definition['Terms of Service'] = 'Términos de Servicio';
$Definition['TermsOfServiceText'] = '
   <p>Usted acepta que mediante el uso de este servicio, no usará esta  comunidad para publicar cualquier material que sea conocidamente falso y/o difamatorio, 
   inexacto, abusivo, vulgar, de odio, de acoso, obsceno, blasfemo, sexual, amenazante, invasivo a la privacidad de una persona, o que infrinja de uno u otro modo cualquier ley. Aceptas no publicar ningún material con derechos de autor a menos que el derecho de autor sea de su propiedad.</p>
   
   <p>Nosotros en esta comunidad también nos reservamos el derecho de revelar tu identidad (o cualquier información que sabemos de ti) en el caso de una queja o acción 
    legal derivada de un mensaje publicado por ti. Registramos todas las direcciones de protocolo
   de Internet que acceden a este sitio web.</p>
   
   <p>Por favor ten en cuenta que los anuncios, cartas en cadena, esquemas piramidales y solicitudes son inapropiadas en esta comunidad. </p>
   
   <p>Nos reservamos el derecho a eliminar cualquier contenido por cualquier razón o ninguna 
   razón. Nos reservamos el derecho a terminar cualquier membrecía por cualquier razón o ninguna razón.</p>
   
   <p>Debes tener al menos 13 años para usar este servicio.</p>
';
$Definition['Text  Max  Length'] = 'Texto  Máx  Longitud';
$Definition['The %s you were looking for could not be found.'] = 'El %s que estás buscando no se pudo encontrar.';
$Definition['the category'] = 'la categoría';
$Definition['The content you were looking for has been deleted.'] = 'El contenido que buscas ha sido eliminado.';
$Definition['The conversation has been cleared.'] = 'La conversación ha sido limpiada. ';
$Definition['The email you entered in use by another member.'] = 'El email que escribiste es usado por otro usuario.';
$Definition['The email you have entered is already related to an existing account.'] = 'El email que escribiste esta relacionado con una cuenta existente ';
$Definition['The file failed to upload.'] = 'El archivo falló al subirlo.';
$Definition['their'] = 'su';
$Definition['The name you entered is already in use by another member.'] = 'El nombre que escribiste esta siendo usado por otro usuario.';
$Definition['The page you were looking for could not be found.'] = 'La página que estabas buscando no se ha encontrado';
$Definition['The quote had to be converted from %s to %s.'] = 'La cita se tubo que convertir de %s a %s. Algunos formatos se puede haber perdido.';
$Definition['There\'s already a %s with the name %s.'] = 'Ya hay un %1$s con el nombre %2$s.';
$Definition['There aren\'t any groups yet.'] = 'Todavía no hay grupos.';
$Definition['There are no tags in the system yet.'] = 'No hay etiquetas en el sistema todavía. ';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'El valor del reCAPTCHA fue ingresado incorrectamente. Por favor inténtalo de nuevo. ';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Ya hay una cuenta de usuario con el mismo nombre (%1$s) o correo electrónico (%2$s) que el tuyo. Puedes crear una cuenta nueva, o puedes ingresar las credenciales de tu cuenta existente en el foro.';
$Definition['The response was not in the correct format.'] = 'La respuesta no esta en el formato correcto. ';
$Definition['There was an error connecting to Disqus'] = 'Hubo error al conectarse a Disqus';
$Definition['There was an error connecting to Facebook'] = 'Hubo un error conectándose a Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Hubo un error cargando el archivo. Lo más probable es que el archivo es demasiado grande.';
$Definition['The site is currently undergoing maintenance.'] = 'El sitio se encuentra actualmente en mantenimiento';
$Definition['The uploaded file was too big (max %s).'] = 'El archivo cargado es muy grande (máx %s)';
$Definition['The user has already been warned for this %s.'] = 'El usuario ya ha sido advertido por este %s.';
$Definition['they'] = 'ellos';
$Definition['Third Anniversary'] = 'Tercer Aniversario';
$Definition['This answer was %s.'] = 'Esta respuesta fue %s. ';
$Definition['This answer was Accepted.'] = 'Es';
$Definition['This discussion has been closed.'] = 'Este hilo ha sido cerrado.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Esta discusión esta relacionada a una fuente de contenido extranjero indefinido.';
$Definition['This discussion was created from comments split from: %s.'] = 'Esta discusión fue creada de los comentarios divididos de: %s.
';
$Definition['This discussion was merged into %s'] = 'Esta discusión se convirtió en %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'El tamaño de la imagen fue cambiado para adecuarse a la página. Haz clic para agrandar.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Esta es una encuesta privada: nadie podrá ver por lo que votaste.';
$Definition['This is a public poll: others will see what you voted for.'] = 'Estas una encuesta pública: otros verán por quién votaste.';
$Definition['This is a system account and does not represent a real person.'] = 'Este es un sistema de cuesta y no representa a una persona real.';
$Definition['This Month\'s Leaders'] = 'Líderes de este Mes ';
$Definition['This question\'s answer has been accepted.'] = 'La respuesta de la pregunta ha sido aceptada. ';
$Definition['This user has been verified as a non-spammer.'] = 'Este usuario ha sido verificado como un usuario que no hace spam.';
$Definition['This user has not been verified as a non-spammer.'] = 'Este usuario no ha sido verificado como un no spammer ';
$Definition['This user has not commented yet.'] = 'Este usuario aún no ha comentado.';
$Definition['This user has not made any discussions yet.'] = 'Este usuario aún no ha realizado ninguna discusión. ';
$Definition['This user is verified as a non-spammer'] = 'Este usuario esta verificado como no spamer';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Esta advertencia ha expirado. ¿Quieres eliminarla completamente?';
$Definition['This Week\'s Leaders'] = 'Líderes de esta Semana';
$Definition['Thumbnail'] = 'Miniatura';
$Definition['Title'] = 'Título';
$Definition['To'] = 'Para';
$Definition['Toggle full page'] = 'Enciende/apaga la página entera';
$Definition['Toggle HTML view'] = 'Enciende/apaga vista HTML';
$Definition['Toggle lights'] = 'Encender/apagar las luces';
$Definition['Topic'] = 'Tema';
$Definition['Topics'] = 'Temas';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'Para enviar otro email de confirmación da clic <a href="%s">aquí</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'Para usar reCAPTCHA debes de tener una llave API de %s';
$Definition['Transport error: %s'] = 'Un error grave ocurrió mientras se procesaba esta petición.<br />El servidor devolvió la siguiente respuesta: %s';
$Definition['Troll'] = 'Trol';
$Definition['Turn ON'] = 'Prender';
$Definition['Twitter Settings'] = 'Configuración de Twitter';
$Definition['Type'] = 'Tipo';
$Definition['Type the text:'] = 'Teclea el texto:';
$Definition['Type what you hear:'] = 'Escribe lo que oyes:';

$Definition['Unable to send message, %s is ignoring you.'] = 'Imposible enviar el mensaje, %s te está ignorando.';
$Definition['Unannounce'] = 'Desanunciar';
$Definition['Unanswered'] = 'Sin respuesta';
$Definition['Unanswered Questions'] = 'Sin respuesta';
$Definition['unavailable'] = 'No disponible';
$Definition['Unban User'] = 'Desbloquear Usuario ';
$Definition['Unbookmark'] = 'Desmarcar';
$Definition['Undefined discussion body.'] = 'Cuerpo de la discusión indefinido. ';
$Definition['Undefined discussion subject.'] = 'Título de la discusión indefinido. ';
$Definition['Undefined foreign content'] = 'Contenido extranjero indefinido ';
$Definition['Undo Follow'] = 'Anular seguimiento';
$Definition['Unfollow'] = 'Dejar de Seguir';
$Definition['Unhide'] = 'Mostrar';
$Definition['Unignore'] = 'Ya no ignorar';
$Definition['UniqueID'] = 'ÚnicoID';
$Definition['Unknown'] = 'Desconocido';
$Definition['Unknown client: %s.'] = 'Cliente desconocido %s. ';
$Definition['Unordered list'] = 'Lista sin ordenar';
$Definition['Unread'] = 'Sin leer ';
$Definition['Unread Discussions'] = 'Discusiones sin leer ';
$Definition['Unsink'] = 'Reflotar';
$Definition['Unspecified'] = 'Sin especificar';
$Definition['Upcoming Events'] = 'Próximos eventos.';
$Definition['Update'] = 'Actualizar';
$Definition['Updated badge'] = 'Actualizar insignia ';
$Definition['Upload'] = 'Subir';
$Definition['Uploading...'] = 'Subiendo...';
$Definition['UrlCode'] = 'Código URL';
$Definition['Use My Current Password'] = 'Usar mi Contraseña Actual';
$Definition['User "%s" does not exist.'] = 'Usuario "%s" no existe. ';
$Definition['Username'] = 'Nombre Usuario';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Los Nombres de Usuarios solamente pueden contener letras, números y guiones bajos. ';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'El nombre de usuario solo puede contener, letras, números, guiones bajos y debe ser entre 3 y 20 caracteres de largo.  ';
$Definition['UsernameError'] = 'Los nombres de usuarios solamente pueden contener letras, números, guiones bajos y deben tener entre 3 a 20 caracteres de largo.';
$Definition['Username or email'] = 'Nombre de usuario o email';
$Definition['User not found.'] = 'Lo sentimos, no se encontró ninguna cuenta relacionada con el email/nombre de usuario que escribiste. ';
$Definition['Users Count'] = 'Conteo de usuarios';

$Definition['ValidateBanned'] = 'Eso %s no esta permitido. ';
$Definition['ValidateBoolean'] = '%s no es un booleano válido.';
$Definition['ValidateConnection'] = 'Los parámetros de conexión que has escepecificado han fallado abriendo una conexión con la base de datos. La base de datos ha reportado el siguiente error: <code>%s</code>';
$Definition['ValidateDate'] = '%s no es una fecha válida.';
$Definition['ValidateDecimal'] = '%s no es un decimal válido';
$Definition['ValidateEmail'] = '%s no parece válido..';
$Definition['ValidateEnum'] = '%s no es válido..';
$Definition['ValidateFormat'] = 'No tienes permitido publicar en html.';
$Definition['ValidateInteger'] = '%s ino es un entero válido.';
$Definition['ValidateIntegerArray'] = '%s debe de ser una lista de números separados por comas.';
$Definition['ValidateLength'] = '%1$s is%2$s caracteres demasiado largo';
$Definition['ValidateMatch'] = 'Los campos %s no coinciden.';
$Definition['ValidateMinimumAge'] = 'No tienes la edad suficiente para unirte a esta comunidad.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Debes seleccionar al menos uno %s.';
$Definition['ValidateRegex'] = '%s no parece estar en el formato correcto.';
$Definition['ValidateRequired'] = '%s es requerido.';
$Definition['ValidateRequiredArray'] = 'Tienes que seleccionar al menos uno %s.';
$Definition['ValidateTag'] = 'Las etiquetas no deben contener espacios.';
$Definition['ValidateTime'] = '%s no es un tiempo válido.';
$Definition['ValidateTimestamp'] = '%s no es un sello válido de tiempo.';
$Definition['ValidateUrlStringRelaxed'] = '%s no puede contener barras, comillas o caracteres de etiquetas.';
$Definition['ValidateUsername'] = 'Los nombres de usuario deben tener de 3 a 20 caracteres y estar compuestos de letras, números y subrayados(_)';
$Definition['ValidateVersion'] = 'El  %s campo no es un número de versión válido. Ver la función php para comparar versiones para ejemplos o números de versión válidos.';
$Definition['Value'] = 'Valor';
$Definition['Vanilla'] = 'Vainilla';
$Definition['Vanilla Statistics'] = 'Estadísticas de Vanilla';
$Definition['Vanilla Statistics Plugin'] = 'Estáticas del plugin Vanilla';
$Definition['Verified'] = 'Verificado';
$Definition['Verifying your credentials...'] = 'Verificando tus credenciales...';
$Definition['via %s'] = 'vía %s';
$Definition['Video embedding has been disabled.'] = 'El video embebido ha sido desactivado La URL no será traducida a su embebido equivalente';
$Definition['View Badge'] = 'Ver Insignia ';
$Definition['Viewing'] = 'Visualizando';
$Definition['Views'] = 'Vistas ';
$Definition['Visits'] = 'Visitas';
$Definition['Visit Site'] = 'Visitar Sitio';
$Definition['Vote'] = 'Votar';
$Definition['Vote Down'] = 'Votar en contra';
$Definition['Votes'] = 'Votos';
$Definition['Vote Up'] = 'Votar a favor';

$Definition['wall'] = 'muro';
$Definition['Want to take part in this discussion? Click one of these:'] = '¿Quieres participar en esta discusión? Haz clic en una de estas: ';
$Definition['Warn'] = 'Advertencia ';
$Definition['Warn %s'] = 'Advertir %s';
$Definition['Warned for'] = 'Advertido para';
$Definition['Warning'] = 'Advertencia';
$Definition['Warnings'] = 'Alertas';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} advertido {WarnUserID,User} por {Points,plural,%s points}.';
$Definition['WarningTitleFormat.Notice'] = '{InsertUserID,User} advertido {WarnUserID,User} por {Points,plural,%s points}.(solo un aviso).';
$Definition['was'] = 'era';
$Definition['Website'] = 'Sitio Web';
$Definition['weeks'] = 'semanas';
$Definition['Welcome Aboard!'] = '¡Bienvenido abordo!';
$Definition['were'] = 'eran';
$Definition['What\'s This?'] = '¿Qué es esto?';
$Definition['What to search'] = 'Qué buscar';
$Definition['When'] = 'Cuando';
$Definition['Where'] = 'Dónde';
$Definition['Where do you want to announce this discussion?'] = '¿Donde quieres anunciar esta discusión? ';
$Definition['Who\'s going?'] = '¿Quién va?';
$Definition['Who\'s Online'] = 'Quien está en linea ';
$Definition['Who\'s Online in this Category'] = 'Quién está conectado en esta categoría';
$Definition['Who\'s Online in this Discussion'] = 'Quién está conectado en esta discusión';
$Definition['Whoops!'] = '¡Vaya!';
$Definition['Whoops! You\'ll need to register before you can email our site.'] = '¡Ups! Deberás registrarte para enviar correo a nuestro sitio.';
$Definition['Why are you Banning this user?'] = '¿Por qué estas bloqueando a este usuario?';
$Definition['Why do you want to join?'] = '¿Por qué quieres entrar?';
$Definition['Would you like to accept the invitation to join this group?'] = '¿Desea aceptar la invitación para unirse a este grupo?';
$Definition['Write a comment'] = 'Escribir un comentario';
$Definition['Write Comment'] = 'Escribir Comentario';
$Definition['Write something about yourself...'] = 'Escribe algo sobre ti...';

$Definition['Yes'] = 'Si';
$Definition['You'] = 'Tú';
$Definition['you'] = 'tú';
$Definition['You\'re banned from joining this group.'] = 'Tiene prohibido unirse a este grupo.';
$Definition['You\'ve already created the maximum number of groups.'] = 'Ya has creado el número máximo de grupos.';
$Definition['You\'ve applied to join this group.'] = 'Has enviado una solicitud para unirte a este grupo.';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">Has hecho preguntas que han sido respondidas</a>. Asegúrate de aceptar/rechazar las respuestas.';
$Definition['You\'ve been invited to join {Name}.'] = 'Ha sido invitado a unirse a {nombre}.';
$Definition['You\'ve been Jailed.'] = 'Te metieron a la cárcel.';
$Definition['You already have an account here.'] = 'Ya tienes una cuenta aquí.';
$Definition['You are about to ban {User.UserID,user}.'] = 'Estas a punto de bloquear a {User.UserID,user}.';
$Definition['You are about to move %1$s of the %2$s of the selected discussions.'] = 'Estás a punto de mover %1$s de las %2$s discusiones seleccionadas.';
$Definition['You are about to move %s.'] = 'Estás a punto de mover %s.';
$Definition['You are about to unban {User.UserID,user}.'] = 'Estas a punto de desbloquear a {User.UserID,user}.';
$Definition['You are allowed to create %s groups.'] = 'Puedes crear %s grupos.';
$Definition['You are already a member of this group.'] = 'Ya eres miembro de este grupo.';
$Definition['You are connected as %s through %s.'] = 'Estás conectado como %s a través de %s.';
$Definition['You are connected through %2$s.'] = 'Estas conectado a través de %2$s. ';
$Definition['You are currently only viewing categories that you follow.'] = 'Por el momento solamente estas mirando categorías que tu sigues.';
$Definition['You are currently viewing all categories.'] = 'Actualmente estas viendo todas las categorías. ';
$Definition['You are editing %s\'s signature'] = 'Estas editando la firma de %s\'s ';
$Definition['You are limited to %s recipient.'] = 'Estás limitado a %s destinatario/s.';
$Definition['You are limited to %s recipients.'] = 'Estás limitado a %s destinatarios.';
$Definition['You aren\'t a %s of this group.'] = 'No eres un %s de este grupo.';
$Definition['You aren\'t allowed to %s this group.'] = 'No tienes permitido %s en este grupo.';
$Definition['You can\'t leave the group you started.'] = 'No puedes dejar el grupo que empezaste.';
$Definition['You can either ask a question or start a discussion.'] = 'Puedes hacer una pregunta o iniciar una discusión. Elige lo que quieres hacer a continuación. ';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Puedes seguir las distintas categorías y ser notificado de todos los mensajes dentro de ellos.';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'No puedes editar la imágen de una imagen de perfil vinculadq de forma externa.';
$Definition['You can only specify up to %s tags.'] = 'Solamente puedes especificar %s etiquetas';
$Definition['You can remove or ban this member from the group.'] = 'Puedes eliminar o prohibir este miembro del grupo. Los miembros prohibidos no podrán unirse de nuevo al grupo.';
$Definition['You can use HTML in your signature.'] = 'Puedes usar <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple Html</a></b> en tu firma.';
$Definition['You don\'t have permission to do that.'] = 'No tienes permiso para hacer eso.';
$Definition['You don\'t have permission to use a signature.'] = 'Usted no tiene permiso para utilizar una firma.';
$Definition['You do not have any %s yet.'] = 'No tienes ningún %s aún.';
$Definition['You do not have any bookmarks.'] = 'No tienes ningún marcador. ';
$Definition['You do not have any conversations.'] = 'No tienes ninguna conversación.';
$Definition['You do not have any drafts.'] = 'No tienes ningún borrador. ';
$Definition['You do not have any notifications yet.'] = 'Aún no tienes notificaciones.';
$Definition['You do not have enough invitations left.'] = 'Ya no tienes más invitaciones.';
$Definition['You do not have permission to move %1$s of the selected discussions.'] = 'No tienes permiso para mover %1$s de las discusiones seleccionadas.';
$Definition['You do not have permission to write new comments.'] = 'No tienes premiso para escribir nuevos comentarios.';
$Definition['YouEarnedBadge'] = 'Has ganado esta insignia ';
$Definition['You have answered questions'] = 'Has respondido preguntas.';
$Definition['You have entered an invalid discussion title'] = 'Has ingresado un título de discusión inválido ';
$Definition['You haven\'t joined any groups yet.'] = 'Todavía no te has unido a ningún grupo.';
$Definition['You haven\'t read this yet.'] = 'No has leído esto aún.';
$Definition['You have not started any discussions.'] = 'No has iniciado ninguna discusión. ';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Publicaste %1$s veces en menos de %2$s segundos. Un bloqueo por spam esta afectando tu cuenta. Debes esperar al menos %3$s segundos antes de intentar publicar otra vez. ';
$Definition['You have selected %1$s.'] = 'Has seleccionado %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Has seleccionado %1$s en esta discusión. ';
$Definition['You have to select at least 2 discussions to merge.'] = 'Tienes que seleccionar al menos 2 discusiones para unirlas. ';
$Definition['You must agree to the terms of service.'] = 'Debes aceptar los términos de servicio.';
$Definition['You need to confirm your email address.'] = 'Es necesario que confirmes tu dirección de correo electrónico. Haz clic <a href="{/entry/emailconfirmrequest,url}">aquí</a> para enviar el correo de confirmación nuevamente.';
$Definition['You need to sign in before you can do this.'] = 'Necesitas iniciar sesión antes de poder hacer esto. ';
$Definition['your'] = 'tu';
$Definition['Your application for this group was denied.'] = 'Tu solicitud para este grupo fue rechazada.';
$Definition['Your changes have been saved.'] = 'Tus cambios se han guardado';
$Definition['Your changes have been saved successfully.'] = 'Tus cambios se han guardado correctamente.';
$Definition['Your changes were saved.'] = 'Tus cambios fueron guardados.';
$Definition['Your email has been successfully confirmed.'] = 'Tu correo ha sido confirmado satisfactoriamente.';
$Definition['Your invitation has been sent.'] = 'Tu invitación ha sido enviada.';
$Definition['Your old password was incorrect.'] = 'Tu antigua contraseña es incorrecta.';
$Definition['Your password has been changed.'] = 'Tu contraseña ha sido cambiada. ';
$Definition['Your picture has been removed.'] = 'Tu imagen ha sido eliminada.';
$Definition['Your post will appear once it\'s been approved.'] = 'Tu comentario aparecerá una vez que sea aprobado.';
$Definition['Your preferences have been saved.'] = 'Tus preferencias han sido guardadas. ';
$Definition['Your private conversations with other members.'] = 'Tus conversaciones privadas con otros usuarios.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Tu nombre de usuario registrado: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'Tu petición ha sido enviada. Verifica tu email para instrucciones adicionales. ';
$Definition['Your settings have been saved.'] = 'Tu configuración se ha guardado.';
$Definition['Your settings have been saved successfully.'] = 'Tu configuración se ha guardado correctamente. ';
$Definition['Your status for this event is now: <b>%s</b>'] = 'Su estado para este evento ahora es: <b>%s</b>';
$Definition['Your warning was added.'] = 'Tu advertencia fue agregada ';

$Definition[' You should '] = 'Deberías';

$Definition['You were added to a conversation.'] = '{InsertUserID,user} agregado {NotifyUserID,you} a una <a href="{Url,htmlencode}"> conversación </a>.';
$Definition['You wrote:'] = 'Has escrito:';
