<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Upozornenie: Povolenie tejto funkcie môže spôsobiť chyby JavaScriptu na vašom webe.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Pozor!</strong> Zmazaním role môžete spôsobiť, že užívatelia nebudú mať prístup na danú aplikáciu.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Pozor!</strong> Presúvanie diskusií do náhradnej kategórie môže spôsobiť zmiznutie diskusie (alebo objavenie) ak nová kategória má iné práva ako kategória ktorá bude zmazaná.';

$Definition['About.DisableStatistics'] = 'Ak musíte vypnúť štatistiky z obchodných dôvodov, môžete tak urobiť pridaním nasledujúceho riadku kódu do vašeho inštalačného súboru: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Je veľmi dôležité aby sme zberali údaje o dosahu a efektívnosti tohto free, open-source softvéru Vanilly. Prosíme vás aby ste nevypínali odosielanie týchto údajov.';
$Definition['AboutCommentEmbedding'] = 'Vanilla môže byť použitá ako náhrada natívneho systému komentárov na vašom blogu. Vpodstate môže byť použitý na pridávanie komentárov na hociakú webovú stránku.';
$Definition['AboutEmbedding'] = 'Vkladanie vašej komunite umožní vložiť odkaz do aplikácií alebo web stránok.';
$Definition['About Vanilla Statistics'] = 'O Štatistikách';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Pre prístup do vášho komunitného fóra kliknite na odkaz „Navštíviť stránku“ v hornej časti stránky alebo <a href={/,url}>kliknite tu</a>. Všetci používatelia a zákazníci uvidia komunitné fórum, keď navštívia odkaz <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'V diskusiách a komentároch pridajte obmedzenia pre rozmery odovzdávania obrázkov.
';
$Definition['AddonProblems'] = '<h2>Máte problémy?</h2><p>Ak máte problém s doplnkom a neviete používať vašu webovú stránku, môžete ho vypnúť manuálne editovaním:</p>%s';
$Definition['AddressBarColorDescription'] = 'Niektoré prehliadače podporujú farbu pre panel s adresou. Iba pre mobilné zariadenia.';
$Definition['Alert users if they click external link.'] = 'Upozorniť používateľov, ak kliknú na odkaz v príspevku, ktorý ich povedie mimo fóra. Používatelia nebudú varovaní, keď nasledujú odkazy, ktoré sa zhodujú s dôveryhodnou doménou';
$Definition['Alignment'] = 'zarovnanie';
$Definition['Alignment (Mobile)'] = 'Zarovnanie (mobil)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Všetky kategórie zobrazujú selekciu 5 posledných diskusií v nej';
$Definition['Allow links to be transformed'] = 'Umožňujú transformáciu odkazov na vložené reprezentácie v diskusiách a komentároch. Napríklad odkaz YouTube sa zmení na vložené video.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Umožnite používateľom s povolením %s zmeniť svoje avatary zo svojich profilových stránok vo Vanille.';
$Definition['ApplicationHelp'] = 'Aplikácie vám umožňujú pridať veľké skupiny funkčnosti na vašu stránku.<br />Akonáhle bola aplikácia pridaná do vášho %s adresára, môžete ju zapnúť alebo vypnúť tu.';
$Definition['Apply Layout'] = 'Použiť rozloženie';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Naozaj chcete odstrániť túto tému? Bude natrvalo odstránené.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Ste si istý(á) že ste zadal(a) správneho hostiteľa databázy? Nepomýlil(a) ste sa? Databáza vrátila: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Na používanie potvrdenia e-mailom je potrebná rola s predvoleným typom „nepotvrdená“.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatary budú zmenšené, ak prekročia túto výšku.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatary budú zmenšené, ak prekročia túto šírku.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatarom sa uložia miniatúry v tejto veľkosti.';

$Definition['Background'] = 'Pozadie';
$Definition['Background Image'] = 'Obrázok na pozadí';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Buď kreatívny! Skúste pomenovať rad podľa vecí, o ktorých komunita hovorí.';
$Definition['Bordered'] = 'ohraničený';
$Definition['Bordered (Unified)'] = 'Ohraničené (zjednotené)';
$Definition['Borderless'] = 'bez hraníc';
$Definition['Border Radius'] = 'Hraničný polomer';
$Definition['Brand Color'] = 'Farba značky';
$Definition['Buttons'] = 'tlačidla';
$Definition['Buttons & Inputs'] = 'Tlačidlá a vstupy';
$Definition['Button Type'] = 'Typ tlačidla';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Kliknutím tlačítka nižšie navždy odstránite účet užívateľa %s.';

$Definition['Center Aligned'] = 'Zarovnať na stred';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Zmeny sa budú týkať iba novo nahraných avatarov.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Zmeňte veľkosti, v ktorých sú uložené avatar obrázky.';
$Definition['Change the way your community works with plugins.'] = 'Zmeňte spôsob, akým vaša komunita pracuje s doplnkami. Do softvéru sme pridaôi balíček populárnych doplnkov, viac ich môžete nájsť online.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Zaškrtávacie políčka umožňujú správcom vykonávať dávkové akcie pri viacerých diskusiách alebo komentároch súčasne.';
$Definition['Check out our %s'] = 'Pozrite si našu %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Pozrite si našu <0>dokumentáciu</0> alebo sa opýtajte našej <1>komunity odborníkov</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla je najjednoduchšia a najrýchlejšia komunitná platforma na svete. Strašne jednoducho sa používa. Začnite s týmto úvodným videom a pokračujte v krokoch nižšie. Užite si to!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Zvoľte rolu ktorá bude pridelená opusteným užívateľom:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Vyberte tému pre túto podkomunitu. <0> Prečítajte si viac </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Zvoľte ako naložiť so všetkými dátami užívateľa %s (komentáre, správy, atď).';
$Definition['Choose Image'] = 'Vyberte Obrázok';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Môžete si vybrať vlastný algoritmus na podpis požiadaviek. Algoritmus musí byť tiež použitá vo vašej klientskej knižnici. Zvoľte md5 ak si nie ste istý čo si vybrať.';
$Definition['Choose the order items are sorted.'] = 'Vyberte poradie Položky sú zoradené.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Vyberte stránku, ktorú by ľudia mali vidieť pri návšteve <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Vyberte preferované rozloženie pre zoznamy kategórií.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Vyberte preferované rozloženie pre zoznamy kategórií. Rozloženie dlaždíc môžete upraviť.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Vyberte preferované rozloženie pre zoznamy diskusií.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Vyberte preferované rozloženie pre zoznamy diskusií. Rozloženie nadácie môžete upraviť.';
$Definition['Color Overlay'] = 'Farebné prekrytie';
$Definition['Continue Import'] = 'Pokračovať v Importovaní';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Nie je možné analyzovať súbor importu. Problém je pri riadku %s.';
$Definition['Create a localization CSV'] = 'Vytvoriť CSV jazykový preklad';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Vlastné motívy sú témy, ktoré ste vytvorili. Môžete ich upravovať, premenovať alebo vytvoriť ich kópiu.';

$Definition['Dark'] = 'tmavý';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Nastavte kto môže odovzdávať a spravovať súbory na stránke <a href="%s">Rolí a Práv</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Nastavte domovskú stránku, odovzdajte vaše logo a viac...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Odstránením role môžete spôsobiť, že užívatelia nebudú mať prístup na danú aplikáciu.';
$Definition['Deleting forever cannot be undone.'] = 'Odstránenie je dobrý spôsob ako udržať vaše fórum čisté.';
$Definition['Disable Google Sign In'] = 'Vypnúť Prihlasovanie cez Google';
$Definition['Disable OpenID'] = 'Vypnúť OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Na stránke <0>Vanilla Labs zakážte laboratórium „Nový systém vkladania“.</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Kategórie diskusie pomôžu vašim užívateľom organizovať ich diskusie zmysluplne pre komunitu.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Nevložiť ovládací panel fóra (otvoriť na celú obrazovku)';
$Definition['Don\'t use too many reactions.'] = 'Nepoužívajte príliš veľa reakcií. Nechcete svojim používateľom poskytovať informácie preťažením.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Ťahať a pustiť kategórie nižšie pre ich zoradenie a vnorenie.';

$Definition['EditContentTimeout.Notes'] = 'Ak užívateľ má priradenú rolu ktorá ma právo upraviť obsah, tie práva nahratie toto.';
$Definition['Edit Route'] = 'Upraviť Cestu';
$Definition['Edits to this theme apply to:'] = 'Úpravy tejto témy sa týkajú:';
$Definition['Embed Settings'] = 'Nastavenia vloženia';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Vložte svoje komunitné fórum na vašu webstránku na zvýšenie účasti...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Povoľte a vyskúšajte si najnovšie funkcie vanilky.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Umožňuje pokročilú úpravu príspevkov v niekoľkých formátoch vrátane WYSIWYG, jednoduchého HTML, Markdown a BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Povoľte Editor rozloženia, aby ste mohli použiť vlastné rozloženie pre stránky komunity. Použite náš nový editor na zobrazenie obsahu pomocou nášho katalógu dostupných miniaplikácií.';
$Definition['Enter a descriptive name.'] = 'Napíšte popisný názov vrecka. Tento názov nebude nikde zobrazený, iba pri spravovaní vašich vreciek tu, takže je použitý iba na to aby vám pomohol zapamätať si toto vrecko.';
$Definition['Enter a short name for the site.'] = 'Napíšte krátky názov pre vašu webstránku. Tento názov je zobrazený na prihlasovacích tlačítkach.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Napíšte adresu vášho Wordpressového blogu a my to zariadime za vás.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Nastavte pripojenie k vašemu sphinx serveru nižšie.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Každá editácia alebo mazanie je zaznamenané tu. Použite ‘Vrátiť späť’ na vrátenie hociakej zmeny.';
$Definition['Everyone who signs up gets a profile page.'] = 'Každý, kto sa zaregistruje vo vašej komunite, získa stránku s verejným profilom, na ktorú môže nahrať svoju fotografiu, spravovať si nastavenia profilu a sledovať, čo zaujímavé sa v komunite deje. Teraz by ste si mali <a href="{/profile,url}">prispôsobiť svoj profil</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Každý užívateľ na vašej stránke má pridelenú aspoň jednu rolu. Role sú použité na určenie, čo môžu títo užívatelia robiť.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect umožní užívateľom používať ich Facebook účet. <b>Musíš registrovať tvoju aplikáciu s Facebookom aby tento plugin fungoval.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Zlyhalo pripojenie do databázy zo zadaným menom a heslom. Nepomýlil si sa? Databáza odkazuje: <code>%s</code>';
$Definition['Font'] = 'font';
$Definition['Font Name'] = 'Názov písma';
$Definition['Font URL'] = 'Adresa URL písma';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Vynúti ovládací panel aby bol sprístupnený len cez tento odkaz <em>(neodporúčané)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Napríklad môžete zakázať všetkých používateľov s mailovými adresami z „example.com“, ak pridáte zákaz typu email s hodnotou „*@example.com“.';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Na účely SEO sú roboti vyhľadávačov vylúčené z toho, aby boli nútené prezerať fórum vo vzdialenej URL.';
$Definition['Foundation Layout'] = 'Rozloženie nadácie';
$Definition['Full Bleed'] = 'Plné krvácanie';

$Definition['Garden.Import.Complete.Description'] = 'Úspešne si dokončil import.
Klikni <b>Dokončné</b> ked budeš pripravený.';
$Definition['Garden.Import.Continue.Description'] = 'Zdá sa, že ste v strede importu. Vyberte jednu z nasledujúcich možností.';
$Definition['Garden.Import.InputInstructions'] = 'Zadajte email a heslo administrátora z importovaných údajov .';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Záhrada.Profily.Upravte povolenie na zmenu vlastných avatarov z ich profilových stránok vo Vanille.';
$Definition['Garden.StatisticsDisabled'] = 'V konfiguračnom súbore ste konkrétne zakázali štatistiku Vanilla.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Zdá sa, že toto fórum beží v testovacom prostredí alebo inak hlási súkromnú IP adresu. Fóra, bežiace na súkromných IP adresách, sa štandardne nesledujú.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Ak ste si istí, že vaše fórum je prístupné z internetu, môžete ho priviesť k hláseniu štatistiky sem:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Zdá sa, že váš súbor config.php je iba na čítanie. To znamená, že Vanilla ho nebude vedieť automaticky zaregistrovať na základe inštalačného ID a tajnej informácie o inštalácii vášho fóra.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Na vyriešenie tohto problému priraďte súborový režim 777 do svojho súboru conf/config.php.';
$Definition['Global Styles'] = 'Globálne štýly';

$Definition['Heads Up!'] = 'Informácia!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Informácia! Toto je špeciálna rola, ktorá neumožňuje aktívne relácie. Z tohto dôvodu sú možnosti povolení obmedzené na povolenia „zobraziť“.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Tu sú všetky reakcie, ktoré môžete použiť na svojich stránkach.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Tu sú rady, ktoré môžu používatelia dosiahnuť na vašom webe. Tieto kategórie môžete prispôsobiť a dokonca pridať nové. Tu je niekoľko tipov.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Po nahraní loga banneru bude nahradený názov bannera na stránkach fóra orientovaných na používateľa.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Ak používateľ nenavštívi stránku v tomto časovom období, bude automaticky odhlásený.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Ak je povolená, celý obsah príspevkov sa odošle používateľom prostredníctvom e-mailových upozornení.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Ak ste novým používateľom HTML alebo CSS, tu je niekoľko návodov, ktoré vám pomôžu začať:';
$Definition['If you have an old theme'] = 'Ak máte starú tému a potrebujete nastaviť samostatnú tému pre plochu a mobil, môžete tak urobiť pomocou starého tematického používateľského rozhrania.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Ak chcete znížiť úroveň varovania, odstráňte varovanie.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Ak chcete vložiť fórum alebo použiť komentáre Vanilla vo svojom blogu, musíte vkladanie povoliť. Ak vkladanie nepoužívate, odporúčame toto nastavenie vypnúť.';
$Definition['Image (Mobile)'] = 'Obrázok (mobil)';
$Definition['Import'] = 'Importovať';
$Definition['Importing to Vanilla'] = 'Importuje sa do Vanilla';
$Definition['In additon to the widgets there are also'] = 'Okrem widgetov existujú aj <0> Globálne štýly </0> , Ak chcete upraviť globálne štýly, kliknite kdekoľvek na stránke, napríklad na tento text.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integrujte nadácie a komponenty do svojej témy';
$Definition['Internationalization & Localization'] = 'Internacionalizácia a lokalizácia';
$Definition['Invalid URL'] = 'neplatná URL adresa';
$Definition['Invitation email failed to send: %'] = 'Hoci bola pozvánka úspešne vytvorená, e-mail sa nepodarilo odoslať. Server nahlásil nasledujúcu chybu: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Ak použijete registráciu pomocou pozvania, používatelia budú mať  na svojich profilových stránkach odkaz s názvom <a href="%s" class="Popup">Moje pozvania</a>.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Zdá sa, že zadaná databáza ešte neexistuje. Už ste ju vytvorili? Urobili ste preklep v názve? Databáza hlási: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Je vhodné dodržať maximálny povolený počet znakov v komentári.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Je vhodné ponechať maximálny počet znakov povolených v príspevku na primeranú veľkosť.';

$Definition['Kick-start your community and increase user engagement.'] = 'Odštartujte svoju komunitu a zvýšte zapojenosť používateľov.';

$Definition['Labs'] = 'Laboratóriá';
$Definition['Layout Editor'] = 'Editor rozloženia';
$Definition['Learn about custom routing.'] = 'Prečítajte si ďalšie informácie o vlastnom smerovaní.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Naučte sa úplne zmeniť vzhľad a celkový dojem fóra: nahrajte svoje logo, nastavte svoju domovskú stránku, vyberte tému a prispôsobte si to.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Naučte sa, ako používať základné funkcie vášho fóra.';
$Definition['Left Aligned'] = 'Ľavé zarovnanie';
$Definition['Light'] = 'Svetlo';
$Definition['Links'] = 'odkazy';
$Definition['Locales allow you to support other languages on your site.'] = 'Miestne nastavenia vám umožňujú podporovať iné jazyky na vašej stránke. Môžete povoliť alebo zakázať miestne nastavenia, ktoré chcete sprístupniť.';
$Definition['LogoDescription'] = 'Logo bannera sa zobrazí v hornej časti stránky.';
$Definition['LogoDisclaimer'] = 'Témy vytvorené pomocou editora motívov a niektoré vlastné motívy toto nastavenie nepoužívajú.';
$Definition['Looking for the Old Embed System?'] = 'Hľadáte starý Embed systém?';

$Definition['Make sure you click View Page'] = 'Uistite sa, že kliknete na <a href="%s">Zobraziť stránku</a>, aby ste si pozreli po uložení pozreli ako vyzerá vaša stránka s kategóriami.';
$Definition['Manage Routes'] = 'Správa ciest';
$Definition['Managing Users'] = 'Správa používateľov';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Ak označíte veci ako NIE spam, vrátite ich späť do svojho fóra.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Ak označíte veci ako nie spam, vrátite ich späť do svojho fóra.';
$Definition['Messages can appear anywhere in your application.'] = 'Správy sa môžu objavovať kdekoľvek vo vašej aplikácií a môžete ich používať na informovanie používateľov o novinkách a udalostiach. Použite túto stránku na reorganizáciu vašich správ ich posúvaním hore alebo dole.';
$Definition['MobileLogoDescription'] = 'Logo mobilného bannera sa zobrazí v hornej časti stránky.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Témy pre mobilné zariadenia vám umožňujú zmeniť vzhľad a dojem z vašich stránok na menších zariadeniach.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'Poznámka: Nový editor rozloženia zdedí tému nastavenú vo vašej príručke štýlov (formálne editor tém). <1>Zistite viac</1>';
$Definition['Need More Help?'] = 'Potrebujete ďalšiu pomoc?';
$Definition['Need more help?'] = 'Potrebujete ďalšiu pomoc?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Vnorené kategórie, ktoré sú hlbšie ako táto hĺbka, sa umiestnia do zoznamu oddeleného čiarkami.';
$Definition['New Embed System'] = 'Nový systém vkladania';
$Definition['New Quick Links'] = 'Nové rýchle odkazy';
$Definition['New Search Page'] = 'Nová stránka vyhľadávania';
$Definition['Not getting what you expect when you preview your theme?'] = 'Nezobrazuje sa vám to, čo očakávate, keď si ukážete svoj motív?';
$Definition['Notify me when people comment on my addons.'] = 'Upozorniť ma, keď ľudia okomentujú moje doplnky.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Na používanie e-mailového potvrdenia je potrebné, aby stránka mala predvolený typ „nepotvrdené“. Pridajte ho na povolenie tohto nastavenia.';

$Definition['Old Theming UI'] = 'UI Old Theming';
$Definition['Once enabled, only members will see inside your community.'] = 'Po povolení sa vo vašej komunite uvidia iba členovia.';
$Definition['OrgDescription'] = 'Názov vašej organizácie sa používa na mikrodáta SEO a SON+LD';
$Definition['Outline'] = 'obrys';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Prekryté zobrazenia alebo témy môžu mať nezamýšľané vedľajšie účinky a nie sú zobrazené v ukážke.';

$Definition['Password.MinLength'] = 'Minimálna povolená dĺžka znakov pre heslá používateľov na stránkach na vytváranie a resetovanie hesla.';
$Definition['Please choose an authenticator to configure.'] = 'Vyberte autentifikátor, ktorý chcete nakonfigurovať.';
$Definition['PluginHelp'] = 'Rozšírenia vám umožňujú pridať funkčnosť na svoje stránky. <br />Po pridaní rozšírenia do svojho %s priečinka ho tu môžete povoliť alebo zakázať.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Pocket sa zobrazuje medzi každou diskusiou v hlavnom zozname diskusií. Pretože diskusie sú zvyčajne v <li>..</li> značkách, budete musieť do týchto značiek tiež zabaliť svoj pocket.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Pomocou Pockets môžete pridať HTML vo voľnom formáte na rôzne miesta v aplikácii.';
$Definition['Preset'] = 'preset';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Zabráňte spamu vo vašom fóre obmedzením počtu diskusií a komentárov, ktoré môžu používatelia uverejniť v priebehu daného časového úseku.';
$Definition['Primary Button'] = 'Primárne tlačidlo';
$Definition['Primary Buttons'] = 'Primárne tlačidlá';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Stručný sprievodca vytvárania tém pre Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Rýchle odkazy sú predvoleným komponentom na stránkach komunity. Povoľte náš nový komponent Rýchle odkazy, aby ste mohli pridávať, upravovať alebo skrývať odkazy z tejto ponuky pomocou nášho editora tém.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Hotové rozšírenie Komentáre Vanilla pre WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Hotový doplnok Vanilla Forum pre WordPress';
$Definition['Realtime progress bars: %s'] = 'Ukazovateľe pokroku v reálnom čase: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Je dobré mať špeciálne rady pre moderátorov a administrátorov, aby vaša komunita mohla ľahko vidieť, kto má na starosti.';
$Definition['Recommend starting with five ranks.'] = 'Nechcete mať príliš veľa hodností. Odporúčame začať s piatimi. Ak je vaša komunita naozaj veľká, môžete pridať viac.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Odstráňte odkazy na diskusie a kategórie z ponúk. Nastaviť stránky súvisiace s diskusiou a kategóriou tak, aby sa vrátila stránka nenájdená 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Vyžaduje sa reakčné povolenie „Označiť“.';
$Definition['Requires “Negative” reaction permission.'] = 'Vyžaduje sa povolenie na negatívnu reakciu.';
$Definition['Requires “Positive” reaction permission.'] = 'Vyžaduje sa povolenie na „pozitívnu“ reakciu.';
$Definition['Restoring your selection removes the items from this list.'] = 'Po obnovení sa položky odstránia z tohto zoznamu a vrátia sa späť na stránku.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Použite nasledujúcu možnosť na povolenie úvodzoviek pre editor Rich. Platí to iba vtedy, ak je predvolený formátovací formát „Bohatý“.';
$Definition['Route Expression'] = 'Výraz pre cestu';
$Definition['Routes are used to redirect users.'] = 'Cesty sa používajú na presmerovanie používateľov v závislosti od požadovanej URL.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Ak chcete zobraziť všetkých používateľov s touto rolou, vyhľadajte ich podľa mena alebo zadajte názov roly.';
$Definition['Secondary Button'] = 'Sekundárne tlačidlo';
$Definition['Secondary Buttons'] = 'Sekundárne tlačidlá';
$Definition['Security.Hsts.HTTPSWarning'] = 'Upozornenie: Túto funkciu povoľte, iba ak ste si istí, že všetky vaše subdomény sú nakonfigurované pre HTTPS s platnými certifikátmi.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Ak je toto pravidlo povolené, aplikuje sa aj na všetky subdomény vašich stránok.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Odporúčame začať s maximálnym vekom 1 týždeň. A keď sa presvedčíte, že vaše stránky fungujú podľa očakávania, potom môžete zvýšiť na 1 mesiac a neskôr na 1 rok.';
$Definition['Security.Hsts.SubmitWarning'] = 'Varovanie: Je najlepšie podporovať predbežné načítanie HSTS . Musíte však vašu stránku odoslať na stránku hstspreload.org, aby ste sa uistili, že sa úspešne predbežne načíta (teda aby ste získali úplnú ochranu zamýšľanej konfigurácie)';
$Definition['See the documentation'] = 'Pozrite si dokumentáciu';
$Definition['Select the default type for this role, if any.'] = 'Vyberte predvolený typ pre túto rolu, ak existuje.';
$Definition['Select the import source'] = 'Vyberte zdroj importu';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Serializovaný stĺpec „%s“ sa nepodarilo odserializovať.';
$Definition['Session Timeout'] = 'Časový limit relácie';
$Definition['ShareImageDescription'] = 'Keď niekto zdieľa odkaz na vašom webe, pokúsime sa načítať obrázok zo stránky. Ak na stránke nie je obrázok, použijeme ho namiesto neho. Obrázok by mal byť aspoň 50 × 50, ale odporúčame 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Zapnite túto možnosť na zobrazenie všetkých možných lokalít vreciek. Zapnutie tejto možnosti zobrazí lokality iba používateľom, ktorí môžu spravovať vrecká.';
$Definition['Solid'] = 'tuhý';
$Definition['Some browsers support a color for the address bar.'] = 'Niektoré prehliadače podporujú farbu panela s adresou.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Niektoré staršie témy nepodporujú úplné možnosti úprav. Ak chcete vidieť, čo téma podporuje, môžete umiestniť kurzor myši nad jeho názov a zistiť, kde sa úpravy prejavia.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Niektoré témy bude možno potrebné aktualizovať, aby fungovali podľa nasledujúcich kategórií. Túto funkciu môžete zakázať počas aktualizácie témy.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Niekedy chcete vložiť svoj web Vanilla do iného webu. Vanilkový embed systém ponúka jednoduchú cestu k tomu. Pri používaní vloženého webu existujú kompromisy vo výkone, preto si v dokumentácii pozrite alternatívy a ideálne prípady použitia.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Osobitné obmedzenie: Túto reakciu môžu používať iba používatelia s povolením záhrady.Kmeň.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Zadajte čiastočnú alebo úplnú zhodu na vytvorenie zákazu';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Trochu popremýšľate o tom, ako tu popisujete svoje stránky. Ak dáte svojim stránkam zmysluplný názov a výstižný popis, mohlo by to pomôcť vašej pozícii vo vyhľadávačoch.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Vylepšite svoje emaily pridaním loga a prispôsobením farieb.';
$Definition['Start Import'] = 'Spustiť import';
$Definition['Start the first discussion.'] = 'Rozbehnite to vo vašej komunite tak, že <a href="{/post/discussion,url}">začnete prvú diskusiu</a>.';
$Definition['Subcommunities'] = 'Subkomunity';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Značkovanie umožňuje používateľom pridať značku do diskusií, ktoré začínajú, aby boli lepšie viditeľné.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Šablóny sú štandardné témy. Ak ich chcete prispôsobiť, musíte si vytvoriť kópiu.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = '%s autentifikátor nemá žiadne možnosti vlastnej konfigurácie.
';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'Poznámka: Laboratórium <0/> je potrebné nakonfigurovať tak, aby zodpovedalo vašej vlastnej téme. To je možné vykonať pomocou nášho nového editora tém. <1> Zistite viac.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Doplnok nebolo možné povoliť, pretože spôsobil závažnú chybu: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Doplnok už bol stiahnutý.';
$Definition['The banner logo appears at the top of your forum.'] = 'Logo bannera sa zobrazí v hornej časti fóra.';
$Definition['The banner title appears on the top-left of every page.'] = 'Názov bannera sa zobrazí v ľavej hornej časti každej stránky.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Názov bannera sa zobrazí na banneri stránky a v titulnej lište prehliadača. Mal by mať menej ako 20 znakov. Ak nahráte logo banneru, nahradí názov bannera na stránkach fóra orientovaných na používateľa. Nezabudnite tiež, že niektoré témy môžu tento názov skryť.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Základný registračný formulár vyžaduje</strong> od nových používateľov, aby skopírovali text z obrázku CAPTCHA na odradenie spammerov. Potrebujete účet na stránke <a href="http://recaptcha.net/">recaptcha.net</a>. Registrácia je jednoduchá a ZADARMO. Po registrácii sa sem vráťte a zadajte nasledujúce nastavenia:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Zadaný používateľ databázy nemá povolenie na prístup k databáze. Už ste vytvorili databázu? Databáza hlási: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Vaša databáza vyžaduje nasledujúce zmeny štruktúry.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Názov domovskej stránky sa zobrazí na vašej domovskej stránke. Vyberte si taký názov, ktorý by ste radi videli vo vyhľadávačoch.';
$Definition['The import file does not contain any data.'] = 'Importovaný súbor neobsahuje žiadne dáta.';
$Definition['The import file is not in the correct format.'] = 'Importovaný súbor nie je v správnom formáte.';
$Definition['The location of the authentication endpoint.'] = 'Poloha koncového bodu autentifikácie.';
$Definition['ThemeHelp'] = 'Témy vám umožnujú meniť vzhľad a dojem z vašej stránky.<br /> Po pridaní témy do vášho adresára %s  ju môžete povoliť tu.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Ukážka témy je obmedzená na zobrazenie šablóny a css témy.';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Mobilné logo sa zobrazuje v hornej časti vašej stránky. Témy vytvorené pomocou editora tém a niektoré vlastné témy toto nastavenie nepoužívajú.';
$Definition['The New Embed System'] = 'Nový systém vkladania';
$Definition['The new embed system has improved performance.'] = 'Nový systém vkladania má vylepšený výkon, vylepšené správanie pri posúvaní a konzistentnejšie správanie ako ten starý. Vkladanie komentárov a wordpress momentálne v novom systéme vkladania nepodporuje.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Overovač hesiel nemá žiadne vlastné možnosti konfigurácie.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Momentálne sa nevyžadujú žiadne zmeny v štruktúre databázy. Môžu sa však vyskytovať zmeny dát.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'V aplikácii sú dva typy tlačidiel: primárne a sekundárne.';
$Definition['The route was saved successfully.'] = 'Cesta bola úspešne uložená.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Popis stránky sa zvyčajne zobrazuje vo vyhľadávačoch. Mali by ste skúsiť mať popis dlhý 100 – 150 znakov.';
$Definition['The text of the pocket.'] = 'Zadajte text pocketu. Toto bude výstupom presne tak, ako to zadáte, takže sa uistite, že ste zadali platné HTML.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Dotyková ikona sa zobrazí, keď si webovú stránku uložíte medzi záložky na domovskej obrazovke mobilného zariadenia. Zvyčajne ide o 152 pixelov.';
$Definition['The user table was not in the import file.'] = 'Používateľská tabuľka nebola v importovanom súbore.';
$Definition['The Vanilla 2 Exporter'] = 'Exportér Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Štatistika Vanilla zmení pracovný panel vášho fóra na analytický reportovací nástroj, ktorý vám umožní sledovať aktivitu na vašom fóre v danom časovom období. V našej dokumentácii si môžete <a href="http://vanillaforums.org/docs/vanillastatistics">prečítať viac o štatistike Vanilla</a>.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Fungujú rovnako ako bežné témy. Po pridaní do priečinka motívov ho môžete povoliť tu.';
$Definition['This is a style guide of your theme.'] = 'Toto je sprievodca štýlom vašej témy. Obsahuje príklady vizuálnych prvkov použitých v celej aplikácii. Môžete kliknúť na rôzne miniaplikácie, ako je napríklad <0> záhlavie </0> alebo <1> banner </1> upravte ich vlastnosti na bočnom paneli.';
$Definition['This is the administrative dashboard for your new community.'] = 'Toto je ovládací panel vašej novej komunity. Pozrite si možnosti konfigurácie na boku. Tam môžete konfigurovať fungovanie vašej komunity. <b>V predvolenom nastavení môžu túto časť komunity vidieť iba používatelia s rolou „správcu“.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Tu môžete povoliť a vyskúšať nové funkcie, stránky a komponenty Vanilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Toto laboratórium nemožno zakázať, pretože je použité vlastné rozloženie.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Toto laboratórium nemožno zakázať, pretože to vyžaduje aktuálna téma.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Toto logo sa zobrazuje v hornej časti vašej stránky. Témy vytvorené pomocou editora tém a niektoré vlastné témy toto nastavenie nepoužívajú.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Táto možnosť zobrazí/skryje miesta, kam môžu ísť pockety, ale iba pre používateľov s povolením na pridávanie/úpravu pocketov. Pokúste sa zobraziť polohu a potom navštíviť svoju stránku.';
$Definition['This page lists the endpoints of your API.'] = 'Na tejto stránke sú uvedené koncové body vášho rozhrania API. Kliknutím na koncové body získate ďalšie informácie. Z tejto stránky môžete uskutočňovať živé hovory do rozhrania API alebo navonok pomocou prístupového tokenu.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Táto rola je osobná informácia. Zobrazia sa to iba používateľom, ktorí majú povolenie na zobrazenie osobných informácií.';
$Definition['This setting loads the page before executing Javascript.'] = 'Toto nastavenie načíta stránku pred spustením Javascriptu, čo môže vylepšiť vaše SEO. <br> <strong>** Varovanie: Povolenie tejto funkcie môže spôsobiť chyby Javascriptu na vašom webe. **</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Toto nastavenie načíta stránku pred spustením JavaScriptu, čo môže zlepšiť vaše SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Túto tému nie je možné odstrániť, pretože je to aktuálne použitá téma.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Tento názov sa zobrazí na banneri vašej stránky a v záhlaví vášho prehliadača. Mal by mať menej ako 20 znakov. Ak je nahrané logo, nahradí tento názov na používateľských stránkach fóra. Majte tiež na pamäti, že niektoré témy môžu skrývať tento názov.';
$Definition['Tiled Layout'] = 'Kachľové rozloženie';
$Definition['Title Bar'] = 'Titulná lišta';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Použite nasledujúci kód na vloženie Vanilla fóra na vašu webovú stránku.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Príliš veľa adries! Naraz posielame až %s adries.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Na zabránenie zneužitiu niektoré nástroje automaticky skryjú obsah a uvádzajú ho tu, kým ho manuálne neschváli správca.';
$Definition['TouchIconDescription'] = 'Dotyková ikona sa zobrazí, keď si na domácej obrazovke zariadenia Apple uložíte záložku. Zvyčajne sú to 152 pixelov. Apple pridáva zaoblené rohy a svetelný efekt automaticky.';
$Definition['Transparent'] = 'priehľadný';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect umožňuje používateľom prihlásiť sa pomocou svojho účtu Twitter. <b>Aby toto rozšírenie fungovalo, svoju požiadavku si musíte zaregistrovať na Twitteri.</b>';

$Definition['Usercards'] = 'Karty užívateľov';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Karty Usercard vám umožňujú získať rýchly online prehľad informácií o používateľovi. Pri prezeraní príspevkov a rebríčkov kliknite na používateľské meno a zobrazí sa karta zobrazujúca základné profilové informácie používateľov bez toho, aby ste museli opustiť stránku. Povolením tejto funkcie pridáte do vlastného motívu používateľské karty.';
$Definition['User inputs are based on the global background and text colors.'] = 'Používateľské vstupy sú založené na globálnych farbách pozadia a textu.';
$Definition['User Profile'] = 'Užívateľský profil';
$Definition['Users may sign into your site using their Twitter account.'] = 'Používatelia sa môžu prihlásiť na vaše stránky pomocou svojho účtu Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Pomocou tlačidla v hornej časti stránky vytvorte pravidlo zákazu.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Použite WordPress plugin na nastavenie Vanilla komentárov na váš blog alebo univerzálny kód na nastavenie Vanilla komentárov na akúkoľvek inú platformu.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Nová vyhľadávacia služba Vanilla je konečne tu. Povolením nášho používateľského rozhrania na novej stránke vyhľadávania získate prístup k najnovším funkciám vyhľadávania, ako je napríklad vyhľadávanie členov, triedenie vyhľadávania a zvýrazňovanie výrazov.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Vanilla Export: %s, Zdroj: %s';
$Definition['Vanilla Statistics are currently disabled'] = 'Štatistika Vanilla je momentálne zakázaná';
$Definition['Verify and restore'] = 'Overte a obnovte';
$Definition['VerifyUser'] = 'Začiarknutím políčka vedľa používateľa ho označíte ako <b>overený,</b> aby jeho príspevky opäť neboli označené ako spam. Tým sa tiež obnovia všetky ich čakajúce príspevky.';
$Definition['Video tutorial on advanced settings'] = 'Video návod na rozšírené nastavenia';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video návod ako nájsť & ako spravovať používateľov';
$Definition['Video tutorial on managing appearance'] = 'Video návod ku spravovaniu vzhľadu';
$Definition['Video tutorial on managing categories'] = 'Video návod ako spravovať kategórie';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video návod na spravovanie rolí a povolení';
$Definition['Video tutorial on user registration'] = 'Video návod k registrácii používateľov';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Varovanie: Povolenie tejto funkcie môže spôsobiť chyby jazyka Javascript na vašom webe.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Výstraha</b> : Konfigurácia servera nepodporuje rýchle načítanie údajov. Ak importujete veľmi veľký súbor (napr. Viac ako 200 000 komentárov), môžete zvážiť zmenu konfigurácie. Kliknite <a href="http://vanillaforums.com/porter">sem</a> pre viac informácií.';
$Definition['Warning: This is for advanced users.'] = '<b>Upozornenie</b>: Toto je pre pokročilých používateľov a vyžaduje vykonanie ďalších zmien na webovom serveri. Toto je zvyčajne k dispozícii, iba ak máte vyhradený alebo vps hosting. Neskúšajte to, ak neviete, čo robíte.';
$Definition['Webhooks'] = 'Webhooky';
$Definition['Welcome to Labs!'] = 'Vitajte v laboratóriách!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Vitajte v používateľskom rozhraní s témou Vanilla. Táto stránka obsahuje zoznam všetkých dostupných tém a umožňuje vám ich kopírovať alebo upravovať.';
$Definition['Welcome To Your Theme'] = 'Vitajte vo svojom téme';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Na podporu účasti odporúčame väčšinou pozitívne reakcie.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Ak je povolená, môžete spravovať produkty a zoskupovať podkomunity podľa týchto produktov.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Keď niekto zdieľa odkaz z vašej stránky, pokúsime sa získať obrázok zo stránky. Ak na stránke nie je obrázok, použijeme namiesto neho tento obrázok. Obrázok by mal mať aspoň 50×50, ale odporúčame 200×200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Ak vyberiete možnosť Plné krvácanie, pozadie bude priehľadné.';
$Definition['Which reactions you use really depends on your community.'] = 'Ktoré reakcie skutočne používate, záleží na vašej komunite, ale odporúčame vám pamätať na niekoľko bodov.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Chystáte sa použiť novú možnosť rozloženia. Toto je možné prispôsobiť a zobraziť ukážku pomocou nášho editora tém. <0> Viac informácií</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Všetkých používateľom s adresami IP s predponou „111.111.111“ môžete zakázať pridaním zákazu typu IP s hodnotou „111.111.111. *“.';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Môžete zakázať IP adresy, e-mailové adresy a používateľské mená.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Môžete si vybrať z jedného z rôznych štýlov, ktoré táto téma ponúka.';
$Definition['You can configure some values differently for different screensizes.'] = 'Niektoré hodnoty môžete nakonfigurovať rôzne pre rôzne veľkosti obrazovky.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Môžete sa pripojiť k viacerým webom, ktoré podporujú jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Ak je váš súbor príliš veľký na priame načítanie na túto stránku, môžete ho umiestniť do svojho priečinka /uploads. Uistite sa, že názov súboru začína slovom <b>export</b> a končí ako <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Môžete zadať minimálnu dĺžku príspevku, aby ste odradili krátke príspevky.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Do systému Theming môžete nahrať vlastné písmo. Stačí skopírovať a vložiť adresu URL do poľa.';
$Definition['You must select a file to import.'] = 'Musíte vybrať súbor na importovanie.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Do adresy <0> Povolené domény musíte pridať doménu adresy URL písma </0> v konfigurácii stránky. <1> Prečítajte si viac informácií o vlastných písmach. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Váš mobilný motív bude zakázaný. Ak chcete nastaviť rôzne motívy pre mobil a pracovnú plochu, použite staré tematické rozhranie.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Názov vašej organizácie sa používa na mikrodáta SEO a SON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Favicon vašej stránky sa zobrazí v záhlaví prehliadača. Primerane sa zmenší.';
