<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s prijal %4$s pozvanie do členstva.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s zmenil %4$s práva.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s si zmenil(a) %6$s profilový obrázok.';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s komentoval %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s vytvoril účet pre %4$s.';
$Definition['%1$s joined.'] = '%1$s sa pripojil(a).';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s zmienil %3$s v %8$s.';
$Definition['%1$s on %2$s'] = '%1$s na %2$s';
$Definition['%1$s signed in.'] = '%1$s sa prihlásil(a).';
$Definition['%1$s to %2$s'] = '%1$s až %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s až %2$s z %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s aktualizoval(a) %6$s profil.';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s bol pridaný(á) do %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s bol odstránený(á) z %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s bol odstránený(á) z %2$s %3$s a pridaný(á) do %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s napísal na %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s prijal %2$s žiadosť o členstvo.';
$Definition['%3$s created an account for %1$s.'] = '%3$s vytvoril(a) účet pre %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 až %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 až %s$2 z %s$3';
$Definition['%s (Current)'] = '%s (Aktuálne)';
$Definition['%s Agrees'] = '%s Súhlasí';
$Definition['%s and you'] = '%s a ty';
$Definition['%s by %s'] = '%s od %s';
$Definition['%s changed %s\'s permissions.'] = '%s zmenil práva %s.';
$Definition['%s Comment'] = '%s Komentár';
$Definition['%s comment'] = '%s komentár';
$Definition['%s comment html'] = '%s komentár';
$Definition['%s Comments'] = '%s Komentáre';
$Definition['%s comments'] = '%s komentáre';
$Definition['%s comments html'] = '%s komentáre';
$Definition['%s Connect'] = '%s Pripojiť';
$Definition['%s day'] = '%s deň';
$Definition['%s days'] = '%s dni';
$Definition['%s deleted this conversation.'] = '%s odstránil túto konverzáciu.';
$Definition['%s discussion'] = '%s diskusia';
$Definition['%s discussion html'] = '%s diskusia';
$Definition['%s discussions'] = '%s diskusie';
$Definition['%s discussions html'] = '%s diskusie';
$Definition['%s has been Jailed.'] = '%s bol uveznený(á).';
$Definition['%s has left this conversation.'] = '%s odišiel z tejto konverzácie.';
$Definition['%s hour'] = '%s hodina';
$Definition['%s hours'] = '%s hodiny';
$Definition['%s Insightfuls'] = '%s Zbystril';
$Definition['%s level deep'] = '%s úroveň hlboko';
$Definition['%s levels deep'] = '%s úrovne hlboko';
$Definition['%s Likes'] = '%s Páči sa mi';
$Definition['%s member'] = '%s užívatel';
$Definition['%s members'] = '%s užívatel';
$Definition['%s mentioned %s in a %s.'] = '%s zmienil %s v %s.';
$Definition['%s message'] = '%s správa';
$Definition['%s messages'] = '%s správy';
$Definition['%s minute'] = '%s minúta';
$Definition['%s minutes'] = '%s minúty';
$Definition['%s month'] = '%s mesiac';
$Definition['%s months'] = '%s mesiace';
$Definition['%s New'] = '%s Nový';
$Definition['%s new'] = '%s nový';
$Definition['%s new comment since you last read this.'] = '%s nový komentár od posledného prečítania.';
$Definition['%s new comments since you last read this.'] = '%s nové komentáre od posledného prečítania.';
$Definition['%s New Plural'] = '%s Nové';
$Definition['%s new plural'] = '%s nový';
$Definition['%s Not Found'] = '%s Nebolo Nájdené';
$Definition['%s not found.'] = '%s nenájdené';
$Definition['%s Point'] = '%s Bod';
$Definition['%s point'] = '%s bod';
$Definition['%s Points'] = '%s Body';
$Definition['%s points'] = '%s body';
$Definition['%s result'] = '%s výsledok';
$Definition['%s results'] = '%s výsledky';
$Definition['%s said'] = '%s povedal';
$Definition['%s said:'] = '%s povedal:';
$Definition['%s tag(s) found.'] = '%s značka(y) nájdené.';
$Definition['%s tags in the system'] = '%s značiek v systéme';
$Definition['%s Up Votes'] = '%s Hodnotení Nahor';
$Definition['%s view'] = '%s zobrazenie';
$Definition['%s view html'] = '%s prezretia';
$Definition['%s viewing'] = '%s prezerá';
$Definition['%s views'] = '%s zobrazenia';
$Definition['%s views html'] = '%s prezretí';
$Definition['%s votes'] = '%s hodnotenia';
$Definition['%s was removed from the %s and added to the %s'] = '%s bol odstránený(á) z %s a pridaný(á) do %s';
$Definition['%s week'] = '%s týždeň';
$Definition['%s weeks'] = '%s týždne';
$Definition['%s WTFs'] = '%s WTF';

$Definition['(All)'] = '(Všetko)';
$Definition['(empty message)'] = '(prázna správa)';

$Definition['+%s Guests'] = '+%s Hostí';

$Definition[' - Page %s'] = '- Stránka %s';

$Definition['1 message'] = '1 správa';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Členstvo Potvrdené';
$Definition['[%s] Welcome Aboard!'] = '[%s] Vitaj!';
$Definition['[Deleted User]'] = '[Odstránený Užívateľ]';

$Definition['About'] = 'O';
$Definition['AboutToDelete'] = 'Chystáš sa vymazať %s';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Chystáš sa zmazat %1$s z %2$s označených diskusí.';
$Definition['Abuse'] = 'Zneužiť';
$Definition['Accept'] = 'Potvrdiť';
$Definition['Accept this answer.'] = 'Potvrdiť túto odpoveď.';
$Definition['Account Options'] = 'Nastavenia Účtu';
$Definition['Activate'] = 'Aktivovať';
$Definition['Active'] = 'Aktívny';
$Definition['Active Users'] = 'Aktívni Užívatelia';
$Definition['Activity'] = 'Aktivita';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s potvrdil %4$s %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s komentoval tvoj %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s komentoval tvoj %8$s.';
$Definition['Activity.Comment'] = 'Komentár';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s zmienil %3$s v %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s zmienil %3$s v %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s ti poslal %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s ti poslal %8$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s sa pripojil(a).';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s sa pripojil(a).';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s si zmenil(a) %6$s profilový obrázok.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s si zmenil(a) %6$s profilový obrázok.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s odpovedal %4$s %8$s.';
$Definition['Add'] = 'Pridať';
$Definition['Add %s'] = 'Pridať %s';
$Definition['Add a Comment'] = 'Pridať Komentár';
$Definition['Add a Message'] = 'Pridať Správu';
$Definition['Add another poll option ...'] = 'Pridať dalšiu možnosť hlasovania...';
$Definition['Add a Profile Picture'] = 'Pridať Profilový Obrázok';
$Definition['Add a time?'] = 'Pridať čas?';
$Definition['Add a Warning'] = 'Pridať Varovanie';
$Definition['Add Badge'] = 'Pridať Odznak';
$Definition['Add Comment'] = 'Pridať Komentár';
$Definition['Add Cost'] = 'Pridať Cenu';
$Definition['Add Image'] = 'Pridať Obrázok';
$Definition['Add Message'] = 'Pridať Správu';
$Definition['Add Note'] = 'Pridať Poznámku';
$Definition['Add People to this Conversation'] = 'Pridať Užívateľov do tejto Konverzácie';
$Definition['Add Route'] = 'Pridať Cestu';
$Definition['Administrator'] = 'Administrátor';
$Definition['Administrator Activity'] = 'Aktivita Administrátora';
$Definition['administrators'] = 'administrátori';
$Definition['Advanced Stuff'] = 'Rozšírené Možnosti';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Nastala kritická chyba pri spracovávaní požiadavky.<br />Server odovzdal nasledujúcu odpoveď: %s';
$Definition['Agree'] = 'Potvrdiť';
$Definition['Alert'] = 'Oznámiť';
$Definition['Align center'] = 'Zamerať do stredu';
$Definition['Align left'] = 'Zamerať vľavo';
$Definition['Align right'] = 'Zamerať vpravo';
$Definition['All %s'] = 'Všetky %s';
$Definition['All %s...'] = 'Všetky %s';
$Definition['All Bookmarks'] = 'Všetky Záložky';
$Definition['All Categories'] = 'Všetky Kategórie';
$Definition['all categories'] = 'všetky kategórie';
$Definition['All Conversations'] = 'Všetky Konverzácie';
$Definition['All Discussions'] = 'Všetky Diskusie';
$Definition['All Events'] = 'Všetky eventy';
$Definition['All Members'] = 'Všetci užívatelia';
$Definition['All members'] = 'Všetci užívatelia';
$Definition['Allow'] = 'Povoliť';
$Definition['Allow other members to see your email?'] = 'Povoliť aby ostatní užívatelia mohli vidieť váš email?';
$Definition['All Time Leaders'] = 'Líder všetkých čias';
$Definition['Already Warned'] = 'Upozornený';
$Definition['Ancient Membership'] = 'Staré Členstvo';
$Definition['An invitation has already been sent to the email you entered.'] = 'Pozvanie už bolo odoslané na email ktorý si zadal.';
$Definition['Announce'] = 'Ohlásiť';
$Definition['Announce...'] = 'Ohlásiť...';
$Definition['Announcement'] = 'Ohlásenie';
$Definition['Announcements'] = 'Ohlásenia';
$Definition['Announce this discussion'] = 'Ohlásiť diskusiu';
$Definition['Answer'] = 'Odpoveď';
$Definition['answer'] = 'odpoveď';
$Definition['Answers'] = 'Odpovede';
$Definition['answers'] = 'odpovede';
$Definition['Applicant'] = 'Uchadzač';
$Definition['Applicants'] = 'Uchádzači';
$Definition['Applicants & Invitations'] = 'Uchádzači & Pozvania';
$Definition['Apply Changes'] = 'Aplikovať Zmeny';
$Definition['Apply for Membership'] = 'Registrovať sa';
$Definition['Apply for membership'] = 'Požiadať o členstvo';
$Definition['Approve'] = 'Schváliť';
$Definition['Approve Applicant'] = 'Schváliť';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Si si NAOZAJ istý(á), že chceš pokračovať?';
$Definition['Are you attending this event?'] = 'Zúčastníš sa na tomto evente?';
$Definition['Are you sure you want to delete this %s?'] = 'Naozaj chceš zmazať %s?';
$Definition['Are you sure you want to do that?'] = 'Naozaj to chceš spraviť?';
$Definition['Are you sure you want to do this?'] = 'Naozaj to chceš spraviť?';
$Definition['Are you sure you want to join this group?'] = 'Si si istý že sa chceš pridať tejto skupine?';
$Definition['Are you sure you want to leave this group?'] = 'Si si istý že chceš opustiť túto skupinu?';
$Definition['Are you sure you wish to continue?'] = 'Naozaj chceš pokračovať?';
$Definition['Ask a Question'] = 'Spýtať sa Otázku';
$Definition['Ask Question'] = 'Spýtať sa Otázku';
$Definition['Attach a file'] = 'Priložiť súbor';
$Definition['Attach image/file'] = 'Priložit obrázok';
$Definition['Attachments'] = 'Prílohy';
$Definition['Attach this warning to the %s.'] = 'Priraď toto varovanie k %s.';
$Definition['AttemptingSignOut'] = 'Naozaj sa chcete %s?';
$Definition['Attending'] = 'Zúčastniť sa';
$Definition['Attending (%s)'] = 'Účasť (%s)';
$Definition['Authenticate URL'] = 'Overiť Adresu';
$Definition['Author'] = 'Autor';
$Definition['available'] = 'dostupný';
$Definition['Awaiting Moderation'] = 'Čaká na Moderovanie';
$Definition['Awesome'] = 'Úžastný';

$Definition['Back to Discussions'] = 'Späť na Súťaže';
$Definition['Back to Profile'] = 'Späť na Profil';
$Definition['Badge'] = 'Odznak';
$Definition['Badge404'] = 'Odznak nebol nájdený.';
$Definition['Badges'] = 'Odznaky';
$Definition['BadgesModuleTitle'] = 'Odznaky';
$Definition['BadgesNobody'] = 'Nikto ešte nezískal tento odznak.';
$Definition['Ban.Action'] = 'BAN';
$Definition['Banned'] = 'Zabanovaný';
$Definition['Banned for being abusive.'] = 'Zabanovaný za urážanie.';
$Definition['Banned for spamming.'] = 'Zabanovaný za spamovanie.';
$Definition['Banned users can no longer access the site.'] = 'Zabanovaný užívatelia už nemôžu pristúpiť na túto stránku.';
$Definition['Ban User'] = 'Zabanovať Užívateľa';
$Definition['Ban Value'] = 'Hodnota Banu';
$Definition['Best Answer'] = 'Najlepšia Odpoveď';
$Definition['Best Answers'] = 'Najlepšie Odpovede';
$Definition['Best Of'] = 'Najlepší Z';
$Definition['Best Of...'] = 'Najlepší Z...';
$Definition['Blank Discussion Topic'] = 'Prázdna Téma Diskusie';
$Definition['Blank Message'] = 'Prázdna Správa';
$Definition['Blogs'] = 'Blogy';
$Definition['Body'] = 'Text';
$Definition['Bold'] = 'Tučné';
$Definition['Bookmark'] = 'Záložka';
$Definition['bookmarked discussion'] = 'Diskusia v záložke';
$Definition['Bookmarked Discussions'] = 'Uložené Diskusie';
$Definition['Bookmarks'] = 'Záložky';
$Definition['bookmarks'] = 'záložky';
$Definition['Browse Groups'] = 'Prehliadaj skupiny';
$Definition['Browse popular groups.'] = 'Prehliadaj polulárne skupiny. ';
$Definition['By'] = 'Od';
$Definition['by'] = 'od';
$Definition['by Date'] = 'v Dátume';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Nahrávaním súboru potvrdzuješ že más právo šíriť tento obrázok a že neporušuje Podmienky Používania.';

$Definition['Cancel'] = 'Zrušiť';
$Definition['Casual'] = 'Neformálny';
$Definition['Categories'] = 'Kategórie';
$Definition['CategoriesShowFollowed'] = 'Zobraziť iba sledované kategórie';
$Definition['CategoriesShowUnfollowed'] = 'Zobraziť skryté kategórie';
$Definition['CategoriesViewingAll'] = 'Práve prezeráš všetky kategórie.';
$Definition['CategoriesViewingFollowed'] = 'Práve prezeráš iba kategórie ktoré sleduješ.';
$Definition['Category'] = 'Kategória';
$Definition['Category Filter'] = 'Filter Kategórií';
$Definition['CategoryID'] = 'Kategória';
$Definition['Category Management'] = 'Spravovanie Kategórií';
$Definition['Category Notifications'] = 'Upozornenia Kategórie';
$Definition['Category to Use'] = 'Kategória pre Použitie';
$Definition['Change'] = 'Zmeniť';
$Definition['Change language'] = 'Zmeniť jazyk';
$Definition['Change My Password'] = 'Zmeniť Moje Heslo';
$Definition['Change My Picture'] = 'Zmeniť Môj Obrázok';
$Definition['Change Password'] = 'Zmeniť Heslo';
$Definition['Change Picture'] = 'Zmeniť Obrázok';
$Definition['Check all roles that apply to this user:'] = 'Zaškrtnúť všetky role ktoré sú nastavené tomuto užívateľovi:';
$Definition['Child Categories'] = 'Podkategórie';
$Definition['Child Categories:'] = 'Podkategórie:';
$Definition['Choose a name to identify yourself on the site.'] = 'Zvoľ si meno pre identifikáciu na stránke.';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Zvoľ hlavnú diskusiu do ktorej sa zlúčia všetky komentáre:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Zvoľ či sa chceš opýtať otázku alebo začať diskusiu.';
$Definition['Clear'] = 'Vyčistiť';
$Definition['clear'] = 'vyčistiť';
$Definition['Clear Conversation History'] = 'Vyčistiť Históriu Konverzácie';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Klikni <a href="%s">sem</a> a vráť sa späť do diskusie.';
$Definition['Click accept or reject beside an answer.'] = 'Klikni potvrdiť alebo odmietnúť vedľa odpovede.';
$Definition['clicking here'] = 'kliknutím tu';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Klikni na %s vedľa diskusie pre založenie.';
$Definition['Click to re-attach'] = 'Klikni na znovupriloženie';
$Definition['Close'] = 'Zavrieť';
$Definition['Closed'] = 'Uzavretý';
$Definition['Close this discussion'] = 'Zavrieť túto diskusiu';
$Definition['Color'] = 'Farba';
$Definition['Comment'] = 'Komentár';
$Definition['comment'] = 'komentár';
$Definition['Comment As ...'] = 'Komentovať Ako...';
$Definition['Comment by %s'] = 'Komentár od %s';
$Definition['Comment in'] = 'v';
$Definition['Commenting as %1$s (%2$s)'] = 'Komentovať ako %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Komentovanie nie je povolené.';
$Definition['Comments'] = 'Komentáre';
$Definition['comments'] = 'komentáre';
$Definition['Comments are between {UserID,you}.'] = 'Komentáre sú medzi {UserID,you}.';
$Definition['Community'] = 'Komunita';
$Definition['Community Guidelines'] = 'Pokyny Komunity';
$Definition['Completely delete the warning.'] = 'Úplne zmazať varovanie';
$Definition['Confirm'] = 'Potvrdiť';
$Definition['Confirmed email address'] = 'Potvrdená emailová adresa';
$Definition['Confirm Email'] = 'Potvrdiť Email';
$Definition['Confirm Password'] = 'Potvrdiť Heslo';
$Definition['Connect'] = 'Pripojiť';
$Definition['ConnectAccountExists'] = 'Už tu máš vytvorený účet.';
$Definition['ConnectChooseName'] = 'Zvoľ si meno pre identifikáciu na stránke.';
$Definition['ConnectCreateAccount'] = 'Pridať Informácie &amp; Vytvoriť Účet';
$Definition['Connected'] = 'Pripojený';
$Definition['ConnectExistingPassword'] = 'Napíš svoje terajšie heslo.';
$Definition['Connecting...'] = 'Pripájanie...';
$Definition['Connection'] = 'Pripojenie';
$Definition['ConnectLeaveBlank'] = 'Nechaj prázdne, dokým sa nepripájaš už k existujúcemu účtu.';
$Definition['ConnectName'] = 'Užívateľské meno';
$Definition['ConnectRegisteredName'] = 'Tvoje zaregistrované užívateľské meno: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Pripoj sa na socialne siete pre odberanie upozornení tu a zdielanie aktivity s tvojimi priateľmi a následovníkmi.';
$Definition['Contact Us'] = 'Kontaktuj Nás';
$Definition['conversation'] = 'konverzácia';
$Definition['Core'] = 'Jadro';
$Definition['Created'] = 'Vytvorený';
$Definition['Create Discussions'] = 'Vytvoriť Diskusie';
$Definition['Create One.'] = 'Vytvoriť Jednu.';
$Definition['Current'] = 'Súčasný';
$Definition['Currently: '] = 'Súčasne:';
$Definition['Custom Information'] = 'Vlastné Informácie';
$Definition['Customize'] = 'Prispôsobiť';
$Definition['customize your profile now'] = 'prispôsobiť svoj profil teraz';
$Definition['Customize your Public Profile'] = 'Prispôsobiť svoj Verejný Profil';
$Definition['Custom Profile Fields'] = 'Vlastné Polia v Profile';
$Definition['Custom Profile Field Settings'] = 'Nastavenia Vlastných Polí v Profile';

$Definition['Dashboard'] = 'Ovládací Panel';
$Definition['Dashboard Home'] = 'Domov Ovládacieho Panelu';
$Definition['Dashboard Summaries'] = 'Prehľad Ovládacieho Panelu';
$Definition['Date'] = 'Dátum';
$Definition['Date.DefaultDateTimeFormat'] = '%B %e, %Y %l:%M%p';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Date. Expects \'mm/dd/yyyy\'.'] = 'Dátum. Očakávaný ´dd/mm/rrrr´.';
$Definition['Date Added'] = 'Dátum Pridaný';
$Definition['Date Examples'] = 'Príklad: Pondelok, dnes, minulý týždeň, 26. Marec, 20.04.1993';
$Definition['Date within'] = 'Dátum medzi';
$Definition['days'] = 'dni';
$Definition['Define Thumbnail'] = 'Klikni a natiahni na obrázku pre prispôsobenie miniatúry.';
$Definition['Delete'] = 'Odstrániť';
$Definition['Delete %s'] = 'Odstrániť %s';
$Definition['Delete Account'] = 'Odstrániť Účet';
$Definition['Delete Conversation'] = 'Odstrániť Konverzáciu';
$Definition['Delete Discussion'] = 'Odstrániť Diskusiu';
$Definition['Delete Group'] = 'Vymazať skupinu';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Vymaže užívatela a všetky jeho aktivity. Spôsobí to vyhodenie z diskusí, čo bude vyzerať, že užívatelia reagujú na obsah ktorý neexistuje. Dobrý spôsob ako sa zbaviť spamerov.';
$Definition['Delete User Content'] = 'Vymazať užívatelov obsah';
$Definition['Delete User Forever'] = 'Vymazať užívatela navždy';
$Definition['Deny'] = 'Zakázať';
$Definition['Deny Applicant'] = 'Zakázať';
$Definition['Did this answer the question?'] = 'Bola tvoja otázka zodpovedaná?';
$Definition['Disagree'] = 'Nesúhlasiť';
$Definition['Discussion'] = 'Diskusia';
$Definition['discussion'] = 'diskusia';
$Definition['Discussion Board'] = 'Diskusné fórum';
$Definition['Discussions'] = 'Diskusie';
$Definition['discussions'] = 'diskusie';
$Definition['Discussions Page'] = 'Diskusná stránka';
$Definition['Discussion Title'] = 'Nadpis diskusie';
$Definition['Dislike'] = 'Nepáči sa mi to';
$Definition['Dismiss'] = 'Odmietnuť';
$Definition['Documentation'] = 'Dokumentácia';
$Definition['Don\'t announce.'] = 'Neoznamovať';
$Definition['Don\'t fold quotes'] = 'Neskladať uvodzovky';
$Definition['Don\'t have an account? %s'] = 'Nemáš účet? %s';
$Definition['Download'] = 'Stiahnuť';
$Definition['Download the sounds as MP3'] = 'Stiahnuť zvuk ako MP3';
$Definition['Do you want to expire or delete this warning?'] = 'Chceš nechať toto upozornenie vypršať alebo vymazať?';
$Definition['Draft saved at %s'] = 'Koncept bol uložený o %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Ťahaním zmeň veľkosť stvorca a definuj veľkost miniatúry.';
$Definition['Drop image/file'] = 'Pusti obrázok/súbor';

$Definition['Earned'] = 'Zarobené';
$Definition['Edit'] = 'Zmeň';
$Definition['Edit %s'] = 'Zmeň %s';
$Definition['Edit Account'] = 'Zmeniť účet';
$Definition['Edit Comment'] = 'Zmeniť komentár';
$Definition['Edit Discussion'] = 'Zmeniť diskusiu';
$Definition['edited %s'] = 'zemené %s';
$Definition['Edited %s by %s.'] = 'Zmenené %s od %s.';
$Definition['Edit My Account'] = 'Zmeniť svoj účet';
$Definition['Edit My Profile'] = 'Zmeniť svoj profil';
$Definition['Edit My Thumbnail'] = 'Zmeniť miniatúru';
$Definition['editor.BBCodeHelpText'] = 'Môžeš použiť <a href="http://en.wikipedia.org/wiki/BBCode" target="_new">BBCode</a> v tvojich príspevkoch.';
$Definition['editor.HtmlHelpText'] = 'Môžeš použiť <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple Html</a> v tvojich príspevkoch.';
$Definition['editor.MarkdownHelpText'] = 'Môžeš použiť <a href="http://en.wikipedia.org/wiki/Markdown" target="_new">Markdown</a> v tvojich príspevkoch.';
$Definition['editor.TextHelpText'] = 'Používaš plain text v tvojich príspevkoch.';
$Definition['editor.WysiwygHelpText'] = 'Môžeš použiť <a href="https://en.wikipedia.org/wiki/WYSIWYG" target="_new">Wysiwyg</a> v tvojich príspevkoch.';
$Definition['Edit Preferences'] = 'Zmeniť nastavenia';
$Definition['Edit Profile'] = 'Zmeniť profil';
$Definition['Edit Tag'] = 'Zmeniť tag';
$Definition['Edit Thumbnail'] = 'Zmeniť miniatúru';
$Definition['Eighth Anniversary'] = 'Ôsme výročie';
$Definition['EmailConfirmEmail'] = 'Predtým ako môžeš pokračovať, musíš potvrdiť tvoju emailovú adresu.Klikni na tento link pre potvrdenie: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = 'Príjemný deň!';
$Definition['EmailHeader'] = 'Ahoj {User.Name}!
';
$Definition['EmailInvitation'] = 'Ahoj!

%1$s Ťa pozval pripojiť sa do %2$s. Ak sa chceš pripojiť, klikni na tento odkaz:

%3$s';
$Definition['EmailMembershipApproved'] = 'Ahoj %1$s,

Tvoja registácia bola potvrdená. Prihlás sa na následnom odkaze:

  %2$s';
$Definition['EmailNotification'] = '%1$s

Klikni na odkaz dole:
%2$s

Pekný deň!';
$Definition['Email Notifications'] = 'Upozornenia e-mailom';
$Definition['Email Or Username'] = 'E-mail alebo užívateľské meno';
$Definition['EmailPassword'] = '%2$s resetoval tvoje heslo na %3$s. Tvoje prihlasovacie údaje sú teraz:

  Email: %6$s
  Heslo: %5$s
  Url: %4$s';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'E-mail odoslaný z aplikácie sa bude odosielať z nasledujúceho názvu a adresy';
$Definition['Email Source'] = 'E-mail';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Následuj odkaz nižšie:
%2$s

Pekný deň!';
$Definition['Email Unavailable'] = 'E-mail nie je k dispozícii';
$Definition['Email visible to other users'] = 'E-mail viditeľný pre ostatných používatelov';
$Definition['EmailWelcome'] = '%2$s Ti vytvoril účet na %3$s. Vaše prihlasovacie údaje sú: 

E-mail: %6$s
Heslo: %5$s
Url: %4$s';
$Definition['EmailWelcomeConnect'] = 'Úspešne si sa pripojil k {Title}. Tu sú vaše informácie: 

Meno: {User.Name} 
Spojený s: {ProviderName} 

Môžetš získať prístup k webu na {/,exurl,domain}.';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Prečítaj si celý článok tu</a></p><div class="ClearFix"></div></div>';
$Definition['EmbeddedNoBodyFormat'] = '{Url}';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Prečítaj si celý článok tu</a></p><div class="ClearFix"></div></div>';
$Definition['End time?'] = 'Čas ukončenia?';
$Definition['English'] = 'angličtina';
$Definition['Enter your Email address'] = 'Zadajte vašu emailovú adresu';
$Definition['Enter your email address'] = 'Zadajte vašu emailovú adresu';
$Definition['Enter your Email address or username'] = 'Zadajte svoj e-mailovú adresu alebo užívateľské meno';
$Definition['Enter Your OpenID Url'] = 'Zadajte svoje OpenID Url';
$Definition['Erase User Content'] = 'Vymaže používateľský obsah';
$Definition['Error'] = 'Chyba';
$Definition['ErrorBadInvitationCode'] = 'Zadaný kód je neplatný.';
$Definition['ErrorCredentials'] = 'Je nám ľúto, žiadny účet s e-mailom/užívateľským menom alebo heslom ktoré ste zadali sa nenašiel.';
$Definition['ErrorPermission'] = 'Prepáčte, prístup zamietnutý.';
$Definition['ErrorPluginDisableRequired'] = '{0} plugin nie je možné zakázať, pretože {1} plugin vyžaduje, aby fungoval.';
$Definition['ErrorPluginEnableRequired'] = 'Tento plugin vyžaduje, aby bol plugin {0} povolený kým je možné ho povoliť.';
$Definition['ErrorPluginVersionMatch'] = 'Povolený {0} plugin (verzia {1}) sa nepodarilo splniť požiadavky na verziu ({2}).';
$Definition['ErrorRecordNotFound'] = 'Požadovaný záznam sa nenašiel.';
$Definition['ErrorTermsOfService'] = 'Musíte súhlasiť s podmienkami poskytovania služby.';
$Definition['Event'] = 'Udalosť';
$Definition['Event Details'] = 'Podrobnosti udalosti';
$Definition['Events'] = 'Udalosti';
$Definition['everyone'] = 'Všetci';
$Definition['Everything'] = 'Všetko';
$Definition['Expired'] = 'Skončila';
$Definition['Expires'] = 'Vypršal';

$Definition['Failed to delete group.'] = 'Odstránenie skupiny zlyhalo.';
$Definition['Failed to find discussion for commenting.'] = 'Nepodarilo sa nájsť diskusiu pre komentovanie.';
$Definition['Failed to load the poll.'] = 'Nepodarilo sa načítať anketu.';
$Definition['Feedback'] = 'Spätná väzba';
$Definition['Female'] = 'Žena';
$Definition['Fifth Anniversary'] = 'Piate výročie';
$Definition['FileName'] = 'Názov súboru';
$Definition['Filename'] = 'Názov súboru';
$Definition['FileSize'] = 'Veľkosť súboru';
$Definition['File Size'] = 'Veľkosť súboru';
$Definition['First Anniversary'] = 'Prvé výročie';
$Definition['First Comment'] = 'Prvý komentár';
$Definition['Folder'] = 'Priečinok';
$Definition['Folders'] = 'Priečinky';
$Definition['Follow'] = 'Následovať';
$Definition['Follow %s'] = 'Následuj %s';
$Definition['Followed by %d people'] = 'Sledovaný  %d ľudmi';
$Definition['Followed by %d person'] = 'Sledovaný  %d ľudmi';
$Definition['followed categories'] = 'sledované kategórie';
$Definition['Following %d people'] = 'Sleduje  %d ľudí';
$Definition['Following %d person'] = 'Sleduje  %d ľudí';
$Definition['FollowOnly'] = 'Klikni na odkaz nižšie pre otvorenie:';
$Definition['Forgot?'] = 'Zabudli ste?';
$Definition['Forgot your password?'] = 'Zabudli ste heslo?';
$Definition['Format'] = 'Formát';
$Definition['Format his'] = 'jeho';
$Definition['Format their'] = 'ich';
$Definition['Format You'] = 'Ty';
$Definition['Format you'] = 'ty';
$Definition['Format Your'] = 'Tvoj';
$Definition['Forum'] = 'Fórum';
$Definition['Forums'] = 'Fórum';
$Definition['Forum Signature Settings'] = 'Fórum podpis nastavenie';
$Definition['Fourth Anniversary'] = 'Štvrté výročie';
$Definition['Friends'] = 'Priatelia';
$Definition['From'] = 'Od';
$Definition['Full Site'] = 'Plná stránka';

$Definition['Garden.Email.SupportAddress'] = 'Podpora e-mailom';
$Definition['Garden.Email.SupportName'] = 'Podpora meno';
$Definition['Garden.Registration.DefaultRoles'] = 'predvolenú rolu';
$Definition['Garden.Title'] = 'Názov Banneru';
$Definition['Gender'] = 'Pohlavie';
$Definition['General'] = 'Všeobecné';
$Definition['Generate import SQL only'] = 'Generovať iba importovať SQL';
$Definition['Generate Password'] = 'Vygenerovanie hesla';
$Definition['Get an audio challenge'] = 'Prijať zvukovú výzvu';
$Definition['Get a new challenge'] = 'Získajte novú výzvu';
$Definition['Get a visual challenge'] = 'Získať vizuálne výzvou';
$Definition['Give'] = 'Daj';
$Definition['Give a Badge to %s'] = 'Daj odznak  %s';
$Definition['Give Badge'] = 'Dať odznak';
$Definition['Given'] = 'Daný';
$Definition['Go'] = 'Ísť';
$Definition['Group'] = 'Skupina';
$Definition['group'] = 'skupina';
$Definition['GroupEmptyAnnouncements'] = 'Dôležité veci pôjdu tu jeden deň.';
$Definition['GroupEmptyDiscussions'] = 'Strašne tu je ťicho, nie?';
$Definition['GroupEmptyEvents'] = 'Jejda, žiadne udalosti neprichádzajú.';
$Definition['Group Info'] = 'Informácie o skupine';
$Definition['Group Leaders'] = 'Vodcovia';
$Definition['Group Members'] = 'Členovia';
$Definition['GroupMembersEmpty'] = 'Nikto sa pripojil ešte. Šír slovo!';
$Definition['Group Options'] = 'Možnosti skupiny';
$Definition['Groups'] = 'Skupiny';
$Definition['groups'] = 'skupiny';
$Definition['Guest'] = 'Hosť';
$Definition['GuestModule.Message'] = 'Vyzerá to, že ste tu nový. Ak sa chcete pripojiť, kliknite na jedno z týchto tlačidiel!';

$Definition['Hang on a sec while we sign you out.'] = 'Vydrž kým ťa odhlásime.';
$Definition['he'] = 'on';
$Definition['Heading'] = 'Nadpis';
$Definition['Heading %s'] = 'Nadpis %s';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} získal <a href="{Url,html}">{Data.Name,text}</a> odznak.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} zabanoval {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} komentoval <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} Pridal nový príspevok. <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} ťa spomenul v <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} zmenil obrázok {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} sa pripojil.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} odbanoval {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} varoval {RegardingUserID,you}.';
$Definition['Help'] = 'Pomoc';
$Definition['her'] = 'jej';
$Definition['Hide'] = 'Skryť';
$Definition['Hide my online status from other members'] = 'Skryť môj online status pre ostatných členov';
$Definition['Hide signatures?'] = 'Skryť podpisy?';
$Definition['Hide signatures always'] = 'Vždy skryť podpisy';
$Definition['Hide signatures on my mobile device'] = 'Skryť podpisy na moje mobilnom zariadení';
$Definition['his'] = 'jeho';
$Definition['Home'] = 'Domov';
$Definition['hours'] = 'hodín';
$Definition['Howdy, Stranger!'] = 'Nazdar cudzinec!';
$Definition['How long do you want this warning to last?'] = 'Ako dlho chcete toto upozornenie trvalo?';
$Definition['How many levels deep should we start folding up quote trees?'] = 'Koľko úrovní hlboko by sme začať skladanie citovania?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Súhlasím s <a id="TermsOfService" class="Popup" target="terms" href="%s">podmienkami</a>';
$Definition['Icon'] = 'Ikona';
$Definition['Ignore'] = 'Ignorovať';
$Definition['Ignore List'] = 'Ignorovací zoznam';
$Definition['Ignore Someone'] = 'Ignorovať niekto';
$Definition['Image'] = 'Obrázok';
$Definition['images'] = 'obrázky';
$Definition['Images not allowed'] = 'Obrázky niesú povolené';
$Definition['Images will be scaled to a maximum height of {maxImageHeight}px.'] = 'Obrázok bude zmenšený do maximálnej výšky {maxImageHeight} px.';
$Definition['Image URL'] = 'URL adresa obrázka';
$Definition['in'] = 'v';
$Definition['In <b>%s.</b>'] = 'V <b>%s</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'V <b>%s</b> a posledných diskusiach.';
$Definition['Inbox'] = 'Doručená pošta';
$Definition['Incorrect. Try again.'] = 'Nesprávne. Skús znova.';
$Definition['Indent'] = 'Zarážka';
$Definition['In recent discussions.'] = 'V posledných diskusiach.';
$Definition['In seconds'] = 'V sekundách';
$Definition['Insert Image'] = 'Vložiť obrázok';
$Definition['Insightful'] = 'Bystrý';
$Definition['Internal'] = 'Vnútorný';
$Definition['In this Conversation'] = 'V tejto konverzácii';
$Definition['Invalid password.'] = 'Zadané heslo je nesprávne. Pamätajte, že heslá snímaju veľlké a malé písmená.';
$Definition['Invitations'] = 'Pozvánky';
$Definition['Invite'] = 'Pozvať';
$Definition['InviteErrorPermission'] = 'Prepáčte, prístup zamietnutý.';
$Definition['Invite Friends'] = 'Pozvať priateľov';
$Definition['Invite friends'] = 'Pozvať priateľov';
$Definition['Invite one or more people to join this group.'] = 'Pozvať jedného alebo viacerých ľudí, aby sa pripojili k tejto skupine.';
$Definition['IP Address'] = 'IP adresa';
$Definition['I remember now!'] = 'Spomínam si teraz!';
$Definition['Italic'] = 'Kurzíva';
$Definition['Item'] = 'Položka';
$Definition['item'] = 'položka';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Vyzerá to, že ste tu nový. Ak sa chcete zapojiť, kliknite na jedno z týchto tlačidiel!';

$Definition['Jail'] = 'Väzenie';
$Definition['Jailed users have reduced abilities.'] = 'Uväznený užívatelia majú znížené schopnosti.';
$Definition['Join %s'] = 'Pripojiť k %s';
$Definition['Joined'] = 'Pripojil';
$Definition['Joined %s'] = 'Pripojil %s';
$Definition['Join this Group'] = 'Pripojte sa k tejto skupine';
$Definition['Join this group to view its content.'] = 'Pripoj sa k tejto skupine pre zobrazenie jej obsahu.';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Stačí odstrániť používateľský záznam a ponechať všetok obsah užívateľa.';
$Definition['Just expire the warning.'] = 'Len skončí varovanie.';
$Definition['Just you!'] = 'Len ty!';

$Definition['Keep me signed in'] = 'Zapamätaj si ma';
$Definition['Keep User Content'] = 'Udržať používateľa obsah';

$Definition['Label'] = 'Štítok';
$Definition['Last Active'] = 'Naposledy aktívny';
$Definition['Last IP'] = 'Posledná IP';
$Definition['lasts %s'] = 'trvá %s';
$Definition['Latest %1$s'] = 'Posledná %1$ s';
$Definition['Latest Post'] = 'Posledný príspevok';
$Definition['Leaders'] = 'Vodcovia';
$Definition['Leave %s'] = 'Nechajte %s';
$Definition['Leave a Comment'] = 'Zanechať komentár';
$Definition['Leave a comment'] = 'Zanechať komentár';
$Definition['Leave a redirect link.'] = 'Zanechať odkaz na presmerovanie.';
$Definition['Leave blank unless connecting to an exising account.'] = 'Nechaj prázdne, dokým sa nepripájaš už k existujúcemu účtu.';
$Definition['Leave Comments'] = 'Zanechať komentár';
$Definition['Leave Group'] = 'Opustiť skupinu';
$Definition['Length'] = 'Dĺžka';
$Definition['Level %s'] = 'Úroveň %s';
$Definition['Like'] = 'Ako';
$Definition['Link to content:'] = 'Odkaz na obsah:';
$Definition['Locale'] = 'Miestne nastavenie';
$Definition['Log'] = 'Denník';
$Definition['log'] = 'Denník';
$Definition['Login with Facebook'] = 'Prihlásiť sa cez Facebook';

$Definition['Make me invisible? (Will not show you on the list)'] = 'Znevideľniť ma? (Nezobrazí sa na zozname)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Anonymná anketa (užívatelové hlasy niesú zverejnené).';
$Definition['Male'] = 'Muž';
$Definition['Mark All Viewed'] = 'Označiť všetko ako prečítané';
$Definition['Mark as Troll'] = 'Označiť ako Troll';
$Definition['Mark Category Viewed'] = 'Označiť Kategóriu ako prezretú';
$Definition['Marking as spam cannot be undone.'] = 'Označenie  SPAM vymaze navždy. Odstránenie je dobrý spôsob, ako udržať vaše fórum čisté.';
$Definition['Mark Read'] = 'Označiť ako prečítané';
$Definition['Maybe'] = 'Možno';
$Definition['Maybe (%s)'] = 'Možno (%s)';
$Definition['Member Count'] = 'Členovia';
$Definition['Members'] = 'Členovia';
$Definition['Merge'] = 'Zlúčiť';
$Definition['Merge Discussions'] = 'Zlúčiť diskusie';
$Definition['Message'] = 'Správa';
$Definition['message'] = 'správa';
$Definition['Messages'] = 'Správy';
$Definition['messages'] = 'správy';
$Definition['Message to User'] = 'Správa používateľovi';
$Definition['Minor'] = 'Drobné';
$Definition['minutes'] = 'minút';
$Definition['Moderation'] = 'Moderovanie';
$Definition['Moderation Queue'] = 'Moderovacia fronta';
$Definition['Moderator'] = 'Moderátor';
$Definition['Moderator Activity'] = 'Činnosti moderátora';
$Definition['Moderators'] = 'Moderátori';
$Definition['moderators'] = 'Moderátori';
$Definition['months'] = 'mesiacov';
$Definition['More'] = 'Viac';
$Definition['More About %s'] = 'Viac o %s';
$Definition['More Comments'] = 'Ďalšie komentáre';
$Definition['More Discussions'] = 'Ďalšie diskusie';
$Definition['More Information'] = 'Ďalšie informácie';
$Definition['More Results'] = 'Ďalšie výsledky';
$Definition['More…'] = 'Viac...';
$Definition['Most Recent'] = 'Najnovšie';
$Definition['Most recent:'] = 'Najnovšie:';
$Definition['Most recent: %1$s by %2$s'] = 'Najnovšie: %1$ od %2$ s';
$Definition['Most recent by %1$s'] = 'Najnovšie od %1$ s';
$Definition['Most Recent Comment'] = 'Najnovšie komentáre';
$Definition['Move'] = 'Presunúť';
$Definition['MyBadgesModuleTitle'] = 'Moja odznaky';
$Definition['My Bookmarks'] = 'Moje záložky';
$Definition['My Discussions'] = 'Moje diskusie';
$Definition['My Drafts'] = 'Moje návrhy';
$Definition['My Forums'] = 'Moje fórum';
$Definition['My Groups'] = 'Moje skupiny';
$Definition['My Preferences'] = 'Moje preferencie';
$Definition['My Signature'] = 'Môj podpis';

$Definition['Name'] = 'Meno';
$Definition['Name Dropper'] = 'Názov kvapkadlo';
$Definition['Name of the Event'] = 'Názov podujatia';
$Definition['Name the Group'] = 'Nazvy skupinu';
$Definition['Name Unavailable'] = 'Názov nie je k dispozícii';
$Definition['new'] = 'nové';
$Definition['New %s'] = 'Novú %s';
$Definition['New Announcement'] = 'Nové oznámenie';
$Definition['New Conversation'] = 'Nová správa';
$Definition['New Discussion'] = 'Nová diskusia';
$Definition['new discussion'] = 'nové';
$Definition['New Event'] = 'Nová udalosť';
$Definition['New Group'] = 'Nová skupina';
$Definition['New Groups'] = 'Nové skupiny';
$Definition['New Message'] = 'Nová správa';
$Definition['New Password'] = 'Nové heslo';
$Definition['New Poll'] = 'Nová Anketa';
$Definition['Next'] = 'Ďalšie';
$Definition['Ninth Anniversary'] = 'Deviate výročie';
$Definition['No'] = 'Nie';
$Definition['NoBadgesEarned'] = 'Každú chvíľu now&hellip;';
$Definition['Nobody has confirmed their attendance yet.'] = 'Nikto potvrdil svoju účasť ešte.';
$Definition['NoPermissionToDeleteDiscussions'] = 'Nemáte povolenie na odstránenie %1$s vybraných diskusií.';

$Definition['Only show followed categories'] = 'Zobraziť iba sledované kategórie';

$Definition['PageDetailsMessage'] = '%1$s až %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s až %2$s z %3$s';
$Definition['Post Discussion'] = 'Spýtať sa Otázku';

$Definition['Register'] = 'Registrovať sa';
$Definition['Register with %s'] = 'Registrovať sa';

$Definition['Transport error: %s'] = 'Nastala kritická chyba pri spracovávaní požiadavky.<br />Server odovzdal nasledujúcu odpoveď: %s';
$Definition['Type'] = 'Typ';

$Definition['Username'] = 'Užívateľské meno';

$Definition['Value'] = 'Hodnota';

$Definition['You already have an account here.'] = 'Už tu máš vytvorený účet.';
$Definition['You are currently only viewing categories that you follow.'] = 'Práve prezeráš iba kategórie ktoré sleduješ.';
$Definition['You are currently viewing all categories.'] = 'Práve prezeráš všetky kategórie.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Tvoje zaregistrované užívateľské meno: <strong>%s</strong>';
