<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Avís: activar aquesta funció pot provocar errors de Javascript al vostre lloc.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Caps amunt!</strong> Eliminació d’un rol pot provocar que els usuaris no tinguin accés a l’aplicació.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Caps amunt!</strong> Si es canvia la discussió a una categoria de substitució, es poden acabar amb les discussions o aparèixer si la categoria de reemplaçament té permisos diferents que la categoria que se suprimeix.';

$Definition['About.DisableStatistics'] = 'Si heu de desactivar aquests informes de dades per algun motiu comercial, podeu fer-ho afegint la línia següent al fitxer de configuració de la vostra instal·lació: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'És de vital importància per a la vida d’aquest programari gratuït de codi obert que mesurem amb precisió l’abast i l’efectivitat de Vanilla. Us preguem que no desactiveu l’informació d’aquestes dades.';
$Definition['AboutCommentEmbedding'] = 'La vainilla es pot utilitzar com a substitut per al sistema de comentaris nadiu del vostre bloc. De fet, es pot utilitzar per afegir comentaris a qualsevol pàgina del web.';
$Definition['AboutEmbedding'] = 'La integració permet que tota o part de la vostra comunitat es pugui incrustar en altres aplicacions i pàgines web.';
$Definition['About Vanilla Statistics'] = 'Sobre les estadístiques de Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Accediu al vostre fòrum de la comunitat fent clic a l\'enllaç "Visita el lloc" situat a la part superior d\'aquesta pàgina o fent <a href={/,url}>clic aquí</a> . El fòrum de la comunitat és el que veuran tots els vostres usuaris i clients quan visiten <a href="{/,url,domain}">{/, url, domini}</a> .';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Afegiu límits a les dimensions de càrrega d’imatges a les discussions i comentaris.';
$Definition['AddonProblems'] = '<h2> Problemes? </h2><p> Si alguna cosa va malament amb un addon i no podeu utilitzar el vostre lloc, podeu desactivar-les manualment editant-les: </p> %s';
$Definition['AddressBarColorDescription'] = 'Alguns navegadors admeten un color per a la barra d’adreces. Només per a mòbils.';
$Definition['Alert users if they click external link.'] = 'Aviseu els usuaris si fan clic en un enllaç d’una publicació que els allunyarà del fòrum. Els usuaris no seran avisats quan segueixin enllaços que coincideixin amb un domini de confiança';
$Definition['Alignment'] = 'Alineació';
$Definition['Alignment (Mobile)'] = 'Alineació (mòbil)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Totes les categories es presenten amb una selecció de cinc debats recents en cadascuna d’elles';
$Definition['Allow links to be transformed'] = 'Permet que els enllaços es transformin en representacions incrustades en debats i comentaris. Per exemple, un enllaç de YouTube es transformarà en un vídeo incrustat.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Permet als usuaris amb el permís %s canviar els seus propis avatars de les seves pàgines de perfil a Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Anonimitzar les adreces IP';
$Definition['ApplicationHelp'] = 'Les aplicacions us permeten afegir grans grups de funcionalitats al vostre lloc. <br /> Un cop s\'hagi afegit una aplicació a la vostra carpeta %s, la podeu habilitar o desactivar aquí.';
$Definition['Apply Layout'] = 'Aplica el disseny';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Segur que voleu suprimir aquest tema? S\'eliminarà definitivament.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Esteu segur que heu introduït el nom d’amfitrió correcte? Potser ho heu equivocat? La base de dades reportada: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Per utilitzar la confirmació del correu electrònic, cal tenir un paper amb el tipus predeterminat "no confirmat".';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Desa automàticament esborranys de discussions, preguntes, idees i comentaris no publicats.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Els avatars es veuran reduïts si superen aquesta alçada.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Els avatars es veuran reduïts si sobrepassen aquesta amplada.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Els avatars es guardaran les miniatures a aquesta mida.';

$Definition['Background'] = 'Antecedents';
$Definition['Background Image'] = 'Imatge de fons';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Sigues creatiu! Proveu d\'anomenar les vostres files segons les coses de què parla la comunitat.';
$Definition['Bordered'] = 'Vorejat';
$Definition['Bordered (Unified)'] = 'Vorejat (unificat)';
$Definition['Borderless'] = 'Sense fronteres';
$Definition['Border Radius'] = 'Radi de frontera';
$Definition['Brand Color'] = 'Color de la marca';
$Definition['Buttons'] = 'Botons';
$Definition['Buttons & Inputs'] = 'Botons i entrades';
$Definition['Button Type'] = 'Tipus de botó';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Fent clic al botó següent, suprimireu el compte d\'usuari per %s per sempre.';

$Definition['Center Aligned'] = 'Centre Alineat';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Els canvis només s\'aplicaran als avatars recentment penjats.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Canvieu les mides en què es desaran les imatges d’avatar.';
$Definition['Change the way your community works with plugins.'] = 'Canvieu el funcionament de la vostra comunitat amb plugins. Hem inclòs els connectors populars amb el programari i n\'hi ha més disponibles en línia.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Les caselles de selecció permeten als administradors realitzar accions per lots en diverses discussions o comentaris alhora.';
$Definition['Check out our %s'] = 'Consulteu el nostre %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Consulteu la nostra <0>documentació</0> , o pregunteu a la nostra <1>comunitat d\'experts</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla és la plataforma comunitària més senzilla i potent del món. És fàcil d\'utilitzar. Comença amb aquest vídeo introductori i continua amb els passos següents. Gaudeix!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Trieu un paper al qual seran assignats els usuaris orfes:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Trieu un tema per a aquesta subcomunitat. <0> Llegiu-ne més </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Trieu com gestionar tot el contingut associat al compte d\'usuari per %s (comentaris, missatges, etc.).';
$Definition['Choose Image'] = 'Trieu Imatge';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Podeu seleccionar un algorisme de hash personalitzat per signar les sol·licituds. L’algorisme hash també s’ha d’utilitzar a la biblioteca de clients. Trieu md5 si no esteu segur de què escollir.';
$Definition['Choose the order items are sorted.'] = 'Trieu la classificació dels elements de la comanda.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Trieu la pàgina que han de veure les persones quan visiten <0 />';
$Definition['Choose the preferred layout for lists of categories.'] = 'Trieu la disposició preferida per a llistes de categories.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Trieu el disseny preferit per a les llistes de categories. Podeu editar el disseny en mosaic.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Trieu la disposició preferida per a llistes de debats.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Trieu el disseny preferit per a llistes de debats. Podeu editar el disseny de la fundació.';
$Definition['Color Overlay'] = 'Superposició de color';
$Definition['Continue Import'] = 'Continua la importació';
$Definition['Could not parse import file. The problem is near line %s.'] = 'No s\'ha pogut analitzar el fitxer d\'importació. El problema és a prop de la línia %s.';
$Definition['Create a localization CSV'] = 'Creeu un CSV de localització';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Els temes personalitzats són els temes que vau crear. Podeu editar-les, canviar-ne el nom o fer-ne una còpia.';

$Definition['Dark'] = 'Fosc';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Definiu qui pot carregar i gestionar fitxers a la pàgina <a href="%s">Funcions i permisos</a> .';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Definiu la pàgina d\'inici del vostre fòrum, pengeu el logotip i molt més ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Eliminació d’un rol pot provocar que els usuaris no tinguin accés a l’aplicació.';
$Definition['Deleting forever cannot be undone.'] = 'Eliminació és una bona manera de mantenir net el vostre fòrum.';
$Definition['Disable Google Sign In'] = 'Desactiva la sessió de sessió de Google';
$Definition['Disable OpenID'] = 'Desactiva OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Desactiveu el laboratori "Nou sistema d\'inserció" a la pàgina <0>Vanilla Labs</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Les categories de debat s’utilitzen per ajudar els usuaris a organitzar les seves discussions de manera significativa per a la vostra comunitat.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'No incorporeu el vostre tauler d\'administració del fòrum (desplegueu-lo a la pantalla completa)';
$Definition['Don\'t use too many reactions.'] = 'No utilitzeu massa reaccions. No voleu proporcionar informació als seus usuaris sobrecàrrega.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Arrossegueu i deixeu anar les categories següents per ordenar-les i niar-les.';

$Definition['EditContentTimeout.Notes'] = 'Si un usuari es troba en un paper que té permís per editar contingut, aquests permisos se substituiran.';
$Definition['Edit Route'] = 'Editar ruta';
$Definition['Edits to this theme apply to:'] = 'Les edicions d’aquest tema s’apliquen a:';
$Definition['Embed Settings'] = 'Configuració d\'inserció';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Incorporeu el fòrum de la vostra comunitat al vostre lloc web per augmentar el compromís ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Activeu i proveu les darreres funcions de vainilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Permet l\'edició avançada de publicacions en diversos formats, inclosos WYSIWYG, HTML senzill, Markdown i BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Activeu l\'Editor de disseny per aplicar un disseny personalitzat a les pàgines de la vostra comunitat. Utilitzeu el nostre nou editor per mostrar contingut mitjançant el nostre catàleg de ginys disponibles.';
$Definition['Enter a descriptive name.'] = 'Introduïu un nom descriptiu per a la butxaca. Aquest nom no apareixerà enlloc, excepte en gestionar les butxaques aquí, de manera que només s’utilitza per ajudar-vos a recordar la butxaca.';
$Definition['Enter a short name for the site.'] = 'Introduïu un nom curt per al lloc. Això es mostra als botons d\'inici de sessió.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Introduïu l\'adreça del vostre Wordpress Blog i us la traurem d\'allà.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'A continuació, introduïu la configuració de connexió del vostre servidor esfinx.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Aquí es registra cada edició o supressió. Utilitzeu "Restaura" per desfer qualsevol canvi.';
$Definition['Everyone who signs up gets a profile page.'] = 'Tothom que s’inscrigui a la vostra comunitat obté una pàgina de perfil públic on es pot carregar una imatge de si mateixa, gestionar la seva configuració de perfil i fer el seguiment de les coses interessants que es fan a la comunitat. <a href="{/profile,url}">Ara</a> hauríeu de <a href="{/profile,url}">personalitzar el vostre perfil</a> .';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Tots els usuaris del vostre lloc tenen assignat almenys un paper. Els rols s’utilitzen per determinar què se’ls permet als usuaris.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect permet als usuaris iniciar la sessió mitjançant el seu compte de Facebook. <b>Per poder funcionar aquest complement heu de registrar la vostra sol·licitud a Facebook.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'No s\'ha pogut connectar a la base de dades amb el nom d\'usuari i la contrasenya que heu introduït. Els heu escrit malament? La base de dades reportada: <code>%s</code>';
$Definition['Font Name'] = 'Nom de la font';
$Definition['Font URL'] = 'URL de la lletra';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Força el quadre de comandament només accessible a aquesta url <em>(no es recomana)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Per exemple, podeu prohibir tots els usuaris amb adreces de correu electrònic des de "exemple.com" afegint una prohibició del tipus de correu electrònic amb el valor "*@exemple.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'A efectes de SEO, s’exclou que els rastrejadors del motor de cerca es vegin obligats a veure el fòrum a l’URL remota.';
$Definition['Foundation Layout'] = 'Disseny de fonamentació';
$Definition['Full Anonymization'] = 'Anonimat total';
$Definition['FullAnonymization.Description'] = '<strong>L\'anonimització total</strong> substitueix totes les adreces IP per 0.0.0.0, negant de manera efectiva a l\'aplicació qualsevol accés per treballar amb adreces IP. Les regles de prohibició d\'IP no funcionaran en absolut en aquest cas.';
$Definition['Full Bleed'] = 'Sang complet';

$Definition['Garden.Import.Complete.Description'] = 'Heu completat correctament una importació. Feu clic a <b>Finalitzat</b> quan estigueu llestos.';
$Definition['Garden.Import.Continue.Description'] = 'Sembla que estigués al mig d’una importació. Tria una de les opcions següents.';
$Definition['Garden.Import.InputInstructions'] = 'Introduïu el correu electrònic i la contrasenya de l’usuari d’administració a partir de les dades que s’estan important.';
$Definition['Garden.Privacy.IPs.Description'] = 'Les adreces IP dels usuaris es recullen normalment per a regles de prohibició automatitzades, moderació i prevenció de correu brossa. L\'habilitació de l\'anonimització d\'IP anonimitzarà totes les adreces IP rastrejades al lloc per a qualsevol propòsit i reduirà l\'eficàcia d\'aquestes eines. Els canvis a aquesta configuració no són retroactius.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit permís per canviar els seus propis avatars de les seves pàgines de perfil a Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Heu desactivat específicament les estadístiques de Vanilla al fitxer de configuració.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Sembla que aquest fòrum s’executa en un entorn de prova o, d’altra manera, està informant d’una IP privada. De manera predeterminada, els fòrums que funcionen amb IP privats no es fan un seguiment.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Si esteu segurs que el vostre fòrum és accessible des d\'Internet, podeu obligar-lo a informar estadístiques aquí:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Sembla que el fitxer config.php és de només lectura. Això vol dir que Vanilla no podrà registrar automàticament InstallationID i InstallationSecret del vostre fòrum.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Per solucionar aquest problema, assigna el mode de fitxer 777 al fitxer conf / config.php.';
$Definition['Global Styles'] = 'Estils globals';

$Definition['Heads Up!'] = 'Caps amunt!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Caps amunt! Aquest és un paper especial que no permet sessions actives. Per aquest motiu, les opcions de permís s’han limitat als permisos de “visualització”.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Aquí es mostren totes les reaccions que podeu utilitzar al vostre lloc.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'A continuació, es mostren les files que els usuaris poden assolir al vostre lloc. Podeu personalitzar aquests rangs i fins i tot afegir-ne de nous. Aquí hi ha alguns consells.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Si es penja un logotip de pancarta, substituirà el títol del bàner a les pàgines del fòrum orientades a l\'usuari.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Si un usuari no visita el lloc durant aquest període de temps, es tancarà automàticament la sessió.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Si està activat, el contingut complet de les publicacions s\'enviarà en notificacions per correu electrònic als usuaris.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Si ets nou a HTML i / o a CSS, aquí teniu alguns tutorials per començar:';
$Definition['If you have an old theme'] = 'Si teniu un tema antic i heu de definir un tema d\'escriptori i mòbils separats, podeu fer-ho amb l\'antiga interfície d\'usuari.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Si voleu disminuir el nivell d\'avís, elimineu un avís.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Si voleu incrustar el vostre fòrum o utilitzar els comentaris de Vanilla al vostre bloc, haureu d’habilitar la incrustació. Si no utilitzeu la inserció, recomanem deixar aquesta opció.';
$Definition['Image (Mobile)'] = 'Imatge (mòbil)';
$Definition['Import'] = 'Importar';
$Definition['Importing to Vanilla'] = 'Importació a la vainilla';
$Definition['In additon to the widgets there are also'] = 'A més dels widgets també hi ha <0> Estils globals </0> . Per editar estils globals, feu clic en qualsevol altre lloc de la pàgina, com ara aquest text.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integra les pàgines i components de la fundació al teu tema';
$Definition['Internationalization & Localization'] = 'Internacionalització i localització';
$Definition['Invalid URL'] = 'URL no vàlid';
$Definition['Invitation email failed to send: %'] = 'Tot i que la invitació es va crear amb èxit, el correu electrònic no va poder enviar-se. El servidor va informar del següent error: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Quan utilitzeu el registre per invitació, els usuaris tindran un enllaç anomenat Les <a href="%s" class="Popup">meves invitacions</a> a les seves pàgines de perfil.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Sembla que la base de dades que heu especificat encara no existeix. Ja l’heu creat? Heu escrit un error malament al nom? La base de dades reportada: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'És una bona idea mantenir el nombre màxim de caràcters permès en un comentari fins a una mida raonable.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'És una bona idea mantenir el nombre màxim de caràcters permès en una publicació fins a una mida raonable.';

$Definition['Kick-start your community and increase user engagement.'] = 'Inicieu la vostra comunitat i augmenteu el nombre d\'usuaris.';

$Definition['Labs'] = 'Laboratoris';
$Definition['Layout Editor'] = 'Editor de maquetació';
$Definition['Learn about custom routing.'] = 'Obteniu més informació sobre l\'encaminament personalitzat.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Obteniu més informació sobre com canvieu l\'aspecte del vostre fòrum: carregueu el logotip, configureu la pàgina d\'inici, escolliu un tema i personalitzeu-lo.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Apreneu a utilitzar la funcionalitat bàsica del vostre fòrum.';
$Definition['Left Aligned'] = 'Alineat esquerre';
$Definition['Light'] = 'Llum';
$Definition['Links'] = 'Enllaços';
$Definition['Locales allow you to support other languages on your site.'] = 'Les ubicacions locals us permeten suportar altres idiomes del vostre lloc. Habiliteu i desactiveu les locals que voleu posar a disposició aquí.';
$Definition['Lockout Time (seconds)'] = 'Temps de bloqueig (segons)';
$Definition['LogoDescription'] = 'El logotip del banner apareix a la part superior del lloc.';
$Definition['LogoDisclaimer'] = 'Els temes elaborats amb l\'editor de temes i alguns temes personalitzats no utilitzen aquesta configuració.';
$Definition['Looking for the Old Embed System?'] = 'Esteu buscant l\'antic sistema incrustat?';

$Definition['Make sure you click View Page'] = 'Assegureu-vos de fer clic a <a href="%s">Veure pàgina</a> per veure com es veu la pàgina de categories després de desar-la.';
$Definition['Manage Routes'] = 'Gestiona les rutes';
$Definition['Managing Users'] = 'Gestió d\'usuaris';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Si marques les coses com a correu brossa, les tornaran al fòrum.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Si marques les coses com a no brossa, les tornaran a afegir al fòrum.';
$Definition['Messages can appear anywhere in your application.'] = 'Els missatges poden aparèixer a qualsevol lloc de la vostra aplicació i es poden utilitzar per informar els vostres usuaris de notícies i esdeveniments. Utilitzeu aquesta pàgina per tornar a organitzar els vostres missatges arrossegant-los cap amunt o cap avall.';
$Definition['MobileLogoDescription'] = 'El logotip de la bandera mòbil apareix a la part superior del lloc.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Els temes per a mòbils us permeten canviar l’aspecte del vostre lloc en dispositius més petits.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB El nou editor de disseny heretarà el tema establert a la vostra Guia d\'estil (formalment editor de temes). <1>Més informació</1>';
$Definition['Need More Help?'] = 'Necessiteu més ajuda?';
$Definition['Need more help?'] = 'Necessiteu més ajuda?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Les categories emplaçades més a fons d\'aquesta profunditat se situaran en una llista delimitada per comes.';
$Definition['New Embed System'] = 'Nou sistema incrustat';
$Definition['New Quick Links'] = 'Nous enllaços ràpids';
$Definition['New Search Page'] = 'Nova pàgina de cerca';
$Definition['No Anonymization'] = 'Sense anonimització';
$Definition['Not getting what you expect when you preview your theme?'] = 'No obteniu el que espereu quan previsualitzeu el tema?';
$Definition['Notify me when people comment on my addons.'] = 'Notifiqueu-me quan la gent comenti els meus addons.';
$Definition['No unconfirmed role available for email confirmation.'] = 'El lloc necessita un paper amb el tipus predeterminat "no confirmat" per utilitzar la confirmació per correu electrònic. Afegiu-ne un per habilitar aquesta configuració.';

$Definition['Old Theming UI'] = 'Interfície d\'usuari de Theming antiga';
$Definition['Once enabled, only members will see inside your community.'] = 'Un cop activat, només els membres veuran la comunitat.';
$Definition['OrgDescription'] = 'El vostre nom d’organització s’utilitza per a microdades de SEO i JSON + LD';
$Definition['Outline'] = 'Esquema';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Les visualitzacions anul·lades o els enllaços de temes poden tenir efectes secundaris no desitjats i no es poden previsualitzar.';

$Definition['Partial Anonymization'] = 'Anonimat parcial';
$Definition['PartialAnonymization.Description'] = '<strong>L\'anonimització parcial</strong> anonimitza només l\'últim octet de l\'adreça IP. Per exemple, 254.230.05.153 es convertiria en 254.230.05.0. Això proporciona una mica d\'anonimat alhora que permet que les regles de prohibició d\'IP funcionin.';
$Definition['Password.MinLength'] = 'Longitud mínima de caràcters permesa per a les contrasenyes dels usuaris a les pàgines de creació i restabliment de contrasenyes.';
$Definition['Please choose an authenticator to configure.'] = 'Seleccioneu un autenticador per configurar.';
$Definition['PluginHelp'] = 'Els complements us permeten afegir funcionalitat al vostre lloc. <br /> Un cop s\'hagi afegit un complement a la vostra carpeta %s, podeu activar-lo o desactivar-lo aquí.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Es mostra la butxaca entre cada discussió de la llista de debats principal. Com que les discussions solen tenir-se en les etiquetes, .. </li>, també heu d\'embolicar la butxaca en aquestes etiquetes.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Les butxaques us permeten afegir HTML de forma gratuïta a diversos llocs de l\'aplicació.';
$Definition['Preset'] = 'Preestablert';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Eviteu el correu brossa al vostre fòrum, limitant el nombre de discussions i comentaris que els usuaris puguin publicar en un període de temps determinat.';
$Definition['Primary Button'] = 'Botó principal';
$Definition['Primary Buttons'] = 'Botons primaris';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Guia d\'inici ràpid per a crear temes per a la vainilla';
$Definition['Quick Links is a default component on community pages.'] = 'Enllaços ràpids és un component predeterminat a les pàgines de la comunitat. Activeu el nostre nou component d’enllaços ràpids per afegir, editar o amagar enllaços d’aquest menú mitjançant el nostre editor de temes.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Plugin de comentaris de vainilla a punt per WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Plugin preparat per a la vainilla for WordPress';
$Definition['Realtime progress bars: %s'] = 'Barres de progrés en temps real: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'És una bona idea disposar de files especials per a moderadors i administradors perquè la vostra comunitat pugui veure fàcilment qui és el responsable.';
$Definition['Recommend starting with five ranks.'] = 'No voldreu tenir massa files. Recomanem començar per cinc. Podeu afegir-ne més si la vostra comunitat és realment nombrosa.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Elimina els enllaços de discussió i categories dels menús. Estableix les pàgines relacionades amb la discussió i les categories per tornar la pàgina 404 no trobada.';
$Definition['Requires “Flag” reaction permission.'] = 'Requereix permís de reacció "marcar".';
$Definition['Requires “Negative” reaction permission.'] = 'Requereix permís de reacció “negatiu”.';
$Definition['Requires “Positive” reaction permission.'] = 'Requereix permís de reacció “positiu”.';
$Definition['Restoring your selection removes the items from this list.'] = 'En restaurar, els elements s\'eliminen d\'aquesta llista i es tornen a posar al lloc.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Utilitzeu la següent opció per habilitar les cotitzacions per a l\'editor enriquit. Això només s\'aplicarà si el format predeterminat és "Ric".';
$Definition['Route Expression'] = 'Expressió de la ruta';
$Definition['Routes are used to redirect users.'] = 'Les rutes s\'utilitzen per redirigir els usuaris segons l\'URL sol·licitat.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Busqueu usuaris pel seu nom o introduïu el nom d’un rol per veure tots els usuaris amb aquest rol.';
$Definition['Secondary Button'] = 'Botó secundari';
$Definition['Secondary Buttons'] = 'Botons secundaris';
$Definition['Security.Hsts.HTTPSWarning'] = 'Avís: activeu aquesta característica només si esteu segurs que tots els vostres subdominis estan configurats per a HTTPS amb certificats vàlids.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Quan està habilitat, aquesta regla s\'aplica a tots els subdominis del vostre lloc també.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Us recomanem que comenceu amb una edat màxima d’1 setmana i, després, augmenteu-lo a 1 mes i un any un cop vegis que el vostre lloc funciona com s’esperava.';
$Definition['Security.Hsts.SubmitWarning'] = 'Avís: És fantàstic donar suport a la càrrega prèvia de HSTS com a bona pràctica. Tot i això, heu d’enviar el vostre lloc a hstspreload.org per assegurar-vos que es carrega prèviament amb èxit (és a dir, per obtenir la protecció completa de la configuració prevista).';
$Definition['See the documentation'] = 'Consulteu la Documentació';
$Definition['Select the default type for this role, if any.'] = 'Seleccioneu el tipus predeterminat d\'aquest rol, si n\'hi ha.';
$Definition['Select the import source'] = 'Seleccioneu l\'origen d\'importació';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'La columna serialitzada "%s" no s\'ha pogut publicar.';
$Definition['Session Timeout'] = 'Temps d\'espera de la sessió';
$Definition['Shadowed'] = 'Ombrada';
$Definition['ShareImageDescription'] = 'Quan algú comparteix un enllaç del vostre lloc, intentem agafar una imatge de la pàgina. Si no hi ha cap imatge a la pàgina, utilitzarem aquesta imatge. La imatge ha de tenir almenys 50×50, però recomanem 200×200.';
$Definition['Show all possible pocket locations.'] = 'Activa aquesta opció per mostrar totes les ubicacions de butxaca possibles. Si activeu aquesta opció, només es mostren les ubicacions als usuaris que puguin gestionar butxaques.';
$Definition['SignIn.LockoutTime'] = 'La quantitat de temps que un usuari està bloquejat per iniciar sessió després de superar el nombre d\'intents d\'inici de sessió.';
$Definition['Solid'] = 'Sòlid';
$Definition['Some browsers support a color for the address bar.'] = 'Alguns navegadors admeten un color per a la barra d\'adreces.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Alguns temes anteriors no admeten funcions d\'edició completes. Per veure què és compatible amb un tema, podeu passar el nom del seu nom per veure on seran efectives les edicions.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'És possible que alguns temes s’hagin d’actualitzar per funcionar amb la categoria següent. Podeu desactivar la funció mentre actualitzeu el tema.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'De vegades, voleu incrustar el vostre lloc Vanilla dins d\'un altre lloc. El sistema d\'inserció de Vanilla ofereix una manera fàcil d\'aconseguir-ho. Hi ha inconvenients de rendiment quan s\'utilitza un lloc incrustat, així que consulteu la documentació per trobar alternatives i casos d\'ús ideals.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Restricció especial: Només els usuaris amb permís Garden.Curation.Manage poden utilitzar aquesta reacció.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Especifiqueu una coincidència parcial o completa quan es crea una prohibició.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Dediqueu una estona a pensar en com descriviu el vostre lloc aquí. Posant-li al vostre lloc un títol significatiu i una descripció concisa pot ajudar a la vostra posició als motors de cerca.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Busqueu correus electrònics afegint un logotip i personalitzant els colors.';
$Definition['Start Import'] = 'Comença a importar';
$Definition['Start the first discussion.'] = 'Comença la <a href="{/post/discussion,url}">primera discussió</a> ara a la vostra comunitat.';
$Definition['Subcommunities'] = 'Subcomunitats';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'L\'etiquetatge permet als usuaris afegir una etiqueta a les discussions que inicien per tal de fer-les més descobertes.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Les plantilles són els temes estàndard. Per personalitzar-les, heu de crear una còpia.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'L’autenticador %s no té cap opció de configuració personalitzada.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'Nota: El laboratori <0 /> s\'ha de configurar perquè coincideixi amb el vostre tema personalitzat. Això es pot fer mitjançant el nou editor de temes. <1> Obteniu més informació.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'L\'addon no s\'ha pogut activar perquè ha generat un error fatal: <pre> %s </pre>';
$Definition['The addon has already been downloaded.'] = 'L’addon ja s’ha descarregat.';
$Definition['The banner logo appears at the top of your forum.'] = 'El logotip del banner apareix a la part superior del fòrum.';
$Definition['The banner title appears on the top-left of every page.'] = 'El títol del banner apareix a la part superior esquerra de cada pàgina.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'El títol del banner apareix al banner del vostre lloc i a la barra del títol del vostre navegador. Hauria de tenir menys de 20 caràcters. Si es penja un logotip de pancarta, substituirà el títol del bàner a les pàgines del fòrum orientades a l\'usuari. Tingueu en compte que alguns temes també poden amagar aquest títol.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>El formulari bàsic d’inscripció requereix que els</strong> usuaris nous copiïn text d’una imatge CAPTCHA per evitar que els spammers estiguin fora del lloc. Necessiteu un compte a <a href="http://recaptcha.net/">recaptcha.net</a> . El registre és GRATU andT i fàcil. Un cop us hàgiu registrat, torneu aquí i introduïu la configuració següent:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'L’usuari de la base de dades que heu especificat no té permís per accedir a la base de dades. Ja heu creat la base de dades? La base de dades reportada: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Els canvis següents d’estructura són necessaris per a la vostra base de dades.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'El títol de la pàgina principal es mostra a la pàgina d\'inici. Trieu un títol que voleu que aparegui als motors de cerca.';
$Definition['The import file does not contain any data.'] = 'El fitxer d\'importació no conté cap dada.';
$Definition['The import file is not in the correct format.'] = 'El fitxer d\'importació no té el format correcte.';
$Definition['The location of the authentication endpoint.'] = 'La ubicació del punt final d’autenticació.';
$Definition['ThemeHelp'] = 'Els temes us permeten canviar l’aspecte del vostre lloc. <br /> Un cop s\'ha afegit un tema a la vostra carpeta %s, ho podeu habilitar aquí.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'La previsualització del tema es limita a mostrar la plantilla i el css del tema.';
$Definition['Theming Guide'] = 'Guia de temàtica';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'El logotip del mòbil apareix a la part superior del vostre lloc. Els temes fets amb l\'editor de temes i alguns temes personalitzats no utilitzen aquesta configuració.';
$Definition['The New Embed System'] = 'El nou sistema incrustat';
$Definition['The new embed system has improved performance.'] = 'El nou sistema d\'inserció ha millorat el rendiment, el comportament de desplaçament millorat i un comportament més coherent que l\'antic. Actualment, les incrustacions de comentaris i wordpress no són compatibles amb el nou sistema d\'inserció.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'L’autenticador de contrasenya no té cap opció de configuració personalitzada.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'No calen canvis d\'estructura de la base de dades. Però pot haver-hi canvis de dades.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'A l\'aplicació hi ha dos tipus de botons: primari i secundari.';
$Definition['The route was saved successfully.'] = 'La ruta s\'ha desat correctament.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'La descripció del lloc sol aparèixer als motors de cerca. Hauríeu de provar de tenir una descripció que tingui entre 100 i 150 caràcters.';
$Definition['The text of the pocket.'] = 'Introduïu el text de la butxaca. Es sortirà exactament quan escriviu, així que assegureu-vos que entreu HTML HTML vàlid.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'La icona tàctil apareix quan marqueu un lloc web a la pantalla d\'inici d\'un dispositiu mòbil. Normalment són 152 píxels.';
$Definition['The user table was not in the import file.'] = 'La taula d\'usuaris no es trobava al fitxer d\'importació.';
$Definition['The Vanilla 2 Exporter'] = 'L’exportador de vainilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla Statistics converteix el quadre de comandament del vostre fòrum en una eina d’informació d’analítica i us permet revisar l’activitat del vostre fòrum durant períodes de temps específics. Podeu <a href="http://vanillaforums.org/docs/vanillastatistics">llegir més informació sobre estadístiques de vainilla</a> a la nostra documentació.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Funcionen igual que els temes habituals. Un cop s\'hagi afegit un a la carpeta de temes, podeu activar-lo aquí.';
$Definition['This is a style guide of your theme.'] = 'Aquesta és una guia d’estil del vostre tema. Té exemples dels elements visuals utilitzats al llarg de l’aplicació. Podeu fer clic en diversos widgets com ara la <0> barra de títols </0> o <1> Banner </1> per editar les seves propietats al tauler lateral.';
$Definition['This is the administrative dashboard for your new community.'] = 'Aquest és el tauler d\'administració de la vostra nova comunitat. Consulteu les opcions de configuració al costat. Des d\'allà, podeu configurar el funcionament de la vostra comunitat. <b>De manera predeterminada, només els usuaris del rol "Administrador" poden veure aquesta part de la vostra comunitat.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Aquí és on podeu habilitar i provar noves funcions, pàgines i components de vainilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Aquest laboratori no es pot desactivar perquè s\'aplica un disseny personalitzat.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Aquest laboratori no es pot desactivar perquè el tema actual ho requereix.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Aquest logotip apareix a la part superior del vostre lloc. Els temes fets amb l\'editor de temes i alguns temes personalitzats no utilitzen aquesta configuració.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Aquesta opció mostra / amaga les ubicacions per on poden anar les butxaques, però només per als usuaris que tenen permís per afegir / editar butxaques. Proveu de mostrar les ubicacions i visiteu el vostre lloc.';
$Definition['This page lists the endpoints of your API.'] = 'Aquesta pàgina enumera els punts finals de la vostra API. Feu clic als extrems per obtenir més informació. Podeu fer trucades en directe a l\'API des d\'aquesta pàgina o bé externament mitjançant un testimoni d\'accés.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Aquest paper és la informació personal. Només els usuaris amb permís per veure informació personal ho veuran.';
$Definition['This setting loads the page before executing Javascript.'] = 'Aquesta configuració carrega la pàgina abans d’executar Javascript, que pot millorar el vostre SEO. <br> <strong>** Advertència: habilitar aquesta funció pot causar errors de Javascript al vostre lloc. **</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Aquesta configuració carrega la pàgina abans d\'executar Javascript, cosa que pot millorar el vostre SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Aquest tema no es pot suprimir perquè és el tema actualment aplicat.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Aquest títol apareix al bàner del vostre lloc i a la barra de títol del vostre navegador. Ha de tenir menys de 20 caràcters. Si es penja un logotip, substituirà aquest títol a les pàgines del fòrum orientades a l\'usuari. A més, tingueu en compte que alguns temes poden amagar aquest títol.';
$Definition['Tiled Layout'] = 'Disseny de rajoles';
$Definition['Title Bar'] = 'Barra de títol';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Per inserir el fòrum Vanilla al vostre lloc web, utilitzeu el codi següent.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Massa adreces! Enviarem fins a adreces %s alhora.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Per evitar el maltractament, algunes eines amaguen automàticament el contingut i el llisten aquí fins que sigui aprovat manualment per un moderador.';
$Definition['TouchIconDescription'] = 'La icona tàctil apareix en marcar un lloc web a la pantalla inicial d’un dispositiu Apple. Generalment són 152 píxels. Apple afegeix les cantonades arrodonides i l\'efecte de la llum automàticament.';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect permet als usuaris iniciar la sessió mitjançant el seu compte de Twitter. <b>Per poder funcionar aquest complement heu de registrar la vostra sol·licitud a Twitter.</b>';

$Definition['Usercards'] = 'Targetes d\'usuari';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Les targetes d’usuari us permeten obtenir una instantània ràpida en línia de la informació d’un usuari. Quan visualitzeu publicacions i taulers de classificació, feu clic al nom d\'usuari per veure una targeta que mostra la informació bàsica del perfil dels usuaris sense haver de sortir de la pàgina. Activeu aquesta funció per afegir targetes d\'usuari al vostre tema personalitzat.';
$Definition['User inputs are based on the global background and text colors.'] = 'Les entrades dels usuaris es basen en els colors de fons i de text global.';
$Definition['User Profile'] = 'Perfil d\'usuari';
$Definition['Users may sign into your site using their Twitter account.'] = 'Els usuaris poden iniciar la sessió al vostre lloc mitjançant el seu compte de Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Utilitzeu el botó a la part superior de la pàgina per crear una regla de prohibició.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Utilitzeu el complement de WordPress per configurar comentaris de Vanilla al vostre bloc o utilitzeu el codi universal per configurar comentaris de Vanilla en qualsevol altra plataforma.';

$Definition['Vanilla\'s new search service is finally here.'] = 'El nou servei de cerca de vainilla ja és aquí. Activeu la nostra nova interfície d’usuari de la pàgina de cerca per accedir a les funcions de cerca més recents, com ara Cerca de membres, ordenació de cerques i ressaltat de termes.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Exportació de vainilla: %s, Font: %s';
$Definition['Vanilla Statistics are currently disabled'] = 'Actualment, les estadístiques de Vanilla estan desactivades';
$Definition['Verify and restore'] = 'Verifiqueu i restaureu';
$Definition['VerifyUser'] = 'Marqueu la casella que hi ha al costat de l\'usuari per marcar-los com a <b>verificats</b> perquè les seves publicacions no es tornin a marcar com a correu brossa. Això també restaurarà totes les publicacions pendents.';
$Definition['Video tutorial on advanced settings'] = 'Video tutorial sobre configuració avançada';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video tutorial sobre com trobar i gestionar usuaris';
$Definition['Video tutorial on managing appearance'] = 'Video tutorial per gestionar l\'aparença';
$Definition['Video tutorial on managing categories'] = 'Video tutorial sobre gestió de categories';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video tutorial sobre gestió de rols i permisos';
$Definition['Video tutorial on user registration'] = 'Video tutorial sobre registre d’usuaris';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Avís: l\'activació d\'aquesta funció pot causar errors de Javascript al vostre lloc.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Avís</b> : la vostra configuració del servidor no admet la càrrega ràpida de dades. Si importeu un fitxer molt gran (ex. Més de 200.000 comentaris), potser voldreu plantejar-vos canviar la configuració. Feu clic <a href="http://vanillaforums.com/porter">aquí</a> per obtenir més informació.';
$Definition['Warning: This is for advanced users.'] = '<b>Avís</b> : és per a usuaris avançats i requereix que feu canvis addicionals al servidor web. Normalment només està disponible si teniu allotjament dedicat o vps. No ho intenteu si no sabeu el que esteu fent.';
$Definition['Welcome to Labs!'] = 'Benvingut a Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Benvingut a la interfície d\'usuari temàtica de Vanilla. Aquesta pàgina enumera tots els temes disponibles i us permet copiar-los o editar-los.';
$Definition['Welcome To Your Theme'] = 'Benvinguts al vostre tema';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Recomanem principalment reaccions positives per fomentar la participació.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Quan està activat, podeu gestionar els productes i agrupar les subcomunitats per aquests productes.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Quan algú comparteix un enllaç del vostre lloc, intentem agafar una imatge de la pàgina. Si no hi ha cap imatge a la pàgina, utilitzarem aquesta imatge. La imatge ha de tenir almenys 50×50, però recomanem 200×200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Quan seleccioneu Full Bleed, el fons és transparent.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Si els camps del perfil intern s\'inclouran o no en aquest webhook.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Si els camps del perfil privat s\'inclouran o no en aquest webhook.';
$Definition['Which reactions you use really depends on your community.'] = 'Les reaccions que feu servir depèn realment de la vostra comunitat, però us recomanem que tingueu en compte un parell de punts.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Esteu a punt d’aplicar una nova opció de disseny. Es pot personalitzar i previsualitzar mitjançant el nostre editor de temes. <0> Més informació</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Podeu prohibir a tots els usuaris amb adreces IP prefixades amb "111.111.111" afegint una prohibició de tipus IP amb el valor "111.111.111. *".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Podeu prohibir les adreces IP, les adreces de correu electrònic i els noms d’usuari.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Podeu triar un dels diferents estils que ofereix aquest tema.';
$Definition['You can configure some values differently for different screensizes.'] = 'Podeu configurar diferents valors de manera diferent per a diferents pantalles.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Podeu connectar-vos a diversos llocs que admetin jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Si el fitxer és massa gran per penjar-lo directament a aquesta pàgina, podeu col·locar-lo a la vostra carpeta / càrregues. Assegureu-vos que el nom de fitxer comenci amb la paraula <b>exportació</b> i finalitzi amb un de <b>.txt, .gz</b> .';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Podeu especificar una longitud mínima de publicació per descoratjar les publicacions curtes.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Podeu carregar un tipus de lletra personalitzat al vostre sistema temàtic. Només heu de copiar i enganxar l’URL al camp.';
$Definition['You must select a file to import.'] = 'Heu de seleccionar un fitxer per importar.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Heu d’afegir el domini de l’URL de la font a <0> Dominis permesos </0> en la configuració del lloc <1> Més informació sobre tipus de lletra personalitzats. </1>';
$Definition['Your mobile theme will be disabled.'] = 'El vostre tema mòbil estarà desactivat. Per configurar diferents temes mòbils i d\'escriptori, utilitzeu la interfície d\'usuari de temàtica antiga.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'El vostre nom d’organització s’utilitza per a microdades de SEO i JSON + LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'El favicon del vostre lloc apareix a la barra de títols del vostre navegador. Es reduirà adequadament.';
