<?php

$Definition['%1$s "%2$s" not found.'] = '%1$s "%2$s" не знайдено.';
$Definition['%1$s Version %2$s'] = '%1$s Версія %2$s';
$Definition['%1$s version %2$s is available.'] = '%1$s версія %2$s доступна.';
$Definition['%s level'] = '%s рівень';
$Definition['%s levels'] = '%s рівні';
$Definition['%s unavailable'] = '%s недоступна';
$Definition['%s user(s) found.'] = '%s користувачів знайдено.';
$Definition['%s years.'] = '%s років.';

$Definition['(YYYY-mm-dd)'] = '(рік-місяць-день)';

$Definition['1 day'] = '1 день';
$Definition['1 hour'] = '1 рік';
$Definition['1 month'] = '1 місяць';
$Definition['1 month after being sent'] = 'Через 1 місяць після відправлення';
$Definition['1 week'] = '1 тиждень';
$Definition['1 week after being sent'] = 'Через 1 тиждень після відправлення';
$Definition['2 weeks after being sent'] = 'Через 2 тиждені після відправлення';
$Definition['4 hours'] = '4 години';
$Definition['5 minutes'] = '5 хвилин';
$Definition['15 minutes'] = '15 хвилин';

$Definition['[%s] Confirm Your Email Address'] = '[%s] Підтвердити адресу електронної пошти';
$Definition['[%s] Invitation'] = '[%s] Запрошення';
$Definition['[%s] Password Reset'] = '[%s] Скидання пароля';
$Definition['[%s] Password Reset Request'] = '[%s] Запит скидання пароля';

$Definition['Abilites'] = 'Здібності';
$Definition['Abilities'] = 'Здібності';
$Definition['Action'] = 'Дія';
$Definition['Add Category'] = 'Додати категорію';
$Definition['Add Info &amp; Create Account'] = 'Додати інформацію; створити аккаунт';
$Definition['Adding & Editing Categories'] = 'Створення та редагування категорій';
$Definition['Add Item'] = 'Додати елемент';
$Definition['Addons'] = 'Розширення';
$Definition['Add Role'] = 'Додати роль';
$Definition['Add User'] = 'Додати користувача';
$Definition['Advanced Forum Settings'] = 'Розширені налаштування форуму';
$Definition['Advanced Options'] = 'Розширені параметри';
$Definition['Advanced Settings'] = 'Розширені налаштування';
$Definition['a full year.'] = 'цілий рік.';
$Definition['Alive'] = 'Живий';
$Definition['All Forum Pages'] = 'Всі сторінки форуму';
$Definition['Allow embedded content'] = 'Дозволити вбудований контент';
$Definition['Allow images'] = 'Дозволити зображення';
$Definition['Allow users to dismiss this message'] = 'Дозволити користувачам відхиляти це повідомлення';
$Definition['All Pages'] = 'Всі сторінки';
$Definition['API Status'] = 'Статус API';
$Definition['Applicant'] = 'Здобувач';
$Definition['Application'] = 'Додаток';
$Definition['Application ID'] = 'ID додатку';
$Definition['Applications'] = 'Додатки';
$Definition['Applied On'] = 'Підтверджено';
$Definition['Approval'] = 'З підтвердженням';
$Definition['Archive Discussions'] = 'Архів обговорень';

$Definition['Background Color'] = 'Колір фону';
$Definition['Back to Mobile Site'] = 'Повернутись до мобільної версії';
$Definition['Badge Name'] = 'Ім\'я';
$Definition['BadgeRecipientsHeading'] = 'Most recent recipients';
$Definition['Ban Item'] = 'Елемент';
$Definition['Ban List'] = 'Бан-лист';
$Definition['Banner'] = 'Банер';
$Definition['Banner Logo'] = 'Банер-логотип';
$Definition['Banner Title'] = 'Текст заголовку';
$Definition['Ban Type'] = 'Тип';
$Definition['Bookmark a discussion using its star icon.'] = 'Додайте дискусію в закладки, використовуючи цю іконку зірочки.';
$Definition['Button Background Color'] = 'Фоновий колір кнопки';
$Definition['Button Text Color'] = 'Колір тексту кнопки';

$Definition['Categories &amp; Discussions'] = 'Категорії та обговорення';
$Definition['Categories are used to organize discussions.'] = 'Категорії використовуються для того, щоб допомогти вашим користувачам організувати обговорення відповідним для вашої спільноти чином.';
$Definition['Category Page Layout'] = 'Розмітка сторінки категорій';
$Definition['Category Url:'] = 'Адреса категорії:';
$Definition['Change Log'] = 'Журнал змін';
$Definition['Change the way that new users register with the site.'] = 'Змініть спосіб реєстрації нових користувачів на сайті';
$Definition['Changing the Discussions Menu Link'] = 'Зміна посилання меню обговорень';
$Definition['Check all permissions that apply for each role'] = 'Позначте всі права, які слід застосувати до кожної ролі';
$Definition['Check all permissions that apply to this role:'] = 'Позначте всі дії, дозволені цій ролі:';
$Definition['Check out the new community forum I\'ve just set up.'] = 'Привіт, друже!

Зазирни на новий форум, який я тільки що створили. Це прекрасне місце для того, щоб спілкуватися один з одним в режимі онлайн.';
$Definition['Choose a locale pack'] = 'Виберіть мовний пакет';
$Definition['Choose who can send out invitations to new members:'] = 'Виберіть, хто може надсилати запрошення новим користувачам:';
$Definition['comment(s)'] = 'коментар(-я, -ів)';
$Definition['Comments per Page'] = 'Коментарів на сторінці';
$Definition['Condition Expression'] = 'Стан виразу';
$Definition['Condition Field'] = 'Field';
$Definition['Condition Type'] = 'Тип';
$Definition['Configure an Authenticator'] = 'Налаштування аутентикатора';
$Definition['Configure how nested categories are displayed to users.'] = 'Налаштуйте відображення користувачам вкладених категорій.';
$Definition['Configuring Vanilla\'s Homepage'] = 'Налаштування головної сторінки Vanilla';
$Definition['Confirm email addresses'] = 'Require users to confirm their email addresses (recommended)';
$Definition['Conversation Messages'] = 'Повідомлень в бесідах';
$Definition['Conversations'] = 'Бесіди';
$Definition['Could not instantiate mail function.'] = 'Не вдалося скористатися функцією пошти.';
$Definition['CreateFile'] = 'Створити';
$Definition['Current Authenticator'] = 'Поточний аутентикатор';
$Definition['Current File:'] = 'Поточний файл:';
$Definition['Current Theme'] = 'Поточна тема';

$Definition['Debugger'] = 'Дебагер';
$Definition['Decline'] = 'Відхилити';
$Definition['Default Category Permissions'] = 'Права категорії по замовчуванню';
$Definition['Default Locale'] = 'Переклад по замовчуванню';
$Definition['default type'] = 'default';
$Definition['Delete Badge'] = 'Видалити значок';
$Definition['Delete Category'] = 'Видалити категорію';
$Definition['Delete Role'] = 'Видалити роль';
$Definition['Delete User'] = 'Видалити користувача';
$Definition['Delete User: %s'] = 'Видалити користувача: %s';
$Definition['Deleting role...'] = 'Видалення ролі...';
$Definition['Description'] = 'Опис';
$Definition['Did You Know?'] = 'Чи знали Ви?';
$Definition['Disable'] = 'Виключити';
$Definition['Disabled'] = 'Виключені';
$Definition['Discussion & Comment Editing'] = 'Редагування обговорення та коментаря';
$Definition['discussion(s)'] = 'обговорення(-ня, -нь)';
$Definition['Discussions per Page'] = 'Обговорень на сторінці';
$Definition['Display in dashboard. (not recommended)'] = 'Display in dashboard. (не рекомендовано)';
$Definition['Display root categories as headings.'] = 'Відображувати батьківські категорії як заголовки.';
$Definition['Don\'t Refresh'] = 'Не оновлювати';
$Definition['Don\'t use Categories'] = 'Не використовувати категорії';
$Definition['Do not display the categories in the side panel.'] = 'Не відображувати категорії в боковій панелі.';
$Definition['DownloadLocalePack'] = 'Завантажити';

$Definition['Edit/Delete Log'] = 'Редагувати/Видалити лог';
$Definition['Edit Category'] = 'Редагування категорії';
$Definition['Edit CSS'] = 'Редагувати CSS';
$Definition['Edit HTML'] = 'Редагувати HTML';
$Definition['Edit Message'] = 'Редагувати повідомлення';
$Definition['Edit Role'] = 'Змінити роль';
$Definition['Edit User'] = 'Редагувати користувача';
$Definition['Email Styles'] = 'Стилі електронного листа';
$Definition['Enable'] = 'Увімкнути';
$Definition['Enable/Disable'] = 'Увімкнути/Вимкнути';
$Definition['Enable OpenID'] = 'Увімкнути OpenID';
$Definition['Enable this message'] = 'Активувати це повідомлення';
$Definition['Enabling a Locale Pack'] = 'Включення пакету перекладу';
$Definition['Enter the email address of the person you would like to invite:'] = 'Введіть адресу Email людини, яку хочете запросити:';
$Definition['Enter the url to the page you would like to use as your homepage:'] = 'Введіть посилання на сторінку, яку хочете зробити головною:';
$Definition['Error sending email. Please review the addresses and try again.'] = 'Помилка під час надсилання повідомлення. Будь ласка, перевірте адресу та спробуйте ще раз.';
$Definition['Every %s hour'] = 'Щогодини';
$Definition['Every %s minute'] = 'Щохвилини';
$Definition['Every %s second'] = 'Щосекунди';
$Definition['Every 1 minute'] = 'Кожну 1 хвилину';
$Definition['Everything is ok.'] = 'Все в порядку.';
$Definition['Exclude archived discussions from the discussions list'] = 'Виключати архівні обговорення зі списку обговорень';
$Definition['Existing members send invitations to new members.'] = 'Діючі користувачі надсилають запрошення новим учасникам.';

$Definition['Facebook Settings'] = 'Налаштування Facebook';
$Definition['Favicon'] = 'Іконка сайту';
$Definition['FaviconBrowse'] = 'Browse for a new favicon if you would like to change it:';
$Definition['FaviconDescription'] = 'Your site\'s favicon appears in your browser\'s title bar. It will be scaled to 16x16 пікселів.';
$Definition['First Visit'] = 'Перше відвідування';
$Definition['Forum Settings'] = 'Налаштування форуму';

$Definition['Get More Applications'] = 'Отримати більше додатків';
$Definition['Get More Plugins'] = 'Отримати більше плагінів';
$Definition['Get More Themes'] = 'Отримати більше тем';
$Definition['Getting Started'] = 'Початок';
$Definition['Getting Started with Vanilla'] = 'Початок роботи з Vanilla';
$Definition['give'] = 'дати';
$Definition['Give a Badge'] = 'Дати відзнаку';

$Definition['HeadlineFormat.AddUser'] = '{ActivityUserID,user} added an account for {RegardingUserID,user}.';
$Definition['HeadlineFormat.PictureChange'] = '{RegardingUserID,You} changed {ActivityUserID,your} profile picture.';
$Definition['HeadlineFormat.RegistrationApproval'] = '{ActivityUserID,user} approved the applications for {RegardingUserID,user}.';
$Definition['HeadlineFormat.Status'] = '{ActivityUserID,user}';
$Definition['HeadlineFormat.WallPost'] = '{RegardingUserID,you} &rarr; {ActivityUserID,you}';
$Definition['Help &amp; Tutorials'] = 'Допомога та посібники';
$Definition['Hidden for mobile'] = 'Приховані для мобільних пристроїв';
$Definition['Hide signatures for guests'] = 'Приховати підписи для гостей';
$Definition['Hide signatures on embedded comments'] = 'Приховати підписи у вбудованих відгуках';
$Definition['Homepage'] = 'Головна сторінка';
$Definition['Homepage Title'] = 'Заголовок головної сторінки';
$Definition['How to use themes'] = 'Використання тем';
$Definition['Html'] = 'HTML';
$Definition['HTML Emails'] = 'Електронні адреси HTML';

$Definition['Information'] = 'Інформація';
$Definition['Internaltionalization & Localization'] = 'Інтернаціоналізація та локалізація';
$Definition['Invitation Code'] = 'Код запрошення';
$Definition['InvitationMessage'] = 'Привіт, друже!

Зазирни на новий форум спільноти, щойно створений мною. Це чудове місце, щоб потеревенити одне з одним онлайн.

Перейти за посиланням нижче, щоб увійти на сайт.';
$Definition['Invitations per month'] = 'Запрошень в місяць';
$Definition['Invitations will expire'] = 'Запрошення будуть втрачати силу';

$Definition['jsConnect Client Libraries'] = 'Клієнтські бібліотеки jsConnect';
$Definition['jsConnect Documentation'] = 'Документація jsConnect';

$Definition['Key Type'] = 'Тип ключа';
$Definition['Key Value'] = 'Значення ключа';

$Definition['Large images will be scaled down.'] = 'Великі зображення будуть зменшені до максимальної ширини %spx та максимальної висоти %spx.';
$Definition['Last Visit'] = 'Останній візит';
$Definition['Level'] = 'Рівень';
$Definition['Locale Name'] = 'Назва перекладу';
$Definition['Locales'] = 'Переклади';
$Definition['Location'] = 'Місцезнаходження';

$Definition['Maintenance Mode'] = 'Режим обслуговування';
$Definition['Manage'] = 'Курування';
$Definition['Manage Applicants'] = 'Керування здобувачами';
$Definition['Manage Applications'] = 'Керування додатками';
$Definition['Manage Categories'] = 'Керування категоріями';
$Definition['Manage Messages'] = 'Керування повідомленнями';
$Definition['Manage Plugins'] = 'Керування плагінами';
$Definition['Manage Roles & Permissions'] = 'Управління ролями і правами';
$Definition['Manage Spam'] = 'Керування спамом';
$Definition['Manage Themes'] = 'Керування темами';
$Definition['Manage Users'] = 'Керування  користувачами';
$Definition['Managing Categories'] = 'Керування категоріями';
$Definition['Max %s length'] = 'Максимальна довжина %s ';
$Definition['Max Comment Length'] = 'Максимальна довжина коментаря';
$Definition['Max height of %s'] = 'Максимальна висота %s';
$Definition['Max height of %s in pixels'] = 'Максимальна висота %s у пікселях';
$Definition['Max number of %s'] = 'Максимальна кількість %s';
$Definition['Method'] = 'Метод';
$Definition['minute(s)'] = 'хвилин(-у, -и)';
$Definition['Mixed Layout'] = 'Змішаний макет';
$Definition['Modern Layout'] = 'Сучасний макет';
$Definition['Modern non-table-based layout'] = 'Сучасний нетабличний макет';
$Definition['My Invitations'] = 'Мої запрошення';

$Definition['Need More Help?'] = 'Потрібна допомога?';
$Definition['never'] = 'ніколи';
$Definition['NewApplicantEmail'] = 'New applicant:';
$Definition['New comments in the last day'] = 'Нових коментарів за останній день';
$Definition['New comments in the last week'] = 'Нових коментарів за останній тиждень';
$Definition['New conversations in the last day'] = 'Нових бесід за останній день';
$Definition['New conversations in the last week'] = 'Нових бесід за останній тиждень';
$Definition['New discussions in the last day'] = 'Нових обговорень за останній день';
$Definition['New discussions in the last week'] = 'Нових обговорень за останній тиждень';
$Definition['New messages in the last day'] = 'Нових повідомлень за останній день';
$Definition['New messages in the last week'] = 'Нових повідомлень за останній тиждень';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'Нові користувачі проглядаються і затверджуються адміністратором (це ви!).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'Нові користувачі заповнюють просту форму і відразу ж отримують права доступу.';
$Definition['New users in the last day'] = 'Нових користувачів за останній день';
$Definition['New users in the last week'] = 'Нових користувачів за останній тиждень';
$Definition['No drafts.'] = 'Немає чернеток.';
$Definition['No Items Selected'] = 'Немає вибраних елементів';
$Definition['No results for %s.'] = 'No results for <b>%s</b>.';
$Definition['Notes'] = 'Примітки';
$Definition['Notifications will appear here.'] = 'Повідомлення з\'являться тут.';
$Definition['NotifyApplicant'] = 'Notify me when anyone applies for membership.';

$Definition['Operation By'] = 'Ким';
$Definition['Organize Categories'] = 'Організація категорій';
$Definition['Or Spamblock For'] = 'Інакше блокувати на';
$Definition['Other Themes'] = 'Інші теми';
$Definition['Other Tutorials'] = 'Інші посібники';
$Definition['Outgoing Email'] = 'Вихідні';

$Definition['Page Color'] = 'Колір сторінки';
$Definition['Password Options'] = 'Налаштування пароля';
$Definition['Permission.Category'] = 'Категорія';
$Definition['Permissions'] = 'Дозволи';
$Definition['Please Confirm'] = 'Будь ласка, підтвердіть';
$Definition['Plugin'] = 'Плагін';
$Definition['Plugins'] = 'Плагіни';
$Definition['Polls'] = 'Опитування';
$Definition['Preview Colors'] = 'Попередній перегляд кольорів';
$Definition['Private Key'] = 'Приватний ключ';
$Definition['Public Key'] = 'Публічний ключ';

$Definition['Recently Active Users'] = 'Нещодавно активні користувачі';
$Definition['Recent News'] = 'Свіжі новини';
$Definition['Refresh Comments'] = 'Обновлення коментарів';
$Definition['Registration'] = 'Реєстрація';
$Definition['Remove Email Logo'] = 'Видалити логотип пошти';
$Definition['Remove Favicon'] = 'Прибрати іконку сайту';
$Definition['Reset password and send email notification to user'] = 'Очистити пароль оповістити про це користувача поштою';
$Definition['Reveal Password'] = 'Показати пароль';
$Definition['Role'] = 'Роль';
$Definition['Role Name'] = 'Назва ролі';
$Definition['Roles & Permissions'] = 'Ролі і права';
$Definition['Roles determine user\'s permissions.'] = 'Кожен користувач на вашому сайті повинен володіти хоча б однією роллю. Ролі використовуються для визначення, що користувачі можуть робити.';
$Definition['Route'] = 'Маршрут';
$Definition['Routes'] = 'Маршрути';

$Definition['Save Colors'] = 'Зберегти кольори';
$Definition['Search by user or role.'] = 'Search for users by name or enter the name of a role to see all users with that role.';
$Definition['seconds'] = 'секунд';
$Definition['Security'] = 'Безпека';
$Definition['Send Again'] = 'Надіслати знову';
$Definition['Send a Test Email'] = 'Надіслати тестового електронного листа';
$Definition['Site Description'] = 'Опис сайту';
$Definition['Site Name'] = 'Назва сайту';
$Definition['SMTP Host'] = 'SMTP сервер';
$Definition['SMTP Password'] = 'SMTP пароль';
$Definition['SMTP Port'] = 'SMTP порт';
$Definition['SMTP Security'] = 'Протокол безпеки SMTP';
$Definition['SMTP User'] = 'SMTP користувач';
$Definition['Statistics'] = 'Статистика';
$Definition['Styles'] = 'Стилі';

$Definition['Temporary (302)'] = 'Тимчасовий (302)';
$Definition['Test Email'] = 'Тестовий електронний лист';
$Definition['Test email from %s'] = 'Тестовий електронний лист від %s';
$Definition['Test Email Message'] = '<p>Це тестове електронне повідомлення.</p>

<p>Ви можете налаштувати вигляд своїх повідомлень з форуму, якщо перейдете на сторінку "Електронний лист" в особистому кабінеті.</p>';
$Definition['Test Mode'] = 'Тестовий режим: The pocket will only be displayed for pocket administrators.';
$Definition['Text Color'] = 'Колір тексту';
$Definition['TextEnterEmails'] = 'Type email addresses separated by commas here';
$Definition['The client ID uniqely identifies the site.'] = 'The client ID uniqely identifies the site. You can generate a new ID with the button at the bottom of this page.';
$Definition['The content you were looking for has been deleted.'] = 'Дані, які ви шукали, було видалено.';
$Definition['The email has been sent.'] = 'Повідомлення надіслано.';
$Definition['The homepage title is displayed on your home page.'] = 'The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.';
$Definition['The homepage was saved successfully.'] = 'Головна сторінка була успішно збереженна.';
$Definition['Theme Options'] = 'Параметри теми';
$Definition['Themes'] = 'Теми';
$Definition['Theming Overview'] = 'Огляд тем';
$Definition['There\'s been an error uploading the image. Your email logo can uploaded in one of the following filetypes: gif, jpg, png'] = 'Сталася помилка при завантаженні зображення. Логотип вашої електронної пошти можна завантажити в 1 з наступних форматів: gif, jpg, png';
$Definition['There are currently no applicants.'] = 'На даний час немає користувачів, котрі очікують підтвердження реєстрації.';
$Definition['The secret secures the sign in process.'] = 'The secret secures the sign in process. Do <b>NOT</b> give the secret out to anyone.';
$Definition['The site description usually appears in search engines.'] = 'The site description usually appears in search engines. You should try having a description that is 100–150 characters long.';
$Definition['This category has custom permissions.'] = 'Ця категорія має користувацькі права';
$Definition['This Database'] = 'Ця база даних';
$Definition['This pocket is an ad.'] = 'Цей блок є рекламним.';
$Definition['This theme has additional options.'] = 'This theme has additional options on the %s page.';
$Definition['This theme has customizable text.'] = 'This theme has text that you can customize.';

$Definition['Universal Code'] = 'Універсальний код';
$Definition['Universal Forum Embed Code'] = 'Універсальний код вбудовування для форумів';
$Definition['Unlimited'] = 'Необмежено';
$Definition['Upload New Email Logo'] = 'Завантажити новий логотип ';
$Definition['Use an SMTP server to send email'] = 'Використовувати SMTP-сервер для відправки Email.';
$Definition['Use asterisks for wildcards'] = 'Використовуйте символ зірочки для імені, напр. &lsquo;*@hotmail.com&rsquo;';
$Definition['Use categories to organize discussions'] = 'Використовувати категорії для організації обговорень';
$Definition['User Count'] = 'Користувачі';
$Definition['UserDelete'] = 'Remove User Content';
$Definition['UserDeleteMessage'] = 'Delete the user and completely remove all of the user\'s content. This may cause discussions to be disjointed. Best option for removing spam.';
$Definition['UserDeletionPrompt'] = 'Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).';
$Definition['UserKeep'] = 'Залишити контент користувача';
$Definition['UserKeepMessage'] = 'Delete the user but keep the user\'s content.';
$Definition['User Registration Settings'] = 'Налаштування реєстрації користувачів';
$Definition['Users with the no ads permission will not see this pocket.'] = 'Користувачі без дозволу на відображення реклами не побачать цей блок.';
$Definition['UserWipe'] = 'Blank User Content';
$Definition['UserWipeMessage'] = 'Delete the user and replace all of the user\'s content with a message stating the user has been deleted. This gives a visual cue that there is missing information.';
$Definition['Use the content at this url as your homepage.'] = 'Choose the page people should see when they visit: <strong style="white-space: nowrap;">%s</strong>';

$Definition['Vanilla.Archive.Description'] = 'Ви можете вибрати архівацію обговорень форумі, старше зазначеної дати. Обговорення в архіві стають закритими і не допускають нових повідомлень.';
$Definition['Vanilla.Categories.MaxDisplayDepth'] = 'Place nested categories in a comma-delimited list when they are %1$s';
$Definition['Vanilla is installed!'] = 'Vanilla встановлена!';
$Definition['Verified!'] = 'Підтверджено!';
$Definition['Version'] = 'Версія';
$Definition['Version %s'] = 'Версія %s';
$Definition['version %s'] = 'версія %s';
$Definition['Version %s Installer'] = 'Інсталятор версії %s ';
$Definition['View Page'] = 'Подивитись сторінку';

$Definition['Warning: deleting is permanent'] = 'WARNING: deleted items are removed from this list and cannot be brought back.';
$Definition['Welcome to Vanilla!'] = 'Ласкаво просимо до Vanilla!';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'За умовчанням ми будемо використовувати локальний сервер для відправки електронної пошти. Якщо ви хочете використовувати інший SMTP-сервер, ви можете налаштувати його нижче.';
$Definition['What\'s the Buzz?'] = 'Які новини?';
$Definition['Why do you want to join?'] = 'Чому ви вирішили приєднатися?';
$Definition['Within'] = 'Протягом';
$Definition['WordPress Plugin'] = 'WordPress плагін';

$Definition['You can also ban the users that posted the spam and delete all of their posts.'] = 'Check the box next to the user that posted the spam to also ban them and delete all of their posts. <b>Only do this if you are sure these are spammers.</b>';
$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'Якщо ви коли-небудь заблокуєте ваш форум, ви  завжди зможете війти,  використовуючи оригінальний Email Vanilla та пароль тут: <a href="%1$s">%1$s</a>';
$Definition['You can make the categories page your homepage.'] = 'You can make your categories page your homepage <a href="%s">here</a>.';
$Definition['You can send emails in plain text by disabling the toggle below.'] = 'Ви можете надсилати листи у вигляді звичайного тексту, увімкнувши перемикач, розташований нижче.';
$Definition['Your default locale won\'t display properly'] = 'Your default locale won\'t display properly until it is enabled below. Please enable the following: %s.';
$Definition['Your inbox is empty.'] = 'Ваш список повідомлень порожній.';
