<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s heeft de lidmaatschapsuitnodiging van %4$s geaccepteerd.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s heeft de rechten van %4$s veranderd.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s wijzigde de profielafbeelding van %6$s.';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s heeft een reactie geplaatst op %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s heeft een account gemaakt voor %4$s. ';
$Definition['%1$s joined.'] = '%1$s werd lid.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['%1$s on %2$s'] = '%1$s op %2$s';
$Definition['%1$s signed in.'] = '%1$s logde in.';
$Definition['%1$s to %2$s'] = '%1$s naar %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s naar %2$s van %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s heeft het profiel van %6$s geüpdatet.';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s is toegevoegd aan de %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s is verwijderd van de %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s is verwijderd van de %2$s %3$s en toegevoegd aan %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s schreef over %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s heeft %2$s lidmaatschapsaanvraag goedgekeurd.';
$Definition['%3$s created an account for %1$s.'] = '%3$s heeft een account gemaakt voor %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 naar %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%1$s naar %2$s van %3$s';
$Definition['%s (Current)'] = '%s (Huidige)';
$Definition['%s Agrees'] = '%s Mee eens\'';
$Definition['%s and you'] = '%s en jij';
$Definition['%s Awesomes'] = '%s Geweldigs';
$Definition['%s by %s'] = '%s bij %s';
$Definition['%s changed %s\'s permissions.'] = '%s veranderde %s\'s rechten.';
$Definition['%s Comment'] = '%s Reactie';
$Definition['%s comment'] = '%s reactie';
$Definition['%s comment html'] = '%s reactie ';
$Definition['%s Comments'] = '%s Reacties';
$Definition['%s comments'] = '%s reacties';
$Definition['%s comments html'] = '%s reacties';
$Definition['%s Connect'] = '%s Verbind';
$Definition['%s day'] = '%s dag';
$Definition['%s days'] = '%s dagen';
$Definition['%s deleted this conversation.'] = '%s verwijderde dit gesprek.';
$Definition['%s discussion'] = '%s discussie';
$Definition['%s discussion html'] = '%s discussie ';
$Definition['%s discussions'] = '%s discussies';
$Definition['%s discussions html'] = '%s discussies';
$Definition['%s has been Jailed.'] = '%s is Opgesloten.';
$Definition['%s has left this conversation.'] = '%s heeft dit gesprek verlaten.';
$Definition['%s hour'] = '%s uur';
$Definition['%s hours'] = '%s uren';
$Definition['%s Insightfuls'] = '%s Verstandigs';
$Definition['%s level deep'] = '%s niveau\'s';
$Definition['%s levels deep'] = '%s niveau\'s';
$Definition['%s Likes'] = '%s Likes ';
$Definition['%s LOLs'] = '%s LOLs ';
$Definition['%s member'] = '%s lid';
$Definition['%s members'] = '%s leden';
$Definition['%s mentioned %s in a %s.'] = '%s noemde %s in een %s.';
$Definition['%s message'] = '%s bericht';
$Definition['%s messages'] = '%s berichten';
$Definition['%s minute'] = '%s minuut';
$Definition['%s minutes'] = '%s minuten';
$Definition['%s month'] = '%s maand';
$Definition['%s months'] = '%s maanden';
$Definition['%s New'] = '%s Nieuw';
$Definition['%s new'] = '%s nieuw';
$Definition['%s new comment since you last read this.'] = '%s nieuwe reactie sinds je dit voor het laatst hebt gelezen.';
$Definition['%s new comments since you last read this.'] = '%s nieuwe reacties sinds je dit voor het laatst hebt gelezen.';
$Definition['%s New Plural'] = '%s Nieuw';
$Definition['%s new plural'] = '%s nieuw';
$Definition['%s Not Found'] = '%s Niet Gevonden';
$Definition['%s not found.'] = '%s niet gevonden.';
$Definition['%s Point'] = '%s Punt';
$Definition['%s point'] = '%s punt';
$Definition['%s Points'] = '%s Punten';
$Definition['%s points'] = '%s punten';
$Definition['%s result'] = '%s resultaat';
$Definition['%s results'] = '%s resultaten';
$Definition['%s said'] = '%s zei';
$Definition['%s said:'] = '%s zei:';
$Definition['%s tag(s) found.'] = '%s tag(s) gevonden.';
$Definition['%s tags in the system'] = '%s tags in het systeem';
$Definition['%s Up Votes'] = '%s Stemmen Voor';
$Definition['%s view'] = '%s keer bekeken';
$Definition['%s view html'] = '%s weergave';
$Definition['%s viewing'] = '%s kijkend';
$Definition['%s views'] = '%s keer bekeken';
$Definition['%s views html'] = '%s weergaven';
$Definition['%s votes'] = '%s stemmen';
$Definition['%s was removed from the %s and added to the %s'] = '%s was verwijderd van de %s en toegevoegd aan de %s';
$Definition['%s week'] = '%s week ';
$Definition['%s weeks'] = '%s weken';
$Definition['%s WTFs'] = '%s WTFs ';
$Definition['%s year'] = '%s jaar';
$Definition['%s years'] = '%s jaren';

$Definition['(All)'] = '(Alle)';
$Definition['(empty message)'] = '(leeg bericht)';

$Definition['+%s Guests'] = '+%s Gasten';

$Definition[' - Page %s'] = ' - Pagina %s';

$Definition['1 message'] = '1 bericht';

$Definition['<General Error>'] = '<Algemene Foutmelding>';

$Definition['[%1$s] %2$s'] = '[%1$s]%2$s';
$Definition['[%1$s] Membership Approved'] = '[%1$s] Lidmaatschap Goedgekeurd';
$Definition['[%s] Welcome Aboard!'] = '[%s] Welkom aan Boord!';
$Definition['[Deleted User]'] = '[Verwijderde Gebruiker]';

$Definition['About'] = 'Over';
$Definition['AboutToDelete'] = 'Je staat op het punt om %s te verwijderen.';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Je staat op het punt om %1$s van de %2$s geselecteerde gesprekken te verwijderen.';
$Definition['Abuse'] = 'Misbruik';
$Definition['Accept'] = 'Accepteren';
$Definition['Accept this answer.'] = 'Keur dit antwoord goed.';
$Definition['Account Options'] = 'Accountopties';
$Definition['Activate'] = 'Activeren';
$Definition['Active'] = 'Actief';
$Definition['Active Users'] = 'Actieve gebruikers';
$Definition['Activity'] = 'Activiteit';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s aanvaard %4$s %8$s. ';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s heeft gereageerd op je %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s heeft gereageerd op je %8$s.';
$Definition['Activity.Comment'] = 'Reactie';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s verzond een %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s verzond een %8$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s werd lid.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s werd lid.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s wijzigde %6$s profiel afbeelding.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s wijzigde %6$s profiel afbeelding.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s antwoordde %4$s %8$s.';
$Definition['Add'] = 'Toevoegen';
$Definition['Add %s'] = 'Voeg %s toe';
$Definition['Add a Comment'] = 'Voeg een reactie toe';
$Definition['Add a Message'] = 'Voeg een Bericht Toe';
$Definition['Add another poll option ...'] = 'Voeg een andere enquêteoptie toe ...';
$Definition['Add a Profile Picture'] = 'Voeg een Profielfoto toe';
$Definition['Add a time?'] = 'Een tijd toevoegen?';
$Definition['Add a Warning'] = 'Voeg een Waarschuwing toe';
$Definition['Add Badge'] = 'Voeg een Badge toe';
$Definition['Add Comment'] = 'Voeg Reactie toe';
$Definition['Add Cost'] = 'Voeg Prijs toe';
$Definition['Add Image'] = 'Voeg afbeelding toe';
$Definition['Add Message'] = 'Voeg Bericht toe';
$Definition['Add Note'] = 'Voeg aantekening toe';
$Definition['Add People to this Conversation'] = 'Voeg Mensen toe aan dit Gesprek';
$Definition['Add Route'] = 'Voeg Route toe';
$Definition['Admin'] = 'Administrator';
$Definition['Administrator'] = 'Beheerder';
$Definition['Administrator Activity'] = 'Administrator Activiteiten';
$Definition['administrators'] = 'beheerders';
$Definition['Advanced Stuff'] = 'Geavanceerde dingen';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Er is een fatale fout opgetreden bij het verwerken van het verzoek.<br />De server geeft de volgende reactie: %s';
$Definition['Agree'] = 'Mee Eens';
$Definition['Alert'] = 'Alarm';
$Definition['Align center'] = 'Lijn centrum uit';
$Definition['Align left'] = 'Lijn links uit';
$Definition['Align right'] = 'Lijn rechts uit';
$Definition['All %s'] = 'Alle %s';
$Definition['All %s...'] = 'Alle %s...';
$Definition['All Bookmarks'] = 'Alle Bladwijzers';
$Definition['All Categories'] = 'Alle Categorieën';
$Definition['all categories'] = 'alle categorieën';
$Definition['All Conversations'] = 'Alle Gesprekken';
$Definition['All Discussions'] = 'Alle Discussies';
$Definition['All Events'] = 'Alle gebeurtenissen';
$Definition['All Members'] = 'Alle Leden';
$Definition['All members'] = 'Alle leden';
$Definition['Allow'] = 'Toestaan';
$Definition['Allow other members to see your email?'] = 'Wil je dat andere leden je e-mail adres kunnen zien?';
$Definition['All Time Leaders'] = 'Beste Leden Aller Tijden';
$Definition['Already Warned'] = 'Al gewaarschuwd';
$Definition['Ancient Membership'] = 'Oud lidmaatschap';
$Definition['An invitation has already been sent to the email you entered.'] = 'Een uitnodiging is al verzonden naar het e-mailadres dat je ingevoerd hebt.';
$Definition['Announce'] = 'Aankondigen';
$Definition['Announce...'] = 'Aankondigen...';
$Definition['Announcement'] = 'Aankondiging';
$Definition['Announcements'] = 'Aankondegingen';
$Definition['Announce this discussion'] = 'Kondig deze discussie aan';
$Definition['Answer'] = 'Antwoord';
$Definition['answer'] = 'antwoord';
$Definition['Answers'] = 'Antwoorden';
$Definition['answers'] = 'antwoorden';
$Definition['Applicant'] = 'Aanvrager';
$Definition['Applicants'] = 'Aanvragers';
$Definition['Applicants & Invitations'] = 'Aanmeldingen en uitnodigingen';
$Definition['Apply Changes'] = 'Sla Veranderingen op';
$Definition['Apply for Membership'] = 'Registreer';
$Definition['Apply for membership'] = 'Vraag lidmaatschap aan';
$Definition['Approve'] = 'Goedkeuren';
$Definition['Approve Applicant'] = 'Goedkeuren';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Weet je 100% ZEKER dat je deze actie wil doen?';
$Definition['Are you attending this event?'] = 'Ga je naar deze gebeurtenis?';
$Definition['Are you sure you want to delete this %s?'] = 'Weet je zeker dat je %s wilt verwijderen?';
$Definition['Are you sure you want to do that?'] = 'Weet je zeker dat je dit wilt doen?';
$Definition['Are you sure you want to do this?'] = 'Weet je zeker dat je dit wilt doen?';
$Definition['Are you sure you want to join this group?'] = 'Ben je zeker dat je lid wil worden van deze groep?';
$Definition['Are you sure you want to leave this group?'] = 'Ben je zeker dat je deze groep wil verlaten?';
$Definition['Are you sure you wish to continue?'] = 'Weet je zeker dat je door wilt gaan?';
$Definition['Ask a Question'] = 'Stel een Vraag';
$Definition['Ask Question'] = 'Stel Vraag';
$Definition['Attach a file'] = 'Voeg een bestand toe';
$Definition['Attach image/file'] = 'Beeld/bestand toevoegen';
$Definition['Attachments'] = 'Bijlagen';
$Definition['Attach this warning to the %s.'] = 'Voeg deze waarschuwing toe aan de %s.';
$Definition['AttemptingSignOut'] = 'Je probeert uit te loggen. Weet je zeker dat je wilt %s?';
$Definition['Attending'] = 'Bijwonen';
$Definition['Attending (%s)'] = 'Bijwonen (%s)';
$Definition['Authenticate URL'] = 'Authenticatie URL';
$Definition['Author'] = 'Auteur';
$Definition['available'] = 'beschikbaar';
$Definition['Awaiting Moderation'] = 'Wachtend op moderatie';
$Definition['Awesome'] = 'Geweldig';

$Definition['Back to Discussions'] = 'Terug naar Discussies';
$Definition['Back to Profile'] = 'Terug naar Profiel';
$Definition['Badge'] = 'Insigne';
$Definition['Badge404'] = 'Badge niet gevonden.';
$Definition['Badges'] = 'Insignes';
$Definition['BadgesModuleTitle'] = 'Insignes';
$Definition['BadgesNobody'] = 'Nog niemand heeft deze badge verdiend.';
$Definition['Ban'] = 'Verbod';
$Definition['Ban.Action'] = 'Verbod';
$Definition['Banned'] = 'Verboden';
$Definition['Banned for being abusive.'] = 'Verbannen voor beledigend zijn.';
$Definition['Banned for spamming.'] = 'Verbannen voor spammen.';
$Definition['Banned users can no longer access the site.'] = 'Verbannen gebruikers kunnen niet langer de site gebruiken.';
$Definition['Banner'] = 'Vaandel';
$Definition['Ban User'] = 'Verban Gebruiker';
$Definition['Ban Value'] = 'Verban Waarde';
$Definition['Best Answer'] = 'Beste Antwoord';
$Definition['Best Answers'] = 'Beste Antwoorden';
$Definition['Best Of'] = 'Beste van';
$Definition['Best Of...'] = 'Beste van...';
$Definition['Blank Discussion Topic'] = 'Blanco Discussieonderwerp';
$Definition['Blank Message'] = 'Blanco Bericht';
$Definition['Body'] = 'Inhoud';
$Definition['Bold'] = 'Vetgedrukt';
$Definition['Bookmark'] = 'Bladwijzer';
$Definition['bookmarked discussion'] = 'bladwijzer ingesteld voor dit gesprek';
$Definition['Bookmarked Discussions'] = 'Bewaarde Discussies';
$Definition['Bookmarks'] = 'Bladwijzers';
$Definition['bookmarks'] = 'bladwijzers';
$Definition['Browse Groups'] = 'Overzicht Groepen';
$Definition['Browse popular groups.'] = 'Doorzoek populaire groepen. ';
$Definition['By'] = 'Door';
$Definition['by'] = 'door';
$Definition['by Date'] = 'op Datum';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Door een bestand te uploaden verklaar jij dat de rechten om deze afbeelding te verspreiden niet in strijd zijn met de Gebruiksvoorwaarden.';

$Definition['Cancel'] = 'Annuleren';
$Definition['Casual'] = 'toevallig';
$Definition['Categories'] = 'Categorieën';
$Definition['CategoriesShowFollowed'] = 'Toon alleen gevolgde categorieën';
$Definition['CategoriesShowUnfollowed'] = 'Toon verborgen categorieën';
$Definition['CategoriesViewingAll'] = 'Je bekijkt momenteel alle categorieën.';
$Definition['CategoriesViewingFollowed'] = 'Je bekijkt momenteel alleen categorieën die je volgt.';
$Definition['Category'] = 'Categorie';
$Definition['Category Filter'] = 'Categoriefilter';
$Definition['CategoryID'] = 'Categorie';
$Definition['Category Management'] = 'Categoriemanagement';
$Definition['Category Notifications'] = 'Categorie Opmerkingen';
$Definition['Category to Use'] = 'Categorie om te gebruiken';
$Definition['Change'] = 'Verander';
$Definition['Change language'] = 'Verander taal';
$Definition['Change My Password'] = 'Wijzig Mijn Wachtwoord';
$Definition['Change My Picture'] = 'Wijzig Mijn Afbeelding';
$Definition['Change Password'] = 'Wijzig Wachtwoord';
$Definition['Change Picture'] = 'Wijzig Afbeelding';
$Definition['Check all roles that apply to this user:'] = 'Selecteer alle rollen die van toepassing zijn op deze gebruiker:';
$Definition['Child Categories'] = 'Subcategorieën';
$Definition['Child Categories:'] = 'Kindcategorieën:';
$Definition['Choose a name to identify yourself on the site.'] = 'Kies een naam om jezelf te identificeren op de site.';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Kies een hoofddiscussie waarin alle reacties in samengevoegd zullen worden:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Kies of je een vraag wilt stellen of een discussie wilt starten.';
$Definition['Clear'] = 'Ruim Op';
$Definition['clear'] = 'ruim op';
$Definition['Clear Conversation History'] = 'Ruim de gespreksgeschiedenis op';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Klik <a href="%s">hier</a> om terug te gaan naar de discussie.';
$Definition['Click accept or reject beside an answer.'] = 'Klik op accepteren of weigeren naast een antwoord.';
$Definition['clicking here'] = 'door hier te klikken';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Kilk op %s naast discussies om ze als bladwijzers toe te voegen.';
$Definition['Click to re-attach'] = 'Klik om opnieuw te bevestigen';
$Definition['Close'] = 'Sluiten';
$Definition['Closed'] = 'Gesloten';
$Definition['Close this discussion'] = 'Sluit deze discussie';
$Definition['Color'] = 'Kleur';
$Definition['Combo Breaker'] = 'Combo Breker';
$Definition['Comment'] = 'Reageer';
$Definition['comment'] = 'reageer';
$Definition['Comment As ...'] = 'Reageer Als ...';
$Definition['Comment by %s'] = 'Reactie door %s';
$Definition['Comment in'] = 'in';
$Definition['Commenting as %1$s (%2$s)'] = 'Aan het reageren als %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Reageren niet toegestaan.';
$Definition['Comments'] = 'Reacties';
$Definition['comments'] = 'opmerkingen';
$Definition['Comments are between {UserID,you}.'] = 'Reacties zijn tussen {UserID, you}.';
$Definition['Community'] = 'Gemeenschap';
$Definition['Community Guidelines'] = 'Community richtlijnen';
$Definition['Completely delete the warning.'] = 'Verwijder de gehele waarschuwing.';
$Definition['Confirm'] = 'Bevestig';
$Definition['Confirmed email address'] = 'Bevestigd e-mailadres';
$Definition['Confirm Email'] = 'Bevestig E-mail';
$Definition['Confirm Password'] = 'Bevestig Wachtwoord';
$Definition['Connect'] = 'Verbind';
$Definition['ConnectAccountExists'] = 'Je hebt hier al een account.';
$Definition['ConnectChooseName'] = 'Een naam kiezen om uzelf te identificeren op de site.';
$Definition['ConnectCreateAccount'] = 'Voeg Info toe &amp; Creër Account';
$Definition['Connected'] = 'Verbonden';
$Definition['ConnectExistingPassword'] = 'Voer het wachtwoord van je huidige account in.';
$Definition['Connecting...'] = 'Verbinden...';
$Definition['Connection'] = 'Verbinding';
$Definition['ConnectLeaveBlank'] = 'Leeg laten tenzij er een verbinding is met een bestaande rekening.';
$Definition['ConnectName'] = 'Gebruikersnaam';
$Definition['ConnectRegisteredName'] = 'Jouw geregistreerde gebruikersnaam: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Verbind je profiel met sociale netwerken om op de hoogte gebracht te worden van nieuwtjes en deel ze met je vrienden en volgers.';
$Definition['Contact Us'] = 'Neem contact met ons op';
$Definition['conversation'] = 'gesprek';
$Definition['Core'] = 'Kern';
$Definition['Created'] = 'Aangemaakt';
$Definition['Create Discussions'] = 'Maak discussies';
$Definition['Create One.'] = 'Maak er één aan.';
$Definition['Current'] = 'Huidig';
$Definition['Currently: '] = 'Momenteel:';
$Definition['Custom Information'] = 'Aangepaste Informate';
$Definition['Customize'] = 'Aanpassen';
$Definition['customize your profile now'] = 'pas je profiel nu aan';
$Definition['Customize your Public Profile'] = 'Pas je Publieke Profiel aan';
$Definition['Custom Profile Fields'] = 'Aangepaste Profielvelden';
$Definition['Custom Profile Field Settings'] = 'Aangepaste Profielveld Instellingen';

$Definition['Dashboard'] = 'Instrumentenbord';
$Definition['Dashboard Home'] = 'Instrumentenbord start';
$Definition['Dashboard Summaries'] = 'Dashboardsamenvattingen';
$Definition['Date'] = 'Datum';
$Definition['Date.DefaultDateTimeFormat'] = '%B %e, %Y %l:%M%p';
$Definition['Date.DefaultDayFormat'] = '%e %B';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%H:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Date. Expects \'mm/dd/yyyy\'.'] = 'Datum. Verwacht \'mm/dd/jjjj\'.';
$Definition['Date Added'] = 'Datum Toegevoegd';
$Definition['Date Examples'] = 'Voorbeelden: maandag, vandaag, vorige week, 26 maart, 3/26/04';
$Definition['Date within'] = 'Datum in';
$Definition['days'] = 'dagen';
$Definition['Define Thumbnail'] = 'Klik en sleep over de afbeelding om de thumbnail te definiëren.';
$Definition['Delete'] = 'Verwijder';
$Definition['Delete %s'] = 'Verwijder %s';
$Definition['Delete Account'] = 'Verwijder Account';
$Definition['Delete Conversation'] = 'Verwijder Gesprek';
$Definition['Delete Discussion'] = 'Verwijder Discussie';
$Definition['Delete Group'] = 'Verwijder Groep';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Verwijder de gebruiker en alle gebruikersinhoud. Dit zal zorgen dat discussies uit elkaar vallen, waardoor het lijkt alsof mensen reageren op berichten die er niet zijn. Dit is een geweldige optie voor het verwijderen van spamberichten.';
$Definition['Delete User Content'] = 'Verwijder Gebruikersinhoud';
$Definition['Delete User Forever'] = 'Verwijder Gebruiker voor Altijd';
$Definition['Deny'] = 'Weigeren';
$Definition['Deny Applicant'] = 'Weigeren';
$Definition['Did this answer the question?'] = 'Heeft dit de vraag beantwoord?';
$Definition['Disagree'] = 'Oneens';
$Definition['Discussion'] = 'Discussie';
$Definition['discussion'] = 'discussie';
$Definition['Discussion Board'] = 'Discussieforum';
$Definition['Discussions'] = 'Discussies';
$Definition['discussions'] = 'gesprekken';
$Definition['Discussions Page'] = 'Discussies pagina';
$Definition['Discussion Title'] = 'Discussietitel';
$Definition['Dislike'] = 'Afkeer';
$Definition['Dismiss'] = 'Negeren';
$Definition['Documentation'] = 'Documentatie';
$Definition['Don\'t announce.'] = 'Kondig niet aan.';
$Definition['Don\'t fold quotes'] = 'Verberg quotes niet';
$Definition['Don\'t have an account? %s'] = 'Heb je nog geen account? <br />%s';
$Definition['Download the sounds as MP3'] = 'Download de geluiden als MP3';
$Definition['Do you want to expire or delete this warning?'] = 'Wil je deze waarschuwing laten vervallen of verwijderen?';
$Definition['Draft saved at %s'] = 'Concept opgeslagen op %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Sleep het kader in de onderstaande afbeelding om je thumbnail te definiëren.';
$Definition['Drop image/file'] = 'Versleep beeld/bestand';

$Definition['Earned'] = 'Verdiend';
$Definition['Edit'] = 'Bewerk';
$Definition['Edit %s'] = 'Bewerk %s';
$Definition['Edit Account'] = 'Bewerk Account';
$Definition['Edit Comment'] = 'Bewerk Reactie';
$Definition['Edit Discussion'] = 'Bewerk Discussie';
$Definition['edited %s'] = '%s aangepast';
$Definition['Edited %s by %s.'] = '%s aangepast door %s.';
$Definition['Edit My Account'] = 'Bewerk Mijn Account';
$Definition['Edit My Profile'] = 'Bewerk Mijn Profiel';
$Definition['Edit My Thumbnail'] = 'Bewerk Mijn Thumbnail';
$Definition['editor.BBCodeHelpText'] = 'U kunt <a href="http://en.wikipedia.org/wiki/BBCode"; target="_new">BBCode</a> gebruiken in uw bericht.';
$Definition['editor.HtmlHelpText'] = 'U kunt <a href="http://htmlguide.drgrog.com/cheatsheet.php"; target="_new">Simple Html</a> gebruiken in uw bericht.';
$Definition['editor.MarkdownHelpText'] = 'U kunt <a href="http://en.wikipedia.org/wiki/Markdown"; target="_new">Markdown</a> gebruiken in uw bericht.';
$Definition['editor.TextHelpText'] = 'U gebruikt platte tekst in uw bericht.';
$Definition['editor.WysiwygHelpText'] = 'U gebruikt <a href="https://en.wikipedia.org/wiki/WYSIWYG"; target="_new">Wysiwyg</a> in uw bericht.';
$Definition['Edit Preferences'] = 'Bewerk Voorkeuren';
$Definition['Edit Profile'] = 'Verander profiel';
$Definition['Edit Tag'] = 'Verander tag';
$Definition['Edit Thumbnail'] = 'Wijzig Thumbnail';
$Definition['Eighth Anniversary'] = 'Achtste verjaardag';
$Definition['Email'] = 'E-mail';
$Definition['Email/Username'] = 'Email/Gebruikersnaam';
$Definition['EmailConfirmEmail'] = 'Je moet je e-mailadres bevestigen voordat je verder kan gaan. Bevestig je e-mailadres a.u.b. door op de volgende link te klikken: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '
Fijne dag verder!';
$Definition['EmailHeader'] = 'Hallo {User.Name}!
';
$Definition['EmailInvitation'] = 'Hallo!

%1$s heeft je uitgenodigd om deel te nemen aan %2$s. Als je wilt deelnemen, kan je dit doen door te klikken op deze link:

  %3$s

Fijne dag verder!';
$Definition['EmailMembershipApproved'] = 'Hallo %1$s,

Je aanvraag voor het lidmaatschap is goedgekeurd. Log in met de volgende link:

  %2$s
  
Fijne dag verder!';
$Definition['EmailNotification'] = '%1$s

Volg deze link om het te bekijken: 
%2$s

Fijne dag verder!';
$Definition['Email Notifications'] = 'E-mail Notificaties';
$Definition['Email Or Username'] = 'E-mail of gebruikersnaam';
$Definition['EmailPassword'] = 'Hallo %1$s,

%2$s heeft je wachtwoord gereset bij %3$s. Je inloggegevens zijn nu als volgt:

  E-mail: %6$s
  Wachtwoord: %5$s
  Url: %4$s

Fijne dag verder!';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'E-mail verzonden vanuit de applicatie zal verwijzen naar onderstaande naam en e-mailadres.';
$Definition['Email Source'] = 'E-mail';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Volg deze link om het te bekijken: %2$s

Fijne dag verder!';
$Definition['Email Unavailable'] = 'E-mail Niet beschikbaar';
$Definition['Email visible to other users'] = 'E-mail zichtbaar voor andere gebruikers';
$Definition['EmailWelcome'] = 'Hallo %1$s,

%2$s heeft een account voor jou aangemaakt op %3$s. Je inloggegevens zijn:

  E-mail: %6$s
  Wachtwoord: %5$s
  Url: %4$s

Fijne dag verder!';
$Definition['EmailWelcomeConnect'] = 'Hallo {User.Name},

Je hebt je succesvol verbonden met {Title}. Hier zijn je gegevens:

  Gebruikersnaam: {User.Name}
  Verbonden Met: {ProviderName}

Je kunt de website bezoeken op {/,url,domain}.

Fijne dag verder!';
$Definition['EmailWelcomeRegister'] = 'Hallo {User.Name},

Je hebt je succesvol geregistreerd voor een account bij {Title}. Hier zijn je gegevens:

  Gebruikersnaam: {User.Name}
  E-mail: {User.Email}

Je kunt de website bezoeken op {/,url,domain}.

Fijne dag verder!';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Lees het volledige verhaal hier</a></p><div class="ClearFix"></div></div>';
$Definition['EmbeddedNoBodyFormat'] = '{Url}';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Lees het volledige verhaal hier</a></p><div class="ClearFix"></div></div>';
$Definition['End time?'] = 'Eindtijdstip?';
$Definition['English'] = 'Engels';
$Definition['Enter your Email address'] = 'Voer je E-mailadres in';
$Definition['Enter your email address'] = 'Voer je e-mailadres in';
$Definition['Enter your Email address or username'] = 'Vul je e-mailadres of gebruikersnaam in';
$Definition['Enter Your OpenID Url'] = 'Voer je OpenID Url in';
$Definition['Erase User Content'] = 'Wis Gebruikersinhoud';
$Definition['Error'] = 'Fout';
$Definition['ErrorBadInvitationCode'] = 'De uitnodigingscode die je hebt gegeven is niet geldig.';
$Definition['ErrorCredentials'] = 'Sorry, er is geen account gevonden met het ingevoerde e-mailadres/gebruikersnaam en wachtwoord.';
$Definition['ErrorPermission'] = 'Sorry, toestemming geweigerd.';
$Definition['ErrorPluginDisableRequired'] = 'Je kan de {0} plugin niet deactiveren om dat de {1} plugin het nodig heeft om te werken.';
$Definition['ErrorPluginEnableRequired'] = 'Deze plugin benodigd dat de {0} plugin geactiveerd is voordat hij zelf geactiveerd kan worden.';
$Definition['ErrorPluginVersionMatch'] = 'De geactiveerde {0} plugin (versie {1}) kon de versiebenodigdheden niet toereiken ({2}).';
$Definition['ErrorRecordNotFound'] = 'De opgevraagde gegevens konden niet gevonden worden.';
$Definition['ErrorTermsOfService'] = 'Je moet akkoord gaan met de gebruiksvoorwaarden.';
$Definition['Event'] = 'Evenement';
$Definition['Event Details'] = 'Details van de Gebeurtenis';
$Definition['Events'] = 'Evenementen';
$Definition['everyone'] = 'iedereen';
$Definition['Everything'] = 'Alles';
$Definition['Expired'] = 'Verlopen';
$Definition['Expires'] = 'Verloopt';

$Definition['Failed to delete group.'] = 'De groep kon niet verwijderd worden.';
$Definition['Failed to find discussion for commenting.'] = 'Het is mislukt om de discussie of commentaar te vinden.';
$Definition['Failed to load the poll.'] = 'Het is mislukt om de enquête te laden.';
$Definition['Feedback'] = 'Terugkoppeling';
$Definition['Female'] = 'Vrouw';
$Definition['Fifth Anniversary'] = 'Vijfde verjaardag';
$Definition['FileName'] = 'Bestandsnaam';
$Definition['Filename'] = 'Bestandsnaam';
$Definition['FileSize'] = 'Bestandsgrootte';
$Definition['File Size'] = 'Bestandsgrootte';
$Definition['First Anniversary'] = 'Eerste verjaardag';
$Definition['First Comment'] = 'Eerste bericht';
$Definition['Flag'] = 'Rapporteer';
$Definition['Folder'] = 'Map';
$Definition['Folders'] = 'Mappen';
$Definition['Follow'] = 'Volg';
$Definition['Follow %s'] = 'Volg %s';
$Definition['Followed by %d people'] = 'Gevolgd door %d mensen';
$Definition['Followed by %d person'] = 'Gevolgd door %d persoon';
$Definition['followed categories'] = 'gevolgde categorieën';
$Definition['Following %d people'] = 'Volgt %d mensen';
$Definition['Following %d person'] = 'Volgt %d persoon';
$Definition['FollowOnly'] = 'Volg de link hieronder om het te bekijken:';
$Definition['Follows'] = 'Volgt';
$Definition['Forgot?'] = 'Vergeten?';
$Definition['Forgot your password?'] = 'Wachtwoord vergeten?';
$Definition['Format'] = 'Opmaak';
$Definition['Format his'] = 'zijn';
$Definition['Format their'] = 'hun';
$Definition['Format You'] = 'Jij';
$Definition['Format you'] = 'jij';
$Definition['Format Your'] = 'Jouw';
$Definition['Forum'] = 'Forum ';
$Definition['Forums'] = 'Forums ';
$Definition['Forum Signature Settings'] = 'Forum Instellingen voor handtekening';
$Definition['Fourth Anniversary'] = 'Vierde verjaardag';
$Definition['Friends'] = 'Vriend';
$Definition['From'] = 'Van';
$Definition['Full Site'] = 'Volledige Site';

$Definition['Garden.Email.SupportAddress'] = 'Ondersteuning e-mail';
$Definition['Garden.Email.SupportName'] = 'Ondersteuningsnaam';
$Definition['Garden.Registration.DefaultRoles'] = 'standaard rol';
$Definition['Garden.Title'] = 'Banner Titel';
$Definition['Gender'] = 'Geslacht';
$Definition['General'] = 'Algemeen';
$Definition['Generate import SQL only'] = 'Genereer import alleen met SQL';
$Definition['Generate Password'] = 'Genereer Wachtwoord';
$Definition['Get an audio challenge'] = 'Ik wil een geluidsuitdaging';
$Definition['Get a new challenge'] = 'Ik wil een nieuwe uitdaging';
$Definition['Get a visual challenge'] = 'Ik wil een visuele uitdaging';
$Definition['Give'] = 'Geef';
$Definition['Give a Badge to %s'] = 'Geef een Badge aan %s';
$Definition['Give Badge'] = 'Geef Badge';
$Definition['Given'] = 'Gegeven';
$Definition['Go'] = 'Ga';
$Definition['Group'] = 'Groep';
$Definition['group'] = 'groep';
$Definition['GroupEmptyAnnouncements'] = 'Belangrijke dingen zullen hier één dag getoond worden.';
$Definition['GroupEmptyDiscussions'] = 'Wat is het hier stil. Vind je ook niet?';
$Definition['GroupEmptyEvents'] = 'Wat jammer, je hebt geen gebeurtenissen in het vooruitzicht.';
$Definition['Group Info'] = 'Groepsinformatie';
$Definition['Group Leaders'] = 'Beste Leden';
$Definition['Group Members'] = 'Leden';
$Definition['GroupMembersEmpty'] = 'Er is nog niemand lid geworden. Vertel het door!';
$Definition['Group Options'] = 'Groep Opties';
$Definition['Groups'] = 'Groepen';
$Definition['groups'] = 'groepen';
$Definition['Guest'] = 'Gast';
$Definition['GuestModule.Message'] = 'Het lijkt erop dat je hier nieuw bent. Klik op één van deze knoppen om je aan te melden!';

$Definition['Hang on a sec while we sign you out.'] = 'Wacht even een seconde terwijl we je uitloggen.';
$Definition['he'] = 'hij';
$Definition['Heading'] = 'Rubriek';
$Definition['Heading %s'] = 'Titel %s';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} heeft de <a href="{Url,html}">{Data.Name,text}</a> badge verdiend.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} heeft {ActivityUserID,you} verbannen.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} reageerde op <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActiviteitGebruikersID,gebruiker} heeft een nieuwe discussie gestart. <a href="{Url,html}">{Gegevens.Naam,tekst}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} noemde jouw in <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} veranderde de profielfoto voor {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} is geregistreerd.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} hefte de verbanning van {ActivityUserID,you} op.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} waarschuwde {RegardingUserID,you}.';
$Definition['her'] = 'haar';
$Definition['Hide'] = 'Verbergen';
$Definition['Hide my online status from other members'] = 'Verberg mijn online status voor andere leden';
$Definition['Hide signatures?'] = 'Handtekeningen verbergen?';
$Definition['Hide signatures always'] = 'Verberg handtekeningen altijd';
$Definition['Hide signatures on my mobile device'] = 'Verberg handtekeningen op mijn mobile apparaat';
$Definition['his'] = 'zijn';
$Definition['Home'] = 'Thuis';
$Definition['hours'] = 'uren';
$Definition['Howdy, Stranger!'] = 'Hoi, vreemdeling!';
$Definition['How long do you want this warning to last?'] = 'Hoe lang wilt u dat deze waarschuwing duurt?';
$Definition['How many levels deep should we start folding up quote trees?'] = 'Vanaf hoeveel niveau\'s moeten quotes verborgen worden?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Ik ga akkoord met de <a id="TermsOfService" class="Popup" target="terms" href="%s">gebruiksvoorwaarden</a>';
$Definition['Icon'] = 'Icoon';
$Definition['Ignore'] = 'Negeren';
$Definition['Ignore List'] = 'Zwarte lijst';
$Definition['Ignore Someone'] = 'Negeer Iemand';
$Definition['Image'] = 'Beeld';
$Definition['images'] = 'afbeeldingen';
$Definition['Images not allowed'] = 'Afbeeldingen niet toegestaan';
$Definition['Images will be scaled to a maximum height of {maxImageHeight}px.'] = 'Afbeeldingen worden aangepast naar een maximum hoogte van {maxImageHeight}px.';
$Definition['Image URL'] = 'Beeld URL';
$Definition['In <b>%s</b> and recent discussions.'] = 'In <b>%s</b> en recente discussies.';
$Definition['Incorrect. Try again.'] = 'Onjuist. Probeer het nogmaals.';
$Definition['Indent'] = 'Inspringing';
$Definition['In recent discussions.'] = 'In recente gesprekken.';
$Definition['In seconds'] = 'In seconden';
$Definition['Insert Image'] = 'Voeg Afbeelding in';
$Definition['Insightful'] = 'Verstandig';
$Definition['Internal'] = 'Intern';
$Definition['In this Conversation'] = 'In dit Gesprek';
$Definition['Invalid password.'] = 'Het wachtwoord dat je invulde was fout. Denk eraan dat wachtwoorden hoofdlettergevoelig zijn.';
$Definition['Invitations'] = 'Uitnodigingen';
$Definition['Invite'] = 'Uitnodiging';
$Definition['InviteErrorPermission'] = 'Sorry, toestemming geweigerd.';
$Definition['Invite Friends'] = 'Nodig vrienden uit';
$Definition['Invite friends'] = 'Nodig vrienden uit';
$Definition['Invite one or more people to join this group.'] = 'Nodig één of meer mensen uit om lid te worden van deze groep.';
$Definition['IPAddress'] = 'IP-Adres';
$Definition['IP Address'] = 'IP-Adres';
$Definition['I remember now!'] = 'Ohja, nu weet ik het weer!';
$Definition['Italic'] = 'Cursief';
$Definition['Item'] = 'Voorwerp';
$Definition['item'] = 'voorwerp';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Het lijkt erop dat je hier nieuw bent. Klik op één van deze knoppen om je aan te melden!';

$Definition['Jail'] = 'Gevangenis';
$Definition['Jailed users have reduced abilities.'] = 'Opgesloten gebruikers hebben minder bevoegdheden.';
$Definition['Join %s'] = 'Word lid %s';
$Definition['Joined'] = 'Aangesloten';
$Definition['Joined %s'] = 'Lid sinds %s';
$Definition['Join this Group'] = 'Word lid van deze groep';
$Definition['Join this group to view its content.'] = 'Word lid van deze groep om de inhoud te bekijken.';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Verwijder alleen de gebruiker, maar bewaar alle inhoud van de gebruiker.';
$Definition['Just expire the warning.'] = 'Laat de waarschuwing alleen verlopen.';
$Definition['Just you!'] = 'Alleen jij!';

$Definition['Keep me signed in'] = 'Houd mij aangemeld';
$Definition['Keep User Content'] = 'Gebruiker tevreden houden';

$Definition['Label'] = 'Etiket';
$Definition['Last Active'] = 'Laatst Actief';
$Definition['Last IP'] = 'Laatste IP';
$Definition['lasts %s'] = 'duurt %s';
$Definition['Latest %1$s'] = 'Laatste %1$s';
$Definition['Latest Post'] = 'Laatste Bericht';
$Definition['Leaders'] = 'Beste Leden';
$Definition['Leave %s'] = 'Verlaat %s';
$Definition['Leave a Comment'] = 'Laat een reactie achter';
$Definition['Leave a comment'] = 'Laat een reactie achter';
$Definition['Leave a redirect link.'] = 'Laat een doorverwijzende link achter.';
$Definition['Leave blank unless connecting to an exising account.'] = 'Laat leeg tenzij je aan een bestaand account aan het koppelen bent.';
$Definition['Leave Comments'] = 'Laat reacties';
$Definition['Leave Group'] = 'Verlaat groep';
$Definition['Length'] = 'Lengte';
$Definition['Level %s'] = 'Niveau %s';
$Definition['Link to content:'] = 'Link naar content:';
$Definition['Locale'] = 'Taalgebied
';
$Definition['Log'] = 'Aanmelden';
$Definition['log'] = 'aanmelden';
$Definition['Login with Facebook'] = 'Log in met Facebook';

$Definition['Major'] = 'Belangrijk';
$Definition['Make me invisible? (Will not show you on the list)'] = 'Mij onzichtbaar maken? (Je zal niet gezien worden op de lijst)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Deze poll anoniem maken (de stemmen van gebruikers worden niet publiekelijk getoond).';
$Definition['Male'] = 'Man';
$Definition['Mark All Viewed'] = 'Markeer alles als Gelezen';
$Definition['Mark as Troll'] = 'Markeer als trol';
$Definition['Mark Category Viewed'] = 'Markeer Categorie Gelezen';
$Definition['Marking as spam cannot be undone.'] = 'Het markeren van iets als SPAM zorgt ervoor dat het voor altijd wordt verwijderd. Verwijderen is een goede manier om je forum schoon te houden.';
$Definition['Mark Read'] = 'Markeer als Gelezen';
$Definition['Maybe'] = 'Misschien';
$Definition['Maybe (%s)'] = 'Misschien (%s)';
$Definition['Member Count'] = 'Leden';
$Definition['Members'] = 'Leden';
$Definition['Merge'] = 'Samenvoegen';
$Definition['Merge Discussions'] = 'Voeg Discussies samen';
$Definition['Message'] = 'Bericht';
$Definition['message'] = 'bericht';
$Definition['Messages'] = 'Berichten';
$Definition['messages'] = 'berichten';
$Definition['Message to User'] = 'Bericht aan gebruiker';
$Definition['Minor'] = 'Onbelangrijk';
$Definition['minutes'] = 'minuten';
$Definition['Moderation'] = 'Moderatie';
$Definition['Moderation Queue'] = 'Moderatielijst';
$Definition['Moderator'] = 'Bemiddelaar';
$Definition['Moderator Activity'] = 'Moderator Activiteiten';
$Definition['Moderators'] = 'Bemiddelaars';
$Definition['moderators'] = 'bemiddelaars';
$Definition['months'] = 'maanden';
$Definition['More'] = 'Meer';
$Definition['More About %s'] = 'Meer over %s';
$Definition['More Comments'] = 'Meer Reacties';
$Definition['More Discussions'] = 'Meer Discussies';
$Definition['More Information'] = 'Meer Informatie';
$Definition['More Results'] = 'Meer resultaten';
$Definition['More…'] = 'Meer...';
$Definition['Most Recent'] = 'Meest Recente';
$Definition['Most recent:'] = 'Meest recent:';
$Definition['Most recent: %1$s by %2$s'] = 'Meest recent: %1$s door %2$s';
$Definition['Most recent by %1$s'] = 'Meest recent door %1$s';
$Definition['Most Recent Comment'] = 'Laatste reactie';
$Definition['Move'] = 'Verplaatsen';
$Definition['MyBadgesModuleTitle'] = 'Mijn Badges';
$Definition['My Bookmarks'] = 'Mijn Bladwijzers';
$Definition['My Discussions'] = 'Mijn Discussies';
$Definition['My Drafts'] = 'Mijn Concepten';
$Definition['My Forums'] = 'Mijn Fora';
$Definition['My Groups'] = 'Mijn Groepen';
$Definition['My Preferences'] = 'Mijn Voorkeuren';
$Definition['My Signature'] = 'Mijn Handtekening';

$Definition['n/a'] = 'niet beschikbaar';
$Definition['Name'] = 'Naam';
$Definition['Name Dropper'] = 'Namennoemer';
$Definition['Name of the Event'] = 'Naam van de Gebeurtenis';
$Definition['Name the Group'] = 'Geef de groep een naam';
$Definition['Name Unavailable'] = 'Naam niet Beschikbaar';
$Definition['new'] = 'nieuw';
$Definition['New %s'] = 'Nieuw %s';
$Definition['New Announcement'] = 'Nieuwe Aankondiging';
$Definition['New Conversation'] = 'Nieuw Bericht';
$Definition['New Discussion'] = 'Nieuwe Discussie';
$Definition['new discussion'] = 'nieuw';
$Definition['New Event'] = 'Nieuw evenement';
$Definition['New Group'] = 'Nieuwe Groep';
$Definition['New Groups'] = 'Nieuwe Groepen';
$Definition['New Message'] = 'Nieuw Bericht';
$Definition['New Password'] = 'Nieuw Wachtwoord';
$Definition['New Poll'] = 'Nieuwe Poll';
$Definition['Next'] = 'Volgende';
$Definition['Ninth Anniversary'] = 'Negende Verjaardag';
$Definition['No'] = 'Nee';
$Definition['NoBadgesEarned'] = 'Bijna&hellip;';
$Definition['No badges yet.'] = 'Nog geen badges.';
$Definition['Nobody has confirmed their attendance yet.'] = 'Er is nog niemand die zijn/haar aanwezigheid al heeft bevestigd.';
$Definition['Nobody has declined the invitation so far.'] = 'Er is nog niemand die de uitnodiging heeft afgewezen.';
$Definition['Nobody is on the fence right now.'] = 'Op dit moment is er niemand die twijfelt.';
$Definition['No default roles.'] = 'Geen standaard rollen';
$Definition['No discussions were found.'] = 'Er zijn geen discussies gevonden.';
$Definition['No items tagged with %s.'] = 'Geen items getagd met %s.';
$Definition['NoPermissionToDeleteDiscussions'] = 'Je hebt geen toestemming om %1$s van de geselecteerde gesprekken te verwijderen.';
$Definition['No results for \'%s\''] = 'Geen resultaten voor \'%s\'.';
$Definition['No Roles'] = 'Geen rollen';
$Definition['Not Attending (%s)'] = 'Niet bijwonen (%s)';
$Definition['Not Authorized (401)'] = 'Niet Toegestaan (401)';
$Definition['Not Found (404)'] = 'Niet Gevonden (404)';
$Definition['Notice'] = 'Aankondiging';
$Definition['Notification'] = 'Notificatie';
$Definition['Notification Preferences'] = 'Notificatievoorkeuren';
$Definition['Notifications'] = 'Notificaties';
$Definition['Notifictions'] = 'Notificaties';
$Definition['Notify'] = 'Waarschuwen';
$Definition['Notify me of private messages.'] = 'Stel mij op de hoogte van privéberichten.';
$Definition['Notify me when a badge is requested.'] = 'Stel mij op de hoogte wanneer er een badge is aangevraagd.';
$Definition['Notify me when a comment is flagged.'] = 'Stel mij op de hoogte wanneer een reactie is gerapporteerd.';
$Definition['Notify me when I am added to private conversations.'] = 'Stel mij op de hoogte wanneer ik wordt toegevoegd aan een privé-gesprek.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Breng me op de hoogte wanneer mensen antwoorden in gesprekken waarin ik heb deelgenomen.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Stel mij op de hoogte wanneer mensen reageren op mijn bewaarde discussies';
$Definition['Notify me when people comment on my discussions.'] = 'Stel mij op de hoogte wanneer mensen reageren op mijn discussies.';
$Definition['Notify me when people mention me.'] = 'Laat mij weten als gebruikers mij noemen.';
$Definition['Notify me when people mention me in comments.'] = 'Stel mij op de hoogte wanneer mensen mij noemen in een reactie.';
$Definition['Notify me when people reply to my wall comments.'] = 'Stel mij op de hoogte wanneer mensen reageren op mijn muurcommentaar.';
$Definition['Notify me when people write on my wall.'] = 'Stel mij op de hoogte wanneer mensen op mijn muur schrijven.';
$Definition['Notify me when there is event activity.'] = 'Hou me op de hoogte van nieuwtjes omtrent gebeurtenissen.';
$Definition['Notify me when there is group activity.'] = 'Breng me op de hoogte van nieuwtjes omtrent groepen.';
$Definition['Not much happening here, yet.'] = 'Hier gebeurt, nog, niet heel veel.';
$Definition['Not Verified'] = 'Niet Geverifieerd';

$Definition[' now.'] = 'nu.';

$Definition['Null Date'] = '-';

$Definition['of'] = 'van';
$Definition['Off Topic'] = 'Off topic';
$Definition['Okay'] = 'Oké';
$Definition['OldPassword'] = 'Oude Wachtwoord';
$Definition['Old Password'] = 'Oud Wachtwoord';
$Definition['on'] = 'aan';
$Definition['Online Preferences'] = 'Online voorkeuren';
$Definition['Only show followed categories'] = 'Toon alleen gevolgde categorieën';
$Definition['OpenID Settings'] = 'OpenID Instellingen';
$Definition['Optional Description'] = 'Optionele Beschrijving';
$Definition['Options'] = 'Opties';
$Definition['or'] = 'of';
$Definition['Ordered list'] = 'Geordende lijst';
$Definition['Organize discussion categories'] = 'Organiseer discussiecategorieën';
$Definition['Organizer'] = 'Organisator';
$Definition['Organize your Categories'] = 'Organiseer je Categorieën';
$Definition['Original'] = 'Oorspronkelijke';
$Definition['Or you can...'] = 'Of je kunt...';
$Definition['Other Records'] = 'Andere Rijen';
$Definition['Outdent'] = 'Uitspringing';
$Definition['Owner'] = 'Eigenaar';

$Definition['PageDetailsMessage'] = '%1$s naar %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s naar %2$s van %3$s';
$Definition['Page Not Found'] = 'Pagina Niet Gevonden';
$Definition['Participated'] = 'Deelgenomen';
$Definition['ParticipatedHomepageTitle'] = 'Deelgenomen Discussies';
$Definition['Password'] = 'Wachtwoord';
$Definition['Password Contains Username'] = 'Bevat Gebruikersnaam';
$Definition['Password Good'] = 'Goed';
$Definition['Password Ok'] = 'Oké';
$Definition['PasswordRequest'] = 'Hallo %1$s,

Iemand heeft een aanvraag gedaan om je wachtwoord opnieuw in te stellen op %2$s. Klik op onderstaande link om je wachtwoord opnieuw in te stellen: 

  %3$s

Mocht jij deze aanvraag niet hebben gedaan dan mag je deze e-mail negeren.';
$Definition['Passwords don\'t match'] = 'Wachtwoorden komen niet overeen';
$Definition['Password Strong'] = 'Zeer goed';
$Definition['Password Too Short'] = 'Te Kort';
$Definition['Password Very Weak'] = 'Zeer zwak';
$Definition['Password Weak'] = 'Zwak';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Kopieer de URL van een beeld om het snel toe te voegen.';
$Definition['PermissionErrorMessage'] = 'U heeft geen rechten om die actie uit te voeren';
$Definition['PermissionErrorTitle'] = 'Rechtenprobleem';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Je moet een moderator zijn om dat te doen.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Je moet een administrator zijn om dat te doen.';
$Definition['PermissionRequired.Javascript'] = 'Je moet javascript inschakelen om dat te doen.';
$Definition['Photogenic'] = 'Fotogeniek';
$Definition['Picture'] = 'Afbeelding';
$Definition['Pin'] = 'Zet vast';
$Definition['Pinned'] = 'Vastgezet';
$Definition['Play the sound again'] = 'Laat het geluid nogmaals horen';
$Definition['Please join my group.'] = 'Neem deel aan mijn <a href="{Url,html}">groep</a>. ';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Je wordt doorgestuurd, even geduld alsjeblieft. Als je niet wordt doorgestuurd, klik dan  <a href="%s">hier</a>.';
$Definition['Points'] = 'Punten';
$Definition['Poll'] = 'Toppen';
$Definition['Poll Options'] = 'Pollopties';
$Definition['Poll Question'] = 'Pollvraag';
$Definition['Popular'] = 'Populair';
$Definition['Popular Discussions'] = 'Populaire Discussies';
$Definition['Popular Groups'] = 'Populaire Groepen';
$Definition['Popular Tags'] = 'Populaire Tags';
$Definition['Position'] = 'Positie';
$Definition['Post'] = 'Bericht';
$Definition['post'] = 'bericht';
$Definition['Post Comment'] = 'Plaats Reactie';
$Definition['Post Discussion'] = 'Plaats Discussie';
$Definition['Post edited by %1$s at %2$s'] = 'Bericht bewerkt door %1$s op %2$s';
$Definition['Posts'] = 'Berichten';
$Definition['Posts.Plural: %s'] = 'Berichten: %s ';
$Definition['Posts.Singular: %s'] = 'Berichten: %s ';
$Definition['Posts: %s'] = 'Berichten: %s ';
$Definition['Post this anonymously'] = 'Publiceer dit bericht anoniem';
$Definition['Powered by %s'] = 'Aangedreven door %s';
$Definition['Powered by Vanilla'] = 'Aangedreven door Vanilla';
$Definition['PreferenceBadgeEmail'] = 'Stel mij op de hoogte als ik een badge ontvang.';
$Definition['PreferenceBadgePopup'] = 'Stel mij op de hoogte als ik een badge ontvang.';
$Definition['Preview'] = 'Voorbeeld';
$Definition['Previous'] = 'Vorige';
$Definition['Privacy Settings'] = 'Privacyinstellingen';
$Definition['Private'] = 'Persoonlijk';
$Definition['Private group.'] = 'Iedereen kan de groep zien, maar alleen leden zien de inhoud. Anderen moeten een verzoek sturen of een uitnodiging krijgen om lid te worden.';
$Definition['Private Note for Moderators'] = 'Privéopmerking voor Moderators';
$Definition['Problem with credentials.'] = 'Probleem met gegevens.';
$Definition['Proceed'] = 'Ga verder';
$Definition['Profile'] = 'Profiel';
$Definition['Profile Fields'] = 'Profielvelden';
$Definition['Profile  Fields'] = 'Profielvelden';
$Definition['ProfileFieldsCustomDescription'] = 'Gebruik deze velden om aangepaste profielinformatie aan te maken. Je kan dingen invullen als "Relatiestatus", "Skype", of "Favoriete Dinosaurus". Ben creatief!';
$Definition['Profile Page'] = 'Profielpagina';
$Definition['Profile Picture'] = 'Profiel Afbeelding';
$Definition['Profiles'] = 'Profielen';
$Definition['Promote'] = 'Promoot';
$Definition['Public'] = 'Openbaar';
$Definition['Public group.'] = 'Iedereen kan de groep en haar inhoud zien. Iedereen kan lid worden.';

$Definition['Q&A'] = 'Q&A ';
$Definition['Q&A Accepted'] = 'Beantwoord ✓';
$Definition['Q&A Answered'] = 'Beantwoord';
$Definition['Q&A Options'] = 'Q&A Opties';
$Definition['Q&A Question'] = 'Vraag';
$Definition['QnA Accepted Answer'] = 'Antwoord ✓';
$Definition['QnA Rejected Answer'] = 'Geweigerd Antwoord';
$Definition['Question'] = 'Vraag';
$Definition['question'] = 'vraag';
$Definition['Questions'] = 'Vragen';
$Definition['questions'] = 'vragen';
$Definition['Question Title'] = 'Vraag Titel';
$Definition['Quote'] = 'Aanhalen';
$Definition['Quote Folding'] = 'Quote Inklappen';
$Definition['Quote on'] = 'op';
$Definition['Quote Settings'] = 'Citaat Instellingen';
$Definition['Quote wrote'] = 'schreef';

$Definition['Rank'] = 'Rang';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,is,zijn} gepromoveerd tot {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = 'Gefeliciteerd! Je bent gepromoveerd tot {Data.Name,plaintext}.';
$Definition['Re: %s'] = 'Re: %s ';
$Definition['Reactions'] = 'Reacties';
$Definition['Real Name'] = 'Echte Naam';
$Definition['Reason'] = 'Reden';
$Definition['Reason (optional)'] = 'Reden (optioneel)';
$Definition['Recent Activity'] = 'Recente Activiteiten';
$Definition['Recent Admin Activity'] = 'Recente Adminactiviteit';
$Definition['Recent Discussions'] = 'Recente Discussies';
$Definition['Recent Events'] = 'Recente evenementen';
$Definition['recently'] = 'recent';
$Definition['Recent Moderator Activity'] = 'Recente Moderatoractiviteit';
$Definition['Recent Tutorials'] = 'Recente Tutorials';
$Definition['Recipients'] = 'Ontvangers';
$Definition['RecipientUserID'] = 'ontvanger';
$Definition['Redirecting...'] = 'Omleiden...';
$Definition['Refetch Page'] = 'Pagina opnieuw ophalen';
$Definition['Register'] = 'Registreren';
$Definition['Register IP'] = 'Registreer IP';
$Definition['Register with %s'] = 'Registreer';
$Definition['Registration  Fields'] = 'Registratievelden';
$Definition['Registration URL'] = 'Registratie URL';
$Definition['Reject'] = 'Weiger';
$Definition['Reject this answer.'] = 'Weiger dit antwoord';
$Definition['Remember me'] = 'Onthoud mij';
$Definition['Remember me on this computer'] = 'Onthoud mij op deze computer';
$Definition['Remote Configuration'] = 'Externe Configuratie';
$Definition['Remove'] = 'Verwijder';
$Definition['Removed by'] = 'Verwijderd door';
$Definition['Remove from %s'] = 'Verwijderen uit %s';
$Definition['Remove Invitation'] = 'Verwijder uitnodiging';
$Definition['Remove My Picture'] = 'Verwijder Mijn Afbeelding';
$Definition['Remove Picture'] = 'Verwijder Afbeelding';
$Definition['Remove Warning'] = 'Verwijder Waarschuwing';
$Definition['Rename Forum'] = 'Hernoem Forum';
$Definition['Reopen'] = 'Opnieuw openen';
$Definition['Replies'] = 'Antwoorden';
$Definition['Reply'] = 'Antwoorden';
$Definition['ReplyOnly'] = 'Je kan rechtstreeks op deze e-mail antwoorden voor verdere opvolging. Verstuurd van {/,exurl}.';
$Definition['ReplyOrFollow'] = 'Antwoord rechtstreeks op deze e-mail of volg de link hieronder om het te bekijken:';
$Definition['Report'] = 'Melden';
$Definition['Report %s'] = 'Rapporteer %s';
$Definition['Reported by: '] = 'Gerapporteerd door:';
$Definition['Reported Posts'] = 'Gerapporteerde berichten';
$Definition['Report Notes'] = 'Notities';
$Definition['Report Reason'] = 'Reden';
$Definition['Request a new password'] = 'Vraag een nieuw wachtwoord aan';
$Definition['Request a new password →'] = 'Vraag een nieuw wachtwoord aan →';
$Definition['Reset Password'] = 'Reset Wachtwoord';
$Definition['Restored'] = 'Hersteld';
$Definition['reverse'] = 'omgekeerd';
$Definition['Revoke'] = 'Neem terug';
$Definition['Revoked'] = 'Ingetrokken';
$Definition['Revoked badge.'] = 'Teruggenomen badge.';
$Definition['role'] = 'rol';
$Definition['RoleID'] = 'rol';
$Definition['Roles'] = 'Rollen';
$Definition['roles'] = 'rollen';

$Definition['Save'] = 'Opslaan';
$Definition['Save Comment'] = 'Sla Reactie op';
$Definition['Save Draft'] = 'Concept Opslaan';
$Definition['Save Poll'] = 'Bewaar Poll';
$Definition['Save Preferences'] = 'Voorkeuren Opslaan';
$Definition['Save your password'] = 'Sla je wachtwoord op';
$Definition['Search'] = 'Zoeken';
$Definition['Search %s'] = 'Zoek naar %s';
$Definition['search archived'] = 'zoek in archief';
$Definition['SearchBoxPlaceHolder'] = 'Zoeken';
$Definition['Search for a tag.'] = 'Zoek voor alles of voor een deel van een tag.';
$Definition['Search results for \'%s\''] = 'Zoekresultaten voor \'%s\'';
$Definition['search subcategories'] = 'zoek in subcategorieën';
$Definition['Second Anniversary'] = 'Tweede verjaardag';
$Definition['Secret'] = 'Geheim';
$Definition['Sections'] = 'Secties';
$Definition['Security Check'] = 'Beveiligingscontrole';
$Definition['Select an image on your computer (2mb max)'] = 'Selecteer een afbeelding op je computer (max. 2MB)';
$Definition['Select one of the following avatars:'] = 'Selecteer één van de volgende avatars:';
$Definition['Send a New Message'] = 'Verzend een Nieuw Bericht';
$Definition['Send Message'] = 'Stuur Bericht';
$Definition['Send Report'] = 'Verstuur Bericht';
$Definition['Send report'] = 'Verstuur bericht';
$Definition['sep and'] = 'en';
$Definition['Set a New Warning Level'] = 'Bepaal een Nieuw Waarschuwingsniveau';
$Definition['Set A Password'] = 'Een Wachtwoord Instellen';
$Definition['Setting'] = 'Instelling';
$Definition['Settings'] = 'Instellingen';
$Definition['Seventh Anniversary'] = 'Zevende verjaardag';
$Definition['Severity'] = 'Ernst';
$Definition['Share'] = 'Delen';
$Definition['Shared Accounts'] = 'Gedeelde Accounts';
$Definition['she'] = 'zij';
$Definition['Shown only on mobile'] = 'Toon alleen op mobiel';
$Definition['Show unfollowed categories'] = 'Toon niet-gevolgde categorieën';
$Definition['Sign-In URL'] = 'Log-in URL';
$Definition['Sign-Out URL'] = 'Log-uit URL';
$Definition['Signature'] = 'Handtekening';
$Definition['Signature Code'] = 'Handtekeningcode';
$Definition['Signature invalid.'] = 'Handtekening ongeldig.';
$Definition['Signatures'] = 'Handtekeningen';
$Definition['Signatures can be up to {maxLength} characters long.'] = 'Handtekeningen kunnen maximaal (maxLength) tekens bevatten. ';
$Definition['Signature Settings'] = 'Handtekening Instellingen';
$Definition['SignIn'] = 'Inloggen';
$Definition['Sign In'] = 'Inloggen';
$Definition['SigningOut'] = 'Wacht even een seconde terwijl we je uitloggen.';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Log In</a> of <a href="{RegisterUrl,html}">Registreer</a> om te reageren.';
$Definition['Sign in to vote!'] = 'Log in om te stemmen!';
$Definition['Sign In with %s'] = 'Log in met %s';
$Definition['Sign In with Disqus'] = 'Log in met Disqus';
$Definition['Sign In with Facebook'] = 'Log in met Facebook';
$Definition['Sign In with Google'] = 'Inloggen met Google';
$Definition['Sign In with OpenID'] = 'Inloggen met OpenID';
$Definition['Sign In with Twitter'] = 'Inloggen met Twitter';
$Definition['Sign Out'] = 'Afmelden';
$Definition['sign out'] = 'log uit';
$Definition['Sign Up'] = 'Registreer';
$Definition['Sink'] = 'Laten zinken';
$Definition['Sink this discussion'] = 'Verzink deze discussie';
$Definition['Sitemap Settings'] = 'Sitemap Instellingen';
$Definition['Sixth Anniversary'] = 'Zesde verjaardag';
$Definition['Social'] = 'Sociaal';
$Definition['somebody'] = 'iemand';
$Definition['Some Code'] = 'Een beetje Code';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Iemand heeft je vraag beantwoord. Je moet dit antwoord accepteren of weigeren.';
$Definition['sorted by'] = 'gesorteerd door';
$Definition['Source:'] = 'Bron:';
$Definition['Source Code'] = 'Code';
$Definition['Spam Queue'] = 'Spamlijst';
$Definition['Split'] = 'Splits';
$Definition['Split Comments'] = 'Splits Reacties';
$Definition['Spoof User'] = 'Doe een Gebruiker na';
$Definition['Start'] = 'Beginnen';
$Definition['Start a Group'] = 'Met een groep beginnen';
$Definition['Start a New Conversation'] = 'Nieuw Bericht';
$Definition['Start a New Discussion'] = 'Nieuwe Discussie';
$Definition['Start Conversation'] = 'Start Gesprek';
$Definition['Started By'] = 'Gestart Door';
$Definition['Started by'] = 'Aangemaakt door';
$Definition['Started by %1$s'] = 'Gestart door %1$s';
$Definition['Start your First Discussion'] = 'Start je eerste Discussie';
$Definition['Stop following'] = 'Stop met volgen';
$Definition['Strikethrough'] = 'Doorhalen';
$Definition['Strip images out of signatures'] = 'Toon geen afbeeldingen in handtekeningen';
$Definition['Strip images out of signatures?'] = 'Haal de afbeeldingen uit handtekeningen?';
$Definition['Subject'] = 'Onderwerp';
$Definition['Suggested Value'] = 'Voorgestelde Waarde';

$Definition['Tagged'] = 'Getagd';
$Definition['Tagged with '] = 'Getagd met';
$Definition['Tagged with "%s"'] = 'Getagd met "%s"';
$Definition['Tagging'] = 'Taggen';
$Definition['TagHint'] = 'Begin te typen...';
$Definition['Tag Name'] = 'Tagnaam';
$Definition['Tags'] = 'Etiketten';
$Definition['tags'] = 'etiketten';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Tags zijn trefwoorden die gebruikers aan discussies kunnen toewijzen om ervoor te zorgen dat hun vraag bij vergelijkbare vragen wordt gecategoriseerd.';
$Definition['Take Action'] = 'Neem Actie';
$Definition['Take Action:'] = 'Neem Actie:';
$Definition['Target'] = 'Doelwit';
$Definition['Tell the user why you\'re warning them'] = 'Zeg de gebruiker waarom je hem waarschuwt';
$Definition['Tell us why you want to join!'] = 'Vertel ons waarom je je wil aansluiten!';
$Definition['Tenth Anniversary'] = 'Tiende verjaardag';
$Definition['Terms'] = 'Voorwaarden';
$Definition['TermsOfService'] = 'Gebruikersvoorwaarden';
$Definition['Terms of Service'] = 'Servicevoorwaarden';
$Definition['TermsOfServiceText'] = '
   <p>Je stemt ermee in, door deze dienst te gebruiken, dat je deze community niet zal gebruiken om enig materiaal te uploaden dat bewust misleidend en/of kwetsend, onjuist, beledigend, vulgair, hatelijk, obsceen, profaan, sexueel geörienteerd, bedreigend, iemands privacy schendend, of op een andere wijze een wet overtreed. Je stemt ermee in om geen auteursrechtelijk beschermd materiaal te uploaden tenzij het auteursrecht bij jouw ligt.</p>
   
   <p>Wij bij deze community houden ons het recht voor om jouw identiteit kenbaar te maken (of wat voor informatie we van je weten) in het geval van een klacht of gerechtelijke stappen die een gevolg zijn van een door jouw gepubliceerd bericht. We bewaren alle internet-protocoladressen die deze website binnenkomen.</p>
   
   <p>Houd er alstjeblieft rekening mee dat reclame, kettingbrieven, pyramidespelen, en sollicitaties ongepast zijn voor deze community.</p>
   
   <p>We houden ons het recht voor enig materiaal te verwijderen, met of zonder enige reden. We houden ons het recht voor elk lidmaatschap te beëindigen, met of zonder enige reden.</p>
   
   <p>Je moet op zijn minst 13 jaar oud zijn om deze dienst te gebruiken.</p>
';
$Definition['Text  Max  Length'] = 'Maximale Tekstlengte';
$Definition['The %s you were looking for could not be found.'] = 'De %s die je zocht, kon niet gevonden worden.';
$Definition['the category'] = 'de categorie';
$Definition['The content you were looking for has been deleted.'] = 'De inhoud waar je naar op zoek bent is verwijderd.';
$Definition['The conversation has been cleared.'] = 'Het gesprek is leeggemaakt.';
$Definition['The email you entered in use by another member.'] = 'Het ingevulde e-mailadres wordt gebruikt door een ander lid.';
$Definition['The email you have entered is already related to an existing account.'] = 'Het ingevulde e-mailadres is al gekoppeld aan een bestaand account.';
$Definition['The file failed to upload.'] = 'Het uploaden van het bestand is mislukt.';
$Definition['their'] = 'hun';
$Definition['The name you entered is already in use by another member.'] = 'De ingevulde naam is al in gebruik door een ander lid.';
$Definition['The page you were looking for could not be found.'] = 'De pagina waarnaar je zocht kon niet gevonden worden.';
$Definition['The quote had to be converted from %s to %s.'] = 'De quote moest van %s naar %s veranderd worden. Er kan een beetje uiterlijk verloren zijn gegaan.';
$Definition['There\'s already a %s with the name %s.'] = 'Er is al een %1$s met de naam %2$s.';
$Definition['There aren\'t any groups yet.'] = 'Er zijn nog geen groepen.';
$Definition['There are no tags in the system yet.'] = 'Er zijn nog geen tags in het systeem.';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'De reCAPTCHA-waarde is niet correct ingevuld. Probeer alstublieft opnieuw.';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Er is al een account met dezelfde gebruikersnaam (%1$s) of hetzelfde e-mailadres (%2$s) als jij. Je kan een nieuw account aanmaken, of inloggen met je bestaande forumaccount.';
$Definition['The response was not in the correct format.'] = 'Het antwoord was niet in het juiste formaat.';
$Definition['There was an error connecting to Disqus'] = 'Er is een fout opgetreden bij het verbinden met Disqus';
$Definition['There was an error connecting to Facebook'] = 'Er is een fout opgetreden bij het verbinden met Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Er is een fout opgetreden bij het uploaden van het bestand. Dit komt waarschijnlijk omdat het bestand te groot is.';
$Definition['The site is currently undergoing maintenance.'] = 'De site ondervindt momenteel onderhoud.';
$Definition['The uploaded file was too big (max %s).'] = 'Het geüploade bestand was te groot (max %s).';
$Definition['The user has already been warned for this %s.'] = 'De gebruiker is hiervoor al gewaarschuwd %s.';
$Definition['they'] = 'zij';
$Definition['Third Anniversary'] = 'Derde verjaardag';
$Definition['This answer was %s.'] = 'Dit antwoord was %s.';
$Definition['This answer was Accepted.'] = 'Dit antwoord was Geaccepteerd.';
$Definition['This discussion has been closed.'] = 'Deze discussie is gesloten.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Deze discussie is gerelateerd aan een ongedefinieerde vreemde inhoudsbron.';
$Definition['This discussion was created from comments split from: %s.'] = 'Deze discussie is gecreeërd van reacties die gesplitst zijn van: %s.';
$Definition['This discussion was merged into %s'] = 'Deze discussie is samengevoegd in %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Deze afbeelding is verkleind om te op de pagina te passen. Klik om te vergroten.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Dit is een anonieme poll: niemand zal zien waar je voor hebt gestemd.';
$Definition['This is a public poll: others will see what you voted for.'] = 'Dit is een publieke poll: anderen zullen zien waar je voor gestemd hebt.';
$Definition['This is a system account and does not represent a real person.'] = 'Dit is een systeemaccount en representeert geen echt persoon.';
$Definition['This Month\'s Leaders'] = 'De beste Leden van deze Maand';
$Definition['This question\'s answer has been accepted.'] = 'Het antwoord op deze vraag is geaccepteerd.';
$Definition['This user has been verified as a non-spammer.'] = 'Deze gebruiker is geverifieerd als non-spammer.';
$Definition['This user has not been verified as a non-spammer.'] = 'Deze gebruiker is niet geverifieerd als een non-spammer.';
$Definition['This user has not commented yet.'] = 'Deze gebruiker heeft nog niet gereageerd.';
$Definition['This user has not made any discussions yet.'] = 'Deze gebruiker heeft nog geen discussies gestart.';
$Definition['This user is verified as a non-spammer'] = 'Deze gebruiker is geverifieerd als non-spammer.';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Deze waarschuwing is verlopen. Wil je deze volledig verwijderen?';
$Definition['This Week\'s Leaders'] = 'De beste Leden van deze Week';
$Definition['Thumbnail'] = 'Miniatuur';
$Definition['Title'] = 'Titel';
$Definition['To'] = 'Aan';
$Definition['Toggle full page'] = 'Volledig scherm aan/uit';
$Definition['Toggle HTML view'] = 'HTML-weergave aan/uit';
$Definition['Toggle lights'] = 'Lichten aan/uit';
$Definition['Topic'] = 'Onderwerp';
$Definition['Topics'] = 'Onderwerpen';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'Klik <a href="%s">hier</a> om nog een bevestigingsmail te verzenden.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'Om reCAPTCHA te gebruiken moet je eerst een API-sleutel krijgen van %s';
$Definition['Transport error: %s'] = 'Er is een fatale fout opgetreden bij het verwerken van het verzoek.<br />De server geeft de volgende reactie: %s';
$Definition['Turn ON'] = 'Zet AAN';
$Definition['Twitter Settings'] = 'Twitter Instellingen';
$Definition['Type the text:'] = 'Type de tekst:';
$Definition['Type what you hear:'] = 'Type wat u hoort:';

$Definition['Unable to send message, %s is ignoring you.'] = 'Bericht kan niet verzonden worden, %s negeert je.';
$Definition['Unannounce'] = 'Niet Aankondigen';
$Definition['Unanswered'] = 'Onbeantwoord';
$Definition['Unanswered Questions'] = 'Onbeantwoord';
$Definition['unavailable'] = 'onbeschikbaar';
$Definition['Unban User'] = 'Hef verbanning op.';
$Definition['Unbookmark'] = 'Verwijder Bladwijzer';
$Definition['Undefined discussion body.'] = 'Ongedefinieerde discussieinhoud';
$Definition['Undefined discussion subject.'] = 'Ongedefiniëerd discussieonderwerp.';
$Definition['Undefined foreign content'] = 'Ongedefinieerde vreemde inhoud';
$Definition['Undo Follow'] = 'Maak Volgen ongedaan';
$Definition['Unfollow'] = 'Stop met volgen';
$Definition['Unhide'] = 'Toon';
$Definition['Unignore'] = 'Negeren opheffen';
$Definition['UniqueID'] = 'UniekID';
$Definition['Unknown'] = 'Onbekend';
$Definition['Unknown client: %s.'] = 'Onbekende client: %s.';
$Definition['Unordered list'] = 'Ongeordende lijst';
$Definition['Unread'] = 'Ongelezen';
$Definition['Unread Discussions'] = 'Ongelezen Discussies';
$Definition['Unsink'] = 'Niet zinken';
$Definition['Unspecified'] = 'Niet gespecificeerd';
$Definition['Upcoming Events'] = 'Aanstaande evenementen';
$Definition['Update'] = 'Updaten';
$Definition['Updated badge'] = 'Bijgewerkte badge';
$Definition['Upload'] = 'Uploaden';
$Definition['Uploading...'] = 'Aan het uploaden...';
$Definition['Url'] = 'URL';
$Definition['UrlCode'] = 'URL-code';
$Definition['Use My Current Password'] = 'Gebruik Mijn Huidige Wachtwoord';
$Definition['User "%s" does not exist.'] = 'Gebruiker "%s" bestaat niet.';
$Definition['Username'] = 'Gebruikersnaam';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Gebruikersnaam mag alleen bestaan uit letters, cijfers en underscores.';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'Gebruikersnaam mag alleen bestaan uit letters, cijfers, underscores, en moet tussen de 3 en 20 tekens lang zijn.';
$Definition['UsernameError'] = 'Gebruikersnaam kan alleen letters, cijfers en underscores bevatten en moet tussen 3 en 20 karakters lang zijn.';
$Definition['Username or email'] = 'Gebruikersnaam of e-mailadres';
$Definition['User not found.'] = 'Sorry, er is geen account gevonden gerelateerd aan het ingevoerde e-mailadres en wachtwoord.';
$Definition['Users Count'] = 'Aantal Gebruikers';
$Definition['Use up to {maxImages,plural,%s image, %s images}.'] = 'Gebruik tot maximaal {maxImages,plural,%s image, %s images}.';

$Definition['ValidateBanned'] = 'Dat, %s, is niet toegestaan.';
$Definition['ValidateBoolean'] = '%s is geen geldige boolean.';
$Definition['ValidateConnection'] = 'Met de huidige verbindingsparameters is het niet gelukt om een verbinding met de database op te zetten. De database geeft de volgende foutmelding: <code>%s</code>';
$Definition['ValidateDate'] = '%s is geen geldige datum.';
$Definition['ValidateDecimal'] = '%s is geen geldige decimale.';
$Definition['ValidateEmail'] = '%s lijkt niet geldig te zijn.';
$Definition['ValidateEnum'] = '%s is niet geldig.';
$Definition['ValidateFormat'] = 'Je bent niet toegestaan om rauwe html te plaatsen.';
$Definition['ValidateInteger'] = '%s is geen geldige integer.';
$Definition['ValidateIntegerArray'] = '%s moet een door komma gescheiden lijst met getallen zijn.';
$Definition['ValidateLength'] = '%1$s is %2$s karakters te lang';
$Definition['ValidateMatch'] = 'De %s velden komen niet overeen.';
$Definition['ValidateMinimumAge'] = 'Je bent niet oud genoeg om lid te worden van deze groep.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Je moet ten minste één %s.';
$Definition['ValidateRegex'] = '%s lijkt niet in het juiste formaat.';
$Definition['ValidateRequired'] = '%s is vereist.';
$Definition['ValidateRequiredArray'] = 'Je moet ten minste één %s selecteren.';
$Definition['ValidateTag'] = 'Tags kunnen geen spaties bevatten.';
$Definition['ValidateTime'] = '%s is geen geldige tijd.';
$Definition['ValidateTimestamp'] = '%s is geen geldige timestamp.';
$Definition['ValidateUrlStringRelaxed'] = '%s kan geen slashes, quotes- of tag-karakters bevatten.';
$Definition['ValidateUsername'] = 'Gebruikersnamen moeten 3-20 tekens lang zijn en mogen alleen bestaan uit letters, cijfers en underscores.';
$Definition['ValidateVersion'] = 'Het %s veld heeft geen geldig versienummer. Bekijk de php version_compare() functie voor een voorbeeld van geldige versienummers.';
$Definition['Value'] = 'Waarde';
$Definition['Vanilla Statistics'] = 'Vanilla Statistieken';
$Definition['Vanilla Statistics Plugin'] = 'Vanilla Statistieken Plugin';
$Definition['Verified'] = 'Geverifieerd ';
$Definition['Verifying your credentials...'] = 'Je gegevens aan het controleren...';
$Definition['via %s'] = 'via %s ';
$Definition['Video embedding has been disabled.'] = 'Het insluiten van video\'s is uitgeschakeld. URL\'s zullen niet vertaald worden naar een insluitlink.  ';
$Definition['View Badge'] = 'Toon Badge';
$Definition['Viewing'] = 'Weergeven';
$Definition['Views'] = 'keer bekeken';
$Definition['Visible'] = 'Zichtbaar';
$Definition['Visits'] = 'Bezoeken';
$Definition['Visit Site'] = 'Bezoek Site';
$Definition['Vote'] = 'Stem';
$Definition['Vote Down'] = 'Stem Tegen';
$Definition['Votes'] = 'Stemmen';
$Definition['Vote Up'] = 'Stem Voor';

$Definition['wall'] = 'muur';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Wil je meedoen in deze discussie? Klik op een van deze:';
$Definition['Warn'] = 'Waarschuw';
$Definition['Warn %s'] = 'Waarschuw %s';
$Definition['Warned for'] = 'Gewaarschuwd voor';
$Definition['Warning'] = 'Waarschuwing';
$Definition['Warnings'] = 'Waarschuwingen';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} waarschuwde {WarnUserID,User} voor {Points,plural,%s punten}.';
$Definition['WarningTitleFormat.Notice'] = '{InsertUserID,User} waarschuwde {WarnUserID,User} voor {Points,plural,%s punten} (alleen een opmerking).';
$Definition['weeks'] = 'weken';
$Definition['Welcome Aboard!'] = 'Welkom aan Boord!';
$Definition['were'] = 'waren';
$Definition['What\'s This?'] = 'Wat is dit?';
$Definition['What to search'] = 'Wat te zoeken';
$Definition['When'] = 'Wanneer';
$Definition['Where'] = 'Waar';
$Definition['Where do you want to announce this discussion?'] = 'Waar wil je deze discussie aankondigen?';
$Definition['Who\'s going?'] = 'Wie gaat er?';
$Definition['Who\'s Online'] = 'Wie is Online';
$Definition['Who\'s Online in this Category'] = 'Wie is er Online in deze Categorie';
$Definition['Who\'s Online in this Discussion'] = 'Wie is er Online in deze Discussie';
$Definition['Whoops!'] = 'Oeps!';
$Definition['Whoops! You\'ll need to register before you can email our site.'] = 'Oeps! Je moet je registreren voor je een e-mail naar onze website kan sturen.';
$Definition['Why are you Banning this user?'] = 'Waarom verban je deze gebruiker?';
$Definition['Why do you want to join?'] = 'Waarom wil jij je aansluiten?';
$Definition['Would you like to accept the invitation to join this group?'] = 'Aanvaard je de uitnodiging om lid te worden van deze groep?';
$Definition['Write a comment'] = 'Schrijf een Reactie';
$Definition['Write Comment'] = 'Schrijf Reactie';
$Definition['Write something about yourself...'] = 'Schrijf iets over jezelf...';

$Definition['Yes'] = 'Ja';
$Definition['You'] = 'Jij';
$Definition['you'] = 'jij';
$Definition['You\'re banned from joining this group.'] = 'U bent verboden om lid te worden van deze groep.';
$Definition['You\'ve already created the maximum number of groups.'] = 'U heeft de maximum hoeveelheid aan groepen al aangemaakt.';
$Definition['You\'ve applied to join this group.'] = 'U heeft u aangemeld om lid te worden van deze groep.';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">Je hebt vragen gesteld die nu beantwoord zijn</a>. Zorg ervoor dat je de antwoorden aanvaardt/afkeurt.';
$Definition['You\'ve been invited to join {Name}.'] = 'Je bent uitgenodigd om lid te worden van {Name}.';
$Definition['You\'ve been Jailed.'] = 'Je bent Opgesloten.';
$Definition['You already have an account here.'] = 'Je hebt hier al een account.';
$Definition['You are about to ban {User.UserID,user}.'] = 'Je staat op het punt om {User.UserID,user} te verbannen.';
$Definition['You are about to move %1$s of the %2$s of the selected discussions.'] = 'Je staat op het punt om %1$s van de %2$s geselecteerde gesprekken te verplaatsen.';
$Definition['You are about to move %s.'] = 'Je staat op het punt om %s te verplaatsen.';
$Definition['You are about to unban {User.UserID,user}.'] = 'Je staat op het punt de verbanning voor {User.UserID,user} op te heffen.';
$Definition['You are allowed to create %s groups.'] = 'U mag %s groepen maken. ';
$Definition['You are already a member of this group.'] = 'U bent al een lid van deze groep.';
$Definition['You are connected as %s through %s.'] = 'Je bent verbonden als %s door %s.';
$Definition['You are connected through %2$s.'] = 'Je bent verbonden via %2$s.';
$Definition['You are currently only viewing categories that you follow.'] = 'Je bekijkt momenteel alleen categorieën die je aan het volgen bent.';
$Definition['You are currently viewing all categories.'] = 'Je bekijkt momenteel alle categorieën.';
$Definition['You are editing %s\'s signature'] = 'Je bent %s zijn handtekening aan het bewerken.';
$Definition['You are limited to %s recipient.'] = 'Maximaal %s ontvanger. ';
$Definition['You are limited to %s recipients.'] = 'Maximaal %s ontvangers.';
$Definition['You aren\'t a %s of this group.'] = 'U bent geen %s van deze groep.';
$Definition['You aren\'t allowed to %s this group.'] = 'U bent niet toegestaan tot %s deze groep.';
$Definition['You are only allowed {maxImages,plural,%s image,%s images}.'] = 'U mag slechts {maxImages,plural,%s image,%s images}.';
$Definition['You can\'t leave the group you started.'] = 'Je kan de groep die je gemaakt hebt niet verlaten.';
$Definition['You can either ask a question or start a discussion.'] = 'Je kan een vraag stellen of een discussie starten. Kies hieronder wat je wilt doen.';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Je kan individuele categorieën volgen en op de hoogte gesteld worden van alle berichten daarin. ';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Je kan de thumbnail van een externe profielfoto niet bewerken.';
$Definition['You can only specify up to %s tags.'] = 'Je kan alleen tot %s tags toewijzen.';
$Definition['You can remove or ban this member from the group.'] = 'U kunt deze persoon verwijderen of verbannen uit de groep. Verbannen personen kunnen niet opnieuw lid worden van de groep. ';
$Definition['You can use HTML in your signature.'] = 'Je kunt <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple Html</a></b> in je handtekening gebruiken.';
$Definition['You don\'t have permission to do that.'] = 'U heeft geen permissie om die actie uit te voeren.';
$Definition['You don\'t have permission to use a signature.'] = 'U heeft geen toestemming om een handtekening te gebruiken';
$Definition['You do not have any %s yet.'] = 'Je hebt nog geen %s.';
$Definition['You do not have any bookmarks.'] = 'Je hebt geen bladwijzers.';
$Definition['You do not have any conversations.'] = 'Je hebt geen gesprekken.';
$Definition['You do not have any drafts.'] = 'Je hebt geen concepten.';
$Definition['You do not have any notifications yet.'] = 'Je hebt nog geen notificaties.';
$Definition['You do not have enough invitations left.'] = 'Je hebt niet genoeg uitnodigingen over.';
$Definition['You do not have permission to move %1$s of the selected discussions.'] = 'Je hebt geen toestemming om %1$s van de geselecteerde gesprekken te verplaatsen.';
$Definition['You do not have permission to write new comments.'] = 'U heeft een permissie om nieuw commentaar te schrijven.';
$Definition['YouEarnedBadge'] = 'U heeft deze badge verdiend.';
$Definition['You have answered questions'] = 'U heeft vragen beantwoord';
$Definition['You have entered an invalid discussion title'] = 'U heeft een ongeldige discussie titel ingevoerd';
$Definition['You haven\'t joined any groups yet.'] = 'U bent nog geen lid van een groep.';
$Definition['You haven\'t read this yet.'] = 'Je hebt dit nog niet lezen.';
$Definition['You have not started any discussions.'] = 'U heeft nog geen discussies gestart.';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'U heeft %1$s keer gepost binnen %2$s seconden. Een spam block is nu in effect op uw account. U dient ten minste %3$s seconden te wachten voordat u weer een poging kunt doen om te posten.';
$Definition['You have selected %1$s.'] = 'U heeft %1$s geselecteerd.';
$Definition['You have selected %1$s in this discussion.'] = 'U heeft %1$s geselecteerd in deze discussie.';
$Definition['You have to select at least 2 discussions to merge.'] = 'U dient ten minste 2 discussies te selecteren om deze te kunnen samenvoegen.';
$Definition['You must agree to the terms of service.'] = 'Je moet akkoord gaan met de gebruiksvoorwaarden.';
$Definition['You need to confirm your email address.'] = 'Je moet je e-mailadres bevestigen. Klik <a href="{/entry/emailconfirmrequest,url}">hier</a> om de confirmatiemail opnieuw te verzenden.';
$Definition['You need to sign in before you can do this.'] = 'U moet inloggen voordat u deze actie kan uitvoeren.';
$Definition['your'] = 'jouw';
$Definition['Your application for this group was denied.'] = 'Uw aanmelding tot deze groep is afgewezen.';
$Definition['Your changes have been saved.'] = 'Je wijzigingen zijn opgeslagen.';
$Definition['Your changes have been saved successfully.'] = 'Je veranderingen zijn succesvol bewaard.';
$Definition['Your changes were saved.'] = 'Uw veranderingen zijn bewaard.';
$Definition['Your email has been successfully confirmed.'] = 'Je e-mailadres is succesvol bevestigd.';
$Definition['Your invitation has been sent.'] = 'Uw uitnodiging is verstuurd.';
$Definition['Your old password was incorrect.'] = 'Uw oude wachtwoord was onjuist.';
$Definition['Your password has been changed.'] = 'Uw wachtwoord is veranderd.';
$Definition['Your picture has been removed.'] = 'Uw afbeelding is verwijderd.';
$Definition['Your post will appear once it\'s been approved.'] = 'Uw post zal worden getoond zodra deze is goedgekeurd.';
$Definition['Your preferences have been saved.'] = 'Uw voorkeuren zijn bewaard.';
$Definition['Your private conversations with other members.'] = 'Uw privé gesprekken met andere leden.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Jouw geregistreerde gebruikersnaam: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'Uw verzoek is ingestuurd. Check uw email voor verdere instructies';
$Definition['Your settings have been saved.'] = 'Je instellingen zijn opgeslagen.';
$Definition['Your settings have been saved successfully.'] = 'Je instellingen zijn succesvol bewaard';
$Definition['Your status for this event is now: <b>%s</b>'] = 'Uw status voor dit evenement is nu: <b>%s</b>';
$Definition['Your warning was added.'] = 'Uw waarschuwing is toegevoegd.';

$Definition[' You should '] = 'Je zou';

$Definition['You were added to a conversation.'] = '{InsertUserID,user} voegde {NotifyUserID,you} toe aan een <a href="{Url,htmlencode}">gesprek</a>.';
$Definition['You wrote:'] = 'Jij schreef:';
