<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Babala: Ang pagpapagana sa feature na ito ay maaaring magdulot ng mga error sa Javascript sa iyong site.**';

$Definition['About.DisableStatistics'] = 'If you must disable this data reporting for some business reason, you can do so by adding the following line to your installation\'s configuration file: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'It is vitally important to the life of this free, open-source software that we accurately measure the reach and effectiveness of Vanilla. We ask that you please do not disable the reporting of this data.';
$Definition['AboutCommentEmbedding'] = 'Vanilla can be used as a drop-in replacement for your blog\'s native commenting system. As a matter of fact, it can be used to add comments to any page on the web.';
$Definition['AboutEmbedding'] = 'Embedding allows all or part of your community to be embedded into other applications & web pages.';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'I-access ang iyong forum ng komunidad sa pamamagitan ng pag-click sa link na "Visit Site" sa itaas ng page na ito, o sa pamamagitan ng <a href={/,url}>pag-click dito</a>. Ang forum ng komunidad ay ang makikita ng lahat ng iyong mga user at kostumer kapag bumisita sila <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Magdagdag ng mga limitasyon sa sukat ng larawan na maaaring i-upload sa mga talakayan at mga komento.';
$Definition['AddonProblems'] = '<h2>Problems?</h2><p>If something goes wrong with an addon and you can\'t use your site, you can disable them manually by editing:</p>%s';
$Definition['AddressBarColorDescription'] = 'Ang ilang mga browser ay sumusuporta sa isang kulay para sa address bar. Mobile lang.';
$Definition['Alert users if they click external link.'] = 'Alerto mga gumagamit kung nag-click sila ng isang link sa isang post na aakayin ang mga ito mula sa forum. Hindi bibigyan ng babala ang mga gumagamit kapag sumusunod sa mga link na tumutugma sa isang Pinagkakatiwalaang Domain';
$Definition['Alignment'] = 'Pag-align';
$Definition['Alignment (Mobile)'] = 'Pag-align (Mobile)';
$Definition['Allow links to be transformed'] = 'Payagan ang mga link na mabago sa naka-embed na representasyon sa mga talakayan at komento. Halimbawa, ang isang link sa YouTube ay magbabago sa isang naka-embed na video.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Payagan ang mga gumagamit na may pahintulot %s na baguhin ang kanilang sariling mga avatar mula sa kanilang mga pahina ng profile sa Vanilla.';
$Definition['Anonymize IP Addresses'] = 'I-anonymize ang mga IP Address';
$Definition['ApplicationHelp'] = 'Applications allow you to add large groups of functionality to your site.<br />Once an application has been added to your %s folder, you can enable or disable it here.';
$Definition['Apply Layout'] = 'Ilapat ang Layout';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Sigurado ka bang gusto mong tanggalin ang temang ito? Ito ay permanenteng tatanggalin.';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Ang isang papel na may default na uri ng "hindi nakumpirma" ay kinakailangan upang gamitin ang kumpirmasyon ng email.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Awtomatikong i-save ang mga draft ng hindi na-publish na mga talakayan, tanong, ideya at komento.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Ang mga avatar ay mai-scale kung lalampas nila ang taas na ito.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Ang mga avatar ay mai-scale kung lalampas nila ang lapad na ito.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Ang mga Avatar ay makatipid ng kanilang mga thumbnail sa laki na ito.';

$Definition['Background Image'] = 'Imahe ng background';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Maging malikhain! Subukang pangalanan ang iyong mga ranggo pagkatapos ng mga bagay na pinag-uusapan ng komunidad.';
$Definition['Bordered'] = 'Pinagsama';
$Definition['Bordered (Unified)'] = 'Pinagsama (Pinagkaisa)';
$Definition['Borderless'] = 'Walang hangganan';
$Definition['Border Radius'] = 'Radius ng Border';
$Definition['Brand Color'] = 'Kulay ng Tatak';
$Definition['Buttons'] = 'Mga pindutan';
$Definition['Buttons & Inputs'] = 'Mga Pindutan at Mga Input';
$Definition['Button Type'] = 'Uri ng Button';

$Definition['Center Aligned'] = 'Nakahanay sa Center';
$Definition['Changes to the set day will take affect the following week.'] = 'Ang mga pagbabago sa itinakdang araw ay makakaapekto sa susunod na linggo.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Ang mga pagbabago ay ilalapat lamang sa mga bagong nai-upload na avatar.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Baguhin ang mga laki na nai-save ang mga imahe ng avatar.';
$Definition['Change the way your community works with plugins.'] = 'Change the way your community works with plugins. We\'ve bundled popular plugins with the software, and there are more available online.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Pinapayagan ng mga checkbox ang mga admins na magsagawa ng mga aksyon sa batch sa maraming mga talakayan o komento nang sabay-sabay.';
$Definition['Check out our %s'] = 'Tingnan ang aming %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Tingnan ang aming <0>dokumentasyon</0> , o magtanong sa aming <1>komunidad ng mga eksperto</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla is the simplest, most powerful community platform in the world. It\'s super-duper easy to use. Start with this introductory video and continue with the steps below. Enjoy!';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Pumili ng isang tema para sa subkomunidad na ito. <0>Magbasa pa </0>';
$Definition['Choose Image'] = 'Piliin ang Imahe';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'You can select a custom hash algorithm to sign your requests. The hash algorithm must also be used in your client library. Choose md5 if you\'re not sure what to choose.';
$Definition['Choose the order items are sorted.'] = 'Piliin ang pagkakasunud-sunod ng mga item sa pagkakasunud-sunod.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Piliin ang pahinang dapat makita ng mga tao kapag bumisita sila sa <0 />';
$Definition['Choose the preferred layout for lists of categories.'] = 'Piliin ang ginustong layout para sa mga listahan ng mga kategorya.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Piliin ang ginustong layout para sa mga listahan ng mga kategorya. Maaari mong i-edit ang Tiled Layout.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Piliin ang ginustong layout para sa mga listahan ng mga talakayan.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Piliin ang ginustong layout para sa mga listahan ng mga talakayan. Maaari mong i-edit ang Layout ng Foundation.';
$Definition['Color Overlay'] = 'Kulay ng Overlay';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Pasadyang Mga Tema ang mga tema na iyong nilikha. Maaari mong i-edit, palitan ang pangalan o gumawa ng isang kopya ng mga ito.';

$Definition['Dark'] = 'Madilim';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Define who can upload and manage files on the <a href="%s">Roles & Permissions</a> page.';
$Definition['Deleting forever cannot be undone.'] = 'Deleting is a good way to keep your forum clean.';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Huwag paganahin ang lab na "Bagong Embed System" sa <0>Vanilla Labs Page</0>';
$Definition['Don\'t use too many reactions.'] = 'Huwag gumamit ng maraming reaksyon. Hindi mo nais na bigyan ang labis na impormasyon sa iyong mga gumagamit.';

$Definition['EditContentTimeout.Notes'] = 'If a user is in a role that has permission to edit content, those permissions will override this.';
$Definition['Edits to this theme apply to:'] = 'Ang mga pag-edit sa temang ito ay nalalapat sa:';
$Definition['Email digests will be sent on the selected day every week.'] = 'Ang mga email digest ay ipapadala sa napiling araw bawat linggo.';
$Definition['Email sent from the application will be addressed from this email address'] = 'Ang email na ipinadala mula sa aplikasyon ay tutugunan mula sa email address na ito';
$Definition['Email sent from the application will be addressed from this name'] = 'Ang email na ipinadala mula sa aplikasyon ay tutugunan mula sa pangalang ito';
$Definition['Email Settings'] = 'Mga Setting ng Email';
$Definition['Embed Settings'] = 'I-embed ang Mga Setting';
$Definition['Enable and test out the latest Vanilla features.'] = 'Paganahin at subukan ang pinakabagong mga tampok na Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Pinapagana ang advanced na pag-edit ng mga post sa maraming mga format, kabilang ang WYSIWYG, simpleng HTML, Markdown, at BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Paganahin ang Layout Editor na maglapat ng custom na layout para sa iyong mga pahina ng komunidad. Gamitin ang aming bagong editor upang itampok ang nilalaman gamit ang aming katalogo ng mga available na widget.';
$Definition['Enter a descriptive name.'] = 'Enter a descriptive name for the pocket. This name will not show up anywhere except when managing your pockets here so it is only used to help you remember the pocket.';
$Definition['Enter a short name for the site.'] = 'Enter a short name for the site. This is displayed on the signin buttons.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Every edit or deletion is recorded here. Use ‘Restore’ to undo any change.';
$Definition['Everyone who signs up gets a profile page.'] = 'Ang lahat ng nag-sign up para sa iyong komunidad ay makakakuha ng public profile page kung saan pwede nilang i-upload ang larawan nila, pangasiwaan ang kanilang mga setting sa profile, at i-track ang mga magagandang bagay na nangyayari sa komunidad. Dapat mong <a href="{/profile,url}">i-customize ang iyong profile ngayon</a>';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect allows users to sign in using their Facebook account. <b>You must register your application with Facebook for this plugin to work.</b>';
$Definition['Font Name'] = 'Pangalan ng font';
$Definition['Font URL'] = 'URL ng font';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Halimbawa, maaari mong pagbawalan ang lahat ng user na may mga email address mula sa "halimbawa.com" sa pamamagitan ng pagdaragdag ng pagbabawal na tipong-email na may value na "*@example.com".';
$Definition['Foundation Layout'] = 'Layout ng Foundation';
$Definition['Full Anonymization'] = 'Buong Anonymization';
$Definition['FullAnonymization.Description'] = 'Pinapalitan ng <strong>Full Anonymization</strong> ang bawat IP address ng 0.0.0.0 na epektibong tinatanggihan ang application ng anumang access upang gumana sa mga IP address. Ang mga panuntunan sa pagbabawal ng IP ay hindi gagana sa kasong ito.';
$Definition['Full Bleed'] = 'Buong Pagdurugo';

$Definition['Garden.Import.Complete.Description'] = 'You have successfully completed an import.
   Click <b>Finished</b> when you are ready.';
$Definition['Garden.Import.Continue.Description'] = 'Lumilitaw na parang nasa gitna ka ng isang import. Mangyaring pumili ng isa sa mga sumusunod na pagpipilian.';
$Definition['Garden.Import.InputInstructions'] = 'Enter the email and password of the admin user from the data being imported.';
$Definition['Garden.Privacy.IPs.Description'] = 'Karaniwang kinokolekta ang mga IP address ng user para sa mga automated na panuntunan sa pagbabawal, pag-moderate at pag-iwas sa spam. Ang pagpapagana ng IP Anonymization ay gagawing anonymize ang lahat ng IP address na sinusubaybayan sa site para sa anumang layunin, at babawasan ang pagiging epektibo ng mga tool na ito. Hindi retroactive ang mga pagbabago sa setting na ito.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Pahintulot ng Garden.Profiles.Edit na baguhin ang kanilang sariling mga avatar mula sa kanilang mga pahina ng profile sa Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'You have specifically disabled Vanilla Statistics in your configuration file.';
$Definition['Garden.StatisticsLocal.Explain'] = 'This forum appears to be running in a test environment, or is otherwise reporting a private IP. By default, forums running on private IPs are not tracked.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'If you\'re sure your forum is accessible from the internet you can force it to report statistics here:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Your config.php file appears to be read-only. This means that Vanilla will be unable to automatically register your forum\'s InstallationID and InstallationSecret.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'To solve this problem, assign file mode 777 to your conf/config.php file.';
$Definition['Global Styles'] = 'Mga istilo ng Pandaigdig';

$Definition['Heads Up!'] = 'Paunawa!';
$Definition['Here are all of the reactions you can use on your site.'] = 'Narito ang lahat ng mga reaksyon na maaari mong gamitin sa iyong site.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Narito ang mga ranggo na maaaring makamit ng mga gumagamit sa iyong site. Maaari mong ipasadya ang mga ranggo na ito at kahit na magdagdag ng mga bago. Narito ang ilang mga tip.';

$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Kung hindi binisita ng isang user ang site sa loob ng panahong ito, awtomatiko silang masa-sign out.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Kung pinagana, ang buong nilalaman ng mga post ay ipapadala sa mga abiso sa email sa mga gumagamit.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Kung bago ka sa HTML at / o CSS, narito ang ilang mga tutorial upang makapagsimula ka:';
$Definition['If you have an old theme'] = 'Kung mayroon kang isang lumang tema at kailangan upang magtakda ng isang hiwalay na desktop at mobile na tema maaari mong gawin ito sa lumang UI ng pag-i tem.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Kung nais mong i-embed ang iyong forum o gumamit ng mga komento ni Vanilla sa iyong blog pagkatapos ay kailangan mong paganahin ang pag-embed. Kung hindi ka gumagamit ng pag-embed ay inirerekumenda namin na iwanan ang setting na ito.';
$Definition['Image (Mobile)'] = 'Larawan (Mobile)';
$Definition['In additon to the widgets there are also'] = 'Bilang karagdagan sa mga widget ay mayroon ding <0> Global Estilo </0> . Upang i-edit ang mga istilo ng pandaigdigang pag-click sa kahit saan pa sa pahina, tulad ng tekstong ito.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Isama ang Mga Pahina ng Foundation at Mga Bahagi Sa Iyong Tema';
$Definition['Internationalization & Localization'] = 'Internasyonalisasyon at Lokalisasyon';
$Definition['Invalid URL'] = 'Hindi wastong URL';
$Definition['Invitation email failed to send: %'] = 'Bagaman matagumpay na nilikha ang imbitasyon, nabigo ang email na ipadala. Iniulat ng server ang sumusunod na error: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'When you use registration by invitation users will have a link called <a href="%s" class="Popup">My Invitations</a> on their profile pages.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Mahusay na panatilihin ang maximum na bilang ng mga character na pinapayagan sa isang post pababa sa isang makatwirang sukat.';

$Definition['Learn about custom routing.'] = 'Matuto tungkol sa custom routing.';
$Definition['Left Aligned'] = 'Nakahanay sa Kaliwa';
$Definition['Light'] = 'Liwanag';
$Definition['Links'] = 'Mga link';
$Definition['Locales allow you to support other languages on your site.'] = 'Ang mga lokal ay nagpapahintulot sa iyo na suportahan ang ibang mga wika sa iyong site. Paganahin at huwag paganahin ang mga lokal na gusto mong gawing available dito.';
$Definition['Lockout Time (seconds)'] = 'Oras ng Lockout (segundo)';
$Definition['LogoDescription'] = 'Ang logo ng banner ay lilitaw sa tuktok ng iyong site.';
$Definition['LogoDisclaimer'] = 'Ang mga tema na ginawa kasama ang editor ng tema at ilang mga pasadyang tema ay hindi gumagamit ng setting na ito.';
$Definition['Looking for the Old Embed System?'] = 'Naghahanap para sa Old Embed System?';

$Definition['Make sure you click View Page'] = 'Make sure you click <a href="%s">View Page</a> to see what your categories page looks like after saving.';
$Definition['Managing Users'] = 'Pamamahala ng Mga Gumagamit';
$Definition['Messages can appear anywhere in your application.'] = 'Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.';
$Definition['MobileLogoDescription'] = 'Ang mobile banner logo ay lilitaw sa tuktok ng iyong site.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Pinapayagan ka ng mga mobile na tema na baguhin ang hitsura at pakiramdam ng iyong site sa mas maliit na aparato.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Ang bagong Layout Editor ay magmamana ng tema na itinakda sa iyong Style Guide (formal na theme editor). <1>Alamin ang higit pa</1>';
$Definition['Need more help?'] = 'Kailangan mo pa ba ng tulong?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Ang mga nested na kategorya na mas malalim kaysa sa lalim na ito ay ilalagay sa isang listahan ng tinanggal na comma.';
$Definition['New Embed System'] = 'Bagong Embed System';
$Definition['New Quick Links'] = 'Bagong Mga Mabilis na Link';
$Definition['New Search Page'] = 'Bagong Pahina ng Paghahanap';
$Definition['No Anonymization'] = 'Walang Anonymization';
$Definition['Not getting what you expect when you preview your theme?'] = 'Hindi nakakakuha ng inaasahan mo kapag nai-preview mo ang iyong tema?';
$Definition['No unconfirmed role available for email confirmation.'] = 'Kailangan ng site ng isang tungkulin na may default na uri na "unconfirmed" para magamit ang kumpirmasyon ng email. Mangyaring maglagay ng isa para mapagana ang setting na ito.';

$Definition['Old Theming UI'] = 'Lumang Theming UI';
$Definition['Once enabled, only members will see inside your community.'] = 'Kapag pinagana, ang mga miyembro lamang ang makakakita sa loob ng iyong komunidad.';
$Definition['OrgDescription'] = 'Ang pangalan ng organisasyon mo ay ginagamit para sa SEO microdata at JSON+LD';
$Definition['Outline'] = 'Balangkas';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Ang mga overridden na view o themehooks ay maaaring magkaroon ng hindi sinasadyang mga epekto at hindi nai-preview.';

$Definition['Partial Anonymization'] = 'Bahagyang Anonymization';
$Definition['PartialAnonymization.Description'] = '<strong>Ang Bahagyang Anonymization</strong> ay hindi nagpapakilala lamang sa huling octet ng IP address. Halimbawa, ang 254.230.05.153 ay magiging 254.230.05.0. Nagbibigay ito ng ilang anonymization habang pinapayagan pa ring gumana ang mga panuntunan sa IP ban.';
$Definition['Password.MinLength'] = 'Pinahihintulutan ang minimum na haba ng character para sa mga user na password sa paggawa at pag-reset ng password sa mga pahina.';
$Definition['PluginHelp'] = 'Plugins allow you to add functionality to your site.<br />Once a plugin has been added to your %s folder, you can enable or disable it here.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'The pocket is displayed between each discussion on the main discussion list. Since discussions are usually in <li>..</li> tags, you\'ll need to wrap your pocket in those tags too.';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Prevent spam on your forum by limiting the number of discussions & comments that users can post within a given period of time.';
$Definition['Primary Button'] = 'Pangunahing pindutan';
$Definition['Primary Buttons'] = 'Pangunahing Mga Pindutan';

$Definition['Quick Links is a default component on community pages.'] = 'Ang Quick Link ay isang default na sangkap sa mga pahina ng komunidad. Paganahin ang aming bagong bahagi ng Quick Link upang magdagdag, mag-edit o magtago ng mga link mula sa menu na ito gamit ang aming editor ng tema.';

$Definition['Recommend special ranks for admins and mods.'] = 'Magandang ideya na magkaroon ng mga espesyal na ranggo para sa mga moderator at administrador upang madaling makita ng iyong komunidad kung sino ang namamahala.';
$Definition['Recommend starting with five ranks.'] = 'Hindi mo nais na magkaroon ng maraming mga ranggo. Inirerekumenda namin na magsimula sa limang. Maaari kang magdagdag ng higit pa kung malaki ang iyong komunidad.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Alisin ang mga link ng talakayan at kategorya mula sa mga menu. Itakda ang mga pahinang nauugnay sa talakayan at kategorya upang ibalik ang hindi nahanap na pahina 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Nangangailangan ng pahintulot ng reaksyon ng "Bandila".';
$Definition['Requires “Negative” reaction permission.'] = 'Nangangailangan ng pahintulot na reaksyon ng "Negatibo".';
$Definition['Requires “Positive” reaction permission.'] = 'Nangangailangan ng pahintulot na reaksyon ng "Positibo".';
$Definition['Restoring your selection removes the items from this list.'] = 'When you restore, the items are removed from this list and put back into the site.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Gamitin ang sumusunod na opsyon para mapagana ang mga sipi para sa Rich Editor. Maikakapit lang ito kung "Rich" ang default na formatter.';
$Definition['Routes are used to redirect users.'] = 'Ang mga route ay ginagamit para i-redirect ang mga user depende sa hiniling na URL.';

$Definition['Secondary Button'] = 'Pangalawang Seksyon';
$Definition['Secondary Buttons'] = 'Pangalawang Mga Pindutan';
$Definition['Security.Hsts.HTTPSWarning'] = 'Babala: Paganahin lang ang tampok na ito kung sigurado ka na ang lahat ng iyong mga subdomain ay na-configure para sa HTTPS na may mga balidong sertipiko.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Kapag pinagana, ang tuntuning ito ay naaangkop din sa lahat ng mga subdomain ng iyong site.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Inirerekomenda namin na magsimula sa pinakamatandang edad na 1 linggo at pagkatapos ay pahahabain ito sa 1 buwan pagkatapos ay 1 taon sa sandaling makita mo na ang iyong site ay gumagana tulad ng inaasahan.';
$Definition['Security.Hsts.SubmitWarning'] = 'Babala: Mahusay na suportahan ang pag-preload ng HSTS bilang isang pinakamainam na kasanayan. Gayunpaman, dapat mong isumite ang iyong site sa hstspreload.org para matiyak na matagumpay itong na-pre-load (i.e. para makuha ang buong proteksyon para sa inilaang configuration).';
$Definition['See the documentation'] = 'Tingnan ang Dokumentasyon';
$Definition['Select the default type for this role, if any.'] = 'Piliin ang default na uri para sa papel na ito, kung mayroon man.';
$Definition['Session Timeout'] = 'Timeout ng Session';
$Definition['Shadowed'] = 'Nakayayakap';
$Definition['ShareImageDescription'] = 'Kapag may nagbabahagi ng isang link mula sa iyong site sinubukan namin at kumuha ng isang imahe mula sa pahina. Kung walang isang imahe sa pahina pagkatapos ay gagamitin namin ang imaheng ito. Ang imahe ay dapat na hindi bababa sa 50 × 50, ngunit inirerekumenda namin ang 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Turn this option on to show all possible pocket locations. Turning on this option will only show the locations to users that can manage pockets.';
$Definition['SignIn.LockoutTime'] = 'Ang tagal ng oras na naharang ang isang user mula sa pag-log in pagkatapos lumampas sa bilang ng mga pagtatangka sa pag-log in.';
$Definition['Some browsers support a color for the address bar.'] = 'Sinusuportahan ng ilang browser ang isang kulay para sa address bar.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Ang ilang mas lumang mga tema ay hindi sumusuporta sa ganap na kakayahan sa pag-edit. Upang makita kung ano ang sinusuportahan ng isang tema, maaari kang mag-hover sa pangalan nito upang makita kung saan magkakabisa ang mga pag-edit.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Ang ilang mga tema ay maaaring kailangang ma-update upang gumana kasama ang kategorya. Maaari mong paganahin ang tampok habang ina-update mo ang iyong tema.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Minsan gusto mong i-embed ang iyong Vanilla site sa loob ng isa pang site. Nag-aalok ang embed system ng Vanilla ng madaling paraan para doon. May mga tradeoff sa pagganap kapag gumagamit ng isang naka-embed na site, kaya tingnan ang dokumentasyon para sa mga alternatibo at mainam na mga kaso ng paggamit.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Espesyal na paghihigpit: Mga gumagamit lamang na may pahintulot na Garden.Curation.Manage ay maaaring gumamit ng reaksyon na ito.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Tukuyin ang bahagya o kumpletong pagtugma kapag gumagawa ng pagbabawal.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Spend a little time thinking about how you describe your site here. Giving your site a meaningful title and concise description could help your position in search engines.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Ayusin ang iyong mga email sa pamamagitan ng paglalagay ng logo at pagko-customize sa mga kulay.';
$Definition['Start the first discussion.'] = 'Umpisihan ang aksyon sa iyong komunidad sa pamamagitan ng <a href="{/post/discussion,url}">pagsisimula ng unang talakayan</a> ngayon.';
$Definition['Subcommunities'] = 'Mga Subkomunidad';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Pinapayagan ng pag-tag ang mga gumagamit na magdagdag ng isang tag sa mga talakayan na sinimulan nila upang mas madaling matuklasan ang mga ito.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Ang mga template ay ang karaniwang mga tema. Upang ipasadya ang mga ito, kailangan mong lumikha ng isang kopya.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB Ang <0 /> lab ay kailangang mai-configure upang tumugma sa iyong pasadyang tema. Magagawa ito gamit ang aming bagong editor ng tema. <1> Alamin ang higit pa.</1>';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'The banner title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages. Also, keep in mind some themes may also hide this title.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong> Ang form ng pangunahing pagpapatala ay nangangailangan ng </strong> pagkopya ng mga bagong user sa text mula sa larawang CAPTHA para panatilihin sa labas ng site ang mga spammer. Kailangan mo ng account sa <a href="http://recaptcha.net/">recaptcha.net</a> . LIBRE at madali lang ang pag-sign up. Kapag nakapag-sign up ka na, bumalik dito at ilagay ang sumusunod na mga setting:';
$Definition['The location of the authentication endpoint.'] = 'Ang lokasyon ng endpoint ng pagpapatotoo.';
$Definition['ThemeHelp'] = 'Themes allow you to change the look & feel of your site.<br />Once a theme has been added to your %s folder, you can enable it here.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Limitado ang preview ng tema sa pagpapakita ng template at css ng tema.';
$Definition['Theming Guide'] = 'Gabay sa pag-iisip';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Lumilitaw ang logo ng mobile sa tuktok ng iyong site. Ang mga temang ginawa gamit ang theme editor at ilang custom na tema ay hindi gumagamit ng setting na ito.';
$Definition['The New Embed System'] = 'Ang Bagong Embed System';
$Definition['The new embed system has improved performance.'] = 'Ang bagong embed system ay nagpabuti ng pagganap, pinahusay na pag-uugali sa pag-scroll, at mas pare-parehong pag-uugali kaysa sa dati. Kasalukuyang hindi sinusuportahan ang mga pag-embed ng komento at wordpress sa Bagong Embed System.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Mayroong dalawang uri ng mga pindutan sa application: pangunahin at pangalawa.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Ang paglalarawan ng site ay karaniwang lumalabas sa mga search engine. Dapat mong subukang magkaroon ng paglalarawan na 100-150 character ang haba.';
$Definition['The text of the pocket.'] = 'Enter the text of the pocket. This will be output exactly as you type it so make sure that you enter valid HTML.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Lalabas ang touch icon kapag nag-bookmark ka ng website sa homescreen ng isang mobile device. Ang mga ito ay karaniwang 152 pixels.';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla Statistics turns your forum\'s dashboard into an analytics reporting tool, allowing you to review activity on your forum over specific time periods. You can <a href="http://vanillaforums.org/docs/vanillastatistics">read more about Vanilla Statistics</a> in our documentation.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Gumagana sila tulad ng mga regular na tema. Kapag ang isang naidagdag sa folder ng mga tema, maaari mo itong paganahin dito.';
$Definition['This is a style guide of your theme.'] = 'Ito ay isang gabay na istilo ng iyong tema. Mayroon itong mga halimbawa ng mga visual na elemento na ginamit sa buong application. Maaari kang mag-click sa iba\'t ibang mga widget tulad ng <0> Title Bar </0> o <1> Banner </1> upang mai-edit ang kanilang mga katangian sa side panel.';
$Definition['This is the administrative dashboard for your new community.'] = 'Ito ang administrative dashboard para sa iyong bagong komunidad. Tingnan ang mga opsyon ng kumpigurasyon sa gilid. Mula doon ay pwede mong i-configure kung paano tumatakbo ang iyong komunidad. <b> Bilang default, tanging ang mga user lang na may tungkuling "Administrator" ang makakakita ng bahaging ito ng iyong komunidad. </b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Dito maaari mong paganahin at subukan ang mga bagong tampok, pahina at sangkap ng Vanilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Hindi maaaring i-disable ang lab na ito dahil may inilapat na custom na layout.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Ang lab na ito ay hindi maaaring hindi paganahin sapagkat kinakailangan ito ng kasalukuyang tema.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Lumilitaw ang logo na ito sa tuktok ng iyong site. Ang mga temang ginawa gamit ang theme editor at ilang custom na tema ay hindi gumagamit ng setting na ito.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Ito ay maaaring gamitin upang isama ang nilalaman tulad ng pangalan ng organisasyon at address sa lahat ng papalabas na email.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'This option shows/hides the locations where pockets can go, but only for users that have permission to add/edit pockets. Try showing the locations and then visit your site.';
$Definition['This page lists the endpoints of your API.'] = 'Inililista ng pahinang ito ang mga dulo ng iyong API. Mag-click sa mga endpoint para sa karagdagang impormasyon. Maaari kang gumawa ng mga live na tawag sa API mula sa pahinang ito o panlabas na gamit ang isang token ng pag-access.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Ang papel na ito ay personal na impormasyon. Ang mga gumagamit lamang na may pahintulot upang tingnan ang personal na impormasyon ay makikita ito.';
$Definition['This setting loads the page before executing Javascript.'] = 'Nilo-load ng setting na ito ang pahina bago maisagawa ang Javascript na maaaring mapahusay ang iyong SEO.<br><strong>**Babala: Ang pagpapagana ng feature na ito ay maaaring maging sanhi ng mga Javascript error sa iyong site.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Nilo-load ng setting na ito ang page bago isagawa ang Javascript na maaaring mapabuti ang iyong SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Ang theme na ito ay hindi pwedeng mabura dahil ito ang kasalukuyang naka-apply na theme.';
$Definition['Tiled Layout'] = 'Naka-tile na Layout';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Masyadong marami ang mga address! Magpapadala kami ng hanggang sa %s address nang sabay-sabay.';
$Definition['TouchIconDescription'] = 'Lumilitaw ang icon ng touch kapag nag-bookmark ka ng isang website sa homescreen ng isang aparatong Apple. Ito ay karaniwang 152 na mga piksel. Nagdagdag ang Apple ng mga bilog na sulok at awtomatikong epekto.';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect allows users to sign in using their Twitter account. <b>You must register your application with Twitter for this plugin to work.</b>';

$Definition['Usercards'] = 'Mga Usercard';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Nagbibigay-daan sa iyo ang mga usercard na makakuha ng mabilis na in-line na snapshot ng impormasyon ng isang user. Kapag tumitingin ng mga post at leaderboard, mag-click sa username upang makakita ng card na nagpapakita ng mga user ng pangunahing impormasyon ng profile nang hindi kinakailangang mag-navigate palayo sa page. Paganahin ang feature na ito upang magdagdag ng mga usercard sa iyong custom na tema.';
$Definition['User inputs are based on the global background and text colors.'] = 'Ang mga input ng gumagamit ay batay sa pandaigdigang background at kulay ng teksto.';
$Definition['User Profile'] = 'Profile ng Gumagamit';
$Definition['Users may sign into your site using their Twitter account.'] = 'Maaaring mag-sign in ang mga gumagamit sa iyong site gamit ang kanilang Twitter account.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Gamitin ang pindutan sa tuktok ng pahina upang lumikha ng isang panuntunan sa pagbabawal.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Use the WordPress plugin to set up Vanilla Comments on your blog, or use the universal code to set up Vanilla Comments on any other platform.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Ang bagong serbisyo sa paghahanap ng Vanilla ay narito na. Paganahin ang aming bagong UI ng pahina ng paghahanap upang makakuha ng access sa mga pinakabagong feature sa paghahanap gaya ng Paghahanap ng Miyembro, pag-uuri ng paghahanap at pag-highlight ng termino.';
$Definition['Verify and restore'] = 'Patunayan at ibalik';
$Definition['VerifyUser'] = 'Lagyan ng tsek ang kahon sa tabi ng gumagamit upang markahan ang mga ito bilang <b>Na-verify</b> upang ang kanilang mga post ay hindi mamarkahan bilang spam muli. Ibabalik din nito ang lahat ng kanilang nakabinbin na mga post.';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video tutorial on finding & managing users';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video tutorial on managing roles & permissions';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Babala: Ang pagpapagana ng tampok na ito ay maaaring maging sanhi ng mga error sa Javascript sa iyong site.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Babala</b> : Ang pagsasaayos ng iyong server ay hindi sumusuporta sa mabilis na pag-load ng data. Kung nag-import ka ng isang napakalaking file (hal. Higit sa 200,000 mga komento) maaari mong isaalang-alang ang pagbabago ng iyong pagsasaayos. Mag-click <a href="http://vanillaforums.com/porter">dito</a> para sa karagdagang impormasyon.';
$Definition['Warning: This is for advanced users.'] = '<b>Warning</b>: This is for advanced users and requires that you make additional changes to your web server. This is usually only available if you have dedicated or vps hosting. Do not attempt this if you do not know what you are doing.';
$Definition['Welcome to Labs!'] = 'Maligayang pagdating sa Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Maligayang pagdating sa theming UI ng Vanilla. Inililista ng page na ito ang lahat ng iyong available na tema, at pinapayagan kang kopyahin o i-edit ang mga ito.';
$Definition['Welcome To Your Theme'] = 'Maligayang pagdating sa Iyong Tema';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Inirerekumenda namin ang karamihan sa mga positibong reaksyon upang hikayatin ang pakikilahok.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Kapag pinagana, maaaring piliin ng mga user na makatanggap ng mga notification mula sa komunidad';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Kapag pinagana, maaari mong pamahalaan ang mga produkto, at mga subkomunidad ng grupo sa pamamagitan ng mga produktong iyon.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Kapag may nagbabahagi ng isang link mula sa iyong site sinubukan namin at kumuha ng isang imahe mula sa pahina. Kung walang isang imahe sa pahina pagkatapos ay gagamitin namin ang imaheng ito. Ang imahe ay dapat na hindi bababa sa 50 × 50, ngunit inirerekumenda namin ang 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Kapag pinili mo ang Full Bleed, transparent ang iyong background.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Kung ang mga panloob na field ng profile ay isasama sa webhook na ito o hindi.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Kung ang mga pribadong field ng profile ay isasama sa webhook na ito o hindi.';
$Definition['Which reactions you use really depends on your community.'] = 'Aling mga reaksyon na ginagamit mo ay talagang nakasalalay sa iyong komunidad, ngunit inirerekumenda namin na alalahanin ang ilang mga puntos.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Malapit ka nang mag-apply ng bagong pagpipilian sa layout. Maaari itong ipasadya at ma-preview gamit ang aming Theme Editor. <0> Matuto nang higit pa</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Maaari mong pagbawalan ang lahat ng gumagamit ng IP address na may prefix na "111.111.111" sa pamamagitan ng pagdaragdag ng pagbabawal na tipong-IP na may value na "111.111.111.*".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Maaari mong pagbawalan ang mga IP address, email address at username.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Maaari kang pumili mula sa isa sa iba\'t ibang mga istilo na alok ng temang ito.';
$Definition['You can configure some values differently for different screensizes.'] = 'Maaari mong i-configure ang ilang mga halaga nang naiiba para sa iba\'t ibang mga screen.';
$Definition['You can place files in your /uploads folder.'] = 'Kung masyadong malaki ang iyong file para direktang mai-upload sa page na ito, pwede mo itong ilagay sa iyong /uploads folder. Siguruhing nagsisimula ang filename sa salitang <b>export</b> at nagtatapos sa isa sa <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Maaari kang tukuyin ang isang minimum na haba ng post upang mawalan ng loob ang mga maiikling post.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Maaari kang mag-upload ng isang Custom Font sa iyong Theming System. Kopyahin lamang at i-paste ang URL sa larangan.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Kailangan mong magdagdag ng domain ng font url sa <0> Pinapayagan na Mga domain </0> sa pagsasaayos ng site. <1> Matuto nang higit pa tungkol sa mga pasadyang mga font. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Ang iyong mobile na tema ay hindi pinagana. Upang itakda ang iba\'t ibang mga mobile at desktop na tema, gamitin ang lumang theming UI.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Ang pangalan ng organisasyon mo ay ginagamit para sa SEO microdata at JSON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Ang favicon ng iyong site ay lilitaw sa title bar ng iyong browser. Ito ay paliliitin ayon sa naaangkop.';
