<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Peringatan: Mengaktifkan fitur ini dapat menyebabkan kesalahan Javascript di situs Anda.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Perhatian!</strong> Menghapus sebuah peran akan berakibat pengguna tidak mempunyai akses lagi ke aplikasi.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Perhatian!</strong> Memindahkan diskusi ke kategori pengganti dapat menyebabkan diskusi menghilang (atau muncul) bila kategori pengganti mempunyai perizinan yang berbeda dari kategori yang dihapus.';

$Definition['About.DisableStatistics'] = 'Bila anda perlu untuk menonaktifkan pelaporan data ini untuk beberapa alasan bisnis, anda dapat melakukannya dengan menambahkan baris kode berikut ini pada file konfigurasi instalasi anda: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Adalah sangat penting bagi kesinambungan status gratis dari perangkat lunak terbuka yang pencapaiannya dan efektivitas dari Vanilla kami ukur dengan akurat. Kami meminta anda agar tidak menonaktifkan pelaporan dari data ini.';
$Definition['AboutCommentEmbedding'] = 'Vanilla dapat pula digunakan sebagai pengganti dari sistem komentar bawaan dari blog anda. Bahkan sebenarnya, ia dapat digunakan untuk menambah komentar di setiap halaman di situs.';
$Definition['AboutEmbedding'] = 'Dengan penanaman, memungkinkan semua atau sebagian dari komunitas anda untuk ditanamkan pada aplikasi lain & halaman web.';
$Definition['About Vanilla Statistics'] = 'Mengenai Statistik Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Akses forum komunitas Anda dengan mengklik tautan "Kunjungi Situs" di puncak laman ini, atau dengan <a href={/,url}>mengklik di sini</a>. Semua pengguna & konsumen Anda akan melihat forum komunitas saat mereka mengunjungi <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Tambah batasan pada dimensi unggah gambar dalam diskusi dan komentar.';
$Definition['AddonProblems'] = '<h2>Masalah?</h2><p>Bila terjadi suatu masalah dengan addon dan anda tidak dapat menggunakan situs anda, anda dapat menonaktifkannya secara manual dengan mengedit:</p>%s';
$Definition['AddressBarColorDescription'] = 'Beberapa browser mendukung warna untuk bilah alamat. Hanya seluler.';
$Definition['Alert users if they click external link.'] = 'Beri tahu pengguna jika mereka mengeklik tautan di pos yang akan membuat mereka menjauh dari forum. Pengguna tidak akan diperingatkan ketika mengikuti tautan yang cocok dengan Domain Tepercaya';
$Definition['Alignment'] = 'Penjajaran';
$Definition['Alignment (Mobile)'] = 'Penyelarasan (Seluler)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Semua kategori diurutkan berdasarkan pilihan 5 diskusi terkini di setiap bawahnya';
$Definition['Allow links to be transformed'] = 'Izinkan tautan ditransformasikan menjadi representasi tertanam dalam diskusi dan komentar. Misalnya, tautan YouTube akan berubah menjadi video yang disematkan.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Izinkan pengguna dengan izin %s untuk mengubah avatar mereka sendiri dari halaman profil mereka di Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Anonimkan Alamat IP';
$Definition['ApplicationHelp'] = 'Aplikasi memungkinkan anda untuk menambah grup yang lebih besar dari fungsionalitas pada situs anda.<br />Segera setelah aplikasi ditambahkan pada folder %s anda, anda dapat mengaktifkannya atau menonaktifkannya di sini.';
$Definition['Apply Layout'] = 'Terapkan Tata Letak';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Anda yakin ingin menghapus tema ini? Itu akan dihapus secara permanen.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Anda yakin telah mengisi nama host basisdata dengan benar? Mungkin anda salah mengetiknya? Basisdata melaporkan: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Peran dengan tipe default "belum dikonfirmasi" diperlukan untuk menggunakan konfirmasi email.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Secara otomatis menyimpan draf diskusi, pertanyaan, ide, dan komentar yang belum dipublikasikan.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatar akan diperkecil jika melebihi ketinggian ini.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatar akan diperkecil jika melebihi lebar ini.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatar akan disimpan thumbnailnya pada ukuran ini.';

$Definition['Background'] = 'Latar Belakang';
$Definition['Background Image'] = 'Gambar latar belakang';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Jadilah kreatif! Coba sebutkan peringkat Anda setelah hal-hal yang dibicarakan komunitas.';
$Definition['Bordered'] = 'Berbatasan';
$Definition['Bordered (Unified)'] = 'Berbatasan (Terpadu)';
$Definition['Borderless'] = 'Tanpa batas';
$Definition['Border Radius'] = 'Radius Perbatasan';
$Definition['Brand Color'] = 'Warna Merek';
$Definition['Buttons'] = 'Tombol';
$Definition['Buttons & Inputs'] = 'Tombol & Input';
$Definition['Button Type'] = 'Jenis tombol';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Dengan mengklik tombol di bawah ini, anda akan menghapus akun pengguna %s selamanya.';

$Definition['Center Aligned'] = 'Rata Tengah';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Perubahan hanya akan berlaku untuk avatar yang baru diunggah.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Ubah ukuran penyimpanan gambar avatar.';
$Definition['Change the way your community works with plugins.'] = 'Ubah kinerja komunitas Anda dengan plugin. Kami telah membundel aneka plugin populer dengan peranti lunak, dan lain-lain yang tersedia di daring.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Kotak centang memungkinkan admin untuk melakukan tindakan batch pada sejumlah diskusi atau komentar pada saat yang sama.';
$Definition['Check out our %s'] = 'Lihat %s kami';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Lihat <0>dokumentasi kami</0> , atau tanyakan <1>komunitas pakar kami</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla adalah platform komunitas paling praktis dan paling bertenaga di dunia. Ia super-sangat mudah digunakan. Mulailah dengan video pengenalan ini dan lanjutkan dengan langkah-langkah di bawah ini. Selamat menikmati!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Pilih sebuah peran untuk pengguna tanpa induk akan ditempatkan:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Pilih tema untuk subkomunitas ini. <0> Baca lebih lanjut </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Pilihlah cara menangani semua  konten yang terkait dengan akun pengguna %s (komentar, pesan, dll).';
$Definition['Choose Image'] = 'Pilih Gambar';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Anda dapat memilih hash algoritma yang disesuaikan untuk menandai permintaan anda. Hash algoritma harus digunakan juga pada library client anda. Pilih md5 bila anda tidak yakin apa yang dipilih.';
$Definition['Choose the order items are sorted.'] = 'Pilih bagaimana sortir item pesanan.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Pilih halaman yang harus dilihat orang ketika mereka mengunjungi </>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Pilih tata letak yang disukai untuk daftar kategori.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Pilih tata letak yang disukai untuk daftar kategori. Anda dapat mengedit Tata Letak Ubin.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Pilih tata letak yang disukai untuk daftar diskusi.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Pilih tata letak yang disukai untuk daftar diskusi. Anda dapat mengedit Tata Letak Yayasan.';
$Definition['Color Overlay'] = 'Lapisan warna';
$Definition['Continue Import'] = 'Lanjutkan Impor';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Tidak dapat mengurai file yang diimpor. Masalahnya ada di sekitar baris %s.';
$Definition['Create a localization CSV'] = 'Buat sebuah CSV lokalisasi';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Tema Khusus adalah tema yang Anda buat. Anda dapat mengedit, mengganti nama, atau membuat salinannya.';

$Definition['Dark'] = 'Gelap';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Definisikan siapa saja yang dapat mengunggah dan mengelola file pada halaman <a href="%s">Peran & Perizinan</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Jelaskan Laman Beranda Anda, unggah logo anda, dan masih banyak lagi...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Menghapus sebuah peran dapat berakibat pengguna tidak punya akses ke aplikasi.';
$Definition['Deleting forever cannot be undone.'] = 'Menghapus adalah cara yang bagus untuk menjaga forum anda tetap bersih.';
$Definition['Disable Google Sign In'] = 'Nonaktifkan Google Sign In';
$Definition['Disable OpenID'] = 'Nonaktifkan OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Nonaktifkan lab "Sistem Sematan Baru" di <0>Halaman Lab Vanilla</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Kategori diskusi digunakan untuk membantu pengguna anda mengorganisir diskusi mereka melalui cara yang berarti untuk komunitas anda.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Jangan tanam dashboard forum anda (pop-kan dengan tampilan penuh)';
$Definition['Don\'t use too many reactions.'] = 'Jangan menggunakan terlalu banyak reaksi. Anda tidak ingin memberi informasi pengguna Anda berlebihan.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Seret dan tempatkan kategori di bawah ini untuk mengurutkannya dan menyarangkannya.';

$Definition['EditContentTimeout.Notes'] = 'Bila seorang pengguna dalam peran yang memiliki perizinan untuk mengedit konten, perizinan tersebut akan menimpa yang ini.';
$Definition['Edit Route'] = 'Sunting Rute';
$Definition['Edits to this theme apply to:'] = 'Pengeditan untuk tema ini berlaku untuk:';
$Definition['Embed Settings'] = 'Menyematkan Pengaturan';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Tanamkan forum komunitas anda ke situs anda untuk meningkatkan hubungan dekat...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Aktifkan dan uji fitur terbaru Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Mengaktifkan pengeditan posting lanjutan dalam beberapa format, termasuk WYSIWYG, HTML sederhana, Penurunan harga, dan BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Aktifkan Editor Tata Letak untuk menerapkan tata letak khusus untuk laman komunitas Anda. Gunakan editor baru kami untuk menampilkan konten menggunakan katalog widget yang tersedia.';
$Definition['Enter a descriptive name.'] = 'Masukkan nama deskriptif dari pocket.  Nama ini tidak akan tampil di manapun kecuali saat anda mengelola pocket anda di sini jadi ini hanya untuk membantu anda mengingat pocket tersebut.';
$Definition['Enter a short name for the site.'] = 'Masukkan nama singkat situs. Ini ditampilkan pada tombol masuk.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Masukkan alamat dari blog Wordpress anda dan kami akan menanganinya dari sana.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Masukkan setelan koneksi dari server sphinx anda di bawah ini.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Setiap pengeditan atau penghapusan direkam di sini. Gunakan ‘Pulihkan’ untuk membatalkan perubahan apapun.';
$Definition['Everyone who signs up gets a profile page.'] = 'Semua anggota yang mendaftar masuk ke komunitas Anda memiliki laman profil publik di mana mereka dapat mengunggah foto mereka, mengelola setelan profil, serta bersosialisasi dalam komunitas. Sebaiknya Anda <a href="{/profile,url}">mengatur profil Anda sekarang</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Setiap pengguna di situs anda setidaknya diterapkan satu peran. Peran digunakan untukmenentukan apa saja yang boleh dilakukan oleh pengguna.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect memungkinkan pengguna untuk masuk menggunakan akun Facebook mereka.';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Gagal terhubung ke basisdata dengan username dan password yang anda masukkan. Apakah anda salah tulis? Basisdata melaporkan: <code>%s</code>';
$Definition['Font'] = 'Fon';
$Definition['Font Name'] = 'Nama Font';
$Definition['Font URL'] = 'URL font';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Paksakan agar dashboard hanya bisa diakses dari url ini saja <em>(tidak direkomendasikan)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Misalnya, Anda dapat melarang semua pengguna dengan alamat email dari "contoh.com" dengan menambahkan larangan tipe email dengan nilai "*@contoh.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Untuk kepentingan SEO, crawler mesin pencari tidak disertakan pada paksaan melihat forum dari url terkendali.';
$Definition['Foundation Layout'] = 'Tata Letak Yayasan';
$Definition['Full Anonymization'] = 'Anonimisasi Penuh';
$Definition['FullAnonymization.Description'] = '<strong>Anonimisasi Penuh</strong> menggantikan setiap alamat IP tunggal dengan 0.0.0.0 secara efektif menolak akses aplikasi apa pun untuk bekerja dengan alamat IP. Aturan larangan IP tidak akan berfungsi sama sekali dalam kasus ini.';
$Definition['Full Bleed'] = 'Berdarah Penuh';

$Definition['Garden.Import.Complete.Description'] = 'Anda berhasi menyelesaikan impor. Klik <b>Selesai</b> jika Anda sudah siap.';
$Definition['Garden.Import.Continue.Description'] = 'Tampaknya Anda berada di tengah-tengah impor. Silakan pilih salah satu opsi berikut.';
$Definition['Garden.Import.InputInstructions'] = 'Masukkan email dan password admin dari data yang sedang diimpor.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit izin untuk mengubah avatar mereka sendiri dari halaman profil mereka di Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Anda telah menonaktifkan Statistik Vanilla pada file konfigurasi anda.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Forum ini tampaknya berjalan dalam lingkungan ujicoba, atau mungkin melaporkan IP privat, Secara baku, forum berjalan dengan IP privat yang tidak terlacak.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Bila anda yakin forum anda dapat diakses dari internet anda dapat menekankannya pada laporan statistik di sini:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'File config.php anda tampaknya read-only. Ini artinya Vanilla tidak bisa secara otomatis mendaftarkan InstallationID dan InstallationSecret forum anda.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Untuk menyelesaikan masalah ini, setel mode 777 pada file conf/config.php anda.';
$Definition['Global Styles'] = 'Gaya Global';

$Definition['Heads Up!'] = 'Perhatian!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Perhatian! Ini adalah peran khusus yang tidak memperkenankan sesi aktif. Atas alasan ini, pilihan izin telah dibatasi hanya untuk "melihat" perizinan.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Berikut ini semua reaksi yang dapat Anda gunakan di situs Anda.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Berikut adalah peringkat yang dapat dicapai pengguna di situs Anda. Anda dapat menyesuaikan peringkat ini dan bahkan menambahkan yang baru. Berikut ini beberapa tipsnya.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Bila sebuah logo diunggah, itu akan menggantikan judul banner pada halaman forum yang dilihat pengguna.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Jika pengguna tidak mengunjungi situs dalam jangka waktu ini, mereka akan keluar secara otomatis.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Jika diaktifkan, konten lengkap dari posting akan dikirim dalam pemberitahuan email kepada pengguna.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Jika Anda baru mengenal HTML dan / atau CSS, berikut ini beberapa tutorial untuk Anda mulai:';
$Definition['If you have an old theme'] = 'Jika Anda memiliki tema lama dan perlu mengatur tema desktop dan seluler yang terpisah, Anda dapat melakukannya dengan UI tema lama.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Bila anda ingin mengurangi tingkat peringatan maka hilangkan sebuah peringatan.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Jika Anda ingin menyematkan forum Anda atau menggunakan komentar Vanilla di blog Anda, maka Anda perlu mengaktifkan penyematan. Jika Anda tidak menggunakan penyematan maka kami sarankan untuk mematikan pengaturan ini.';
$Definition['Image (Mobile)'] = 'Gambar (Ponsel)';
$Definition['Import'] = 'Impor';
$Definition['Importing to Vanilla'] = 'Mengimpor ke Vanilla';
$Definition['In additon to the widgets there are also'] = 'Selain widget ada juga <0> Gaya Global </0> . Untuk mengedit gaya global klik di mana saja di halaman, seperti teks ini.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integrasikan Halaman Dasar & Komponen Kedalam Tema Anda';
$Definition['Internationalization & Localization'] = 'Internasionalisasi & Lokalisasi';
$Definition['Invalid URL'] = 'URL tidak valid';
$Definition['Invitation email failed to send: %'] = 'Meskipun undangan berhasil dibuat, email gagal dikirim. Server melaporkan kesalahan berikut: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Saat anda menggunakan undangan sebagai pendaftaran pengguna akan memiliki tautan berupa <a href="%s" class="Popup">Undangan Saya</a> pada halaman profil mereka';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Tampaknya basisdata yang anda spesifikasikan belum tersedia. Sudahkah anda membuatnya? Apakah anda salah tulis nama? Basisdata melaporkan: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Adalah ide yang bagus menjaga jumlah maksimal dari karakter yang diperkenankan pada komentar di bawah ukuran yang rasional.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Sebaiknya pertahankan jumlah karakter maksimum yang diperbolehkan dalam pos hingga ukuran yang wajar.';

$Definition['Kick-start your community and increase user engagement.'] = 'Genjot komunitas anda dan tingkatkan hubungan dengan pengguna.';

$Definition['Labs'] = 'laboratorium';
$Definition['Layout Editor'] = 'Editor Tata Letak';
$Definition['Learn about custom routing.'] = 'Pelajari lebih lanjut tentang kostumasi route';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Pelajari bagaimana mengubah sepenuhnya tampilan dan rasa forum anda: unggah logo anda, setel laman berandanya, memilih sebuah tema dan menyesuaikannya.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Pelajari bagaimana menggunakan fungsional dasar dari forum anda.';
$Definition['Left Aligned'] = 'Rata kiri';
$Definition['Light'] = 'Cahaya';
$Definition['Links'] = 'Tautan';
$Definition['Locales allow you to support other languages on your site.'] = 'Bahasa mengizinkan Anda mendukung bahasa lainnya pada situs Anda. Aktif dan nonaktifkan bahasa yang Anda inginkan agar tersedia di sini.';
$Definition['Lockout Time (seconds)'] = 'Waktu Penguncian (detik)';
$Definition['LogoDescription'] = 'Logo spanduk muncul di bagian atas situs Anda.';
$Definition['LogoDisclaimer'] = 'Tema dibuat dengan editor tema dan beberapa tema khusus tidak menggunakan pengaturan ini.';
$Definition['Looking for the Old Embed System?'] = 'Mencari Sistem Embed Lama?';

$Definition['Make sure you click View Page'] = 'Pastikan anda klik <a href="%s">Lihat Halaman</a> untuk melihat seperti apa halaman kategori anda setelah disimpan.';
$Definition['Manage Routes'] = 'Kelola Route';
$Definition['Managing Users'] = 'Mengelola Pengguna';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Menandai sesuatu sebagai BUKAN spam akan menempatkan mereka kembali ke forum anda.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Menandai sesuatu sebagai bukan spam akan menempatkan mereka kembali ke forum anda.';
$Definition['Messages can appear anywhere in your application.'] = 'Pesan dapat tampil di mana saja dalam aplikasi anda, dan dapat digunakan untuk menginformasikan kepada pengguna anda mengenai berita atau acara baru. Gunakan halaman ini untuk mengorganisir ulang pesan anda dengan menyeretnya ke atas atau bawah. ';
$Definition['MobileLogoDescription'] = 'Logo spanduk seluler muncul di bagian atas situs Anda.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Tema seluler memungkinkan Anda mengubah tampilan dan nuansa situs Anda di perangkat yang lebih kecil.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Layout Editor baru akan mewarisi set tema di Panduan Gaya Anda (secara resmi editor tema). <1>Cari tahu lebih lanjut</1>';
$Definition['Need More Help?'] = 'Perlu Bantuan Lanjut?';
$Definition['Need more help?'] = 'Butuh bantuan lebih banyak?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Kategori bersarang yang lebih dalam dari kedalaman ini akan ditempatkan dalam daftar yang dibatasi koma.';
$Definition['New Embed System'] = 'Sistem Sematan Baru';
$Definition['New Quick Links'] = 'Tautan Cepat Baru';
$Definition['New Search Page'] = 'Halaman Pencarian Baru';
$Definition['Not getting what you expect when you preview your theme?'] = 'Tidak mendapatkan apa yang Anda harapkan saat mempratinjau tema Anda?';
$Definition['Notify me when people comment on my addons.'] = 'Beritahu saya saat orang-orang berkomentar pada addon saya.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Situs ini membutuhkan peran dengan tipe default "unconfirmed" untuk menggunakan email konfirmasi. Harap tambahkan satu untuk mengaktifkan setelan ini.';

$Definition['Old Theming UI'] = 'UI Tema Lama';
$Definition['Once enabled, only members will see inside your community.'] = 'Setelah diaktifkan, hanya anggota yang akan melihat di dalam komunitas Anda.';
$Definition['OrgDescription'] = 'Nama organisasi Anda digunakan untuk mikrodata SEO dan JSON+LD';
$Definition['Outline'] = 'Garis besar';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Tampilan yang diganti atau mungkin dapat menimbulkan efek samping yang tidak diinginkan dan tidak dipratinjau.';

$Definition['Partial Anonymization'] = 'Anonimisasi Sebagian';
$Definition['PartialAnonymization.Description'] = '<strong>Anonimisasi Parsial</strong> menganonimkan hanya oktet terakhir dari alamat IP. Misalnya 254.230.05.153 akan menjadi 254.230.05.0. Ini memberikan beberapa anonimisasi sambil tetap mengizinkan aturan larangan IP berfungsi.';
$Definition['Password.MinLength'] = 'Panjang karakter minimum yang diizinkan untuk kata sandi pengguna pada halaman pembuatan dan pengaturan ulang kata sandi.';
$Definition['Please choose an authenticator to configure.'] = 'Pilih salah satu autentikator untuk mengkonfigurasi';
$Definition['PluginHelp'] = 'Plugin memungkinkan anda untuk menambah fungsionalitas situs anda.<br />Segera setelah sebuah plugin ditambahkan pada folder %s anda, anda dapat mengaktifkannya atau menonaktifkannya di sini.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Pocket ditampilkan di antara setiap diskusinya pada daftar diskusi utama. Semenjak diskusi yang biasanya dalam tag <li>..</li> maka anda pun perlu untuk membungkus pocket bersamaan dengan tag tersebut.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Pocket memungkinkan anda untuk menambahkan free-form HTML ke berbagai tempat di aplikasi.';
$Definition['Preset'] = 'Prasetel';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Cegah spam di forum anda dengan membatasi jumlah diskusi & komentar yang bisa dikirim pengguna dalam periode waktu tertentu.';
$Definition['Primary Button'] = 'Tombol Utama';
$Definition['Primary Buttons'] = 'Tombol Utama';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Panduan Cepat-Mulai untuk Membuat Tema Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Tautan Cepat adalah sebuah komponen standar pada halaman komunitas. Aktifkan komponen Tautan Cepat baru kami untuk menambah, menyunting atau menyembunyikan tautan dari menu ini menggunakan editor tema kami.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Plugin Siap-sedia Komentar Vanilla untuk WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Plugin Siap-sedia Forum Vanilla untuk WordPress';
$Definition['Realtime progress bars: %s'] = 'Baris progres realistik: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Merupakan ide bagus untuk memiliki peringkat khusus untuk moderator dan administrator sehingga komunitas Anda dapat dengan mudah melihat siapa yang bertanggung jawab.';
$Definition['Recommend starting with five ranks.'] = 'Anda tidak ingin memiliki peringkat terlalu banyak. Kami merekomendasikan dimulai dengan lima. Anda dapat menambahkan lebih banyak jika komunitas Anda benar-benar besar.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Hapus tautan diskusi dan kategori dari menu. Setel halaman terkait diskusi dan kategori untuk mengembalikan halaman tidak ditemukan 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Membutuhkan izin "Tandai" reaksi.';
$Definition['Requires “Negative” reaction permission.'] = 'Membutuhkan izin reaksi "Negatif".';
$Definition['Requires “Positive” reaction permission.'] = 'Membutuhkan izin reaksi "Positif".';
$Definition['Restoring your selection removes the items from this list.'] = 'Saat anda memulihkan, item-item akan dihilangkan dari daftar ini dan dikembalikan lagi ke situs.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Gunakan opsi berikut untuk mengaktifkan kutipan untuk Editor Kaya. Ini hanya akan berlaku jika formatter default adalah "Kaya".';
$Definition['Route Expression'] = 'Ekspresi Route';
$Definition['Routes are used to redirect users.'] = 'Route dapat digunakan untuk mengalihkan pengguna ke bermacam bagian dari situs anda tergantung dari url-nya.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Pencarian pengguna berdasarkan nama atau masukkan nama dari peran untuk melihat semua pengguna dengan peran tersebut.';
$Definition['Secondary Button'] = 'Tombol Sekunder';
$Definition['Secondary Buttons'] = 'Tombol Sekunder';
$Definition['Security.Hsts.HTTPSWarning'] = 'Peringatan: Aktifkan fitur ini hanya jika Anda yakin semua subdomain Anda dikonfigurasikan untuk HTTPS dengan sertifikat yang valid.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Saat diaktifkan, aturan ini juga berlaku untuk semua subdomain situs Anda.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Kami menyarankan mulai dengan usia maksimal 1 minggu dan kemudian meningkat menjadi 1 bulan kemudian 1 tahun setelah Anda melihat situs Anda berfungsi seperti yang diharapkan.';
$Definition['Security.Hsts.SubmitWarning'] = 'Peringatan: Sangat bagus untuk mendukung prapemuatan HSTS sebagai praktik terbaik. Namun, Anda harus mengajukan situs Anda ke hstspreload.org untuk memastikan bahwa situs tersebut berhasil menjalankan proses prapemuatan (yaitu untuk mendapatkan perlindungan penuh untuk konfigurasi yang dimaksud).';
$Definition['See the documentation'] = 'Lihat Dokumentasi';
$Definition['Select the default type for this role, if any.'] = 'Pilih tipe default untuk peran ini, jika ada.';
$Definition['Select the import source'] = 'Pilih sumber impor';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Kolom terserialisasi "%s" gagal untuk tidak diserialisasikan.';
$Definition['Session Timeout'] = 'Batas Waktu Sesi';
$Definition['Shadowed'] = 'Dibayangi';
$Definition['ShareImageDescription'] = 'Ketika seseorang membagikan tautan dari situs Anda, kami mencoba dan mengambil gambar dari halaman tersebut. Jika tidak ada gambar di halaman maka kami akan menggunakan gambar ini sebagai gantinya. Gambar harus minimal 50 × 50, tetapi kami menyarankan 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Nyalakan opsi ini untuk menampilkan semua peluang lokasi pocket. Menyalakan opsi ini akan hanya menampilkan saja kepada pengguna bahwa mereka bisa mengelola pocket.';
$Definition['SignIn.LockoutTime'] = 'Jumlah waktu pengguna diblokir dari login setelah melebihi jumlah upaya login.';
$Definition['Solid'] = 'Padat';
$Definition['Some browsers support a color for the address bar.'] = 'Beberapa browser mendukung warna untuk bilah alamat.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Beberapa tema lama tidak mendukung kemampuan pengeditan penuh. Untuk melihat apa yang didukung tema, Anda dapat mengarahkan kursor ke namanya untuk melihat di mana pengeditan akan diterapkan.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Beberapa tema mungkin perlu diperbarui untuk bekerja dengan kategori berikut. Anda dapat menonaktifkan fitur saat Anda memperbarui tema Anda.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Terkadang Anda ingin menyematkan situs Vanilla Anda di dalam situs lain. Sistem embed Vanilla menawarkan cara mudah untuk itu. Ada pengorbanan kinerja saat menggunakan situs tersemat, jadi periksa dokumentasi untuk alternatif dan kasus penggunaan yang ideal.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Pembatasan khusus: Hanya pengguna dengan izin Garden.Curation.Manage dapat menggunakan reaksi ini.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Tentukan kecocokan sebagian atau semuanya saat membuat larangan.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Luangkan waktu untuk berpikir bagaimana anda menggambarkan situs anda di sini. Berikan situs anda judul yang berarti dan deskripsi yang singkat akan membantu posisi anda di mesin pencari.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Rapikan email Anda dengan menambahkan logo dan menyesuaikan warna.';
$Definition['Start Import'] = 'Mulai Impor';
$Definition['Start the first discussion.'] = 'Meriahkan komunitas Anda dengan <a href="{/post/discussion,url}">memulai diskusi pertama</a> sekarang.';
$Definition['Subcommunities'] = 'Subkomunitas';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Pemberian tag memungkinkan pengguna untuk menambahkan tag pada diskusi yang mereka mulai untuk membuatnya lebih mudah ditemukan.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Template adalah tema standar. Untuk menyesuaikannya, Anda harus membuat salinan.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Autentikator %s tidak memiliki opsi konfigurasi yang disesuaikan.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'Catatan. <0/> lab harus dikonfigurasikan untuk sama dengan tema khusus Anda. Ini dapat dilakukan menggunakan editor tema kami yang baru. <1>Ketahui lebih lanjut.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Addon tidak dapat aktif karena ia membangkitkan galat yang fatal: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Addon sudah diunduh.';
$Definition['The banner logo appears at the top of your forum.'] = 'Banner logo akan tampil di posisi atas forum Anda.';
$Definition['The banner title appears on the top-left of every page.'] = 'Judul banner akan tampil di posisi kiri-atas setiap halaman.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Judul banner akan tampil pada banner situs anda dan pada baris judul peramban anda. Ia harus tidak lebih dari 20 karakter. Bila logo banner diunggah, ia akan menggantikan judul banner pada halaman forum anda. Juga, selalu ingat bahwa beberapa tema mungkin menyembunyikan judul banner ini.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Formulir pendaftaran dasar mewajibkan</strong> pengguna baru untuk menyalin teks dari gambar CAPTCHA guna menghindari spammer dari situs ini. Anda memerlukan akun di <a href="http://recaptcha.net/">recaptcha.net</a>. Pendaftaran GRATIS dan mudah. Setelah mendaftar, kembalilah ke sini dan masukkan setelan berikut:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'User dari basisdata yang anda spesifikasikan tidak memiliki izin akses ke basisdata. Sudahkan anda membuat basisdatanya? Basisdata telah melaporkan: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Perubahan struktur di bawah ini diperlukan untuk basisdata anda.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Judul laman beranda akan ditampilkan pada laman beranda Anda. Pilih sebuah judul yang Anda ingin tampilkan pada mesin pencari.';
$Definition['The import file does not contain any data.'] = 'File yang diimpor tidak memiliki data apapun.';
$Definition['The import file is not in the correct format.'] = 'File yang diimpor tidak dalam format yang benar.';
$Definition['The location of the authentication endpoint.'] = 'Lokasi titik akhir otentikasi.';
$Definition['ThemeHelp'] = 'Tema memungkinkan anda untuk mengubah tampilan & rasa dari situs.<br />Segera setelah sebuah tema ditambahkan pada folder %s anda, and adapat mengaktifkannya di sini.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Pratinjau tema terbatas untuk menampilkan templat dan css tema.';
$Definition['Theming Guide'] = 'Panduan Mereka';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Logo seluler muncul di bagian atas situs Anda. Tema yang dibuat dengan editor tema dan beberapa tema khusus tidak menggunakan pengaturan ini.';
$Definition['The New Embed System'] = 'Sistem Sematan Baru';
$Definition['The new embed system has improved performance.'] = 'Sistem penyematan baru telah meningkatkan kinerja, meningkatkan perilaku pengguliran, dan perilaku yang lebih konsisten daripada yang lama. Saat ini komentar dan penyematan wordpress tidak didukung di Sistem Penyematan Baru.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Password autentikator tidak memiliki opsi konfigurasi yang disesuaikan.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Tidak ada perubahan struktur basisdata yang diperlukan. Tapi dimungkinkan adanya perubahan pada data.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Ada dua jenis tombol dalam aplikasi: primer dan sekunder.';
$Definition['The route was saved successfully.'] = 'Route berhasil disimpan.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Deskripsi situs biasanya muncul di mesin pencari. Anda harus mencoba memiliki deskripsi yang panjangnya 100-150 karakter.';
$Definition['The text of the pocket.'] = 'Masukkan teks dari pocket. Ini akan menjadi keluaran persis seperti yang anda ketikkan maka pastikan anda memasukkan HTML yang benar.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Ikon sentuh muncul saat Anda menandai situs web di layar beranda perangkat seluler. Ini biasanya 152 piksel.';
$Definition['The user table was not in the import file.'] = 'Tabel pengguna tidak berada dalam file impor.';
$Definition['The Vanilla 2 Exporter'] = 'Vanilla 2 Exporter';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Statistik Vanilla menjadikan dashboard forum anda menjadi perangkat pelaporan teranalisis, memungkinkan anda untuk meninjau aktivitas forum anda dengan periode waktu tertentu. Anda dapat <a href="http://vanillaforums.org/docs/vanillastatistics">membaca lebih lanjut tentang Statistik Vanilla</a> pada dokumentasi kami.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Mereka bekerja seperti tema biasa. Setelah satu ditambahkan ke folder tema, Anda dapat mengaktifkannya di sini.';
$Definition['This is a style guide of your theme.'] = 'Ini adalah panduan gaya tema Anda. Ini memiliki contoh elemen visual yang digunakan di seluruh aplikasi. Anda dapat mengklik berbagai widget seperti Bilah Judul <0> </0> atau <1> Spanduk </1> untuk mengedit propertinya di panel samping.';
$Definition['This is the administrative dashboard for your new community.'] = 'Ini adalah dasbor administratif untuk komunitas baru Anda. Simaklah opsi konfigurasi di samping. Dari situ Anda dapat mengatur kinerja komunitas Anda. <b>Secara default, hanya pengguna dengan status "Administrator" dapat melihat bagian komunitas ini.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Disini Anda dapat mengaktifkan dan menguji fitur,halaman & komponen terbaru Vanilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Lab ini tidak dapat dinonaktifkan karena tata letak khusus diterapkan.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Lab ini tidak dapat dinonaktifkan karena diperlukan oleh tema saat ini.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Logo ini muncul di bagian atas situs Anda. Tema yang dibuat dengan editor tema dan beberapa tema khusus tidak menggunakan pengaturan ini.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Opsi ini menampilkan/menyembunyikan lokasi di mana pocket dapat bekerja, namun hanya untuk pengguna yang mendapat izin untuk menambah/mengeditnya. Cobalah untuk menampilkan lokasinya lalu kunjungi situs anda.';
$Definition['This page lists the endpoints of your API.'] = 'Halaman ini mencantumkan titik akhir API Anda. Klik titik akhir untuk informasi lebih lanjut. Anda dapat membuat panggilan langsung ke API dari halaman ini atau secara eksternal menggunakan token akses.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Peran ini adalah info pribadi. Hanya pengguna dengan izin untuk melihat info pribadi yang akan melihatnya.';
$Definition['This setting loads the page before executing Javascript.'] = 'Pengaturan ini memuat halaman sebelum mengeksekusi Javascript, ini dapat meningkatkan SEO Anda.<br><strong>**Peringatan: Mengaktifkan fitur ini dapat menyebabkan kesalahan Javascript di situs Anda.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Pengaturan ini memuat halaman sebelum menjalankan Javascript yang dapat meningkatkan SEO Anda.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Tema ini tidak dapat dihapus karena ini adalah tema yang sedang diterapkan.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Judul ini muncul di spanduk situs Anda dan di bilah judul browser Anda. Itu harus kurang dari 20 karakter. Jika logo diunggah, itu akan menggantikan judul ini di halaman forum yang menghadap pengguna. Juga, perlu diingat beberapa tema mungkin menyembunyikan judul ini.';
$Definition['Tiled Layout'] = 'Tata Letak Ubin';
$Definition['Title Bar'] = 'Bar judul';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Untuk menanamkan forum Vanilla anda pada situs anda, gunakan kode berikut.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Terlalu banyak alamat tujuan! Kami akan mengirim hingga %s alamat dalam satu waktu';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Untuk mencegah tindak penyalahgunaan, beberapa perangkat secara otomatis menyembunyikan konten dan daftarnya di sini hingga disetujui secara manual oleh moderator.';
$Definition['TouchIconDescription'] = 'Ikon sentuh muncul ketika Anda menandai situs web di layar beranda perangkat Apple. Ini biasanya 152 piksel. Apple menambahkan sudut membulat dan efek pencahayaan secara otomatis.';
$Definition['Transparent'] = 'Transparan';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect memungkinkan pengguna untuk masuk dengan akun Twitter. <b>Anda harus mendaftarkan aplikasi anda dengan Twitter agar plugin ini bisa bekerja.</b>';

$Definition['Usercards'] = 'Usercard';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Usercard memungkinkan Anda untuk mendapatkan snapshot in-line yang cepat dari informasi seorang pengguna. Saat melihat posting dan papan peringkat, klik pada nama pengguna untuk melihat kartu yang memperlihatkan informasi profil dasar pengguna tanpa harus menavigasi dari luar halaman. Aktifkan fitur ini untuk menambahkan usercard ke tema khusus Anda.';
$Definition['User inputs are based on the global background and text colors.'] = 'Input pengguna didasarkan pada latar belakang global dan warna teks.';
$Definition['User Profile'] = 'Profil pengguna';
$Definition['Users may sign into your site using their Twitter account.'] = 'Pengguna dapat masuk ke situs Anda menggunakan akun Twitter mereka.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Gunakan tombol di bagian atas halaman untuk membuat aturan larangan.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Gunakan plugin WordPress untuk menyetel Komentar Vanilla pada blog anda, atau gunakan kode universal untuk menyetel Komentar Vanilla pada platform lainnya.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Layanan pencarian baru Vanilla akhirnya ada di sini. Aktifkan halaman antarmuka pengguna pencarian baru kami untuk mendapatkan akses ke fitur pencarian terbaru seperti pencarian Anggota, urutan pencarian dan penyorotan istilah.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Ekspor Vanilla: %s, Sumber: %s';
$Definition['Vanilla Statistics are currently disabled'] = 'Statistik Vanilla saat ini dinonaktifkan';
$Definition['Verify and restore'] = 'Verifikasi dan pulihkan';
$Definition['VerifyUser'] = 'Ceklis kotak disebelah pengguna untuk menandai mereka sebagai  <b>Diverifikasi </b> supaya postingan mereka tidak ditandai sebagai spam lagi. Ini juga akan mengembalikan semua postingan mereka yang tertunda.';
$Definition['Video tutorial on advanced settings'] = 'Video tutorial setelan tingkat lanjut';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video tutorial pencarian & pengelolaan pengguna';
$Definition['Video tutorial on managing appearance'] = 'Video tutorial pengelolaan tampilan';
$Definition['Video tutorial on managing categories'] = 'Video tutorial pengelolaan kategori';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video tutorial pengelolaan peran & perizinan';
$Definition['Video tutorial on user registration'] = 'Video tutorial pendaftaran pengguna';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Peringatan: Mengaktifkan fitur ini dapat menyebabkan kesalahan Javascript di situs Anda.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Peringatan</b> : Konfigurasi server Anda tidak mendukung pemuatan data yang cepat. Jika Anda mengimpor file yang sangat besar (mis. Lebih dari 200.000 komentar), Anda mungkin ingin mempertimbangkan untuk mengubah konfigurasi Anda. Klik di <a href="http://vanillaforums.com/porter">sini</a> untuk informasi lebih lanjut.';
$Definition['Warning: This is for advanced users.'] = '<b>Peringatan</b>: Ini untuk pengguna tingkat lanjut dan memerlukan perubahan tambahan pada web server anda. Ini biasanya hanya tersedia bila anda menggunakan dedicated hosting atau vps. Jangan lakukan ini bila anda tidak yakin untuk melakukannya.';
$Definition['Webhooks'] = 'Webhook';
$Definition['Welcome to Labs!'] = 'Selamat datang ke Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Selamat datang di UI bertema Vanilla. Halaman ini mencantumkan semua tema yang tersedia, dan memungkinkan Anda untuk menyalin atau mengeditnya.';
$Definition['Welcome To Your Theme'] = 'Selamat Datang Di Tema Anda';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Kami merekomendasikan sebagian besar reaksi positif untuk mendorong partisipasi.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Saat diaktifkan, Anda dapat mengelola produk, dan mengelompokkan subkomunitas oleh produk-produk tersebut.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Ketika seseorang membagikan tautan dari situs Anda, kami mencoba dan mengambil gambar dari halaman tersebut. Jika tidak ada gambar di halaman maka kami akan menggunakan gambar ini sebagai gantinya. Gambar harus minimal 50 × 50, tetapi kami menyarankan 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Ketika Anda memilih Bleed Penuh, latar belakang Anda transparan.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Apakah bidang profil internal akan disertakan atau tidak dalam webhook ini.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Apakah bidang profil pribadi akan disertakan atau tidak dalam webhook ini.';
$Definition['Which reactions you use really depends on your community.'] = 'Reaksi mana yang Anda gunakan benar-benar tergantung pada komunitas Anda, tetapi kami sarankan Anda mengingat beberapa hal.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Anda akan menerapkan opsi tata letak baru. Ini dapat disesuaikan dan dipratinjau menggunakan Editor Tema kami. <0>Pelajari lebih lanjut</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Anda dapat melarang semua pengguna dengan alamat IP yang diawali "111.111.111" dengan menambahkan larangan tipe IP dengan nilai "111.111.111.*".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Anda dapat melarang alamat IP, alamat email dan nama pengguna.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Anda dapat memilih dari salah satu gaya berbeda yang ditawarkan tema ini.';
$Definition['You can configure some values differently for different screensizes.'] = 'Anda dapat mengkonfigurasi beberapa nilai secara berbeda untuk screensizes yang berbeda.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Anda dapat terhubung ke multi situs yang mendukung jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Jika berkas Anda terlalu besar untuk diunggah langsung ke laman ini Anda dapat memasukkannya ke folder /uploads Anda. Pastikan nama berkas dimulai dengan kata <b>ekspor</b> dan berakhir dengan salah satu dari ekstensi <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Anda dapat menentukan panjang posting minimum untuk mencegah posting pendek.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Anda dapat mengunggah Font Kustom di Sistem Mereka. Cukup salin & tempel URL di bidang.';
$Definition['You must select a file to import.'] = 'Anda harus memilih sebuah file untuk diimpor.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Anda perlu menambahkan domain url font ke <0> Domain yang Diizinkan </0> dalam konfigurasi situs. <1> Pelajari lebih lanjut tentang font khusus. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Tema seluler Anda akan dinonaktifkan. Untuk mengatur berbagai tema seluler dan desktop, gunakan UI tema lama.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Nama organisasi Anda digunakan untuk mikrodata SEO dan JSON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Favicon situs Anda tampil di bilah judul peramban Anda. Ikon ini akan disesuaikan ukurannya.';
