<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**هشدار: فعال کردن این ویژگی ممکن است باعث ایجاد خطاهای جاوا اسکریپت در سایت شما شود.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>مراقب باشيد !</strong> حذف كردن يك نقش ميتواند منجر به عدم دسترسي كاربران به درخواستي شود.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>مراقب باشيد !</strong> انتقال گفتگوها به يك دسته بندي جايگزين ميتواند منجر به ناپديد شدن‌( يا پديدار شدن‌ ) گفتگوها شود اگر كه دسته بندي جايگزين مجوزهاي ديگري نسبت به دسته بندي حذف شده داشته باشد.';

$Definition['About.DisableStatistics'] = 'اگر گزارش اطلاعات را بايد به دلايلي غيرفعال كنيد، اين كار را با اضافه كردن خط زير در فايل پيكربندي نصبي خود ميتوانيد انجام دهيد : <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'بسيار مهم و حياتي است كه اين نرم افزار رايگان و منبع باز است . ما از شما تقاضا داريم كه لطفاً گزارش اين اطلاعات را غيرفعال نكنيد.';
$Definition['AboutCommentEmbedding'] = 'وانيلا ميتواند بعنوان سيستم جايگزين براي ارسال ديدگاه وبلاگ شما باشد. درواقع، ميتوان از وانيلا براي ارسال ديدگاه در هر صفحه از وب استفاده كرد.';
$Definition['AboutEmbedding'] = 'درج كردن اجازه ميدهد كه تمام يا بخشي از انجمن شما به درون ديگر اپليكيشن يا صفحات وب درج گردد.';
$Definition['About Vanilla Statistics'] = 'درباره آمار وانيلا';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'دسترسي به انجمن خود با كليك كردن بر روي لينك " بازديد از سايت " در بالاي اين صفحه، يا توسط لينك <a href={/,url}> اينجا را كليك كنيد</a> . انجمن تمام چيزهايي است كه كاربران و مشتريهاي شما وقتي كه <a href="{/,url,domain}">{/,url,domain}</a> را بازديد ميكنند، ميباشد.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'در بحث ها و نظرات ، ابعاد بارگذاری تصویر را اضافه کنید.';
$Definition['AddonProblems'] = '<h2>مشكلي داريد؟</h2><p>اگر مشكلي با افزونه اي پيش آمد و شما نتوانستيد از سايت خود استفاده كنيد، شما ميتواند بصورت دستي با ويرايش %s آنها را غيرفعال كنيد</p>';
$Definition['AddressBarColorDescription'] = 'بعضی از مرورگرها از یک رنگ برای نوار آدرس پشتیبانی می کنند. فقط موبایل';
$Definition['Alert users if they click external link.'] = 'در صورت کلیک روی پیوندی در پستی ، کاربران هشدار می دهند که آنها را از این انجمن دور می کند. به دنبال پیوندهایی که با یک دامنه معتبر مطابقت دارند ، کاربران هشدار داده نمی شوند';
$Definition['Alignment'] = 'هم ترازی';
$Definition['Alignment (Mobile)'] = 'تراز (موبایل)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'تمام دسته بندي ها با 5 گفتگوي جديد زير هم ليست شده است';
$Definition['Allow links to be transformed'] = 'اجازه دهید پیوندها در مباحث و نظرات به بازنمودهای تعبیه شده تبدیل شوند. به عنوان مثال ، یک لینک YouTube به یک فیلم جاسازی شده تبدیل می شود.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'اجازه دهید کاربران با اجازه %s اجازه تغییر آواتارهای خود را از صفحات نمایه خود در وانیل داشته باشند.';
$Definition['Anonymize IP Addresses'] = 'ناشناس کردن آدرس های IP';
$Definition['ApplicationHelp'] = 'اپليكيشن ها به شما اجازه ميدهند گروه هاي بزرگي از قابليت ها را به سايت خود اضافه كنيد.<br />هنگامي كه اپليكيشني به پوشه %s شما اضافه شد، ميتوانيد آن را از اينجا فعال يا غيرفعال كنيد.';
$Definition['Apply Layout'] = 'Layout را اعمال کنید';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'مطمئن هستید که می خواهید این موضوع را حذف کنید؟ به طور دائم حذف می شود.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'آيا مطمئن هستيد كه نام ميزبان پايگاه داده را صحيح وارد كرده ايد؟ شايد اسمش را اشتباه تايپ كرده باشيد؟ پايگاه داده گزارش ميدهد : <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'نقشی با نوع پیش فرض "تائید نشده" نیازمند تائید توسط ایمیل میباشد.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'پیش نویس بحث ها، سوالات، ایده ها و نظرات منتشر نشده را به صورت خودکار ذخیره کنید.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'اگر از این ارتفاع بیشتر شود ، آواتارها کوچکتر می شوند.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'اگر از این عرض بیشتر شود ، آواتارها کوچکتر می شوند.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'آواتارها تصاویر کوچک خود را در این اندازه ذخیره می کنند.';

$Definition['Background'] = 'زمینه';
$Definition['Background Image'] = 'تصویر پس زمینه';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'خلاق بودن! سعی کنید صفحات خود را بعد از مواردی که جامعه درباره آن صحبت می کند ، نامگذاری کنید.';
$Definition['Bordered'] = 'هم مرز';
$Definition['Bordered (Unified)'] = 'هم مرز (متحد)';
$Definition['Borderless'] = 'بدون مرز';
$Definition['Border Radius'] = 'شعاع مرزی';
$Definition['Brand Color'] = 'رنگ مارک';
$Definition['Buttons'] = 'دکمه ها';
$Definition['Buttons & Inputs'] = 'دکمه ها و ورودی ها';
$Definition['Button Type'] = 'نوع دکمه';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'با كليك بر روي دكمه زير، شما حساب كاربري را براي هميشه براي %s حذف خواهيد كرد.';

$Definition['Center Aligned'] = 'مرکز تراز شد';
$Definition['Changes to the set day will take affect the following week.'] = 'تغییرات در روز تعیین شده در هفته بعد تأثیر می گذارد.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'تغییرات فقط در آواتارهای تازه آپلود شده اعمال می شوند.';
$Definition['Change the sizes that avatar images are saved at.'] = 'اندازه هایی را که تصاویر آواتار در آنها ذخیره می شود تغییر دهید.';
$Definition['Change the way your community works with plugins.'] = 'شيوه كاركرد انجمن خود را با پلاگين ها تغيير دهيد. ما پلاگين هاي محبوبي را به همراه نرم افزار ارائه كرديم، و پلاگين هاي ديگري بصورت آنلاين در دسترس ميباشد.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'کادرهای انتخاب به مدیران اجازه می دهد تا اقدامات دسته ای را در تعدادی از بحث ها یا نظرات همزمان انجام دهند.';
$Definition['Check out our %s'] = '%s ما را بررسی کنید';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = '<0>اسناد ما را بررسی کنید</0> ، یا از <1>جامعه کارشناسان ما بپرسید</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'وانيلا ساده ترين، و قدرتمندترين پلتفرم انجمن ساز دنياست. بطور چشمگيري براي استفاده ساده است. با اين ويدئوي مقدماتي كار خود را شروع كرده و از مراحل زير ادامه دهيد. لذت ببريد !';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'نقشي را براي اختصاص به كاربران بدون نقش انتخاب كنيد :';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'موضوعی را برای این فرعی انتخاب کنید. <0> بیشتر بخوانید </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'انتخاب چگونگي بكارگيري تمام محتواي مرتبط با حساب كاربري براي %s ( ديدگاه ها، پيام ها، غيره ).';
$Definition['Choose Image'] = 'تصویر را انتخاب کنید';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'ميتوانيد الگوريتم هش دلخواه براي ثبت درخواست هاي خود انتخاب نماييد. همينطور بايد الگوريتم هش در كتابخانه كلاينت شما نيز استفاده شده باشد. اگر مطمئن نيستيد چه چيزي را انتخاب كنيد md5 را انتخاب نماييد.';
$Definition['Choose the order items are sorted.'] = 'انتخاب موارد سفارش مرتب شده اند.';
$Definition['Choose the page people should see when they visit <0/>'] = 'صفحه ای را انتخاب کنید که افراد هنگام بازدید از <0/> باید ببینند';
$Definition['Choose the preferred layout for lists of categories.'] = 'طرح دلخواه را برای لیست دسته ها انتخاب کنید.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'طرح دلخواه را برای فهرست دسته ها انتخاب کنید. می توانید طرح کاشی کاری را ویرایش کنید.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'طرح مورد نظر را برای لیست مباحث انتخاب کنید.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'طرح مورد نظر را برای فهرست مباحث انتخاب کنید. می توانید طرح بنیاد را ویرایش کنید.';
$Definition['Color Overlay'] = 'پوشش رنگ';
$Definition['Continue Import'] = 'ادامه درون ريزي';
$Definition['Could not parse import file. The problem is near line %s.'] = 'نميتوان فايل درون ريزي را تجزيه كرد. مشكل در نزديكي خط %s ميباشد.';
$Definition['Create a localization CSV'] = 'ايجاد يك CSV بومي سازي';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'مضامین سفارشی مضامی است که شما ایجاد کرده اید. می توانید ویرایش ، تغییر نام دهید یا نسخه ای از آنها تهیه کنید.';

$Definition['Dark'] = 'تاریک';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'تعيين كنيد چه كسي بتواند فايل ها را در صفحه <a href="%s"> نقش ها و مجوزها </a> آپلود و مديريت كند.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'صفحه اصلي انجمن خود را تعريف كنيد. لوگوي خود را آپلود كرده، و كارهاي ديگر ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'حذف يك نقش منجر به عدم دسترسي كاربران به اپليكيشن ميشود.';
$Definition['Deleting forever cannot be undone.'] = 'حذف كردن يك روش خوبي براي پاك نگه داشتن انجمن شماست.';
$Definition['Disable Google Sign In'] = 'غيرفعالسازي ورود از گوگل';
$Definition['Disable OpenID'] = 'غيرفعالسازي OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'آزمایشگاه "سیستم جاسازی جدید" را در صفحه <0>Vanilla Labs غیرفعال کنید</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'دسته بندي گفتگو براي كمك به كاربران جهت سازماندهي به گفتگوهايشان به روش معني داري براي انجمن شما ميباشد.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'پيشخوان مديريت خود را درج نكنيد ( پنجره اي به تمام-صفحه باز خواهد شد‌)';
$Definition['Don\'t use too many reactions.'] = 'از واکنش های زیاد استفاده نکنید. شما نمی خواهید اطلاعات اضافی به کاربران خود بدهید.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'براي مرتب سازي و زيرهم قرار دادن دسته ها آنها را كشيده و رها كنيد.';

$Definition['EditContentTimeout.Notes'] = 'اگر كاربري در يك نقشي باشد كه مجوز ويرايش محتوا را دارد، آن مجوزها بر روي اين رونويسي خواهند شد.';
$Definition['Edit Route'] = 'ويرايش مسير';
$Definition['Edits to this theme apply to:'] = 'ویرایشهای مربوط به این موضوع در مورد:';
$Definition['Email digests will be sent on the selected day every week.'] = 'خلاصه ایمیل در روز انتخاب شده هر هفته ارسال می شود.';
$Definition['Email sent from the application will be addressed from this email address'] = 'ایمیل ارسال شده از برنامه از این آدرس ایمیل آدرس داده می شود';
$Definition['Email sent from the application will be addressed from this name'] = 'ایمیل ارسال شده از برنامه از این نام آدرس داده می شود';
$Definition['Email Settings'] = 'تنظیمات ایمیل';
$Definition['Embed Settings'] = 'تعبیه تنظیمات';
$Definition['Embed your community forum into your website to increase engagement...'] = 'براي افزايش تعامل انجمن خود را درون وبسايت خود درج كنيد ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'آخرین ویژگی های وانیل را فعال و آزمایش کنید.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'ویرایش پیشرفته ارسال ها در چندین قالب ، از جمله WYSIWYG ، HTML ساده ، Markdown و BBCode را فعال می کند.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'ویرایشگر طرح‌بندی را فعال کنید تا یک طرح‌بندی سفارشی برای صفحات انجمن شما اعمال کند. از ویرایشگر جدید ما برای نمایش محتوا با استفاده از کاتالوگ ویجت های موجود استفاده کنید.';
$Definition['Enter a descriptive name.'] = 'يك نام توصيفي براي بسته خود وارد كنيد. اين نام هيچ جا نمايش داده نميشود بجز هنگامي كه ميخواهيد بسته خود را از اينجا مديريت كنيد بنابراين فقط براي كمك به يادآوري بسته مفيد ميباشد.';
$Definition['Enter a short name for the site.'] = 'نام كوتاهي را براي اين سايت وارد كنيد. اين بر روي دكمه هاي ثبت نام نمايش داده ميشود.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'آدرس براي بلاگ وردپرس خود را وارد كرده و ما از اينجا آدرس را برميداريم.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'تنظيمات اتصال براي سرويس دهنده sphinx خود را در زير وارد كنيد.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'تمام ويرايش و حذف كردن ها در اينجا ثبت ميشود. براي برگشت هر تغييري از ‘بازيابي’ استفاده كنيد.';
$Definition['Everyone who signs up gets a profile page.'] = 'هركسي كه براي انجمن شما ثبت نام كند يك صفحه پروفايل عمومي دريافت ميكند جايي كه ميتوانند يك تصويري از خود را آپلود كرده، تنظيمات پروفايل خود را مديريت كنند، و چيزهاي جالبي كه در انجمن رخ ميدهد را دنبال كنند. شما بايد <a href="{/profile,url}"> همينك پروفايل خود را شخصي سازي</a> كنيد.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'هركاربر در وبسايت شما حداقل به يك نقش اختصاص داده شده. نقش ها تعيين كننده اين هستند كه كاربران مجاز به چه كاري ميباشند.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'اتصال فيس بوك به كاربران اين اجازه را ميدهد تا با حساب كاربري فيس بوك خود وارد انجمن شوند.<b> شما بايد اپليكيشن خود را با فيس بوك براي اين پلاگين ثبت كرده تا اين اتصال جواب بدهد</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'با نام كاربري و كلمه عبوري كه شما وارد كرده ايد اتصال به پايگاه داده با خطا روبرو شد. آيا اطلاعات را اشتباه تايپ كرده ايد؟‌پايگاه داده گزارش ميدهد : <code>%s</code>';
$Definition['Font'] = 'قلم';
$Definition['Font Name'] = 'نام قلم';
$Definition['Font URL'] = 'URL قلم';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'اجبار كردن پيشخوان براي اينكه فقط از طريق اين آدرس وب قابل دسترس باشد <em> (توصيه نميشود) </em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'به عنوان مثال ، شما می توانید با اضافه کردن یک ممنوعیت نوع ایمیل به ارزش "*@example.com" ، همه کاربران را با آدرس های ایمیل از "example.com" ممنوع کنید.';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'براي اهداف سئو، خزنده هاي موتور جستجوگر شامل اجباري براي نمايش انجمن در آدرس وب از راه دور نميباشند.';
$Definition['Foundation Layout'] = 'طرح بندی بنیاد';
$Definition['Full Anonymization'] = 'ناشناس سازی کامل';
$Definition['FullAnonymization.Description'] = '<strong>ناشناس‌سازی کامل</strong> هر آدرس IP را با 0.0.0.0 جایگزین می‌کند و به طور مؤثری از دسترسی برنامه به کار با آدرس‌های IP جلوگیری می‌کند. قوانین ممنوعیت IP در این مورد به هیچ وجه کار نمی کند.';
$Definition['Full Bleed'] = 'کامل خونریزی';

$Definition['Garden.Import.Complete.Description'] = 'شما با موفقيت عمليات درون ريزي را انجام داديد.
   هنگامي كه آماده بوديد بر روي <b>پايان</b> كليك كنيد.';
$Definition['Garden.Import.Continue.Description'] = 'به نظر می رسد که شما در وسط واردات هستید. لطفا یکی از گزینه های زیر را انتخاب کنید.';
$Definition['Garden.Import.InputInstructions'] = 'ايميل و كلمه عبور كاربر مدير را از داده هايي كه درحال درون ريزي است را وارد نماييد.';
$Definition['Garden.Privacy.IPs.Description'] = 'آدرس‌های IP کاربر معمولاً برای قوانین ممنوعیت خودکار، تعدیل و اهداف جلوگیری از هرزنامه جمع‌آوری می‌شوند. فعال کردن IP Anonymization تمام آدرس های IP ردیابی شده در سایت را برای هر هدفی ناشناس می کند و کارایی این ابزارها را کاهش می دهد. تغییرات در این تنظیم عطف به ماسبق نیستند.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit اجازه تغییر آواتارهای خود را از صفحات نمایه خود در وانیل.';
$Definition['Garden.StatisticsDisabled'] = 'شما بطور خاص آمار وانيلا را در فايل پيكربندي خود غيرفعال كرده ايد.';
$Definition['Garden.StatisticsLocal.Explain'] = 'اين انجمن بنظر ميرسد در حالت آزمايشي اجرا شده است،و يا درصورت ديگر يك IP خصوصي گزارش ميشود. بطور پيش فرض، انجمن هايي كه با IPهاي خصوصي اجرا شوند رديابي نميشوند.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'اگر مطمئن هستيد كه انجمن شما در اينترنت قابل دسترس ميباشد ميتوانيد اجبار كنيد كه آمار را در اينجا گزارش كنيد :';
$Definition['Garden.StatisticsReadonly.Explain'] = 'بنظر ميرسد فايل config.php شما فقط خواندني باشد. اين بدان معني است كه وانيلا نميتواند بطور خودكار InstallationID و InstallationSecret انجمن شما را ثبت كند.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'براي حل اين مشكل، مجوز فايل conf/config.php خود را بر روي 777 قرار دهيد.';
$Definition['Global Styles'] = 'سبک جهانی';

$Definition['Heads Up!'] = 'سر بالا!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'مراقب باشيد! اين يك نقش بخصوصي است كه اجازه جلسه هاي فعال را نميدهد. به اين دليل، گزينه هاي مجوز به مجوز "ديدن" محدود شده است.';
$Definition['Here are all of the reactions you can use on your site.'] = 'در اینجا تمام واکنش هایی که می توانید در سایت خود استفاده کنید وجود دارد.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'در اینجا رتبه هایی وجود دارد که کاربران می توانند در سایت شما به آن دست پیدا کنند. می توانید این رده ها را به صورت دلخواه تنظیم کرده و حتی موارد جدیدی را اضافه کنید. در اینجا چند نکته وجود دارد.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'اگر لوگوي بنر آپلود شده باشد، جايگزين عنوان بنر در صفحه هاي انجمن محيط كاربري خواهد شد.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'اگر کاربر در این بازه زمانی از سایت بازدید نکند، به طور خودکار از سیستم خارج می شود.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'در صورت فعال بودن ، محتوای کامل پستها در اطلاعیه های ایمیل به کاربران ارسال می شود.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'اگر تازه وارد HTML و / یا CSS نیستید ، در اینجا چند آموزش برای شروع کار آورده شده است:';
$Definition['If you have an old theme'] = 'اگر یک موضوع قدیمی دارید و باید یک میز کار جداگانه و یک تلفن همراه تنظیم کنید ، می توانید با استفاده از UI با مضمون قدیمی این کار را انجام دهید.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'اگر ميخواهيد سطح هشدار را پايين بياوريد يك هشدار را حذف كنيد.';
$Definition['If you want to embed your forum, enable embedding.'] = 'اگر می خواهید فروم خود را جاسازی کنید یا از نظرات وانیل در وبلاگ خود استفاده کنید ، باید تعبیه را فعال کنید. اگر از تعبیه استفاده نمی کنید ، توصیه می کنیم این تنظیم را خاموش کنید.';
$Definition['Image (Mobile)'] = 'تصویر (موبایل)';
$Definition['Import'] = 'درون ريزي';
$Definition['Importing to Vanilla'] = 'درون ريزي به وانيلا';
$Definition['In additon to the widgets there are also'] = 'در افزونه ابزارک ها <0> سبک های جهانی نیز وجود دارد </0> . برای ویرایش سبک های جهانی ، در هر نقطه دیگری از صفحه ، مانند این متن ، کلیک کنید.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'صفحات و اجزای بنیاد را در موضوع خود ادغام کنید';
$Definition['Internationalization & Localization'] = 'بین المللی و بومی سازی';
$Definition['Invalid URL'] = 'URL نامعتبر است';
$Definition['Invitation email failed to send: %'] = 'اگرچه این دعوت با موفقیت ایجاد شد ، ایمیل ارسال نشد. سرور خطای زیر را گزارش داد: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'هنگامي كه شما از ثبت نام توسط دعوت استفاده ميكنيد كاربران لينكي به نام <a href="%s" class="Popup"> دعوتنامه هاي من </a> در پروفايل خود خواهند داشت.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'بنظر ميرسد پايگاه داده شما هنوز وجود ندارد. آيا پايگاه داده خود را ايجاد كرده ايد؟ نام پايگاه داده خود را اشتباه تايپ نكرده ايد؟ پايگاه داده گزارش ميدهد :  <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'اين ايده خوبي است كه حداكثر تعداد كاراكترهاي مجاز به اندازه معقول براي نوشتن ديدگاه درنظر گرفته شود.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'این ایده خوبی است که حداکثر تعداد کاراکترهای مجاز در یک نوشته را در اندازه معقول نگه دارید.';

$Definition['Kick-start your community and increase user engagement.'] = 'انجمن خود را شروع كرده و ارتباط كاربري را افزايش دهيد.';

$Definition['Labs'] = 'آزمایشگاه ها';
$Definition['Layout Editor'] = 'ویرایشگر چیدمان';
$Definition['Learn about custom routing.'] = 'کسب اطلاع در مورد مسیریابی سفارشی.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'يادبگيريد چگونه كاملاً‌ظاهر انجمن خود را تغيير دهيد : لوگوي خود را آپلود كنيد، صفحه اصلي خود را تنظيم كنيد، قالبي را انتخاب و سفارشي كنيد.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'يادبگيريد چگونه از قابليتهاي ابتدايي انجمن خود استفاده كنيد.';
$Definition['Left Aligned'] = 'سمت چپ تراز شد';
$Definition['Light'] = 'سبک';
$Definition['Links'] = 'پیوندها';
$Definition['Locales allow you to support other languages on your site.'] = 'بومي سازي به شما اجازه ميدهد تا از ديگر زبان ها را بر روي سايت خود پشتيباني كنيد. زبان هاي موجودي را كه مايل هستيد را ميتوانيد از اينجا فعال يا غيرفعال كنيد.';
$Definition['Lockout Time (seconds)'] = 'زمان قفل شدن (ثانیه)';
$Definition['LogoDescription'] = 'نماد بنر در بالای سایت شما ظاهر می شود.';
$Definition['LogoDisclaimer'] = 'مضامین ساخته شده با ویرایشگر موضوع و برخی از تم های سفارشی از این تنظیم استفاده نمی کنند.';
$Definition['Looking for the Old Embed System?'] = 'به دنبال سیستم جاسازی قدیمی هستید؟';

$Definition['Make sure you click View Page'] = 'براي ديدن ظاهر صفحه دسته بندي هاي خود پس از ذخيره كردن مطمئن شويد كه بر روي <a href="%s"> نمايش صفحه </a> كليك كنيد.';
$Definition['Manage Routes'] = 'مديريت مسيرها';
$Definition['Managing Users'] = 'مدیریت کاربران';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'نشانه گزاري نوشته ها بعنوان اسپم نيست آنها را دوباره در انجمن برميگرداند.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'نشانه گزاري نوشته ها بعنوان اسپم نيست آنها را دوباره در انجمن برميگرداند.';
$Definition['Messages can appear anywhere in your application.'] = 'پيام ها ميتوانند هرجايي در اپليكيشن شما نمايش داده شوند، و ميتواند براي اطلاع رساني كاربران از اخبار و رويدادها مفيد باشد. از اين صفحه براي سازماندهي مجدد پيام هاي خود با كشيدن به بالا و پايين استفاده كنيد.';
$Definition['MobileLogoDescription'] = 'نماد بنر موبایل در بالای سایت شما ظاهر می شود.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'مضامین موبایل به شما امکان می دهد نگاه و ظاهر سایت خود را در دستگاه های کوچکتر تغییر دهید.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB ویرایشگر طرح‌بندی جدید، تم مجموعه‌ای را در راهنمای سبک (به طور رسمی ویرایشگر تم) به ارث می‌برد. <1>بیشتر بیاموزید</1>';
$Definition['Need More Help?'] = 'به راهنماي بيشتري نياز داريد؟';
$Definition['Need more help?'] = 'به کمک بیشتری نیاز دارید؟';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'دسته های توخالی عمیق تر از این عمق در یک لیست محدود شده با کاما قرار می گیرند.';
$Definition['New Embed System'] = 'سیستم جاسازی جدید';
$Definition['New Quick Links'] = 'پیوندهای سریع جدید';
$Definition['New Search Page'] = 'صفحه جستجوی جدید';
$Definition['No Anonymization'] = 'بدون ناشناس سازی';
$Definition['Not getting what you expect when you preview your theme?'] = 'هنگام پیش نمایش موضوع خود آنچه را انتظار دارید دریافت نکنید؟';
$Definition['Notify me when people comment on my addons.'] = 'هنگامي كه شخصي بر روي افزونه هاي من ديدگاهي ارسال كرد من را مطلع كن.';
$Definition['No unconfirmed role available for email confirmation.'] = 'سایت نیازمند نقشی با نوع پیش فرض "تائید نشده" با استفاده از تائید ایمیل میباشد. لطفا ً یک نقش را برای فعالسازی این تنظیمات اضافه کنید';

$Definition['Old Theming UI'] = 'رابط کاربری قدیمی تم';
$Definition['Once enabled, only members will see inside your community.'] = 'پس از فعال کردن ، فقط اعضا در انجمن شما خواهند دید.';
$Definition['OrgDescription'] = 'نام سازمان شما برای microdata SEO و JSON+LD استفاده می شود';
$Definition['Outline'] = 'طرح کلی';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'نماهای محدود یا مضامین اصلی می توانند عوارض جانبی ناخواسته داشته باشند و پیش نمایش نشوند.';

$Definition['Partial Anonymization'] = 'ناشناس سازی جزئی';
$Definition['PartialAnonymization.Description'] = '<strong>ناشناس سازی جزئی</strong> فقط آخرین اکتت آدرس IP را ناشناس می کند. به عنوان مثال 254.230.05.153 به 254.230.05.0 تبدیل می شود. این مقداری ناشناس سازی را فراهم می کند در حالی که همچنان به قوانین ممنوعیت IP اجازه عملکرد می دهد.';
$Definition['Password.MinLength'] = 'حداقل طول کاراکتر مجاز برای رمزهای عبور کاربران در صفحات ایجاد و بازنشانی رمز عبور.';
$Definition['Please choose an authenticator to configure.'] = 'لطفاً يك اعتبار سنج براي پيكربندي انتخاب كنيد.';
$Definition['PluginHelp'] = 'پلاگين ها به شما اجازه اضافه كردن قابليتهايي به سايت شما ميدهند.<br />هنگامي كه پلاگيني به پوشه %s شما اضافه شد، از اينجا ميتوانيد آن را فعال و يا غيرفعال كنيد.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'بسته بين هر گفتگو در ليست گفتگوي اصلي نمايش داده ميشود. از آنجايي كه گفتگوها معمولا در <li>..</li> برچسب ها هستند، لازم است كه شما بسته را بين آن برچسب ها قرار دهيد.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'بسته ها به شما اجازه ميدهند تا انواع HTML را در مكان هاي مختلفي در سرتاسر اپليكيشن قرار دهيد.';
$Definition['Preset'] = 'از پیش تعیین شده';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'جلوگيري از ارسال هرزنامه در انجمن خود توسط محدود كردن تعداد گفتگوها & ديدگاه ها كه كاربران ميتوانند در يك زمان مشخص شده اي ارسال كنند.';
$Definition['Primary Button'] = 'دکمه اولیه';
$Definition['Primary Buttons'] = 'دکمه های اولیه';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'راهنماي شروع سريع براي ساخت قالب وانيلا';
$Definition['Quick Links is a default component on community pages.'] = 'پیوندهای سریع یک جزء پیش فرض در صفحات انجمن است. برای افزودن ، ویرایش یا مخفی کردن پیوندها از این منو با استفاده از ویرایشگر موضوع ، جزء پیوندهای سریع ما را فعال کنید.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'پلاگين ارسال ديدگاه آماده براي وردپرس';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'پلاگين انجمن ساز آماده براي وردپرس';
$Definition['Realtime progress bars: %s'] = 'نوار پيشرفت بهنگام : %s';
$Definition['Recommend special ranks for admins and mods.'] = 'این ایده خوبی است که برای مدرسین و سرپرستان رتبه های خاصی داشته باشید تا جامعه شما به راحتی ببیند چه کسی مسئول است.';
$Definition['Recommend starting with five ranks.'] = 'شما نمی خواهید رتبه های خیلی زیادی داشته باشید توصیه می کنیم از پنج شروع کنید. اگر جامعه شما واقعاً بزرگ است ، می توانید موارد بیشتری اضافه کنید.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'پیوندهای بحث و دسته بندی را از منوها حذف کنید. صفحات مربوط به بحث و دسته بندی را طوری تنظیم کنید که صفحه 404 یافت نشد.';
$Definition['Requires “Flag” reaction permission.'] = 'به عکس العمل "پرچم" نیاز دارد.';
$Definition['Requires “Negative” reaction permission.'] = 'نیاز به اجازه واکنش "منفی" دارد.';
$Definition['Requires “Positive” reaction permission.'] = 'نیاز به اجازه واکنش مثبت دارد.';
$Definition['Restoring your selection removes the items from this list.'] = 'هنگام بازيابي، آيتم ها از اين ليست حذف شده و سرجاي خود در سايت قرار ميگيرند.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'از گزینه زیر برای فعال کردن نقل قول ها برای ویرایشگر غنی استفاده کنید. فقط در صورتی اعمال خواهد شد که قالب بندی پیش فرض "غنی" باشد.';
$Definition['Route Expression'] = 'اصلاح مسير';
$Definition['Routes are used to redirect users.'] = 'مسيرها براي تغيير مسير كاربران بسته به آدرس وب درخواست شده استفاده ميشود.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'جستجوي كاربران بر اساس نام و يا نام يك نقش را وارد كرده تا تمام كاربراني كه اين نقش را داشته مشاهده شوند.';
$Definition['Secondary Button'] = 'دکمه ثانویه';
$Definition['Secondary Buttons'] = 'دکمه های ثانویه';
$Definition['Security.Hsts.HTTPSWarning'] = 'هشدار: اگر مطمئن هستید که تمام زیر دامنه های شما برای HTTPS با گواهی های معتبر تنظیم شده اند ، این ویژگی را فعال کنید.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'در صورت فعال بودن ، این قانون برای همه زیر دامنه های سایت شما نیز اعمال می شود.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'توصیه می کنیم با حداکثر سن 1 هفته شروع کرده و پس از مشاهده سایت خود مطابق پیش بینی ، آن را به 1 ماه و 1 سال افزایش دهید.';
$Definition['Security.Hsts.SubmitWarning'] = 'هشدار: پشتیبانی از پیش بارگذاری HSTS به عنوان بهترین روش بسیار عالی است. با این حال ، شما باید سایت خود را به آدرس hstspreload.org ارسال کنید تا اطمینان حاصل شود که از قبل بارگیری شده با موفقیت انجام می شود (یعنی برای به دست آوردن حفاظت کامل از پیکربندی مورد نظر).';
$Definition['See the documentation'] = 'مستندات را ببینید';
$Definition['Select the default type for this role, if any.'] = 'در صورت وجود نوع پیش فرض برای این نقش را انتخاب کنید.';
$Definition['Select the import source'] = 'منبع درون ريزي را انتخاب كنيد';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'ستون هاي سريال "%s" براي خارج كردن از حالت سريالي با خطا روبرو شد.';
$Definition['Session Timeout'] = 'پایان جلسه';
$Definition['Shadowed'] = 'سایه دار';
$Definition['ShareImageDescription'] = 'هنگامی که شخصی پیوندی را از سایت شما به اشتراک می گذارد، ما سعی می کنیم تصویری را از صفحه بگیریم. اگر تصویری در صفحه وجود ندارد، به جای آن از این تصویر استفاده می کنیم. تصویر باید حداقل 50×50 باشد، اما ما 200×200 را توصیه می کنیم.';
$Definition['Show all possible pocket locations.'] = 'اين گزينه را روشن كرده تا تمام مكان هاي ممكن بسته نمايان شود. روشن كردن اين گزينه فقط مكان ها را براي كاربراني كه ميتوانند بسته ها را مديريت كنند نمايش ميدهد.';
$Definition['SignIn.LockoutTime'] = 'مدت زمانی که کاربر پس از بیش از تعداد تلاش‌های ورود به سیستم، از ورود به سیستم مسدود می‌شود.';
$Definition['Solid'] = 'جامد';
$Definition['Some browsers support a color for the address bar.'] = 'برخی از مرورگرها از یک رنگ برای نوار آدرس پشتیبانی می کنند.';
$Definition['Some older themes don\'t support full editing capability.'] = 'برخی از تم های قدیمی از قابلیت ویرایش کامل پشتیبانی نمی کنند. برای مشاهده اینکه یک طرح زمینه از چه چیزی پشتیبانی می‌کند، می‌توانید روی نام آن نگه دارید تا ببینید ویرایش‌ها در کجا اعمال می‌شوند.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'ممکن است برخی از تم ها برای کار با دسته زیر به روز شوند. می توانید ویژگی را غیرفعال کنید در حالی که موضوع خود را به روز می کنید.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'گاهی اوقات می خواهید سایت Vanilla خود را در یک سایت دیگر جاسازی کنید. سیستم جاسازی Vanilla یک راه آسان برای آن ارائه می دهد. هنگام استفاده از یک سایت تعبیه شده، معاوضه هایی در عملکرد وجود دارد، بنابراین اسناد را برای موارد جایگزین و موارد استفاده ایده آل بررسی کنید.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'محدودیت ویژه: فقط کاربران دارای مجوز Garden.Curation.Manage ممکن است از این واکنش استفاده کنند.';
$Definition['Specify a partial or full match when creating a ban.'] = 'هنگام ایجاد ممنوعیت ، یک مسابقه جزئی یا کامل را مشخص کنید.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'كمي وقت گذاشته و فكر كنيد كه در اينجا چه توضيحاتي براي سايت خود ميخواهيد بنويسيد. با نوشتن يك عنوان معني دار و توضيحات مختصر ميتواند به موقعيت بهتري در موتورهاي جستجو كمك كند.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'با اضافه كردن لوگو و شخصي سازي رنگ ها ايميل هاي خود را زيباتر كنيد.';
$Definition['Start Import'] = 'شروع درون ريزي';
$Definition['Start the first discussion.'] = 'همين حالا <a href="{/post/discussion,url}"> اولين نفري باشيد كه يك گفتگو را شروع ميكند </a>.';
$Definition['Subcommunities'] = 'انجمن های فرعی';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'برچسب زدن به کاربران این امکان را می دهد تا برای کشف بیشتر آنها ، برچسبهایی را به مباحثی که شروع می شوند اضافه کنند.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'قالبها مضامین استاندارد هستند. برای شخصی سازی آنها ، باید یک نسخه بسازید.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'اعتبار سنج %s گزينه هاي پيكربندي سفارشي ندارد.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB آزمایشگاه <0/> باید پیکربندی شود تا با طرح سفارشی شما مطابقت داشته باشد. این را می توان با استفاده از ویرایشگر تم جدید انجام داد. <1> بیشتر بدانید.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'افزونه نميتواند فعال شود زيرا يك خطاي مهلكي توليد كرد : <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'افزونه قبلا ً دانلود شده است.';
$Definition['The banner logo appears at the top of your forum.'] = 'لوگوي بنر در بالاي انجمن شما نمايش داده ميشود.';
$Definition['The banner title appears on the top-left of every page.'] = 'عنوان بنر در بالا- راست/چپ هر صفحه نمايش داده ميشود.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'عنوان بندر در بنر سايت شما و نوار عنوان مرورگر نمايش داده ميشود. اين بايد كمتر از 20 كاراكتر باشد. اگر لوگوي بنر آپلود شده باشد، جايگزين عنوان بندر در صفحات محيط كاربري انجمن خواهد شد. همچنين، به خاطر داشته باشيد كه شايد بعضي از قالب ها اين عنوان را نمايش ندهند.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>فرم ثبت نام ابتدايي نيازمند</strong> اين است كه كاربران جديد براي دور نگه داشتن هرزنامه نگاران كدامنيتي را از تصوير كپچا وارد كنند. شما به يك حساب كاربري در <a href="http://recaptcha.net/">recaptcha.net</a> نياز داريد. ثبت نام رايگان و ساده ميباشد. هنگامي كه ثبت نام كرديد ، برگشته و اين تنظيمات را وارد نماييد:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'نام كاربري پايگاه داده كه تعيين كرده ايد مجوز دسترسي به پايگاه داده را ندارد. آيا پايگاه داده را ايجاد كرده ايد؟ پايگاه داده گزارش ميدهد : <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'تغييرات ساختاري ذيل براي پايگاه داده شما نياز است.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'عنوان صفحه اصلي شما در صفحه اصلي نمايش داده ميشود. عنواني را انتخاب كنيد كه مايل هستيد آن را در موتورهاي جستجو ببينيد.';
$Definition['The import file does not contain any data.'] = 'فايل درون ريزي حاوي هيچ اطلاعاتي است.';
$Definition['The import file is not in the correct format.'] = 'فايل درون ريزي به فرمت صحيحي نميباشد.';
$Definition['The location of the authentication endpoint.'] = 'محل انتهای احراز هویت.';
$Definition['ThemeHelp'] = 'قالب ها به شما اجازه ميدهند تا ظاهر سايت خود را تغيير دهيد.<br />هنگامي كه قالبي به پوشه %s شما اضافه شد، از اينجا ميتوانيد آن را فعال كنيد.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'پیش نمایش تم محدود به نمایش قالب و CSS موضوع است.';
$Definition['Theming Guide'] = 'راهنمای سرقت';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'لوگوی موبایل در بالای سایت شما ظاهر می شود. طرح‌های زمینه ساخته شده با ویرایشگر طرح زمینه و برخی از طرح‌های زمینه سفارشی از این تنظیم استفاده نمی‌کنند.';
$Definition['The New Embed System'] = 'سیستم جاسازی جدید';
$Definition['The new embed system has improved performance.'] = 'سیستم جاسازی جدید عملکرد بهبود یافته، رفتار پیمایشی بهبود یافته و رفتار منسجم‌تری نسبت به سیستم قبلی دارد. در حال حاضر تعبیه‌های نظر و وردپرس در سیستم جاسازی جدید پشتیبانی نمی‌شوند.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'اعتبار سنج كلمه عبور گزينه هاي پيكربندي سفارشي ندارد. ';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'هيچگونه تغييراتي براي ساختار پايگاه داده لازم نيست. شايد، تغييراتي در داده نياز باشد.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'دو نوع دکمه در برنامه وجود دارد: اولیه و ثانویه.';
$Definition['The route was saved successfully.'] = 'مسير با موفقيت ذخيره شد.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'توضیحات سایت معمولا در موتورهای جستجو ظاهر می شود. باید سعی کنید توضیحاتی از 100 تا 150 کاراکتر داشته باشید.';
$Definition['The text of the pocket.'] = 'متن بسته را وارد كنيد. دقيقاً هرچه شما تايپ كنيد خروجي آن خواهد بود پس مطمئن باشيد كه HTML معتبري را وارد كرده باشيد.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'هنگامی که یک وب سایت را در صفحه اصلی یک دستگاه تلفن همراه نشانک می کنید، نماد لمسی ظاهر می شود. اینها معمولاً 152 پیکسل هستند.';
$Definition['The user table was not in the import file.'] = 'جدول كاربر در فايل درون ريز نبود.';
$Definition['The Vanilla 2 Exporter'] = 'برون ريز وانيلا 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'آمار وانيلا پيشخوان انجمن شما را به يك ابزار گزارش تجزيه و تحليل تبديل ميكند، به شما اجازه ميدهد تا فعاليت انجمن خود را در مدت زمان هاي خاصي بررسي نماييد. شما ميتوانيد <a href="http://vanillaforums.org/docs/vanillastatistics"> درباره آمار وانيلا بيشتر بدانيد </a> در مستندات ما.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'آنها درست مانند تم های منظم کار می کنند. هنگامی که یکی به پوشه مضامین اضافه شد ، می توانید آن را در اینجا فعال کنید.';
$Definition['This is a style guide of your theme.'] = 'این یک راهنمای سبک از موضوع شماست. این نمونه هایی از عناصر بصری است که در طول برنامه استفاده می شود. می توانید بر روی ابزارکهای مختلف مانند نوار عنوان <0> کلیک کنید </0> یا <1> بنر </1> برای ویرایش خصوصیات آنها در صفحه جانبی.';
$Definition['This is the administrative dashboard for your new community.'] = 'اين پيشخوان مديريتي براي انجمن جديد شما ميباشد. گزينه هاي پيكربندي را در گوشه بررسي نماييد. از آنجا شما ميتوانيد چگونگي كاركرد انجمن خود را پيكربندي كنيد.<b> بصورت پيش فرض، تنها كاربران با نقش "مدير" ميتوانند اين بخش انجمن شما را مشاهده كنند.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'اینجاست که می توانید ویژگی ها ، صفحات و اجزای جدید وانیل را فعال و آزمایش کنید.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'این آزمایشگاه را نمی توان غیرفعال کرد زیرا یک طرح بندی سفارشی اعمال شده است.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'این آزمایشگاه را نمی توان غیرفعال کرد زیرا توسط موضوع فعلی مورد نیاز است.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'این لوگو در بالای سایت شما ظاهر می شود. طرح‌های زمینه ساخته شده با ویرایشگر طرح زمینه و برخی از طرح‌های زمینه سفارشی از این تنظیم استفاده نمی‌کنند.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'این ممکن است برای درج محتوایی مانند نام و آدرس سازمان در همه ایمیل‌های ارسالی استفاده شود.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'اين گزينه مكان هايي را كه بسته ها به آنجا ميروند را نمايش/ عدم نمايش ميدهد، ولي فقط براي كاربراني كه مجوز اضافه/ ويرايش كردن بسته ها را دارند. سعي كرده مكان هاي بسته را نمايش داده سپس از انجمن بازديد كنيد.';
$Definition['This page lists the endpoints of your API.'] = 'این صفحه نقاط پایانی API شما را لیست می کند. برای اطلاعات بیشتر روی نقاط پایانی کلیک کنید. می توانید از این صفحه یا از طریق خارج از کشور با استفاده از یک نشانه دسترسی تماس های زنده به API برقرار کنید.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'این نقش اطلاعات شخصی است. فقط کاربرانی که اجازه مشاهده اطلاعات شخصی را دارند ، آن را مشاهده می کنند.';
$Definition['This setting loads the page before executing Javascript.'] = 'این تنظیمات قبل از اجرای Javascript می تواند صفحه بارگیری کند که می تواند سئوی شما را بهبود بخشد. <br> <strong>** هشدار: فعال کردن این ویژگی ممکن است باعث ایجاد خطاهای Javascript در سایت شما شود. **</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'این تنظیم صفحه را قبل از اجرای جاوا اسکریپت بارگیری می کند که می تواند سئوی شما را بهبود بخشد.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'این موضوع حذف نمی شود زیرا این موضوع در حال حاضر کاربردی است.';
$Definition['Tiled Layout'] = 'چیدمان کاشی کاری شده';
$Definition['Title Bar'] = 'نوار عنوان';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'براي درج انجمن وانيلا در وبسايت خود، از كد زير استفاده كنيد.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'تعداد زيادي آدرس ! ما %s آدرس را در هربار ارسال ميكنيم.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'براي جلوگيري از سوءاستفاده، برخي ابزارها بصورت خودكار محتوا را مخفي كرده و در اينجا ليست ميكند تا زماني كه بصورت دستي توسط مدير تائيد شود.';
$Definition['TouchIconDescription'] = 'نماد لمسی هنگامی که یک وب سایت را در صفحه اصلی یک دستگاه اپل علامت گذاری می کنید ظاهر می شود. اینها معمولاً 152 پیکسل هستند. اپل گوشه های گرد و نورپردازی را به صورت خودکار اضافه می کند.';
$Definition['Transparent'] = 'شفاف';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'اتصال توئيتر به كاربران اين اجازه را ميدهد تا توسط حساب كاربري توئيتر خود استفاده كرده و وارد انجمن شوند.<b> براي اينكه اين پلاگين جواب دهد بايد اپليكيشن خود را با توئيتر ثبت كنيد.</b>';

$Definition['Usercards'] = 'کارت های کاربر';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'کارت‌های کاربری به شما این امکان را می‌دهند که یک عکس فوری سریع از اطلاعات کاربر دریافت کنید. هنگام مشاهده پست‌ها و تابلوهای امتیازات، روی نام کاربری کلیک کنید تا کارتی را ببینید که اطلاعات اولیه نمایه کاربران را بدون نیاز به دور شدن از صفحه نمایش می‌دهد. این ویژگی را فعال کنید تا کارت های کاربری را به تم سفارشی خود اضافه کنید.';
$Definition['User inputs are based on the global background and text colors.'] = 'ورودی های کاربر مبتنی بر پس زمینه جهانی و رنگ متن است.';
$Definition['User Profile'] = 'مشخصات کاربر';
$Definition['Users may sign into your site using their Twitter account.'] = 'کاربران ممکن است با استفاده از حساب توییتر خود وارد سایت شما شوند.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'برای ایجاد یک قانون ممنوعیت از دکمه در بالای صفحه استفاده کنید.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'از پلاگين ورودپرس براي راه اندازي ديدگاه وانيلا در وبلاگ خود استفاده كنيد، يا اينكه از كد عمومي استفاده كرده تا ديدگاه وانيلا را بر روي هر پلتفرم ديگري راه اندازي كنيد.';

$Definition['Vanilla\'s new search service is finally here.'] = 'سرویس جستجوی جدید Vanilla بالاخره آمد. برای دسترسی به جدیدترین ویژگی‌های جستجو مانند جستجوی اعضا، مرتب‌سازی جستجو و برجسته‌سازی عبارت، رابط کاربری صفحه جستجوی جدید ما را فعال کنید.';
$Definition['Vanilla Export: %s, Source: %s'] = 'برون ريز وانيلا: %s، منبع: %s';
$Definition['Vanilla Labs'] = 'آزمایشگاه های وانیلی';
$Definition['Vanilla Statistics are currently disabled'] = 'آمار وانيلا درحال حاضر غيرفعال ميباشد';
$Definition['Verify and restore'] = 'تأیید و بازیابی';
$Definition['VerifyUser'] = 'کادر کنار کاربر را علامت بزنید تا آنها را به عنوان <b>Verified</b> علامت گذاری کنید تا پست های آنها دوباره به عنوان هرزنامه علامت گذاری نشوند. با این کار همه پست های معلق آنها بازگردانده می شود.';
$Definition['Video tutorial on advanced settings'] = 'آموزش تصويري براي تنظيمات پيشرفته';
$Definition['Video tutorial on finding &amp; managing users'] = 'آموزش تصويري براي يافتن & مديريت كاربران';
$Definition['Video tutorial on managing appearance'] = 'آموزش تصويري براي مديريت ظاهر';
$Definition['Video tutorial on managing categories'] = 'آموزش تصويري براي مديريت دسته بندي';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'آموزش تصويري براي مديريت نقش & مجوزها';
$Definition['Video tutorial on user registration'] = 'آموزش تصويري براي ثبت نام كاربر';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'هشدار: فعال کردن این ویژگی ممکن است باعث ایجاد خطاهای Javascript در سایت شما شود.';
$Definition['Warning: Loading tables can be slow.'] = '<b>هشدار</b> : پیکربندی سرور شما از بارگیری سریع داده پشتیبانی نمی کند. اگر در حال وارد کردن پرونده ای بسیار بزرگ هستید (مثلاً بیش از 200000 نظر) ممکن است بخواهید پیکربندی خود را تغییر دهید. برای اطلاعات بیشتر <a href="http://vanillaforums.com/porter">اینجا را</a> کلیک <a href="http://vanillaforums.com/porter">کنید</a>';
$Definition['Warning: This is for advanced users.'] = '<b>هشدار</b> : اين تنظيمات براي كاربران حرفه اي ميباشد و نيازمند اين است كه يكسري تغييرات در سرويس دهنده وب خود اعمال كنيد. اين تنظيمات معمولا براي اين است كه اگر شما ميزبان اختصاصي و يا VPS داشته باشيد. اگر نميدانيد كه داريد چه كاري ميكنيد سعي نكنيد اينها را تغيير دهيد.';
$Definition['Webhooks'] = 'قلاب های وب';
$Definition['Welcome to Labs!'] = 'به آزمایشگاه ها خوش آمدید!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'به رابط کاربری قالب Vanilla خوش آمدید. این صفحه همه تم های موجود شما را فهرست می کند و به شما امکان می دهد آنها را کپی یا ویرایش کنید.';
$Definition['Welcome To Your Theme'] = 'به موضوع شما خوش آمديد';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'ما اکیداً برای تشویق مشارکت واکنشهای مثبت پیشنهاد می کنیم.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'وقتی فعال باشد، کاربران ممکن است انتخاب کنند که اعلان‌هایی از انجمن دریافت کنند';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'در صورت فعال بودن ، می توانید محصولات و گروه های فرعی را توسط این محصولات مدیریت کنید.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'هنگامی که شخصی پیوندی را از سایت شما به اشتراک می گذارد، ما سعی می کنیم تصویری را از صفحه بگیریم. اگر تصویری در صفحه وجود ندارد، به جای آن از این تصویر استفاده می کنیم. تصویر باید حداقل 50×50 باشد، اما ما 200×200 را توصیه می کنیم.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'وقتی Full Bleed را انتخاب می کنید ، پس زمینه شما شفاف است.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'آیا فیلدهای نمایه داخلی در این وب هوک گنجانده می شود یا خیر.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'آیا فیلدهای نمایه خصوصی در این وب هوک گنجانده می شود یا خیر.';
$Definition['Which reactions you use really depends on your community.'] = 'کدام واکنش هایی که استفاده می کنید به جامعه شما بستگی دارد ، اما توصیه می کنیم چند نکته را در خاطر داشته باشید.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'شما در حال اعمال یک گزینه طرح بندی جدید هستید. این را می توان با استفاده از ویرایشگر تم ما سفارشی و پیش نمایش کرد. <0> بیشتر بیاموزید</0> به';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'می توانید با اضافه کردن یک ممنوعیت از نوع IP با مقدار "111.111.111. *" ، همه کاربران را با آدرس IP پیش شماره "111.111.111" ممنوع کنید.';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'می توانید آدرس های IP ، آدرس های ایمیل و نام کاربری را ممنوع کنید.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'می توانید یکی از سبک های مختلفی که این موضوع ارائه می دهد را انتخاب کنید.';
$Definition['You can configure some values differently for different screensizes.'] = 'می توانید مقادیر مختلف را برای صفحه های مختلف پیکربندی کنید.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'شما ميتوانيد با چندين سايتي كه jsConnect را پشتيباني كنند متصل شويد.';
$Definition['You can place files in your /uploads folder.'] = 'اگر فايل شما براي آپلود مستقيم به اين صفحه بسيار حجيم ميباشد ميتوانيد فايل خود را در پوشه /uploads قرار دهيد. مطمئن باشيد كه نام فايل شما با كلمه <b>export</b> شروع شده و با يكي از فرمتهاي <b>.txt, .gz</b> باشد.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'برای دلسردی از پست های کوتاه می توانید حداقل طول ارسال را تعیین کنید.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'می توانید یک قلم سفارشی را در سیستم Theming خود بارگذاری کنید. فقط URL را در قسمت کپی و چسباندن کنید.';
$Definition['You must select a file to import.'] = 'براي درون ريزي بايد يك فايلي را انتخاب كنيد.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'شما باید دامنه آدرس فونت را به <0> دامنه مجاز اضافه کنید </0> در پیکربندی سایت <1> در مورد قلم های سفارشی بیشتر بدانید. </1>';
$Definition['Your mobile theme will be disabled.'] = 'موضوع تلفن همراه شما غیرفعال خواهد شد. برای تنظیم تم های مختلف موبایل و دسک تاپ ، از UI theming قدیمی استفاده کنید.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'نام سازمان شما برای microdata SEO و JSON+LD استفاده می شود';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'مورد علاقه سایت شما در نوار عنوان مرورگر شما نمایان می شود. آن را به طور مناسب کاهش می یابد.';
