<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '** تحذير: قد يؤدي تمكين هذه الميزة إلى حدوث أخطاء جافا سكريبت على موقعك. **';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>تنبيه!</strong> حذف الصلاحية قد يؤدي إلى عدم قدرة المستخدمين على الدخول للبرنامج.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>تنبيه!</strong> نقل المواضيع إلى أقسام أخرى قد يسبب إختفاء أو (ظهور) تلك المواضيع على حسب إعدادات تلك الأقسام.';

$Definition['About.DisableStatistics'] = 'إن كان عليك تعطيل خاصية تقارير البيانات لأي سبب فيمكنك القيام بذلك عن طريق إضافة الكود التالي لملف الإعدادات configuration: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'إنه من الضروري لضمان إستمرارية ومستقبل هذا البرنامج المجاني مفتوح المصدر أن نتمكن من القياس بدقة مدى إنتشار وفاعلية فانيلا. نرجوا منك عدم تعطيل خاصية إرسال تقارير بيانات التشغيل.';
$Definition['AboutCommentEmbedding'] = 'يمكن إستخدام فانيلا كبديل جاهز لنظام التعليقات في مدونتك. في الحقيقة يمكن إستخدامه لإضافة التعليقات لأي صفحة على الشبكة.';
$Definition['AboutEmbedding'] = 'الغرس Embedding يسمح بغرس جزء أو كل برنامج فانيلا في برامج أو صفحات أخرى.';
$Definition['About Vanilla Statistics'] = 'عن احصاءات الفانيلا';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'قم بدخول المنتدى عن طريق الضغط على رابط "زيارة الموقع" في الأعلى في هذه الصفحة أو  <a href={/,url}>بالضغط هنا</a>. المنتدى سيراه كل من أعضاؤك وعملاؤك عندما يزورون الرابط <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'أضف حدوداً لأبعاد تحميل الصور في المناقشات والتعليقات. ';
$Definition['AddonProblems'] = '<h2>مشاكل؟</h2><p> إذا حدث خلل مع أحد الإضافات وتعذر عليك إستخدام الموقع فيمكنك تعطيلها يدويا بتحرير:</p> %s';
$Definition['AddressBarColorDescription'] = 'تدعم بعض المتصفحات لونًا لشريط العناوين. للجوال فقط.';
$Definition['Alert users if they click external link.'] = 'تنبيه المستخدمين إذا قاموا بالنقر فوق ارتباط في منشور سيقودهم بعيدًا عن المنتدى. لن يتم تحذير المستخدمين عند اتباع الروابط التي تتطابق مع المجال الموثوق';
$Definition['Alignment'] = 'انتقام';
$Definition['Alignment (Mobile)'] = 'المحاذاة (الجوال)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'كل الأقسام المختارة مع عرض 5 مواضيع حديثة تحت كل منها';
$Definition['Allow links to be transformed'] = 'السماح بتحويل الروابط إلى تمثيلات مضمنة في المناقشات والتعليقات. على سبيل المثال ، سيتم تحويل رابط YouTube إلى فيديو مضمن.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'السماح للمستخدمين الذين لديهم إذن %s بتغيير الصور الرمزية الخاصة بهم من صفحات ملفاتهم الشخصية في Vanilla.';
$Definition['Anonymize IP Addresses'] = 'إخفاء هوية عناوين IP';
$Definition['ApplicationHelp'] = 'التطبيقات تسمح لك بإضافة مجموعة كبيرة من الإمكانيات للموقع.<br>عند إضافة تطبيق إلى ملف %s ، يمكنك تنشيطه أو تعطيله هنا.';
$Definition['Apply Layout'] = 'تطبيق التخطيط';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'هل تريد بالتأكيد حذف هذا الموضوع؟ سيتم حذفه نهائيًا.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'هل أنت متأكد من أنك أدخلت اسم مضيف قاعدة البيانات الصحيح؟ ربما أخطأت في الكتابة؟ ذكرت قاعدة البيانات: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'يجب إضافة مجموعة "غير مفعل" كمجموعة افتراضية كي تستخدم لتفعيل البريد الإلكتروني.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'حفظ مسودات المناقشات والأسئلة والأفكار والتعليقات غير المنشورة تلقائيًا.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'سيتم تصغير الصور الرمزية إذا تجاوزت هذا الارتفاع.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'سيتم تصغير الصور الرمزية إذا تجاوزت هذا العرض.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'سيتم حفظ الصور المصغرة الخاصة بهم في هذا الحجم.';

$Definition['Background'] = 'خلفية';
$Definition['Background Image'] = 'الصورة الخلفية';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'كن مبدعا! حاول تسمية درجاتك بعد الأشياء التي يتحدث عنها المجتمع.';
$Definition['Bordered'] = 'يحدها';
$Definition['Bordered (Unified)'] = 'يحدها (موحد)';
$Definition['Borderless'] = 'بلا حدود';
$Definition['Border Radius'] = 'نصف قطر الحدود';
$Definition['Brand Color'] = 'لون العلامة التجارية';
$Definition['Buttons'] = 'أزرار';
$Definition['Buttons & Inputs'] = 'الأزرار والمدخلات';
$Definition['Button Type'] = 'نوع الزر';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'بالنقر فوق الزر أدناه، ستقوم بحذف حساب المستخدم لـ %s إلى الأبد.';

$Definition['Center Aligned'] = 'محاذاة إلى الوسط';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'ستنطبق التغييرات على الصور الرمزية التي تم تحميلها حديثًا فقط.';
$Definition['Change the sizes that avatar images are saved at.'] = 'تغيير الأحجام التي يتم حفظ الصور الرمزية بها.';
$Definition['Change the way your community works with plugins.'] = 'قم بتغيير الطريقة التي يعمل بها مجتمعك بواسطة الملحقات. لقد قمنا بتجميع ملحقات شهيرة مع البرنامج، وهناك المزيد من البرامج المتوفرة عبر الإنترنت.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'تسمح مربعات الاختيار للمشرفين بتنفيذ إجراءات مجمعة على عدد من المناقشات أو التعليقات في نفس الوقت.';
$Definition['Check out our %s'] = 'تحقق من %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'تحقق من وثائقنا <0></0> ، أو اسأل <1> مجتمع الخبراء لدينا</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'إنّ Vanilla هي أبسط وأقوى منصة مجتمعية في العالم. إن استخدامها فائق السهولة. ابدأ بهذا الفيديو التمهيدي وتابع الخطوات التالية. استمتع!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'اختر مجموعة يضم لها الأعضاء الذين بلا مجموعة:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'اختر موضوعًا لهذه الفئة الفرعية. <0> اقرأ المزيد </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'اختر كيفية معالجة كل المحتوى المرتبط بحساب المستخدم لـ %s (التعليقات والرسائل وما إلى ذلك).';
$Definition['Choose Image'] = 'اختر صورة';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'يمكنك تحديد خوارزمية تجزئة مخصصة لتوقيع طلباتك. يجب أيضًا استخدام خوارزمية التجزئة في مكتبة العميل الخاصة بك. اختر md5 إذا لم تكن متأكدًا مما يجب أن تختار.';
$Definition['Choose the order items are sorted.'] = 'اختر ترتيب العناصر مرتبة.';
$Definition['Choose the page people should see when they visit <0/>'] = 'اختر الصفحة التي يجب أن يراها الأشخاص عند زيارتهم <0 />';
$Definition['Choose the preferred layout for lists of categories.'] = 'اختر التنسيق المفضل لقوائم الفئات.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'اختر التخطيط المفضل لقوائم الفئات. يمكنك تحرير تخطيط التجانب.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'اختر التنسيق المفضل لقوائم المناقشات.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'اختر التخطيط المفضل لقوائم المناقشات. يمكنك تحرير تخطيط الأساس.';
$Definition['Color Overlay'] = 'تراكيب الالوان';
$Definition['Continue Import'] = 'متابعة الاستيراد';
$Definition['Could not parse import file. The problem is near line %s.'] = 'تعذّر تحليل ملف الاستيراد. المشكلة قريبة من السطر رقم %s.';
$Definition['Create a localization CSV'] = 'إنشاء ملف تعريب CSV';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'السمات المخصصة هي السمات التي أنشأتها. يمكنك تحريرها أو إعادة تسميتها أو عمل نسخة منها.';

$Definition['Dark'] = 'داكن';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'حدّد من يمكنه تحميل وإدارة الملفات في صفحة <a href="%s">الأدوار والأذونات</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'حدّد الصفحة الرئيسية للمنتدى الخاص بك، وحمّل شعارك، وأكثر...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'يمكن أن يؤدي حذف دور ما إلى عدم تمكن المستخدمين من الوصول إلى التطبيق.';
$Definition['Deleting forever cannot be undone.'] = 'يُعد الحذف طريقة جيدة للحفاظ على نظافة منتداك.';
$Definition['Disable Google Sign In'] = 'تعطيل تسجيل دخول Google';
$Definition['Disable OpenID'] = 'تعطيل OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'قم بتعطيل معمل "نظام تضمين جديد" في صفحة Vanilla Labs <0></0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'تُستخدم فئات المناقشة لمساعدة المستخدمين على تنظيم مناقشاتهم بطريقة مفيدة لمجتمعك.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'لا تقم بتضمين لوحة تحكم مشرف المنتدى (قم بإظهارها في وضع ملء الشاشة)';
$Definition['Don\'t use too many reactions.'] = 'لا تستخدم ردود فعل كثيرة. أنت لا تريد أن تزود المستخدمين بمعلومات زائدة.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'قم بسحب وإسقاط الفئات أدناه لفرزها وتداخلها.';

$Definition['EditContentTimeout.Notes'] = 'إذا كان للمستخدم دوراً يعطيه الإذن بتحرير المحتوى، فستتجاوز هذه الأذونات ذلك.';
$Definition['Edit Route'] = 'تحرير المسار';
$Definition['Edits to this theme apply to:'] = 'تنطبق تعديلات هذا المظهر على:';
$Definition['Embed Settings'] = 'إعدادات التضمين';
$Definition['Embed your community forum into your website to increase engagement...'] = 'قم بتضمين منتدى مجتمعك في موقع الويب الخاص بك لزيادة المشاركة ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'قم بتمكين واختبار أحدث ميزات Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'تمكين التحرير المتقدم للمشاركات بعدة تنسيقات ، بما في ذلك WYSIWYG و HTML البسيط و Markdown و BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'قم بتمكين محرر التخطيط لتطبيق تخطيط مخصص لصفحات المجتمع الخاصة بك. استخدم محررنا الجديد لتمييز المحتوى باستخدام كتالوج عناصر واجهة المستخدم المتاحة لدينا.';
$Definition['Enter a descriptive name.'] = 'أدخل اسماً وصفياً للجيب. لن يظهر هذا الاسم في أي مكان إلا عند إدارة جيوبك هنا، لذا فهو يستخدم فقط لمساعدتك على تذكر الجيب.';
$Definition['Enter a short name for the site.'] = 'أدخل اسماً قصيراً للموقع. يتم عرض هذا على أزرار تسجيل الدخول.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'أدخل عنوان مدونة Wordpress الخاصة بك وسنتولى الأمر من هناك.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'أدخل إعدادات الاتصال لخادم أبو الهول الخاص بك أدناه.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'يتم تسجيل كل تحرير أو حذف هنا. استخدم ‘استعادة’ للتراجع عن أي تغيير.';
$Definition['Everyone who signs up gets a profile page.'] = 'يحصل كل من اشترك في مجتمعك على صفحة ملف شخصي عام حيث يمكنه تحميل صورة لنفسه ، وإدارة إعدادات ملفه الشخصي ، وتتبع الأشياء الرائعة في المنتدى. يجب 
<a href="{/profile,url}">تخصيص الملف الشخصي الان</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'يتم تعيين كل مستخدم في موقعك لدور واحد على الأقل. تستخدم الأدوار لتحديد ما يسمح للمستخدمين القيام به.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'يتيح Facebook Connect للمستخدمين تسجيل الدخول باستخدام حساب Facebook الخاص بهم. <b> يجب عليك تسجيل طلبك في Facebook حتى يعمل هذا الملحق. </b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'أخفق الاتصال بقاعدة البيانات باستخدام اسم المستخدم وكلمة المرور اللذين أدخلتهما. هل كتبتهما بشكل خاطئ؟ ذكرت قاعدة البيانات: <code>%s</code>';
$Definition['Font'] = 'الخط';
$Definition['Font Name'] = 'اسم الخط';
$Definition['Font URL'] = 'URL الخط';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'قم بإجبار لوحة التحكم على الوصول إليها فقط من خلال عنوان url <em> (غير مستحسن) </em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'على سبيل المثال، يمكنك حظر جميع المستخدمين بعناوين البريد الإلكتروني من "example.com" عن طريق إضافة حظر من نوع البريد الإلكتروني مع القيمة "*@example.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'لأغراض تحسين محركات البحث (SEO)، يتم استبعاد برامج زحف محركات البحث من إجبارها على عرض المنتدى في عنوان رابط URL البعيد.';
$Definition['Foundation Layout'] = 'تخطيط الأساس';
$Definition['Full Anonymization'] = 'إخفاء الهوية الكامل';
$Definition['FullAnonymization.Description'] = 'يستبدل <strong>إخفاء الهوية الكامل</strong> كل عنوان IP فردي بـ 0.0.0.0 مما يحرم التطبيق بشكل فعال من أي وصول للعمل مع عناوين IP. لن تعمل قواعد حظر IP على الإطلاق في هذه الحالة.';
$Definition['Full Bleed'] = 'نزيف حاد';

$Definition['Garden.Import.Complete.Description'] = 'لقد أكملت عملية الاستيراد بنجاح.
    انقر على <b>انتهى</b> عندما تكون مستعداً.';
$Definition['Garden.Import.Continue.Description'] = 'يبدو كما لو كنت في منتصف عملية استيراد. الرجاء اختيار واحد من الخيارات التالية.';
$Definition['Garden.Import.InputInstructions'] = 'أدخل البريد الإلكتروني وكلمة المرور للمستخدم المسؤول من البيانات التي يتم استيرادها.';
$Definition['Garden.Privacy.IPs.Description'] = 'عادةً ما يتم جمع عناوين IP الخاصة بالمستخدم لأغراض قواعد الحظر الآلي والإشراف ومنع البريد العشوائي. سيؤدي تمكين إخفاء هوية IP إلى إخفاء هوية جميع عناوين IP التي يتم تتبعها في الموقع لأي غرض، وسيقلل من فعالية هذه الأدوات. التغييرات في هذا الإعداد ليست بأثر رجعي.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit إذن لتغيير الصور الرمزية الخاصة بهم من صفحات ملفاتهم الشخصية في فانيلا.';
$Definition['Garden.StatisticsDisabled'] = 'لقد قمت بشكل خاص بتعطيل إحصائيات Vanilla في ملف التهيئة الخاص بك.';
$Definition['Garden.StatisticsLocal.Explain'] = 'يبدو أن هذا المنتدى يعمل في بيئة اختبارية، أو أنه يقوم بالإبلاغ عن عنوان IP خاص. افتراضياً، لا يتم تعقب المنتديات التي تعمل على عنوان IP خاص.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'إذا كنت متأكداً من أن منتداك يسهل الوصول إليه عبر الإنترنت، فيمكنك إجباره على الإبلاغ عن الإحصاءات هنا:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'يبدو أن ملف config.php الخاص بك للقراءة فقط. هذا يعني أن Vanilla لن تتمكن من تسجيل InstallationID و InstallationSecret في منتداك تلقائياً.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'لحل هذه المشكلة، قم بتعيين وضع الملف 777 إلى ملف conf/config.php.';
$Definition['Global Styles'] = 'الأنماط العالمية';

$Definition['Heads Up!'] = 'انتباه! ';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'انتباه! هذا دور خاص والذي لا يسمح بجلسات نشطة. لهذا السبب، اقتصرت خيارات الأذونات على أذونات "العرض".';
$Definition['Here are all of the reactions you can use on your site.'] = 'إليك كل ردود الفعل التي يمكنك استخدامها على موقعك.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'فيما يلي الرتب التي يمكن للمستخدمين تحقيقها على موقعك. يمكنك تخصيص هذه الرتب وحتى إضافة رتب جديدة. هنا بعض النصائح.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'إذا تم تحميل شعار لافتة ما، فسوف يستبدل عنوان اللافتة في صفحات المنتدى التي تواجه المستخدم.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'إذا لم يقم المستخدم بزيارة الموقع خلال هذه الفترة الزمنية ، فسيتم تسجيل خروجه تلقائيًا.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'في حالة التمكين ، سيتم إرسال المحتوى الكامل للمشاركات في إشعارات بالبريد الإلكتروني إلى المستخدمين.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'إذا كنت مستخدمًا جديدًا لـ HTML و / أو CSS ، فإليك بعض البرامج التعليمية لتبدأ:';
$Definition['If you have an old theme'] = 'إذا كان لديك مظهر قديم وتحتاج إلى تعيين مظهر منفصل لسطح المكتب والجوال ، فيمكنك القيام بذلك باستخدام واجهة المستخدم القديمة.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'إذا كنت ترغب في خفض مستوى التحذير، فقم بإزالة تحذير.';
$Definition['If you want to embed your forum, enable embedding.'] = 'إذا كنت ترغب في تضمين منتداك أو استخدام تعليقات Vanilla في مدونتك ، فأنت بحاجة إلى تمكين التضمين. إذا كنت لا تستخدم التضمين ، فنوصيك بإيقاف هذا الإعداد.';
$Definition['Image (Mobile)'] = 'صورة (جوال)';
$Definition['Import'] = 'استيراد';
$Definition['Importing to Vanilla'] = 'استيراد إلى Vanilla';
$Definition['In additon to the widgets there are also'] = 'بالإضافة إلى الأدوات ، هناك أيضًا <0> أنماط عالمية </0> . لتحرير الأنماط العامة ، انقر في أي مكان آخر على الصفحة ، مثل هذا النص.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'ادمج صفحات التأسيس والمكونات في الموضوع الخاص بك';
$Definition['Internationalization & Localization'] = 'التدويل والترجمة';
$Definition['Invalid URL'] = 'URL غير صالح';
$Definition['Invitation email failed to send: %'] = 'على الرغم من إنشاء الدعوة بنجاح ، فشل إرسال البريد الإلكتروني. أبلغ الخادم عن الخطأ التالي: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'عندما تستخدم التسجيل عن طريق الدعوة، سيكون لدى المستخدمين رابط يسمى <a href="%s" class="Popup">دعواتي</a> على صفحات ملفهم الشخصي.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'يبدو كما لو أن قاعدة البيانات التي حددتها غير موجودة حتى الآن. هل قمت بإنشائه بعد؟ هل أخطأت في كتابة الاسم؟ ذكرت قاعدة البيانات: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'من المستحسن الاحتفاظ بالحد الأقصى لعدد الأحرف المسموح بها في التعليق بحجم معقول.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'من الجيد الاحتفاظ بالحد الأقصى لعدد الأحرف المسموح به في المنشور إلى حجم معقول.';

$Definition['Kick-start your community and increase user engagement.'] = 'ابدأ بإطلاق مجتمعك وزيادة مشاركة المستخدمين.';

$Definition['Labs'] = 'مختبرات';
$Definition['Layout Editor'] = 'مصمم تخطيط';
$Definition['Learn about custom routing.'] = 'تعرف على التوجيه المخصص';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'تعرّف على كيفية تغيير شكل وطابع المنتدى الخاص بك تماماً: قم بتحميل شعارك وتعيين صفحتك الرئيسية واختيار مظهر ما وتخصيصه.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'تعرف على كيفية استخدام الوظائف الأساسية لمنتداك.';
$Definition['Left Aligned'] = 'تمت محاذاة اليسار';
$Definition['Light'] = 'ضوء';
$Definition['Links'] = 'الروابط';
$Definition['Locales allow you to support other languages on your site.'] = 'تتيح لك اللغات المحلية دعم لغات أخرى على موقعك. تمكين وتعطيل اللغات التي تريد إتاحتها هنا.';
$Definition['Lockout Time (seconds)'] = 'وقت الإغلاق (بالثواني)';
$Definition['LogoDescription'] = 'يظهر شعار البانر أعلى موقعك.';
$Definition['LogoDisclaimer'] = 'السمات التي تم إنشاؤها باستخدام محرر السمات وبعض السمات المخصصة لا تستخدم هذا الإعداد.';
$Definition['Looking for the Old Embed System?'] = 'هل تبحث عن نظام تضمين قديم؟';

$Definition['Make sure you click View Page'] = 'تأكد من النقر فوق <a href="%s">عرض الصفحة</a> لترى كيف تبدو صفحة الفئات الخاصة بك بعد الحفظ.';
$Definition['Manage Routes'] = 'إدارة المسارات';
$Definition['Managing Users'] = 'إدارة المستخدمين';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'سيؤدي وضع علامة على الأشياء على أنها "ليست" بريداً عشوائياً إلى إعادة وضعها في منتداك.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'سيؤدي وضع علامة على الأشياء على أنها ليست رسائل غير مزعجة إلى إعادة وضعها في المنتدى';
$Definition['Messages can appear anywhere in your application.'] = 'يمكن أن تظهر الرسائل في أي مكان في التطبيق الخاص بك، ويمكن استخدامها لإعلام المستخدمين بالأخبار والأحداث. استخدم هذه الصفحة لإعادة تنظيم رسائلك بسحبها لأعلى أو لأسفل.';
$Definition['MobileLogoDescription'] = 'يظهر شعار بانر الجوال أعلى موقعك.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'تسمح لك مظاهر الجوال بتغيير شكل موقعك وأسلوبه على الأجهزة الصغيرة.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'ملحوظة: سوف يرث محرر التخطيط الجديد السمة المحددة في دليل الأنماط (محرر السمة رسميًا). <1> اكتشف المزيد</1>';
$Definition['Need More Help?'] = 'هل تريد المزيد من المساعدة؟';
$Definition['Need more help?'] = 'هل تريد المزيد من المساعدة؟';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'سيتم وضع الفئات المتداخلة أعمق من هذا العمق في قائمة محددة بفواصل.';
$Definition['New Embed System'] = 'نظام تضمين جديد';
$Definition['New Quick Links'] = 'روابط سريعة جديدة';
$Definition['New Search Page'] = 'صفحة بحث جديدة';
$Definition['No Anonymization'] = 'لا إخفاء الهوية';
$Definition['Not getting what you expect when you preview your theme?'] = 'لا تحصل على ما تتوقعه عند معاينة السمة الخاصة بك؟';
$Definition['Notify me when people comment on my addons.'] = 'أعلمني عندما يقوم الأشخاص بالتعليق على الإضافات الخاصة بي.';
$Definition['No unconfirmed role available for email confirmation.'] = 'يحتاج الموقع إلى دور بنوع افتراضي "غير مؤكد" لاستخدام تأكيد البريد الإلكتروني. الرجاء إضافة واحد لتمكين هذا الإعداد.';

$Definition['Old Theming UI'] = 'واجهة مستخدم Theming القديمة';
$Definition['Once enabled, only members will see inside your community.'] = 'بمجرد التمكين ، سيرى الأعضاء فقط داخل مجتمعك.';
$Definition['OrgDescription'] = 'يتم استخدام اسم مؤسستك لصالح SEO microdata و JSON + LD';
$Definition['Outline'] = 'الخطوط العريضة';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'يمكن أن يكون لوجهات النظر التي تم تجاوزها أو الكتب الصوتية آثارًا جانبية غير مقصودة ولا تتم معاينتها.';

$Definition['Partial Anonymization'] = 'إخفاء الهوية الجزئي';
$Definition['PartialAnonymization.Description'] = 'يؤدي <strong>إخفاء الهوية الجزئي</strong> إلى إخفاء هوية آخر ثماني بتات فقط من عنوان IP. على سبيل المثال ، سيصبح 254.230.05.153 254.230.05.0. يوفر هذا بعض إخفاء الهوية بينما لا يزال يسمح لقواعد حظر IP بالعمل.';
$Definition['Password.MinLength'] = 'الحد الأدنى لطول الأحرف المسموح به لكلمات مرور المستخدمين في صفحات إنشاء وإعادة تعيين كلمة المرور.';
$Definition['Please choose an authenticator to configure.'] = 'يُرجى اختيار مصادق للتهيئة.';
$Definition['PluginHelp'] = 'تسمح لك الإضافات بإضافة وظائف إلى موقعك. <br /> بمجرد إضافة ملحق إلى مجلد %s الخاص بك ، يمكنك تمكينه أو تعطيله هنا.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'يتم عرض الجيب بين كل نقاش حول قائمة المناقشات الرئيسية. حيث أن موضوعات النقاش عادة ما تكون في علامات <li>..</li> ، ستحتاج إلى طيّ جيبك في تلك العلامات أيضاً.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'تسمح لك الجيوب بإضافة قالب HTML حر إلى أماكن متعددة عبر التطبيق.';
$Definition['Preset'] = 'المعد مسبقا';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'امنع البريد المزعج في منتداك عن طريق الحد من عدد المناقشات والمحادثات و& التعليقات التي يمكن للمستخدمين نشرها خلال فترة زمنية محددة.';
$Definition['Primary Button'] = 'الزر الأساسي';
$Definition['Primary Buttons'] = 'الأزرار الأساسية';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'دليل البدء السريع لإنشاء مظاهر لـ Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'الروابط السريعة هي مكون افتراضي في صفحات المجتمع. قم بتمكين مكون الروابط السريعة الجديد الخاص بنا لإضافة أو تعديل أو إخفاء الروابط من هذه القائمة باستخدام محرر السمات الخاص بنا.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'ملحق تعليقات Vanilla جاهز لـ WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'ملحق منتدى Vanilla جاهز لـ WordPress';
$Definition['Realtime progress bars: %s'] = 'أشرطة تقدم الوقت الفعلي: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'إنها لفكرة جيدة أن يكون لديك رتب خاصة للمشرفين والإداريين حتى يتمكن مجتمعك من رؤية المسؤول عن ذلك بسهولة.';
$Definition['Recommend starting with five ranks.'] = 'لا تريد أن يكون لديك الكثير من الرتب. نوصي بالبدء بخمسة. يمكنك إضافة المزيد إذا كان مجتمعك كبيرًا حقًا.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'إزالة روابط المناقشة والفئات من القوائم. قم بتعيين صفحات المناقشة والفئة ذات الصلة لإرجاع صفحة غير موجودة 404.';
$Definition['Requires “Flag” reaction permission.'] = 'يتطلب إذن رد فعل "الإبلاغ".';
$Definition['Requires “Negative” reaction permission.'] = 'يتطلب إذن رد فعل "سلبي".';
$Definition['Requires “Positive” reaction permission.'] = 'يتطلب إذن رد فعل "إيجابي".';
$Definition['Restoring your selection removes the items from this list.'] = 'عندما تقوم بالاستعادة، تتم إزالة العناصر من هذه القائمة وإعادتها إلى الموقع.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'استخدم الخيار التالي لتمكين علامات الاقتباس لـ "Rich Editor". سيتم تطبيق هذا فقط إذا كان المنسق الافتراضي هو "Rich".';
$Definition['Route Expression'] = 'إيضاح المسار';
$Definition['Routes are used to redirect users.'] = 'تُستخدم المسارات لإعادة توجيه المستخدمين بناءً على عنوان URL المطلوب.
';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'ابحث عن المستخدمين بالاسم أو أدخل اسم الدور لرؤية جميع المستخدمين الذين لديهم هذا الدور.';
$Definition['Secondary Button'] = 'الزر الثانوي';
$Definition['Secondary Buttons'] = 'الأزرار الثانوية';
$Definition['Security.Hsts.HTTPSWarning'] = 'تحذير: قم بتمكين هذه الميزة فقط إذا كنت متأكداً من أن جميع مجالاتك الفرعية مهيئة لـ HTTPS مع شهادات صالحة.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'عند التمكين فستنطبق هذه القاعدة على جميع المجالات الفرعية لموقعك كذلك.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'نوصي بالبدء بعمرٍ يبلغ أسبوعاً 1 كحد أقصى ثم زيادته إلى شهرٍ 1 ثم سنة 1 بمجرد رؤية أن موقعك يعمل كما هو متوقع.';
$Definition['Security.Hsts.SubmitWarning'] = 'تحذير: من الرائع دعم التحميل المسبق HSTS كأفضل ممارسة، ومع ذلك يجب عليك إرسال موقعك إلى hstspreload.org لضمان تحميله مسبقاً بنجاح (أي للحصول على الحماية الكاملة للتهيئة المقصودة).';
$Definition['See the documentation'] = 'انظر التوثيق';
$Definition['Select the default type for this role, if any.'] = 'حدد النوع الافتراضي لهذا الدور ، إن وجد.';
$Definition['Select the import source'] = 'حدد مصدر الاستيراد';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'فشل العمود المتسلسل "%s" في أن يكون غير متسلسل.';
$Definition['Session Timeout'] = 'مهلة جلسة';
$Definition['Shadowed'] = 'مظلل';
$Definition['ShareImageDescription'] = 'عندما يشارك شخص ما رابطًا من موقعك ، نحاول التقاط صورة من الصفحة. إذا لم تكن هناك صورة على الصفحة ، فسنستخدم هذه الصورة بدلاً من ذلك. يجب أن تكون الصورة 50 × 50 على الأقل ، لكننا نوصي 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'قم بتشغيل هذا الخيار لإظهار جميع مواقع الجيب الممكنة. يؤدي تشغيل هذا الخيار إلى إظهار المواقع للمستخدمين الذين يمكنهم إدارة الجيوب فقط.';
$Definition['SignIn.LockoutTime'] = 'مقدار الوقت الذي يُمنع فيه المستخدم من تسجيل الدخول بعد تجاوز عدد محاولات تسجيل الدخول.';
$Definition['Solid'] = 'صلب';
$Definition['Some browsers support a color for the address bar.'] = 'تدعم بعض المتصفحات لونًا لشريط العناوين.';
$Definition['Some older themes don\'t support full editing capability.'] = 'بعض السمات القديمة لا تدعم إمكانية التحرير الكاملة. لمعرفة ما يدعمه النسق ، يمكنك التمرير فوق اسمه لمعرفة مكان سريان التعديلات.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'قد تحتاج إلى تحديث بعض السمات للعمل مع الفئة التالية. يمكنك تعطيل الميزة أثناء تحديث السمة الخاصة بك.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'في بعض الأحيان تريد تضمين موقع Vanilla الخاص بك داخل موقع آخر. يوفر نظام تضمين Vanilla طريقة سهلة لذلك. هناك مقايضات في الأداء عند استخدام موقع مضمن ، لذا تحقق من الوثائق للبدائل وحالات الاستخدام المثالية.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'قيود خاصة: يمكن فقط للمستخدمين الذين لديهم إذن Garden.Curation.Manage استخدام هذا التفاعل.';
$Definition['Specify a partial or full match when creating a ban.'] = 'حدد مطابقة جزئية أو كاملة عند إنشاء حظر.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'خذ بضع دقائق من وقتك في التفكير في كيفية وصف موقعك هنا. يمكن أن يساعدك إعطاء عنوان ذي مغزى ووصف موجز لموقعك في محركات البحث.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'التنوب رسائل البريد الإلكتروني الخاصة بك عن طريق إضافة شعار وتخصيص الألوان.';
$Definition['Start Import'] = 'بدء الاستيراد';
$Definition['Start the first discussion.'] = 'الحصول على الكرة المتداول في مجتمعك من قبل<a href="{/post/discussion,url}">بدء المناقشة الأولى</a>الآن.';
$Definition['Subcommunities'] = 'المجتمعات الفرعية';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'يسمح وضع العلامات للمستخدمين بإضافة علامة إلى المناقشات التي يبدأونها لجعلهم أكثر قابلية للاكتشاف.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'القوالب هي المواضيع القياسية. لتخصيصها ، يجب عليك إنشاء نسخة.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'ليس لدى مصادق %s أي خيارات تهيئة مخصصة.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'ملحوظة: يجب تكوين معمل <0/> ليتوافق مع المظهر المخصص الخاص بك. يمكن القيام بذلك باستخدام محرر السمات الجديد الخاص بنا. <1> اكتشف المزيد.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'تعذر تمكين الوظيفة الإضافية لأنها تسببت في خطأ فادح: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'لقد تم تنزيل الملحق بالفعل.';
$Definition['The banner logo appears at the top of your forum.'] = 'يظهر شعار اللافتة في أعلى صفحات المنتدى الخاص بك.';
$Definition['The banner title appears on the top-left of every page.'] = 'يظهر عنوان اللافتة في أعلى يمين كل صفحة.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'يظهر عنوان اللافتة على لافتة موقعك وفي شريط عنوان المتصفح الخاص بك. يجب أن يكون أقل من 20 حرفاً. إذا تم تحميل شعار لافتة ما، فسوف يستبدل عنوان اللافتة في صفحات المنتدى التي تواجه المستخدم. أيضاً، ضع في اعتبارك أن بعض السمات قد تخفي هذا العنوان أيضاً.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>نموذج التسجيل الأساسي يتطلب</strong> مستخدمين جدد لنسخ نص من صورة CAPTCHA لإبقاء مرسلي البريد غير المرغوب فيه خارج الموقع. أنت بحاجة إلى حساب على <a href="http://recaptcha.net/">recaptcha.net</a>. Sالاشتراك مجاني وسهل. بمجرد تسجيل الاشتراك ، ارجع إلى هنا وأدخل الإعدادات التالية:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'ليس لدى مستخدم قاعدة البيانات الذي حددته إذن بالوصول إلى قاعدة البيانات. هل قمت بإنشاء قاعدة البيانات حتى الآن؟ ذكرت قاعدة البيانات: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'التغييرات الهيكلية التالية مطلوبة لقاعدة البيانات الخاصة بك.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'يتم عرض عنوان الصفحة الرئيسية على صفحتك الرئيسية. اختر العنوان الذي تريد أن يظهر في محركات البحث.';
$Definition['The import file does not contain any data.'] = 'لا يحتوي ملف الاستيراد على أي بيانات.';
$Definition['The import file is not in the correct format.'] = 'ملف الاستيراد ليس بالتنسيق الصحيح.';
$Definition['The location of the authentication endpoint.'] = 'موقع نقطة نهاية المصادقة.';
$Definition['ThemeHelp'] = 'تسمح لك المظاهر بتغيير الشكل و& طابع موقعك. <br /> بمجرد إضافة مظهر إلى مجلد %s الخاص بك، يمكنك تمكينه هنا.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'تقتصر معاينة السمة على عرض قالب السمة و CSS.';
$Definition['Theming Guide'] = 'دليل Theming';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'يظهر شعار الجوال في الجزء العلوي من موقعك. السمات التي تم إنشاؤها باستخدام محرر السمات وبعض السمات المخصصة لا تستخدم هذا الإعداد.';
$Definition['The New Embed System'] = 'نظام التضمين الجديد';
$Definition['The new embed system has improved performance.'] = 'أدى نظام التضمين الجديد إلى تحسين الأداء وتحسين سلوك التمرير وسلوك أكثر اتساقًا من النظام القديم. التعليقات المضمنة ووردبريس غير مدعومة حاليًا في نظام التضمين الجديد.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'لا يحتوي "مصادق كلمة المرور" على أي خيارات تهيئة مخصصة.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'لا توجد تغييرات هيكل قاعدة البيانات مطلوبة. ومع ذلك، قد تكون هناك تغييرات في البيانات.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'هناك نوعان من الأزرار في التطبيق: الأساسي والثانوي.';
$Definition['The route was saved successfully.'] = 'تم حفظ المسار بنجاح.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'يظهر وصف الموقع عادة في محركات البحث. يجب أن تحاول الحصول على وصف يتراوح طوله بين 100 و 150 حرفًا.';
$Definition['The text of the pocket.'] = 'أدخل نص الجيب. سيتم إظهار ذلك كما قمت بكتابته تماماً، لذا تأكد من إدخال رمز HTML صالح.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'يظهر رمز اللمس عند وضع إشارة مرجعية على موقع ويب على الشاشة الرئيسية لجهاز محمول. هذه عادة 152 بكسل.';
$Definition['The user table was not in the import file.'] = 'لم يكن جدول المستخدمين في ملف الاستيراد.';
$Definition['The Vanilla 2 Exporter'] = 'برنامج تصدير Vanilla 2 Exporter';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'تقوم إحصائيات Vanilla بتحويل لوحة معلومات المنتدى الخاص بك إلى أداة تقارير تحليلية، مما يتيح لك مراجعة النشاط في منتداك خلال فترات زمنية محددة. يمكنك <a href="http://vanillaforums.org/docs/vanillastatistics"> قراءة المزيد حول إحصائيات Vanilla </a> في البيانات الموثقة الخاصة بنا.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'إنهم يعملون مثل المواضيع العادية. بمجرد إضافة واحد إلى مجلد السمات ، يمكنك تمكينه هنا.';
$Definition['This is a style guide of your theme.'] = 'هذا هو دليل أسلوب السمة الخاصة بك. يحتوي على أمثلة للعناصر المرئية المستخدمة في جميع أنحاء التطبيق. يمكنك النقر على عناصر واجهة المستخدم المختلفة مثل شريط العنوان <0> </0> أو <1> بانر </1> لتعديل خصائصهم في اللوحة الجانبية.';
$Definition['This is the administrative dashboard for your new community.'] = 'هذه هي لوحة التحكم الإدارية لمجتمعك الجديد. تحقق من خيارات التكوين إلى الجانب. من هناك يمكنك تكوين كيفية عمل مجتمعك.
<b>بشكل افتراضي ، يمكن فقط للمستخدمين في دور "المسؤول" رؤية هذا الجزء من مجتمعك.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'هذا هو المكان الذي يمكنك فيه تمكين واختبار ميزات وصفحات ومكونات Vanilla الجديدة.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'لا يمكن تعطيل هذا التمرين بسبب تطبيق تخطيط مخصص.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'لا يمكن تعطيل هذا المختبر لأنه مطلوب من قبل السمة الحالية.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'يظهر هذا الشعار في الجزء العلوي من موقعك. السمات التي تم إنشاؤها باستخدام محرر السمات وبعض السمات المخصصة لا تستخدم هذا الإعداد.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'يعرض هذا الخيار/ أو يخفي المواقع التي يمكن أن تذهب إليها الجيوب، ولكن فقط للمستخدمين الذين لديهم إذن لإضافة / أو تحرير الجيوب. جرّب إظهار المواقع، ثم قم بزيارة موقعك.';
$Definition['This page lists the endpoints of your API.'] = 'تسرد هذه الصفحة نقاط نهاية API الخاصة بك. انقر نقاط النهاية لمزيد من المعلومات. يمكنك إجراء مكالمات مباشرة إلى واجهة برمجة التطبيقات من هذه الصفحة أو خارجيًا باستخدام رمز وصول.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'هذا الدور هو معلومات شخصية. لن يتمكن من رؤيتها إلا المستخدمون الذين لديهم إذن لعرض المعلومات الشخصية.';
$Definition['This setting loads the page before executing Javascript.'] = 'يقوم هذا الإعداد بتحميل الصفحة قبل تنفيذ جافاسكريبت والتي يمكن أن تحسن محرك البحث الخاص بك. <br> <strong> ** تحذير: قد يؤدي تمكين هذه الميزة إلى حدوث أخطاء في جافاسكريبت على موقعك. ** </strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'يقوم هذا الإعداد بتحميل الصفحة قبل تنفيذ جافا سكريبت الذي يمكنه تحسين مُحسّنات محرّكات البحث لديك.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'لا يمكن حذف هذه السمة لأنها السمة المطبقة حالياً.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'يظهر هذا العنوان على شعار موقعك وفي شريط عنوان المستعرض الخاص بك. يجب أن يكون أقل من 20 حرفًا. إذا تم تحميل شعار ، فسيحل محل هذا العنوان في صفحات المنتديات التي تواجه المستخدم. أيضًا ، ضع في اعتبارك أن بعض السمات قد تخفي هذا العنوان.';
$Definition['Tiled Layout'] = 'تخطيط تجانب';
$Definition['Title Bar'] = 'شريط العنوان';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'لتضمين منتدى Vanilla الخاص بك في موقع الويب الخاص بك، استخدم الكود التالي.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'عناوين كثيرة جدا! سنرسل حتى %s عناوين في وقت واحد.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'لمنع إساءة الاستخدام، تقوم بعض الأدوات تلقائياً بإخفاء المحتوى وإدراجه هنا حتى تتم الموافقة عليه يدوياً من قبل المشرف.';
$Definition['TouchIconDescription'] = 'يظهر رمز اللمس عند وضع إشارة مرجعية على موقع ويب على الشاشة الرئيسية لجهاز Apple. هذه عادة 152 بكسل. تضيف Apple الزوايا الدائرية وتأثير الإضاءة تلقائيًا.';
$Definition['Transparent'] = 'شفاف';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'يتيح Twitter Connect للمستخدمين تسجيل الدخول باستخدام حساب Twitter الخاص بهم. <b> يجب عليك تسجيل التطبيق الخاص بك مع Twitter حتى يعمل هذا الملحق. </b>';

$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'تسمح لك بطاقات Usercards بالحصول على لقطة سريعة لمعلومات المستخدم. عند عرض المنشورات ولوحات الصدارة ، انقر فوق اسم المستخدم لرؤية بطاقة تعرض معلومات الملف الشخصي الأساسية للمستخدمين دون الحاجة إلى الانتقال بعيدًا عن الصفحة. قم بتمكين هذه الميزة لإضافة بطاقات مستخدم إلى نسقك المخصص.';
$Definition['User inputs are based on the global background and text colors.'] = 'تعتمد إدخالات المستخدم على الخلفية العامة وألوان النص.';
$Definition['User Profile'] = 'ملف تعريفي للمستخدم';
$Definition['Users may sign into your site using their Twitter account.'] = 'يمكن للمستخدمين تسجيل الدخول إلى موقعك باستخدام حساب Twitter الخاص بهم.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'استخدم الزر الموجود في أعلى الصفحة لإنشاء قاعدة حظر.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'استخدم البرنامج الملحق لـ WordPress لإعداد تعليقات Vanilla على مدونتك، أو استخدم الكود العالمي لإعداد تعليقات Vanilla على أي منصة أخرى.';

$Definition['Vanilla\'s new search service is finally here.'] = 'خدمة البحث الجديدة من Vanilla هنا أخيرًا. قم بتمكين واجهة مستخدم صفحة البحث الجديدة الخاصة بنا للوصول إلى أحدث ميزات البحث مثل البحث عن الأعضاء وفرز البحث وتمييز المصطلحات.';
$Definition['Vanilla Export: %s, Source: %s'] = 'تصدير Vanilla: %s, المصدر: %s';
$Definition['Vanilla Labs'] = 'مختبرات الفانيليا';
$Definition['Vanilla Statistics are currently disabled'] = 'إحصائيات Vanilla معطلة حالياً';
$Definition['Verify and restore'] = 'تحقق واستعد';
$Definition['VerifyUser'] = 'حدد المربع بجوار المستخدم <b>لتمييزه على أنه تم التحقق منه</b> حتى لا يتم وضع علامة على مشاركاته كرسائل غير مرغوب فيها مرة أخرى. سيؤدي هذا أيضًا إلى استعادة جميع مشاركاتهم المعلقة.';
$Definition['Video tutorial on advanced settings'] = 'فيديو تعليمي عن الإعدادات المتقدمة';
$Definition['Video tutorial on finding &amp; managing users'] = 'فيديو تعليمي حول إيجاد و& إدارة المستخدمين';
$Definition['Video tutorial on managing appearance'] = 'فيديو تعليمي عن إدارة المظاهر';
$Definition['Video tutorial on managing categories'] = 'فيديو تعليمي عن إدارة الفئات';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'فيديو تعليمي عن إدارة الأدوار و& الأذونات';
$Definition['Video tutorial on user registration'] = 'فيديو تعليمي عن تسجيل المستخدم';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'تحذير: قد يؤدي تمكين هذه الميزة إلى حدوث أخطاء جافا سكريبت على موقعك.';
$Definition['Warning: Loading tables can be slow.'] = '<b>تحذير</b> : تكوين الخادم الخاص بك لا يدعم التحميل السريع للبيانات. إذا كنت تقوم باستيراد ملف كبير جدًا (على سبيل المثال ، أكثر من 200000 تعليق) ، فقد تحتاج إلى تغيير تكوينك. انقر <a href="http://vanillaforums.com/porter">هنا</a> لمزيد من المعلومات.';
$Definition['Warning: This is for advanced users.'] = '<b> تحذير </b>: هذا مخصص للمستخدمين المتطورين ويتطلب إجراء تغييرات إضافية على خادم الويب الخاص بك. عادةً ما يكون هذا متاحاً فقط إذا كنت قد خصصت أو قمت باستضافة vps. لا تحاول ذلك إذا كنت لا تعرف ما الذي تفعله.';
$Definition['Webhooks'] = 'ويب هوك';
$Definition['Welcome to Labs!'] = 'مرحبًا بك في المختبرات!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'مرحبًا بك في واجهة مستخدم Vanilla. تسرد هذه الصفحة جميع السمات المتاحة لديك ، وتسمح لك بنسخها أو تحريرها.';
$Definition['Welcome To Your Theme'] = 'مرحبا بك في موضوعك';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'نوصي بردود فعل إيجابية في الغالب لتشجيع المشاركة.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'عند التمكين ، يمكنك إدارة المنتجات والمجموعات الفرعية من خلال تلك المنتجات.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'عندما يشارك شخص ما رابطًا من موقعك ، نحاول التقاط صورة من الصفحة. إذا لم تكن هناك صورة على الصفحة ، فسنستخدم هذه الصورة بدلاً من ذلك. يجب أن تكون الصورة 50 × 50 على الأقل ، لكننا نوصي 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'عند تحديد Full Bleed ، تكون خلفيتك شفافة.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'ما إذا كان سيتم تضمين حقول الملف الشخصي الداخلية في خطاف الويب هذا أم لا.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'ما إذا كان سيتم تضمين حقول الملف الشخصي الخاصة في خطاف الويب هذا أم لا.';
$Definition['Which reactions you use really depends on your community.'] = 'تعتمد ردود الفعل التي تستخدمها حقًا على مجتمعك ، لكننا نوصي بوضع بضع نقاط في الاعتبار.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'أنت على وشك تطبيق خيار تخطيط جديد. يمكن تخصيص ذلك ومعاينته باستخدام محرر السمات الخاص بنا. <0> معرفة المزيد</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'يمكنك حظر جميع المستخدمين بعناوين IP مسبوقة بـ "111.111.111" عن طريق إضافة حظر من نوع IP بالقيمة "111.111.111. *". ';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'يمكنك حظر عناوين IP وعناوين البريد الإلكتروني وأسماء المستخدمين. ';
$Definition['You can choose from one of the different styles this theme offers.'] = 'يمكنك الاختيار من بين الأنماط المختلفة التي يقدمها هذا الموضوع.';
$Definition['You can configure some values differently for different screensizes.'] = 'يمكنك تكوين بعض القيم بشكل مختلف لأحجام الشاشات المختلفة.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'يمكنك الاتصال بمواقع متعددة تدعم jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'إذا كان حجم ملفك كبيرًا جدًا بحيث لا يمكن تحميله مباشرةً إلى هذه الصفحة ، يمكنك وضعه في مجلد / uploads. تأكد من أن اسم الملف يبدأ بالكلمة<b>تصدير</b> وينتهي بواحد من<b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'يمكنك تحديد الحد الأدنى لطول المنشور لتثبيط المنشورات القصيرة.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'يمكنك تحميل خط مخصص في نظام Theming الخاص بك. ما عليك سوى نسخ ولصق عنوان URL في الحقل.';
$Definition['You must select a file to import.'] = 'يجب عليك تحديد ملف للاستيراد.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'تحتاج إلى إضافة مجال عنوان url الخاص بالخط إلى <0> المجالات المسموح بها </0> في تكوين الموقع. <1> تعرف على المزيد حول الخطوط المخصصة. </1>';
$Definition['Your mobile theme will be disabled.'] = 'سيتم تعطيل موضوع الهاتف المحمول الخاص بك. لتعيين سمات مختلفة للجوال وسطح المكتب ، استخدم واجهة المستخدم القديمة.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'يتم استخدام اسم مؤسستك لصالح SEO microdata و JSON + LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'ستظهر أيقونة الموقع الخاص بك في شريط عنوان متصفحك. وسيتم تصغيرها بشكل مناسب.';
