<?php

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Glavo pokonci!</strong> Če izbrišete vlogo, lahko uporabniki nimajo dostopa do aplikacije.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Glavo pokonci!</strong> Če razprave premaknete v nadomestno kategorijo, lahko razprave izginejo (ali se prikažejo), če ima nadomestna kategorija drugačna dovoljenja kot kategorija, ki jo brišete.';

$Definition['About.DisableStatistics'] = 'Če morate iz nekega poslovnega razloga onemogočiti to poročanje podatkov, lahko to storite tako, da v konfiguracijsko datoteko namestitve dodate naslednjo vrstico: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Za življenje te brezplačne odprtokodne programske opreme je zelo pomembno, da natančno merimo doseg in učinkovitost Vanille. Prosimo vas, da ne onemogočite poročanja teh podatkov.';
$Definition['AboutCommentEmbedding'] = 'Vanilijo lahko uporabite kot nadomestek za izvorni sistem komentiranja vašega spletnega dnevnika. Pravzaprav se lahko uporablja za dodajanje komentarjev na katero koli stran v spletu.';
$Definition['AboutEmbedding'] = 'Vdelava omogoča vdelavo celotne ali dela vaše skupnosti v druge aplikacije in spletne strani.';
$Definition['About Vanilla Statistics'] = 'O statističnih podatkih Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Dostopite do svojega foruma skupnosti s klikom na povezavo »Obiščite spletno mesto« na vrhu te strani ali s <a href={/,url}>klikom tukaj</a> . Forum skupnosti je tisto, kar bodo videli vsi vaši uporabniki in stranke, ko obiščejo <a href="{/,url,domain}">{/,url,domain}</a> .';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Dodajte omejitve dimenzij nalaganja slik v razpravah in komentarjih.';
$Definition['AddonProblems'] = '<h2>Težave?</h2><p> Če gre kaj narobe z dodatkom in ne morete uporabljati svojega mesta, ga lahko ročno onemogočite tako, da uredite:</p> %s';
$Definition['AddressBarColorDescription'] = 'Nekateri brskalniki podpirajo barvo naslovne vrstice. Samo mobilni.';
$Definition['Alert users if they click external link.'] = 'Opozorite uporabnike, če kliknejo povezavo v objavi, ki jih bo odpeljala stran od foruma. Uporabniki ne bodo opozorjeni, ko sledijo povezavam, ki se ujemajo z zaupanja vredno domeno';
$Definition['Alignment'] = 'Poravnava';
$Definition['Alignment (Mobile)'] = 'Poravnava (mobilno)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Vse kategorije so navedene z izborom 5 nedavnih razprav pod vsako';
$Definition['Allow links to be transformed'] = 'Dovolite pretvorbo povezav v vdelane predstavitve v razpravah in komentarjih. Povezava YouTube se bo na primer spremenila v vdelan video.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Dovoli uporabnikom z dovoljenjem %s, da spremenijo lastne avatarje na svojih profilnih straneh v Vaniliji.';
$Definition['ApplicationHelp'] = 'Aplikacije vam omogočajo dodajanje velikih skupin funkcij na vaše spletno mesto.<br /> Ko je aplikacija dodana v mapo %s, jo lahko tukaj omogočite ali onemogočite.';
$Definition['Apply Layout'] = 'Uporabi postavitev';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Ali res želite izbrisati to temo? Trajno bo izbrisan.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Ali ste prepričani, da ste vnesli pravilno ime gostitelja baze podatkov? Ste se morda zmotili? Baza podatkov je poročala: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Za uporabo potrditve po e-pošti je potrebna vloga s privzeto vrsto »nepotrjeno«.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatarji bodo pomanjšani, če presežejo to višino.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatarji bodo pomanjšani, če presežejo to širino.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatarji bodo imeli svoje sličice shranjene v tej velikosti.';

$Definition['Background'] = 'Ozadje';
$Definition['Background Image'] = 'Slika ozadja';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Bodi ustvarjalen! Poskusite poimenovati svoje uvrstitve po stvareh, o katerih govori skupnost.';
$Definition['Bordered'] = 'Obrobljen';
$Definition['Bordered (Unified)'] = 'Obrobljeno (poenoteno)';
$Definition['Borderless'] = 'Brez meja';
$Definition['Border Radius'] = 'Polmer obrobe';
$Definition['Brand Color'] = 'Barva znamke';
$Definition['Buttons'] = 'Gumbi';
$Definition['Buttons & Inputs'] = 'Gumbi in vhodi';
$Definition['Button Type'] = 'Vrsta gumba';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'S klikom na spodnji gumb boste za vedno izbrisali uporabniški račun za %s.';

$Definition['Center Aligned'] = 'Sredinsko poravnano';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Spremembe bodo veljale samo za na novo naložene avatarje.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Spremenite velikosti, v katerih so shranjene slike avatarjev.';
$Definition['Change the way your community works with plugins.'] = 'Spremenite način delovanja svoje skupnosti z vtičniki. S programsko opremo smo združili priljubljene vtičnike, na spletu pa jih je na voljo več.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Potrditvena polja omogočajo skrbnikom, da izvajajo paketna dejanja na več razpravah ali komentarjih hkrati.';
$Definition['Check out our %s'] = 'Oglejte si naše %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Oglejte si našo <0>dokumentacijo</0> , ali vprašajte našo <1>skupnost strokovnjakov</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla je najpreprostejša in najmočnejša platforma skupnosti na svetu. Je super-duper enostaven za uporabo. Začnite s tem uvodnim videoposnetkom in nadaljujte s spodnjimi koraki. Uživajte!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Izberite vlogo, ki ji bodo dodeljeni osiroteli uporabniki:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Izberite temo za to podskupnost. <0>Preberite več</0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Izberite način ravnanja z vso vsebino, povezano z uporabniškim računom za %s (komentarji, sporočila itd.).';
$Definition['Choose Image'] = 'Izberite Slika';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Za podpisovanje zahtev lahko izberete algoritem zgoščevanja po meri. Algoritem zgoščevanja je treba uporabiti tudi v vaši odjemalski knjižnici. Če niste prepričani, kaj izbrati, izberite md5.';
$Definition['Choose the order items are sorted.'] = 'Izberite predmeti naročila so razvrščeni.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Izberite stran, ki naj jo ljudje vidijo, ko obiščejo <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Izberite želeno postavitev za sezname kategorij.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Izberite želeno postavitev za sezname kategorij. Postavitev s ploščicami lahko uredite.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Izberite želeno postavitev za sezname razprav.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Izberite želeno postavitev za sezname razprav. Postavitev temelja lahko uredite.';
$Definition['Color Overlay'] = 'Barvno prekrivanje';
$Definition['Continue Import'] = 'Nadaljujte z uvozom';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Ni bilo mogoče razčleniti uvozne datoteke. Težava je blizu vrstice %s.';
$Definition['Create a localization CSV'] = 'Ustvarite lokalizacijski CSV';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Teme po meri so teme, ki ste jih ustvarili. Lahko jih urejate, preimenujete ali kopirate.';

$Definition['Dark'] = 'Temno';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Na strani <a href="%s">Vloge in dovoljenja</a> določite, kdo lahko nalaga in upravlja datoteke.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Določite svojo domačo stran foruma, naložite svoj logotip in še več ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Če izbrišete vlogo, lahko uporabniki nimajo dostopa do aplikacije.';
$Definition['Deleting forever cannot be undone.'] = 'Brisanje je dober način za ohranjanje čistega foruma.';
$Definition['Disable Google Sign In'] = 'Onemogoči prijavo v Google';
$Definition['Disable OpenID'] = 'Onemogoči OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Onemogočite laboratorij »Nov vdelani sistem« na strani <0>Vanilla Labs</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Kategorije razprav se uporabljajo za pomoč vašim uporabnikom pri organizaciji razprav na način, ki je pomemben za vašo skupnost.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Ne vdelajte skrbniške nadzorne plošče foruma (odprite jo v celozaslonskem načinu)';
$Definition['Don\'t use too many reactions.'] = 'Ne uporabljajte preveč reakcij. Svojim uporabnikom ne želite dati prevelike količine informacij.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Povlecite in spustite spodnje kategorije, da jih razvrstite in ugnezdite.';

$Definition['EditContentTimeout.Notes'] = 'Če je uporabnik v vlogi, ki ima dovoljenje za urejanje vsebine, bodo ta dovoljenja preglasila to.';
$Definition['Edit Route'] = 'Uredi pot';
$Definition['Edits to this theme apply to:'] = 'Spremembe te teme veljajo za:';
$Definition['Embed Settings'] = 'Nastavitve vdelave';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Vdelajte svoj forum skupnosti v svoje spletno mesto, da povečate sodelovanje ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Omogočite in preizkusite najnovejše funkcije Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Omogoča napredno urejanje objav v več formatih, vključno z WYSIWYG, preprostim HTML, Markdown in BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Omogočite urejevalnik postavitve, da uporabite postavitev po meri za vaše strani skupnosti. Uporabite naš novi urejevalnik za prikaz vsebine z našim katalogom razpoložljivih pripomočkov.';
$Definition['Enter a descriptive name.'] = 'Vnesite opisno ime za žep. To ime ne bo prikazano nikjer, razen pri upravljanju vaših žepov tukaj, zato se uporablja samo za pomoč pri zapomnitvi žepa.';
$Definition['Enter a short name for the site.'] = 'Vnesite kratko ime za mesto. To je prikazano na gumbih za prijavo.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Vnesite naslov svojega bloga Wordpress in mi ga bomo prevzeli od tam.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Spodaj vnesite nastavitve povezave za vaš strežnik sphinx.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Tu se zabeleži vsako urejanje ali brisanje. Za razveljavitev morebitnih sprememb uporabite »Obnovi«.';
$Definition['Everyone who signs up gets a profile page.'] = 'Vsakdo, ki se prijavi v vašo skupnost, dobi javno stran s profilom, kamor lahko naloži svojo sliko, upravlja nastavitve svojega profila in spremlja zanimive stvari, ki se dogajajo v skupnosti. Zdaj bi morali <a href="{/profile,url}">prilagoditi svoj profil</a> .';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Vsakemu uporabniku na vašem spletnem mestu je dodeljena vsaj ena vloga. Vloge se uporabljajo za določanje, kaj lahko uporabniki počnejo.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect omogoča uporabnikom, da se prijavijo s svojim Facebook računom. <b>Da bo ta vtičnik deloval, morate svojo aplikacijo registrirati pri Facebooku.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Povezava z bazo podatkov z uporabniškim imenom in geslom, ki ste ju vnesli, ni uspela. Ste jih napačno vnesli? Baza podatkov je poročala: <code>%s</code>';
$Definition['Font'] = 'Pisava';
$Definition['Font Name'] = 'Ime pisave';
$Definition['Font URL'] = 'URL pisave';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Vsili, da je nadzorna plošča dostopna samo prek tega URL-ja <em>(ni priporočljivo)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Vse uporabnike z e-poštnimi naslovi lahko na primer izključite iz »example.com« tako, da dodate prepoved vrste e-pošte z vrednostjo »*@example.com«.';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Za namene SEO so pajki iskalnikov izključeni iz tega, da si forum ogledajo na oddaljenem URL-ju.';
$Definition['Foundation Layout'] = 'Postavitev temeljev';

$Definition['Garden.Import.Complete.Description'] = 'Uspešno ste zaključili uvoz. Kliknite <b>Končano</b> , ko ste pripravljeni.';
$Definition['Garden.Import.Continue.Description'] = 'Zdi se, kot da ste sredi uvoza. Izberite eno od naslednjih možnosti.';
$Definition['Garden.Import.InputInstructions'] = 'Vnesite e-pošto in geslo skrbniškega uporabnika iz podatkov, ki se uvažajo.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Dovoljenje Garden.Profiles.Edit za spreminjanje lastnih avatarjev s strani profila v Vaniliji.';
$Definition['Garden.StatisticsDisabled'] = 'V konfiguracijski datoteki ste izrecno onemogočili Vanilla Statistics.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Zdi se, da ta forum deluje v testnem okolju ali kako drugače poroča o zasebnem IP-ju. Privzeto se forumom, ki delujejo na zasebnih naslovih IP, ne sledi.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Če ste prepričani, da je vaš forum dostopen iz interneta, ga lahko prisilite, da poroča statistiko tukaj:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Videti je, da je vaša datoteka config.php samo za branje. To pomeni, da Vanilla ne bo mogla samodejno registrirati InstallationID in InstallationSecret vašega foruma.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Za rešitev te težave dodelite datotečni način 777 svoji datoteki conf/config.php.';
$Definition['Global Styles'] = 'Globalni slogi';

$Definition['Heads Up!'] = 'Glavo pokonci!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Glavo pokonci! To je posebna vloga, ki ne dovoljuje aktivnih sej. Iz tega razloga so bile možnosti dovoljenj omejene na dovoljenja za »ogled«.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Tukaj so vsi odzivi, ki jih lahko uporabite na svojem spletnem mestu.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Tukaj so uvrstitve, ki jih lahko uporabniki dosežejo na vašem spletnem mestu. Te uvrstitve lahko prilagodite in celo dodate nove. Tukaj je nekaj nasvetov.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Če je naložen logotip pasice, bo nadomestil naslov pasice na straneh foruma, ki jih vidijo uporabniki.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Če uporabnik v tem času ne obišče spletnega mesta, bo samodejno odjavljen.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Če je omogočeno, bo uporabnikom v e-poštnih obvestilih poslana celotna vsebina objav.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Če šele spoznavate HTML in/ali CSS, je tukaj nekaj vadnic za lažji začetek:';
$Definition['If you have an old theme'] = 'Če imate staro temo in morate nastaviti ločeno temo za namizje in mobilno napravo, lahko to storite s starim uporabniškim vmesnikom za teme.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Če želite znižati raven opozorila, odstranite opozorilo.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Če želite vdelati svoj forum ali uporabiti Vanilline komentarje v svoj blog, morate omogočiti vdelavo. Če ne uporabljate vdelave, priporočamo, da to nastavitev pustite izklopljeno.';
$Definition['Image (Mobile)'] = 'Slika (mobilno)';
$Definition['Import'] = 'Uvozi';
$Definition['Importing to Vanilla'] = 'Uvoz v Vanillo';
$Definition['In additon to the widgets there are also'] = 'Poleg gradnikov obstajajo tudi <0>Globalni slogi</0> . Za urejanje globalnih slogov kliknite kjer koli drugje na strani, na primer to besedilo.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integrirajte temeljne strani in komponente v svojo temo';
$Definition['Internationalization & Localization'] = 'Internacionalizacija in lokalizacija';
$Definition['Invalid URL'] = 'Neveljaven URL';
$Definition['Invitation email failed to send: %'] = 'Čeprav je bilo povabilo uspešno ustvarjeno, e-poštno sporočilo ni bilo poslano. Strežnik je sporočil naslednjo napako: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Ko uporabljate registracijo s povabilom, bodo imeli uporabniki na svojih profilnih straneh povezavo <a href="%s" class="Popup">Moja povabila</a> .';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Zdi se, kot da baza podatkov, ki ste jo navedli, še ne obstaja. Ste ga že ustvarili? Ste se zmotili pri imenu? Baza podatkov je poročala: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Dobro je, da največje dovoljeno število znakov v komentarju zmanjšate na razumno velikost.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Dobro je, da največje dovoljeno število znakov v objavi zmanjšate na razumno velikost.';

$Definition['Kick-start your community and increase user engagement.'] = 'Zaženite svojo skupnost in povečajte angažiranost uporabnikov.';

$Definition['Labs'] = 'laboratoriji';
$Definition['Layout Editor'] = 'Urejevalnik postavitve';
$Definition['Learn about custom routing.'] = 'Več o usmerjanju po meri.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Naučite se popolnoma spremeniti videz in občutek svojega foruma: naložite svoj logotip, nastavite domačo stran, izberite temo in jo prilagodite.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Naučite se uporabljati osnovne funkcije vašega foruma.';
$Definition['Left Aligned'] = 'Levo poravnano';
$Definition['Light'] = 'Svetloba';
$Definition['Links'] = 'Povezave';
$Definition['Locales allow you to support other languages on your site.'] = 'Lokalne nastavitve vam omogočajo podporo drugim jezikom na vašem spletnem mestu. Omogočite in onemogočite lokalne nastavitve, ki jih želite dati na voljo tukaj.';
$Definition['LogoDescription'] = 'Logotip pasice se prikaže na vrhu vašega spletnega mesta.';
$Definition['LogoDisclaimer'] = 'Teme, narejene z urejevalnikom tem, in nekatere teme po meri ne uporabljajo te nastavitve.';
$Definition['Looking for the Old Embed System?'] = 'Iščete Old Embed System?';

$Definition['Make sure you click View Page'] = 'Prepričajte se, da ste kliknili <a href="%s">Ogled strani</a> , da vidite, kako je videti vaša stran s kategorijami po shranjevanju.';
$Definition['Manage Routes'] = 'Upravljanje poti';
$Definition['Managing Users'] = 'Upravljanje uporabnikov';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Če stvari označite kot NI vsiljena pošta, jih boste vrnili na svoj forum.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Če stvari označite kot neželeno, jih boste vrnili na svoj forum.';
$Definition['Messages can appear anywhere in your application.'] = 'Sporočila se lahko prikažejo kjer koli v vaši aplikaciji in se lahko uporabljajo za obveščanje uporabnikov o novicah in dogodkih. Uporabite to stran za ponovno organiziranje sporočil tako, da jih povlečete gor ali dol.';
$Definition['MobileLogoDescription'] = 'Logotip mobilne pasice se prikaže na vrhu vašega spletnega mesta.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Mobilne teme vam omogočajo, da spremenite videz in občutek vašega spletnega mesta na manjših napravah.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'Opomba: novi urejevalnik postavitve bo podedoval temo, nastavljeno v vašem vodniku po slogu (formalno urejevalnik tem). <1>Izvedite več</1>';
$Definition['Need More Help?'] = 'Potrebujete več pomoči?';
$Definition['Need more help?'] = 'Potrebujete več pomoči?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Ugnezdene kategorije, ki so globlje od te globine, bodo uvrščene na seznam, ločen z vejico.';
$Definition['New Embed System'] = 'Nov vdelani sistem';
$Definition['New Quick Links'] = 'Nove hitre povezave';
$Definition['New Search Page'] = 'Nova iskalna stran';
$Definition['Not getting what you expect when you preview your theme?'] = 'Ne dobite tega, kar pričakujete, ko si predogledate svojo temo?';
$Definition['Notify me when people comment on my addons.'] = 'Obvesti me, ko ljudje komentirajo moje dodatke.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Spletno mesto potrebuje vlogo s privzeto vrsto »nepotrjeno« za uporabo potrditve po e-pošti. Dodajte enega, da omogočite to nastavitev.';

$Definition['Old Theming UI'] = 'Stari uporabniški vmesnik za temiranje';
$Definition['Once enabled, only members will see inside your community.'] = 'Ko je omogočeno, bodo samo člani videli notranjost vaše skupnosti.';
$Definition['OrgDescription'] = 'Ime vaše organizacije se uporablja za mikropodatke SEO in JSON+LD';
$Definition['Outline'] = 'Oris';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Preglaseni pogledi ali kljukice za teme imajo lahko nenamerne stranske učinke in niso prikazani v predogledu.';

$Definition['Password.MinLength'] = 'Najmanjša dovoljena dolžina znakov za gesla uporabnikov na straneh za ustvarjanje in ponastavitev gesel.';
$Definition['Please choose an authenticator to configure.'] = 'Izberite avtentifikator za konfiguracijo.';
$Definition['PluginHelp'] = 'Vtičniki vam omogočajo, da svojemu spletnemu mestu dodate funkcionalnost.<br /> Ko je vtičnik dodan vaši mapi %s, ga lahko omogočite ali onemogočite tukaj.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Žepek je prikazan med vsako razpravo na glavnem seznamu razprav. Ker so razprave običajno v oznakah <li>..</li>, boste morali tudi vi zaviti svoj žep v te oznake.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Žepi vam omogočajo, da dodate HTML v prosti obliki na različna mesta v aplikaciji.';
$Definition['Preset'] = 'Prednastavitev';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Preprečite vsiljeno pošto na svojem forumu tako, da omejite število razprav in komentarjev, ki jih lahko uporabniki objavijo v določenem časovnem obdobju.';
$Definition['Primary Button'] = 'Primarni gumb';
$Definition['Primary Buttons'] = 'Primarni gumbi';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Hitri vodnik za ustvarjanje tem za Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Hitre povezave so privzeta komponenta na straneh skupnosti. Omogočite našo novo komponento hitrih povezav, da dodate, uredite ali skrijete povezave iz tega menija z našim urejevalnikom tem.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Pripravljen vtičnik za komentarje Vanilla za WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Pripravljen vtičnik Vanilla Forum za WordPress';
$Definition['Realtime progress bars: %s'] = 'Vrstice napredka v realnem času: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Dobro je imeti posebne položaje za moderatorje in skrbnike, da lahko vaša skupnost zlahka vidi, kdo je glavni.';
$Definition['Recommend starting with five ranks.'] = 'Nočete imeti preveč činov. Priporočamo, da začnete s petimi. Če je vaša skupnost res velika, jih lahko dodate več.';
$Definition['Requires “Flag” reaction permission.'] = 'Zahteva dovoljenje za reakcijo »Označi«.';
$Definition['Requires “Negative” reaction permission.'] = 'Zahteva dovoljenje za »Negativno« reakcijo.';
$Definition['Requires “Positive” reaction permission.'] = 'Zahteva dovoljenje za »pozitivno« reakcijo.';
$Definition['Restoring your selection removes the items from this list.'] = 'Ko obnovite, se elementi odstranijo s tega seznama in vrnejo na spletno mesto.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Uporabite naslednjo možnost, da omogočite narekovaje za Rich Editor. To bo veljalo samo, če je privzeti formater "Rich".';
$Definition['Route Expression'] = 'Izraz poti';
$Definition['Routes are used to redirect users.'] = 'Poti se uporabljajo za preusmerjanje uporabnikov glede na zahtevani URL.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Iščite uporabnike po imenu ali vnesite ime vloge, da vidite vse uporabnike s to vlogo.';
$Definition['Secondary Button'] = 'Sekundarni gumb';
$Definition['Secondary Buttons'] = 'Sekundarni gumbi';
$Definition['Security.Hsts.HTTPSWarning'] = 'Opozorilo: to funkcijo omogočite le, če ste prepričani, da so vse vaše poddomene konfigurirane za HTTPS z veljavnimi potrdili.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Ko je omogočeno, to pravilo velja tudi za vse poddomene vašega spletnega mesta.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Priporočamo, da začnete z najvišjo starostjo 1 teden in jo nato povečate na 1 mesec in nato na 1 leto, ko vidite, da vaše spletno mesto deluje po pričakovanjih.';
$Definition['Security.Hsts.SubmitWarning'] = 'Opozorilo: odlično je podpirati vnaprejšnje nalaganje HSTS kot najboljšo prakso. Vendar pa morate svoje spletno mesto poslati na hstspreload.org, da zagotovite, da je uspešno vnaprej naloženo (tj. da dobite popolno zaščito za predvideno konfiguracijo).';
$Definition['See the documentation'] = 'Oglejte si dokumentacijo';
$Definition['Select the default type for this role, if any.'] = 'Izberite privzeto vrsto za to vlogo, če obstaja.';
$Definition['Select the import source'] = 'Izberite vir uvoza';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Serializiranega stolpca »%s« ni bilo mogoče razveljaviti iz serializacije.';
$Definition['Session Timeout'] = 'Časovna omejitev seje';
$Definition['Shadowed'] = 'Zasenčeno';
$Definition['ShareImageDescription'] = 'Ko nekdo deli povezavo z vašega mesta, poskušamo zgrabiti sliko s strani. Če na strani ni slike, bomo namesto nje uporabili to sliko. Slika naj bo velika vsaj 50×50, priporočamo pa 200×200.';
$Definition['Show all possible pocket locations.'] = 'Vklopite to možnost, da prikažete vse možne lokacije žepov. Če vklopite to možnost, bodo lokacije prikazane le uporabnikom, ki lahko upravljajo žepe.';
$Definition['Solid'] = 'Trdna';
$Definition['Some older themes don\'t support full editing capability.'] = 'Nekatere starejše teme ne podpirajo popolne možnosti urejanja. Če si želite ogledati, kaj tema podpira, se pomaknite nad njeno ime in si oglejte, kje bodo spremembe začele veljati.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Nekatere teme bo morda treba posodobiti, da bodo delovale s sledenjem kategorij. Med posodabljanjem teme lahko to funkcijo onemogočite.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Včasih želite svoje spletno mesto Vanilla vdelati v drugo spletno mesto. Vanillin sistem za vdelavo ponuja preprost način za to. Pri uporabi vdelanega mesta obstajajo kompromisi glede zmogljivosti, zato preverite dokumentacijo za alternative in idealne primere uporabe.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Posebna omejitev: Samo uporabniki z dovoljenjem Garden.Curation.Manage lahko uporabljajo to reakcijo.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Pri ustvarjanju prepovedi določite delno ali popolno ujemanje.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Nekaj časa razmislite o tem, kako tukaj opisujete svoje spletno mesto. Če svojemu spletnemu mestu daste smiseln naslov in jedrnat opis, bi to lahko pripomoglo k vašemu položaju v iskalnikih.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Popestrite svoja e-poštna sporočila z dodajanjem logotipa in prilagajanjem barv.';
$Definition['Start Import'] = 'Zaženi uvoz';
$Definition['Start the first discussion.'] = 'Zaženite svojo skupnost tako, da zdaj <a href="{/post/discussion,url}">začnete prvo razpravo</a> .';
$Definition['Subcommunities'] = 'Podskupnosti';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Označevanje omogoča uporabnikom, da dodajo oznako razpravam, ki jih začnejo, da jih naredijo lažje odkrite.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Predloge so standardne teme. Če jih želite prilagoditi, morate ustvariti kopijo.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Authenticator %s nima nobenih možnosti konfiguracije po meri.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'Opomba: Laboratorij <0/> mora biti konfiguriran tako, da ustreza vaši temi po meri. To lahko storite z našim novim urejevalnikom tem. <1>Izvedite več.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Dodatka ni bilo mogoče omogočiti, ker je povzročil usodno napako:<pre> %s</pre>';
$Definition['The addon has already been downloaded.'] = 'Dodatek je že prenesen.';
$Definition['The banner logo appears at the top of your forum.'] = 'Logotip pasice se prikaže na vrhu foruma.';
$Definition['The banner title appears on the top-left of every page.'] = 'Naslov pasice se prikaže v zgornjem levem kotu vsake strani.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Naslov pasice se prikaže na pasici vašega spletnega mesta in v naslovni vrstici brskalnika. Imeti mora manj kot 20 znakov. Če je naložen logotip pasice, bo nadomestil naslov pasice na straneh foruma, ki jih vidijo uporabniki. Upoštevajte tudi, da nekatere teme morda skrivajo ta naslov.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Osnovni obrazec za registracijo zahteva</strong> , da novi uporabniki kopirajo besedilo iz slike CAPTCHA, da preprečijo pošiljatelje neželene pošte stran od spletnega mesta. Potrebujete račun na <a href="http://recaptcha.net/">recaptcha.net</a> . Prijava je BREZPLAČNA in enostavna. Ko se prijavite, se vrnite sem in vnesite naslednje nastavitve:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Uporabnik baze podatkov, ki ste ga navedli, nima dovoljenja za dostop do baze podatkov. Ste že ustvarili bazo podatkov? Baza podatkov je poročala: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Za vašo bazo podatkov so potrebne naslednje spremembe strukture.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Naslov domače strani je prikazan na vaši domači strani. Izberite naslov, za katerega želite, da se pojavi v iskalnikih.';
$Definition['The import file does not contain any data.'] = 'Datoteka za uvoz ne vsebuje nobenih podatkov.';
$Definition['The import file is not in the correct format.'] = 'Datoteka za uvoz ni v pravilni obliki.';
$Definition['The location of the authentication endpoint.'] = 'Lokacija končne točke preverjanja pristnosti.';
$Definition['ThemeHelp'] = 'Teme vam omogočajo, da spremenite videz in občutek vašega spletnega mesta.<br /> Ko je tema dodana vaši mapi %s, jo lahko omogočite tukaj.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Predogled teme je omejen na prikaz predloge teme in css.';
$Definition['Theming Guide'] = 'Tematski vodnik';
$Definition['The New Embed System'] = 'Nov sistem vdelave';
$Definition['The new embed system has improved performance.'] = 'Novi vdelani sistem ima izboljšano delovanje, izboljšano vedenje drsenja in bolj dosledno vedenje kot stari. Novi vdelani sistem trenutno ne podpira vdelave komentarjev in wordpressa.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Password Authenticator nima nobenih možnosti konfiguracije po meri.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Spremembe strukture baze podatkov niso potrebne. Lahko pa pride do spremembe podatkov.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'V aplikaciji sta dve vrsti gumbov: primarni in sekundarni.';
$Definition['The route was saved successfully.'] = 'Pot je bila uspešno shranjena.';
$Definition['The text of the pocket.'] = 'Vnesite besedilo žepa. To bo izpisano točno tako, kot ga vnesete, zato se prepričajte, da ste vnesli veljaven HTML.';
$Definition['The user table was not in the import file.'] = 'Uporabniške tabele ni bilo v uvozni datoteki.';
$Definition['The Vanilla 2 Exporter'] = 'Izvoznik Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla Statistics nadzorno ploščo vašega foruma spremeni v analitično orodje za poročanje, ki vam omogoča pregled dejavnosti na vašem forumu v določenih časovnih obdobjih. <a href="http://vanillaforums.org/docs/vanillastatistics">Več o statistiki Vanilla lahko preberete</a> v naši dokumentaciji.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Delujejo tako kot običajne teme. Ko je ena dodana v mapo tem, jo lahko omogočite tukaj.';
$Definition['This is a style guide of your theme.'] = 'To je slogovni vodnik za vašo temo. Vsebuje primere vizualnih elementov, ki se uporabljajo v celotni aplikaciji. Lahko kliknete različne pripomočke, kot je <0>naslovna vrstica</0> ali <1>Pasica</1> za urejanje njihovih lastnosti na stranski plošči.';
$Definition['This is the administrative dashboard for your new community.'] = 'To je skrbniška nadzorna plošča za vašo novo skupnost. Oglejte si možnosti konfiguracije ob strani. Od tam lahko konfigurirate, kako deluje vaša skupnost. <b>Privzeto lahko ta del vaše skupnosti vidijo le uporabniki z vlogo "skrbnika".</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Tukaj lahko omogočite in preizkusite nove funkcije, strani in komponente Vanilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Tega laboratorija ni mogoče onemogočiti, ker je uporabljena postavitev po meri.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Tega laboratorija ni mogoče onemogočiti, ker ga zahteva trenutna tema.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Ta možnost prikaže/skrije lokacije, kamor lahko gredo žepi, vendar samo za uporabnike, ki imajo dovoljenje za dodajanje/urejanje žepov. Poskusite prikazati lokacije in nato obiščite svoje spletno mesto.';
$Definition['This page lists the endpoints of your API.'] = 'Na tej strani so navedene končne točke vašega API-ja. Za več informacij kliknite končne točke. API-ju lahko kličete v živo s te strani ali zunaj z uporabo žetona za dostop.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Ta vloga je osebni podatek. Videli jih bodo samo uporabniki z dovoljenjem za ogled osebnih podatkov.';
$Definition['This setting loads the page before executing Javascript.'] = 'Ta nastavitev naloži stran pred izvajanjem Javascripta, kar lahko izboljša vaš SEO.<br> <strong>**Opozorilo: omogočanje te funkcije lahko povzroči napake Javascripta na vašem spletnem mestu.**</strong>';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Te teme ni mogoče izbrisati, ker je trenutno uporabljena tema.';
$Definition['Tiled Layout'] = 'Postavitev s ploščicami';
$Definition['Title Bar'] = 'Naslovna vrstica';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Če želite svoj forum Vanilla vdelati v svoje spletno mesto, uporabite naslednjo kodo.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Preveč naslovov! Poslali bomo do %s naslovov hkrati.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Da bi preprečili zlorabo, nekatera orodja samodejno skrijejo vsebino in jo navedejo tukaj, dokler je ročno ne odobri moderator.';
$Definition['TouchIconDescription'] = 'Ikona na dotik se prikaže, ko dodate spletno stran med zaznamke na začetnem zaslonu naprave Apple. Te so običajno 152 slikovnih pik. Apple samodejno doda zaobljene vogale in svetlobni učinek.';
$Definition['Transparent'] = 'Pregleden';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect omogoča uporabnikom, da se prijavijo s svojim računom Twitter. <b>Če želite, da ta vtičnik deluje, morate svojo aplikacijo registrirati pri Twitterju.</b>';

$Definition['Usercards'] = 'Uporabniške kartice';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Uporabniške kartice vam omogočajo, da dobite hiter in-line posnetek informacij o uporabniku. Ko si ogledujete objave in lestvice najboljših, kliknite uporabniško ime, da vidite kartico, ki prikazuje osnovne podatke o profilu uporabnika, ne da bi morali zapustiti stran. Omogočite to funkcijo, če želite svoji temi po meri dodati uporabniške kartice.';
$Definition['User inputs are based on the global background and text colors.'] = 'Uporabniški vnosi temeljijo na globalnem ozadju in barvah besedila.';
$Definition['User Profile'] = 'Uporabniški profil';
$Definition['Users may sign into your site using their Twitter account.'] = 'Uporabniki se lahko prijavijo na vaše spletno mesto s svojim računom Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Uporabite gumb na vrhu strani, da ustvarite pravilo prepovedi.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Uporabite vtičnik WordPress za nastavitev komentarjev Vanilla na svojem spletnem dnevniku ali uporabite univerzalno kodo za nastavitev komentarjev Vanilla na kateri koli drugi platformi.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Vanilla nova storitev iskanja je končno tu. Omogočite naš novi uporabniški vmesnik iskalne strani, da pridobite dostop do najnovejših iskalnih funkcij, kot so iskanje po članih, razvrščanje iskanja in označevanje izrazov.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Izvoz vanilije: %s, vir: %s';
$Definition['Vanilla Statistics are currently disabled'] = 'Statistika Vanilla je trenutno onemogočena';
$Definition['Verify and restore'] = 'Preverite in obnovite';
$Definition['VerifyUser'] = 'Potrdite polje poleg uporabnika, da ga označite kot <b>preverjenega</b> , da njegove objave ne bodo ponovno označene kot vsiljena pošta. S tem boste obnovili tudi vse njihove čakajoče objave.';
$Definition['Video tutorial on advanced settings'] = 'Video vadnica o naprednih nastavitvah';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video vadnica o iskanju in upravljanju uporabnikov';
$Definition['Video tutorial on managing appearance'] = 'Video vadnica o upravljanju videza';
$Definition['Video tutorial on managing categories'] = 'Video vadnica o upravljanju kategorij';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video vadnica o upravljanju vlog in dovoljenj';
$Definition['Video tutorial on user registration'] = 'Video navodila za registracijo uporabnika';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Opozorilo: omogočanje te funkcije lahko povzroči napake Javascripta na vašem spletnem mestu.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Opozorilo</b> : konfiguracija vašega strežnika ne podpira hitrega nalaganja podatkov. Če uvažate zelo veliko datoteko (npr. več kot 200.000 komentarjev), boste morda želeli razmisliti o spremembi konfiguracije. Kliknite <a href="http://vanillaforums.com/porter">tukaj</a> za več informacij.';
$Definition['Warning: This is for advanced users.'] = '<b>Opozorilo</b> : To je za napredne uporabnike in zahteva dodatne spremembe v vašem spletnem strežniku. To je običajno na voljo samo, če imate namensko ali vps gostovanje. Ne poskušajte tega, če ne veste, kaj počnete.';
$Definition['Welcome to Labs!'] = 'Dobrodošli v laboratorijih!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Dobrodošli v tematskem uporabniškem vmesniku Vanilla. Na tej strani so navedene vse vaše razpoložljive teme in vam omogoča, da jih kopirate ali urejate.';
$Definition['Welcome To Your Theme'] = 'Dobrodošli v vaši temi';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Za spodbujanje sodelovanja priporočamo večinoma pozitivne odzive.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Ko je omogočeno, lahko upravljate izdelke in združujete podskupnosti po teh izdelkih.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Ko nekdo deli povezavo z vašega mesta, poskušamo zgrabiti sliko s strani. Če na strani ni slike, bomo namesto nje uporabili to sliko. Slika naj bo velika vsaj 50×50, priporočamo pa 200×200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Ko izberete Full Bleed, je vaše ozadje prozorno.';
$Definition['Which reactions you use really depends on your community.'] = 'Katere reakcije boste uporabili, je res odvisno od vaše skupnosti, vendar priporočamo, da upoštevate nekaj točk.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Uporabili boste novo možnost postavitve. To lahko prilagodite in si ogledate predogled z našim urejevalnikom tem. <0>Več o tem</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Vse uporabnike z naslovi IP s predpono "111.111.111" lahko izključite tako, da dodate prepoved tipa IP z vrednostjo "111.111.111.*".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Prepovedate lahko naslove IP, e-poštne naslove in uporabniška imena.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Izbirate lahko med enim od različnih stilov, ki jih ponuja ta tema.';
$Definition['You can configure some values differently for different screensizes.'] = 'Nekatere vrednosti lahko konfigurirate drugače za različne velikosti zaslona.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Lahko se povežete z več mesti, ki podpirajo jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Če je vaša datoteka prevelika za nalaganje neposredno na to stran, jo lahko postavite v mapo /uploads. Prepričajte se, da se ime datoteke začne z besedo <b>izvoz</b> in konča z eno od <b>.txt, .gz</b> .';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Določite lahko najmanjšo dolžino objave, da preprečite kratke objave.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Pisavo po meri lahko naložite v svoj Theming System. Samo kopirajte in prilepite URL v polje.';
$Definition['You must select a file to import.'] = 'Izbrati morate datoteko za uvoz.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'V <0>Dovoljene domene morate dodati domeno URL-ja pisave</0> v konfiguraciji spletnega mesta. <1>Več o pisavah po meri.</1>';
$Definition['Your mobile theme will be disabled.'] = 'Vaša mobilna tema bo onemogočena. Če želite nastaviti različne teme za mobilne naprave in namizje, uporabite stari uporabniški vmesnik za teme.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Ime vaše organizacije se uporablja za mikropodatke SEO in JSON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Ikona priljubljenega mesta se prikaže v naslovni vrstici brskalnika. Ustrezno bo pomanjšan.';
