<?php

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Pozor!</strong> Smazání role se může projevit u uživatelů, kteří nemají k aplikaci přístup.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Pozor!</strong> Přesouvání diskuzí do náhradní kategorie může vést k mizení (objevování) příspěvku v závislosti na jiných právech dané kategorie.';

$Definition['About.DisableStatistics'] = 'Pokud máte požadavek na zakázání sledování statistik, přidejte do konfiguračního souboru instalace tento řádek:
<code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'K životu tohoto systému Vanilla, který je zdarma a open-source, jsou tyto statistiky důležité. Nezakazujte tedy prosím reportování těchto statistik.';
$Definition['AboutCommentEmbedding'] = 'Vanilla může být použita místo vašeho stávajícího komentářového systému na vašem blogu. Ve skutečnosti může být použita pro komentáře na jakékoliv stránce vašeho webu.';
$Definition['AboutEmbedding'] = 'Vkládán umožňuje vkládat různé části, nebo celou diskuzi do vašich aplikací nebo webových stránek.';
$Definition['About Vanilla Statistics'] = 'O Vanilla statistikách';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Otevřete fórum komunity kliknutím na odkaz „navštívit stránku“ na horní straně této stránky nebo <a href={/,url}>klikněte sem</a>. Fórum komunity je místo, které všichni vaši uživatelé a zákazníci uvidí, když navštíví <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Přidejte do diskuzí a komentářů omezení rozměrů nahrávaných obrázků.';
$Definition['AddonProblems'] = '<h2>Problémy?</h2><p>Pokud se s doplňkem něco stane a nebude moci používat svoji stránku, můžete je deaktivovat manuálně upravením:</p>%s';
$Definition['AddressBarColorDescription'] = 'Některé prohlížeče podporují barvu adresního řádku. Pouze mobilní.';
$Definition['Alert users if they click external link.'] = 'Upozornit uživatele, pokud kliknou na odkaz v příspěvku, který je povede mimo fórum. Uživatelé nebudou upozorněni, když budou následovat odkazy, které odpovídají důvěryhodné doméně';
$Definition['Alignment'] = 'Zarovnání';
$Definition['Alignment (Mobile)'] = 'Zarovnání (mobilní)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Všechny kategorie uvedeny s výběrem z 5 posledních diskusí pod každou z nich';
$Definition['Allow links to be transformed'] = 'Umožňují transformaci odkazů na vložené reprezentace v diskusích a komentářích. Například odkaz na YouTube se změní na vložené video.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Umožněte uživatelům s oprávněním %s změnit své vlastní avatary ze svých profilových stránek ve Vanille.';
$Definition['ApplicationHelp'] = 'Aplikace vám dávají možnost přidávat na vaši stránku spoustu funkcí.<br />Jakmile aplikaci přidáte do vaší složky %s, můžete ji povolit nebo deaktivovat zde. ';
$Definition['Apply Layout'] = 'Použít rozvržení';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Opravdu chcete toto téma smazat? Bude trvale smazán.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Opravdu jste zadali správný název hostitele databáze? Nespletli jste si název? Nahlášená databáze: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Pro použití e-mailového potvrzení je vyžadována role s „nepotvrzeným“ výchozím typem.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatary budou zmenšeny, pokud překročí tuto výšku.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatary budou zmenšeny, pokud překročí tuto šířku.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatary budou mít své miniatury uloženy v této velikosti.';

$Definition['Background'] = 'Pozadí';
$Definition['Background Image'] = 'Obrázek na pozadí';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Být kreativní! Zkuste pojmenovat své řady podle toho, o čem komunita mluví.';
$Definition['Bordered'] = 'Ohraničené';
$Definition['Borderless'] = 'Bez hranic';
$Definition['Border Radius'] = 'Hraniční poloměr';
$Definition['Brand Color'] = 'Barva značky';
$Definition['Buttons'] = 'Tlačítka';
$Definition['Buttons & Inputs'] = 'Tlačítka a vstupy';
$Definition['Button Type'] = 'Typ tlačítka';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Kliknutím na tlačítko níže navždy odstraníte uživatelský účet %s. ';

$Definition['Center Aligned'] = 'Střed zarovnán';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Změny se týkají pouze nově nahraných avatarů.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Změňte velikosti, ve kterých jsou obrázky avatar uloženy.';
$Definition['Change the way your community works with plugins.'] = 'Změňte způsob, jakým vaše komunita používá pluginy. Pomocí tohoto softwaru jsme propojili populární pluginy a k dispozici jsou další online. ';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Zaškrtávací políčka umožňují správcům provádět hromadné akce na několika diskusích nebo komentářích současně.';
$Definition['Check out our %s'] = 'Podívejte se na naši %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Podívejte se na naši <0>dokumentaci</0> nebo se zeptejte naší <1>komunity odborníků</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla je nejjednodušší, nejvýkonnější komunitní platforma na světě. Její použití je extrémně snadné. Začněte tímto úvodním videem a pokračujte níže uvedenými kroky. Užívejte!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Vyberte roli, která bude přiřazena samotným uživatelům:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Vyberte téma pro tuto podkomunitu. <0> Čtěte více </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Vyberte způsob zpracování veškerého obsahu spojeného s uživatelským účtem pro %s (komentáře, zprávy atd.). ';
$Definition['Choose Image'] = 'Zvolte Obrázek';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Pro podepsání svých požadavků si můžete zvolit vlastní hashovací algoritmus. Hashovací algoritmus musí být používán také v knihovně vašeho klienta. Pokud si nejste jisti výběrem, zvolte md5.';
$Definition['Choose the order items are sorted.'] = 'Zvolte pořadí položek.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Vyberte stránku, kterou by lidé měli vidět při návštěvě <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Vyberte preferované rozložení pro seznamy kategorií.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Vyberte upřednostňované rozložení pro seznamy kategorií. Rozložení vedle sebe můžete upravit.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Vyberte preferované rozložení pro seznamy diskusí.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Vyberte upřednostňované rozložení pro seznamy diskusí. Rozložení nadace můžete upravit.';
$Definition['Color Overlay'] = 'Barevné překrytí';
$Definition['Continue Import'] = 'Pokračovat v importování ';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Importovaný soubor nelze analyzovat. Problém je v blízkosti řádku %s.';
$Definition['Create a localization CSV'] = 'Vytvořte lokalizační CSV';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Vlastní témata jsou vytvořená témata. Můžete je upravit, přejmenovat nebo vytvořit jejich kopii.';

$Definition['Dark'] = 'Temný';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Určete, kdo může nahrávat a spravovat soubory na stránce <a href="%s">Role a oprávnění</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Zadejte domovskou stránku svého fóra, nahrajte své logo a další...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Odstranění role může mít způsobit, že uživatelé nebudou mít přístup k aplikaci.';
$Definition['Deleting forever cannot be undone.'] = 'Mazání je dobrý způsob, jak udržovat ve fóru pořádek. ';
$Definition['Disable Google Sign In'] = 'Deaktivovat přihlášení Google';
$Definition['Disable OpenID'] = 'Deaktivovat OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Na stránce <0>Vanilla Labs deaktivujte experimentální funkci „New Embed System“.</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Kategorie diskusí slouží k tomu, aby pomohly vašim uživatelům organizovat diskusi způsobem, který je pro vaši komunitu smysluplný.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Nevkládejte administrativní palubovku vašeho fóra (roztáhněte na celou obrazovku)';
$Definition['Don\'t use too many reactions.'] = 'Nepoužívejte příliš mnoho reakcí. Nechcete dát svým uživatelům přetížení informací.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Přetáhněte kategorie níže, abyste je mohli třídit a vnořovat.';

$Definition['EditContentTimeout.Notes'] = 'Pokud má uživatel přidělenou roli, která má oprávnění upravovat obsah, tato oprávnění tuto funkci přepíšou. ';
$Definition['Edit Route'] = 'Upravit trasu';
$Definition['Edits to this theme apply to:'] = 'Úpravy tohoto tématu se týkají:';
$Definition['Embed Settings'] = 'Nastavení vložení';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Vložte své komunitní fórum na svoji webovou stránku pro zvýšení angažovanosti... ';
$Definition['Enable and test out the latest Vanilla features.'] = 'Povolte a vyzkoušejte nejnovější funkce Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Umožňuje pokročilé úpravy příspěvků v několika formátech, včetně WYSIWYG, jednoduchého HTML, Markdown a BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Povolte editoru rozložení použít vlastní rozložení pro vaše stránky komunity. Použijte náš nový editor k zobrazení obsahu pomocí našeho katalogu dostupných widgetů.';
$Definition['Enter a descriptive name.'] = 'Zadejte popisný název kapsy. Tento název se zobrazí pouze zde, když budete kapsy spravovat, takže slouží pouze k tomu, aby se vám kapsa lépe pamatovala. ';
$Definition['Enter a short name for the site.'] = 'Zadejte krátký název webové stránky. Zobrazí se na tlačítkách pro přihlášení.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Zadejte adresu svého blogu Wordpress a my už si s tím poradíme.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Níže zadejte nastavení připojení pro váš server sphinx.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Každá editace nebo odstranění se zaznamenává zde. Pro vrácení jakékoliv změny použijte funkci ‘Obnovit’.';
$Definition['Everyone who signs up gets a profile page.'] = 'Každý, kdo se zaregistruje do vaší komunity, získá veřejnou stránku s profilem, kam si může nahrát svůj obrázek, spravovat nastavení profilu a sledovat skvělé novinky ve vaší komunitě. Měli byste si <a href="{/profile,url}">upravit svůj profil nyní</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Každý uživatel na vaší stránce je přiřazen alespoň k jedné roli. Role se používají pro určení toho, co mohou uživatelé dělat.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect umožňuje uživatelům přihlásit se pomocí svého účtu na Facebooku. <b>Aby tento plugin fungoval, musíte svoji aplikaci zaregistrovat na Facebooku.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Nepodařilo se nám připojit k databázi pomocí zadaného uživatelského jména a hesla. Nespletli jste si název? Nahlášená databáze: <code>%s</code>';
$Definition['Font'] = 'Písmo';
$Definition['Font Name'] = 'Název písma';
$Definition['Font URL'] = 'URL písma';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Přinutit palubovku, aby byla přístupná pouze prostřednictvím této adresy URL <em>(nedoporučujeme)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Například můžete zakázat všechny uživatele s e-mailovými adresami z domény  „example.com“ přidáním zákazu typu e-mailu s hodnotou „*@example.com“.';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Pro účely SEO jsou clawleři vyhledávače vyloučeni nutnosti zobrazovat si fórum ve vzdálené url.';
$Definition['Foundation Layout'] = 'Rozložení nadace';
$Definition['Full Bleed'] = 'Plné krvácení';

$Definition['Garden.Import.Complete.Description'] = 'Úspěšně jste dokončili import. Jakmile budete připraveni, klikněte na <b>Hotovo</b>.';
$Definition['Garden.Import.Continue.Description'] = 'Vypadá to, že jste uprostřed importu. Vyberte jednu z následujících možností.';
$Definition['Garden.Import.InputInstructions'] = 'Zadejte e-mail a heslo administrátora z importovaných dat.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Upravte povolení měnit své vlastní avatary ze svých profilových stránek ve Vanille.';
$Definition['Garden.StatisticsDisabled'] = 'Ve svém konfiguračním souboru jste specificky zakázali Vanilla Statistics.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Zdá se, že toto fórum je spuštěno v testovacím prostředí nebo z jiného důvodu hlásí soukromou IP adresu. Ve výchozím nastavení nejsou fóra spuštěná na soukromých adresách IP sledována.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Pokud jste si jisti, že je vaše fórum přístupné z internetu, můžete zařídit, aby se zde zobrazovaly statistiky:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Zdá se, že váš soubor config.php je pouze pro čtení. To znamená, že Vanilla nebude moci automaticky zaregistrovat InstallationID a InstallationSecret vašeho fóra.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Pro vyřešení tohoto problému přiřaďte svému souboru conf/config.php režim 777.';
$Definition['Global Styles'] = 'Globální styly';

$Definition['Heads Up!'] = 'Hlavu vzhůru!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Varování! Toto je zvláštní role, která nepovoluje aktivní relace. Z tohoto důvodu byly možnosti oprávnění omezeny na „zobrazovací“ oprávnění. ';
$Definition['Here are all of the reactions you can use on your site.'] = 'Zde jsou všechny reakce, které můžete na svém webu použít.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Zde jsou pozice, které mohou uživatelé na vašem webu dosáhnout. Tyto řady můžete přizpůsobit a dokonce přidat nové. Zde je několik tipů.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Pokud je nahráno bannerové logo, nahradí název banneru na uživatelsky orientovaných stránkách fóra.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Pokud uživatel stránky během této doby nenavštíví, bude automaticky odhlášen.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Pokud je tato možnost povolena, bude veškerý obsah příspěvků odeslán uživatelům prostřednictvím e-mailových oznámení.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Pokud jste novým jazykem HTML a / nebo CSS, zde je několik návodů, jak začít:';
$Definition['If you have an old theme'] = 'Pokud máte staré téma a potřebujete nastavit samostatné téma pro plochu a mobilní, můžete tak učinit pomocí starého tematického uživatelského rozhraní.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Pokud chcete snížit úroveň varování, odstraňte varování.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Pokud chcete vložit vaše fórum nebo použít Vanilla komentáře ve svém blogu, musíte povolit vkládání. Pokud vkládání nepoužíváte, doporučujeme toto nastavení vypnout.';
$Definition['Image (Mobile)'] = 'Obrázek (mobilní)';
$Definition['Import'] = 'Importovat ';
$Definition['Importing to Vanilla'] = 'Imporování na Vanilla ';
$Definition['In additon to the widgets there are also'] = 'Kromě widgetů existují také <0> Globální styly </0> . Chcete-li upravit globální styly, klikněte kdekoli na stránce, například na tento text.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integrujte stránky nadace a komponenty do svého tématu';
$Definition['Internationalization & Localization'] = 'Internacionalizace a lokalizace';
$Definition['Invalid URL'] = 'neplatná URL';
$Definition['Invitation email failed to send: %'] = 'Přestože byla pozvánka vytvořena úspěšně, e-mail se nepodařilo odeslat. Server ohlásil následující chybu: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Když použijete registraci prostřednictvím pozvánky, uživatelé budou mít na svých profilových stránkách odkaz s názvem <a href="%s" class="Popup">Mé pozvánky</a>.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Zdá se, že zadaná databáze ještě neexistuje. Už jste ji vytvořili? Nespletli jste si název? Nahlášená databáze: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Je dobré nastavit maximální počet znaků povolených v komentáři na rozumně nízkou velikost.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Je vhodné udržet maximální počet znaků povolených v příspěvku na přiměřenou velikost.';

$Definition['Kick-start your community and increase user engagement.'] = 'Spusťte svou komunitu a podpořte zapojení uživatelů.';

$Definition['Labs'] = 'Laboratoře';
$Definition['Layout Editor'] = 'Editor rozvržení';
$Definition['Learn about custom routing.'] = 'Zjistěte více o vlastním směrování. ';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Naučte se, jak zcela změnit vzhled a pocit z fóra: nahrajte své logo, nastavte svou domovskou stránku, vyberte motiv a přizpůsobujte.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Naučte se používat základní funkce svého fóra.';
$Definition['Left Aligned'] = 'Zarovnání doleva';
$Definition['Light'] = 'Světlo';
$Definition['Links'] = 'Odkazy';
$Definition['Locales allow you to support other languages on your site.'] = 'Umístění vám umožňují podporovat na vašich stránkách další jazyky. Umístění můžete povolit a zakázat zde.';
$Definition['LogoDescription'] = 'Logo banneru se zobrazí v horní části webu.';
$Definition['LogoDisclaimer'] = 'Motivy vytvořené pomocí editoru motivů a některá vlastní témata toto nastavení nepoužívají.';
$Definition['Looking for the Old Embed System?'] = 'Hledáte Old Embed System?';

$Definition['Make sure you click View Page'] = 'Nezapomeňte kliknout na <a href="%s">Zobrazit stránku</a>, abyste viděli, jak vaše stránka kategorií vypadá po uložení. ';
$Definition['Manage Routes'] = 'Spravovat trasy ';
$Definition['Managing Users'] = 'Správa uživatelů';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Položky označené jako NENÍ spam budou umístěny zpět do vašeho fóra. ';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Položky označené jako Není spam budou umístěny zpět do vašeho fóra. ';
$Definition['Messages can appear anywhere in your application.'] = 'Zprávy se mohou objevit kdekoli ve vaší aplikaci a mohou být použity k informování uživatelů o novinkách a událostech. Tuto stránku můžete použít k uspořádání zpráv přetažením nahoru nebo dolů.';
$Definition['MobileLogoDescription'] = 'Logo banneru pro mobilní zařízení se zobrazí v horní části webu.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Mobilní témata vám umožňují změnit vzhled a dojem vašeho webu na menších zařízeních.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'Poznámka: Nový editor rozvržení zdědí motiv nastavený ve vašem průvodci styly (formálně editor motivů). <1>Zjistěte více</1>';
$Definition['Need more help?'] = 'Potřebujete další pomoc?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Vnořené kategorie hlouběji než tato hloubka budou zařazeny do seznamu oddělených čárkami.';
$Definition['New Embed System'] = 'Nový systém vkládání';
$Definition['New Quick Links'] = 'Nové rychlé odkazy';
$Definition['New Search Page'] = 'Nová stránka vyhledávání';
$Definition['Not getting what you expect when you preview your theme?'] = 'Nedostanete to, co očekáváte při náhledu motivu?';
$Definition['Notify me when people comment on my addons.'] = 'Upozorněte mě, když se lidé k mým doplňkům vyjádří.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Pro použití e-mailového potvrzení potřebuje tato stránka roli s výchozím typem „nepotvrzeno“. Pro aktivaci tohoto nastavení prosím přidejte tuto roli. ';

$Definition['Once enabled, only members will see inside your community.'] = 'Po aktivaci uvidí vaši komunitu pouze členové.';
$Definition['OrgDescription'] = 'Název vaší organizace je použit pro SEO mikrodata a JSON-LD';
$Definition['Outline'] = 'Obrys';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Přepsané pohledy nebo tematické hity mohou mít nezamýšlené vedlejší účinky a nejsou zobrazeny náhledy.';

$Definition['Password.MinLength'] = 'Minimální povolená délka znaků pro uživatelská hesla na stránkách pro vytváření a resetování hesla.';
$Definition['Please choose an authenticator to configure.'] = 'Vyberte prosím autentizátor, který chcete konfigurovat. ';
$Definition['PluginHelp'] = 'Pluginy vám dávají možnost přidat na vaši stránku další funkce.<br />Jakmile plugin přidáte do své složky %s, může jej odtud povolit nebo zakázat. ';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Kapsa se nachází mezi jednotlivými diskuzemi na hlavním seznamu diskuzí. Protože se diskuze obvykle nachází mezi tagy <li>..</li>, budete muset tyto tagy přidat také k vaší kapse.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Kapsy vám umožňují přidávat HTML ve volné formě do různých míst v aplikaci.';
$Definition['Preset'] = 'Přednastavení';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Spamu na fóru lze předcházet tím, že omezíte počet diskuzí & komentářů, které uživatel může odeslat během určitého časového intervalu.';
$Definition['Primary Button'] = 'Primární tlačítko';
$Definition['Primary Buttons'] = 'Primární tlačítka';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Průvodce rychlým startem pro vytváření témat ve Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Rychlé odkazy jsou výchozí součástí komunitních stránek. Povolením naší nové komponenty Rychlé odkazy můžete přidávat, upravovat nebo skrývat odkazy z této nabídky pomocí našeho editoru motivů.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Hotový plugin Vanilla Comments pro WordPress ';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Hotový plugin fór Vanilla pro WordPress ';
$Definition['Realtime progress bars: %s'] = 'Indikátory průběhu v reálném čase: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Je dobré mít speciální pozice pro moderátory a administrátory, aby vaše komunita mohla snadno vidět, kdo má na starosti.';
$Definition['Recommend starting with five ranks.'] = 'Nechcete mít příliš mnoho pozic. Doporučujeme začít s pěti. Pokud je vaše komunita opravdu velká, můžete přidat další.';
$Definition['Requires “Flag” reaction permission.'] = 'Vyžaduje povolení reakce „Označit“.';
$Definition['Requires “Negative” reaction permission.'] = 'Vyžaduje povolení „negativní“ reakce.';
$Definition['Requires “Positive” reaction permission.'] = 'Vyžaduje povolení „Pozitivní“.';
$Definition['Restoring your selection removes the items from this list.'] = 'Po obnovení budou položky odstraněny z tohoto seznamu a vloženy zpět na web.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Pomocí následující možnosti povolte nabídky pro Rich Editor. To bude platit, pouze pokud je výchozí formátovací formát „Rich“.';
$Definition['Route Expression'] = 'Vyjádření trasy ';
$Definition['Routes are used to redirect users.'] = 'Trasy se používají k přesměrování uživatelů v závislosti na požadované adrese URL.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Vyhledejte uživatele podle jména nebo zadejte název role a zobrazte všechny uživatele s touto rolí.';
$Definition['Secondary Button'] = 'Sekundární tlačítko';
$Definition['Secondary Buttons'] = 'Sekundární tlačítka';
$Definition['Security.Hsts.HTTPSWarning'] = 'Upozornění: Tuto funkci aktivujte pouze tehdy, pokud jste si jisti, že všechny subdomény máte nakonfigurovány na HTTPS s platnými certifikáty.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Po aktivaci se toto pravidlo použije také na veškeré subdomény vašich stránek.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Doporučujeme začít s maximálním stářím 1 týdne a zvýšit je na 1 měsíc teprve tehdy, když uvidíte, že stránky fungují podle očekávání.';
$Definition['Security.Hsts.SubmitWarning'] = 'Upozornění: Nejlepší postup je podpora preloadu HSTS. Aby byl však preload stránek úspěšný, musíte je odeslat do hstspreload.org (tj. získat plnou ochranu uvažované konfigurace).';
$Definition['See the documentation'] = 'Viz Dokumentace';
$Definition['Select the default type for this role, if any.'] = 'Vyberte výchozí typ této role, pokud existuje.';
$Definition['Select the import source'] = 'Vyberte zdroj importu ';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Zrušení serializace serializovaného sloupce „%s“ se nezdařilo.';
$Definition['Session Timeout'] = 'Časový limit relace';
$Definition['Shadowed'] = 'Stínované';
$Definition['ShareImageDescription'] = 'Když někdo sdílí odkaz z vašeho webu, pokusíme se obrázek ze stránky chytit. Pokud na stránce není obrázek, použijeme tento obrázek. Obrázek by měl být alespoň 50 × 50, ale doporučujeme 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Zapněte tuto možnost, pokud chcete zobrazit všechna možná umístění kapes. Zapnutí této možnosti zobrazí umístění pouze uživatelům, kteří mohou spravovat kapsy.';
$Definition['Solid'] = 'Pevný';
$Definition['Some older themes don\'t support full editing capability.'] = 'Některá starší témata nepodporují plnou editaci. Chcete-li zjistit, co motiv podporuje, můžete umístit kurzor nad jeho název a zjistit, kde se úpravy projeví.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Některá témata mohou vyžadovat aktualizaci, aby fungovala s následující kategorií. Tuto funkci můžete zakázat při aktualizaci motivu.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Někdy chcete vložit svůj Vanilla web na jiný web. Vanilkový embed systém k tomu nabízí snadný způsob. Při používání vestavěného webu dochází ke kompromisům ve výkonu, proto si v dokumentaci vyhledejte alternativy a ideální případy použití.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Zvláštní omezení: Tuto reakci mohou použít pouze uživatelé s povolením Garden.Curation.Manage.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Při vytváření zákazu zadejte částečnou nebo úplnou shodu.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Zkuste tu trochu popřemýšlet o tom, jak byste svoji stránku popsali. Smysluplný název a stručný popis může posílit vaši pozici ve výsledcích vyhledávání. ';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Upravte své e-maily přidáním loga a přizpůsobením barev.';
$Definition['Start Import'] = 'Začít import';
$Definition['Start the first discussion.'] = 'Zvyšte produktivitu ve vaší komunitě tím, že <a href="{/post/discussion,url}">začnete první diskuzi</a> nyní.';
$Definition['Subcommunities'] = 'Podskupiny';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Značkování umožňuje uživatelům přidat značku do diskusí, které začínají, aby byli lépe objevitelní.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Šablony jsou standardní témata. Chcete-li je upravit, musíte vytvořit kopii.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Nástroj pro ověření %s nenabízí žádné vlastní možnosti konfigurace.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'Poznámka: Laboratoř <0/> je třeba nakonfigurovat tak, aby odpovídala vašemu vlastnímu motivu. To lze provést pomocí našeho nového editoru motivů. <1> Zjistěte více.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Doplněk nelze aktivovat, protože generoval závažnou chybu: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Doplněk již byl stažen.';
$Definition['The banner logo appears at the top of your forum.'] = 'Logo záhlaví se zobrazuje v hlavičce vašeho fóra. ';
$Definition['The banner title appears on the top-left of every page.'] = 'Nadpis záhlaví se zobrazuje v horní-levé části každé stránky.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Název banneru se zobrazí na banneru na vaší webové stránce a v záhlaví prohlížeče. Mělo by být méně než 20 znaků. Pokud nahrajete bannerové logo, nahradí název banneru na uživatelsky orientovaných stránkách fóra. Také mějte na paměti, že některá témata mohou skrýt i tento název.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Základní registrační formulář po nových uživatelích vyžaduje</strong> opsat text z obrázku CAPTCHA, aby se na stránku nedostali spammeři. Musíte si vytvořit účet na stránce <a href="http://recaptcha.net/">recaptcha.net</a>. Registrace je jednoduchá a ZDARMA. Jakmile se zaregistrujete, vraťte se zpět sem a zadejte následující nastavení: ';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Zadaný uživatel databáze nemá oprávnění k přístupu k databázi. Už jste databázi vytvořili? Nahlášená databáze: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Pro vaši databázi jsou vyžadovány následující změny struktury.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Nadpis domácí stránky je zobrazen na domácí stránce fóra. Vyberte takový nadpis, který byste chtěli, aby byl zobrazen ve vyhledávačích.';
$Definition['The import file does not contain any data.'] = 'Soubor importu neobsahuje žádná data. ';
$Definition['The import file is not in the correct format.'] = 'Soubor importu není ve správném formátu. ';
$Definition['The location of the authentication endpoint.'] = 'Umístění ověřovacího koncového bodu.';
$Definition['ThemeHelp'] = 'Témata vám umožňují měnit vzhled a náladu vaší stránky. <br />Jakmile téma přidáte do své složky %s, můžete jej odtud povolit.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Náhled motivu je omezen na zobrazení šablony motivu a css.';
$Definition['The New Embed System'] = 'Nový systém vkládání';
$Definition['The new embed system has improved performance.'] = 'Nový systém vkládání má vylepšený výkon, vylepšené chování posouvání a konzistentnější chování než ten starý. V současné době nejsou vkládání komentářů a wordpressu v novém systému vkládání podporováno.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Password Authenticator nenabízí žádné možnosti konfigurace. ';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Nejsou zapotřebí žádné změny struktury databáze. Může ale dojít ke změně dat. ';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'V aplikaci existují dva typy tlačítek: primární a sekundární.';
$Definition['The route was saved successfully.'] = 'Trasa byla úspěšně uložena.';
$Definition['The text of the pocket.'] = 'Zadejte text kapsy. Výstup bude vypadat přesně tak, jak jej napíšete. Ujistěte se tedy, že zadáváte platnou HTML.';
$Definition['The user table was not in the import file.'] = 'Uživatelská tabulka nebyla v souboru importu.';
$Definition['The Vanilla 2 Exporter'] = 'Exportér Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Díky Vanilla Statistics se palubovka vašeho fóra promění na analytický nástroj, který vám umožní kontrolovat aktivitu ve vašem fóru v určitých časových obdobích. Více o <a href="http://vanillaforums.org/docs/vanillastatistics">Vanilla Statistics si můžete přečíst</a> v naší dokumentaci.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Fungují stejně jako běžná témata. Po přidání do složky motivů ji můžete povolit zde.';
$Definition['This is a style guide of your theme.'] = 'Toto je průvodce stylem vašeho tématu. Obsahuje příklady vizuálních prvků používaných v celé aplikaci. Můžete kliknout na různé widgety, například na <0> záhlaví </0> nebo <1> Banner </1> upravit jejich vlastnosti v postranním panelu.';
$Definition['This is the administrative dashboard for your new community.'] = 'Toto je administrativní palubovka pro vaši novou komunitu. Podívejte se na možnosti konfigurace, které najdete na straně. Odtud můžete nastavit fungování vaší komunity. <b>Ve výchozím nastavení mohou tuto část ve vaší komunitě vidět pouze uživatelé s rolí „Administrátor“.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Zde můžete povolit a vyzkoušet nové funkce, stránky a komponenty Vanilla.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Tuto experimentální funkci nelze deaktivovat, protože je použito vlastní rozvržení.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Tuto laboratoř nelze deaktivovat, protože to vyžaduje aktuální téma.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Tato volba zobrazuje/skrývá umístění, kam se vaše kapsy mohou dostat, ale pouze pro uživatele s oprávněním k přidávání/úpravě kapes. Zkuste si zobrazit umístění a poté navštívit svoji stránku. ';
$Definition['This page lists the endpoints of your API.'] = 'Na této stránce jsou uvedeny koncové body vašeho API. Kliknutím na koncové body získáte další informace. Z této stránky můžete uskutečňovat přímá volání do rozhraní API nebo externě pomocí přístupového tokenu.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Tato role je osobní informace. Zobrazí se pouze uživatelům s povolením k prohlížení osobních údajů.';
$Definition['This setting loads the page before executing Javascript.'] = 'Toto nastavení načte stránku před spuštěním Javascriptu, což může vylepšit vaše SEO. <br> <strong>** Varování: Povolení této funkce může způsobit chyby Javascriptu na vašem webu. **</strong>';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Toto téma nelze odstranit, protože je aktuálně použitým motivem.';
$Definition['Tiled Layout'] = 'Rozložení kachlů';
$Definition['Title Bar'] = 'Titulek';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Pokud chcete fórum Vanilla vložit na své webové stránky, použijte následující kód.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Příliš mnoho adres! Najednou odešleme maximálně %s adres. ';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Abychom předešli zneužití, některé nástroje automaticky skrývají obsah a uvedou jej zde, dokud jej neschválí moderátor. ';
$Definition['TouchIconDescription'] = 'Dotyková ikona se objeví, když si na domovské obrazovce zařízení Apple uložíte záložku. Jedná se obvykle o 152 pixelů. Apple přidává zaoblené rohy a světelný efekt automaticky.';
$Definition['Transparent'] = 'Průhledný';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect umožňuje uživatelům přihlásit se pomocí svého účtu na Twitteru. <b>Aby tento plugin fungoval, musíte svoji aplikaci zaregistrovat na Twitteru.</b>';

$Definition['Usercards'] = 'Karty uživatelů';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Usercards vám umožní získat rychlý in-line snímek informací o uživateli. Při prohlížení příspěvků a výsledkových tabulek kliknutím na uživatelské jméno zobrazíte kartu se základními informacemi o profilu uživatele, aniž byste museli opustit stránku. Povolením této funkce přidáte do svého vlastního motivu uživatelské karty.';
$Definition['User inputs are based on the global background and text colors.'] = 'Uživatelské vstupy jsou založeny na globálních barvách pozadí a textu.';
$Definition['User Profile'] = 'Uživatelský profil';
$Definition['Users may sign into your site using their Twitter account.'] = 'Uživatelé se mohou přihlásit na váš web pomocí svého účtu Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Pomocí tlačítka v horní části stránky vytvořte pravidlo zákazu.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Pro nastavení Vanilla Comments na svém blogu použijte plugin WordPress, nebo použijte univerzální kód pro nastavení Vanilla Comments na jakékoli jiné platformě.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Nová vyhledávací služba Vanilla je konečně tady. Povolením našeho nového uživatelského rozhraní vyhledávací stránky získáte přístup k nejnovějším funkcím vyhledávání, jako je vyhledávání členů, třídění vyhledávání a zvýrazňování výrazů.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Export Vanilla: %s, Zdroj: %s';
$Definition['Vanilla Statistics are currently disabled'] = 'Doplněk Vanilla Statistics je v tuto chvíli deaktivován ';
$Definition['Verify and restore'] = 'Ověřte a obnovte';
$Definition['VerifyUser'] = 'Zaškrtněte políčko vedle uživatele a označte jej jako <b>Ověřeného,</b> aby jeho příspěvky již nebyly označeny jako spam. Tím se také obnoví všechny jeho nevyřízené příspěvky.';
$Definition['Video tutorial on advanced settings'] = 'Video tutoriál o pokročilých nastaveních';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video tutoriál o hledání a spravování uživatelů ';
$Definition['Video tutorial on managing appearance'] = 'Video tutoriál o spravování vzhledu';
$Definition['Video tutorial on managing categories'] = 'Video tutoriál o spravování kategorií';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video tutoriál o spravování rolí a oprávnění';
$Definition['Video tutorial on user registration'] = 'Video tutoriál o registraci uživatele ';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Upozornění: Aktivace této funkce může na vašem webu způsobit chyby jazyka Javascript.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Upozornění</b> : Konfigurace serveru nepodporuje rychlé načítání dat. Pokud importujete velmi velký soubor (např. Přes 200 000 komentářů), měli byste zvážit změnu konfigurace. Klikněte <a href="http://vanillaforums.com/porter">zde</a> pro více informací.';
$Definition['Warning: This is for advanced users.'] = '<b>Varování</b>: Tato funkce je pro pokročilé uživatele a vyžaduje, abyste provedli další změny na svém webovém serveru. Tato funkce je obvykle k dispozici pouze v případě, že máte vyhrazený nebo vps hosting. Nepokoušejte se tuto funkci zapnout, pokud nevíte, co děláte. ';
$Definition['Webhooks'] = 'Webhooky';
$Definition['Welcome to Labs!'] = 'Vítejte v laboratořích!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Vítejte v uživatelském rozhraní s tématikou Vanilla. Tato stránka obsahuje seznam všech dostupných témat a umožňuje vám je zkopírovat nebo upravit.';
$Definition['Welcome To Your Theme'] = 'Vítejte ve vašem tématu';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Doporučujeme většinou pozitivní reakce na podporu účasti.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Pokud je povoleno, můžete spravovat produkty a seskupovat podkomunity podle těchto produktů.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Pokud vyberete možnost Plné krvácení, bude vaše pozadí průhledné.';
$Definition['Which reactions you use really depends on your community.'] = 'Které reakce skutečně použijete, záleží na vaší komunitě, ale doporučujeme mít na paměti několik bodů.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Chystáte se použít novou možnost rozložení. To lze přizpůsobit a zobrazit náhled pomocí našeho editoru motivů. <0> Další informace</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Můžete zakázat všechny uživatele s IP adresami začínajícími „111.111.111“ přidáním zákazu typu IP s hodnotou „111.111.111.*“.';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Můžete zakázat IP adresy, e-mailové adresy a uživatelská jména.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Můžete si vybrat z jednoho z různých stylů, které toto téma nabízí.';
$Definition['You can configure some values differently for different screensizes.'] = 'Některé hodnoty můžete konfigurovat různě pro různé velikosti obrazovky.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Můžete se připojit k více webovým stránkám, které podporují protokol jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Pokud je soubor příliš velký pro přímé nahrání na tuto stránku, můžete jej umístit do své složky /uploads. Ověřte si, že název souboru začíná slovem <b>export</b> a končí jednou z přípon <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Můžete určit minimální délku příspěvku, abyste odradili krátké příspěvky.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Do systému Theming můžete nahrát vlastní písmo. Stačí zkopírovat a vložit adresu URL do pole.';
$Definition['You must select a file to import.'] = 'Musíte vybrat soubor k importování.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Do <0> povolených domén musíte přidat doménu adresy URL písma </0> v konfiguraci webu. <1> Další informace o uživatelských fontech. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Vaše mobilní téma bude deaktivováno. Chcete-li nastavit různá témata pro mobily a počítače, použijte staré tematické uživatelské rozhraní.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Název vaší organizace je použit pro SEO mikrodata a JSON-LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Favikona vašich stránek se zobrazuje na hlavní liště prohlížeče. Odpovídajícím způsobem se zmenší.';
