<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Rhybudd: Gall galluogi\'r nodwedd hon achosi gwallau Javascript ar eich gwefan.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Dalier Sylw!</strong> Gall dileu rôl achosi i ddefnyddwyr fethu cael mynediad i\'r rhaglen.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Dalier Sylw!</strong> Gall symud trafodaethau i gategori arall achosi i drafodaethau ddiflannu (neu ymddangos) os oes gan y categori newydd hawliau gwahanol i\'r un gafodd ei ddileu.';

$Definition['About.DisableStatistics'] = 'Os oes rhaid i chi analluogi adrodd y data yma oherwydd rhesymau busnes, gallwch wneud hynny drwy ychwanegu llinell ganlynol i ffeil ffurfweddu eich gosodiad: <code>$Configuration [\'ardd\'] [\'Analytics\'] [\'Enabled\'] = ANWIR;</code>';
$Definition['About.VanillaStatistics'] = 'Mae\'n allweddol i lwyddiant y meddalwedd ffynhonnell agored hwn sydd ar gael am ddim ein bod yn mesur cyrhaeddiad ac effeithiolrwydd Vanilla. Gofynnwn i chi beidio ag analluogi adrodd y data yma.';
$Definition['AboutCommentEmbedding'] = 'Gellir defnyddio Vanilla yn hwylus yn lle system gwneud sylwadau cynhenid eich blog. A dweud y gwir, gellir ei ddefnyddio i ychwanegu sylwadau at unrhyw dudalen ar y we.';
$Definition['AboutEmbedding'] = 'Mae ymgorffori yn golygu bod eich cymuned, neu ran ohonni, yn cael ei hymgorffori mewn rhaglenni a gwefannau eraill.';
$Definition['About Vanilla Statistics'] = 'Am ystadegau Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Cewch fynediad at eich fforwm cymunedol drwy glicio ar ddolen "Ymweld â safle" ar frig y dudalen hon, neu drwy <a href={/,url}> glicio yma</a>. Bydd eich holl ddefnyddwyr a chwsmeriaid yn gweld y fforwm gymunedol trwy ymweld â <a href="{/,url,domain}"> {/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Ychwanegwch derfynau at ddimensiynau uwchlwytho delweddau mewn trafodaethau a sylwadau.';
$Definition['AddonProblems'] = '<h2>Problemau?</h2> <p>Os aiff rhywbeth o\'i le gyda ychwanegyn fel na allwch ddefnyddio\'ch safle, gallwch eu hanalluogi eich hun trwy olygu:</p> %s';
$Definition['AddressBarColorDescription'] = 'Mae rhai porwyr yn cefnogi lliw ar gyfer y bar cyfeiriad. Symudol yn unig.';
$Definition['Alert users if they click external link.'] = 'Rhybuddiwch ddefnyddwyr os ydyn nhw\'n clicio dolen mewn post a fydd yn eu harwain i ffwrdd o\'r fforwm. Ni fydd defnyddwyr yn cael eu rhybuddio wrth ddilyn dolenni sy\'n cyfateb i Barth dibynadwy';
$Definition['Alignment'] = 'Aliniad';
$Definition['Alignment (Mobile)'] = 'Aliniad (Symudol)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Pob categori a restrwyd ynghyd a detholiad o 5 trafodaeth diweddar o bob un';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Caniatáu i ddefnyddwyr y caniatâd %s i newid eu avatars eu hunain o\'u tudalennau proffil yn Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Anhysbys Cyfeiriadau IP';
$Definition['ApplicationHelp'] = 'Mae rhaglenni yn caniatáu i chi ychwanegu grwpiau mawr o ffwythiannau i\'ch safle. < br / > unwaith y bydd rhaglen wedi\'i ychwanegu at eich ffolder %s, gallwch ei alluogi neu analluogi yma.';
$Definition['Apply Layout'] = 'Cymhwyso Cynllun';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Ydych chi\'n sicr am ddileu\'r thema hon? Bydd yn cael ei ddileu yn barhaol.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Ydych chi\'n siŵr bod wedi rhoi enw\'r gweinydd cronfa ddata cywir? Ydych chi wedi ei gamdeipio? Adroddodd y gronfa ddata: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Mae angen rōl gyda\'r math diofyn "heb ei gadarnhau" er mwyn gallu defnyddio e-bost cadarnhau.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Cadw drafftiau o drafodaethau, cwestiynau, syniadau a sylwadau heb eu cyhoeddi yn awtomatig.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Bydd afatars yn cael eu graddio i lawr os ydyn nhw\'n uwch na\'r uchder hwn.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Bydd afatarau\'n cael eu graddio i lawr os ydyn nhw\'n fwy na\'r lled hwn.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Bydd bawd bawd Avatars yn cael ei arbed ar y maint hwn.';

$Definition['Background'] = 'Cefndir';
$Definition['Background Image'] = 'Delwedd Cefndir';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Byddwch yn greadigol! Ceisiwch enwi eich rhengoedd ar ôl pethau y mae\'r gymuned yn siarad amdanynt.';
$Definition['Bordered'] = 'Wedi\'i ffinio';
$Definition['Bordered (Unified)'] = 'Bordered (Unedig)';
$Definition['Borderless'] = 'Yn ddiderfyn';
$Definition['Border Radius'] = 'Radiws y Gororau';
$Definition['Brand Color'] = 'Lliw Brand';
$Definition['Buttons'] = 'Botymau';
$Definition['Buttons & Inputs'] = 'Botymau a Mewnbynnau';
$Definition['Button Type'] = 'Math o Botwm';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Drwy glicio ar y botwm isod, byddwch yn dileu cyfrif defnyddiwr ar gyfer %s am byth.';

$Definition['Center Aligned'] = 'Alinio Canolfan';
$Definition['Changes to the set day will take affect the following week.'] = 'Bydd newidiadau i\'r diwrnod penodol yn cael eu heffeithio yr wythnos ganlynol.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Bydd newidiadau yn berthnasol i afatarau sydd newydd eu llwytho i fyny yn unig.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Newidiwch y meintiau y mae delweddau avatar yn cael eu cadw ynddynt.';
$Definition['Change the way your community works with plugins.'] = 'Newid y ffordd y mae eich cymuned yn gweithio gydag ategion. Rydym wedi bwndelu ategion poblogaidd gyda\'r meddalwedd, ac mae mwy ar gael ar-lein.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Mae blychau gwirio yn caniatáu i edmygwyr gyflawni gweithredoedd swp ar nifer o drafodaethau neu sylwadau ar yr un pryd.';
$Definition['Check out our %s'] = 'Edrychwch ar ein %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Edrychwch ar ein dogfen <0></0> , neu gofynnwch i\'n <1>cymuned o arbenigwyr</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla yw\'r llwyfan cymunedol symlaf a mwyaf pwerus yn y byd. Mae\'n eithriadol o hawdd i\'w defnyddio. Dechreuwch gyda\'r fideo rhagarweiniol hwn a pharhau gyda\'r camau isod. Mwynhewch!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Dewiswch rôl fydd yn cael ei neulltio ar gyfer defnyddiwr amddifad:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Dewiswch thema ar gyfer yr is-gymuned hon. <0> Darllenwch fwy </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Dewis sut i drin yr holl gynnwys sy\'n gysylltiedig â chyfrif defnyddiwr ar gyfer %s (sylwadau, negeseuon, ac ati).';
$Definition['Choose Image'] = 'Dewiswch Delwedd';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Gallwch ddewis algorithm hash personol i lofnodi eich ceisiadau. Rhaid defnyddio\'r algorithm hash yn eich llyfrgell cleient hefyd. Dewiswch md5 os nad ydych yn siŵr beth i\'w ddewis.';
$Definition['Choose the order items are sorted.'] = 'Dewiswch yr eitemau archebu yn cael eu didoli.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Dewiswch y dudalen y dylai pobl ei gweld pan fyddant yn ymweld â <0 />';
$Definition['Choose the preferred layout for lists of categories.'] = 'Dewiswch y cynllun a ffefrir ar gyfer rhestrau o gategorïau.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Dewiswch y cynllun a ffefrir ar gyfer rhestrau o gategorïau. Gallwch olygu\'r Cynllun Teils.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Dewiswch y cynllun a ffefrir ar gyfer rhestrau o drafodaethau.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Dewiswch y cynllun a ffefrir ar gyfer rhestrau o drafodaethau. Gallwch olygu\'r Cynllun Sylfaen.';
$Definition['Color Overlay'] = 'Troshaen Lliw';
$Definition['Continue Import'] = 'Parhau i Fewnforio';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Methu dosrannu ffeil mewnforio. Mae\'r broblem yn agos at linell %s.';
$Definition['Create a localization CSV'] = 'Creu CSV lleoleiddio';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Themâu Custom yw\'r themâu y gwnaethoch chi eu creu. Gallwch olygu, ailenwi neu wneud copi ohonynt.';

$Definition['Dark'] = 'Tywyll';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Diffinio pwy all lwytho a rheoli ffeiliau ar y dudalen <a href="%s"> Hawliau & rôlau</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Diffinio hafan eich fforwm, uwchlwytho eich logo, a mwy...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Gall dileu rôl achosi i ddefnyddwyr beidio cael mynediad i\'r rhaglen.';
$Definition['Deleting forever cannot be undone.'] = 'Mae dileu yn ffordd dda i gadw eich fforwm yn lân.';
$Definition['Digest Settings'] = 'Gosodiadau Crynhoad';
$Definition['Disable Google Sign In'] = 'Analluogi arwyddo mewn Google';
$Definition['Disable OpenID'] = 'Analluogi OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Analluoga\'r labordy "New Embed System" ar dudalen <0>Vanilla Labs</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Defnyddir y categorïau drafodaeth i helpu eich defnyddwyr a threfnu eu trafodaethau mewn ffordd sy\'n ystyrlon ar gyfer eich cymuned.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Peidio ymgorffori dangosfwrdd gweinyddol eich fforwm (Neidio allan i sgrin lawn)';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Llusgwch a gollwng y categorïau isod i\'w ddidoli a\'u nythu.';

$Definition['EditContentTimeout.Notes'] = 'Os yw\'r defnyddiwr yn yn rôl y mae hawl i olygu\'r cynnwys, bydd yr hawliau hynny yn diystyru hyn.';
$Definition['Edit Route'] = 'Golygu\'r llwybr';
$Definition['Edits to this theme apply to:'] = 'Mae golygiadau i\'r thema hon yn berthnasol i:';
$Definition['Email digests will be sent on the selected day every week.'] = 'Bydd crynodebau e-bost yn cael eu hanfon ar y diwrnod a ddewiswyd bob wythnos.';
$Definition['Email sent from the application will be addressed from this email address'] = 'Bydd e-bost a anfonir o\'r cais yn cael ei gyfeirio o\'r cyfeiriad e-bost hwn';
$Definition['Email sent from the application will be addressed from this name'] = 'Bydd e-bost a anfonir o\'r cais yn cael ei gyfeirio o\'r enw hwn';
$Definition['Email Settings'] = 'Gosodiadau E-bost';
$Definition['Embed Settings'] = 'Mewnosod Gosodiadau';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Ymgorffori eich Fforwm cymunedol yn eich gwefan i ymgysylltu mwy...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Galluogi a phrofi nodweddion diweddaraf Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Yn galluogi golygu swyddi mewn sawl fformat yn uwch, gan gynnwys WYSIWYG, HTML syml, Markdown, a BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Galluogi\'r Golygydd Cynllun i gymhwyso cynllun wedi\'i deilwra ar gyfer eich tudalennau cymuned. Defnyddiwch ein golygydd newydd i gynnwys cynnwys gan ddefnyddio ein catalog o widgets sydd ar gael.';
$Definition['Enter a descriptive name.'] = 'Rhowch enw disgrifiadol i\'r boced. Ni fydd yr enw yma\'n ymddangos unrhywle heblaw wrth reoli eich pocedi yma felly defnyddir yn unig i\'ch helpu chi i gofio\'r boced.';
$Definition['Enter a short name for the site.'] = 'Rhowch enw byr ar gyfer y safle. Mae hyn yn cael ei arddangos ar y botymau mewgofnodi.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Rhowch gyfeiriad eich blog Wordpress a byddwn yn gofalu am bethau o hynny ymlaen.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Rhowch y gosodiadau cysylltiad ar gyfer eich gweinydd sphinx isod.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Cofnodir pob golygu neu dileu yma. Defnyddiwch \'Adfer\' i ddad-wneud unrhyw newid.';
$Definition['Everyone who signs up gets a profile page.'] = 'Mae pawb sydd yn ymuno a\'ch cymuned yn cael tudalen broffil cyhoeddus lle gallant uwchlwytho llun o\'u hunain, a rheoli eu gosodiadau proffil a dilyn pethau difyr sy\'n digwydd yn y gymuned. Dylech chi <a href="{/profile,url}"> addasu eich proffil nawr</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Mae pob defnyddiwr yn eich safle yn cael ei neilltuo i o leiaf un rôl. Caiff rôlau eu defnyddio i benderfynu beth mae\'r defnyddwyr yn cael ei wneud.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Mae cyswllt Facebook yn caniatáu i ddefnyddwyr i logio i mewn gan ddefnyddio eu cyfrif Facebook. <b>Rhaid i chi gofrestru eich rhaglen gyda Facebook i wneud i\'r ategyn hwn weithio.</b>i ';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Wedi methu cysylltu a\'r gronfa ddata gan ddefnyddio\'r enw defnyddiwr a\'r cyfrinair roesoch chi. Wnaethoch chi gamgymeriad?  Adroddodd y gronfa ddata: <code>%s</code>';
$Definition['Font'] = 'Ffont';
$Definition['Font Name'] = 'Enw Ffont';
$Definition['Font URL'] = 'URL ffont';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Gorfodi\'r mynediad i\'r dangosfwrdd trwy\'r url hwn yn unig <em>(gwell peidio)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Er enghraifft, gallwch wahardd pob defnyddiwr â chyfeiriadau e-bost rhag "example.com" trwy ychwanegu gwaharddiad math e-bost gyda\'r gwerth "*@example.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'I ddibenion SEO, mae chwilwyr peiriannol wedi\'u eithrio rhag cael eu gorfodi i weld y fforwm yn yr URL pell.';
$Definition['Foundation Layout'] = 'Cynllun Sylfaen';
$Definition['Full Anonymization'] = 'Anhysbysiad Llawn';
$Definition['FullAnonymization.Description'] = '<strong>Mae Anonymization Llawn</strong> yn disodli pob cyfeiriad IP unigol gyda 0.0.0.0 i bob pwrpas yn gwadu i\'r cais unrhyw fynediad at waith gyda chyfeiriadau IP. Ni fydd rheolau gwahardd IP yn gweithio o gwbl yn yr achos hwn.';
$Definition['Full Bleed'] = 'Gwaedu Llawn';

$Definition['Garden.Import.Complete.Description'] = 'Wedi gorffen mewnforio.
   Cliciwch <b>Gorffen</b> pan fyddwch yn barod.';
$Definition['Garden.Import.Continue.Description'] = 'Mae\'n ymddangos eich bod yng nghanol mewnforio. Dewiswch un o\'r opsiynau canlynol.';
$Definition['Garden.Import.InputInstructions'] = 'Rhowch e-bost a chyfrinair defnyddiwr gweinyddol o\'r data sy\'n cael ei fewnforio.';
$Definition['Garden.Privacy.IPs.Description'] = 'Mae cyfeiriadau IP defnyddwyr fel arfer yn cael eu casglu at ddibenion rheolau gwahardd awtomataidd, cymedroli ac atal sbam. Bydd galluogi Anhysbysiad IP yn gwneud yr holl gyfeiriadau IP sy\'n cael eu holrhain yn y wefan yn ddienw at unrhyw ddiben, a bydd yn lleihau effeithiolrwydd yr offer hyn. Nid yw newidiadau i\'r gosodiad hwn yn ôl-weithredol.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit caniatâd i newid eu avatars eu hunain o\'u tudalennau proffil yn Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Rydych chi wedi analluogi Ystadegau Vanilla yn eich ffeil ffurfweddu.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Ymddengys bod y fforwm hwn yn rhedeg mewn amgylchedd prawf, neu fel arall mae\'n adrodd IP preifat. Nid yw fforymau sy\'n rhedeg ar  IPs preifat yn cael eu tracio\'n ddiofyn.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Os ydych chi\'n siŵr eich fod Fforwm yn hygyrch o\'r rhyngrwyd gellir ei alluogi i adrodd ystadegau yma:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Ymddengys bod eich ffeil config.php yn darllen-yn-unig. Mae hyn yn golygu y na all Vanilla gofrestru InstallationID na InstallationSecret eich Fforwm yn awtomatig.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'I ddatrys y broblem hon, gosodwch fodd 777 i\'ch ffeil conf/config.php.';
$Definition['Global Styles'] = 'Arddulliau Byd-eang';

$Definition['Heads Up!'] = 'Pennau i Fyny!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Dalier Sylw! Mae hon yn rôl arbennig nad yw\'n caniatáu sesiynau gweithredol. Oherwydd hyn mae dewisiadau hawliau wedi eu cyfyngu i hawliau "gweld".';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Dyma\'r rhengoedd y gall defnyddwyr eu cyflawni ar eich gwefan. Gallwch chi addasu\'r rhengoedd hyn a hyd yn oed ychwanegu rhai newydd. Dyma rai awgrymiadau.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Os yw logo baner wedi ei uwchlwytho, bydd yn disodli\'r baner teitl ar dudalennau fforwm sy\'n wynebu\'r defnyddwyr.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Os na fydd defnyddiwr yn ymweld â\'r wefan o fewn y cyfnod hwn, bydd yn cael ei allgofnodi\'n awtomatig.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Os yw wedi\'i alluogi, bydd cynnwys llawn swyddi yn cael ei anfon mewn hysbysiadau e-bost at ddefnyddwyr.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Os ydych chi\'n newydd i HTML a / neu CSS, dyma rai sesiynau tiwtorial i\'ch rhoi ar ben ffordd:';
$Definition['If you have an old theme'] = 'Os oes gennych hen thema ac angen gosod bwrdd gwaith a thema symudol ar wahân gallwch wneud hynny gyda\'r hen UI theming.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Os ydych am i ostwng y lefel rhybudd wedyn tynnwch rhybudd.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Os ydych chi am wreiddio\'ch fforwm neu ddefnyddio sylwadau Vanilla yn eich blog yna mae angen i chi alluogi ymgorffori. Os nad ydych yn defnyddio gwreiddio, rydym yn argymell gadael y gosodiad hwn i ffwrdd.';
$Definition['Image (Mobile)'] = 'Delwedd (Symudol)';
$Definition['Import'] = 'Mewnforio';
$Definition['Importing to Vanilla'] = 'Mewnforio i Vanilla';
$Definition['In additon to the widgets there are also'] = 'Yn ychwanegol at y teclynnau mae yna hefyd <0> Global Styles </0> . I olygu arddulliau byd-eang cliciwch unrhyw le arall ar y dudalen, fel y testun hwn.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integreiddio Tudalennau a Chydrannau Sylfaen i\'ch Thema';
$Definition['Internationalization & Localization'] = 'Rhyngwladoli a Lleoleiddio';
$Definition['Invalid URL'] = 'URL annilys';
$Definition['Invitation email failed to send: %'] = 'Er i\'r gwahoddiad gael ei greu\'n llwyddiannus, methodd yr e-bost ag anfon. Adroddodd y gweinydd y gwall canlynol: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Pan ydych yn defnyddio cofrestru trwy wahoddiad bydd defnyddwyr yn derbyn cyswllt o\'r enw <a href="%s" class="Popup"> Fy gwahoddiadau</a> ar eu tudalennau proffil.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Mae\'n ymddangos nad yw\'r gronfa ddata a nodwyd gennych yn bodoli eto. Ydych chi wedi ei chreu eto? Wnaethoch chi yn gamdeipio\'r enw? Adroddodd y gronfa ddata: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Mae\'n syniad da i gadw y nifer uchaf o nodau a ganiateir mewn sylw i lawr i faint rhesymol.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Mae\'n syniad da cadw\'r nifer uchaf o gymeriadau a ganiateir mewn post i lawr i faint rhesymol.';

$Definition['Kick-start your community and increase user engagement.'] = 'Hwb eich cymuned a chynyddu ymgysylltiad defnyddwyr.';

$Definition['Layout Editor'] = 'Golygydd Gosodiad';
$Definition['Learn about custom routing.'] = 'Dysgwch am lwybro personol.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Dysgwch sut i newid naws eich fforwm yn llwyr: uwchlwytho eich logo, gosod eich hafan, dewisw thema ac addasu.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Dysgu sut i ddefnyddio swyddogaeth sylfaenol eich Fforwm.';
$Definition['Left Aligned'] = 'Wedi\'i adael wedi\'i alinio';
$Definition['Light'] = 'Golau';
$Definition['Links'] = 'Dolenni';
$Definition['Locales allow you to support other languages on your site.'] = 'Mae\'r locales yn caniatáu ichi gefnogi ieithoedd eraill ar eich safle. Galluogwch neu analluogwch y locales yr hoffech eu darparu yma.';
$Definition['Lockout Time (seconds)'] = 'Amser cloi allan (eiliadau)';
$Definition['LogoDescription'] = 'Mae logo\'r faner yn ymddangos ar frig eich gwefan.';
$Definition['LogoDisclaimer'] = 'Nid yw\'r themâu a wneir gyda\'r golygydd thema a rhai themâu arfer yn defnyddio\'r gosodiad hwn.';
$Definition['Looking for the Old Embed System?'] = 'Chwilio am yr Old Embed System?';

$Definition['Make sure you click View Page'] = 'Gofalwch glicio <a href="%s"> golwg tudalen</a> i weld sut mae\'ch tudalen gategorïau yn edrych ar ôl arbed.';
$Definition['Manage Routes'] = 'Rheoli llwybrau';
$Definition['Managing Users'] = 'Rheoli Defnyddwyr';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Bydd marcio pethau fel DIM sbam yn eu rhoi yn ôl yn eich Fforwm.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Bydd marcio pethau fel dim sbam yn eu rhoi yn ôl yn eich Fforwm.';
$Definition['Messages can appear anywhere in your application.'] = 'Gall negeseuon ymddangos unrhyw le yn y rhaglen, a gellir eu defnyddio i roi gwybod i\'ch defnyddwyr am newyddion a digwyddiadau. Defnyddiwch y dudalen hon i ail-drefnu eich negeseuon drwy eu llusgo i fyny neu i lawr.';
$Definition['MobileLogoDescription'] = 'Mae logo\'r faner symudol yn ymddangos ar frig eich gwefan.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Mae themâu symudol yn caniatáu ichi newid edrychiad a theimlad eich gwefan ar ddyfeisiau llai.';
$Definition['Most communities stick to positive reactions to encourage participation.'] = 'Mae\'r rhan fwyaf o gymunedau yn glynu at ymatebion cadarnhaol i annog cyfranogiad.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'DS Bydd y Golygydd Gosodiad newydd yn etifeddu\'r thema a osodwyd yn eich Arddull Arddull (golygydd thema gynt). <1> Darganfod mwy</1>';
$Definition['Need More Help?'] = 'Angen mwy o Help?';
$Definition['Need more help?'] = 'Angen mwy o help?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Bydd categorïau nythu sy\'n ddyfnach na\'r dyfnder hwn yn cael eu rhoi mewn rhestr wedi\'i therfynu â choma.';
$Definition['New Embed System'] = 'System Mewnosod Newydd';
$Definition['New Quick Links'] = 'Dolenni Cyflym Newydd';
$Definition['New Search Page'] = 'Tudalen Chwilio Newydd';
$Definition['No Anonymization'] = 'Dim Anonymization';
$Definition['Not getting what you expect when you preview your theme?'] = 'Ddim yn cael yr hyn rydych chi\'n ei ddisgwyl pan fyddwch chi\'n rhagolwg o\'ch thema?';
$Definition['Notify me when people comment on my addons.'] = 'Rhoi gwybod i mi pan mae pobl yn gwneud sylwadau ar fy ychwanegion';
$Definition['No unconfirmed role available for email confirmation.'] = 'Mae angen rôl ar y safle gyda\'r math diofyn "heb ei gadarnhau" er mwyn defnyddio ebost cadarnhau. Ychwanegwch un i alluogi\'r gosodiad hwn.';

$Definition['Old Theming UI'] = 'UI Thema Hen';
$Definition['Once enabled, only members will see inside your community.'] = 'Ar ôl ei alluogi, dim ond aelodau fydd yn gweld y tu mewn i\'ch cymuned.';
$Definition['OrgDescription'] = 'Defnyddir enw eich sefydliad ar gyfer microdata SEO a JSON + LD';
$Definition['Outline'] = 'Amlinelliad';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Gall golygfeydd gor-guddiedig neu luniau thema gael sgîl-effeithiau anfwriadol ac ni chânt eu rhagolwg.';

$Definition['Partial Anonymization'] = 'Anhysbysiad Rhannol';
$Definition['PartialAnonymization.Description'] = 'Dim ond wythawd olaf y cyfeiriad IP y mae <strong>Anonymization Rhannol</strong> yn ei wneud. Er enghraifft byddai 254.230.05.153 yn dod yn 254.230.05.0. Mae hyn yn darparu rhywfaint o anhysbysrwydd tra\'n dal i ganiatáu i reolau gwahardd IP weithredu.';
$Definition['Password.MinLength'] = 'Isafswm hyd nod a ganiateir ar gyfer cyfrineiriau defnyddwyr ar dudalennau creu ac ailosod cyfrinair.';
$Definition['Please choose an authenticator to configure.'] = 'Dewiswch ddilyswr i\'w ffurfweddu.';
$Definition['PluginHelp'] = 'Mae ategion yn caniatáu i chi ychwanegu ffwythiannau i\'ch safle. < br / > unwaith mae ategyn wedi\'i ychwanegu i\'ch ffolder %s, gallwch ei alluogi neu analluogi yma.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Arddangosir y poced rhwng pob trafodaeth ar y prif restr trafod. Gan fod y trafodaethau hyn fel arfer yn dagiau < li >... < /li > bydd angen i chi lapio eich poced o gwmpas y tagiau hynny hefyd.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Mae pocedi yn caniatáu i chi ychwanegu HTML rhydd mewn gwahanol fannau o gwmpas y rhaglen.';
$Definition['Preset'] = 'Rhagosodiad';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Ataliwch sbam ar eich fforwm drwy gyfyngu ar y nifer o drafodaethau a sylwadau y gall defnyddwyr bostio o fewn cyfnod penodol o amser.';
$Definition['Primary Button'] = 'Botwm Cynradd';
$Definition['Primary Buttons'] = 'Botymau Cynradd';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Canllaw cyflym i ddechrau creu themâu ar gyfer Vanilla';
$Definition['Quicklinks'] = 'Dolenni cyflym';
$Definition['Quick Links is a default component on community pages.'] = 'Mae Dolenni Cyflym yn elfen ddiofyn ar dudalennau cymunedol. Galluogi ein cydran Dolenni Cyflym newydd i ychwanegu, golygu neu guddio dolenni o\'r ddewislen hon gan ddefnyddio ein golygydd thema.';

$Definition['Reactions Documentation'] = 'Dogfennaeth Ymatebion';
$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Ategyn sylwadau parod Vanilla ar gyfer WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Ategyn Fforwm Vanilla parod ar gyfer WordPress';
$Definition['Realtime progress bars: %s'] = 'Bariau cynnydd amser real: %s';
$Definition['Recommended dimensions are about 400px by 300px or smaller with similar ratio.'] = 'Mae\'r dimensiynau a argymhellir tua 400px wrth 300px neu lai gyda chymhareb debyg.';
$Definition['Recommend special ranks for admins and mods.'] = 'Mae\'n syniad da cael rhengoedd arbennig ar gyfer cymedrolwyr a gweinyddwyr fel y gall eich cymuned weld yn hawdd pwy sydd â gofal.';
$Definition['Recommend starting with five ranks.'] = 'Nid ydych chi am gael gormod o rengoedd. Rydym yn argymell dechrau gyda phump. Gallwch ychwanegu mwy os yw\'ch cymuned yn wirioneddol fawr.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Dileu dolenni trafodaeth a chategorïau o fwydlenni. Gosodwch dudalennau trafodaeth a chategori i ddychwelyd heb ei chanfod tudalen 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Angen caniatâd ymateb “Baner”.';
$Definition['Requires “Negative” reaction permission.'] = 'Angen caniatâd ymateb “negyddol”.';
$Definition['Requires “Positive” reaction permission.'] = 'Angen caniatâd ymateb “Cadarnhaol”.';
$Definition['Restoring your selection removes the items from this list.'] = 'Wrth adfer, bydd eitemau\'n cael eu tynnu oddi ar y rhestr yma a\'u rhoi nôl ar y safle.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Defnyddiwch yr opsiwn canlynol i alluogi dyfynbrisiau ar gyfer y Golygydd Cyfoethog. Dim ond os yw\'r fformatydd diofyn yn "Gyfoethog" y bydd hyn yn berthnasol.';
$Definition['Route Expression'] = 'Llwybr mynegiant';
$Definition['Routes are used to redirect users.'] = 'Defnyddir llwybrau i ailgyfeirio defnyddwyr gan ddibynnu ar yr URL a gofyn.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Chwilio am ddefnyddwyr wrth eu henw, neu rhowch enw rôl i weld holl ddefnyddwyr y rôl honno.';
$Definition['Secondary Button'] = 'Botwm Eilaidd';
$Definition['Secondary Buttons'] = 'Botymau Eilaidd';
$Definition['Security.Hsts.HTTPSWarning'] = 'Rhybudd: Peidiwch â galluogi\'r nodwedd hon oni bai eich bod yn siŵr bod eich holl is-barthau wedi\'u ffurfweddu ar gyfer HTTPS gyda thystysgrifau dilys.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Pan fydd wedi\'i alluogi, mae\'r rheol hon yn berthnasol i bob un o is-barthau eich gwefan hefyd.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Rydym yn argymell dechrau gydag uchafswm o 1 wythnos ac yna ei gynyddu i 1 mis ac yna blwyddyn ar ôl i chi weld eich gwefan yn gweithio yn ôl y disgwyl.';
$Definition['Security.Hsts.SubmitWarning'] = 'Rhybudd: Mae\'n wych cefnogi rhag-lwytho HSTS fel arfer gorau. Fodd bynnag, mae\'n rhaid i chi gyflwyno\'ch gwefan i hstspreload.org i sicrhau ei bod yn cael ei llwytho ymlaen llaw yn llwyddiannus (hy i gael yr amddiffyniad llawn ar gyfer y ffurfweddiad a fwriadwyd).';
$Definition['See the documentation'] = 'Gweler y Dogfennaeth';
$Definition['Select the default type for this role, if any.'] = 'Dewiswch y math diofyn ar gyfer y rôl hon, os o gwbl.';
$Definition['Select the import source'] = 'Dewiswch y Ffynhonnell Mewnforio';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Methodd serialized golofn "%s" yn unserialized.';
$Definition['Session Timeout'] = 'Goramser Sesiwn';
$Definition['Shadowed'] = 'Cysgodol';
$Definition['ShareImageDescription'] = 'Pan fydd rhywun yn rhannu dolen o\'ch gwefan, rydyn ni\'n ceisio bachu delwedd o\'r dudalen. Os nad oes delwedd ar y dudalen yna byddwn yn defnyddio\'r ddelwedd hon yn lle. Dylai\'r ddelwedd fod o leiaf 50 × 50, ond rydym yn argymell 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Rhoi opsiwn hwn ar waith i ddangos yr holl leoliadau poced posibl. Dim ond defnyddwyr sy\'n gallu rheoli pocedi fydd yn gallu gweld y lleoliadau.';
$Definition['SignIn.LockoutTime'] = 'Faint o amser y mae defnyddiwr yn cael ei rwystro rhag mewngofnodi ar ôl mynd y tu hwnt i nifer yr ymdrechion mewngofnodi.';
$Definition['Solid'] = 'Solet';
$Definition['Some browsers support a color for the address bar.'] = 'Mae rhai porwyr yn cefnogi lliw ar gyfer y bar cyfeiriad.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Nid yw rhai themâu hŷn yn cefnogi gallu golygu llawn. I weld beth mae thema\'n ei gefnogi gallwch hofran dros ei enw i weld lle bydd golygiadau yn dod i rym.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Efallai y bydd angen diweddaru rhai themâu i weithio gyda\'r categori canlynol. Gallwch chi analluogi\'r nodwedd wrth i chi ddiweddaru\'ch thema.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Weithiau rydych chi am ymgorffori\'ch gwefan Fanila y tu mewn i wefan arall. Mae system wreiddio Vanilla yn cynnig ffordd hawdd o wneud hynny. Mae cyfaddawdau perfformiad wrth ddefnyddio safle wedi\'i fewnosod, felly gwiriwch y ddogfennaeth am ddewisiadau amgen ac achosion defnydd delfrydol.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Cyfyngiad arbennig: Dim ond defnyddwyr â chaniatâd Garden.Curation.Manage all ddefnyddio\'r adwaith hwn.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Nodwch ornest rhannol neu lawn wrth greu gwaharddiad.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Treuliwch ychydig o amser yn meddwl am sut rydych yn disgrifio eich safle yma. Gallai rhoi teitl ystyrlon a disgrifiad cryno helpu eich sefyllfa mewn peiriannau chwilio.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Gwella golwg eich e-byst trwy ychwanegu logo ac addasu lliwiau.';
$Definition['Start Import'] = 'Dechrau mewnforio';
$Definition['Start the first discussion.'] = 'Taniwch eich cymuned drwy <a href="{/post/discussion,url}"> gychwyn y drafodaeth gyntaf</a> nawr.';
$Definition['Subcommunities'] = 'Is-gymunedau';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Mae tagio yn caniatáu i ddefnyddwyr ychwanegu tag at drafodaethau y maent yn eu cychwyn er mwyn eu gwneud yn fwy y gellir eu darganfod.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Templedi yw\'r themâu safonol. Er mwyn eu haddasu, mae\'n rhaid i chi greu copi.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Nid oes gan y dilyswr %s unrhyw opsiynau ffurfweddu personol.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'DS Mae angen ffurfweddu\'r labordy <0 /> i gyd-fynd â\'ch thema arferiad. Gellir gwneud hyn gan ddefnyddio ein golygydd thema newydd. <1> Darganfyddwch fwy.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Ni lwyddwyd i alluogi\'r ategyn gan iddo gynhyrchu gwall difrifol: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Mae\'r ategyn eisoes wedi\'i lwytho i lawr.';
$Definition['The banner logo appears at the top of your forum.'] = 'Mae\'r logo yn ymbaner ddangos ar frig eich fforwm.';
$Definition['The banner title appears on the top-left of every page.'] = 'Mae teitl y faner yn ymddangos ar chwith uchaf pob tudalen.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Mae teitl y faner yn ymddangos ar faner eich safle ac ym mar teitl eich porwr. Dylai fod yn llai na 20 o lythrennau. Os uwchlwythwyd logo baner, bydd yn disodli teitl y faner ar y tudalennau fforwm sy\'n wynebu\'r defnyddwyr. Hefyd, cofiwch y bydd rhai themâu hefyd yn cuddio\'r teitl hwn.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Mae\'r ffurflen gofrestru sylfaenol yn mynnu</strong> bod defnyddwyr newydd yn copïo testun o ddelwedd CAPTCHA i gadw spam o\'r safle. Mae angen cyfrif ar <a href="http://recaptcha.net/"> recaptcha.net</a>. Mae ymuno yn hawdd ac yn rhad ac am ddim. Unwaith rydych wedi arwyddo, dewch yn ôl yma a mewnosod y gosodiadau canlynol:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Nid oes gan y defnyddiwr cronfa ddata a nodwyd gennych fynediad i\'r gronfa ddata. Ydych chi wedi creu\'r gronfa ddata eto? Adroddodd y gronfa ddata: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Mae\'r newidiadau strwythur canlynol yn ofynnol ar gyfer eich cronfa ddata.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Mae teitl y dudalen hafan yn cael ei arddangos ar eich tudalen gartref. Dewiswch deitl yr ydych am ei weld yn ymddangos mewn peiriannau chwilio.';
$Definition['The import file does not contain any data.'] = 'Nid yw\'r ffeil mewnforio cynnwys unrhyw ddata.';
$Definition['The import file is not in the correct format.'] = 'Nid yw ffeil mewnforio yn y fformat cywir.';
$Definition['The location of the authentication endpoint.'] = 'Lleoliad y pwynt terfyn dilysu.';
$Definition['ThemeHelp'] = 'Mae themâu yn caniatáu i chi newid edrychiad a naws eich safle. < br / > unwaith mae thema wedi\'i ychwanegu at eich ffolder %s, gallwch ei alluogi yma.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Mae rhagolwg thema wedi\'i gyfyngu i arddangos templed a CSS y thema.';
$Definition['Theming Guide'] = 'Canllaw Thema';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Mae\'r logo symudol yn ymddangos ar frig eich gwefan. Nid yw themâu a wneir gyda\'r golygydd thema a rhai themâu arfer yn defnyddio\'r gosodiad hwn.';
$Definition['The New Embed System'] = 'Y System Mewnosod Newydd';
$Definition['The new embed system has improved performance.'] = 'Mae\'r system gwreiddio newydd wedi gwella perfformiad, gwella ymddygiad sgrolio, ac ymddygiad mwy cyson na\'r hen un. Ar hyn o bryd nid yw sylwadau a gwreiddio wordpress yn cael eu cefnogi yn y New Embed System.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Nid oes unrhyw opsiynau ffurfweddu penodol gan y dilyswr cyfrinair. ';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Nid oes angen unrhyw newidiadau strwythur cronfa ddata. Fodd bynnag, mae\'n bosibl bod newidiadau i\'r data.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Mae dau fath o fotymau yn y cymhwysiad: cynradd ac uwchradd.';
$Definition['The route was saved successfully.'] = 'Cafodd y llwybr ei arbed yn llwyddiannus.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Mae disgrifiad y safle fel arfer yn ymddangos mewn peiriannau chwilio. Dylech geisio cael disgrifiad sy\'n 100-150 nod o hyd.';
$Definition['The text of the pocket.'] = 'Teipiwch testun y boced. Bydd hyn yn cael ei allbynnu yn union fel y teipiwch ef felly gwnewch yn siŵr eich bod yn cofnodi HTML dilys.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Mae\'r eicon cyffwrdd yn ymddangos pan fyddwch chi\'n rhoi nod tudalen ar wefan ar sgrin gartref dyfais symudol. Mae\'r rhain fel arfer yn 152 picsel.';
$Definition['The user table was not in the import file.'] = 'Nid oedd yn y tabl defnyddiwr yn y ffeil mewnforio.';
$Definition['The Vanilla 2 Exporter'] = 'Allforiwr Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Mae Ystadegau Vanilla yn troi dangosfwrdd eich Fforwm yn offeryn adrodd analytig, sy\'n eich galluogi i adolygu\'r gweithgaredd ar eich fforwm dros gyfnodau amser penodol. Gallwch <a href="http://vanillaforums.org/docs/vanillastatistics"> ddarllen mwy am Ystadegau Vanilla</a> yn ein dogfennaeth.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Maent yn gweithio yn union fel themâu rheolaidd. Ar ôl i un gael ei ychwanegu at y ffolder themâu, gallwch ei alluogi yma.';
$Definition['This is a style guide of your theme.'] = 'Dyma ganllaw arddull o\'ch thema. Mae ganddo enghreifftiau o\'r elfennau gweledol a ddefnyddir trwy gydol y cymhwysiad. Gallwch glicio ar y teclynnau amrywiol fel y Bar Teitl <0> </0> neu <1> Baner </1> i olygu eu priodweddau yn y panel ochr.';
$Definition['This is the administrative dashboard for your new community.'] = 'Hwn yw dangosfwrdd gweinyddol eich cymuned newydd. Edrychwch ar y dewisiadau ffurfweddu ar yr ochr. Oddi yno gallwch ffurfweddu sut y mae eich cymuned yn gweithio. <b>Yn ddiofyn, gall dim ond defnyddwyr yn rôl "Gweinyddwr" sy\'n gallu gweld y rhan hon o\'ch cymuned.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Dyma lle gallwch chi alluogi a phrofi nodweddion, tudalennau a chydrannau Fanila newydd.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Ni ellir analluogi\'r labordy hwn oherwydd bod cynllun unigryw yn cael ei gymhwyso.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Ni all y labordy hwn fod yn anabl oherwydd ei fod yn ofynnol yn ôl y thema gyfredol.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Mae\'r logo hwn yn ymddangos ar frig eich gwefan. Nid yw themâu a wneir gyda\'r golygydd thema a rhai themâu arfer yn defnyddio\'r gosodiad hwn.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Gellir defnyddio hwn i gynnwys cynnwys fel enw a chyfeiriad y sefydliad ym mhob e-bost a anfonir.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Mae\'r opsiwn hwn yn dangos/cuddio y lleoliadau lle gall pocedi fynd, ond dim ond ar gyfer defnyddwyr sydd a hawliau i ychwanegu/golygu pocedi. Ceisiwch ddangos y lleoliadau ac yna ymweld a\'ch safle.';
$Definition['This page lists the endpoints of your API.'] = 'Mae\'r dudalen hon yn rhestru pwyntiau terfyn eich API. Cliciwch endpoints i gael mwy o wybodaeth. Gallwch wneud galwadau byw i\'r API o\'r dudalen hon neu\'n allanol gan ddefnyddio tocyn mynediad.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Gwybodaeth bersonol yw\'r rôl hon. Dim ond defnyddwyr sydd â chaniatâd i weld gwybodaeth bersonol fydd yn ei gweld.';
$Definition['This setting loads the page before executing Javascript.'] = 'Mae\'r gosodiad hwn yn llwytho\'r dudalen cyn gweithredu Javascript a all wella\'ch SEO. <br> <strong>** Rhybudd: Gall galluogi\'r nodwedd hon achosi gwallau Javascript ar eich gwefan. **</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Mae\'r gosodiad hwn yn llwytho\'r dudalen cyn gweithredu Javascript a all wella\'ch SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Ni ellir dileu\'r thema hon oherwydd dyma\'r thema a gymhwysir ar hyn o bryd.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Mae\'r teitl hwn yn ymddangos ar faner eich gwefan ac ym mar teitl eich porwr. Os caiff logo ei uwchlwytho, bydd yn disodli\'r teitl hwn ar dudalennau fforwm sy\'n wynebu defnyddwyr. Hefyd, cofiwch y gallai rhai themâu guddio\'r teitl hwn.';
$Definition['Tiled Layout'] = 'Cynllun Teils';
$Definition['Title Bar'] = 'Bar Teitl';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Defnyddiwch y cod canlynol i ymgorffori eich Fforwm Vanilla yn eich gwefan.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Gormod o gyfeiriadau! Byddwn yn anfon at gyfeiriadau %s ar y tro.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'I atal cam-ddefnydd, mae rhai offer awtomatig yn cuddio\'r cynnwys ac mae\'n cael ei restru yma tan y caiff ei gymeradwyo gan gymedrolwr.';
$Definition['TouchIconDescription'] = 'Mae\'r eicon cyffwrdd yn ymddangos pan fyddwch chi\'n rhoi nod tudalen ar wefan ar sgrin gartref dyfais Apple. Mae\'r rhain fel arfer yn 152 picsel. Mae Apple yn ychwanegu corneli crwn ac effaith goleuo yn awtomatig.';
$Definition['Transparent'] = 'Tryloyw';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Mae Twitter Connect yn caniatáu i ddefnyddwyr lofnodi wrth ddefnyddio eu cyfrif Twitter. <b>Rhaid i chi gofrestru eich rhaglen gyda Twitter er mwyn i\'r ategyn hwn weithio.</b>';

$Definition['Usercards'] = 'Cardiau defnyddiwr';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Mae cardiau defnyddiwr yn caniatáu ichi gael cipolwg cyflym ar-lein o wybodaeth defnyddiwr. Wrth edrych ar bostiadau a byrddau arweinwyr, cliciwch ar yr enw defnyddiwr i weld cerdyn yn arddangos gwybodaeth proffil sylfaenol y defnyddiwr heb orfod llywio i ffwrdd o\'r dudalen. Galluogi\'r nodwedd hon i ychwanegu cardiau ymarfer at eich thema arferiad.';
$Definition['User inputs are based on the global background and text colors.'] = 'Mae mewnbynnau defnyddwyr yn seiliedig ar y cefndir byd-eang a lliwiau testun.';
$Definition['User Profile'] = 'Proffil Defnyddiwr';
$Definition['Users may sign into your site using their Twitter account.'] = 'Gall defnyddwyr fewngofnodi i\'ch gwefan gan ddefnyddio eu cyfrif Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Defnyddiwch y botwm ar frig y dudalen i greu rheol gwahardd.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Defnyddiwch ategyn WordPress i sefydlu sylwadau Vanilla ar eich blog, neu defnyddiwch y Cod cyffredinol i sefydlu sylwadau Vanilla ar  unrhyw blatfform arall.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Mae gwasanaeth chwilio newydd Vanilla yma o\'r diwedd. Galluogi UI ein tudalen chwilio newydd i gael mynediad at y nodweddion chwilio mwyaf newydd fel Chwilio Aelod, didoli chwilio ac amlygu termau.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Allforio Vanilla: %s, Ffynhonnell: %s';
$Definition['Vanilla Labs'] = 'Labeli Fanila';
$Definition['Vanilla Statistics are currently disabled'] = 'Ystadegau Vanilla heb eu galluogi ar hyn o bryd';
$Definition['Verify and restore'] = 'Gwirio ac adfer';
$Definition['VerifyUser'] = 'Gwiriwch y blwch wrth ymyl y defnyddiwr i\'w farcio fel Wedi\'i <b>Wirio</b> fel nad yw eu postiadau\'n cael eu marcio fel sbam eto. Bydd hyn hefyd yn adfer eu holl swyddi sydd ar ddod.';
$Definition['Video tutorial on advanced settings'] = 'Fideo Tiwtorial ar osodiadau uwch';
$Definition['Video tutorial on finding &amp; managing users'] = 'Tiwtorialau fideo ar ganfod a rheoli defnyddwyr';
$Definition['Video tutorial on managing appearance'] = 'Tiwtorial fideo ar reoli ymddangosiad';
$Definition['Video tutorial on managing categories'] = 'Tiwtorial fideo ar reoli categorïau';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Fideo tiwtorial ar reoli rôlau a hawliau';
$Definition['Video tutorial on user registration'] = 'Tiwtorialau fideo ar gofrestru defnyddwyr';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Rhybudd: Gall galluogi\'r nodwedd hon achosi gwallau Javascript ar eich gwefan.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Rhybudd</b> : Nid yw cyfluniad eich gweinydd yn cefnogi llwytho data yn gyflym. Os ydych chi\'n mewnforio ffeil fawr iawn (cyn. 200,000 o sylwadau) efallai yr hoffech chi ystyried newid eich cyfluniad. Cliciwch <a href="http://vanillaforums.com/porter">yma</a> i gael mwy o wybodaeth.';
$Definition['Warning: This is for advanced users.'] = '<b>Rhybudd</b>: Mae hyn ar gyfer defnyddwyr profiadol ac yn gofyn am wneud newidiadau ychwanegol i weinydd eich gwefan. Fel arfer mae angen gwesteio neilltuedig neu vps ar gyfer hyn. Peidiwch ceisio gwneud hyn os nad ydych yn gwybod beth rydych yn ei wneud.';
$Definition['Welcome to Labs!'] = 'Croeso i Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Croeso i UI thematig Vanilla. Mae\'r dudalen hon yn rhestru\'ch holl themâu sydd ar gael, ac yn caniatáu ichi eu copïo neu eu golygu.';
$Definition['Welcome To Your Theme'] = 'Croeso i\'ch Thema';
$Definition['We recommend enabling 1–3 reactions at a time to avoid overwhelming users.'] = 'Rydym yn argymell galluogi 1-3 adwaith ar y tro i osgoi llethu defnyddwyr.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Pan fydd wedi\'i alluogi, gall defnyddwyr ddewis derbyn hysbysiadau gan y gymuned';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Pan fydd wedi\'i alluogi, gallwch reoli cynhyrchion, a grwpio is-gymunedau yn ôl y cynhyrchion hynny.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Pan fydd rhywun yn rhannu dolen o\'ch gwefan, rydyn ni\'n ceisio bachu delwedd o\'r dudalen. Os nad oes delwedd ar y dudalen yna byddwn yn defnyddio\'r ddelwedd hon yn lle. Dylai\'r ddelwedd fod o leiaf 50 × 50, ond rydym yn argymell 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Pan ddewiswch Full Bleed, mae eich cefndir yn dryloyw.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'A fydd y meysydd proffil mewnol yn cael eu cynnwys yn y bachyn gwe hwn ai peidio.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'A fydd y meysydd proffil preifat yn cael eu cynnwys yn y bachyn gwe hwn ai peidio.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Rydych chi ar fin cymhwyso opsiwn cynllun newydd. Gellir addasu a rhagolwg hyn gan ddefnyddio ein Golygydd Thema. <0> Dysgu mwy</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Gallwch wahardd pob defnyddiwr sydd â chyfeiriadau IP wedi\'u rhagddodi â "111.111.111" trwy ychwanegu gwaharddiad math IP gyda\'r gwerth "111.111.111. *".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Gallwch wahardd cyfeiriadau IP, cyfeiriadau e-bost ac enwau defnyddwyr.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Gallwch ddewis o un o\'r gwahanol arddulliau y mae\'r thema hon yn eu cynnig.';
$Definition['You can configure some values differently for different screensizes.'] = 'Gallwch chi ffurfweddu rhai gwerthoedd yn wahanol ar gyfer gwahanol sgrinluniau.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Gallwch gysylltu â safleoedd lluosog sy\'n cefnogi jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Os yw\'ch ffeil yn rhy fawr i\'w lwytho\'n uniongyrchol i\'r dudalen hon, gallwch ei roi yn eich ffolder /llwytho. Sicrhewch fod enw\'r ffeil yn dechrau gyda\'r gair <b> export </b> ac diweddu gydag un o <b> .txt, .gz </b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Gallwch chi nodi isafswm hyd post i annog swyddi byr i beidio.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Gallwch uwchlwytho Ffont Custom yn eich System Thema. Copïwch a gludwch yr URL yn y maes.';
$Definition['You must select a file to import.'] = 'Rhaid i chi ddewis ffeil i\'w mewnforio.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Mae angen ichi ychwanegu parth yr url ffont at <0> Parth a Ganiateir </0> yng nghyfluniad y wefan. <1> Dysgu mwy am ffontiau arfer. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Bydd eich thema symudol yn anabl. I osod gwahanol themâu symudol a bwrdd gwaith, defnyddiwch yr hen UI theming.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Defnyddir enw eich sefydliad ar gyfer microdata SEO a JSON + LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Mae ffafriaeth eich gwefan yn ymddangos ym mar teitl eich porwr. Bydd yn cael ei ostwng yn briodol.';
