<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Упозорење: Омогућавање ове функције може да изазове Јавасцрипт грешке на вашем сајту.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Главу горе!</strong> Брисање улоге може резултирати да корисници немају приступ апликацији.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Главу горе!</strong> Прелазак на расправу у категорију замене може резултирати дискусијом која нестаје (или се појављује) ако замена садржи другачија одобрења од оне која се брише.';

$Definition['About.DisableStatistics'] = 'Ако из неког пословног разлога морате онемогућити извештавање ових података, то можете учинити додавањем следећег ретка у конфигурациону датотеку ваше инсталације: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'За живот овог бесплатног софтвера отвореног кода од виталног је значаја да прецизно измеримо досег и ефикасност Ванилле. Молимо вас да не онемогућите пријављивање ових података.';
$Definition['AboutCommentEmbedding'] = 'Ванилија се може користити као замена за изворни систем коментарисања вашег блога. У ствари, може се користити за додавање коментара на било коју страницу на вебу.';
$Definition['AboutEmbedding'] = 'Уграђивање омогућава да се цела или део ваше заједнице угради у друге апликације и веб странице.';
$Definition['About Vanilla Statistics'] = 'О ванилла статистикама';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Приступите форуму заједнице кликом на везу „Посети веб локацију“ на врху ове странице или <a href={/,url}>кликом овде</a> . Форум заједнице је оно што ће видети сви ваши корисници и купци када посете <a href="{/,url,domain}">{/,url,domain}</a> .';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Dodajte ograničenja na dimenzije slika za otpremanje u diskusijama i komentarima. ';
$Definition['AddonProblems'] = '<h2> Проблеми? </h2><p> Ако нешто није у реду са додатком и не можете да користите своју веб локацију, можете их ручно онемогућити уређивањем: </p> %s';
$Definition['AddressBarColorDescription'] = 'Неки прегледачи подржавају боју адресне траке. Само за мобилне уређаје.';
$Definition['Alert users if they click external link.'] = 'Обавијестите кориснике ако кликну везу у посту који ће их одвести са форума. Корисници неће бити упозорени када следе везе које одговарају поузданом домену';
$Definition['Alignment'] = 'Поравнање';
$Definition['Alignment (Mobile)'] = 'Поравнање (мобилно)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Све категорије су наведене са избором 5 недавних дискусија испод сваке';
$Definition['Allow links to be transformed'] = 'Дозволите да се линкови трансформишу у уграђене представке у дискусијама и коментарима. На пример, ИоуТубе веза ће се трансформисати у уграђени видео.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Дозволите корисницима са дозволом %s да промене сопствене аватаре са својих страница профила у Ванилли.';
$Definition['Anonymize IP Addresses'] = 'Анонимизирај ИП адресе';
$Definition['ApplicationHelp'] = 'Апликације вам омогућавају да на своју веб локацију додате велике групе функционалности. <br /> Једном када је апликација додата у мапу %s, овде је можете омогућити или онемогућити.';
$Definition['Apply Layout'] = 'Примени изглед';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Јесте ли сигурни да желите да избришете ову тему? Биће трајно избрисана.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Јесте ли сигурни да сте унијели исправно име хоста базе података? Можда сте погрешно написали? Извештава се база података: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'За употребу потврде е-поште потребна је улога са подразумеваним типом „непотврђено“.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Аутоматски сачувајте нацрте необјављених дискусија, питања, идеја и коментара.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Аватари ће бити смањени ако пређу ову висину.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Аватари ће бити смањени ако пређу ову ширину.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Аватари ће своје сличице сачувати у овој величини.';

$Definition['Background'] = 'Позадина';
$Definition['Background Image'] = 'Позадинска слика';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Будите креативни! Покушајте именовати своје редове по стварима о којима заједница говори.';
$Definition['Bordered'] = 'Ограничена';
$Definition['Bordered (Unified)'] = 'Ограничена (обједињена)';
$Definition['Borderless'] = 'Бордерлесс';
$Definition['Border Radius'] = 'Гранични радијус';
$Definition['Brand Color'] = 'Боја марке';
$Definition['Buttons'] = 'Дугмад';
$Definition['Buttons & Inputs'] = 'Дугмад и уноси';
$Definition['Button Type'] = 'Тип дугмета';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Кликом на доњи тастер заувек ћете избрисати кориснички налог за %s.';

$Definition['Center Aligned'] = 'Поравнавање центра';
$Definition['Changes to the set day will take affect the following week.'] = 'Промене постављеног дана ће утицати на следећу недељу.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Промјене ће се односити само на ново учитане аватаре.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Промените величине у које се слике аватора чувају.';
$Definition['Change the way your community works with plugins.'] = 'Промените начин рада ваше заједнице с додацима. Софтвер смо добили заједно, а ту је и више доступних на мрежи.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Потврдни оквири омогућавају администраторима да истовремено извршавају групне акције на одређеном броју дискусија или коментара.';
$Definition['Check out our %s'] = 'Погледајте наш %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Погледајте нашу <0>документацију</0> , или питајте нашу <1>заједницу стручњака</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Ванилла је најједноставнија, најмоћнија платформа заједнице на свету. Изузетно је једноставан за употребу. Започните с овим уводним видеом и наставите са доњим корацима. Уживати!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Изаберите улогу којој ће сироти корисници бити додељени:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Изаберите тему за ову заједницу. <0> Прочитајте више </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Изаберите како да обрађујете сав садржај повезан са корисничким налогом за %s (коментари, поруке итд.).';
$Definition['Choose Image'] = 'Изаберите Слика';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Можете одабрати прилагођени хасх алгоритам за потписивање захтева. Алхитам алгоритам такође се мора користити у вашој библиотеци клијената. Одаберите мд5 ако нисте сигурни шта одабрати.';
$Definition['Choose the order items are sorted.'] = 'Одаберите да су ставке поруџбине сортиране.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Одаберите страницу коју би људи требали видјети када посјете <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Изаберите жељени распоред за листе категорија.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Одаберите жељени изглед за листе категорија. Можете уредити изглед плочица.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Изаберите жељени изглед за листе дискусија.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Одаберите жељени изглед за листе дискусија. Можете уредити темељни изглед.';
$Definition['Color Overlay'] = 'Боја преклапање';
$Definition['Continue Import'] = 'Наставите увоз';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Увоз датотеке није успео. Проблем је близу линије %s.';
$Definition['Create a localization CSV'] = 'Направите ЦСВ за локализацију';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Прилагођене теме су теме које сте креирали. Можете их уређивати, преименовати или направити копију.';

$Definition['Dark'] = 'Дарк';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'На страници <a href="%s">Ролес & Пермиссионс</a> одредите ко може пренијети и управљати датотекама.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Дефинишите почетну страницу форума, пренесите свој лого и још много тога ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Брисање улоге може резултирати да корисници немају приступ апликацији.';
$Definition['Deleting forever cannot be undone.'] = 'Брисање је добар начин да свој форум очистите.';
$Definition['Disable Google Sign In'] = 'Онемогући Гоогле пријаву';
$Definition['Disable OpenID'] = 'Онемогући ОпенИД';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Онемогућите лабораторију „Нови систем за уграђивање“ на страници <0>Ванилла Лабс</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Категорије дискусије користе се за помоћ корисницима да организују своје дискусије на начин који је важан за вашу заједницу.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Немојте уграђивати контролну плочу вашег администратора на форуму (прикажите је на целом екрану)';
$Definition['Don\'t use too many reactions.'] = 'Не користите превише реакција. Не желите да преоптерећујете информације својим корисницима.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Превуците и испустите доње категорије да бисте их сортирали и угнијездили.';

$Definition['EditContentTimeout.Notes'] = 'Ако је корисник у улози која има дозволу за уређивање садржаја, та дозвола ће то надјачати.';
$Definition['Edit Route'] = 'Измена руте';
$Definition['Edits to this theme apply to:'] = 'Измене ове теме односе се на:';
$Definition['Email digests will be sent on the selected day every week.'] = 'Сажеци е-поште ће се слати на изабрани дан сваке недеље.';
$Definition['Email sent from the application will be addressed from this email address'] = 'Е-пошта послата из апликације биће адресирана са ове адресе е-поште';
$Definition['Email sent from the application will be addressed from this name'] = 'Е-пошта послата из апликације биће адресирана са овог имена';
$Definition['Email Settings'] = 'Подешавања е-поште';
$Definition['Embed Settings'] = 'Ембед Сеттингс';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Уградите форум заједнице у своју веб локацију да бисте повећали ангажман ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Омогућите и испробајте најновије функције ваниле.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Омогућава напредно уређивање постова у неколико формата, укључујући ВИСИВИГ, једноставан ХТМЛ, Маркдовн и ББЦоде.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Омогућите уређивач распореда да примени прилагођени изглед за странице ваше заједнице. Користите наш нови уређивач да бисте представили садржај користећи наш каталог доступних виџета.';
$Definition['Enter a descriptive name.'] = 'Унесите описно име за џеп. Ово се име неће појавити нигде, осим када овде управљате џеповима, па ће се само користити за памћење џепа.';
$Definition['Enter a short name for the site.'] = 'Унесите кратко име веб локације. Ово је приказано на тастерима за пријаву.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Унесите адресу свог Вордпресс блога и однећемо је одатле.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Унесите подешавања везе за свој сфингк сервер у наставку.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Свака измена или брисање се овде бележи. Употријебите \'Ресторе\' да бисте поништили било какве промјене.';
$Definition['Everyone who signs up gets a profile page.'] = 'Сви који се пријаве за вашу заједницу добијају страницу јавног профила на којој могу да поставе слику о себи, управљају својим подешавањима профила и прате цоол ствари које се дешавају у заједници. Сада би требало да <a href="{/profile,url}">прилагодите свој профил</a> .';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Сваком кориснику на вашој веб локацији додијељена је најмање једна улога. Улоге се користе за одређивање онога што је корисницима дозвољено да раде.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Фацебоок Цоннецт омогућава корисницима да се пријаве путем свог Фацебоок налога. <b>Морате да региструјете своју пријаву на Фацебооку да би овај додатак могао да функционише.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Повезивање са базом података није успело са унесеним корисничким именом и лозинком. Да ли сте их погрешно унели? Извештава се база података: <code>%s</code>';
$Definition['Font'] = 'Фонт';
$Definition['Font Name'] = 'Назив фонта';
$Definition['Font URL'] = 'УРЛ фонта';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Присилите контролну таблу да буде доступна само путем овог УРЛ-а <em>(није препоручљиво)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'На пример, можете да забраните свим корисницима адресе е-поште са „екампле.цом“ додавањем забране типа е-поште са вредности „*@екампле.цом“.';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'За потребе СЕО претраживања, претраживачи претраживача искључени су од присиљавања да прегледају форум у удаљеном УРЛ-у.';
$Definition['Foundation Layout'] = 'Изглед темеља';
$Definition['Full Anonymization'] = 'Потпуна анонимизација';
$Definition['FullAnonymization.Description'] = '<strong>Потпуна анонимизација</strong> замењује сваку појединачну ИП адресу са 0.0.0.0 ефективно ускраћујући апликацији било какав приступ за рад са ИП адресама. Правила забране ИП адресе у овом случају уопште неће функционисати.';
$Definition['Full Bleed'] = 'Фулл Блеед';

$Definition['Garden.Import.Complete.Description'] = 'Успешно сте завршили увоз. Кликните <b>Готово</b> када будете спремни.';
$Definition['Garden.Import.Continue.Description'] = 'Изгледа да сте усред увоза. Изаберите једну од следећих опција.';
$Definition['Garden.Import.InputInstructions'] = 'Унесите адресу е-поште и лозинку администратора од података који се увозе.';
$Definition['Garden.Privacy.IPs.Description'] = 'ИП адресе корисника се обично прикупљају ради аутоматизованих правила забране, модерирања и спречавања нежељене поште. Омогућавање ИП анонимизације ће анонимизовати све ИП адресе праћене на сајту за било коју сврху и смањиће ефикасност ових алата. Промене овог подешавања нису ретроактивне.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Гарден.Профилес.Додајте дозволу за промену сопствених аватара са својих страница профила у Ванили.';
$Definition['Garden.StatisticsDisabled'] = 'У конфигурацијској датотеци посебно сте онемогућили статистику ванилије.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Чини се да се овај форум покреће у тестном окружењу или на неки други начин пријављује приватни ИП. Форуми који раде на приватним ИП адресама не подразумевано се не прате.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Ако сте сигурни да је ваш форум доступан са интернета, можете га натерати да овде пријави статистику:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Чини се да је датотека цонфиг.пхп доступна само за читање. То значи да Ванилла неће моћи аутоматски да региструје ИнсталлатионИД и ИнсталлатионСецрет вашег форума.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Да бисте решили овај проблем, доделите режим датотеке 777 вашој датотеци цонф / цонфиг.пхп.';
$Definition['Global Styles'] = 'Глобал Стилес';

$Definition['Heads Up!'] = 'Главу горе!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Главу горе! Ово је посебна улога која не дозвољава активне сесије. Из тог разлога, опције дозвола су ограничене на „прегледавање“ дозвола.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Ево свих реакција које можете користити на својој веб локацији.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Ево редова које корисници могу постићи на вашој веб локацији. Можете прилагодити ове редове, па чак и додати нове. Ево неколико савета.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Ако се пренесе логотип банера, он ће заменити наслов банера на страницама форума окренутим корисницима.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Ако корисник не посети сајт у овом временском периоду, биће аутоматски одјављен.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Ако је омогућено, цео садржај постова ће бити послат корисницима у обавештењима путем е-поште.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Ако сте нови у ХТМЛ и / или ЦСС-у, ево неколико упутстава за почетак:';
$Definition['If you have an old theme'] = 'Ако имате стару тему и требате подесити засебну тему за радну површину и мобилне уређаје, то можете учинити са старим тематским корисничким сучељем.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Ако желите да смањите ниво упозорења, уклоните упозорење.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Ако желите да уградите свој форум или користите коментаре Ванилије на свом блогу, тада морате да омогућите уградњу. Ако не користите уграђивање, препоручујемо да ово подешавање искључите.';
$Definition['Image (Mobile)'] = 'Слика (мобилна)';
$Definition['Import'] = 'Увоз';
$Definition['Importing to Vanilla'] = 'Увоз у Ванилију';
$Definition['In additon to the widgets there are also'] = 'Поред додатака к видгетима постоје и <0> Глобал Стилес </0> . Да бисте изменили глобалне стилове, кликните било где друго на страници, као што је овај текст.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Интегришите странице и компоненте темеља у своју тему';
$Definition['Internationalization & Localization'] = 'Интернационализација и локализација';
$Definition['Invalid URL'] = 'Неважећи УРЛ';
$Definition['Invitation email failed to send: %'] = 'Иако је позивница креирана успешно, е-пошта није успела да се пошаље. Сервер је пријавио следећу грешку: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Када користите регистрацију путем позива, корисници ће на својим профилима имати везу под називом <a href="%s" class="Popup">Моји</a> позиви.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Изгледа да база података коју сте навели још не постоји. Јесте ли га већ створили? Да ли сте погрешно унели име? Извештава се база података: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Добро је задржати максимални број дозвољених карактера у коментару на разумну величину.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Добро је задржати максимални број дозвољених ликова у посту на разумну величину.';

$Definition['Kick-start your community and increase user engagement.'] = 'Започните заједницу и повећајте ангажман корисника.';

$Definition['Labs'] = 'Лабс';
$Definition['Layout Editor'] = 'Лаиоут Едитор';
$Definition['Learn about custom routing.'] = 'Сазнајте више о прилагођеном усмјеравању.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Научите како да потпуно промените изглед и осећај форума: учитајте свој лого, поставите почетну страницу, изаберите тему и прилагодите је.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Научите како да користите основне функције вашег форума.';
$Definition['Left Aligned'] = 'Лево поравнато';
$Definition['Light'] = 'Светлост';
$Definition['Links'] = 'Везе';
$Definition['Locales allow you to support other languages on your site.'] = 'Локале вам омогућавају да подржавате друге језике на вашој веб локацији. Омогућите и онемогућите локалитете које желите да учините доступним овде.';
$Definition['Lockout Time (seconds)'] = 'Време блокаде (секунде)';
$Definition['LogoDescription'] = 'Логотип банера појављује се на врху ваше веб локације.';
$Definition['LogoDisclaimer'] = 'Теме направљене помоћу уређивача тема и неке прилагођене теме не користе ову поставку.';
$Definition['Looking for the Old Embed System?'] = 'Тражите стари систем за уграђивање?';

$Definition['Make sure you click View Page'] = 'Обавезно кликните на <a href="%s">Прикажи страницу</a> да бисте видели како страница са категоријама изгледа након чувања.';
$Definition['Manage Routes'] = 'Управљање рутама';
$Definition['Managing Users'] = 'Управљање корисницима';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Означивање ствари као НЕ спам вратиће их на ваш форум.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Означавањем ствари као нежељене поште вратит ћете их на ваш форум.';
$Definition['Messages can appear anywhere in your application.'] = 'Поруке се могу појавити било где у вашој апликацији и могу се користити за обавештавање корисника о вестима и догађајима. Помоћу ове странице поново организујте поруке повлачењем их нагоре или надоле.';
$Definition['MobileLogoDescription'] = 'Логотип мобилног банера појављује се на врху веб странице.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Теме за мобилне уређаје омогућавају вам да промените изглед и изглед свог вебсајта на мањим уређајима.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'НБ Нови Лаиоут Едитор ће наследити тему постављену у вашем Водичу за стилове (формално уређивач тема). <1>Сазнајте више</1>';
$Definition['Need More Help?'] = 'Требате више помоћи?';
$Definition['Need more help?'] = 'Треба вам додатна помоћ?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Гнездене категорије дубље од ове дубине биће смештене у листи ограниченом зарезом.';
$Definition['New Embed System'] = 'Нови систем за уграђивање';
$Definition['New Quick Links'] = 'Нове брзе везе';
$Definition['New Search Page'] = 'Нова страница за претрагу';
$Definition['No Anonymization'] = 'Без анонимизације';
$Definition['Not getting what you expect when you preview your theme?'] = 'Не добијате оно што очекујете током прегледа своје теме?';
$Definition['Notify me when people comment on my addons.'] = 'Обавести ме када људи коментаришу моје додатке.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Веб локацији треба улога са подразумеваним типом „непотврђено“ да би користила потврду е-поште. Додајте га да бисте омогућили ово подешавање.';

$Definition['Old Theming UI'] = 'Корисничко сучеље Олд Тхеминг';
$Definition['Once enabled, only members will see inside your community.'] = 'Једном када су омогућени, само чланови ће видети у вашој заједници.';
$Definition['OrgDescription'] = 'Назив ваше организације се користи за СЕО микроподатке и ЈСОН+ЛД';
$Definition['Outline'] = 'Скица';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Прекривени погледи или приказе тема могу имати ненамерне нежељене ефекте и нису прегледани.';

$Definition['Partial Anonymization'] = 'Делимична анонимизација';
$Definition['PartialAnonymization.Description'] = '<strong>Делимична анонимизација</strong> анонимизује само последњи октет ИП адресе. На пример, 254.230.05.153 би постало 254.230.05.0. Ово обезбеђује извесну анонимизацију док и даље дозвољава да функционишу правила забране ИП-а.';
$Definition['Password.MinLength'] = 'Минимална дужина знакова дозвољена за корисничке лозинке на страницама за креирање и ресетовање лозинки.';
$Definition['Please choose an authenticator to configure.'] = 'Одаберите конфигурацију аутентификата.';
$Definition['PluginHelp'] = 'Додаци омогућавају додавање функционалности на вашу веб локацију. <br /> Након што додатак додате у мапу %s, овде га можете омогућити или онемогућити.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Џеп се приказује између сваке расправе на главној листи дискусија. Будући да су расправе обично у <ли> .. </ли> таговима, мораћете да увучете џеп и у те ознаке.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Џепови вам омогућавају да додате ХТМЛ у слободној форми на разна места око апликације.';
$Definition['Preset'] = 'Унапред подешено';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Спречите нежељену пошту на вашем форуму тако што ћете ограничити број дискусија и коментара које корисници могу објављивати у одређеном временском периоду.';
$Definition['Primary Button'] = 'Примарно дугме';
$Definition['Primary Buttons'] = 'Примарни тастери';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Водич за брзи почетак стварања тема за ванилију';
$Definition['Quick Links is a default component on community pages.'] = 'Брзе везе су подразумевана компонента на страницама заједнице. Омогућите нашој новој компоненти Брзе везе за додавање, уређивање или скривање веза из овог менија помоћу нашег уређивача тема.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Готов производ Ванилла Цомментс Плугин за ВордПресс';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Спремни додатак за ванилла форум за ВордПресс';
$Definition['Realtime progress bars: %s'] = 'Ствари за напредак у стварном времену: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Добра идеја је имати посебне редове за модераторе и администраторе како би ваша заједница могла лако да види ко је главни.';
$Definition['Recommend starting with five ranks.'] = 'Не желите имати превише звања. Препоручујемо да почнете са пет. Можете додати још ако је заједница заиста велика.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Уклоните везе за дискусију и категорије из менија. Подесите странице које се односе на дискусију и категорију да врате ненађену страницу 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Захтијева дозволу реакције „Означи“.';
$Definition['Requires “Negative” reaction permission.'] = 'Захтијева дозволу за „негативну реакцију“.';
$Definition['Requires “Positive” reaction permission.'] = 'Захтијева дозволу за позитивну реакцију.';
$Definition['Restoring your selection removes the items from this list.'] = 'Када је вратите, ставке се уклањају са ове листе и враћају на веб локацију.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Користите следећу опцију да бисте омогућили цитате за Рицх Едитор. Ово ће се применити само ако је подразумевани формат "Рицх".';
$Definition['Route Expression'] = 'Роуте Екпрессион';
$Definition['Routes are used to redirect users.'] = 'Руте се користе за преусмеравање корисника у зависности од тражене УРЛ адресе.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Претражите кориснике по имену или унесите име улоге да бисте видели све кориснике са том улогом.';
$Definition['Secondary Button'] = 'Секундарно дугме';
$Definition['Secondary Buttons'] = 'Секундарни тастери';
$Definition['Security.Hsts.HTTPSWarning'] = 'Упозорење: Ову функцију омогућите само ако сте сигурни да су сви ваши поддомене конфигурирани за ХТТПС са важећим сертификатима.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Када је омогућено, ово правило се примењује и на све поддомене ваше веб локације.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Препоручујемо да започнете са максималном старошћу од 1 недеље, а затим да је повећате на 1 месец, а затим и за 1 годину када видите да ваша веб локација функционише како сте очекивали.';
$Definition['Security.Hsts.SubmitWarning'] = 'Упозорење: Одлично је подржати ХСТС прединсталирање као најбољу праксу. Међутим, морате да пошаљете своју веб локацију на хстспрелоад.орг да бисте били сигурни да је успешно унапред учитана (тј. Да бисте добили потпуну заштиту намењене конфигурације).';
$Definition['See the documentation'] = 'Погледајте документацију';
$Definition['Select the default type for this role, if any.'] = 'Изаберите задати тип ове улоге, ако постоји.';
$Definition['Select the import source'] = 'Изаберите извор увоза';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Серијализована колона "%s“ није успела да се несерисалише.';
$Definition['Session Timeout'] = 'Временско ограничење сесије';
$Definition['Shadowed'] = 'Схадовед';
$Definition['ShareImageDescription'] = 'Када неко дели везу са ваше веб локације, покушавамо да снимимо слику са странице. Ако на страници нема слике, тада ћемо је користити ту слику. Слика би требала бити најмање 50 × 50, али препоручујемо 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Укључите ову опцију да бисте приказали све могуће локације џепова. Ако укључите ову опцију, локације ће се показати само корисницима који могу управљати џеповима.';
$Definition['SignIn.LockoutTime'] = 'Време које је кориснику блокирано да се пријави након што је премашио број покушаја пријаве.';
$Definition['Solid'] = 'Чврст';
$Definition['Some browsers support a color for the address bar.'] = 'Неки претраживачи подржавају боју за адресну траку.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Неке старије теме не подржавају пуну могућност уређивања. Да бисте видели шта тема подржава, можете да пређете мишем преко њеног имена да видите где ће измене ступити на снагу.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Неке теме ће можда требати ажурирати да би радиле са следећом категоријом. Можете да онемогућите ову функцију док ажурирате тему.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Понекад желите да уградите своју Ванилла локацију у другу локацију. Ванилин систем за уградњу нуди једноставан начин за то. Постоје компромиси у погледу перформанси када користите уграђену локацију, па погледајте документацију за алтернативе и идеалне случајеве употребе.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Посебно ограничење: Само корисници с дозволом Гарден.Цуратион.Манаге могу користити ову реакцију.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Наведите делимично или потпуно подударање приликом креирања забране.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Проведите мало времена размишљајући о томе како овде описујете своју веб локацију. Давање ваше веб странице смисленом наслову и сажетим описом могло би вам помоћи у положају у претраживачима.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Израстајте е-пошту додавањем логотипа и прилагођавањем боја.';
$Definition['Start Import'] = 'Започни увоз';
$Definition['Start the first discussion.'] = 'Закотрљајте своју заједницу тако што ћете одмах <a href="{/post/discussion,url}">започети прву дискусију</a> .';
$Definition['Subcommunities'] = 'Подзаједнице';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Означавање омогућава корисницима да додају ознаку дискусијама које су започели како би их учинили откривенијима.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Предлошци су стандардне теме. Да бисте их прилагодили, морате да креирате копију.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Аутентификат %s нема прилагођене опције конфигурације.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'Напомена: Лабораторија <0/> мора бити конфигурисана тако да одговара вашој прилагођеној теми. То можете учинити помоћу нашег новог уређивача тема. <1> Сазнајте више.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Додатак није могао бити омогућен јер је створио фаталну грешку: <pre> %s </pre>';
$Definition['The addon has already been downloaded.'] = 'Додатак је већ преузет.';
$Definition['The banner logo appears at the top of your forum.'] = 'Логотип банера појављује се на врху форума.';
$Definition['The banner title appears on the top-left of every page.'] = 'Наслов банера се појављује у горњем левом делу сваке странице.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Наслов банера се појављује на банеру ваше веб локације и у насловној траци вашег прегледача. Треба да буде мање од 20 знакова. Ако се пренесе логотип банера, он ће заменити наслов банера на страницама форума окренутим корисницима. Такође, имајте на уму да неке теме могу сакрити и овај наслов.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Основни образац за регистрацију захтева од</strong> нових корисника да копирају текст са ЦАПТЦХА слике како би спамери били ван локације. Потребан вам је налог на <a href="http://recaptcha.net/">рецаптцха.нет</a> . Пријављивање је БЕСПЛАТНО и лако. Након што се пријавите, вратите се овде и унесите следећа подешавања:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Корисник базе података који сте навели нема дозволу за приступ бази података. Да ли сте већ створили базу података? Извештава се база података: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Следеће промене структуре су потребне за вашу базу података.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Наслов почетне странице приказује се на вашој почетној страници. Изаберите наслов који желите да се прикаже у претраживачима.';
$Definition['The import file does not contain any data.'] = 'Датотека за увоз не садржи никакве податке.';
$Definition['The import file is not in the correct format.'] = 'Увозна датотека није у исправном формату.';
$Definition['The location of the authentication endpoint.'] = 'Локација крајње тачке за потврду идентитета.';
$Definition['ThemeHelp'] = 'Теме вам омогућавају да промените изглед и изглед свог вебсајта. <br /> Једном када је тема додата у мапу %s, овде је можете омогућити.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Преглед теме је ограничен на приказивање предлошка и цсс теме.';
$Definition['Theming Guide'] = 'Тхеминг Гуиде';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Логотип за мобилне уређаје се појављује на врху вашег сајта. Теме направљене помоћу уређивача тема и неке прилагођене теме не користе ово подешавање.';
$Definition['The New Embed System'] = 'Нови систем за уграђивање';
$Definition['The new embed system has improved performance.'] = 'Нови систем за уграђивање има побољшане перформансе, побољшано понашање померања и доследније понашање од старог. Тренутно уграђивање коментара и вордпресс-а није подржано у новом систему за уграђивање.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Верификатор лозинке нема прилагођене опције конфигурације.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Нису потребне промјене структуре базе података. Међутим, може доћи до промена података.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Постоје две врсте дугмади у апликацији: примарни и секундарни.';
$Definition['The route was saved successfully.'] = 'Рута је успешно сачувана.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Опис сајта се обично појављује у претраживачима. Требало би да покушате да имате опис који је дугачак 100-150 знакова.';
$Definition['The text of the pocket.'] = 'Унесите текст џепа. Ово ће се појавити тачно док га куцате, тако да обавезно унесите важећи ХТМЛ.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Додирна икона се појављује када обележите веб локацију на почетном екрану мобилног уређаја. То су обично 152 пиксела.';
$Definition['The user table was not in the import file.'] = 'Корисничка таблица није била у датотеци за увоз.';
$Definition['The Vanilla 2 Exporter'] = 'Извозник ванилије 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Ванилла Статистицс претвара контролну таблу вашег форума у алат за извештавање о аналитикама, омогућавајући вам да прегледате активности на вашем форуму током одређених временских периода. <a href="http://vanillaforums.org/docs/vanillastatistics">Више о Ванилла Статистицс</a> можете <a href="http://vanillaforums.org/docs/vanillastatistics">прочитати</a> у нашој документацији.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Делују баш као и редовне теме. Када је додате у мапу тема, можете је овде омогућити.';
$Definition['This is a style guide of your theme.'] = 'Ово је стилски водич ваше теме. Има примере визуелних елемената који се користе у целој апликацији. Можете да кликнете на разне виџете као што је <0> насловна трака </0> или <1> Банер </1> за уређивање њихових својстава на бочној плочи.';
$Definition['This is the administrative dashboard for your new community.'] = 'Ово је административна табла за вашу нову заједницу. Погледајте опције конфигурације са стране. Одатле можете конфигурирати како ваша заједница функционише. <b>Подразумевано, само корисници у улози „Администратор“ могу видети овај део ваше заједнице.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Овде можете омогућити и испробати нове Ванилла функције, странице и компоненте.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Ова лабораторија не може да се онемогући јер је примењен прилагођени изглед.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Ова лабораторија се не може онемогућити јер то захтева тренутна тема.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Овај лого се појављује на врху вашег сајта. Теме направљене помоћу уређивача тема и неке прилагођене теме не користе ово подешавање.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Ово се може користити за укључивање садржаја као што су назив организације и адреса у све одлазне е-поруке.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Ова опција приказује / скрива локације на којима џепови могу ићи, али само за кориснике који имају дозволу за додавање / уређивање џепова. Покушајте да прикажете локације, а затим посетите своју веб локацију.';
$Definition['This page lists the endpoints of your API.'] = 'Ова страница наводи крајње тачке вашег АПИ-ја. Кликните крајње тачке за више информација. Можете да упућујете активне позиве АПИ-ју са ове странице или екстерно користећи приступни токен.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Ова улога је лични податак. Само корисници који имају дозволу за преглед личних података видјет ће их.';
$Definition['This setting loads the page before executing Javascript.'] = 'Ovo podešavanje učitava stranicu pre Javascript izvršenja, što može poboljšati vaš SEO. <br> <strong> ** Upozorenje: Omogućavanje ove funkcije može prouzrokovati JavaScript greške na vašoj veb lokaciji.** </strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Ово подешавање учитава страницу пре извршавања Јавасцрипт-а што може побољшати ваш СЕО.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Ову тему није могуће избрисати јер је тренутно примењена тема.';
$Definition['Tiled Layout'] = 'Тилед Лаиоут';
$Definition['Title Bar'] = 'Насловна трака';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Да бисте уградили ваш Ванилла форум на своју веб локацију, користите следећи код.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Превише адреса! Послаћемо до %s адресе одједном.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Да би се спречила злоупотреба, неки алати аутоматски сакривају садржај и овде га наводе све док га модератор ручно не одобри.';
$Definition['TouchIconDescription'] = 'Икона на додир појављује се када обележите веб локацију на почетном екрану Аппле уређаја. Обично су то 152 пиксела. Аппле аутоматски додаје заобљене углове и осветљење.';
$Definition['Transparent'] = 'Транспарентно';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Твиттер Цоннецт омогућава корисницима да се пријаве помоћу свог Твиттер налога. <b>Морате да региструјете своју апликацију на Твиттеру да би овај додатак могао да функционише.</b>';

$Definition['Usercards'] = 'Корисничке картице';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Корисничке картице вам омогућавају да брзо добијете ин-лине снимак информација о кориснику. Када прегледате постове и табеле са резултатима, кликните на корисничко име да бисте видели картицу која приказује основне информације о профилу корисника без потребе да се крећете са странице. Омогућите ову функцију да додате корисничке картице вашој прилагођеној теми.';
$Definition['User inputs are based on the global background and text colors.'] = 'Уноси корисника заснивају се на глобалној боји позадине и текста.';
$Definition['User Profile'] = 'Профил корисника';
$Definition['Users may sign into your site using their Twitter account.'] = 'Корисници могу да се пријаве на вашу веб локацију користећи свој Твиттер налог.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Употријебите типку на врху странице како бисте створили правило забране.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Користите ВордПресс додатак да бисте поставили Ванилла Цомментс на свом блогу или користите универзални код да бисте поставили Ванилла Цомментс на било којој другој платформи.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Ванилин нови сервис за претрагу је коначно стигао. Омогућите наш нови кориснички интерфејс странице за претрагу да бисте добили приступ најновијим функцијама претраге као што су Претрага чланова, сортирање претраге и истицање термина.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Извоз ванилије: %s, Извор: %s';
$Definition['Vanilla Labs'] = 'Ванилла Лабс';
$Definition['Vanilla Statistics are currently disabled'] = 'Статистика ванилије тренутно је онемогућена';
$Definition['Verify and restore'] = 'Верификујте и вратите';
$Definition['VerifyUser'] = 'Означите поље поред корисника да бисте их означили као <b>верификоване</b> како њихови постови не би поново били означени као нежељени. Ово ће такође вратити све њихове постове на чекању.';
$Definition['Video tutorial on advanced settings'] = 'Видео туториал о напредним подешавањима';
$Definition['Video tutorial on finding &amp; managing users'] = 'Видео туториал о проналажењу и управљању корисницима';
$Definition['Video tutorial on managing appearance'] = 'Видео туториал о управљању изгледом';
$Definition['Video tutorial on managing categories'] = 'Видео туториал о управљању категоријама';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Видео туториал о управљању улогама и дозволама';
$Definition['Video tutorial on user registration'] = 'Видео туториал о регистрацији корисника';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Упозорење: Омогућавање ове функције може проузроковати погрешке ЈаваСцрипта на вашој веб локацији.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Упозорење</b> : Конфигурација вашег сервера не подржава брзо учитавање података. Ако увозите веома велику датотеку (нпр. Преко 200.000 коментара), можда бисте желели да размотрите промену своје конфигурације. Кликните <a href="http://vanillaforums.com/porter">овде</a> за више информација.';
$Definition['Warning: This is for advanced users.'] = '<b>Упозорење</b> : Ово је за напредне кориснике и захтева додавање додатних промена на вашем веб серверу. Обично је доступан само ако имате наменски или впс хостинг. Не покушавајте ово ако не знате шта радите.';
$Definition['Webhooks'] = 'Вебхоокс';
$Definition['Welcome to Labs!'] = 'Добро дошли у Лабс!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Добродошли у корисничко сучеље тематике Ванилла. Ова страница наводи све ваше доступне теме и омогућава вам да их копирате или измените.';
$Definition['Welcome To Your Theme'] = 'Добродошли у вашу тему';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Ми углавном препоручујемо позитивне реакције за подстицање учешћа.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Када је омогућено, корисници могу изабрати да примају обавештења од заједнице';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Када је омогућено, можете да управљате производима и групишете подкомуне према тим производима.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Када неко дели везу са ваше веб локације, покушавамо да снимимо слику са странице. Ако на страници нема слике, тада ћемо је користити ту слику. Слика би требала бити најмање 50 × 50, али препоручујемо 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Када одаберете Фулл Блеед, позадина вам је прозирна.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Да ли ће интерна поља профила бити укључена у овај веб-хук.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Да ли ће поља приватног профила бити укључена у овај веб-хук.';
$Definition['Which reactions you use really depends on your community.'] = 'Које реакције заиста користите зависи од заједнице, али препоручујемо да имате на уму неколико тачака.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Применићете нову опцију изгледа. Ово се може прилагодити и прегледати помоћу нашег уређивача тема. <0> Сазнајте више</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Можете забранити свим корисницима ИП адресе са префиксом „111.111.111“ додавањем забране типа ИП са вредностом „111.111.111. *“.';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Можете забранити ИП адресе, адресе е-поште и корисничка имена.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Можете изабрати један од различитих стилова које ова тема нуди.';
$Definition['You can configure some values differently for different screensizes.'] = 'Неке вредности можете другачије конфигурирати за различите величине заслона.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Можете да се повежете на више веб локација које подржавају јсЦоннецт.';
$Definition['You can place files in your /uploads folder.'] = 'Ако је ваша датотека превелика да бисте је директно пренијели на ову страницу, можете је смјестити у мапу / уплоад. Уверите се да име датотеке започиње речју <b>извоз</b> и завршава једним од <b>.ткт, .гз</b> .';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Можете одредити минималну дужину поста да бисте обесхрабрили кратке постове.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Можете да пошаљете прилагођени фонт у ваш систем за темирање. Само копирајте и залепите УРЛ у поље.';
$Definition['You must select a file to import.'] = 'Морате одабрати датотеку коју желите да увозите.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Морате да додате домен УРЛ-а фонта у <0> Дозвољене домене </0> у конфигурацији сајта. <1> Сазнајте више о прилагођеним фонтовима. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Ваша тема за мобилне уређаје биће онемогућена. Да бисте поставили различите теме за мобилне уређаје и радне површине, користите стари тематски интерфејс.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Назив ваше организације се користи за СЕО микроподатке и ЈСОН+ЛД';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Фавицон ваше странице приказује се у насловној траци прегледача. Биће смањен на одговарајући начин.';
