<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = 'Ο χρήστης %1$s αποδέχτηκε την πρόσκληση μέλους του χρήστη %4$s.';
$Definition['%1$s changed %4$s permissions.'] = 'Ο χρήστης %1$s άλλαξε τα δικαιώματα του χρήστη %4$s.';
$Definition['%1$s changed %6$s profile picture.'] = 'Ο χρήστης %1$s άλλαξε την εικόνα προφίλ του χρήστη %6$s.';
$Definition['%1$s commented on %4$s %8$s.'] = 'Ο χρήστης %1$s σχολίασε για %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = 'Ο χρήστης %1$s δημιούργησε ένα λογαριασμό για το χρήστη %4$s.';
$Definition['%1$s joined.'] = 'Ο χρήστης %1$s προσχώρησε.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = 'Ο χρήστης %1$s αναφέρθηκε στο χρήστη %3$s στο %8$s.';
$Definition['%1$s on %2$s'] = '%1$s στο %2$s';
$Definition['%1$s signed in.'] = 'Ο χρήστης %1$s συνδέθηκε';
$Definition['%1$s to %2$s'] = '%1$s σε %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s σε %2$s από %3$s';
$Definition['%1$s updated %6$s profile.'] = 'Ο χρήστης %1$s ενημέρωσε το προφίλ του χρήστη %6$s.';
$Definition['%1$s was added to the %2$s %3$s.'] = 'Ο χρήστης %1$s προστέθηκε στα %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s.'] = 'Ο χρήστης %1$s απομακρύνθηκε από τα %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = 'Ο χρήστης %1$s απομακρύνθηκε από τα %2$s %3$s και προστέθηκε στα %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = 'Ο χρήστης %1$s έγραψε στο %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = 'Ο χρήστης %3$s ενέκρινε την αίτηση μέλους του χρήστη %2$s.';
$Definition['%3$s created an account for %1$s.'] = 'Ο χρήστης %3$s δημιούργησε ένα λογαριασμό για τον χρήστη %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 σε %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 σε %s$2 από %s$3';
$Definition['%s (Current)'] = '%s (Τρέχων)';
$Definition['%s Agrees'] = 'Ο χρήστης %s συμφωνεί';
$Definition['%s and you'] = 'Ο χρήστης %s και εσείς';
$Definition['%s Awesomes'] = 'Ο χρήστης %s είναι φοβερός';
$Definition['%s by %s'] = '%s από %s';
$Definition['%s changed %s\'s permissions.'] = 'ο %s άλλαξε τα δικαιώματα του χρήστη %s.';
$Definition['%s Comment'] = '%s Σχόλιο';
$Definition['%s comment'] = '%s σχόλιο';
$Definition['%s Comments'] = '%s Σχόλια';
$Definition['%s comments'] = '%s σχόλια';
$Definition['%s Connect'] = 'Ο χρήστης %s συνδέθηκε';
$Definition['%s day'] = '%s ημέρα';
$Definition['%s days'] = '%s ημέρες';
$Definition['%s deleted this conversation.'] = 'ο χρήστης %s διέγραψε αυτή τη συνομιλία.';
$Definition['%s discussion'] = '%s συζήτηση';
$Definition['%s discussions'] = '%s συζητήσεις';
$Definition['%s has been Jailed.'] = 'ο χρήστης %s Φυλακίστηκε.';
$Definition['%s has left this conversation.'] = 'ο χρήστης %s έφυγε από αυτή τη συνομιλία.';
$Definition['%s hour'] = '%s ώρα';
$Definition['%s hours'] = '%s ώρες';
$Definition['%s Insightfuls'] = 'Ο χρήστης %s είναι διορατικός';
$Definition['%s level deep'] = '%s βάθος επιπέδου';
$Definition['%s levels deep'] = '%s βάθος επιπέδων';
$Definition['%s Likes'] = 'Στον χρήστη %s αρέσει';
$Definition['%s LOLs'] = 'Ο χρήστης %s γέλασε δυνατά';
$Definition['%s member'] = '%s μέλος';
$Definition['%s members'] = '%s μέλη';
$Definition['%s mentioned %s in a %s.'] = 'Ο χρήστης %s ανέφερε τον χρήστη %s σε μία %s.';
$Definition['%s message'] = '%s μήνυμα';
$Definition['%s messages'] = '%s μηνύματα';
$Definition['%s minute'] = '%s λεπτό';
$Definition['%s minutes'] = '%s λεπτά';
$Definition['%s month'] = '%s μήνας';
$Definition['%s months'] = '%s μήνες';
$Definition['%s New'] = '%s Νέο';
$Definition['%s new'] = '%s νέο';
$Definition['%s new comment since you last read this.'] = '%s νέα σχόλια από την τελευταία φορά που το διαβάσατε.';
$Definition['%s new comments since you last read this.'] = '%s νέα σχόλια από την τελευταία φορά που το διαβάσατε.';
$Definition['%s New Plural'] = '%s Νέα';
$Definition['%s new plural'] = '%s νέο';
$Definition['%s Not Found'] = '%s Δε Βρέθηκε';
$Definition['%s Point'] = '%s Βαθμός';
$Definition['%s point'] = '%s βαθμός';
$Definition['%s Points'] = '%s Βαθμοί';
$Definition['%s points'] = '%s βαθμοί';
$Definition['%s result'] = '%s αποτέλεσμα';
$Definition['%s results'] = '%s αποτελέσματα';
$Definition['%s said'] = 'Ο χρήστης %s είπε';
$Definition['%s said:'] = 'Ο χρήστης %s είπε:';
$Definition['%s tag(s) found.'] = 'Βρέθηκαν %s ετικέτες.';
$Definition['%s tags in the system'] = '%s ετικέτες στο σύστημα';
$Definition['%s Up Votes'] = 'Ο χρήστης %s ψήφισε θετικά';
$Definition['%s view'] = '%s ανάγνωση';
$Definition['%s views'] = '%s αναγνώσεις';
$Definition['%s votes'] = '%s ψήφοι';
$Definition['%s was removed from the %s and added to the %s'] = 'Ο χρήστης %s αφαιρέθηκε από το %s και προστέθηκε στο %s';
$Definition['%s week'] = '%s εβδομάδα';
$Definition['%s weeks'] = '%s εβδομάδες';
$Definition['%s WTFs'] = 'Ο χρήστης %s απόρησε';
$Definition['%s year'] = '%s έτος';
$Definition['%s years'] = '%s έτη';

$Definition['(empty message)'] = '(κενό μήνυμα)';

$Definition['+%s Guests'] = '+%s Επισκέπτες';

$Definition[' - Page %s'] = '- Σελίδα %s';

$Definition['1 message'] = '1 μήνυμα';

$Definition['<General Error>'] = '<Γενικό Σφάλμα>';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Η Αίτησή Μέλους Εγκρίθηκε ';
$Definition['[%s] Welcome Aboard!'] = '[%s] Καλωσήλθατε!';
$Definition['[Deleted User]'] = '[Διεγραμμένος Χρήστης]';

$Definition['About'] = 'Σχετικά';
$Definition['AboutToDelete'] = 'Πρόκειται να διαγράψετε το %s.';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Πρόκειται να διαγράψετε το %1$s από το %2$s των επιλεγμένων συζητήσεων.';
$Definition['Abuse'] = 'Κατάχρηση';
$Definition['Accept'] = 'Αποδοχή';
$Definition['Accept this answer.'] = 'Δεχτείτε αυτή την απάντηση';
$Definition['Account Options'] = 'Επιλογές Λογαριασμού';
$Definition['Activate'] = 'Ενεργοποίηση';
$Definition['Active'] = 'Ενεργός';
$Definition['Active Users'] = 'Ενεργοί Χρήστες';
$Definition['Activity'] = 'Δραστηριότητα';
$Definition['Activity.AnswerAccepted.FullHeadline'] = 'Ο χρήστης %1$s αποδέχτηκε %4$s %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = 'Ο χρήστης %1$s σχολίασε στο %8$s σας.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = 'Ο χρήστης %1$s σχολίασε στο %8$s σας.';
$Definition['Activity.Comment'] = 'Σχόλιο';
$Definition['Activity.CommentMention.FullHeadline'] = 'Ο χρήστης %1$s αναφέρθηκε %3$s σε ένα %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = 'Ο χρήστης %1$s αναφέρθηκε %3$s ένα %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = 'Ο/Η %1$s σας έστειλε ένα %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = 'Ο/Η %1$s σας έστειλε ένα %8$s.';
$Definition['Activity.Join.FullHeadline'] = 'Ο χρήστης %1$s προσχώρησε.';
$Definition['Activity.Join.ProfileHeadline'] = 'Ο χρήστης %1$s προσχώρησε.';
$Definition['Activity.PictureChange.FullHeadline'] = 'Ο χρήστης %1$s άλλαξε την εικόνα προφίλ του %6$s.';
$Definition['Activity.PictureChange.ProfileHeadline'] = 'Ο χρήστης %1$s άλλαξε την εικόνα προφίλ του %6$s.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = 'Ο χρήστης %1$s απάντηστε %4$s %8$s.';
$Definition['Add'] = 'Προσθήκη';
$Definition['Add a Comment'] = 'Προσθέστε Σχόλιο';
$Definition['Add a Message'] = 'Προσθέστε Μήνυμα';
$Definition['Add another poll option ...'] = 'Προσθέστε μία επιπλέον επιλογή ... ';
$Definition['Add a Profile Picture'] = 'Προσθέστε Εικόνα Προφιλ';
$Definition['Add a Warning'] = 'Προσθέστε Προειδοποίηση';
$Definition['Add Badge'] = 'Προσθέστε Έμβλημα';
$Definition['Add Comment'] = 'Προσθέστε Σχόλιο';
$Definition['Add Cost'] = 'Προσθέστε Κόστος';
$Definition['Add Image'] = 'Προσθέστε Εικόνα';
$Definition['Add Message'] = 'Προσθέστε Μήνυμα';
$Definition['Add Note'] = 'Προσθήκη Σημείωσης';
$Definition['Add People to this Conversation'] = 'Προσθέστε Ατομα σε αυτή τη Συνομιλία';
$Definition['Add Route'] = 'Προσθέστε Δρομολόγηση';
$Definition['Admin'] = 'Διαχειριστής';
$Definition['Administrator'] = 'Διαχειριστής';
$Definition['Administrator Activity'] = 'Δραστηριότητα Διαχειριστή';
$Definition['administrators'] = 'διαχειριστές';
$Definition['Advanced Stuff'] = 'Για Προχωρημένους';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Ένα καίριο λάθος προκλήθηκε κατά την επεξεργασία της αίτησής σας.<br />Ο Εξυπηρετητής επέστρεψε το ακόλουθο μήνυμα μήνυμα: %s';
$Definition['Agree'] = 'Συμφωνώ';
$Definition['Alert'] = 'Προειδοποίηση';
$Definition['All %s'] = 'Όλοι οι %s';
$Definition['All %s...'] = 'Όλα %s...';
$Definition['All Bookmarks'] = 'Όλοι οι Σελιδοδείκτες';
$Definition['All Categories'] = 'Όλες οι Κατηγορίες';
$Definition['all categories'] = 'όλες οι κατηγορίες';
$Definition['All Conversations'] = 'Όλες οι Συνομιλίες';
$Definition['All Discussions'] = 'Όλες οι Συζητήσεις';
$Definition['All Events'] = 'Όλες οι Εκδηλώσεις';
$Definition['All members'] = 'Όλα τα μέλη';
$Definition['Allow'] = 'Επίτρεψε';
$Definition['Allow other members to see your email?'] = 'Επιτρέπετε σε άλλα μέλη να βλεπουν το email σας;';
$Definition['All Time Leaders'] = 'Ηγέτες Όλων των Εποχών';
$Definition['Ancient Membership'] = 'Αρχείο Μέλος';
$Definition['An invitation has already been sent to the email you entered.'] = 'Έχει σταλεί ήδη μία πρόσκληση στο email που δώσατε.';
$Definition['Announce'] = 'Ανακοίνωση';
$Definition['Announce...'] = 'Ανακοινώστε...';
$Definition['Announcement'] = 'Ανακοίνωση';
$Definition['Announcements'] = 'Ανακοινώσεις';
$Definition['Announce this discussion'] = 'Ανακοινώστε αυτή τη συζήτηση.';
$Definition['Answer'] = 'Απάντηση';
$Definition['answer'] = 'απάντηση';
$Definition['Answers'] = 'Απαντήσεις';
$Definition['answers'] = 'απαντήσεις';
$Definition['Applicant'] = 'Αιτών';
$Definition['Applicants'] = 'Αιτούντες';
$Definition['Applicants & Invitations'] = 'Αιτούντες &amp; Προσκλήσεις';
$Definition['Apply Changes'] = 'Εφαρμογή Αλλαγών';
$Definition['Apply for Membership'] = 'Εγγραφή Μέλους';
$Definition['Apply for membership'] = 'Αίτηση μέλους';
$Definition['Approve'] = 'Εγκρίνεται';
$Definition['Approve Applicant'] = 'Εγκρίνεται';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Είστε ΑΠΟΛΥΤΑ σίγουρος ότι θέλετε να γίνει αυτό;';
$Definition['Are you sure you want to delete this %s?'] = 'Είστε σίγουρος ότι θέλετε να διαγράψετε το %s;';
$Definition['Are you sure you want to do that?'] = 'Είσαι σίγουρος ότι θέλετε να το κάνετε αυτό;';
$Definition['Are you sure you want to do this?'] = 'Είστε σίγουρος ότι θέλετε να το κάνετε αυτό;';
$Definition['Are you sure you want to join this group?'] = 'Θέλετε σίγουρα να γίνετε μέλος αυτής της ομάδας;';
$Definition['Are you sure you want to leave this group?'] = 'Θέλετε σίγουρα να εγκαταλείψετε αυτή την ομάδα;';
$Definition['Are you sure you wish to continue?'] = 'Είστε σίγουρος ότι θέλετε να συνεχίσετε;';
$Definition['Ask a Question'] = 'Κάντε μια ερώτηση';
$Definition['Ask Question'] = 'Κάντε μία Ερώτηση';
$Definition['Attach a file'] = 'Επισύναψη αρχείου';
$Definition['Attach image/file'] = 'Επισύναψε εικόνα/αρχείο';
$Definition['Attachments'] = 'Συνημμένα';
$Definition['Attach this warning to the %s.'] = 'Επισυνάψτε αυτήν την προειδοποίηση προς τον/την %s.';
$Definition['AttemptingSignOut'] = 'Προσπαθείτε να βγείτε από το σύστημα. Είστε βέβαιος ότι θετε να %s;';
$Definition['Authenticate URL'] = 'Πιστοποίηση URL';
$Definition['Author'] = 'Συγγραφέας';
$Definition['available'] = 'διαθέσιμος';
$Definition['Awaiting Moderation'] = 'Αναμονή Συντονισμού';
$Definition['Awesome'] = 'Φοβερό';

$Definition['Back to Discussions'] = 'Πίσω στους Διαγωνισμούς';
$Definition['Back to Profile'] = 'Επιστροφή στο Προφίλ';
$Definition['Badge'] = 'Έμβλημα';
$Definition['Badge404'] = 'Το Έμβλημα δε βρέθηκε.';
$Definition['Badges'] = 'Εμβλήματα';
$Definition['BadgesModuleTitle'] = 'Εμβλήματα';
$Definition['BadgesNobody'] = 'Κανείς δεν έχει αποκτήσει αυτό το έμβλημα ακόμη.';
$Definition['Ban'] = 'Αποκλεισμός';
$Definition['Ban.Action'] = 'Αποκλεισμός';
$Definition['Banned'] = 'Αποκλεισμένος';
$Definition['Banned for being abusive.'] = 'Αποκλεισμένος λόγω εξύβρισης';
$Definition['Banned for spamming.'] = 'Αποκλεισμένος λόγω spamming';
$Definition['Banned users can no longer access the site.'] = 'Οι αποκλεισμένοι χρήστες δεν έχουν πλέον πρόσβαση στη σελίδα.';
$Definition['Banner'] = 'Αποκλειστής';
$Definition['Ban User'] = 'Αποκλεισμός Χρήστη';
$Definition['Ban Value'] = 'Τιμή Αποκλεισμού';
$Definition['Best Answer'] = 'Καλύτερη Απάντηση';
$Definition['Best Answers'] = 'Καλύτερες Απαντήσεις';
$Definition['Best Of'] = 'Τα καλύτερα';
$Definition['Best Of...'] = 'Τα καλύτερα...';
$Definition['Blank Discussion Topic'] = 'Κενό Θέμα Συζήτησης';
$Definition['Blank Message'] = 'Κενό Μήνυμα';
$Definition['Blog'] = 'Ιστολόγιο';
$Definition['Blogs'] = 'Ιστολόγια';
$Definition['Body'] = 'Σώμα';
$Definition['Bold'] = 'Έντονη γραφή';
$Definition['Bookmark'] = 'Αγαπημένο';
$Definition['Bookmarked Discussions'] = 'Αγαπημένες Συζητήσεις';
$Definition['Bookmarks'] = 'Αγαπημένα';
$Definition['bookmarks'] = 'Αγαπημένα';
$Definition['Browse Groups'] = 'Αναζήτηση ομάδων';
$Definition['By'] = 'Από';
$Definition['by'] = 'από';
$Definition['by Date'] = 'με Ημερομηνία';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Ανεβάζοντας ένα αρχείο πιστοποιείτε ότι έχετε το δικαίωμα να διανέμετε την εικόνα και ότι αυτό δεν έρχεται σε αντίθεση με τους Όρους Χρήσης.';

$Definition['Cancel'] = 'Ακύρωση';
$Definition['Casual'] = 'Τυχαίος';
$Definition['Categories'] = 'Κατηγορίες';
$Definition['CategoriesShowFollowed'] = 'Να εμφανίζονται οι συζητήσεις που ακολουθώ';
$Definition['CategoriesShowUnfollowed'] = 'Εμφάνιση κρυμμένων κατηγοριών';
$Definition['CategoriesViewingAll'] = 'Βλέπετε όλες τις κατηγορίες.';
$Definition['CategoriesViewingFollowed'] = 'Βλέπετε μόνο τις κατηγορίες που ακολουθείτε.';
$Definition['Category'] = 'Κατηγορία';
$Definition['Category Filter'] = 'Φίλτρο Κατηγορίας';
$Definition['CategoryID'] = 'Κατηγορία';
$Definition['Category Management'] = 'Διαχείριση Κατηγοριών';
$Definition['Category Notifications'] = 'Ειδοποιήσεις Κατηγοριών';
$Definition['Category to Use'] = 'Κατηγορία προς Χρήση';
$Definition['Change'] = 'Αλλαγή';
$Definition['Change language'] = 'Αλλαγή γλώσσας';
$Definition['Change My Password'] = 'Αλλαγή του Κωδικού μου';
$Definition['Change My Picture'] = 'Αλλαγή της Εικόνας μου';
$Definition['Change Password'] = 'Αλλαγή Κωδικού';
$Definition['Change Picture'] = 'Αλλαγή Εικόνας';
$Definition['Check all roles that apply to this user:'] = 'Τσεκάρετε όλους τους ρόλους που σχετίζονται με αυτόν τον χρήστη:';
$Definition['Child Categories'] = 'Υποκατηγορίες';
$Definition['Child Categories:'] = 'Υποκατηγορίες:';
$Definition['Choose a name to identify yourself on the site.'] = 'Επιλέξτε ένα αναγνωριστικό όνομα γι αυτό το χώρο.';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Επιλέξτε την κύρια συζήτηση στην οποία θα ενοποιηθούν όλα τα σχόλια:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Επιλέξτε αν θέλετε να θέσετε ένα ερώτημα ή να ξεκινήσετε μία συζήτηση.';
$Definition['Clear'] = 'Καθαρισμός';
$Definition['clear'] = 'καθαρισμός';
$Definition['Clear Conversation History'] = 'Καθαρισμός Ιστορικού Συνομιλιών';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Πατήστε <a href="%s">εδώ</a> για να επιστρέψετε στη συζήτηση.';
$Definition['Click accept or reject beside an answer.'] = 'Πατήστε για να αποδεχτείτε ή να απορρίψετε δίπλα σε μία απάντηση.';
$Definition['clicking here'] = 'πατώντας εω';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Πατήστε στο %s δίπλα στις συζητήσεις για να τις βάλετε στα αγαπημένα.';
$Definition['Click to re-attach'] = 'Κάντε κλικ για να επισυνάψετε εκ νέου.';
$Definition['Close'] = 'Κλείσιμο';
$Definition['Closed'] = 'Κλειστό';
$Definition['Close this discussion'] = 'Κλείσιμο αυτής της συζήτησης';
$Definition['Color'] = 'Χρώμα';
$Definition['Combo Breaker'] = 'Συνδυαστικός Διαχωριστής';
$Definition['Comment'] = 'Σχόλιο';
$Definition['comment'] = 'σχόλιο';
$Definition['Comment As ...'] = 'Σχολιασμός Ως ...';
$Definition['Comment by %s'] = 'Σχόλιο από το χρήστη %s';
$Definition['Comment in'] = 'σε';
$Definition['Commenting as %1$s (%2$s)'] = 'Σχολιάζετε ως %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Ο σχολιασμός δεν επιτρέπεται.';
$Definition['Comments'] = 'Σχόλια';
$Definition['comments'] = 'Σχόλια';
$Definition['Comments are between {UserID,you}.'] = 'Τα σχόλια είναι μεταξύ {UserID,you}.';
$Definition['Community'] = 'Κοινότητα';
$Definition['Community Guidelines'] = 'Οδηγίες Κοινότητας';
$Definition['Completely delete the warning.'] = 'Πλήρης διαγραφή της προειδοποίησης.';
$Definition['Confirm'] = 'Επιβεβαίωση';
$Definition['Confirm Email'] = 'Επιβεβαίωση Email';
$Definition['Confirm Password'] = 'Επιβεβαίωση Κωδικού';
$Definition['Connect'] = 'Σύνδεση';
$Definition['ConnectAccountExists'] = 'Έχετε ήδη λογαριασμό εδώ.';
$Definition['ConnectChooseName'] = 'Επιλέξτε ένα όνομα για να σας αναγνωρίζουν σε αυτό το χώρο.';
$Definition['ConnectCreateAccount'] = 'Προσθήκη Πληροφορίας &amp; Δημιουργία Λογαριασμού';
$Definition['Connected'] = 'Συνδεδεμένος';
$Definition['ConnectExistingPassword'] = 'Δώστε τον υπάρχοντα κωδικό λογαριασμού.';
$Definition['Connecting...'] = 'Σύνδεση...';
$Definition['Connection'] = 'Σύνδεση';
$Definition['ConnectLeaveBlank'] = 'Αφήστε το κενό εκτός αν συνδέεστε με υπάρχοντα λογαριασμό.';
$Definition['ConnectName'] = 'Όνομα Χρήστη';
$Definition['ConnectRegisteredName'] = 'Γραφτήκατε με το όνομα χρήστη: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Συνδέστε το προφίλ σας με τα κοινωνικά σας δίκτυα για να ενημερώνεστε εδώ για κάθε δραστηριότητα και να την μοιράζεστε με τους φίλους και ακόλουθούς σας.';
$Definition['Contact Us'] = 'Επικοινωνήστε με εμάς';
$Definition['conversation'] = 'συνομιλία';
$Definition['Core'] = 'Πυρήνας';
$Definition['Created'] = 'Δημιουργήθηκε';
$Definition['Create Discussions'] = 'Δημιουργία Συζητήσεων';
$Definition['Create One.'] = 'Δημιουργία ενός.';
$Definition['Current'] = 'Τρέχων';
$Definition['Currently: '] = 'Αυτή τη στιγμή:';
$Definition['Custom Information'] = 'Προσαρμοσμένες Πληροφορίες';
$Definition['Customize'] = 'Προσαρμογή';
$Definition['customize your profile now'] = 'προσαρμόστε το προφίλ σας τώρα';
$Definition['Customize your Public Profile'] = 'Προσαρμόστε το Δημόσιο προφίλ σας';
$Definition['Custom Profile Fields'] = 'Ιδιότητες Προσαρμοσμένων Πεδίων';
$Definition['Custom Profile Field Settings'] = 'Ρυθμίσεις Προσαρμοσμένων Πεδίων Προφίλ';

$Definition['Dashboard'] = 'Ταμπλό';
$Definition['Dashboard Home'] = 'Αρχικό Ταμπλό';
$Definition['Dashboard Summaries'] = 'Περίληψη Ταμπλό';
$Definition['Date'] = 'Ημερομηνία';
$Definition['Date Added'] = 'Ημερομηνία προσθήκης';
$Definition['Date Examples'] = 'Παραδείγματα: Δευτέρα, σήμερα, την περασμένη εβδομάδα, 26 Μάρτιου, 26/03/04';
$Definition['Date within'] = 'Ημερομηνία εντός';
$Definition['days'] = 'ημέρες';
$Definition['Define Thumbnail'] = 'Πατήστε και τραβήξτε  την εικόνατην για να καθορίσετε τη μικρογραφία σας.';
$Definition['Delete'] = 'Διαγραφή';
$Definition['Delete %s'] = 'Διαγράψτε %s';
$Definition['Delete Account'] = 'Διαγραφή Λογαριασμού';
$Definition['Delete Conversation'] = 'Διαγραφή Συνομιλίας';
$Definition['Delete Discussion'] = 'Διαγραφή Συζήτησης';
$Definition['Delete Group'] = 'Διαγραφή Ομάδας';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Διαγράψτε το χρήστη και όλα τα περιεχόμενά του. Αυτό θα κάνει τις συζητήσεις να φαίνονται αποσπασματικές, και θα φαίνεται ότι οι άνθρωποι που απάντησαν δεν υπήρχαν.Αυτό είναι μια σημαντική επιλογή για την αφαίρεση περιεχομένου ενός spammer.';
$Definition['Delete User Content'] = 'Διαγραφή Περιεχομένων Χρήστη';
$Definition['Delete User Forever'] = 'Διαγραφή Χρήστη για Πάντα';
$Definition['Deny'] = 'Άρνηση';
$Definition['Deny Applicant'] = 'Άρνηση';
$Definition['Did this answer the question?'] = 'Απάντησε αυτό στην ερώτηση;';
$Definition['Disagree'] = 'Διαφωνώ';
$Definition['Discussion'] = 'Συζήτηση';
$Definition['discussion'] = 'συζήτηση';
$Definition['Discussion Board'] = 'Πίνακας Συζητήσεων';
$Definition['Discussions'] = 'Συζητήσεις';
$Definition['discussions'] = 'συζητήσεις';
$Definition['Discussions Page'] = 'Σελίδα Συζητήσεων';
$Definition['Discussion Title'] = 'Τίτλος Συζήτησης';
$Definition['Dislike'] = 'Δε μου αρέσει';
$Definition['Dismiss'] = 'Απόρριψη';
$Definition['Don\'t announce.'] = 'Χωρίς ανακοίνωση.';
$Definition['Don\'t fold quotes'] = 'Μην αναδιπλώνετε φράσεις';
$Definition['Don\'t have an account? %s'] = 'Δεν έχετε λογαριασμό; %s';
$Definition['Do you want to expire or delete this warning?'] = 'Θέλετε να λήξει ή να διαγράψετε αυτή την προειδοποίηση;';
$Definition['Draft saved at %s'] = 'Το Προσχέδιο αποθηκεύτηκε στο %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Σύρετε και αλλάξτε το μέγεθος του τετραγώνου παρακάτω για να ορίσετε το εικονίδιο της μικρογραφίας σας.';
$Definition['Drop image/file'] = 'τοποθέτησε την εικόνα/αρχείο';

$Definition['Earned'] = 'Κερδισμένα';
$Definition['Edit'] = 'Επεξεργασία';
$Definition['Edit Account'] = 'Επεξεργασία Λογαριασμού';
$Definition['Edit Comment'] = 'Επεξεργασία Σχόλιου';
$Definition['Edit Discussion'] = 'Επεξεργασία Συζήτησης';
$Definition['edited %s'] = 'επεξεργάστηκε %s';
$Definition['Edited %s by %s.'] = 'Επιμέλήθηκε %s από %s';
$Definition['Edit My Account'] = 'Επεξεργασία του Λογαριασμού μου';
$Definition['Edit My Profile'] = 'Επεξεργασία του Προφίλ Μου';
$Definition['Edit My Thumbnail'] = 'Επεξεργασία της Μικρογραφίας μου';
$Definition['editor.BBCodeHelpText'] = 'Τώρα μπορείτε να χρησιμοποιήσετε το <a href="http://en.wikipedia.org/wiki/BBCode" target="_new">BBCode</a> στο post σας.';
$Definition['editor.HtmlHelpText'] = 'Μπορείτε να χρησιμοποιήσετε το <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple Html</a> στη δημοσίευσή σας.';
$Definition['editor.MarkdownHelpText'] = 'Μπορείτε να χρησιμοποιήσετε το <a href="http://en.wikipedia.org/wiki/Markdown" target="_new">Markdown</a> στη δημοσίευσή σας.';
$Definition['editor.TextHelpText'] = 'Χρησιμοποιείτε απλό κείμενο στη δημοσίευσή σας.';
$Definition['editor.WysiwygHelpText'] = 'Χρησιμοποιείτε το <a href="https://en.wikipedia.org/wiki/WYSIWYG" target="_new">Wysiwyg</a> στη δημοσίευσή σας.';
$Definition['Edit Preferences'] = 'Επεξεργασία Προτιμήσεων';
$Definition['Edit Profile'] = 'Επεξεργασία Προφίλ';
$Definition['Edit Tag'] = 'Επεξεργασία Ετικέτας';
$Definition['Edit Thumbnail'] = 'Επεξεργασία Μικρογραφίας';
$Definition['Eighth Anniversary'] = 'Όγδοη Επέτειος';
$Definition['Email/Username'] = 'Email/Όνομα Χρήστη';
$Definition['EmailConfirmEmail'] = 'Πρέπει να επιβεβαιώσετε τη διεύθυνση του email σας πριν προχωρήσετε. Παρακαλώ επιβεβαιώστε τη διεύθυνση του email σας ακολουθώντας τον πιο κάτω σύνδεσμο: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '↳ Να έχετε μια υπέροχη μέρα!';
$Definition['EmailHeader'] = 'Γεια σας {User.Name}!
';
$Definition['EmailInvitation'] = 'Γεια ας!

Ο χρήσης %1$s σας κάλεσε να συνδεθείτε στο %2$s. Αν θέλετε να συνδεθείτε, μπορείτε να το κάνετε πατώντας σε αυτό το σύνδεσμο:

%3$s';
$Definition['EmailMembershipApproved'] = 'Γεια σας %1$s,

Έχει γίνει δεκτή η αίτηση μέλους σας. Συνδεθείτε τώρα στον ακόλουθο σύνδεσμο:

%2$s';
$Definition['EmailNotification'] = '%1$s

Ακολουθήστε τον παρακάτω σύνδεσμο για να το τσεκάρετε:
%2$s

Να έχετε μια υπέροχη μέρα!';
$Definition['Email Notifications'] = 'Ειδοποιήσεις Email';
$Definition['Email Or Username'] = 'Email ή Όνομα Χρήστη';
$Definition['EmailPassword'] = 'Ο χρήστης %2$s έχει αλλάξει τον κωδικό σας στο %3$s. Τα στοιχεία της σύνδεσής σας είναι πλέον:

  Email: %6$s
  Κωδικός: %5$s
  Url: %4$s';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Τα email που θα στέλνονται από την εφαρμογή θα φαίνονται ότι στάλθηκαν από το εξής όνομα και διεύθυνση';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Ακολουθήστε τον παρακάτω σύνδεσμο για να το τσεκάρετε:
%2$s

Να έχετε μία υπέροχη μέρα!';
$Definition['Email Unavailable'] = 'Μη Διαθέσιμο Email';
$Definition['Email visible to other users'] = 'Το email σας να είναι ορατό στους άλλους χρήστες';
$Definition['EmailWelcome'] = 'Ο χρήστης %2$s δημιούργησε έναν λογαριασμό για εσάς στο  %3$s. Τα στοιχεία της σύνδεσής σας είναι:

  Email: %6$s
  Κωδικός: %5$s
  Url: %4$s';
$Definition['EmailWelcomeConnect'] = 'Συνδεθήκατε με επιτυχία στο {Title}. Ορίστε οι πληροφορίες σας:

  Όνομα Χρήστη: {User.Name}
  Σύνδεση με: {ProviderName}

Μπορείτε να επισκεφθείτε το χώρο στη διεύθυνση {/,exurl,domain}.';
$Definition['EmailWelcomeRegister'] = 'Δημιουργήσατε με επιτυχία ένα λογαριασμό στο {Title}. Οι προσωπικές σας πληροφορίες είναι:

 Όνομα χρήστη: {User.Name}
 Email: {User.Email}

Μπορείτε να δείτε το χώρο στη διεύθυνση {/,exurl,domain}.';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Διαβάστε ολόκληρη την ιστορία εδώ</a></p><div class="ClearFix"></div></div>';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Διαβάστε ολόκληρη την ιστορία εδώ</a></p><div class="ClearFix"></div></div>';
$Definition['Emoji'] = 'Χαρακτήρες Emoji';
$Definition['English'] = 'Αγγλικά';
$Definition['Enter your Email address'] = 'Εισάγετε την διεύθυνση Email';
$Definition['Enter your email address'] = 'Εισάγετε την διεύθυνση email';
$Definition['Enter your Email address or username'] = 'Δώστε το email σας ή το όνομα χρήστη';
$Definition['Enter Your OpenID Url'] = 'Εισάγετε το OpenID Url σας';
$Definition['Erase User Content'] = 'Διαγραφή Περιεχομένων Χρήστη';
$Definition['Error'] = 'Σφάλμα';
$Definition['ErrorBadInvitationCode'] = 'Ο κωδικός πρόσκλησης που έχετε εισάγει δεν είναι έγκυρος.';
$Definition['ErrorCredentials'] = 'Λυπάμαι, δεν βρέθηκε κανένας λογαριασμός σχετιζόμενος με το email και τον κωδικό που εισάγατε.';
$Definition['ErrorPermission'] = 'Λυπάμαι, το αίτημα απορρίφθηκε.';
$Definition['ErrorPluginDisableRequired'] = 'Δε μπορείτε να απενεργοποιήσετε το πρόσθετο {0} γιατί το πρόσθετο {1} το χρειάζεται για να λειτουργήσει.';
$Definition['ErrorPluginEnableRequired'] = 'Το πρόσθετο αυτό απαιτεί ενεργοποιημένο το πρόσθετο {0} πριν ενεργοποιηθεί.';
$Definition['ErrorPluginVersionMatch'] = 'Το ενεργοποιημένο πρόσθετο {0} (έκδοση {1}) δεν καλύπτει τις απαιτήσεις έκδοσης ({2}).';
$Definition['ErrorRecordNotFound'] = 'Η εγγραφή που ζητήσατε δε βρέθηκε.';
$Definition['ErrorTermsOfService'] = 'Πρέπει να συμφωνήσετε με τους όρους της υπηρεσίας.';
$Definition['Event'] = 'Εκδήλωση';
$Definition['Events'] = 'Εκδηλώσεις';
$Definition['everyone'] = 'όλοι';
$Definition['Everything'] = 'Όλα';
$Definition['Expired'] = 'Έληξε';
$Definition['Expires'] = 'Λήγει';

$Definition['Failed to delete group.'] = 'Αποτυχία διαγραφής ομάδας.';
$Definition['Failed to find discussion for commenting.'] = 'Αποτυχία εύρεσης συζήτησης για σχολιασμό.';
$Definition['Failed to load the poll.'] = 'Αποτυχία φόρτωσης ψηφοφορίας.';
$Definition['Feedback'] = 'Ανάδραση';
$Definition['Female'] = 'Θηλυκό';
$Definition['Fifth Anniversary'] = 'Πέμπτη Επέτειος';
$Definition['FileName'] = 'Όνομα Αρχείου';
$Definition['Filename'] = 'Όνομα Αρχείου';
$Definition['FileSize'] = 'Μέγεθος αρχείου';
$Definition['File Size'] = 'Μέγεθος Αρχείου';
$Definition['First Anniversary'] = 'Πρώτη επέτειος';
$Definition['First Comment'] = 'Πρώτο Σχόλιο';
$Definition['Flag'] = 'Σημαία';
$Definition['Follow'] = 'Ακολουθήστε';
$Definition['Follow %s'] = 'Ακολουθήστε το χρήστη %s';
$Definition['Followed by %d people'] = 'Ακολουθείται από %d ανθρώπους';
$Definition['Followed by %d person'] = 'Ακολουθείται από %d άτομο.';
$Definition['followed categories'] = 'κατηγορίες που ακολουθήθηκαν';
$Definition['Following %d people'] = 'Ακολουθεί %d ανθρώπους';
$Definition['Following %d person'] = 'Ακολουθεί %d άτομο';
$Definition['FollowOnly'] = 'Ακολουθήστε τον παρακάτω σύνδεσμο για να το δείτε:';
$Definition['Follows'] = 'Ακολουθεί';
$Definition['Forgot?'] = 'Τον ξεχάσατε;';
$Definition['Forgot your password?'] = 'Ξεχάσατε τον κωδικό σας;';
$Definition['Format'] = 'Μορφοποίηση';
$Definition['Format his'] = 'του';
$Definition['Format their'] = 'αυτών';
$Definition['Format You'] = 'εσείς';
$Definition['Format you'] = 'εσείς';
$Definition['Format Your'] = 'σας';
$Definition['Forum'] = 'Φόρουμ';
$Definition['Forums'] = 'Φόρουμ';
$Definition['Fourth Anniversary'] = 'Τέταρτη επέτειος';
$Definition['Friends'] = 'Φίλοι';
$Definition['Full Site'] = 'Πλήρης Χώρος';

$Definition['Garden.Email.SupportAddress'] = 'Email υποστήριξης';
$Definition['Garden.Email.SupportName'] = 'Όνομα υποστηρικτή';
$Definition['Garden.Registration.DefaultRoles'] = 'Προεπιλεγμένος ρόλος';
$Definition['Garden.Title'] = 'Τίτλος πανό';
$Definition['Gender'] = 'Φύλο';
$Definition['General'] = 'Γενικά';
$Definition['Generate import SQL only'] = 'Δημιουργία του SQL εισαγωγής μόνο';
$Definition['Generate Password'] = 'Δημιουργία Κωδικού';
$Definition['Give'] = 'Δώστε';
$Definition['Give a Badge to %s'] = 'Δώστε ένα έμβλημα στον χρήστη %s';
$Definition['Give Badge'] = 'Δώστε Έμβλημα';
$Definition['Given'] = 'Δώσατε';
$Definition['Go'] = 'Βρες';
$Definition['Group'] = 'Ομάδα';
$Definition['group'] = 'ομάδα';
$Definition['GroupEmptyAnnouncements'] = 'Κάποια μέρα θα συμβούν σημαντικά πράγματα εδώ.';
$Definition['GroupEmptyDiscussions'] = 'Παραείναι ήσυχα εδώ, έτσι δεν είναι;';
$Definition['GroupEmptyEvents'] = 'Δυστυχώς δεν υπάρχουν εκδηλώσεις.';
$Definition['Group Info'] = 'Πληροφορίες Ομάδας';
$Definition['Group Leaders'] = 'Ηγέτες Ομάδας';
$Definition['Group Members'] = 'Μέλη Ομάδας';
$Definition['GroupMembersEmpty'] = 'Κανείς δεν έχει πάρει μέρος ακόμη. Διαδώστε τα νέα!';
$Definition['Group Options'] = 'Επιλογές ομάδας';
$Definition['Groups'] = 'Ομάδες';
$Definition['groups'] = 'ομάδες';
$Definition['Guest'] = 'Επισκέπτης';
$Definition['GuestModule.Message'] = 'Φαίνεται πως έρχεστε για πρώτη φορά εδώ. Αν θέλετε να συμμετέχετε, πάτησε ένα από αυτά τα πλήκτρα!';

$Definition['Hang on a sec while we sign you out.'] = 'Περιμένε λίγο να σας συνδέσω.';
$Definition['he'] = 'αυτός';
$Definition['Heading %s'] = 'Τίτλος %s';
$Definition['HeadlineFormat.Badge'] = 'Ο χρήστης {ActivityUserID,You} κέρδισε το Έμβλημα <a href=\'{Url,html}\'>{Data.Name,text}</a>.';
$Definition['HeadlineFormat.Ban'] = 'Ο χρήστης {RegardingUserID,You} απέκλησε το χρήστη {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = 'Ο χρήστης {ActivityUserID,user} σχολίασε στο <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Discussion'] = 'Ο χρήστης {ActivityUserID,user} ξεκίνησε μία νέα συζήτηση. <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = 'Ο χρήστης {ActivityUserID,user} σας ανέφερε στο <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = 'Ο χρήστης {RegardingUserID,You} άλλαξε την εικόνα προφίλ του χρήστη {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} προσχώρησε.';
$Definition['HeadlineFormat.Unban'] = 'Ο χρήστης {RegardingUserID,You} τερμάτισε τον αποκλεισμό του χρήστη {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = 'Ο χρήστης {ActivityUserID,You} προειδοποίησε το χρήστη {RegardingUserID,you}.';
$Definition['Help'] = 'Βοήθεια';
$Definition['her'] = 'της';
$Definition['Hide'] = 'Απόκρυψη';
$Definition['Hide my online status from other members'] = 'Να μη φαίνομαι online στα άλλα μέλη';
$Definition['Hide signatures?'] = 'Απόκρυψη υπογραφών;';
$Definition['Hide signatures always'] = 'Απόκρυψη υπογραφών πάντα';
$Definition['Hide signatures on my mobile device'] = 'Απόκρυψη υπογραφών στο κινητό μου';
$Definition['his'] = 'του';
$Definition['Home'] = 'Αρχική';
$Definition['hours'] = 'ώρες';
$Definition['Howdy, Stranger!'] = 'Καλωσορίσατε, επισκέπτη!';
$Definition['How long do you want this warning to last?'] = 'Πόσο πολύ θέλετε να διαρκέσει αυτή η προειδοποίηση;';
$Definition['How many levels deep should we start folding up quote trees?'] = 'Πόσα παραθέσεις μπορούμε να συμπεριλαμβάνουμε σε μία παράθεση;';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Συμφωνώ με τους <a id="TermsOfService" class="Popup" target="terms" href="%s">όρους χρήστης</a>';
$Definition['Icon'] = 'Εικονίδιο';
$Definition['Ignore'] = 'Αγνόησε';
$Definition['Ignore List'] = 'Αγνοήστε τη λίστα';
$Definition['Ignore Someone'] = 'Αγνόησε κάποιον';
$Definition['Image'] = 'Εικόνα';
$Definition['Image URL'] = 'Εικόνα URL';
$Definition['in'] = 'σε';
$Definition['In <b>%s.</b>'] = 'Στο <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'Στο <b>%s.</b> και σε πρόσφατες συζητήσεις';
$Definition['Inbox'] = 'Εισερχόμενα';
$Definition['Indent'] = 'Εσοχή';
$Definition['In recent discussions.'] = 'Σε πρόσφατες συζητήσεις';
$Definition['In seconds'] = 'Σε δευτερόλεπτα';
$Definition['Insert Image'] = 'Εισαγωγή Εικόνας';
$Definition['Insightful'] = 'Διορατικό';
$Definition['Internal'] = 'Εσωτερικά';
$Definition['In this Conversation'] = 'Σε αυτή τη Συνομιλία';
$Definition['Invalid password.'] = 'Ο κωδικός που δώσατε δεν ήταν σωστός. Θυμηθείτε ότι στους κωδικούς υπάρχει διάκριση πεζών-κεφαλαίων.';
$Definition['Invitations'] = 'Προσκλήσεις';
$Definition['Invite'] = 'Προσκαλέστε';
$Definition['InviteErrorPermission'] = 'Λυπάμαι, η άδεια δε δόθηκε.';
$Definition['Invite Friends'] = 'Προσκαλέστε Φίλους';
$Definition['Invite friends'] = 'Προσκαλέστε φίλους';
$Definition['IPAddress'] = 'Διεύθυνση IP';
$Definition['IP Address'] = 'Διεύθυνση IP';
$Definition['I remember now!'] = 'Το θυμήθηκα!';
$Definition['Italic'] = 'Πλάγια γραφή';
$Definition['Item'] = 'Αντικείμενο';
$Definition['item'] = 'αντικείμενο';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Φαίνεται πως είστε νέος εδώ. Αν θέλεις να συμμετέχετε, πάτησε ένα από αυτά τα πλήκτρα!';

$Definition['Jail'] = 'Φυλακή';
$Definition['Jailed users have reduced abilities.'] = 'Οι Φυλακισμένοι χρήστες έχουν περιοριμένες δυνατότητες.';
$Definition['Joined'] = 'Προσχώρησε';
$Definition['Joined %s'] = 'Συμμετείχε %s';
$Definition['Join this Group'] = 'Γίνετε μέλος αυτής της Ομάδας';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Απλά να διαγραφεί η εγγραφή του χρήστη και να διατηρηθούν όλα τα περιεχόμενά του.';
$Definition['Just expire the warning.'] = 'Απλά να λήξει η προειδοποίηση.';
$Definition['Just you!'] = 'Απλά εσείς!';

$Definition['Keep me signed in'] = 'Κράτησε με συνδεδεμένο';
$Definition['Keep User Content'] = 'Διατήρηση Περιεχομένων Χρήστη';

$Definition['Label'] = 'Ετικέτα';
$Definition['Last Active'] = 'Τελευταία Ενέργεια';
$Definition['Last IP'] = 'Τελευταία IP';
$Definition['lasts %s'] = 'διάρκεια %s';
$Definition['Latest %1$s'] = 'Τελευταία %1$s';
$Definition['Latest Post'] = 'Τελευταία ανάρτηση';
$Definition['Leaders'] = 'Ηγέτες';
$Definition['Leave a Comment'] = 'Σχολιάστε';
$Definition['Leave a comment'] = 'Σχολιάστε';
$Definition['Leave a redirect link.'] = 'Αφήστε ένα σύνδεσμο ανακατεύθυνσης.';
$Definition['Leave blank unless connecting to an exising account.'] = 'Αφήστε το κενό εκτός αν συνδέεστε με ένα υπάρχοντα λογαριασμό.';
$Definition['Leave Comments'] = 'Αφήστε Σχόλια';
$Definition['Leave Group'] = 'Εγκατάλειψη Ομάδας';
$Definition['Length'] = 'Μήκος';
$Definition['Level %s'] = 'Επίπεδο %s';
$Definition['Like'] = 'Μου αρέσει';
$Definition['Link to content:'] = 'Σύνδεσμος στο περιεχόμενο:';
$Definition['Locale'] = 'Αγγλικά (Καναδά)';
$Definition['Log'] = 'Αρχείο καταγραφής';
$Definition['log'] = 'Σύνδεση';
$Definition['Login with Facebook'] = 'Σύνδεση μέσω Facebook';

$Definition['Major'] = 'Ενήλικος';
$Definition['Make me invisible? (Will not show you on the list)'] = 'Να είστε αόρατος; (Δεν θα φαίνεστε στη λίστα)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Κάντε αυτή την ψηφοφορία ανώνυμη (οι ψήφοι των χρηστών δε θα φαίνονται δημόσια)';
$Definition['Male'] = 'Αρσενικό';
$Definition['Mark All Viewed'] = 'Μαρκάρετε τα Πάντα ως Αναγνωσμένα';
$Definition['Mark as Troll'] = 'Σημείωση ως Τρολ';
$Definition['Marking as spam cannot be undone.'] = 'Σημειώνοντας κάτι ως SPAM θα οδηγήσει στη μόνιμη διαγραφή του. Η διαγραφή είναι ένας καλός τρόπος για να διατηρείτε το φόρουμ σας καθαρό.';
$Definition['Mark Read'] = 'Μαρκάρετε ως Αναγνωσμένο';
$Definition['Member Count'] = 'Μέλη';
$Definition['Members'] = 'Μέλη';
$Definition['Merge'] = 'Συνένωσε';
$Definition['Merge Discussions'] = 'Συνένωσε τις Συζητήσεις';
$Definition['Message'] = 'Μήνυμα';
$Definition['message'] = 'μήνυμα';
$Definition['Messages'] = 'Μηνύματα';
$Definition['messages'] = 'μηνύματα';
$Definition['Message to User'] = 'Μήνυμα προς Χρήστη';
$Definition['Minor'] = 'Ανήλικος';
$Definition['minutes'] = 'λεπτά';
$Definition['Moderation'] = 'Συντονισμός';
$Definition['Moderation Queue'] = 'Ουρά Συντονισμού';
$Definition['Moderator'] = 'Συντονιστής';
$Definition['Moderator Activity'] = 'Δραστηριότητα Συντονιστή';
$Definition['Moderators'] = 'Συντονιστές';
$Definition['moderators'] = 'συντονιστές';
$Definition['months'] = 'μήνες';
$Definition['More'] = 'Περισσότερα';
$Definition['More About %s'] = 'Περισσότερα Σχετικά με %s';
$Definition['More Comments'] = 'Περισσότερα Σχόλια';
$Definition['More Discussions'] = 'Περισσότερες Συζητήσεις';
$Definition['More Information'] = 'Περισσότερες Πληροφορίες';
$Definition['More Results'] = 'Περισσότερα Αποτελέσματα';
$Definition['More…'] = 'Περισσότερα...';
$Definition['Most Recent'] = 'Πιο Πρόσφατα';
$Definition['Most recent:'] = 'πιο Πρόσφατα:';
$Definition['Most recent: %1$s by %2$s'] = 'Πιο πρόσφατη: %1$s από %2$s';
$Definition['Most recent by %1$s'] = 'Πιο πρόσφατο από το χρήστη %1$s';
$Definition['Most Recent Comment'] = 'Πιο Πρόσφατο Σχόλιο';
$Definition['Move'] = 'Μετακίνησε';
$Definition['MyBadgesModuleTitle'] = 'Τα Εμβλήματά μου';
$Definition['My Bookmarks'] = 'Τα Αγαπημένα μου';
$Definition['My Discussions'] = 'Οι Συζητήσεις μου';
$Definition['My Drafts'] = 'Τα Προσχέδια μου';
$Definition['My Forums'] = 'Τα Φόρουμ μου';
$Definition['My Groups'] = 'Οι ομάδες μου';
$Definition['My Preferences'] = 'Οι Προτιμήσεις μου';

$Definition['n/a'] = 'μη διαθέσιμο';
$Definition['Name'] = 'Όνομα';
$Definition['Name Dropper'] = 'Εναπόθεση Ονόματος';
$Definition['Name the Group'] = 'Ονομασία Ομάδας';
$Definition['Name Unavailable'] = 'Όνομα μη διαθέσιμο';
$Definition['new'] = 'νέα';
$Definition['New %s'] = 'Νέο %s';
$Definition['New Conversation'] = 'Νέο Μήνυμα';
$Definition['New Discussion'] = 'Νέα Συζήτηση';
$Definition['new discussion'] = 'νέα';
$Definition['New Event'] = 'Νέα Εκδήλωση';
$Definition['New Group'] = 'Νέο γκρουπ';
$Definition['New Groups'] = 'Νέες Ομάδες';
$Definition['New Message'] = 'Νέο Μήνυμα';
$Definition['New Password'] = 'Νέος Κωδικός';
$Definition['New Poll'] = 'Νέα Ψηφοφορία';
$Definition['Next'] = 'Επόμενη';
$Definition['Ninth Anniversary'] = 'Ένατη επέτειος';
$Definition['No'] = 'Όχι';
$Definition['NoBadgesEarned'] = 'Όπου να\'ναι&hellip;';
$Definition['No badges yet.'] = 'Δε βρέθηκαν εμβλήματα';
$Definition['No default roles.'] = 'Δεν υπάρχουν προεπιλεγμένοι ρόλοι';
$Definition['No discussions were found.'] = 'Δε βρέθηκαν συζητήσεις.';
$Definition['No items tagged with %s.'] = 'Δε βρέθηκαν θέματα με την ετικέτα %s.';
$Definition['NoPermissionToDeleteDiscussions'] = 'Δεν έχετε άδεια για να διαγράψετε το %1$s των επιλεγμένων συζητήσεων.';
$Definition['No results for \'%s\''] = 'Δε βρέθηκαν αποτελέσματα για \'%s\'';
$Definition['No Roles'] = 'Δεν υπάρχουν ρόλοι';
$Definition['Not Authorized (401)'] = 'Μη εγκεκριμμένος (401)';
$Definition['Not Found (404)'] = 'Δεν βρέθηκε (404)';
$Definition['Notice'] = 'Σημείωση';
$Definition['Notification'] = 'Ειδοποίηση';
$Definition['Notification Preferences'] = 'Προτιμήσεις Ειδοποιήσεων';
$Definition['Notifications'] = 'Ειδοποιήσεις';
$Definition['Notifictions'] = 'Υπενθυμίσεις';
$Definition['Notify'] = 'Ειδοποίησε';
$Definition['Notify me of private messages.'] = 'Ειδοποίησέ με για προσωπικά μηνύματα.';
$Definition['Notify me when a badge is requested.'] = 'Ειδοποίησέ με όταν ζητηθεί ένα έμβλημα';
$Definition['Notify me when a comment is flagged.'] = 'Ειδοποίησε με όταν ένα σχόλιο μου σημανθεί.';
$Definition['Notify me when I am added to private conversations.'] = 'Ειδοποίησε με όταν προστεθώ σε προσωπικές συνομιλίες.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Ειδοποίησε με όταν κάποιος σχολιάσει τις συζητήσεις στις οποίες έχω συμμετάσχει.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Ειδοποίησε με όταν γίνονται σχόλια για τις αγαπημένες μου συζητήσεις.';
$Definition['Notify me when people comment on my discussions.'] = 'Ειδοποίησε με όταν γίνονται σχόλια στις συζητήσεις μου.';
$Definition['Notify me when people mention me.'] = 'Ειδοποίησε με όταν με αναφέρουν.';
$Definition['Notify me when people mention me in comments.'] = 'Ειδοποίησε με όταν με αναφέρουν σε σχόλια.';
$Definition['Notify me when people reply to my wall comments.'] = 'Ειδοποίησε με όταν κάποιος απαντήσει στα σχόλια του τοίχου μου.';
$Definition['Notify me when people write on my wall.'] = 'Ειδοποίησε με όταν κάποιος γράψει στον τοίχο μου.';
$Definition['Not much happening here, yet.'] = 'Δεν συμβαίνει κάτι εδώ, ακόμα.';
$Definition['Not Verified'] = 'Μη Επιβεβαιωμένο';

$Definition[' now.'] = 'τώρα.';

$Definition['of'] = 'του';
$Definition['Off Topic'] = 'Εκτός Θέματος';
$Definition['OK'] = 'Εντάξει';
$Definition['Okay'] = 'Εντάξει';
$Definition['OldPassword'] = 'Παλιός Κωδικός';
$Definition['Old Password'] = 'Παλιός Κωδικός';
$Definition['on'] = 'σε';
$Definition['Online Preferences'] = 'Διαδικτυακές Προτιμήσεις';
$Definition['Only show followed categories'] = 'Δείτε μόνο τις κατηγορίες που ακολουθείτε.';
$Definition['OpenID Settings'] = 'Ρυθμίσεις OpenID';
$Definition['Optional Description'] = 'Προαιρετική Περιγραφή';
$Definition['Options'] = 'Επιλογές';
$Definition['or'] = 'ή';
$Definition['Ordered list'] = 'Ταξινομημένη λίστα';
$Definition['Organize discussion categories'] = 'Οργανώστε τις κατηγορίες συζητήσεων';
$Definition['Organize your Categories'] = 'Οργανώστε τις Κατηγορίες σας';
$Definition['Original'] = 'Πρωτότυπο';
$Definition['Or you can...'] = 'Ή μπορείτε να να...';
$Definition['Other Records'] = 'Άλλες Εγγραφές';
$Definition['Outdent'] = 'Προεξοχή';
$Definition['Owner'] = 'Ιδιοκτήτης';

$Definition['PageDetailsMessage'] = 'Ο χρήστης %1$s στον χρήστη %2$s';
$Definition['PageDetailsMessageFull'] = 'Ο χρήστης %1$s στο χρήστη %2$s του %3$s';
$Definition['Page Not Found'] = 'Η Σελίδα Δεν Βρέθηκε';
$Definition['Participated'] = 'Συμμετείχε';
$Definition['ParticipatedHomepageTitle'] = 'Συμμετοχές Συζητήσεων';
$Definition['Password'] = 'Κωδικός χρήστη';
$Definition['PasswordRequest'] = 'Κάποιος ζήτησε επαναφορά κωδικού στο %2$s. Για να επαναφέρετε τον κωδικό σας, ακολουθείτε αυτό το σύνδεμο:

  %3$s

Αν δεν κάνατε αυο το αίτημα, αγνοήστε αυτό το email.';
$Definition['Passwords don\'t match'] = 'Οι Κωδικοί δεν ταιριάζουν';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Επικολλήστε το URL μιας εικόνας για να την ενσωματώσετε γρήγορα';
$Definition['Permalink'] = 'Μόνιμος Σύνδεσμος';
$Definition['permalink'] = 'μόνιμος σύνδεσμος';
$Definition['Permanent (301)'] = 'Μόνιμο (301)';
$Definition['PermissionErrorMessage'] = 'Δεν έχετε δικαίωμα να κάνετε αυτό.';
$Definition['PermissionErrorTitle'] = 'Πρόβλημα με τα Δικαιώματα';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Χρειάζεται να είστε συντονιστής για να το κάνετε αυτό.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Χρειάζεται να είστε Διαχειριστής για να το κάνετε αυτό.';
$Definition['PermissionRequired.Javascript'] = 'Χρειάζεται να ενεργοποιήσετε τη javascript για να το κάνετε αυτό.';
$Definition['Photogenic'] = 'Φωτογενής';
$Definition['Picture'] = 'Εικόνα';
$Definition['Pin'] = 'Καρφίτσωμα';
$Definition['Pinned'] = 'Καρφιτσωμένο';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Παρακαλώ περιμένετε ενώ ανακατευθύνεστε. Αν δεν ανακατευθυνθείτε, πατήστε <a href="%s">εδώ</a>.';
$Definition['Poll'] = 'Ψηφοφορία';
$Definition['Poll Options'] = 'Επιλογές Ψηφοφορίας';
$Definition['Poll Question'] = 'Ερώτηση Ψηφοφορίας';
$Definition['Popular'] = 'Δημοφιλή';
$Definition['Popular Discussions'] = 'Δημοφιλείς Συζητήσεις';
$Definition['Popular Groups'] = 'Δημοφιλή γκρουπ';
$Definition['Popular Tags'] = 'Δημοφιλείς Ετικέτες';
$Definition['Popup'] = 'Αναδυώμενο';
$Definition['Position'] = 'Θέση';
$Definition['Post'] = 'Ανάρτηση';
$Definition['Post Comment'] = 'Ανάρτηση Σχόλιου';
$Definition['Post Discussion'] = 'Θέστε μία Ερώτηση';
$Definition['Post edited by %1$s at %2$s'] = 'Η Ανάρτηση διορθώθηκε από το χρήστη %1$s στις %2$s';
$Definition['Posts'] = 'Αναρτήσεις';
$Definition['Posts.Plural: %s'] = 'Αναρτήσεις: %s';
$Definition['Posts.Singular: %s'] = 'Αναρτήσεις: %s';
$Definition['Posts: %s'] = 'Αναρτήσεις: %s';
$Definition['Post this anonymously'] = 'Αναρτήστε αυτό ανώνυμα';
$Definition['Powered by %s'] = 'Τροφοδοτείται από το %s';
$Definition['Powered by Vanilla'] = 'Τροφοδοτείται από το Vanilla';
$Definition['PreferenceBadgeEmail'] = 'Ειδοποίησέ με όταν αποκτώ ένα έμβλημα.';
$Definition['PreferenceBadgePopup'] = 'Ειδοποίησέ με όταν αποκτώ ένα έμβλημα.';
$Definition['Preview'] = 'Προεπισκόπηση';
$Definition['Previous'] = 'Προηγούμενη';
$Definition['Privacy'] = 'Ιδιωτικότητα';
$Definition['Privacy Settings'] = 'Ρυθμίσεις Ιδιωτικότητας';
$Definition['Private'] = 'Ιδιωτικό';
$Definition['Private group.'] = 'Ο καθένας μπορεί να δει την ομάδα, αλλά μόνο τα μέλη μπορούν να δουν το περιεχόμενό της. Οι ενδιαφερόμενοι θα πρέπει να δηλώσουν συμμετοχή ή να προσκληθούν για να συμμετάσχουν.';
$Definition['Private Note for Moderators'] = 'Ιδιωτική Σημείωση για Συντονιστές';
$Definition['Problem with credentials.'] = 'Πρόβλημα με τα διαπιστευτήρια.';
$Definition['Proceed'] = 'Προχωρήστε';
$Definition['Profile'] = 'Προφίλ';
$Definition['Profile Fields'] = 'Πεδία Προφίλ';
$Definition['Profile  Fields'] = 'Πεδία  Προφιλ';
$Definition['ProfileFieldsCustomDescription'] = 'Χρησιμοποιήστε αυτά τα πεδία για να δημιουργήσετε προσαρμοσμένες πληροφορίες προφίλ. Μπορείτε να καταγράψετε πράγματα όπως  "Κατάσταση Σχέσης", "Skype", or "Αγαπημένος Δεινόσαυρος". Να είστε δημιουργικός!';
$Definition['Profile Page'] = 'Σελίδα προφίλ';
$Definition['Profile Picture'] = 'Εικόνα Προφίλ';
$Definition['Profiles'] = 'Προφιλ';
$Definition['Promote'] = 'Προβιβάστε';
$Definition['Public'] = 'Δημόσιο';
$Definition['Public group.'] = 'Οποιοσδήποτε μπορεί να δει το γκρουπ και το περιεχόμενο του. Οποιοσδήποτε μπορεί να συμμετάσχει.';

$Definition['Q&A'] = 'Ερωτήσεις &amp; Απαντήσεις';
$Definition['Q&A Accepted'] = 'Απαντήθηκε ✓';
$Definition['Q&A Answered'] = 'Απαντήθηκε';
$Definition['Q&A Options'] = 'Επιλογές Q&A';
$Definition['Q&A Question'] = 'Ερώτηση';
$Definition['QnA Accepted Answer'] = 'Απάντηση ✓';
$Definition['QnA Rejected Answer'] = 'Η Απάντηση απορρίφθηκε';
$Definition['Question'] = 'Ερώτηση';
$Definition['question'] = 'ερώτηση';
$Definition['Questions'] = 'Ερωτήσεις';
$Definition['questions'] = 'ερωτήσεις';
$Definition['Question Title'] = 'Τίτλος Ερώτησης';
$Definition['Quote'] = 'Παράθεση';
$Definition['Quote Folding'] = 'Αναδίπλωση Παράθεσης';
$Definition['Quote on'] = 'στις';
$Definition['Quote Settings'] = 'Ρυθμίσεις Παράθεσης';
$Definition['Quote wrote'] = 'έγραψε';

$Definition['Rank'] = 'Κατάταξη';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were} προβιβάστηκε σε {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = 'Συγχαρητήρια, έχετε προβιβαστεί σε {Data.Name,plaintext}.';
$Definition['Re: %s'] = 'Απάντηση προς: %s';
$Definition['Reactions'] = 'αντιδράσεις';
$Definition['Real Name'] = 'Πραγματικό Όνομα';
$Definition['Reason'] = 'Αιτία';
$Definition['Reason (optional)'] = 'Αιτία (προαιρετικά)';
$Definition['Recent Activity'] = 'Πρόσφατη Δραστηριότητα';
$Definition['Recent Admin Activity'] = 'Πρόσφατη Δραστηριότητα Διαχειριστή';
$Definition['Recent Discussions'] = 'Πρόσφατες Συζητήσεις';
$Definition['recently'] = 'πρόσφατα';
$Definition['Recent Moderator Activity'] = 'Πρόσφατη Δραστηριότητα Συντονιστή';
$Definition['Recent Tutorials'] = 'Πρόσφατα Φροντιστήρια';
$Definition['Recipients'] = 'Αποδέκτες';
$Definition['RecipientUserID'] = 'αποδέκτης';
$Definition['Redirecting...'] = 'Ανακατεύθυνση...';
$Definition['Refetch Page'] = 'Επανάληψη Σελίδας';
$Definition['Register'] = 'Εγγραφή';
$Definition['Register IP'] = 'IP Εγγραφής';
$Definition['Register with %s'] = 'Εγγραφή';
$Definition['Registration  Fields'] = 'Πεδία  Εγγραφής';
$Definition['Registration URL'] = 'URL εγγραφής';
$Definition['Reject'] = 'Απορρίψτε';
$Definition['Reject this answer.'] = 'Απορρίψτε αυτή την απάντηση.';
$Definition['Remember me'] = 'Να με θυμάσαι';
$Definition['Remember me on this computer'] = 'Να με θυμάσαι σε αυτόν τον υπολογιστή';
$Definition['Remote Configuration'] = 'Απομακρυσμένη Διαμόρφωση';
$Definition['Remove'] = 'Αφαίρεση';
$Definition['Removed by'] = 'Αφαιρέθηκε από';
$Definition['Remove from %s'] = 'Αφαίρεση από %s';
$Definition['Remove Invitation'] = 'Αφαίρεση Πρόσκλησης';
$Definition['Remove My Picture'] = 'Αφαίρεση της Εικόνας μου';
$Definition['Remove Picture'] = 'Αφαίρεση Εικόνας';
$Definition['Remove Warning'] = 'Αφαίρεση Προειδοποίησης';
$Definition['Rename Forum'] = 'Μετονομάστε το Φόρουμ';
$Definition['Reopen'] = 'Άνοιγμα ξανά';
$Definition['Replies'] = 'Απαντήσεις';
$Definition['Reply'] = 'Απάντηση';
$Definition['ReplyOnly'] = 'Μπορείτε να απαντήσετε σε αυτό το e-mail απευθείας για να παρακολουθείτε την εξέλιξη. Στάλθηκε από {/,exurl}.';
$Definition['ReplyOrFollow'] = 'Απαντήστε στο email άμεσα ή ακολουθήστε το παρακάτω σύνδεσμο για να το δείτε:';
$Definition['Report'] = 'Αναφορά';
$Definition['Report %s'] = 'Αναφορά %s';
$Definition['Reported by: '] = 'Αναφέρθηκε από:';
$Definition['Reported Posts'] = 'Δημοσιεύσεις με Αναφορές';
$Definition['Report Notes'] = 'Σημειώσεις';
$Definition['Report Reason'] = 'Αιτία';
$Definition['Request a new password'] = 'Αίτηση νέου κωδικού';
$Definition['Request a new password →'] = 'Αίτημα νέου κωδικού →';
$Definition['Reset Password'] = 'Επαναφορά Κωδικού';
$Definition['Restored'] = 'Αποκαταστάθηκε';
$Definition['reverse'] = 'αντιστροφή';
$Definition['Revoke'] = 'Ανάκληση';
$Definition['Revoked'] = 'Ανάκληση';
$Definition['Revoked badge.'] = 'Ανάκληση εμβλήματος';
$Definition['role'] = 'ρόλος';
$Definition['RoleID'] = 'ρόλος';
$Definition['Roles'] = 'Ρόλοι';
$Definition['roles'] = 'ρόλοι';

$Definition['Save'] = 'Αποθήκευση';
$Definition['Save Comment'] = 'Αποθήκευση Σχόλιου';
$Definition['Save Draft'] = 'Αποθήκευση Προσχέδιου';
$Definition['Save Poll'] = 'Αποθήκευση Ψηφοφορίας';
$Definition['Save Preferences'] = 'Αποθήκευση Προτιμήσεων';
$Definition['Save your password'] = 'Αποθήκευση του κωδικού σας';
$Definition['Search'] = 'Αναζήτηση';
$Definition['Search %s'] = 'Αναζήτηση %s';
$Definition['search archived'] = 'αναζήτηση αρχειοθετημένων';
$Definition['SearchBoxPlaceHolder'] = 'Αναζήτηση';
$Definition['Search for a tag.'] = 'Αναζήτηση ολόκληρης ή μέρους της ετικέτας.';
$Definition['Search results for \'%s\''] = 'Αποτελέσματα αναζήτηση για \'%s\'';
$Definition['search subcategories'] = 'αναζήτηση υποκατηγοριών';
$Definition['Second Anniversary'] = 'Δεύτερη Επέτειος';
$Definition['Secret'] = 'Μυστικό';
$Definition['Sections'] = 'Ενότητες';
$Definition['Security Check'] = 'Έλεγχος Ασφαλείας';
$Definition['Select an image on your computer (2mb max)'] = 'Επέλεξε μια εικόνα από τον υπολογιστή (2mb max)';
$Definition['Select one of the following avatars:'] = 'Επιλέξτε ένα από τα ακόλουθα άβαταρ:';
$Definition['Send a New Message'] = 'Στείλτε ένα Νέο Μήνυμα';
$Definition['Send Message'] = 'Αποστολή Μηνύματος';
$Definition['Send Report'] = 'Αποστολή Αναφοράς';
$Definition['Send report'] = 'Στείλτε αναφορά';
$Definition['sep and'] = 'και';
$Definition['Set a New Warning Level'] = 'Ορισμός Νέου Επιπέδου Προειδοποίησης';
$Definition['Set A Password'] = 'Ορισμός Κωδικό';
$Definition['Setting'] = 'Ρύθμιση';
$Definition['Settings'] = 'Ρυθμίσεις';
$Definition['Seventh Anniversary'] = 'Έβδομη επέτειος';
$Definition['Severity'] = 'Αυστηρότητα';
$Definition['Share'] = 'Κοινοποίηση';
$Definition['Shared Accounts'] = 'Κοινοί Λογαριασμοί';
$Definition['she'] = 'αυτή';
$Definition['Shown only on mobile'] = 'Δείξτε μόνο σε κινητό';
$Definition['Show unfollowed categories'] = 'Δείξτε τις κατηγορίες που δεν ακολουθούνται';
$Definition['Sign-In URL'] = 'Διεύθυνση Εισόδου';
$Definition['Sign-Out URL'] = 'Διεύθυνση Αποσύνδεσης';
$Definition['Signature Code'] = 'Κώδικας Υπογραφής';
$Definition['Signature invalid.'] = 'Άκυρη υπογραφή.';
$Definition['Signatures'] = 'Υπογραφές';
$Definition['Signature Settings'] = 'Ρυθμίσεις Υπογραφής';
$Definition['Sign In'] = 'Σύνδεση';
$Definition['SignIn'] = 'Σύνδεση';
$Definition['SigningOut'] = 'Μια στιγμή, σας αποσυνδέουμε.';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Συνδεθείτε</a> ή <a href="{RegisterUrl,html}">Εγγραφείτε</a> για να σχολιάσετε.';
$Definition['Sign in to vote!'] = 'Συνδεθείτε για να ψηφίσετε!';
$Definition['Sign In with %s'] = 'Σύνδεση μέσω %s';
$Definition['Sign In with Disqus'] = 'Σύνδεση μέσω Disqus';
$Definition['Sign In with Facebook'] = 'Σύνδεση μέσω Facebook';
$Definition['Sign In with Google'] = 'Σύνδεση μέσω Google';
$Definition['Sign In with OpenID'] = 'Σύνδεση μέσω OpenID';
$Definition['Sign In with Twitter'] = 'Σύνδεση μέσω Twitter';
$Definition['Sign Out'] = 'Αποσύνδεση';
$Definition['sign out'] = 'αποσύνδεση';
$Definition['Sign Up'] = 'Εγγραφή';
$Definition['Sink'] = 'Βύθιση';
$Definition['Sink this discussion'] = 'Βυθίστε αυτή τη συζήτηση';
$Definition['Sitemap Settings'] = 'Ρυθμίσεις Χάρτη Χώρου';
$Definition['Sixth Anniversary'] = 'Έκτη Επέτειος';
$Definition['Social'] = 'Kοινωνικός';
$Definition['somebody'] = 'κάποιος';
$Definition['Some Code'] = 'Κώδικας';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Κάποιος απάντησε στην ερώτησή σας. Πρέπει να δεχτείτε/απορρίψετε αυτή την απάντηση';
$Definition['sorted by'] = 'ταξινόμηση κατά';
$Definition['Source:'] = 'Πηγή:';
$Definition['Source Code'] = 'Κωδικός';
$Definition['Spam'] = 'Ανεπιθύμητο μήνυμα';
$Definition['Spam Queue'] = 'Ουρά Spam';
$Definition['Split'] = 'Διαχωρίστε';
$Definition['Split Comments'] = 'Σχόλια Διαχωρισμού';
$Definition['Spoiler'] = 'Αποκάλυψη';
$Definition['Spoof User'] = 'Ψεύτικος Χρήστης';
$Definition['Start'] = 'Έναρξη';
$Definition['Start a New Conversation'] = 'Νέο Μήνυμα';
$Definition['Start a New Discussion'] = 'Νέα Συζήτηση';
$Definition['Start Conversation'] = 'Έναρξη Συνομιλίας';
$Definition['Started By'] = 'Ξεκίνησε από το χρήστη';
$Definition['Started by %1$s'] = 'Ξεκίνησε από το χρήστη %1$s';
$Definition['Start your First Discussion'] = 'Ξεκινήστε την Πωτη σας Συζήτηση';
$Definition['Stop following'] = 'Σταμάτα να ακολουθείς';
$Definition['Strikethrough'] = 'Διαγραφή';
$Definition['Strip images out of signatures'] = 'Αφαιρέστε τις εικόνες απο τις υπογραφές';
$Definition['Strip images out of signatures?'] = 'Να αφαιρεθούν οι εικόνες από τις υπογραφές;';
$Definition['Subject'] = 'Θέμα';
$Definition['Suggested Value'] = 'Προτεινόμενη Τιμή';

$Definition['Tagged'] = 'Σχετιζόμενο';
$Definition['Tagged with '] = 'Σχετιζόμενο με';
$Definition['Tagged with "%s"'] = 'Σχετιζόμενο με "%s"';
$Definition['Tagging'] = 'Βάζοντας Ετικέτες';
$Definition['Tag Name'] = 'Όνομα Ετικέτας';
$Definition['Tags'] = 'Ετικέτες';
$Definition['tags'] = 'ετικέτες';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Οι Ετικέτες είναι λέξεις κλειδιά που αντιστοιχίζονται σε συζητήσεις για να μπορούν να κατηγοριοποιηθούν ερωτήσεις που σχετίζοτναι με αυτές';
$Definition['Take Action'] = 'Αναλάβετε Δράση';
$Definition['Take Action:'] = 'Αναλάβετε Δράση:';
$Definition['Target'] = 'Στόχος';
$Definition['Tell the user why you\'re warning them'] = 'Πείτε στο χρήστη γιατί τον προειδοποιείτε';
$Definition['Tell us why you want to join!'] = 'Πείτε μας γιατί θέλετε να συμμετάσχετε!';
$Definition['Tenth Anniversary'] = 'Δέκατη Επέτειος';
$Definition['Terms'] = 'Όροι';
$Definition['TermsOfService'] = 'Όροι χρήσης';
$Definition['Terms of Service'] = 'Όροι χρήσης';
$Definition['TermsOfServiceText'] = '
   <p>Συμφωνείτε ότι, μέσα από τη χρήση αυτής της υπηρεσίας, ότι δε θα χρησιμοποιήσετε αυτή
   την κοινότητα για να δημοσιεύσετε υλικό που μπορεί εν γνώση σας να είναι ψευδές και/ή προσβλητικό,
   ανακριβές, καταχρηστικό, χυδαίο εχολητικό, άσεμνο, βέβηλο, με ερωτικό
περιεχόμενο, απειλητικό, που να εισβάλει στην ιδιωτικότητα ενός ατόμου ή γενικά που να παραβιάζει
   κάποιο νόμο. Συμφωνείτε ότι δε θα δημοσιεύσετε υλικό προστατευόμενο εκτός αν σας ανήκουν τα πνευματικά δικαιώματα.</p>
   
   <p>Σε αυτή την κοινότητα διατηρούμε το δικαίωμα να αποκαλύψουμε την ταυτότητά σας (ή
   όποια άλλη πληροφορία γνωρίζουμε για εσάς) σε περίπτωση παραπόνων ή νομικής δράσης
   που πηγάζει από οποιοδήποτε μήνυμα δημοσιεύσατε. Καταγράφουμε όλες τις διευθύνσης πρόσβασης
   σε αυτό το χώρο.</p>
   
   <p>Σημειώστε ότι οι διαφημίσεις, η αλυσιδωτή αλληλογραφία, τα σχήματα πυραμίδας, και η
   εύρεση πελατών δεν επιτρέπεται σε αυτή την κοινότητα.</p>
   
   <p>Διατηρούμε το δικαίωμα να αφαιρέσουμε οποιοδήποτε περιεχόμενο για οποιονδήποτε λόγο ή και χωρίς κανέναν
   λόγο. Διατηρούμε τη δυνατότητα να διακόψουμε την πρόσβαση για οποιονδήποτε λόγο και και χωρίς κανένα
   λόγο απολύτως.</p>
   
   <p>Πρέπει να είστε τουλάχιστον 13 ετών για να χρησιμοποιήσετε αυτή την υπηρεσία.</p>
';
$Definition['Text  Max  Length'] = 'Μέγιστο  Μήκος  Κειμένου';
$Definition['the category'] = 'η κατηγορία';
$Definition['The conversation has been cleared.'] = 'Η συνομιλία έχει διαγραφεί';
$Definition['The email you entered in use by another member.'] = 'Το email που δώσατε χρησιμοποιείται από άλλο χρήστη.';
$Definition['The email you have entered is already related to an existing account.'] = 'Το email που δώσατε σχετίζεται με το λογαριασμό άλλου χρήστη';
$Definition['The file failed to upload.'] = 'Αποτυχία στο ανέβασμα του αρχείου.';
$Definition['their'] = 'των';
$Definition['The name you entered is already in use by another member.'] = 'Το όνομα που δώσατε χρησιμοποιείται ήδη από άλλο χρήστη';
$Definition['The page you were looking for could not be found.'] = 'Η σελίδα που ζητήσατε δεν ήταν δυνατό να βρεθεί';
$Definition['The quote had to be converted from %s to %s.'] = 'Η παράθεση άλλαξε από %s σε %s. Κάποιες επιλογές μορφοποίησης χάθηκαν.';
$Definition['There aren\'t any groups yet.'] = 'Δεν υπάρχουν ομάδες ακόμα.';
$Definition['There are no tags in the system yet.'] = 'Δεν υπάρχουν ετικέτες στο σύστημα ακόμα.';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'Η τιμή του reCAPTCHA δε δόθηκε σωστά. Παρακαλώ δοκιμάστε αργότερα';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Υπάρχει ήδη ένας λογαριασμός με τό ίδιο όνομα (%1$s) ή email(%2$s). Μπορείτε να δημιουργήσετε νέο λογαριασμό ή να εισάγετε τα στοιχεία του δικού σας λογαριασμού.';
$Definition['The response was not in the correct format.'] = 'Η απάντηση δεν ήταν στη σωστή μορφή.';
$Definition['There was an error connecting to Disqus'] = 'Προέκυψε σφάλμα κατά τη σύνδεσή σας στο Disqus';
$Definition['There was an error connecting to Facebook'] = 'Προέκυψε σφάλμα κατά τη σύνδεσή σας στο Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Προέκυψε σφάλμα στο ανέβασμα του αρχείου. Το πιθανότερο είναι ότι το αρχείο είναι πολύ μεγάλο.';
$Definition['The site is currently undergoing maintenance.'] = 'Ο χώρος βρίσκεται αυτή τη στιγμή υπό συντήρηση.';
$Definition['The uploaded file was too big (max %s).'] = 'Το αρχείο που ανεβάσατε είναι πολύ μεγάλο (max %s).';
$Definition['they'] = 'αυτοί';
$Definition['Third Anniversary'] = 'Τρίτη Επέτειος';
$Definition['This answer was %s.'] = 'Η απάντηση ήταν %s.';
$Definition['This answer was Accepted.'] = 'Η απάντηση έγινε αποδεκτή';
$Definition['This discussion has been closed.'] = 'Αυτή η συζήτηση έχει κλείσει.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Αυτή η συζήτηση έχει σχέση με μια απροσδιόριστη πηγή ξένου περιεχομένου.';
$Definition['This discussion was created from comments split from: %s.'] = 'Αυτή η συζήτηση δημιουργήθηκε από σχόλια που διαχωρίστηκαν από: %s.';
$Definition['This discussion was merged into %s'] = 'Αυτή η συζήτηση ενώθηκε στο %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Το μέγεθος της εικόνας άλλαξε για να χωρέσει στη σελίδα. Πατήστε για μεγέθυνση.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Αυτή είναι μια ιδιωτική ψηφοφορία: κανείς δε θα δει τι ψηφίσατε';
$Definition['This is a public poll: others will see what you voted for.'] = 'Αυτή είναι μια δημόσια ψηφοφορία: οι υπόλοιποι θα δουν τι ψηφίσατε.';
$Definition['This is a system account and does not represent a real person.'] = 'Αυτός είναι λογαριασμός συστήματος και δεν αντιπροσωπεύει πραγματικό πρόσωπο.';
$Definition['This Month\'s Leaders'] = 'Οι Ηγέτες του Μήνα';
$Definition['This question\'s answer has been accepted.'] = 'Η απάντηση αυτής της ερώτησης έγινε αποδεκτή.';
$Definition['This user has been verified as a non-spammer.'] = 'Αυτός ο χρήστης έχει επιβεβαιωθεί ως μη-spammer.';
$Definition['This user has not been verified as a non-spammer.'] = 'Αυτός ο χρήστης δεν έχει επιβεβαιωθεί ως μη-spammer.';
$Definition['This user has not commented yet.'] = 'Αυτός ο χρήστης δεν έχει κάνει σχόλιο ακόμη.';
$Definition['This user has not made any discussions yet.'] = 'Αυτός ο χρήστης δεν έχει κάνει κάποια συζήτηση ακόμη.';
$Definition['This user is verified as a non-spammer'] = 'Αυτός ο χρήστης έχει επιβεβαιωθεί ως μη-spammer.';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Η προειδοποίηση έχει ληξει. Θέλετε να τη διαγράψετε οριστικά;';
$Definition['This Week\'s Leaders'] = 'Οι Ηγέτες της Εβδομάδας';
$Definition['Thumbnail'] = 'Μικρογραφία';
$Definition['Title'] = 'Τίτλος';
$Definition['TLS'] = 'TSL';
$Definition['Toggle full page'] = 'Εναλλαγή πλήρους σελίδας';
$Definition['Toggle HTML view'] = 'Εναλλαγή προβολής HTML';
$Definition['Toggle lights'] = 'Εναλλαγή φωτισμού';
$Definition['Topic'] = 'Θέμα';
$Definition['Topics'] = 'Θέματα';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'Για να στείλετε ένα νέο email επιβεβαίωσης πατήστε <a href="%s">εδώ</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'Για να χρησιμοποιήσετε το reCAPTCHA πρέπει να πάρετε ένα κλειδί API από %s';
$Definition['Transport error: %s'] = 'Ένα καίριο λάθος προέκυψε κατά τη διάρκεια της επεξεργασίας του αιτήματός σας.<br />Ο εξυπηρετητής επέστρεψε την εξής απάντηση: %s';
$Definition['Troll'] = 'Τρολ';
$Definition['Turn ON'] = 'Ενεργοποίηση';
$Definition['Twitter Settings'] = 'Ρυθμίσεις Twitter';
$Definition['Type'] = 'Τύπος';

$Definition['Unable to send message, %s is ignoring you.'] = 'Δεν μπορείτε να στείλετε μήνυμα,%s σας αγνοεί.';
$Definition['Unannounce'] = 'Ακύρωση Ανακοίνωσης';
$Definition['Unanswered'] = 'Αναπάντητες';
$Definition['Unanswered Questions'] = 'Αναπάντητες';
$Definition['unavailable'] = 'μη διαθέσιμο';
$Definition['Unban User'] = 'Αφαίρεση Αποκλεισμού Χρήστη';
$Definition['Unbookmark'] = 'Κατάργηση Αγαπημένου';
$Definition['Undefined discussion body.'] = 'Απροσδιόριστο περιεχόμενο συζήτησης.';
$Definition['Undefined discussion subject.'] = 'Απροσδιόριστο θέμα συζήτησης.';
$Definition['Undefined foreign content'] = 'Απροσδιόριστο ξένο περιεχόμενο';
$Definition['Undo Follow'] = 'Αναίρεση Ακολουθίας';
$Definition['Unfollow'] = 'Να μην ακολουθείτε';
$Definition['Unhide'] = 'Αφαίρεση απόκρυψης';
$Definition['Unignore'] = 'Aναίρεση παράβλεψης';
$Definition['Unknown'] = 'Άγνωστος';
$Definition['Unknown client: %s.'] = 'Άγνωστος πελάτης: %s.';
$Definition['Unordered list'] = 'Μη ταξινομημένη λίστα';
$Definition['Unread'] = 'Αδιάβαστα';
$Definition['Unread Discussions'] = 'Αδιάβαστες Συζητήσεις';
$Definition['Unsink'] = 'Σταμάτημα βύθισης';
$Definition['Unspecified'] = 'Αδήλωτος';
$Definition['Upcoming Events'] = 'Επερχόμενες Εκδηλώσεις';
$Definition['Update'] = 'Ενημερώστε';
$Definition['Updated badge'] = 'Ενημερωμένο έμβλημα';
$Definition['Upload'] = 'Ανέβασμα';
$Definition['Uploading...'] = 'Γίνεται μεταφόρτωση...';
$Definition['UrlCode'] = 'Κώδικας Url';
$Definition['Use My Current Password'] = 'Χρήση του Τρέχοντος Κωδικού Μου';
$Definition['User "%s" does not exist.'] = 'Ο χρήστης "%s" δεν υπάρχει.';
$Definition['Username'] = 'Όνομα Χρήστη';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Το Όνομα Χρήστη μπορεί να περιέχει μόνο γράμματα, αριθμούς και κάτω παύλες';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'Το Όνομα Χρήστη μπορεί να περιέχει μόνο γράμματα, αριθμούς, κάτω παύλες, και πρέπει να έχει μήκος απο 3 έως 20 χαρακτήρες.';
$Definition['UsernameError'] = 'Το Όνομα Χρήστη μπορεί να περιέχει μόνο γράμματα, αριθμούς, κάτω παύλες, και πρέπει να έχει μήκος απο 3 έως 20 χαρακτήρες.';
$Definition['Username or email'] = 'Όνομα Χρήστη ή email';
$Definition['User not found.'] = 'Λυπάμαι, δεν υπάρχει λογαριασμός με το email/όνομα χρήστη που δώσατε.';
$Definition['Users Count'] = 'Πλήθος Χρηστών';

$Definition['ValidateBanned'] = 'Αυτό το %s δεν είναι έγκυρο.';
$Definition['ValidateBoolean'] = 'Το %s δεν είναι έγκυρη λογική μεταβλητή.';
$Definition['ValidateConnection'] = 'Οι παράμετροι που δώσατε απέτυχαν να ανοίξουν σύνδεση με τη βάση δεδομένων. Η βάση δεδομένων επέστρεψε το ακόλουθο μήνυμα λάθους: <code>%s</code>';
$Definition['ValidateDate'] = 'Το %s δεν είναι έγκυρη ημερομηνία.';
$Definition['ValidateDecimal'] = 'Το %s δεν είναι έγκυρος δεκαδικός.';
$Definition['ValidateEmail'] = 'Το %s δεν φαίνεται να είναι έγκυρο.';
$Definition['ValidateEnum'] = 'Το %s δεν είναι έγκυρο.';
$Definition['ValidateFormat'] = 'Δεν επιτρέπετε να δημοσιεύσετε html.';
$Definition['ValidateInteger'] = 'Το %s δεν είναι έγκυρος ακέραιος.';
$Definition['ValidateIntegerArray'] = 'Το %s πρέπει να είναι μία λίστα με αριθμούς που χωρίζονται με κόμμα.';
$Definition['ValidateLength'] = 'Το %1$s είναι κατά %2$s χαρακτήρες μεγαλύτερο.';
$Definition['ValidateMatch'] = 'Τα %s πεδία δεν ταιρίαζουν.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Πρέπει να επιλέξεις τουλάχιστον ένα %s.';
$Definition['ValidateRegex'] = 'Το %s δεν φαίνεται να είναι στη σωστή μορφή.';
$Definition['ValidateRequired'] = 'Το %s είναι υποχρεωτικό.';
$Definition['ValidateRequiredArray'] = 'Πρέπει να επιλέξεις τουλάχιστον ένα %s.';
$Definition['ValidateTag'] = 'Οι ετικέτες δε μπορεί να έχουν κενά';
$Definition['ValidateTime'] = 'Το %s δεν είναι έγκυρη ώρα.';
$Definition['ValidateTimestamp'] = 'Το %s δεν είναι έγκυρο timestamp.';
$Definition['ValidateUrlStringRelaxed'] = 'Το %s δεν μπορεί να περιέχει πλάγιες, εισαγωγικά ή χαρακτήρες tag.';
$Definition['ValidateUsername'] = 'Το όνομα του χρήστη πρέπει να είναι από 3-20 χαρακτήρες και να περιλαμβάνει γράμματα, αριθμούς και το σύμβολο της κάτω παύλας.';
$Definition['ValidateVersion'] = 'Το πεδίο  %s δεν έχει έγκυρο αριθμό έκδοσης. Δείτε τη συνάρτηση version_compare() για παραδείγματα έγκυρων αριθμών εκδόσεων.';
$Definition['Value'] = 'Τιμή';
$Definition['Vanilla Statistics'] = 'Στατιστικά Vanilla';
$Definition['Vanilla Statistics Plugin'] = 'Πρόσθετο Στατιστικών Vanilla';
$Definition['Verified'] = 'Επιβεβαιωμένος';
$Definition['Verifying your credentials...'] = 'Επιβεβαιώνονται τα στοιχεία σας...';
$Definition['via %s'] = 'μέσω %s';
$Definition['Video embedding has been disabled.'] = 'Η ενσωμάτωση βίντεο έχει απενεργοποιηθεί. Τα URLs δεν θα μεταφράσουν στο εσωματωμένο ισοδύναμό τους.';
$Definition['View Badge'] = 'Εμφάνιση Εμβλήματος';
$Definition['Viewing'] = 'Προβολή';
$Definition['Views'] = 'Εμφανίσεις';
$Definition['Visible'] = 'Ορατό';
$Definition['Visits'] = 'Επισκέψεις';
$Definition['Visit Site'] = 'Επισκεφτείτε τη Σελίδα';
$Definition['Vote'] = 'Ψήφος';
$Definition['Vote Down'] = 'Καταψηφίστε';
$Definition['Votes'] = 'Ψήφοι';
$Definition['Vote Up'] = 'Υπερψηφίστε';

$Definition['wall'] = 'τοίχος';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Θέλετε να συμμετάσχετε σε αυτή τη συζήτηση; Πατήστε κάποιο από τα εξής:';
$Definition['Warn'] = 'Προειδοποίηση';
$Definition['Warn %s'] = 'Προειδοποίησε %s';
$Definition['Warned for'] = 'Προειδοποίηση για';
$Definition['Warning'] = 'Προειδοποίηση';
$Definition['Warnings'] = 'Προειδοποιήσεις';
$Definition['WarningTitleFormat'] = 'Ο χρήστης {InsertUserID,User} προειδοποιήθηκε από το χρήστη {WarnUserID,User} για {Points,plural,%s points}.';
$Definition['WarningTitleFormat.Notice'] = 'Ο χρήστης {InsertUserID,User} προειδοποιήθηκε από το χρήστη {WarnUserID,User} για {Points,plural,%s points} (απλά μια ανακοίνωση).';
$Definition['was'] = 'ήταν';
$Definition['Website'] = 'Ιστοσελίδα';
$Definition['weeks'] = 'εβδομάδες';
$Definition['Welcome Aboard!'] = 'Καλωσήλθατε στο χώρο μας!';
$Definition['were'] = 'ήταν';
$Definition['What\'s This?'] = 'Τι είναι αυτό;';
$Definition['What to search'] = 'Τι να αναζητήσετε';
$Definition['Where do you want to announce this discussion?'] = 'Θέλετε να ανακοινώσετε αυτή τη συζήτηση;';
$Definition['Who\'s Online'] = 'Ποιός είναι Συνδεμένος';
$Definition['Whoops! You\'ll need to register before you can email our site.'] = 'Ουπς! Θα χρειαστεί να εγγραφείτε πριν μπορέσετε να στείλετε email στην ιστοσελίδα μας.';
$Definition['Whos Online'] = 'Ποιός είναι Συνδεμένος';
$Definition['Why are you Banning this user?'] = 'Γιατί Αποκλείετε αυτόν τον χρήστη;';
$Definition['Write a comment'] = 'Γράψτε ένα σχόλιο';
$Definition['Write Comment'] = 'Γράψε Σχόλιο';
$Definition['Write something about yourself...'] = 'Γράψε κάτι για τον εαυτό σας...';
$Definition['WTF'] = 'Τι στο καλό!';

$Definition['Yes'] = 'Ναι';
$Definition['You'] = 'Εσείς';
$Definition['you'] = 'εσείς';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">Έχετε θέσει ερωτήσεις που πλέον έχουν απαντήσεις</a>. Βεβαιωθείτε ότι έχετε αποδεχθεί/απορρίψει τις απαντήσεις.';
$Definition['You\'ve been Jailed.'] = 'Έχετε Φυλακισθεί.';
$Definition['You already have an account here.'] = 'Έχετε ήδη έναν λογαριασμό εδώ.';
$Definition['You are about to ban {User.UserID,user}.'] = 'Πρόκειται να αποκλείσετε τον χρήστη {User.UserID,user}.';
$Definition['You are about to move %1$s of the %2$s of the selected discussions.'] = 'Πρόκειται να μετακινήσετε το %1$s απο τo %2$s απο τις επιλεγμένες συζητήσεις.';
$Definition['You are about to move %s.'] = 'Πρόκειται να μετακινήσετε το %s.';
$Definition['You are about to unban {User.UserID,user}.'] = 'Πρόκειται να άρετε τον αποκλεισμό του χρήστη {User.UserID,user}.';
$Definition['You are allowed to create %s groups.'] = 'Δεν σας επιτρέπεται να δημιουργήσετε %s ομάδες.';
$Definition['You are connected as %s through %s.'] = 'Είσαι συνδεδεμένος ως %s μέσω του %s.';
$Definition['You are connected through %2$s.'] = 'Είσαι συνδεδεμένος μέσω του %2$s.';
$Definition['You are currently only viewing categories that you follow.'] = 'Βλέπετε μόνο τις κατηγορίες που ακολουθείτε.';
$Definition['You are currently viewing all categories.'] = 'Βλέπετε όλες τις κατηγορίες';
$Definition['You are editing %s\'s signature'] = 'Επεξεργάζεστε την υπογραφή του χρήστη %s.';
$Definition['You are limited to %s recipient.'] = 'Έχετε περιορισμό σε %s παραλήπτη.';
$Definition['You are limited to %s recipients.'] = 'Έχετε περιορισμό %s παραληπτών.';
$Definition['You can\'t leave the group you started.'] = 'Δεν μπορείτε να αποχωρήσετε από την ομάδα που έχετε δημιουργήσει.';
$Definition['You can either ask a question or start a discussion.'] = 'Μπορείτε να κάνετε μια ερώτηση ή να αρχίσετε μια συζήτηση. Διαλέξτε τι θέλετε παρακάτω.';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Μπορείτε να ακολουθήσετε συγκεκριμένες κατηγορίες και να ενημερώνεστε για όλες τις αναρτήσεις που θα γίνονται σε αυτές.';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Δεν μπορείτε να επεξεργαστείτε τη μικρογραφία μιας εξωτερικά συνδεδεμένης εικόνας προφίλ';
$Definition['You can only specify up to %s tags.'] = 'Μπορείτε να καθορίστετε μόνο μέχρι %s ετικέτες.';
$Definition['You can remove or ban this member from the group.'] = 'Μπορείτε να αφαιρέσετε ή να αποκλείσετε αυτό το μέλος από την ομάδα. Τα αποκλεισμένα μέλη δεν θα μπορούν να γίνουν ξανά μέλη αυτής της ομάδας.';
$Definition['You can use HTML in your signature.'] = 'Μπορείτε να χρησιμοποιήσετε <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Απλή Html</a></b> στην υπογραφή σας.';
$Definition['You don\'t have permission to do that.'] = 'Δεν έχετε την άδεια να το κάνετε αυτό.';
$Definition['You do not have any %s yet.'] = 'Δεν έχετε κανένα %s ακόμη.';
$Definition['You do not have any bookmarks.'] = 'Δεν έχετε κάποια αγαπημένη σελίδα.';
$Definition['You do not have any conversations.'] = 'Δεν έχετε κάποια συνομιλία.';
$Definition['You do not have any drafts.'] = 'Δεν έχετε κάποιο προσχέδιο';
$Definition['You do not have any notifications yet.'] = 'Δε έχετε κάποια ειδοποίηση ακόμη.';
$Definition['You do not have enough invitations left.'] = 'Δεν σας έχουν επομείνει αρκετές προσκλήσεις.';
$Definition['You do not have permission to move %1$s of the selected discussions.'] = 'Δεν έχετε άδεια για να μετακινήσετε το %1$s  των επιλεγμένων συζητήσεων.';
$Definition['You do not have permission to write new comments.'] = 'Δεν έχτε άδεια να γράψετε νέα σχόλια.';
$Definition['YouEarnedBadge'] = 'Κερδίσατε αυτό το έμβλημα';
$Definition['You have answered questions'] = 'Έχετε απαντήσεις στις ερωτήσεις σας';
$Definition['You have entered an invalid discussion title'] = 'Έχετε δώσει μη αποδεκτό τίτλο συζήτησης';
$Definition['You haven\'t read this yet.'] = 'Δεν το έχετε διαβάσει ακόμη αυτό.';
$Definition['You have not started any discussions.'] = 'Δεν έχετε ξεκινήσει κάποια συζήτηση.';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Έχετε ανεβάσει αναρτήσεις %1$s φορές μέσα σε %2$s δευτερόλεπτα. Ένα spam block είναι ενεργό στο λογαριασμό σας. Πρέπει να περιμένετε τουλάχιστον %3$s δευτερόλεπτα πριν προσπαθήσετε να ανεβάσετε νέα ανάρτηση.';
$Definition['You have selected %1$s.'] = 'Έχετε επιλέξει %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Έχετε επιλέξει %1$s σε αυτή τη συζήτηση.';
$Definition['You have to select at least 2 discussions to merge.'] = 'Πρέπει να επιλέξετε τουλάχιστον 2 συζητήσεις για συνένωση.';
$Definition['You must agree to the terms of service.'] = 'Πρέπει να συμφωνήσετε με τους όρους της υπηρεσίας.';
$Definition['You need to confirm your email address.'] = 'Πρέπει να επιβεβαιώσετε τη διαύθυνση email σας. Πατήστε <a href="{/entry/emailconfirmrequest,url}">εδώ</a> για να σας αποσταλεί το email επιβεβαίωσης.';
$Definition['You need to sign in before you can do this.'] = 'Πρέπει να συνδεθείτε πριν το κάνετε αυτό.';
$Definition['your'] = 'δικό σας';
$Definition['Your changes have been saved.'] = 'Οι αλλαγές σας έχουν αποθηκευτεί.';
$Definition['Your changes have been saved successfully.'] = 'Οι αλλαγές σας έχουν αποθηκευτεί επιτυχώς';
$Definition['Your changes were saved.'] = 'Οι αλλαγές σας αποθηκεύτηκαν.';
$Definition['Your email has been successfully confirmed.'] = 'Το email σας επιβεβαιώθηκε επιτυχώς.';
$Definition['Your invitation has been sent.'] = 'Η πρόσκλησή σας εστάλη.';
$Definition['Your old password was incorrect.'] = 'Ο παλιός κωδικός σας είναι λανθασμένος.';
$Definition['Your password has been changed.'] = 'Ο κωδικός σας άλλαξε.';
$Definition['Your picture has been removed.'] = 'Η εικόνα σας απομακρύνθηκε.';
$Definition['Your post will appear once it\'s been approved.'] = 'Η ανάρτησή σας θα εμφανιστεί μόλις εγκριθεί.';
$Definition['Your preferences have been saved.'] = 'Οι προτιμήσεις σας έχουν αποθηκευτεί.';
$Definition['Your private conversations with other members.'] = 'Οι ιδιωτικές συνομιλίες σας με άλλα μέλη.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Το εγγεγραμμένο σας όνομα χρήστη: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'Το αίτημά σας στάλθηκε. Ελέγξτε το email σας για περαιτέρω οδηγίες.';
$Definition['Your settings have been saved.'] = 'Οι ρυθμίσεις σας έχουν αποθηκευτεί.';
$Definition['Your settings have been saved successfully.'] = 'Οι ρυθμίσεις σας έχουν αποθηκευτεί επιτυχώς.';
$Definition['Your warning was added.'] = 'Η προειδοποίησή σας προστέθηκε.';

$Definition[' You should '] = 'Θα έπρεπε';

$Definition['You were added to a conversation.'] = 'Ο χρήστης {InsertUserID,user} πρόσθεσε το χρήστη {NotifyUserID,you} σε μία <a href="{Url,htmlencode}">συνομιλία</a>.';
$Definition['You wrote:'] = 'Εσύ έγραψες:';

$Definition['↳ No results for \'%s\''] = '↳ Κανένα αποτέλεσμα για \'%s\'';
$Definition['↳ Search results for \'%s\''] = '↳ Αποτελέσματα αναζήτησης για \'%s\'';
$Definition['↳ Show All'] = '↳ Εμφάνιση Όλων';
