<?php

$Definition['%1$s "%2$s" not found.'] = '%1$s "%2$s" ikke fundet.';
$Definition['%1$s version %2$s is available.'] = '%1$s version %2$s er tilgængelig.';
$Definition['%s is not a valid email address'] = '%s er ikke en gyldig email-adresse';
$Definition['%s item in queue'] = '%s i kø';
$Definition['%s level'] = '%s niveau';
$Definition['%s levels'] = '%s niveauer';
$Definition['%s site(s) found.'] = '%s side(r) fundet.';
$Definition['%s sources(s) found.'] = '%s kilder(s) fundet.';
$Definition['%s times'] = '%s gange';
$Definition['%s unavailable'] = '%s ikke tilgængelig';
$Definition['%s user(s) found.'] = '%s brugere fundet.';
$Definition['%s user(s) will be affected by this action.'] = '%s bruger(e) vil blive påvirket af denne ændring.';
$Definition['%s years.'] = '%s år.';

$Definition['(less)'] = '(mindre)';
$Definition['(more)'] = '(mere)';

$Definition['1 day'] = '1 dag';
$Definition['1 hour'] = '1 time';
$Definition['1 month'] = '1 måned';
$Definition['1 month after being sent'] = '1 måned efter sendt';
$Definition['1 week'] = '1 uge';
$Definition['1 week after being sent'] = '1 uge efter sendt';
$Definition['2 weeks after being sent'] = '2 uger efter sendt';
$Definition['4 hours'] = '4 timer';
$Definition['5 minutes'] = '5 minutter';
$Definition['15 minutes'] = '15 minutter';

$Definition['[%s] Confirm Your Email Address'] = '[%s] Bekræft din E-mail-adresse';
$Definition['[%s] Password Reset'] = '[%s] Nulstilling af adgangskode';
$Definition['[%s] Password Reset Request'] = '[%s] Password nulstilling anmodning';

$Definition['a Badge'] = 'et Badge';
$Definition['Abilites'] = 'Muligheder';
$Definition['Abilities'] = 'Muligheder';
$Definition['Above Main Content'] = 'Over hovedindholdet';
$Definition['Account Sync Failed'] = 'Konto Synkronisering mislykkedes';
$Definition['Action'] = 'Handling';
$Definition['Actions Based on Votes'] = 'Aktioner baseret på stemmer';
$Definition['Activity Item'] = 'Aktiviteten vare';
$Definition['Activity item not found.'] = 'Aktivitet element blev ikke fundet.';
$Definition['Add a new Pocket to your site.'] = 'Tilføje en ny lomme til dit websted.';
$Definition['Add Category'] = 'Tilføj kategori';
$Definition['Add Connection'] = 'Tilføje forbindelse';
$Definition['Added By'] = 'Tilføjet af';
$Definition['Add Info &amp; Create Account'] = 'Tilf¯j Info &amp; Lav Bruger';
$Definition['Add information into the from field in email addresses to help with replies (recommended).'] = 'Tilføje oplysninger i den fra felt i e-mail-adresser til at hjælpe med svar (anbefales).';
$Definition['Adding & Editing Categories'] = 'Tilføje & redigering kategorier';
$Definition['Add Item'] = 'Tilføj element';
$Definition['Addons'] = 'Tilføjelser';
$Definition['Add Role'] = 'Tilføj rolle';
$Definition['Add User'] = 'Tilf¯j Bruger';
$Definition['Advanced Editor Settings'] = 'Avanceret Editor-indstillinger';
$Definition['Advanced Embed Settings'] = 'Avanceret Embed indstillinger';
$Definition['Advanced Forum Settings'] = 'Avanceret Forum indstillinger';
$Definition['Advanced Options'] = 'Avancerede indstillinger';
$Definition['Advanced Settings'] = 'Avancerede indstillinger';
$Definition['Advanced settings for embedded community elements'] = 'Avancerede indstillinger for integrerede fællesskabselementerne';
$Definition['After'] = 'Efter';
$Definition['a full year.'] = 'et helt år.';
$Definition['Alive'] = 'I live';
$Definition['All %1$s'] = 'Alle %1$s';
$Definition['All Dashboard Pages'] = 'Alle Dashboard sider';
$Definition['All discussions in this category will be permanently deleted.'] = 'Alle diskussioner i denne kategori vil blive slettet permanent.';
$Definition['All Forum Pages'] = 'Alle Forum sider';
$Definition['All of the user content will be replaced with a message stating the user has been deleted.'] = 'Alle bruger-indhold vil blive erstattet med en meddelelse om brugeren er blevet slettet.';
$Definition['Allow embedded content'] = 'Tillad indlejret indhold';
$Definition['Allow images'] = 'Tillad billeder';
$Definition['Allow new users to be registered through email.'] = 'Tillad nye brugere at registere via e-mail.';
$Definition['Allow users to dismiss this message'] = 'Tillad brugere at afvise denne meddelelse';
$Definition['All Pages'] = 'Alle sider';
$Definition['Applicant'] = 'Ans¯ger';
$Definition['Applicant Role'] = 'Vælg den rolle, der skal anvendes for nye ansøgere. Dette gælder kun hvis du har <b>godkendelse</b> registrering metode.';
$Definition['Application'] = 'Ands¯gning';
$Definition['Application ID'] = 'Ands¯gnings ID';
$Definition['Applications'] = 'Ans¯gninger';
$Definition['Application Secret'] = 'Ans¯gnings Hemmelighed';
$Definition['Applied by Administrator'] = 'Anvendes af administratoren';
$Definition['Applied Manually'] = 'Anvendes manuelt';
$Definition['Applied On'] = 'Dato';
$Definition['Approval'] = 'Godkendelse';
$Definition['Archive Discussions'] = 'Arkiver Diskussioner';
$Definition['Are you sure you want to delete %s items forever?'] = 'Er du sikker på du vil slette %s varer for evigt?';
$Definition['Are you sure you want to delete 1 item forever?'] = 'Er du sikker på du vil slette denne for evigt?';
$Definition['Are you sure you want to delete this badge? This is irreversible and will revoke the badge from all users who have it.'] = 'Er du sikker på du vil slette denne badge? Dette er irreversibel og vil tilbagekalde badge fra alle brugere, der har det.';
$Definition['Are you sure you want to delete this category?'] = 'Er du sikker på du vil slette denne kategori?';
$Definition['Are you sure you want to restore %s items?'] = 'Er du sikker på, du vil gendanne %s elementer?';
$Definition['Are you sure you want to restore 1 item?'] = 'Er du sikker på, du vil gendanne 1 element?';
$Definition['A url-friendly version of the category name for better SEO.'] = 'En url-version af kategori navnet for bedre SEO.';
$Definition['Authors may always edit'] = 'Forfattere kan altid redigere';
$Definition['Authors may edit for %s'] = 'Forfattere kan redigere til %s';
$Definition['Authors may never edit'] = 'Forfatterne må aldrig redigere';
$Definition['Auto-Fetch New Comments'] = 'Auto-hente nye kommentarer';

$Definition['Background Color'] = 'Baggrundsfarve';
$Definition['Back to all users'] = 'Tilbage til alle brugere';
$Definition['Back to Mobile Site'] = 'Tilbage til Mobile Site';
$Definition['Badge cannot be deleted.'] = 'Badge kan ikke slettes.';
$Definition['Badge deleted.'] = 'Badge slettet.';
$Definition['Badge Name'] = 'Navn';
$Definition['BadgeRecipientsHeading'] = 'Seneste modtagere';
$Definition['Badge Requests'] = 'Badge anmodninger';
$Definition['Ban Item'] = 'Element';
$Definition['Banner Title'] = 'Bannertitel';
$Definition['Banning'] = 'Forbud mod';
$Definition['Banning Options'] = 'Ban indstillinger';
$Definition['Ban Type'] = 'Type';
$Definition['Basic Information'] = 'Grundlæggende oplysninger';
$Definition['Before'] = 'Før';
$Definition['Begin At'] = 'Begynde på';
$Definition['Below Sidebar'] = 'Under Sidebar';
$Definition['Blocked'] = 'Blokeret';
$Definition['Blog Comments'] = 'Blog kommentarer';
$Definition['Browse Addons'] = 'Gennemse Addons';
$Definition['Browse for a new banner logo if you would like to change it:'] = 'Søg efter et nyt banner logo hvis du ønsker at ændre det:';
$Definition['Button Background Color'] = 'Knappers baggrundsfarve';
$Definition['Button Text Color'] = 'Knappers tekstfarve';

$Definition['Cannot build profile information if user is not defined.'] = 'Kan ikke opbygge profiloplysninger, hvis brugeren ikke er defineret.';
$Definition['Categories &amp; Discussions'] = 'Kategorier &amp; diskussioner';
$Definition['Categories are used to organize discussions.'] = 'Kategorier bruges til at hjælpe dine brugere med at organisere deres diskussioner på en måde der er meningsfuld for dit fællesskab.';
$Definition['Categories Layout'] = 'Kategorier Layout';
$Definition['Category Page Layout'] = 'Kategori sidelayout';
$Definition['Category Url:'] = 'Kategori Url:';
$Definition['Censored Words'] = 'Censurerede ord';
$Definition['Change Log'] = 'Ændringsloggen';
$Definition['Change the look of All Categories'] = 'Du kan ændre udseendet af <b>Alle kategorier</b> side <a href="%s"> her</a>.';
$Definition['Change the way that new users register with the site.'] = 'Lav om pÂ mÂden som nye brugere registrere pÂ.';
$Definition['Change your banner'] = 'Ændre din banner';
$Definition['Changing the Discussions Menu Link'] = 'Ændre linket diskussioner Menu';
$Definition['Check all permissions that apply for each role'] = 'Tjek alle tilladelser, der gÊlder for hver rolle';
$Definition['Check all permissions that apply to this role:'] = 'Kontrollér alle tilladelser, der gælder for denne rolle:';
$Definition['Check out the new community forum I\'ve just set up.'] = 'Hej ven!

Tjek det nye fællesskabsforum jeg lige har sat op. Det er alletiders sted for os til at chatte med hinanden online.';
$Definition['Choose a locale pack'] = 'VÊlg en lokal pakke';
$Definition['Choose who can send out invitations to new members:'] = 'VÊlg hvem der kan sende invitationer til nye medlemmer:';
$Definition['Client ID'] = 'Klient ID';
$Definition['comment(s)'] = 'kommentar(er)';
$Definition['Comment Settings'] = 'Kommentar indstillinger';
$Definition['Comments per Page'] = 'Kommentarer per side';
$Definition['Condition Expression'] = 'Værdi';
$Definition['Condition Field'] = 'Field';
$Definition['Conditions'] = 'Vilkår';
$Definition['Condition Type'] = 'Type';
$Definition['Configure an Authenticator'] = 'Konfigurerer en Godkendelsesprocedurer';
$Definition['Configuring Vanilla\'s Homepage'] = 'Konfigurer Vanilla\'s hjemmeside';
$Definition['Confirm email addresses'] = 'Require users to confirm their email addresses (recommended)';
$Definition['Conversation Messages'] = 'Samtale Meddelelser';
$Definition['Conversations'] = 'Samtaler';
$Definition['CreateFile'] = 'Create';
$Definition['Current Authenticator'] = 'NuvÊrende Godkendelsesprocedure';
$Definition['Current Theme'] = 'NuvÊrende Tema';

$Definition['Decline'] = 'AfslÂ';
$Definition['Default  Category'] = 'Standard kategorier';
$Definition['default type'] = 'default';
$Definition['Define your forum homepage'] = 'Beskriv dit forums hjemmeside';
$Definition['Description'] = 'Beskrivelse';
$Definition['Disable'] = 'Deaktiver';
$Definition['Disabled %1$s'] = 'Deaktiverede %1$s';
$Definition['Discussion & Comment Editing'] = 'Diskussion & Kommentar Redigering';
$Definition['discussion(s)'] = 'diskussion(er)';
$Definition['Discussions per Page'] = 'Diskussioner per Side';
$Definition['DownloadLocalePack'] = 'Download';

$Definition['Edit Category'] = 'Rediger Kategori';
$Definition['Edit HTML'] = 'Rediger HTML';
$Definition['Edit User'] = 'Rediger Bruger';
$Definition['Email Styles'] = 'E-mail-stilarter';
$Definition['Enable'] = 'Aktiver';
$Definition['Enabled %1$s'] = 'Aktiverede %1$s';
$Definition['Enable embedding to use blog comments.'] = 'In order for this to work, you will need to enable embedding.';
$Definition['Enable OpenID'] = 'Aktiver OpenID';
$Definition['Enter the email address of the person you would like to invite:'] = 'Indtast email adressen for personen du vil invitere:';
$Definition['Enter the url to the page you would like to use as your homepage'] = 'Indtast url adressen på den side du vil bruge som din hjemmeside';
$Definition['Enter the url to the page you would like to use as your homepage:'] = 'Indtast url adressen på den side du vil bruge som din hjemmeside';
$Definition['Error sending email. Please review the addresses and try again.'] = 'Fejl ved e-mail-afsendelse. Gennemse venligst adresserne og prøv igen.';
$Definition['Every %s hour'] = 'Every hour';
$Definition['Every %s minute'] = 'Every minute';
$Definition['Every %s second'] = 'Every second';
$Definition['Existing members send invitations to new members.'] = 'Eksisterende medlemer sender invitationer til nye medlemmer.';

$Definition['Facebook Settings'] = 'Facebook Indstillinger';
$Definition['FaviconBrowse'] = 'Browse for a new favicon if you would like to change it:';
$Definition['FaviconDescription'] = 'Your site\'s favicon appears in your browser\'s title bar. It will be scaled to 16x16 pixels.';
$Definition['First Visit'] = 'F¯rste Bes¯g';
$Definition['Forum Settings'] = 'Forum Indstillinger';

$Definition['Generate'] = 'Generer';
$Definition['Give a Badge'] = 'Giv et badge';
$Definition['Guest roles'] = 'Check all roles that should be applied to guests.';

$Definition['HeadlineFormat.AddUser'] = '{ActivityUserID,user} added an account for {RegardingUserID,user}.';
$Definition['HeadlineFormat.PictureChange'] = '{RegardingUserID,You} changed {ActivityUserID,your} profile picture.';
$Definition['HeadlineFormat.RegistrationApproval'] = '{ActivityUserID,user} approved the applications for {RegardingUserID,user}.';
$Definition['HeadlineFormat.Status'] = '{ActivityUserID,user}';
$Definition['HeadlineFormat.WallPost'] = '{RegardingUserID,you} &rarr; {ActivityUserID,you}';
$Definition['Help &amp; Tutorials'] = 'Hjælp & Vejledninger';
$Definition['Hide from the recent discussions page.'] = 'Skjul fra siden seneste diskussioner.';
$Definition['Hide signatures for guests'] = 'Skjul underskrifter for gæster';
$Definition['Hide signatures on embedded comments'] = 'Skjul underskrifter på indlejrede kommentarer';
$Definition['Homepage'] = 'Hjemmeside';
$Definition['Homepage Title'] = 'Hjemmeside titel';
$Definition['Html'] = 'HTML';
$Definition['HTML Emails'] = 'HTML e-mails';

$Definition['Invitation Code'] = 'Invitations Kode';
$Definition['InvitationMessage'] = 'Hi Pal!

Check out the new community forum I\'ve just set up. It\'s a great place for us to chat with each other online.

Follow the link below to log in.';
$Definition['Invitations per month'] = 'Invitationer per mÂned';
$Definition['Invitations will expire'] = 'Invitationer vil udl¯be';
$Definition['Invited by'] = 'Inviteret af';

$Definition['Key Type'] = 'Kode Type';
$Definition['Key Value'] = 'Kode VÊrdi';

$Definition['Large images will be scaled down.'] = 'Store billeder vil blive nedskaleret til en maks bredde på %spx og en maks højde på %spx.';
$Definition['Last Visit'] = 'Sidste Bes¯g';
$Definition['Locale Key (Folder)'] = 'sprog Kode (Mappe)';
$Definition['Locale Name'] = 'sprog Navn';
$Definition['Locales'] = 'sprog pakker';
$Definition['Location'] = 'Placering';
$Definition['LogoBrowse'] = 'Søg efter et nyt banner logo hvis du ønsker at ændre det:';

$Definition['Manage Applicants'] = 'Administrer Ans¯gere';
$Definition['Manage Applications'] = 'Administrer Ans¯gninger';
$Definition['Manage Categories'] = 'Administrer Kategorier';
$Definition['Manage Messages'] = 'Administrer Beskeder';
$Definition['Manage Plugins'] = 'Administrer plugins';
$Definition['Manage Roles & Permissions'] = 'Administrer Roller & Tilladelser';
$Definition['Manage Spam'] = 'Administrer Spam';
$Definition['Manage Themes'] = 'Administrer Temaer';
$Definition['Manage Users'] = 'Administrer Brugere';
$Definition['Max %s length'] = 'Maks %s længde';
$Definition['Max Comment Length'] = 'Maximum Kommentar lÊngde';
$Definition['Max height of %s'] = 'Maks højde på %s';
$Definition['Max height of %s in pixels'] = 'Maks højde på %s i pixels';
$Definition['Max number of %s'] = 'Maks antal %s';
$Definition['Member roles'] = 'Check all roles that should be applied to new/approved users.';
$Definition['Method'] = 'Metode';
$Definition['minute(s)'] = 'minut(ter)';
$Definition['My Invitations'] = 'Mine Invitationer';

$Definition['never'] = 'Aldrig';
$Definition['NewApplicantEmail'] = 'New applicant:';
$Definition['New comments in the last day'] = 'Nye kommentarer pÂ den sidste dag';
$Definition['New comments in the last week'] = 'Nye kommentarer pÂ den sidste uge';
$Definition['New conversations in the last day'] = 'Nye samtaler pÂ den sidste dag ';
$Definition['New conversations in the last week'] = 'Nye samtaler pÂ den sidste uge';
$Definition['New discussions in the last day'] = 'Nye diskussioner pÂ den sidste dag';
$Definition['New discussions in the last week'] = 'Nye diskussioner pÂ den sidste uge';
$Definition['New messages in the last day'] = 'Nye beskeder pÂ den sidste dag';
$Definition['New messages in the last week'] = 'Nye beskeder pÂ den sidste uge';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'Nye brugere bliver gennemgÂet og godkendt af en administrator (det er dig!).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'Nye brugere udfylder en simpel registration og er givet adgang med det samme.';
$Definition['New users in the last day'] = 'Nye brugere pÂ den sidste dag';
$Definition['New users in the last week'] = 'Nye brugere i den forrige uge';
$Definition['No results for %s.'] = 'No results for <b>%s</b>.';
$Definition['Notes'] = 'Noter';
$Definition['NotifyApplicant'] = 'Notify me when anyone applies for membership.';

$Definition['On'] = 'PÂ';
$Definition['Operation By'] = 'Af';
$Definition['Organize Categories'] = 'Organiser kategorierne';
$Definition['Original Version'] = 'Original version';
$Definition['Other Themes'] = 'Andre temaer';
$Definition['Outgoing Email'] = 'UdgÂende Email';

$Definition['Page Color'] = 'Sidefarve';
$Definition['Password Options'] = 'Kodeords Indstillinger';
$Definition['Permission.Category'] = 'Kategori';
$Definition['Permissions'] = 'Rettigheder';
$Definition['Plugins'] = 'Tilføjelser';
$Definition['Preview Colors'] = 'Forhåndsvisning af farver';
$Definition['Private Key'] = 'Privat Kode';
$Definition['Public Key'] = 'Offentlig Kode';

$Definition['Recently Active Users'] = 'For nylig Aktive  Brugere';
$Definition['Record Content'] = 'Content';
$Definition['Refresh Comments'] = 'OpdatÈr Kommentarer';
$Definition['Remove Email Logo'] = 'Fjern e-mail-logo';
$Definition['Requires: '] = 'KrÊver: ';
$Definition['Reset password and send email notification to user'] = 'Nulstil kodeord og send email meddelelse til bruger';
$Definition['Restart'] = 'Genstart';
$Definition['Reveal Password'] = 'Vis kodeord';
$Definition['Role'] = 'Rolle';
$Definition['Role Name'] = 'Rolle navn';
$Definition['Roles & Permissions'] = 'Roller & Tilladelser';
$Definition['Roles determine user\'s permissions.'] = 'Hver bruger pÂ dit forum har mindst en rolle. Roller kan blive brugt til at bestemme hvad brugeren kan.';
$Definition['Route'] = 'Rute';
$Definition['Routes'] = 'Ruter';

$Definition['Save Colors'] = 'Gem farver';
$Definition['Search by user or role.'] = 'Search for users by name or enter the name of a role to see all users with that role.';
$Definition['seconds'] = 'sekunder';
$Definition['Security'] = 'Sikkerhed';
$Definition['Select'] = 'Vælg';
$Definition['Send %s a Message'] = 'Send %s en Besked';
$Definition['Send a confirmation email when people ask a question or start a discussion over email.'] = 'Send en bekræftelses email når folk stiller et spørgsmål eller starter en diskussion over email.';
$Definition['Send Again'] = 'Send igen';
$Definition['Send a Test Email'] = 'Send en test-e-mail';
$Definition['Send Invitations!'] = 'Send invitationer!';
$Definition['Send users a welcome email.'] = 'Sender brugerne en velkomst email.';
$Definition['Sent To'] = 'Sendt til';
$Definition['SignedOut'] = 'Du er logget ud.';
$Definition['Sign In Url'] = 'Log ind url';
$Definition['Site Description'] = 'Side beskrivelse';
$Definition['Site Name'] = 'Side navn';
$Definition['SMTP Host'] = 'SMTP udbyder';
$Definition['SMTP Password'] = 'SMTP Kodeord';
$Definition['SMTP Security'] = 'SMTP Sikkerhed';
$Definition['SMTP User'] = 'SMTP Bruger';
$Definition['Start Discussions'] = 'Start diskussion';
$Definition['Statistics'] = 'statistik';

$Definition['Temporary (302)'] = 'Midlertidig (302)';
$Definition['Test Email'] = 'Test-e-mail';
$Definition['Test email from %s'] = 'Test e-mail fra %s';
$Definition['Test Email Message'] = '<p>Dette er en e-mail-testbesked.</p>

<p>Du kan konfigurere udseendet på dit forums e-mails ved at navigere til e-mail-siden i instrumentbrættet.</p>';
$Definition['Test Mode'] = 'Test Mode: The pocket will only be displayed for pocket administrators.';
$Definition['Text Color'] = 'Tekstfarve';
$Definition['TextEnterEmails'] = 'Type email addresses separated by commas here';
$Definition['The client ID uniqely identifies the site.'] = 'The client ID uniqely identifies the site. You can generate a new ID with the button at the bottom of this page.';
$Definition['The content you were looking for has been deleted.'] = 'Indholdet du leder efter, er blevet slettet.';
$Definition['The email has been sent.'] = 'E-mailen er sendt.';
$Definition['The homepage title is displayed on your home page.'] = 'Hjemmeside titlen vises på din hjemmeside. Vælg en titel som du vil se på søgemaskiner.';
$Definition['The homepage was saved successfully.'] = 'Hjemmesiden blev gemt med success!';
$Definition['Theme Options'] = 'Tema opsætning';
$Definition['Themes'] = 'Temaer';
$Definition['Theming Overview'] = 'Tema overblik';
$Definition['There\'s been an error uploading the image. Your email logo can uploaded in one of the following filetypes: gif, jpg, png'] = 'Der er sket en fejl ved upload af billedet. Dit e-mail-logo kan uploades i et af følgende filformater: gif, jpg, png';
$Definition['There are currently no applicants.'] = 'Der er ikke nogle ans¯gninger.';
$Definition['The secret secures the sign in process.'] = 'The secret secures the sign in process. Do <b>NOT</b> give the secret out to anyone.';
$Definition['The site description usually appears in search engines.'] = 'The site description usually appears in search engines. You should try having a description that is 100–150 characters long.';
$Definition['This pocket is an ad.'] = 'Denne lomme er en reklame.';
$Definition['This theme has additional options.'] = 'This theme has additional options on the %s page.';
$Definition['This theme has customizable text.'] = 'This theme has text that you can customize.';
$Definition['Thumbnails'] = 'Miniaturer';

$Definition['Universal Forum Embed Code'] = 'Universel forum-indlejringskode';
$Definition['Unlimited'] = 'UbegrÊnset';
$Definition['Upload New Email Logo'] = 'Upload nyt e-mail-logo';
$Definition['Use asterisks for wildcards'] = 'Brug asterikser til wildcards, f.eks. &lsquo;*@hotmail.com&rsquo;';
$Definition['User Count'] = 'Brugere';
$Definition['UserDelete'] = 'Remove User Content';
$Definition['UserDeleteMessage'] = 'Delete the user and completely remove all of the user\'s content. This may cause discussions to be disjointed. Best option for removing spam.';
$Definition['UserDeletionPrompt'] = 'Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).';
$Definition['UserKeep'] = 'Behold brugerindhold';
$Definition['UserKeepMessage'] = 'Delete the user but keep the user\'s content.';
$Definition['User Registration Settings'] = 'Bruger Registreringsindstillinger';
$Definition['Users with the no ads permission will not see this pocket.'] = 'Brugere med ingen reklamer-tilladelsen vil ikke se denne lomme.';
$Definition['UserWipe'] = 'Blank User Content';
$Definition['UserWipeMessage'] = 'Delete the user and replace all of the user\'s content with a message stating the user has been deleted. This gives a visual cue that there is missing information.';
$Definition['Use the content at this url as your homepage.'] = 'Choose the page people should see when they visit: <strong style="white-space: nowrap;">%s</strong>';

$Definition['Vanilla.Archive.Description'] = 'Du kan vÊlge at  arkivere forum diskussioner  Êldre end en bestemt  dato. Arkiverede diskussioner er  effektivt lukket, sÂ ingen nye indlÊg bliver skrevet.';
$Definition['Vanilla.Categories.MaxDisplayDepth'] = 'Place nested categories in a comma-delimited list when they are %1$s';

$Definition['Warning: deleting is permanent'] = 'WARNING: deleted items are removed from this list and cannot be brought back.';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'Vi vil fors¯ge at bruge den lokale mail-server til at sende e-mails som standard. Hvis du ¯nsker  at bruge en separat SMTP mail-server, kan du konfigurere den nedenfor.';
$Definition['Why do you want to join?'] = 'Hvorfor vil du gerne deltage?';
$Definition['Within'] = 'Inden';

$Definition['You can also ban the users that posted the spam and delete all of their posts.'] = 'Check the box next to the user that posted the spam to also ban them and delete all of their posts. <b>Only do this if you are sure these are spammers.</b>';
$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'Hvis du  nogensinde er lÂst ude  af dit forum, kan du altid  logge ind med din oprindelige  Vanilla e-mail og adgangskode  pÂ <a href="%1$s">%1$s</a>';
$Definition['You can make the categories page your homepage.'] = 'You can make your categories page your homepage <a href="%s">here</a>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'Du kan ikke  deaktivere %1$s plugin fordi %2$s plugin er n¯dvÊndigt for at virke.';
$Definition['You can send emails in plain text by disabling the toggle below.'] = 'Du kan sende e-mails med almindelig tekst ved at deaktivere vælgeren forneden.';
$Definition['Your default locale won\'t display properly'] = 'Your default locale won\'t display properly until it is enabled below. Please enable the following: %s.';
