<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Advarsel: Aktivering af denne funktion kan forårsage Javascript-fejl på dit websted.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Pas på!</strong> Sletning af en rolle kan resultere i brugere ikke har adgang til programmet.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Pas på!</strong> Flytning af diskussioner ind i en erstatningskategori kan resultere i diskussioner forsvinder (eller vises), hvis erstatningskategorien har andre tilladelser end den kategori som slettes.';

$Definition['About.DisableStatistics'] = 'Hvis du skal deaktivere denne indberetning af forretningsmæssige årsager, kan du gøre det ved at føje følgende linje til din installations konfigurationsfil: <code>$Configuration [\'Garden\'] [\'Analytics\'] [\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Det er yderst vigtigt for dette gratis, open source program, at vi præcist kan måle rækkevidden og effektiviteten af Vanilla. Vi beder dig venligst om at ikke deaktivere indberetning af disse data.';
$Definition['AboutCommentEmbedding'] = 'Vanille kan bruges som en erstatning for din blogs indbyggede kommentarsystem. Faktisk kan det bruges til at føje kommentarer til enhver side på internettet.';
$Definition['AboutEmbedding'] = 'Indlejring tillader hele eller en del af dit fællesskab at være integreret i andre programmer og websider.';
$Definition['About Vanilla Statistics'] = 'Om Vanilla statistik';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Få adgang til dit fællesskab ved at klikke "Vis side" linket i toppen af denne side, eller ved at <a href={/,url}>klikke her</a>. Fællesskabforummet er det som alle brugere og kunder vil se når de besøger <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Tilføj begrænsninger for dimensioner for billedopload i diskussioner og kommentarer.';
$Definition['AddonProblems'] = '<h2>Problemer?</h2><p>Hvis noget går galt med en tilføjelse og du kan ikke bruge dit websted, kan du deaktivere den manuelt ved at redigere:</p> %s';
$Definition['AddressBarColorDescription'] = 'Nogle browsere understøtter en farve til adresselinjen. Kun mobil.';
$Definition['Alert users if they click external link.'] = 'Advar brugere, hvis de klikker på et link i et indlæg, der fører dem væk fra forummet. Brugere vil ikke blive advaret, når de følger links, der matcher et betroet domæne';
$Definition['Alignment'] = 'Justering';
$Definition['Alignment (Mobile)'] = 'Justering (mobil)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Alle kategorierne vises med et udvalg af de fem seneste diskussioner under hver';
$Definition['Allow links to be transformed'] = 'Tillad, at links omdannes til indlejrede repræsentationer i diskussioner og kommentarer. For eksempel transformerer et YouTube-link til en indlejret video.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Tillad brugere med %s tilladelse til at ændre deres egne avatarer fra deres profilsider i Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Anonymiser IP-adresser';
$Definition['ApplicationHelp'] = 'Applikationer giver dig mulighed for at lave store grupper af funktionalitet til din site.<br />Når en applikation er blevet tilføjet til din %s mappe, kan du aktivere eller deaktivere den her.';
$Definition['Apply Layout'] = 'Anvend Layout';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Er du sikker på, at du vil slette dette tema? Det vil blive slettet permanent.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Er du sikker på du har indtastet det korrekte database værtsnavn? Måske du har skrevet det forkert? Databasen rapporterede: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'En rolle med standardtype "ubekræftet" er påkrævet for at bruge e-mail-bekræftelse.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Gem automatisk udkast til upublicerede diskussioner, spørgsmål, ideer og kommentarer.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatarer skaleres ned, hvis de overskrider denne højde.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatarer skaleres ned, hvis de overskrider denne bredde.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatarer gemmer deres miniaturebilleder i denne størrelse.';

$Definition['Background'] = 'Baggrund';
$Definition['Background Image'] = 'Baggrundsbillede';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Vær kreativ! Prøv at navngive dine rækker efter ting, som samfundet taler om.';
$Definition['Bordered'] = 'omkranset';
$Definition['Bordered (Unified)'] = 'Kantet (forenet)';
$Definition['Borderless'] = 'Uden ramme';
$Definition['Border Radius'] = 'Grænseradius';
$Definition['Brand Color'] = 'Mærkefarve';
$Definition['Buttons'] = 'Knapper';
$Definition['Buttons & Inputs'] = 'Knapper & indgange';
$Definition['Button Type'] = 'Knap Type';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Ved at klikke på knappen nedenfor, sletter du brugerkontoen for %s for evigt.';

$Definition['Center Aligned'] = 'Centerjusteret';
$Definition['Changes to the set day will take affect the following week.'] = 'Ændringer af den indstillede dag træder i kraft den følgende uge.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Ændringer gælder kun for nyligt uploadede avatarer.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Skift størrelser, som avatarbilleder gemmes på.';
$Definition['Change the way your community works with plugins.'] = 'Ændre måden dit fællesskab fungerer med tilføjelser. Vi har inkluderet populære tilføjelser med softwaren, og der findes flere online.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Afkrydsningsfelter tillader administratorer at udføre batchhandlinger på et antal diskussioner eller kommentarer på samme tid.';
$Definition['Check out our %s'] = 'Tjek vores %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Tjek vores <0>dokumentation</0> , eller spørg vores <1>fællesskab af eksperter</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla er den enkleste og kraftigste fællesskabsplatform i verden. Det er super nemt at bruge. Start med introduktionsvideoen og fortsæt med trinene nedenfor. Nyd det!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Vælg en rolle som forældreløse brugere bliver tildelt:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Vælg et tema for dette underfællesskab. <0> Læs mere </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Vælg hvordan indholdet (kommentarer, beskeder, etc.) for brugerkonto %s skal håndteres.';
$Definition['Choose Image'] = 'Vælg billede';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Du kan vælge en tilpasset hash algoritme til at underskrive dine anmodninger. Hash algoritmen skal også bruges i dit klientbibliotek. Vælg md5 hvis du ikke ved hvad du skal vælge.';
$Definition['Choose the order items are sorted.'] = 'Vælg ordren varer er sorteret.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Vælg den side, folk skal se, når de besøger <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Vælg det foretrukne layout til lister over kategorier.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Vælg det foretrukne layout til lister over kategorier. Du kan redigere fliselayoutet.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Vælg det foretrukne layout til lister med diskussioner.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Vælg det foretrukne layout til lister over diskussioner. Du kan redigere Foundation Layout.';
$Definition['Color Overlay'] = 'Farveoverlay';
$Definition['Continue Import'] = 'Fortsæt import';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Kunne ikke forstå import filen. Problemet er nær linje %s.';
$Definition['Create a localization CSV'] = 'Opret en oversættelses CSV fil';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Tilpassede temaer er de temaer, du har oprettet. Du kan redigere, omdøbe eller oprette en kopi af dem.';

$Definition['Dark'] = 'Mørk';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Angiv hvem der kan uploade og administrere filer på <a href="%s">Roller og tilladelser</a> siden.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Beskriv dit forums hjemmeside, upload et logo og mere....';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Når du sletter en rolle kan du risikere at brugere mister adgang til programmet.';
$Definition['Deleting forever cannot be undone.'] = 'At slette er en god måde at holde dit forum rent på.';
$Definition['Disable Google Sign In'] = 'Deaktiver Google login';
$Definition['Disable OpenID'] = 'Deaktiver OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Deaktiver "New Embed System"-laben på <0>Vanilla Labs-siden</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Diskussionskategorier bruges til at hjælpe dine brugere med at organisere deres diskussioner på en meningfuld måde for dit fællesskab.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Indlejr ikke dit forum instrumentpanel (vis det i fuld skærm)';
$Definition['Don\'t use too many reactions.'] = 'Brug ikke for mange reaktioner. Du ønsker ikke at give dine brugere information overbelastning.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Træk og slip kategorierne nedenfor for at sortere og indlejre dem.';

$Definition['EditContentTimeout.Notes'] = 'Hvis en bruger har en rolle der giver tilladelse til at redigere indhold, så vil den tilladelse bestemme over denne tilladelse her.';
$Definition['Edit Route'] = 'Redigér rute';
$Definition['Edits to this theme apply to:'] = 'Redigeringer til dette tema gælder for:';
$Definition['Email digests will be sent on the selected day every week.'] = 'E-mail-sammendrag vil blive sendt på den valgte dag hver uge.';
$Definition['Email sent from the application will be addressed from this email address'] = 'E-mail sendt fra applikationen vil blive adresseret fra denne e-mailadresse';
$Definition['Email sent from the application will be addressed from this name'] = 'E-mail sendt fra applikationen vil blive adresseret fra dette navn';
$Definition['Email Settings'] = 'E-mail-indstillinger';
$Definition['Embed Settings'] = 'Integrer indstillinger';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Indlejr dit fællesskabsforum på din webside for at forøge engagementet...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Aktiver og afprøv de nyeste Vanilla -funktioner.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Aktiver avanceret redigering af indlæg i flere formater, herunder WYSIWYG, enkel HTML, Markdown og BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Aktiver Layout Editor for at anvende et brugerdefineret layout til dine fællesskabssider. Brug vores nye editor til at vise indhold ved hjælp af vores katalog over tilgængelige widgets.';
$Definition['Enter a descriptive name.'] = 'Indtast et beskrivende navn for lommen. Dette navn bliver kun vist når du administrerer dine lommer, så det bruges kun til at huske lommens funktion.';
$Definition['Enter a short name for the site.'] = 'Angiv et kort navn for siden. Dette vises på login knapperne.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Indtast adressen på din WordPress blog og vi klarer resten.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Indtast forbindelsesoplysningene for din Sphinx server nedenunder.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Hver eneste redigering og sletning bliver registreret her.  Brug ‘Genskab’ for at fjerne ændringer.';
$Definition['Everyone who signs up gets a profile page.'] = 'Alle der registrerer sig i fællesskabet får en offentlig profilside hvor de kan uploade et billede af dem selv, rette deres profilindstillinger, og finde spændende ting der foregår i fællesskabet. Du bør <a href="{/profile,url}">rette din profil nu</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Hver bruger i dit forum har mindst en rolle. Roller bruges til at bestemme hvad brugeren har tilladelse til at gøre.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect giver brugerne mulighed for at logge ind med deres Facebook konto. <b>Du skal oprette din ansøgning med Facebook for denne tilføjelse virker.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Der opstod en fejl under forbindelse til databasen. Har du indtastet brugernavn og adgangskode korrekt? Databasen svarede: <code>%s</code>';
$Definition['Font'] = 'Skrifttype';
$Definition['Font Name'] = 'Skriftnavn';
$Definition['Font URL'] = 'Font-URL';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Tving instrumentbrættet til at kun være tilgængeligt gennem denne URL <em>(ikke anbefalet)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'For eksempel kan du forbyde alle brugere med e-mail-adresser fra "eksempel.com" ved at tilføje et forbud af e-mail-typen med værdien "*@eksempel.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Af SEO hensyn, er søgemaskinerner udelukket fra at blive tvunget til at se forummet igennem den angivne fjerne URL.';
$Definition['Foundation Layout'] = 'Fundament Layout';
$Definition['Full Anonymization'] = 'Fuld anonymisering';
$Definition['FullAnonymization.Description'] = '<strong>Fuld anonymisering</strong> erstatter hver enkelt IP-adresse med 0.0.0.0, hvilket effektivt nægter applikationen adgang til at arbejde med IP-adresser. IP-forbudsregler virker slet ikke i dette tilfælde.';
$Definition['Full Bleed'] = 'Fuld blødning';

$Definition['Garden.Import.Complete.Description'] = 'Importen lykkedes.
Klik <b>Færdig</b> når du er klar.';
$Definition['Garden.Import.Continue.Description'] = 'Det ser ud som om du er midt i en import. Vælg en af følgende muligheder.';
$Definition['Garden.Import.InputInstructions'] = 'Indtast mail adresse og adgangskode for administratoren fra de data som bliver importeret.';
$Definition['Garden.Privacy.IPs.Description'] = 'Brugernes IP-adresser indsamles typisk med henblik på automatiserede forbudsregler, moderering og spamforebyggelse. Aktivering af IP-anonymisering vil anonymisere alle IP-adresser, der spores på webstedet til ethvert formål, og vil reducere effektiviteten af disse værktøjer. Ændringer af denne indstilling har ikke tilbagevirkende kraft.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Have.Profiler. Rediger tilladelse til at ændre deres egne avatarer fra deres profilsider i Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Du har direkte deaktiveret Vanilla statistik i din konfigurationsfil.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Dette forum ser ud til at køre i et testmiljø eller rapporterer af en eller anden grund en privat IP adresse.  Som standard bliver der ikke lavet statistik for fora der kører på private IP adresse.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Hvis du er sikker på, at dit forum er tilgængeligt på Internettet, så kan du tvinge det til at rapportere statistik her.';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Din config.php fil ser ud til at være læsbar men ikke skrivbar. Dette betyder, at Vanilla ikke automatisk kan registrere dit forums installations ID og installations nøgle.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Du løser dette problem ved at sætte din conf/config.php fils rettigheder til 777.';
$Definition['Global Styles'] = 'Globale stilarter';

$Definition['Heads Up!'] = 'Bemærk!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Bemærk! Dette er en speciel rolle som ikke tillader interaktive sessioner.  Derfor er tilladelserne blevet begrænset til "læs" tilladelse.';
$Definition['Here are all of the reactions you can use on your site.'] = 'Her er alle de reaktioner, du kan bruge på dit websted.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Her er de rækker, som brugerne kan opnå på dit websted. Du kan tilpasse disse rækker og endda tilføje nye. Her er nogle tip.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Hvis et banner logo uploades, vil det erstatte banner titlen på forum sider som brugerne ser.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Hvis en bruger ikke besøger webstedet inden for denne tidsperiode, bliver vedkommende automatisk logget ud.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Hvis det er aktiveret, vil det fulde indhold af poster blive sendt i e-mail-meddelelser til brugerne.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Hvis du er ny med HTML og / eller CSS, her er nogle tutorials, der kommer i gang:';
$Definition['If you have an old theme'] = 'Hvis du har et gammelt tema og har brug for at indstille et separat desktop- og mobiltema, kan du gøre det med det gamle tema-UI.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Hvis du ønsker at sænke advarselsniveauet og så fjerne en advarsel.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Hvis du vil integrere dit forum eller bruge Vanilas kommentarer i din blog, skal du aktivere indlejring. Hvis du ikke bruger indlejring, anbefaler vi, at denne indstilling er slået fra.';
$Definition['Image (Mobile)'] = 'Billede (mobil)';
$Definition['Import'] = 'Importer';
$Definition['Importing to Vanilla'] = 'Importerer til Vanilla';
$Definition['In additon to the widgets there are also'] = 'Som supplement til widgets er der også <0> Global Styles </0> . Klik på et andet sted på siden for at redigere globale stilarter, f.eks. Denne tekst.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integrer grundsider og komponenter i dit tema';
$Definition['Internationalization & Localization'] = 'Internationalisering og Lokalisering';
$Definition['Invalid URL'] = 'ugyldig URL';
$Definition['Invitation email failed to send: %'] = 'Selvom invitationen blev oprettet med succes, kunne e-mailen ikke sendes. Serveren rapporterede følgende fejl: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Når nye brugere skal inviteres for at registrere sig, så vil de have et link kaldet <a href="%s" class="Popup">Mine invitationer</a> i deres profil.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Det ser ud til at den database du angiv ikke eksisterer endnu. Har du oprettet den? Har du tastet navnet forkert? Databasen svarede: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Det er en god idé, at begrænse det maksimalle antal tegn i en kommentar så den har en rimelig størrelse.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Det er en god ide at holde det maksimale antal tilladte tegn i et indlæg nede til en rimelig størrelse.';

$Definition['Kick-start your community and increase user engagement.'] = 'Spark dit fællesskab i gang og forøg brugernes engagement.';

$Definition['Learn about custom routing.'] = 'Lær om tilpassede ruter.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Lær hvordan du ændrer din sides udseende, uploader et logo, beskriver siden, vælger et tema og tilpasser det.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Lær hvordan du grundlæggende bruger dit forum.';
$Definition['Left Aligned'] = 'Venstrejusteret';
$Definition['Light'] = 'Lys';
$Definition['Locales allow you to support other languages on your site.'] = 'Sprogpakker tillader dig at bruge andre sprog på din side. Aktiver og deaktiver sprogpakker som du gerne vil gøre tilgængelige her.';
$Definition['Lockout Time (seconds)'] = 'Lockout-tid (sekunder)';
$Definition['LogoDescription'] = 'Banneret logo vises øverst på dit websted.';
$Definition['LogoDisclaimer'] = 'Temaer lavet med temaditoren og nogle tilpassede temaer bruger ikke denne indstilling.';
$Definition['Looking for the Old Embed System?'] = 'Leder du efter det gamle indlejringssystem?';

$Definition['Make sure you click View Page'] = 'Klik <a href="%s">Vis side</a> for at se hvordan dine kategorier ser ud efter at du har gemt.';
$Definition['Manage Routes'] = 'Administrer ruter';
$Definition['Managing Users'] = 'Håndtering af brugere';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Hvis du markerer noget som IKKE spam, så dukker det op i dit forum igen.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Hvis du markerer noget som ikke-spam, så dukker det op i dit forum igen.';
$Definition['Messages can appear anywhere in your application.'] = 'Beskeder kan ses overalt i forummet og kan bruges til at orientere dine brugere om nyheder og hændelser. Brug denne side til at organisere dine beskeder ved at trække dem op eller ned.';
$Definition['MobileLogoDescription'] = 'Det mobile bannerlogo vises øverst på dit websted.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Mobiltemaer giver dig mulighed for at ændre udseendet og følelsen af dit websted på mindre enheder.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Den nye Layout Editor vil arve det tema, der er sat i din Style Guide (formelt tema editor). <1>Få mere at vide</1>';
$Definition['Need More Help?'] = 'Behov for mere hjælp?';
$Definition['Need more help?'] = 'Brug for mere hjælp?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Indlejrede kategorier dybere end denne dybde placeres i en kommasepareret liste.';
$Definition['New Embed System'] = 'Nyt indlejringssystem';
$Definition['New Quick Links'] = 'Nye hurtige links';
$Definition['New Search Page'] = 'Ny søgeside';
$Definition['No Anonymization'] = 'Ingen anonymisering';
$Definition['Not getting what you expect when you preview your theme?'] = 'Får du ikke det, du forventer, når du forhåndsviser dit tema?';
$Definition['Notify me when people comment on my addons.'] = 'Orientér mig når folk skriver kommentarer om mine tilføjelser.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Webstedet har brug for en rolle med standardtype "ubekræftet" for at bruge e-mail-bekræftelse. Tilføj venligst en for at aktivere denne indstilling.';

$Definition['Old Theming UI'] = 'Gammel Theming UI';
$Definition['Once enabled, only members will see inside your community.'] = 'Når det er aktiveret, er det kun medlemmer, der kan ses i dit samfund.';
$Definition['OrgDescription'] = 'Dit organisationsnavn bruges til SEO-mikrodata og JSON + LD';
$Definition['Outline'] = 'Omrids';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Overordnede visninger eller temahooks kan have utilsigtede bivirkninger og er ikke vist.';

$Definition['Partial Anonymization'] = 'Delvis anonymisering';
$Definition['PartialAnonymization.Description'] = '<strong>Delvis anonymisering</strong> anonymiserer kun den sidste oktet af IP-adressen. For eksempel ville 254.230.05.153 blive 254.230.05.0. Dette giver en vis anonymisering, mens IP-forbudsreglerne stadig fungerer.';
$Definition['Password.MinLength'] = 'Minimum tegnlængde tilladt for brugere adgangskoder på adgangskode oprette og nulstille sider.';
$Definition['Please choose an authenticator to configure.'] = 'Vælg venligst en måde at tillade login på.';
$Definition['PluginHelp'] = 'Tilføjelser tillader dig at tilføje funktioner til dit forum.<br />Når en tilføjelse er blevet tilføjet til folderen %s, kan du aktivere og deaktivere det her.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Denne lomme vises mellem hvert indlæg i den primære liste af diskussioner. Eftersom diskussioner normal er omgivet af <li>..</li> kode, så bør du også omgive dine lommer med sådan kode.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Lommer tillader dig at tilføje vilkårlig HTML kode rundt omkring i forumet.';
$Definition['Preset'] = 'Forudindstillet';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Undgå spam i dit forum ved at begrænse antallet af indlæg og kommentarer som folk kan lave indenfor et givent tidsrum.';
$Definition['Primary Button'] = 'Primær knap';
$Definition['Primary Buttons'] = 'Primære knapper';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Nem vejledning i hvordan man laver temaer til Vanilla.';
$Definition['Quick Links is a default component on community pages.'] = 'Hurtige links er en standardkomponent på fællesskabssider. Aktiver vores nye Quick Links -komponent for at tilføje, redigere eller skjule links fra denne menu ved hjælp af vores temaditor.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Tilføjelse der gør det muligt at bruge Vanilla kommentarer med WordPress.';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Tilføjelse der gør det muligt at bruge Vanilla forum med WordPress.';
$Definition['Realtime progress bars: %s'] = 'Live statusmåler: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Det er en god ide at have særlige rækker for moderatorer og administratorer, så dit samfund nemt kan se, hvem der har ansvaret.';
$Definition['Recommend starting with five ranks.'] = 'Du vil ikke have for mange rækker. Vi anbefaler at starte med fem. Du kan tilføje mere, hvis dit samfund er rigtig stort.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Fjern diskussions- og kategorilinks fra menuer. Indstil diskussions- og kategorirelaterede sider til at returnere ikke fundet side 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Kræver "Flag" reaktionstilladelse.';
$Definition['Requires “Negative” reaction permission.'] = 'Kræver "negativ" reaktionstilladelse.';
$Definition['Requires “Positive” reaction permission.'] = 'Kræver "positiv" reaktionstilladelse.';
$Definition['Restoring your selection removes the items from this list.'] = 'Når du gendanner, fjernes elementerne fra denne liste og lægges ind på siden igen';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Brug følgende valgmulighed til at slå citater til for Rich Editor. Dette vil kun gælde hvis standardformateringen er "Rich". ';
$Definition['Route Expression'] = 'Udtryk for ruter';
$Definition['Routes are used to redirect users.'] = 'Ruter bruges til at omdirigere brugere afhængigt af den URL der blev anmodt om.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Søg efter brugeres navn eller indtast navnet på en rolle for at se alle brugere med den rolle.';
$Definition['Secondary Button'] = 'Sekundær knap';
$Definition['Secondary Buttons'] = 'Sekundære knapper';
$Definition['Security.Hsts.HTTPSWarning'] = 'Advarsel: Aktiver kun denne funktion, hvis du er sikker på, at alle dine subdomæner er konfigureret for HTTPS med gyldige certifikater.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Når den er aktiveret, gælder denne regel også for alle din sides subdomæner.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Vi anbefaler at du starter med en maks. alder på 1 uge og derefter øger den til en 1 måned og derefter 1 år, når du kan se at din side fungerer som forventet.';
$Definition['Security.Hsts.SubmitWarning'] = 'Advarsel: Det er godt at understøtte HSTS forhåndsindlæsning som bedste praksis. Du skal dog indsende din side til hstspreload.org for at sikre at den bliver forhåndsindlæst uden problemer (dvs. for at få den fulde beskyttelse for den tiltænkte konfiguration).';
$Definition['See the documentation'] = 'Se dokumentationen';
$Definition['Select the default type for this role, if any.'] = 'Vælg standardtypen for denne rolle, hvis nogen.';
$Definition['Select the import source'] = 'Vælg kilden til import';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Kolonne "%s" kunne ikke de-serialiseres efter serialisering.';
$Definition['Session Timeout'] = 'Session timeout';
$Definition['Shadowed'] = 'Skygget';
$Definition['ShareImageDescription'] = 'Når nogen deler et link fra dit websted, prøver vi at få et billede fra siden. Hvis der ikke er et billede på siden, bruger vi dette billede i stedet. Billedet skal være mindst 50 × 50, men vi anbefaler 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Aktiver denne indstilling for at vise alle mulige placeringer af lommer. Hvis denne indstilling aktiveres, så vises placeringerne kun for brugere der kan administrere lommer.';
$Definition['SignIn.LockoutTime'] = 'Den tid, en bruger er blokeret fra at logge ind efter at have overskredet antallet af loginforsøg.';
$Definition['Some browsers support a color for the address bar.'] = 'Nogle browsere understøtter en farve til adresselinjen.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Nogle ældre temaer understøtter ikke fuld redigeringsfunktion. For at se, hvad et tema understøtter, kan du holde markøren over dets navn for at se, hvor redigeringer træder i kraft.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Nogle temaer skal muligvis opdateres for at arbejde med følgende kategori. Du kan deaktivere funktionen, mens du opdaterer dit tema.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Nogle gange vil du indlejre dit Vanilla-websted på et andet websted. Vanillas indlejringssystem tilbyder en nem måde til det. Der er afvejninger i ydeevnen, når du bruger et indlejret websted, så tjek dokumentationen for alternativer og ideelle brugssager.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Særlig begrænsning: Kun brugere med tilladelse Garden.Curation.Manage må bruge denne reaktion.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Angiv et delvist eller fuldt match, når du opretter et forbud.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Brug gerne lidt tid på at overveje hvordan du beskriver din side her. En meningfuld titel og en kortfattet beskrivelse kan måske hjælpe din placering i forskellige søgemaskiner.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Gør dine mails mere spændende ved at tilføje et logo og tilpasse farverne.';
$Definition['Start Import'] = 'Start import';
$Definition['Start the first discussion.'] = 'Læg grunden til dit fællesskab ved at <a href="{/post/discussion,url}">starte den første diskussion</a> nu.';
$Definition['Subcommunities'] = 'Underfællesskaber';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Tagging giver brugerne mulighed for at tilføje et mærke til diskussioner, de starter for at gøre dem mere synlige.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Skabeloner er standardtemaer. For at tilpasse dem skal du oprette en kopi.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Godkendelsesmetode %s har ikke nogle brugerdefinerede konfigurationsmuligheder.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB <0/> lab skal konfigureres til at matche dit tilpassede tema. Dette kan gøres ved hjælp af vores nye temaredigerer. <1> Få mere at vide.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Tilføjelsen kunne ikke aktiveres fordi den rapporterede en fejl:<pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Denne tilføjelse er allerede blevet hentet.';
$Definition['The banner logo appears at the top of your forum.'] = 'Banner logoet vises i toppen af dit forum.';
$Definition['The banner title appears on the top-left of every page.'] = 'Bannertitlen vises i øverste venstre hjørne på alle sider.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Bannertitlen vises i din sides banner og i din browsers titelbjælke. Den bør være mindre end 20 tegn. Hvis du uploader et banner logo, vil det erstatte bannertitlen på de sider som brugerne ser. Husk også at temaer kan skjule denne titel.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Den grundlæggende registreringsformular kræver</strong> at nye brugere kopierer tekst fra et CAPTCHA-billede for at holde spammere væk fra siden. Du skal have en konto på <a href="http://recaptcha.net/">recaptcha.net</a>. Registrering er GRATIS og nemt. Kom tilbage hertil når du har registreret dig og angiv så følgende værdier: ';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Databasebrugeren som du angav har ikke tilladelse til at tilgå databasen. Har du oprettet databasen? Databasen svarede: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Følgende strukturelle ændringer kræves i din database.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Hjemmesidens titel vises på din hjemmeside. Vælg en titel som du gerne vil se dukke op i søgemaskiner.';
$Definition['The import file does not contain any data.'] = 'Filen der importeres indeholder ikke nogle data.';
$Definition['The import file is not in the correct format.'] = 'Filen der importeres har ikke det rigtige format.';
$Definition['The location of the authentication endpoint.'] = 'Placeringen af godkendelsesslutpunktet.';
$Definition['ThemeHelp'] = 'Temaer tillader dig at ændre udseendet og oplevelsen af din side.<br />Når et tema er blevet tilføjet til mappen %s, så kan du aktivere det her.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Temaeksempel er begrænset til at vise temas skabelon og css.';
$Definition['Theming Guide'] = 'Temaguide';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Mobillogoet vises øverst på dit websted. Temaer lavet med temaeditoren og nogle brugerdefinerede temaer bruger ikke denne indstilling.';
$Definition['The New Embed System'] = 'Det nye indlejringssystem';
$Definition['The new embed system has improved performance.'] = 'Det nye indlejringssystem har forbedret ydeevne, forbedret rulleadfærd og mere ensartet adfærd end det gamle. I øjeblikket understøttes kommentar- og wordpress-indlejringer ikke i det nye indlejringssystem.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Adgangskodevalidatoren har ikke nogle tilpassede indstillinger.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Der er ingen strukturelle ændringer af databasen.  Der kan dog være ændringer til data i den.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Der er to typer knapper i applikationen: primær og sekundær.';
$Definition['The route was saved successfully.'] = 'Ruten blev gemt uden fejl.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Webstedets beskrivelse vises normalt i søgemaskiner. Du bør prøve at have en beskrivelse på 100-150 tegn.';
$Definition['The text of the pocket.'] = 'Indtast lommens tekst. Dette bliver vist præcist som du indtaster det, så vær sikker på, at du bruger gyldigt HTML.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Berøringsikonet vises, når du bogmærker et websted på startskærmen på en mobilenhed. Disse er normalt 152 pixels.';
$Definition['The user table was not in the import file.'] = 'Tabellen over brugere var ikke i den importerede fil.';
$Definition['The Vanilla 2 Exporter'] = 'Vanilla 2 eksporteringsfunktionen';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla Statistik omdanner dit forums instrumentbræt til et analytisk rapporteringsværktøj som tillader dig at gennemse aktivitet i dit forum i angivne tidsrum. Du kan <a href="http://vanillaforums.org/docs/vanillastatistics"> læse mere om Vanilla Statistik i vores engelske dokumentation.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'De fungerer ligesom almindelige temaer. Når en er blevet føjet til temamappen, kan du aktivere den her.';
$Definition['This is a style guide of your theme.'] = 'Dette er en stilguide til dit tema. Det har eksempler på de visuelle elementer, der bruges i hele applikationen. Du kan klikke på de forskellige widgets, f.eks. <0> Titellinje </0> eller <1> Banner </1> for at redigere deres egenskaber i sidepanelet.';
$Definition['This is the administrative dashboard for your new community.'] = 'Dette er det administrative instrumentbræt for dit nye fællesskab. Tjek konfigurationsmulighederne ude i siden. Derfra kan du konfigurere hvordan dit fællesskab fungerer. <b>Som standard er det kun brugere med "Administrator" rollen der kan se denne del af dit fællesskab.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Det er her, du kan aktivere og afprøve nye Vanilla -funktioner, sider og komponenter.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Denne prøvefunktion kan ikke deaktiveres, fordi der er anvendt et tilpasset layout.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Dette laboratorium kan ikke deaktiveres, fordi det er påkrævet af det aktuelle tema.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Dette logo vises øverst på dit websted. Temaer lavet med temaeditoren og nogle brugerdefinerede temaer bruger ikke denne indstilling.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Dette kan bruges til at inkludere indhold såsom organisationens navn og adresse i alle udgående e-mails.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Denne indstilling viser/skjuler de placeringer som lommer kan være i men kun for brugere der har rettigheder til at tilføje/rette lommer. Prøv at vise placeringerne og besøg så din webside.';
$Definition['This page lists the endpoints of your API.'] = 'Denne side viser slutpunkterne på din API. Klik på slutpunkter for at få flere oplysninger. Du kan foretage liveopkald til API\'en fra denne side eller eksternt ved hjælp af et adgangstoken.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Denne rolle er personlig info. Kun brugere med tilladelse til at se personlige oplysninger vil se dem.';
$Definition['This setting loads the page before executing Javascript.'] = 'Denne indstilling indlæser siden, før der køres et Javascript, hvilket kan forbedre din søgemaskineoptimering.<br><strong>**Advarsel: Aktivering af denne funktion kan forårsage Javascript-fejl på din side.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Denne indstilling indlæser siden, før Javascript udføres, hvilket kan forbedre din SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Dette tema kan ikke slettes, fordi det er det aktuelt anvendte tema.';
$Definition['Tiled Layout'] = 'Flisebelagt layout';
$Definition['Title Bar'] = 'Titellinje';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'For at indlejre dit Vanilla forum i din webside, skal du bruge følgende kode.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'For mange adresser! Vi sender maksimalt til %s adresser på en gang.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'For at undgå misbrug, skjuler nogle værktøjer automatisk indhold og viser det her indtil det det er manuelt godkendt af en moderator.';
$Definition['TouchIconDescription'] = 'Berøringsikonet vises, når du bogmærker et websted på hjemmeskærmen på en Apple-enhed. Disse er normalt 152 pixels. Apple tilføjer automatisk afrundede hjørner og lyseffekt.';
$Definition['Transparent'] = 'Gennemsigtig';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect giver brugere adgang til at logge ind med deres Twitter konto. <b>Du skal oprette din ansøgning med Twitter for denne tilføjelse virker.</b>';

$Definition['Usercards'] = 'Brugerkort';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Brugerkort giver dig mulighed for at få et hurtigt in-line snapshot af en brugers oplysninger. Når du ser indlæg og ranglister, skal du klikke på brugernavnet for at se et kort, der viser brugernes grundlæggende profilinformation uden at skulle navigere væk fra siden. Aktiver denne funktion for at tilføje brugerkort til dit tilpassede tema.';
$Definition['User inputs are based on the global background and text colors.'] = 'Brugerindgange er baseret på den globale baggrund og tekstfarver.';
$Definition['User Profile'] = 'Brugerprofil';
$Definition['Users may sign into your site using their Twitter account.'] = 'Brugere kan logge ind på dit websted ved hjælp af deres Twitter-konto.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Brug knappen øverst på siden for at oprette en forbudsregel.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Brug WordPress tilføjelsen til at bruge Vanilla kommentarer i din blog, eller brug den universelle kode for at sætte Vanilla kommentarer op på en anden platform.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Vanillas nye søgetjeneste er endelig her. Aktiver vores nye søgeside -brugergrænseflade for at få adgang til de nyeste søgefunktioner, f.eks. Medlemssøgning, søgesortering og fremhævelse af udtryk.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Vanilla eksport: %s, kilde: %s';
$Definition['Vanilla Labs'] = 'Vanilje Labs';
$Definition['Vanilla Statistics are currently disabled'] = 'Vanilla Statistik er p.t. deaktiveret.';
$Definition['Verify and restore'] = 'Bekræft og gendan';
$Definition['VerifyUser'] = 'Marker feltet ud for brugeren for at markere dem som <b>verificerede,</b> så deres indlæg ikke bliver markeret som spam igen. Dette vil også gendanne alle deres ventende indlæg.';
$Definition['Video tutorial on advanced settings'] = 'Videovejledning om avancerede indstillinger';
$Definition['Video tutorial on finding &amp; managing users'] = 'Videovejledning om at finde og administrere brugere';
$Definition['Video tutorial on managing appearance'] = 'Videovejledning om at administrere udseende';
$Definition['Video tutorial on managing categories'] = 'Videovejledning om at administrere kategorier';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Videovejledning om at administrere roller og rettigheder';
$Definition['Video tutorial on user registration'] = 'Videovejledning om registrering af brugere';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Advarsel: Aktivering af denne funktion kan forårsage Javascript-fejl på dit websted.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Advarsel</b> : Din serverkonfiguration understøtter ikke hurtig dataindlæsning. Hvis du importerer en meget stor fil (f.eks. Over 200.000 kommentarer), kan du overveje at ændre din konfiguration. Klik <a href="http://vanillaforums.com/porter">her</a> for mere information.';
$Definition['Warning: This is for advanced users.'] = '<b>Advarsel</b>: Dette er for avancerede brugere og kræver at du laver yderligere ændringer til din web server. Dette er normalt kun en mulighed hvis du har en dedikeret eller VPS løsning. Forsøg ikke dette hvis du ikke ved hvad du gør.';
$Definition['Welcome to Labs!'] = 'Velkommen til Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Velkommen til Vanilla\'s tema UI. Denne side viser alle dine tilgængelige temaer og giver dig mulighed for at kopiere eller redigere dem.';
$Definition['Welcome To Your Theme'] = 'Velkommen til dit tema';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Vi anbefaler for det meste positive reaktioner for at tilskynde til deltagelse.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Når det er aktiveret, kan brugere vælge at modtage meddelelser fra fællesskabet';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Når det er aktiveret, kan du administrere produkter og gruppere underfællesskaber efter disse produkter.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Når nogen deler et link fra dit websted, prøver vi at få et billede fra siden. Hvis der ikke er et billede på siden, bruger vi dette billede i stedet. Billedet skal være mindst 50 × 50, men vi anbefaler 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Når du vælger Full blødning, er din baggrund gennemsigtig.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Hvorvidt de interne profilfelter vil blive inkluderet i denne webhook.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Hvorvidt de private profilfelter vil blive inkluderet i denne webhook.';
$Definition['Which reactions you use really depends on your community.'] = 'Hvilke reaktioner du bruger, afhænger virkelig af dit samfund, men vi anbefaler, at du tager et par punkter i tankerne.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Du er ved at anvende en ny layoutindstilling. Dette kan tilpasses og forhåndsvises ved hjælp af vores temaredigerer. <0> Få flere oplysninger</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Du kan forbyde alle brugere med en IP-adresse, der er præfixeret med "111.111.111" ved at tilføje et IP-forbud med værdien "111.111.111. *".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Du kan forbyde IP-adresser, e-mail-adresser og brugernavne.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Du kan vælge mellem en af de forskellige stilarter, som dette tema tilbyder.';
$Definition['You can configure some values differently for different screensizes.'] = 'Du kan konfigurere nogle værdier forskelligt for forskellige skærmbilleder.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Du kan forbinde til flere websteder som understøtter jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Hvis din fil er for stor til at uploade direkte på denne side, kan du placere den i mappen /uploads. Sørg for at filnavnet begynder med ordet <b>export</b> og slutter på en af <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Du kan angive en minimum postlængde for at afskrække korte indlæg.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Du kan uploade en brugerdefineret skrifttype i dit temasystem. Bare kopiér og indsæt URL\'en i feltet.';
$Definition['You must select a file to import.'] = 'Du skal vælge en fil at importere.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Du skal tilføje font url\'s domæne til <0> Tilladte domæner </0> i stedets konfiguration. <1>Lær mere om tilpassede skrifttyper.</1>';
$Definition['Your mobile theme will be disabled.'] = 'Dit mobiltema deaktiveres. Hvis du vil indstille forskellige mobil- og desktop-temaer, skal du bruge det gamle tema-UI.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Dit organisationsnavn bruges til SEO-mikrodata og JSON + LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Dit websteds favicon vises i din browsers titelbjælke. Det skaleres hensigtsmæssigt ned.';
