<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Uyarı: Bu özelliğin etkinleştirilmesi sitenizde Javascript hatalarına neden olabilir.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Dikkat!</strong> Bir rolü silmek, kullanıcıların uygulamaya erişememesine neden olabilir.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Dikkatli Ol!!</strong>Tartışmaları yedek kategoriye taşırken tartışmalar kaybolabilir (veya görünebilir ) eğer yedek kategoride farklı izinlere sahipse kategori silinebilir.';

$Definition['About.DisableStatistics'] = 'Bu veri raporlamasını bazı nedenlerden dolayı devre dışı bırakmanız gerekiyorsa, bunu kurulumunuzun yapılandırma dosyasına aşağıdaki satırı ekleyerek yapabilirsiniz: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Vanilya\'nın erişimini ve etkinliğini doğru bir şekilde ölçmemiz bu ücretsiz, açık kaynaklı yazılımın yaşamı için hayati derecede önemlidir. Lütfen bu verilerin raporlanmasını devre dışı bırakmamanızı rica ederiz.';
$Definition['AboutCommentEmbedding'] = 'Vanilya, blogunuzun yerel yorumlama sisteminin yerine geçme yerine kullanılabilir. Aslında, web\'deki herhangi bir sayfaya yorum eklemek için kullanılabilir.';
$Definition['AboutEmbedding'] = 'kod yerleştirme, topluluğunuzun tamamının veya bir kısmının diğer uygulamalara ve web sayfalarına gömülmesine izin verir.';
$Definition['About Vanilla Statistics'] = 'Vanilla İstatistikleri Hakkında';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Bu sayfanın en üstündeki "Siteyi Ziyaret Et" bağlantısını tıklayarak veya <a href={/,url}>buraya tıklayarak</a> topluluk forumunuza erişin. Topluluk forumu, tüm kullanıcılarınızın ne yaptığından ibarettir. müşteriler <a href="{/,url,domain}">{/,url,domain}</a> adresini ne zaman ziyaret ettiklerini göreceklerdir.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Konuşma ve yorumlardaki boyutlara resim yükleme limitleri koy.';
$Definition['AddonProblems'] = '<h2>Sorunlar?</h2><p>Bir eklentiyle ilgili bir şeyler ters giderse ve sitenizi kullanamıyorsanız, bunları düzenleyerek el ile devre dışı bırakabilirsiniz:</p>%s';
$Definition['AddressBarColorDescription'] = 'Bazı tarayıcılar adres çubuğu için bir rengi destekler. Yalnızca mobil.';
$Definition['Alert users if they click external link.'] = 'Kullanıcıları bir yayında, forumdan uzaklaştıracak bir bağlantıyı tıkladıklarında uyar. Güvenilir bir Alan Adı ile eşleşen bağlantıları izlerken kullanıcılar uyarılmayacak';
$Definition['Alignment'] = 'Hizalama';
$Definition['Alignment (Mobile)'] = 'Hizalama (Mobil)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Her kategoride son 5 tartışmadan oluşan seçkin kategoriler';
$Definition['Allow links to be transformed'] = 'Bağlantıların tartışmalarda ve yorumlarda gömülü temsillere dönüştürülmesine izin verin. Örneğin, bir YouTube bağlantısı gömülü bir videoya dönüşür.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = '%s kullanıcılarına kendi avatarlarını Vanilla profil sayfalarından değiştirme izni verin.';
$Definition['Anonymize IP Addresses'] = 'IP Adreslerini Anonimleştirin';
$Definition['ApplicationHelp'] = 'Uygulamalar sitenize geniş bir işlevsellik grubu eklemenize izin verir. <br />Bir uygulama %s klasörünüze eklendikten sonra, buradan etkinleştirebilir veya devre dışı bırakabilirsiniz.';
$Definition['Apply Layout'] = 'Düzeni Uygula';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Bu temayı silmek istediğinizden emin misiniz? Kalıcı olarak silinecek.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Doğru veritabanı adını girdiğinizden emin misiniz? Belki, yanlış girmiş olabilirsiniz. Veritabanı raporu: <code>%s</code> ';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'E-posta onayını kullanmak için varsayılan olarak "onaylanmadı" tipinde bir rol gereklidir.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Yayınlanmamış tartışmaların, soruların, fikirlerin ve yorumların taslaklarını otomatik olarak kaydedin.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatarlar bu yüksekliği aşarsa ölçeklendirilir.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatarlar bu genişliği aşarsa ölçeklendirilir.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatarların küçük resimleri bu boyutta kaydedilecektir.';

$Definition['Background'] = 'Arkaplan';
$Definition['Background Image'] = 'Arkaplan Görseli';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Yaratıcı ol! Sıralamanızı, topluluğun hakkında konuştuğu şeylerden sonra adlandırmayı deneyin.';
$Definition['Bordered'] = 'Sınırlı';
$Definition['Bordered (Unified)'] = 'Sınırlı (Birleşik)';
$Definition['Borderless'] = 'Sınırsız';
$Definition['Border Radius'] = 'Sınır Yarıçapı';
$Definition['Brand Color'] = 'Marka Renk';
$Definition['Buttons'] = 'Düğmeler';
$Definition['Buttons & Inputs'] = 'Düğmeler & Girişler';
$Definition['Button Type'] = 'Düğme Tipi';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Aşağıdaki butona basarak %s hesabını daimi olarak silmiş olacaksınız.';

$Definition['Center Aligned'] = 'Ortaya Hizala';
$Definition['Changes to the set day will take affect the following week.'] = 'Ayarlanan günde yapılan değişiklikler bir sonraki haftayı etkileyecektir.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Değişiklikler yalnızca yeni yüklenen avatarlar için geçerli olacaktır.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Avatar resimlerinin kaydedildiği boyutları değiştirin.';
$Definition['Change the way your community works with plugins.'] = 'Topluluğunuzun eklentilerle çalışma şeklini değiştirin. Yazılımla popüler eklentileri bir araya getirdik ve çevrimiçi olarak daha fazlası var.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Onay kutuları, yöneticilerin aynı anda birkaç tartışma veya yorum üzerinde toplu işlemler gerçekleştirmesine olanak tanır.';
$Definition['Check out our %s'] = '%s sayfamıza göz atın';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = '<0>belgelerimize göz atın</0> veya <1>uzmanlar topluluğumuza sorun</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilya, dünyadaki en basit, en güçlü topluluk platformudur. Super-duper kullanımı kolaydır. Bu tanıtım videosu ile başlayın ve aşağıdaki adımlarla devam edin. Keyfini çıkarın!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Lütfen sahipsiz hesaplar için bir rol (yetki seviyesi) seçin:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Alt topluluk için bir tema seçin. <0>Daha fazlasını oku</0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Kullanıcı hesabıyla ilişkili tüm içeriğin nasıl işleneceğini seçin. %s (yorumlar, mesajlar, vb.)';
$Definition['Choose Image'] = 'Görsel Seç';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'İsteklerinizi imzalamak için özel bir karma algoritma seçebilirsiniz. Karma algoritması, istemci kitaplığınızda da kullanılmalıdır. Ne seçeceğinizden emin değilseniz md5\'i seçin.';
$Definition['Choose the order items are sorted.'] = 'Öğelerin sıralanacağı sırayı seçin.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Kullanıcıların <0/> sayfasını ziyaret ettiklerinde görmeleri gereken sayfayı seçin';
$Definition['Choose the preferred layout for lists of categories.'] = 'Kategori listeleri için tercih edilen düzeni seçin.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Kategori listeleri için tercih edilen düzeni seçin. Döşenmiş Düzeni düzenleyebilirsiniz.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Tartışma listeleri için tercih edilen düzeni seçin.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Tartışma listeleri için tercih edilen düzeni seçin. Temel Düzenini düzenleyebilirsiniz.';
$Definition['Color Overlay'] = 'Renk Kaplama';
$Definition['Continue Import'] = 'İçe Aktarmaya Devam';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Alınan dosyada hata. %s satırını kontrol edin';
$Definition['Create a localization CSV'] = 'Dil CSV dosyası oluştur';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Özel Temalar, oluşturduğunuz temalardır. Bunları düzenleyebilir, yeniden adlandırabilir veya kopyalayabilirsiniz.';

$Definition['Dark'] = 'Koyu';
$Definition['Define who can upload files on the Roles & Permissions page.'] = '<a href="%s">Roller ve İzinler</a> sayfasında dosyaları kimlerin yükleyip yönetebileceğini tanımlayın.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Forum anasayfanızı belirleyin, logonuzu yükleyin ve daha fazlası...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Bir rolü silmek, kullanıcıların uygulamaya erişememesine neden olabilir.';
$Definition['Deleting forever cannot be undone.'] = 'Silme, forumunuzu temiz tutmak için iyi bir yoldur.';
$Definition['Digest Settings'] = 'Özet Ayarları';
$Definition['Disable Google Sign In'] = 'Google Sign In özelliğini devre dışı bırak';
$Definition['Disable OpenID'] = 'OpenID Devre Dışı Bırak';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = '<0>Vanilla Labs Sayfasında "New Embed System" laboratuvarını devre dışı bırakın</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Tartışma kategorileri, kullanıcılarınızın tartışmalarını topluluğunuz için anlamlı bir şekilde düzenlemelerine yardımcı olmak için kullanılır.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Forum yönetici panosunu gömmeyin (tam ekran yapın)';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Sıralamak ve yer değiştirmek için aşağıdaki kategorileri sürükleyip bırakın.';

$Definition['EditContentTimeout.Notes'] = 'Bir kullanıcı içeriği düzenleme iznine sahip bir rolde ise, bu izinler bunu geçersiz kılar.';
$Definition['Edit Route'] = 'Rotayı değiştir';
$Definition['Edits to this theme apply to:'] = 'Bu temadaki düzenlemeler aşağıdakiler için geçerlidir:';
$Definition['Email digests will be sent on the selected day every week.'] = 'E-posta özetleri her hafta seçilen günde gönderilecektir.';
$Definition['Email sent from the application will be addressed from this email address'] = 'Uygulamadan gönderilen e-posta bu e-posta adresinden gönderilecek';
$Definition['Email sent from the application will be addressed from this name'] = 'Uygulamadan gönderilen e-posta bu isimle gönderilecek';
$Definition['Email Settings'] = 'e mail ayarları';
$Definition['Embed Settings'] = 'Gömme Ayarları';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Katılımı artırmak için Forum\'unuzu kendi sitenize gömebilirsiniz...';
$Definition['Enable and test out the latest Vanilla features.'] = 'En son Vanilla özelliklerini etkinleştirin ve test edin.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'WYSIWYG, basit HTML, Markdown ve BBCode dahil olmak üzere çeşitli formatlarda yayınların gelişmiş şekilde düzenlenmesini sağlar.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Topluluk sayfalarınız için özel bir düzen uygulamak üzere Düzen Düzenleyici\'yi etkinleştirin. Mevcut widget\'lardan oluşan kataloğumuzu kullanarak içeriği öne çıkarmak için yeni düzenleyicimizi kullanın.';
$Definition['Enter a descriptive name.'] = 'Cep için açıklayıcı bir ad girin. Bu ad, ceplerinizi burada yönetme dışında hiçbir yerde görünmez, bu nedenle yalnızca cebinizi hatırlamanıza yardımcı olmak için kullanılır.';
$Definition['Enter a short name for the site.'] = 'Site için kısa bir ad girin. Bu, oturum açma düğmelerinde görüntülenir.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Wordpress Blogunuzun adresini girin, biz de oradan alalım.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Sphinx sunucunuzun bağlantı ayarlarını aşağıya girin.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Her düzenleme veya silme buraya kaydedilir. Herhangi bir değişikliği geri almak için ‘Geri Yükle’ seçeneğini kullanın.';
$Definition['Everyone who signs up gets a profile page.'] = 'Topluluğunuz için kaydolan herkes, kendi resimlerini yükleyebilecekleri, profil ayarlarını yönetebilecekleri ve toplulukta olup bitenleri izleyebilecekleri bir genel profil sayfası alır. <a href="{/profile,url}">Profilinizi şimdi özelleştirmelisiniz</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Sitenizdeki her kullanıcı en az bir rol için atanır. Roller, kullanıcıların ne yapmasına izin verildiğini belirlemek için kullanılır.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect, kullanıcıların Facebook hesaplarını kullanarak giriş yapmalarını sağlar. <b>Bu eklentinin çalışması için başvurunuzu Facebook\'a kaydetmelisiniz.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Girdiğiniz kullanıcı adı ve şifre ile veritabanına bağlanılamadı. Onları yanlış mı yazdınız? Veritabanı raporu: <code>%s</code>';
$Definition['Font'] = 'Yazı Tipi';
$Definition['Font Name'] = 'Yazı Tipi Adı';
$Definition['Font URL'] = 'Yazı tipi URL\'si';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Gösterge tablosunu yalnızca bu URL\'den erişilebilir olmaya zorlayın <em>(önerilmez)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Örneğin, "*@örnek.com" değeriyle bir e-posta tipi engel ekleyerek, "örnek.com" adresinden e-postası olan tüm kullanıcıları yasaklayabilirsin.';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'SEO amacıyla, arama motoru tarayıcılarının uzak url\'deki forumu görüntülemeye zorlanması engellenmiştir.';
$Definition['Foundation Layout'] = 'Temel Düzeni';
$Definition['Full Anonymization'] = 'Tam Anonimleştirme';
$Definition['FullAnonymization.Description'] = '<strong>Tam Anonimleştirme,</strong> her bir IP adresini 0.0.0.0 ile değiştirir ve uygulamanın IP adresleriyle çalışmasına herhangi bir erişimi etkili bir şekilde reddeder. Bu durumda IP ban kuralları hiç işlemeyecektir.';
$Definition['Full Bleed'] = 'Tam Taşma';

$Definition['Garden.Import.Complete.Description'] = 'Bir içe aktarma işlemini başarıyla tamamladınız.
    Hazır olduğunuzda <b>Son\'u</b> tıklayın.';
$Definition['Garden.Import.Continue.Description'] = 'Bir içe aktarmanın ortasındaymışsınız gibi görünür. Lütfen aşağıdaki seçeneklerden birini seçin.';
$Definition['Garden.Import.InputInstructions'] = 'İçe aktarılan verilerden yönetici kullanıcısının e-posta adresini ve şifresini girin.';
$Definition['Garden.Privacy.IPs.Description'] = 'Kullanıcı IP adresleri genellikle otomatik yasaklama kuralları, denetleme ve spam önleme amacıyla toplanır. IP Anonimleştirmeyi etkinleştirmek, sitede herhangi bir amaçla takip edilen tüm IP adreslerini anonimleştirecek ve bu araçların etkinliğini azaltacaktır. Bu ayarda yapılan değişiklikler geriye dönük değildir.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Vanilla\'daki profil sayfalarından kendi avatarlarını değiştirme iznini düzenleyin.';
$Definition['Garden.StatisticsDisabled'] = 'Yapılandırma dosyanızda özellikle Vanilya İstatistikleri\'ni devre dışı bıraktınız.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Bu forum bir test ortamında çalışıyor gibi görünüyor veya başka bir şekilde özel bir IP bildiriyor. Varsayılan olarak, özel IP\'lerde çalışan forumlar izlenmez.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Forumunuza internetten erişilebildiğinden eminseniz, istatistikleri burada bildirmeye zorlayabilirsiniz:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Config.php dosyanız salt okunur görünüyor. Bu, Vanilla\'nın forumunuzun InstallationID ve InstallationSecret\'lerini otomatik olarak kaydedemeyeceği anlamına gelir.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Bu sorunu çözmek için, conf/config.php dosyasına 777 dosya iznini atayın.';
$Definition['Global Styles'] = 'Genel Stiller';

$Definition['Heads Up!'] = 'Dikkat Et!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Dikkat et! Bu, aktif oturumlara izin vermeyen özel bir roldür. Bu nedenle izin seçenekleri "görüntüleme" izinleriyle sınırlandırılmıştır.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'İşte kullanıcıların sitenizde elde edebileceği dereceler. Bu dereceleri özelleştirebilir ve hatta yenilerini ekleyebilirsiniz. İşte bazı ipuçları.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Bir başlık logosu yüklenirse, kullanıcının karşılaştığı forum sayfalarındaki başlığin yerini alır.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Bir kullanıcı bu süre içinde siteyi ziyaret etmezse, otomatik olarak oturumu kapatılacaktır.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Etkinleştirilirse, gönderilerin tüm içeriği kullanıcılara e-posta bildirimlerinde gönderilir.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'HTML ve/veya CSS konusunda yeniyseniz, başlamanıza yardımcı olacak bazı eğitimler:';
$Definition['If you have an old theme'] = 'Eski bir temanız varsa ve ayrı bir masaüstü ve mobil tema ayarlamanız gerekiyorsa bunu eski tema kullanıcı arayüzüyle yapabilirsiniz.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Uyarı seviyesini azaltmak istiyorsanız, bir uyarıyı kaldırın.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Forumunuza yerleştirmek veya blogunuzda Vanilla\'nın yorumlarını kullanmak istiyorsanız, yerleştirmeyi etkinleştirmeniz gerekir. Gömme kullanmıyorsanız, bu ayarı kapalı bırakmanızı öneririz.';
$Definition['Image (Mobile)'] = 'Görsel (Mobil)';
$Definition['Import'] = 'İçe Aktar';
$Definition['Importing to Vanilla'] = 'Vanilla\'ya içe aktarılıyor';
$Definition['In additon to the widgets there are also'] = 'Widget\'lara ek olarak <0>Genel Stiller</0> var. Genel stilleri düzenlemek için sayfada bu metin gibi başka herhangi bir yeri tıklayın.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Temel Sayfaları ve Bileşenleri Temanıza Entegre Edin';
$Definition['Internationalization & Localization'] = 'Uluslararasılaştırma & Yerelleştirme';
$Definition['Invalid URL'] = 'Geçersiz URL';
$Definition['Invitation email failed to send: %'] = 'Davetiye başarıyla oluşturulmuş olmasına rağmen, e-posta gönderilemedi. Sunucu aşağıdaki hatayı bildirdi: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Davetiyeyle kaydı kullandığınızda, kullanıcılar profil sayfalarında <a href="%s" class="Popup">Davetiyelerim</a> adlı bir bağlantıya sahip olacaklardır.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Belirttiğiniz veritabanı henüz mevcut değil gibi görünüyor. Yeni mi oluşturdun? Adını mı yanlış yazdın? Veritabanı raporu: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Bir yorumda izin verilen maksimum karakter sayısını makul bir boyuta indirmek iyi bir fikirdir.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Bir yayında izin verilen azami karakter sayısını makul bir boyuta tutmak iyi bir fikirdir.';

$Definition['Kick-start your community and increase user engagement.'] = 'Topluluğun için çalışmaya başla ve kullanıcı katılımını arttır.';

$Definition['Labs'] = 'Laboratuvarlar';
$Definition['Layout Editor'] = 'Düzen Düzenleyici';
$Definition['Learn about custom routing.'] = 'Özel yönlendirme hakkında bilgi edinin.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Forumunuzun görünüşünü ve hissini nasıl değiştireceğinizi öğrenin: logonuzu yükleyin, ana sayfanızı ayarlayın, bir tema seçin ve özelleştirin.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Forumunuzun temel işlevlerini nasıl kullanacağınızı öğrenin.';
$Definition['Left Aligned'] = 'Sola Hizala';
$Definition['Light'] = 'Açık';
$Definition['Links'] = 'Bağlantılar';
$Definition['Locales allow you to support other languages on your site.'] = 'Yerel ayarlar, sitenizdeki diğer dilleri desteklemenizi sağlar. Burada kullanılabilir yapmak istediğiniz yerel ayarları etkinleştirin ve devre dışı bırakın.';
$Definition['Lockout Time (seconds)'] = 'Kilitleme Süresi (saniye)';
$Definition['LogoDescription'] = 'Banner logosu sitenizin üstünde görünür.';
$Definition['LogoDisclaimer'] = 'Tema düzenleyici ile yapılan temalar ve bazı özel temalar bu ayarı kullanmaz.';
$Definition['Looking for the Old Embed System?'] = 'Eski Gömme Sistemini mi arıyorsunuz?';

$Definition['Make sure you click View Page'] = 'Kategoriler sayfanızın kaydettikten sonra nasıl göründüğünü görmek için <a href="%s">Sayfayı Görüntüle</a> seçeneğini tıkladığınızdan emin olun.';
$Definition['Manage Routes'] = 'Yönlendirmeleri Yönet';
$Definition['Managing Users'] = 'Kullanıcı Yönetimi';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'İşleri spam değil olarak işaretlemek onları forumunuza geri koyacaktır.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'İşleri spam olmayan olarak işaretlemek onları forumunuza geri koyacaktır.';
$Definition['Messages can appear anywhere in your application.'] = 'Mesajlar, uygulamanızın herhangi bir yerinde görünebilir ve kullanıcılarınızı haber ve etkinliklerle ilgili bilgilendirmek için kullanılabilir. İletilerinizi yukarı veya aşağı sürükleyerek yeniden düzenlemek için bu sayfayı kullanın.';
$Definition['MobileLogoDescription'] = 'Mobil banner logosu sitenizin üstünde görünür.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Mobil temalar, sitenizin görünümünü ve hissini daha küçük cihazlarda değiştirmenize olanak tanır.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Yeni Düzen Düzenleyici, Stil Rehberinizdeki (resmi tema düzenleyici) tema setini devralır. <1>Daha fazlasını öğrenin</1>';
$Definition['Need More Help?'] = 'Daha Fazla Yardıma mı ihtiyacınız var?';
$Definition['Need more help?'] = 'Daha fazla yardıma mı ihtiyacınız var?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Bu derinlikten daha derin yuvalanmış kategoriler, virgülle ayrılmış bir listeye yerleştirilir.';
$Definition['New Embed System'] = 'Yeni Gömme Sistemi';
$Definition['New Quick Links'] = 'Yeni Hızlı Bağlantılar';
$Definition['New Search Page'] = 'Yeni Arama Sayfası';
$Definition['No Anonymization'] = 'Anonimleştirme Yok';
$Definition['Not getting what you expect when you preview your theme?'] = 'Temanızı önizlerken beklediğiniz şeyi almıyor musunuz?';
$Definition['Notify me when people comment on my addons.'] = 'Kullanıcılar eklentilerime yorum yaptığında beni haberdar et.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Sitenin, e-posta onayını kullanmak için varsayılan olarak "onaylanmamış" bir role ihtiyacı var. Lütfen bu ayarı etkinleştirmek için bir tane ekleyin.';

$Definition['Old Theming UI'] = 'Eski Tema Arayüzü';
$Definition['Once enabled, only members will see inside your community.'] = 'Etkinleştirildiğinde, topluluğunuzun içinde yalnızca üyeler görünür.';
$Definition['OrgDescription'] = 'Organizasyon ismin SEO microdata ve JSON+LD için kullanılıyor.';
$Definition['Outline'] = 'Taslak';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Geçersiz kılınan görünümlerin veya tema kancalarının istenmeyen yan etkileri olabilir ve önizlenmezler.';

$Definition['Partial Anonymization'] = 'Kısmi Anonimleştirme';
$Definition['PartialAnonymization.Description'] = '<strong>Kısmi Anonimleştirme,</strong> IP adresinin yalnızca son sekizlisini anonimleştirir. Örneğin 254.230.05.153, 254.230.05.0 olur. Bu, IP yasağı kurallarının çalışmasına izin verirken bir miktar anonimleştirme sağlar.';
$Definition['Password.MinLength'] = 'Parola oluşturma ve sıfırlama sayfalarında kullanıcı parolaları için izin verilen minimum karakter uzunluğu.';
$Definition['Please choose an authenticator to configure.'] = 'Lütfen yapılandırmak için bir onaylayıcı seçin.';
$Definition['PluginHelp'] = 'Eklentiler sitenize işlevsellik eklemenizi sağlar. %s Klasörünüze  <br /> bir eklenti eklendikten sonra, buradan etkinleştirebilir veya devre dışı bırakabilirsiniz.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Cep ana tartışma listesindeki her tartışma arasında görüntülenir. Tartışmalar genellikle <li>..</li> Etiketler, cebinizi de bu etiketlere sarmanız gerekir.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Paketler, uygulamanın etrafındaki çeşitli yerlere serbest biçimli HTML eklemenizi sağlar.';
$Definition['Preset'] = 'Ön ayar';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Tartışmaların sayısını sınırlandırarak forumunuzdaki spam’leri önleyin. kullanıcıların belirli bir süre içinde gönderebilecekleri yorumlar.';
$Definition['Primary Button'] = 'Birincil Düğme';
$Definition['Primary Buttons'] = 'Birincil Düğmeler';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Vanilla için Hızlı Tema Oluşturma Başlangıç Kılavuzu';
$Definition['Quicklinks'] = 'Hızlı Linkler';
$Definition['Quick Links is a default component on community pages.'] = 'Hızlı Bağlantılar, topluluk sayfalarında varsayılan bir bileşendir. Tema düzenleyicimizi kullanarak bu menüden bağlantı eklemek, düzenlemek veya gizlemek için yeni Hızlı Bağlantılar bileşenimizi etkinleştirin.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Vanilya WordPress eklentisi hazır';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'WordPress için Hazır Vanilya Forum Eklentisi';
$Definition['Realtime progress bars: %s'] = 'Gerçek zamanlı ilerleme çubuğu: %s';
$Definition['Recommended dimensions are about 400px by 300px or smaller with similar ratio.'] = 'Önerilen boyutlar yaklaşık 400 piksele 300 piksel veya benzer oranda daha küçüktür.';
$Definition['Recommend special ranks for admins and mods.'] = 'Topluluğunuzun kimin sorumlu olduğunu kolayca görebilmesi için moderatörler ve yöneticiler için özel derecelere sahip olmak iyi bir fikirdir.';
$Definition['Recommend starting with five ranks.'] = 'Çok fazla rütbe almak istemezsiniz. Beş ile başlamanızı öneririz. Topluluğunuz gerçekten büyükse daha fazlasını ekleyebilirsiniz.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Menülerden tartışma ve kategori bağlantılarını kaldırın. Bulunamayan 404. sayfaya dönmek için tartışma ve kategoriyle ilgili sayfaları ayarlayın.';
$Definition['Requires “Flag” reaction permission.'] = '"İşaretle" reaksiyon izni gerektirir.';
$Definition['Requires “Negative” reaction permission.'] = '“Negatif” reaksiyon izni gerektirir.';
$Definition['Requires “Positive” reaction permission.'] = '“Pozitif” reaksiyon izni gerektirir.';
$Definition['Restoring your selection removes the items from this list.'] = 'Geri yüklediğinizde, öğeler bu listeden kaldırılır ve siteye geri konur.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Zengin Editör alıntılarını etkinleştirmek için aşağıdaki seçeneği kullanın. Bu, yalnızca varsayılan biçimlendirici "Zengin" ise geçerli olacaktır.';
$Definition['Route Expression'] = 'Rota İfadesi';
$Definition['Routes are used to redirect users.'] = 'Rotalar, istenen URL\'ye bağlı olarak kullanıcıları yönlendirmek için kullanılır.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Kullanıcıları adına göre arayın veya bu roldeki tüm kullanıcıları görmek için rolün adını girin.';
$Definition['Secondary Button'] = 'İkincil Düğme';
$Definition['Secondary Buttons'] = 'İkincil Düğmeler';
$Definition['Security.Hsts.HTTPSWarning'] = 'Uyarı: Bu özelliği yalnızca, tüm alt alan adlarınızın HTTPS için geçerli sertifikalarla yapılandırıldığından eminseniz etkinleştirin.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Etkinleştirildiğinde, bu kural sitenizin tüm alt etki alanları için de geçerlidir.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Sitenizin beklendiği gibi çalıştığını gördüğünüzde, maksimum 1 hafta ile başlayıp 1 ay sonra 1 yıl kadar artırmanızı öneririz.';
$Definition['Security.Hsts.SubmitWarning'] = 'Uyarı: HSTS önyüklemesini en iyi uygulama olarak desteklemek harika. Bununla birlikte, sitenizi başarılı bir şekilde önceden yüklendiğinden emin olmak için hstspreload.org adresine göndermelisiniz (yani, amaçlanan yapılandırma için tam koruma sağlamak için).';
$Definition['See the documentation'] = 'Belgelere Bakın';
$Definition['Select the default type for this role, if any.'] = 'Varsa, bu rol için varsayılan türü seçin.';
$Definition['Select the import source'] = 'İçe aktarma kaynağını seçin';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Serileştirilmiş sütun "%s" serileştirilemedi.';
$Definition['Session Timeout'] = 'Oturum zaman aşımına uğradı';
$Definition['Shadowed'] = 'Gölgeli';
$Definition['ShareImageDescription'] = 'Birisi sitenizden bir bağlantı paylaştığında sayfadan bir resim almaya çalışırız. Sayfada resim yoksa, bu resmi kullanırız. Görüntü en az 50×50 olmalıdır, ancak 200×200 önerilir.';
$Definition['Show all possible pocket locations.'] = 'Tüm olası cep konumlarını göstermek için bu seçeneği açın. Bu seçeneği açmak, sadece yerleri yönetebilecek kullanıcılara yerleri gösterecektir.';
$Definition['SignIn.LockoutTime'] = 'Bir kullanıcının oturum açma girişimi sayısını aştıktan sonra oturum açmasının engellendiği süre.';
$Definition['Solid'] = 'Katı';
$Definition['Some browsers support a color for the address bar.'] = 'Bazı tarayıcılar adres çubuğu için bir rengi destekler.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Bazı eski temalar tam düzenleme özelliğini desteklemez. Bir temanın neyi desteklediğini görmek için düzenlemelerin nerede etkili olacağını görmek için imleci adının üzerine getirebilirsiniz.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Aşağıdaki temalarla çalışmak için bazı temaların güncellenmesi gerekebilir. Temanızı güncellerken özelliği devre dışı bırakabilirsiniz.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Bazen Vanilla sitenizi başka bir sitenin içine gömmek istersiniz. Vanilla\'nın yerleştirme sistemi bunun için kolay bir yol sunuyor. Gömülü bir site kullanırken performans ödünleşimleri vardır, bu nedenle alternatifler ve ideal kullanım durumları için belgelere bakın.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Özel kısıtlama: Yalnızca Garden.Curation.Manage izni olan kullanıcılar bu reaksiyonu kullanabilir.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Bir yasak oluştururken kısmi ya da tam bir eşleşme belirt.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Sitenizi burada nasıl tanımladığınızı düşünerek biraz zaman geçirin. Sitenize anlamlı bir başlık ve kısa bir açıklama vermek, arama motorlarında konumunuzu belirlemekte ve sağlamlaştırmakta yardımcı olabilir.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Logo ekleyerek ve renkleri özelleştirerek e-postalarınızı yükseltin.';
$Definition['Start Import'] = 'İçe Aktarımı Başlat';
$Definition['Start the first discussion.'] = '<a href="{/post/discussion,url}">İlk tartışma başlığını şimdi açarak</a> topluluğunuza hareket kazandırın.';
$Definition['Subcommunities'] = 'alt topluluklar';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Etiketleme, kullanıcıların daha keşfedilebilir hale getirmek için başlattıkları tartışmalara bir etiket eklemesine olanak tanır.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Şablonlar standart temalardır. Bunları özelleştirmek için bir kopya oluşturmanız gerekir.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = '%s Doğrulayıcı, herhangi bir özel yapılandırma seçeneğine sahip değildir.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'N.B. <0/> Laboratuvarın özel temanıza uyacak şekilde yapılandırılması gerekir. Bu, yeni tema düzenleyicimiz kullanılarak yapılabilir. <1>Daha fazla bilgi edin.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Eklenti önemli bir hata oluşturduğu için etkinleştirilemedi: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Eklenti zaten indirildi.';
$Definition['The banner logo appears at the top of your forum.'] = 'Forumunuzun en başında gözükecek olan logo.';
$Definition['The banner title appears on the top-left of every page.'] = 'Başlık logosu her sayfanın sol üst köşesinde görünür.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Başlık logosu, sitenizin başlığında ve tarayıcınızın başlık çubuğunda görünür. 20 karakterden az olmalıdır. Bir başlık logosu yüklenirse, kullanıcının karşılaştığı forum sayfalarındaki başlığın yerini alır. Ayrıca, bazı temaların bu başlığı da gizleyebileceğini unutmayın.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Temel kayıt formu,</strong> spam gönderenleri siteden uzak tutmak için yeni kullanıcıların bir CAPTCHA görüntüsünden metin kopyalamasını gerektirir. <a href="http://recaptcha.net/">recaptcha.net</a> adresinden bir hesaba ihtiyacınız var. Kayıt olmak ÜCRETSİZ ve kolaydır. Kaydolduktan sonra buraya geri dönün ve aşağıdaki ayarları girin:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Belirttiğiniz veritabanı kullanıcısı veritabanına erişim iznine sahip değil. Veritabanını oluşturdun mu? Veritabanı raporu: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Veritabanınız için aşağıdaki yapı değişiklikleri gereklidir.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Ana sayfa başlığı ana sayfanızda gösterilir. Arama motorlarında görünmesini istediğiniz bir başlığı seçin.';
$Definition['The import file does not contain any data.'] = 'İçe aktarılan dosya herhangi bir veri içermiyor.';
$Definition['The import file is not in the correct format.'] = 'İçe aktarılan dosya doğru biçimde değil.';
$Definition['The location of the authentication endpoint.'] = 'Kimlik doğrulama uç noktasının konumu.';
$Definition['ThemeHelp'] = 'Temalar görünümü değiştirmenizi sağlar & Bakın ve sitenizde deneyin. %s Tema klasörünüze bir tema eklendikten sonra, buradan etkinleştirebilirsiniz.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Tema önizlemesi, temanın şablonunu ve css görüntülemekle sınırlıdır.';
$Definition['Theming Guide'] = 'Tema Kılavuzu';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Mobil logosu sitenizin üst kısmında görünür. Tema düzenleyici ile yapılan temalar ve bazı özel temalar bu ayarı kullanmaz.';
$Definition['The New Embed System'] = 'Yeni Gömme Sistemi';
$Definition['The new embed system has improved performance.'] = 'Yeni gömme sistemi, eskisinden daha iyi performansa, iyileştirilmiş kaydırma davranışına ve daha tutarlı davranışa sahiptir. Şu anda yorum ve wordpress yerleştirmeleri Yeni Yerleştirme Sisteminde desteklenmemektedir.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Parola Doğrulayıcı\'nın herhangi bir özel yapılandırma seçeneği yoktur.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Veritabanı yapısında değişikliğe gerek yoktur. Bununla birlikte, veri değişiklikleri olabilir.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Uygulamada iki tür düğme vardır: birincil ve ikincil.';
$Definition['The route was saved successfully.'] = 'Rota başarıyla kaydedildi.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Site açıklaması genellikle arama motorlarında görünür. 100-150 karakter uzunluğunda bir açıklama yapmayı denemelisiniz.';
$Definition['The text of the pocket.'] = 'Cep metnini girin. Bu tam olarak sizin yazdığınız gibi çıkar, bu yüzden geçerli bir HTML girdiğinizden emin olun.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Bir mobil cihazın ana ekranında bir web sitesini yer imlerine eklediğinizde dokunmatik simgesi görünür. Bunlar genellikle 152 pikseldir.';
$Definition['The user table was not in the import file.'] = 'Kullanıcı tablosu içe aktarma dosyasında değildi.';
$Definition['The Vanilla 2 Exporter'] = 'Vanilya 2 Dışa Aktarıcı';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla İstatistikleri, forumunuzun panosunu bir analitik raporlama aracına dönüştürerek, belirli bir zaman dilimi içerisinde forumunuzdaki etkinliği gözden geçirmenize olanak sağlar. <a href="http://vanillaforums.org/docs/vanillastatistics">Vanilya İstatistikleri hakkında daha fazla bilgiyi</a> dokümanlarımızda okuyabilirsiniz.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Normal temalar gibi çalışırlar. Bir tanesi temalar klasörüne eklendikten sonra buradan etkinleştirebilirsiniz.';
$Definition['This is a style guide of your theme.'] = 'Bu, temanızın bir stil kılavuzudur. Uygulama boyunca kullanılan görsel öğelerin örneklerine sahiptir. <0>Başlık Çubuğu </0> gibi çeşitli widget\'ları tıklayabilirsiniz veya <1>Logo</1> yan panelinde özelliklerini düzenleyin.';
$Definition['This is the administrative dashboard for your new community.'] = 'Bu, yeni topluluğunuz için yönetim panosudur. Yan taraftaki yapılandırma seçeneklerini kontrol edin. Oradan topluluğunuzun nasıl çalıştığını düzenleyebilirsiniz. <b>Varsayılan olarak, yalnızca "Yönetici" rolündeki kullanıcılar topluluğunuzun bu bölümünü görebilir.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Yeni Vanilla özelliklerini, sayfalarını ve bileşenlerini etkinleştirip test edebileceğiniz yer burasıdır.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Özel bir düzen uygulandığı için bu laboratuvar devre dışı bırakılamaz.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Bu laboratuvar, geçerli tema tarafından gerekli olduğu için devre dışı bırakılamaz.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Bu logo sitenizin üst kısmında görünür. Tema düzenleyici ile yapılan temalar ve bazı özel temalar bu ayarı kullanmaz.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Bu, giden tüm e-postalara kuruluş adı ve adresi gibi içeriği eklemek için kullanılabilir.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Bu seçenek, ceplerin gidebileceği yerleri gösterir/gizler, ancak yalnızca cep ekleme/düzenleme iznine sahip kullanıcılar için. Yerleri göstermeyi deneyin ve ardından sitenizi ziyaret edin.';
$Definition['This page lists the endpoints of your API.'] = 'Bu sayfa sizin API uç noktalarını listeler. Daha fazla bilgi için bitiş noktalarını tıklayın. Bu sayfadan veya harici olarak bir erişim belirteci kullanarak API canlı arama yapabilirsiniz.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Bu rol kişisel bilgidir. Yalnızca kişisel bilgileri görüntüleme izni olan kullanıcılar görecektir.';
$Definition['This setting loads the page before executing Javascript.'] = 'Bu ayar sayfayı,  SEO\'nuzu iyileştirebilecek Javascript\'i çalıştırmadan önce yükler.<br><strong>**Uyarı: Bu özelliği etkinleştirmek, sitenizde Javascript hatalarının oluşmasına sebep olabilir.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Bu ayar, SEO\'nuzu iyileştirebilecek Javascript\'i çalıştırmadan önce sayfayı yükler.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Bu tema uygulanan mevcut tema olduğundan silinemez.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Bu başlık sitenizin başlığında ve tarayıcınızın başlık çubuğunda görünür. Bir logo yüklenirse, kullanıcıya yönelik forum sayfalarında bu başlığın yerini alacaktır. Ayrıca bazı temaların bu başlığı gizleyebileceğini unutmayın.';
$Definition['Tiled Layout'] = 'Döşeme Düzeni';
$Definition['Title Bar'] = 'Bağlık Çubuğu';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Vanilla forumunuzu web sitenize yerleştirmek için aşağıdaki kodu kullanın.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Çok fazla adres! Bir kerede %s adrese göndeririz.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Kötüye kullanımı önlemek için, bazı araçlar içeriği otomatik olarak gizler ve bir moderatör tarafından manuel olarak onaylanana kadar burada listeler.';
$Definition['TouchIconDescription'] = 'Bir Apple cihazının ana ekranında bir web sitesine yer işareti koyduğunuzda dokunmatik simgesi görünür. Bunlar genellikle 152 pikseldir. Apple otomatik olarak yuvarlatılmış köşeler ve ışık efekti ekler.';
$Definition['Transparent'] = 'Şeffaf';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Bağlantısı, kullanıcıların Twitter hesaplarını kullanarak giriş yapmalarını sağlar. <b>Bu eklentinin çalışması için başvurunuzu Twitter\'a kaydetmeniz gerekir.</b>';

$Definition['Usercards'] = 'Kullanıcı kartı';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Kullanıcı kartları, bir kullanıcının bilgilerinin hızlı bir şekilde anlık görüntüsünü almanızı sağlar. Gönderileri ve skor tablolarını görüntülerken, sayfadan ayrılmak zorunda kalmadan kullanıcıların temel profil bilgilerini gösteren bir kart görmek için kullanıcı adına tıklayın. Özel temanıza kullanıcı kartları eklemek için bu özelliği etkinleştirin.';
$Definition['User inputs are based on the global background and text colors.'] = 'Kullanıcı girişleri genel arka plan ve metin renklerini temel alır.';
$Definition['User Profile'] = 'Kullanıcı profili';
$Definition['Users may sign into your site using their Twitter account.'] = 'Kullanıcılar, Twitter hesaplarını kullanarak sitenizde oturum açabilir.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Yasaklama kuralı oluşturmak için sayfanın üst kısmındaki düğmeyi kullanın.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Blogunuzda Vanilla Yorumları ayarlamak için WordPress eklentisini kullanın veya başka bir platformda Vanilla Yorumları ayarlamak için evrensel kodu kullanın.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Vanilla\'nın yeni arama hizmeti sonunda burada. Üye Arama, arama sıralama ve terim vurgulama gibi en yeni arama özelliklerine erişmek için yeni arama sayfası kullanıcı arayüzünü etkinleştirin.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Vanilla Dışa Aktar: %s, Kaynak: %s';
$Definition['Vanilla Labs'] = 'Vanilya Laboratuvarları';
$Definition['Vanilla Statistics are currently disabled'] = 'Vanilya İstatistikleri şu anda devre dışı';
$Definition['Verify and restore'] = 'Doğrula ve geri yükle';
$Definition['VerifyUser'] = 'Yayınlarının tekrar spam olarak işaretlenmemesi için kullanıcının <b>Doğrulandı</b> olarak işaretlemek için kullanıcının yanındaki kutuyu işaretleyin. Bu ayrıca bekleyen tüm gönderilerini de geri yükleyecektir.';
$Definition['Video tutorial on advanced settings'] = 'Gelişmiş ayarlarla ilgili video eğitimi';
$Definition['Video tutorial on finding &amp; managing users'] = 'Kullanıcı yönetimi hakkında & video eğitimi bul';
$Definition['Video tutorial on managing appearance'] = 'Görünüm yönetimi hakkında video eğitimi';
$Definition['Video tutorial on managing categories'] = 'Kategori yönetimi ilgili video eğitimi';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Rollerin yönetimi hakkında & video eğitimi bul';
$Definition['Video tutorial on user registration'] = 'Kullanıcı kaydı hakkında video eğitimi';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Uyarı: Bu özelliğin etkinleştirilmesi sitenizde Javascript hatalarına neden olabilir.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Uyarı</b>: Sunucu yapılandırmanız hızlı veri yüklemeyi desteklemiyor. Sunucu yapılandırmanız hızlı veri yüklemeyi desteklemiyor. Çok büyük bir dosyayı içe aktarıyorsanız (ör. 200.000\'den fazla yorum) yapılandırmanızı değiştirmeyi düşünebilirsiniz. Daha fazla bilgi için <a href="http://vanillaforums.com/porter">buraya</a> tıklayın.';
$Definition['Warning: This is for advanced users.'] = '<b>Uyarı</b>: Bu, ileri düzey kullanıcılar içindir ve web sunucunuzda ek değişiklikler yapmanızı gerektirir. Bu genellikle yalnızca adanmış veya vps hostinginiz varsa kullanılabilir. Ne yaptığınızı bilmiyorsanız bunu denemeyin.';
$Definition['Webhooks'] = 'Web kancaları';
$Definition['Welcome to Labs!'] = 'Laboratuvara hoş geldiniz!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Vanilla\'nın tema arayüzüne hoş geldiniz. Bu sayfa mevcut tüm temalarınızı listeler ve kopyalamanıza veya düzenlemenize olanak tanır.';
$Definition['Welcome To Your Theme'] = 'Temanıza Hoşgeldiniz';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Etkinleştirildiğinde kullanıcılar topluluktan bildirim almayı seçebilir';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Etkinleştirildiğinde ürünleri yönetebilir ve alt ürünleri bu ürünlerle gruplayabilirsiniz.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Birisi sitenizden bir bağlantı paylaştığında sayfadan bir resim almaya çalışırız. Sayfada resim yoksa, bu resmi kullanırız. Görüntü en az 50×50 olmalıdır, ancak 200×200 önerilir.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Tam Taşma tpyını seçtiğinizde arka planınız saydam olur.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Dahili profil alanlarının bu web kancasına dahil edilip edilmeyeceği.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Özel profil alanlarının bu web kancasına dahil edilip edilmeyeceği.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Yeni bir düzen seçeneği uygulamak üzeresiniz. Bu, Tema Editörümüz kullanılarak özelleştirilebilir ve önizlenebilir. <0>Daha fazla bilgi</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = '"111.111.111.*" değeriyle bir IP tipi yasak ekleyerek, IP adresleri "111.111.111" ile başlayan tüm kullanıcıları yasaklayabilirsiniz.';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'IP adreslerini, e-posta adreslerini ve kullanıcı adlarını yasaklayabilirsin.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Bu temanın sunduğu farklı stillerden birini seçebilirsiniz.';
$Definition['You can configure some values differently for different screensizes.'] = 'Bazı değerleri farklı ekran boyutları için farklı yapılandırabilirsiniz.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'JsConnect destekleyen birden çok siteye bağlanabilirsiniz.';
$Definition['You can place files in your /uploads folder.'] = 'Dosyanız doğrudan bu sayfaya yüklemek için çok büyükse, dosyayı  /uploads klasörüne yerleştirebilirsiniz. Dosya adının <b>export</b> sözcüğü ile başladığından ve <b>.txt, .gz</b> sözcüklerinden biriyle bitdiğinden emin olun.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Kısa gönderileri engellemek için asgari bir ileti uzunluğu belirleyebilirsiniz.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Tema Sisteminize bir Özel Yazı Tipi yükleyebilirsiniz. Yazı Tipi URL\'sini alana kopyalayıp yapıştırmanız yeterlidir.';
$Definition['You must select a file to import.'] = 'İçe aktarmak için bir dosya seçmek zorundasınız.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Yazı tipi url\'sinin alanını sitenin yapılandırmasında <0>İzin Verilen Alan Adlarına </0> eklemeniz gerekir. <1>Özel yazı tipleri hakkında daha fazla bilgi edinin.</1>';
$Definition['Your mobile theme will be disabled.'] = 'Mobil temanız devre dışı bırakılacak. Farklı mobil ve masaüstü temaları ayarlamak için eski tema kullanıcı arayüzünü kullanın.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Organizasyon ismin SEO microdata ve JSON+LD için kullanılıyor.';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Sitenizin ikonu, tarayıcınızın başlık çubuğunda görünüyor ve uygun bir şekilde küçültülecek.';
