<?php

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>سر!</strong> کسی کردار کو حذف کرنے کے نتیجے میں صارفین کو درخواست تک رسائی حاصل نہیں ہوسکتی ہے۔';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>سر!</strong> تبادلہ خیال کے زمرے میں تبادلہ خیال کے نتیجے میں تبادلہ خیال غائب ہوسکتا ہے (یا نمودار ہوسکتا ہے) اگر متبادل زمرے میں حذف ہونے سے مختلف اجازتیں ہوں۔';

$Definition['About.DisableStatistics'] = 'اگر آپ کو کسی کاروباری وجوہ کی بناء پر اس کوائف کی اطلاع دہندگی کو غیر فعال کرنا ہوگا تو ، آپ اپنی انسٹالیشن کی تشکیل فائل میں درج ذیل لائن کو شامل کرکے ایسا کرسکتے ہیں: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'اس مفت ، اوپن سورس سافٹ ویئر کی زندگی کے لئے یہ انتہائی اہم ہے کہ ہم ونیلا کی پہنچ اور تاثیر کو درست طریقے سے ناپتے ہیں۔ ہم دعا گو ہیں کہ آپ براہ کرم اس ڈیٹا کی رپورٹنگ کو غیر فعال نہ کریں۔';
$Definition['AboutCommentEmbedding'] = 'ونیلا کو آپ کے بلاگ کے آبائی تبصرہ کرنے والے نظام کے متبادل کے طور پر استعمال کیا جاسکتا ہے۔ حقیقت میں ، اس کا استعمال ویب کے کسی بھی صفحے پر تبصرے شامل کرنے کے لئے کیا جاسکتا ہے۔';
$Definition['AboutEmbedding'] = 'ایمبیڈنگ سے آپ کی کمیونٹی کے سبھی حص partے کو دوسرے ایپلیکیشنز اور ویب صفحات میں شامل کرنے کی اجازت ملتی ہے۔';
$Definition['About Vanilla Statistics'] = 'ونیلا کے اعدادوشمار کے بارے میں';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'اس صفحے کے اوپری حصے میں "سائٹ ملاحظہ کریں" لنک پر <a href={/,url}>کلک کرکے</a> یا <a href={/,url}>یہاں کلک کرکے</a> اپنے کمیونٹی فورم تک رسائی حاصل کریں۔ کمیونٹی فورم وہ ہے جو آپ کے صارف اور صارفین سبھی دیکھیں گے جب وہ <a href="{/,url,domain}">{/، url ، ڈومین</a> visit جائیں گے۔';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'مباحثوں اور تبصروں میں تصویری اپلوڈ کے طول و عرض کی حدود شامل کریں۔';
$Definition['AddonProblems'] = '<h2 style=";text-align:right;direction:rtl"> مسائل؟ </h2><p style=";text-align:right;direction:rtl"> اگر کسی ایڈون کے ساتھ کچھ غلط ہو گیا ہے اور آپ اپنی سائٹ استعمال نہیں کرسکتے ہیں تو ، آپ ان میں ترمیم کرکے دستی طور پر اسے غیر فعال کرسکتے ہیں۔ </p> %s';
$Definition['AddressBarColorDescription'] = 'کچھ براؤزر ایڈریس بار کے لئے رنگ کی حمایت کرتے ہیں۔ صرف موبائل۔';
$Definition['Alert users if they click external link.'] = 'صارفین کو متنبہ کریں اگر وہ کسی پوسٹ میں کسی ایسے لنک پر کلک کرتے ہیں جس سے وہ فورم سے دور ہوجائیں۔ قابل اعتماد ڈومین سے ملنے والے روابط کی پیروی کرتے وقت صارفین کو متنبہ نہیں کیا جائے گا';
$Definition['Alignment'] = 'صف بندی';
$Definition['Alignment (Mobile)'] = 'سیدھ (موبائل)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'ہر ایک کے تحت حالیہ 5 مباحثوں کے انتخاب کے ساتھ درج تمام زمرے';
$Definition['Allow links to be transformed'] = 'روابط کو مباحثوں اور تبصروں میں ایمبیڈڈ نمائندوں میں تبدیل کرنے کی اجازت دیں۔ مثال کے طور پر ، ایک YouTube لنک ایک ایمبیڈڈ ویڈیو میں تبدیل ہوجائے گا۔';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = '%s صارفین کو ونیلا میں اپنے پروفائل صفحات سے اپنے اوتار تبدیل کرنے کی اجازت دیں۔';
$Definition['ApplicationHelp'] = 'ایپلی کیشنز آپ کو اپنی سائٹ میں فعالیت کے بڑے گروپس کو شامل کرنے کی اجازت دیتی ہیں۔ <br /> ایک بار جب آپ کے %s فولڈر میں ایک درخواست شامل ہوجائے تو ، آپ اسے یہاں فعال یا غیر فعال کرسکتے ہیں۔';
$Definition['Apply Layout'] = 'لے آؤٹ کا اطلاق کریں۔';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'کیا آپ واقعی اس تھیم کو حذف کرنا چاہتے ہیں؟ اسے مستقل طور پر حذف کردیا جائے گا۔';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'کیا آپ واقعی صحیح ڈیٹا بیس کے میزبان کا نام درج کر چکے ہیں؟ شاید آپ نے غلط ٹائپ کیا ہے؟ ڈیٹا بیس کی اطلاع: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'ای میل کی توثیق کو استعمال کرنے کے لئے پہلے سے طے شدہ "غیر مصدقہ" کردار کے ساتھ ایک کردار کی ضرورت ہوتی ہے۔';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'اگر اوتار اس اونچائی سے تجاوز کریں گے تو ان کو کم کیا جائے گا۔';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'اوتار اگر اس چوڑائی سے تجاوز کر جائیں تو ان کو کم کیا جائے گا۔';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'اوتار کے پاس اس تھمب نیلز کو اس سائز میں محفوظ کیا جائے گا۔';

$Definition['Background'] = 'پس منظر';
$Definition['Background Image'] = 'پس منظر کی تصویر';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'تخلیقی بنو، کچھ نیا کرکے دکھاؤ! برادری جس چیز کے بارے میں بات کرتی ہے ان کے نام پر اپنی صفوں کا نام لینے کی کوشش کریں۔';
$Definition['Bordered'] = 'بارڈرڈ';
$Definition['Bordered (Unified)'] = 'بارڈرڈ (متحد)';
$Definition['Borderless'] = 'بے حد';
$Definition['Border Radius'] = 'بارڈر رداس';
$Definition['Brand Color'] = 'برانڈ کا رنگ';
$Definition['Buttons'] = 'بٹن';
$Definition['Buttons & Inputs'] = 'بٹن اور آدانوں';
$Definition['Button Type'] = 'بٹن کی قسم';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'نیچے والے بٹن پر کلک کرکے ، آپ صارف اکاؤنٹ کو ہمیشہ کے لئے %s کے لئے حذف کردیں گے۔';

$Definition['Center Aligned'] = 'سینٹر منسلک ہے';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'تبدیلیوں کا اطلاق صرف نئے اپ لوڈ کردہ اوتار پر ہوگا۔';
$Definition['Change the sizes that avatar images are saved at.'] = 'وہ سائز تبدیل کریں جس میں اوتار کی تصاویر محفوظ کی گئی ہیں۔';
$Definition['Change the way your community works with plugins.'] = 'پلگ ان کے ساتھ آپ کی کمیونٹی کے کام کرنے کا طریقہ تبدیل کریں۔ ہم سافٹ ویئر کے ساتھ مقبول پلگ ان بنڈل کر چکے ہیں ، اور اور بھی آن لائن دستیاب ہیں۔';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'چیک باکسز ایک ہی وقت میں متعدد مباحثوں یا تبصروں پر منتظمین کو بیچ ایکشن انجام دینے کی اجازت دیتے ہیں۔';
$Definition['Check out our %s'] = 'ہمارے %s چیک کریں';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'ہماری <0>دستاویزات دیکھیں</0> یا ہمارے <1>ماہرین کی کمیونٹی سے پوچھیں۔</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'ونیلا دنیا کا آسان ترین ، طاقت ور کمیونٹی کا پلیٹ فارم ہے۔ یہ سپر ڈوپر استعمال میں آسان ہے۔ اس تعارفی ویڈیو سے شروع کریں اور نیچے دیئے گئے اقدامات کے ساتھ جاری رکھیں۔ لطف اٹھائیں!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'ایک ایسے کردار کا انتخاب کریں جس پر یتیم صارفین کو تفویض کیا جائے:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'اس سب کمیونٹی کے لئے ایک تھیم منتخب کریں۔ <0> مزید پڑھیں </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = '%s (تبصرے ، پیغامات ، وغیرہ) کے صارف اکاؤنٹ سے وابستہ تمام مواد کو ہینڈل کرنے کا طریقہ منتخب کریں۔';
$Definition['Choose Image'] = 'تصویر منتخب کریں';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'آپ اپنی درخواستوں پر دستخط کرنے کے لئے ایک حسب ضرورت ہیش الگورتھم منتخب کرسکتے ہیں۔ ہیش الگورتھم کو آپ کے مؤکل لائبریری میں بھی استعمال کرنا چاہئے۔ اگر آپ کو یقین نہیں ہے کہ کیا انتخاب کرنا ہے تو ایم ڈی 5 کا انتخاب کریں۔';
$Definition['Choose the order items are sorted.'] = 'آرڈر آئٹمز کو ترتیب دیا گیا ہے منتخب کریں۔';
$Definition['Choose the page people should see when they visit <0/>'] = 'وہ صفحہ منتخب کریں جب لوگ <0/> پر جائیں۔';
$Definition['Choose the preferred layout for lists of categories.'] = 'زمرہ جات کی فہرست کے لئے ترجیحی ترتیب منتخب کریں۔';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'زمروں کی فہرستوں کے لیے ترجیحی ترتیب منتخب کریں۔ آپ ٹائلڈ لے آؤٹ میں ترمیم کرسکتے ہیں۔';
$Definition['Choose the preferred layout for lists of discussions.'] = 'مباحثوں کی فہرستوں کے لئے ترجیحی ترتیب منتخب کریں۔';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'مباحثوں کی فہرستوں کے لیے ترجیحی ترتیب منتخب کریں۔ آپ فاؤنڈیشن لے آؤٹ میں ترمیم کرسکتے ہیں۔';
$Definition['Color Overlay'] = 'رنگین اوورلی';
$Definition['Continue Import'] = 'درآمد جاری رکھیں';
$Definition['Could not parse import file. The problem is near line %s.'] = 'درآمد فائل کی تجزیہ نہیں کرسکا۔ مسئلہ لائن %s کے قریب ہے۔';
$Definition['Create a localization CSV'] = 'لوکلائزیشن CSV بنائیں';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'کسٹم تھیمز آپ کے تخلیق کردہ تھیمز ہیں۔ آپ ان میں ترمیم کرسکتے ہیں ، نام بدل سکتے ہیں یا کاپی بنا سکتے ہیں۔';

$Definition['Dark'] = 'گہرا';
$Definition['Define who can upload files on the Roles & Permissions page.'] = '<a href="%s">رولز اور اجازت والے</a> صفحے پر فائلیں کون اپلوڈ اور سنبھال سکتا ہے اس کی وضاحت کریں۔';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'اپنے فورم کے مرکزی صفحہ کی وضاحت کریں ، اپنا لوگو اپ لوڈ کریں ، اور بہت کچھ ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'کسی کردار کو حذف کرنے کے نتیجے میں صارفین کو درخواست تک رسائی حاصل نہیں ہوسکتی ہے۔';
$Definition['Deleting forever cannot be undone.'] = 'حذف کرنا اپنے فورم کو صاف ستھرا رکھنے کا ایک اچھا طریقہ ہے۔';
$Definition['Disable Google Sign In'] = 'گوگل سائن ان کو غیر فعال کریں';
$Definition['Disable OpenID'] = 'اوپن آئی ڈی کو غیر فعال کریں';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = '<0>ونیلا لیبز پیج پر "نیا ایمبیڈ سسٹم" لیب کو غیر فعال کریں۔</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'آپ کے صارفین کی گفتگو کو اس انداز سے منظم کرنے میں مدد کے ل Disc گفتگو کے زمرے استعمال کیے جاتے ہیں جو آپ کے معاشرے کے لئے معنی خیز ہیں۔';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'اپنے فورم ایڈمن ڈیش بورڈ کو سرایت نہ کریں (اسے پوری اسکرین پر ڈال دیں)';
$Definition['Don\'t use too many reactions.'] = 'بہت زیادہ رد عمل استعمال نہ کریں۔ آپ اپنے صارفین کو اوورلوڈ معلومات نہیں دینا چاہتے۔';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'درجہ بندی کرنے اور گھوںسلا کرنے کیلئے نیچے کیٹیگریوں کو گھسیٹیں اور گرا دیں۔';

$Definition['EditContentTimeout.Notes'] = 'اگر کوئی صارف اس کردار میں ہے جس میں مواد میں ترمیم کرنے کی اجازت ہے تو ، وہ اجازتیں اس کو ختم کردیں گی۔';
$Definition['Edit Route'] = 'روٹ میں ترمیم کریں';
$Definition['Edits to this theme apply to:'] = 'اس موضوع پر کی جانے والی ترامیم کا اطلاق اس پر ہوتا ہے:';
$Definition['Embed Settings'] = 'ایمبیڈ سیٹنگز';
$Definition['Embed your community forum into your website to increase engagement...'] = 'مصروفیت بڑھانے کے ل your اپنے کمیونٹی فورم کو اپنی ویب سائٹ میں شامل کریں ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'وینیلا کی تازہ ترین خصوصیات کو فعال اور آزمائیں۔';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'WYSIWYG ، سادہ ایچ ٹی ایم ایل ، مارک ڈاون ، اور بی بی سی کوڈ سمیت متعدد فارمیٹس میں پوسٹس کی اعلی درجے کی ترمیم کو اہل بناتا ہے۔';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'اپنی کمیونٹی کے صفحات کے لیے حسب ضرورت لے آؤٹ لاگو کرنے کے لیے لے آؤٹ ایڈیٹر کو فعال کریں۔ ہمارے دستیاب ویجٹس کے کیٹلاگ کا استعمال کرتے ہوئے مواد کو نمایاں کرنے کے لیے ہمارے نئے ایڈیٹر کا استعمال کریں۔';
$Definition['Enter a descriptive name.'] = 'جیب کے لئے وضاحتی نام درج کریں۔ یہ نام کہیں بھی نہیں دکھائے گا سوائے اس کے کہ جب اپنی جیبوں کا یہاں انتظام کریں تو یہ صرف جیب کو یاد رکھنے میں آپ کی مدد کے لئے استعمال ہوتا ہے۔';
$Definition['Enter a short name for the site.'] = 'سائٹ کے لئے ایک مختصر نام درج کریں۔ یہ سائن ان بٹنوں پر ظاہر ہوتا ہے۔';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'اپنے ورڈپریس بلاگ کا پتہ درج کریں اور ہم اسے وہاں سے لے جائیں گے۔';
$Definition['Enter the connection settings for your sphinx server below.'] = 'ذیل میں اپنے اسپنکس سرور کیلئے کنکشن کی ترتیبات درج کریں۔';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'ہر ترمیم یا حذف کی اطلاع یہاں درج ہے۔ کسی بھی تبدیلی کو کالعدم کرنے کے لئے \'بحال\' کا استعمال کریں۔';
$Definition['Everyone who signs up gets a profile page.'] = 'ہر ایک جو آپ کی کمیونٹی کے لئے سائن اپ کرتا ہے اسے ایک عوامی پروفائل کا صفحہ مل جاتا ہے جہاں وہ اپنی تصویر اپ لوڈ کرسکتے ہیں ، ان کی پروفائل کی ترتیبات کا نظم کرسکتے ہیں ، اور کمیونٹی میں جاری ٹھنڈی چیزوں کو ٹریک کرسکتے ہیں۔ آپ کو <a href="{/profile,url}">اب اپنے پروفائل</a> کو <a href="{/profile,url}">اپنی مرضی کے مطابق</a> بنانا چاہئے۔';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'آپ کی سائٹ کے ہر صارف کو کم از کم ایک کردار کے لئے تفویض کیا گیا ہے۔ کرداروں کا استعمال اس بات کا تعین کرنے کے لئے کیا جاتا ہے کہ صارفین کو کیا کرنے کی اجازت ہے۔';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'فیس بک کنیکٹ صارفین کو اپنے فیس بک اکاؤنٹ کا استعمال کرکے سائن ان کرنے کی اجازت دیتا ہے۔ <b>اس پلگ ان کے کام کرنے کے ل You آپ کو اپنی درخواست فیس بک کے ساتھ رجسٹر کرنی ہوگی۔</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'آپ نے جو صارف نام اور پاس ورڈ درج کیا ہے اس سے ڈیٹا بیس سے رابطہ قائم کرنے میں ناکام۔ کیا آپ نے انہیں غلط ٹائپ کیا؟ ڈیٹا بیس کی اطلاع: <code>%s</code>';
$Definition['Font'] = 'فونٹ';
$Definition['Font Name'] = 'فونٹ کا نام';
$Definition['Font URL'] = 'فونٹ URL';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'اس یو آر ایل کے ذریعہ ڈیش بورڈ کو صرف قابل رسائی پر مجبور کریں <em>(تجویز کردہ نہیں)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'مثال کے طور پر ، آپ "مثال ڈاٹ کام" کے ای میل پتے والے تمام صارفین پر "*@example.com" ویلیو کے ساتھ ای میل کی قسم پر پابندی شامل کرکے پابندی عائد کرسکتے ہیں۔';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'SEO کے مقاصد کے لئے ، سرچ انجن کرالروں کو دور دراز یو آر ایل میں فورم دیکھنے پر مجبور کرنے سے خارج کردیا گیا ہے۔';
$Definition['Foundation Layout'] = 'فاؤنڈیشن لے آؤٹ۔';
$Definition['Full Bleed'] = 'مکمل خون';

$Definition['Garden.Import.Complete.Description'] = 'آپ نے درآمد کامیابی کے ساتھ مکمل کرلی ہے۔ جب آپ <b>تیار ہوں</b> تو <b>ختم</b> پر کلک کریں۔';
$Definition['Garden.Import.Continue.Description'] = 'ایسا لگتا ہے جیسے آپ کسی درآمد کے وسط میں ہوں۔ براہ کرم مندرجہ ذیل میں سے ایک آپشن منتخب کریں۔';
$Definition['Garden.Import.InputInstructions'] = 'درآمد ہونے والے ڈیٹا سے ایڈمن صارف کا ای میل اور پاس ورڈ درج کریں۔';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'گارڈن۔پروفائلز۔ ونیلا میں اپنے پروفائل صفحات سے اپنے اوتار تبدیل کرنے کی اجازت میں ترمیم کریں۔';
$Definition['Garden.StatisticsDisabled'] = 'آپ نے اپنی تشکیل فائل میں خاص طور پر ونیلا شماریات کو غیر فعال کردیا ہے۔';
$Definition['Garden.StatisticsLocal.Explain'] = 'ایسا لگتا ہے کہ یہ فورم آزمائشی ماحول میں چل رہا ہے ، یا کسی اور نجی نجی IP کی اطلاع دے رہا ہے۔ ڈیفالٹ کے ذریعہ ، نجی IPs پر چلنے والے فورمز کو ٹریک نہیں کیا جاتا ہے۔';
$Definition['Garden.StatisticsLocal.Resolve'] = 'اگر آپ کو یقین ہے کہ آپ کا فورم انٹرنیٹ سے قابل رسائی ہے تو آپ اسے اعدادوشمار کی اطلاع دینے پر مجبور کرسکتے ہیں:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'آپ کی تشکیل ڈاٹ پی پی فائل صرف پڑھنے کے قابل دکھائی دیتی ہے۔ اس کا مطلب یہ ہے کہ وینیلا آپ کے فورم کے انسٹالیشن ایڈ اور انسٹالیشن سیکریٹ کو خود بخود رجسٹر نہیں کرسکیں گی۔';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'اس مسئلے کو حل کرنے کے ل file ، آپ کے کنف / config.php فائل کو فائل موڈ 777 تفویض کریں۔';
$Definition['Global Styles'] = 'عالمی طرزیں';

$Definition['Heads Up!'] = 'سر!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'سر! یہ ایک خاص کردار ہے جو فعال سیشنوں کی اجازت نہیں دیتا ہے۔ اس وجہ سے ، اجازت کے اختیارات "دیکھنے" کی اجازت تک ہی محدود کردیئے گئے ہیں۔';
$Definition['Here are all of the reactions you can use on your site.'] = 'یہ وہ تمام رد عمل ہیں جو آپ اپنی سائٹ پر استعمال کرسکتے ہیں۔';
$Definition['Here are the ranks that users can achieve on your site.'] = 'یہاں وہ درجات ہیں جو صارف آپ کی سائٹ پر حاصل کرسکتے ہیں۔ آپ ان درجات کو اپنی مرضی کے مطابق بنا سکتے ہیں اور یہاں تک کہ نئی فہرستیں شامل کرسکتے ہیں۔ یہاں کچھ نکات ہیں۔';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'اگر بینر کا لوگو اپ لوڈ ہوتا ہے تو ، اس صارف کے سامنا والے فورم کے صفحات پر بینر کا عنوان بدل دے گا۔';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'اگر کوئی صارف اس مدت کے اندر سائٹ پر نہیں جاتا ہے تو وہ خود بخود سائن آؤٹ ہو جائے گا۔';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'اگر چالو ہوتا ہے تو ، خطوط کا پورا مواد استعمال کنندگان کو ای میل اطلاعات میں بھیجا جائے گا۔';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'اگر آپ HTML اور / یا CSS کے لئے نئے ہیں تو ، آپ کو شروع کرنے کے لئے کچھ سبق یہ ہیں:';
$Definition['If you have an old theme'] = 'اگر آپ کے پاس ایک پرانا تھیم ہے اور آپ کو ایک الگ ڈیسک ٹاپ اور موبائل تھیم ترتیب دینے کی ضرورت ہے تو آپ پرانے تھیٹنگ UI کے ساتھ ایسا کرسکتے ہیں۔';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'اگر آپ انتباہ کی سطح کو کم کرنا چاہتے ہیں تو انتباہ کو ہٹا دیں۔';
$Definition['If you want to embed your forum, enable embedding.'] = 'اگر آپ اپنے فورم میں سرایت کرنا چاہتے ہیں یا اپنے بلاگ میں ونیلا کے تبصروں کو استعمال کرنا چاہتے ہیں تو آپ کو سرایت کو قابل بنانا ہوگا۔ اگر آپ ایمبیڈنگ استعمال نہیں کررہے ہیں تو ہمارا مشورہ ہے کہ اس ترتیب کو چھوڑ دیں۔';
$Definition['Image (Mobile)'] = 'تصویر (موبائل)';
$Definition['Import'] = 'درآمد کریں';
$Definition['Importing to Vanilla'] = 'ونیلا کو درآمد کرنا';
$Definition['In additon to the widgets there are also'] = 'ویجٹ میں اضافے میں <0> عالمی طرزیں بھی موجود ہیں </0> . عالمی انداز میں تدوین کے ل the اس متن جیسے صفحے پر کہیں بھی کلک کریں۔';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'فاؤنڈیشن پیجز اور اجزاء کو اپنے تھیم میں ضم کریں۔';
$Definition['Internationalization & Localization'] = 'عالمگیریت اور لوکلائزیشن';
$Definition['Invalid URL'] = 'غلط URL';
$Definition['Invitation email failed to send: %'] = 'اگرچہ دعوت نامہ کامیابی کے ساتھ تشکیل دیا گیا تھا ، ای میل بھیجنے میں ناکام رہا۔ سرور نے درج ذیل خامی کی اطلاع دی: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'جب آپ دعوت نامے کے ذریعہ رجسٹریشن استعمال کرتے ہیں تو صارفین کے اپنے پیجز پر <a href="%s" class="Popup">میرے دعوت نامے</a> کے نام سے ایک لنک ہوگا۔';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'ایسا لگتا ہے گویا آپ نے جو ڈیٹا بیس کا ذکر کیا ہے وہ ابھی موجود نہیں ہے۔ کیا آپ نے ابھی تک اسے تخلیق کیا ہے؟ کیا آپ نے نام غلط ٹائپ کیا؟ ڈیٹا بیس کی اطلاع: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'کمنٹس میں زیادہ سے زیادہ حروف کی تعداد کو مناسب سائز تک رکھنا اچھا خیال ہے۔';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'ایک پوسٹ میں زیادہ سے زیادہ حروف کی تعداد کو مناسب سائز تک رکھنا اچھا خیال ہے۔';

$Definition['Kick-start your community and increase user engagement.'] = 'اپنی کمیونٹی کو کک اسٹارٹ کریں اور صارف کی مصروفیت میں اضافہ کریں۔';

$Definition['Labs'] = 'لیبز۔';
$Definition['Layout Editor'] = 'لے آؤٹ ایڈیٹر';
$Definition['Learn about custom routing.'] = 'کسٹم روٹنگ کے بارے میں جانیں۔';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'اپنے فورم کی شکل و صورت کو مکمل طور پر تبدیل کرنے کا طریقہ سیکھیں: اپنا لوگو اپ لوڈ کریں ، اپنا ہوم پیج مرتب کریں ، ایک تھیم منتخب کریں اور اسے اپنی مرضی کے مطابق بنائیں۔';
$Definition['Learn how to use the basic functionality of your forum.'] = 'اپنے فورم کی بنیادی فعالیت کو استعمال کرنے کا طریقہ سیکھیں۔';
$Definition['Left Aligned'] = 'بائیں منسلک';
$Definition['Light'] = 'روشنی';
$Definition['Links'] = 'لنکس';
$Definition['Locales allow you to support other languages on your site.'] = 'مقامات آپ کو اپنی سائٹ پر دوسری زبانوں کی حمایت کرنے کی سہولت دیتے ہیں۔ آپ ان دستیاب مقامات کو اہل اور غیر فعال کریں جو آپ یہاں دستیاب کرنا چاہتے ہیں۔';
$Definition['LogoDescription'] = 'بینر کا لوگو آپ کی سائٹ کے اوپری حصے میں آتا ہے۔';
$Definition['LogoDisclaimer'] = 'تھیم ایڈیٹر اور کچھ کسٹم تھیمز کے ساتھ بنی تھیمز اس ترتیب کو استعمال نہیں کرتے ہیں۔';
$Definition['Looking for the Old Embed System?'] = 'پرانے ایمبیڈ سسٹم کی تلاش ہے؟';

$Definition['Make sure you click View Page'] = 'اس بات کو یقینی بنائیں کہ بچت کے بعد آپ کے زمرے کا صفحہ کیسا لگتا ہے اس کے ل you آپ <a href="%s">دیکھیں صفحے</a> پر کلک کریں ۔';
$Definition['Manage Routes'] = 'راستوں کا انتظام کریں';
$Definition['Managing Users'] = 'صارفین کا انتظام کرنا';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'چیزوں کو اسپام کے بطور نشان زد کرنے سے وہ آپ کے فورم میں واپس آجائیں گی۔';
$Definition['Marking things as not spam will put them back in your forum.'] = 'چیزوں کو اسپام کے بطور نشان زد کرنے سے وہ آپ کے فورم میں واپس آجائیں گی۔';
$Definition['Messages can appear anywhere in your application.'] = 'پیغامات آپ کی درخواست میں کہیں بھی ظاہر ہوسکتے ہیں ، اور آپ کے صارفین کو خبروں اور واقعات سے آگاہ کرنے کے لئے استعمال ہوسکتے ہیں۔ اپنے پیغامات کو اوپر یا نیچے گھسیٹ کر دوبارہ منظم کرنے کے لئے اس صفحے کا استعمال کریں۔';
$Definition['MobileLogoDescription'] = 'موبائل بینر کا لوگو آپ کی سائٹ کے سب سے اوپر ظاہر ہوتا ہے۔';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'موبائل تھیمز آپ کو چھوٹے آلات پر اپنی سائٹ کی شکل اور شکل تبدیل کرنے کی سہولت دیتے ہیں۔';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB نیا لے آؤٹ ایڈیٹر آپ کے اسٹائل گائیڈ (رسمی طور پر تھیم ایڈیٹر) میں سیٹ کردہ تھیم کا وارث ہوگا۔ <1>مزید جانیں۔</1>';
$Definition['Need More Help?'] = 'مزید مدد کی ضرورت ہے؟';
$Definition['Need more help?'] = 'مزید مدد کی ضرورت ہے؟';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'اس گہرائی سے بھی زیادہ گہری گھریلو اقسام کوما سے خارج کی گئی فہرست میں رکھی جائیں گی۔';
$Definition['New Embed System'] = 'نیا ایمبیڈ سسٹم';
$Definition['New Quick Links'] = 'نئے فوری لنکس۔';
$Definition['New Search Page'] = 'نیا سرچ پیج۔';
$Definition['Not getting what you expect when you preview your theme?'] = 'جب آپ اپنے تھیم کا جائزہ لیتے ہو تو آپ کی توقع کیا نہیں ملتی؟';
$Definition['Notify me when people comment on my addons.'] = 'جب لوگ میرے ایڈونز پر تبصرہ کرتے ہیں تو مجھے مطلع کریں۔';
$Definition['No unconfirmed role available for email confirmation.'] = 'سائٹ کو ای میل کی توثیق کے استعمال کے ل default ڈیفالٹ قسم "غیر مصدقہ" کے ساتھ کردار کی ضرورت ہے۔ براہ کرم اس ترتیب کو فعال کرنے کیلئے ایک شامل کریں۔';

$Definition['Old Theming UI'] = 'پرانا تیمنگ UI';
$Definition['Once enabled, only members will see inside your community.'] = 'ایک بار فعال ہوجانے کے بعد ، آپ کی برادری میں صرف ممبران ہی نظر آئیں گے۔';
$Definition['OrgDescription'] = 'آپ کی تنظیم کا نام SEO مائکرو ڈیٹا اور JSON + LD کے لئے استعمال کیا جاتا ہے';
$Definition['Outline'] = 'خاکہ';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'زیر نظر آراء نظریات یا تھیمککس کے غیر منفی ضمنی اثرات ہو سکتے ہیں اور ان کا پیش نظارہ نہیں کیا جاتا ہے۔';

$Definition['Password.MinLength'] = 'پاس ورڈ بنانے اور دوبارہ ترتیب دینے والے صفحات پر صارفین کے پاس ورڈز کے لیے حروف کی کم از کم لمبائی کی اجازت ہے۔';
$Definition['Please choose an authenticator to configure.'] = 'براہ کرم کنفیگر کرنے کے لئے ایک مصدقہ منتخب کریں۔';
$Definition['PluginHelp'] = 'پلگ ان آپ کو اپنی سائٹ میں فعالیت شامل کرنے کی اجازت دیتے ہیں۔ <br /> ایک بار جب آپ کے %s فولڈر میں پلگ ان شامل ہوجائے تو آپ اسے یہاں فعال یا غیر فعال کرسکتے ہیں۔';
$Definition['Pockets.BetweenDiscussions.Description'] = 'اہم گفتگو کی فہرست میں ہر گفتگو کے درمیان جیب دکھائی جاتی ہے۔ چونکہ گفتگو عام طور پر <li> .. </li> ٹیگز میں ہوتی ہے ، لہذا آپ کو بھی اپنی ٹیب میں اپنی جیب سمیٹنے کی ضرورت ہوگی۔';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'جیبز آپ کو اطلاق کے آس پاس کے مختلف مقامات پر فری فارم ایچ ٹی ایم ایل شامل کرنے کی اجازت دیتی ہیں۔';
$Definition['Preset'] = 'پیش سیٹ کریں';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'اپنے مباحثوں اور تبصروں کی تعداد کو محدود کرکے اپنے فورم پر اسپام کو روکیں جو صارفین مقررہ مدت میں پوسٹ کرسکتے ہیں۔';
$Definition['Primary Button'] = 'پرائمری بٹن';
$Definition['Primary Buttons'] = 'پرائمری بٹن';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'ونیلا کے لئے تھیمز تخلیق کرنے کیلئے کوئٹ اسٹارٹ گائیڈ';
$Definition['Quick Links is a default component on community pages.'] = 'کوئیک لنکس کمیونٹی پیجز پر ڈیفالٹ جزو ہے۔ ہمارے تھیم ایڈیٹر کا استعمال کرتے ہوئے اس مینو سے روابط کو شامل ، ترمیم یا چھپانے کے لیے ہمارے نئے کوئیک لنکس جزو کو فعال کریں۔';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'ورڈپریس کے لئے تیار میڈ ونیلہ تبصرے پلگ ان';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'ورڈپریس کے لئے تیار میڈ وینیلا فورم پلگ ان';
$Definition['Realtime progress bars: %s'] = 'ریئل ٹائم پروگریس بار: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'ماڈریٹرز اور ایڈمنسٹریٹرز کے ل special خصوصی پوزیشن حاصل کرنا اچھا خیال ہے تاکہ آپ کی برادری آسانی سے یہ دیکھ سکے کہ انچارج کون ہے۔';
$Definition['Recommend starting with five ranks.'] = 'آپ بہت ساری صفیں حاصل نہیں کرنا چاہتے۔ ہم پانچ سے شروع کرنے کی سفارش کرتے ہیں۔ اگر آپ کی برادری واقعی بڑی ہے تو آپ مزید شامل کرسکتے ہیں۔';
$Definition['Requires “Flag” reaction permission.'] = '"پرچم" رد عمل کی اجازت کی ضرورت ہے۔';
$Definition['Requires “Negative” reaction permission.'] = '"منفی" رد عمل کی اجازت کی ضرورت ہے۔';
$Definition['Requires “Positive” reaction permission.'] = '"مثبت" رد عمل کی اجازت کی ضرورت ہے۔';
$Definition['Restoring your selection removes the items from this list.'] = 'جب آپ بازیافت کرتے ہیں تو ، اس فہرست سے آئٹمز کو ہٹا دیا جاتا ہے اور سائٹ پر واپس ڈال دیا جاتا ہے۔';
$Definition['RichEditor.QuoteEnable.Notes'] = 'رچ ایڈیٹر کے حوالے درج کرنے کے لئے درج ذیل آپشن کا استعمال کریں۔ یہ تبھی لاگو ہوگا جب ڈیفالٹ فارمیٹر "رچ" ہو۔';
$Definition['Route Expression'] = 'روٹ اظہار';
$Definition['Routes are used to redirect users.'] = 'مطلوبہ یو آر ایل کے لحاظ سے صارفین کو ری ڈائریکٹ کرنے کیلئے راستوں کا استعمال کیا جاتا ہے۔';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'اس کردار کے حامل تمام صارفین کو دیکھنے کے لئے نام کے ذریعہ صارفین کی تلاش کریں یا کسی کردار کا نام درج کریں۔';
$Definition['Secondary Button'] = 'ثانوی بٹن';
$Definition['Secondary Buttons'] = 'ثانوی بٹن';
$Definition['Security.Hsts.HTTPSWarning'] = 'انتباہ: صرف اس خصوصیت کو قابل بنائیں اگر آپ کو یقین ہے کہ آپ کے سب ڈومینز درست سرٹیفکیٹ کے ساتھ HTTPS کے لئے تشکیل شدہ ہیں۔';
$Definition['Security.Hsts.IncludeSubDomains'] = 'جب فعال ہوجاتا ہے تو ، یہ اصول آپ کی سائٹ کے سب ڈومینز پر بھی لاگو ہوتا ہے۔';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'ایک بار جب آپ اپنی سائٹ کو توقع کے مطابق کام کرتے ہوئے دیکھتے ہیں تو ہم زیادہ سے زیادہ عمر 1 ہفتہ کی عمر کے ساتھ شروع کرنے اور پھر اسے 1 ماہ پھر 1 سال تک بڑھانے کی سفارش کرتے ہیں۔';
$Definition['Security.Hsts.SubmitWarning'] = 'انتباہ: ایک بہترین عمل کے طور پر HSTS پری لوڈنگ کی حمایت کرنا بہت اچھا ہے۔ تاہم ، آپ کو یقینی بنانا ہے کہ وہ پہلے سے لوڈ ہو چکی ہے (یعنی مطلوبہ ترتیب کے لئے مکمل تحفظ حاصل کرنے کے ل.) اپنی سائٹ کو ہٹسٹری لوڈ ڈاٹ آرگ پر جمع کروائے۔';
$Definition['See the documentation'] = 'دستاویزات دیکھیں';
$Definition['Select the default type for this role, if any.'] = 'اس کردار کے لئے پہلے سے طے شدہ قسم کا انتخاب کریں ، اگر کوئی ہے تو۔';
$Definition['Select the import source'] = 'درآمد کا منبع منتخب کریں';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'سیریلائزڈ کالم "%s" غیر سیزریل ہونے میں ناکام رہا۔';
$Definition['Session Timeout'] = 'دورانیہ ختم ہو گیا';
$Definition['Shadowed'] = 'شیڈو';
$Definition['ShareImageDescription'] = 'جب کوئی آپ کی سائٹ سے کوئی لنک شیئر کرتا ہے تو ہم کوشش کرتے ہیں اور پیج سے ایک تصویر لے لیں۔ اگر صفحے پر کوئی تصویر نہیں ہے تو ہم اس کی بجائے اس کی تصویر استعمال کریں گے۔ تصویر کم از کم 50 × 50 ہونی چاہئے ، لیکن ہم 200 × 200 کی سفارش کرتے ہیں۔';
$Definition['Show all possible pocket locations.'] = 'جیب کے تمام ممکنہ مقامات کو دکھانے کے لئے اس آپشن کو آن کریں۔ اس آپشن کو آن کرنے سے صرف وہ مقامات دکھائے جائیں گے جو جیب کا انتظام کرسکیں۔';
$Definition['Solid'] = 'ٹھوس';
$Definition['Some older themes don\'t support full editing capability.'] = 'کچھ پرانے موضوعات مکمل ترمیم کی اہلیت کی حمایت نہیں کرتے ہیں۔ ایک تھیم کس چیز کی تائید کرتی ہے یہ دیکھنے کے ل you آپ اس کے نام پر گھوم سکتے ہیں تاکہ یہ دیکھیں کہ ترمیمات کہاں سے اثر پذیر ہوں گی۔';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'درج ذیل زمرے کے ساتھ کام کرنے کے لئے کچھ تھیمز کو اپ ڈیٹ کرنے کی ضرورت پڑسکتی ہے۔ اپنے تھیم کو اپ ڈیٹ کرتے وقت آپ اس خصوصیت کو غیر فعال کرسکتے ہیں۔';
$Definition['Sometimes you want to embed your Vanilla site'] = 'بعض اوقات آپ اپنی ونیلا سائٹ کو کسی دوسری سائٹ کے اندر سرایت کرنا چاہتے ہیں۔ ونیلا کا ایمبیڈ سسٹم اس کے لیے ایک آسان طریقہ پیش کرتا ہے۔ ایمبیڈڈ سائٹ کا استعمال کرتے وقت کارکردگی کا سودا ہوتا ہے، اس لیے متبادلات اور مثالی استعمال کے کیسز کے لیے دستاویزات چیک کریں۔';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'خصوصی پابندی: صرف گارڈن کی اجازت کے صارفین۔';
$Definition['Specify a partial or full match when creating a ban.'] = 'پابندی کے وقت جزوی یا مکمل میچ کی وضاحت کریں۔';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'اپنی سائٹ کو یہاں کس طرح بیان کرتے ہیں اس کے بارے میں سوچنے میں تھوڑا سا وقت گزاریں۔ آپ کی ویب سائٹ کو ایک معنی خیز عنوان اور مختصر تفصیل دینے سے سرچ انجنوں میں آپ کی پوزیشن میں مدد مل سکتی ہے۔';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'لوگو شامل کرکے اور رنگوں کی تخصیص کرکے اپنی ای میلز کو تیز کریں۔';
$Definition['Start Import'] = 'درآمد شروع کریں';
$Definition['Start the first discussion.'] = 'ابھی <a href="{/post/discussion,url}">پہلی بحث شروع کرکے</a> اپنی برادری میں بال رولنگ کرو۔';
$Definition['Subcommunities'] = 'ذیلی کمیونٹیز';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'ٹیگ کرنے سے صارفین کو ان مباحثوں میں ٹیگ شامل کرنے کی اجازت ملتی ہے تاکہ وہ انھیں مزید قابل فہم بنائیں۔';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'ٹیمپلیٹس معیاری موضوعات ہیں۔ انہیں تخصیص کرنے کے ل you ، آپ کو ایک کاپی بنانی ہوگی۔';
$Definition['The %s Authenticator does not have any custom configuration options.'] = '%s استنادک کے پاس حسب ضرورت کوئی ترتیب کے اختیارات نہیں ہیں۔';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB <0/> لیب کو آپ کے کسٹم تھیم سے ملنے کے لیے ترتیب دینے کی ضرورت ہے۔ یہ ہمارے نئے تھیم ایڈیٹر کا استعمال کرتے ہوئے کیا جا سکتا ہے۔ <1> مزید جانیں۔</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'ایڈون کو اہل نہیں کیا جا سکا کیونکہ اس نے مہلک خرابی پیدا کی ہے۔ <pre style=";text-align:right;direction:rtl"> %s </pre>';
$Definition['The addon has already been downloaded.'] = 'ایڈون پہلے ہی ڈاؤن لوڈ ہوچکا ہے۔';
$Definition['The banner logo appears at the top of your forum.'] = 'بینر کا لوگو آپ کے فورم کے اوپری حصے میں آتا ہے۔';
$Definition['The banner title appears on the top-left of every page.'] = 'بینر کا عنوان ہر صفحے کے اوپر بائیں طرف ظاہر ہوتا ہے۔';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'بینر کا عنوان آپ کی سائٹ کے بینر اور آپ کے براؤزر کے ٹائٹل بار میں ظاہر ہوتا ہے۔ اس میں 20 حرف سے کم ہونا چاہئے۔ اگر بینر کا لوگو اپ لوڈ ہوتا ہے تو ، اس صارف کے سامنا والے فورم کے صفحات پر بینر کا عنوان بدل دے گا۔ نیز ، ذہن میں رکھنا کچھ موضوعات اس عنوان کو بھی چھپا سکتے ہیں۔';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>بنیادی رجسٹریشن فارم میں</strong> نئے صارفین کی <strong>ضرورت ہوتی ہے</strong> کہ وہ اسپیمرز کو سائٹ سے دور رکھنے کیلئے کیپچا کی تصویر سے متن کی کاپی کریں۔ آپ کو <a href="http://recaptcha.net/">recaptcha.net</a> پر ایک اکاؤنٹ کی ضرورت ہے۔ سائن اپ کرنا مفت اور آسان ہے۔ ایک بار دستخط کرنے کے بعد ، یہاں واپس آجائیں اور درج ذیل ترتیبات درج کریں۔';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'آپ کے بیان کردہ ڈیٹا بیس صارف کے پاس ڈیٹا بیس تک رسائی کی اجازت نہیں ہے۔ کیا آپ نے ابھی تک ڈیٹا بیس بنایا ہے؟ ڈیٹا بیس کی اطلاع: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'آپ کے ڈیٹا بیس کے لئے درج ذیل ڈھانچے میں تبدیلی کی ضرورت ہے۔';
$Definition['The import file does not contain any data.'] = 'درآمد فائل میں کوئی اعداد و شمار شامل نہیں ہیں۔';
$Definition['The import file is not in the correct format.'] = 'امپورٹ فائل صحیح شکل میں نہیں ہے۔';
$Definition['The location of the authentication endpoint.'] = 'توثیق کے آخری نقطہ کا مقام۔';
$Definition['ThemeHelp'] = 'تھیمز آپ کو اپنی سائٹ کی شکل و صورت کو تبدیل کرنے کی اجازت دیتے ہیں۔ <br /> ایک بار جب آپ کے %s فولڈر میں ایک تھیم شامل ہوجائے تو ، آپ اسے یہاں فعال کرسکتے ہیں۔';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'تھیم کا پیش نظارہ مرکزی خیال ، موضوع کے سانچے اور CSS کی نمائش تک محدود ہے۔';
$Definition['Theming Guide'] = 'تھیمنگ گائیڈ';
$Definition['The New Embed System'] = 'نیا ایمبیڈ سسٹم';
$Definition['The new embed system has improved performance.'] = 'نئے ایمبیڈ سسٹم نے کارکردگی کو بہتر بنایا ہے، اسکرولنگ کے رویے کو بہتر بنایا ہے، اور پرانے سسٹم کے مقابلے زیادہ مستقل رویہ ہے۔ فی الحال تبصرہ اور ورڈپریس ایمبیڈ نئے ایمبیڈ سسٹم میں غیر تعاون یافتہ ہیں۔';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'پاس ورڈ کی توثیق کرنے والے کے پاس کوئی حسب ضرورت ترتیب کے اختیارات نہیں ہیں۔';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'ڈیٹا بیس کے ڈھانچے میں تبدیلی کی ضرورت نہیں ہے۔ تاہم ، اعداد و شمار میں تبدیلی ہوسکتی ہے۔';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'درخواست میں دو قسم کے بٹن ہیں: پرائمری اور سیکنڈری۔';
$Definition['The route was saved successfully.'] = 'راستہ کامیابی کے ساتھ محفوظ کر لیا گیا۔';
$Definition['The text of the pocket.'] = 'جیب کا متن درج کریں۔ یہ آپ کے ٹائپ کرتے وقت ٹھیک ہوگا۔ لہذا یہ یقینی بنائیں کہ آپ درست HTML داخل کریں گے۔';
$Definition['The user table was not in the import file.'] = 'صارف کی میز درآمد فائل میں نہیں تھی۔';
$Definition['The Vanilla 2 Exporter'] = 'ونیلا 2 ایکسپورٹر';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'ونیلا شماریات آپ کے فورم کے ڈیش بورڈ کو تجزیاتی رپورٹنگ کے آلے میں بدل دیتے ہیں ، اس سے آپ کو مخصوص فورم کے اوقات میں اپنے فورم پر سرگرمی کا جائزہ لینے کی اجازت مل جاتی ہے۔ آپ ہماری دستاویزات <a href="http://vanillaforums.org/docs/vanillastatistics">میں ونیلا شماریات کے بارے میں مزید پڑھ</a> سکتے <a href="http://vanillaforums.org/docs/vanillastatistics">ہیں</a> ۔';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'وہ بھی باقاعدہ تھیمز کی طرح کام کرتے ہیں۔ ایک بار جب کسی کو تھیمز کے فولڈر میں شامل کرلیا جاتا ہے ، تو آپ اسے یہاں فعال کرسکتے ہیں۔';
$Definition['This is a style guide of your theme.'] = 'یہ آپ کے تھیم کا ایک اسٹائل گائیڈ ہے۔ اس میں پوری ایپلی کیشن میں استعمال ہونے والے بصری عناصر کی مثالیں ہیں۔ آپ مختلف وجیٹس پر کلک کر سکتے ہیں جیسے <0> ٹائٹل بار </0> یا <1> بینر </1> سائیڈ پینل میں ان کی خصوصیات میں ترمیم کرنے کے لئے۔';
$Definition['This is the administrative dashboard for your new community.'] = 'یہ آپ کی نئی برادری کا انتظامی ڈیش بورڈ ہے۔ کنفیگریشن کے اختیارات کو ایک طرف چیک کریں۔ وہاں سے آپ تشکیل دے سکتے ہیں کہ آپ کی کمیونٹی کس طرح کام کرتی ہے۔ <b>پہلے سے طے شدہ طور پر ، صرف "ایڈمنسٹریٹر" کے کردار میں شامل صارفین ہی آپ کی برادری کا یہ حصہ دیکھ سکتے ہیں۔</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'یہ وہ جگہ ہے جہاں آپ وینیلا کی نئی خصوصیات ، صفحات اور اجزاء کو چالو اور جانچ سکتے ہیں۔';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'اس لیب کو غیر فعال نہیں کیا جا سکتا کیونکہ حسب ضرورت لے آؤٹ لاگو ہے۔';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'اس لیب کو غیر فعال نہیں کیا جا سکتا کیونکہ یہ موجودہ تھیم کی ضرورت ہے۔';
$Definition['This option shows/hides the locations where pockets can go.'] = 'یہ اختیار ان مقامات کو دکھاتا ہے / چھپا دیتا ہے جہاں جیب جاسکتی ہے ، لیکن صرف ان صارفین کے لئے جو جیبیں شامل کرنے / ترمیم کرنے کی اجازت رکھتے ہیں۔ مقامات کو دکھانے کی کوشش کریں اور پھر اپنی سائٹ دیکھیں۔';
$Definition['This page lists the endpoints of your API.'] = 'یہ صفحہ آپ کے API کے آخری نکات کی فہرست دیتا ہے۔ مزید معلومات کے لئے اختتامی مقامات پر کلک کریں۔ آپ اس صفحے سے یا بیرونی طور پر رسائی ٹوکن کا استعمال کرکے API پر براہ راست کال کرسکتے ہیں۔';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'یہ کردار ذاتی معلومات ہے۔ صرف وہ صارفین جو ذاتی معلومات کو دیکھنے کی اجازت رکھتے ہوں گے۔';
$Definition['This setting loads the page before executing Javascript.'] = 'یہ ترتیب جاوا اسکرپٹ پر عمل کرنے سے پہلے پیج کو بوجھ دیتی ہے جو آپ کے SEO کو بہتر بنا سکتی ہے۔ <br> <strong>** انتباہ: اس خصوصیت کو چالو کرنے سے آپ کی ویب سائٹ پر جاوا اسکرپٹ کی غلطیاں ہوسکتی ہیں۔ **</strong>';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'اس تھیم کو حذف نہیں کیا جاسکتا کیونکہ یہ فی الحال اطلاق شدہ تھیم ہے۔';
$Definition['Tiled Layout'] = 'ٹائلڈ لے آؤٹ۔';
$Definition['Title Bar'] = 'عنوان بار';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'اپنی ویب سائٹ میں اپنے ونیلا فورم کو سرایت کرنے کے لئے ، درج ذیل کوڈ کا استعمال کریں۔';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'بہت سارے پتے! ہم ایک بار میں %s پتے بھیجیں گے۔';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'بدسلوکی سے بچنے کے ل some ، کچھ ٹولز خودبخود مواد کو چھپاتے ہیں اور یہاں اس وقت کی فہرست بناتے ہیں جب تک کہ اسے کسی ناظم کے ذریعہ دستی طور پر منظوری نہیں مل جاتا ہے۔';
$Definition['TouchIconDescription'] = 'ٹچ آئیکن ظاہر ہوتا ہے جب آپ ایپل ڈیوائس کے ہوم اسکرین پر کسی ویب سائٹ کو بک مارک کرتے ہیں۔ یہ عام طور پر 152 پکسلز ہیں۔ ایپل گول کونے اور روشنی کا اثر خود بخود شامل کرتا ہے۔';
$Definition['Transparent'] = 'شفاف';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'ٹویٹر کنیکٹ صارفین کو اپنے ٹویٹر اکاؤنٹ کا استعمال کرکے سائن ان کرنے کی اجازت دیتا ہے۔ <b>اس پلگ ان کے کام کرنے کے ل Twitter آپ کو اپنی درخواست ٹویٹر کے ساتھ رجسٹر کرنی ہوگی۔</b>';

$Definition['Usercards'] = 'یوزر کارڈز۔';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'یوزر کارڈ آپ کو صارف کی معلومات کا فوری ان لائن سنیپ شاٹ حاصل کرنے کی اجازت دیتا ہے۔ پوسٹس اور لیڈر بورڈز کو دیکھتے وقت ، صارف نام پر کلک کریں تاکہ کارڈ کو صفحے سے دور تشریف لائے بغیر صارفین کی بنیادی پروفائل کی معلومات کو دکھایا جا سکے۔ اپنے فیچر کو اپنے کسٹم تھیم میں یوزر کارڈز شامل کرنے کے لیے اس فیچر کو فعال کریں۔';
$Definition['User inputs are based on the global background and text colors.'] = 'صارف کے آدانوں کا رنگ عالمی پس منظر اور متن کے رنگوں پر مبنی ہے۔';
$Definition['User Profile'] = 'صارف کا پروفائل';
$Definition['Users may sign into your site using their Twitter account.'] = 'صارفین اپنے ٹویٹر اکاؤنٹ کا استعمال کرکے آپ کی سائٹ میں سائن ان کرسکتے ہیں۔';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'پابندی کا اصول بنانے کے لئے صفحے کے اوپری حصے کے بٹن کا استعمال کریں۔';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'اپنے بلاگ پر وینیلا تبصرے مرتب کرنے کے لئے ورڈپریس پلگ ان کا استعمال کریں ، یا کسی دوسرے پلیٹ فارم پر ونیلا تبصرے مرتب کرنے کے لئے آفاقی کوڈ کا استعمال کریں۔';

$Definition['Vanilla\'s new search service is finally here.'] = 'ونیلا کی نئی سرچ سروس آخر کار یہاں ہے۔ ممبر سرچ ، سرچ سرچنگ اور ٹرم ہائی لائٹنگ جیسی نئی سرچ فیچرز تک رسائی حاصل کرنے کے لیے ہمارے نئے سرچ پیج UI کو فعال کریں۔';
$Definition['Vanilla Export: %s, Source: %s'] = 'ونیلا ایکسپورٹ: %s ، ماخذ: %s';
$Definition['Vanilla Labs'] = 'ونیلا لیبز۔';
$Definition['Vanilla Statistics are currently disabled'] = 'ونیلا کے شماریات فی الحال غیر فعال ہیں';
$Definition['Verify and restore'] = 'تصدیق کریں اور بحال کریں';
$Definition['VerifyUser'] = 'صارف کے پاس والے باکس کو نشان زد کریں <b>تاکہ انہیں تصدیق شدہ کے</b> طور پر نشان زد کیا جا سکے تاکہ ان کی پوسٹس دوبارہ سپام کے طور پر نشان زد نہ ہوں۔ اس سے ان کی تمام زیر التوا پوسٹس بھی بحال ہو جائیں گی۔';
$Definition['Video tutorial on advanced settings'] = 'اعلی درجے کی ترتیبات سے متعلق ویڈیو ٹیوٹوریل';
$Definition['Video tutorial on finding &amp; managing users'] = 'صارفین کو تلاش کرنے اور ان کا انتظام کرنے سے متعلق ویڈیو ٹیوٹوریل';
$Definition['Video tutorial on managing appearance'] = 'ظاہری انتظام کے بارے میں ویڈیو ٹیوٹوریل';
$Definition['Video tutorial on managing categories'] = 'زمرے کے انتظام سے متعلق ویڈیو ٹیوٹوریل';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'کرداروں اور اجازتوں کے نظم و نسق سے متعلق ویڈیو ٹیوٹوریل';
$Definition['Video tutorial on user registration'] = 'صارف کے اندراج سے متعلق ویڈیو ٹیوٹوریل';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'انتباہ: اس خصوصیت کو فعال کرنے سے آپ کی ویب سائٹ پر جاوا اسکرپٹ کی خرابیاں ہوسکتی ہیں۔';
$Definition['Warning: Loading tables can be slow.'] = '<b>انتباہ</b> : آپ کی سرور ترتیب میں فاسٹ ڈیٹا لوڈنگ کا تعاون نہیں ہے۔ اگر آپ بہت بڑی فائل درآمد کر رہے ہیں (جیسے 200،000 تبصرے) تو آپ اپنی تشکیل تبدیل کرنے پر غور کرنا چاہتے ہو۔ مزید معلومات کے لئے <a href="http://vanillaforums.com/porter">یہاں</a> کلک کریں۔';
$Definition['Warning: This is for advanced users.'] = '<b>انتباہ</b> : یہ اعلی درجے کی صارفین کے لئے ہے اور اس کی ضرورت ہے کہ آپ اپنے ویب سرور میں اضافی تبدیلیاں کریں۔ یہ عام طور پر صرف اس صورت میں دستیاب ہوتا ہے جب آپ کے پاس وقف شدہ یا وی پی ایس ہوسٹنگ ہو۔ اگر آپ نہیں جانتے کہ آپ کیا کر رہے ہیں تو اس کی کوشش نہ کریں۔';
$Definition['Webhooks'] = 'ویب ہکس۔';
$Definition['Welcome to Labs!'] = 'لیبز میں خوش آمدید!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'ونیلا کے تیاری کرنے والے UI میں خوش آمدید۔ اس صفحے میں آپ کے تمام دستیاب تھیمز کی فہرست دی گئی ہے ، اور آپ کو ان میں کاپی یا ترمیم کرنے کی سہولت دیتی ہے۔';
$Definition['Welcome To Your Theme'] = 'آپ کے تھیم میں خوش آمدید';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'ہم شرکت کی حوصلہ افزائی کے لئے زیادہ تر مثبت رد عمل کی سفارش کرتے ہیں۔';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'فعال ہونے پر ، آپ ان مصنوعات کے ذریعہ مصنوعات ، اور گروپ ذیلی کمیونٹیوں کا نظم کرسکتے ہیں۔';
$Definition['When you select Full Bleed, your background is transparent.'] = 'جب آپ فل بلیڈ منتخب کرتے ہیں تو ، آپ کا پس منظر شفاف ہوتا ہے۔';
$Definition['Which reactions you use really depends on your community.'] = 'آپ کون سے رد عمل کا استعمال کرتے ہیں وہ واقعی آپ کی برادری پر منحصر ہوتا ہے ، لیکن ہم تجویز کرتے ہیں کہ کچھ نکات کو دھیان میں رکھیں۔';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'آپ ایک نیا لے آؤٹ آپشن لاگو کرنے والے ہیں۔ ہمارے تھیم ایڈیٹر کا استعمال کرتے ہوئے اسے اپنی مرضی کے مطابق اور پیش نظارہ کیا جاسکتا ہے۔ <0> مزید جانیں</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'آپ "111.111.111" کے ساتھ متعارف IP IP پتے والے تمام صارفین پر "111.111.111. *" کی قدر کے ساتھ IP قسم کی پابندی شامل کرکے پابندی عائد کرسکتے ہیں۔';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'آپ IP پتوں ، ای میل پتوں اور صارف ناموں پر پابندی عائد کرسکتے ہیں۔';
$Definition['You can choose from one of the different styles this theme offers.'] = 'آپ اس تھیم کے پیش کردہ مختلف اسٹائل میں سے ایک میں سے انتخاب کرسکتے ہیں۔';
$Definition['You can configure some values differently for different screensizes.'] = 'آپ مختلف اسکرینز کے ل some کچھ قدروں کو مختلف طریقے سے تشکیل دے سکتے ہیں۔';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'آپ متعدد سائٹوں سے رابطہ قائم کرسکتے ہیں جو jsConnect کی حمایت کرتے ہیں۔';
$Definition['You can place files in your /uploads folder.'] = 'اگر آپ کی فائل براہ راست اس صفحے پر اپ لوڈ کرنے کے لئے بڑی ہے تو آپ اسے اپنے / اپ لوڈز فولڈر میں رکھ سکتے ہیں۔ اس بات کو یقینی بنائیں کہ فائل کا نام لفظ <b>برآمد کے</b> ساتھ شروع ہوتا ہے اور <b>.txt ، .gz میں</b> سے کسی ایک پر ختم ہوتا ہے۔';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'آپ مختصر پوسٹس کی حوصلہ شکنی کے لئے پوسٹ کی کم از کم لمبائی بیان کرسکتے ہیں۔';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'آپ اپنے تھیمنگ سسٹم میں کسٹم فونٹ اپ لوڈ کرسکتے ہیں۔ صرف کاپی اور فیلڈ میں یو آر ایل چسپاں کریں۔';
$Definition['You must select a file to import.'] = 'درآمد کے ل You آپ کو ایک فائل کا انتخاب کرنا چاہئے۔';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'آپ کو فونٹ یو آر ایل کے ڈومین کو <0> اجازت شدہ ڈومینز میں شامل کرنے کی ضرورت ہے </0> سائٹ کی ترتیب میں۔ <1> کسٹم فونٹس کے بارے میں مزید معلومات حاصل کریں۔ </1>';
$Definition['Your mobile theme will be disabled.'] = 'آپ کا موبائل تھیم غیر فعال ہوجائے گا۔ موبائل اور ڈیسک ٹاپ کے مختلف تھیمز مرتب کرنے کیلئے ، پرانا تیمنگ UI استعمال کریں۔';
