<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s نے %4$s کی رکنیت کا دعوت نامہ قبول کرلیا ہے۔';
$Definition['%1$s changed %4$s permissions.'] = '%1$s نے %4$s کے اختیارات میں تبدیلی کی ہے۔';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s نے %6$s کی نمائیندہ تصویر تبدیل کر دی ہے۔';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s نے %4$s %8$s پر تبصرہ کیا ہے۔';
$Definition['%1$s created an account for %4$s.'] = '%1$s نے %4$s  کےلئے کھاتہ بنایا ہے۔';
$Definition['%1$s joined.'] = '%1$s نے شرکت کی';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s نے %3$s کا %8$s میں تذکرہ کیا ہے۔';
$Definition['%1$s on %2$s'] = '%1$s پر %2$s';
$Definition['%1$s signed in.'] = '%1$s نے سائن ان کیا۔';
$Definition['%1$s to %2$s'] = '%1$s سے %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s سے %2$s از %3$s ';
$Definition['%1$s updated %6$s profile.'] = '%1$s نے %6$s  کوائف کی تجدید کی۔';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s کو %2$s %3$s شامل کر لیا گیا ہے۔';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s کو%2$s %3$s سے بے دخل کر دیا گیا۔';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s کو %2$s %3$s سے نکال کر %4$s %5$s میں شامل کر دیا گیا ہے۔';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s نے %4$s %5$s پر لکھا۔';
$Definition['%3$s approved %2$s membership application.'] = '%3$sنے  %2$s کی رکنیت کی درخواست قبول کر لی۔';
$Definition['%3$s created an account for %1$s.'] = '%3$s نے %1$s کےلئے کھاتہ بنایا۔';
$Definition['%s$1 to %s$2'] = '%s$1 سے %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 سے %s$2 از %s$3';
$Definition['%s (Current)'] = '%s (موجودہ)';
$Definition['%s Agrees'] = '%s متفق ہے۔';
$Definition['%s and you'] = '%s اور آپ';
$Definition['%s Awesomes'] = '%s زبردست';
$Definition['%s changed %s\'s permissions.'] = '%s نے %s کے اختیارات میں تبدیلی کی ہے۔';
$Definition['%s Comment'] = '%s تبصرہ';
$Definition['%s comment'] = '%s تبصرہ';
$Definition['%s comment html'] = '%s تبصرہ';
$Definition['%s Comments'] = '%s تبصرے';
$Definition['%s comments'] = '%sتبصرے';
$Definition['%s comments html'] = '%sتبصرے';
$Definition['%s deleted this conversation.'] = '%s نے یہ مکالمہ حذف کر دیا ہے۔';
$Definition['%s discussion'] = '%s  مباحثہ';
$Definition['%s discussion html'] = '%s  مباحثہ';
$Definition['%s discussions'] = '%s  مباحثے';
$Definition['%s discussions html'] = '%s  مباحثے';
$Definition['%s has been Jailed.'] = '%s کو مقید کر دیا گیا۔';
$Definition['%s has left this conversation.'] = '%s نے گفتگو ترک کر دی۔';
$Definition['%s Insightfuls'] = '%s دوراندیش';
$Definition['%s Likes'] = '%s پسندیدہ';
$Definition['%s LOLs'] = '%s پر مزاح';
$Definition['%s mentioned %s in a %s.'] = '%s نے %s کا %s میں تذکرہ کیا۔';
$Definition['%s message'] = '%s پیغام';
$Definition['%s messages'] = '%s پیغامات';
$Definition['%s New'] = '%s نیا';
$Definition['%s new'] = '%s نئے';
$Definition['%s new comment since you last read this.'] = 'آپ کے آخری بار اسے پڑھنے کے بعد %s تبصرہ نیا آیا ہے۔';
$Definition['%s new comments since you last read this.'] = 'آپ کے آخری بار اسے پڑھنے کے بعد %s تبصرے نئے آئے ہیں۔';
$Definition['%s New Plural'] = '%s نئے';
$Definition['%s new plural'] = '%s نیا';
$Definition['%s Not Found'] = '%s نہیں ملا';
$Definition['%s Point'] = '%s پوائینٹ';
$Definition['%s point'] = '%s  نقطہ';
$Definition['%s Points'] = '%s کے پوائنٹس';
$Definition['%s points'] = '%s پوائنٹس';
$Definition['%s said'] = '%s نےکہا';
$Definition['%s said:'] = '%s نے کہا:';
$Definition['%s tag(s) found.'] = '%s ٹیگ(s)ملے۔';
$Definition['%s tags in the system'] = 'سسٹم میں %s ٹیگ ہیں۔';
$Definition['%s Up Votes'] = '%s مثبت ووٹ';
$Definition['%s view'] = '%s نظارہ';
$Definition['%s view html'] = '%s نظارہ';
$Definition['%s views'] = '%sنظارے';
$Definition['%s views html'] = '%sنظارے';
$Definition['%s votes'] = '%s ووٹ';
$Definition['%s was removed from the %s and added to the %s'] = '%s کو %s میں سے بے دخل کر کے %s میں شامل کردیا گیا ہے۔';

$Definition['(empty message)'] = '(خالی پیغام)';

$Definition['+%s Guests'] = '+ %s مہمان';

$Definition[' - Page %s'] = ' - صفحہ %s';

$Definition['1 message'] = '1 پیغام';

$Definition['<General Error>'] = '<عمومی نقص>';

$Definition['[%1$s] Membership Approved'] = '[%1$s] رکنیت منظورکر لی گئی';
$Definition['[%s] Welcome Aboard!'] = '[%s] ہمارے فورم پر خوش آمدید!';
$Definition['[Deleted User]'] = '[حذف شدہ رکن]';

$Definition['About'] = 'بارے میں';
$Definition['Abuse'] = 'بداخلاقی';
$Definition['Accept'] = 'قبول';
$Definition['Accept this answer.'] = 'اس جواب کو منظور کریں';
$Definition['Account Options'] = 'کھاتے کے اختیارات';
$Definition['Activate'] = 'فعال';
$Definition['Active'] = 'سرگرم';
$Definition['Active Users'] = 'فعال اراکین';
$Definition['Activity'] = 'سرگرمی';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$sنے  %4$s %8$s.قبول کر لیا';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s نےآپ کی%8$s پر تبصرہ کیاہے۔';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s نے آپ کے %8$s پر تبصرہ کیا ہے۔';
$Definition['Activity.Comment'] = 'تبصرہ';
$Definition['Activity.CommentMention.FullHeadline'] = '%s1$s نے %3$s کا %8$s میں تذکرہ کیا ہے۔';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%s1$s نے %3$s کا %8$s میں تذکرہ کیا ہے۔';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s نے آپ کو %8$s بھیجا ہے۔';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s نے آپ کو %8$s بھیجا ہے۔';
$Definition['Activity.Join.FullHeadline'] = '%1$s نےشرکت کی۔';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s نے شرکت کی۔';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s نے %6$s کی نمائیندہ تصویر تبدیل کی ہے۔';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s نے %6$s کی نمائیندہ تصویر تبدیل کی ہے۔';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s نے %4$s %8$s کا جواب دے دیا ہے۔';
$Definition['Add'] = 'شامل کریں';
$Definition['Add a Comment'] = 'تبصرہ شامل کریں';
$Definition['Add a Message'] = 'پیغام شامل کریں';
$Definition['Add another poll option ...'] = 'رائے شماری کیلئے ایک اور آپشن کا اضافہ کریں۔';
$Definition['Add a Profile Picture'] = 'نمائندہ تصویر لگائیں';
$Definition['Add a Warning'] = 'تنبیہ کریں';
$Definition['Add Badge'] = 'امتیازی نشان شامل کریں';
$Definition['Add Comment'] = 'تبصرہ کریں';
$Definition['Add Cost'] = 'اہمیت شامل کریں';
$Definition['Add Image'] = 'تصویر لگائیں';
$Definition['Add Message'] = 'پیغام شامل کریں';
$Definition['Add People to this Conversation'] = 'اس گفتگو میں مزید لوگ شامل کریں';
$Definition['Add Route'] = 'روٹ شامل کریں';
$Definition['Admin'] = 'منتظم اعلیٰ';
$Definition['Administrator Activity'] = 'منتظمیں کی سرگرمی';
$Definition['administrators'] = 'منتظمین';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'اس درخواست پر عمل درآمد کے دوران ایک اچانک نقص آگیا ہے.<br />The server returned the following response: %s';
$Definition['Agree'] = 'متفق';
$Definition['Alert'] = 'ہوشیار باش';
$Definition['All %s'] = ' تمام %s ';
$Definition['All Bookmarks'] = 'تمام بک مارکس';
$Definition['All Categories'] = 'تمام زمرہ جات';
$Definition['All Conversations'] = 'تمام مکالمات';
$Definition['All Discussions'] = 'تمام مباحثے';
$Definition['Allow'] = 'اجازت دیں';
$Definition['Allow other members to see your email?'] = 'کیا آپ دوسرے اراکین کو اجازت دینا چاہتے ہیں کہ وہ آپ کا ای میل دیکھ سکیں؟';
$Definition['All Time Leaders'] = 'ہمیشہ سے سبقت یافتگان';
$Definition['Ancient Membership'] = 'قدیم رکنیت';
$Definition['An invitation has already been sent to the email you entered.'] = 'اس ای میل پر دعوت نامہ پہلے ہی بھیجا جا چکا ہے۔';
$Definition['Announce'] = 'اعلان';
$Definition['Announce...'] = 'اعلان کریں';
$Definition['Announcement'] = 'اعلان';
$Definition['Announcements'] = 'اعلانات';
$Definition['Announce this discussion'] = 'اس مباحثے کا اعلان کریں۔';
$Definition['Answer'] = 'جواب';
$Definition['answer'] = 'جواب';
$Definition['Answers'] = 'جوابات';
$Definition['Applicants'] = 'درخواست گزار';
$Definition['Apply Changes'] = 'تبدیلیاں لاگو کریں';
$Definition['Apply for Membership'] = 'رجسٹر';
$Definition['Apply for membership'] = 'رکنیت لیں';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'کیا آپ کو پورا یقین ہے کہ ایسا کرنا مناسب رہے گا؟';
$Definition['Are you sure you want to delete this %s?'] = 'کیا اس  %s کو واقعی آپ حذف کرنا چاہتے ہیں۔';
$Definition['Are you sure you want to do that?'] = 'آپ واقعی ایسا کرنا چاہتے ہیں؟';
$Definition['Are you sure you want to do this?'] = 'کیا آپ واقعی ایسا کرنا چاہتے ہیں؟';
$Definition['Are you sure you wish to continue?'] = 'کیا واقعی آپ اس کو جاری رکھنا چاہتے ہیں؟';
$Definition['Ask a Question'] = 'ایک سوال پوچھیں';
$Definition['Ask Question'] = 'سوال پوچھئیے';
$Definition['Attach a file'] = 'فائل منسلک کریں';
$Definition['Attachments'] = 'منسلکات';
$Definition['AttemptingSignOut'] = '%s آپ یہاں سے نکلنے کی کوشش کر رہے ہیں کیا واقعی آپ جانا چاہتے ہیں؟';
$Definition['available'] = 'دستیاب';
$Definition['Awaiting Moderation'] = 'اشاعت کیلئے منتظر';
$Definition['Awesome'] = 'زبردست';

$Definition['Back to Discussions'] = 'مسابقت کی طرف واپسی';
$Definition['Back to Profile'] = 'واپس کوائف نامے کی طرف';
$Definition['Badge'] = 'بیج';
$Definition['Badge404'] = 'کوئی  نشانِ امتیاز  نہیں ملا';
$Definition['Badges'] = 'نشانِ امتیاز';
$Definition['BadgesModuleTitle'] = 'تمغے';
$Definition['BadgesNobody'] = 'ابھی تک کسی آدمی کو یہ نشانِ امتیاز نہیں ملا';
$Definition['Ban'] = 'معطل';
$Definition['Ban.Action'] = 'پابند';
$Definition['Banned'] = 'معطل شدہ';
$Definition['Banned for being abusive.'] = 'غیر اخلاقی رویے کی بنیاد پر معطل';
$Definition['Banned for spamming.'] = 'فضولیات کی وجہ سے معطل';
$Definition['Banned users can no longer access the site.'] = 'معطل صارفین کی سائٹ تک رسائی ممکن نہیں۔';
$Definition['Ban User'] = 'پابند صارف';
$Definition['Ban Value'] = 'پابندی کی وجہ';
$Definition['Best Answer'] = 'بہترین جواب';
$Definition['Best Answers'] = 'بہترین جواب';
$Definition['Best Of'] = ' بہترین';
$Definition['Best Of...'] = 'بہترین از ۔۔۔';
$Definition['Blank Discussion Topic'] = 'خالی مباحثے کا عنوان';
$Definition['Blank Message'] = 'خالی پیغام';
$Definition['Body'] = 'مضمون';
$Definition['Bookmark'] = 'نشان زد';
$Definition['Bookmarked Discussions'] = 'بک مارک کئے گئے مباحثے';
$Definition['Bookmarks'] = 'نشان زدہ';
$Definition['bookmarks'] = 'نشانزد';
$Definition['By'] = 'از';
$Definition['by'] = 'از';
$Definition['by Date'] = 'از تاریخ';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'یہ فائل منسلک کرتے ہوئے آپ اس بات کی تصدیق کرتے ہیں کہ آپ کے پاس اس تصویر کو شائع کرنے کا اختیار ہے اور یہ قوانین و ضوابط سے متصادم نہیں ہے۔';

$Definition['Cancel'] = 'منسوخ';
$Definition['Casual'] = 'عمومی';
$Definition['Categories'] = 'زمرہ جات';
$Definition['CategoriesShowFollowed'] = 'صرف میرے زیر اقتداء زمرہ جات دکھائیں';
$Definition['CategoriesShowUnfollowed'] = 'اوجھل زمرہ جات بھی دکھائیں';
$Definition['CategoriesViewingAll'] = 'ابھی آپ تمام زمرہ جات دیکھ رہے ہیں۔';
$Definition['CategoriesViewingFollowed'] = 'ابھی آپ کو صرف وہی زمرہ جات دکھائی دے رہے ہیں جو آپ کی زیر اقتداء ہیں۔';
$Definition['Category'] = 'زمرہ';
$Definition['CategoryID'] = 'زمرہ';
$Definition['Category Management'] = 'انتظامیہ برائے زمرہ جات';
$Definition['Category Notifications'] = 'زمرے کی اطلاعات';
$Definition['Category to Use'] = 'زمرہ برائے استعمال';
$Definition['Change'] = 'تدوین';
$Definition['Change My Password'] = 'پاسورڈ بدلیں';
$Definition['Change My Picture'] = 'میری تصویر بدلیں';
$Definition['Change Password'] = 'پاسورڈ بدلیں';
$Definition['Change Picture'] = 'تصویر بدلیں';
$Definition['Check all roles that apply to this user:'] = 'اس صارف کو دی جانے والی تمام ذمہ داریوں کو منتخب کیجئے۔';
$Definition['Child Categories'] = 'ذیلی زمرہ جات';
$Definition['Child Categories:'] = 'ذیلی زمرہ جات :';
$Definition['Choose a name to identify yourself on the site.'] = 'ایک نام منتخب کریں جو اس سائٹ پر آپ کی پہچان بنے۔';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'اس بنیادی مباحثے کا انتخاب کریں جس میں تمام تبصرے ضم کر دئیے جائیں۔';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'آپ سوال پوچھنا چاہتے ہیں یا مباحثہ شروع کرنا چاہتے ہیں دونوں میں سے کسی ایک کا انتخاب کریں۔';
$Definition['Clear'] = 'صاف';
$Definition['clear'] = 'صاف';
$Definition['Clear Conversation History'] = 'سابقہ تمام گفتگو مٹا دیں۔';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'واپس مباحثہ کی طرف جانے کےلئے <a href="%s"> یہاں </a> کلک کریں۔';
$Definition['Click accept or reject beside an answer.'] = 'جواب قبول یا رد کرنے کیلئے کلک کریں';
$Definition['clicking here'] = 'یہاں کلک کرتے ہوئے';
$Definition['Click the %s beside discussions to bookmark them.'] = '%s پر کلک کرکے مباحثہ کو نشانزد کریں۔';
$Definition['Close'] = 'بند';
$Definition['Closed'] = 'بند';
$Definition['Close this discussion'] = 'مباحثہ بند کریں';
$Definition['Comment'] = 'تبصرہ';
$Definition['comment'] = 'تبصرہ';
$Definition['Comment As ...'] = 'تبصرہ کریں بطور ۔۔۔';
$Definition['Comment by %s'] = '%s نے تبصرہ کیا';
$Definition['Comment in'] = 'میں';
$Definition['Commenting as %1$s (%2$s)'] = 'تبصرہ بطور %1$s  <span class="SignOutWrap"> (%2$s)</span>';
$Definition['Commenting not allowed.'] = 'تبصرہ کرنے کی اجازت نہیں۔';
$Definition['Comments'] = 'تبصرے';
$Definition['Comments are between {UserID,you}.'] = 'تبصرے {UserID,you} کے درمیان ہیں۔';
$Definition['Completely delete the warning.'] = 'مکمل طور پر تنبیہ حذف کریں۔';
$Definition['Confirm'] = 'تصدیق';
$Definition['Confirm Email'] = 'ای میل کی تصدیق کریں';
$Definition['Confirm Password'] = 'پاسورڈ کی تصدیق';
$Definition['Connect'] = 'منسلک';
$Definition['ConnectAccountExists'] = 'آپ کا پہلے سے ایک کھاتہ موجود ہے۔';
$Definition['ConnectChooseName'] = 'اس نام کا انتخاب کریں جو اس سائٹ پر آپ کی پہچان بنے۔';
$Definition['ConnectCreateAccount'] = 'تفصیلات شامل کریں اور نیا کھاتہ بنائیں';
$Definition['ConnectExistingPassword'] = 'اپنے موجودہ کھاتے کا پاسورڈ درج کریں۔';
$Definition['Connecting...'] = 'رابطہ کرتے ہوئے ۔۔۔';
$Definition['Connection'] = 'رابطہ';
$Definition['ConnectLeaveBlank'] = 'خالی چھوڑ دیں اگر پہلے سے موجود کھاتے سے منسلک ہو رہے ہیں۔';
$Definition['ConnectName'] = 'اسمِ صارف';
$Definition['ConnectRegisteredName'] = 'آپ کا رجسٹر اسمِ صارف : <strong>%s</strong>';
$Definition['conversation'] = 'تبادلہ خیال';
$Definition['Create Discussions'] = 'مباحثے شروع کریں۔';
$Definition['Create One.'] = 'کھاتہ کھولیں';
$Definition['Current'] = 'حالیہ';
$Definition['Currently: '] = 'فی الحال';
$Definition['Custom Information'] = 'حسب منشاء معلومات';
$Definition['Customize'] = 'حسبِ منشاء ترمیم';
$Definition['customize your profile now'] = 'کوائف کی حسبِ منشاء ترمیم کریں۔';
$Definition['Customize your Public Profile'] = 'عمومی کوائف کی حسبِ منشاء ترمیم کریں۔';
$Definition['Custom Profile Fields'] = 'حسب ِ منشا کوائف کے ذیل';
$Definition['Custom Profile Field Settings'] = 'حسبِ منشا کوائف کی ترتیبات';

$Definition['Dashboard'] = 'ڈیش بورڈ';
$Definition['Dashboard Home'] = 'مرکزی ڈیش بورڈ';
$Definition['Dashboard Summaries'] = 'ڈیش بورڈ خلاصہ';
$Definition['Date'] = 'تاریخ';
$Definition['Date Added'] = 'تاریخ شامل کر دی گئی';
$Definition['days'] = 'ایام';
$Definition['Define Thumbnail'] = 'کلک کر کے گھسیٹیں اور تصویر کے اس حصے کا تعین کریں جسے آپ"تھمب نیل" کے طور پر استعمال کرنا چاہتے ہیں۔';
$Definition['Delete'] = 'حذف';
$Definition['Delete %s'] = 'حذف %s';
$Definition['Delete Account'] = 'کھاتہ حذف کریں';
$Definition['Delete Conversation'] = 'گفتگو حذف کریں';
$Definition['Delete Discussion'] = 'مباحثہ حذف کریں';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'صارف اور اس کاشامل کردہ تمام مواد بھی حذف کر دیں. یہ سپامرز سے جان چھڑانے کا سب سے بہترین طریقہ ہے';
$Definition['Delete User Content'] = 'صارف کا مواد حذف کریں';
$Definition['Delete User Forever'] = 'صارف کو ہمیشہ کے لئے حذف کریں';
$Definition['Did this answer the question?'] = 'کیا سوال کا یہی جواب ہے؟';
$Definition['Disagree'] = 'غیر متفق';
$Definition['Discussion'] = 'مباحثہ';
$Definition['discussion'] = 'مباحثہ';
$Definition['Discussions'] = 'مباحثے';
$Definition['Discussions Page'] = 'مباحثاتی صفحہ';
$Definition['Discussion Title'] = 'عنوان';
$Definition['Dislike'] = 'ناپسند';
$Definition['Dismiss'] = 'ختم';
$Definition['Don\'t announce.'] = 'اعلان مت کریں';
$Definition['Don\'t have an account? %s'] = ' %s اگر رجسٹر نہیں تو';
$Definition['Do you want to expire or delete this warning?'] = ' کیا آپ اس " تنبیہ" کو حذف کرنا یا اس کی میعاد ختم کرنا چاہتے ہیں؟';
$Definition['Draft saved at %s'] = 'بجے ڈرافٹ محفوظ ہوا۔ %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'اپا تھمب نیل بنانے کےلئے نیچے والا ڈبہ اردگرد گھسیٹیں اور حجم چھوٹا کریں۔';

$Definition['Earned'] = 'حاصل کردہ';
$Definition['Edit'] = 'تدوین';
$Definition['Edit Account'] = 'کھاتہ کی تدوین';
$Definition['Edit Comment'] = 'تبصرہ مدون کریں';
$Definition['Edit Discussion'] = 'تدوین مباحثہ';
$Definition['Edit My Account'] = 'میرے کھاتے کی تدوین';
$Definition['Edit My Profile'] = 'کوائف نامہ کی تدوین';
$Definition['Edit My Thumbnail'] = ' تعارفی تصویر کی تدوین';
$Definition['Edit Preferences'] = 'ترتیبات کی تدوین کریں';
$Definition['Edit Profile'] = 'کوائف نامہ کی تدوین';
$Definition['Edit Tag'] = 'تدوین ٹیگ';
$Definition['Edit Thumbnail'] = '"تھمب نیل"کی تدوین';
$Definition['Eighth Anniversary'] = 'آٹھویں سالگرہ';
$Definition['Email'] = 'ای-میل';
$Definition['Email/Username'] = 'ای میل/نام';
$Definition['EmailConfirmEmail'] = 'استعمال سےپہلے آپ کو اپنے ای میل کی تصدیق کی ضرورت ہے ۔ براہِ مہربانی درج ذیل روابط میں سے کسی ایک پر کلک کر کے اپے ای میل کی تصدیق کرائیں۔
{/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '
اللہ کی رحمت آپ پہ سایہ فگن رہے';
$Definition['EmailHeader'] = 'اسلامُ علیکم {User.Name}!\\n';
$Definition['EmailInvitation'] = 'اسلامُ علیکم!

%1$s نے آپ کو  %2$s پر شمولیت کےلئے مدعو کیا ہے ۔ اگر آپ شمولیت اختیار کرنا چاہتے ہیں تو درج ذیل ربط پر کلک کریں:

  %3$s';
$Definition['EmailMembershipApproved'] = 'اسلامُ علیکم %1$s ،

آپ کی رکنیت  منظور ہوگئی ہے ۔ سائن ان کرنے کےلئے درج ذیل ربط پر کلک کریں:

  %2$s';
$Definition['EmailNotification'] = '%1$s

دیکھنے کےلئے درج ذیل ربط پر کلک کریں:
%2$s

اللہ نگہبان';
$Definition['Email Notifications'] = 'اطلاع کی ای میل';
$Definition['Email Or Username'] = 'ای میل یا صارف کا نام';
$Definition['EmailPassword'] = '%2$s نے %3$s پر آپ کا پاسورڈ تبدیل کردیا ہے۔ آپ کی لاگ ان کی معلومات درج ذیل ہیں:

 ای میل : %6$s
  پاسورڈ : %5$s
  ربط : %4$s';
$Definition['Email Source'] = 'ای-میل';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
دیکھنے کےلئے درج ذیل ربط پر کلک کریں:
%2$s

اللہ نگہبان';
$Definition['Email Unavailable'] = 'ای-میل موجود نہیں';
$Definition['Email visible to other users'] = 'ای-میل دیگر اراکین پر عیاں ہے۔';
$Definition['EmailWelcome'] = '%2$s نے %3$s پر آپ کےلئے ایک کھاتہ بنایا ہے ۔ آپ کی لاگ ان کی معلومات درج ذیل ہیں:

 ای میل : %6$s
  پاسورڈ : %5$s
  ربط : %4$s';
$Definition['EmailWelcomeConnect'] = 'آپ {Title} کے ساتھ کامیابی سے منسلک ہوگئے ہیں۔ آپ کی معلومات درج ذیل ہیں:

اسمِ صارف : {User.Name}
  منسلک بذریعہ : {ProviderName}

آپ یہاں سے ویب سائٹ تک رسائی حاصل کرسکتے ہیں {/,exurl,domain}۔';
$Definition['EmailWelcomeRegister'] = '{Title} پر خوش آمدید ۔ آپ کا کھاتہ کامیابی کے ساتھ بن گیا ہے۔ آپ کی معلومات درج ذیل ہیں۔

اسمِ صارف : {User.Name}
ای میل : {User.Email}

آپ ویب سائٹ پر {/,exurl,domain} سے رسائی حاصل کر سکتے ہیں۔';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">مکمل تحریر یہاں پڑھیں</a></p><div class="ClearFix"></div></div>';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">مکمل تحریر یہاں پڑھیں</a></p><div class="ClearFix"></div></div>';
$Definition['English'] = 'انگلش';
$Definition['Enter your Email address'] = 'اپا ای میل ایڈریس لکھیں';
$Definition['Enter your email address'] = 'اپنا ای میل ایڈریس لکھیں';
$Definition['Enter your Email address or username'] = 'اپنا ای میل یا اسم صارف داخل کریں';
$Definition['Enter Your OpenID Url'] = 'اپنے اوپن آئی ڈی (OpenID) کا ربط دیں';
$Definition['Erase User Content'] = 'صارف کا مواد حذف کریں';
$Definition['Error'] = 'نقص';
$Definition['ErrorBadInvitationCode'] = 'آپ کا درج کردہ  دعوت نامے کا کوڈ درست نہیں ہے۔';
$Definition['ErrorCredentials'] = 'معذرت ، آپ کے داخل کئے گئے ای -میل/اسم صارف اور پاسورڈ  جیسا کوئی کھاتہ ہمارے پاس موجود نہیں ہے۔';
$Definition['ErrorPermission'] = 'معذرت،آپ کو مزید اجازت نہیں۔';
$Definition['ErrorPluginDisableRequired'] = 'آپ پلگ ان کو غیر فعال نہیں کر سکتے {0} کیونکہ {1} اس فعالیت کے سلسلے میں یہ پلگ ان ضرور درکار ہے.';
$Definition['ErrorPluginEnableRequired'] = 'اس پلگ ان کو فعال کرنے سے پہلے  {0} ضروری ہے کہ پہلے اس پلگ ان کو فعال کیا جائے.';
$Definition['ErrorPluginVersionMatch'] = 'فعال شدہ {0} پلگ ان (ورژن {1}) اس ورژن سے مطابقت نہیں رکھتا ({2}).';
$Definition['ErrorRecordNotFound'] = 'مطالبہ شدہ ریکارڈ نہیں مل سکا.';
$Definition['ErrorTermsOfService'] = 'آپ کا سروس کی شرائط سے متفق ہونا لازمی ہے۔';
$Definition['everyone'] = 'ہر کوئی';
$Definition['Everything'] = 'سب کچھ';
$Definition['Expired'] = 'معیاد ختم شد';
$Definition['Expires'] = 'میعاد ختم ہو چکی ہے۔';

$Definition['Failed to find discussion for commenting.'] = 'تبصرہ کے لئے مباحثہ ڈھونڈنے میں ناکامی ہوئی۔';
$Definition['Failed to load the poll.'] = 'رائے شماری لوڈ کرنے میں ناکامی ہوئی۔';
$Definition['Feedback'] = 'تجاویز';
$Definition['Female'] = 'موئنث';
$Definition['Fifth Anniversary'] = 'پانچویں سالگرہ';
$Definition['FileName'] = 'فائل کا نام';
$Definition['Filename'] = 'فائل کا نام';
$Definition['FileSize'] = 'فائل کا سائز';
$Definition['File Size'] = 'فائل کا حجم';
$Definition['First Anniversary'] = 'پہلی سالگرہ';
$Definition['First Comment'] = 'پہلا تبصرہ';
$Definition['Flag'] = 'جھنڈا';
$Definition['Follow'] = 'اقتداء';
$Definition['Follow %s'] = ' %s کی اقتداء';
$Definition['Followed by %d people'] = '%d لوگوں کے زیر اقتداء';
$Definition['Followed by %d person'] = ' %d آدمی نے زیر اقتداء رکھا';
$Definition['Following %d people'] = '%d لوگوں کی زیر نگرانی ہے۔';
$Definition['Following %d person'] = '%d کے زیرِ اقتداء';
$Definition['Follows'] = 'زیر اقتداء';
$Definition['Forgot?'] = 'بھول گئے؟';
$Definition['Forgot your password?'] = 'اپنا پاسورڈ بھول گئے؟';
$Definition['Format his'] = 'اُس کا';
$Definition['Format their'] = 'ان کے';
$Definition['Format You'] = 'آپ';
$Definition['Format you'] = 'آپ';
$Definition['Format Your'] = 'آپ';
$Definition['Fourth Anniversary'] = 'چوتھی سالگری';
$Definition['Friends'] = 'احباب';
$Definition['Full Site'] = 'مکمل سائٹ';

$Definition['Garden.Email.SupportAddress'] = 'مددگار ای -میل';
$Definition['Garden.Email.SupportName'] = 'مددگار نام';
$Definition['Garden.Registration.DefaultRoles'] = 'طے شدہ کردار';
$Definition['Garden.Title'] = 'اشتہار کا عنوان';
$Definition['Gender'] = 'جنس';
$Definition['General'] = 'عمومی';
$Definition['Generate import SQL only'] = 'صرف ایس کیو ایل بنائیں';
$Definition['Generate Password'] = 'پاسورڈ بنائیں';
$Definition['Give'] = 'دیں';
$Definition['Give a Badge to %s'] = '%s کو نشانِ امتیاز دیں';
$Definition['Give Badge'] = 'تمغہ دیں';
$Definition['Given'] = 'دیا گیا';
$Definition['Go'] = 'جائیے';
$Definition['Group Leaders'] = 'لیڈرز';
$Definition['Guest'] = 'مہمان';
$Definition['GuestModule.Message'] = 'السلام علیکم ، خوش آمدید ۔اگر آپ بھی یہاں کی سرگرمیوں میں حصہ لینا چاہتے ہیں تو ذیل میں سے کسی بٹن پر کلک کریں۔';

$Definition['Hang on a sec while we sign you out.'] = 'ایک لحظہ رکئیے ہم آپ کو خارج کر رہے ہیں۔';
$Definition['he'] = 'وہ';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} نے <a href="{Url,html}">{Data.Name,text}</a> نشانِ امتیاز حاصل کیا۔';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} نے {ActivityUserID,you} کو معطل کردیا ہے۔';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} نے <a href="{Url,html}">{Data.Name,text}</a> پر تبصرہ کیا ہے۔';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} نے ایک نئے مباحثے کا آغاز کیا<a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} نے <a href="{Url,html}">{Data.Name,text}</a> میں آپ کا تذکرہ کیا ہے';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} نے {ActivityUserID,user} کی نمائیندہ تصویر تبدیل کی ہے۔';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} نے شراکت کی۔';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} نے {ActivityUserID,you} کو بحال کردیا ہے۔';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} نے {RegardingUserID,you} کو متنبہ کیا ہے۔';
$Definition['her'] = 'اُس کا';
$Definition['Hide'] = 'چھُپائیں';
$Definition['Hide signatures?'] = 'دستخط چُٗھپائیں؟';
$Definition['Hide signatures always'] = 'دستخط ہمیشہ چھُپائیں۔';
$Definition['Hide signatures on my mobile device'] = 'موبائل پر دستخط چُھپائیں';
$Definition['his'] = 'اُس کا';
$Definition['Home'] = 'سرورق';
$Definition['hours'] = 'گھنٹے';
$Definition['Howdy, Stranger!'] = 'السلام علیکم ، خوش آمدید جناب';
$Definition['How long do you want this warning to last?'] = 'آپ کب تک یہ " تنبیہ" جاری رکھنا چاہتے ہیں؟';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'میں <a id="TermsOfService" class="Popup" target="terms" href="%s">سروس کی شرائط</a> سے متفق ہوں۔';
$Definition['in'] = 'میں';
$Definition['In <b>%s.</b>'] = 'میں <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'میں <b>%s</b>اور حالیہ مباحثے.';
$Definition['Inbox'] = 'ان باکس';
$Definition['In seconds'] = 'لمحوں میں';
$Definition['Insert Image'] = 'تصویر شامل کریں';
$Definition['Insightful'] = 'دور اندیش';
$Definition['Internal'] = 'اندرونی';
$Definition['In this Conversation'] = ' اس مکالمے میں شامل اراکین ';
$Definition['Invalid password.'] = 'آپ کا درج کردہ پاسورڈ درست نہیں۔یاد رکھیں کہ پاسورڈ چھوڑے بڑے حروف تہجی کے لئے حساس ہوتا ہے۔';
$Definition['Invitations'] = 'دعوت نامے';
$Definition['Invite'] = 'دعوت نامہ';
$Definition['InviteErrorPermission'] = 'معذرت ،اجازت رد کر دی گئی۔';
$Definition['I remember now!'] = 'مجھے یاد آگیا ہے۔';
$Definition['Item'] = 'جزو';
$Definition['item'] = 'جزو';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'یونہی  فورم پر خوش آؐمدید۔اگر آپ یہاں کی سرگرمیوں میں حصہ لینا چاہتے ہیں تو ذیل میں سے کسی بٹن پر کلک کریں۔';

$Definition['Jail'] = 'جیل';
$Definition['Jailed users have reduced abilities.'] = 'پابند صارفین کی سرگرمیاں محدود ہیں۔';
$Definition['Joined'] = 'شمولیت ';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'صرف صارف کا ریکارڈ حذف کر دیا جائے, اور اس کا شامل کردہ مواد رہنے دیا جائے.';
$Definition['Just expire the warning.'] = 'تنبیہ کی میعاد ختم کریں۔ ';
$Definition['Just you!'] = 'صرف آپ!';

$Definition['Keep me signed in'] = 'دائمی داخلہ';
$Definition['Keep User Content'] = 'صارف کا مواد موجود رہنے دیں';

$Definition['Label'] = 'عنوان';
$Definition['Last Active'] = 'آخری دفعہ پائے گئے۔';
$Definition['Last IP'] = 'آخری آئی پی';
$Definition['Latest %1$s'] = 'تازہ ترین %1$s';
$Definition['Latest Post'] = 'تازہ ترین پوسٹ';
$Definition['Leaders'] = 'لیڈرز';
$Definition['Leave a Comment'] = 'تبصرہ کریں';
$Definition['Leave a comment'] = 'تبصرہ کریں';
$Definition['Leave Comments'] = 'تبصرے کریں';
$Definition['Length'] = 'لمبائی';
$Definition['Level %s'] = 'درجہ %s';
$Definition['Like'] = 'پسند';
$Definition['Link to content:'] = 'مواد سے منسلک کریں';
$Definition['Login with Facebook'] = 'سائن ان  بذریعہ فیس بُک';
$Definition['LOL'] = 'قہقہہ';

$Definition['Make me invisible? (Will not show you on the list)'] = 'مجھے اوجھل کریں(آپ آن لائن لسٹ میں نظر نہیں آئیں گے)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'اس رائے شماری کو گمنام بنائیں ( صارفین کے ووٹ کسی پر ظاہر نہیں ہوں گے)۔';
$Definition['Male'] = 'مذکر';
$Definition['Mark All Viewed'] = 'سبھی بطورخواندہ شدہ ظاہر کریں';
$Definition['Marking as spam cannot be undone.'] = 'کسی چیز کو بطور سپیم نشان زد کرنے کا مطلب ہمیشہ کےلئے حذف کرنا ہے۔ اپنے فورم کو صاف ستھرا رکھنے کےلئے حذف کرنا ایک اچھا عمل ہے۔';
$Definition['Mark Read'] = 'خواندہ شدہ ظاہر کریں';
$Definition['Merge'] = 'ضم';
$Definition['Merge Discussions'] = 'مباحثے ضم کریں';
$Definition['Message'] = 'پیغام';
$Definition['message'] = 'پیغام';
$Definition['Messages'] = 'پیغامات';
$Definition['messages'] = 'پیغام';
$Definition['minutes'] = 'منٹ';
$Definition['Moderator Activity'] = 'ناظم کی سرگرمی';
$Definition['Moderators'] = 'ناظمین';
$Definition['moderators'] = 'ناظم';
$Definition['months'] = 'مہینے';
$Definition['More'] = 'مزید';
$Definition['More Comments'] = 'مزید تبصرے';
$Definition['More Discussions'] = 'مزید مباحثے';
$Definition['More Information'] = 'مزید معلومات';
$Definition['More Results'] = 'مزید نتائج';
$Definition['More…'] = 'مزید ۔۔۔';
$Definition['Most Recent'] = 'تازہ ترین';
$Definition['Most recent:'] = 'تازہ ترین:';
$Definition['Most recent: %1$s by %2$s'] = 'تازہ ترین: %1$sاز %2$s';
$Definition['Most recent by %1$s'] = ' %1$s  آخری جواب از';
$Definition['MyBadgesModuleTitle'] = 'میرے نشانِ امتیاز';
$Definition['My Bookmarks'] = 'میرے بک مارکس';
$Definition['My Discussions'] = 'میرے مباحثے';
$Definition['My Drafts'] = 'میرے ڈرافٹ';
$Definition['My Forums'] = 'میرے فورمز';
$Definition['My Preferences'] = 'میری ترجیحات';

$Definition['Name'] = 'نام';
$Definition['Name Dropper'] = 'نام ڈراپر';
$Definition['Name Unavailable'] = 'مطلوبہ نام موجود نہیں';
$Definition['new'] = 'نیا';
$Definition['New Conversation'] = 'نیا پیغام';
$Definition['New Discussion'] = 'نیا مباحثہ';
$Definition['new discussion'] = 'نیا';
$Definition['New Message'] = 'نیا پیغام';
$Definition['New Password'] = 'نیا پاسورڈ';
$Definition['New Poll'] = 'نئی رائے شماری';
$Definition['Next'] = 'اگلا';
$Definition['Ninth Anniversary'] = 'نویں سالگرہ';
$Definition['No'] = 'نہیں';
$Definition['NoBadgesEarned'] = 'کبھی بھی ...';
$Definition['No badges yet.'] = 'کوئی تمغہ نہیں';
$Definition['No default roles.'] = 'کوئی "طے شدہ کردار" نہیں۔';
$Definition['No discussions were found.'] = 'کوئی مباحثہ نہیں ملا۔';
$Definition['No items tagged with %s.'] = '%s کے نام سے کچھ بھی ٹیگ نہیں ہے۔';
$Definition['No results for \'%s\''] = ' \'%s\' کی تلاش کا نتیجہ کچھ نہیں۔';
$Definition['No Roles'] = 'کوئی ذمہ داری نہیں۔';
$Definition['Not Authorized (401)'] = 'اختیار نہیں (401)';
$Definition['Not Found (404)'] = 'موجود نہیں (404)';
$Definition['Notification'] = 'اطلاع';
$Definition['Notification Preferences'] = ' اطلاع کی ترجیحات';
$Definition['Notifications'] = ' اطلاعات';
$Definition['Notifictions'] = 'اطلاعات';
$Definition['Notify'] = 'مطلع';
$Definition['Notify me of private messages.'] = 'اطلاع دیں جب ذاتی پیغام آئے۔';
$Definition['Notify me when a badge is requested.'] = 'مجھے تحریری اطلاع دیں جب بیج کی درخواست کی جائے';
$Definition['Notify me when a comment is flagged.'] = 'مجھے مطلع کریں جب کسی تبصرے کو جھنڈی دکھائی جائے';
$Definition['Notify me when I am added to private conversations.'] = 'اگر مجھے کسی ذاتی گفتگو میں شامل کیا جائے تو مجھے مطلع کریں۔';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'جب میرے بک مارک کئے گئے مباحثوں پر لوگ تبصرہ کریں تو مجھے اطلاع دیں۔';
$Definition['Notify me when people comment on my discussions.'] = 'جب میرے شروع کردہ مباحثے پر تبصرہ ہو تو مجھے اطلاع دیں۔';
$Definition['Notify me when people mention me.'] = 'اطلاع دیں جب لوگ میرا تذکرہ کریں۔';
$Definition['Notify me when people mention me in comments.'] = 'اگر کسی تبصرے میں کوئی میرا تذکرہ کرے تو مجھے مطلع کریں۔';
$Definition['Notify me when people reply to my wall comments.'] = 'اطلاع دیں جب لوگ میری دیوار کے تبصرہ جات کا جواب دیں۔';
$Definition['Notify me when people write on my wall.'] = 'اطلاع دیں جب لوگ میری دیوار پر لکھیں۔';
$Definition['Not much happening here, yet.'] = 'فی الحال یہاں کوئی خاص سرگرمی دیکھنے میں نہیں آئی۔';
$Definition['Not Verified'] = 'غیر تصدیق شدہ';

$Definition[' now.'] = 'ابھی۔';

$Definition['Off Topic'] = 'بند موضوع';
$Definition['OldPassword'] = 'پُرانا پاسورڈ';
$Definition['Old Password'] = 'پرانا پاسورڈ';
$Definition['on'] = 'پر';
$Definition['Only show followed categories'] = 'صرف زیرِ اقتداء زمرے دکھائیں';
$Definition['OpenID Settings'] = 'اوپن آئی ڈی کی ترتیبات';
$Definition['Optional Description'] = 'اختیاری تفصیل';
$Definition['Options'] = 'اختیارات';
$Definition['or'] = 'یا';
$Definition['Organize discussion categories'] = 'مباحثہ کے زمرہ جات کو ترتیب دیں';
$Definition['Organize your Categories'] = 'زمرہ جات کی ترتیب';
$Definition['Original'] = 'اصلی';
$Definition['Or you can...'] = 'یا درج ذیل طریقے سے داخل ہوسکتے ہیں۔۔';
$Definition['Other Records'] = 'دیگر ریکارڈ';

$Definition['PageDetailsMessage'] = '%1$s سے %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s سے %2$s کا %3$s';
$Definition['Page Not Found'] = 'صفحہ نہیں ملا';
$Definition['ParticipatedHomepageTitle'] = 'شرکت کردہ مباحثے';
$Definition['Password'] = 'پاسورڈ';
$Definition['PasswordRequest'] = '%2$s پر پاسورڈ کے ری سیٹ کرنے کی درخواست کی گئی ہے۔ پاسورڈ ری سیٹ کرنے کےلئے درج ذیل ربط پر کلک کریں:

  %3$s

اگر یہ درخواست آپ کی طرف سے نہیں کی گئی تو اس ای میل کو نظر انداز کر دیں۔';
$Definition['Passwords don\'t match'] = 'دونوں پاسورڈ مطابقت نہیں رکھتے۔';
$Definition['Permalink'] = 'پرما لنک';
$Definition['permalink'] = 'پرما لنک';
$Definition['Permanent (301)'] = 'مستقل (301)';
$Definition['PermissionErrorMessage'] = 'آپ کو ایسا کرنے کی اجازت نہیں ہے۔';
$Definition['PermissionErrorTitle'] = 'اجازت کا مسئلہ';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'ایسا کرنے کیلئے آپ کا ناظم ہونا ضروری ہے۔';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'ایسا کرنے کےلئے آپ کا ایڈمنسٹریٹر ہونا لازمی ہے۔';
$Definition['PermissionRequired.Javascript'] = 'آپ کو ایسا کرنے سے پہلے جاوا سکرپٹ بحال کرنا ضروری ہے۔';
$Definition['Picture'] = 'تصویر';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'براہِ مہربانی انتظار فرمائیں جب تک آپ کو ری ڈائریکٹ کیا جارہا ہے۔ اگر آپ ری ڈائریکٹ نہیں ہو رہے تو <a href="%s"> یہاں </a> کریں۔';
$Definition['Poll'] = 'رائے شماری';
$Definition['Poll Options'] = 'رائے شماری کے اختیارات';
$Definition['Poll Question'] = 'رائے شماری کا سوال';
$Definition['Popular'] = 'مشہور';
$Definition['Popular Discussions'] = 'مشہور مباحثے';
$Definition['Popular Tags'] = 'مشہور ٹیگ';
$Definition['Popup'] = 'پاپ اپ';
$Definition['Position'] = 'جگہ';
$Definition['Post'] = 'پوسٹ';
$Definition['Post Comment'] = 'تبصرہ شائع کریں';
$Definition['Post Discussion'] = 'سوال پوچھیں';
$Definition['Post edited by %1$s at %2$s'] = ' %2$s کو  %1$s نے پوسٹ کی تدوین کی ۔';
$Definition['Posts'] = 'پوسٹ';
$Definition['Posts.Plural: %s'] = ' پوسٹ: %s';
$Definition['Posts.Singular: %s'] = 'پوسٹ:  %s';
$Definition['Posts: %s'] = 'پوسٹ:  %s';
$Definition['Post this anonymously'] = 'اسے گمنام رہتے ہوئے شائع کریں';
$Definition['Powered by %s'] = 'تقویت یافتہ از %s';
$Definition['Powered by Vanilla'] = 'تقویت یافتہ از ونیلا';
$Definition['PreferenceBadgeEmail'] = 'اطلاع دیں جب کوئی تمغہ حاصل ہو۔';
$Definition['PreferenceBadgePopup'] = 'اطلاع دیں جب کوئی تمغہ حاصل ہو۔';
$Definition['Preview'] = 'پیش منظر';
$Definition['Previous'] = 'پچھلا';
$Definition['Privacy Settings'] = 'رازداری کی ترتیبات';
$Definition['Private Note for Moderators'] = 'ناظمین کے لئے نجی نوٹ';
$Definition['Problem with credentials.'] = 'معلومات میں کوئی مسئلہ ہے۔';
$Definition['Proceed'] = 'آگے بڑھیئے۔';
$Definition['Profile'] = 'کوائف';
$Definition['Profile Fields'] = 'کوائف کے حلقے';
$Definition['Profile  Fields'] = 'کوائف کے حلقے';
$Definition['ProfileFieldsCustomDescription'] = 'حسبِ منشا کوائف ترتیب دینے کیلئے یہ فیلڈز استعمال کریں. آپ ان میں درج کر سکتے ہیں جیسا کہ "سماجی تعلقات", "Skype", یا "پسندیدہ ڈائنوسار". اپنے تخلیقی رحجان کا اظہار کریں!';
$Definition['Profile Page'] = 'کوائف نامہ کا صفحہ';
$Definition['Profile Picture'] = 'کوائف نامے کی تصویر';
$Definition['Profiles'] = 'کوائف نامے';
$Definition['Promote'] = 'ترقی دیں';
$Definition['Public'] = 'عوامی';

$Definition['Q&A'] = 'سوال اور جواب';
$Definition['Q&A Accepted'] = 'جواب شدہ';
$Definition['Q&A Answered'] = 'جواب شدہ';
$Definition['Q&A Options'] = 'سوال وجواب کے اختیارات';
$Definition['Q&A Question'] = 'سوال';
$Definition['QnA Accepted Answer'] = 'بہترین جواب ✓';
$Definition['QnA Rejected Answer'] = 'رد شدہ جواب';
$Definition['Question'] = 'سوال';
$Definition['question'] = 'سوال';
$Definition['Question Title'] = 'سوال کا عنوان';
$Definition['Quote'] = 'اقتباس';
$Definition['Quote Folding'] = 'اقتباس دہرائیں';
$Definition['Quote on'] = 'پر';
$Definition['Quote Settings'] = 'اقتباس کی ترتیب';
$Definition['Quote wrote'] = 'لکھا';

$Definition['Rank'] = 'عہدہ';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were}  کی {Data.Name,plaintext} پر ترقی کردی گئی ہے۔';
$Definition['Ranks.NotificationFormat'] = 'مبارک ہو ! آپ کی ترقی {Data.Name,plaintext} پر ہو گئی ہے۔';
$Definition['Reactions'] = 'ردعمل';
$Definition['Real Name'] = 'اصل نام';
$Definition['Reason'] = 'وجہ';
$Definition['Reason (optional)'] = 'وجہ(اختیاری)';
$Definition['Recent Activity'] = 'حالیہ سرگرمی';
$Definition['Recent Admin Activity'] = 'منتظم اعلیٰ کی حالیہ سرگرمی';
$Definition['Recent Discussions'] = 'حالیہ بحث';
$Definition['recently'] = 'فی الوقت';
$Definition['Recent Moderator Activity'] = 'ناظم کی حالیہ سرگرمی';
$Definition['Recent Tutorials'] = 'تازہ ترین ٹیوٹوریلز';
$Definition['Recipients'] = 'وصول کنندہ گان';
$Definition['RecipientUserID'] = 'وصول کنندہ';
$Definition['Redirecting...'] = 'منتقل کیا جا رہا ہے۔۔ ۔ ۔ ۔ ';
$Definition['Refetch Page'] = 'صفحہ بازیافت کریں';
$Definition['Register'] = 'رجسٹر';
$Definition['Register IP'] = 'رجسٹر آئی پی';
$Definition['Register with %s'] = 'رجسٹر';
$Definition['Registration  Fields'] = 'رجسٹریشن کے حلقے';
$Definition['Registration URL'] = 'رجسٹریشن یو آر ایل';
$Definition['Reject'] = 'رد';
$Definition['Reject this answer.'] = 'اس جواب کو رد کریں۔';
$Definition['Remember me'] = 'مجھے یاد رکھیں۔';
$Definition['Remember me on this computer'] = 'مجھے اس کمپیوٹر پر یاد رکھیں';
$Definition['Removed by'] = 'نے ہٹایا';
$Definition['Remove My Picture'] = 'میری تصویر ہٹائیں';
$Definition['Remove Picture'] = 'تصویر ہٹائیں';
$Definition['Remove Warning'] = 'تنبیہ ختم کریں';
$Definition['Rename Forum'] = 'فورم کا نام بدلیں';
$Definition['Reopen'] = 'دوبارہ کھولیں';
$Definition['Replies'] = 'جوابات';
$Definition['Reply'] = 'جواب';
$Definition['Reported by: '] = ':نے رپورٹ کیا';
$Definition['Report Reason'] = 'وجہ';
$Definition['Request a new password'] = 'نئے پاسورڈ کیلئے درخواست';
$Definition['Request a new password →'] = 'نئے پاسورڈ کی درخواست ←';
$Definition['Reset Password'] = 'ری سیٹ پاسورڈ';
$Definition['Revoke'] = 'منسوخی';
$Definition['Revoked badge.'] = 'بیج کی تنسیخ';
$Definition['role'] = 'کردار';
$Definition['RoleID'] = 'کردار';
$Definition['Roles'] = 'کردار';
$Definition['roles'] = 'کردار';
$Definition['RSVP'] = 'فورا جواب';

$Definition['Save'] = 'محفوظ';
$Definition['Save Comment'] = 'تبصرہ محفوظ کریں';
$Definition['Saved'] = 'آپ کی ، کی گئی تبدیلیاں محفوظ ہو گئی ہیں۔';
$Definition['Save Draft'] = 'ڈرافٹ محفوظ کریں';
$Definition['Save Poll'] = 'رائے شماری محفوظ کریں';
$Definition['Save Preferences'] = 'ترجیحات محفوظ کریں';
$Definition['Save your password'] = 'اپنا پاسورڈ محفوظ کریں';
$Definition['Search'] = 'تلاش';
$Definition['SearchBoxPlaceHolder'] = 'تلاش';
$Definition['Search for a tag.'] = 'تمام یا ٹیگ کے کچھ حصے تلاش کریں۔';
$Definition['Search results for \'%s\''] = '\'%s\' کی تلاش کے نتائج';
$Definition['Second Anniversary'] = 'دوسری سالگرہ';
$Definition['Sections'] = 'سیکشن';
$Definition['Security Check'] = 'حفاظتی تصدیق';
$Definition['Select an image on your computer (2mb max)'] = 'اپنے کمپیوٹر سے تصویر منتخب کریں (سائز انتہائی حد:2ایم بی)';
$Definition['Send a New Message'] = 'نیا پیغام بھیجیں';
$Definition['Send Message'] = 'پیغام بھیجیں';
$Definition['sep and'] = 'اور';
$Definition['Set a New Warning Level'] = 'ایک نیا تنبیہی درجہ وضع کریں';
$Definition['Set A Password'] = 'پاسورڈ ترتیب دیں';
$Definition['Setting'] = 'ترتیبات';
$Definition['Settings'] = 'ترتیبات';
$Definition['Seventh Anniversary'] = 'ساتویں سالگرہ';
$Definition['Share'] = 'تشہیر';
$Definition['Shared Accounts'] = 'اشتراک شدہ کھاتے';
$Definition['she'] = 'وہ';
$Definition['Shown only on mobile'] = 'صرف موبائل پر ظاہر ہو۔';
$Definition['Show unfollowed categories'] = 'وہ زمرہ جات ظاہر کریں جو میری زیرِ اقتداء نہیں';
$Definition['Sign-In URL'] = 'سائن ان ربط';
$Definition['Sign-Out URL'] = 'سائن آؤٹ ربط';
$Definition['Signature Code'] = 'دستخط کوڈ';
$Definition['Signature invalid.'] = 'غلط دستخط۔';
$Definition['Signatures'] = 'دستخط';
$Definition['Signature Settings'] = 'دستخط کی ترتیب';
$Definition['SignIn'] = 'سائن ان';
$Definition['Sign In'] = 'داخلہ  / سائن ان';
$Definition['SigningOut'] = 'ذرا ٹھہریئے ہم آپ کو سائن آؤٹ کر رہے ہیں۔';
$Definition['Sign In or Register to Comment.'] = 'تبصرہ کرنے کے لئے <a href="{SignInUrl,html}"{Popup}> سائن ان </a> کریں یا <a href="{RegisterUrl,html}"> رجسٹر </a> ہوں۔';
$Definition['Sign in to vote!'] = 'ووٹ کرنے کے لئے سائن ان ہوں!';
$Definition['Sign In with %s'] = 'سائن ان بذریعہ %s';
$Definition['Sign In with Disqus'] = 'سائن ان بذریعہ Disqus';
$Definition['Sign In with Facebook'] = 'فیس بک کے ذریعے داخل ہوں';
$Definition['Sign In with Google'] = 'سائن ان بذریعہ Google';
$Definition['Sign In with OpenID'] = 'سائن ان بذریعہ OpenID';
$Definition['Sign In with Twitter'] = 'سائن ان بذریعہ ٹوئیٹر';
$Definition['Sign Out'] = 'سائن آؤٹ';
$Definition['sign out'] = 'سائن آؤٹ';
$Definition['Sign Up'] = 'سائن اپ';
$Definition['Sink'] = 'غرق';
$Definition['Sink this discussion'] = 'اس مباحثے کو خارج کریں';
$Definition['Sitemap Settings'] = 'Sitemap ترتیبات';
$Definition['Sixth Anniversary'] = 'چھٹی سالگرہ';
$Definition['somebody'] = 'کوئی';
$Definition['Some Code'] = 'کچھ کوڈ';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'کسی نے آپ کے سوال کا جواب دیا ہے ۔ آپ جواب کو قبول یار رد کر سکتے ہیں۔';
$Definition['sorted by'] = 'ترتیب دئیے گئے از';
$Definition['Source:'] = 'ماخذ:';
$Definition['Spam'] = 'فضول';
$Definition['Split'] = 'تقسیم';
$Definition['Split Comments'] = 'تبصروں کی تقسیم';
$Definition['Spoiler'] = 'غار تگر';
$Definition['Spoof User'] = 'شرارتی صارف';
$Definition['SSL'] = 'ایس ایس ایل';
$Definition['Start'] = 'آغاز';
$Definition['Start a New Conversation'] = 'نیا پیغام';
$Definition['Start a New Discussion'] = 'نیا مباحثہ';
$Definition['Start Conversation'] = 'مکالمہ شروع کریں';
$Definition['Started By'] = 'نے شروع کیا';
$Definition['Started by %1$s'] = '%1$s شروع کنندہ';
$Definition['Start your First Discussion'] = 'اپنا پہلا مباحثہ شروع کریں۔';
$Definition['Stop following'] = 'اقتدا ترک کریں';
$Definition['Strip images out of signatures'] = 'دستخط میں سے تصویریں ختم کریں۔';
$Definition['Strip images out of signatures?'] = 'دستخط میں سے تصویریں نکالیں؟';
$Definition['Suggested Value'] = 'مجوزہ حیثیت';

$Definition['Tagged'] = 'ٹیگ شدہ';
$Definition['Tagged with '] = 'کےساتھ ٹیگ شدہ';
$Definition['Tagged with "%s"'] = '"%s "کے ساتھ ٹیگ';
$Definition['Tagging'] = 'ٹیگنگ';
$Definition['Tag Name'] = 'ٹیگ کا نام';
$Definition['Tags'] = 'ٹیگ';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'ٹیگ اور کچھ نہیں صرف چند کی ورڈز ہیں جن کو صارفین  اپنے مباحثوں  کے ساتھ لگاتے ہیں تا کہ ایک جیسے سوالات اور مباحثوں کو ترتیب دی جا سکے۔';
$Definition['Take Action'] = 'کاروئی کریں';
$Definition['Take Action:'] = 'کاروائی کریں:';
$Definition['Target'] = 'نشانہ';
$Definition['Tell the user why you\'re warning them'] = 'صارف کو آگاہ کریں کہ آپ نے انہیں کیوں متنبہ کیا ہے۔';
$Definition['Tell us why you want to join!'] = 'وضاحت فرمائیے ،آپ کیوں شمولیت چاہتے ہیں!';
$Definition['Tenth Anniversary'] = 'دسویں سالگرہ';
$Definition['TermsOfService'] = 'سروس کی شرائط';
$Definition['Terms of Service'] = 'سروس کی شرائط';
$Definition['TermsOfServiceText'] = '
   <p>آپ یہاں کسی بھی قسم کی منافرت انگیزی، فحش کلامی  ،تضحیک آمیز کلام، گالم گلوچ، دہشت گردی، پائریسی اور تمام قواعد و ضوابط کی خلاف ورزی  گریزاں رہنے کے پابند ہیں۔</p>
 
     <p>یہاں ارسال کیئے گئے کسی بھی مراسلے کے مواد کے لئے ادارہ ذمہ دار نہیں۔ تمام پیغامات مصنفین کی ذاتی آراء کا اظہار کرتے ہیں۔</p>

   <p>یہاں شائع شدہ مواد کسی بھی سبب حذف کرنے یا مدون کرنے کے تمام حقوق بحق ادارہ محفوظ ہیں۔</p>
   
   <p>اس سروس کو استعمال کرنے کےلئے آپ کا 13 سال سے زیادہ عمر کا ہونا لازمی ہے۔</p>
';
$Definition['Text  Max  Length'] = 'متن کی زیادہ سے زیادہ لمبائی';
$Definition['The conversation has been cleared.'] = 'گفتگو مٹا دی گئی ہے۔';
$Definition['The email you entered in use by another member.'] = 'آپ کا داخل کردہ ای میل کسی اور رکن کے زیر استعمال ہے۔';
$Definition['The email you have entered is already related to an existing account.'] = 'آپ کے درج کردہ ای میل سے پہلے ہی ایک کھاتہ منسلک ہے۔';
$Definition['The file failed to upload.'] = 'فائل کی اپلوڈنگ ناکم ہو گئی ہے۔';
$Definition['their'] = 'ان کے';
$Definition['The name you entered is already in use by another member.'] = 'جو نام آپ نے داخل کیا وہ کسی اور رکن کے زیر استعمال ہے۔';
$Definition['The page you were looking for could not be found.'] = 'آپ کا مطلوبہ صفحہ موجود نہیں';
$Definition['There are no tags in the system yet.'] = 'ابھی تک کوئی ٹیگ نہیں ہے۔';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = ' reCAPTCHA  درست داخل نہیں کیا گیا ،برائے مہربانی دوبارہ کوشش کیجئے۔';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'یہاں پر پہلے ہی ایک کھاتہ آپکے منتخب کردہ اسمِ صارف (%1$s) یا ای میل (%2$s) سے میل کھاتا ہے ۔ آپ نیا کھاتہ بنائیں یا پھر پہلے سے موجود کھاتہ کی معلومات درج کریں۔';
$Definition['The response was not in the correct format.'] = 'جواب درست شکل میں نہیں تھا۔';
$Definition['There was an error connecting to Disqus'] = 'Disqus کے ذریعے رابطے میں مسئلہ آرہا ہے۔';
$Definition['There was an error connecting to Facebook'] = 'فیس بُک کے ذریعے رابطے میں مسئلہ آرہا ہے۔';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'فائل منسلک کرتے ہوئے کچھ  دشواریاں سامنے آ رہی  ہیں۔ایسا اکثر اس وقت ہوتا ہے جب فائل کا حجم بہت زیادہ ہو۔';
$Definition['The site is currently undergoing maintenance.'] = 'یہ سائٹ مینٹیننس کے مراحل سے گزر رہی ہے۔';
$Definition['The uploaded file was too big (max %s).'] = 'منسلک کردہ فائل کا حجم بہت زیادہ تھا(انتہائی حد  %s)';
$Definition['they'] = 'وہ';
$Definition['Third Anniversary'] = 'تیسری سالگرہ';
$Definition['This answer was %s.'] = 'جواب تھا %s ۔';
$Definition['This answer was Accepted.'] = 'یہ جواب قبول کیا جاچکا ہے۔';
$Definition['This discussion has been closed.'] = 'یہ مباحثہ بند ہو چکا ہے۔';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'یہ مباحثہ ایک غیر واضح غیر ملکی مواد سے ماخوذ ہے.';
$Definition['This discussion was created from comments split from: %s.'] = 'یہ مباحثہ  %s  سے الگ کئے گئے تبصرہ جات اخذ کیا گیا تھا۔';
$Definition['This discussion was merged into %s'] = 'یہ مباحثہ %s میں ضم کردیا گیا تھا۔';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'صفحے کی مطابقت سے یہ تصویر چھوٹی نظر آ رہی ہے۔ یہاں کلک کر کے بڑی کریں۔';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'یہ ایک نجی رائے شماری ہے: آپ کا ووٹ کسی پر ظاہر نہیں کیاجائے گا۔';
$Definition['This is a public poll: others will see what you voted for.'] = 'یہ ایک عوامی رائے شماری ہے: آپ کا ووٹ ہر کوئی دیکھ سکتا ہے۔';
$Definition['This is a system account and does not represent a real person.'] = 'یہ ایک مشینی کھاتہ ہے اور کسی حقیقی شخص کی نمائندگی نہیں کرتا.';
$Definition['This Month\'s Leaders'] = 'اس ماہ کے سبقت یافتگان';
$Definition['This question\'s answer has been accepted.'] = 'اس سوال کا جواب قبول کرلیا گیا ہے۔';
$Definition['This user has been verified as a non-spammer.'] = 'بطور غیر سپیمر تصدیق شدہ';
$Definition['This user has not been verified as a non-spammer.'] = 'اس صارف کی ابھی تک تصدیق نہیں ہوئی کہ یہ سپیمنگ کرنے والا نہیں ہے۔';
$Definition['This user has not commented yet.'] = 'اس صارف نے ابھی تک کوئی تبصرہ نہیں کیا۔';
$Definition['This user has not made any discussions yet.'] = 'اس صارف نے ابھی تک کسی بحث میں حصہ نہیں لیا';
$Definition['This user is verified as a non-spammer'] = 'اس صارف کی تصدیق ہو گئی ہیں کہ یہ غیر سپیمر ہے۔';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'اس تنبیہ کی معیاد ختم ہو چکی ہے کیا آپ اس کو مکمل حذف کرنا چاہتے ہیں؟';
$Definition['This Week\'s Leaders'] = 'اس ہفتے کے سبقت یافتہ';
$Definition['Thumbnail'] = 'تعارفی تصویر';
$Definition['Title'] = 'عنوان';
$Definition['TLS'] = 'ٹی ایل ایس (TLS)';
$Definition['To'] = 'بنام';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'ایک اور تصدیقی ای میل بھیجنے کےلئے <a href="%s"> یہاں </a> کلک کریں۔';
$Definition['Transport error: %s'] = 'اس درخواست پر عمل درآمد کے دوران ای اتفاقی نقص واقع ہوا ہے.<br />سرور نے اس ذمہ داری کو لوٹا دیا ہے: %s';
$Definition['Troll'] = 'ٹرول';
$Definition['Turn ON'] = 'آن کیجئے۔';
$Definition['Twitter'] = 'ٹوئیٹر';
$Definition['Twitter Settings'] = 'ٹوئیٹر کی ترتیبات';
$Definition['Type'] = 'قسم';

$Definition['Unannounce'] = 'غیر اعلان شدہ';
$Definition['Unanswered'] = 'غیر جواب شدہ';
$Definition['Unanswered Questions'] = 'غیر جواب شدہ';
$Definition['unavailable'] = 'دستیاب نہیں';
$Definition['Unban User'] = 'صارف کو بحال کریں';
$Definition['Unbookmark'] = 'بُک مارک ختم کریں';
$Definition['Undefined discussion body.'] = 'غیر واضح مضمون';
$Definition['Undefined discussion subject.'] = 'غیر واضح موضوعِ مباحثہ';
$Definition['Undefined foreign content'] = 'غیر واضح بیرونی مواد';
$Definition['Undo Follow'] = 'نگرانی کالعدم';
$Definition['Unfollow'] = 'نگرانی منسوخ';
$Definition['Unhide'] = 'عیاں کریں';
$Definition['Unknown'] = 'نا معلوم';
$Definition['Unknown client: %s.'] = 'انجان کلائنٹ: %s.';
$Definition['Unread'] = 'غیر خواندہ شدہ';
$Definition['Unread Discussions'] = 'غیر خواندہ مباحثہ';
$Definition['Unsink'] = 'ناغرق';
$Definition['Unspecified'] = 'غیر مخصوص';
$Definition['Update'] = 'اپڈیٹ';
$Definition['Updated badge'] = 'جدید تمغہ';
$Definition['Upload'] = 'اپ لوڈ';
$Definition['Uploading...'] = 'اپ لوڈنگ۔۔';
$Definition['Url'] = 'ربط';
$Definition['UrlCode'] = 'ربط کا کوڈ';
$Definition['Use My Current Password'] = 'میرا موجودہ پاسورڈ استعمال کریں';
$Definition['User "%s" does not exist.'] = 'صارف "%s" موجود نہیں۔';
$Definition['Username'] = 'نام';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'اسمِ صارف حروف ،گنتی اور انڈر سکور پربھی مشتمل ہو سکتا ہے۔';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'اسمِ صارف صرف حروف یا حسبِ ضرورت نمبرز پر مشتمل ہو اور لمبائی 3 سے 20 حروف پر مشتمل ہو۔';
$Definition['UsernameError'] = 'اسمِ صارف کم از کم 3 اور زیادہ سے زیادہ 20 حروف تک  رکھا جا سکتا ہے ۔ دو الفاظ کے درمیان وقفے کیلئے انڈر سکور\' __ \' استعمال کریں، حسب ِ ضرورت ہندسوں کا استعمال بھی کیا جا سکتا ہے۔';
$Definition['Username or email'] = 'اسمِ صارف یا ای میل';
$Definition['User not found.'] = 'معذرت ، آپ کے درج کئے گئے ای میل یا اسمِ صاف سے کوئی کھاتہ مطابقت نہیں رکھتا۔';
$Definition['Users Count'] = 'صارفین کی تعداد';

$Definition['ValidateBanned'] = '%s کی اجازت نہیں ہے۔';
$Definition['ValidateLength'] = '%1$s میں %2$s حروف زیادہ ہیں۔';
$Definition['ValidateMatch'] = ' %s فیلڈز آپس میں مطابقت نہیں رکھتیں';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'کم از کم ایک  %s. کا چناؤ ضروری ہے۔';
$Definition['ValidateRequired'] = '%s ضروری ہے۔';
$Definition['ValidateRequiredArray'] = 'کم از کم ایک  %s. کا چناؤ ضروری ہے۔';
$Definition['ValidateTag'] = 'ٹیگز کے درمیان وقفہ نہیں دیا جا سکتا';
$Definition['ValidateTime'] = '%s درست وقت نہیں ہے۔';
$Definition['ValidateUrlStringRelaxed'] = '%s میں  سلیشز، کوٹس یا ٹیگ کے حروف شامل نہیں کیے جا سکتے۔';
$Definition['ValidateUsername'] = 'اسمِ صارف 3 سے 20 حروف یا حروف ، گنتی اور انڈر سکور پر مشتمل ہونا لازمی ہے۔';
$Definition['Value'] = 'قدر';
$Definition['Vanilla'] = 'ونیلا';
$Definition['Vanilla Statistics'] = 'ونیلا کے اعداد و شمار';
$Definition['Vanilla Statistics Plugin'] = 'ونیلا کے اعداد و شمار کا پلگ ان';
$Definition['Verified'] = 'تصدیق شدہ';
$Definition['Verifying your credentials...'] = 'آپ کی مہیا کردہ معلومات کی توثیق کی جا رہی ہے۔۔۔۔';
$Definition['via %s'] = 'بذریعہ %s';
$Definition['View Badge'] = 'تمغہ دیکھیں';
$Definition['Views'] = 'مناظر';
$Definition['Visible'] = 'ظاہر';
$Definition['Visits'] = 'دورے';
$Definition['Visit Site'] = 'سائٹ دیکھیں';
$Definition['Vote'] = 'ووٹ';
$Definition['Vote Down'] = 'منفی ووٹ';
$Definition['Votes'] = 'ووٹ';
$Definition['Vote Up'] = 'مثبت ووٹ';

$Definition['wall'] = 'وال';
$Definition['Want to take part in this discussion? Click one of these:'] = 'اس مباحثہ میں حصہ لینا چاہتے ہیں ؟ ان میں سے کسی ایک پر کلک کریں:';
$Definition['Warn'] = 'تنبیہہ';
$Definition['Warnings'] = 'انتباہ';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} نے {WarnUserID,User} کو {Points,plural,%s points} کی وجہ سے تنبیہہ کی ہے۔';
$Definition['WarningTitleFormat.Notice'] = '{InsertUserID,User} نے {WarnUserID,User} کو {Points,plural,%s points} کی وجہ سے تنبیہہ کی ہے۔(صرف ایک نوٹس ہے)';
$Definition['was'] = 'تھا';
$Definition['Website'] = 'ویب سائٹ';
$Definition['weeks'] = 'ہفتے';
$Definition['Welcome Aboard!'] = 'خوش آمدید!';
$Definition['were'] = 'تھے';
$Definition['Where do you want to announce this discussion?'] = 'آپ اس مباحثہ کا اعلان کہاں کرنا چاہتے ہیں؟';
$Definition['Who\'s Online'] = 'فی الوقت آن لائن اراکین';
$Definition['Why are you Banning this user?'] = 'آپ اس صارف کو کیوں معطل کر رہے ہیں؟';
$Definition['Write a comment'] = 'تبصرہ لکھیں۔۔';
$Definition['Write Comment'] = 'تبصرہ کریں';
$Definition['Write something about yourself...'] = 'اپنے بارے میں کچھ لکھیں۔۔';

$Definition['Yes'] = 'ہاں';
$Definition['You'] = 'آپ';
$Definition['you'] = 'آپ';
$Definition['You\'ve been Jailed.'] = 'آپ کو پابند کر دیا گیا تھا۔';
$Definition['You already have an account here.'] = 'آپ کا پہلے سے ایک کھاتہ موجود ہے۔';
$Definition['You are about to ban {User.UserID,user}.'] = 'آپ معطل ہونے والے ہیں :{User.UserID,user}';
$Definition['You are about to unban {User.UserID,user}.'] = 'آپ بحال ہونے والے ہیں: {User.UserID,user}';
$Definition['You are connected as %s through %s.'] = 'آپ منسلک ہیں بطور %s بذریعہ %s .';
$Definition['You are connected through %2$s.'] = '%2$s کے ذریعے آپ  منسلک ہوئے ہیں';
$Definition['You are currently only viewing categories that you follow.'] = 'فی الوقت وہی زمرہ جات آپ پر عیاں ہیں جو آپ کی زیرِ اقتداء ہیں۔';
$Definition['You are currently viewing all categories.'] = 'آپ اس وقت تمام زمرہ جات دیکھ رہے ہیں۔';
$Definition['You are editing %s\'s signature'] = 'آپ %s کے دستخط تدوین کررہے ہیں';
$Definition['You can either ask a question or start a discussion.'] = 'آپ سوال بھی پوچھ سکتےہیں اور نیا مباحثہ بھی شروع کر سکتے ہیں۔ ذیل میں کسی ایک کا انتخاب کیجئے۔';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'آپ انفرادی زمرہ جات کی پیروی کر سکتے ہیں اور ان میں ہونے والی ساری سرگرمیوں کی آپ کو اطلاع ملتی رہے گی۔';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'آپ بیرونی کسی سائٹ سے منسلک کوائف نامہ کی تصویر سے منتخب کیا گیا تھمب نیل مدون نہیں کر سکتے۔';
$Definition['You can only specify up to %s tags.'] = 'آپ %s تک ٹیگ لگا سکتے ہیں۔';
$Definition['You don\'t have permission to do that.'] = 'آپ کو ایسا کرنے کی اجازت نہیں ہے۔';
$Definition['You do not have any %s yet.'] = 'آپ کے پاس ابھی کوئی بھی %s نہیں ہے۔';
$Definition['You do not have any bookmarks.'] = 'آپ  کے پاس کوئی بک مارک نہیں ہے۔';
$Definition['You do not have any conversations.'] = 'آپ نے کوئی گفتگو نہیں کی ہے۔';
$Definition['You do not have any drafts.'] = 'آپ کا کوئی ڈرافٹ نہیں ہے۔';
$Definition['You do not have any notifications yet.'] = 'ابھی تک آپ کےلئے کوئی اطلاع موجود نہیں ہے۔';
$Definition['You do not have enough invitations left.'] = 'آپ کے پاس دعوت نامے ناکافی ہیں۔';
$Definition['You do not have permission to write new comments.'] = 'آپ کو نئے تبصرے کرنے کی اجازت نہیں ہے۔';
$Definition['YouEarnedBadge'] = 'آپ نے یہ تمغہ حاصل کیا ہے۔';
$Definition['You have answered questions'] = 'آپ نے سوالات کے جوابات دے دیئے ہیں۔';
$Definition['You have entered an invalid discussion title'] = 'آپ کا درج کیا گیا مباحثے کا عنوان غلط ہے۔';
$Definition['You haven\'t read this yet.'] = 'آپ نے ابھی تک اسے نہیں پڑھا ہے۔';
$Definition['You have not started any discussions.'] = 'آپ نے کوئی مباحثہ شروع نہیں کیا۔';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = ' %2$s سیکنڈ میں آپ نے  %1$s بار پوسٹ کرنے کی کوشش کی ہے جس کی وجہ سے آپ کا اکاؤٹ سپیم بلاکر سسٹم کی زد میں آگیا ہے۔اب دوبارہ کوشش کرنے سے پہلے آپ کو کم از کم %3$s سیکنڈ انتظار کرنا پڑے گا۔';
$Definition['You have selected %1$s.'] = 'آپ نے %1$s منتخب کیا ہے۔';
$Definition['You have selected %1$s in this discussion.'] = 'آپ نے اس مباحثے میں %1$s کو منتخب کیا ہے۔';
$Definition['You have to select at least 2 discussions to merge.'] = 'آپ کو کم از کم 2 مباحثے ضم کرنے کیلئے منتخب کرنا ضروری ہیں.';
$Definition['You must agree to the terms of service.'] = 'آپ کا سروس کی شرائط سے متفق ہونا لازمی ہے۔';
$Definition['You need to confirm your email address.'] = 'آپ نے ابھی تک اپنے ای میل کی تصدیق  نہیں کی ہے ۔ یہ لازمی ہے ۔ <a href="{/entry/emailconfirmrequest,url}"> یہاں </a> کلک کر کے تصدیقی ای میل دوبارہ بھیجیں۔';
$Definition['You need to sign in before you can do this.'] = 'ایسا کرنے سے پہلے آپ کو سائن ان ہونے کی ضرورت ہے۔';
$Definition['your'] = 'آپ کا';
$Definition['Your changes have been saved.'] = 'آپ کی ، کی گئی تبدیلیاں محفوظ ہو گئی ہیں۔';
$Definition['Your changes have been saved successfully.'] = 'آپ کی کی گئی تبدیلیاں کامیابی سے محفوظ ہو گئی ہیں۔';
$Definition['Your changes were saved.'] = 'آپ کی ترامیم محفوظ کردی گئیں ہیں۔';
$Definition['Your email has been successfully confirmed.'] = 'آپ کےای-میل کی تصدیق کامیابی سے ہو گئی ہے۔';
$Definition['Your invitation has been sent.'] = 'آپ کا دعوت نامہ بھیج دیا گیا ہے۔';
$Definition['Your old password was incorrect.'] = 'آپ کا پرانا پاسورڈ غلط ہے۔';
$Definition['Your password has been changed.'] = 'آپ کا پاسورڈ تبدیل کردیا گیا ہے۔';
$Definition['Your picture has been removed.'] = 'آپ کی تصویر حذف کر دی گئی ہے۔';
$Definition['Your post will appear once it\'s been approved.'] = 'آپ کی پوسٹ منظوری کے بعد شائع کی جائے گی۔';
$Definition['Your preferences have been saved.'] = 'آپ کی ترجیحات کو محفوظ کر دیا گیا ہے۔';
$Definition['Your private conversations with other members.'] = 'آپ کی ذاتی گفتگو دوسرے اراکین کے ساتھ۔';
$Definition['Your registered username: <strong>%s</strong>'] = 'آپ کا رجسٹر اسمِ صارف : <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'آپ کی درخواست بھیج دی گئی ہے۔ مزید ہدایات کےلئے اپنی ای میل دیکھیں۔';
$Definition['Your settings have been saved.'] = 'آپ کی ترجیحات کو محفوظ کردیا گیا ہے۔';
$Definition['Your settings have been saved successfully.'] = 'آپ کی ترجیحات کو کامیابی سے محفوظ کردیا گیا ہے۔';
$Definition['Your warning was added.'] = 'آپ کی تنبیہہ شامل کردی گئی ہے۔';
$Definition['You were added to a conversation.'] = '{InsertUserID,user} نے {NotifyUserID,you}  کو اس <a href="{Url,htmlencode}">  گفتگو </a> میں شامل کیا ہے۔';
