<?php

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Amakhanda phezulu!</strong> Ukususa indima kungaholela ekutheni abasebenzisi bangakwazi ukufinyelela kuhlelo.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Amakhanda phezulu!</strong> Ukuhambisa izingxoxo kusigaba sokuphindisela kungaholela ezingxenyeni zokushabalala (noma ukuvela) uma isigaba sombambiso sinemvume ehlukile kunesigaba esisusiwe.';

$Definition['About.DisableStatistics'] = 'Uma kufanele ukhubaze lokhu kubikwa kwedatha ngesizathu esithile sebhizinisi, ungakwenza lokho ngokungeza umugqa olandelayo kufayela lokumiswa lokufaka kwakho: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Kubaluleke kakhulu empilweni yale software yamahhala, yomthombo ovulekile esikala ngokunembile ukufinyelela nokusebenza kweVanilla. Siyacela ukuthi ukhubaze ukukhubaza ukubikwa kwale datha.';
$Definition['AboutCommentEmbedding'] = 'I-Vanilla ingasetjenziswa njengendawo yokungena esikhundleni yohlelo lokuphawula kwendabuko lwe-blog yakho. Empeleni, singasetshenziswa ukwengeza amazwana kunoma yiliphi ikhasi kuwebhu.';
$Definition['AboutEmbedding'] = 'Ukushumeka kuvumela konke noma ingxenye yomphakathi wakho ukuthi ingene kwezinye izinhlelozo kanye namakhasi e-web.';
$Definition['About Vanilla Statistics'] = 'Mayelana Nezibalo zeVanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Finyelela isithangami sakho somphakathi ngokuchofoza kusixhumanisi esithi "vakashela isayithi" phezulu kuleli khasi, noma <a href={/,url}>ngokuchofoza lapha</a> . Iforamu yomphakathi yilokho bonke abasebenzisi bakho namakhasimende abazokubona lapho bevakashela i- <a href="{/,url,domain}">{/, url, domain}</a> .';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Ngeza imikhawulo kuzimo zokulayisha izithombe ezingxoxweni nasemazwaneni.';
$Definition['AddonProblems'] = '<h2> Izinkinga? </h2><p> Uma kukhona okungahambi kahle nge-addon futhi ungakwazi ukusebenzisa isayithi lakho, ungakhubaza ngesandla ngokuhlela: </p> %s';
$Definition['AddressBarColorDescription'] = 'Ezinye iziphequluli zisekela umbala webha yekheli. Iselula kuphela.';
$Definition['Alert users if they click external link.'] = 'Abasebenzisi bezaziso uma bechofoza isixhumanisi kokuthunyelwe okuzoholela kude nesithangami. Abasebenzisi ngeke baxwayiswe uma kulandela izixhumanisi ezihambelana ne-Domain Ethembekile';
$Definition['Alignment'] = 'Ukuqondanisa';
$Definition['Alignment (Mobile)'] = 'Ukuqondanisa (Iselula)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Zonke izigaba ezifakwe kuhlu ezikhethiwe kwezingxoxo ezi-5 zakamuva ngaphansi kwesigaba ngasinye';
$Definition['Allow links to be transformed'] = 'Vumela izixhumanisi ukuthi ziguqulwe zibe yizifanekiselo ezishumekiwe ezingxoxweni nasemazwaneni. Isibonelo, ukuxhumana kwe-YouTube kuzoshintsha kube yividiyo eshumekiwe.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Vumela abasebenzisi abane-%s imvume yokushintsha ama-avatar abo kusuka kumakhasi abo e-Vanilla.';
$Definition['ApplicationHelp'] = 'Izicelo zikuvumela ukuthi ungeze amaqembu amakhulu wokusebenza kusayithi lakho. <br /> Lapho uhlelo lokusebenza selungezwe kufolda yakho ye-%s, ungayinika amandla noma ikhubaze lapha.';
$Definition['Apply Layout'] = 'Sebenzisa Isakhiwo';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Ngabe uqinisekile ukuthi ufuna ukususa lesi sihloko? Izosuswa unomphela.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Uqinisekile ukuthi ufake igama lomsingathi wemininingwane efanele? Mhlawumbe uyiphathe kabi? Imininingwane yabika: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Indima enohlobo lokuzenzakalelayo "olungakaqinisekisiwe" liyadingeka ukusebenzisa ukuqinisekiswa kwe-imeyili.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Ama-avatar azokwehliswa uma edlula lokhu ukuphakama.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Ama-avatar azokwehliswa uma edlula lobu bubanzi.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Ama-avatar azoba nezithonjana zawo zilondolozwe ngalesayizi.';

$Definition['Background'] = 'Isendlalelo';
$Definition['Background Image'] = 'Izithombe zangemuva';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Yakha! Zama ukuqamba amazinga akho ngemuva kwezinto umphakathi ezikhuluma ngazo.';
$Definition['Bordered'] = 'Kuhlanganisiwe';
$Definition['Bordered (Unified)'] = 'Kuhlanganisiwe (Kuhlanganisiwe)';
$Definition['Borderless'] = 'Akunamkhawulo';
$Definition['Border Radius'] = 'Imingcele ye-Border';
$Definition['Brand Color'] = 'Umbala Womkhiqizo';
$Definition['Buttons'] = 'Izinkinobho';
$Definition['Buttons & Inputs'] = 'Izinkinobho nokokufaka';
$Definition['Button Type'] = 'Uhlobo lwe-Button';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Ngokuchofoza inkinobho engezansi, uzobe ususa i-akhawunti yomsebenzisi ye-%s unaphakade.';

$Definition['Center Aligned'] = 'Isikhungo Sihlukaniselwe';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Izinguquko zizosebenza kuma-avatar asanda kulayishwa kuphela.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Shintsha osayizi ukuthi izithombe ze-avatar zigcinwa kuzo.';
$Definition['Change the way your community works with plugins.'] = 'Shintsha indlela umphakathi wakho osebenza ngayo nama-plugins. Sihlanganise ama-plugins athandwayo ngesoftware, futhi kukhona amanye atholakala online.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Amabhokisi wokuhlola avumela ama-admins ukuthi enze isenzo se-batch kwinqwaba yezingxoxo noma amazwana ngasikhathi sinye.';
$Definition['Check out our %s'] = 'Bheka i-%s yethu';
$Definition['Check out these tutorials to get started using Vanilla'] = 'I-Vanilla iyipulatifomu yomphakathi elula, enamandla kunazo zonke emhlabeni. Kulula ukuyisebenzisa. Qala ngale vidiyo yesingeniso bese uqhubeka ngezinyathelo ezingezansi. Jabulela!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Khetha indima abazoyisebenzisa abayizintandane:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Khetha ingqikithi yaleli bandla elingaphansi. <0> Funda kabanzi </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Khetha ukuthi ukuphatha kanjani konke okuqukethwe okuhambisana ne-akhawunti yomsebenzisi ye-%s (imibono, imilayezo, njll).';
$Definition['Choose Image'] = 'Khetha isithombe';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Ungakhetha i-algorithm yangokwezifiso ukusayina izicelo zakho. I-hash algorithm kumele futhi isetshenziswe kulabhulali yakho yekhasimende. Khetha i-md5 uma ungaqiniseki ukuthi yini okufanele uyikhethe.';
$Definition['Choose the order items are sorted.'] = 'Khetha izinto oda ihlelwa.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Khetha ikhasi abantu okufanele balibone lapho bevakashela i- <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Khetha ukwakheka okuthandwayo kohlu lwezigaba.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Khetha ukwakheka okuncamelayo kohlu lwezigaba. Ungahlela Ukuhlelwa Kwethayili.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Khetha isakhiwo esithandwayo sohlu lwezingxoxo.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Khetha ukwakheka okuncamelayo kohlu lwezingxoxo. Ungahlela i-Foundation Layout.';
$Definition['Color Overlay'] = 'Imbondela Umbala';
$Definition['Continue Import'] = 'Qhubeka Ngenisa';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Ayikwazanga ukuhlaziya ifayela lokungenisa. Inkinga isondele kulayini %s.';
$Definition['Create a localization CSV'] = 'Dala i-CSV yendawo';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Izindikimba ezenziwe ngokwezifiso yizindikimba ozidalile. Ungahlela, uqambe kabusha noma wenze ikhophi lazo.';

$Definition['Dark'] = 'Mnyama';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Chaza ukuthi ngubani ongalayisha futhi aphathe amafayela ekhasini <a href="%s">lezindima nezimvume</a> .';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Chaza ikhasi eliyikhaya lakho lesithangami, layisha ilogo yakho, nokuningi ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Ukususa indima kungaholela ekutheni abasebenzisi bangakwazi ukufinyelela kuhlelo.';
$Definition['Deleting forever cannot be undone.'] = 'Ukususa kuyindlela enhle yokugcina iforamu yakho ihlanzekile.';
$Definition['Disable Google Sign In'] = 'Khubaza Ukungena ngemvume kwe-Google';
$Definition['Disable OpenID'] = 'Khubaza i-OpenID';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Imikhakha yezingxoxo isetshenziselwa ukusiza abasebenzisi bakho ukuthi bahlele izingxoxo zabo ngendlela enenjongo emphakathini wakho.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Musa ukushumeka kudeshibhodi yakho yesithangami';
$Definition['Don\'t use too many reactions.'] = 'Musa ukusebenzisa izimpendulo eziningi. Awufuni ukunika abasebenzisi bakho imininingwane ethe xaxa.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Hudula bese uphonsa izigaba ezingezansi ukuzihlunga nokuzidlisa.';

$Definition['EditContentTimeout.Notes'] = 'Uma umsebenzisi esesendimeni enemvume yokuhlela okuqukethwe, lezo zimvume zizokweqa lokhu.';
$Definition['Edit Route'] = 'Hlela umzila';
$Definition['Edits to this theme apply to:'] = 'Ukuhlelwa kwalesi sihloko kusebenza ku:';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Shuthela inkundla yakho yomphakathi kuwebhusayithi yakho ukwandisa ukubandakanyeka ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Nika amandla futhi uhlole izici zakamuva ze-Vanilla.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Inika amandla ukuhlelwa okuthuthukile kokuthunyelwe ngezindlela eziningi, kufaka phakathi i-WYSIWYG, i-HTML elula, iMarkdown, ne-BBCode.';
$Definition['Enter a descriptive name.'] = 'Faka igama elichazayo ephaketheni. Leli gama ngeke liboniswe ndawo ngaphandle kokuthi lapho ulawula amaphakethe akho lapha ngakho-ke asetshenziswa kuphela ukukusiza ukhumbule ephaketheni.';
$Definition['Enter a short name for the site.'] = 'Faka igama elifushane lesiza. Lokhu kukhonjiswa kuzinkinobho ze-signin.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Faka ikheli leBlogpress Blog yakho futhi sizoyithatha lapho.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Faka izilungiselelo zokuxhumeka kweseva yakho ye-sphinx ngezansi.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Konke ukuhlela noma ukusulwa kuqoshwe lapha. Sebenzisa \'Buyisela\' ukulungisa noma yiluphi ushintsho.';
$Definition['Everyone who signs up gets a profile page.'] = 'Wonke umuntu obhalisela umphakathi wakho uthola ikhasi lephrofayela esesidlangalaleni lapho angalayisha khona isithombe, aphathe izilungiselelo zephrofayela yakhe, futhi alandelele izinto ezipholile ezenzekayo emphakathini. Kufanele <a href="{/profile,url}">wenze ngezifiso iphrofayili yakho manje</a> .';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Wonke umsebenzisi kusayithi lakho unikezwa okungenani indima eyodwa. Izindima zisetshenziselwa ukuthola ukuthi abasebenzisi bavunyelwe ukwenzani.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'I-Facebook Connect ivumela abasebenzisi ukuthi bangene ngemvume besebenzisa i-akhawunti yabo ye-Facebook. <b>Kufanele ubhalise uhlelo lwakho lokusebenza ne-Facebook ukuze le plugin isebenze.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Yehlulekile ukuxhuma database ngegama lomsebenzisi nephasiwedi oyifakile. Ngabe ubaphatha kabi? Imininingwane yabika: <code>%s</code>';
$Definition['Font'] = 'Ifonti';
$Definition['Font Name'] = 'Igama Lamafonti';
$Definition['Font URL'] = 'I-URL yefonti';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Phoqa ideshibhodi ukuthi itholakale kuphela nge-url <em>(ayinconywa)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Isibonelo, ungavimba bonke abasebenzisi ngamakheli ama-imeyili asuka ku- "example.com" ngokungeza ukuvinjelwa kohlobo lwe-imeyili ngenani le- "*@example.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Ngezinhloso ze-SEO, abakhandi benjini yokusesha abakhishwa ngaphandle kokuphoqwa ukuthi babuke isithangami ku-url eyihlane.';
$Definition['Foundation Layout'] = 'Ukuhlelwa Kwesisekelo';
$Definition['Full Bleed'] = 'Okugcwele Kugcwele';

$Definition['Garden.Import.Complete.Description'] = 'Uqede ngempumelelo ukungenisa. Chofoza <b>kuQedile</b> lapho usukulungele.';
$Definition['Garden.Import.Continue.Description'] = 'Kubukeka sengathi uphakathi kokungenisa. Sicela ukhethe okukodwa kokulandelayo.';
$Definition['Garden.Import.InputInstructions'] = 'Faka i-imeyili ne-password yomsebenzisi wokuqondisa kusuka kudatha engeniswayo.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Ingadi.Profiles.Hlela imvume yokushintsha ama-avatar abo kusuka kumakhasi abo e-Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Ukhubaze ngokukhethekile i-Vanilla Statistics kwifayela lakho lokucushwa.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Le nkundla ibonakala isebenza endaweni yokuhlola, noma ngenye indlela ibika i-IP yangasese. Ngokuzenzakalelayo, izinkundla ezisebenza kuma-IP angasese azilandelelwa.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Uma uqinisekile ukuthi iforamu yakho iyatholakala kusuka ku-inthanethi ungayiphoqa ukuthi ibike izibalo lapha:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Ifayela lakho le-config.php libonakala lifundwa kuphela. Lokhu kusho ukuthi uVanilla ngeke akwazi ukubhalisa ngokuzenzakalela iforamu yakho ye-PuttingID ne-UkufakaationSecret.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Ukuxazulula le nkinga, nika imodi yefayela engu-777 kwifayela lakho le-conf / config.php.';
$Definition['Global Styles'] = 'Izitayela Zomhlaba';

$Definition['Heads Up!'] = 'Amakhanda phezulu!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Amakhanda phezulu! Le yindima ekhethekile engavumeli amaseshini asebenzayo. Ngalesi sizathu, izinketho zemvume zikhawulelwe izimvume "zokubuka".';
$Definition['Here are all of the reactions you can use on your site.'] = 'Nayi yonke imiphumela ongayisebenzisa esizeni sakho.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Nawa amasheya abasebenzisi abangawafinyelela kusayithi lakho. Ungawenza ngokwezifiso lezi zigaba futhi ungeze nezintsha. Nawa amanye amathiphu.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Uma ilogo yesibhengezo ilayishwa, izothatha isikhundla sesihloko sesibhengezo kumakhasi eforamu abheke abasebenzisi.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Uma kunikwe amandla, okuqukethwe okugcwele kokuthunyelwe kuzothunyelwa kwizaziso ze-imeyili kubasebenzisi.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Uma umusha ku-HTML kanye / noma i-CSS, nazi ezinye izifundo zokukuqalisa:';
$Definition['If you have an old theme'] = 'Uma unengqikithi yakudala futhi udinga ukusetha ideskithophu ehlukile nengqikithi yeselula ungakwenza nge-UI ye-theming yakudala.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Uma ufuna ukwehlisa izinga lesexwayiso bese ususa isexwayiso.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Uma ufuna ukushumeka iforamu yakho noma usebenzise amazwana kaVanilla kubhulogi lakho lapho-ke udinga ukunika amandla ukushumeka. Uma ungasebenzisi ukushumeka sincoma ukushiya lokhu kulungiselelwa kuvaliwe.';
$Definition['Image (Mobile)'] = 'Izithombe (Iselula)';
$Definition['Import'] = 'Ngenisa';
$Definition['Importing to Vanilla'] = 'Ingenisa kuVanilla';
$Definition['In additon to the widgets there are also'] = 'Okwengezwayo kumawijethi kukhona futhi <0> Izitayela Zomhlaba </0> . Ukuhlela izitayela zomhlaba wonke chofoza kwenye indawo ekhasini, njengalo mbhalo.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Hlanganisa amakhasi we-Foundation & Components Into Yakho';
$Definition['Internationalization & Localization'] = 'I-Internationalization kanye ne-Localization';
$Definition['Invalid URL'] = 'I-URL engavumelekile';
$Definition['Invitation email failed to send: %'] = 'Yize isimemo sidalwe ngempumelelo, i-imeyili yehlulekile ukuthumela. Iseva ibike iphutha elilandelayo: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Uma usebenzisa ukubhaliswa kwabasebenzisi besimemo bazoba nesixhumanisi esibizwa ngokuthi <a href="%s" class="Popup">Izimemo Zami</a> ekhasini labo lephrofayili.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Kubukeka sengathi i-database oyichazile ayikho okwamanje. Ngabe usuyidalile? Ngabe uliphathe kabi igama? Imininingwane yabika: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Kungumqondo omuhle ukugcina inani eliphakeme lezinhlamvu livunyelwe kumazwana kuze kube usayizi olungile.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Kungumqondo omuhle ukugcina inani eliphezulu lezinhlamvu livunyelwe eposini liye kusayizi ofanele.';

$Definition['Kick-start your community and increase user engagement.'] = 'Qalisa umphakathi wakho futhi ukhuphule ukuzibandakanya komsebenzisi.';

$Definition['Labs'] = 'Amalebhu';
$Definition['Learn about custom routing.'] = 'Funda ngemikhondo yangokwezifiso.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Funda ukuthi ungakushintsha ngokuphelele ukubukeka nokuzwa kwesithangami sakho: layisha ilogo yakho, setha ikhasi lakho eliyisiqalo, khetha ingqikithi bese uyenza ngokwezifiso.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Funda ukuthi usebenzise kanjani ukusebenza okuyisisekelo kwesithangami sakho.';
$Definition['Left Aligned'] = 'Kuhlukaniswe Kwesobunxele';
$Definition['Light'] = 'Kukhanya';
$Definition['Links'] = 'Izixhumanisi';
$Definition['Locales allow you to support other languages on your site.'] = 'Izindawo zikuvumela ukuthi uxhase ezinye izilimi kusayithi lakho. Nika amandla futhi ukhubaze izindawo lapho ufuna ukwenza zitholakale lapha.';
$Definition['LogoDescription'] = 'Ilogo yesibhengezo ivela phezulu kusayithi lakho.';
$Definition['LogoDisclaimer'] = 'Izindikimba ezenziwe ngesihleli sengqikithi nezinye izingqikili ezenziwe ngokwezifiso azisebenzisi lokhu kulungiselelwa.';

$Definition['Make sure you click View Page'] = 'Qiniseka ukuthi uchofoza <a href="%s">Ukubuka Ikhasi</a> ukubona ukuthi ikhasi lakho lezigaba libukeka kanjani ngemuva kokulondolozwa.';
$Definition['Manage Routes'] = 'Phatha Imizila';
$Definition['Managing Users'] = 'Ukuphatha Abasebenzisi';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Ukumaka izinto njengokuthi AKUFUNI ogaxekile kuzobabuyisela esithangamini sakho.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Ukumaka izinto njengezingekho kogaxekile kuzozibuyisela emuva esithangamini sakho.';
$Definition['Messages can appear anywhere in your application.'] = 'Imilayezo ingavela noma yikuphi kuhlelo lwakho lokusebenza, futhi lungasetshenziselwa ukwazisa abasebenzisi bakho ngezindaba nezehlakalo. Sebenzisa leli khasi ukuhlela kabusha imilayezo yakho ngokuyihudulela phezulu noma phansi.';
$Definition['MobileLogoDescription'] = 'I-logo yamabhanela eselula avela phezulu kusayithi lakho.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Izindikimba zeselula zikuvumela ukuthi ushintshe ukubukeka nokuzwa kwesayithi lakho kumadivayisi amancane.';

$Definition['Need More Help?'] = 'Ngabe udinga usizo olwengeziwe?';
$Definition['Need more help?'] = 'Udinga usizo olwengeziwe?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Izigaba ezifakiwe ezijule kakhulu kunale ukujula zizofakwa kuhlu olunqunyelwe kukhefana.';
$Definition['New Quick Links'] = 'Izixhumanisi Ezisha Ezintsha';
$Definition['New Search Page'] = 'Ukucinga okusha';
$Definition['Not getting what you expect when you preview your theme?'] = 'Ukungatholi okudingayo lapho ubuka kuqala itimu yakho?';
$Definition['Notify me when people comment on my addons.'] = 'Ngazise lapho abantu bephawula ngama-addons ami.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Isiza sidinga indima enohlobo lokuzenzakalelayo "olungagunyaziwe" ukusebenzisa ukuqinisekiswa kwe-imeyili. Sicela ungeze eyodwa ukuze unike amandla lokhu kulungiselelwa.';

$Definition['Old Theming UI'] = 'UI Old Theming UI';
$Definition['Once enabled, only members will see inside your community.'] = 'Uma sekuvunyelwe, amalungu kuphela azobona ngaphakathi komphakathi wakho.';
$Definition['OrgDescription'] = 'Igama lenhlangano yakho lisetshenziselwa i-SEO microdata ne-JSON + LD';
$Definition['Outline'] = 'Hlela';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Ukubukwa okwenziwe ngokweqile noma ama-themehooks angaba nemiphumela emibi engahlosiwe futhi akubukwa kuqala.';

$Definition['Please choose an authenticator to configure.'] = 'Sicela ukhethe ubuqiniso bokumisa.';
$Definition['PluginHelp'] = 'Ama-plugins akuvumela ukuthi ungeze ukusebenza kusayithi lakho. <br /> Uma i-plugin ingeziwe kufolda yakho ye-%s, ungayinika amandla noma ikhubaze lapha.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Iphakethe liboniswa phakathi kwengxoxo ngayinye esohlwini lwezingxoxo oluphambili. Njengoba izingxoxo zivame ukuba kumathegi we- <li> .. </li>, uzodinga ukusonga ephaketheni lakho kulawo maga.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Amaphakethe akuvumela ukuthi ungeze ifomu lamahhala le-HTML ezindaweni ezahlukahlukene eziseduzane nesicelo.';
$Definition['Preset'] = 'Ukumisa ngaphambili';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Vikela ogaxekile esithangamini sakho ngokukhawula inani lezingxoxo namazwana abasebenzisi abangawathumela ngesikhathi esithile.';
$Definition['Primary Button'] = 'Inkinobho yokuqala';
$Definition['Primary Buttons'] = 'Izinkinobho eziyinhloko';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Umhlahlandlela oqala Ngokushesha Wokwenza Izindikimba zeVanilla';
$Definition['Quick Links is a default component on community pages.'] = 'I-Quick Links iyinto ezenzakalelayo emakhasini omphakathi. Nika amandla ingxenye yethu entsha ye-Quick Links ukwengeza, ukuhlela noma ukufihla izixhumanisi ezivela kule menyu usebenzisa isihleli setimu yethu.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'I-plugin ye-Vanilla Comments eyenziwe isilungele ye-WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'I-plugin ye-Vanilla Forum elungiselelwe eyenziwe ye-WordPress';
$Definition['Realtime progress bars: %s'] = 'Amabha wenqubekela phambili wesikhathi esisetshenziswa: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Kungumqondo omuhle ukuba nezikhundla ezikhethekile zabongameli nabaphathi ukuze umphakathi wakho ukwazi ukubona kalula ukuthi ngubani ophethe.';
$Definition['Recommend starting with five ranks.'] = 'Awufuni ukuba nezikhundla eziningi kakhulu. Sincoma ukuqala ngezihlanu. Ungangeza okuningi uma umphakathi wakho mkhulu.';
$Definition['Requires “Flag” reaction permission.'] = 'Dinga imvume yokusabela ethi "Hlaba umkhosi".';
$Definition['Requires “Negative” reaction permission.'] = 'Dinga imvume yokusabela "Engalungile".';
$Definition['Requires “Positive” reaction permission.'] = 'Dinga imvume yokuphendula "Okuhle".';
$Definition['Restoring your selection removes the items from this list.'] = 'Uma ubuyisela, izinto ziyasuswa kulolu hlu bese ziphindiselwa kusayithi.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Sebenzisa inketho elandelayo ukunika amandla izingcaphuno zomhleli ocebile. Lokhu kuzosebenza kuphela uma ifomathi ezenzakalelayo engu- "Rich".';
$Definition['Route Expression'] = 'Ukuvezwa Kwendlela';
$Definition['Routes are used to redirect users.'] = 'Imizila isetshenziselwa ukuqondisa kabusha abasebenzisi ngokuya nge-URL eceliwe.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Sesha abasebenzisi ngegama noma faka igama lendima ukubona bonke abasebenzisi ngalendima.';
$Definition['Secondary Button'] = 'Inkinobho Yesibili';
$Definition['Secondary Buttons'] = 'Izinkinobho Zesibili';
$Definition['Security.Hsts.HTTPSWarning'] = 'Isexwayiso: Vumela lesi sici kuphela uma uqiniseka ukuthi wonke amasizinda akho enzelwe i-HTTPS ngezitifiketi ezivumelekile.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Uma unikwe amandla, lo mthetho usebenza kuzo zonke izizinda zesayithi lakho.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Sincoma ukuqala ngobudala obukhulu beviki eli-1 bese ulukhulisa lube inyanga eyi-1 bese kuthi unyaka ongu-1 uma usuqala isayithi lakho lisebenza njengoba bekulindelekile.';
$Definition['Security.Hsts.SubmitWarning'] = 'Isexwayiso: Kuhle ukusekela ukulayisha kuqala i-HSTS njengomkhuba ongcono kakhulu. Kodwa-ke, kufanele uhambise isiza sakho ku-hispreloadrere.org ukuze uqinisekise ukuthi ilayishwa ngempumelelo (okusho ukuthola ukuvikelwa okugcwele kokucushwa okuhlosiwe).';
$Definition['Select the default type for this role, if any.'] = 'Khetha uhlobo oluzenzakalelayo lwale ndima, uma ikhona.';
$Definition['Select the import source'] = 'Khetha umthombo wokungenisa';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Ikholamu elenziwe "%s" yehlulekile ukungaphatheki kahle.';
$Definition['Shadowed'] = 'Kuthunyelwe';
$Definition['ShareImageDescription'] = 'Lapho othile abelana ngesixhumanisi kusuka kusayithi lakho sizama futhi sibambe isithombe esivela ekhasini. Uma kungekho isithombe ekhasini khona-ke sizosebenzisa lesi sithombe esikhundleni. Lesi sithombe kufanele okungenani sibe ngu-50 × 50, kepha sincoma ama-200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Vula le ndlela ukukhombisa zonke izindawo ezingena ephaketheni. Ukuvula le nketho kuzokhombisa kuphela izindawo kubasebenzisi abangaphatha amaphakethe.';
$Definition['Solid'] = 'Kuqinile';
$Definition['Some older themes don\'t support full editing capability.'] = 'Ezinye izingqikithi ezindala azixhasi ukusekelwa okugcwele kokuhlela. Ukuze ubone ukuthi itimu isekela ini ungahamba ngaphezulu kwegama layo ukubona ukuthi ukuhlela kuzoqala kuphi.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Ezinye izingqikithi zingadinga ukuvuselelwa ukuze zisebenze nesigaba esilandelayo. Ungakhubaza isici ngenkathi uvuselela itimu yakho.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Imikhawulo ekhethekile: Abasebenzisi kuphela abanemvume yeGarden.Curation.Manage bangasebenzisa lokhu kusabela.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Cacisa ukufana noma ukufana okugcwele lapho udala ukuvinjelwa.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Chitha isikhathi esincane ucabanga ukuthi usichaza kanjani isiza sakho lapha. Ukunikeza isiza sakho isihloko esinenjongo nencazelo emfushane kungasiza isikhundla sakho ezinjini zokusesha.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Hlanganisa ama-imeyili akho ngokungeza ilogo nokwenza imibala ibe ngokwezifiso.';
$Definition['Start Import'] = 'Qala Ukungenisa';
$Definition['Start the first discussion.'] = 'Qondisa ibhola emphakathini wakho <a href="{/post/discussion,url}">ngokuqala ingxoxo yokuqala</a> manje.';
$Definition['Subcommunities'] = 'Imiphakathi';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Ukumaka kuvumela abasebenzisi ukuthi bangeze ithegi ezingxoxweni abaqala ngazo ukuze bazenze zitholakale.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Izifanekiso yizindikimba ezijwayelekile. Ukuze ubenzise ngokwezifiso, kufanele udale ikhophi.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Isiqinisekisi i-%s asinazo izinketho zokucushwa ngokwezifiso.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB Ilebhu ye- <0/> idinga ukulungiswa ukuze ifane netimu yakho yangokwezifiso. Lokhu kungenziwa kusetshenziswa isihleli sethu setimu esisha. <1>Thola okuningi.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Isengezo asikwazanga ukunikwa amandla ngoba sikhiphe iphutha elibulalayo: <pre> %s </pre>';
$Definition['The addon has already been downloaded.'] = 'Isengezo sesivele silandiwe.';
$Definition['The banner logo appears at the top of your forum.'] = 'Ilogo yesibhengezo ivela phezulu kwiforamu yakho.';
$Definition['The banner title appears on the top-left of every page.'] = 'Isihloko sesibhengezo sivela ngakwesobunxele sawo wonke amakhasi.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Isihloko sesibhengezo siyavela kubhengezo lesayithi lakho nakwibha yesihloko sesiphequluli sakho. Kufanele kube ngaphansi kwezinhlamvu ezingama-20. Uma ilogo yesibhengezo ilayishwa, izothatha isikhundla sesihloko sesibhengezo kumakhasi eforamu abheke abasebenzisi. Futhi, gcina engqondweni ezinye izingqikithi zingase futhi zifihle lesi sihloko.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Ifomu lokubhaliswa eliyisisekelo lidinga</strong> abasebenzisi abasha ukuthi bakopishe umbhalo osuka esithombeni seCAPTCHA ukugcina ama-spammers engangeni. Udinga i-akhawunti <a href="http://recaptcha.net/">ku-reaptaptcha.net</a> . Ukubhalisela MAHHALA futhi kulula. Uma usubhalisile, buyela lapha bese ufaka izilungiselelo ezilandelayo:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Umsebenzisi wedatha oyichazile akanayo imvume yokufinyelela ku-database. Ngabe usuyenzile i-database? Imininingwane yabika: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Izinguquko ezilandelayo zesakhiwo ziyadingeka database wakho.';
$Definition['The import file does not contain any data.'] = 'Ifayela lokungenisa alinayo idatha.';
$Definition['The import file is not in the correct format.'] = 'Ifayela lokungenisa alikho ngendlela eyiyo.';
$Definition['The location of the authentication endpoint.'] = 'Indawo yendawo yokugcina yokufakazela ubuqiniso.';
$Definition['ThemeHelp'] = 'Izindikimba zikuvumela ukuthi ushintshe ukubukeka nokuzwa kwesayithi lakho. <br /> Lapho isihloko sesingezwe kufolda yakho ye-%s, ungasivumela lapha.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Ukubuka kuqala itimu kukhawulelwe ekuboniseni isifanekiso sengqikithi kanye ne-css.';
$Definition['Theming Guide'] = 'Umhlahlandlela Wokuqondisa';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Isiqinisekisi sephasiwedi asinazo izinketho zokucushwa ngokwezifiso.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Azikho izinguquko zesakhiwo sedatha ezidingekayo. Kungenzeka kube, noma kunjalo, kube nezinguquko zedatha.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Kunezinhlobo ezimbili zezinkinobho kwisicelo: eyokuqala neyesekondari.';
$Definition['The route was saved successfully.'] = 'Indlela isindiswe ngempumelelo.';
$Definition['The text of the pocket.'] = 'Faka umbhalo wephakethe. Lokhu kuzoba umphumela njengoba nje uthayipha ngakho qiniseka ukuthi ufaka i-HTML esemthethweni.';
$Definition['The user table was not in the import file.'] = 'Itafula lomsebenzisi belingekho kufayela lokungenisa.';
$Definition['The Vanilla 2 Exporter'] = 'Umthengisi we-Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'I-Vanilla Statistics iguqula ideshibhodi yesithangami sakho ibe ithuluzi lokubika labahlaziyi, ikuvumela ukuthi ubuyekeze umsebenzi esithangamini sakho ngezikhathi ezithile. <a href="http://vanillaforums.org/docs/vanillastatistics">Ungafunda okuningi mayelana neVanilla Statistics</a> kumadokhumenti ethu.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Zisebenza njengezindikimba ezijwayelekile. Uma eyodwa ingeziwe kufolda yezindikimba, ungayinika amandla lapha.';
$Definition['This is a style guide of your theme.'] = 'Lesi umhlahlandlela wesitimu sengqikithi yakho. Inezibonelo zezinto ezibonakalayo ezisetshenzisiwe kulo lonke uhlelo lokusebenza. Ungachofoza amawijethi ahlukahlukene njenge <0> Isihloko Bar </0> noma <1> Isibhengezo </1> ukuhlela izakhiwo zabo kuphaneli eseceleni.';
$Definition['This is the administrative dashboard for your new community.'] = 'Le deshibhodi yokulawula yomphakathi wakho omusha. Bheka izinketho zokumisa ohlangothini. Ukusuka lapho ungahlela ukuthi umphakathi wakho usebenza kanjani. <b>Ngokuzenzakalelayo, abasebenzisi kuphelaendima ethi "Administrator" abangabona le ngxenye yomphakathi wakho.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Yilapho ungavumela khona futhi uvivinye izici ezintsha ze-Vanilla, amakhasi nezinto.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Le lebhu ayikwazi ukukhutshazwa ngoba idinga itimu yamanje.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Le nketho ikhombisa / ifihla izindawo lapho amaphakethe angaya khona, kepha yenzelwe abasebenzisi kuphela abanemvume yokwengeza / ukuhlela amaphakethe. Zama ukubonisa izindawo bese uvakashela isayithi lakho.';
$Definition['This page lists the endpoints of your API.'] = 'Leli khasi libonisa uhlu lwe-API yakho. Chofoza iziphetho ukuthola eminye imininingwane. Ungenza izingcingo bukhoma ku-API kusuka kuleli khasi noma ngaphandle usebenzisa ithokheni yokufinyelela.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Le ndima ulwazi lomuntu siqu. Abasebenzisi abanemvume yokubuka imininingwane yabantu kuphela abazoyibona.';
$Definition['This setting loads the page before executing Javascript.'] = 'Lokhu kulungiswa kulayisha ikhasi ngaphambi kokukhipha iJavascript okungathuthukisa i-SEO yakho. <br> <strong>** Isexwayiso: Ukunika amandla lesi sici kungadala amaphutha weJavascript kusayithi lakho.</strong>';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Le ndatshana ayikwazi ukususwa ngoba yingqikithi esetshenziswayo njengamanje.';
$Definition['Tiled Layout'] = 'Isakhiwo Esifakiwe';
$Definition['Title Bar'] = 'Ibha yesihloko';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Ukuze ushumeke iforamu yakho yeVanilla kuwebhusayithi yakho, sebenzisa ikhodi elandelayo.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Amakheli amaningi kakhulu! Sizokuthumela kumakheli %s ngasikhathi sinye.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Ukuvikela ukuhlukunyezwa, amanye amathuluzi afihla ngokuzenzakalela okuqukethwe futhi aklelise lapha kuze kuvunyelwe ngokomthetho ngumongameli.';
$Definition['TouchIconDescription'] = 'Isithonjana sokuthinta sivela lapho ubeka uphawu iwebhusayithi kuwebhusayithi yesikrini se-Apple. Lokhu kuvame ngamaphikseli ayi-152. I-Apple ingeza amakhona ayindilinga kanye nomphumela wokukhanyisa ngokuzenzakalelayo.';
$Definition['Transparent'] = 'Okusobala';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'I-Twitter Connect ivumela abasebenzisi ukuthi bangene ngemvume besebenzisa i-akhawunti yabo ye-Twitter. <b>Kufanele ubhalise uhlelo lwakho lokusebenza ne-Twitter ukuze le plugin isebenze.</b>';

$Definition['Usercards'] = 'Ama-usercards';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Ama-usercards akuvumela ukuthi uthole isifinyezo esisheshayo esiku-inthanethi semininingwane yomsebenzisi. Lapho ubuka okuthunyelwe namabhodi wabaphambili, chofoza egameni lomsebenzisi ukubona ikhadi elibonisa imininingwane eyisisekelo yephrofayili yabasebenzisi ngaphandle kokuzulazula kude nekhasi. Nika amandla lesi sici ukwengeza ama-usercards kutimu yakho yangokwezifiso.';
$Definition['User inputs are based on the global background and text colors.'] = 'Okufakwayo komsebenzisi kusekelwe kumbala wembulunga yonke nemibala yombhalo.';
$Definition['User Profile'] = 'Iphrofayili Yomsebenzisi';
$Definition['Users may sign into your site using their Twitter account.'] = 'Abasebenzisi bangangena ngemvume kwisayithi lakho besebenzisa i-akhawunti yabo ye-Twitter.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Sebenzisa inkinobho engenhla kwekhasi ukudala umthetho wokuvinjelwa.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Sebenzisa i-plugin ye-WordPress ukusetha amazwana e-Vanilla kubhulogi yakho, noma usebenzise ikhodi yendawo yonke ukusetha amazwana e-Vanilla kunoma iyiphi enye ipulatifomu.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Insizakalo entsha yokucinga kaVanilla ekugcineni ifikile. Nika amandla i-UI yethu yekhasi lokusesha elisha ukuthola ukufinyelela kuzici ezintsha zosesho ezinjengokusesha kwamaLungu, ukuhlungwa kosesho nokugqanyiswa kwethemu.';
$Definition['Vanilla Export: %s, Source: %s'] = 'I-Vanilla Export: %s, Umthombo: %s';
$Definition['Vanilla Labs'] = 'Amalebhu e-Vanilla';
$Definition['Vanilla Statistics are currently disabled'] = 'Izibalo zeVanilla okwamanje zikhutshaziwe';
$Definition['Verify and restore'] = 'Qinisekisa futhi ubuyisele';
$Definition['VerifyUser'] = 'Faka uqhwishi ebhokisini umsebenzisi ukumaka kubo njengoba <b>eliqinisekisiwe lokubona i</b> ngakho okuthunyelwe kwabo abayi amakwe njengogaxekile futhi. Lokhu kuzophinda kubuyise konke okuthunyelwe kwabo okulindile.';
$Definition['Video tutorial on advanced settings'] = 'Isifundo sevidiyo kuzilungiselelo ezithuthukile';
$Definition['Video tutorial on finding &amp; managing users'] = 'Isifundo sevidiyo sokuthola nokulawula abasebenzisi';
$Definition['Video tutorial on managing appearance'] = 'Isifundo sevidiyo sokuphatha ukubukeka';
$Definition['Video tutorial on managing categories'] = 'Isifundo sevidiyo sokuphatha izigaba';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Isifundo sevidiyo sokuphatha izindima nezimvume';
$Definition['Video tutorial on user registration'] = 'Isifundo sevidiyo ekubhalisweni komsebenzisi';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Isexwayiso: Ukunika amandla lesi sici kungadala amaphutha weJavascript kusayithi lakho.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Isexwayiso</b> : Ukulungiswa kweseva yakho akusekeli ukulayisha idatha okusheshayo. Uma ungenisa ifayela elikhulu kakhulu (imibono engaphezulu kwama-200,000) ungahle uthande ukucabanga ngokushintsha ukumiswa kwakho. Chofoza <a href="http://vanillaforums.com/porter">lapha</a> ukuthola eminye imininingwane.';
$Definition['Warning: This is for advanced users.'] = '<b>Isexwayiso</b> : Lokhu kwenzelwa abasebenzisi abasezingeni eliphezulu futhi kudinga ukuthi wenze ushintsho olwengeziwe kuseva yakho ye-web. Lokhu kuvame ukutholakala kuphela uma uzinikezele noma usingatha i-vps. Ungazami lokhu uma ungazi ukuthi wenzani.';
$Definition['Webhooks'] = 'Ama-Webhooks';
$Definition['Welcome to Labs!'] = 'Uyemukelwa kumaLab!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Uyemukelwa kwi-UI ye-theme ka-Vanilla. Leli khasi libala zonke izingqikithi zakho ezikhona, futhi likuvumela ukuthi uzikopishe noma uzihlele.';
$Definition['Welcome To Your Theme'] = 'Uyemukelwa ku-Itimu Yakho';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Sincoma ukusabela okuhle kakhulu ukukhuthaza ukubamba iqhaza.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Uma unikwe amandla, ungaphatha imikhiqizo, kanye namaqembu amancane weqembu ngaleyo mikhiqizo.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Uma ukhetha i-Full Bleed, ingemuva lakho libonakala.';
$Definition['Which reactions you use really depends on your community.'] = 'Ukuphendula okusebenzisayo kuxhomeke kumphakathi wakho, kepha sincoma ukugcina amaphuzu ambalwa engqondweni.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Usuzosebenzisa inketho yesakhiwo esisha. Lokhu kungenziwa ngokwezifiso futhi kubukwe kuqala kusetshenziswa i-Theme Editor yethu. <0>Funda kabanzi</0>.';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Ungavimba bonke abasebenzisi ngamakheli we-IP agqokwa nge "111.111.111" ngokungeza ukuvinjelwa kohlobo lwe-IP ngenani "111.111.111. *".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Ungavimbela amakheli we-IP, amakheli e-imeyili kanye namagama abasebenzisi.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Ungazikhetha kwesinye sezitayela ezahlukahlukene lesi sihloko esikunikezayo.';
$Definition['You can configure some values differently for different screensizes.'] = 'Ungahlela amanye amanani ngendlela eyehlukile kwizikrini ezihlukile.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Ungaxhuma kumasayithi amaningi asekela i-jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Uma ifayela lakho likhulu kakhulu ukulayisha ngokuqondile kuleli khasi ungalibeka kufolda yakho / yokulayisha. Qinisekisa igama lefayela okuqala ngegama elithi <b>ukuthekelisa</b> kanye imikhawulo nomunye <b>.txt, .gz.</b>';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Ungacacisa ubude obuphakathi bokuposa ukuze ukhubaze okuthunyelwe okufushane.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Ungalayisha i-Font Yokwezifiso kusistimu yakho ye-Theming. Vele ukopishe bese unamathisela i-URL enkundleni.';
$Definition['You must select a file to import.'] = 'Kufanele ukhethe ifayela elizolingenisa.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Udinga ukungeza isizinda se-url yefont ku <0> Izizinda ezivunyelwe </0> ekucushweni kwesayithi. <1> Funda kabanzi ngamafonti wangokwezifiso. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Itimu yakho yeselula izokhutshazwa. Ukusetha izingqikithi ezahlukahlukene zeselula nezedeskithophu, sebenzisa i-UI yezingxoxo zakudala.';
