<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**चेतावनी: इस सुविधा को सक्षम करने से आपकी साइट पर Javascript त्रुटियां हो सकती हैं।**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>ध्यान दें</strong> भूमिका को हटाने के परिणाम स्वरूप उपयोगकर्ता की एप्लिकेशन तक पहुँच समाप्त हो सकती है।';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>सूचना!</strong> प्रतिस्थापन श्रेणी में चर्चाओं को बदलने पर चर्चा गायब हो सकती है (या दिखाई दे सकती है) यदि प्रतिस्थापन श्रेणी में हटाए जा रहे वर्ग की तुलना में अलग-अलग अनुमतियां हैं।';

$Definition['About.DisableStatistics'] = 'यदि आपको इस डेटा रिपोर्टिंग को किसी व्यावसायिक कारण से अक्षम करना होगा, तो आप अपनी स्थापना की कॉन्फ़िगरेशन फ़ाइल में निम्न पंक्ति जोड़कर ऐसा कर सकते हैं: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'इस निःशुल्क, ओपन-सोर्स सॉफ़्टवेयर के जीवन के लिए यह महत्वपूर्ण है कि हम वेनिला की पहुँच और प्रभावशीलता का प्रभावी आंकलन करें. हम निवेदन करते हैं कि कृपया इस डेटा की रिपोर्टिंग को अक्षम न करें.';
$Definition['AboutCommentEmbedding'] = 'वेनिला का उपयोग आपके ब्लॉग की मूल टिप्पणी प्रणाली के लिए ड्रॉप-इन प्रतिस्थापन के रूप में किया जा सकता है। वास्तव में, इसका उपयोग वेब पर किसी भी पेज पर टिप्पणियों को जोड़ने के लिए किया जा सकता है।';
$Definition['AboutEmbedding'] = 'एंबेडिंग आपके समुदाय के सभी या कुछ भाग को अन्य अनुप्रयोगों और वेब पेजेज़ में एम्बेड करने की अनुमति देता है।
';
$Definition['About Vanilla Statistics'] = 'वेनिला सांख्यिकी के बारे में';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'इस पेज में सबसे ऊपर "Visit Site" लिंक पर क्लिक करके अपने सामुदायिक फोरम तक पहुचें, या <a href={/,url}>clicking here</a> द्वारा। सामुदायिक फ़ोरम वह है जो आपके सभी उपयोगकर्ता और ग्राहक जब वे <a href="{/,url,domain}"> {/,url,domain} </a> पर जाएंगे, तो देख पाएंगे।';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'चर्चाओं और टिप्पणियों मे छवि अपलोड के विस्तार की सीमाएँ जोड़ें।';
$Definition['AddonProblems'] = '<h2> समस्याएँ?</h2><p> अगर कुछ ग़लत हो गया है और आप अपनी साइट का उपयोग नहीं कर सकते हैं, तो आप उन्हें मैन्युअल रूप से संपादित करके अक्षम कर सकते हैं: </p>%s';
$Definition['AddressBarColorDescription'] = 'कुछ ब्राउज़र एड्रेस बार के लिए एक रंग का समर्थन करते हैं। केवल मोबाइल।';
$Definition['Alert users if they click external link.'] = 'उपयोगकर्ताओं को सचेत करें यदि वे किसी पोस्ट में एक लिंक पर क्लिक करते हैं जो उन्हें मंच से दूर ले जाएगा। किसी विश्वसनीय डोमेन से मेल खाने वाले लिंक का अनुसरण करने पर उपयोगकर्ताओं को चेतावनी नहीं दी जाएगी';
$Definition['Alignment'] = 'संरेखण';
$Definition['Alignment (Mobile)'] = 'संरेखण (मोबाइल)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'सभी श्रेणियों को प्रत्येक के अंदर 5 हालिया चर्चाओं के चुनाव के साथ सूचीबद्ध किया गया है';
$Definition['Allow links to be transformed'] = 'लिंक को चर्चाओं और टिप्पणियों में एम्बेडेड अभ्यावेदन में बदलने की अनुमति दें। उदाहरण के लिए, एक YouTube लिंक एक एम्बेडेड वीडियो में परिवर्तित हो जाएगा।';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'वेनिला में अपने प्रोफाइल पेज से अपने स्वयं के अवतार को बदलने के लिए %s अनुमति वाले उपयोगकर्ताओं को अनुमति दें।';
$Definition['Anonymize IP Addresses'] = 'आईपी पते को अज्ञात करें';
$Definition['ApplicationHelp'] = 'एप्लिकेशन आपको अपनी साइट पर कार्यक्षमता के बड़े समूहों को जोड़ने की अनुमति देते हैं। <br />एक बार आपके %s फ़ोल्डर में कोई एप्लिकेशन जुड़ने के बाद, आप इसे यहाँ सक्षम या अक्षम कर सकते हैं।';
$Definition['Apply Layout'] = 'लेआउट लागू करें';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'क्या आप वाकई इस थीम को हटाना चाहते हैं? इसे स्थायी रूप से हटा दिया जाएगा।';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'क्या आपने सचमुच में सही डेटाबेस होस्ट का नाम दर्ज किया है? शायद आप इसे गलत समझे? डेटाबेस के मुताबिक: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'ईमेल पुष्टिकरण का उपयोग करने के लिए डिफ़ॉल्ट प्रकार "अपुष्ट" का कार्य आवश्यक है।';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'अप्रकाशित चर्चाओं, प्रश्नों, विचारों और टिप्पणियों के ड्राफ़्ट को स्वचालित रूप से सहेजें।';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'यदि वे इस ऊंचाई से अधिक हो जाते हैं, तो अवतारों को छोटा कर दिया जाएगा।';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'यदि वे इस चौड़ाई से अधिक हो जाते हैं, तो अवतारों को छोटा कर दिया जाएगा।';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'अवतार इस आकार में अपने थंबनेल सहेजे होंगे।';

$Definition['Background'] = 'पृष्ठभूमि';
$Definition['Background Image'] = 'पृष्ठभूमि छवि';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'रचनात्मक बनो! उन चीजों के बाद अपने रैंक का नामकरण करने का प्रयास करें जिनके बारे में समुदाय बात करता है।';
$Definition['Bordered'] = 'इसकी सीमाएं';
$Definition['Bordered (Unified)'] = 'सीमाबद्ध (एकीकृत)';
$Definition['Borderless'] = 'अनवधि';
$Definition['Border Radius'] = 'सीमा त्रिज्या';
$Definition['Brand Color'] = 'ब्रांड रंग';
$Definition['Buttons'] = 'बटन';
$Definition['Buttons & Inputs'] = 'बटन और इनपुट';
$Definition['Button Type'] = 'बटन प्रकार';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'नीचे दिए गए बटन पर क्लिक करके, आप उपयोगकर्ता खाते को हमेशा के लिए %s हटा देंगे।';

$Definition['Center Aligned'] = 'केंद्र ने संरेखित किया';
$Definition['Changes to the set day will take affect the following week.'] = 'निर्धारित दिन में परिवर्तन अगले सप्ताह प्रभावित होगा।';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'परिवर्तन केवल नए अपलोड किए गए अवतार पर लागू होंगे।';
$Definition['Change the sizes that avatar images are saved at.'] = 'उन आकारों को बदलें जिनमें अवतार चित्र सहेजे गए हैं।';
$Definition['Change the way your community works with plugins.'] = 'अपने कम्यूनिटी के प्लगइन्स के साथ काम करने का तरीका बदलें। हमने सॉफ्टवेयर के साथ लोकप्रिय प्लगइन्स को बंडल किया है, ऑनलाइन और अधिक उपलब्ध हैं.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'चेकबॉक्स एक ही समय में कई चर्चाओं या टिप्पणियों पर बैच क्रियाओं को करने की अनुमति देता है।';
$Definition['Check out our %s'] = 'हमारे %s को देखें';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'हमारे <0>दस्तावेज देखें</0> , या हमारे <1>विशेषज्ञों के समुदाय से पूछें</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'वेनिला विश्व का सबसे सरल, सबसे शक्तिशाली सामुदायिक मंच है. यह उपयोग करने में बहुत ही आसान है. इस परिचयात्मक वीडियो के साथ शुरू करें और नीचे दिए गए चरणों के साथ आगे बढ़ें. इसका आनंद लें!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'कोई ऐसा रोल चुनें जिसे ऑरफन यूजर्स को सौंपा जाएगा:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'इस सबकोम्यूनिटी के लिए एक थीम चुनें। <0> और पढ़ें </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'चुनें कि %s (टिप्पणी, संदेश, आदि) के लिए उपयोगकर्ता खाते से जुड़ी सभी सामग्री को कैसे संभालना है।';
$Definition['Choose Image'] = 'छवि चुनें';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'आप अपने अनुरोधों पर हस्ताक्षर करने के लिए एक कस्टम हैश एल्गोरिथ्म का चयन कर सकते हैं। हैश एल्गोरिथ्म का उपयोग आपके क्लाइंट लाइब्रेरी में भी किया जाना चाहिए। Md5 चुनें अगर आप सुनिश्चित नहीं हैं कि क्या चुनना है।';
$Definition['Choose the order items are sorted.'] = 'चुनें कि ऑर्डर आइटम सॉर्ट किए गए हैं।';
$Definition['Choose the page people should see when they visit <0/>'] = 'वह पृष्ठ चुनें जिसे लोगों को देखना चाहिए जब वे <0/> . पर जाते हैं';
$Definition['Choose the preferred layout for lists of categories.'] = 'श्रेणियों की सूचियों के लिए पसंदीदा लेआउट चुनें।';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'श्रेणियों की सूचियों के लिए पसंदीदा लेआउट चुनें। आप टाइल वाले लेआउट को संपादित कर सकते हैं।';
$Definition['Choose the preferred layout for lists of discussions.'] = 'चर्चाओं की सूचियों के लिए पसंदीदा लेआउट चुनें।';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'चर्चाओं की सूचियों के लिए पसंदीदा लेआउट चुनें। आप फाउंडेशन लेआउट को संपादित कर सकते हैं।';
$Definition['Color Overlay'] = 'रंग आवरण';
$Definition['Continue Import'] = 'आयात जारी रखें';
$Definition['Could not parse import file. The problem is near line %s.'] = 'आयात फ़ाइल पार्स नहीं कर सका। समस्या लाइन %s के पास है।';
$Definition['Create a localization CSV'] = 'एक स्थानीयकरण CSV तैयार करें';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'कस्टम थीम्स आपके द्वारा बनाई गई थीम हैं। आप उनकी प्रतिलिपि बना सकते हैं, नाम बदल सकते हैं या उनकी प्रतिलिपि बना सकते हैं।';

$Definition['Dark'] = 'अंधेरा';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'परिभाषित करें कि <a href="%s"> भूमिकाएँ और अनुमतियाँ </a> पेज पर फ़ाइलें कौन अपलोड और प्रबंधित कर सकता है।';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'अपने फ़ोरम होमपेज को परिभाषित करें, अपना लोगो अपलोड करें, आदि ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'भूमिका हटाने से यूज़र्स एप्लिकेशन तक पहुंच प्राप्त नहीं कर सकते हैं. ';
$Definition['Deleting forever cannot be undone.'] = 'आपके फोरम को साफ रखने में हटाना एक अच्छा तरीका है।';
$Definition['Digest Settings'] = 'डाइजेस्ट सेटिंग्स';
$Definition['Disable Google Sign In'] = 'Google साइन इन अक्षम करें';
$Definition['Disable OpenID'] = 'OpenID अक्षम करें';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = '<0>वेनिला लैब्स पेज . पर "नया एम्बेड सिस्टम" लैब अक्षम करें</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'चर्चा श्रेणियों का उपयोग आपके उपयोगकर्ताओं को अपने समुदाय के लिए सही तरीक़े से अपनी चर्चाओं को व्यवस्थित करने में मदद करता है।';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'अपने फोरम एडमिन डैशबोर्ड को एम्बेड ना करें (इसे पूरी स्क्रीन पर लाएं)';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'उन्हें सॉर्ट और नेस्ट करने के लिए नीचे की श्रेणियों को ड्रैग और ड्राप करें';

$Definition['EditContentTimeout.Notes'] = 'यदि किसी यूजर को कंटेंट संपादित करने की अनुमति है, तो वे अनुमतियाँ इसे ओवरराइड कर देंगी.';
$Definition['Edit Route'] = 'रूट संपादित करें';
$Definition['Edits to this theme apply to:'] = 'इस विषय पर संपादन इस पर लागू होता है:';
$Definition['Email digests will be sent on the selected day every week.'] = 'ईमेल डाइजेस्ट प्रत्येक सप्ताह चयनित दिन पर भेजा जाएगा।';
$Definition['Email sent from the application will be addressed from this email address'] = 'आवेदन से भेजे गए ईमेल को इस ईमेल पते से संबोधित किया जाएगा';
$Definition['Email sent from the application will be addressed from this name'] = 'आवेदन से भेजा गया ईमेल इसी नाम से संबोधित किया जाएगा';
$Definition['Email Settings'] = 'ईमेल सेटिंग्स';
$Definition['Embed Settings'] = 'एम्बेड सेटिंग्स';
$Definition['Embed your community forum into your website to increase engagement...'] = 'सहभागिता बढ़ाने के लिए अपनी वेबसाइट में अपना सामुदायिक फोरम एम्बेड करें ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'नवीनतम वेनिला सुविधाओं को सक्षम और परीक्षण करें।';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'WYSIWYG, सरल HTML, Markdown और BBCode सहित कई प्रारूपों में उन्नत संपादन में सक्षम बनाता है।';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'अपने समुदाय पृष्ठों के लिए एक कस्टम लेआउट लागू करने के लिए लेआउट संपादक को सक्षम करें। उपलब्ध विजेट्स के हमारे कैटलॉग का उपयोग करके सामग्री को प्रदर्शित करने के लिए हमारे नए संपादक का उपयोग करें।';
$Definition['Enter a descriptive name.'] = 'पॉकेट के लिए एक वर्णनात्मक नाम दर्ज करें। यह नाम कहीं भी दिखाई नहीं देगा सिवाय आपकी पॉकेट को प्रबंधित करने के लिए इसलिए इसका उपयोग केवल पॉकेट को याद रखने में मदद करने के लिए किया जाता है।';
$Definition['Enter a short name for the site.'] = 'साइट के लिए एक छोटा नाम दर्ज करें. यह साइन-इन बटनों पर प्रदर्शित होता है.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'अपने Wordpress ब्लॉग का पता दर्ज करें और हम इसे वहां से ले लेंगे।';
$Definition['Enter the connection settings for your sphinx server below.'] = 'नीचे अपने स्फिंक्स सर्वर के लिए कनेक्शन सेटिंग्स दर्ज करें।';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'प्रत्येक संपादन या विलोपन यहाँ रिकॉर्ड किया गया है. किसी भी बदलाव को पूर्ववत करने के लिए ‘Restore&rsquo का प्रयोग करें. ';
$Definition['Everyone who signs up gets a profile page.'] = 'आपके समुदाय के लिए साइन अप करने वाले हर व्यक्ति को एक सार्वजनिक प्रोफ़ाइल पृष्ठ मिलता है, जहाँ वे स्वयं की तस्वीर अपलोड कर सकते हैं, अपनी प्रोफ़ाइल सेटिंग प्रबंधित कर सकते हैं, और समुदाय में चल रही बढ़िया चीज़ों को ट्रैक कर सकते हैं। आपको <a href="{/profile,url}"> अब अपनी प्रोफ़ाइल को अनुकूलित करना चाहिए </a>।';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'आपकी साइट के प्रत्येक उपयोगकर्ता को कम से कम एक भूमिका सौंपी जाती है। रोल्स का उपयोग यह निर्धारित करने के लिए किया जाता है कि उपयोगकर्ताओं को क्या करने की अनुमति है।';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'फेसबुक कनेक्ट उपयोगकर्ताओं को अपने फेसबुक खाते का उपयोग करने में साइन इन करने की अनुमति देता है। <b> काम करने के लिए आपको इस प्लगइन के लिए फेसबुक के साथ अपना आवेदन पंजीकृत करना होगा। </b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'आपके द्वारा दर्ज यूजरनाम और पासवर्ड के साथ डेटाबेस से संपर्क में विफल रहा। क्या आपने उन्हें गलत टाइप किया? डेटाबेस ने रिपोर्ट किया: <code>%s</code>';
$Definition['Font'] = 'फ़ॉन्ट';
$Definition['Font Name'] = 'फ़ॉन्ट का नाम';
$Definition['Font URL'] = 'फ़ॉन्ट URL';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'केवल इस url<em>(अनुशंसित नहीं) </em> के माध्यम से डैशबोर्ड तक पहुँचने के लिए बाध्य करें';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'उदाहरण के लिए, आप "*@example.com" मान युक्त एक ईमेल-प्रकार का प्रतिबंध जोड़कर "example.com" ईमेल पते वाले सभी उपयोगकर्ताओं को प्रतिबंधित कर सकते हैं।';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'एसईओ प्रयोजनों के लिए, सर्च इंजन क्रॉलर को दूरस्थ यूआरएल में फोरम को देखने के लिए मजबूर होने से बाहर रखा गया है.';
$Definition['Foundation Layout'] = 'फाउंडेशन लेआउट';
$Definition['Full Anonymization'] = 'पूर्ण गुमनामीकरण';
$Definition['FullAnonymization.Description'] = '<strong>पूर्ण अज्ञातीकरण</strong> प्रत्येक आईपी पते को 0.0.0.0 से बदल देता है, जिससे एप्लिकेशन को आईपी पते के साथ काम करने की किसी भी पहुंच से प्रभावी ढंग से वंचित कर दिया जाता है। इस मामले में आईपी प्रतिबंध नियम बिल्कुल भी काम नहीं करेंगे।';
$Definition['Full Bleed'] = 'पूर्ण खून बहना';

$Definition['Garden.Import.Complete.Description'] = 'आपने एक आयात सफलतापूर्वक पूरा कर लिया है. 
    जब आप तैयार हों तो <b> समाप्त</b> पर क्लिक करें ';
$Definition['Garden.Import.Continue.Description'] = 'ऐसा प्रतीत होता है जैसे आप किसी आयात के बीच में हैं। कृपया निम्न में से कोई एक विकल्प चुनें।';
$Definition['Garden.Import.InputInstructions'] = 'आयात किए जा रहे डेटा से एडमिन उपयोगकर्ता का ईमेल और पासवर्ड दर्ज करें।';
$Definition['Garden.Privacy.IPs.Description'] = 'उपयोगकर्ता आईपी पते आमतौर पर स्वचालित प्रतिबंध नियमों, मॉडरेशन और स्पैम रोकथाम उद्देश्यों के लिए एकत्र किए जाते हैं। आईपी गुमनामीकरण को सक्षम करने से किसी भी उद्देश्य के लिए साइट में ट्रैक किए गए सभी आईपी पते गुमनाम हो जाएंगे, और इन उपकरणों की प्रभावशीलता कम हो जाएगी। इस सेटिंग में परिवर्तन पूर्वव्यापी नहीं हैं.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles. वेनिला में अपने प्रोफाइल पेज से अपने स्वयं के अवतार को बदलने की अनुमति दें।';
$Definition['Garden.StatisticsDisabled'] = 'आपने अपनी कॉन्फ़िगरेशन फ़ाइल में वैनिला सांख्यिकी को विशेष रूप से अक्षम किया है.';
$Definition['Garden.StatisticsLocal.Explain'] = 'यह फोरम एक परीक्षण वातावरण में चलता प्रतीत हो रहा है, या अन्यथा एक निजी IP की रिपोर्ट कर रहा है। डिफ़ॉल्ट रूप से, निजी IP पर चलने वाले फोरम को ट्रैक नहीं किया जाता है।';
$Definition['Garden.StatisticsLocal.Resolve'] = 'यदि आप सुनिश्चित हैं कि आपका फ़ोरम इंटरनेट से उपलब्ध है, तो आप आँकड़ों को यहाँ प्रस्तुत करने के लिए उसे बाध्य कर सकते हैं:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'आपकी config.php फ़ाइल रीड-ओनली प्रतीत होती है। इसका मतलब है कि वनीला आपके फ़ोरम के इंस्टॉलेशनID और इंस्टॉलेशनसीक्रेट को स्वचालित रूप से पंजीकृत करने में असमर्थ होगा।';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'इस समस्या को हल करने के लिए, फ़ाइल मोड 777 को अपने conf / config.php फ़ाइल में असाइन करें।';
$Definition['Global Styles'] = 'ग्लोबल स्टाइल्स';

$Definition['Heads Up!'] = 'सचेत!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'सावधान! यह एक विशेष भूमिका है जो सक्रिय सत्रों की अनुमति नहीं देती है। इस कारण से, अनुमति विकल्पों को "देखना" अनुमति के लिए सीमित कर दिया गया है।';
$Definition['Here are the ranks that users can achieve on your site.'] = 'यहां वे रैंक दिए गए हैं जो उपयोगकर्ता आपकी साइट पर प्राप्त कर सकते हैं। आप इन रैंकों को कस्टमाइज़ कर सकते हैं और नए जोड़ भी सकते हैं। यहाँ कुछ युक्तियाँ हैं।';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'यदि बैनर लोगो अपलोड किया गया है, तो यह यूज़र-फेसिंग फ़ोरम पेजों पर बैनर शीर्षक को बदल देगा.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'यदि कोई उपयोगकर्ता इस समयावधि के भीतर साइट पर नहीं जाता है तो वे स्वतः ही साइन आउट हो जाएंगे।';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'सक्षम होने पर, पोस्ट की पूरी सामग्री उपयोगकर्ताओं को ईमेल सूचनाओं में भेजी जाएगी।';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'यदि आप HTML और / या CSS के लिए नए हैं, तो यहां कुछ ट्यूटोरियल शुरू किए गए हैं:';
$Definition['If you have an old theme'] = 'यदि आपके पास एक पुरानी थीम है और आपको एक अलग डेस्कटॉप और मोबाइल थीम सेट करने की आवश्यकता है, तो आप पुराने थीम वाले UI के साथ ऐसा कर सकते हैं।';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'यदि आप चेतावनी के स्तर को घटाना चाहते हैं तो एक चेतावनी को हटा दें।';
$Definition['If you want to embed your forum, enable embedding.'] = 'यदि आप अपने फ़ोरम को एम्बेड करना चाहते हैं या अपने ब्लॉग में वैनिला की टिप्पणियों का उपयोग करना चाहते हैं तो आपको एम्बेडिंग को सक्षम करने की आवश्यकता है। यदि आप एम्बेडिंग का उपयोग नहीं कर रहे हैं तो हम इस सेटिंग को छोड़ने की सलाह देते हैं।';
$Definition['Image (Mobile)'] = 'छवि (मोबाइल)';
$Definition['Import'] = 'आयात';
$Definition['Importing to Vanilla'] = 'वेनिला को आयात करना';
$Definition['In additon to the widgets there are also'] = 'विजेट में एडिटॉन में <0> ग्लोबल स्टाइल्स भी हैं </0> । वैश्विक शैलियों को संपादित करने के लिए पृष्ठ पर कहीं भी क्लिक करें, जैसे कि यह पाठ।';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'अपनी थीम में फाउंडेशन पेज और कंपोनेंट्स को एकीकृत करें';
$Definition['Internationalization & Localization'] = 'अंतर्राष्ट्रीयकरण और स्थानीयकरण';
$Definition['Invalid URL'] = 'अवैध यूआरएल';
$Definition['Invitation email failed to send: %'] = 'हालाँकि आमंत्रण सफलतापूर्वक बनाया गया था, लेकिन ईमेल भेजने में विफल रहा। सर्वर ने निम्न त्रुटि की सूचना दी: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'जब आप निमंत्रण द्वारा पंजीकरण का उपयोग करते हैं तो उपयोगकर्ताओं के पास उनके प्रोफ़ाइल पृष्ठों पर <a href="%s" class="Popup">मेरा निमंत्रण</a> नाम से एक लिंक होगा।';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'ऐसा लगता है कि आपके द्वारा निर्दिष्ट डेटाबेस अभी तक मौजूद नहीं है। क्या आपने इसे अभी तक बना लिया है? क्या आपने नाम गलत टाइप किया है? डेटाबेस ने रिपोर्ट किया: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'किसी टिप्पणी में अनुमत अधिकतम वर्णों को उचित आकार में रखना एक अच्छा विचार है।';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'किसी पोस्ट में उचित आकार में अधिकतम वर्णों को रखने की अनुमति देना एक अच्छा विचार है।';

$Definition['Kick-start your community and increase user engagement.'] = 'अपने कम्यूनिटी को किक-स्टार्ट करें और यूजर सहभागिता बढ़ाएँ';

$Definition['Labs'] = 'प्रयोगशालाओं';
$Definition['Layout Editor'] = 'लेआउट संपादक';
$Definition['Learn about custom routing.'] = 'कस्टम रूटिंग के बारे में जानें।';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'अपने फ़ोरम के स्वरूप और अनुभव को पूरी तरह से बदलना सीखें: अपना लोगो अपलोड करें, अपना मुखपृष्ठ सेट करें, एक थीम चुनें और इसे अपनी पसंद के अनुसार बनाएँ।';
$Definition['Learn how to use the basic functionality of your forum.'] = 'अपने फ़ोरम की मूल कार्य का उपयोग करना सीखें.';
$Definition['Left Aligned'] = 'बाएं संरेखित';
$Definition['Light'] = 'रोशनी';
$Definition['Links'] = 'लिंक';
$Definition['Locales allow you to support other languages on your site.'] = 'लोकेल्स आपको अपनी साइट पर अन्य भाषाओं का समर्थन करने की अनुमति देते हैं। उन लोकेल्स को सक्षम और अक्षम करें जिन्हें आप यहां उपलब्ध कराना चाहते हैं।';
$Definition['Lockout Time (seconds)'] = 'तालाबंदी का समय (सेकंड)';
$Definition['LogoDescription'] = 'आपकी साइट के शीर्ष पर बैनर लोगो दिखाई देता है।';
$Definition['LogoDisclaimer'] = 'थीम संपादक और कुछ कस्टम थीम के साथ बनाए गए थीम इस सेटिंग का उपयोग नहीं करते हैं।';
$Definition['Looking for the Old Embed System?'] = 'पुराने एम्बेड सिस्टम की तलाश है?';

$Definition['Make sure you click View Page'] = 'आपके कैटेगरी के पेज सहेजने के बाद कैसी दिखती हैं, यह सुनिश्चित करने के लिए आप <a href="%s"> देखें पेज </a> पर क्लिक करें.';
$Definition['Manage Routes'] = 'मार्गों का प्रबंधन करें';
$Definition['Managing Users'] = 'उपयोगकर्ताओं को प्रबंधित करना';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'चीजों को स्पैम नहीं के रूप में चिह्नित करने से वे आपके फोरम में वापस आ जाएंगी।';
$Definition['Marking things as not spam will put them back in your forum.'] = 'स्पैम नही  के रूप में चीजों को चिह्नित करना उन्हें आपके फोरम में वापस डाल देगा।';
$Definition['Messages can appear anywhere in your application.'] = 'संदेश आपके एप्लीकेशन में कहीं भी दिखाई दे सकते हैं, और आपके उपयोगकर्ताओं को समाचार और कार्यक्रमों के बारे में सूचित करने के लिए उपयोग किए जा सकते हैं। अपने संदेशों को ऊपर या नीचे करके पुनः व्यवस्थित करने के लिए इस पृष्ठ का उपयोग करें।';
$Definition['MobileLogoDescription'] = 'आपकी साइट के शीर्ष पर मोबाइल बैनर लोगो दिखाई देता है।';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'मोबाइल थीम आपको छोटे उपकरणों पर अपनी साइट के रंगरूप को बदलने की अनुमति देती हैं।';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB नया लेआउट संपादक आपकी स्टाइल गाइड (औपचारिक रूप से थीम संपादक) में सेट की गई थीम को इनहेरिट करेगा। <1>और जानें</1>';
$Definition['Need More Help?'] = 'क्या और मदद चाहिये?';
$Definition['Need more help?'] = 'क्या और मदद चाहिये?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'इस गहराई से अधिक नेस्टेड श्रेणियों को अल्पविराम-सीमांकित सूची में रखा जाएगा।';
$Definition['New Embed System'] = 'नया एम्बेड सिस्टम';
$Definition['New Quick Links'] = 'नए त्वरित लिंक';
$Definition['New Search Page'] = 'नया खोज पृष्ठ';
$Definition['No Anonymization'] = 'कोई गुमनामीकरण नहीं';
$Definition['Not getting what you expect when you preview your theme?'] = 'जब आप अपने विषय का पूर्वावलोकन करते हैं तो आपको वह नहीं मिल रहा है, जिसकी आपको उम्मीद है?';
$Definition['Notify me when people comment on my addons.'] = 'जब लोग मेरे ऐड-ऑन ऐडॉन पर टिप्पणी करें तब मुझे सूचित करें.';
$Definition['No unconfirmed role available for email confirmation.'] = 'ईमेल पुष्टिकरण का उपयोग करने के लिए साइट को डिफ़ॉल्ट प्रकार "अपुष्ट" की भूमिका चाहिए। कृपया इस सेटिंग को सक्षम करने के लिए एक भूमिका जोड़ें।';

$Definition['Old Theming UI'] = 'पुराने थेमिंग यूआई';
$Definition['Once enabled, only members will see inside your community.'] = 'एक बार सक्षम होने के बाद, केवल सदस्य आपके समुदाय के अंदर देखेंगे।';
$Definition['OrgDescription'] = 'आपके संगठन के नाम का उपयोग SEO माइक्रोडेटा और JSON+LD के लिए किया जाता है';
$Definition['Outline'] = 'रेखांकित करें';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'ओवरराइड किए गए विचार या थीमहूक के अनपेक्षित दुष्प्रभाव हो सकते हैं और इसका पूर्वावलोकन नहीं किया जाता है।';

$Definition['Partial Anonymization'] = 'आंशिक गुमनामीकरण';
$Definition['PartialAnonymization.Description'] = '<strong>आंशिक अज्ञातीकरण</strong> आईपी पते के केवल अंतिम ऑक्टेट को अज्ञात करता है। उदाहरण के लिए 254.230.05.153 254.230.05.0 बन जाएगा। यह आईपी प्रतिबंध नियमों को कार्य करने की अनुमति देते हुए कुछ गुमनामी प्रदान करता है।';
$Definition['Password.MinLength'] = 'पासवर्ड बनाने और पेज रीसेट करने पर उपयोगकर्ताओं के पासवर्ड के लिए न्यूनतम वर्ण लंबाई की अनुमति है।';
$Definition['Please choose an authenticator to configure.'] = 'कॉन्फ़िगर करने के लिए कृपया एक  प्रमाणक चुनें। ';
$Definition['PluginHelp'] = 'प्लगइन आपको अपनी साइट में कार्यक्षमता जोड़ने की अनुमति देते हैं.<br /> एक बार आपके %s फ़ोल्डर में प्लगइन जोड़ दिए जाने के बाद, आप यहाँ इसे सक्षम या अक्षम कर सकते हैं.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'पॉकेट को मुख्य चर्चा सूची पर प्रत्येक चर्चा के बीच प्रदर्शित किया जाता है। चूँकि चर्चा में आमतौर पर <li>..</li> टैग लगे होते हैं, आपको अपने पॉकेट को उन टैग के हिसाब से बनाना होगा।';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'पॉकेट्स आपको एप्लिकेशन के आसपास विभिन्न स्थानों पर मुफ्त-फॉर्म HTML जोड़ने देते हैं।';
$Definition['Preset'] = 'प्रीसेट';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'चर्चाओं की संख्या सीमित करके अपने मंच पर स्पैम को रोकें & amp; टिप्पणियां जो उपयोगकर्ता किसी निश्चित समय के भीतर पोस्ट कर सकते हैं।';
$Definition['Primary Button'] = 'प्राथमिक बटन';
$Definition['Primary Buttons'] = 'प्राथमिक बटन';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'वेनिला के लिए थीम बनाने के लिए क्विक-स्टार्ट गाइड';
$Definition['Quicklinks'] = 'त्वरित सम्पक';
$Definition['Quick Links is a default component on community pages.'] = 'त्वरित लिंक समुदाय पृष्ठों पर एक डिफ़ॉल्ट घटक है। हमारे थीम संपादक का उपयोग करके इस मेनू से लिंक जोड़ने, संपादित करने या छिपाने के लिए हमारे नए त्वरित लिंक घटक को सक्षम करें।';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'वर्डप्रेस के लिए  रेडीमेड वनीला कमेंट प्लग-इन   ';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'WordPress के लिए पहले से तैयार वनिला फोरम प्लगइन';
$Definition['Realtime progress bars: %s'] = 'रीयलटाइम प्रगति बार: %s';
$Definition['Recommended dimensions are about 400px by 300px or smaller with similar ratio.'] = 'अनुशंसित आयाम लगभग 400px x 300px या समान अनुपात के साथ छोटे हैं।';
$Definition['Recommend special ranks for admins and mods.'] = 'मध्यस्थों और प्रशासकों के लिए विशेष रैंक रखना एक अच्छा विचार है ताकि आपका समुदाय आसानी से देख सके कि प्रभारी कौन है।';
$Definition['Recommend starting with five ranks.'] = 'आप बहुत अधिक रैंक नहीं चाहते हैं। हम पांच से शुरू करने की सलाह देते हैं। यदि आपका समुदाय वास्तव में बड़ा है तो आप अधिक जोड़ सकते हैं।';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'मेनू से चर्चा और श्रेणियों के लिंक निकालें। नहीं मिला पृष्ठ 404 वापस करने के लिए चर्चा और श्रेणी से संबंधित पृष्ठों को सेट करें।';
$Definition['Requires “Flag” reaction permission.'] = '"ध्वज" प्रतिक्रिया अनुमति की आवश्यकता है।';
$Definition['Requires “Negative” reaction permission.'] = '"नकारात्मक" प्रतिक्रिया अनुमति की आवश्यकता है।';
$Definition['Requires “Positive” reaction permission.'] = '"सकारात्मक" प्रतिक्रिया अनुमति की आवश्यकता है।';
$Definition['Restoring your selection removes the items from this list.'] = 'जब आप रिस्टोर करते हैं तो सामग्रियों को  इस सूची से हटाकर पुनः साइट पर रख दिया जाता है।';
$Definition['RichEditor.QuoteEnable.Notes'] = 'रिच एडिटर में उद्धरण सक्रिय करने के लिए निम्नलिखित विकल्प का उपयोग करें। यह केवल तभी लागू होगा जब डिफ़ॉल्ट फ़ॉर्मेटर "रिच" हो।';
$Definition['Route Expression'] = 'रूट एक्सप्रेशन';
$Definition['Routes are used to redirect users.'] = 'रूट का उपयोग उपयोगकर्ताओं को अनुरोधित URL के आधार पर पुनर्निर्देशित करने के लिए किया जाता है।';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'नाम से यूज़र्स को खोजें या उस भूमिका वाले सभी यूज़र्स को देखने के लिए किसी एक भूमिका का नाम दर्ज करें.';
$Definition['Secondary Button'] = 'द्वितीयक बटन';
$Definition['Secondary Buttons'] = 'माध्यमिक बटन';
$Definition['Security.Hsts.HTTPSWarning'] = 'चेतावनी: इस सुविधा को केवल तब सक्षम करें जब आप सुनिश्चित हों कि आपके सभी उपडोमेन को मान्य सर्टिफ़िकेट युक्त HTTPS के लिए कॉन्फ़िगर किया गया है।';
$Definition['Security.Hsts.IncludeSubDomains'] = 'सक्रीय किए जाने पर यह नियम आपकी साइट के सभी उपडोमेन पर भी लागू होता है।';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'हम अधिकतम 1 सप्ताह के समय के साथ शुरू करने और जब आप अपनी साइट को उम्मीद के मुताबिक काम करते देखते हैं तब इसे 1 महीने और फिर 1 वर्ष तक बढ़ाने की सलाह देते हैं।';
$Definition['Security.Hsts.SubmitWarning'] = 'चेतावनी: एक बेहतरीन कार्य प्रणाली के रूप में HSTS प्रीलोडिंग का समर्थन करना सबसे अच्छा है। फ़िर भी, अपनी साईट का सफ़लतापूर्वक प्रीलोड सुनिश्चित करने के लिए आपको अपनी साईट को hstspreload.org पर सबमिट करना आवश्यक है। (अर्थात इच्छित कॉन्फ़िगरेशन के लिए पूर्ण सुरक्षा प्राप्त करना)।';
$Definition['See the documentation'] = 'दस्तावेज़ीकरण देखें';
$Definition['Select the default type for this role, if any.'] = 'इस भूमिका के लिए डिफ़ॉल्ट प्रकार का चयन करें, यदि कोई हो।';
$Definition['Select the import source'] = 'आयात स्रोत चुनें';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'सीरियलाइज्ड कॉलम "%s" को अनसीरियलाइज्ड  नहीं किया जा सका.';
$Definition['Session Timeout'] = 'सेशन खत्म';
$Definition['Shadowed'] = 'छाया';
$Definition['ShareImageDescription'] = 'जब कोई आपकी साइट से लिंक साझा करता है, तो हम पृष्ठ से एक छवि लेते हैं। यदि पृष्ठ पर कोई छवि नहीं है, तो हम इस छवि का उपयोग करेंगे। छवि कम से कम 50 × 50 होनी चाहिए, लेकिन हम 200 × 200 की सलाह देते हैं।';
$Definition['Show all possible pocket locations.'] = 'सभी संभावित पॉकेट स्थानों को दिखाने के लिए इस विकल्प को शुरू करें. 
इस विकल्प को शुरू  करने से केवल उन यूज़र्स को स्थान दिखाई देंगे जो पॉकेट का प्रबंधन कर सकते हैं.';
$Definition['SignIn.LockoutTime'] = 'लॉगिन प्रयासों की संख्या से अधिक होने के बाद किसी उपयोगकर्ता को लॉग इन करने से रोके जाने की अवधि।';
$Definition['Solid'] = 'ठोस';
$Definition['Some browsers support a color for the address bar.'] = 'कुछ ब्राउज़र पता बार के लिए रंग का समर्थन करते हैं।';
$Definition['Some older themes don\'t support full editing capability.'] = 'कुछ पुराने विषय पूर्ण संपादन क्षमता का समर्थन नहीं करते हैं। यह देखने के लिए कि कोई थीम किसका समर्थन करती है आप उसके नाम पर होवर करके देख सकते हैं कि संपादन कहां प्रभावी होंगे।';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'निम्नलिखित श्रेणी के साथ काम करने के लिए कुछ विषयों को अद्यतन करने की आवश्यकता हो सकती है। आप अपने विषय को अपडेट करते समय सुविधा को अक्षम कर सकते हैं।';
$Definition['Sometimes you want to embed your Vanilla site'] = 'कभी-कभी आप अपनी वेनिला साइट को किसी अन्य साइट के अंदर एम्बेड करना चाहते हैं। वेनिला का एम्बेड सिस्टम उसके लिए एक आसान तरीका प्रदान करता है। एम्बेडेड साइट का उपयोग करते समय प्रदर्शन ट्रेडऑफ़ होते हैं, इसलिए विकल्पों और आदर्श उपयोग के मामलों के लिए दस्तावेज़ीकरण की जांच करें।';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'विशेष प्रतिबंध: केवल अनुमति गार्डन के साथ उपयोगकर्ता। अवधि। संदेश इस प्रतिक्रिया का उपयोग कर सकते हैं।';
$Definition['Specify a partial or full match when creating a ban.'] = 'प्रतिबंध बनाते समय आंशिक या पूर्ण मिलान का विवरण दें।';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'थोड़ा समय यह सोचने में व्यतीत करें कि आप अपनी साइट का वर्णन यहाँ कैसे करते हैं।
अपनी साइट को एक उचित शीर्षक और संक्षिप्त विवरण देने से सर्च इंजन में आपकी पोज़ीशन में मदद मिल सकती है।';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'लोगो जोड़कर और रंगों को कस्टमाइज़ करके अपने ईमेल को सजायें.';
$Definition['Start Import'] = 'आयात शुरू करें';
$Definition['Start the first discussion.'] = 'अपने समुदाय में प्रारंभ करने के लिए <a href="{/post/discussion,url}">पहली चर्चा करें </a> अभी।';
$Definition['Subcommunities'] = 'उपसमुदाय';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'टैगिंग उपयोगकर्ताओं को उन चर्चाओं के लिए एक टैग जोड़ने की अनुमति देता है, जो उन्हें अधिक खोज योग्य बनाने के लिए शुरू करते हैं।';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'टेम्प्लेट मानक विषय हैं। उन्हें कस्टमाइज़ करने के लिए, आपको एक कॉपी बनानी होगी।';
$Definition['The %s Authenticator does not have any custom configuration options.'] = '%s प्रमाणीकरणकर्ता के पास कोई कस्टम कॉन्फ़िगरेशन विकल्प नहीं है।';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB आपकी कस्टम थीम से मेल खाने के लिए <0/> लैब को कॉन्फ़िगर करने की आवश्यकता है। यह हमारे नए थीम संपादक का उपयोग करके किया जा सकता है। <1>और जानें।</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'इस ऐडऑन को सक्रिय नही किया जा सकता क्योंकि इसने एक घातक त्रुटि उत्पन्न की है: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'ऐडऑन पहले ही डाउनलोड हो चुका है।';
$Definition['The banner logo appears at the top of your forum.'] = 'आपके फोरम के शीर्ष पर बैनर लोगो दिखाई देता है।';
$Definition['The banner title appears on the top-left of every page.'] = 'बैनर का शीर्षक प्रत्येक पेज के ऊपरी-बाएँ दिखाई देता है।';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'बैनर शीर्षक आपकी साइट के बैनर पर और आपके ब्राउज़र के शीर्षक बार में दिखाई देता है। यह 20 से कम अक्षर होने चाहिए। यदि बैनर लोगो अपलोड किया गया है, तो यह उपयोगकर्ता-की तरफ़ फ़ोरम पेजेज़ पर बैनर शीर्षक को बदल देगा। इसके अलावा, ध्यान रखें कि कुछ थीम भी इस शीर्षक को छिपा सकती हैं।';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong> मूल पंजीकरण फॉर्म में </strong> स्पैमर को साइट से बाहर रखने के लिए नए यूजर को कैप्चा इमेज से टेक्स्ट कॉपी करने की आवश्यकता होती है। आपको <a href="http://recaptcha.net/"> recaptcha.net </a> पर एक खाते की आवश्यकता है। साइन अप करना फ्री और आसान है। एक बार साइन अप करने के बाद, यहां वापस आएं और निम्नलिखित सेटिंग्स दर्ज करें:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'आपके द्वारा निर्दिष्ट डेटाबेस उपयोगकर्ता के पास डेटाबेस तक पहुँचने की अनुमति नहीं है। क्या आपने अभी तक डेटाबेस बना लिया है? डेटाबेस ने रिपोर्ट दिया: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'आपके डेटाबेस के लिए निम्न संरचना में परिवर्तन आवश्यक हैं.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'होमपेज का शीर्षक आपके होम पेज पर प्रदर्शित होता है। एक शीर्षक चुनें जिसे आप खोज इंजन में दिखाना चाहते हैं।';
$Definition['The import file does not contain any data.'] = 'आयातित फ़ाइल में कोई डेटा नहीं है।';
$Definition['The import file is not in the correct format.'] = 'आयात फ़ाइल सही प्रारूप में नहीं है।';
$Definition['The location of the authentication endpoint.'] = 'प्रमाणीकरण समापन बिंदु का स्थान।';
$Definition['ThemeHelp'] = 'थीम्स आपको अपनी साइट के रूप और स्वरूप को बदलने की अनुमति देते हैं। <br /> एक बार आपके %s फ़ोल्डर में कोई थीम जोड़ दी जाए, तो आप यहां सक्षम कर सकते हैं।';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'थीम पूर्वावलोकन विषय के टेम्पलेट और सीएसएस को प्रदर्शित करने तक सीमित है।';
$Definition['Theming Guide'] = 'गमिंग गाइड';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'आपकी साइट के शीर्ष पर मोबाइल लोगो दिखाई देता है। थीम संपादक और कुछ कस्टम थीम से बनी थीम इस सेटिंग का उपयोग नहीं करती हैं।';
$Definition['The New Embed System'] = 'नई एम्बेड प्रणाली';
$Definition['The new embed system has improved performance.'] = 'नए एम्बेड सिस्टम ने प्रदर्शन में सुधार किया है, स्क्रॉलिंग व्यवहार में सुधार किया है, और पुराने की तुलना में अधिक सुसंगत व्यवहार किया है। वर्तमान में टिप्पणी और वर्डप्रेस एम्बेड नए एम्बेड सिस्टम में असमर्थित हैं।';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'पासवर्ड सत्यापक के पास कस्टम कॉन्फ़िगरेशन का कोई विकल्प नहीं है।';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'कोई डेटाबेस संरचना परिवर्तन आवश्यक नहीं हैं. हालाँकि, डेटा परिवर्तन हो सकते हैं.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'आवेदन में दो प्रकार के बटन होते हैं: प्राथमिक और द्वितीयक।';
$Definition['The route was saved successfully.'] = 'मार्ग सफलतापूर्वक सहेजा गया।';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'साइट विवरण आमतौर पर खोज इंजन में दिखाई देता है। आपको 100-150 वर्णों का वर्णन करने का प्रयास करना चाहिए।';
$Definition['The text of the pocket.'] = 'पॉकेट का पाठ दर्ज करें। यह ठीक उसी तरह आउटपुट होगा जब आप इसे टाइप करते हैं, इसलिए सुनिश्चित करें कि आप मान्य HTML दर्ज करें।';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'जब आप किसी मोबाइल डिवाइस की होमस्क्रीन पर किसी वेबसाइट को बुकमार्क करते हैं तो टच आइकन दिखाई देता है। ये आमतौर पर 152 पिक्सल होते हैं।';
$Definition['The user table was not in the import file.'] = 'इंपोर्ट फ़ाइल में यूजर टेबल नहीं थी.';
$Definition['The Vanilla 2 Exporter'] = 'दा वैनिला 2 एक्सपोर्टर';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'वनिला सांख्यिकी आपके फोरम के डैशबोर्ड को एक विश्लेषणात्मक रिपोर्टिंग टूल में बदल देती है, जिससे आप विशिष्ट समय अवधि में अपने फोरम पर गतिविधि की समीक्षा कर सकते हैं। आप हमारे दस्तावेज में <a href="http://vanillaforums.org/docs/vanillastatistics"> वेनिला सांख्यिकी के बारे में अधिक पढ़ </a> सकते हैं।';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'वे नियमित थीम की तरह ही काम करते हैं। एक बार थीम फ़ोल्डर में एक जोड़ दिए जाने के बाद, आप इसे यहां सक्षम कर सकते हैं।';
$Definition['This is a style guide of your theme.'] = 'यह आपकी थीम का एक स्टाइल गाइड है। इसमें पूरे एप्लिकेशन में उपयोग किए जाने वाले दृश्य तत्वों के उदाहरण हैं। आप <0> टाइटल बार जैसे विभिन्न विगेट्स पर क्लिक कर सकते हैं </0> या <1> बैनर </1> साइड पैनल में उनके गुणों को संपादित करने के लिए।';
$Definition['This is the administrative dashboard for your new community.'] = 'यह आपकी नई बिरादरी के लिए प्रशासनिक डैशबोर्ड है। बगल में कॉन्फ़िगरेशन विकल्पों की ओर देखें।  वहां से आप कॉन्फ़िगर कर सकते हैं कि आपका समुदाय कैसे काम करता है। <b> डिफ़ॉल्ट रूप से, केवल "व्यवस्थापक" भूमिका में उपयोगकर्ता</b> अपने समुदाय के इस हिस्से देख सकते हैं।';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'यह वह जगह है जहां आप नई वेनिला सुविधाओं, पृष्ठों और घटकों को सक्षम और परीक्षण कर सकते हैं।';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'इस लैब को अक्षम नहीं किया जा सकता क्योंकि एक कस्टम लेआउट लागू किया गया है।';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'इस लैब को अक्षम नहीं किया जा सकता क्योंकि यह वर्तमान थीम के लिए आवश्यक है।';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'यह लोगो आपकी साइट के शीर्ष पर दिखाई देता है। थीम संपादक और कुछ कस्टम थीम से बनी थीम इस सेटिंग का उपयोग नहीं करती हैं।';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'इसका उपयोग सभी आउटगोइंग ईमेल में संगठन का नाम और पता जैसी सामग्री शामिल करने के लिए किया जा सकता है।';
$Definition['This option shows/hides the locations where pockets can go.'] = 'यह विकल्प उन स्थानों को दिखाता/छिपाता है जहाँ पॉकेट जा सकता है, लेकिन केवल उन यूज़र्स के लिए जिन्हें पॉकेट जोड़ने/संपादित करने की अनुमति है. स्थानों को दिखाने का प्रयास करें और फिर अपनी साइट पर जाएँ.';
$Definition['This page lists the endpoints of your API.'] = 'यह पृष्ठ आपके एपीआई के अंतिम बिंदुओं को सूचीबद्ध करता है। अधिक जानकारी के लिए समापन बिंदु पर क्लिक करें। आप इस पृष्ठ से एपीआई या बाह्य रूप से एक्सेस टोकन का उपयोग करके लाइव कॉल कर सकते हैं।';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'यह भूमिका व्यक्तिगत जानकारी है। केवल व्यक्तिगत जानकारी देखने की अनुमति वाले उपयोगकर्ता इसे देखेंगे।';
$Definition['This setting loads the page before executing Javascript.'] = 'यह सेटिंग जावास्क्रिप्ट को निष्पादित करने से पहले पृष्ठ को लोड करती है जो आपके SEO को बेहतर बना सकती है। <br><strong>** चेतावनी: इस सुविधा को सक्रीय करने से आपकी साइट पर जावास्क्रिप्ट की समस्याएँ हो सकती हैं।**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'यह सेटिंग Javascript को क्रियान्वित करने से पहले पृष्ठ को लोड करती है जो आपके SEO को बेहतर बना सकती है।';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'इस थीम को हटाया नहीं जा सकता क्योंकि यह वर्तमान में उपयोग में है।';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'यह शीर्षक आपकी साइट के बैनर और आपके ब्राउज़र के शीर्षक बार में दिखाई देता है। यदि कोई लोगो अपलोड किया जाता है, तो यह उपयोगकर्ता-सामना वाले फ़ोरम पृष्ठों पर इस शीर्षक को प्रतिस्थापित कर देगा। साथ ही, ध्यान रखें कि कुछ थीम इस शीर्षक को छिपा सकती हैं।';
$Definition['Tiled Layout'] = 'टाइल वाला लेआउट';
$Definition['Title Bar'] = 'शीर्षक पट्टी';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'अपने वेनिला फोरम को अपनी वेब साइट में एम्बेड करने के लिए, निम्न कोड का उपयोग करें।';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'बहुत सारे पते! हम एक बार में %s पते तक भेजेंगे।';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'दुरुपयोग रोकने के लिए, कुछ उपकरण स्वचालित रूप से सामग्री गोपनीय रखते हैं और इसे यहाँ सूचीबद्ध करते हैं जब तक कि इसे मैन्युअल रूप से किसी मॉडरेटर द्वारा अनुमोदित नहीं किया जाता है.';
$Definition['TouchIconDescription'] = 'जब आप किसी Apple डिवाइस के होमस्क्रीन पर वेबसाइट को बुकमार्क करते हैं तो टच आइकन दिखाई देता है। ये आमतौर पर 152 पिक्सल होते हैं। Apple स्वचालित रूप से गोल कोनों और प्रकाश प्रभाव जोड़ता है।';
$Definition['Transparent'] = 'पारदर्शक';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'ट्विटर कनेक्ट यूजर को ट्विटर खाते के जरिए साइन इन करने की अनुमति देता है। <b> इस प्लगइन के इस्तेमाल हेतु ट्विटर के पास अपना आवेदन पंजीकृत करना होगा। </b>';

$Definition['Usercards'] = 'उपयोगकर्ता कार्ड';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'यूजरकार्ड आपको उपयोगकर्ता की जानकारी का त्वरित इन-लाइन स्नैपशॉट प्राप्त करने की अनुमति देते हैं। पोस्ट और लीडरबोर्ड देखते समय, पृष्ठ से दूर नेविगेट किए बिना उपयोगकर्ताओं की मूल प्रोफ़ाइल जानकारी दिखाने वाला कार्ड देखने के लिए उपयोगकर्ता नाम पर क्लिक करें। अपनी कस्टम थीम में यूजरकार्ड जोड़ने के लिए इस सुविधा को सक्षम करें।';
$Definition['User inputs are based on the global background and text colors.'] = 'उपयोगकर्ता इनपुट वैश्विक पृष्ठभूमि और पाठ रंगों पर आधारित हैं।';
$Definition['User Profile'] = 'उपयोगकर्ता प्रोफ़ाइल';
$Definition['Users may sign into your site using their Twitter account.'] = 'उपयोगकर्ता अपने ट्विटर खाते का उपयोग करके आपकी साइट पर साइन इन कर सकते हैं।';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'प्रतिबंध नियम बनाने के लिए पृष्ठ के शीर्ष पर स्थित बटन का उपयोग करें।';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'अपने ब्लॉग पर वेनिला टिप्पणियाँ सेट करने के लिए वर्डप्रेस प्लगइन का उपयोग करें, या किसी अन्य प्लेटफ़ॉर्म पर वेनिला टिप्पणियाँ सेट करने के लिए यूनिवर्सल कोड का उपयोग करें.';

$Definition['Vanilla\'s new search service is finally here.'] = 'वेनिला की नई खोज सेवा अंत में यहाँ है। सदस्य खोज, खोज छँटाई और शब्द हाइलाइटिंग जैसी नवीनतम खोज सुविधाओं तक पहुँच प्राप्त करने के लिए हमारे नए खोज पृष्ठ UI को सक्षम करें।';
$Definition['Vanilla Export: %s, Source: %s'] = 'Vanilla निर्यात: %s, स्रोत:%s';
$Definition['Vanilla Labs'] = 'वेनिला लैब्स';
$Definition['Vanilla Statistics are currently disabled'] = 'वर्तमान में वेनिला सांख्यिकी अक्षम हैं';
$Definition['Verify and restore'] = 'सत्यापित करें और पुनर्स्थापित करें';
$Definition['VerifyUser'] = '<b>उपयोगकर्ता को सत्यापित के</b> रूप में चिह्नित करने के लिए उसके बगल में स्थित बॉक्स को चेक करें ताकि उनकी पोस्ट फिर से स्पैम के रूप में चिह्नित न हों। यह उनके सभी लंबित पदों को भी बहाल करेगा।';
$Definition['Video tutorial on advanced settings'] = 'एडवांस सेटिंग्स पर वीडियो ट्यूटोरियल';
$Definition['Video tutorial on finding &amp; managing users'] = 'उपयोगकर्ताओं को प्रबंधित करना & खोजने पर वीडियो ट्यूटोरियल';
$Definition['Video tutorial on managing appearance'] = 'दिखावट के प्रबंधन पर वीडियो ट्यूटोरियल';
$Definition['Video tutorial on managing categories'] = 'श्रेणियों के प्रबंधन के लिए वीडियो ट्यूटोरियल';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'भूमिकाओं और एएमपी के प्रबंधन पर वीडियो शिक्षण; अनुमतियाँ';
$Definition['Video tutorial on user registration'] = 'यूज़र पंजीकरण पर वीडियो शिक्षण ';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'चेतावनी: इस सुविधा को सक्षम करने से आपकी साइट पर जावास्क्रिप्ट त्रुटियां हो सकती हैं।';
$Definition['Warning: Loading tables can be slow.'] = '<b>चेतावनी</b> : आपका सर्वर कॉन्फ़िगरेशन तेज़ डेटा लोडिंग का समर्थन नहीं करता है। यदि आप एक बहुत बड़ी फ़ाइल आयात कर रहे हैं (200,000 से अधिक टिप्पणियाँ) तो आप अपने कॉन्फ़िगरेशन को बदलने पर विचार कर सकते हैं। अधिक जानकारी के लिए <a href="http://vanillaforums.com/porter">यहां</a> क्लिक <a href="http://vanillaforums.com/porter">करें</a> ।';
$Definition['Warning: This is for advanced users.'] = '<b>चेतावनी</b>: यह एडवांस उपयोगकर्ताओं के लिए है और इसके लिए आपको अपने वेब सर्वर में अतिरिक्त बदलाव करने की आवश्यकता होगी। सामान्यतया यह केवल तभी उपलब्ध होगा जब आपके पास डेडिकेटेड या vps होस्टिंग हो। यदि आप नहीं जानते हैं कि आप क्या कर रहे हैं तो कृपया इसे करने का प्रयास न करें।   ';
$Definition['Webhooks'] = 'वेबहुक';
$Definition['Welcome to Labs!'] = 'लैब्स में आपका स्वागत है!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'वेनिला के थीम यूआई में आपका स्वागत है। यह पृष्ठ आपके सभी उपलब्ध विषयों को सूचीबद्ध करता है, और आपको उन्हें कॉपी या संपादित करने की अनुमति देता है।';
$Definition['Welcome To Your Theme'] = 'आपका थीम में स्वागत है';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'सक्षम होने पर, उपयोगकर्ता समुदाय से सूचनाएं प्राप्त करना चुन सकते हैं';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'सक्षम होने पर, आप उन उत्पादों द्वारा उत्पादों और समूह उप-समूहों का प्रबंधन कर सकते हैं।';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'जब कोई आपकी साइट से लिंक साझा करता है, तो हम पृष्ठ से एक छवि लेते हैं। यदि पृष्ठ पर कोई छवि नहीं है, तो हम इस छवि का उपयोग करेंगे। छवि कम से कम 50 × 50 होनी चाहिए, लेकिन हम 200 × 200 की सलाह देते हैं।';
$Definition['When you select Full Bleed, your background is transparent.'] = 'जब आप Full Bleed का चयन करते हैं, तो आपकी पृष्ठभूमि पारदर्शी होती है।';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'इस वेबहुक में आंतरिक प्रोफ़ाइल फ़ील्ड शामिल किए जाएंगे या नहीं।';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'निजी प्रोफ़ाइल फ़ील्ड को इस वेबहुक में शामिल किया जाएगा या नहीं.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'आप एक नया लेआउट विकल्प लागू करने वाले हैं। इसे हमारे थीम संपादक का उपयोग करके अनुकूलित और पूर्वावलोकन किया जा सकता है। <0>और जानें</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'आप "111.111.111" मान युक्त आईपी-प्रकार का प्रतिबंध जोड़कर "111.111.111" प्रीफ़िक्स युक्त आईपी पते वाले सभी उपयोगकर्ताओं को प्रतिबंधित कर सकते हैं।';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'आप आईपी पते, ईमेल पते और उपयोगकर्ताओं के नाम को प्रतिबंधित कर सकते हैं।';
$Definition['You can choose from one of the different styles this theme offers.'] = 'आप इस विषय की पेशकश विभिन्न शैलियों में से एक चुन सकते हैं।';
$Definition['You can configure some values differently for different screensizes.'] = 'आप अलग-अलग स्क्रीनसेज़ के लिए कुछ मान अलग-अलग कॉन्फ़िगर कर सकते हैं।';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'आप कई साइटों से जुड़ सकते हैं जो jsConnect को सपोर्ट करती हैं.';
$Definition['You can place files in your /uploads folder.'] = 'यदि आपकी फ़ाइल इस पेज पर सीधे अपलोड करने के लिए बहुत बड़ी है, तो आप इसे अपने /अपलोड फ़ोल्डर में रख सकते हैं. सुनिश्चित करें कि फ़ाइल का नाम <b> एक्सपोर्ट </b> शब्द से शुरू होता है और <b>.txt, .gz </b> में से एक के साथ समाप्त होता है.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'आप छोटी पोस्ट को हतोत्साहित करने के लिए न्यूनतम पद की लंबाई निर्दिष्ट कर सकते हैं।';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'आप अपने थीमिंग सिस्टम में एक कस्टम फ़ॉन्ट अपलोड कर सकते हैं। बस क्षेत्र में URL कॉपी और पेस्ट करें।';
$Definition['You must select a file to import.'] = 'इम्पोर्ट करने के लिए आपको एक फ़ाइल का चयन करना होगा.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'आपको फ़ॉन्ट यूआरएल के डोमेन को <0> अनुमत डोमेन से जोड़ना होगा </0> साइट के विन्यास में। <1> कस्टम फोंट के बारे में अधिक जानें। </1>';
$Definition['Your mobile theme will be disabled.'] = 'आपकी मोबाइल थीम अक्षम हो जाएगी। विभिन्न मोबाइल और डेस्कटॉप थीम सेट करने के लिए, पुराने थीमिंग UI का उपयोग करें।';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'आपके संगठन के नाम का उपयोग SEO माइक्रोडेटा और JSON+LD के लिए किया जाता है';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'आपकी साइट का फ़ेविकॉन आपके ब्राउज़र के शीर्षक बार में दिखाई देता है। इसे उचित रूप से घटाया जाएगा।';
