<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**אזהרה: הפעלת תכונה זו עלולה לגרום לשגיאות Javascript באתר שלך.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>זהירות!</strong> מחיקת תפקיד עלולה למנוע מהמשתמש גישה לתוכנה.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>זהירות!</strong> הזזת דיונים לקטגוריה חלופית עלולה לגרום להעילמותם (או הופעתם) של דיונים אם לקטגוריה החדשה יש הרשאות שונות משל זו המקורית.';

$Definition['About.DisableStatistics'] = 'אם הינכם חייבים לבטל דיווח נתונים זה מסיבות עסקיות כלשהן, תוכלו לעשות זאת ע"י הוספת השורה הנ"ל לקובץ הקונפיגורציה: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'זה חשוב בצורה משמעותית לחיי תוכנת הקוד פתוח החינמית הזאת שאנו נמדוד את היעילות של ונילה. אנו מבקשים ממך אנא אל תבטל את דיווח המידע.';
$Definition['AboutCommentEmbedding'] = 'Vanilla יכולה לשמש כתחליף למערכת התגובות המקורית של הבלוג שלך. למעשה, היא יכולה לשמש להוספת תגובות לכל דף באינטרנט. ';
$Definition['AboutEmbedding'] = 'הטבעה מאפשר לכל או חלק מהקהילה שלך להיות מוטבעת ליישומים ודפי אינרטנט אחרים';
$Definition['About Vanilla Statistics'] = 'אודות הסטטיסטיקות של Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'קבלת גישה לפורום הקהילה שלך על ידי לחיצה על הקישור "בקר באתר" בראש העמוד הזה, על על ידי <a href={/,url}>לחיצה כאן</a>. פורום הקהילה הוא מה שכל המשתמשים & הלקוחות שלך רואים כאשר הם מבקרים <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'הוסף/י גבולות לממדי העלאת תמונה בדיונים ובתגובות.';
$Definition['AddonProblems'] = '<h2>בעיות?</h2><p>אם משהו הולך שלא כשורה עם תוסף אינך יכול להשתמש באתר שלך, באפשרותך לבטל אותם ידנית על ידי עריכת:</p>%s';
$Definition['AddressBarColorDescription'] = 'דפדפנים מסוימים תומכים בצבע בסרגל הכתובות. נייד בלבד.';
$Definition['Alert users if they click external link.'] = 'התריע על משתמשים אם הם לוחצים על קישור בפוסט שיוביל אותם הרחק מהפורום. משתמשים לא יזהירו בעת ביצוע קישורים התואמים לתחום מהימן';
$Definition['Alignment'] = 'יישור';
$Definition['Alignment (Mobile)'] = 'יישור (נייד)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'כל הקטגוריות הרשומות עם 5 הדיונים האחרונים תחת כל אחת מהן';
$Definition['Allow links to be transformed'] = 'אפשר להפוך את הקישורים לייצוגים משובצים בדיונים והערות. לדוגמה, קישור ביוטיוב יהפוך לסרטון משובץ.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'אפשר למשתמשים עם הרשאה %s לשנות את האווטרים שלהם מדפי הפרופיל שלהם בוונילה.';
$Definition['ApplicationHelp'] = 'אפליקציות מאפשרות לך להוסיף פונקציונליות רבה לאתר שלך.<br />
ברגע שהאפליקציה נמצאת בתיקיית %s , תוכל לאפשר או לכבות אותה כאן.';
$Definition['Apply Layout'] = 'החל פריסה';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'האם אתה בטוח שברצונך למחוק נושא זה? זה יימחק לצמיתות.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'הנכם בטוחים שכתבתם את שם השרת המארח בצורה תקינה? אולי שגית בהקלדה? תגובה השרת היתה:
<code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'תפקיד עם סוג ברירת המחדל "לא מאושר" נדרש להשתמש אישור דוא"ל.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'שמור אוטומטית טיוטות של דיונים, שאלות, רעיונות והערות שלא פורסמו.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'אבטרים יוגדלו אם הם יעלו מגובה זה.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'אבטרים יוגדלו אם הם חורגים מרוחב זה.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'באווטרים נשמרים התמונות הממוזערות בגודל זה.';

$Definition['Background'] = 'רקע כללי';
$Definition['Background Image'] = 'תמונת רקע';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'תהיה יצירתי! נסה לתת שמות לשורותיך על פי דברים שהקהילה מדברת עליהם.';
$Definition['Bordered'] = 'גבול';
$Definition['Bordered (Unified)'] = 'גבול (מאוחד)';
$Definition['Borderless'] = 'ללא גבולות';
$Definition['Border Radius'] = 'רדיוס גבול';
$Definition['Brand Color'] = 'צבע מותג';
$Definition['Buttons'] = 'כפתורים';
$Definition['Buttons & Inputs'] = 'כפתורים וכניסות';
$Definition['Button Type'] = 'סוג הכפתור';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'על ידי לחיצה על הכפתור שמלמטה, תמחק את רשומות המשתמש של %s לצמיתות.';

$Definition['Center Aligned'] = 'מרכז יישור';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'השינויים יחולו על avatars שזה עתה הועלה בלבד.';
$Definition['Change the sizes that avatar images are saved at.'] = 'שנה את הגדלים שבהם נשמרים תמונות אווטאר.';
$Definition['Change the way your community works with plugins.'] = 'שינוי הדרך בה הקהילה שלך עובדת עם תוספים. חיברנו מספר תוספים למערכת הזאת, וישנם עוד אשר מינים ברשת.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'תיבות הסימון מאפשרות למנהלי מערכת לבצע פעולות אצווה על מספר דיונים או הערות בו זמנית.';
$Definition['Check out our %s'] = 'בדוק את %s שלנו';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'עיין בתיעוד <0> שלנו</0> , או שאל את <1>קהילת המומחים שלנו</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'ונילה היא פלטפורמת הקהילה היא קלה והכי עוצמתית בעולם. הוא קלה במיוחד לשימוש. התחל עם סרטון היכרות והמשך עם הצעדים למטה. תהנה!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'בחר בתפקיד שכל המשתמשים חסר התפקיד יקבלו.';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'בחר נושא עבור תת-קהילה זו. <0> קרא עוד </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'בחר כיצד לנהל את כל התוכן המשוייך לחשבון המשתמש של %s (הערות, הודעות וכו\')';
$Definition['Choose Image'] = 'בחר תמונה';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'באפשרותך לבחור אלגוריתם האש מותאם אישית כדי לרשום את הבקשות שלך. אלגוריתם האש מוכרח להיות בשימוש בספריית הלקוח שלך. בחר md5 to thbl cyuj cnv kcjur/';
$Definition['Choose the order items are sorted.'] = 'בחר את פריטי ההזמנה ממוינים.';
$Definition['Choose the page people should see when they visit <0/>'] = 'בחר את הדף שאנשים צריכים לראות כאשר הם מבקרים ב <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'בחר בפריסה המועדפת על רשימות קטגוריות.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'בחר את הפריסה המועדפת על רשימות של קטגוריות. ניתן לערוך את פריסת האריחים.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'בחר במערך המועדף לרשימות דיונים.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'בחר את הפריסה המועדפת על רשימות דיונים. אתה יכול לערוך את פריסת הבסיס.';
$Definition['Color Overlay'] = 'כיסוי צבע';
$Definition['Continue Import'] = 'המשך בייבוא';
$Definition['Could not parse import file. The problem is near line %s.'] = 'לא הצלחתי לעשות parsing לקובץ המיובא. הבעיה נמצאת בסמוך לשורה %s.';
$Definition['Create a localization CSV'] = 'צור ערכת לוקאליזציה ב-CSV';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'ערכות נושא מותאמות אישית הן הנושאים שיצרת. אתה יכול לערוך, לשנות את שמם או ליצור עותק שלהם.';

$Definition['Dark'] = 'אפל';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'הגדר מי יכול להעלות ולנהל קבצים בדף <a href="%s">תפקידים והרשאות</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'הגדרת הדף הראשי של הפורום, העלאת הלוגו שלך, ועוד...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'מחיקת תפקיד עלולה למנוע גישה מהמשתמשים לתוכנה';
$Definition['Deleting forever cannot be undone.'] = 'מחיקה היא דרך טובה לשמירת הפורום שלך נקי.';
$Definition['Disable Google Sign In'] = 'כבה אפשרות ל-Google Sign In';
$Definition['Disable OpenID'] = 'כבה אפשרות ל-OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'השבת את המעבדה "מערכת הטבעה חדשה" בדף <0>Vanilla Labs</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'קטגוריות לדיונים מסייעות למשתמשים שלך לארגן את הדיונים שלה בצורה משמעותית.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'על תטמיע את לוח הבקרה של אדמין הפורום (במקום, גרום לו להפתח על מסך מלא)';
$Definition['Don\'t use too many reactions.'] = 'אל תשתמש יותר מדי בתגובות. אינך רוצה לספק למשתמשים שלך עומס יתר.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'גרור את הקטגוריות המופיעות מטה על מנת לסדר אותן';

$Definition['EditContentTimeout.Notes'] = 'אם למשתמש יש הרשאות לערוך תוכן, אז ההרשאות האלו יעקפו את זה.';
$Definition['Edit Route'] = 'ערוך מסלול';
$Definition['Edits to this theme apply to:'] = 'עריכות בנושא זה חלות על:';
$Definition['Embed Settings'] = 'הטמע הגדרות';
$Definition['Embed your community forum into your website to increase engagement...'] = 'הטעמת פורום הקהילה שלך לתוך האתר על מנת להגביר את מעורבות המשתמשים...';
$Definition['Enable and test out the latest Vanilla features.'] = 'הפעל ובדוק את תכונות הווניל העדכניות ביותר.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'מאפשר עריכה מתקדמת של פוסטים בכמה פורמטים, כולל WYSIWYG, HTML פשוט, Markdown ו- BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'אפשר את עורך הפריסה כדי להחיל פריסה מותאמת אישית עבור דפי הקהילה שלך. השתמש בעורך החדש שלנו כדי להציג תוכן באמצעות קטלוג הווידג\'טים הזמינים שלנו.';
$Definition['Enter a descriptive name.'] = 'הכנס שם תיאורי עבור הכיס. השם לא יוצג באף מקום חוץ מאשר כאשר תנהל את הכיסים שלך כאן אז זה משמש רק כדי לעזור לך לזכור את הכיס.';
$Definition['Enter a short name for the site.'] = 'הכנס שם קצר לאתר. זה מוצג על כפתורי ההתחברות.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'הכנס את כתובת בלוג ה-Wordpress שלך, ואנחנו כבר נעשה את השאר.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'הכנס את נתוני הקישור לשרת ה-Sphinx שלך מטה.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'כל עריכה או מחיקה נשמרת כאן. השתמש ב- ‘Restore’ על מנת לבטל כל שינוי.';
$Definition['Everyone who signs up gets a profile page.'] = 'כל מי שנרשם לקהילה שלך מקבל עמוד פרופיל ציבורי בו הם יכולים להעלות תמונה של עצמם, לנהל את אפשרויות הפרופיל שלהם, ולעקוב אחר דברים מגניבים המתרחשים בקהילה. הנכם צריכים <a href="{/profile,url}">להתאים אישית את הפרופיל שלך כעת</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'לכל משתמש באתר יש לפחות תפקיד אחד מוגדר. התפקידים מאפשרים להגדיר מה מותר ואסור לכל משתמש לעשות.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'התחברות באמצעות פייסבוק מאפשרת למשתמשם להכנס באמצעות שימוש בחשבונות פייסבוק שלהם. <b> חובה לרשום את היישום שלך עם פייסבוק על מנת שהתוסף הזה יעבוד.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'הייתה תקלה בהתחברות למאגר הנתונים עם שם המשתמש והסיסמה שיפקת.
אולי טעית בהקלדה? מאגר הנתונים דיווח: <code>%s</code>';
$Definition['Font'] = 'גוֹפָן';
$Definition['Font Name'] = 'שם גופן';
$Definition['Font URL'] = 'כתובת אתר גופן';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'חסום את הגישה לעמוד הראשית לכול כתובת מלבד ה-URL הבא <em>(לא מומלץ)</em> ';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'למשל, באפשרותך לאסור את כניסתם של כל המשתמשים עם כתובות אימייל של example.com על ידי הוספת איסור כניסה מסוג אימייל עם הערך "*@example.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'בשביל לקדם את האתר במנועי חיפוש, הגישה לכתובת ה-URL הנוכחית חסומה לרובוטי חיפוש.';
$Definition['Foundation Layout'] = 'פריסת קרן';
$Definition['Full Bleed'] = 'דימום מלא';

$Definition['Garden.Import.Complete.Description'] = 'סיימת בהצלחה ייבוא. לחצו <b>סיום</b> לסיום התהליך.';
$Definition['Garden.Import.Continue.Description'] = 'נראה כאילו אתה באמצע יבוא. בחר אחת מהאפשרויות הבאות.';
$Definition['Garden.Import.InputInstructions'] = 'הכנס את הדוא"ל והסיסמא של משתמש האדמין מהמידע שייובא.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles. ערוך הרשאה לשנות את האווטרים שלהם מדפי הפרופיל שלהם בוונילה.';
$Definition['Garden.StatisticsDisabled'] = 'ביטלת במיוחד את סטטיסטיקס Vanilla בקובץ ההגדרות שלך.';
$Definition['Garden.StatisticsLocal.Explain'] = 'נראה שהפורום הזה עובד בסביבת בדיקה, או שהוא מדווח לIP פרטי. בברירת מחדל, פורומים הרצים על IP פרטי לא נעקבים.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'הנכם בטוחים שהפורום נגיש מהאינטרנט באפשרותך להכריח אותו לדווח על סטטיסטיקות כאן: ';
$Definition['Garden.StatisticsReadonly.Explain'] = 'נדמה שקובץ ה-config.php שלך הוא לקריאה בלבד. זה אומר שונילה לא יוכל לרשום באופן אוטומטי את InstallationID-ו InstallationSecret של הפורום שלך.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'כדי לפתור בעיה זאת, שייך מצב קובץ 777 לקובץ conf/config.php שלך.';
$Definition['Global Styles'] = 'סגנונות גלובליים';

$Definition['Heads Up!'] = 'הרימו ראש!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'זהירות! זהו תפקיד מיוחד שאינו מאפשר פעילות. מסיבה זו, ההרשאות של תפקיד זה מוגלות ל\'צפייה\' בלבד.';
$Definition['Here are all of the reactions you can use on your site.'] = 'להלן כל התגובות בהן תוכלו להשתמש באתר שלכם.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'להלן הדרגות שמשתמשים יכולים להשיג באתר שלך. אתה יכול להתאים אישית את הדרגות האלה ואפילו להוסיף חדשות. הנה כמה עצות.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'עם העלית לוגו לבאנר, הוא יחליף את הכותרת של הבאנר בדפי פורום כפי שהמשתמשים רואים אותם.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'אם משתמש לא יבקר באתר תוך פרק זמן זה הוא ינותק אוטומטית.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'אם זה מופעל, התוכן המלא של הפוסטים יישלח בהודעות דוא"ל למשתמשים.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'אם אתה חדש ב- HTML ו / או CSS, הנה כמה הדרכות שתתחיל:';
$Definition['If you have an old theme'] = 'אם יש לך נושא ישן ואתה צריך להגדיר נושא שולחני ונייד נפרד אתה יכול לעשות זאת באמצעות ממשק המשתמש הישן של הנושא.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'אם ברצונך להוריד את רמת האזהרה, הסר את האזהרה.';
$Definition['If you want to embed your forum, enable embedding.'] = 'אם אתה רוצה להטביע את הפורום שלך או להשתמש בתגובות של וניל בבלוג שלך, עליך לאפשר הטמעה. אם אינך משתמש בהטמעה אנו ממליצים להפסיק הגדרה זו.';
$Definition['Image (Mobile)'] = 'תמונה (נייד)';
$Definition['Import'] = 'יבא';
$Definition['Importing to Vanilla'] = 'מייבא לתוך Vanilla';
$Definition['In additon to the widgets there are also'] = 'בנוסף לווידג\'טים ישנם גם <0> סגנונות גלובליים </0> . כדי לערוך סגנונות גלובליים לחץ על מקום אחר בדף, כגון טקסט זה.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'שילוב של דפי קרן ורכיבים בנושא שלך';
$Definition['Internationalization & Localization'] = 'בינאום ולוקליזציה ';
$Definition['Invalid URL'] = 'כתובת אתר לא חוקית';
$Definition['Invitation email failed to send: %'] = 'למרות שההזמנה נוצרה בהצלחה, הדוא"ל לא הצליח לשלוח. השרת דיווח על השגיאה הבאה: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'כאשר אתם משתמשים בהרשמה באמצעות הזמנה למשתמשים יהיה קישור שיוצג ב<a href="%s" class="Popup">ההזמנות שלי</a> בדפי הפרופיל שלהם.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'מאגר הנתונים שבחרת לא קיים. כבר יצרת אותו? אולי טעית בשם? מאגר הנתונים המדובר: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'מומלץ להגביל את מספר האותיות בתגובה לכמות סבירה.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'כדאי לשמור על מספר התווים המרבי המותר בפוסט עד לגודל סביר.';

$Definition['Kick-start your community and increase user engagement.'] = 'תן דחיפה לקהילה ותגביר את מעורבות המשתתפים.';

$Definition['Labs'] = 'מעבדות';
$Definition['Layout Editor'] = 'עורך פריסה';
$Definition['Learn about custom routing.'] = 'למד/י על ניתוב מותאם אישית.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'למד איך לשנות חלוטין את המראה וההרגשה של הפורום: הוסף לוגו, קבע את הפורום כדף הבית, בחר ערכת נושא ותעצב את הפורום לפי טעמך האישי.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'הדרכה על האפשרויות הבסיסיות של הפורום';
$Definition['Left Aligned'] = 'משמאל מיושר';
$Definition['Light'] = 'אוֹר';
$Definition['Links'] = 'קישורים';
$Definition['Locales allow you to support other languages on your site.'] = 'איזורים מאפשרים לך לתמוך בשפות אחרות באתר שלך. אפשר ובטל איזורים שאתרצה להפוך לזמינים כאן.';
$Definition['LogoDescription'] = 'לוגו הבאנר מופיע בראש האתר שלך.';
$Definition['LogoDisclaimer'] = 'ערכות נושא שנוצרו עם עורך הנושאים וכמה ערכות נושא מותאמות אישית אינן משתמשות בהגדרה זו.';
$Definition['Looking for the Old Embed System?'] = 'מחפש את מערכת ההטמעה הישנה?';

$Definition['Make sure you click View Page'] = 'וודאו לחיצה ב<a href="%s">צפה בדף</a> על מנת לראות כיצד דף הקטגוריות שלך נראה לאחר שמירה.';
$Definition['Manage Routes'] = 'ניהול נתיבים';
$Definition['Managing Users'] = 'ניהול משתמשים';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'סימון דברים כלא ספאם יחזיר אותם אל הפורום.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'סימון דברים כלא ספאם יחזיר אותם אל הפורום.';
$Definition['Messages can appear anywhere in your application.'] = 'הודעות יכולות להופיע בכל מקום בתוך התוכנה שלך, ויכולות לשמש על מנת להודיע למשתמשים על אירועים או חדשות. השתמש בעמוד זה על מנת לארגן את ההודעות שלך על ידי גרירתם ממקום למקום.';
$Definition['MobileLogoDescription'] = 'לוגו הבאנר הנייד מופיע בראש האתר שלך.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'ערכות נושא לנייד מאפשרות לך לשנות את המראה והתחושה של האתר שלך במכשירים קטנים יותר.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'הערה עורך ה-Layout החדש יירש את ערכת הנושא שהוגדרה במדריך הסגנונות שלך (עורך ערכות נושא באופן רשמי). <1>למידע נוסף</1>';
$Definition['Need More Help?'] = 'צריכים עזרה?';
$Definition['Need more help?'] = 'צריך עוד עזרה?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'קטגוריות מקוננות עמוקות יותר מעומק זה יוצבו ברשימה המוגדרת בפסיקים.';
$Definition['New Embed System'] = 'מערכת הטמעה חדשה';
$Definition['New Quick Links'] = 'קישורים מהירים חדשים';
$Definition['New Search Page'] = 'דף חיפוש חדש';
$Definition['Not getting what you expect when you preview your theme?'] = 'לא משיגים את מה שאתה מצפה כשאתה מקדימה את הנושא שלך?';
$Definition['Notify me when people comment on my addons.'] = 'תודיע לי כשמשתמשים מגיבים על התוספים שלי.';
$Definition['No unconfirmed role available for email confirmation.'] = 'האתר צריך תפקיד עם סוג ברירת המחדל "לא מאושר" להשתמש אישור דוא"ל. הוסף אחד כדי לאפשר הגדרה זו.';

$Definition['Old Theming UI'] = 'ממשק משתמש ישן';
$Definition['Once enabled, only members will see inside your community.'] = 'לאחר הפעלה, רק חברים יראו בתוך הקהילה שלך.';
$Definition['OrgDescription'] = 'נעשה שימוש בשם הארגון שלך למטרות SEO microdata ו- JSON+LD';
$Definition['Outline'] = 'מתווה';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'תצוגות או ווי ערכות נושא מורכבות יכולות לגרום לתופעות לוואי לא מכוונות ולא ניתן לראות בתצוגה מקדימה.';

$Definition['Password.MinLength'] = 'אורך תו מינימלי המותר לסיסמאות של משתמשים בדפי יצירה ואיפוס של סיסמה.';
$Definition['Please choose an authenticator to configure.'] = 'אנא בחר מאמת כדי להגדיר.';
$Definition['PluginHelp'] = 'תוספים מאפשרים לך להוסיף פונקציונליות לאתר שלך. <br />ברגע שתוסף הוסף לתיקיית ה-%s שלך, באפשרותך לאפשר או לבטל אותו כאן.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'הכיס מוצג בין כל דיון ברשימת הדיונים הראשית. מאחר ודיונים בדרך כלל בתיוגים <li>..</li>, תצטרך לעטוף את הכיס שלך בתיוגים האלה גם כן.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Pockets מאפשרים לך לשלב HTML בצורה חופשית בתוך מקומות שונים באפליקציה.';
$Definition['Preset'] = 'מוגדר מראש';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'תוכל למנוע ספאם בפורום על ידי הגבלה של מספר הדיונים והתגובות שהמשתמשים יכולים לפרסם בפרק זמן נתון.';
$Definition['Primary Button'] = 'כפתור ראשי';
$Definition['Primary Buttons'] = 'כפתורים ראשיים';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'מדריך מהיר ליצירה של ערכות נושא ל-Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'קישורים מהירים הוא רכיב ברירת מחדל בדפי קהילה. אפשר את רכיב הקישורים המהירים החדש שלנו כדי להוסיף, לערוך או להסתיר קישורים מתפריט זה באמצעות עורך הנושאים שלנו.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'תוסף הערות Vanilla שכבר מוכן ל-WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'תוסף פורום Vanilla שכבר מוכן ל-WordPress';
$Definition['Realtime progress bars: %s'] = 'התקדמות בזמן אמת: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'כדאי שיהיו דרגות מיוחדות למנחים ומנהלים כדי שהקהילה שלכם תוכל לראות בקלות מי האחראי.';
$Definition['Recommend starting with five ranks.'] = 'אתה לא רוצה להיות יותר מדי דרגות. אנו ממליצים להתחיל בחמש. אתה יכול להוסיף עוד אם הקהילה שלך באמת גדולה.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'הסר קישורי דיונים וקטגוריות מהתפריטים. הגדר דפים הקשורים לדיונים וקטגוריות כך שיחזירו את עמוד 404 לא נמצא.';
$Definition['Requires “Flag” reaction permission.'] = 'דורש הרשאת תגובה "דגל".';
$Definition['Requires “Negative” reaction permission.'] = 'דורש הרשאת תגובה "שלילית".';
$Definition['Requires “Positive” reaction permission.'] = 'דורש הרשאת תגובה "חיובית".';
$Definition['Restoring your selection removes the items from this list.'] = 'בשחזור, הפריטים מוסרים מהרשימה ומוחזרים בחזרה לתוך האתר.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'באמצעות האפשרות הבאה אפשר/י ציטוטים ל-Rich Editor. זה ייושם רק עם מעצב ברירת המחדל הוא "Rich".';
$Definition['Route Expression'] = 'שם הנתיב';
$Definition['Routes are used to redirect users.'] = 'נעשה שימוש בנתבים כדי לנתב מחדש משתמשים בהתאם ל-URL המבוקש.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'חפש משתמשים לפי שם או לפי שם התפקיד כדי לצפות בכל המשתמשים עם התפקיד הזה.';
$Definition['Secondary Button'] = 'כפתור משני';
$Definition['Secondary Buttons'] = 'כפתורים משניים';
$Definition['Security.Hsts.HTTPSWarning'] = 'אזהרה: יש לאפשר תכונה זו רק אם את/ה בטוח/ה שכל תחומי המשנה שלך מוגדרים ל-HTTPS עם הרשאות תקפות.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'במצב מאופשר, חוק זה חל גם על כל תחומי המשנה באתר שלך.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'אנו ממליצים להתחיל בגיל מרבי של שבוע ולהעלות אוֹתו לחודש ולאחר מכן לשנה ברגע שתראה/י שהאתר שלך עובד בהתאם לציפיות.';
$Definition['Security.Hsts.SubmitWarning'] = 'אזהרה: מעולה לתמוך בטעינה מראש של HSTS כשיטת עבודה מומלצת. עם זאת, עליך לשלוח את האתר שלך ל-hstspreload.org כדי להטיח שהוא ייטען מראש בהצלחה (כלומר, כדי לקבל את מלוא ההגנה לקונפיגורציה המתוכננת).';
$Definition['See the documentation'] = 'ראה את התיעוד';
$Definition['Select the default type for this role, if any.'] = 'בחר את סוג ברירת המחדל עבור תפקיד זה, אם קיים.';
$Definition['Select the import source'] = 'בחר מה לייבא';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'טור ממושך "%s" נכשל להיות לא ממושך.';
$Definition['Session Timeout'] = 'זמן קצוב להפעלה';
$Definition['Shadowed'] = 'מוצל';
$Definition['ShareImageDescription'] = 'כאשר מישהו משתף קישור מהאתר שלך אנו מנסים לתפוס תמונה מהדף. אם אין תמונה בדף, אנו נשתמש בתמונה זו במקום זאת. התמונה צריכה להיות לפחות 50 × 50, אך אנו ממליצים על 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'הפעל אפשרות זאת כדי להראות את כל מקומות הכיסים האפשריים. הפעלת אפשרות זאת תראה המיקומים רק למשתמשים שיכולים לנהל כיסים.';
$Definition['Solid'] = 'מוצק';
$Definition['Some browsers support a color for the address bar.'] = 'דפדפנים מסוימים תומכים בצבע עבור שורת הכתובת.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'יתכן שיהיה צורך לעדכן כמה ערכות נושא כדי לעבוד עם הקטגוריות שלהלן. אתה יכול להשבית את התכונה בזמן שאתה מעדכן את הנושא שלך.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'לפעמים אתה רוצה להטמיע את אתר Vanilla שלך בתוך אתר אחר. מערכת ההטמעה של Vanilla מציעה דרך קלה לכך. ישנן פשרות בביצועים בעת שימוש באתר מוטבע, אז בדוק בתיעוד עבור חלופות ומקרי שימוש אידיאליים.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'הגבלה מיוחדת: רק משתמשים עם הרשאה Garden.Curation.Manage רשאים להשתמש בתגובה זו.';
$Definition['Specify a partial or full match when creating a ban.'] = 'יש לפרט התאמה חלקית או מלאה כשיוצרים איסור כניסה.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'בזבז קצת זמן בנוגע לאיך לתאר את האתר שלך כאן. הענקת כותרת מלאת משמעות לאתר שלך ותיאור תמציתי יכול לעזור למיקום שלך במנועי חיפוש.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'שדרג/י את מראה האימיילים שלך ע"י הוספת לוגו ועיצוב הצבעים לפי טעמך.';
$Definition['Start Import'] = 'תחל ייבוא';
$Definition['Start the first discussion.'] = 'תן לכדור להתחיל להתגלגל בקהילה שלך על ידי <a href="{/post/discussion,url}">התחלת הדיון הראשון</a> כעת.';
$Definition['Subcommunities'] = 'קהילות משנה';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'תיוג מאפשר למשתמשים להוסיף תג לדיונים שהם מתחילים בכדי להפוך אותם לגלויים יותר.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'תבניות הן הנושאים הסטנדרטיים. כדי להתאים אותם אישית עליך ליצור עותק.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'ה%s מאמת לא מכיל אפשרויות להתאמה אישית.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'הערה יש להגדיר את המעבדה <0/> כך שתתאים לנושא המותאם אישית שלך. ניתן לעשות זאת באמצעות עורך הנושאים החדש שלנו. <1> למידע נוסף.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'התוספת לא אותחלה בגלל השגיאה הבאה:
<pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'כבר הורדת את התוספת הזאת.';
$Definition['The banner logo appears at the top of your forum.'] = 'הלוגו של האתר מופיע מעל הפורום.';
$Definition['The banner title appears on the top-left of every page.'] = 'שם הפורום מופיע בפינה הימנית העליונה של כול עמוד.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'כותרת הבאנר מופיעה בבאנר של האתר שלך ובכותרת הדפדפן שלך. אסור שאורכו יעלה על 20 תווים. אם לוגו באנר מועלה, הוא יחליף של כותרת הבאנר בפורומים בהם המשתמשים יכולים לצפות. בנוסף, זכור כי ישנן ערכות נושא העלולות להסתיר את הכותרת.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>טופס ההרשמה הבסיסי דורש</strong> ממשתמשים חדשים להעתיק טקסט מתמונת CAPTCHA על מנת להרחיק ספאמרים מהאתר. ישנו צורך בחשבון ב-<a href="http://recaptcha.net/">recaptcha.net</a>. הרישום חינמי וקל. ברגע שנרשמת, חזור לכאן והכנס את ההגדרות הבאות:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'למשתמש במאגר הנתונים שציינת אין הרשאות לגשת אליו. האם יצרת כבר את מאגר הנתונים? השגיאה שדווחה:
<code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'יש לבצע את השינויים המבניים הבאים במאגר הנתונים.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'כותרת דף הבית מוצגת בדף הבית שלך. בחר כותרת שתרצה לראות מופיעה במנועי חיפוש.';
$Definition['The import file does not contain any data.'] = 'הקובץ המיובא לא הכיל כול מידע.';
$Definition['The import file is not in the correct format.'] = 'הקובץ המיובא אינו בפורמט המתאים.';
$Definition['The location of the authentication endpoint.'] = 'המיקום של נקודת קצה האימות.';
$Definition['ThemeHelp'] = 'ערכות נושא מאפשרות לך לשנות את המראה & התחושה של האתר שלך. <br /> ברגע שערכת נושא הוספת לתיקיית %s שלך, באפשרותך לאפשר אותה כאן.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'תצוגה מקדימה של נושא מוגבלת להצגת התבנית וה- css של העיצוב.';
$Definition['Theming Guide'] = 'מדריך נושאים';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'הלוגו לנייד מופיע בחלק העליון של האתר שלך. ערכות נושא שנוצרו עם עורך ערכות הנושא וכמה ערכות נושא מותאמות אישית אינן משתמשות בהגדרה זו.';
$Definition['The New Embed System'] = 'מערכת ההטמעה החדשה';
$Definition['The new embed system has improved performance.'] = 'מערכת ההטמעה החדשה שיפרה ביצועים, שיפור התנהגות הגלילה והתנהגות עקבית יותר מזו הישנה. נכון לעכשיו, הערות והטמעות וורדפרס אינן נתמכות במערכת ההטמעה החדשה.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'במאמת הסיסמאות אין אפשרויות להתאמה אישית.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'אין צורך בשינויים מהותיים במבנה של מאגר הנתונים. עם זאת, ייתכן שיהיו שינויים במידה עצמו.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'יש שני סוגים של כפתורים ביישום: ראשוני ומשני.';
$Definition['The route was saved successfully.'] = 'הנתיב נשמר בהצלחה';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'תיאור האתר מופיע בדרך כלל במנועי חיפוש. כדאי לנסות לקבל תיאור באורך 100-150 תווים.';
$Definition['The text of the pocket.'] = 'הכנס את המלל של הכיס. זה יוציא בדיוק את מה שהנכם מקלידים אז וודאו  הקלדת HTML בתוקף.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'סמל המגע מופיע כאשר אתה מסמן אתר במסך הבית של מכשיר נייד. אלה הם בדרך כלל 152 פיקסלים.';
$Definition['The user table was not in the import file.'] = 'הטבלה של המתמש לא הייתה בקובץ המיובא.';
$Definition['The Vanilla 2 Exporter'] = 'המייצא של Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'ונילה סטטיסטיקס הופך את לוח הניהול של הפורום שלך לכלי לדיווח ניתוח, מאפשר לך לסקור פעילות בפורום שלך למשך תקופות זמן ממוקדות. באפשרותך <a href="http://vanillaforums.org/docs/vanillastatistics">לקרוא עוד אודות ונילה סטטיסטיקס</a> בתיעוד שלנו.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'הם עובדים בדיוק כמו נושאים רגילים. לאחר שנוספה אחת לתיקיית הנושאים, תוכל להפעיל אותה כאן.';
$Definition['This is a style guide of your theme.'] = 'זהו מדריך לסגנון של הנושא שלך. יש לו דוגמאות לאלמנטים הויזואליים המשמשים בכל היישום. אתה יכול ללחוץ על יישומונים שונים כגון <0> סרגל הכותרות </0> או <1> באנר </1> כדי לערוך את המאפיינים שלהם בלוח הצדדי.';
$Definition['This is the administrative dashboard for your new community.'] = 'זהו לוח ניהול אדמינסטריבי עבור הקהילה החדשה שלך. בדוק את אפשרויות התצורה בצד. משם באפשרותך להגדיר איך הקהילה שלך עובדת. <b>כברירת מחדל, רק משתמשי במעמד "אדמין" יכולים לראות את החל הזה של הקהילה.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'כאן תוכל להפעיל ולבדוק תכונות, דפים ורכיבים חדשים של וניל.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'לא ניתן להשבית את המעבדה הזו מכיוון שהוחלה פריסה מותאמת אישית.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'לא ניתן לבטל מעבדה זו מכיוון שהיא נדרשת על ידי העיצוב הנוכחי.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'לוגו זה מופיע בחלק העליון של האתר שלך. ערכות נושא שנוצרו עם עורך ערכות הנושא וכמה ערכות נושא מותאמות אישית אינן משתמשות בהגדרה זו.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'האפשרות הזאת מראה/מחביאה את המיקומים בהם כיסים יכולים ללכת, אבל רק למשתמשים עם ההרשאה להוסיף/לערוך כיסים. נסה להראות את המיקומים ואז בקר באתר שלך.';
$Definition['This page lists the endpoints of your API.'] = 'דף זה מציג את נקודות הקצה של ה- API שלך. לחץ על נקודות קצה לקבלת מידע נוסף. אתה יכול לבצע שיחות חיות לממשק ה- API מדף זה או חיצונית באמצעות אסימון גישה.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'תפקיד זה הוא מידע אישי. רק משתמשים עם הרשאה להציג מידע אישי יראו אותו.';
$Definition['This setting loads the page before executing Javascript.'] = 'הגדרה זו טוענת את הדף קודם לביצוע Javascript שיכול לשפר את ה-SEO שלך. <br><strong>**אזהרה: הפיכת תכונה זו לזמינה עלולה לגרום שגיאות Javascript באתר שלך.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'הגדרה זו טוענת את הדף לפני הפעלת Javascript שיכולה לשפר את SEO שלך.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'לא ניתן למחוק ערכת נושא זו מכיוון שזו ערכת הנושא הנמצאת בשימוש כעת.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'כותרת זו מופיעה על הבאנר של האתר שלך ובשורת הכותרת של הדפדפן שלך. זה צריך להיות פחות מ-20 תווים. אם יועלה לוגו, הוא יחליף את הכותרת הזו בדפי הפורום הפונים למשתמש. כמו כן, זכור שכמה נושאים עשויים להסתיר את הכותרת הזו.';
$Definition['Tiled Layout'] = 'פריסת אריחים';
$Definition['Title Bar'] = 'שורת כותרת';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'כדי לשלב את הפורום של Vanilla באתר שלך, תשתמש בקוד הבא.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'כתובות רבות מדי! יישלחו עד %s כתובות בבת אחת.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'כדי למנוע שימוש לרעה, ישנם כלים המחביאים תוכן באופן אוטומטי, ומציגים אותו כאן עד לאישור ממנהל פורום.';
$Definition['TouchIconDescription'] = 'סמל המגע מופיע כשאתה מסמן סימניות באתר במסך הבית של מכשיר אפל. לרוב מדובר על 152 פיקסלים. אפל מוסיפה פינות מעוגלות ואפקט תאורה באופן אוטומטי.';
$Definition['Transparent'] = 'שָׁקוּף';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'התחברות באמצעות טוויטר מאפשרת למשתמשם להכנס באמצעות שימוש בחשבונות הטוויטר שלהם. <b> חובה בהרשאות של היישום שלך עם טוויטר על מנת שהתוסף הזה יעבוד.</b>';

$Definition['Usercards'] = 'כרטיסי משתמש';
$Definition['User inputs are based on the global background and text colors.'] = 'תשומות המשתמשים מבוססות על צבעי הרקע והטקסט העולמיים.';
$Definition['User Profile'] = 'פרופיל משתמש';
$Definition['Users may sign into your site using their Twitter account.'] = 'משתמשים עשויים להיכנס לאתר שלך באמצעות חשבון הטוויטר שלהם.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'השתמש בלחצן בראש הדף כדי ליצור כלל איסור.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'השתמש בתוסף WordPress כדי להתקין את ונילה תגובות בבלוג שלך, או השתמש בקוד האוניברסלי כדי להתקין את ונילה תגובות על כל פלטפורמה אחרת.';

$Definition['Vanilla Export: %s, Source: %s'] = 'ונילה ייצוא: %s, מקור: %s';
$Definition['Vanilla Labs'] = 'מעבדות וניל';
$Definition['Vanilla Statistics are currently disabled'] = 'הסטטיסטיקות של ונילה לא מופעלות';
$Definition['Verify and restore'] = 'אמת ושחזר';
$Definition['VerifyUser'] = 'סמן את התיבה שליד המשתמש כדי לסמן אותם <b>כמאומתים</b> כדי שהפוסטים שלו לא יסומנו כספאם שוב. זה גם ישחזר את כל הפוסטים הממתינים שלהם.';
$Definition['Video tutorial on advanced settings'] = 'מדריך וידאו על האפשרויות המתקדמות';
$Definition['Video tutorial on finding &amp; managing users'] = 'מדריך וידאו על מציאת & ניהול משתמשים';
$Definition['Video tutorial on managing appearance'] = 'מדריך וידאו על ניהול תצוגה';
$Definition['Video tutorial on managing categories'] = 'מדריך וידאו על ניהול קטגוריות';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'מדריך וידאו על ניהול תפקידים & הרשאות';
$Definition['Video tutorial on user registration'] = 'מדריך וידאו על רישום משתמשים';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'אזהרה: הפעלת תכונה זו עלולה לגרום לשגיאות Javascript באתר שלך.';
$Definition['Warning: Loading tables can be slow.'] = '<b>אזהרה</b> : תצורת השרת שלך אינה תומכת בטעינת נתונים מהירה. אם אתה מייבא קובץ גדול מאוד (למשל מעל 200,000 תגובות), אולי כדאי לך לשקול לשנות את התצורה שלך. לחץ <a href="http://vanillaforums.com/porter">כאן</a> למידע נוסף.';
$Definition['Warning: This is for advanced users.'] = '<b>אזהרה</b>: זה למשתמשים מתקדמים ודרוש שתעשה שינויים נוסיף לשרת האינטרנט שלך. זה בדרך כלל זמין רק אם אתה מסור או vps hosting. אל תנסה את זה אם אתה לא יודע מה אתה עושה.';
$Definition['Webhooks'] = 'וו הוקס';
$Definition['Welcome to Labs!'] = 'ברוכים הבאים למעבדות!';
$Definition['Welcome To Your Theme'] = 'ברוך הבא לנושא שלך';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'אנו ממליצים בעיקר על תגובות חיוביות כדי לעודד השתתפות.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'כאשר הדבר מופעל, אתה יכול לנהל מוצרים ולקבוצות משנה תת קבוצות לפי מוצרים אלה.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'כאשר מישהו משתף קישור מהאתר שלך אנו מנסים לתפוס תמונה מהדף. אם אין תמונה בדף, אנו נשתמש בתמונה זו במקום זאת. התמונה צריכה להיות לפחות 50 × 50, אך אנו ממליצים על 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'כשאתה בוחר דימום מלא, הרקע שלך שקוף.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'האם שדות הפרופיל הפנימיים ייכללו ב-webhook זה או לא.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'האם שדות הפרופיל הפרטי ייכללו ב-webhook זה או לא.';
$Definition['Which reactions you use really depends on your community.'] = 'אילו תגובות אתה משתמש באמת תלויות בקהילה שלך, אך אנו ממליצים לזכור כמה נקודות.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'אתה עומד ליישם אפשרות פריסה חדשה. ניתן להתאים אישית ולצפות בתצוגה מקדימה באמצעות עורך הנושאים שלנו. <0> למידע נוסף</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'באפשרותך לאסור את הכניסה של כל המשתמשים בעלי כתובת IP  עם הקידומת "111.111.111" על ידי הוספת איסור כניסה מסוג IP עם הערך "111.111.111.*".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'באפשרות לאסור כניסה לפי כתובות IP, כתובות אימייל ושמות משתמש.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'אתה יכול לבחור מבין אחד הסגנונות השונים שהנושא הזה מציע.';
$Definition['You can configure some values differently for different screensizes.'] = 'אתה יכול להגדיר ערכים שונים באופן שונה עבור מסכי מסך שונים.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'ניתן להתחבר לאתרים שונים שתומכים ב-jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'הקובץ שלך גדול מדי כדי להעלות אותו ישירות לדף הזה באפשרותך לשים אותו בתיקיית /uploads שלך. וודא כי שם הקובץ מתחיל עם המילה <b>export</b> ונגמר עם אחת מהאופציות <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'אתה יכול לציין אורך מינימום של פוסט כדי להרתיע פוסטים קצרים.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'אתה יכול להעלות גופן מותאם אישית במערכת ההכנה שלך. פשוט העתק והדבק את כתובת האתר בשדה.';
$Definition['You must select a file to import.'] = 'בחר קובץ לייבוא.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'עליך להוסיף את הדומיין של כתובת הגופן ל <0> דומיינים מותרים </0> בתצורת האתר. <1> למידע נוסף על גופנים מותאמים אישית. </1>';
$Definition['Your mobile theme will be disabled.'] = 'הנושא שלך לנייד יושבת. כדי להגדיר נושאים שונים להתקנים ניידים ושולחן העבודה, השתמש בממשק המשתמש הישן של הנושאים.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'נעשה שימוש בשם הארגון שלך למטרות SEO microdata ו- JSON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'סמל המועדפים של האתר שלך מופיע בפס הכותרת של הדפדפן. הוא יוקטן באופן פרופורציונלי.';
