<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Amaran: Mendayakan ciri ini boleh menyebabkan ralat Javascript pada tapak anda.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Awas!</strong> Menghapus peranan boleh menyebabkan pengguna tidak dapat mengakses aplikasi.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Awas!</strong> Memindahkan perbincangan ke kategori pengganti boleh mengakibatkan perbincangan lenyap (atau muncul) jika kategori pengganti mempunyai kebenaran yang berbeza daripada kategori yang dihapuskan.';

$Definition['About.DisableStatistics'] = 'Sekiranya anda mesti melumpuhkan pelaporan data ini atas sebab perniagaan, anda boleh melakukannya dengan menambahkan baris berikut ke fail konfigurasi pemasangan anda: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Sangat penting bagi kehidupan perisian sumber terbuka percuma ini yang kita dapat mengukur jangkauan dan keberkesanan Vanilla dengan tepat. Kami meminta agar anda tidak melumpuhkan pelaporan data ini.';
$Definition['AboutCommentEmbedding'] = 'Vanilla boleh digunakan sebagai pengganti drop-in untuk sistem komen asli blog anda. Sebenarnya, ia boleh digunakan untuk menambahkan komen ke mana-mana halaman di web.';
$Definition['AboutEmbedding'] = 'Penyematan membolehkan semua atau sebahagian komuniti anda disisipkan ke dalam aplikasi & halaman web yang lain.';
$Definition['About Vanilla Statistics'] = 'Mengenai Statistik Vanilla';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Akses forum komuniti anda dengan mengklik pautan "Lawati Laman" di bahagian atas halaman ini, atau dengan <a href={/,url}>mengklik di sini</a> . Forum komuniti adalah apa yang akan dilihat oleh semua pengguna & pelanggan anda semasa mereka melawat <a href="{/,url,domain}">{/, url, domain}</a> .';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Tambahkan had pada dimensi muat naik gambar dalam perbincangan dan komen.';
$Definition['AddonProblems'] = '<h2> Masalah? </h2><p> Sekiranya ada yang tidak kena dengan addon dan anda tidak dapat menggunakan laman web anda, anda boleh melumpuhkannya secara manual dengan menyunting: </p> %s';
$Definition['AddressBarColorDescription'] = 'Beberapa penyemak imbas menyokong warna untuk bar alamat. Mudah alih sahaja.';
$Definition['Alert users if they click external link.'] = 'Maklumkan pengguna sekiranya mereka mengklik pautan dalam siaran yang akan membawa mereka keluar dari forum. Pengguna tidak akan diberi amaran ketika mengikuti pautan yang sesuai dengan Domain yang Dipercayai';
$Definition['Alignment'] = 'Penjajaran';
$Definition['Alignment (Mobile)'] = 'Penjajaran (Mudah Alih)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Semua kategori disenaraikan dengan pilihan 5 perbincangan terkini di bawah masing-masing';
$Definition['Allow links to be transformed'] = 'Benarkan pautan diubah menjadi representasi tertanam dalam perbincangan dan komen. Sebagai contoh, pautan YouTube akan berubah menjadi video terbenam.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Benarkan pengguna dengan kebenaran %s untuk menukar avatar mereka sendiri dari halaman profil mereka di Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Anonimkan Alamat IP';
$Definition['ApplicationHelp'] = 'Aplikasi membolehkan anda menambahkan kumpulan fungsi yang besar ke laman web anda. <br /> Setelah aplikasi ditambahkan ke folder %s anda, anda boleh mengaktifkan atau mematikannya di sini.';
$Definition['Apply Layout'] = 'Gunakan Tata Letak';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Adakah anda pasti mahu memadamkan tema ini? Ia akan dipadamkan secara kekal.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Adakah anda pasti memasukkan nama host pangkalan data yang betul? Mungkin anda salah menaipnya? Pangkalan data dilaporkan: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Peranan dengan jenis lalai "tidak disahkan" diperlukan untuk menggunakan pengesahan e-mel.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Simpan secara automatik draf perbincangan, soalan, idea dan ulasan yang tidak diterbitkan.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatar akan dikecilkan jika melebihi ketinggian ini.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatar akan dikecilkan jika melebihi lebar ini.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatar akan menyimpan gambar kecil mereka pada saiz ini.';

$Definition['Background'] = 'Latar belakang';
$Definition['Background Image'] = 'Gambar Latar Belakang';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Jadilah kreatif! Cuba namakan barisan anda mengikut perkara yang dibincangkan oleh komuniti.';
$Definition['Bordered'] = 'Bersempadan';
$Definition['Bordered (Unified)'] = 'Bersempadan (Bersatu)';
$Definition['Borderless'] = 'Tanpa sempadan';
$Definition['Border Radius'] = 'Radius Sempadan';
$Definition['Brand Color'] = 'Warna Jenama';
$Definition['Buttons'] = 'Butang';
$Definition['Buttons & Inputs'] = 'Butang & Input';
$Definition['Button Type'] = 'Jenis Butang';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Dengan mengklik butang di bawah, anda akan menghapus akaun pengguna untuk %s selama-lamanya.';

$Definition['Center Aligned'] = 'Pusat Sejajar';
$Definition['Changes to the set day will take affect the following week.'] = 'Perubahan pada hari yang ditetapkan akan memberi kesan pada minggu berikutnya.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Perubahan hanya akan berlaku untuk avatar yang baru dimuat naik.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Ubah ukuran gambar avatar disimpan.';
$Definition['Change the way your community works with plugins.'] = 'Ubah cara komuniti anda bekerja dengan pemalam. Kami telah menggabungkan pemalam yang popular dengan perisian, dan terdapat lebih banyak yang tersedia dalam talian.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Kotak pilihan membolehkan pentadbir melakukan banyak tindakan pada beberapa perbincangan atau komen pada masa yang sama.';
$Definition['Check out our %s'] = 'Lihat %s kami';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Lihat <0>dokumentasi kami</0> , atau tanya <1>komuniti pakar kami</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla adalah platform komuniti paling mudah dan paling berkuasa di dunia. Ia sangat mudah digunakan. Mulakan dengan video pengenalan ini dan teruskan dengan langkah di bawah. Selamat mencuba!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Pilih peranan yang akan diberikan kepada pengguna yatim:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Pilih tema untuk subkomuniti ini. <0> Baca lebih lanjut </0>';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Pilih cara menangani semua kandungan yang berkaitan dengan akaun pengguna untuk %s (komen, mesej, dll).';
$Definition['Choose Image'] = 'Pilih Imej';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Anda boleh memilih algoritma hash khusus untuk menandatangani permintaan anda. Algoritma hash juga mesti digunakan di perpustakaan pelanggan anda. Pilih md5 jika anda tidak pasti apa yang harus dipilih.';
$Definition['Choose the order items are sorted.'] = 'Pilih item pesanan yang disusun.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Pilih halaman yang mesti dilihat orang ketika mereka mengunjungi <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Pilih susun atur pilihan untuk senarai kategori.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Pilih susun atur pilihan untuk senarai kategori. Anda boleh mengedit Susun atur Berubin.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Pilih susun atur pilihan untuk senarai perbincangan.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Pilih reka letak pilihan untuk senarai perbincangan. Anda boleh mengedit Reka Letak Asas.';
$Definition['Color Overlay'] = 'Hamparan Warna';
$Definition['Continue Import'] = 'Teruskan Import';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Tidak dapat menguraikan fail import. Masalahnya adalah berhampiran talian %s.';
$Definition['Create a localization CSV'] = 'Buat CSV penyetempatan';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Tema Custom adalah tema yang anda buat. Anda boleh mengedit, menamakan semula atau membuat salinannya.';

$Definition['Dark'] = 'Gelap';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Tentukan siapa yang boleh memuat naik dan menguruskan fail di halaman <a href="%s">Peranan & Kebenaran</a> .';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Tentukan laman utama forum anda, muat naik logo anda dan banyak lagi ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Menghapus peranan boleh menyebabkan pengguna tidak dapat mengakses aplikasi.';
$Definition['Deleting forever cannot be undone.'] = 'Menghapus adalah cara yang baik untuk menjaga kebersihan forum anda.';
$Definition['Disable Google Sign In'] = 'Lumpuhkan Log Masuk Google';
$Definition['Disable OpenID'] = 'Lumpuhkan OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Lumpuhkan makmal "Sistem Benam Baharu" pada <0>Halaman Makmal Vanila</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Kategori perbincangan digunakan untuk membantu pengguna anda mengatur perbincangan mereka dengan cara yang bermakna bagi komuniti anda.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Jangan tanamkan papan pemuka pentadbir forum anda (masukkan ke layar penuh)';
$Definition['Don\'t use too many reactions.'] = 'Jangan terlalu banyak menggunakan reaksi. Anda tidak mahu memberi maklumat pengguna yang berlebihan.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Seret dan lepaskan kategori di bawah untuk menyusun dan menyusunnya.';

$Definition['EditContentTimeout.Notes'] = 'Sekiranya pengguna mempunyai peranan yang mempunyai izin untuk mengedit kandungan, kebenaran tersebut akan menggantikannya.';
$Definition['Edit Route'] = 'Edit Laluan';
$Definition['Edits to this theme apply to:'] = 'Pengeditan pada tema ini berlaku untuk:';
$Definition['Email digests will be sent on the selected day every week.'] = 'Ringkasan e-mel akan dihantar pada hari yang dipilih setiap minggu.';
$Definition['Email sent from the application will be addressed from this email address'] = 'E-mel yang dihantar daripada permohonan akan dialamatkan daripada alamat e-mel ini';
$Definition['Email sent from the application will be addressed from this name'] = 'E-mel yang dihantar daripada permohonan akan dialamatkan daripada nama ini';
$Definition['Email Settings'] = 'Tetapan E-mel';
$Definition['Embed Settings'] = 'Benamkan Tetapan';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Benamkan forum komuniti anda ke laman web anda untuk meningkatkan penglibatan ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Aktifkan dan uji ciri Vanilla terkini.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Membolehkan penyuntingan catatan lanjutan dalam beberapa format, termasuk WYSIWYG, HTML ringkas, Markdown, dan BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Dayakan Editor Layout untuk menggunakan reka letak tersuai untuk halaman komuniti anda. Gunakan editor baharu kami untuk menampilkan kandungan menggunakan katalog widget kami yang tersedia.';
$Definition['Enter a descriptive name.'] = 'Masukkan nama deskriptif untuk poket. Nama ini tidak akan muncul di mana sahaja kecuali ketika menguruskan poket anda di sini sehingga hanya digunakan untuk membantu anda mengingat poket.';
$Definition['Enter a short name for the site.'] = 'Masukkan nama pendek untuk laman web ini. Ini dipaparkan pada butang log masuk.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Masukkan alamat Blog Wordpress anda dan kami akan mengambilnya dari sana.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Masukkan tetapan sambungan untuk pelayan sphinx anda di bawah.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Setiap pengeditan atau penghapusan direkodkan di sini. Gunakan \'Pulihkan\' untuk membuat asal perubahan.';
$Definition['Everyone who signs up gets a profile page.'] = 'Setiap orang yang mendaftar untuk komuniti anda mendapat halaman profil awam di mana mereka dapat memuat naik gambar diri mereka sendiri, menguruskan tetapan profil mereka, dan mengesan perkara menarik yang berlaku di komuniti. Anda harus <a href="{/profile,url}">menyesuaikan profil anda sekarang</a> .';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Setiap pengguna di laman web anda diberikan sekurang-kurangnya satu peranan. Peranan digunakan untuk menentukan apa yang dibenarkan oleh pengguna.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect membolehkan pengguna log masuk menggunakan akaun Facebook mereka. <b>Anda mesti mendaftarkan aplikasi anda ke Facebook agar plugin ini berfungsi.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Gagal menyambung ke pangkalan data dengan nama pengguna dan kata laluan yang anda masukkan. Adakah anda salah menaipnya? Pangkalan data dilaporkan: <code>%s</code>';
$Definition['Font'] = 'Fon';
$Definition['Font Name'] = 'Nama Fon';
$Definition['Font URL'] = 'URL fon';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Memaksa papan pemuka hanya dapat diakses melalui url ini <em>(tidak disyorkan)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Sebagai contoh, anda boleh melarang semua pengguna dengan alamat e-mel dari "example.com" dengan menambahkan larangan jenis e-mel dengan nilai "*@example.com".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Untuk tujuan SEO, perayap mesin carian dikecualikan daripada dipaksa untuk melihat forum di url terpencil.';
$Definition['Foundation Layout'] = 'Susun atur Asas';
$Definition['Full Anonymization'] = 'Penganoniman Penuh';
$Definition['FullAnonymization.Description'] = '<strong>Anonimisasi Penuh</strong> menggantikan setiap alamat IP tunggal dengan 0.0.0.0 dengan berkesan menafikan aplikasi sebarang akses untuk berfungsi dengan alamat IP. Peraturan larangan IP tidak akan berfungsi sama sekali dalam kes ini.';
$Definition['Full Bleed'] = 'Pendarahan Penuh';

$Definition['Garden.Import.Complete.Description'] = 'Anda berjaya menyelesaikan import. Klik <b>Selesai</b> apabila anda sudah bersedia.';
$Definition['Garden.Import.Continue.Description'] = 'Nampaknya anda berada di tengah-tengah import. Sila pilih salah satu pilihan berikut.';
$Definition['Garden.Import.InputInstructions'] = 'Masukkan e-mel dan kata laluan pengguna pentadbir dari data yang diimport.';
$Definition['Garden.Privacy.IPs.Description'] = 'Alamat IP pengguna biasanya dikumpulkan untuk peraturan larangan automatik, penyederhanaan dan tujuan pencegahan spam. Mendayakan Penganoniman IP akan menamakan semua alamat IP yang dijejaki dalam tapak untuk sebarang tujuan dan akan mengurangkan keberkesanan alat ini. Perubahan pada tetapan ini tidak retroaktif.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit kebenaran untuk menukar avatar mereka sendiri dari halaman profil mereka di Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Anda secara khusus telah melumpuhkan Statistik Vanila dalam fail konfigurasi anda.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Forum ini nampaknya berjalan dalam lingkungan ujian, atau melaporkan IP persendirian. Secara lalai, forum yang dijalankan di IP peribadi tidak dijejaki.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Sekiranya anda yakin forum anda dapat diakses dari internet, anda boleh memaksanya untuk melaporkan statistik di sini:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Fail config.php anda hanya boleh dibaca. Ini bermaksud bahawa Vanilla tidak dapat mendaftarkan InstallationID dan InstallationSecret forum anda secara automatik.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Untuk menyelesaikan masalah ini, tetapkan mod fail 777 ke fail conf / config.php anda.';
$Definition['Global Styles'] = 'Gaya Global';

$Definition['Heads Up!'] = 'Awas!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Awas! Ini adalah peranan khas yang tidak membenarkan sesi aktif. Atas sebab ini, pilihan kebenaran telah terhad kepada kebenaran "melihat".';
$Definition['Here are all of the reactions you can use on your site.'] = 'Berikut adalah semua reaksi yang boleh anda gunakan di laman web anda.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Berikut adalah kedudukan yang boleh dicapai oleh pengguna di laman web anda. Anda boleh menyesuaikan peringkat ini dan bahkan menambah yang baru. Berikut adalah beberapa petua.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Sekiranya logo sepanduk dimuat, ia akan menggantikan tajuk sepanduk di halaman forum yang menghadap pengguna.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Jika pengguna tidak melawat tapak dalam tempoh masa ini mereka akan dilog keluar secara automatik.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Sekiranya diaktifkan, kandungan penuh siaran akan dihantar dalam pemberitahuan e-mel kepada pengguna.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Sekiranya anda baru menggunakan HTML dan / atau CSS, berikut adalah beberapa tutorial untuk memulakan anda:';
$Definition['If you have an old theme'] = 'Sekiranya anda mempunyai tema lama dan perlu menetapkan tema desktop dan mudah alih yang berasingan, anda boleh melakukannya dengan UI bertema lama.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Sekiranya anda ingin menurunkan tahap amaran maka hapus amaran.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Sekiranya anda ingin menanamkan forum anda atau menggunakan komen Vanilla di blog anda, maka anda perlu mengaktifkan penyematan. Sekiranya anda tidak menggunakan penyematan, sebaiknya matikan tetapan ini.';
$Definition['Image (Mobile)'] = 'Imej (Mudah Alih)';
$Definition['Importing to Vanilla'] = 'Mengimport ke Vanilla';
$Definition['In additon to the widgets there are also'] = 'Di samping widget terdapat juga <0> Gaya Global </0> . Untuk mengedit gaya global klik di tempat lain di halaman, seperti teks ini.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Mengintegrasikan Halaman & Komponen Asas ke Tema Anda';
$Definition['Internationalization & Localization'] = 'Pengantarabangsaan & Penyetempatan';
$Definition['Invalid URL'] = 'URL tidak sah';
$Definition['Invitation email failed to send: %'] = 'Walaupun jemputan berjaya dibuat, e-mel gagal dihantar. Pelayan melaporkan ralat berikut: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Apabila anda menggunakan pendaftaran oleh jemputan, pengguna akan mempunyai pautan yang disebut <a href="%s" class="Popup">Jemputan Saya</a> di halaman profil mereka.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Nampaknya pangkalan data yang anda nyatakan belum wujud. Adakah anda telah membuatnya? Adakah anda salah menamakan nama? Pangkalan data dilaporkan: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Adalah idea yang baik untuk mengekalkan bilangan maksimum watak yang dibenarkan dalam komen sehingga ukurannya masuk akal.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Adalah idea yang baik untuk mengekalkan bilangan maksimum watak yang dibenarkan dalam siaran ke ukuran yang wajar.';

$Definition['Kick-start your community and increase user engagement.'] = 'Mulakan komuniti anda dan tingkatkan penglibatan pengguna.';

$Definition['Labs'] = 'Makmal';
$Definition['Layout Editor'] = 'Editor Reka Letak';
$Definition['Learn about custom routing.'] = 'Ketahui mengenai penghalaan tersuai.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Pelajari cara mengubah rupa dan nuansa forum anda sepenuhnya: muat naik logo anda, tetapkan laman utama anda, pilih tema dan sesuaikannya.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Ketahui cara menggunakan fungsi asas forum anda.';
$Definition['Left Aligned'] = 'Kiri Sejajar';
$Definition['Light'] = 'Cahaya';
$Definition['Links'] = 'Pautan';
$Definition['Locales allow you to support other languages on your site.'] = 'Lokasi membolehkan anda menyokong bahasa lain di laman web anda. Dayakan dan lumpuhkan tempat yang ingin anda sediakan di sini.';
$Definition['Lockout Time (seconds)'] = 'Masa Kunci Keluar (saat)';
$Definition['LogoDescription'] = 'Logo sepanduk muncul di bahagian atas laman web anda.';
$Definition['LogoDisclaimer'] = 'Tema yang dibuat dengan editor tema dan beberapa tema khusus tidak menggunakan tetapan ini.';
$Definition['Looking for the Old Embed System?'] = 'Mencari Sistem Benam Lama?';

$Definition['Make sure you click View Page'] = 'Pastikan anda mengklik <a href="%s">Lihat Halaman</a> untuk melihat seperti apa halaman kategori anda setelah disimpan.';
$Definition['Manage Routes'] = 'Urus Laluan';
$Definition['Managing Users'] = 'Menguruskan Pengguna';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Menandakan perkara sebagai BUKAN spam akan mengembalikannya di forum anda.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Menandakan sesuatu sebagai bukan spam akan meletakkannya kembali di forum anda.';
$Definition['Messages can appear anywhere in your application.'] = 'Mesej boleh muncul di mana saja dalam aplikasi anda, dan dapat digunakan untuk memberi tahu pengguna tentang berita dan peristiwa. Gunakan halaman ini untuk menyusun semula mesej anda dengan menyeretnya ke atas atau ke bawah.';
$Definition['MobileLogoDescription'] = 'Logo sepanduk bergerak muncul di bahagian atas laman web anda.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Tema mudah alih membolehkan anda mengubah rupa dan nuansa laman web anda pada peranti yang lebih kecil.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Editor Reka Letak baharu akan mewarisi set tema dalam Panduan Gaya anda (secara rasmi editor tema). <1>Ketahui lebih lanjut</1>';
$Definition['Need More Help?'] = 'Perlukan Lebih Banyak Bantuan?';
$Definition['Need more help?'] = 'Perlukan lebih banyak pertolongan?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Kategori bersarang lebih dalam daripada kedalaman ini akan dimasukkan dalam senarai yang dipisahkan koma.';
$Definition['New Embed System'] = 'Sistem Benam Baharu';
$Definition['New Quick Links'] = 'Pautan Pantas Baru';
$Definition['New Search Page'] = 'Halaman Carian Baru';
$Definition['No Anonymization'] = 'Tiada Anonimisasi';
$Definition['Not getting what you expect when you preview your theme?'] = 'Tidak mendapat apa yang anda harapkan semasa anda melihat tema anda?';
$Definition['Notify me when people comment on my addons.'] = 'Beritahu saya apabila orang memberi komen mengenai addon saya.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Laman web memerlukan peranan dengan jenis lalai "tidak disahkan" untuk menggunakan pengesahan e-mel. Sila tambah satu untuk mengaktifkan tetapan ini.';

$Definition['Old Theming UI'] = 'UI Tema Lama';
$Definition['Once enabled, only members will see inside your community.'] = 'Setelah diaktifkan, hanya ahli yang akan melihat di dalam komuniti anda.';
$Definition['OrgDescription'] = 'Nama organisasi anda digunakan untuk microdata SEO dan JSON + LD';
$Definition['Outline'] = 'Garis besar';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Paparan yang berlebihan atau kaitannya boleh mempunyai kesan sampingan yang tidak diingini dan tidak dipratonton.';

$Definition['Partial Anonymization'] = 'Penganoniman Separa';
$Definition['PartialAnonymization.Description'] = '<strong>Penganoniman Separa</strong> hanya menyamaratakan oktet terakhir alamat IP. Contohnya 254.230.05.153 akan menjadi 254.230.05.0. Ini menyediakan beberapa anonimisasi sementara masih membenarkan peraturan larangan IP berfungsi.';
$Definition['Password.MinLength'] = 'Panjang aksara minimum dibenarkan untuk kata laluan pengguna pada kata laluan membuat dan menetapkan semula halaman.';
$Definition['Please choose an authenticator to configure.'] = 'Sila pilih pengesah untuk dikonfigurasi.';
$Definition['PluginHelp'] = 'Pemalam membolehkan anda menambahkan fungsi ke laman web anda. <br /> Setelah pemalam ditambahkan ke folder %s anda, anda boleh mengaktifkan atau mematikannya di sini.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Poket dipaparkan di antara setiap perbincangan dalam senarai perbincangan utama. Oleh kerana perbincangan biasanya terdapat dalam tag <li> .. </li>, anda juga perlu membungkus poket anda pada tag tersebut.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Poket membolehkan anda menambahkan HTML bentuk bebas ke pelbagai tempat di sekitar aplikasi.';
$Definition['Preset'] = 'Pratetap';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Cegah spam di forum anda dengan menghadkan jumlah perbincangan & komen yang boleh dihantar oleh pengguna dalam jangka masa tertentu.';
$Definition['Primary Button'] = 'Butang Utama';
$Definition['Primary Buttons'] = 'Butang Utama';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Panduan Memulakan Pantas untuk Membuat Tema untuk Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Pautan Pantas adalah komponen lalai di laman komuniti. Dayakan komponen Pautan Pantas kami untuk menambah, mengedit atau menyembunyikan pautan dari menu ini menggunakan penyunting tema kami.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Plugin Komen Vanilla Sedia untuk WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Plugin Forum Vanila siap pakai untuk WordPress';
$Definition['Realtime progress bars: %s'] = 'Bar kemajuan masa nyata: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Adalah idea yang baik untuk mempunyai barisan khas untuk moderator dan pentadbir supaya komuniti anda dapat dengan mudah melihat siapa yang bertanggungjawab.';
$Definition['Recommend starting with five ranks.'] = 'Anda tidak mahu mempunyai terlalu banyak pangkat. Kami mengesyorkan bermula dengan lima. Anda boleh menambahkan lagi jika komuniti anda benar-benar besar.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Alih keluar pautan perbincangan dan kategori daripada menu. Tetapkan halaman berkaitan perbincangan dan kategori untuk mengembalikan halaman tidak ditemui 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Memerlukan kebenaran reaksi "Bendera".';
$Definition['Requires “Negative” reaction permission.'] = 'Memerlukan kebenaran reaksi "Negatif".';
$Definition['Requires “Positive” reaction permission.'] = 'Memerlukan kebenaran reaksi "Positif".';
$Definition['Restoring your selection removes the items from this list.'] = 'Apabila anda memulihkan, item akan dikeluarkan dari senarai ini dan dimasukkan kembali ke laman web.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Gunakan pilihan berikut untuk mengaktifkan sebut harga untuk Editor Kaya. Ini hanya akan berlaku jika pemformat lalai adalah "Kaya".';
$Definition['Route Expression'] = 'Ekspresi Laluan';
$Definition['Routes are used to redirect users.'] = 'Laluan digunakan untuk mengarahkan pengguna bergantung pada URL yang diminta.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Cari pengguna dengan nama atau masukkan nama peranan untuk melihat semua pengguna dengan peranan itu.';
$Definition['Secondary Button'] = 'Butang Sekunder';
$Definition['Secondary Buttons'] = 'Butang Sekunder';
$Definition['Security.Hsts.HTTPSWarning'] = 'Amaran: Aktifkan ciri ini hanya jika anda pasti semua subdomain anda dikonfigurasi untuk HTTPS dengan sijil yang sah.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Apabila diaktifkan, peraturan ini juga berlaku untuk semua subdomain laman web anda.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Kami mengesyorkan bermula dengan usia maksimum 1 minggu dan kemudian meningkatkannya menjadi 1 bulan kemudian 1 tahun setelah anda melihat laman web anda berfungsi seperti yang diharapkan.';
$Definition['Security.Hsts.SubmitWarning'] = 'Amaran: Senang menyokong pramuat HSTS sebagai amalan terbaik. Walau bagaimanapun, anda mesti menghantar laman web anda ke hstspreload.org untuk memastikan bahawa laman web ini berjaya dimuatkan terlebih dahulu (iaitu untuk mendapatkan perlindungan penuh untuk konfigurasi yang dimaksudkan).';
$Definition['See the documentation'] = 'Lihat Dokumentasi';
$Definition['Select the default type for this role, if any.'] = 'Pilih jenis lalai untuk peranan ini, jika ada.';
$Definition['Select the import source'] = 'Pilih sumber import';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Lajur bersiri "%s" gagal dicetak.';
$Definition['Session Timeout'] = 'Tamat Masa Sesi';
$Definition['Shadowed'] = 'Dibayang';
$Definition['ShareImageDescription'] = 'Apabila seseorang berkongsi pautan dari laman web anda, kami mencuba dan mengambil gambar dari halaman. Sekiranya tidak ada gambar di halaman maka kami akan menggunakan gambar ini sebagai gantinya. Gambar mestilah sekurang-kurangnya 50 × 50, tetapi kami mengesyorkan 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Hidupkan pilihan ini untuk menunjukkan semua lokasi poket yang mungkin. Menghidupkan pilihan ini hanya akan menunjukkan lokasi kepada pengguna yang boleh menguruskan poket.';
$Definition['SignIn.LockoutTime'] = 'Jumlah masa pengguna disekat daripada log masuk selepas melebihi bilangan percubaan log masuk.';
$Definition['Solid'] = 'Padu';
$Definition['Some browsers support a color for the address bar.'] = 'Sesetengah penyemak imbas menyokong warna untuk bar alamat.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Sesetengah tema lama tidak menyokong keupayaan penyuntingan penuh. Untuk melihat perkara yang disokong oleh tema, anda boleh menuding pada namanya untuk melihat tempat pengeditan akan berkuat kuasa.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Beberapa tema mungkin perlu dikemas kini agar sesuai dengan kategori berikut. Anda boleh mematikan ciri semasa anda mengemas kini tema anda.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Kadangkala anda ingin membenamkan tapak Vanila anda di dalam tapak lain. Sistem benam Vanila menawarkan cara mudah untuk itu. Terdapat pertukaran prestasi apabila menggunakan tapak terbenam, jadi semak dokumentasi untuk alternatif dan kes penggunaan yang ideal.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Sekatan khas: Hanya pengguna dengan izin Garden.Curation.Manage boleh menggunakan reaksi ini.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Tentukan padanan separa atau penuh ketika membuat larangan.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Luangkan sedikit masa untuk memikirkan bagaimana anda menerangkan laman web anda di sini. Memberi judul yang bermakna dan keterangan ringkas kepada laman web anda dapat membantu kedudukan anda di mesin pencari.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Masukkan e-mel anda dengan menambahkan logo dan menyesuaikan warnanya.';
$Definition['Start Import'] = 'Mulakan Import';
$Definition['Start the first discussion.'] = 'Buat bola meluncur di komuniti anda dengan <a href="{/post/discussion,url}">memulakan perbincangan pertama</a> sekarang.';
$Definition['Subcommunities'] = 'Subkomuniti';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Pemberian tag membolehkan pengguna menambahkan teg pada perbincangan yang mereka mulakan untuk menjadikannya lebih mudah ditemui.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Templat adalah tema standard. Untuk menyesuaikannya, anda mesti membuat salinan.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Pengesah %s tidak mempunyai pilihan konfigurasi tersuai.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB Makmal <0 /> perlu dikonfigurasikan agar sesuai dengan tema tersuai anda. Ini boleh dilakukan dengan menggunakan editor tema baru kami. <1> Ketahui lebih lanjut.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Addon tidak dapat diaktifkan kerana menghasilkan ralat maut: <pre> %s </pre>';
$Definition['The addon has already been downloaded.'] = 'Addon telah dimuat turun.';
$Definition['The banner logo appears at the top of your forum.'] = 'Logo sepanduk muncul di bahagian atas forum anda.';
$Definition['The banner title appears on the top-left of every page.'] = 'Tajuk sepanduk muncul di kiri atas setiap halaman.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Tajuk sepanduk muncul di sepanduk laman web anda dan di bar tajuk penyemak imbas anda. Harus kurang dari 20 aksara. Sekiranya logo sepanduk dimuat, ia akan menggantikan tajuk sepanduk di halaman forum yang menghadap pengguna. Juga, ingat beberapa tema mungkin juga menyembunyikan tajuk ini.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Borang pendaftaran asas memerlukan</strong> pengguna baru untuk menyalin teks dari gambar CAPTCHA untuk mengelakkan spammer keluar dari laman web ini. Anda memerlukan akaun di <a href="http://recaptcha.net/">recaptcha.net</a> . Mendaftar adalah PERCUMA dan mudah. Setelah mendaftar, kembali ke sini dan masukkan tetapan berikut:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Pengguna pangkalan data yang anda tentukan tidak mempunyai kebenaran untuk mengakses pangkalan data. Adakah anda sudah membuat pangkalan data? Pangkalan data dilaporkan: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Perubahan struktur berikut diperlukan untuk pangkalan data anda.';
$Definition['The homepage title is displayed on your home page. Pick a title that you would want to see appear in search engines.'] = 'Tajuk laman utama dipaparkan di laman utama anda. Pilih tajuk yang ingin anda lihat muncul di enjin carian.';
$Definition['The import file does not contain any data.'] = 'Fail import tidak mengandungi data.';
$Definition['The import file is not in the correct format.'] = 'Fail import tidak dalam format yang betul.';
$Definition['The location of the authentication endpoint.'] = 'Lokasi titik akhir pengesahan.';
$Definition['ThemeHelp'] = 'Tema membolehkan anda mengubah rupa & nuansa laman web anda. <br /> Setelah tema ditambahkan ke folder %s anda, anda boleh mengaktifkannya di sini.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Pratonton tema terhad untuk memaparkan templat dan css tema.';
$Definition['Theming Guide'] = 'Panduan Tema';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Logo mudah alih muncul di bahagian atas tapak anda. Tema yang dibuat dengan editor tema dan beberapa tema tersuai tidak menggunakan tetapan ini.';
$Definition['The New Embed System'] = 'Sistem Benam Baharu';
$Definition['The new embed system has improved performance.'] = 'Sistem benam baharu telah meningkatkan prestasi, kelakuan menatal yang lebih baik dan kelakuan yang lebih konsisten daripada yang lama. Pada masa ini ulasan dan benaman wordpress tidak disokong dalam Sistem Benam Baharu.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Password Authenticator tidak mempunyai pilihan konfigurasi tersuai.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Tidak diperlukan perubahan struktur pangkalan data. Akan tetapi, mungkin ada perubahan data.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Terdapat dua jenis butang dalam aplikasi: primer dan sekunder.';
$Definition['The route was saved successfully.'] = 'Laluan berjaya disimpan.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Penerangan tapak biasanya muncul dalam enjin carian. Anda harus cuba mempunyai perihalan sepanjang 100-150 aksara.';
$Definition['The text of the pocket.'] = 'Masukkan teks poket. Ini akan dihasilkan sama seperti yang anda taipkan, jadi pastikan anda memasukkan HTML yang sah.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Ikon sentuh muncul apabila anda menanda halaman tapak web pada skrin utama peranti mudah alih. Ini biasanya 152 piksel.';
$Definition['The user table was not in the import file.'] = 'Jadual pengguna tidak ada dalam fail import.';
$Definition['The Vanilla 2 Exporter'] = 'Pengeksport Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Statistik Vanilla mengubah papan pemuka forum anda menjadi alat pelaporan analitik, yang membolehkan anda menyemak aktiviti di forum anda dalam jangka masa tertentu. Anda boleh <a href="http://vanillaforums.org/docs/vanillastatistics">membaca lebih lanjut mengenai Statistik Vanilla</a> dalam dokumentasi kami.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Mereka berfungsi seperti tema biasa. Setelah dimasukkan ke folder tema, anda boleh mengaktifkannya di sini.';
$Definition['This is a style guide of your theme.'] = 'Ini adalah panduan gaya tema anda. Ia mempunyai contoh elemen visual yang digunakan sepanjang aplikasi. Anda boleh mengklik pelbagai widget seperti Bar Tajuk <0> </0> atau <1> Sepanduk </1> untuk mengedit sifat mereka di panel sisi.';
$Definition['This is the administrative dashboard for your new community.'] = 'Ini adalah papan pemuka pentadbiran untuk komuniti baru anda. Lihat pilihan konfigurasi di sebelah. Dari sana anda dapat mengkonfigurasi bagaimana komuniti anda berfungsi. <b>Secara lalai, hanya pengguna dalam peranan "Pentadbir" yang dapat melihat bahagian komuniti ini.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Di sinilah anda dapat mengaktifkan dan menguji ciri, halaman & komponen Vanilla baru.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Makmal ini tidak boleh dilumpuhkan kerana reka letak tersuai digunakan.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Makmal ini tidak dapat dilumpuhkan kerana diperlukan oleh tema semasa.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Logo ini muncul di bahagian atas tapak anda. Tema yang dibuat dengan editor tema dan beberapa tema tersuai tidak menggunakan tetapan ini.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Ini boleh digunakan untuk memasukkan kandungan seperti nama dan alamat organisasi dalam semua e-mel keluar.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Pilihan ini menunjukkan / menyembunyikan lokasi di mana poket boleh pergi, tetapi hanya untuk pengguna yang mempunyai izin untuk menambah / mengedit poket. Cuba tunjukkan lokasi dan kemudian lawati laman web anda.';
$Definition['This page lists the endpoints of your API.'] = 'Halaman ini menyenaraikan titik akhir API anda. Klik titik akhir untuk maklumat lebih lanjut. Anda boleh membuat panggilan langsung ke API dari halaman ini atau secara luaran menggunakan token akses.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Peranan ini adalah maklumat peribadi. Hanya pengguna yang mempunyai kebenaran untuk melihat maklumat peribadi yang akan melihatnya.';
$Definition['This setting loads the page before executing Javascript.'] = 'Tetapan ini memuat halaman sebelum melaksanakan Javascript yang dapat meningkatkan SEO anda. <br> <strong>** Amaran: Mengaktifkan fitur ini boleh menyebabkan kesalahan Javascript di laman web anda. **</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Tetapan ini memuatkan halaman sebelum melaksanakan Javascript yang boleh meningkatkan SEO anda.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Tema ini tidak dapat dihapus kerana ini adalah tema yang sedang digunakan.';
$Definition['Tiled Layout'] = 'Susun atur berjubin';
$Definition['Title Bar'] = 'Bar Tajuk';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'Untuk memasukkan forum Vanilla ke laman web anda, gunakan kod berikut.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Terlalu banyak alamat! Kami akan menghantar hingga ke alamat %s sekaligus.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'Untuk mengelakkan penyalahgunaan, beberapa alat menyembunyikan kandungan secara automatik dan menyenaraikannya di sini sehingga disetujui secara manual oleh moderator.';
$Definition['TouchIconDescription'] = 'Ikon sentuh muncul apabila anda menandai laman web di skrin utama peranti Apple. Ini biasanya berukuran 152 piksel. Apple menambah sudut bulat dan kesan pencahayaan secara automatik.';
$Definition['Transparent'] = 'Telus';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Sambungan Twitter membolehkan pengguna masuk menggunakan akaun Twitter mereka. <b>Anda mesti mendaftarkan aplikasi anda dengan Twitter agar plugin ini berfungsi.</b>';

$Definition['Usercards'] = 'Kad Pengguna';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Kad pengguna membolehkan anda mendapatkan petikan dalam talian pantas maklumat pengguna. Apabila melihat siaran dan papan pendahulu, klik pada nama pengguna untuk melihat kad yang mempamerkan maklumat profil asas pengguna tanpa perlu menavigasi keluar dari halaman. Dayakan ciri ini untuk menambah kad pengguna pada tema tersuai anda.';
$Definition['User inputs are based on the global background and text colors.'] = 'Input pengguna berdasarkan latar belakang global dan warna teks.';
$Definition['User Profile'] = 'Profil pengguna';
$Definition['Users may sign into your site using their Twitter account.'] = 'Pengguna boleh masuk ke laman web anda menggunakan akaun Twitter mereka.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Gunakan butang di bahagian atas halaman untuk membuat peraturan larangan.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Gunakan pemalam WordPress untuk menyiapkan Komen Vanilla di blog anda, atau gunakan kod universal untuk menyiapkan Komen Vanilla di platform lain.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Perkhidmatan carian baharu Vanila akhirnya di sini. Dayakan UI halaman carian baharu kami untuk mendapatkan akses kepada ciri carian terbaharu seperti Carian Ahli, pengisihan carian dan penyerlahan istilah.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Eksport Vanila: %s, Sumber: %s';
$Definition['Vanilla Labs'] = 'Makmal Vanilla';
$Definition['Vanilla Statistics are currently disabled'] = 'Statistik Vanilla pada masa ini dilumpuhkan';
$Definition['Verify and restore'] = 'Sahkan dan pulihkan';
$Definition['VerifyUser'] = 'Tandai kotak di sebelah pengguna untuk menandainya sebagai <b>Disahkan</b> supaya catatan mereka tidak lagi ditandai sebagai spam. Ini juga akan memulihkan semua catatan mereka yang belum selesai.';
$Definition['Video tutorial on advanced settings'] = 'Tutorial video mengenai tetapan lanjutan';
$Definition['Video tutorial on finding &amp; managing users'] = 'Tutorial video untuk mencari & mengurus pengguna';
$Definition['Video tutorial on managing appearance'] = 'Tutorial video mengenai pengurusan penampilan';
$Definition['Video tutorial on managing categories'] = 'Tutorial video mengenai menguruskan kategori';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Tutorial video mengenai pengurusan peranan & kebenaran';
$Definition['Video tutorial on user registration'] = 'Tutorial video mengenai pendaftaran pengguna';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Amaran: Mengaktifkan fitur ini boleh menyebabkan kesalahan Javascript di laman web anda.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Amaran</b> : Konfigurasi pelayan anda tidak menyokong pemuatan data yang pantas. Sekiranya anda mengimport fail yang sangat besar (mis. Lebih dari 200,000 komen) anda mungkin ingin mempertimbangkan untuk mengubah konfigurasi anda. Klik <a href="http://vanillaforums.com/porter">di sini</a> untuk maklumat lebih lanjut.';
$Definition['Warning: This is for advanced users.'] = '<b>Amaran</b> : Ini untuk pengguna lanjutan dan menghendaki anda membuat perubahan tambahan pada pelayan web anda. Ini biasanya hanya tersedia jika anda mempunyai hosting khusus atau vps. Jangan mencuba ini jika anda tidak tahu apa yang anda lakukan.';
$Definition['Welcome to Labs!'] = 'Selamat Datang ke Makmal!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Selamat datang ke UI bertemakan Vanila. Halaman ini menyenaraikan semua tema anda yang tersedia dan membolehkan anda menyalin atau mengeditnya.';
$Definition['Welcome To Your Theme'] = 'Selamat Datang ke Tema Anda';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Kami mengesyorkan reaksi positif untuk menggalakkan penyertaan.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Apabila didayakan, pengguna boleh memilih untuk menerima pemberitahuan daripada komuniti';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Apabila diaktifkan, anda boleh menguruskan produk, dan mengelompokkan subkomuniti mengikut produk tersebut.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Apabila seseorang berkongsi pautan dari laman web anda, kami mencuba dan mengambil gambar dari halaman. Sekiranya tidak ada gambar di halaman maka kami akan menggunakan gambar ini sebagai gantinya. Gambar mestilah sekurang-kurangnya 50 × 50, tetapi kami mengesyorkan 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Apabila anda memilih Full Bleed, latar belakang anda telus.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Sama ada medan profil dalaman akan disertakan dalam webhook ini atau tidak.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Sama ada atau tidak medan profil peribadi akan disertakan dalam webhook ini.';
$Definition['Which reactions you use really depends on your community.'] = 'Reaksi mana yang anda gunakan bergantung pada komuniti anda, tetapi kami mengesyorkan anda mengingat beberapa perkara.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Anda akan menggunakan pilihan susun atur baru. Ini dapat disesuaikan dan dipratonton menggunakan Editor Tema kami. <0> Ketahui lebih lanjut</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Anda boleh melarang semua pengguna dengan alamat IP yang diawali dengan "111.111.111" dengan menambahkan larangan jenis IP dengan nilai "111.111.111. *".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Anda boleh melarang alamat IP, alamat e-mel dan nama pengguna.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Anda boleh memilih dari salah satu gaya berbeza yang ditawarkan oleh tema ini.';
$Definition['You can configure some values differently for different screensizes.'] = 'Anda boleh mengkonfigurasi beberapa nilai secara berbeza untuk ukuran skrin yang berbeza.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Anda boleh menyambung ke beberapa laman web yang menyokong jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Sekiranya fail anda terlalu besar untuk dimuat naik terus ke halaman ini, anda boleh meletakkannya di folder / muat naik anda. Pastikan nama fail bermula dengan kata <b>eksport</b> dan diakhiri dengan salah satu <b>.txt, .gz</b> .';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Anda boleh menentukan panjang pos minimum untuk mengelakkan jawatan pendek.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Anda boleh memuat naik Font Kustom di Sistem Tema anda. Cukup salin & tampal URL di lapangan.';
$Definition['You must select a file to import.'] = 'Anda mesti memilih fail untuk diimport.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Anda perlu menambahkan domain url font ke <0> Domain yang Dibolehkan </0> dalam konfigurasi laman web. <1> Ketahui lebih lanjut mengenai fon tersuai. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Tema mudah alih anda akan dilumpuhkan. Untuk menetapkan tema mudah alih dan desktop yang berbeza, gunakan UI bertema lama.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Nama organisasi anda digunakan untuk microdata SEO dan JSON + LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Favicon laman web anda muncul di bar tajuk penyemak imbas anda. Ia akan dikurangkan dengan tepat.';
