<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s ได้ยอมรับคำเชิญจาก %4$s สำหรับการเป็นสมาชิก';
$Definition['%1$s changed %4$s permissions.'] = '%1$s แก้ไข %4$s สิทธิ์';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s เปลี่ยน %6$s รูปโปรไฟล์';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s แสดงความคิดเห็น %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s สร้างบัญชีสำหรับ %4$s.';
$Definition['%1$s joined.'] = '%1$s เข้าร่วมแล้ว';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s พูดถึงคุณ %3$s ใน %8$s.';
$Definition['%1$s on %2$s'] = '%1$s ที่ %2$s';
$Definition['%1$s signed in.'] = '%1$s ลงชื่อเข้าใช้แล้ว';
$Definition['%1$s to %2$s'] = '%1$s ถึง %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s ถึง %2$s จาก %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s ปรับปรุง %6$s โปรไฟล์';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s ถูกเพิ่มเข้ามา %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s ถูกลบออกจาก %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s ถูกลบออกจาก %2$s %3$s และเพิ่ม %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s เขียนบน %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s ได้รับการอนุมัติ %2$s สมัครสมาชิก';
$Definition['%3$s created an account for %1$s.'] = '%3$s สร้างบัญชีสำหรับ %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 ไปถึง %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 ไปถึง %s$2 ของ %s$3';
$Definition['%s (Current)'] = '%s (ปัจจุบัน)';
$Definition['%s Agrees'] = '%s เห็นด้วย';
$Definition['%s and you'] = '%s และคุณ';
$Definition['%s Awesomes'] = '%s สุดยอด';
$Definition['%s changed %s\'s permissions.'] = '%1$s แก้ไข %4$s สิทธิ์';
$Definition['%s Comment'] = '%s ความเห็น';
$Definition['%s comment'] = '%s ความคิดเห็น';
$Definition['%s Comments'] = '%s ความเห็น';
$Definition['%s comments'] = '%s ความเห็น';
$Definition['%s Connect'] = '%s ติดต่อ';
$Definition['%s deleted this conversation.'] = '%s ลบการสนทนานี้';
$Definition['%s discussion'] = '%s กระทู้';
$Definition['%s discussions'] = '%s กระทู้';
$Definition['%s has been Jailed.'] = '%s ได้ถูกจำกัดสิทธิ์';
$Definition['%s has left this conversation.'] = '%s ได้ออกจากการสนทนานี้';
$Definition['%s Insightfuls'] = '%s ลึกซึ้ง';
$Definition['%s Likes'] = '%s ถูกใจ';
$Definition['%s LOLs'] = '%s ขำๆ';
$Definition['%s mentioned %s in a %s.'] = '%s ได้พูดถึงคุณ %s ใน %s.';
$Definition['%s message'] = '%s ข้อความ';
$Definition['%s messages'] = '%s ข้อความ';
$Definition['%s New'] = '%s ใหม่';
$Definition['%s new'] = '%s ใหม่';
$Definition['%s new comment since you last read this.'] = '%s ความคิดเห็นใหม่ตั้งแต่ครั้งล่าสุดที่คุณอ่านบทความนี้';
$Definition['%s new comments since you last read this.'] = '%s ความคิดเห็นใหม่ตั้งแต่ครั้งล่าสุดที่คุณอ่านบทความนี้';
$Definition['%s New Plural'] = '%s แบบใหม่';
$Definition['%s new plural'] = '%s ใหม่';
$Definition['%s Not Found'] = '%s ไม่พบ';
$Definition['%s Point'] = '%s คะแนน';
$Definition['%s point'] = '%s คะแนน';
$Definition['%s Points'] = '%s คะแนน';
$Definition['%s points'] = '%s แต้ม';
$Definition['%s said'] = '%s พูดว่า';
$Definition['%s said:'] = '%s พูดว่า:';
$Definition['%s tag(s) found.'] = 'พบ %s Tag';
$Definition['%s tags in the system'] = 'มี %s Tag ในระบบ';
$Definition['%s Up Votes'] = '%s โหวตขึ้น';
$Definition['%s view'] = 'อ่าน %s ครั้ง';
$Definition['%s views'] = 'อ่าน %s ครั้ง';
$Definition['%s votes'] = 'โหวต';
$Definition['%s was removed from the %s and added to the %s'] = '%s โดยนำออก และเพิ่มไปยัง %s';
$Definition['%s WTFs'] = '%s อะไรเนี่ย';

$Definition['(empty message)'] = '(ข้อความว่าง)';

$Definition['+%s Guests'] = '+%s ผู้มาเยือน';

$Definition[' - Page %s'] = ' - หน้า %s';

$Definition['1 message'] = '1 ข้อความ';

$Definition['[%1$s] Membership Approved'] = '[%1$s] สมาชิกได้รับการอนุมัติ';
$Definition['[%s] Welcome Aboard!'] = '[%s] ยินดีต้อนรับ';
$Definition['[Deleted User]'] = '[ผู้ใช้ที่ถูกลบ]';

$Definition['About'] = 'เกี่ยวกับฉัน';
$Definition['Abuse'] = 'ใช้ในทางผิด';
$Definition['Accept'] = 'ยอมรับ';
$Definition['Accept this answer.'] = 'ยอมรับคำตอบนี้';
$Definition['Account Options'] = 'ตั้งค่า';
$Definition['Activate'] = 'เปิดใช้งาน';
$Definition['Active'] = 'มีการใช้งาน';
$Definition['Active Users'] = 'ผู้ใช้งาน';
$Definition['Activity'] = 'ความเคลื่อนไหว';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s ยอมรับ %4$s %8$s';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s แสดงความคิดเห็นใน %8$s ของคุณ';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s แสดงความคิดเห็นใน %8$s ของคุณ';
$Definition['Activity.Comment'] = 'ความคิดเห็น';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s ถูกกล่าวถึง %3$s ใน %8$s';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s ถูกกล่าวถึง %3$s ใน %8$s';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s ถึงคุณ %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s ถึงคุณ %8$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s ได้เข้าร่วมแล้ว';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s ได้เข้าร่วมแล้ว';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s เปลี่ยน %6$s รูปโปร์ไฟล์';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s เปลี่ยน %6$s รูปโปร์ไฟล์';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s ตอบ %4$s %8$s.';
$Definition['Add'] = 'เพิ่ม';
$Definition['Add a Comment'] = 'แสดงความคิดเห็น';
$Definition['Add a Message'] = 'เพิ่มข้อความใหม่';
$Definition['Add another poll option ...'] = 'เพิ่มแบบสำรวจ ...';
$Definition['Add a Profile Picture'] = 'เพิ่มรูปภาพโปรไฟล์';
$Definition['Add a Warning'] = 'เพิ่มคำเตือน';
$Definition['Add Badge'] = 'เพิ่มแบดจ์';
$Definition['Add Comment'] = 'แสดงความคิดเห็น';
$Definition['Add Cost'] = 'เพิ่มค่าใช้จ่าย';
$Definition['Add Image'] = 'เพิ่มรูปภาพ';
$Definition['Add Message'] = 'เพิ่มข้อความใหม่';
$Definition['Add People to this Conversation'] = 'เพิ่มเพื่อนสู่การสนทนานี้';
$Definition['Add Route'] = 'เพิ่มเส้นทาง';
$Definition['Admin'] = 'ผู้ดูแลระบบ';
$Definition['Administrator Activity'] = 'กิจกรรมของผู้ดูแลระบบ';
$Definition['administrators'] = 'ผู้ดูแลระบบ';
$Definition['Advanced Stuff'] = 'ขั้นสูง';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Transport error: %s';
$Definition['Agree'] = 'ยอมรับ';
$Definition['Alert'] = 'เตือน';
$Definition['All %s'] = 'ทั้งหมด %s';
$Definition['All Bookmarks'] = 'บุ๊คมาร์คทั้งหมด';
$Definition['All Categories'] = 'หมวดหมู่ทั้งหมด';
$Definition['All Conversations'] = 'จดหมายทั้งหมด';
$Definition['All Discussions'] = 'กระทู้ทั้งหมด';
$Definition['Allow'] = 'อนุญาต';
$Definition['Allow other members to see your email?'] = 'อนุญาติให้ผู้อื่นเห็นอีเมล์ของคุณ?';
$Definition['All Time Leaders'] = 'ผู้นำโดยรวม';
$Definition['Ancient Membership'] = 'สมาชิกโบราณ';
$Definition['An invitation has already been sent to the email you entered.'] = 'อีเมล์เชิญได้ถูกส่งไปยังอีเมล์ที่คุณใส่แล้ว';
$Definition['Announce'] = 'ประกาศ';
$Definition['Announce...'] = 'ประกาศ...';
$Definition['Announcement'] = 'ประกาศ';
$Definition['Announcements'] = 'ประกาศ';
$Definition['Announce this discussion'] = 'ประกาศกระทู้นี้';
$Definition['Answer'] = 'คำตอบ';
$Definition['answer'] = 'คำตอบ';
$Definition['Answers'] = 'คำตอบ';
$Definition['Applicants'] = 'ผู้สมัคร';
$Definition['Apply Changes'] = 'เปลี่ยนค่า';
$Definition['Apply for Membership'] = 'สมัครสมาชิก';
$Definition['Apply for membership'] = 'สมัครสมาชิก';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'คุณแน่ใจว่าคุณต้องการที่จะดำเนินการนี้ ?';
$Definition['Are you sure you want to delete this %s?'] = 'คุณแน่ใจว่าต้องการที่จะลบ %s ?';
$Definition['Are you sure you want to do that?'] = 'คุณแน่ใจว่าคุณต้องการที่จะทำเช่นนั้น ?';
$Definition['Are you sure you want to do this?'] = 'คุณแน่ใจว่าคุณต้องการที่จะทำเช่นนี้ ?';
$Definition['Are you sure you wish to continue?'] = 'คุณแน่ใจว่าคุณต้องการที่จะดำเนินการต่อ ?';
$Definition['Ask a Question'] = 'ถามคำถาม';
$Definition['Ask Question'] = 'ตั้งกระทู้';
$Definition['Attach a file'] = 'แนบไฟล์';
$Definition['Attachments'] = 'สิ่งที่แนบมา';
$Definition['AttemptingSignOut'] = 'คุณกำลังพยายามที่จะออกจากระบบ คุณแน่ใจว่าคุณต้องการที่จะ %s?';
$Definition['Authenticate URL'] = 'URL ตรวจสอบ';
$Definition['available'] = 'สามารถใช้ได้';
$Definition['Awaiting Moderation'] = 'รอการดูแล';
$Definition['Awesome'] = 'สุดยอด';

$Definition['Back to Discussions'] = 'กลับสู่กระดานสนทนา';
$Definition['Back to Profile'] = 'กลับสู่โปร์ไฟล์';
$Definition['Badge'] = 'แบดจ์';
$Definition['Badge404'] = 'ไม่พบแบดจ์';
$Definition['Badges'] = 'แบดจ์';
$Definition['BadgesModuleTitle'] = 'แบดจ์';
$Definition['BadgesNobody'] = 'ยังไม่มีใครได้รับแบดจ์นี้';
$Definition['Ban'] = 'เเบน';
$Definition['Ban.Action'] = 'เเบน';
$Definition['Banned'] = 'เเบน';
$Definition['Banned for being abusive.'] = 'เเบนเพราะการใช้ที่ไม่เหมาะสม';
$Definition['Banned for spamming.'] = 'เเบนเพราะสแปม';
$Definition['Banned users can no longer access the site.'] = 'ผู้ใช้ที่ไม่ได้รับอนุญาตจะไม่สามารถเข้าใช้งานเว็บไซต์';
$Definition['BanType'] = 'ประเภทของการเเบน';
$Definition['Ban User'] = 'เเบนผู้ใช้';
$Definition['Ban Value'] = 'เเบนค่า';
$Definition['Best Answer'] = 'คำตอบที่ดีที่สุด';
$Definition['Best Answers'] = 'คำตอบที่ดีที่สุด';
$Definition['Best Of'] = 'ที่สุดของ';
$Definition['Best Of...'] = 'ที่สุดของ...';
$Definition['Blank Discussion Topic'] = 'ไม่มีชื่อกระทู้';
$Definition['Blank Message'] = 'ข้อความว่างเปล่า';
$Definition['Body'] = 'เนื้อหา';
$Definition['Bookmark'] = 'บุ๊คมาร์ค';
$Definition['bookmarked discussion'] = 'บุ๊คมาร์คคู่แข่ง';
$Definition['Bookmarked Discussions'] = 'บุ๊คมาร์คกระทู้';
$Definition['Bookmarks'] = 'บุ๊คมาร์ค';
$Definition['bookmarks'] = 'บุ๊คมาร์ค';
$Definition['By'] = 'โดย';
$Definition['by'] = 'โดย';
$Definition['by Date'] = 'โดยวันที่';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'ในการอัพโหลดไฟล์ของคุณจะต้องรับรองว่าคุณมีสิทธิที่จะแจกจ่ายไฟล์ภาพนี้และไม่ได้ละเมิดข้อตกลงในการให้บริการ.';

$Definition['Cancel'] = 'ยกเลิก';
$Definition['Casual'] = 'ไม่เป็นทางการ';
$Definition['Categories'] = 'หมวดหมู่';
$Definition['CategoriesShowFollowed'] = 'แสดงเฉพาะหมวดหมู่ที่ติดตาม';
$Definition['CategoriesShowUnfollowed'] = 'แสดงหมวดหมู่ที่ซ่อนอยู่';
$Definition['CategoriesViewingAll'] = 'คุณกำลังดูทุกหมวดหมู่';
$Definition['CategoriesViewingFollowed'] = 'คุณกำลังดูหมวดหมู่ที่คุณติดตามเท่านั้น';
$Definition['Category'] = 'หมวดหมู่';
$Definition['CategoryID'] = 'หมวดหมู่';
$Definition['Category Management'] = 'การจัดการหมวดหมู่';
$Definition['Category Notifications'] = 'การแจ้งเตือนหมวดหมู่';
$Definition['Category to Use'] = 'หมวดหมู่สำหรับใช้งาน';
$Definition['Change'] = 'เปลี่ยน';
$Definition['Change My Password'] = 'เปลี่ยนรหัสผ่าน';
$Definition['Change My Picture'] = 'เปลี่ยนรูปภาพประจำตัว';
$Definition['Change Password'] = 'เปลี่ยนรหัสผ่าน';
$Definition['Change Picture'] = 'เปลี่ยนรูปประจำตัว';
$Definition['Check all roles that apply to this user:'] = 'ตรวจสอบทุกยศสำหรับผู้ใช้นี้:';
$Definition['Child Categories'] = 'หมวดหมู่ย่อย';
$Definition['Child Categories:'] = 'หมวดหมู่ย่อย:';
$Definition['Choose a name to identify yourself on the site.'] = 'เลือกชื่อที่จะระบุตัวเองในเว็บไซต์';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'เลือกกระทู้หลักซึ่งความเห็นทั้งหมดจะถูกรวม:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'เลือกว่าคุณต้องการที่จะถามคำถามหรือเริ่มกระทู้';
$Definition['Clear'] = 'ล้าง';
$Definition['clear'] = 'ล้าง';
$Definition['Clear Conversation History'] = 'ล้างประวัติการสนทนา';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'คลิก <a href="%s">ที่นี่</a> เพื่อกลับไปยังกระทู้';
$Definition['Click accept or reject beside an answer.'] = 'คลิกยอมรับหรือปฏิเสธข้างคำตอบ';
$Definition['clicking here'] = 'คลิกที่นี่';
$Definition['Click the %s beside discussions to bookmark them.'] = 'คลิก %s ข้างหัวข้อกระทู้เพื่อบุ๊คมาร์ค';
$Definition['Close'] = 'ปิดกระทู้';
$Definition['Closed'] = 'ปิด';
$Definition['Close this discussion'] = 'ปิดกระทู้';
$Definition['Comment'] = 'ความคิดเห็น';
$Definition['comment'] = 'ความเห็น';
$Definition['Comment As ...'] = 'แสดงความคิดเห็นโดย ...';
$Definition['Comment by %s'] = 'ความเห็นโดย %s';
$Definition['Comment in'] = 'ใน';
$Definition['Commenting as %1$s (%2$s)'] = 'แสดงความคิดเห็นด้วย %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'ไม่อนุญาตให้แสดงความคิดเห็น';
$Definition['Comments'] = 'ความคิดเห็น';
$Definition['Comments are between {UserID,you}.'] = 'ความเห็นที่อยู่ระหว่าง {UserID,you}.';
$Definition['Completely delete the warning.'] = 'ลบคำเตือน';
$Definition['Confirm'] = 'ยืนยัน';
$Definition['Confirm Email'] = 'อีเมล์ยืนยัน';
$Definition['Confirm Password'] = 'ยืนยันรหัสผ่าน';
$Definition['Connect'] = 'ต่อ';
$Definition['ConnectAccountExists'] = 'คุณมีบัญชีที่นี่อยู่แล้ว';
$Definition['ConnectChooseName'] = 'เลือกชื่อที่จะระบุตัวคุณในเว็บไซต์';
$Definition['ConnectCreateAccount'] = 'เพิ่มข้อมูล &amp; สร้างบัญชี';
$Definition['ConnectExistingPassword'] = 'ใส่รหัสผ่านของบัญชีของคุณ';
$Definition['Connecting...'] = 'อยู่ระหว่างการเชื่อมต่อ ...';
$Definition['Connection'] = 'เชื่อมต่อ';
$Definition['ConnectLeaveBlank'] = 'ปล่อยว่างไว้ ยกเว้นในกรณีที่ต้องการเชื่อมต่อไปยังบัญชีที่มีอยู่';
$Definition['ConnectName'] = 'ชื่อผู้ใช้';
$Definition['ConnectRegisteredName'] = 'ชื่อผู้ใช้ของคุณ: <strong>%s</strong>';
$Definition['conversation'] = 'การสนทนา';
$Definition['Core'] = 'ส่วนกลาง';
$Definition['Create Discussions'] = 'สร้างกระทู้';
$Definition['Create One.'] = 'สร้างบัญชี.';
$Definition['Current'] = 'ปัจจุบัน';
$Definition['Currently: '] = 'ปัจจุบัน:';
$Definition['Custom Information'] = 'ข้อมูลที่กำหนดเอง';
$Definition['Customize'] = 'ปรับค่า';
$Definition['customize your profile now'] = 'ปรับโปรไฟล์ของคุณ';
$Definition['Customize your Public Profile'] = 'ปรับโปรไฟล์สาธารณะของคุณ';
$Definition['Custom Profile Fields'] = 'ข้อมูลโปรไฟล์ที่กำหนดเอง';
$Definition['Custom Profile Field Settings'] = 'ค่าข้อมูลโปรไฟล์ที่กำหนดเอง';

$Definition['Dashboard'] = 'แผงควบคุม';
$Definition['Dashboard Home'] = 'แผงควบคุมหน้าแรก';
$Definition['Dashboard Summaries'] = 'แผงควบคุมหน้าสรุป';
$Definition['Date'] = 'วันที่';
$Definition['Date Added'] = 'เพิ่มวันที่แล้ว';
$Definition['days'] = 'วัน';
$Definition['Define Thumbnail'] = 'คลิกและลากข้ามภาพเพื่อกำหนดภาพของคุณ';
$Definition['Delete'] = 'ลบ';
$Definition['Delete %s'] = 'ลบ %s';
$Definition['Delete Account'] = 'ลบบัญชี';
$Definition['Delete Conversation'] = 'ลบการสนทนา';
$Definition['Delete Discussion'] = 'ลบกระทู้';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'ลบผู้ใช้และเนื้อหาทั้งหมดของผู้ใช้ ซึ่งจะทำให้เกิดกระทู้ปะติดปะต่อ ราวกับว่าผู้ใช้อื่นมีการตอบสนองไปยังเนื้อหาที่ไม่ได้มี ตัวเลือกนี้เป็นตัวเลือกที่ดีสำหรับการลบเนื้อหาสแปม';
$Definition['Delete User Content'] = 'ลบเนื้อหาของผู้ใช้';
$Definition['Delete User Forever'] = 'ลบผู้ใช้ตลอดกาล';
$Definition['Did this answer the question?'] = 'ตอบคำถามนี้หรือไม่ ?';
$Definition['Disagree'] = 'ไม่เห็นด้วย';
$Definition['Discussion'] = 'กระทู้';
$Definition['discussion'] = 'กระทู้';
$Definition['Discussions'] = 'กระทู้';
$Definition['Discussions Page'] = 'กระดานกระทู้';
$Definition['Discussion Title'] = 'หัวข้อกระทู้';
$Definition['Dislike'] = 'เลิกถูกใจ';
$Definition['Dismiss'] = 'ยกเลิก';
$Definition['Don\'t announce.'] = 'ไม่ประกาศ';
$Definition['Don\'t have an account? %s'] = 'ถ้ายังไม่มีบัญชี? %s';
$Definition['Do you want to expire or delete this warning?'] = 'คุณต้องการที่จะปลดเกษียณหรือลบคำเตือนนี้หรือไม่ ?';
$Definition['Draft saved at %s'] = 'ดราฟท์ได้บันทึกไว้ที่ %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'ปรับขนาดภาพด้านล่างนี้เพื่อกำหนดภาพไอคอนของคุณ';

$Definition['Earned'] = 'ได้รับ';
$Definition['Edit'] = 'แก้ไข';
$Definition['Edit Account'] = 'แก้ไขบัญชี';
$Definition['Edit Comment'] = 'แก้ไขความเห็น';
$Definition['Edit Discussion'] = 'แก้ไขกระทู้';
$Definition['Edit My Account'] = 'แก้ไขบัญชีของคุณ';
$Definition['Edit My Profile'] = 'แก้ไขโปร์ไฟล์';
$Definition['Edit My Thumbnail'] = 'แก้ไขรูปย่อ';
$Definition['Edit Preferences'] = 'แก้ไขข้อมูล';
$Definition['Edit Profile'] = 'แก้ไขข้อมูลส่วนตัว';
$Definition['Edit Tag'] = 'แก้ไข Tag';
$Definition['Edit Thumbnail'] = 'แก้ไขรูปย่อ';
$Definition['Eighth Anniversary'] = 'ครบรอบแปดปี';
$Definition['Email'] = 'อีเมล์';
$Definition['Email/Username'] = 'อีเมล์/ชื่อผู้ใช้';
$Definition['EmailConfirmEmail'] = 'คุณจำเป็นต้องยืนยันที่อยู่อีเมล์ของคุณก่อนที่คุณจะสามารถดำเนินการต่อ กรุณายืนยันที่อยู่อีเมล์ของคุณโดยคลิกที่ลิงค์ต่อไปนี้: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = 'ขอให้มีความสุข!';
$Definition['EmailHeader'] = 'สวัสดี {User.Name}!';
$Definition['EmailInvitation'] = 'สวัสดี!

%1$s ได้เชิญคุณเข้าร่วม %2$s ถ้าคุณต้องการที่จะเข้าร่วมคุณสามารถทำได้โดยคลิกที่ลิงก์นี้

  %3$s';
$Definition['EmailMembershipApproved'] = 'สวัสดี %1$s,

คุณได้รับการอนุมัติให้เป็นสมาชิก เข้าสู่ระบบได้ที่ลิงค์ต่อไปนี้:

  %2$s';
$Definition['EmailNotification'] = '%1$s

ตามลิงค์ด้านล่างเพื่อเช็คดู:
%2$s
';
$Definition['Email Notifications'] = 'แจ้งเตือนทางอีเมล์';
$Definition['Email Or Username'] = 'อีเมล์ หรือ ชื่อผู้ใช้';
$Definition['EmailPassword'] = '%2$s ได้ตั้งค่ารหัสผ่านของคุณใหม่เมื่อ %3$s. รหัสเข้าสู่ระบบของคุณในขณะนี้คือ

  อีเมล์: %6$s
  รหัสผ่าน: %5$s
  Url: %4$s';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'อีเมล์ที่ส่งจากระบบจะได้รับชื่อและที่อยู่อีเมล์ดังนี้';
$Definition['Email Source'] = 'อีเมล์';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
ตามลิงค์ด้านล่างเพื่อเช็คดู:
%2$s';
$Definition['Email Unavailable'] = 'อีเมล์ถูกใช้แล้ว';
$Definition['Email visible to other users'] = 'แสดงอีเมล์สู่สาธารณะ';
$Definition['EmailWelcome'] = '%2$s ได้สร้างบัญชีสำหรับคุณเมื่อ %3$s. รหัสเข้าสู่ระบบของคุณคือ:

  อีเมล์: %6$s
  รหัสผ่าน: %5$s
  Url: %4$s';
$Definition['EmailWelcomeConnect'] = 'คุณเชื่อมต่อกับ {Title} ได้สำเร็จ. นี่คือข้อมูลของคุณ:

  ชื่อผู้ใช้: {User.Name}
  เชื่อมต่อโดย: {ProviderName}

คุณสามารถเข้าใช้งานเว็บไซต์ได้ที่ {/,exurl,domain}.';
$Definition['EmailWelcomeRegister'] = 'คุณประสบความสำเร็จในการลงทะเบียน {Title}. นี่คือข้อมูลรายละเอียดของคุณ:

  ชื่อผู้ใช้: {User.Name}
  อีเมล์: {User.Email}

คุณสามารถเริ่มใช้งานได้ที่ {/,exurl,domain}.';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">อ่านเรื่องเต็มได้ที่นี่</a></p><div class="ClearFix"></div></div>';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">อ่านเรื่องเต็มได้ที่นี่</a></p><div class="ClearFix"></div></div>';
$Definition['English'] = 'ภาษาอังกฤษ';
$Definition['Enter your Email address'] = 'ใส่ที่อยู่อีเมล์ของคุณ';
$Definition['Enter your email address'] = 'ใส่ที่อยู่อีเมล์ของคุณ';
$Definition['Enter your Email address or username'] = 'กรอกอีเมล์ หรือ ชื่อผู้ใช้ของคุณ';
$Definition['Enter Your OpenID Url'] = 'ใส่ที่อยู่ Url OpenID ของคุณ';
$Definition['Erase User Content'] = 'ลบเนื้อหาของผู้ใช้';
$Definition['Error'] = 'ข้อผิดพลาด';
$Definition['ErrorBadInvitationCode'] = 'รหัสคำเชิญที่คุณให้มาไม่ถูกต้อง';
$Definition['ErrorCredentials'] = 'ขออภัย ไม่พบบัญชีที่เกี่ยวข้องกับ อีเมล์ / ชื่อผู้ใช้ และ รหัสผ่าน ที่คุณป้อน';
$Definition['ErrorPermission'] = 'ขออภัย ปฏิเสธการใช้งาน';
$Definition['ErrorPluginDisableRequired'] = 'คุณไม่สามารถปิดการใช้งานปลั๊กอิน {0} เพราะปลั๊กอิน {1} ต้องใช้มันเพื่อที่จะทำงาน';
$Definition['ErrorPluginEnableRequired'] = 'ปลั๊กอินนี้กำหนดว่าปลั๊กอิน {0} จะต้องถูกเปิดใช้งานก่อนที่จะสามารถเปิดการใช้งานตัวเอง';
$Definition['ErrorPluginVersionMatch'] = 'ในการเปิดการใช้งานปลั๊กอิน {0} (เวอร์ชัน {1}) ล้มเหลวเนื่องจากว่าจำเป็นต้องใช้เวอร์ชัน ({2}) เป็นอย่างต่ำ';
$Definition['ErrorRecordNotFound'] = 'ไม่พบบันทึกที่ร้องขอ';
$Definition['ErrorTermsOfService'] = 'คุณต้องยอมรับเงื่อนไขการให้บริการ';
$Definition['everyone'] = 'ทุกคน';
$Definition['Everything'] = 'ทุกอย่าง';
$Definition['Expired'] = 'หมดอายุแล้ว';
$Definition['Expires'] = 'หมดอายุ';

$Definition['Failed to find discussion for commenting.'] = 'ไม่พบกระทู้สำหรับที่ต้องการแสดงความคิดเห็น';
$Definition['Failed to load the poll.'] = 'ไม่สามารถโหลดแบบสำรวจ';
$Definition['Feedback'] = 'ผลตอบรับ';
$Definition['Female'] = 'หญิง';
$Definition['Fifth Anniversary'] = 'ครบรอบห้าปี';
$Definition['FileName'] = 'ชื่อไฟล์';
$Definition['Filename'] = 'ชื่อไฟล์';
$Definition['FileSize'] = 'ขนาดของไฟล์';
$Definition['File Size'] = 'ขนาดไฟล์';
$Definition['First Anniversary'] = 'ครบรอบปีแรก';
$Definition['First Comment'] = 'ความเห็นแรก';
$Definition['Follow'] = 'ติดตาม';
$Definition['Follow %s'] = 'ติดตาม %s';
$Definition['Followed by %d people'] = 'มีผู้ติดตาม %d คน';
$Definition['Followed by %d person'] = 'มีผู้ติดตาม %d คน';
$Definition['Following %d people'] = 'ติดตาม %d คน';
$Definition['Following %d person'] = 'ติดตาม %d คน';
$Definition['Follows'] = 'ติดตาม';
$Definition['Forgot?'] = 'ลืม?';
$Definition['Forgot your password?'] = 'ลืมรหัสผ่าน ?';
$Definition['Format his'] = 'ของเขา';
$Definition['Format their'] = 'ของพวกเขา';
$Definition['Format You'] = 'คุณ';
$Definition['Format you'] = 'คุณ';
$Definition['Format Your'] = 'ของคุณ';
$Definition['Fourth Anniversary'] = 'ครบรอบปีที่สี่';
$Definition['Friends'] = 'เพื่อน';
$Definition['Full Site'] = 'เว็บไซต์เต็มรูปแบบ';

$Definition['Garden.Email.SupportAddress'] = 'ซัพพอร์ทอีเมล์';
$Definition['Garden.Email.SupportName'] = 'ชื่อซัพพอร์ท';
$Definition['Garden.Registration.DefaultRoles'] = 'ยศดีฟอลต์';
$Definition['Garden.Title'] = 'แบนเนอร์ไตเติ้ล';
$Definition['Gender'] = 'เพศ';
$Definition['General'] = 'ทั่วไป';
$Definition['Generate import SQL only'] = 'สร้างการอิมพอตโดย SQL เท่านั้น';
$Definition['Generate Password'] = 'สร้างรหัสผ่าน';
$Definition['Give'] = 'มอบ';
$Definition['Give a Badge to %s'] = 'ให้แบดจ์กับ %s';
$Definition['Give Badge'] = 'ให้แบดจ์';
$Definition['Given'] = 'ให้';
$Definition['Go'] = 'ค้นหา';
$Definition['GuestModule.Message'] = 'ดูเหมือนว่าคุณพึ่งมาที่นี่เป็นครั้งแรก ถ้าคุณต้องการที่จะเข้าร่วมชุมชนออนไลน์ของเรา คลิกปุ่มใดปุ่มหนึ่งเหล่านี้!';

$Definition['Hang on a sec while we sign you out.'] = 'กรุณารอสักครู่ในขณะดำเนินการออกจากระบบ';
$Definition['he'] = 'เขา';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,คุณ} ได้รับแบดจ์ <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} เเบน {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} แสดงความคิดเห็นใน <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} ได้เริ่มกระทู้ใหม่ <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} กล่าวถึงคุณใน <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} เปลี่ยนภาพโปรไฟล์สำหรับ {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} เข้าร่วม';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} ยกเลิกเเบน {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} เตือน {RegardingUserID,you}.';
$Definition['her'] = 'เธอ';
$Definition['Hide'] = 'ซ่อน';
$Definition['Hide signatures?'] = 'ซ่อนลายเซ็น?';
$Definition['Hide signatures always'] = 'ซ่อนลายเซ็นเสมอ';
$Definition['Hide signatures on my mobile device'] = 'ซ่อนลายเซ็นบนมือถือเสมอ';
$Definition['his'] = 'ของเขา';
$Definition['Home'] = 'หน้าหลัก';
$Definition['hours'] = 'ชั่วโมง';
$Definition['Howdy, Stranger!'] = 'สวัสดี, แขกผู้มาเยือน!';
$Definition['How long do you want this warning to last?'] = 'นานแค่ไหนคุณต้องการคำเตือนนี้ไปยังหน้าล่าสุด?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'ข้าพเจ้ายอมรับ <a id="TermsOfService" class="Popup" target="terms" href="%s">ข้อตกลงการให้บริการ</a>';
$Definition['in'] = 'ใน';
$Definition['In <b>%s.</b>'] = 'ใน <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'ใน <b>%s</b> และในกระทู้อื่น ๆเมื่อเร็ว ๆ นี้';
$Definition['Inbox'] = 'กล่องจดหมาย';
$Definition['In seconds'] = 'ในไม่กี่วินาที';
$Definition['Insert Image'] = 'ใส่รูปภาพ';
$Definition['Insightful'] = 'ลึกซึ้ง';
$Definition['Internal'] = 'ภายใน';
$Definition['In this Conversation'] = 'ในการสนทนานี้';
$Definition['Invalid password.'] = 'รหัสผ่านที่คุณป้อนไม่ถูกต้อง อย่าลืมว่าระบบรหัสผ่านจะแบ่งแยกระหว่างตัวอักษรตัวใหญ่และอักษรตัวเล็ก';
$Definition['Invitations'] = 'เชิญ';
$Definition['Invite'] = 'เชิญ';
$Definition['InviteErrorPermission'] = 'ขออภัย ปฏิเสธการดำเนินการ';
$Definition['IPAddress'] = 'หมายเลข IP';
$Definition['IP Address'] = 'หมายเลข IP';
$Definition['I remember now!'] = 'ฉันจำได้แล้ว!';
$Definition['Item'] = 'รายการ';
$Definition['item'] = 'รายการ';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'ดูเหมือนว่าคุณพึ่งมาที่นี่เป็นครั้งแรก ถ้าคุณต้องการที่จะเข้าร่วมชุมชนออนไลน์ของเรา คลิกปุ่มเหล่านี้!';

$Definition['Jail'] = 'จำกัดสิทธิ์';
$Definition['Jailed users have reduced abilities.'] = 'ผู้ใช้ที่ถูกจำกัดสิทธิ์จะไม่สามารถใช้ได้เต็มรูปแบบ';
$Definition['Joined'] = 'เข้าร่วมเมื่อ';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'ลบข้อมูลผู้ใช้แต่เก็บหัวข้อสนทนา,ความคิดเห็นและอื่น ๆของผู้ใช้';
$Definition['Just expire the warning.'] = 'ยกเลิกคำเตือน';
$Definition['Just you!'] = 'เพียงแค่คุณ!';

$Definition['Keep me signed in'] = 'อยู่ในระบบตลอดไป';
$Definition['Keep User Content'] = 'เก็บเนื้อหาของผู้ใช้';

$Definition['Label'] = 'เครื่องหมาย';
$Definition['Last Active'] = 'ใช้งานล่าสุด';
$Definition['Last IP'] = 'ไอพีล่าสุด';
$Definition['Latest %1$s'] = '%1$s ล่าสุด';
$Definition['Latest Post'] = 'โพสต์ล่าสุด';
$Definition['Leaders'] = 'ผู้นำ';
$Definition['Leave a Comment'] = 'ฝากความคิดเห็น';
$Definition['Leave a comment'] = 'ฝากความคิดเห็น';
$Definition['Leave blank unless connecting to an exising account.'] = 'ปล่อยว่างไว้ เว้นแต่จะเชื่อมต่อไปยังบัญชีที่มีอยู่แล้ว';
$Definition['Leave Comments'] = 'ฝากความคิดเห็น';
$Definition['Length'] = 'ความยาว';
$Definition['Level %s'] = 'ระดับ %s';
$Definition['Like'] = 'ถูกใจ';
$Definition['Link to content:'] = 'เชื่อมโยงไปยังเนื้อหา:';
$Definition['Login with Facebook'] = 'เข้าสู่ระบบด้วย Facebook';
$Definition['LOL'] = 'ฮ่า ๆ';

$Definition['Make me invisible? (Will not show you on the list)'] = 'ไม่แสดงตน? (จะไม่แสดงคุณในรายการ)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'ทำให้แบบสำรวจความคิดเห็นนี้ไม่ต้องระบุชื่อผู้ใช้ (การโหวตของผู้ใช้จะไม่แสดงต่อสาธารณะ)';
$Definition['Male'] = 'ชาย';
$Definition['Mark All Viewed'] = 'อ่านทั้งหมดแล้ว';
$Definition['markallviewed'] = 'ทำเครื่องหมายว่าดูแล้วทั้งหมด';
$Definition['Marking as spam cannot be undone.'] = 'การทำเครื่องหมายว่าเป็นสแปมจะทำให้มันถูกลบออกไปตลอดกาล การลบเป็นวิธีที่ดีที่จะทำให้ฟอรั่มของคุณสะอาด';
$Definition['Mark Read'] = 'ทำเครื่องหมายว่าอ่านแล้ว';
$Definition['Merge'] = 'รวม';
$Definition['Merge Discussions'] = 'รวมกระทู้';
$Definition['Message'] = 'ข้อความ';
$Definition['message'] = 'ข้อความ';
$Definition['Messages'] = 'ข้อความ';
$Definition['messages'] = 'ข้อความ';
$Definition['minutes'] = 'นาที';
$Definition['Moderation'] = 'ดูแล';
$Definition['Moderation Queue'] = 'คิวดูแล';
$Definition['Moderator Activity'] = 'ความเคลื่อนไหวของโมเดอเรเตอร์';
$Definition['Moderators'] = 'โมเดอเรเตอร์';
$Definition['moderators'] = 'โมเดอเรเตอร์';
$Definition['months'] = 'เดือน';
$Definition['More'] = 'ต่อไป';
$Definition['More Comments'] = 'ความคิดเห็นต่อไป';
$Definition['More Discussions'] = 'กระทู้ต่อไป';
$Definition['More Information'] = 'ข้อมูลเพิ่มเติม';
$Definition['More Results'] = 'ผลการค้นหาต่อไป';
$Definition['More…'] = 'อื่น ๆ ...';
$Definition['Most Recent'] = 'ล่าสุด';
$Definition['Most recent:'] = 'ล่าสุด:';
$Definition['Most recent: %1$s by %2$s'] = 'ล่าสุด: %1$s โดย %2$s';
$Definition['Most recent by %1$s'] = 'ล่าสุด โดย %1$s';
$Definition['MyBadgesModuleTitle'] = 'แบดจ์ของฉัน';
$Definition['My Bookmarks'] = 'ที่คั่นหน้าของฉัน';
$Definition['My Discussions'] = 'กระทู้ของฉัน';
$Definition['My Drafts'] = 'ดราฟท์ของฉัน';
$Definition['My Forums'] = 'ฟอรั่มของฉัน';
$Definition['My Preferences'] = 'การตั้งค่าของฉัน';

$Definition['n/a'] = 'ไม่มี';
$Definition['Name'] = 'ชื่อ';
$Definition['Name Unavailable'] = 'ชื่อถูกใช้แล้ว';
$Definition['New Conversation'] = 'เขียนจดหมาย';
$Definition['New Discussion'] = 'ตั้งกระทู้';
$Definition['new discussion'] = 'ใหม่';
$Definition['New Message'] = 'เขียนจดหมาย';
$Definition['New Password'] = 'รหัสผ่านใหม่';
$Definition['New Poll'] = 'แบบสำรวจใหม่';
$Definition['Next'] = 'ถัดไป';
$Definition['Ninth Anniversary'] = 'ครบรอบปีที่เก้า';
$Definition['No'] = 'ไม่';
$Definition['NoBadgesEarned'] = 'เกือบแล้ว&hellip;';
$Definition['No badges yet.'] = 'ยังไม่มีแบดจ์';
$Definition['No default roles.'] = 'ไม่มียศดีฟอลต์';
$Definition['No discussions were found.'] = 'ไม่พบกระทู้';
$Definition['No items tagged with %s.'] = 'ไม่มีรายการที่ Tag ด้วย %s';
$Definition['No results for \'%s\''] = 'ไม่มีผลลัพธ์สำหรับ \'%s\'';
$Definition['No Roles'] = 'ไม่มียศ';
$Definition['Not Authorized (401)'] = 'ไม่ได้รับอนุญาต (401)';
$Definition['Not Found (404)'] = 'ไม่พบเนื้อหา (404)';
$Definition['Notification'] = 'แจ้งเตือน';
$Definition['Notification Preferences'] = 'ตั้งค่าการแจ้งเตือน';
$Definition['Notifications'] = 'แจ้งเตือน';
$Definition['Notifictions'] = 'แจ้งเตือน';
$Definition['Notify'] = 'แจ้งเตือน';
$Definition['Notify me of private messages.'] = 'แจ้งเตือนเมื่อมีข้อความส่วนตัว';
$Definition['Notify me when a badge is requested.'] = 'แจ้งเตือนเมื่อมีการร้องขอแบดจ์';
$Definition['Notify me when a comment is flagged.'] = 'แจ้งเตือนเมื่อความคิดเห็นถูก Flag';
$Definition['Notify me when I am added to private conversations.'] = 'แจ้งเตือนเมื่อคุณถูกรวมถึงในการสนทนาส่วนตัว';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'แจ้งเตือนเมื่อมีคนเก็บบุคมาร์กกระทู้ของคุณ';
$Definition['Notify me when people comment on my discussions.'] = 'แจ้งเตือนเมื่อมีคนแสดงความคิดเห็นในกระทู้';
$Definition['Notify me when people mention me.'] = 'แจ้งเตือนเมื่อมีคนพูดถึงฉัน.';
$Definition['Notify me when people mention me in comments.'] = 'แจ้งเตือนเมื่อมีคนพูดถึงคุณในความคิดเห็น';
$Definition['Notify me when people reply to my wall comments.'] = 'แจ้งเตือนเมื่อมีคนตอบกลับความคิดเห็นบนหน้า Wall ของคุณ';
$Definition['Notify me when people write on my wall.'] = 'แจ้งเตือนเมื่อมีคนมาเขียนบนหน้า Wall ของคุณ';
$Definition['Not much happening here, yet.'] = 'ยังไม่มีอะไรเกิดขึ้นที่นี่';
$Definition['Not Verified'] = 'ยังไม่ยืนยัน';

$Definition[' now.'] = 'ขณะนี้';

$Definition['Off Topic'] = 'ออกทะเล';
$Definition['Old Password'] = 'รหัสผ่านเก่า';
$Definition['OldPassword'] = 'รหัสผ่านเก่า';
$Definition['on'] = 'บน';
$Definition['Only show followed categories'] = 'แสดงเฉพาะหมวดหมู่ที่ติดตาม';
$Definition['OpenID Settings'] = 'ตั้งค่า OpenID';
$Definition['Optional Description'] = 'คำอธิบาย';
$Definition['Options'] = 'ออฟชั่น';
$Definition['or'] = 'หรือ';
$Definition['Organize discussion categories'] = 'จัดหมวดหมู่กระทู้';
$Definition['Organize your Categories'] = 'จัดหมวดหมู่ของคุณ';
$Definition['Original'] = 'ต้นฉบับ';
$Definition['Or you can...'] = 'หรือคุณสามารถ...';
$Definition['Other Records'] = 'บันทึกอื่น ๆ';

$Definition['PageDetailsMessage'] = '%1$s ถึง %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s ถึง %2$s ของ %3$s';
$Definition['Page Not Found'] = 'ไม่พบหน้า';
$Definition['PageViews'] = 'จำนวนเยี่ยมชม';
$Definition['ParticipatedHomepageTitle'] = 'กระทู้ที่มีการเข้าร่วม';
$Definition['Password'] = 'รหัสผ่าน';
$Definition['PasswordRequest'] = 'มีคนร้องขอให้รีเซ็ตรหัสผ่านของคุณเมื่อ %2$s. เพื่อรีเซ็ตรหัสผ่านของคุณทำตามลิงค์นี้:

  %3$s

หากคุณไม่ได้ทำการร้องขอ กรุณาไม่ต้องสนใจอีเมล์นี้';
$Definition['Passwords don\'t match'] = 'รหัสผ่านไม่ตรงกัน';
$Definition['Permalink'] = 'ลิงค์ถาวร';
$Definition['permalink'] = 'ลิงค์ถาวร';
$Definition['PermissionErrorMessage'] = 'คุณไม่ได้รับสิทธิ์ที่จะทำสิ่งนี้';
$Definition['PermissionErrorTitle'] = 'สิทธิ์การเข้าถึงปัญหา';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'คุณจะต้องเป็นโมเดอเรเตอร์เพื่อดำเนินการ';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'คุณจะต้องเป็นผู้ดูแลระบบเพื่อดำเนินการ';
$Definition['PermissionRequired.Javascript'] = 'คุณต้องเปิดการใช้งาน javascript เพื่อทำเช่นนั้น';
$Definition['Photogenic'] = 'ถ่ายรูปขึ้น';
$Definition['Picture'] = 'รูปภาพ';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'กรุณารอสักครู่ในขณะที่คุณได้รับการเปลี่ยนจุดหมาย ถ้าคุณไม่ได้รับการเปลี่ยนจุดหมาย คลิกที่ <a href="%s">here</a>.';
$Definition['Poll'] = 'แบบสำรวจ';
$Definition['Poll Options'] = 'ตั้งค่าแบบสำรวจ';
$Definition['Poll Question'] = 'คำถามของแบบสำรวจ';
$Definition['Popular'] = 'ยอดฮิต';
$Definition['Popular Discussions'] = 'กระทู้ยอดฮิต';
$Definition['Popular Tags'] = 'Tag ยอดฮิต';
$Definition['Popup'] = 'ป๊อปอัพ';
$Definition['Position'] = 'ตำแหน่ง';
$Definition['Post'] = 'โพสต์';
$Definition['Post Comment'] = 'แสดงความคิดเห็น';
$Definition['Post Discussion'] = 'ตั้งกระทู้';
$Definition['Post edited by %1$s at %2$s'] = 'โพสต์แก้ไขโดย %1$s เมื่อ %2$s';
$Definition['Posts'] = 'โพสต์';
$Definition['Posts.Plural: %s'] = 'โพสต์: %s';
$Definition['Posts.Singular: %s'] = 'โพสต์: %s';
$Definition['Posts: %s'] = 'โพสต์: %s';
$Definition['Post this anonymously'] = 'โพสต์โดยไม่ระบุชื่อ';
$Definition['PreferenceBadgeEmail'] = 'แจ้งเตือนเมื่อฉันได้รับแบดจ์';
$Definition['PreferenceBadgePopup'] = 'แจ้งเตือนเมื่อฉันได้รับแบดจ์';
$Definition['Preview'] = 'ตัวอย่าง';
$Definition['Previous'] = 'ก่อน';
$Definition['Privacy Settings'] = 'ตั้งค่าความเป็นส่วนตัว';
$Definition['Private Note for Moderators'] = 'ส่งข้อความถึงโมเดอเรเตอร์';
$Definition['Problem with credentials.'] = 'มีปัญหากับข้อมูลเข้าสู่ระบบ';
$Definition['Proceed'] = 'ดำเนินการ';
$Definition['Profile'] = 'โปรไฟล์';
$Definition['Profile Fields'] = 'รายละเอียดข้อมูล';
$Definition['Profile  Fields'] = 'รายละเอียดข้อมูล';
$Definition['ProfileFieldsCustomDescription'] = 'ใช้ฟิลด์เหล่านี้เพื่อสร้างข้อมูลส่วนตัวของคุณ คุณสามารถใส่สิ่งที่ชอบ "สถานะด้านความสัมพันธ์", "Skype" หรือ "ไดโนเสาร์ที่ชอบ" ใช้ความคิดสร้างสรรค์ของคุณ!';
$Definition['Profile Page'] = 'หน้าโปรไฟล์';
$Definition['Profile Picture'] = 'รูปภาพโปรไฟล์';
$Definition['Profiles'] = 'โปรไฟล์';
$Definition['Promote'] = 'เลื่อนขั้น';
$Definition['Public'] = 'สาธารณะ';

$Definition['Q&A'] = 'ถาม&ตอบ';
$Definition['Q&A Answered'] = 'มีคำตอบ';
$Definition['Q&A Options'] = 'ตั้งค่า ถาม&ตอบ';
$Definition['Q&A Question'] = 'คำถาม';
$Definition['QnA Rejected Answer'] = 'คำตอบที่ที่ได้รับการปฏิเสธ';
$Definition['Question'] = 'คำถาม';
$Definition['question'] = 'คำถาม';
$Definition['Question Title'] = 'หัวข้อคำถาม';
$Definition['Quote'] = 'อ้างอิง';
$Definition['Quote Folding'] = 'อ้างอิงจาก';
$Definition['Quote on'] = 'บน';
$Definition['Quote Settings'] = 'ตั้งค่าการอ้างอิง';
$Definition['Quote wrote'] = 'เขียน';

$Definition['Rank'] = 'ระดับ';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were} เลื่อนตำแหน่งเป็น {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = 'ขอแสดงความยินดี คุณได้รับการเลื่อนตำแหน่งให้เป็น {Data.Name,plaintext}.';
$Definition['Reactions'] = 'ปฏิกิริยา';
$Definition['Real Name'] = 'ชื่อจริง';
$Definition['Reason'] = 'เหตุผล';
$Definition['Reason (optional)'] = 'เหตุผล (ตัวเลิอก)';
$Definition['Recent Activity'] = 'ความเคลื่อนไหวล่าสุด';
$Definition['Recent Admin Activity'] = 'ความเคลื่อนไหวล่าสุดของผู้ดูแลระบบ';
$Definition['Recent Discussions'] = 'กระทู้ล่าสุด';
$Definition['recently'] = 'เมื่อเร็ว ๆ นี้';
$Definition['Recent Moderator Activity'] = 'ความเคลื่อนไหวล่าสุดของโมเดอเรเตอร์';
$Definition['Recent Tutorials'] = 'บทเรียนล่าสุด';
$Definition['Recipients'] = 'ผู้รับ';
$Definition['RecipientUserID'] = 'ผู้รับ';
$Definition['Redirecting...'] = 'กำลังเปลี่ยนจุดหมาย...';
$Definition['Refetch Page'] = 'เรียกหน้าใหม่';
$Definition['Register'] = 'สมัครสมาชิก';
$Definition['Register IP'] = 'IP ลงทะเบียน';
$Definition['Register with %s'] = 'สมัครสมาชิก';
$Definition['Registration  Fields'] = 'ข้อมูลลงทะเบียน';
$Definition['Registration URL'] = 'ลงทะเบียน URL';
$Definition['Reject'] = 'ปฎิเสธ';
$Definition['Reject this answer.'] = 'ปฏิเสธคำตอบ';
$Definition['Remember me'] = 'จำฉันไว้';
$Definition['Remember me on this computer'] = 'จำฉันไว้ในคอมพิวเตอร์เครื่องนี้';
$Definition['Remote Configuration'] = 'กำหนดค่า Remote';
$Definition['Removed by'] = 'ถูกลบโดย';
$Definition['Remove My Picture'] = 'ลบรูปภาพของฉัน';
$Definition['Remove Picture'] = 'ลบรูปภาพ';
$Definition['Remove Warning'] = 'ลบคำเตือน';
$Definition['Rename Forum'] = 'เปลี่ยนชื่อฟอรั่ม';
$Definition['Reopen'] = 'เปิดใหม่';
$Definition['Replies'] = 'ตอบกลับ';
$Definition['Reply'] = 'ตอบกลับ';
$Definition['Reported by: '] = 'รายงานโดย:';
$Definition['Request a new password'] = 'ขอรหัสผ่านใหม่';
$Definition['Request a new password →'] = 'ขอรหัสผ่านใหม่ →';
$Definition['Reset Password'] = 'รีเซ็ตรหัสผ่าน';
$Definition['Revoke'] = 'เรียกคืน';
$Definition['Revoked badge.'] = 'เรียกคืนแบดจ์';
$Definition['role'] = 'ยศ';
$Definition['RoleID'] = 'ยศ';
$Definition['Roles'] = 'ยศ';
$Definition['roles'] = 'ยศ';

$Definition['Save'] = 'บันทึก';
$Definition['Save Comment'] = 'บันทึกความเห็น';
$Definition['Save Draft'] = 'บันทึกดราฟท์';
$Definition['Save Poll'] = 'บันทึกแบบสำรวจ';
$Definition['Save Preferences'] = 'บันทึก';
$Definition['Save your password'] = 'บันทึกรหัสผ่านของคุณ';
$Definition['Search'] = 'ค้นหา';
$Definition['SearchBoxPlaceHolder'] = 'ค้นหา';
$Definition['Search for a tag.'] = 'ค้นหาทั้งหมดหรือบางส่วนของ Tag';
$Definition['Search results for \'%s\''] = 'ผลลัพธ์การค้นหาสำหรับ \'%s\'';
$Definition['Second Anniversary'] = 'ครบรอบปีที่สอง';
$Definition['Sections'] = 'ส่วน';
$Definition['Security Check'] = 'ตรวจสอบความปลอดภัย';
$Definition['Select an image on your computer (2mb max)'] = 'เลือกภาพจากคอมพิวเตอร์ของคุณ (สูงสุด 2MB)';
$Definition['Send a New Message'] = 'ส่งข้อความใหม่';
$Definition['Send Message'] = 'ส่งข้อความ';
$Definition['sep and'] = 'และ';
$Definition['Set a New Warning Level'] = 'ตั้งระดับคำเตือนใหม่';
$Definition['Set A Password'] = 'ตั้งรหัสผ่าน';
$Definition['Setting'] = 'ตั้งค่า';
$Definition['Settings'] = 'การตั้งค่า';
$Definition['Seventh Anniversary'] = 'ครบรอบปีที่เจ็ด';
$Definition['Share'] = 'แชร์';
$Definition['Shared Accounts'] = 'บัญชีที่ใช้ร่วมกัน';
$Definition['she'] = 'เธอ';
$Definition['Shown only on mobile'] = 'แสดงเฉพาะบนมือถือ';
$Definition['Show unfollowed categories'] = 'แสดงหมวดหมู่ที่ไม่มีการติดตาม';
$Definition['Sign-In URL'] = 'URL ที่เข้าสู่ระบบ';
$Definition['Sign-Out URL'] = 'URL ที่ออกจากระบบ';
$Definition['Signature Code'] = 'โค๊ดลายเซ็น';
$Definition['Signature invalid.'] = 'ลายเซ็นไม่ถูกต้อง';
$Definition['Signatures'] = 'ลายเซ็น';
$Definition['Signature Settings'] = 'ตั้งค่าลายเซ็น';
$Definition['SignIn'] = 'เข้าสู่ระบบ';
$Definition['Sign In'] = 'เข้าสู่ระบบ';
$Definition['SigningOut'] = 'กรุณารอสักครู่ในขณะดำเนินการออกจากระบบ';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Sign In</a> หรือ <a href="{RegisterUrl,html}">Register</a> เพื่อแสดงความคิดเห็น';
$Definition['Sign in to vote!'] = 'เข้าสู่ระบบเพื่อออกเสียง!';
$Definition['Sign In with %s'] = 'เข้าสู่ระบบด้วย %s';
$Definition['Sign In with Disqus'] = 'เข้าสู่ระบบด้วย Disqus';
$Definition['Sign In with Facebook'] = 'เข้าสู่ระบบด้วยเฟสบุ๊ค';
$Definition['Sign In with Google'] = 'เข้าสู่ระบบด้วย Google';
$Definition['Sign In with OpenID'] = 'เข้าสู่ระบบด้วย OpenID';
$Definition['Sign In with Twitter'] = 'เข้าสู่ระบบด้วย Twitter';
$Definition['Sign Out'] = 'ออกจากระบบ';
$Definition['sign out'] = 'ออกจากระบบ';
$Definition['Sign Up'] = 'สมัครสมาชิก';
$Definition['Sink'] = 'ปล่อยตก';
$Definition['Sink this discussion'] = 'จมกระทู้นี้';
$Definition['Sitemap Settings'] = 'ตั้งค่าแผนผังเว็บไซต์';
$Definition['Sixth Anniversary'] = 'ครบรอบปีที่หก';
$Definition['somebody'] = 'บางคน';
$Definition['Some Code'] = 'Code บางอย่าง';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'มีคนตอบคำถามของคุณ คุณจำเป็นต้องยอมรับ / ปฏิเสธคำตอบ';
$Definition['sorted by'] = 'เรียงลำดับตาม';
$Definition['Source:'] = 'ที่มา:';
$Definition['Spam'] = 'สแปม';
$Definition['Spam Queue'] = 'คิวสแปม';
$Definition['Split'] = 'แยก';
$Definition['Split Comments'] = 'แยกความเห็น';
$Definition['Spoiler'] = 'แสดงเนื้อหา';
$Definition['Spoof User'] = 'ผู้ใช้ที่ได้ปลอมแปลงหมายเลข IP';
$Definition['Start'] = 'เริ่ม';
$Definition['Start a New Conversation'] = 'เขียนจดหมาย';
$Definition['Start a New Discussion'] = 'ตั้งกระทู้ใหม่';
$Definition['Start Conversation'] = 'ส่งจดหมาย';
$Definition['Started By'] = 'เริ่มโดย';
$Definition['Started by %1$s'] = 'เริ่มโดย %1$s';
$Definition['Start your First Discussion'] = 'เริ่มกระทู้แรกของคุณ';
$Definition['Stop following'] = 'หยุดติดตาม';
$Definition['Strip images out of signatures'] = 'ตัดภาพจากลายเซ็น';
$Definition['Strip images out of signatures?'] = 'ตัดภาพออกจากลายเซ็น ?';
$Definition['Suggested Value'] = 'ค่าที่แนะนำ';

$Definition['Tagged'] = 'Tag';
$Definition['Tagged with '] = 'Tag ด้วย';
$Definition['Tagged with "%s"'] = 'Tag ด้วย %s';
$Definition['Tagging'] = 'Tag';
$Definition['Tag Name'] = 'ชื่อ Tag';
$Definition['Tags'] = 'Tag';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Tag คือคำสำคัญที่ผู้ใช้สามารถกำหนดให้กับกระทู้ที่จะช่วยจัดหมวดหมู่กระทู้';
$Definition['Take Action'] = 'ดำเนินการ';
$Definition['Take Action:'] = 'ดำเนินการ:';
$Definition['Target'] = 'เป้าหมาย';
$Definition['Tell the user why you\'re warning them'] = 'บอกผู้ใช้เกี่ยวกับการตักเตือน';
$Definition['Tell us why you want to join!'] = 'บอกเราทำไมคุณถึงต้องการเข้าร่วม!';
$Definition['Tenth Anniversary'] = 'ครบรอบปีที่สิบ';
$Definition['TermsOfService'] = 'เงื่อนไขการให้บริการ';
$Definition['Terms of Service'] = 'เงื่อนไขการให้บริการ';
$Definition['TermsOfServiceText'] = '
   <p>You agree, through your use of this service, that you will not use this
   community to post any material which is knowingly false and/or defamatory,
   inaccurate, abusive, vulgar, hateful, harassing, obscene, profane, sexually
   oriented, threatening, invasive of a person\'s privacy, or otherwise violative
   of any law. You agree not to post any copyrighted material unless the
   copyright is owned by you.</p>
   
   <p>We at this community also reserve the right to reveal your identity (or
   whatever information we know about you) in the event of a complaint or legal
   action arising from any message posted by you. We log all internet protocol
   addresses accessing this web site.</p>
   
   <p>Please note that advertisements, chain letters, pyramid schemes, and
   solicitations are inappropriate on this community.</p>
   
   <p>We reserve the right to remove any content for any reason or no reason at
   all. We reserve the right to terminate any membership for any reason or no
   reason at all.</p>
   
   <p>You must be at least 13 years of age to use this service.</p>
';
$Definition['Text  Max  Length'] = 'ความยาวข้อความสูงสุด';
$Definition['The conversation has been cleared.'] = 'การสนทนาได้รับการลบ';
$Definition['The email you entered in use by another member.'] = 'อีเมล์ที่คุณใส่ได้มีการใช้งานโดยสมาชิกคนอื่นแล้ว';
$Definition['The email you have entered is already related to an existing account.'] = 'อีเมล์ที่คุณใส่มีการเกี่ยวข้องกับบัญชีที่มีอยู่แล้ว';
$Definition['The file failed to upload.'] = 'อัปโหลดไฟล์ล้มเหลว';
$Definition['their'] = 'ของพวกเขา';
$Definition['The name you entered is already in use by another member.'] = 'ชื่อที่คุณใส่ได้ใช้งานโดยสมาชิกคนอื่นแล้ว';
$Definition['The page you were looking for could not be found.'] = 'หน้าที่คุณกำลังหาไม่มีอยู่';
$Definition['The quote had to be converted from %s to %s.'] = 'คำอ้างอิงได้รับการดัดแปลงมาจาก %s ไปสู่ %s การจัดรูปแบบบางอย่างอาจจะไม่สมบูรณ์';
$Definition['There are no tags in the system yet.'] = 'ยังไม่มี Tag ในระบบ';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'ค่า reCAPTCHA ไม่ได้รับการป้อนอย่างถูกต้อง โปรดลองอีกครั้ง';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'มีบัญชีที่มีชื่อผู้ใช้เดียวกัน (%1$s) หรือ อีเมล์ (%2$s) เดียวกันอยู่แล้ว คุณสามารถสร้างบัญชีผู้ใช้ใหม่หรือคุณสามารถเข้าสู่ระบบโดยป้อนข้อมูลของคุณที่มีอยู่แล้ว';
$Definition['The response was not in the correct format.'] = 'การตอบสนองที่ไม่ได้อยู่ในรูปแบบถูกต้อง';
$Definition['There was an error connecting to Disqus'] = 'ไม่สามารถเชื่อมต่อกับ Disqus';
$Definition['There was an error connecting to Facebook'] = 'ไม่สามารถเชื่อมต่อกับ Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'ไม่สามารถอัปโหลดไฟล์ เป็นไปได้มากที่สุดว่าไฟล์มีขนาดใหญ่เกินไป';
$Definition['The site is currently undergoing maintenance.'] = 'เว็บไซต์กำลังอยู่ระหว่างการบำรุง';
$Definition['The uploaded file was too big (max %s).'] = 'อัพโหลดไฟล์มีขนาดใหญ่เกินไป (สูงสุด %s)';
$Definition['they'] = 'พวกเขา';
$Definition['Third Anniversary'] = 'ครบรอบปีที่สาม';
$Definition['This answer was %s.'] = 'คำตอบนี้เป็น %s';
$Definition['This answer was Accepted.'] = 'คำตอบนี้ได้รับการยอมรับ';
$Definition['This discussion has been closed.'] = 'กระทู้นี้ถูกปิด';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'กระทู้นี้มีความเกี่ยวข้องกับแหล่งเนื้อหาภายนอก';
$Definition['This discussion was created from comments split from: %s.'] = 'กระทู้นี้ถูกสร้างขึ้นจากความเห็นที่แยกมาจาก: %s.';
$Definition['This discussion was merged into %s'] = 'กระทู้นี้ถูกรวมเข้าไปกับ %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'ภาพนี้ได้รับการปรับขนาดให้พอดีกับหน้า คลิกที่นี่เพื่อขยายขนาดรูป';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'นี่เป็นโพลปิด: จะไม่มีใครเห็นว่าคุณคุณโหวตอะไร';
$Definition['This is a public poll: others will see what you voted for.'] = 'นี่เป็นโพลเปิด: ทุกคนจะเห็นว่าคุณคุณโหวตอะไร';
$Definition['This is a system account and does not represent a real person.'] = 'นี้เป็นบัญชีของระบบและไม่ได้เป็นบัญชีตัวแทนของคนจริง';
$Definition['This Month\'s Leaders'] = 'ผู้นำเดือนนี้';
$Definition['This question\'s answer has been accepted.'] = 'คำตอบของคำถามนี้ได้รับการยอมรับแล้ว';
$Definition['This user has been verified as a non-spammer.'] = 'ผู้ใช้รายนี้ได้ผ่านการยืนยันเรียบร้อยไม่ใช้สแปม';
$Definition['This user has not been verified as a non-spammer.'] = 'ผู้ใช้รายนี้ได้ผ่านการยืนยันเรียบร้อยว่าไม่ใช่สแปม';
$Definition['This user has not commented yet.'] = 'ผู้ใช้นี้ยังไม่ได้แสดงความคิดเห็นใด ๆ';
$Definition['This user has not made any discussions yet.'] = 'ผู้ใช้นี้ไม่ได้มีกระทู้ใด ๆ';
$Definition['This user is verified as a non-spammer'] = 'ผู้ใช้รายนี้ได้ผ่านการยืนยันเรียบร้อยไม่ใช้สแปม';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'คำเตือนนี้ได้หมดอายุแล้ว คุณต้องการที่จะลบมันได้หรือไม่ ?';
$Definition['This Week\'s Leaders'] = 'ผู้นำประจำสัปดาห์นี้';
$Definition['Thumbnail'] = 'รูปย่อ';
$Definition['Title'] = 'ชื่อเรื่อง';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'ถ้าต้องการส่งอีเมล์ยืนยันอีกครั้ง คลิก <a href="%s">here</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'จะใช้ reCAPTCHA คุณต้องได้รับ API คีย์จาก %s';
$Definition['Transport error: %s'] = 'เกิดข้อผิดพลาดในขณะที่การประมวลผลคำร้องขอ <br /> เซิร์ฟเวอร์ตอบสนองต่อไปนี้: %s';
$Definition['Troll'] = 'สร้างดราม่า';
$Definition['Turn ON'] = 'เปิด';
$Definition['Twitter Settings'] = 'ตั้งค่า Twitter';
$Definition['Type'] = 'Condition Type';

$Definition['Unannounce'] = 'ยกเลิกประกาศ';
$Definition['Unanswered'] = 'ยังไม่มีคำตอบ';
$Definition['Unanswered Questions'] = 'ยังไม่มีคำตอบ';
$Definition['unavailable'] = 'ไม่อยู่';
$Definition['Unban User'] = 'ยกเลิกเเบนผู้ใช้';
$Definition['Unbookmark'] = 'ยกเลิกบุ๊คมาร์ค';
$Definition['Undefined discussion body.'] = 'เนื้อหากระทู้ไม่ได้กำหนด';
$Definition['Undefined discussion subject.'] = 'หัวข้อกระทู้ไม่ได้กำหนด';
$Definition['Undefined foreign content'] = 'เนื้อหาจากภายนอกที่ยังไม่ได้ยืนยัน';
$Definition['Undo Follow'] = 'ยกเลิกติดตาม';
$Definition['Unfollow'] = 'ยกเลิกติดตาม';
$Definition['Unhide'] = 'ยกเลิกการซ่อน';
$Definition['Unknown'] = 'ไม่ทราบ';
$Definition['Unknown client: %s.'] = 'Client ที่ไม่รู้จัก: %s';
$Definition['Unread'] = 'ยังไม่ได้อ่าน';
$Definition['Unread Discussions'] = 'กระทู้ที่ยังไม่ได้อ่าน';
$Definition['Unspecified'] = 'ยังไม่ระบุ';
$Definition['Update'] = 'อัพเดท';
$Definition['Updated badge'] = 'อัพเดทแบดจ์';
$Definition['Upload'] = 'อัพโหลด';
$Definition['Uploading...'] = 'กำลังอัพโหลด...';
$Definition['Url'] = 'URL';
$Definition['Use My Current Password'] = 'ใช้รหัสผ่านปัจจุบันของฉัน';
$Definition['User "%s" does not exist.'] = 'ไม่มีผู้ใช้ "%s"';
$Definition['Username'] = 'ชื่อผู้ใช้';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'ชื่อผู้ใช้สามารถมี ตัวอักษร ตัวเลข และ ขีด เท่านั้น';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'ชื่อผู้ใช้สามารถมี ตัวอักษร ตัวเลข และ ขีดเท่านั้น และจะต้องอยู่ระหว่าง 3 ถึง 20 ตัวอักษร';
$Definition['UsernameError'] = 'ชื่อผู้ใช้ต้องประกอบด้วยม ตัวอักษร ตัวเลข ขีด และต้องมีความยาวอยู่ระหว่าง 3 และ 20 ตัวอักษร';
$Definition['Username or email'] = 'ชื่อผู้ใช้หรืออีเมล์';
$Definition['User not found.'] = 'ขออภัยไม่พบบัญชีที่เกี่ยวข้องกับ อีเมล์ / ชื่อผู้ใช้ ที่คุณป้อน';
$Definition['Users Count'] = 'จำนวนผู้ใช้งาน';

$Definition['ValidateBanned'] = '%s ไม่ได้รับอนุญาต';
$Definition['ValidateBoolean'] = '%s ไม่ได้เป็น boolean ที่ถูกต้อง';
$Definition['ValidateConnection'] = 'พารามิเตอร์การเชื่อมต่อที่คุณระบุล้มเหลวในการเปิดการเชื่อมต่อไปยังฐานข้อมูล ฐานข้อมูลที่มีการรายงานข้อผิดพลาดต่อไปนี้ <code>%s</code>';
$Definition['ValidateDate'] = '%s ไม่ใช่วันที่ที่ถูกต้อง';
$Definition['ValidateDecimal'] = '%s ไม่ได้เป็นทศนิยมที่ถูกต้อง';
$Definition['ValidateEmail'] = '%s ไม่ปรากฏที่จะถูกต้อง';
$Definition['ValidateEnum'] = '%s ไม่ถูกต้อง';
$Definition['ValidateFormat'] = 'ไม่อนุญาตให้โพสต์ html';
$Definition['ValidateInteger'] = '%s ไม่ได้เป็นจำนวนเต็มถูกต้อง';
$Definition['ValidateIntegerArray'] = '%s ต้องเป็นรายการตัวเลขที่คั่นด้วยจุลภาค';
$Definition['ValidateLength'] = '%1$s มี %2$s ตัวอักษรยาวเกินไป';
$Definition['ValidateMatch'] = ' %s ฟิลด์ไม่ตรงกัน';
$Definition['ValidateMinimumAge'] = 'ตรวจสอบอายุขั้นต่ำ';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'คุณต้องเลือกอย่างน้อยหนึ่ง %s.';
$Definition['ValidateRegex'] = '%s ไม่ปรากฏที่จะอยู่ในรูปแบบถูกต้อง';
$Definition['ValidateRequired'] = 'กรุณาตรวจสอบช่องว่าง';
$Definition['ValidateRequiredArray'] = 'คุณต้องเลือกอย่างน้อยหนึ่ง %s.';
$Definition['ValidateTag'] = 'Tag ไม่สามารถมีช่องว่าง';
$Definition['ValidateTime'] = '%s ไม่ได้เป็นเวลาที่ถูกต้อง';
$Definition['ValidateTimestamp'] = '%s ไม่ได้เป็นเวลาที่ถูกต้อง';
$Definition['ValidateUrlStringRelaxed'] = '%s ห้ามใช้ เครื่องหมายทับ อ้างอิงข้อความ หรือ Tag';
$Definition['ValidateUsername'] = 'ชื่อผู้ใช้จะต้องมี 3-20 ตัวอักษรและประกอบด้วยตัวอักษร ตัวเลข และ ขีด';
$Definition['ValidateVersion'] = '%s ไม่ได้เป็นเวอร์ชั่นที่ถูกต้อง โปรดดู php ฟังก์ชัน version_compare() สำหรับตัวอย่างของเวอร์ชั่นที่ถูกต้อง';
$Definition['Vanilla'] = 'วานิลลา';
$Definition['Vanilla Statistics'] = 'สถิติวานิลลา';
$Definition['Vanilla Statistics Plugin'] = 'สถิติวานิลลาปลั๊กอิน';
$Definition['Verified'] = 'ยืนยันแล้ว';
$Definition['Verifying your credentials...'] = 'กำลังตรวจสอบข้อมูลของคุณ ...';
$Definition['via %s'] = 'ผ่านทาง %s';
$Definition['View Badge'] = 'ดูแบดจ์';
$Definition['Views'] = 'อ่าน';
$Definition['Visible'] = 'มองเห็นได้';
$Definition['Visits'] = 'เข้าชม';
$Definition['Visit Site'] = 'ชมหน้าเว็บ';
$Definition['Vote'] = 'โหวต';
$Definition['Vote Down'] = 'โหวตลง';
$Definition['Votes'] = 'โหวต';
$Definition['Vote Up'] = 'โหวตขึ้น';

$Definition['wall'] = 'หน้า Wall';
$Definition['Want to take part in this discussion? Click one of these:'] = 'ต้องการมีส่วนร่วมกระทู้นี้ คลิก:';
$Definition['Warn'] = 'เตือน';
$Definition['Warning'] = 'คำเตือน';
$Definition['Warnings'] = 'คำเตือน';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} เตือน {WarnUserID,User} เพราะ {Points,plural,%s points}.';
$Definition['WarningTitleFormat.Notice'] = '{InsertUserID,User} เตือน {WarnUserID,User} เพราะ {Points,plural,%s points} (แจ้งให้ทราบ).';
$Definition['was'] = 'ได้';
$Definition['Website'] = 'เว็บไซต์';
$Definition['weeks'] = 'สัปดาห์';
$Definition['Welcome Aboard!'] = 'ยินดีต้อนรับ';
$Definition['were'] = 'ได้';
$Definition['Where do you want to announce this discussion?'] = 'คุณต้องการที่จะประกาศกระทู้นี้ที่ไหน';
$Definition['Who\'s Online'] = 'มีใครออนไลน์';
$Definition['Whos Online'] = 'มีใครออนไลน์';
$Definition['Why are you Banning this user?'] = 'ทำไมคุณเเบนใช้นี้ ?';
$Definition['Write a comment'] = 'เขียนความคิดเห็น';
$Definition['Write Comment'] = 'เขียนความคิดเห็น';
$Definition['Write something about yourself...'] = 'เขียนอธิบายสั้นๆเกี่ยวกับตัวเอง...';
$Definition['WTF'] = 'อะไรเนี่ย';

$Definition['Yes'] = 'ใช่';
$Definition['You'] = 'คุณ';
$Definition['you'] = 'คุณ';
$Definition['You\'ve been Jailed.'] = 'คุณได้ถูกจำกัดสิทธิ์';
$Definition['You already have an account here.'] = 'คุณมีบัญชีที่นี่แล้ว';
$Definition['You are about to ban {User.UserID,user}.'] = 'คุณกำลังจะเเบน {User.UserID,user}';
$Definition['You are about to unban {User.UserID,user}.'] = 'คุณกำลังจะยกเลิกเเบน {User.UserID,user}';
$Definition['You are connected as %s through %s.'] = 'คุณเชื่อมต่อด้วย %s ผ่าน %s';
$Definition['You are connected through %2$s.'] = 'คุณเชื่อมต่อผ่าน %2$s';
$Definition['You are currently only viewing categories that you follow.'] = 'คุณเห็นหมวดหมู่ที่คุณติดตามเท่านั้น';
$Definition['You are currently viewing all categories.'] = 'คุณเห็นทุกหมวดหมู่';
$Definition['You are editing %s\'s signature'] = 'คุณกำลังแก้ไขลายเซ็นของ %s';
$Definition['You can either ask a question or start a discussion.'] = 'คุณสามารถถามคำถาม หรือ เริ่มต้นกระทู้ก็ได้ โปรดเลือกอย่างใดอย่างหนึ่งด้านล่าง';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'คุณสามารถปฏิบัติตามหมวดหมู่ของแต่ละบุคคลและได้รับการแจ้งจากโพสทั้งหมดภายในพวกเขา';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'คุณไม่สามารถแก้ไขภาพโปร์ไฟล์ที่มีการเชื่อมโยงจากภายนอก';
$Definition['You can only specify up to %s tags.'] = 'คุณสามารถระบุ Tag สูงสุดได้ % s แท็ก';
$Definition['You can use HTML in your signature.'] = 'คุณสามารถใช้ <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Html ธรรมดา</a></b> ในลายเซ็นของคุณ';
$Definition['You don\'t have permission to do that.'] = 'คุณไม่ได้รับอนุญาตให้ทำเช่นนั้น';
$Definition['You do not have any %s yet.'] = 'คุณยังไม่ได้รับ %s ใดๆ';
$Definition['You do not have any bookmarks.'] = 'คุณไม่มีบุ๊คมาร์คใดๆ';
$Definition['You do not have any conversations.'] = 'คุณไม่ได้รับข้อความใดๆ';
$Definition['You do not have any drafts.'] = 'คุณไม่มีดราฟท์ใดๆ';
$Definition['You do not have any notifications yet.'] = 'คุณยังไม่ได้รับการแจ้งเตือนใด ๆ';
$Definition['You do not have enough invitations left.'] = 'คุณไม่มีบัตรเชิญเหลือแล้ว';
$Definition['You do not have permission to write new comments.'] = 'คุณไม่ได้รับอนุญาตที่จะเขียนความคิดเห็นใหม่';
$Definition['YouEarnedBadge'] = 'คุณได้รับแบดจ์นี้';
$Definition['You have answered questions'] = 'คุณได้ตอบคำถาม';
$Definition['You have entered an invalid discussion title'] = 'คุณใส่ชื่อหัวข้อกระทู้ที่ไม่ถูกต้อง';
$Definition['You haven\'t read this yet.'] = 'คุณยังไม่ได้อ่านบทความนี้';
$Definition['You have not started any discussions.'] = 'คุณยังไม่ได้เริ่มกระทู้าใด ๆ';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'คุณได้โพสต์ %1$s ครั้งภายใน %2$s วินาที บล็อกสแปมขณะนี้มีผลในบัญชีของคุณ คุณต้องรออย่างน้อย %3$s วินาทีก่อนที่จะโพสต์ได้อีกครั้ง';
$Definition['You have selected %1$s.'] = 'คุณได้เลือก %1$s';
$Definition['You have selected %1$s in this discussion.'] = 'คุณได้เลือก %1$s ในกระทู้นี้';
$Definition['You have to select at least 2 discussions to merge.'] = 'คุณจะต้องเลือกอย่างน้อย 2 กระทู้ที่จะรวม';
$Definition['You must agree to the terms of service.'] = 'คุณต้องยอมรับเงื่อนไขการให้บริการ';
$Definition['You need to confirm your email address.'] = 'คุณต้องยืนยันตัวเองผ่านอีเมล์ที่เราส่งไป คลิ๊ก <a href="{/entry/emailconfirmrequest,url}">ที่นี่</a> เพื่อส่งอีเมลยืนยันอีกครั้ง';
$Definition['You need to sign in before you can do this.'] = 'คุณจำเป็นต้องเข้าสู่ระบบก่อน';
$Definition['your'] = 'ของคุณ';
$Definition['Your changes have been saved.'] = 'การเปลี่ยนแปลงของคุณได้รับการบันทึกแล้ว';
$Definition['Your changes have been saved successfully.'] = 'การเปลี่ยนแปลงค่าของคุณถูกบันทึกเรียบร้อยแล้ว';
$Definition['Your changes were saved.'] = 'การเปลี่ยนแปลงค่าของคุณถูกบันทึกแล้ว';
$Definition['Your email has been successfully confirmed.'] = 'อีเมล์ของคุณได้รับการยืนยันเรียบร้อยแล้ว';
$Definition['Your invitation has been sent.'] = 'คำเชิญของคุณได้ถูกส่งไปแล้ว';
$Definition['Your old password was incorrect.'] = 'รหัสผ่านเก่าของคุณไม่ถูกต้อง';
$Definition['Your password has been changed.'] = 'รหัสผ่านของคุณได้มีการเปลี่ยนแปลง';
$Definition['Your picture has been removed.'] = 'ภาพของคุณได้ถูกลบออก';
$Definition['Your post will appear once it\'s been approved.'] = 'โพสต์ของคุณจะปรากฏเมื่อมีการได้รับการอนุมัติ';
$Definition['Your preferences have been saved.'] = 'การตั้งค่าของคุณถูกบันทึกแล้ว';
$Definition['Your private conversations with other members.'] = 'การสนทนาส่วนตัวของคุณกับสมาชิกคนอื่น';
$Definition['Your registered username: <strong>%s</strong>'] = 'ชื่อผู้ใช้ของคุณ: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'คำขอของคุณได้ถูกส่งไปแล้ว ตรวจสอบอีเมล์ของคุณสำหรับการดำเนินการขั้นตอนต่อไป';
$Definition['Your settings have been saved.'] = 'การตั้งค่าของคุณถูกบันทึกแล้ว';
$Definition['Your settings have been saved successfully.'] = 'การตั้งค่าของคุณถูกบันทึกแล้วเรียบร้อยแล้ว';
$Definition['Your warning was added.'] = 'คำเตือนของคุณถูกบันทึกแล้ว';

$Definition[' You should '] = 'คุณควร';

$Definition['You were added to a conversation.'] = '{InsertUserID,user} ได้รวม {NotifyUserID,you} ที่ <a href="{Url,htmlencode}">การสนทนา</a>.';

$Definition['↳ No results for \'%s\''] = 'ไม่มีผลลัพธ์การค้นหาสำหรับ \'%s\'';
$Definition['↳ Search results for \'%s\''] = 'ผลลัพธ์การค้นหาสำหรับ \'%s\'';
$Definition['↳ Show All'] = 'แสดงทั้งหมด';
