<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s hyv&auml;ksyi j&auml;senen %4$s kutsun palstalle.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s vaihtoi j&auml;senen %4$s k&auml;ytt&auml;j&auml;oikeuksia.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s vaihtoi %6$s profiilikuvan.';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s kommentoi %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s loi tunnuksen k&auml;ytt&auml;j&auml;lle %4$s.';
$Definition['%1$s joined.'] = '%1$s liittyi.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s mainitsi j&auml;senen %3$s keskustelussa %8$s.';
$Definition['%1$s on %2$s'] = '%1$s kohteessa %2$s ';
$Definition['%1$s signed in.'] = '%1$s kirjautui sis&auml;&auml;n.';
$Definition['%1$s to %2$s'] = '%1$s - %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s - %2$s / %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s p&auml;ivitti %6$sn profiilin.';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s lis&auml;ttiin %2$s %3$s.';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s poistettiin kohteesta %2$s %3$s. ';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s poistettiin kohteesta %2$s %3$s ja lisättiin kohteeseen %4$s %5$s. ';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s kirjoitti %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s hyv&auml;ksyi j&auml;senen %2$s rekister&ouml;itymisen.';
$Definition['%3$s created an account for %1$s.'] = '%3$s loi k&auml;ytt&auml;j&auml;tilin j&auml;senelle %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 - %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 - %s$2 / %s$3';
$Definition['%s (Current)'] = '%s (Nykyinen)';
$Definition['%s Agrees'] = '%s hyv&auml;ksynt&auml;&auml;';
$Definition['%s and you'] = '%s ja sin&auml;';
$Definition['%s Awesomes'] = '%s mielest&auml; loistava vastaus';
$Definition['%s by %s'] = '%s kohteelta %s';
$Definition['%s changed %s\'s permissions.'] = '%s muutti j&auml;senen %s oikeuksia.';
$Definition['%s Comment'] = '%s kommentti';
$Definition['%s comment'] = '%s viesti';
$Definition['%s comment html'] = '%s viesti';
$Definition['%s Comments'] = '%s kommenttia';
$Definition['%s comments'] = '%s viesti&auml;';
$Definition['%s comments html'] = '%s viesti&auml;';
$Definition['%s Connect'] = '%s Liitä';
$Definition['%s day'] = '%s päivä';
$Definition['%s days'] = '%s päivää';
$Definition['%s deleted this conversation.'] = '%s poisti t&auml;m&auml;n keskustelun.';
$Definition['%s discussion'] = '%s keskustelu';
$Definition['%s discussion html'] = '%s keskustelu';
$Definition['%s discussions'] = '%s keskustelua';
$Definition['%s discussions html'] = '%s keskustelua';
$Definition['%s has been Jailed.'] = '%s on laitettu j&auml;&auml;hylle.';
$Definition['%s has created an account for you at %s.'] = '%s on luonut sinulle %s käyttäjätilin.';
$Definition['%s has invited you to join %s.'] = '%s on kutsunut sinut liittymään %s -jäseneksi.';
$Definition['%s has left this conversation.'] = '%s poistui t&auml;st&auml; keskustelusta.';
$Definition['%s has reset your password at %s.'] = '%s on uusinut %s salasanasi.';
$Definition['%s hour'] = '%s tunti';
$Definition['%s hours'] = '%s tuntia';
$Definition['%s Insightfuls'] = '%s mielest&auml; hy&ouml;dyllinen vastaus ';
$Definition['%s level deep'] = '%s tasoa syvä';
$Definition['%s levels deep'] = '%s tasoa syvä';
$Definition['%s Likes'] = '%s tykk&auml;yst&auml;';
$Definition['%s LOLs'] = '%s LOLlia';
$Definition['%s member'] = '%s jäsen';
$Definition['%s members'] = '%s jäsentä';
$Definition['%s mentioned %s in a %s.'] = '%s mainitsi j&auml;senen %s. Katso %s.';
$Definition['%s message'] = '%s viesti&nbsp;|&nbsp;';
$Definition['%s messages'] = '%s viesti&auml;&nbsp;|&nbsp;';
$Definition['%s minute'] = '%s minuutti';
$Definition['%s minutes'] = '%s minuuttia';
$Definition['%s month'] = '%s kuukausi';
$Definition['%s months'] = '%s kuukautta';
$Definition['%s New'] = 'Uusia: %s';
$Definition['%s new'] = 'Uusia: %s';
$Definition['%s new comment since you last read this.'] = '%s uusi kommentti viime lukukerran j&auml;lkeen.';
$Definition['%s new comments since you last read this.'] = '%s uutta kommenttia viime lukukerran j&auml;lkeen.';
$Definition['%s New Plural'] = '%s Uutta';
$Definition['%s new plural'] = '%s uusi';
$Definition['%s Not Found'] = '%s ei l&ouml;ytynyt';
$Definition['%s not found.'] = '%s ei löytynyt.';
$Definition['%s of %s'] = '%s / %s';
$Definition['%s Point'] = '%s piste';
$Definition['%s point'] = '%s piste';
$Definition['%s Points'] = '%s pistett&auml;';
$Definition['%s points'] = '%s pistett&auml;';
$Definition['%s posts'] = '%s viesti&auml;';
$Definition['%s result'] = '%s tulos';
$Definition['%s results'] = '%s tulokset';
$Definition['%s said'] = '%s kirjoitti';
$Definition['%s said:'] = '%s kirjoitti:';
$Definition['%s tag(s) found.'] = '%s tagia l&ouml;ytyi.';
$Definition['%s tags in the system'] = '%s tagia j&auml;rjestelm&auml;ss&auml;';
$Definition['%s Up Votes'] = '%s &auml;&auml;ntä yl&ouml;s';
$Definition['%s user'] = '%s käyttäjä';
$Definition['%s users'] = '%s käyttäjää';
$Definition['%s view'] = '%s lukukerta';
$Definition['%s view html'] = '%s lukukerta';
$Definition['%s viewing'] = '%s katsoo';
$Definition['%s views'] = '%s lukukertaa';
$Definition['%s views html'] = '%s lukukertaa';
$Definition['%s votes'] = '%s &auml;&auml;nt&auml;';
$Definition['%s was removed from the %s and added to the %s'] = '%s poistettiin sijainnista %s ja lisättiin sijaintiin %s';
$Definition['%s week'] = '%s viikko';
$Definition['%s weeks'] = '%s viikkoa';
$Definition['%s WTFs'] = '%s WTF&auml;&auml;';
$Definition['%s year'] = '%s vuosi';
$Definition['%s years'] = '%s vuotta';

$Definition['(All)'] = '(Kaikki)';
$Definition['(empty message)'] = '(viestiss&auml; ei ole sis&auml;lt&ouml;&auml;)';
$Definition['(Spoiler)'] = '(Juonipaljastus)';

$Definition['+%s Guests'] = '+%s vierasta';

$Definition[' - Page %s'] = '- Sivu %s';

$Definition['1 message'] = '1 viesti';

$Definition['<General Error>'] = '<Yleinen virhe>';
$Definition['<strong>%1$s</strong> (%2$s) %3$s'] = '<strong>%1$s</strong> (%2$s) %3$s ';

$Definition['[%1$s] %2$s'] = '[%1$s] %2$s ';
$Definition['[%1$s] Membership Approved'] = '[%1$s]: J&auml;senyys vahvistettu';
$Definition['[%s] Welcome Aboard!'] = '[%s] Tervetuloa mukaan!';
$Definition['[Deleted User]'] = '[Poistettu k&auml;ytt&auml;j&auml;]';

$Definition['About'] = 'J&auml;sentiedot';
$Definition['About %s users'] = 'Tietoja %s käyttäjistä';
$Definition['AboutToDelete'] = 'Olet poistamassa tiedoston %s. ';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Olet poistamassa %1$s keskustelua %2$s valitusta keskustelusta. ';
$Definition['Abuse'] = 'V&auml;&auml;rink&auml;yt&ouml;s';
$Definition['Accept'] = 'Hyv&auml;ksy';
$Definition['Accepted'] = 'Vahvistettu';
$Definition['Accept this answer.'] = 'Hyv&auml;ksy t&auml;m&auml; vastaus.';
$Definition['Access the Site'] = 'Pääsy verkkosivulle';
$Definition['Account Options'] = 'Tilin asetukset';
$Definition['Activate'] = 'Aktivoi';
$Definition['Active'] = 'Aktiivinen';
$Definition['Active Users'] = 'Aktiiviset k&auml;ytt&auml;j&auml;t';
$Definition['Activity'] = 'Sy&ouml;te';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s hyväksyi %4$s %8$s. ';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s kommentoi %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s kommentoi %8$s.';
$Definition['Activity.Comment'] = 'Kommentoi';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s mainitsi(t) j&auml;senen %3$s. Katso %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s mainitsi(t) j&auml;senen %3$s. Katso %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = 'Uusi privaviesti, l&auml;hett&auml;j&auml;n&auml; %1$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = 'Uusi privaviesti, l&auml;hett&auml;j&auml;n&auml; %1$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s liittyi.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s liittyi.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s vaihtoi %6$s profiilikuvan.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s vaihtoi %6$s profiilikuvan.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s vastasi %4$s %8$s. ';
$Definition['Add'] = 'Lis&auml;&auml;';
$Definition['Add %s'] = 'Lisää %s';
$Definition['Add a Comment'] = 'Kommentoi';
$Definition['Add a Message'] = 'L&auml;het&auml; viesti';
$Definition['Add another poll option ...'] = 'Lis&auml;&auml; uusi kyselyn vaihtoehto..';
$Definition['Add a Profile Picture'] = 'Lis&auml;&auml; profiilikuva';
$Definition['Add a time?'] = 'Haluatko lisätä ajan?';
$Definition['Add a Warning'] = 'Varoita';
$Definition['Add Badge'] = 'Lis&auml;&auml; kunniamerkki';
$Definition['Add Comment'] = 'Lis&auml;&auml; kommentti';
$Definition['Add Cost'] = 'Lis&auml;&auml; hinta';
$Definition['Add Image'] = 'Lis&auml;&auml; kuva';
$Definition['Add Message'] = 'Vastaa';
$Definition['Add Note'] = 'Lisää muistutus';
$Definition['Add People to this Conversation'] = 'Lis&auml;&auml; henkil&ouml;it&auml; t&auml;h&auml;n keskusteluun';
$Definition['Add Route'] = 'Lis&auml;&auml; reitti';
$Definition['Admin'] = 'Ylläpitäjä';
$Definition['Administrator'] = 'Admin';
$Definition['Administrator Activity'] = 'Yll&auml;pidon sy&ouml;te';
$Definition['administrators'] = 'yll&auml;pit&auml;j&auml;t';
$Definition['Advanced'] = 'Lis&auml;asetukset';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Pyynt&ouml;&auml; k&auml;sitelt&auml;essä tapahtui kohtalokas virhe. <br />Serverin vastaus: %s';
$Definition['Agree'] = 'Hyv&auml;ksy';
$Definition['Alert'] = 'Varoitus';
$Definition['Align center'] = 'Ryhmitä keskelle';
$Definition['Align left'] = 'Ryhmitä vasemmalle';
$Definition['Align right'] = 'Ryhmitä oikealle';
$Definition['All'] = 'Kaikki';
$Definition['All %s'] = 'Kaikki %s';
$Definition['All %s...'] = 'Kaikki %s...';
$Definition['All Bookmarks'] = 'Kaikki suosikit';
$Definition['All Categories'] = 'Kaikki kategoriat';
$Definition['all categories'] = 'kaikki luokat';
$Definition['All Conversations'] = 'Kaikki keskustelut';
$Definition['All Discussions'] = 'Kaikki keskustelut';
$Definition['All Events'] = 'Kaikki tapahtumat';
$Definition['All Members'] = 'Kaikki jäsenet';
$Definition['All members'] = 'Kaikki jäsenet';
$Definition['Allow'] = 'Salli';
$Definition['Allow other members to see your email?'] = 'Salli muiden n&auml;hd&auml; s&auml;hk&ouml;postiosoitteesi?';
$Definition['All Time Leaders'] = 'Kaikkien aikojen parhaat';
$Definition['Already Warned'] = 'Valmiiksi varoitettu';
$Definition['Also banned for the following:'] = 'Estetty myös seuraavista syistä:';
$Definition['A message has been sent to your email address with password reset instructions.'] = 'S&auml;hk&ouml;postiosoitteeseesi on l&auml;hetty viesti, jossa on ohjeet salasanan vaihtamiseen.';
$Definition['Ancient Membership'] = 'Muinainen j&auml;senyys';
$Definition['An invitation has already been sent to the email you entered.'] = 'Antamaasi s&auml;hk&ouml;postiosoiteeseen on jo l&auml;hetetty kutsu.';
$Definition['Announce'] = 'Aseta huomioitaviin';
$Definition['Announce...'] = 'Ilmoita...';
$Definition['Announcement'] = 'Huom!';
$Definition['Announcements'] = 'Ilmoitukset';
$Definition['Announce this discussion'] = 'Aseta t&auml;m&auml; keskustelu huomioitaviin';
$Definition['Answer'] = 'Vastaus';
$Definition['answer'] = 'vastaus';
$Definition['Answers'] = 'Vastausvaihtoehdot';
$Definition['answers'] = 'vastaukset';
$Definition['Appearance'] = 'Ulkoasu';
$Definition['Applicant'] = 'Hakija';
$Definition['Applicants'] = 'J&auml;senhakemukset';
$Definition['Applicants & Invitations'] = 'Hakemukset & kutsut';
$Definition['Apply'] = 'L&auml;het&auml;';
$Definition['Apply Changes'] = 'Tallenna muutokset';
$Definition['Apply for Membership'] = 'Hae j&auml;senyytt&auml;';
$Definition['Apply for membership'] = 'Hae j&auml;senyytt&auml;';
$Definition['Approve'] = 'Hyväksy';
$Definition['Approve Applicant'] = 'Hyväksy';
$Definition['Approved'] = 'Hyväksytty
';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Oletko T&Auml;YSIN VARMA ett&auml; haluat suorittaa valitun toiminnon?';
$Definition['Are you attending this event?'] = 'Oletko mukana tässä tapahtumassa?';
$Definition['Are you sure you want to delete this %s?'] = 'Oletko varma ett&auml; haluat poistaa t&auml;m&auml;n %s?';
$Definition['Are you sure you want to do that?'] = 'Vahvista toiminto?';
$Definition['Are you sure you want to do this?'] = 'Oletko varma ett&auml; haluat tehd&auml; t&auml;m&auml;n?';
$Definition['Are you sure you want to join this group?'] = 'Haluatko varmasti liittyä tähän ryhmään?';
$Definition['Are you sure you want to leave this conversation?'] = 'Tahdotko varmasti poistua tästä keskustelusta?';
$Definition['Are you sure you want to leave this group?'] = 'Haluatko varmasti jättää tämän ryhmän?';
$Definition['Are you sure you wish to continue?'] = 'Oletko varma ett&auml; haluat jatkaa?';
$Definition['Ask a Question'] = 'L&auml;het&auml; uusi kysymys';
$Definition['Ask Question'] = 'L&auml;het&auml; kysymys';
$Definition['Attach a file'] = 'Lis&auml;&auml; liitetiedosto';
$Definition['Attach image/file'] = 'Liitä kuva/tiedosto';
$Definition['Attachments'] = 'Liitetiedostot';
$Definition['Attach this warning to the %s.'] = 'Liitä tämä varoitus tiedostoon %s';
$Definition['AttemptingSignOut'] = 'Olet kirjautumassa ulos. Vahvista toiminto: %s?';
$Definition['Attending'] = 'Mukana';
$Definition['Attending (%s)'] = 'Mukana (%s)';
$Definition['Authenticate URL'] = 'Autentikoinnin URL';
$Definition['Authentication'] = 'Autentikointi';
$Definition['Author'] = 'Kirjoittaja';
$Definition['available'] = 'vapaa';
$Definition['Awaiting Moderation'] = 'Odottaa moderointia';
$Definition['Awesome'] = 'Loistava';

$Definition['Back to Discussions'] = 'Takaisin keskustelulistaukseen';
$Definition['Back to Profile'] = 'Takaisin profiiliin';
$Definition['Badge'] = 'Kunniamerkki';
$Definition['Badge404'] = 'Kunniamerkki&auml; ei l&ouml,ytynyt.';
$Definition['Badges'] = 'Kunniamerkit';
$Definition['BadgesModuleTitle'] = 'Kunniamerkit';
$Definition['BadgesNobody'] = 'Kukaan ei ole ansainnut t&auml;t&auml; kunniamerkki&auml; viel&auml;';
$Definition['Ban'] = 'Aseta esto';
$Definition['Ban.Action'] = 'Est&auml;';
$Definition['Banned'] = 'Estetty';
$Definition['Banned for being abusive.'] = 'Estetty syyn&auml; v&auml;&auml;rink&auml;yt&ouml;kset.';
$Definition['Banned for spamming.'] = 'Estetty syyn&auml; roskapostiviestien l&auml;hetys.';
$Definition['Banned for the following:'] = 'Estetty seuraavista syistä:';
$Definition['Banned users can no longer access the site.'] = 'Estetyt k&auml;ytt&auml;j&auml;t eiv&auml;t voi en&auml;&auml; kirjautua sivustolle nykyisell&auml; tunnuksellaan.';
$Definition['Banner'] = 'Banneri';
$Definition['BanReason.1'] = 'Estetty yhteisömanagerin toimesta.';
$Definition['BanReason.2'] = 'Estetty IP-osoitteen, sähköpostin tai nimen perusteella.';
$Definition['BanReason.4'] = 'Estetty väliaikaisesti yhteisömanagerin toimesta.';
$Definition['BanReason.8'] = 'Estetty varoitusten vuoksi.';
$Definition['Ban User'] = 'Aseta esto &auml;ytt&auml;j&auml;lle';
$Definition['Ban Value'] = 'Eston kohde';
$Definition['Basic'] = 'Perus';
$Definition['Best Answer'] = 'Paras vastaus';
$Definition['Best Answers'] = 'Parhaat vastaukset';
$Definition['Best Of'] = 'Parhaat';
$Definition['Best Of...'] = 'Parhaat…';
$Definition['Blank Discussion Topic'] = 'Tyhj&auml; aiheen otsikko';
$Definition['Blank Message'] = 'Tyhj&auml; viesti';
$Definition['Blog'] = 'Blogi';
$Definition['Blogs'] = 'Blogit';
$Definition['Body'] = 'Sis&auml;lt&ouml;';
$Definition['Bold'] = 'Rohkea';
$Definition['Bookmark'] = 'Aseta suosikkeihin';
$Definition['bookmarked discussion'] = 'Kirjanmerkitty keskustelu';
$Definition['Bookmarked Discussions'] = 'Suosikkeihin asettamasi keskustelut';
$Definition['Bookmarks'] = 'Suosikit';
$Definition['bookmarks'] = 'suosikit';
$Definition['Browse Groups'] = 'Selaa ryhmiä';
$Definition['Browse popular groups.'] = 'Selaile suosittuja ryhmiä.';
$Definition['By'] = 'L&auml;hett&auml;j&auml;n&auml;';
$Definition['by'] = 'l&auml;hett&auml;j&auml;n&auml;';
$Definition['By %s'] = 'L&auml;hett&auml;j&auml;n&auml; %s';
$Definition['by %s'] = 'L&auml;hett&auml;j&auml;: %s';
$Definition['by Date'] = 'p&auml;iv&auml;yksen mukaan';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Lataamalla kuvan vakuutat omistavasi oikeudet siihen sek&auml; sen, ettei kuva riko palstan s&auml;&auml;nt&ouml;j&auml; ja k&auml;ytt&ouml;ehtoja.';

$Definition['Cancel'] = 'Peruuta';
$Definition['Casual'] = 'Tuttavallinen';
$Definition['Categories'] = 'Kategoriat';
$Definition['CategoriesShowFollowed'] = 'N&auml;yt&auml; vain seurantaan asettamani kategoriat';
$Definition['CategoriesShowUnfollowed'] = 'N&auml;yt&auml; piilotetut kategoriat';
$Definition['CategoriesViewingAll'] = 'Olet asettanut seurantaan kaikki kategoriat';
$Definition['CategoriesViewingFollowed'] = 'N&auml;ytet&auml;&auml;n vain seurantaan asettamasi kategoriat.';
$Definition['Category'] = 'Kategoria';
$Definition['Category Filter'] = 'Kategoriasuodatin';
$Definition['CategoryID'] = 'Kategoria';
$Definition['Category Management'] = 'Kategorioiden n&auml;ytt&ouml;asetukset';
$Definition['Category Notifications'] = 'Kategorioiden ilmoitukset';
$Definition['Category to Use'] = 'K&auml;ytett&auml;v&auml; kategoria';
$Definition['Change'] = 'Vaihda';
$Definition['Change language'] = 'Vaihda kieltä';
$Definition['Change My Password'] = 'Vaihda salasanasi';
$Definition['Change My Picture'] = 'Vaihda kuvasi';
$Definition['Change Password'] = 'Vaihda salasana';
$Definition['Change Picture'] = 'Vaihda kuva';
$Definition['Check all roles that apply to this user:'] = 'Valitse kaikki ne roolit, joihin t&auml;m&auml; k&auml;ytt&auml;j&auml; kuuluu:';
$Definition['Check it out'] = 'Siihen kannattaa tutustua';
$Definition['Child Categories'] = 'Alakategoriat';
$Definition['Child Categories:'] = 'Alakategoriat:';
$Definition['Choose a name to identify yourself on the site.'] = 'Valitse k&auml;ytt&auml;j&auml;tunnus itsellesi sivustolla.';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Valitse keskustelu, johon kaikki kommentit yhdistet&auml;&auml;n: ';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Valitse haluatko l&auml;hett&auml;&auml; kysymyksen vaiko aloittaa uuden keskustelun';
$Definition['Clear'] = 'Tyhjenn&auml;';
$Definition['clear'] = 'tyhjenn&auml;';
$Definition['Clear Conversation History'] = 'Tyhjenn&auml; keskusteluhistoria';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Klikkaa <a href="%s">t&auml;st&auml;</a> siirty&auml;ksesi takaisin keskusteluun.';
$Definition['Click accept or reject beside an answer.'] = 'Klikkaa hyv&auml;ksy tai hylk&auml;&auml; vastauksen yhteydess&auml;.';
$Definition['clicking here'] = 'klikkaamalla t&auml;st&auml;';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Klikkaa %s keskustelun vieress&auml; asettaaksesi sen suosikkeihin.';
$Definition['Click to re-attach'] = 'Napsauta kiinnittääksesi uudelleen';
$Definition['Close'] = 'Sulje';
$Definition['Closed'] = 'Suljettu';
$Definition['Close this discussion'] = 'Sulje t&auml;m&auml; keskustelu';
$Definition['Color'] = 'Väri';
$Definition['Combo Breaker'] = 'Yhdistelm&auml;';
$Definition['Comment'] = 'Kommentoi';
$Definition['comment'] = 'kommentti';
$Definition['Comment As ...'] = 'Kommentoi tunnuksella...';
$Definition['Comment by %s'] = 'Kommentoijana %s';
$Definition['Comment in'] = 'kohteessa';
$Definition['Commenting as %1$s (%2$s)'] = 'Kommentoidaan nimellä %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Kommentointi on pois k&auml;yt&ouml;st&auml;.';
$Definition['Comments'] = 'Viestej&auml; yhteens&auml;';
$Definition['comments'] = 'kommentit';
$Definition['Comments are between {UserID,you}.'] = 'Kommentointi tapahtuu seuraavien käyttäjien välillä {UserID,you}. ';
$Definition['Community'] = 'Yhteisö';
$Definition['Community Guidelines'] = 'Yhteisön säännöt';
$Definition['Completely delete the warning.'] = 'Poista varoitus lopullisesti.';
$Definition['Confirm'] = 'Vahvista';
$Definition['Confirmed email address'] = 'Vahvistettu sähköpostiosoite.';
$Definition['Confirm Email'] = 'S&auml;hk&ouml;postiosoitteen vahvistus';
$Definition['Confirm My Email Address'] = 'Vahvista sähköpostiosoitteeni.';
$Definition['Confirm Password'] = 'Vahvista salasana';
$Definition['Confirm Your Email Address'] = 'Vahvista sähköpostiosoitteesi';
$Definition['Connect'] = 'Yhdist&auml;';
$Definition['ConnectAccountExists'] = 'Vaikuttaa silt&auml;, ett&auml; olet jo j&auml;sen?';
$Definition['ConnectChooseName'] = 'Valitse k&auml;ytt&auml;j&auml;tunnus sivustolle.';
$Definition['ConnectCreateAccount'] = 'Lis&auml;&auml; infoa &amp; luo tunnus';
$Definition['Connected'] = 'Yhdistetty';
$Definition['Connected With: {ProviderName}'] = 'Yhdistetty: {ProviderName}';
$Definition['ConnectExistingPassword'] = 'Anna nykyinen salasanasi.';
$Definition['Connecting...'] = 'Yhdistet&auml;&auml;n...';
$Definition['Connection'] = 'Yhteys';
$Definition['ConnectLeaveBlank'] = 'J&auml;t&auml; tyhj&auml;ksi jos et halua yhdist&auml;&auml; olemassaolevaan k&auml;ytt&auml;j&auml;tiliin.';
$Definition['ConnectName'] = 'K&auml;ytt&auml;j&auml;tunnus';
$Definition['ConnectRegisteredName'] = 'Rekister&ouml;ity tunnuksesi: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Liitä profiilisi sosiaaliseen verkostoon saadaksesi tietoa siellä tapahtuvasta toiminnasta, sekä jaa omat tekemisesi ystävillesi ja seuraajillesi.';
$Definition['Contact Us'] = 'Ota meihin yhteyttä';
$Definition['Continue'] = 'Jatka';
$Definition['conversation'] = 'keskustelu';
$Definition['Copy'] = 'Kopioi';
$Definition['Core'] = 'Ydin';
$Definition['Created'] = 'Luotu';
$Definition['Create Discussions'] = 'Aloita uusia keskusteluja';
$Definition['Create One.'] = 'Luo uusi.';
$Definition['Current'] = 'Nykyinen';
$Definition['Currently: '] = 'T&auml;ll&auml; hetkell&auml;: ';
$Definition['Custom Information'] = 'Muokatut tiedot';
$Definition['Customize'] = 'Muokkaa';
$Definition['customize your profile now'] = 'muokkaa profiiliasi nyt';
$Definition['Customize your Public Profile'] = 'Muokkaa julkista profiiliasi';
$Definition['Custom Profile Fields'] = 'Muokatut profiilin tiedot';
$Definition['Custom Profile Field Settings'] = 'Muokattujen profiilitietojen asetukset';

$Definition['Dashboard'] = 'Admin';
$Definition['Dashboard Home'] = 'Kojelaudan etusivu';
$Definition['Dashboard Summaries'] = 'Kojelaudan tietojen yhteenveto';
$Definition['Date'] = 'P&auml;iv&auml;ys';
$Definition['Date.DefaultDateTimeFormat'] = '%B %e, %l:%M%p %Y ';
$Definition['Date.DefaultDayFormat'] = '%B %e ';
$Definition['Date.DefaultFormat'] = '%B %e, %Y ';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y ';
$Definition['Date. Expects \'mm/dd/yyyy\'.'] = 'Päivämäärä. Oletusarvoisesti \'kk/pv/vvvv\'.';
$Definition['Date Added'] = 'Lis&auml;tty';
$Definition['Date Examples'] = 'Esimerkkejä: maanantai, tänään, viime viikolla, 26. marraskuuta, 3/26/04';
$Definition['Date within'] = 'Aikaväli';
$Definition['days'] = 'p&auml;iv&auml;&auml;';
$Definition['Decline'] = 'Hylk&auml;&auml;';
$Definition['Declined'] = 'Estetty ';
$Definition['Default'] = 'Oletus';
$Definition['default'] = 'oletus';
$Definition['Define Thumbnail'] = 'M&auml;&auml;rit&auml; pikkukuva klikkaamalla ja raahaamalla valinta sopivaan kohtaan josta haluat kuvan rajattavan.';
$Definition['Delete'] = 'Poista';
$Definition['Delete %s'] = 'Poista %s';
$Definition['Delete Account'] = 'Poista tunnus';
$Definition['Delete Content'] = 'Poista sis&auml;lt&ouml;';
$Definition['Delete Conversation'] = 'Poista viesti';
$Definition['Deleted'] = 'Poistettu';
$Definition['Delete Discussion'] = 'Poista keskustelu';
$Definition['Delete Forever'] = 'Poista lopullisesti';
$Definition['Delete Group'] = 'Poista ryhmä';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Poista j&auml;sen ja j&auml;senen l&auml;hett&auml;m&auml; kaikki sis&auml;lt&ouml;. T&auml;m&auml; yleens&auml; aiheuttaa keskusteluissa ep&auml;loogisuuksia, kun muut k&auml;ytt&auml;j&auml;t vastaavat viesteihin, joita ei en&auml;&auml; ole. Roskapostien poistoon t&auml;m&auml; kuitenkin on paras vaihtoehto. ';
$Definition['Delete User Content'] = 'Poista j&auml;senen l&auml;hett&auml;m&auml; sis&auml;lt&ouml;';
$Definition['Delete User Forever'] = 'Poista j&auml;sen pysyv&auml;sti';
$Definition['Deny'] = 'Kiellä';
$Definition['Deny Applicant'] = 'Kiellä';
$Definition['Did this answer the question?'] = 'Oliko t&auml;m&auml; vastaus kysymykseesi?';
$Definition['Disable'] = 'Poista k&auml;yt&ouml;st&auml;';
$Definition['Disabled'] = 'Pois k&auml;yt&ouml;st&auml;';
$Definition['Disagree'] = 'Hylk&auml;&auml;';
$Definition['Discussion'] = 'Keskustelu';
$Definition['discussion'] = 'keskustelu';
$Definition['Discussion Board'] = 'Keskustelulauta';
$Definition['Discussions'] = 'Keskustelut';
$Definition['discussions'] = 'keskustelut';
$Definition['Discussions Page'] = 'Keskustelu -sivu';
$Definition['Discussion Title'] = 'Keskustelun otsikko';
$Definition['Dislike'] = 'En tykk&auml;&auml;k&auml;&auml;n';
$Definition['Dismiss'] = 'Ohita';
$Definition['Documentation'] = 'Dokumentaatio';
$Definition['Don\'t announce.'] = '&Auml;l&auml; luo ilmoitusta';
$Definition['Don\'t fold quotes'] = 'Älä arkistoi lainauksia';
$Definition['Don\'t have an account? %s'] = 'Ei viel&auml; k&auml;ytt&auml;j&auml;tunnusta? %s';
$Definition['Download'] = 'Lataa';
$Definition['Download the sounds as MP3'] = 'Lataa äänet MP3-tiedostona';
$Definition['Do you want to expire or delete this warning?'] = 'Haluatko asettaa t&auml;lle varoitukselle p&auml;&auml;ttymisp&auml;iv&auml;n tai poistaa sen kokonaan?';
$Definition['Draft saved at %s'] = 'Luonnos tallennettu %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Croppaa kuva raahaamalla ja valitun alueen kokoa s&auml;&auml;t&auml;m&auml;ll&auml; sopivaksi.';
$Definition['Drop image/file'] = 'Pudota kuva/tiedosto';

$Definition['Earned'] = 'Ansaittu';
$Definition['Edit'] = 'Muokkaus';
$Definition['edit'] = 'muokkaa';
$Definition['Edit %s'] = 'Muuta %s';
$Definition['Edit Account'] = 'Muokkaa tunnusta';
$Definition['Edit Comment'] = 'Muokkaa viesti&auml;';
$Definition['Edit Discussion'] = 'Muokkaa keskustelua';
$Definition['edited %s'] = 'editoi %s ';
$Definition['Edited %s by %s.'] = '%s, joka tuli %s kautta, on korjattu.';
$Definition['Editing'] = 'Muokkaa';
$Definition['Edit My Account'] = 'Muokkaa tunnustasi';
$Definition['Edit My Profile'] = 'Muokkaa omaa profiilia';
$Definition['Edit My Thumbnail'] = 'Muokkaa pikkukuvaa';
$Definition['editor.BBCodeHelpText'] = 'Voit käyttää seuraavaa viesteissäsi: <a href="http://en.wikipedia.org/wiki/BBCode" target="_new">BBCode</a>';
$Definition['editor.HtmlHelpText'] = 'Voit käyttää <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple HTML</a>;:ää viesteissäsi.';
$Definition['editor.MarkdownHelpText'] = 'Voit käyttää <a href="http://en.wikipedia.org/wiki/Markdown" target="_new">Markdown</a>ia viesteissäsi. ';
$Definition['editor.TextHelpText'] = 'Käytät parhaillaan pelkkää tekstiä viesteissäsi.';
$Definition['editor.WysiwygHelpText'] = 'Tunnus <a href="https://en.wikipedia.org/wiki/WYSIWYG" target="_new">WYSIWYG</a> on käytössä viesteissäsi.';
$Definition['Edit Preferences'] = 'Muokkaa asetuksia';
$Definition['Edit Profile'] = 'Muokkaa profiilia';
$Definition['Edit Tag'] = 'Muokkaa tagia';
$Definition['Edit Thumbnail'] = 'Muokkaa pikkukuvaa';
$Definition['Eighth Anniversary'] = 'Kahdeksas vuosip&auml;iv&auml;';
$Definition['Email'] = 'S&auml;hk&ouml;posti';
$Definition['Email/Username'] = 'S&auml;hk&ouml;posti tai tunnus';
$Definition['EmailConfirmEmail'] = 'Sinun t&auml;ytyy viel&auml; vahvistaa s&auml;hk&ouml;postiosoitteesi. Klikkaa t&auml;st&auml; vahvistaaksesi sen: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '
Kivaa päivänjatkoa!';
$Definition['EmailHeader'] = 'Hei {User.Name}!
';
$Definition['EmailInvitation'] = 'Hei!

%1$s kutsui sinut mukaan keskustelupalstalle %2$s. 

Vahvistaaksesi kutsun, siirry allaolevaan osoitteeseen:

  %3$s

Paljon tervetuloa!';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s
  
Have a great day!';
$Definition['EmailNotification'] = '%1$s

Seuraa alla olevaa linkkiä nähdäksesi lisää:
%2$s

Hyvää päivänjatkoa! ';
$Definition['Email Notifications'] = 'S&auml;hk&ouml;posti-ilmoitukset';
$Definition['Email Or Username'] = 'S&auml;hk&ouml;posti tai k&auml;ytt&auml;j&auml;tunnus';
$Definition['EmailPassword'] = 'Hello %1$s,

%2$s has reset your password at %3$s. Your login credentials are now:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Sovelluksen lähettämiin sähköpostiin vastataan seuraavista nimestä ja osoitteesta';
$Definition['Email Source'] = 'S&auml;hk&ouml;posti';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Napsauta alla olevaa linkkiä nähdäksesi lisää:
%2$s

Hyvää päivänjatkoa! ';
$Definition['Email Unavailable'] = 'S&auml;hk&ouml;postiosoite ei saatavilla';
$Definition['Email visible to other users'] = 'S&auml;hk&ouml;postiosoite n&auml;kyviss&auml; muille j&auml;senille';
$Definition['EmailWelcome'] = 'Hello %1$s,

%2$s has created an account for you at %3$s. Your login credentials are:

  Email: %6$s
  Password: %5$s
  Url: %4$s

Have a great day!';
$Definition['EmailWelcomeConnect'] = 'Hello {User.Name},

You have successfully connected to {Title}. Here is your information:

  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['EmailWelcomeRegister'] = 'Hei {User.Name},

Rekisteröitymisesi palstalle {Title} onnistui. Ohessa käyttäjätietosi:

  Tunnus: {User.Name}
  Sähköposti: {User.Email}

Sivuston osoite on {/,exurl,domain}.

Tervetuloa!';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Lue koko juttu t&auml;&auml;lt&auml;</a></p><div class="ClearFix"></div></div>';
$Definition['EmbeddedNoBodyFormat'] = '{Url}';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Lue koko juttu t&auml;&auml;lt&auml;</a></p><div class="ClearFix"></div></div>';
$Definition['Enable'] = 'Ota k&auml;ytt&ouml;&ouml;n';
$Definition['Enabled'] = 'Ota k&auml;ytt&ouml;&ouml;n: Valittu Tasku n&auml;ytet&auml;&auml;n.';
$Definition['End time?'] = 'Lopetusaika?';
$Definition['English'] = 'Englanti';
$Definition['Enter your Email address'] = 'Anna s&auml;hk&ouml;postiosoitteesi';
$Definition['Enter your email address'] = 'Anna s&auml;hk&ouml;postiosoitteesi';
$Definition['Enter your Email address or username'] = 'Anna s&auml;hk&ouml;postiosoitteesi tai tunnuksesi';
$Definition['Enter Your OpenID Url'] = 'Anna OpenID -url';
$Definition['Erase User Content'] = 'Tyhjenn&auml; k&auml;ytt&auml;j&auml;n sis&auml;lt&ouml;';
$Definition['Error'] = 'Virhe';
$Definition['ErrorBadInvitationCode'] = 'Kutsukoodi on virheellinen tai vanhentunut.';
$Definition['ErrorCredentials'] = 'Pahoittelut, annetuilla tiedoilla ei l&ouml;ytynyt tietoja. Joko s&auml;hk&ouml;postiosoite tai salasana on virheellinen.';
$Definition['ErrorPermission'] = 'Pahoittelut, ei oikeuksia.';
$Definition['ErrorPluginDisableRequired'] = 'Et voi laittaa liitännäistä {0} pois päältä, koska liitännäinen {1} tarvitsee sitä toimiakseen. ';
$Definition['ErrorPluginEnableRequired'] = 'Tämän liitännäisen käynnistäminen vaatii, että myös liitännäinen {0} on päällä.';
$Definition['ErrorPluginVersionMatch'] = 'Valittu liitännäinen {0} (versio {1}) ei täyttänyt versiovaatimuksia ({2}).';
$Definition['ErrorRecordNotFound'] = 'Pyydetty&auml; tietoa ei l&ouml;ytynyt.';
$Definition['ErrorTermsOfService'] = 'Hyv&auml;ksy palstan k&auml;ytt&ouml;ehdot ensin!';
$Definition['Event'] = 'Tapahtuma';
$Definition['Event Details'] = 'Tapahtuman yksityiskohdat';
$Definition['Events'] = 'Tapahtumat';
$Definition['everyone'] = 'jokainen';
$Definition['Everything'] = 'Kaikki';
$Definition['Expired'] = 'Rauennut';
$Definition['Expires'] = 'Raukeaa';

$Definition['Failed to delete group.'] = 'Ryhmän poistaminen epäonnistui.';
$Definition['Failed to find discussion for commenting.'] = 'Keskustelun l&ouml;yt&auml;minen kommentointiin ep&auml;onnistui.';
$Definition['Failed to load the poll.'] = 'Kyselyn lataus ep&auml;onnistui';
$Definition['Feedback'] = 'Palaute';
$Definition['Female'] = 'Nainen';
$Definition['Fifth Anniversary'] = 'Viides vuosip&auml;iv&auml;';
$Definition['FileName'] = 'Tiedoston nimi';
$Definition['Filename'] = 'Tiedoston nimi';
$Definition['FileSize'] = 'Tiedoston koko';
$Definition['File Size'] = 'Tiedoston koko';
$Definition['Find your account information below.'] = 'Löydät käyttäjätilisi tiedot alta.';
$Definition['First Anniversary'] = 'Ensimm&auml;inen vuosip&auml;iv&auml;';
$Definition['First Comment'] = 'Ensimm&auml;inen kommentti';
$Definition['Flag'] = 'Ilmianna';
$Definition['Folder'] = 'Kansio';
$Definition['Folders'] = 'Kansiot';
$Definition['Follow'] = 'Seuraa';
$Definition['Follow %s'] = 'Seuraa k&auml;ytt&auml;j&auml;&auml; %s';
$Definition['Followed by %d people'] = 'Seurantaan asettanut %d k&auml;ytt&auml;j&auml;&auml;';
$Definition['Followed by %d person'] = 'Seurantaan asettanut %d k&auml;ytt&auml;j&auml;&auml;';
$Definition['followed categories'] = 'seuratut luokat';
$Definition['Following %d people'] = 'Seurannassa %d k&auml;ytt&auml;j&auml;&auml;';
$Definition['Following %d person'] = 'Seurannassa %d k&auml;ytt&auml;j&auml;&auml;';
$Definition['FollowOnly'] = 'Seuraa alla olevaa linkkiä nähdäksesi lisää:';
$Definition['Follows'] = 'Seurannat';
$Definition['Forgot?'] = '<br /><small>Salasana unohtunut?</small>';
$Definition['Forgot your password?'] = 'Salasana unohtunut?';
$Definition['Format'] = 'Alusta';
$Definition['Format his'] = 'oman';
$Definition['Format their'] = 'heid&auml;n';
$Definition['Format You'] = 'Sin&auml;';
$Definition['Format you'] = 'sin&auml;';
$Definition['Format Your'] = 'Sinun';
$Definition['Forum'] = 'Foorumi';
$Definition['Forums'] = 'Foorumit';
$Definition['Forum Signature Settings'] = 'Keskustelupalstan allekirjoitusasetukset';
$Definition['Fourth Anniversary'] = 'Nelj&auml;s vuosip&auml;iv&auml;';
$Definition['Friends'] = 'Kaverit';
$Definition['From'] = 'lähteestä';
$Definition['Full Site'] = 'Koko sivu';

$Definition['Garden.Email.SupportAddress'] = 'Yll&auml;pidon s&auml;hk&ouml;postiosoite';
$Definition['Garden.Email.SupportName'] = 'K&auml;ytt&ouml;tuen nimi';
$Definition['Garden.Registration.DefaultRoles'] = 'oletusrooli';
$Definition['Garden.Title'] = 'Bannerin otsikko';
$Definition['Gender'] = 'Sukupuoli';
$Definition['General'] = 'Yleinen';
$Definition['Generate import SQL only'] = 'Luo vain SQL import -tiedosto';
$Definition['Generate Password'] = 'Luo salasana';
$Definition['Get an audio challenge'] = 'Hanki audiohaaste';
$Definition['Get a new challenge'] = 'Ota vastaan uusi haaste';
$Definition['Get a visual challenge'] = 'Ota vastaan visuaalinen haaste';
$Definition['Give'] = 'Anna';
$Definition['Give a Badge to %s'] = 'My&ouml;nn&auml; kunniamerkki k&auml;ytt&auml;j&auml;lle %s';
$Definition['Give Badge'] = 'My&ouml;nn&auml; kunniamerkki';
$Definition['Given'] = 'Annettu';
$Definition['Go'] = 'Ok';
$Definition['Group'] = 'Ryhmä';
$Definition['group'] = 'ryhmä';
$Definition['GroupEmptyAnnouncements'] = 'Täällä tulee vielä tapahtumaan tärkeitä asioita.';
$Definition['GroupEmptyDiscussions'] = 'Täällä on todella hiljaista, eikö vain?';
$Definition['GroupEmptyEvents'] = 'Voi sentään, yhtään tulevaa tapahtumaa ei löytynyt.';
$Definition['Group Info'] = 'Tietoa ryhmästä';
$Definition['Group Leaders'] = 'Johtajat';
$Definition['Group Members'] = 'Jäsenet';
$Definition['GroupMembersEmpty'] = 'Kukaan ei ole vielä liittynyt. Levitä sanaa!';
$Definition['Group Options'] = 'Ryhmän valikko';
$Definition['Groups'] = 'Ryhmät';
$Definition['groups'] = 'ryhmät';
$Definition['Guest'] = 'Vieras';
$Definition['GuestModule.Message'] = 'Ole hyv&auml; ja kirjaudu sis&auml;&auml;n! Jos et ole viel&auml; rekister&ouml;itynyt, sekin onnistuu ohessa.';

$Definition['Hang on a sec while we sign you out.'] = 'Odota hetki kun kirjaamme sinut ulos.';
$Definition['Have a great day!'] = 'Hyvää päivänjatkoa!';
$Definition['he'] = 'oman';
$Definition['Heading'] = 'Otsikko';
$Definition['Heading %s'] = 'Otsikko %s';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} ansaitsi(t) <a href="{Url,html}">{Data.Name,text}</a> kunniamerkin.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} asetit eston j&auml;senelle  {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} kommentoi seuraavaa: <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.ConversationMessage'] = '{ActivityUserID,User} lähetti sinulle <a href="{Url,html}">viestin</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} mainitsi sinut keskustelussa <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} vaihtoi profiilikuvan j&auml;senelle  {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} liittyi.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} poisti eston j&auml;senelt&auml; {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} antoi varoituksen k&auml;ytt&auml;j&auml;lle {RegardingUserID,you}.';
$Definition['Hello!'] = 'Hei!';
$Definition['Hello %s!'] = 'Hei %s!';
$Definition['Hello {User.Name}!'] = 'Hei {User.Name}!';
$Definition['Help'] = 'Apua';
$Definition['her'] = 'oman';
$Definition['Hide'] = 'Piilota';
$Definition['Hide my online status from other members'] = 'Piilota online-statukseni muilta jäseniltä';
$Definition['Hide signatures?'] = 'Piilota allekirjoitukset?';
$Definition['Hide signatures always'] = 'Piilota allekirjoitukset aina';
$Definition['Hide signatures on my mobile device'] = 'Piilota allekirjoitukset kun k&auml;yt&auml;n palstaa puhelimella';
$Definition['his'] = 'oman';
$Definition['Home'] = 'Etusivu';
$Definition['hours'] = 'tuntia';
$Definition['How can we help you?'] = 'Kuinka voimme auttaa?';
$Definition['Howdy, Stranger!'] = 'Hei vieras, tervetuloa!';
$Definition['How long do you want this warning to last?'] = 'Miten kauan haluat varoituksen kest&auml;v&auml;n?';
$Definition['How many levels deep should we start folding up quote trees?'] = 'Kuinka monen tason jälkeen meidän kannattaa alkaa pienentämään lainauspuita?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Hyv&auml;ksyn <a id="TermsOfService" class="Popup" target="terms" href="%s">k&auml;ytt&ouml;ehdot ja s&auml;&auml;nn&ouml;t</a>';
$Definition['Icon'] = 'Kuvake';
$Definition['I confirm that I have received consent to join this community.'] = 'Koska olen alle %d vuotta vanha, vahvistan saaneeni huoltajan suostumuksen tähän yhteisöön liittymistä varten. ';
$Definition['Ignore'] = 'Jätä huomioimatta';
$Definition['Ignore List'] = 'Jätä lista huomioimatta';
$Definition['Ignore Someone'] = 'Jätä jonkun viestit huomioimatta';
$Definition['Image'] = 'Kuvake';
$Definition['images'] = 'kuvat';
$Definition['Images not allowed'] = 'Kuvien käyttö ei ole sallittu';
$Definition['Images will be scaled to a maximum height of {maxImageHeight}px.'] = 'Kuvat skaalataan maksimikorkeuteen {maxImageHeight}px.';
$Definition['Image URL'] = 'Kuvan URL-osoite';
$Definition['in'] = '&nbsp;';
$Definition['In <b>%s.</b>'] = 'Kohteessa <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = '<b>%s</b> sekä viimeisimmissä keskusteluissa. ';
$Definition['Inbox'] = 'Privaviestit';
$Definition['Incorrect. Try again.'] = 'Väärin. Yritä uudestaan.';
$Definition['Indent'] = 'Sisennys';
$Definition['In recent discussions.'] = 'Viimeaikaisissa keskusteluissa.';
$Definition['In seconds'] = 'Sekunteina';
$Definition['Insert Image'] = 'Lis&auml;&auml; kuva';
$Definition['Insightful'] = 'Hy&ouml;dyllinen vastaus';
$Definition['Internal'] = 'Sis&auml;inen';
$Definition['In this Conversation'] = 'Viestin vastaanottajat';
$Definition['Invalid password.'] = 'Antamasi salasana oli virheellinen. Muistathan ett&auml; isot ja pienet kirjaimet merkitsev&auml;t.';
$Definition['Invitation'] = 'Kutsu';
$Definition['Invitations'] = 'Kutsut';
$Definition['Invite'] = 'L&auml;het&auml; kutsu';
$Definition['InviteErrorPermission'] = 'Pahoittelut, ei oikeuksia.';
$Definition['Invite Friends'] = 'Kutsu ystäviä';
$Definition['Invite friends'] = 'Kutsu ystäviä';
$Definition['Invite one or more people to join this group.'] = 'Kutsu yksi tai useampi henkilö mukaan tähän ryhmään.';
$Definition['IPAddress'] = 'IP-osoite';
$Definition['IP Address'] = 'IP-osoite';
$Definition['I remember now!'] = 'Takaisin';
$Definition['Italic'] = 'Kursiivi';
$Definition['Item'] = 'Kohta';
$Definition['item'] = 'kohta';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Vaikuttaa silt&auml; ett&auml; olet uusi t&auml;&auml;ll&auml;? Jos haluat osallistua keskusteluihin, rekister&ouml;idy valitsemalla joku painikkeista ohessa! ';

$Definition['Jail'] = 'Vankila';
$Definition['Jailed users have reduced abilities.'] = 'Vankilaan laitetuilla k&auml;ytt&auml;jill&auml; on v&auml;hemm&auml;n toiminnallisuuksia k&auml;yt&ouml;ss&auml;&auml;n.';
$Definition['Join %s'] = 'Liity %s';
$Definition['Joined'] = 'Liittynyt';
$Definition['Joined %s'] = 'Liity %s';
$Definition['Join this Community Now'] = 'Liity nyt tähän yhteisöön';
$Definition['Join this Group'] = 'Liity ryhmään.';
$Definition['Join this group to view its content.'] = 'Sinun täytyy liittyä tähän ryhmään nähdäksesi sen tuottaman sisällön.';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Poista vain k&auml;ytt&auml;j&auml;tunnus, mutta s&auml;ilyt&auml; kaikki k&auml;ytt&auml;j&auml;n l&auml;hett&auml;m&auml; sis&auml;lt&ouml;.';
$Definition['Just expire the warning.'] = 'Aseta vain varoitus p&auml;&auml;ttyneeksi.';
$Definition['Just you!'] = 'Vain sin&auml;!';

$Definition['Keep me signed in'] = 'Muista minut';
$Definition['Keep User Content'] = 'S&auml;ilyt&auml; j&auml;senen l&auml;hett&auml;m&auml; sis&auml;lt&ouml;';

$Definition['Label'] = 'Luokitus';
$Definition['Last Active'] = 'Viimeksi';
$Definition['Last IP'] = 'Viimeisin IP';
$Definition['lasts %s'] = 'Kesto %s';
$Definition['Latest %1$s'] = 'Uusin %1$s';
$Definition['Latest Post'] = 'Uusin viesti';
$Definition['Leaders'] = 'Johtajat';
$Definition['Leave %s'] = 'Jätä %s';
$Definition['Leave a Comment'] = 'Vastaa';
$Definition['Leave a comment'] = 'Kommentoi';
$Definition['Leave a redirect link.'] = 'Poistu uudelleenohjatusta linkistä.';
$Definition['Leave blank unless connecting to an existing account.'] = 'Jätä tämä tyhjäksi, ellet ole muodostamassa yhteyttä jo olemassa olevaan käyttäjätiliin.';
$Definition['Leave Comments'] = 'Kommentoi';
$Definition['Leave Conversation'] = 'Poistu keskustelusta';
$Definition['Leave Group'] = 'Poistu ryhmästä';
$Definition['Length'] = 'Pituus';
$Definition['Level %s'] = 'Taso %s';
$Definition['Like'] = 'Tykk&auml;&auml;';
$Definition['Link to content:'] = 'Linkit&auml; sis&auml;lt&ouml;&ouml;n: ';
$Definition['Locale'] = 'Sijainti';
$Definition['Log'] = 'Loki';
$Definition['log'] = 'loki';
$Definition['Login with Facebook'] = 'Kirjaudu Facebook-tunnuksella';

$Definition['Major'] = 'Suuri';
$Definition['Make me invisible? (Will not show you on the list)'] = 'Kirjaudu n&auml;kym&auml;tt&ouml;m&auml;n&auml;? (Tunnuksesi ei n&auml;y online-listassa)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Tee kyselyst&auml; anonyymi (yksitt&auml;isen k&auml;ytt&auml;j&auml;n &auml;&auml;nestysvalintaa ei n&auml;ytet&auml;)';
$Definition['Male'] = 'Mies';
$Definition['Mark All Viewed'] = 'Merkitse kaikki luetuiksi';
$Definition['Mark as Troll'] = 'Merkitse trolliksi';
$Definition['Mark Category Viewed'] = 'Merkitse tämä kategoria katsotuksi';
$Definition['Marking as spam cannot be undone.'] = 'Roskapostiksi merkkaaminen aiheuttaa valitun viestin tai aiheen poiston lopullisesti. T&auml;m&auml; on hyv&auml; tapa pit&auml;&auml; palsta siistin&auml;.';
$Definition['Mark Read'] = 'Merkitse luetuksi';
$Definition['Maybe'] = 'Ehkä';
$Definition['Maybe (%s)'] = 'Ehkä (%s)';
$Definition['Member'] = 'J&auml;sen';
$Definition['Member Count'] = 'Jäsenet';
$Definition['Members'] = 'Jäsenet';
$Definition['Merge'] = 'Yhdist&auml;';
$Definition['Merge Discussions'] = 'Yhdist&auml; keskustelut';
$Definition['Message'] = 'Viesti';
$Definition['message'] = 'viestin';
$Definition['Messages'] = 'Yll&auml;pidon viestit';
$Definition['messages'] = 'viestit';
$Definition['Message to User'] = 'Viesti käyttäjälle';
$Definition['Minor'] = 'Pieni';
$Definition['minutes'] = 'minuuttia';
$Definition['Moderate'] = 'Moderoi';
$Definition['Moderation'] = 'Moderointi';
$Definition['Moderation Queue'] = 'Moderoinnin jono';
$Definition['Moderator'] = 'Moderaattori';
$Definition['Moderator Activity'] = 'Moderaattorien loki';
$Definition['Moderators'] = 'Moderaattorit';
$Definition['moderators'] = 'moderaattorit';
$Definition['months'] = 'kuukautta';
$Definition['More'] = 'Lis&auml;&auml;';
$Definition['More About %s'] = 'Lisätietoa aiheesta %s';
$Definition['More Comments'] = 'Lis&auml;&auml; viestej&auml;';
$Definition['More Discussions'] = 'Lis&auml;&auml; keskusteluita';
$Definition['More Information'] = 'Lis&auml;tietoja';
$Definition['More Results'] = 'Lis&auml;&auml; tuloksia';
$Definition['More…'] = 'Lis&auml;&auml;...';
$Definition['Most Recent'] = 'Uusin';
$Definition['Most recent:'] = 'Uusin:';
$Definition['Most recent: %1$s by %2$s'] = 'Uusin: %1$s %2$s';
$Definition['Most recent by %1$s'] = 'Uusin viesti: %1$s';
$Definition['Most Recent Comment'] = 'Viimeisimmät kommentit.';
$Definition['Move'] = 'Siirrä';
$Definition['MyBadgesModuleTitle'] = 'Kunniamerkkini';
$Definition['My Bookmarks'] = 'Suosikkiaiheeni';
$Definition['My Discussions'] = 'Omat keskustelut';
$Definition['My Drafts'] = 'Omat luonnokset';
$Definition['My Forums'] = 'Omat forumit';
$Definition['My Groups'] = 'Minun ryhmäni';
$Definition['My Preferences'] = 'Ilmoitusten asetukset';
$Definition['My Signature'] = 'Allekirjoitukseni';

$Definition['Name'] = 'Nimi';
$Definition['Name Dropper'] = 'Nimien mainitsija';
$Definition['Name of the Event'] = 'Tapahtuman nimi';
$Definition['Name the Group'] = 'Nimeä ryhmä';
$Definition['Name Unavailable'] = 'Nimi ei saatavilla ';
$Definition['new'] = 'uusi';
$Definition['New %s'] = 'Uusi %s';
$Definition['New Announcement'] = 'Uusi ilmoitus';
$Definition['New Conversation'] = 'Uusi viesti';
$Definition['New Discussion'] = 'Aloita uusi keskustelu';
$Definition['new discussion'] = 'uusi';
$Definition['New Event'] = 'Uusi tapahtuma';
$Definition['New Group'] = 'Uusi ryhmä';
$Definition['New Groups'] = 'Uudet ryhmät';
$Definition['New Message'] = 'Uusi viesti';
$Definition['New Password'] = 'Uusi salasana';
$Definition['New Poll'] = 'Uusi kysely';
$Definition['Next'] = 'Seuraava';
$Definition['Ninth Anniversary'] = 'Yhdeks&auml;s vuosip&auml;iv&auml;';
$Definition['No'] = 'Ei';
$Definition['NoBadgesEarned'] = 'Min&auml; hetken&auml; tahansa&hellip;';
$Definition['No badges yet.'] = 'Ei kunniamerkkej&auml; viel&auml;.';
$Definition['Nobody has confirmed their attendance yet.'] = 'Kukaan ei ole vielä vahvistanut läsnäoloaan.';
$Definition['Nobody has declined the invitation so far.'] = 'Kukaan ei ole vielä kieltäytynyt kutsusta.';
$Definition['Nobody is on the fence right now.'] = 'Kukaan ei ole vielä ilmaissut epävarmuuttaan.';
$Definition['No default roles.'] = 'Ei oletusrooleja.';
$Definition['No discussions were found.'] = 'Keskusteluja ei l&ouml;ytynyt.';
$Definition['No items tagged with %s.'] = 'Tuloksia ei l&ouml;ytynyt tagill&auml; %s.';
$Definition['None'] = 'Ei mit&auml;&auml;n';
$Definition['NoPermissionToDeleteDiscussions'] = 'Sinulla ei ole oikeuksia poistaa %1$s valituista keskusteluista.';
$Definition['No results for \'%s\''] = 'Tuloksia ei l&ouml;ytynyt \'%s\'';
$Definition['No Roles'] = 'Ei rooleja';
$Definition['Not Attending (%s)'] = 'Ei osallistu(%s)';
$Definition['Not Authorized (401)'] = 'Ei sallittu (401)';
$Definition['Not Found (404)'] = 'Ei l&ouml;ytynyt (404)';
$Definition['Notice'] = 'Ilmoitus';
$Definition['Notification'] = 'Ilmoitus';
$Definition['Notification Preferences'] = 'Ilmoitusten asetukset';
$Definition['Notifications'] = 'Ilmoitukset';
$Definition['Notifictions'] = 'Huomatukset';
$Definition['Notify'] = 'Ilmoitus';
$Definition['Notify me of private messages.'] = 'L&auml;het&auml; ilmoitus privaviesteist&auml;.';
$Definition['Notify me when a badge is requested.'] = 'Ilmoita kunniamerkkipyynn&ouml;st&auml;';
$Definition['Notify me when a comment is flagged.'] = 'Ilmoita minulle, kun kommentti on ilmiannettu.';
$Definition['Notify me when I am added to private conversations.'] = 'L&auml;het&auml; ilmoitus kun minut lis&auml;t&auml;&auml;n mukaan privaviestiin uudeksi vastaanottajaksi.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Ilmoita jos joku kommentoi keskusteluja, joissa olen osallistujana.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'L&auml;het&auml; ilmoitus kun suosikkeihin asettamiini keskusteluihin tulee uusi vastaus.';
$Definition['Notify me when people comment on my discussions.'] = 'L&auml;het&auml; ilmoitus kun aloittamaani keskusteluun tulee uusi vastaus.';
$Definition['Notify me when people mention me.'] = 'L&auml;het&auml; ilmoitus kun minut mainitaan keskustelussa.';
$Definition['Notify me when people mention me in comments.'] = 'L&auml;het&auml; ilmoitus kun joku mainitsee minut viestiss&auml;.';
$Definition['Notify me when people reply to my wall comments.'] = 'L&auml;het&auml; ilmoitus kun joku vastaa sein&auml;lle kirjoittamaani kommenttiin.';
$Definition['Notify me when people write on my wall.'] = 'L&auml;het&auml; ilmoitus kun sein&auml;ll&auml;ni on uusi kirjoitus.';
$Definition['Notify me when there is event activity.'] = 'Ilmoita minulle muutoksista tapahtumissa.';
$Definition['Notify me when there is group activity.'] = 'Ilmoita ryhmässä tapahtuneesta toiminnasta.';
$Definition['Not much happening here, yet.'] = 'Ei viel&auml; mit&auml;&auml;n n&auml;ht&auml;v&auml;&auml;. Korjaa tilanne kommentoimalla?';
$Definition['Not Verified'] = 'Vahvistamaton';

$Definition[' now.'] = ' nyt.';

$Definition['Null Date'] = '-';

$Definition['of'] = 'kohteesta';
$Definition['Off Topic'] = 'Aiheen vierestä';
$Definition['Okay'] = 'Ok';
$Definition['OldPassword'] = 'Vanha salasana';
$Definition['Old Password'] = 'Vanha salasana';
$Definition['on'] = 'aika';
$Definition['Online Preferences'] = 'Online-mieltymykset ';
$Definition['Only show followed categories'] = 'N&auml;yt&auml; vain seurantaan asetetut kategoriat';
$Definition['OpenID Settings'] = 'OpenID:n asetukset';
$Definition['Optional'] = 'Valinnainen';
$Definition['Optional Description'] = 'Valinnainen kuvausteksti';
$Definition['Options'] = 'Valinnat';
$Definition['or'] = 'tai';
$Definition['Ordered list'] = 'Järjestetty lista';
$Definition['Organize discussion categories'] = 'J&auml;rjest&auml; keskustelukategoriat';
$Definition['Organizer'] = 'Järjestäjä';
$Definition['Organize your Categories'] = 'Kategorioiden j&auml;rjestely';
$Definition['Original'] = 'Alkuper&auml;inen';
$Definition['Or you can...'] = 'Tai voit...';
$Definition['Other'] = 'Muu';
$Definition['Other Records'] = 'Muut tilastot';
$Definition['Outdent'] = 'Levennys';
$Definition['Owner'] = 'Omistaja';

$Definition['Page'] = 'Sivu';
$Definition['page'] = 'sivu';
$Definition['PageDetailsMessage'] = '%1$s kohteeseen %2$s ';
$Definition['PageDetailsMessageFull'] = '%1$s kohteeseen %2$s kohteesta %3$s ';
$Definition['Page Not Found'] = 'Sivua ei l&ouml;ytynyt';
$Definition['Participated'] = 'Osallistui';
$Definition['ParticipatedHomepageTitle'] = 'Keskustelut joihin osallistunut';
$Definition['Password'] = 'Salasana';
$Definition['Password Contains Username'] = 'Sisältää käyttäjätunnuksen';
$Definition['Password Good'] = 'Hyvä';
$Definition['Password Ok'] = 'Ok';
$Definition['PasswordRequest'] = 'Hi %1$s,

Someone has requested to reset your password at %2$s. To reset your password, follow this link:

  %3$s

If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = 'Salasanat eiv&auml;t t&auml;sm&auml;&auml;';
$Definition['Password Strong'] = 'Vahva';
$Definition['Password Too Short'] = 'Liian lyhyt';
$Definition['Password Very Weak'] = 'Todella heikko';
$Definition['Password Weak'] = 'Heikko';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Liitä kuvan URL-osoite upottaaksesi se nopeasti sivulle. ';
$Definition['Pending'] = 'Odottaa vahvistusta';
$Definition['Permalink'] = 'Kestolinkki';
$Definition['permalink'] = '&nbsp;|&nbsp;kestolinkki';
$Definition['Permanent (301)'] = 'Pysyv&auml; (301)';
$Definition['PermissionErrorMessage'] = 'Sinulla ei ole oikeuksia valittuun toimintoon.';
$Definition['PermissionErrorTitle'] = 'Ongelma k&auml;ytt&auml;j&auml;oikeuksissa';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Tarvitset moderaattorin oikeudet suorittaaksesi valitun toiminnon.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Tarvitset yll&auml;pidon oikeudet suorittaaksesi valitun toiminnon.';
$Definition['PermissionRequired.Javascript'] = 'Sinun pit&auml;&auml; sallia javascript ensin.';
$Definition['Photogenic'] = 'Valokuvauksellinen';
$Definition['Picture'] = 'Kuva';
$Definition['Pin'] = 'Kiinnitä';
$Definition['Pinned'] = 'Kiinnitetty';
$Definition['Play the sound again'] = 'Soita ääni uudestaan';
$Definition['Please join my group.'] = 'Liittyisitkö ryhmääni <a href="{Url,html}">group</a>? ';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Odota kun sinut uudelleenohjataan. Voit my&ouml,s klikata  <a href="%s">t&auml;st&auml;</a>.';
$Definition['Points'] = 'Pisteet';
$Definition['Poll'] = 'Aiheeseen liittyv&auml; kysely';
$Definition['Poll Options'] = 'Vastausvaihtoehdot';
$Definition['Poll Question'] = 'Kysymys';
$Definition['Popular'] = 'Suosittu';
$Definition['Popular Discussions'] = 'Suositut keskustelut';
$Definition['Popular Groups'] = 'Suositut ryhmät';
$Definition['Popular Tags'] = 'Suositut tagit';
$Definition['Popup'] = 'Popup-kuvake';
$Definition['Position'] = 'Asema';
$Definition['Post'] = 'Viesti';
$Definition['post'] = 'viesti';
$Definition['Post Comment'] = 'L&auml;het&auml;';
$Definition['Post Discussion'] = 'L&auml;het&auml; uusi kysymys';
$Definition['Post edited by %1$s at %2$s'] = 'Viesti&auml; on muokannut %1$s, %2$s';
$Definition['Posts'] = 'Viestej&auml;';
$Definition['Posts.Plural: %s'] = 'Viestej&auml;: %s';
$Definition['Posts.Singular: %s'] = 'Viestej&auml;: %s';
$Definition['Posts: %s'] = 'Viestej&auml;: %s';
$Definition['Post this anonymously'] = 'L&auml;het&auml; t&auml;m&auml; anonyymin&auml;';
$Definition['Powered by %s'] = 'Tuottajana %s';
$Definition['Powered by Vanilla'] = 'Vanillan tarjoama';
$Definition['PreferenceBadgeEmail'] = 'L&auml;het&auml; ilmoitus kun saan uuden kunniamerkin.';
$Definition['PreferenceBadgePopup'] = 'L&auml;het&auml; ilmoitus kun saan uuden kunniamerkin.';
$Definition['Preferences'] = 'Asetukset';
$Definition['Preview'] = 'Esikatselu';
$Definition['Previous'] = 'Edellinen';
$Definition['Privacy'] = 'Yksityisyys';
$Definition['Privacy Settings'] = 'Yksityisyysasetukset';
$Definition['Private'] = 'Yksityinen';
$Definition['Private group.'] = 'Kuka tahansa voi liittyä ryhmään, mutta vain jäsenet näkevät sen sisällön. Mahdollisten jäsenten täytyy joko hakea ryhmään tai heidät täytyy kutsua siihen.';
$Definition['Private Note for Moderators'] = 'Yksityinen viesti moderaattoreille';
$Definition['Problem with credentials.'] = 'Ongelma tunnusten kanssa.';
$Definition['Proceed'] = 'Jatka';
$Definition['Profile'] = 'Profiili';
$Definition['Profile Fields'] = 'Profiilin kent&auml;t';
$Definition['Profile  Fields'] = 'Profiilin   kent&auml;t';
$Definition['ProfileFieldsCustomDescription'] = 'K&auml;yt&auml; n&auml;it&auml; kentti&auml; luodaksesi profiileihin paikkoja lis&auml;tiedoille. Voit asettaa kentti&auml; tiedoille kuten "Parisuhdestatus", "Skype", tai mit&auml; haluatkin! Luovuus on sallittua! ';
$Definition['Profile Page'] = 'profiilisivu';
$Definition['Profile Picture'] = 'Profiilin kuva';
$Definition['Profiles'] = 'Profiilit';
$Definition['Promote'] = 'Promotoi';
$Definition['Public'] = 'Julkinen';
$Definition['Public group.'] = 'Kuka tahansa voi nähdä tämän ryhmän ja sen sisällön. Kuka tahansa voi liittyä ryhmään.';

$Definition['Q&A'] = 'Kysymykset & vastaukset';
$Definition['Q&A Accepted'] = 'Vastattu ✓';
$Definition['Q&A Answered'] = 'Vastattu';
$Definition['Q&A Options'] = 'Q&A asetukset';
$Definition['Q&A Question'] = 'Kysymys';
$Definition['QnA Accepted Answer'] = 'Vastaus ✓';
$Definition['QnA Rejected Answer'] = 'Hyl&auml;tty vastaus';
$Definition['Question'] = 'Kysymys';
$Definition['question'] = 'kysymys';
$Definition['Questions'] = 'Kysymykset';
$Definition['questions'] = 'kysymykset';
$Definition['Question Title'] = 'Kysymyksen otsikko';
$Definition['Quote'] = 'Lainaus';
$Definition['Quote Folding'] = 'Lainausten ketjutus';
$Definition['Quote on'] = '@';
$Definition['Quote Settings'] = 'Lainausten asetukset';
$Definition['Quote wrote'] = 'kirjoitti';

$Definition['Rank'] = 'Arvo';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were} ylennettiin asemaan {Data.Name,plaintext}. ';
$Definition['Ranks.NotificationFormat'] = 'Onneksi olkoon! Sinut on ylennetty asemaan {Data.Name,plaintext}. ';
$Definition['Re: %s'] = 'Liittyen: %s';
$Definition['Reaction'] = 'Reaktio';
$Definition['Reactions'] = 'Reaktiot';
$Definition['Read the full story here'] = 'Lue koko tarina täältä';
$Definition['Real Name'] = 'Oikea nimi';
$Definition['Reason'] = 'Syy';
$Definition['Reason (optional)'] = 'Syy (valinnainen)';
$Definition['Recent'] = 'Viimeaikainen';
$Definition['Recent Activity'] = 'Forumin sy&ouml;te';
$Definition['Recent Admin Activity'] = 'Viimeisimm&auml;t yll&auml;pidon toimet';
$Definition['Recent Discussions'] = 'Uusimmat viestit';
$Definition['Recent Events'] = 'Viimeaikaiset tapahtumat';
$Definition['recently'] = 'hiljattain';
$Definition['Recent Moderator Activity'] = 'Viimeisimm&auml;t moderaatorien toimet';
$Definition['Recent Tutorials'] = 'Uusimmat oppaat';
$Definition['Recipients'] = 'Vastaanottajat';
$Definition['RecipientUserID'] = 'vastaanottaja';
$Definition['Redirecting...'] = 'Uudelleenohjataan...';
$Definition['Refetch Page'] = 'Nouda sivu uudestaan';
$Definition['Register'] = 'Rekister&ouml;idy';
$Definition['Register IP'] = 'Rekist. IP';
$Definition['Register with %s'] = 'Rekister&ouml;idy';
$Definition['Registration  Fields'] = 'Rekister&ouml;itymisen  kent&auml;t';
$Definition['Registration URL'] = 'Rekister&ouml;itymisen URL';
$Definition['Reject'] = 'Hylk&auml;&auml;';
$Definition['Reject this answer.'] = 'Hylk&auml;&auml; t&auml;m&auml; vastaus.';
$Definition['Remember me'] = 'Muista minut';
$Definition['Remember me on this computer'] = 'Muista minut t&auml;ll&auml; koneella';
$Definition['Remote Configuration'] = 'Et&auml;asetukset';
$Definition['Remove'] = 'Poista';
$Definition['Removed by'] = 'Poistajana ';
$Definition['Remove from %s'] = 'Poista kohteesta %s';
$Definition['Remove Invitation'] = 'Poista kutsu';
$Definition['Remove My Picture'] = 'Poista kuvasi';
$Definition['Remove Picture'] = 'Poista kuva';
$Definition['Remove Warning'] = 'Poista varoitus';
$Definition['Rename Forum'] = 'Uudelleennime&auml; forum';
$Definition['Reopen'] = 'Avaa uudelleen';
$Definition['Replies'] = 'Vastauksia';
$Definition['Reply'] = 'Vastaa';
$Definition['ReplyOnly'] = 'Voit vastata tähän sähköpostiin seurataksesi sen lähdettä. Lähettäjänä {/,exurl}. ';
$Definition['ReplyOrFollow'] = 'Nähdäksesi lisää joko vastaa suoraan tähän sähköpostiin tai seuraa alla olevaa linkkiä:';
$Definition['Report'] = 'Raportoi';
$Definition['Report %s'] = 'Raportoi %s';
$Definition['Reported'] = 'Raportoitu';
$Definition['Reported by: '] = 'Raportoijana: ';
$Definition['Reported Posts'] = 'Raportoidut viestit';
$Definition['Report Notes'] = 'Muistiinpanot';
$Definition['Report Reason'] = 'Syy';
$Definition['Reputation'] = 'Maine';
$Definition['Request a new password'] = 'Pyyd&auml; uusi salasana';
$Definition['Request a new password →'] = 'Pyyd&auml; uusi salasana →';
$Definition['Request another password reset.'] = 'Pyydä toista salasanan nollausta.';
$Definition['Reset Password'] = 'Nollaa salasana';
$Definition['Reset Your Password'] = 'Uudista salasanasi';
$Definition['Restore'] = 'Palauta';
$Definition['Restored'] = 'Palautettu';
$Definition['reverse'] = 'peruuta';
$Definition['Revoke'] = 'Peru';
$Definition['Revoked'] = 'Poistettu';
$Definition['Revoked badge.'] = 'Peruttu kunniamerkki';
$Definition['role'] = 'rooli';
$Definition['RoleID'] = 'rooli';
$Definition['Roles'] = 'Roolit';
$Definition['roles'] = 'roolit';
$Definition['RSS Feed'] = 'RSS-syöte';
$Definition['RSVP'] = 'Vastausta';

$Definition['Save'] = 'Tallenna';
$Definition['Save Comment'] = 'Tallenna viesti';
$Definition['Saved'] = 'Muutokset tallennettiin.';
$Definition['Save Draft'] = 'Tallenna luonnos';
$Definition['Save Poll'] = 'Tallenna kysely';
$Definition['Save Preferences'] = 'Tallenna asetukset';
$Definition['Save your password'] = 'Tallenna salasanasi';
$Definition['Search'] = 'Haku';
$Definition['Search %s'] = 'Etsi %s';
$Definition['search archived'] = 'haku arkistoitu';
$Definition['SearchBoxPlaceHolder'] = 'Haku';
$Definition['Search for a tag.'] = 'Etsi koko tagia tai osaa siit&auml;.';
$Definition['Search results for \'%s\''] = 'Tulokset haulla \'%s\'';
$Definition['search subcategories'] = 'etsi alakategorioita';
$Definition['Second Anniversary'] = 'Toinen vuosip&auml;iv&auml;';
$Definition['Secret'] = 'Salainen';
$Definition['Sections'] = 'Osiot';
$Definition['Security Check'] = 'Turvallisuustarkastus';
$Definition['Select a %s'] = 'Valitse %s';
$Definition['Select a category...'] = 'Valitse kategoria...';
$Definition['Select an image on your computer (2mb max)'] = 'Valitse siirrett&auml;v&auml; kuva (2mb max)';
$Definition['Select one of the following avatars:'] = 'Valitse yksi seuraavista profiilikuvista:';
$Definition['Send'] = 'Lähetä';
$Definition['Send a New Message'] = 'L&auml;het&auml; uusi viesti';
$Definition['Send Message'] = 'L&auml;het&auml; viesti';
$Definition['Send Report'] = 'Raportoi';
$Definition['Send report'] = 'Raportoi';
$Definition['sep and'] = 'ja';
$Definition['Set a New Warning Level'] = 'Aseta uusi varoitustaso';
$Definition['Set A Password'] = 'Aseta salasana';
$Definition['Setting'] = 'Asetus';
$Definition['Settings'] = 'Asetukset';
$Definition['Seventh Anniversary'] = 'Seitsem&auml;s vuosip&auml;iv&auml;';
$Definition['Severity'] = 'Vakavuus';
$Definition['Share'] = 'Jaa';
$Definition['Shared Accounts'] = 'Jaetut k&auml;ytt&auml;j&auml;tilit';
$Definition['she'] = 'h&auml;n';
$Definition['Shown only on mobile'] = 'N&auml;yt&auml; vain mobiilissa';
$Definition['Show unfollowed categories'] = 'N&auml;yt&auml; kategoriat joita en ole asettanut seurantaan.';
$Definition['Sign-In URL'] = 'Sis&auml;&auml;nkirjautumisen URL';
$Definition['Sign-Out URL'] = 'Uloskirjautumisen URL';
$Definition['Signature'] = 'Allekirjoitus';
$Definition['Signature Code'] = 'Allekirjoituksesi';
$Definition['Signature invalid.'] = 'Allekirjoitus on virheellinen.';
$Definition['Signatures'] = 'Allekirjoitukset';
$Definition['Signatures can be up to {maxLength} characters long.'] = 'Allekirjoitukset voivat olla korkeintaan {maxLength} merkkiä pitkiä.';
$Definition['Signature Settings'] = 'Allekirjoituksen asetus';
$Definition['SignIn'] = 'Kirjaudu';
$Definition['Sign In'] = 'Kirjaudu sis&auml;&auml;n';
$Definition['SigningOut'] = 'Odota hetki kun sinut kirjataan ulos.';
$Definition['Sign In Now'] = 'Kirjaudu sisään välittömästi';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Kirjaudu sis&auml;&auml;n</a> tai <a href="{RegisterUrl,html}">Rekister&ouml;idy</a> kommentoidaksesi.';
$Definition['Sign in to vote!'] = 'Kirjaudu sis&auml;&auml;n &auml;&auml;nest&auml;&auml;ksesi!';
$Definition['Sign In with %s'] = 'Kirjaudu sis&auml;&auml;n tunnuksella %s';
$Definition['Sign In with Disqus'] = 'Kirjaudu Disqus -tunnuksella';
$Definition['Sign In with Facebook'] = 'Kirjaudu Facebook -tunnuksellasi';
$Definition['Sign In with Google'] = 'Kirjaudu Google -tunnuksella';
$Definition['Sign In with OpenID'] = 'Kirjaudu OpenID -tunnuksella';
$Definition['Sign In with Twitter'] = 'Kirjaudu Twitter -tunnuksella';
$Definition['Sign Out'] = 'Kirjaudu ulos';
$Definition['sign out'] = 'Kirjaudu ulos';
$Definition['Sign Up'] = 'Kirjaudu';
$Definition['Sink'] = 'Upota';
$Definition['Sink this discussion'] = 'Upota t&auml;m&auml; keskustelu';
$Definition['Site'] = 'Sivusto';
$Definition['Sitemap Settings'] = 'Sivukartan asetukset';
$Definition['Sites'] = 'Sivustot';
$Definition['Sixth Anniversary'] = 'Kuudes vuosip&auml;iv&auml;';
$Definition['Social'] = 'Sosiaalinen';
$Definition['somebody'] = 'joku';
$Definition['Some Code'] = 'Esimerkkikoodi';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Kysymykseesi on tullut vastaus! Ole hyv&auml; ja hyv&auml;ksy tai hylk&auml;&auml; se.';
$Definition['sorted by'] = 'j&auml;rjestysperuste';
$Definition['Source'] = 'L&auml;hde';
$Definition['Source:'] = 'L&auml;hde:';
$Definition['Source Code'] = 'Koodi';
$Definition['Spam'] = 'Roskaviesti';
$Definition['Spam Queue'] = 'Roskaviestien moderointijono';
$Definition['Split'] = 'Jaa osiin';
$Definition['Split Comments'] = 'Jaa kommentit osiin';
$Definition['Spoiler'] = 'Spoileri';
$Definition['Spoof User'] = 'Testik&auml;ytt&auml;j&auml;';
$Definition['Start'] = 'Aloita';
$Definition['Start a Group'] = 'Perusta ryhmä';
$Definition['Start a New Conversation'] = 'L&auml;het&auml; uusi viesti';
$Definition['Start a New Discussion'] = 'Aloita uusi keskustelu';
$Definition['Start Conversation'] = 'L&auml;het&auml;';
$Definition['Started By'] = 'Aloittanut';
$Definition['Started by'] = 'Aloittajana toimi';
$Definition['Started by %1$s'] = 'Aloittanut %1$s';
$Definition['Start your First Discussion'] = 'Aloita ensimm&auml;inen keskustelusi';
$Definition['Stop following'] = 'Poista seuranta';
$Definition['Strikethrough'] = 'Läpimurto';
$Definition['Strip images out of signatures'] = '&Auml;l&auml; n&auml;yt&auml; kuvia allekirjoituksissa';
$Definition['Strip images out of signatures?'] = '&Auml;l&auml; n&auml;yt&auml; kuvia allekirjoituksissa?';
$Definition['Subject'] = 'Aihe';
$Definition['Subscriber'] = 'Tilaaja';
$Definition['Success'] = 'Onnistui';
$Definition['Suggested Value'] = 'Ehdotettu arvo';
$Definition['System'] = 'J&auml;rjestelm&auml;';

$Definition['Tagged'] = 'Tagit';
$Definition['Tagged with '] = 'Tagit:  ';
$Definition['Tagged with "%s"'] = 'Tagi "%s"';
$Definition['Tagging'] = 'Taggaaminen';
$Definition['TagHint'] = 'Aloita kirjoittaminen...';
$Definition['Tag Name'] = 'Tagin nimi';
$Definition['Tags'] = 'Tagit';
$Definition['tags'] = 'tägit';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Tagit ovat avainsanoja joita k&auml;ytt&auml;j&auml;t voivat lis&auml;t&auml; keskusteluihin helpottaakseen niiden l&ouml;ydett&auml;vyytt&auml; ja luokittelua vastaavien keskustelujen kanssa. ';
$Definition['Take Action'] = 'Valitse toiminto';
$Definition['Take Action:'] = 'Valitse toiminto:';
$Definition['Target'] = 'Kohde';
$Definition['Tell the user why you\'re warning them'] = 'Kerro k&auml;ytt&auml;j&auml;lle syy varoitukseen';
$Definition['Tell us why you want to join!'] = 'Kerro meille miksi haluat liitty&auml;.';
$Definition['Tenth Anniversary'] = 'Kymmenes vuosip&auml;iv&auml;';
$Definition['Terms'] = 'Ehdot';
$Definition['TermsOfService'] = 'K&auml;ytt&ouml;ehdot ja s&auml;&auml;nn&ouml;t';
$Definition['Terms of Service'] = 'K&auml;ytt&ouml;ehdot';
$Definition['TermsOfServiceText'] = '
   <p>You agree, through your use of this service, that you will not use this
   community to post any material which is knowingly false and/or defamatory,
   inaccurate, abusive, vulgar, hateful, harassing, obscene, profane, sexually
   oriented, threatening, invasive of a person\'s privacy, or otherwise violative
   of any law. You agree not to post any copyrighted material unless the
   copyright is owned by you.</p>
   
   <p>We at this community also reserve the right to reveal your identity (or
   whatever information we know about you) in the event of a complaint or legal
   action arising from any message posted by you. We log all internet protocol
   addresses accessing this web site.</p>
   
   <p>Please note that advertisements, chain letters, pyramid schemes, and
   solicitations are inappropriate on this community.</p>
   
   <p>We reserve the right to remove any content for any reason or no reason at
   all. We reserve the right to terminate any membership for any reason or no
   reason at all.</p>
   
   <p>You must be at least 13 years of age to use this service.</p>
';
$Definition['Test'] = 'Testi';
$Definition['Testing'] = 'Testaus';
$Definition['Text'] = 'Teksti';
$Definition['Text  Max  Length'] = 'Tekstin  maksimi  pituus';
$Definition['Thank You!'] = 'Kiitokset!';
$Definition['The %s has been deleted.'] = ' %s on poistettu.';
$Definition['The %s has been flagged for moderation.'] = '%s on merkitty tarkastettavaksi.';
$Definition['The %s you were looking for could not be found.'] = 'Etsimääsi kohdetta %s ei löytynyt.';
$Definition['the category'] = 'kategoria';
$Definition['The content you were looking for has been deleted.'] = 'Etsimäsi sisältö on poistettu.';
$Definition['The conversation has been cleared.'] = 'T&auml;m&auml; keskustelu on tyhjennetty.';
$Definition['The CSRF token is invalid.'] = 'CSRF-tarkiste on virheellinen.';
$Definition['The email you entered in use by another member.'] = 'S&auml;hk&ouml;postiosoite jonka annoit, on jo palstalla k&auml;yt&ouml;ss&auml;.';
$Definition['The email you have entered is already related to an existing account.'] = 'S&auml;hk&ouml;postiosoite jonka annoit, on jo palstalla k&auml;yt&ouml;ss&auml; yhdistettyn&auml; toiseen k&auml;ytt&auml;j&auml;tunnukseen.';
$Definition['The file failed to upload.'] = 'Tiedoston siirto ep&auml;onnistui.';
$Definition['their'] = 'heid&auml;n';
$Definition['The name you entered is already in use by another member.'] = 'K&auml;ytt&auml;j&auml;tunnus jonka annoit, on jo rekister&ouml;ityn&auml; palstan j&auml;senelle.';
$Definition['The page you were looking for could not be found.'] = 'Etsim&auml;&auml;si sivua ei l&ouml;ytynyt.';
$Definition['The quote had to be converted from %s to %s.'] = 'Lainaus täytyi muuttaa muodosta %s muotoon %s. Tietoja on saattanut hävitä prosessin aikana.';
$Definition['There\'s already a %s with the name %s.'] = '%1$s nimellä %2$s on jo olemassa.';
$Definition['There aren\'t any groups yet.'] = 'Yhtään ryhmää ei ole vielä luotu.';
$Definition['There are no tags in the system yet.'] = 'J&auml;rjestelm&auml;ss&auml; ei ole yht&auml;&auml;n tageja viel&auml;.';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'ReCAPTCHA-kent&auml;n arvo oli v&auml;&auml;rin. Yrit&auml; uudestaan.';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Tili samalla k&auml;ytt&auml;j&auml;nimellä (%1$s) tai s&auml;hk&ouml;postiosoitteella (%2$s) on jo olemassa. Voit joko luoda uuden tilin tai voit kirjautua sis&auml;&auml;n olemassa olevaan tiliin.';
$Definition['The response was not in the correct format.'] = 'Vastaus annettiin v&auml;&auml;r&auml;ss&auml; muodossa';
$Definition['There was an error connecting to Disqus'] = 'Disqusiin yhdist&auml;minen ep&auml;onnistui';
$Definition['There was an error connecting to Facebook'] = 'Facebookiin yhdist&auml;minen ep&auml;onnistui';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Tiedoston siirto ep&auml;onnistui. Todenn&auml;k&ouml;isin syy siihen on tiedoston liian suuri koko.';
$Definition['The site is currently undergoing maintenance.'] = 'Sivusto on t&auml;ll&auml; hetkell&auml; huoltotilassa.';
$Definition['The uploaded file was too big (max %s).'] = 'Tiedosto jota yritettiin ladata, on liian suuri (max %s).';
$Definition['The user has already been warned for this %s.'] = 'Käyttäjää on jo varoitettu aiheesta %s.';
$Definition['The user isn\'t banned.'] = 'Käyttäjää ei ole estetty tai hänet on estetty jonkin toisen toiminnon perusteella.';
$Definition['they'] = 'he';
$Definition['Third Anniversary'] = 'Kolmas vuosip&auml;iv&auml;';
$Definition['This answer was %s.'] = 'T&auml;m&auml; vastaus on %s.';
$Definition['This answer was Accepted.'] = 'Vastaus hyv&auml;ksyttiin.';
$Definition['This discussion has been closed.'] = 'T&auml;m&auml; keskustelu on suljettu.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'T&auml;m&auml; keskustelu liittyy m&auml;&auml;rittelem&auml;tt&ouml;m&auml;&auml;n vieraaseen keskustelusis&auml;lt&ouml;&ouml;n';
$Definition['This discussion was created from comments split from: %s.'] = 'T&auml;m&auml; uusi keskustelu luotiin viesteist&auml; jotka l&auml;hetettiin alkujaan aiheeseen %s.';
$Definition['This discussion was merged into %s'] = 'Keskustelu yhdistettiin aiheeseen %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Kuva on pienenetty automaattisesti. Klikkaa kuvaa n&auml;hd&auml;ksesi sen suuremmassa koossa.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'T&auml;m&auml; on yksityinen kysely: Muut eiv&auml;t n&auml;e, mit&auml; &auml;&auml;nestit';
$Definition['This is a public poll: others will see what you voted for.'] = 'T&auml;m&auml; on julkinen kysely: Muut n&auml;kev&aumlt;, mit&auml; &auml;&auml;nestit';
$Definition['This is a system account and does not represent a real person.'] = 'T&auml;m&auml; on j&auml;rjestelm&auml;n luoma k&auml;ytt&auml;j&auml;tili';
$Definition['This Month\'s Leaders'] = 'T&auml;m&auml;n kuukauden johtajat';
$Definition['This question\'s answer has been accepted.'] = 'Vastaus kysymykseen on hyv&auml;ksytty.';
$Definition['This user has been verified as a non-spammer.'] = 'T&auml;m&auml; j&auml;sen on vahvistettu ei-roskapostittajaksi.';
$Definition['This user has not been verified as a non-spammer.'] = 'J&auml;sent&auml; ei ole vahvistettu ei-roskapostittajaksi';
$Definition['This user has not commented yet.'] = 'K&auml;ytt&auml;j&auml; ei ole viel&auml; l&auml;hett&auml;nyt yht&auml;&auml;n viesti&auml;.';
$Definition['This user has not made any discussions yet.'] = 'K&auml;ytt&auml;j&auml; ei ole viel&auml; aloittanut yht&auml;&auml;n keskustelua.';
$Definition['This user is also banned for other reasons and may stay banned.'] = 'Tämä käyttäjä on estetty myös muista syistä ja saattaa pysyä estettynä.';
$Definition['This user is verified as a non-spammer'] = 'J&auml;sen on vahvistettu ei-roskapostittajaksi';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'T&auml;m&auml; varoitus on rauennut. Haluatko poistaa sen kokonaan?';
$Definition['This Week\'s Leaders'] = 'T&auml;m&auml;n viikon johtajat';
$Definition['Thumbnail'] = 'Pikkukuva';
$Definition['Title'] = 'Otsikko';
$Definition['To'] = 'Vastaanottaja';
$Definition['Toggle full page'] = 'Laita koko sivun näyttö päälle';
$Definition['Toggle HTML view'] = 'Siirry HTML-tilaan';
$Definition['Toggle lights'] = 'Säädä valot';
$Definition['Topic'] = 'Aihe';
$Definition['Topics'] = 'Aiheet';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'L&auml;hett&auml;&auml;ksesi vahvistuss&auml;hk&ouml;postin  uudelleen, klikkaa <a href="%s">t&auml;st&auml;</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'K&auml;ytt&auml;&auml;ksesi reCAPTCHA:aa sinulla pit&auml;&auml; olla ainakin yksi API avain palvelusta %s';
$Definition['Transport error: %s'] = 'Valitsemasi toiminnon toteuttamisessa tapahtui vakava virhe. <br /> Palvelin palautti seuraavan vastauksen: %s ';
$Definition['Troll'] = 'Trolli';
$Definition['Try Again'] = 'Yrit&auml; uudelleen';
$Definition['Turn ON'] = 'Ota k&auml;ytt&ouml;&ouml;n';
$Definition['Twitter Settings'] = 'Twitterin asetukset';
$Definition['Type'] = 'Tyyppi';
$Definition['Type the text:'] = 'Kirjoita teksti:';
$Definition['Type what you hear:'] = 'Kirjoita kuulemasi:';

$Definition['Unable to send message, %s is ignoring you.'] = 'Viestin lähettäminen ei onnistunut, %s on jättänyt viestisi huomioimatta.';
$Definition['Unannounce'] = 'Poista huomioitavista';
$Definition['Unanswered'] = 'Vastaamaton';
$Definition['Unanswered Questions'] = 'Vastaamaton';
$Definition['unavailable'] = 'Ei saatavilla';
$Definition['Unban'] = 'Peru esto';
$Definition['Unban User'] = 'Peru j&auml;senen esto';
$Definition['Unbookmark'] = 'Poista suosikeista';
$Definition['Undefined discussion body.'] = 'Viestist&auml; puuttuu sis&auml;lt&ouml;.';
$Definition['Undefined discussion subject.'] = 'Viestist&auml; puuttuu otsikko.';
$Definition['Undefined foreign content'] = 'M&auml;&auml;rittelem&auml;t&ouml;n vieras sis&auml;lt&ouml;';
$Definition['Undo Follow'] = 'Peru seuranta';
$Definition['Unfollow'] = 'Poista seurannasta';
$Definition['Unhide'] = 'Poista piilotetuista';
$Definition['Unignore'] = 'Näe käyttäjän viestit';
$Definition['UniqueID'] = 'AinutlaatuinenID';
$Definition['Unknown'] = 'Tuntematon';
$Definition['unknown'] = 'tuntematon';
$Definition['Unknown client: %s.'] = 'Tuntematon asiakas: %s.';
$Definition['Unordered list'] = 'Tilaamaton lista';
$Definition['Unread'] = 'Ei luetut';
$Definition['Unread Discussions'] = 'Ei luetut keskustelut';
$Definition['Unsink'] = 'Poista upotetuista';
$Definition['Unspecified'] = 'M&auml;&auml;ritt&auml;m&auml;t&ouml;n';
$Definition['Upcoming Events'] = 'Tulevat tapahtumat';
$Definition['Update'] = 'P&auml;ivit&auml;';
$Definition['Updated badge'] = 'Kunniamerkki p&auml;ivitettiin';
$Definition['Upload'] = 'Lataa';
$Definition['Uploading...'] = 'Ladataan...';
$Definition['UrlCode'] = 'Urlin koodi';
$Definition['Use My Current Password'] = 'K&auml;yt&auml; nykyist&auml; salasanaani';
$Definition['User'] = 'K&auml;ytt&auml;j&auml;';
$Definition['User "%s" does not exist.'] = 'K&auml;ytt&auml;j&auml;&auml; "%s" ei ole olemassa.';
$Definition['Username'] = 'Tunnus';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'K&auml;ytt&auml;j&auml;tunnus voi sis&auml;lt&auml; vain kirjaimia, numeroita ja alaviivoja.';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'K&auml;ytt&auml;j&auml;tunnusten pit&auml;&auml; olla 3-20 merkki&auml; pitki&auml;, ja ne voivat muodustua merkeist&auml; sis&auml;lt&auml;en kirjaimia, numeroita ja alaviivoja.';
$Definition['UsernameError'] = 'Tunnukset voivat sis&auml;lt&auml;&auml vain kirjaimia, numeroita ja alaviivoja. K&auml;ytt&auml;j&auml;tunnuksen pituuden on oltava 3-20 merkki&auml;.';
$Definition['Username or email'] = 'K&auml;ytt&auml;j&auml;tunnus tai s&auml;hk&ouml;postiosoite';
$Definition['User not found.'] = 'Pahoittelut, antamallasi s&auml;hk&ouml;postiosoitteella tai k&auml;ytt&auml;j&auml;tiedoilla ei l&ouml;ytynyt tunnusta.';
$Definition['Users'] = 'J&auml;senet';
$Definition['Users Count'] = 'K&auml;ytt&auml;ji&auml; yhteens&auml;';
$Definition['Use up to {maxImages,plural,%s image, %s images}.'] = 'Käytä korkeintaan {maxImages,monikko,%s kuva, %s kuvaa}.';

$Definition['ValidateBanned'] = 'Toiminto %s ei ole sallittu.';
$Definition['ValidateBoolean'] = '%s ei ole kelvollinen muuttuja.';
$Definition['ValidateConnection'] = 'Yhdist&auml;minen tietokantaan ep&auml;onnistui antamillasi tiedoilla. Tietokanta vastasi antaen seuraavan virheen: <code>%s</code>';
$Definition['ValidateDate'] = '%s ei ole kelvollinen p&auml;iv&auml;ys.';
$Definition['ValidateDecimal'] = '%s ei ole kelvollinen desimaali.';
$Definition['ValidateEmail'] = '%s ei ole kelvollinen.';
$Definition['ValidateEnum'] = '%s ei kelpaa.';
$Definition['ValidateFormat'] = 'Et voi l&auml;hett&auml;&auml; raakamuodossa olevaa HTML -koodia.';
$Definition['ValidateInteger'] = '%s ei ole kelvollinen kokonaisluku.';
$Definition['ValidateIntegerArray'] = '%s pit&auml;&auml; olla pilkuilla toisistaan erotettuna listana numeroita. ';
$Definition['ValidateLength'] = '%1$s on %2$s merkki&auml; liian pitk&auml;.';
$Definition['ValidateMatch'] = ' %s -kent&auml;t eiv&auml;t t&auml;sm&auml;&auml;.';
$Definition['ValidateMinimumAge'] = 'Olet liian nuori liittyäksesi tähän ryhmään.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Sinun pit&auml;&auml; valita ensin ainakin yksi %s.';
$Definition['ValidateRegex'] = '%s ei ole oikeassa muodossa. ';
$Definition['ValidateRequired'] = '%s on vaadittu.';
$Definition['ValidateRequiredArray'] = 'Sinun pit&auml;&auml; valita ensin ainakin yksi %s.';
$Definition['ValidateString'] = '%s ei ole kelpaava merkkijono.';
$Definition['ValidateTag'] = 'Yksitt&auml;inen tagi ei voi sis&auml;lt&auml;&auml;  v&auml;lily&ouml;nti&auml;.';
$Definition['ValidateTime'] = '%s on virheellinen aika.';
$Definition['ValidateTimestamp'] = '%s on virheellinen aikaleima.';
$Definition['ValidateUrl'] = 'Kenttä %s ei ole kelvollinen Internet-osoite.';
$Definition['ValidateUrlStringRelaxed'] = '%s ei voi sis&auml;lt&auml;&auml; viivoja, lainauksia tai tageiss&auml; k&auml;ytettyj&auml; merkkej&auml;.';
$Definition['ValidateUsername'] = 'K&auml;ytt&auml;j&auml;tunnusten pit&auml;&auml; olla 3-20 merkki&auml; pitki&auml;, ja ne voivat muodustua merkeist&auml; sis&auml;lt&auml;en kirjaimia, numeroita ja alaviivoja.';
$Definition['ValidateVersion'] = '%s ei ole käypä versionumero. Käytä php version_compare()-funktiota nähdäksesi esimerkkejä käyvistä versionumeroista. ';
$Definition['Value'] = 'Arvo';
$Definition['Vanilla Statistics'] = 'Vanillan statistiikat';
$Definition['Vanilla Statistics Plugin'] = 'Vanillan statistiikka-lis&auml;osa';
$Definition['Verified'] = 'Vahvistettu';
$Definition['Verifying your credentials...'] = 'Tarkistetaan tietoja...';
$Definition['via %s'] = '%s kautta';
$Definition['Video embedding has been disabled.'] = 'Videon upotusmahdollisuus tiedostoon on poissa päältä. URL-osoitteet eivät käänny upotusvastineikseen. ';
$Definition['View Badge'] = 'N&auml;yt&auml; kunniamerkki';
$Definition['Viewing'] = 'Näytetään';
$Definition['Views'] = 'Luettu';
$Definition['Visible'] = 'N&auml;kyv&auml;';
$Definition['Visits'] = 'K&auml;yntej&auml;';
$Definition['Visit Site'] = 'Forumin etusivulle';
$Definition['Vote'] = '&Auml;&auml;nest&auml;';
$Definition['Vote Down'] = '&Auml;&auml;nest&auml; alas';
$Definition['Votes'] = '&Auml;&auml;ni&auml;';
$Definition['Vote Up'] = '&Auml;&auml;nest&auml; yl&ouml;s';

$Definition['wall'] = 'sein&auml;';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Haluatko osallistua n&auml;ihin keskusteluihin? Klikkaa yht&auml; n&auml;ist&auml;:';
$Definition['Warn'] = 'Varoita';
$Definition['Warn %s'] = 'Varoita %s';
$Definition['Warned for'] = 'Varoitus rikkeestä';
$Definition['Warning'] = 'Varoitus';
$Definition['Warnings'] = 'Varoitukset';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} varoitti käyttäjää {WarnUserID,User} aiheesta {Points,plural,%s points}. ';
$Definition['WarningTitleFormat.Notice'] = '{SyötäKäyttäjätunnus,Käyttäjä} varoitettu {VaroitaKäyttäjätunnusta,Käyttäjä} syystä {Pisteet,monikko,%s pistettä} (vain ilmoitus).';
$Definition['was'] = 'oli';
$Definition['We\'ve received a request to change your password.'] = 'Meitä pyydettiin vaihtamaan %s salasanasi. Jos et ole itse pyytänyt salasanan vaihtamista, niin jätä tämä sähköposti huomioitta.';
$Definition['Website'] = 'Kotisivu';
$Definition['weeks'] = 'viikkoa';
$Definition['Welcome Aboard!'] = 'Tervetuloa mukaan!';
$Definition['were'] = 'olivat';
$Definition['What\'s This?'] = 'Mitä tämä on?';
$Definition['What to search'] = 'Mitä etsiä';
$Definition['When'] = 'Milloin';
$Definition['Where'] = 'Missä';
$Definition['Where do you want to announce this discussion?'] = 'Mihin haluat nostaa t&auml;m&auml;n keskustelun huomioitaviin?';
$Definition['Who\'s going?'] = 'Kuka on menossa?';
$Definition['Who\'s Online'] = 'Paikalla on';
$Definition['Who\'s Online in this Category'] = 'Kuka on online-tilassa tässä kategoriassa';
$Definition['Who\'s Online in this Discussion'] = 'Kuka on online-tilassa tässä keskustelussa';
$Definition['Whoops!'] = 'Hups!';
$Definition['Whoops! You\'ll need to register before you can email our site.'] = 'Hups! Sinun täytyy rekisteröityä ennen kuin voit lähettää sivustollemme sähköpostia.';
$Definition['Why are you Banning this user?'] = 'Kerro eston syy?';
$Definition['Why do you want to join?'] = 'Mit&auml; kautta palstan l&ouml;ysit/mahdollinen suosittelija?';
$Definition['Would you like to accept the invitation to join this group?'] = 'Haluaisitko hyväksyä kutsun liittyä tähän ryhmään?';
$Definition['Write a comment'] = 'L&auml;het&auml; uusi kommentti';
$Definition['Write Comment'] = 'Vastaa';
$Definition['Write something about yourself...'] = 'Kerro jotain itsest&auml;si..?';

$Definition['Yes'] = 'Kyll&auml;';
$Definition['You'] = 'Sin&auml;';
$Definition['you'] = 'sin&auml;';
$Definition['You\'re banned from joining this group.'] = 'Sinua on estetty liittymästä tähän ryhmään.';
$Definition['You\'ve already created the maximum number of groups.'] = 'Olet jo luonut maksimimäärän ryhmiä.';
$Definition['You\'ve applied to join this group.'] = 'Olet pyrkinyt tämän ryhmän jäseneksi.';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">Olet esittänyt kysymyksiä, joille on nyt vastauksia</a>. Varmistathan, että hyväksyt/hylkäät vastaukset.';
$Definition['You\'ve been invited to join {Name}.'] = 'Sinut on kutsuttu liittymään ryhmään {Nimi}.';
$Definition['You\'ve been Jailed.'] = 'Sinut on asetettu j&auml;&auml;hylle';
$Definition['You already have an account here.'] = 'Vaikuttaa silt&auml;, ett&auml; olet jo j&auml;sen?';
$Definition['You are about to ban {User.UserID,user}.'] = 'Olet aikeissa asettaa eston k&auml;ytt&auml;j&auml;lle {User.UserID,user}.';
$Definition['You are about to move %1$s of the %2$s of the selected discussions.'] = 'Olet aikeissa siirtää %1$s / %2$s valituista keskusteluista.';
$Definition['You are about to move %s.'] = 'Olet aikeissa siirtää %s.';
$Definition['You are about to unban {User.UserID,user}.'] = 'Olet aikeissa poistaa eston k&auml;ytt&auml;j&auml;lt&auml; {User.UserID,user}.';
$Definition['You are allowed to create %s groups.'] = 'Voit luoda %s ryhmää.';
$Definition['You are already a member of this group.'] = 'Olet jo tämän ryhmän jäsen.';
$Definition['You are connected as %s through %s.'] = 'Olet yhteydessä kohteeseen %s kohteen %s kautta.';
$Definition['You are connected through %2$s.'] = 'Sinut on yhdistetty palvelun %2$s kautta.';
$Definition['You are currently only viewing categories that you follow.'] = 'Olet asettanut n&auml;kyviin vain kategoriat, joita seuraat.';
$Definition['You are currently viewing all categories.'] = 'Olet asettanut n&auml;kyviin kaikki kategoriat';
$Definition['You are editing %s\'s signature'] = 'Muokkaat j&auml;senen %s\'s allekirjoitusta';
$Definition['You are limited to %s recipient.'] = 'Rajoituksesi on %s vastaanottaja.';
$Definition['You are limited to %s recipients.'] = 'Rajoituksesi on %s vastaanottajaa.';
$Definition['You aren\'t a %s of this group.'] = 'Et ole tämän ryhmän %s.';
$Definition['You aren\'t allowed to %s this group.'] = 'Sinä et pysty %s tähän ryhmään.';
$Definition['You are now signed in.'] = 'Olet kirjautuneena.';
$Definition['You are only allowed {maxImages,plural,%s image,%s images}.'] = 'Saat vain {maxImages,monikko,%s kuvan,%s kuvaa}.';
$Definition['You can\'t leave the group you started.'] = 'Et voi lähteä aloittamastasi ryhmästä.';
$Definition['You can either ask a question or start a discussion.'] = 'Voit joko aloittaa uuden keskustelun tai l&auml;hett&auml;&auml; uuden kysymyksen. Valitse haluamasi vaihtoehto ohessa.';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Seurannassa';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Pikkukuvaa ei voi muokata kun se on linkitettyn&auml; toisesta verkkosijainnista suoraan.';
$Definition['You cannot edit the thumbnail of another member.'] = 'Et voi muokata toisen k&auml;ytt&auml;j&auml;n pikkukuvaa.';
$Definition['You cannot remove an invitation that has been accepted.'] = 'Et voi poistaa kutsua joka on jo hyv&auml;ksytty.';
$Definition['You can only specify up to %s tags.'] = 'Voit m&auml;ritell&auml; %s tagia.';
$Definition['You can remove or ban this member from the group.'] = 'Voit poistaa tai estää tämän jäsenen ryhmästä. Estetyt jäsenet eivät voi liittyä ryhmään uudelleen.';
$Definition['You can use HTML in your signature.'] = 'Voit käyttää <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple HTML</a></b> allekirjoituksessasi.';
$Definition['You don\'t have permission to do that.'] = 'Sinulta puuttuvat oikeudet valittuun toimintoon.';
$Definition['You don\'t have permission to use a signature.'] = 'Sinulla ei ole lupaa käyttää allekirjoitusta.';
$Definition['You do not have any %s yet.'] = 'Sinulla ei ole viel&auml; yht&auml;&auml;n %s.';
$Definition['You do not have any bookmarks.'] = 'Sinulla ei ole suosikkeihin asettamiasi aiheita.';
$Definition['You do not have any conversations.'] = 'Et ole viel&auml; aloittanut yht&auml;&auml;n uutta keskustelua.';
$Definition['You do not have any drafts.'] = 'Sinulla ei ole tallennettuja luonnoksia.';
$Definition['You do not have any notifications yet.'] = 'Sinulla ei ole viel&auml; ilmoituksia';
$Definition['You do not have enough invitations left.'] = 'Sinulla ei ole tarpeeksi kutsuja j&auml;ljell&auml;.';
$Definition['You do not have permission to edit all of the posts you are trying to merge.'] = 'Sinulla ei ole oikeuksia muokata kaikkia viestejä, jotka haluat yhdistää.';
$Definition['You do not have permission to move %1$s of the selected discussions.'] = 'Sinulla ei ole lupaa siirtää %1$s valituista keskusteluista.';
$Definition['You do not have permission to view other profiles.'] = 'Muiden j&auml;senien profiilien katselu ei ole sallittua k&auml;ytt&auml;j&auml;tasollasi.';
$Definition['You do not have permission to write new comments.'] = 'Sinulta puuttuvat oikeudet l&auml;hett&auml;&auml; uusia kommentteja.';
$Definition['YouEarnedBadge'] = 'Ansaitsit t&auml;m&auml;n kunniamerkin ';
$Definition['You have answered questions'] = 'Olet saanut vastauksen kysymykseesi!';
$Definition['You have been approved for membership.'] = 'Sinut on hyväksytty jäseneksi.';
$Definition['You have entered an invalid discussion title'] = 'Keskustelun otsikko jonka annoit, on virheellinen.';
$Definition['You haven\'t joined any groups yet.'] = 'Et ole vielä liittynyt mihinkään ryhmään.';
$Definition['You haven\'t read this yet.'] = 'Et ole lukenut t&auml;t&auml; viel&auml;.';
$Definition['You have not started any discussions.'] = 'Et ole viel&auml; aloittanut yht&auml;&auml;n uutta keskustelua.';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Olet l&auml;hett&auml;nyt %1$s viesti&auml; %2$s sekunnin aikana. Roskapostin filtteri on nyt p&auml;&auml;ll&auml;. Odota v&auml;hint&auml;&auml;n  %3$s sekuntia ennen seuraavan viestin l&auml;hetyst&auml;.';
$Definition['You have selected %1$s.'] = 'Olet valinnut %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Olet valinnut %1$s t&auml;ss&auml; keskustelussa.';
$Definition['You have successfully connected to {Title}.'] = 'Yhdistyminen kohteeseen {Title} onnistui.';
$Definition['You have successfully registered for an account at {Title}.'] = 'Sinulle on nyt rekisteröity {Title}-käyttäjätili.';
$Definition['You have to select at least 2 discussions to merge.'] = 'Valitse ainakin kaksi keskustelua ensin yhdist&auml;&auml;ksesi ne.';
$Definition['You must agree to the terms of service.'] = 'Sinun pit&auml;&auml; hyv&auml;ksy&auml; s&auml;&auml;nn&ouml;t ja k&auml;ytt&ouml;ehdot ensin.';
$Definition['You must be at least %d years old to register.'] = 'Sinun on oltava vähintään %d vuotta vanha rekisteröityäksesi.';
$Definition['You must be signed in.'] = 'Sinun täytyy olla sisäänkirjautuneena.';
$Definition['You must confirm you have received consent to register.'] = 'Sinun on vahvistettava, että olet saanut huoltajan suostumuksen rekisteröitymistä varten.';
$Definition['You need to confirm your email address.'] = 'Sinun t&auml;ytyy viel&auml; vahvistaa s&auml;hk&ouml;postiosoitteesi. Klikkaa <a href="{/entry/emailconfirmrequest,url}">t&auml;st&auml;</a> l&auml;hett&auml;&auml;ksesi vahvistuss&auml;hk&ouml;postin.';
$Definition['You need to confirm your email address before you can continue.'] = 'Et voi jatkaa ennen kuin olet vahvistanut sähköpostiosoitteesi.';
$Definition['You need to sign in before you can do this.'] = 'Sinun pit&auml;&auml;  kirjautua sis&auml;&auml;n ensin.';
$Definition['your'] = 'oman';
$Definition['Your application for this group was denied.'] = 'Hakemuksesi ryhmään on hylätty.';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Yll&auml;pito hyv&auml;ksyy manuaalisesti j&auml;senhakemukset. Saat s&auml;hk&ouml;postitse ilmoituksen kun hakemuksesi on k&auml;sitelty. Kiitos rekister&ouml;itymisest&auml;si!';
$Definition['Your changes have been saved.'] = 'Asetuksesi on nyt tallennettu.';
$Definition['Your changes have been saved successfully.'] = 'Asetustesi tallentaminen onnistui.';
$Definition['Your changes were saved.'] = 'Asetukset tallennettiin.';
$Definition['Your email has been successfully confirmed.'] = 'S&auml;hk&ouml;postiosoitteesi vahvistus onnistui.';
$Definition['Your invitation has been sent.'] = 'Kutsusi on nyt l&auml;hetetty.';
$Definition['Your old password was incorrect.'] = 'Vanha salasanasi ei t&auml;sm&auml;&auml;.';
$Definition['Your password has been changed.'] = 'Salasanasi vaihdettiin.';
$Definition['Your password reset token has expired.'] = 'Salasanan nollauskoodisi on vanhentunut. Yritä käyttää nollauksen pyyntölomaketta uudelleen.';
$Definition['Your picture has been removed.'] = 'Kuvasi on nyt poistettu.';
$Definition['Your post will appear once it\'s been approved.'] = 'Viestisi tulee n&auml;kyviin kun se on hyv&auml;ksytty yll&auml;pidon toimesta.';
$Definition['Your preferences have been saved.'] = 'Asetuksesi on tallennettu';
$Definition['Your private conversations with other members.'] = 'Privaviestisi muiden j&auml;senien kanssa.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Rekister&ouml;ity tunnuksesi: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'Pyynt&ouml;si on l&auml;hetetty. Katso s&auml;hk&ouml;postistasi tarkemmat ohjeet.';
$Definition['Your settings have been saved.'] = 'Asetuksesi on tallennettu.';
$Definition['Your settings have been saved successfully.'] = 'Asetuksesi on tallennettu.';
$Definition['Your status for this event is now: <b>%s</b>'] = 'Tilasi tässä tapahtumassa on nyt: <b>%s</b>';
$Definition['Your warning was added.'] = 'Varoitus on l&auml;hetetty.';
$Definition['You were added to a conversation.'] = '{InsertUserID,user} lis&auml;si {NotifyUserID,you} sinut <a href="{Url,htmlencode}">keskusteluun</a>.';
$Definition['You wrote:'] = 'Sinä kirjoitit:';
