<?php

$Definition['%1$s "%2$s" not found.'] = '%1$s "%2$s" не найдено.';
$Definition['%1$s Version %2$s'] = '%1$s Версія %2$s';
$Definition['%1$s version %2$s is available.'] = '%1$s версія %2$s теперь доступна.';
$Definition['%s is not a valid email address'] = '%s не правильный адресъ электронной почты';
$Definition['%s item in queue'] = '%s item въ очереди';
$Definition['%s level'] = '%s уровень';
$Definition['%s levels'] = '%s уровни';
$Definition['%s of %s'] = '%s → %s ';
$Definition['%s posts'] = '%s сообщеній';
$Definition['%s Settings'] = '%s настройки';
$Definition['%s site(s) found.'] = '%s сайтовъ найдено';
$Definition['%s sources(s) found.'] = '%s источниковъ найдено.';
$Definition['%s times'] = '%s разъ';
$Definition['%s unavailable'] = '%s недоступно';
$Definition['%s user(s) found.'] = '%s пользователь(ей) найденъ(о).';
$Definition['%s user(s) will be affected by this action.'] = 'къ %s пользователямъ будутъ примѣнено данное дѣйствіе.';
$Definition['%s years.'] = '%s лѣтъ (годъ, года).';

$Definition['(less)'] = '(скрыть)';
$Definition['(more)'] = '(дальше)';

$Definition['. The community forum is what all of your users &amp; customers will see when they visit '] = 'Обшій форумъ это то что видятъ всѣ ваши посѣтители и кліенты когда они посѣщаютъ';

$Definition['1 day'] = '1 день';
$Definition['1 hour'] = '1 часъ ';
$Definition['1 month'] = '1 мѣсяцъ';
$Definition['1 month after being sent'] = 'Мѣсяцъ послѣ отправки';
$Definition['1 week'] = '1 недѣля';
$Definition['1 week after being sent'] = 'Недѣлю послѣ отправки';

$Definition['2 weeks after being sent'] = 'Двѣ недѣли послѣ отправки';

$Definition['4 hours'] = '4 часа';

$Definition['5 minutes'] = '5 минутъ';

$Definition['15 minutes'] = '15 минутъ';

$Definition['<strong>Categories</strong>'] = '<strong>Категоріи</strong>';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Вниманіе!</strong> Перемѣщеніе темы въ другую категорію можетъ привести къ ее исчезновенію, если замѣняемая категорія имѣетъ другіе права';

$Definition['[%s] Confirm Your Email Address'] = '[%s] подтвердилъ вашъ email адресъ';
$Definition['[%s] Invitation'] = 'Приглашеніе [%s]';

$Definition['_Locale'] = 'Языкъ';

$Definition['Abilites'] = 'Способность';
$Definition['About.DisableStatistics'] = 'Если вамъ по какимъ-то причинамъ необходимо отключить этотъ плагинъ, отредактируйте файлъ config.php, добавивъ (или измѣнивъ) строку<p> <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code></p>';
$Definition['About.VanillaStatistics'] = 'Это очень важный плагинъ, отправляющій статистику использованія вашего форума на сервера Vanillaforums.org. Для того чтобы авторы Vanilla могли сдѣлать движокъ форума еще лучше. Мы просимъ Васъ не отключать отправку статистическихъ данныхъ';
$Definition['About Vanilla Statistics'] = 'Про этотъ плагинъ';
$Definition['Accepted'] = 'Одобренъ(а)';
$Definition['Action'] = 'Дѣйствія';
$Definition['Add %s'] = 'Добавить %s';
$Definition['Add Category'] = 'Добавить категорію';
$Definition['Added By'] = 'Добавилъ';
$Definition['Add Info &amp; Create Account'] = 'Добавить информацію & Создать аккаунтъ';
$Definition['Add information into the from field in email addresses to help with replies (recommended).'] = 'Добавить информацію въ полѣ email формы чтобы помочь съ отвѣтами (рекомендуется). ';
$Definition['Adding & Editing Categories'] = 'Добавленіе и редактированіе категорій';
$Definition['Add Item'] = 'Добавить запись';
$Definition['Addons'] = 'Дополненія';
$Definition['Add Role'] = 'Добавить новую группу';
$Definition['Add User'] = 'Добавить пользователя';
$Definition['Administrator'] = 'Администраторъ';
$Definition['Advanced'] = 'Настройки';
$Definition['Advanced Forum Settings'] = 'Продвинутыя установки форума';
$Definition['AdvancedNotifications'] = 'ДОПОЛНИТЕЛЬНЫЕУВЕДОМЛЕНІЯ';
$Definition['Advanced Options'] = 'Расширенныя опціи';
$Definition['Advanced Settings'] = 'Дополнительныя настройки';
$Definition['All'] = 'Все';
$Definition['All %1$s'] = 'Все %1$s';
$Definition['All discussions in this category will be permanently deleted.'] = 'Все темы въ этой категоріи будутъ удалены.';
$Definition['All Forum Pages'] = 'На всѣхъ страницахъ форума';
$Definition['All of the user content will be replaced with a message stating the user has been deleted.'] = 'Все сообщенія пользователя будутъ замѣнены сообщеніемъ о томъ, что этотъ пользователь былъ удаленъ.';
$Definition['Allow new users to be registered through email.'] = 'Разрѣшить новымъ пользователямъ регистрироваться черезъ email.';
$Definition['Allow users to dismiss this message'] = 'Разрѣшить пользователямъ скрывать это сообщеніе';
$Definition['All Pages'] = 'Все страницы';
$Definition['A message has been sent to your email address with password reset instructions.'] = 'На вашъ email выслано письмо съ инструкціей по смѣнѣ пароля';
$Definition['API Status'] = 'API статусъ';
$Definition['Appearance'] = 'Внѣшній видъ';
$Definition['Applicant'] = 'Кандидатъ';
$Definition['Applicant Role'] = 'Выберите группу для новыхъ кандидатовъ';
$Definition['Application'] = 'Приложеніе';
$Definition['ApplicationHelp'] = 'Съ помощью приложеній вы можете измѣнить базовую функціональность форума.<br />Сразу послѣ того, какъ вы загрузите приложеніе въ эту %s категорію, вы сможете активировать его въ этой панели.';
$Definition['Application ID'] = 'ID Приложенія';
$Definition['Applications'] = 'Приложенія';
$Definition['Application Secret'] = 'Скрытый пароль';
$Definition['Applied by Administrator'] = 'Примѣнено администраторомъ ';
$Definition['Applied Manually'] = 'Примѣнено вручную ';
$Definition['Applied On'] = 'Дата';
$Definition['Apply'] = 'Включить';
$Definition['Approval'] = 'Послѣ провѣрки';
$Definition['Approve'] = 'Допускъ';
$Definition['Archive Discussions'] = 'Архивъ сообщеній';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Вы увѣрены, что правильно ввели имя хоста базы данныхъ? Возможно Вы ошиблись при наборѣ. <code>%s</code>';
$Definition['Are you sure you want to delete %s items forever?'] = 'Вы увѣрены, что хотите навсегда удалить %s отзыва(овъ)?';
$Definition['Are you sure you want to delete 1 item forever?'] = 'Вы увѣрены, что хотите навсегда удалить 1 отзывъ?';
$Definition['Are you sure you want to delete this category?'] = 'Вы увѣрены, въ томъ, что хотите удалить эту категорію?';
$Definition['A url-friendly version of the category name for better SEO.'] = 'Url-версія названія категоріи для улучшенія SEO.';
$Definition['Authenticate Url'] = 'URL провѣрки';
$Definition['Authentication'] = 'Аутентификація';
$Definition['Authors can always edit their posts'] = 'Авторъ всегда можетъ редактировать свой постъ';
$Definition['Authors can edit for 1 day after posting'] = 'Авторъ не сможетъ редактировать свой постъ спустя сутки послѣ публикаціи';
$Definition['Authors can edit for 1 month after posting'] = 'Авторъ не сможетъ редактировать свой постъ черезъ мѣсяцъ послѣ публикаціи';
$Definition['Authors can edit for 1 week after posting'] = 'Авторъ не сможетъ редактировать свой постъ черезъ недѣлю послѣ публикаціи';
$Definition['Authors can edit for 5 minutes after posting'] = 'Авторъ не сможетъ редактировать свой постъ черезъ 5 минутъ послѣ публикаціи';
$Definition['Authors can edit for 15 minutes after posting'] = 'Авторъ не сможетъ редактировать свой постъ черезъ 15 минутъ послѣ публикаціи';
$Definition['Authors can edit for 30 minutes after posting'] = 'Авторъ не сможетъ редактировать свой постъ черезъ 30 минутъ послѣ публикаціи';
$Definition['Authors cannot edit their posts'] = 'Автору вообще нельзя редактировать опубликованные посты';

$Definition['Back to all users'] = 'Назадъ ко всѣмъ пользователямъ';
$Definition['Back to Mobile Site'] = 'Назадъ, на мобильную версію';
$Definition['Badge Name'] = 'Имя';
$Definition['Badge Requests'] = 'Запросы на значки';
$Definition['Ban Item'] = 'Запись';
$Definition['Ban List'] = 'Списокъ забаненыхъ';
$Definition['Banner'] = 'Названіе и лого';
$Definition['Banner Logo'] = 'Логотипъ сайта';
$Definition['Banner Title'] = 'Названіе сайта';
$Definition['Ban Type'] = 'Типъ бана';
$Definition['Basic'] = 'По умолчанію';
$Definition['Blocked'] = 'Заблокированно';
$Definition['Browse for a new banner logo if you would like to change it:'] = 'Просто загрузите новый логотипъ, если вы хотите смѣнить текущій:';
$Definition['By %s'] = 'Отъ %s';
$Definition['by %s'] = 'отъ %s';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Нажавъ на кнопку ниже, вы удалите учетную запись %s навсегда.';

$Definition['Capture definitions throughout the site. You must visit the pages in the site in order for the definitions to be captured. The captured definitions will be put in the <code>captured.php</code> and <code>captured_admin.php</code>.'] = 'Перехватъ настроекъ сайта. Вы должны послѣдовательно посѣтить все страницы сайта, чтобы настройки были сохранены. Все настройки будутъ находиться въ файлахъ <code>captured.php</code> и <code>captured_admin.php</code>.';
$Definition['Categories &amp; Discussions'] = 'Раздѣлы и Обсужденія';
$Definition['Categories are used to help organize discussions.'] = 'Категоріи используются для того, чтобы организовать дисскуссіи.<br /> Вы можете дѣлать многоуровневое меню сайта, съ помощью функціи <i>drag and drop</i> въ спискѣ категорій. ';
$Definition['Categories are used to organize discussions.'] = '<strong>Категоріи</strong> позволяютъ организовать форумъ.';
$Definition['Category Page Layout'] = 'Шаблонъ страницы категорій';
$Definition['Category Url:'] = 'URL адресъ:';
$Definition['Change the look of All Categories'] = 'Вы можете измѣнить внѣшній видъ <b>Всѣхъ категорій</b> <a href="%s">здѣсь</a>.';
$Definition['Change the way that new users register with the site.'] = 'На этой страницѣ вы можете измѣнить настройки регистраціи новыхъ пользователей.';
$Definition['Change the way your community works with plugins. We\'ve bundled popular plugins with the software, and there are more available online.'] = 'Настройте Вашъ форумъ, используя встроенныя расширенія и плагины, расположенныя на сайтѣ форума.';
$Definition['Change your banner'] = 'Установи собственное лого';
$Definition['Changing the Discussions Menu Link'] = 'Обсужденіе настройки контекстнаго меню';
$Definition['Check all permissions that apply for each role'] = 'Провѣрьте права доступа, которыя примѣняются въ каждой группѣ.';
$Definition['Check all permissions that apply to this role:'] = 'Провѣрьте права доступа, которыя относятся къ этой группѣ:';
$Definition['Choose a locale pack'] = 'Выберите локализацію';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Выберите и настройте схему авторизаціи на форумѣ';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Какъ обрабатывать содержимое для %s ? (отзывы, увѣдомленія, и т.д.).';
$Definition['Choose who can send out invitations to new members:'] = 'Укажите, кто можетъ приглашать новыхъ пользователей:';
$Definition['Clean Spam'] = 'Очистить спамъ';
$Definition['Click a tag name to edit. Click x to remove.'] = 'Кликните на имя тэга для редактированія. Кликните на x для удаленія.';
$Definition['Click here to apply it.'] = 'Кликните здѣсь для подтвержденія';
$Definition['Click here to carry on to your dashboard'] = 'Нажмите для перехода къ панели управленія сайтомъ';
$Definition['comment(s)'] = 'отзывъ(овъ)';
$Definition['Comment  Body'] = 'Сообщеніе Основное поле';
$Definition['Comments Page'] = 'Страницъ комментаріевъ';
$Definition['Comments per Page'] = 'Отзывовъ на страницѣ';
$Definition['Comment  Subject'] = 'Сообщеніе Тема';
$Definition['Condition Type'] = 'Типъ';
$Definition['Configure an Authenticator'] = 'Настройки аутентификаціи';
$Definition['Configure how nested categories are displayed to users.'] = 'Настройте количество вложенныхъ категорій, видимыхъ пользователямъ';
$Definition['Configuring Vanilla\'s Homepage'] = 'Настройте домашнюю страницу сайта';
$Definition['Confirmation  Body'] = 'Подтвержденіе Основное поле сообщенія';
$Definition['Confirm email addresses'] = 'Запрашивать у пользователей подтвержденіе по email (рекомендуется)';
$Definition['Consumer Key'] = 'Ключъ потребителя';
$Definition['Consumer Secret'] = 'Секретный ключъ потребителя';
$Definition['Content Flagging'] = 'Помѣтить содержимое';
$Definition['Conversation Messages'] = 'Свѣдѣнія';
$Definition['Conversations'] = 'Діалоги';
$Definition['Copy'] = 'Копировать';
$Definition['Could not instantiate mail function.'] = 'Не удалось воспользоваться функціей почты.';
$Definition['Create & organize discussion categories, manage your users, and more...'] = 'Создай и разсортируй категоріи для общенія, управляй своими пользователями, и еще много всякой всячины... ';
$Definition['Create & organize discussion categories and manage your users.'] = 'Создай и разсортируй категоріи для общенія, управляй своими пользователями. ';
$Definition['Criteria'] = 'Критеріи';
$Definition['Current Authenticator'] = 'Текущій плагинъ аутентификаціи';
$Definition['Current Theme'] = 'Используемая тема';

$Definition['Database Structure Upgrades'] = 'Обновленіе структуры базы данныхъ';
$Definition['Decline'] = 'Отклонить';
$Definition['Default'] = 'По умолчанію';
$Definition['default'] = 'по умолчанію';
$Definition['Default %s Permissions'] = 'Стандартныя %s разрѣшенія';
$Definition['Default  Category'] = 'Раздѣлъ по умолчанію';
$Definition['Default Category Permissions'] = 'Разрѣшенія на категоріи по умолчанію';
$Definition['Default Locale'] = 'Языкъ по-умолчанію';
$Definition['Default Roles'] = 'Группа для новыхъ пользователей по умолчанію';
$Definition['Define your forum homepage'] = 'Назначь главную страницу для форума';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Ты можешь измѣнить главную страницу, загрузить свой логотипъ, и еще много всякой всячины...';
$Definition['Delete Category'] = 'Удалить категорію';
$Definition['Delete Forever'] = 'Удалить навсегда';
$Definition['Delete User'] = 'Удалить пользователя';
$Definition['Delete User: %s'] = 'Удалить пользователя: %s';
$Definition['Deleting category...'] = 'Удаленіе категоріи...';
$Definition['Description'] = 'Описаніе';
$Definition['Did You Know?'] = 'А Вы знаете?';
$Definition['Disable'] = 'Выключить';
$Definition['Disable Content Flagging'] = 'Выключить жалобы на контентъ';
$Definition['Disabled'] = 'Выключено';
$Definition['Disabled %1$s'] = 'Неактивныя %1$s';
$Definition['Disable Google Sign In'] = 'Выключить авторизацію съ помощью Google';
$Definition['Disable OpenID'] = 'Выключить OpenID';
$Definition['Disable Tagging'] = 'Выключить теги';
$Definition['Discussion & Comment Editing'] = 'Редактированіе Темъ и Отзывовъ';
$Definition['discussion(s)'] = 'Темъ';
$Definition['Discussion  Body'] = 'Обсужденіе Основное поле';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Категоріи помогаютъ упростить навигацію по форуму, а также разбить темы на группы. Напримѣръ, темы про мотоциклы нужно отнести въ категорію "мото", а про автомобили — въ категорію "авто"';
$Definition['Discussions per Page'] = 'Темъ на страницѣ';
$Definition['Discussion  Subject'] = 'Обсужденіе Тема';
$Definition['Display root categories as headings.'] = 'Показывать главныя категоріи какъ заголовки.';
$Definition['Don\'t Refresh'] = 'Не обновлять';
$Definition['Don\'t use Categories'] = 'Не использовать категоріи';
$Definition['Do not display the categories in the side panel.'] = 'Не показывать списокъ категорій въ сайдбаре.';
$Definition['Drag &amp; drop the categories to sort and nest them.'] = 'Перетяните раздѣлы чтобы сортировать и упорядочить ихъ.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Схватите и перетащите категорію для сортировки въ спискѣ.';

$Definition['edit'] = 'редактировать';
$Definition['Edit %s'] = 'Редактировать %s';
$Definition['Edit/Delete Log'] = 'Логъ редактированія';
$Definition['Edit Category'] = 'Редактировать категорію';
$Definition['EditContentTimeout.Notes'] = 'Примѣчаніе: Если въ группѣ пользователя стоятъ настройки, разрѣшающія редактированіе въ любое время - имъ будетъ отдано предпочтеніе';
$Definition['Editing'] = 'Редактированіе';
$Definition['Edit Message'] = 'Редактировать сообщеніе';
$Definition['Edit Role'] = 'Редактировать группы';
$Definition['Edit Route'] = 'Редактировать права';
$Definition['Edit User'] = 'Редактировать пользователя';
$Definition['Email Confirmation Role'] = 'Подтвержденіе правъ по email';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Добавь форумъ на свой сайтъ, для повышенія количества участниковъ';
$Definition['Embed your forum in your web site'] = 'Добавленіе форума на вашъ сайтъ';
$Definition['Enable'] = 'Включить';
$Definition['Enabled'] = 'Включено';
$Definition['Enabled %1$s'] = 'Доступные %1$s';
$Definition['Enabled: The pocket will be displayed.'] = 'Включено';
$Definition['Enable OpenID'] = 'Включить OpenID';
$Definition['Enable this message'] = 'Включить это сообщеніе';
$Definition['Enabling a Locale Pack'] = 'Включеніе локализаціи';
$Definition['Encourage your friends to join your new community!'] = 'Пригласи своихъ друзей участвовать въ обсужденіяхъ на форумѣ!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Введите адресъ электронной почты человѣка, котораго вы хотѣли бы пригласить:';
$Definition['Enter the url to the page you would like to use as your homepage:'] = 'Введите URL на страницу, которую вы бы хотѣли использовать въ качествѣ главной страницы:';
$Definition['Every 1 minute'] = 'Каждую минуту';
$Definition['Every 5 minutes'] = 'Каждыя 5 минъ';
$Definition['Every 5 seconds'] = 'Каждыя 5 сѣкъ';
$Definition['Every 10 seconds'] = 'Каждыя 10 сѣкъ';
$Definition['Every 30 seconds'] = 'Каждыя 30 сѣкъ';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Каждое редактированіе или удаленіе здѣсь записывается. Примѣните функцію возстановленія чтобы отмѣнить измѣненія.';
$Definition['Exclude archived discussions from the discussions list'] = 'Исключить архивъ дискуссій изъ списка обсужденій';
$Definition['Existing members send invitations to new members.'] = 'Зарегистрированные пользователи приглашаютъ новыхъ пользователей.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Подключеніе черезъ Facebook позволитъ использовать Facebook аккаунтъ. <b>Для того, чтобы плагинъ работалъ, вы должны быть зарегистрированы на Facebook.</b>';
$Definition['Facebook Settings'] = 'Настройки Facebook';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Ошибка при подключеніи къ базѣ данныхъ. Неправильно введенъ логинъ или пароль. Провѣрьте, правильно ли выбранъ языкъ ввода данныхъ. <code>%s</code>';
$Definition['First Visit'] = 'Первый визитъ';
$Definition['Flood Control'] = 'Антиспамъ';
$Definition['Forum Settings'] = 'Настройки форума';
$Definition['Frequency'] = 'Частота обновленій';
$Definition['From'] = 'Отъ';

$Definition['Garden.Import.Complete.Description'] = 'You have successfully completed an import.

Click <b>Finished</b> when you are ready.';
$Definition['Garden.Import.Continue.Description'] = 'It appears as though you are in the middle of an import.

  Please choose one of the following options.';
$Definition['Garden.Import.Description'] = 'Эта страница служитъ для импорта данныхъ изъ другого форума, который былъ экспортированъ съ помощью виджета экспорта Vanilla. Дополнительную информацію вы можете получить въ <a href="%s">документаціи</a>.';
$Definition['Garden.Import.InputInstructions'] = 'Email и пароль администратора для источника импорта.';
$Definition['Garden.Import.Merge.Description'] = 'This will merge all of the user and discussion data from the import into this forum.

<b>Warning: If you merge the same data twice you will get duplicate discussions.</b>';
$Definition['Garden.Import.Overwrite.Description'] = 'Вниманіе! Все данные въ этомъ форумѣ будутъ перезаписаны.';
$Definition['Garden.StatisticsDisabled'] = 'Модуль статистики отключенъ въ файлѣ конфигураціи.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Форумъ работаетъ въ тестовомъ режимѣ, или расположенъ на частномъ IP-адресѣ.<br>По умолчанію форумы, работающіе на частныхъ IP-адресахъ, не отслѣживаются.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Если Вы увѣрены, что Вашъ форумъ доступенъ изъ интернета, Вы можете получить здѣсь отчетъ о статистикѣ.';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Вашъ config.php имѣетъ атрибуты "только для чтенія". Поэтому форумъ не сможетъ автоматически регистрировать InstallationID и InstallationSecret.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'Для рѣшенія возникшей проблемы, назначьте атрибуты 777 вашему файлу conf/config.php.';
$Definition['Generate'] = 'Генерировать';
$Definition['Generate Client ID and Secret'] = 'Создать кодъ кліента и тайнъ -ую -ое';
$Definition['Get More Applications'] = 'Новыя приложенія';
$Definition['Get more information on creating custom routes'] = 'Читайте болѣе подробную информацію о перенаправленіяхъ.';
$Definition['Get More Plugins'] = 'Новые плагины';
$Definition['Get More Themes'] = 'Новыя темы';
$Definition['Getting Started with Vanilla'] = 'Добро пожаловать въ міръ Vanilla!';
$Definition['give'] = 'дать';
$Definition['Google Sign In Settings'] = 'Настройки авторизаціи Google';
$Definition['Guest'] = 'Гость';
$Definition['Guest roles'] = 'Отмѣтить все группы, которыя относятся къ гостямъ.';

$Definition['Hash Algorithm'] = 'Алгоритмъ хешированія';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Здѣсь недоступны активныя соединенія. По этой причинѣ Вамъ отказано въ доступѣ.';
$Definition['Help &amp; Tutorials'] = 'Помочь и Уроки';
$Definition['Here\'s how to get started:'] = 'Приступаемъ къ работѣ:';
$Definition['Hide from the recent discussions page.'] = 'Скрыть отъ послѣднихъ страницъ обсужденій.';
$Definition['Hide this category from the recent discussions page.'] = 'Скрыть эту категорію изъ послѣднихъ страницъ обсужденій.';
$Definition['Hi Pal!

Check out the new community forum I\'ve just set up. It\'s a great place for us to chat with each other online.

Follow the link below to log in.'] = 'Приветствуем!»⏎
»⏎
Вотъ такой новый формъ мы создали. Здѣсь можно обсуждать все обо всѣмъ! »⏎
»⏎
Слѣдуйте ссылкѣ чтобы зайти.';
$Definition['Homepage'] = 'Главная страница';
$Definition['How to use themes'] = 'Используй новыя темы';

$Definition['If you are using ProxyConnect with an officially supported remote application plugin such as our wordpress-proxyconnect plugin, these values will be available in that plugin\'s configuration screen.'] = 'ProxyConnect.RimBlurb';
$Definition['Import'] = 'Импортъ';
$Definition['Importing to Vanilla'] = 'Импортировать въ Vanill\'u';
$Definition['Information'] = 'Информація';
$Definition['Install Vanilla without a .htaccess file.'] = 'Установите Vanilla безъ файла .htaccess';
$Definition['Internaltionalization & Localization'] = 'Интернаціонализація и локализація';
$Definition['Invitation'] = 'По приглашенію';
$Definition['Invitation Code'] = 'Кодъ инвайта';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Если включена регистрація по инвайтамъ, на страницахъ профилей пользователей<br>отображается дополнительная ссылка, называемая <a href="%s" class="Popup">Мои приглашенія</a>';
$Definition['Invitations per month'] = 'Приглашеній въ мѣсяцъ';
$Definition['Invitations will expire'] = 'Приглашеніе истекаетъ';
$Definition['Invited by'] = 'Приглашенъ';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Базы данныхъ съ такимъ именемъ не существуетъ. Возможно Вы ошиблись при наборѣ или попробуйте создать новую БДЪ. <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Опція ниже поможетъ вамъ сократить максимальное количество символовъ въ отзывахъ до разумнаго размѣра.';

$Definition['Key Type'] = 'Типъ ключа';
$Definition['Key Value'] = 'Значеніе ключа';
$Definition['Kick-start your community and increase user engagement.'] = 'Настрой и приглашай пользователей въ свое сообщество!';

$Definition['Last Visit'] = 'Послѣдній визитъ';
$Definition['Level'] = 'Уровень';
$Definition['Locale Key (Folder)'] = 'Ключъ локализаціи (папка)';
$Definition['Locale Name'] = 'Названіе';
$Definition['Locales'] = 'Локализаціи';
$Definition['Locales are in your %s folder.'] = 'Локализація позволяетъ поддерживать нѣсколько языковъ на форумѣ.<br /><br /> Какъ только вы добавите локализацію въ папку %s , она отобразиться въ спискѣ ниже и вы сможете ее активировать. <br /><br />';
$Definition['Location'] = 'Мѣстоположеніе';
$Definition['LogoBrowse'] = 'Просто загрузите новый логотипъ, если вы хотите смѣнить текущій:';

$Definition['Make sure to use a forum theme that meshes well with the look and feel of the remote site.'] = 'Удостовѣрьтесь, что выбранная тема сочетается съ другими элементами дизайна.';
$Definition['Make sure you click View Page'] = 'Кликните <a href="%s">по ссылкѣ</a>, чтобы увидѣть какіе страницы категорій появятся послѣ сохраненія.';
$Definition['Make sure you select at least one item before continuing.'] = 'Удостовѣрьтесь, что вы выбрали хотя бы одну запись передъ редактированіемъ.';
$Definition['Manage'] = 'Управленіе';
$Definition['Manage Applicants'] = 'Управленіе неактивными';
$Definition['Manage Applications'] = 'Управленіе приложеніями';
$Definition['Manage Categories'] = 'Управленіе категоріями';
$Definition['Manage Messages'] = 'Управленіе сообщеніями';
$Definition['Manage Plugins'] = 'Управленіе плагинами';
$Definition['Manage Roles & Permissions'] = 'Управленіе группами и правами доступа';
$Definition['Manage Routes'] = 'Управленіе перенаправленіями';
$Definition['Manage Spam'] = 'Управленіе спамомъ';
$Definition['Manage Themes'] = 'Управленіе темами';
$Definition['Manage Users'] = 'Управленіе пользователями';
$Definition['Manage users'] = 'Управляй пользователями';
$Definition['Manage your Plugins'] = 'Управленіе вашими плагинами';
$Definition['Managing Categories'] = 'Управленіе категоріями';
$Definition['Manual'] = 'Инструкція';
$Definition['Max Comment Length'] = 'Максимальное количество символовъ въ отзывѣ:';
$Definition['Media'] = 'Загрузка файловъ';
$Definition['Member'] = 'Участникъ';
$Definition['Member roles'] = 'Отмѣтить все группы, которыя примѣняются къ новымъ или подтвержденнымъ пользователямъ.';
$Definition['Message ID'] = 'ID сообщенія';
$Definition['Messages can appear anywhere in your application.'] = 'Сообщенія могутъ быть отображены въ любомъ мѣстѣ сайта пользователя.<br>Напримѣръ, это можетъ быть использовано для информированія о новостяхъ.<br>На этой страницѣ можно управлять ими съ помощью перетаскиванія.';
$Definition['Method'] = 'Способъ';
$Definition['minute(s)'] = 'Минутъ(ы)';
$Definition['Mixed Layout'] = 'Смѣшанное расположеніе';
$Definition['Moderator'] = 'Модераторъ';
$Definition['Move discussions in this category to a replacement category.'] = 'Перемѣстите обсжуденіе въ эту категорію для ее замѣны.';
$Definition['My Invitations'] = 'Мои инвайты';

$Definition['Need More Help?'] = 'Нужна помощь?';
$Definition['never'] = 'никогда';
$Definition['New comments in the last day'] = 'Новыхъ комментаріевъ за сутки';
$Definition['New comments in the last week'] = 'Новыхъ комментаріевъ за 7 дней';
$Definition['New conversations in the last day'] = 'Новыхъ разговоровъ за сутки';
$Definition['New conversations in the last week'] = 'Новыхъ разговоровъ за 7 дней';
$Definition['New discussions in the last day'] = 'Новыхъ темъ за 24 часа';
$Definition['New discussions in the last week'] = 'Новыхъ темъ за 7 дней';
$Definition['New messages in the last day'] = 'Новыхъ сообщеній за сутки';
$Definition['New messages in the last week'] = 'Новыхъ сообщеній за недѣлю';
$Definition['New users are only registered through SSO plugins.'] = 'Новые пользователи регистрируются съ помощью соціальныхъ плагиновъ.';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'Новые пользователи разсматриваются и подтверждаются администраторомъ (вами).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'Новые пользователи регистрируются и получаютъ доступъ къ созданію ║темъ│тѣмъ║ сразу.';
$Definition['New users in the last day'] = 'Новыхъ пользователей за сутки';
$Definition['New users in the last week'] = 'Новыхъ пользователей за недѣлю';
$Definition['No Items Selected'] = 'Ничего не выбрано';
$Definition['None'] = 'Нѣтъ';
$Definition['No results for %s.'] = 'По запросу "<b>%s</b>" ничего не найдено.';
$Definition['Notes'] = 'Примѣчаніе';
$Definition['Notify me when people start new discussions.'] = 'Увѣдомлять <b>о всѣхъ новыхъ</b> темахъ';
$Definition['Not Spam'] = 'Это не спамъ';

$Definition['On'] = 'На';
$Definition['One, two, three...'] = 'Разъ, два, три...';
$Definition['Only Allow Each User To Post'] = 'Разрѣшить пользователямъ создавать не болѣе';
$Definition['Organize'] = 'Организуй';
$Definition['Organize Categories'] = 'Сортировка категорій';
$Definition['Or Spamblock For'] = 'или заблокировать на';
$Definition['Other Themes'] = 'Другіе темы';
$Definition['Outgoing Email'] = 'Исходящая почта';
$Definition['Outgoing Email Address'] = 'Исходящій адресъ электронной почты';

$Definition['Page'] = 'Страница';
$Definition['page'] = 'страница';
$Definition['Panel Box'] = 'Панель увѣдомленій';
$Definition['Password Options'] = 'Настройки пароля';
$Definition['Pending'] = 'Въ ожиданіи';
$Definition['Permission.Category'] = 'Категорія';
$Definition['Please choose an authenticator to configure.'] = 'Выберите плагинъ аутентификаціи для настройки';
$Definition['Please Confirm'] = 'Подтвердите пожалуйста';
$Definition['Plugin'] = 'Плагинъ';
$Definition['Plugin.Enabled'] = 'Включены';
$Definition['PluginHelp'] = 'Плагины позволяютъ измѣнять функціональность вашего сайта<br />Для установки плагина помѣстите его въ папку %s и затѣмъ активируйте на этой страницѣ';
$Definition['Plugins'] = 'Плагины';
$Definition['Plugins.Tagging.Enabled'] = 'Плагинъ "Теги" Включенъ';
$Definition['Polls'] = 'Вопросы';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Предотвратите появленіе хлама на форумѣ посредствомъ ограниченія сообщеній  которыя пользователи могутъ размѣщать въ конкретный срокъ времени.';
$Definition['Private Key'] = 'Приватный ключъ';
$Definition['Public Key'] = 'Публичный ключъ';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Краткое руководство по созданію темъ для Vanill\'ы';

$Definition['Ranks'] = 'Рангъ';
$Definition['Recently Active Users'] = 'Послѣдніе активные пользователи';
$Definition['Recent News'] = 'Послѣдніе новости';
$Definition['Refresh Comments'] = 'Обновить отзывы';
$Definition['Register Url'] = 'Зарегистрировать URL';
$Definition['Registration'] = 'Регистрація';
$Definition['Remove'] = 'Удалить';
$Definition['Remove Banner Logo'] = 'Удалить логотипъ';
$Definition['Replacement Category'] = 'Замѣна категоріи';
$Definition['Reply  To'] = 'Отвѣтить Кому';
$Definition['Request'] = 'Запросъ';
$Definition['Requires: '] = 'Необходимо: ';
$Definition['Require users to confirm their email addresses (recommended)'] = 'Запрашивать у пользователей подтвержденіе по email (рекомендуется)';
$Definition['Rescan'] = 'Сканировать';
$Definition['Reset my password'] = 'Сбросить мой пароль';
$Definition['Reset password and send email notification to user'] = 'Сбросить пароль и отправить пользователю на почту сообщеніе объ этомъ';
$Definition['Restore'] = 'Возстановить';
$Definition['Reveal Password'] = 'Показать пароль';
$Definition['Role'] = 'Группа';
$Definition['Role Name'] = 'Имя группы';
$Definition['Roles & Permissions'] = 'Группы и права доступа';
$Definition['Roles determine user\'s permissions.'] = 'Каждый пользователь сайта состоитъ минимумъ въ одной группѣ. Настройка группъ опредѣляетъ, что пользователь, состоящій въ группѣ, можетъ дѣлать на сайтѣ';
$Definition['Route'] = 'Перенаправленіе';
$Definition['Route Expression'] = 'Формированіе перенаправленія';
$Definition['Routes'] = 'Перенаправленія';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'Перенаправленія могутъ быть использованы для автоматической переадресаціи пользователей на различныя части вашего сайта въ зависимости отъ URL.';
$Definition['Run structure & data scripts'] = 'Запустить обновленіе структуры и скриптовъ';

$Definition['Saved'] = 'Сохранено.';
$Definition['SaveLocalePack'] = 'Сохранить';
$Definition['Search by user or role.'] = 'Поискъ по имени пользователя или группѣ';
$Definition['seconds'] = 'секундъ';
$Definition['Security'] = 'Безопасность';
$Definition['Select the file to import'] = 'Выберите файлъ для импорта';
$Definition['Select the import source'] = 'Выберите файлъ для импорта данныхъ';
$Definition['Send %s a Message'] = 'Отправить %s сообщеніе';
$Definition['Send a confirmation email when people ask a question or start a discussion over email.'] = 'Высылать проверочное письмо когда пользователи задаютъ вопросъ черезъ электронную почту. ';
$Definition['Send Again'] = 'Повторно отправить';
$Definition['Send Invitations!'] = 'Послать приглашеніе!';
$Definition['Sent To'] = 'Отправить';
$Definition['Sign In Url'] = 'URL входа въ систему';
$Definition['Site Description'] = 'Описаніе сайта';
$Definition['SMTP Host'] = 'SMTP серверъ';
$Definition['SMTP Password'] = 'SMTP Пароль';
$Definition['SMTP Port'] = 'SMTP Портъ';
$Definition['SMTP Security'] = 'Протоколъ безопасности SMTP';
$Definition['SMTP User'] = 'SMTP Пользователь';
$Definition['Spoof'] = 'Притворство';
$Definition['Start Discussions'] = 'Начать обсужденіе';
$Definition['starting your first discussion'] = 'иконку';
$Definition['Statistics'] = 'Статистика';
$Definition['Status'] = 'Статусъ';
$Definition['Subject'] = 'Тема';

$Definition['take away'] = 'отнять';
$Definition['Test Mode: The pocket will only be displayed for pocket administrators.'] = 'Test Mode';
$Definition['Thank You!'] = 'Спасибо!';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'Плагинъ %s не используетъ индивидуальныя настройки';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Аддонъ не можетъ быть активированъ потому, что онъ выдаетъ фатальную ошибку: <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'Логотипъ отображается на всѣхъ страницахъ и замѣняетъ названіе форума на загруженное изображеніе.';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Названіе сайта отображается на каждой страницѣ въ лѣвомъ верхнемъ углу (въ зависимости отъ выбранной темы оформленія), а также въ заголовкахъ страницъ.<br><br>Кромѣ того, вы можете загрузить логотипъ, вмѣсто названія сайта.';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Пользователь базы данныхъ, имя котораго Вы указали, не имѣетъ достаточныхъ полномочій для доступа къ БДЪ. Попробуйте создать новую базу данныхъ. <code>%s</code>';
$Definition['The following content has been flagged by users for moderator review.'] = 'Контентъ, который помѣтили пользователи для провѣрки модераторомъ.';
$Definition['The homepage was saved successfully.'] = 'Страница была успѣшно сохранена.';
$Definition['ThemeHelp'] = 'Темы позволяютъ измѣнить внѣшній видъ вашего сайта.<br />Загрузите папку съ темой сюда: %s и активируйте ее на этой страницѣ.';
$Definition['Themes'] = 'Темы оформленія';
$Definition['Theming Overview'] = 'Информація о темахъ';
$Definition['There are currently no applicants.'] = 'Въ настоящее время нѣтъ пользователей ожидающихъ одобренія участія на форумѣ.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Никакихъ измѣненій въ структурѣ базы данныхъ не требуется. Однако, измѣненія уже могли быть сдѣланы.';
$Definition['There are no items awaiting moderation at this time.'] = 'Въ настоящее время нѣтъ новыхъ сообщеній для модераціи.';
$Definition['The specified url code is already in use by another category.'] = 'Указанный URL кодъ уже используется другой категоріей.';
$Definition['The user and all related content has been deleted.'] = 'Пользователь и вся информація, которая была съ нимъ связана, удалены.';
$Definition['The user content will be completely deleted.'] = 'Контентъ пользователя будетъ полностью удаленъ';
$Definition['The user has been deleted.'] = 'Пользователь былъ удаленъ.';
$Definition['The Vanilla 2 Exporter'] = 'Экспортъ въ Vanilla 2';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Плагинъ статистики въ панели управленія Vanilla показываетъ графики активности на форумѣ, основываясь на данныхъ, записаныхъ движкомъ форума. Вы можете получить исчерпывающую информацію объ этомъ плагине въ его <a href="http://vanillaforums.org/docs/vanillastatistics">документаціи</a>.';
$Definition['This action cannot be undone.'] = 'Это дѣйствіе не можетъ быть отмѣнено.';
$Definition['This category has custom permissions.'] = 'Эта категорія содержитъ ║особые│особыя║ права.';
$Definition['This category is archived.'] = 'Эта категорія находится въ архивѣ.';
$Definition['This connection is in test-mode.'] = 'Данное соединеніе работаетъ въ режимѣ тестированія. ';
$Definition['This Database'] = 'Эту базу данныхъ';
$Definition['This is the administrative dashboard for your new community. Check out the configuration options to the left: from here you can configure how your community works. <b>Only users in the "Administrator" role can see this part of your community.</b>'] = 'Это административная панель Вашего новаго сообщества. Въ лѣвой части панели Вы можете настроить параметры конфигураціи. <b>Сдѣлать это могутъ только пользователи съ привилегіями "Администратора".</b>';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'Этотъ плагинъ позволяетъ пользователю войти на сайтъ съ помощью OpenID. <b>Послѣ активаціи перейдите въ настройки чтобы включить входъ по OpenID</b>.';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'Этотъ плагинъ позволяетъ пользователю войти на сайтъ съ помощью Google. <b>Послѣ активаціи перейдите въ настройки чтобы включить входъ съ помощью Google аккаунта.</b>.';
$Definition['This show the plugin on only selected discussion pages'] = 'Эта опція будетъ показывать панель только на выбранныхъ страницахъ.';
$Definition['This will show the panel on every page.'] = 'Эта опція будетъ показывать панель на каждой страницѣ.';
$Definition['Titles'] = 'Заголовки';
$Definition['To'] = 'КЪ';
$Definition['To embed your Vanilla community forum into a remote web application, use the forum embed code or one of the forum embed plugins below.'] = 'Для интеграціи вашего форума на другіе сайты, используйте кодъ вставки форума или вставьте его съ помощью плагиновъ описаныхъ ниже.';
$Definition['Try Again'] = 'Повторите';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Подключеніе черезъ Twitter позволяетъ пользователю войти на форумъ съ помощью twitter аккаунта. <b>Необходима активація приложенія на сайтѣ Twitter\'a чтобы плагинъ работалъ правильно.</b>';

$Definition['Uninvite'] = 'Отмѣнить приглашеніе';
$Definition['unknown'] = 'неизвѣстно';
$Definition['Unlimited'] = 'Не ограничено';
$Definition['Use an SMTP server to send email'] = 'Использовать SMTP-серверъ для отправки писемъ';
$Definition['Use Categories'] = 'Использовать категоріи';
$Definition['Use categories to organize discussions'] = 'Использовать категоріи для организаціи общенія';
$Definition['User'] = 'Пользователь';
$Definition['User Count'] = 'Колъ-во пользователей';
$Definition['User Deleted'] = 'Пользователь удаленъ';
$Definition['UserDeletionPrompt'] = 'Какъ обрабатывать содержимое для %s ? (отзывы, увѣдомленія, и т.д.).';
$Definition['User Registration Settings'] = 'Настройки регистраціи пользователей';
$Definition['Users'] = 'Пользователи';
$Definition['Users that get this reaction get %+d point.'] = 'Пользователи которые получатъ этотъ отзывъ получатъ %+d балъ.';
$Definition['Users that get this reaction get %+d points.'] = 'Пользователи которые получатъ этотъ отзывъ получатъ %+d баловъ.';
$Definition['Users will be assigned to this role until they\'ve confirmed their email addresses.'] = 'Пользователи будутъ отнесены къ этой группѣ, когда подтвердятъ свой email';
$Definition['Use the content at this url as your homepage.'] = 'Главная страница, которую посѣтители будутъ видѣть, заходя по адресу <b>%s</b>. По умолчанію показываются "Все темы", но вы можете использовать все, что захотите. Вотъ нѣсколько популярныхъ варіантовъ: ';

$Definition['Vanilla.Archive.Description'] = 'Вы можете выбрать архивацію темъ на форумѣ старше опредѣленной даты. Архивированные темы практически закрываются, что не позволяетъ добавить въ нихъ ║новые│новыя║ посты.';
$Definition['Vanilla.Categories.MaxDisplayDepth'] = 'Сколько уровней вложенности отображать въ категоріяхъ: %1$s';
$Definition['Vanilla is installed!'] = 'Форумъ Vanilla установленъ!';
$Definition['Vanilla Statistics are currently disabled'] = 'Модуль статистики отключенъ';
$Definition['Verified!'] = 'Провѣренъ!';
$Definition['Version'] = 'Версія';
$Definition['Version %s'] = 'Версія %s';
$Definition['version %s'] = 'версія %s';
$Definition['Version %s Installer'] = 'Версія %s';
$Definition['Video tutorial on finding &amp; managing users'] = 'Видео урокъ по тому какъ привлечь пользователей и какъ ими управлять.';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Видео урокъ по тому какъ управлять ролями и правами доступа.';
$Definition['Video tutorial on user registration'] = 'Видео урокъ по регистраціи пользователей';
$Definition['View'] = 'Просмотръ';
$Definition['View Page'] = 'Показать страницу';

$Definition['Warning'] = 'Вниманіе!';
$Definition['Warning: All of your data will be lost. Once you delete, there is absolutely no recovery of any kind.'] = 'Вниманіе: Все ваши данные будутъ потеряны. Послѣ удаленія, нѣтъ абсолютно никакого способа возстановленія.';
$Definition['Warning: deleting is permanent'] = 'ПРЕДУПРЕЖДЕНІЕ: удаленные элементы будутъ удалены изъ этого списка и не могутъ быть возвращены.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Вниманіе</b>! Конфигурація сервера не поддерживаетъ быструю загрузку. Если вы пытаетесь импортировать большой файлъ (> 200.000 комментаріевъ), то вамъ лучше обновить конфигурацію сервера. Для болѣе подробной информаціи <a href="http://vanillaforums.com/porter">перейдите сюда</a>';
$Definition['Warning: This is for advanced users.'] = '<b>Вниманіе</b>: Это сообщеніе адресовано продвинутымъ пользователямъ и требуетъ, чтобы Вы внесли дополнительныя измѣненія на вашемъ вебъ-серверѣ. Это возможно, если у Васъ есть выдѣленный или виртуальный хостингъ. Ничего не предпринимайте, если не знаете, что необходимо дѣлать.';
$Definition['Welcome to Vanilla!'] = 'Добро пожаловать!';
$Definition['Welcome to your Dashboard'] = 'Добро пожаловать въ панель управленія';
$Definition['We only accept urls that begin with http:// or https://'] = 'Разрѣшены только 2 типа ссылокъ: http:// или https://';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'Мы попытаемся использовать локальный почтовый серверъ для отправки электронной почты по умолчанію. Если вы хотите использовать отдѣльный почтовый SMTP серверъ, настройте его ниже.';
$Definition['What\'s the Buzz?'] = 'Какіе новости?';
$Definition['Where is your Community Forum?'] = 'Расположеніе форума';
$Definition['Where should the plugin be shown?'] = 'Гдѣ долженъ быть показанъ модуль?';
$Definition['Who\'s Online Settings'] = 'Настройки "Кто въ сѣти?"';
$Definition['Why do you want to join?'] = 'Почему вы хотите зарегистрироваться?';
$Definition['Within'] = 'Въ предѣлахъ';
$Definition['WordPress Plugin'] = 'Плагинъ для WordPress';

$Definition['Yes, the following information can be changed later.'] = 'Информація, расположенная ниже, впослѣдствіи можетъ быть измѣнена.';
$Definition['You are now signed in.'] = 'Теперь вы вошли';
$Definition['You are previewing the %s theme.'] = 'Вы просматриваете тему %s';
$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'Вы всегда можете использовать пароль на <a href="%1$s">%1$s</a>.';
$Definition['You can make the categories page your homepage.'] = 'Страницы категорій можно установить въ качествѣ главной страницы <a href="%s">тутъ</a>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'Плагинъ %1$s нельзя отключить потому, что онъ необходимъ для стабильной работы плагина %2$s.';
$Definition['You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.'] = 'Плагинъ OpenID нельзя отключить потому, что онъ необходимъ для стабильной работы плагина GoogleSignIn.';
$Definition['You can place files in your /uploads folder.'] = 'Если Вашъ файлъ слишкомъ великъ чтобы загрузить его напрямую — залейте его въ папку /uploads.<br>Затѣмъ вы можете начать <b>экспортъ</b> въ файлы съ расширеніемъ: <b>.txt, .gz</b>.';
$Definition['You have %s invitations left for this month.'] = 'У Васъ %s пропущенныхъ приглашеній въ этомъ мѣсяцѣ.';
$Definition['You must have the MySQL driver for PDO enabled in order for Vanilla to connect to your database.'] = 'Для подключенія къ базѣ данныхъ у Васъ должны быть включены драйвера MySQL.';
$Definition['You must have the PDO module enabled in PHP in order for Vanilla to connect to your database.'] = 'Включите въ PHP модуль PDO для подключенія къ базѣ данныхъ.';
$Definition['You must manually apply this rank.'] = 'Вамъ нужно вручную примѣнить этотъ рангъ.';
$Definition['You must select a file to import.'] = 'Вы должны выбрать файлъ для импорта';
$Definition['You must specify an admin password.'] = 'Вы не ввели пароль администратора';
$Definition['You must specify an admin username.'] = 'Вы не ввели имя администратора';
$Definition['You need to configure ProxyConnect'] = 'Вамъ необходимо настроить ProxyConnect';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Спасибо. Ваша заявка будетъ разсмотрѣна администраторомъ. Вы будете увѣдомлены по электронной почтѣ, если ваша заявка будетъ одобрена.';
$Definition['Your changes were saved successfully.'] = 'Ваши измѣненія были успѣшно сохранены.';
$Definition['Your configuration file does not have the correct permissions. PHP needs to be able to read and write to this file: <code>%s</code>'] = 'Неправильно установлены права для файла конфигураціи. PHP долженъ имѣть возможность чтенія и записи въ файлъ: <code>%s</code>';
$Definition['Your default locale won\'t display properly'] = 'Ваше мѣстоположеніе по умолчанію не отображается правильно. Пожалуйста, выберите его: %s.';
$Definition['Your invitations were sent successfully.'] = 'Вашъ инвайтъ былъ успѣшно отосланъ';
