<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s приняли %4$s приглашеніе.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s измѣнили %4$s полномочія.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s обновили фотографію на страницѣ:';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s прокомментировали %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s создали учетную запись для %4$s.';
$Definition['%1$s joined.'] = '%1$s — теперь участникъ нашего форума.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s упомянули %3$s въ %8$s';
$Definition['%1$s on %2$s'] = '%1$s на %2$s';
$Definition['%1$s signed in.'] = '%1$s вошли.';
$Definition['%1$s to %2$s'] = 'отъ %1$s до %2$s';
$Definition['%1$s to %2$s of %3$s'] = 'отъ %1$s до %2$s изъ %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s обновили %6$s профиль.
';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s былъ добавлены въ группу "%2$s"';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s были удалены изъ группы "%2$s"';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s былъ перенесены изъ группы "%2$s" въ группу "%4$s"';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s написали на %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = 'Членство пользователя %2$s было утверждено %3$s.';
$Definition['%3$s created an account for %1$s.'] = '%3$s создали учетную запись для %1$s.';
$Definition['%s$1 to %s$2'] = 'отъ %s$1 до %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = 'отъ %s$1 до %s$2 изъ %s$3';
$Definition['%s (Current)'] = '%s (текущее)';
$Definition['%s Agrees'] = '%s согласныхъ';
$Definition['%s and %s others'] = '%s и %s других';
$Definition['%s and you'] = '%s и вы';
$Definition['%s Answers'] = '%s ответов';
$Definition['%s Awesomes'] = '%s впечатленній';
$Definition['%s changed %s\'s permissions.'] = '%s измѣнили настройки доступа';
$Definition['%s Comment'] = '%s комментарій';
$Definition['%s comment'] = 'Сообщеній: %s';
$Definition['%s comment html'] = '%s комментарий';
$Definition['%s Comments'] = '%s комментаріевъ';
$Definition['%s comments'] = 'Сообщеній: %s';
$Definition['%s comments html'] = '%s комментариев';
$Definition['%s Connect'] = '%s Соедененъ';
$Definition['%s day'] = '%s день';
$Definition['%s days'] = '%s дней';
$Definition['%s deleted this conversation.'] = '%s удалили этотъ діалогъ.';
$Definition['%s discussion'] = '%s темъ';
$Definition['%s discussion html'] = '%s темъ';
$Definition['%s discussions'] = '%s темъ';
$Definition['%s discussions html'] = '%s темъ';
$Definition['%s has been Jailed.'] = '%s были заключены.';
$Definition['%s has created an account for you at %s.'] = '%s создал для вас аккаунт в %s.';
$Definition['%s has invited you to join %s.'] = '%s пригласил вас вступить в %s.';
$Definition['%s has left this conversation.'] = '%s покинули этотъ діалогъ.';
$Definition['%s has reset your password at %s.'] = '%s сбросил ваш пароль в %s.';
$Definition['%s hour'] = '%s час';
$Definition['%s hours'] = '%s часов';
$Definition['%s Insightfuls'] = '%s проницаній';
$Definition['%s is jailed.'] = '%s в тюрьме';
$Definition['%s Likes'] = '%s лайковъ';
$Definition['%s LOLs'] = '%s ЛОЛОВЪ';
$Definition['%s member'] = '%s участник';
$Definition['%s members'] = '%s участников';
$Definition['%s mentioned %s in a %s.'] = '%s упомянули васъ въ отзывѣ';
$Definition['%s message'] = '%s сообщеніе';
$Definition['%s messages'] = '%s сообщенія';
$Definition['%s month'] = '%s месяц';
$Definition['%s months'] = '%s месяцев';
$Definition['%s New'] = '%s новое';
$Definition['%s new'] = '%s новыхъ';
$Definition['%s new comment since you last read this.'] = '%s новыхъ комментаріевъ съ момента вашего послѣдняго прочтенія.';
$Definition['%s new comments since you last read this.'] = '%s новыхъ комментаріевъ съ момента вашего послѣдняго прочтенія.';
$Definition['%s New Plural'] = 'Новыя сообщенія: %s';
$Definition['%s new plural'] = '%s новыхъ';
$Definition['%s Not Found'] = '%s Не найдено';
$Definition['%s not found.'] = '%s не найден.';
$Definition['%s of %s'] = '%s → %s ';
$Definition['%s other'] = '%s другое';
$Definition['%s others'] = '%s других';
$Definition['%s people have earned this badge.'] = 'Людей, получивших этот значок: %s';
$Definition['%s person has earned this badge.'] = '%s человек получил этот значок. ';
$Definition['%s Point'] = '%s очко';
$Definition['%s point'] = '%s балловъ';
$Definition['%s Points'] = '%s очковъ';
$Definition['%s points'] = '%s очковъ';
$Definition['%s posts'] = '%s сообщеній';
$Definition['%s said'] = '%s сказали';
$Definition['%s said:'] = '%s написалъ:';
$Definition['%s Settings'] = '%s настройки';
$Definition['%s tag(s) found.'] = '%s тэгъ(овъ) найдено.';
$Definition['%s tags in the system'] = '%s тэговъ въ системѣ';
$Definition['%s Up Votes'] = '%s проголосовавшихъ';
$Definition['%s user'] = '%s пользователь';
$Definition['%s users'] = '%s пользователей';
$Definition['%s view'] = '%s просмотръ';
$Definition['%s view html'] = '%s просмотръ';
$Definition['%s viewing'] = '%s просматривающих';
$Definition['%s views'] = '%s просмотровъ';
$Definition['%s views html'] = '%s просмотровъ';
$Definition['%s votes'] = '%s проголосовало';
$Definition['%s was removed from the %s and added to the %s'] = '%s былъ удаленъ изъ %s и добавленъ въ %s';
$Definition['%s week'] = '%s неделя';
$Definition['%s WTFs'] = '%s WTF-ковъ';

$Definition['&laquo; hide previous quotes'] = '&laquo; скрыть предыдущие ценовые предложения';
$Definition['&raquo; show previous quotes'] = '&raquo; показать предыдущие ценовые предложения';

$Definition['(empty message)'] = '(пустое сообщеніе)';
$Definition['(Spoiler)'] = '(Спойлер)';

$Definition['+%s Guests'] = '+%s Гостей';

$Definition[' - Page %s'] = '- Страница %s';

$Definition['1 message'] = 'Одно сообщеніе';

$Definition['<General Error>'] = '<Общая ошибка>';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Пользователей подтверждено';
$Definition['[%s] Welcome Aboard!'] = '[%s] Добро пожаловать!';
$Definition['[Deleted User]'] = '[Пользователь удаленъ]';

$Definition['About'] = 'Подробная информація';
$Definition['About %s users'] = 'Около %s пользователей ';
$Definition['AboutToDelete'] = 'You are about to delete %s.';
$Definition['AboutToDeleteSelectedDiscussions'] = 'You are about to delete %1$s of the %2$s selected discussions.';
$Definition['Abuse'] = 'Жалоба';
$Definition['Accept'] = 'Одобрить';
$Definition['Accepted'] = 'Одобренъ(а)';
$Definition['Accept this answer.'] = 'Сей отвѣтъ вѣрный.';
$Definition['Access the Site'] = 'Доступ к сайту';
$Definition['Account Options'] = 'Опціи аккаунта';
$Definition['Actions'] = 'Действия';
$Definition['Activate'] = 'Активированный';
$Definition['Active'] = 'Активно';
$Definition['Active Users'] = 'Активные пользователи';
$Definition['Activity'] = 'Дѣятельность';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s приняли %4$s %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s комментируетъ вашу %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s комментируетъ вашу %8$s.';
$Definition['Activity.Comment'] = 'Комментарій';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s упомянули %3$s въ %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s упомянули %3$s въ %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s отправилъ %8$s для %3$s';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s отправилъ %8$s для %3$s';
$Definition['Activity.Join.FullHeadline'] = 'теперь %1$s участникъ(ца) форума.';
$Definition['Activity.Join.ProfileHeadline'] = 'теперь %1$s участникъ(ца) форума';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s обновили фотографію на страницѣ:';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s обновили фотографію на страницѣ:';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s answered %4$s %8$s.';
$Definition['Add'] = 'Добавить';
$Definition['Add %s'] = 'Добавить %s';
$Definition['Add a Comment'] = 'Оставить отзывъ';
$Definition['Add a Message'] = 'Добавить сообщеніе';
$Definition['Add an explanation'] = 'Добавить объяснение';
$Definition['Add another poll option ...'] = 'Добавить другой варіантъ отвѣта';
$Definition['Add a Profile Picture'] = 'Добавить фотографію';
$Definition['Add a Warning'] = 'Добавить предупрежденіе';
$Definition['Add Badge'] = 'Добавить значекъ';
$Definition['Add Comment'] = 'Отправить';
$Definition['Add Cost'] = 'Добавить цѣну';
$Definition['Add Image'] = 'Добавить картинку';
$Definition['Add Message'] = 'Добавить сообщеніе';
$Definition['Add Note'] = 'Добавить запись';
$Definition['Add People to this Conversation'] = 'Добавить людей къ разговору? <i>(Введите имя пользователя)</i>';
$Definition['Add Route'] = 'Добавить перенаправленіе';
$Definition['Administrator'] = 'Администраторъ';
$Definition['Administrator Activity'] = 'Активность администраторовъ';
$Definition['Administrator and moderator'] = 'Администратор и модератор';
$Definition['administrators'] = 'Администраторы';
$Definition['Advanced'] = 'Настройки';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Произошла ошибка при обработкѣ запроса <br /> серверъ вернулъ слѣдующее сообщеніе: %s';
$Definition['Agree'] = 'Согласенъ';
$Definition['Alert'] = 'Предупрежденіе';
$Definition['All'] = 'Все';
$Definition['All %s'] = 'Все %s';
$Definition['All Bookmarks'] = 'Все закладки';
$Definition['All Categories'] = 'Все категоріи';
$Definition['all categories'] = 'все категоріи';
$Definition['All Conversations'] = 'Все разговоры';
$Definition['All Discussions'] = 'Все темы';
$Definition['All discussions marked as viewed.'] = 'Все дискуссии отмечены как просмотренные.';
$Definition['All Messages'] = 'Все сообщения';
$Definition['All Notifications'] = 'Все уведомления';
$Definition['Allow'] = 'Одобрить';
$Definition['Allow other members to see your email?'] = 'Показывать вашъ email<br>другимъ пользователямъ?';
$Definition['All Statuses'] = 'Все статусы';
$Definition['All Time Leaders'] = 'Лидеры за все время';
$Definition['Already Offered'] = 'Ранее предложенные';
$Definition['Already Warned'] = 'Уже предупрежден';
$Definition['Also banned for the following:'] = 'Был заблокирован за следующее: ';
$Definition['A message has been sent to your email address with password reset instructions.'] = 'На вашъ email выслано письмо съ инструкціей по смѣнѣ пароля';
$Definition['Analytics'] = 'Аналитика';
$Definition['Ancient Membership'] = 'Древнее членство';
$Definition['An invitation has already been sent to the email you entered.'] = 'Инвайтъ былъ отправленъ на тотъ Email, который вы ввели';
$Definition['Announce'] = 'Анонсъ';
$Definition['Announce...'] = 'Всегда наверху';
$Definition['Announcement'] = 'Объявленіе';
$Definition['Announcements'] = 'Объявленія';
$Definition['Announce this discussion'] = 'Объявить эту дискуссію';
$Definition['Answer'] = 'Отвѣтъ';
$Definition['answer'] = 'отвѣтъ';
$Definition['Answers'] = 'Вопросы';
$Definition['Appearance'] = 'Внѣшній видъ';
$Definition['Applicant'] = 'Кандидатъ';
$Definition['Applicants'] = 'Ожидаютъ одобренія';
$Definition['Apply'] = 'Включить';
$Definition['Apply Changes'] = 'Сохранить настройки';
$Definition['Apply for Membership'] = 'Зарегистрироваться';
$Definition['Apply for membership'] = 'Вступить въ команду';
$Definition['Approve'] = 'Допускъ';
$Definition['Approve Applicant'] = 'Допускъ';
$Definition['Approved'] = 'Утверждено';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Вы точно хотите выполнить это дѣйствіе?';
$Definition['Are you sure you want to delete this %s?'] = 'Вы увѣрены, что хотите удалить %s?';
$Definition['Are you sure you want to do that?'] = 'Вы увѣрены, что хотите сдѣлать это?';
$Definition['Are you sure you want to do this?'] = 'Вы увѣрены, что хотите сдѣлать это?';
$Definition['Are you sure you want to leave this conversation?'] = 'Вы уверены, что хотите покинуть этот диалог?';
$Definition['Are you sure you wish to continue?'] = 'Вы увѣрены, что хотите продолжить?
';
$Definition['Ask a Question'] = 'Задать вопросъ';
$Definition['Ask Question'] = 'Отправить';
$Definition['Attach a file'] = 'Прикрѣпить файлъ';
$Definition['Attachments'] = 'Прикрѣпленные файлы';
$Definition['AttemptingSignOut'] = 'Вы пытаетесь выйти. Вы увѣрены, что хотите %s?
';
$Definition['Authenticate URL'] = 'Провѣрить URL';
$Definition['available'] = 'доступно';
$Definition['Awaiting Moderation'] = 'Ожидаетъ модераціи';
$Definition['Awesome'] = 'Потрясающій';

$Definition['Back to Discussions'] = 'Вернуться къ просмотру темъ';
$Definition['Back to Profile'] = 'Вернуться въ профиль';
$Definition['Badge'] = 'Значекъ';
$Definition['Badge404'] = 'Значекъ не найденъ.';
$Definition['Badges'] = 'Значки';
$Definition['BadgesModuleTitle'] = 'Значки';
$Definition['BadgesNobody'] = 'Никто еще небылъ награжденъ этимъ значкомъ.';
$Definition['Ban'] = 'Заблокировать';
$Definition['Ban.Action'] = 'Заблокировать';
$Definition['Banned'] = 'Забаненъ';
$Definition['Banned for being abusive.'] = 'Заблокированъ, за оскорбленія';
$Definition['Banned for spamming.'] = 'Забаненъ за спамъ.';
$Definition['Banned for the following:'] = 'Заблокирован за следующее:';
$Definition['Banned users can no longer access the site.'] = 'Забаненные пользователи не имѣютъ доступа къ сайту.';
$Definition['Banner'] = 'Названіе и лого';
$Definition['BanReason.1'] = 'Заблокирован менеджером сообщества.';
$Definition['BanReason.2'] = 'Заблокирован по IP адресу, электронной почте или никнейму.';
$Definition['BanReason.4'] = 'Временно забанен менеджером сообщества.';
$Definition['BanReason.8'] = 'Заблокирован за предупреждения.';
$Definition['Ban User'] = 'Заблокированные пользователи';
$Definition['Ban Value'] = 'Значеніе';
$Definition['Basic'] = 'По умолчанію';
$Definition['Best Answer'] = 'Лучшій отвѣтъ';
$Definition['Best Answers'] = 'Лучшія отвѣты';
$Definition['Best Of'] = 'Лучшее';
$Definition['Best Of...'] = 'Лучшее...';
$Definition['Blank Discussion Topic'] = 'Пустая тема обсужденія';
$Definition['Blank Message'] = 'Пустое сообщеніе';
$Definition['Body'] = 'текстъ сообщенія';
$Definition['Bookmark'] = 'Добавить въ закладки';
$Definition['Bookmarked Discussions'] = 'Ваши закладки';
$Definition['Bookmarks'] = 'Закладки';
$Definition['bookmarks'] = 'закладки';
$Definition['Browse popular groups.'] = 'Обзор популярных групп.';
$Definition['By'] = 'Отъ';
$Definition['by'] = 'по';
$Definition['By %s'] = 'Отъ %s';
$Definition['by %s'] = 'отъ %s';
$Definition['by Date'] = 'по Датѣ';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Загружая изображеніе, вы автоматически подтверждаете, что имѣете право распространять загружаемое изображеніе и не нарушаете <strong>авторскія права правообладателя</strong>.';

$Definition['Can\'t post as often.'] = 'Не может создавать дискуссии';
$Definition['Can\'t post discussions.'] = 'Не может создавать дискуссии';
$Definition['Cancel'] = 'Отмѣна';
$Definition['Casual'] = 'Повседневный';
$Definition['Categories'] = 'Категоріи';
$Definition['CategoriesShowFollowed'] = 'Показать только тѣ категоріи, на которыя я подписанъ.';
$Definition['CategoriesShowUnfollowed'] = 'Показать категоріи на которыя Вы не подписаны.';
$Definition['CategoriesViewingAll'] = 'Вы просматриваете все категоріи.';
$Definition['CategoriesViewingFollowed'] = 'Вы просматриваете только тѣ категоріи, на которыя подписаны.';
$Definition['Category'] = 'Категорія';
$Definition['Category Filter'] = 'отсеяваніе категорій';
$Definition['CategoryID'] = 'Категорія';
$Definition['Category Management'] = 'Менеджеръ категорій';
$Definition['Category marked as viewed.'] = 'Раздел отмечен как просмотренный.';
$Definition['Category Notifications'] = 'Увѣдомленія раздѣла';
$Definition['Category to Use'] = 'Используемая категорія';
$Definition['Change'] = 'Измѣнить';
$Definition['Change Icon'] = 'Изменить иконку';
$Definition['Change My Password'] = 'Измѣнить мой пароль';
$Definition['Change My Picture'] = 'Измѣнить мое изображеніе';
$Definition['Change Password'] = 'Измѣненіе пароля';
$Definition['Change Picture'] = 'Измѣненіе изображенія';
$Definition['Check all roles that apply to this user:'] = 'Провѣрьте все группы, въ которыхъ можетъ состоять этотъ пользователь:';
$Definition['Check it out'] = 'Перейдите к материалу';
$Definition['Child Categories'] = 'Дочерніе категоріи';
$Definition['Child Categories:'] = 'Дочерняя категорія:';
$Definition['Choose a name to identify yourself on the site.'] = 'Выберите имя для идентификаціи себя на сайтѣ';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Выберите дискуссію, въ которую будутъ объединены все комментаріи:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Выберите, хотите ли вы задать вопросъ или начать обсужденіе.';
$Definition['Clear'] = 'Очистить';
$Definition['clear'] = 'очистить';
$Definition['Clear %s'] = 'Очистить %s';
$Definition['Clear Conversation History'] = 'Очистить исторію діалога';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Нажмите <a href="%s">здѣсь</a> чтобы вернуться къ темѣ.';
$Definition['Click accept or reject beside an answer.'] = 'Кликните "Одобрить" или "Отклонить" для того, чтобы отвѣтить на вопросъ.';
$Definition['clicking here'] = 'ссылкѣ';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Нажмите %s рядомъ съ темой, чтобы добавить въ закладки.';
$Definition['Close'] = 'Закрыть';
$Definition['Closed'] = 'Закрыто';
$Definition['Close this discussion'] = 'Закрыть эту тему';
$Definition['Combo Breaker'] = 'Комбо выключатель';
$Definition['Comment'] = 'Отправить';
$Definition['comment'] = 'отзывы';
$Definition['Comment As ...'] = 'Комментировать какъ ...';
$Definition['Comment by %s'] = 'Отзывъ %s';
$Definition['Comment in'] = 'въ';
$Definition['Commenting as %1$s (%2$s)'] = 'Commenting as %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Комментированіе запрещено.';
$Definition['Comments'] = 'Отзывы';
$Definition['Comments are between {UserID,you}.'] = 'Комментаріи между {UserID,you}.';
$Definition['Community Home'] = 'Дом сообщества';
$Definition['Completed'] = 'Завершено';
$Definition['Completely delete the warning.'] = 'Полностью удалить предупрежденіе.';
$Definition['Confirm'] = 'Подтвержденіе';
$Definition['Confirmed email address'] = 'Подтвержденный email адрес';
$Definition['Confirm Email'] = 'Подтвердите email';
$Definition['Confirm My Email Address'] = 'Подтвердить мой адрес эл. почты';
$Definition['Confirm Password'] = 'Подтвердите пароль';
$Definition['Confirm Your Email Address'] = 'Подтвердите свой адрес эл. почты';
$Definition['Connect'] = 'Соединеніе';
$Definition['ConnectAccountExists'] = 'У васъ уже есть здѣсь учетная запись.';
$Definition['ConnectChooseName'] = 'Выберите имя подъ которымъ вы будете извѣстны на сайтѣ. ';
$Definition['ConnectCreateAccount'] = 'Добавить информацію & Создать учетную запись';
$Definition['Connected With: {ProviderName}'] = 'Подключение через: {ProviderName}';
$Definition['ConnectExistingPassword'] = 'Введите вашъ существующій пароль.';
$Definition['Connecting...'] = 'Подключеніе...';
$Definition['Connection'] = 'Подключеніе';
$Definition['ConnectLeaveBlank'] = 'Оставить пустымъ въ томъ случаѣ если вы не подключаетесь къ существующей учетной записи.';
$Definition['ConnectName'] = 'Никъ';
$Definition['ConnectRegisteredName'] = 'Ваше имя учетной записи: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Connect your profile to social networks to be notified of activity here and share your activity with your friends and followers.';
$Definition['conversation'] = 'діалоги';
$Definition['Copy'] = 'Копировать';
$Definition['Core'] = 'Ядро';
$Definition['Couldn\'t confirm email.'] = 'Невозможно подтвердить адрес почты.';
$Definition['Create Discussions'] = 'Создать обсужденіе';
$Definition['Created on %s'] = 'Создано: %s';
$Definition['Create One.'] = 'Зарегистрируйтесь!';
$Definition['Current'] = 'Текущій';
$Definition['Currently: '] = 'Сейчасъ';
$Definition['Custom Information'] = 'Особая информація';
$Definition['Customize'] = 'Выдѣляйся';
$Definition['customize your profile now'] = 'настройки профиля';
$Definition['Customize your Public Profile'] = 'Измѣненіе вашего профиля';
$Definition['Custom Profile Fields'] = 'Произвольныя поля аккаунта';
$Definition['Custom Profile Field Settings'] = 'Настройка особыхъ полей профиля';

$Definition['Dashboard'] = 'Панель управленія';
$Definition['Dashboard Home'] = 'Главная страница панели';
$Definition['Dashboard Summaries'] = '<b>Панель управленія</b>. Основная информація';
$Definition['Date'] = 'Дата';
$Definition['Date.DefaultDateTimeFormat'] = '%B %e, %Y %l:%M%p';
$Definition['Date.DefaultDayFormat'] = '%A %e <font style="text-transform:lowercase;">%b</font> въ %H:%M';
$Definition['Date.DefaultFormat'] = '%h %i, %Y, %H:%M';
$Definition['Date.DefaultTimeFormat'] = 'сегодня въ %H:%M';
$Definition['Date.DefaultYearFormat'] = '%e <font style="text-transform:lowercase;">%b</font> %Y';
$Definition['Date Added'] = 'Дата добавленія';
$Definition['Date Examples'] = 'Examples: Monday, today, last week, Mar 26, 3/26/04';
$Definition['days'] = 'дней';
$Definition['Decline'] = 'Отклонить';
$Definition['Declined'] = 'Отклонено';
$Definition['Default'] = 'По умолчанію';
$Definition['default'] = 'по умолчанію';
$Definition['Default Status'] = 'Статус по умолчанию';
$Definition['Define Thumbnail'] = 'Кликните и выберите область на основной фотографіи, которая будетъ отображаться въ миніатюрахъ на сайтѣ.';
$Definition['Delete'] = 'Удалить';
$Definition['Delete %s'] = 'Удалить %s';
$Definition['Delete Account'] = 'Удалить учетную запись';
$Definition['Delete Conversation'] = 'Удалить все сообщенія';
$Definition['Delete Discussion'] = 'Удалить топикъ';
$Definition['Delete Forever'] = 'Удалить навсегда';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Удалить пользователя и содержимое его профиля. Это можетъ вызвать нѣкоторую путаницу, т.к. пользователи отвѣтившіе ранѣе на сообщенія этого пользователя - не увидятъ ихъ. Хорошо подходитъ для удаленія хлама.';
$Definition['Delete User Content'] = 'Удалить сообщенія пользователя';
$Definition['Delete User Forever'] = 'Удалить пользователя навсегда';
$Definition['Deny Applicant'] = 'Deny';
$Definition['Description'] = 'Описаніе';
$Definition['Did this answer the question?'] = 'Это отвѣтъ на вопросъ?';
$Definition['Disable'] = 'Выключить';
$Definition['Disabled'] = 'Выключено';
$Definition['Disagree'] = 'Не согласиться';
$Definition['Discussion'] = 'Только на страницахъ дискуссій';
$Definition['discussion'] = 'тему';
$Definition['Discussions'] = 'Все темы';
$Definition['Discussions Page'] = 'Дискуссіи';
$Definition['Discussion Title'] = 'Заголовокъ темы';
$Definition['Dislike'] = 'Не одобрять';
$Definition['Dismiss'] = 'Отмѣнить';
$Definition['Documentation'] = 'Документация';
$Definition['Don\'t announce.'] = 'Не объявлять.';
$Definition['Don\'t have an account? %s'] = 'Нѣтъ аккаунта? %s';
$Definition['Download the sounds as MP3'] = 'Скачать аудио в виде MP3';
$Definition['Do you want to expire or delete this warning?'] = 'Вы хотите отмѣтить это предупрежденіе какъ устарѣвшее или удалить?';
$Definition['Draft.Delete'] = 'Удалить';
$Definition['Draft saved at %s'] = 'Черновикъ сохраненъ %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Выдѣлите и измѣните размѣръ вашего аватара.';

$Definition['Earned'] = 'Заработанно';
$Definition['Edit'] = 'Измѣнить';
$Definition['edit'] = 'редактировать';
$Definition['Edit %s'] = 'Редактировать %s';
$Definition['Edit Account'] = 'Измѣнить учетную запись';
$Definition['Edit Comment'] = 'Измѣнить комментарій';
$Definition['Edit Discussion'] = 'Измѣнить обсужденіе';
$Definition['Editing'] = 'Редактированіе';
$Definition['Edit My Account'] = 'Измѣнить мой учетную запись';
$Definition['Edit My Profile'] = 'Измѣнить профиль';
$Definition['Edit My Thumbnail'] = 'Измѣнить мой аватаръ';
$Definition['editor.BBCodeHelpText'] = 'You can use <a href="http://en.wikipedia.org/wiki/BBCode" target="_new">BBCode</a> in your post.';
$Definition['editor.HtmlHelpText'] = 'Вы можете использовать <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple HTML</a> в вашей публикации.';
$Definition['editor.MarkdownHelpText'] = 'You can use <a href="http://en.wikipedia.org/wiki/Markdown" target="_new">Markdown</a> in your post.';
$Definition['editor.TextHelpText'] = 'You are using plain text in your post.';
$Definition['editor.WysiwygHelpText'] = 'Вы используете <a href="https://ru.wikipedia.org/wiki/WYSIWYG" target="_new">WYSIWYG</a> в вашей публикации.';
$Definition['Edit Preferences'] = 'Измѣнить настройки';
$Definition['Edit Profile'] = 'Измѣнить учетную запись';
$Definition['Edit Tag'] = 'Измѣнить тэгъ';
$Definition['Edit Thumbnail'] = 'Измѣненіе аватара';
$Definition['Eighth Anniversary'] = 'Восьмая годовщина';
$Definition['Email'] = 'Эл. почта';
$Definition['Email/Username'] = 'Почта или Логинъ';
$Definition['EmailConfirmEmail'] = 'Вамъ необходимо подтвердить Вашъ email.
Для подтвержденія нажмите на ссылку ниже: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '

Удачнаго дня!';
$Definition['EmailHeader'] = 'Здравствуйте, {User.Name}!
';
$Definition['EmailInvitation'] = 'Привѣтъ!



%1$s приглашаетъ присоединиться %2$s.

Если вы хотите присоедниться, то перейдите по ссылкѣ:

%3$s



Спасибо за вниманіе!';
$Definition['EmailMembershipApproved'] = 'Привѣтъ %1$s,



Вы были приняты. Вы можете войти по этой ссылкѣ:

%2$s



Спасибо за вниманіе!';
$Definition['EmailNotification'] = '%1$s



Для провѣрки перейдите по ссылкѣ:

%2$s



Спасибо за вниманіе!';
$Definition['Email Notifications'] = 'Увѣдомленія по Email';
$Definition['Email Or Username'] = 'Имя пользователя или email';
$Definition['EmailPassword'] = 'Привѣтъ %1$s,



%2$s сбросилъ вашъ пароль въ %3$s. Ваши данные:



Email: %6$s

Пароль: %5$s

Ссылка: %4$s



Благодаримъ за вниманіе!';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Использовать въ качествѣ отправителя слѣдующій адресъ электронной почты:';
$Definition['Email Source'] = 'Эл. почта';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---------------------------------

Для провѣрки перейдите по ссылкѣ:

%2$s



Благодаримъ за вниманіе!';
$Definition['Email Unavailable'] = 'Почта недоступна';
$Definition['Email visible to other users'] = 'Email виденъ другимъ пользователямъ';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Прочитайте подробно тутъ</a></p><div class="ClearFix"></div></div>';
$Definition['EmbeddedNoBodyFormat'] = '{Url}';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Прочитайте подробно тутъ</a></p><div class="ClearFix"></div></div>';
$Definition['Enable'] = 'Включить';
$Definition['Enabled'] = 'Включено';
$Definition['Enter your Email address'] = 'Адресъ вашей почты';
$Definition['Enter your email address'] = 'Введите вашъ email адресъ';
$Definition['Enter your Email address or username'] = 'Введите вашъ Email или логинъ';
$Definition['Enter Your OpenID Url'] = 'Введите вашъ OpenID адресъ';
$Definition['Enter your search term.'] = 'Введите ваш критерий поиска.';
$Definition['Erase User Content'] = 'Удалить сообщенія пользователя';
$Definition['Error'] = 'Ошибка';
$Definition['ErrorBadInvitationCode'] = 'Ошибка: невѣрный кодъ приглашенія';
$Definition['ErrorCredentials'] = 'Къ сожалѣнію, нѣтъ доступа къ этой учетной записи';
$Definition['ErrorPermission'] = 'Простите, но у васъ нѣтъ разрѣшенія';
$Definition['ErrorPluginDisableRequired'] = 'Вы не можете отключить плагинъ {0}, такъ какъ плагинъ зависитъ отъ {1}.';
$Definition['ErrorPluginEnableRequired'] = 'Прежде чѣмъ включить этотъ плагинъ, необходимо включить плагинъ: {0}.';
$Definition['ErrorPluginVersionMatch'] = 'Активированный {0} плагинъ (версіи {1}) не отвѣчаетъ условіямъ, необходимымъ версіи ({2}).';
$Definition['ErrorRecordNotFound'] = 'Запрошеная запись не найдена';
$Definition['ErrorTermsOfService'] = 'Вы должны согласиться съ условіями использованія.';
$Definition['everyone'] = 'все';
$Definition['Everything'] = 'Всѣ';
$Definition['Expired'] = 'Истекло';
$Definition['Expires'] = 'Истекаетъ';
$Definition['expires %s'] = 'истекает: %s';

$Definition['Facebook Connect'] = 'Подключиться к Facebook';
$Definition['Failed to find discussion for commenting.'] = 'Не удалось найти обсужденіе для комментаріевъ.';
$Definition['Failed to load the poll.'] = 'Ошибка загрузки опроса';
$Definition['Favorites'] = 'Избранное';
$Definition['Feedback'] = 'Обратная связь';
$Definition['Female'] = 'Женскаго пола';
$Definition['Fifth Anniversary'] = 'Пятая годовщина';
$Definition['FileName'] = 'Названіе файла';
$Definition['Filename'] = 'Названіе файла';
$Definition['FileSize'] = 'Размѣръ файла';
$Definition['File Size'] = 'Размѣръ файла';
$Definition['Find your account information below.'] = 'Ниже представлена информация вашего аккаунта.';
$Definition['First Anniversary'] = 'Первая годовщина';
$Definition['First Answer'] = 'Первый ответ';
$Definition['First Comment'] = 'Первый комментарій';
$Definition['Flag'] = 'Пожаловаться';
$Definition['Folder'] = 'Папка';
$Definition['Folders'] = ' Папки';
$Definition['Follow'] = 'Подписаться';
$Definition['Follow %s'] = 'Слѣдить %s';
$Definition['Followed by %d people'] = '%d подписчиковъ';
$Definition['Followed by %d person'] = 'Подписанъ %d человѣкъ';
$Definition['followed categories'] = 'отслѣживаемыя категорій';
$Definition['Following %d people'] = 'Слѣдитъ за %d людми';
$Definition['Following %d person'] = 'Слѣдитъ за %d человѣкомъ';
$Definition['FollowOnly'] = 'Follow the link below to check it out:';
$Definition['Follows'] = 'Слѣдятъ';
$Definition['For a stronger password, increase its length or combine upper and lowercase letters, digits, and symbols.'] = 'Чтобы сделать пароль более надежным, увеличьте его длину или комбинируйте буквы верхнего и нижнего регистра, цифры и символы.';
$Definition['Forgot?'] = 'Забыли?';
$Definition['Forgot your password?'] = 'Забыли вашъ пароль?';
$Definition['Format his'] = 'его';
$Definition['Format their'] = 'ихъ';
$Definition['Format You'] = 'вы';
$Definition['Format you'] = 'я';
$Definition['Format Your'] = 'вашъ';
$Definition['Forum Signature Settings'] = 'Настройки подписей для форума';
$Definition['Fourth Anniversary'] = 'Четвертая годовщина';
$Definition['Friends'] = 'Друзья';
$Definition['From'] = 'Отъ';
$Definition['Full Site'] = 'Полная версія сайта';

$Definition['Garden.Email.SupportAddress'] = 'Email поддержки';
$Definition['Garden.Email.SupportName'] = 'Названіе поддержки';
$Definition['Garden.Registration.DefaultRoles'] = 'по-умолчанію';
$Definition['Garden.Title'] = 'Заголовокъ';
$Definition['Gender'] = 'Полъ';
$Definition['General'] = 'Общее';
$Definition['Generate import SQL only'] = 'Генерировать только импортъ SQL';
$Definition['Generate Password'] = 'Генерировать пароль';
$Definition['Get an audio challenge'] = 'Получить звуковой вызов';
$Definition['Get a new challenge'] = 'Получить вызов';
$Definition['Get a visual challenge'] = 'Получить визуальный вызов';
$Definition['Give'] = 'Выдать';
$Definition['Give a Badge to %s'] = 'Выдать значекъ %s';
$Definition['Give Badge'] = 'Выдать значекъ';
$Definition['Given'] = 'Выданный';
$Definition['Go'] = '→';
$Definition['GroupEmptyAnnouncements'] = 'Important stuff will go here one day.';
$Definition['GroupEmptyDiscussions'] = 'Awfully quiet in here, isn&rsquo;t it?';
$Definition['GroupEmptyEvents'] = 'Aw snap, no events are coming up.';
$Definition['Group Icon'] = 'Иконка группы';
$Definition['Group Leaders'] = 'Лидеры';
$Definition['Group Members'] = 'Members';
$Definition['GroupMembersEmpty'] = 'No one has joined yet. Spread the word!';
$Definition['Guest'] = 'Гость';
$Definition['GuestModule.Message'] = 'Похоже, вы новечекъ! Чтобы начать обсужденіе, нажмите одну изъ кнопокъ ниже.';
$Definition['Guests'] = 'гостей';

$Definition['Hang on a sec while we sign you out.'] = 'Подождите секунду, пока мы подпишемъ васъ';
$Definition['Have a great day!'] = 'Приятного вам дня!';
$Definition['he'] = 'онъ';
$Definition['Heading'] = 'Заголовок';
$Definition['HeadlineFormat.AcceptAnswer'] = '{ActivityUserID} принял ответ {NotifyUserID}.';
$Definition['HeadlineFormat.Answer'] = '{ActivityUserID,user} ответил(а) на ваш вопрос: <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} удостоились <a href="{Url,html}">{Data.Name,text}</a> значка.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} были забанены {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} комментировали <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.ConversationMessage'] = '{ActivityUserID,User} отправил вам <a href="{Url,html}">сообщение</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} начали новое обсужденіе. <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} упомянули васъ въ <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} измѣнили свою картинку {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} на сайтѣ.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} сняли банъ съ {ActivityUserID,you}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,You} предупредили {RegardingUserID,you}.';
$Definition['Hello!'] = 'Здравствуйте!';
$Definition['Hello %s!'] = 'Здравствуйте, %s!';
$Definition['Hello {User.Name}!'] = 'Здравствуйте, {User.Name}!';
$Definition['her'] = 'её';
$Definition['Hide'] = 'Скрыть';
$Definition['Hide previous quotes'] = '&laquo; скрыть предыдущие ценовые предложения';
$Definition['Hide signatures?'] = 'Скрыть подписи?';
$Definition['Hide signatures always'] = 'Не показывать подписи';
$Definition['Hide signatures on my mobile device'] = 'Скрывать подпись на мобильныхъ устройствахъ';
$Definition['his'] = 'его';
$Definition['Home'] = 'Домой';
$Definition['hours'] = 'часъ(овъ)';
$Definition['How can we help you?'] = 'Как мы можем вам помочь?';
$Definition['Howdy, Stranger!'] = 'Привѣтствуемъ Васъ!';
$Definition['How long do you want this warning to last?'] = 'На какой срокъ вынести предупрежденіе?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Соглашаюсь съ <a id="TermsOfService" class="Popup" target="terms" href="%s">правилами</a> форума';
$Definition['I confirm that I have received consent to join this community.'] = 'Так как я не достиг возраста %d лет, я подтверждаю, что получил согласие присоединиться к этому сообществу.';
$Definition['Idea'] = 'Идея';
$Definition['idea'] = 'идея';
$Definition['Ideas'] = 'Идеи';
$Definition['ideas'] = 'идеи';
$Definition['Idea Status'] = 'Статус идеи';
$Definition['Idea Statuses'] = 'Статусы идей';
$Definition['Ideation'] = 'Формирование идеи';
$Definition['images'] = 'изображения';
$Definition['Images not allowed'] = 'Изображения запрещены';
$Definition['Images will be scaled to a maximum height of {maxImageHeight}px.'] = 'Изображения будут отрегулированы до максимальной высоты {maxImageHeight}px';
$Definition['in'] = 'въ';
$Definition['In <b>%s.</b>'] = 'Въ <b>%s.</b>';
$Definition['In <b>%s</b> and recent discussions.'] = 'Въ <b>%s</b> и недавніе обсужденія.';
$Definition['Inbox'] = 'Входящія';
$Definition['Incorrect. Try again.'] = 'Не правильно. Повторите.';
$Definition['In Progress'] = 'В процессе';
$Definition['In Review'] = 'На рассмотрении';
$Definition['In seconds'] = ' въ секундахъ';
$Definition['Inserted'] = 'Вставлено';
$Definition['Insert Image'] = 'Вставить картинку въ сообщеніе';
$Definition['Insightful'] = 'Проницательно';
$Definition['Internal'] = 'Внутренній';
$Definition['In this Conversation'] = 'Пользователи';
$Definition['Invalid CSRF token.'] = 'Недопустимый маркер CSRF. Пожалуйста, попробуйте еще раз.';
$Definition['Invalid password.'] = 'Пароли который вы ввели невѣрный. Имѣйте ввиду что пароли различаются капитализаціей.';
$Definition['Invalid photo URL.'] = 'Неверный URL фото.';
$Definition['Invitations'] = 'Приглашенія';
$Definition['Invite'] = 'Инвайтъ';
$Definition['Invited on %s'] = 'Приглашен %s';
$Definition['InviteErrorPermission'] = 'Простите, но у васъ нѣтъ правъ.';
$Definition['Invite Members'] = 'Пригласить участников';
$Definition['IPAddress'] = 'IP-адресъ';
$Definition['IP Address'] = 'IP адресъ';
$Definition['I remember now!'] = 'Вспомнился пароль!';
$Definition['Item'] = 'Запись';
$Definition['item'] = 'Вкладъ';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Похоже, вы здѣсь новенькій! Чтобы пообщаться съ нами, кликните на одну изъ кнопокъ ниже :)';

$Definition['Jail'] = 'Темница';
$Definition['Jailed users have reduced abilities.'] = 'Заключенные пользователи ограниченны въ возможностяхъ.';
$Definition['Join'] = 'Вступить';
$Definition['Join Date'] = 'Дата вступления';
$Definition['Joined'] = 'Съ нами съ ';
$Definition['Join this Community Now'] = 'Вступить в это сообщество';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Удалить пользователя, но оставить все его записи.';
$Definition['Just expire the warning.'] = 'Просто истекаетъ предупрежденіе.';
$Definition['Just you!'] = 'Только вы!';

$Definition['Keep me signed in'] = 'Запомнить меня!';
$Definition['Keep User Content'] = 'Оставить контентъ пользователя';

$Definition['Label'] = 'Ярлыкъ';
$Definition['Last Active'] = 'Былъ на сайтѣ';
$Definition['Last IP'] = 'Послѣдній ip';
$Definition['Last Updated'] = 'Последнее изменение';
$Definition['Latest %1$s'] = 'Послѣдній %1$s';
$Definition['Latest Post'] = 'Послѣдній постъ';
$Definition['Leaders'] = 'Лидеры';
$Definition['Learn more about %s'] = 'Узнать больше о %s';
$Definition['Leave a Comment'] = 'Оставить комментарій';
$Definition['Leave a comment'] = 'Комментировать';
$Definition['Leave blank unless connecting to an existing account.'] = 'Если вы не подключаетесь к существующему аккаунту, оставьте поле пустым.';
$Definition['Leave Comments'] = 'Комментировать';
$Definition['Leave Conversation'] = 'Покинуть диалог';
$Definition['Leaving'] = 'Выход';
$Definition['Length'] = 'Длинна';
$Definition['Level %s'] = 'Уровень %s';
$Definition['Like'] = 'Лайкъ';
$Definition['Link to content:'] = 'Ссылка на контентъ:';
$Definition['Locale'] = 'Языкъ';
$Definition['Login with Facebook'] = 'Войти съ Facebook';

$Definition['Major'] = 'Главный';
$Definition['Make %s'] = 'Выдать роль: %s';
$Definition['Make Leader'] = 'В лидеры';
$Definition['Make me invisible? (Will not show you on the list)'] = 'Сдѣлать меня невидимымъ? (Не выдавать присутствіе на сайтѣ)';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Сдѣлать этотъ опросъ анонимный (голоса пользователей не публикуются).';
$Definition['Male'] = 'Мужчина';
$Definition['Manage Members'] = 'Управление участниками';
$Definition['Mark All Viewed'] = 'Отмѣтить все прочитаннымъ';
$Definition['Mark as Troll'] = 'Помѣтить какъ вредителя';
$Definition['Marking as spam cannot be undone.'] = 'Marking something as SPAM will cause it to be deleted forever. Deleting is a good way to keep your forum clean.';
$Definition['Mark Read'] = '<span title="Отмѣтить сообщенія въ этой категоріи прочитанными">Прочитано</span>';
$Definition['Media'] = 'Загрузка файловъ';
$Definition['Member'] = 'Участникъ';
$Definition['Member Count'] = 'Members';
$Definition['Merge'] = 'Объединеніе';
$Definition['Merge Discussions'] = 'Объединить темы';
$Definition['Message'] = 'Сообщеніе';
$Definition['message'] = 'сообщеніе';
$Definition['Messages'] = 'Сообщенія';
$Definition['messages'] = 'сообщенія';
$Definition['Message to User'] = 'Отправить сообщеніе';
$Definition['Minor'] = 'Малый';
$Definition['minutes'] = 'минутъ(ы)';
$Definition['Moderation'] = 'Модерированіе';
$Definition['Moderation Queue'] = 'Отложеная модерація';
$Definition['Moderator'] = 'Модераторъ';
$Definition['Moderator Activity'] = 'Активность модератора';
$Definition['Moderators'] = 'Модераторы';
$Definition['moderators'] = 'модераторы';
$Definition['month.letter.1'] = 'Я';
$Definition['month.letter.2'] = 'Ф';
$Definition['month.letter.3'] = 'М';
$Definition['month.letter.4'] = 'А';
$Definition['month.letter.5'] = 'М';
$Definition['month.letter.6'] = 'И';
$Definition['month.letter.7'] = 'И';
$Definition['month.letter.8'] = 'А';
$Definition['month.letter.9'] = 'С';
$Definition['month.letter.10'] = 'О';
$Definition['month.letter.11'] = 'Н';
$Definition['month.letter.12'] = 'Д';
$Definition['month.long.1'] = 'января';
$Definition['month.long.2'] = 'февраля';
$Definition['month.long.3'] = 'марта';
$Definition['month.long.4'] = 'апреля';
$Definition['month.long.5'] = 'мая';
$Definition['month.long.6'] = 'июня';
$Definition['month.long.7'] = 'июля';
$Definition['month.long.8'] = 'августа';
$Definition['month.long.9'] = 'сентября';
$Definition['month.long.10'] = 'октября';
$Definition['month.long.11'] = 'ноября';
$Definition['month.long.12'] = 'декабря';
$Definition['month.short.1'] = 'янв.';
$Definition['month.short.2'] = 'февр.';
$Definition['month.short.3'] = 'мар.';
$Definition['month.short.4'] = 'апр.';
$Definition['month.short.5'] = 'мая';
$Definition['month.short.6'] = 'июн.';
$Definition['month.short.7'] = 'июл.';
$Definition['month.short.8'] = 'авг.';
$Definition['month.short.9'] = 'сент.';
$Definition['month.short.10'] = 'окт.';
$Definition['month.short.11'] = 'нояб.';
$Definition['month.short.12'] = 'дек.';
$Definition['months'] = 'мѣсяцевъ';
$Definition['More'] = 'Еще';
$Definition['More Comments'] = 'Больше комментаріевъ';
$Definition['More Discussions'] = 'Больше дискуссій';
$Definition['More Information'] = 'Больше информаціи';
$Definition['More Results'] = 'Больше результатовъ';
$Definition['More…'] = 'Еще...';
$Definition['Most Recent'] = 'Самый новый';
$Definition['Most recent:'] = 'Самый новый:';
$Definition['Most recent: %1$s by %2$s'] = 'Новое: %1$s въ %2$s';
$Definition['Most recent by %1$s'] = 'Послѣднее сообщеніе отъ %1$s';
$Definition['Most Recent Comment'] = 'Новѣйшій отвѣтъ';
$Definition['Most recent discussion'] = 'Последняя дискуссия';
$Definition['Mute'] = 'Отключить уведомления';
$Definition['MyBadgesModuleTitle'] = 'My Badges';
$Definition['My Bookmarks'] = 'Закладки';
$Definition['My Discussions'] = 'Мои темы';
$Definition['My Drafts'] = 'Мои черновики';
$Definition['My Forums'] = 'Мои форумы';
$Definition['My Preferences'] = 'Мои настройки';
$Definition['My Signature'] = 'Моя подпись';

$Definition['n/a'] = 'Нѣтъ данныхъ';
$Definition['Name'] = 'Имя';
$Definition['Name Dropper'] = 'Неймдропперъ';
$Definition['Name Unavailable'] = 'Имя недоступно';
$Definition['new'] = 'новые';
$Definition['New Conversation'] = 'Начать новый діалогъ';
$Definition['New Discussion'] = 'Начать новую тему';
$Definition['new discussion'] = 'новые';
$Definition['New Icon'] = 'Новая иконка';
$Definition['New Idea'] = 'Новая идея';
$Definition['New Message'] = 'Начать новый діалогъ';
$Definition['New Password'] = 'Новый пароль';
$Definition['New Poll'] = 'Новый опросъ';
$Definition['Next'] = 'Слѣдующій';
$Definition['Ninth Anniversary'] = 'Девятая годовщина';
$Definition['No'] = 'Нѣтъ';
$Definition['NoBadgesEarned'] = 'Скоро …';
$Definition['No badges yet.'] = 'Нѣтъ значковъ';
$Definition['No default roles.'] = 'Группа по умолчанію настроена неправильно. Кликните сюда: %s, чтобы исправить это.';
$Definition['No discussions were found.'] = 'Не найденно ни одной темы';
$Definition['No items tagged with %s.'] = 'Ничего не отмѣчено тэгомъ %s.';
$Definition['None'] = 'Нѣтъ';
$Definition['NoPermissionToDeleteDiscussions'] = 'You do not have permission to delete %1$s of the selected discussions.';
$Definition['No results for \'%s\''] = 'Нѣтъ результатовъ для \'%s\'';
$Definition['No Roles'] = 'Нѣтъ ролей';
$Definition['Not Authorized (401)'] = 'Не авторизированы (401)';
$Definition['Notes'] = 'Примѣчаніе';
$Definition['Not Found (404)'] = 'Не найдена (404)';
$Definition['Notice'] = 'Извѣщеніе';
$Definition['Notification'] = 'Увѣдомленіе';
$Definition['Notification Preferences'] = 'Настройки увѣдомленій';
$Definition['Notifications'] = 'Увѣдомленія';
$Definition['Notifictions'] = 'Увѣдомленія';
$Definition['Notify'] = 'Увѣдомлять';
$Definition['Notify me of private messages.'] = 'Сообщать о новыхъ личныхъ сообщеніяхъ.';
$Definition['Notify me when a badge is requested.'] = 'Сообщите мнѣ, когда запрашивается значекъ.';
$Definition['Notify me when a comment is flagged.'] = 'Сообщите мнѣ когда комментарій отмѣченъ.';
$Definition['Notify me when I am added to private conversations.'] = 'Сообщать, когда меня добавляютъ къ приватному разговору.';
$Definition['Notify me when my ideas\' statuses change.'] = 'Сообщать мне об изменениях статуса моих идей.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Сообщать о комментаріяхъ въ темахъ изъ закладокъ.';
$Definition['Notify me when people comment on my discussions.'] = 'Сообщать о комментаріяхъ въ моихъ темахъ.';
$Definition['Notify me when people mention me.'] = 'Сообщать, когда люди ссылаются на меня.';
$Definition['Notify me when people mention me in comments.'] = 'Сообщать, когда меня упоминаютъ въ комментаріяхъ.';
$Definition['Notify me when people reply to my wall comments.'] = 'Сообщать объ отвѣтахъ на мои отзывы на стѣнѣ';
$Definition['Notify me when people write on my wall.'] = 'Сообщать о новыхъ надписяхъ на стѣнѣ';
$Definition['Notify me when the status changes on an idea I\'ve voted on.'] = 'Сообщать мне об изменении статуса идеи, за которую я голосовал.';
$Definition['Not much happening here, yet.'] = 'Пока еще ничего не произошло.';
$Definition['Not Verified'] = 'Непровѣренный';

$Definition[' now.'] = 'сейчасъ';

$Definition['Null Date'] = '-';

$Definition['Off'] = 'Выкл';
$Definition['Off Topic'] = 'Оффтопъ';
$Definition['OK'] = 'Да';
$Definition['Okay'] = 'Да';
$Definition['OldPassword'] = 'Старый пароль';
$Definition['Old Password'] = 'Старый пароль';
$Definition['On'] = 'На';
$Definition['on'] = 'на';
$Definition['Only show followed categories'] = 'Показать только тѣ категоріи, на которыя я подписанъ.';
$Definition['Open'] = 'Открыть';
$Definition['OpenID Settings'] = 'Настройки OpenID';
$Definition['Optional'] = 'Опционально';
$Definition['Optional Description'] = 'Дополнительное описаніе';
$Definition['Options'] = 'Настройки';
$Definition['or'] = 'или';
$Definition['Organize discussion categories'] = 'Сортировать категоріи';
$Definition['Organize your Categories'] = 'Сортировка вашихъ категорій';
$Definition['Original'] = 'Оригиналъ';
$Definition['Or you can...'] = 'Или...';
$Definition['Other Records'] = 'Другіе записи';

$Definition['Page'] = 'Страница';
$Definition['page'] = 'страница';
$Definition['Page %1$s of %2$s'] = 'Страница %1$s из %2$s';
$Definition['Page %s'] = 'Страница %s';
$Definition['PageDetailsMessage'] = '%1$s для %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s для %2$s изъ %3$s';
$Definition['Page Not Found'] = 'Страница не найдена';
$Definition['Participated Discussions'] = 'Участныя обсужденія';
$Definition['ParticipatedHomepageTitle'] = 'Участныя обсужденія';
$Definition['Password'] = 'Пароль';
$Definition['Password Contains Username'] = 'Содержит имя пользователя';
$Definition['Password Good'] = 'Хороший';
$Definition['Password Ok'] = 'Ок';
$Definition['PasswordRequest'] = 'Hallo %1$s,



Кто-то проситъ сбросить %2$s пароль. Если это были вы, пройдите по ссылкѣ ниже:

%3$s



Въ противномъ случаѣ, просто проигнорируйте это письмо



Всего хорошаго!';
$Definition['Passwords don\'t match'] = 'Пароль не подходитъ';
$Definition['Password Strong'] = 'Сильный';
$Definition['Password Too Short'] = 'Слишком короткий';
$Definition['Password Very Weak'] = 'Очень слабый';
$Definition['Password Weak'] = 'Слабый';
$Definition['Pending'] = 'Въ ожиданіи';
$Definition['Permalink'] = '#';
$Definition['permalink'] = 'ссылка';
$Definition['Permanent (301)'] = 'Перемѣщено (301)';
$Definition['PermissionErrorMessage'] = 'У васъ недостаточно правъ для просмотра этой страницы.';
$Definition['PermissionErrorTitle'] = 'Ошибка доступа';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'You need to be a moderator to do that.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'You need to be an administrator to do that.';
$Definition['PermissionRequired.Javascript'] = 'You need to enable javascript to do that.';
$Definition['Photogenic'] = 'Фотогеничный';
$Definition['Picture'] = 'Изображеніе';
$Definition['Play the sound again'] = 'Проиграть звук снова';
$Definition['Please join my group.'] = 'Пожалуйста, присоединяйтесь к моей <a href="{Url,html}">группе</a>.
';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Пожалуйста, подождите пока вы будете перенаправленны. Если въ теченіи 10 секунъ ничего не произошло, щелкните <a href="%s">тутъ</a>.';
$Definition['Poll'] = 'Голосованіе';
$Definition['poll'] = 'Голосованіе';
$Definition['Poll Options'] = 'Опціи опроса';
$Definition['Poll Question'] = 'Проголосовать вопросъ';
$Definition['Polls'] = 'Вопросы';
$Definition['polls'] = 'Вопросы';
$Definition['Popular'] = 'Популярныя';
$Definition['Popular Discussions'] = 'Популярныя темы';
$Definition['Popular Tags'] = 'Популярныя тэги';
$Definition['Popup'] = 'Всплывающее окно';
$Definition['Position'] = 'Позиція';
$Definition['Post'] = 'Сообщить';
$Definition['post'] = 'публикация';
$Definition['Post Comment'] = 'Отправить';
$Definition['Post Discussion'] = 'Опубликовать дискуссию';
$Definition['Post edited by %1$s at %2$s'] = 'Постъ отредактированъ %1$s въ %2$s';
$Definition['Posts'] = 'Сообщенія';
$Definition['Posts.Plural: %s'] = 'Сообщеній: %s';
$Definition['Posts.Singular: %s'] = 'Сообщеній: %s';
$Definition['Posts: %s'] = 'Сообщеній: %s';
$Definition['Post this anonymously'] = 'Сообщить это анонимно';
$Definition['Powered by %s'] = 'Работаетъ на %s';
$Definition['Powered by Vanilla'] = 'Движокъ «Vanilla»';
$Definition['PreferenceBadgeEmail'] = 'Сообщить мнѣ когда я получу значекъ.';
$Definition['PreferenceBadgePopup'] = 'Сообщить мнѣ когда я получу значекъ.';
$Definition['Preferences'] = 'Настройки';
$Definition['Preview'] = 'Просмотръ';
$Definition['Previous'] = 'Предыдущій';
$Definition['Privacy Settings'] = 'Настройки приватности';
$Definition['Private group.'] = 'Anyone can see the group, but only members can see its content. People must apply or be invited to join.';
$Definition['Private Note for Moderators'] = 'Скрытая замѣтка для модератора';
$Definition['Problem with credentials.'] = 'Проблема съ учетными данными.';
$Definition['Proceed'] = 'Продолжить';
$Definition['Profile'] = 'Профиль';
$Definition['Profile Fields'] = 'Поля профиля';
$Definition['Profile  Fields'] = 'Поля профиля';
$Definition['ProfileFieldsCustomDescription'] = 'Use these fields to create custom profile information. You can enter things like "Relationship Status", "Skype", or "Favorite Dinosaur". Be creative!';
$Definition['Profile Page'] = 'Страница профиля';
$Definition['Profile Picture'] = 'Личная картинка';
$Definition['Profiles'] = 'Профили';
$Definition['Progress on an idea you voted on!'] = 'У идеи, за которую вы голосовали, есть прогресс!';
$Definition['Promote'] = 'Рекламировать';
$Definition['Public'] = 'Публичный';
$Definition['Public group.'] = 'Anyone can see the group and its content. Anyone can join.';

$Definition['Q&A'] = 'Биографія';
$Definition['Q&A Accepted'] = 'отвѣчено ✓';
$Definition['Q&A Answered'] = 'отвѣчено';
$Definition['Q&A Options'] = 'Настройки биографіи';
$Definition['Q&A Question'] = 'Вопросъ';
$Definition['QnA Accepted Answer'] = 'Ответ ✓';
$Definition['QnA Rejected Answer'] = 'отклоненный отвѣтъ';
$Definition['Question'] = 'Вопросъ';
$Definition['question'] = 'вопросъ';
$Definition['Question Title'] = 'Заголовокъ вопроса';
$Definition['Quote'] = 'Цитировать';
$Definition['Quote Folding'] = 'Свертываніе кавычекъ';
$Definition['Quote on'] = 'на';
$Definition['Quote Settings'] = 'Настройки цитатъ';
$Definition['Quote wrote'] = 'написали';

$Definition['Rank'] = 'Рейтингъ';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,was,were} произведены въ рангъ {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = 'Поздравляемъ васъ! Васъ произвели въ рангъ {Data.Name,plaintext}.';
$Definition['React'] = 'Отреагировать';
$Definition['Reactions'] = 'Отклики';
$Definition['Read the full story here'] = 'Прочтите полный текст здесь';
$Definition['Real Name'] = 'Настоящее имя';
$Definition['Reason'] = 'Причина';
$Definition['Reason (optional)'] = 'Причина (опціонально)';
$Definition['reCAPTCHA has not been set up by the site administrator in registration settings. This is required to register.'] = ' reCAPTCHA не была установлена в настройках регистрации администратором сайта. Это необходимо для регистрации.';
$Definition['Recent'] = 'Последнее';
$Definition['Recent Activity'] = 'Послѣдняя активность';
$Definition['Recent Admin Activity'] = 'Послѣдніе дѣйствія администратора';
$Definition['Recent Discussions'] = 'Послѣдніе темы';
$Definition['recently'] = 'недавно';
$Definition['Recent Moderator Activity'] = 'Послѣдніе дѣйствія модератора';
$Definition['Recent Tutorials'] = 'Новые уроки';
$Definition['Recipients'] = 'Получатели';
$Definition['RecipientUserID'] = 'ID получателя';
$Definition['Redirecting...'] = 'Перенаправленіе...';
$Definition['Refetch Page'] = 'Перезагрузить страницу';
$Definition['Register'] = 'Зарегистрироваться';
$Definition['Register IP'] = 'Зарегистрированный IP';
$Definition['Register with %s'] = 'Зарегистрироваться';
$Definition['Registration  Fields'] = 'Поля регистраціи';
$Definition['Registration URL'] = 'Ссылка для регистраціи';
$Definition['Reject'] = 'Отклонить';
$Definition['Reject this answer.'] = 'Этотъ отвѣтъ не подходитъ.';
$Definition['Remember me'] = 'Запомнить меня';
$Definition['Remember me on this computer'] = 'Запомнить на этомъ компьютерѣ';
$Definition['Remote Configuration'] = 'Удаленная настройка';
$Definition['Remove'] = 'Удалить';
$Definition['Remove %s'] = 'Удалить %s';
$Definition['Removed by'] = 'Удалено';
$Definition['Remove file'] = 'Удалить файл';
$Definition['Remove Icon'] = 'Удалить иконку';
$Definition['Remove My Picture'] = 'Удалить мое изображеніе';
$Definition['Remove Picture'] = 'Удалить изображеніе';
$Definition['Remove Warning'] = 'Удалить предупрежденіе';
$Definition['Rename Forum'] = 'Переименовать форумъ';
$Definition['Reopen'] = 'Открыть снова';
$Definition['Replies'] = 'Отвѣтовъ';
$Definition['Reply'] = 'Отвѣтить';
$Definition['ReplyOnly'] = 'You can reply to this email directly to follow up. Sent from {/,exurl}.';
$Definition['ReplyOrFollow'] = 'Reply to this email directly or follow the link below to check it out:';
$Definition['Reported by: '] = 'Объ этомъ сообщаетъ: ';
$Definition['Reported Posts'] = 'Сообщенныя сообщенія';
$Definition['Report Notes'] = 'Примѣчаніе';
$Definition['Report Reason'] = 'Причина';
$Definition['Request a new password'] = 'Выслать новый пароль.';
$Definition['Request a new password →'] = 'Запросить новый пароль →';
$Definition['Request another password reset.'] = 'Запросите ещё один сброс пароля.';
$Definition['Reset Password'] = 'Сбросить пароль';
$Definition['Reset Your Password'] = 'Сброс пароля';
$Definition['Restore'] = 'Возстановить';
$Definition['Return to %s'] = 'Назад к %s';
$Definition['reverse'] = 'возвратъ';
$Definition['Revoke'] = 'Аннулировать';
$Definition['Revoked badge.'] = 'Аннулировать знакъ';
$Definition['role'] = 'ID Группы';
$Definition['RoleID'] = 'ID Группы';
$Definition['Roles'] = 'Группы';
$Definition['roles'] = 'роли';
$Definition['RSS Feed'] = 'RSS-лента';
$Definition['RSVP'] = 'Ответить';

$Definition['Save'] = 'Сохранить';
$Definition['Save Comment'] = 'Сохранить исправленія';
$Definition['Saved'] = 'Сохранено.';
$Definition['Save Draft'] = 'Сохранить черновикъ';
$Definition['Save Poll'] = 'Сохранить опросъ';
$Definition['Save Preferences'] = 'Сохранить настройки';
$Definition['Save Thumbnail'] = 'Сохранить миниатюру';
$Definition['Save your password'] = 'Сохранить пароль';
$Definition['Search'] = 'Поискъ';
$Definition['SearchBoxPlaceHolder'] = 'Поискъ';
$Definition['Search for a tag.'] = 'Search for all or part of a tag.';
$Definition['Search group members'] = 'Поиск участников группы';
$Definition['Search results for \'%s\''] = 'Результаты поиска по \'%s\'';
$Definition['Second Anniversary'] = 'Двухлѣтіе';
$Definition['Sections'] = 'Раздѣлы';
$Definition['Security Check'] = 'Провѣрка безопасности';
$Definition['Select a category...'] = 'Выбрать категорию...';
$Definition['Select a community.'] = 'Выберите сообщество.';
$Definition['Select an image on your computer (2mb max)'] = 'Выберите изображеніе на вашемъ компьютерѣ (максимумъ 2Мбъ)';
$Definition['Send'] = 'Отправить';
$Definition['Send a New Message'] = 'Отправить новое сообщеніе';
$Definition['Send Message'] = 'Отправить сообщеніе';
$Definition['sep and'] = 'и';
$Definition['Set a New Warning Level'] = 'Установить новый уровень предупрежденій';
$Definition['Set A Password'] = 'Установить пропускъ';
$Definition['Setting'] = 'Настройка';
$Definition['Settings'] = 'Настройки';
$Definition['Seventh Anniversary'] = 'Седьмая годовщина';
$Definition['Severity'] = 'уровень';
$Definition['Share'] = 'Подѣлиться';
$Definition['Shared Accounts'] = 'Общія учетныя записи';
$Definition['she'] = 'она';
$Definition['Shown only on mobile'] = 'Показывать только на мобильныхъ устройствахъ';
$Definition['Show previous quotes'] = '&raquo; показать предыдущие ценовые предложения';
$Definition['Show unfollowed categories'] = 'Показать категоріи, на которыя не подписанъ';
$Definition['Sign-In URL'] = 'URL входа';
$Definition['Sign-Out URL'] = 'URL выхода';
$Definition['Signature'] = 'Подпись';
$Definition['Signature Code'] = 'Подпись';
$Definition['Signature hidden.'] = 'Подпись скрыта';
$Definition['Signature invalid.'] = 'Подпись недѣйствительна.';
$Definition['Signatures'] = 'Подписи';
$Definition['Signatures can be up to {maxLength} characters long.'] = 'Максимальное количество символов в подписи: {maxLength}.';
$Definition['Signature Settings'] = 'Настройки подписи';
$Definition['SignIn'] = 'Входъ';
$Definition['Sign In'] = 'Войти';
$Definition['SigningOut'] = 'Подождите. Вы сейчасъ выходите изъ системы.';
$Definition['Sign In Now'] = 'Войти сейчас';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Войдите</a> или <a href="{RegisterUrl,html}">Зарегистрируйтесь</a> чтобы оставлять комментаріи.';
$Definition['Sign in to vote!'] = 'Войдите, чтобы голосовать!';
$Definition['Sign In with %s'] = 'Войти черезъ %s';
$Definition['Sign In with Disqus'] = 'Войти черезъ Disqus';
$Definition['Sign In with Facebook'] = 'Войти черезъ Facebook';
$Definition['Sign In with Google'] = 'Войти съ помощью Google';
$Definition['Sign In with OpenID'] = 'Войти съ помощью OpenID';
$Definition['Sign In with Twitter'] = 'Войти съ помощью Twitter';
$Definition['Sign Out'] = 'Выйти';
$Definition['sign out'] = 'Выйти';
$Definition['Sign Up'] = 'Зарегистрироваться';
$Definition['Sink'] = 'Пауза';
$Definition['Sink this discussion'] = 'Опустить это обсужденіе.';
$Definition['Site'] = 'Сайт';
$Definition['Sitemap Settings'] = 'Настройки карты сайта';
$Definition['Sites'] = 'Сайты';
$Definition['Sixth Anniversary'] = 'Шестая годовщина';
$Definition['somebody'] = 'кто-то';
$Definition['Some Code'] = 'А сюда идетъ переводъ.';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Кто-то отвѣтилъ на вашъ вопросъ. Вы должны принять или отклонить отвѣтъ.';
$Definition['sorted by'] = 'отсортировано';
$Definition['Source:'] = 'Исходный:';
$Definition['Source Code'] = 'Code';
$Definition['Spam'] = 'Спамъ';
$Definition['Spam Queue'] = 'Спамъ въ очереди';
$Definition['Split'] = 'Раздѣлить';
$Definition['Split Comments'] = 'Раздѣлить комментаріи';
$Definition['Spoiler'] = 'Спойлеръ';
$Definition['Spoof User'] = 'Поддѣлать пользователя';
$Definition['Start'] = 'Стартъ';
$Definition['Start a Group'] = 'Создать группу';
$Definition['Start a New Conversation'] = 'Начать новый діалогъ';
$Definition['Start a New Discussion'] = 'Начать новую тему';
$Definition['Start Conversation'] = 'Начать обсужденіе';
$Definition['Started By'] = 'Началъ';
$Definition['Started by %1$s'] = 'Опубликовали %1$s';
$Definition['Start your First Discussion'] = 'Ваша первая тема';
$Definition['Status'] = 'Статусъ';
$Definition['status'] = 'статус';
$Definition['Status: %s'] = 'Статус: %s';
$Definition['Statuses'] = 'Статусы';
$Definition['statuses'] = 'статусы';
$Definition['Stop following'] = 'Отписаться';
$Definition['Strip images out of signatures'] = 'Удалять изображенія изъ подписей';
$Definition['Strip images out of signatures?'] = 'Удалить изображенія изъ подписей?';
$Definition['Subject'] = 'Тема';
$Definition['Suggested Value'] = 'Предлагаемое значеніе';

$Definition['Tagged'] = 'Тэги темы';
$Definition['Tagged with '] = 'Отмѣчено тэгами: ';
$Definition['Tagged with "%s"'] = 'Съ тегомъ "%s"';
$Definition['Tagging'] = 'Тэгированіе';
$Definition['TagHint'] = 'Start to type...';
$Definition['Tag Name'] = 'Имя тэга';
$Definition['Tags'] = 'Тэги';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Пользователи могутъ добавлять тэги и ключевыя слова для улучшенія навигаціи по связанымъ дискуссіямъ.';
$Definition['Take Action'] = 'Принять мѣры';
$Definition['Take Action:'] = 'Выберите дѣйствіе:';
$Definition['Target'] = 'Расположеніе';
$Definition['Tell the user why you\'re warning them'] = 'Скажите пользователю, почему вы его предупреждаете';
$Definition['Tell us why you want to join!'] = 'Разскажите, почему вы рѣшили присоединиться къ намъ!';
$Definition['Tenth Anniversary'] = 'Десятая годовщина';
$Definition['TermsOfService'] = 'Условія использованія';
$Definition['Terms of Service'] = 'Условія использованія';
$Definition['TermsOfServiceText'] = '<p>1. Модерація форума. На форумѣ отсутствуетъ предварительная фильтрація сообщеній. Все сообщенія пользователей прочитываются модераторомъ форума. Въ случаѣ нарушенія пользователемъ правилъ форума, пользователь получаетъ предупрежденіе или заносится въ банлистъ. Администрація форума не несетъ отвѣтственности за информацію, размещенную пользователями.<br>
2. Незнаніе правилъ. На форумѣ запрещена публикація информаціи, противорѣчащей даннымъ правиламъ. Незнаніе правилъ не освобождаетъ отъ отвѣтственности.
Въ частности, запрещена публикація информаціи, которая:
а) завѣдомо является ложью и/или клеветой;
бъ) неточна, оскорбительна, вульгарна, внушаетъ ненависть, содержитъ угрозы, непристойности, грубость;
въ) сексуально оріентирована, вторгается въ личную жизнь другихъ людей;
гъ) нарушаетъ законы.
Движокъ форума записываетъ все IP-адреса, и Администрація форума сохраняетъ за собой право раскрывать ихъ въ случаѣ жалобъ или юридическихъ дѣйствій, ставшихъ слѣдствіемъ публикаціи сообщенія на этомъ сайтѣ. Также Администрація имѣетъ право удалить любую информацію на этомъ сайтѣ и отмѣнить регистрацію любого пользователя безъ объясненія причинъ. Чтобы пользоваться форумомъ, вамъ должно быть хотя бы 13 лѣтъ.<br>
3. Публикація информаціи третьими лицами. Отвѣтственность за информацію, размещенную отъ лица пользователя, несетъ только самъ пользователь. Администрація рекомендуетъ не допускать использованія вашихъ учетныхъ данныхъ третьими лицами.<br>
4. Аватара. Въ качествѣ аватары разрѣшается использовать любое изображеніе, не содержащее кровавыхъ сценъ, сценъ насилія, порнографіи. Запрещается использовать аватары, уже используемые другими участниками форума.<br>
5. Реклама. На форумѣ запрещено заниматься рекламой, въ томъ числѣ размѣщать частныя объявленія.<br>
6. Новыя темы. Привѣтствуется созданіе интересныхъ темъ.<br>
7. Сознательность. Поощряется своевременное оповѣщеніе Администраціи о нарушеніи правилъ форума.</p>';
$Definition['Thank You!'] = 'Благодаримъ Васъ!';
$Definition['The %s has been flagged for moderation.'] = '%s помечено для проверки модератором.';
$Definition['The connection data has not been verified.'] = 'Данные соединения не были проверены.';
$Definition['The conversation has been cleared.'] = 'Разговоръ былъ очищенъ.';
$Definition['The CSRF token is invalid.'] = 'CSRF токен некорректен.';
$Definition['The email you entered is in use by another member.'] = 'Этот адрес электронной почты используется другим участником.';
$Definition['The email you have entered is already related to an existing account.'] = 'Этотъ Email уже привязанъ къ существующему акаунту.';
$Definition['The file failed to upload.'] = 'Невозможно загрузить файлъ.';
$Definition['their'] = 'ихъ';
$Definition['The name you entered is already in use by another member.'] = 'Этотъ никъ уже занятъ, придумайте другой';
$Definition['The page you were looking for could not be found.'] = 'Страница, которую вы ищете, не существуетъ.';
$Definition['The quote had to be converted from %s to %s.'] = 'The quote had to be converted from %s to %s. Some formatting may have been lost.';
$Definition['There\'s already a %s with the name %s.'] = 'There\'s already a %1$s with the name %2$s.';
$Definition['There are no tags in the system yet.'] = 'Въ системѣ еще нѣтъ ни одного тэга.';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'Кодъ провѣрки введенъ не вѣрно. Если вамъ не понятны символы на картинкѣ, нажмите пиктограмму "двѣ стрѣлки по кругу", чтобы загрузить другіе';
$Definition['The reCAPTCHA was not completed correctly. Please try again.'] = ' reCAPTCHA была выполнена некорректно. Пожалуйста, попробуйте еще раз.';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Уже существуетъ учетная запись съ такимъ же именемъ пользователя (%1$s) или такой же почтой (%2$s). Вы можете создать новую учетную запись или ввести учетныя данныя уже существующей учетной записи на форумѣ.';
$Definition['The response was not in the correct format.'] = 'Отвѣтъ былъ въ неправильномъ форматѣ.';
$Definition['There was an error connecting to Disqus'] = 'Произошла ошибка при подключеніи къ Disqus';
$Definition['There was an error connecting to Facebook'] = 'Произошла ошибка при подключеніи къ Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Произошла ошибка при загрузкѣ файла. Скорѣе всего файлъ слишкомъ большой.';
$Definition['These tags are reserved and cannot be used: %s'] = 'Эти метки заняты и не могут быть использованы: %s';
$Definition['The site is currently undergoing maintenance.'] = 'Сайтъ въ настоящее время проходитъ техническое обслуживаніе.';
$Definition['The status for "%s" has changed to %s.'] = 'Статус "%s" сменился на %s.';
$Definition['The uploaded file was too big (max %s).'] = 'Загруженный файлъ былъ слишкомъ большой (максимумъ %s).';
$Definition['The user has already been warned for this %s.'] = 'Пользователь уже предупрежден об этом %s.';
$Definition['The user isn\'t banned.'] = 'Пользователь не забанен или забанен посредством другой функции.';
$Definition['they'] = 'они';
$Definition['Third Anniversary'] = 'Трехлѣтіе';
$Definition['This answer was %s.'] = 'Сей отвѣтъ былъ %s';
$Definition['This answer was Accepted.'] = 'Сей отвѣтъ подошелъ.';
$Definition['This discussion has been closed.'] = 'Сія тема была закрыта.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Сіе обсужденіе было связанно съ неосознаннымъ внѣшнимъ источникомъ.';
$Definition['This discussion was created from comments split from: %s.'] = 'Сія дискуссія была создана изъ комментаріевъ, выдѣленныхъ изъ: %s.';
$Definition['This discussion was merged into %s'] = 'Сія тема была перемѣщена';
$Definition['This image has been inserted into the body of text.'] = 'Это изображение было вставлено в текст.';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Изображеніе было уменьшено. Нажмите для увеличенія.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Это приватный опросъ: никто не будетъ видѣть что вы голосовали.';
$Definition['This is a public poll: others will see what you voted for.'] = 'Это общественный опросъ: другіе будутъ видѣть что вы голосовали.';
$Definition['This is a system account and does not represent a real person.'] = 'Это техническій пользователь';
$Definition['This Month\'s Leaders'] = 'Ведущие текущаго мѣсяца';
$Definition['This question\'s answer has been accepted.'] = 'Отвѣтъ на этотъ вопросъ былъ принятъ.';
$Definition['This user has been verified as a non-spammer.'] = 'Этотъ пользователь не спамеръ';
$Definition['This user has not been verified as a non-spammer.'] = 'Пользователь не были провѣренъ на спамера.';
$Definition['This user has not commented yet.'] = 'Этотъ пользователь ничего не комментировалъ.';
$Definition['This user has not made any discussions yet.'] = 'Этотъ пользователь не создалъ ни одной темы.';
$Definition['This user is also banned for other reasons and may stay banned.'] = 'Этот пользователь также забанен по другой причине и может остаться забаненым.';
$Definition['This user is verified as a non-spammer'] = 'Этотъ пользователь не спамеръ';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Предупрежденіе истекло. Вы хотите его удалить?';
$Definition['This Week\'s Leaders'] = 'Лидеры текущей недѣли';
$Definition['Thumbnail'] = 'Миніатюра';
$Definition['Title'] = 'Названіе';
$Definition['To'] = 'Къ';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'Для того, чтобы послать другое письмо активаціи, кликните <a href="%s">здѣсь</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'Для использованія системы reCAPTCHA вы должны получить API ключъ на сайтѣ %s';
$Definition['Transport error: %s'] = 'Произошла ошибка при обработкѣ запроса <br /> серверъ вернулъ слѣдующее сообщеніе: %s';
$Definition['Troll'] = 'Вредитель';
$Definition['Try Again'] = 'Повторите';
$Definition['Turn ON'] = 'Включить';
$Definition['Twitter'] = 'Твиттеръ';
$Definition['Twitter Connect'] = 'Подключиться к Twitter';
$Definition['Twitter Settings'] = 'Настройки входа черезъ Twitter';
$Definition['Type'] = 'Типъ';
$Definition['Type the text:'] = 'Введите текст:';
$Definition['Type what you hear:'] = 'Введите, то что слышите:';

$Definition['Unannounce'] = 'Убрать объявленіе';
$Definition['Unanswered'] = 'Вопросы безъ отвѣта';
$Definition['Unanswered Questions'] = 'Вопросы безъ отвѣта';
$Definition['unavailable'] = 'недоступно';
$Definition['Unban User'] = 'Разбанить пользователя';
$Definition['Unbookmark'] = 'Убрать изъ закладокъ';
$Definition['Undefined discussion body.'] = 'Не указано тѣло обсужденія.';
$Definition['Undefined discussion subject.'] = 'Не указана тема обсужденія.';
$Definition['Undefined foreign content'] = 'Внѣшній контентъ не опредѣленъ';
$Definition['Undo Follow'] = 'Отписаться';
$Definition['Unfollow'] = 'Отписаться';
$Definition['Unhide'] = 'Показать';
$Definition['Unknown'] = 'Неизвѣстно';
$Definition['unknown'] = 'неизвѣстно';
$Definition['Unknown client: %s.'] = 'Неизвѣстный кліентъ: %s.';
$Definition['Unmute'] = 'Включить уведомления';
$Definition['Unpin'] = 'Снять отметку';
$Definition['Unread'] = 'Непрочитанно';
$Definition['Unread Discussions'] = 'Непрочитанныя обсужденія';
$Definition['Unsink'] = 'Открыть';
$Definition['Unspecified'] = 'Не указано';
$Definition['Update'] = 'Обновленіе';
$Definition['Updated badge'] = 'Обновленный значекъ';
$Definition['Upload'] = 'Загрузить';
$Definition['Uploading...'] = 'Загрузка...';
$Definition['Upload New Icon'] = 'Загрузить новую иконку';
$Definition['Upload New Picture'] = 'Загрузить новую фотографию';
$Definition['Url'] = 'URL';
$Definition['UrlCode'] = 'Кодъ ссылки';
$Definition['Use My Current Password'] = 'Использовать мой текущій пароль';
$Definition['User'] = 'Пользователь';
$Definition['User "%s" does not exist.'] = 'Пользователь "%s" не существуетъ.';
$Definition['Username'] = 'Имя';
$Definition['Username already exists.'] = 'Это имя пользователя уже существует';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Имя пользователя можетъ содержать только буквы, цифры и знакъ подчеркиванія.';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'Имена пользователей могутъ содержать только буквы, цифры и знаки подчеркиванія и должны быть въ діапазонѣ отъ 3 до 20 символовъ.';
$Definition['UsernameError'] = 'Имена пользователей могутъ содержать только буквы, цифры и знаки подчеркиванія и должны быть въ діапазонѣ отъ 3 до 20 символовъ.';
$Definition['Username or email'] = 'Имя пользователя или почта';
$Definition['User not found.'] = 'Sorry, no account could be found related to the email/username you entered.';
$Definition['Users'] = 'Пользователи';
$Definition['Users Count'] = 'Число пользователей';
$Definition['Use up to {maxImages,plural,%s image, %s images}.'] = 'Вы можете использовать до {maxImages,plural,%s изображения, %s изображений}.';

$Definition['ValidateBanned'] = '%s не доступно.';
$Definition['ValidateBoolean'] = '%s - неправильный отвѣтъ';
$Definition['ValidateConnection'] = 'При указанныхъ параметрахъ не можетъ быть установлено соедененіе съ базой данныхъ. База данныхъ отдаетъ слѣдующія ошибки: <code>%s</code>';
$Definition['ValidateDate'] = '%s - неправильная дата.';
$Definition['ValidateDecimal'] = '%s - невѣрная дробь.';
$Definition['ValidateEmail'] = '%s некорректный адресъ почты.';
$Definition['ValidateEnum'] = '%s неправильно.';
$Definition['ValidateFormat'] = 'Вам запрещается вводить сырой HTML.';
$Definition['ValidateInteger'] = '%s - не цѣлое число (цѣлое число).';
$Definition['ValidateIntegerArray'] = '%s must be a comma-delimited list of numbers.';
$Definition['ValidateLength'] = '%1$s съ %2$s символовъ слишкомъ много.';
$Definition['ValidateMatch'] = 'Поля "%s" не совпадаютъ.';
$Definition['ValidateMinimumAge'] = 'You are not old enough to join this community.';
$Definition['ValidateMinLength'] = '%1$s короче на %2$s символ(ов), чем нужно.';
$Definition['ValidateMinLengthPlural'] = '%1$s короче на %2$s символов, чем нужно.';
$Definition['ValidateMinLengthSingular'] = '%1$s на %2$s символ короче, чем нужно';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Вы должны выбрать хотя бы одинъ %s';
$Definition['ValidateRegex'] = '%s не является корректнымъ.';
$Definition['ValidateRequired'] = 'Вы не заполнили поле %s.';
$Definition['ValidateRequiredArray'] = 'Вы должны выбрать хотя бы одинъ %s.';
$Definition['ValidateStrength'] = 'Введенный %s слишком легкий. Попробуйте использовать более сложный пароль и используйте индикатор сложности при его подборе.';
$Definition['ValidateString'] = '%s не является допустимой строкой.';
$Definition['ValidateTag'] = 'Тэги не могутъ содержать пробѣлы.';
$Definition['ValidateTime'] = '%s - невѣрное время.';
$Definition['ValidateTimestamp'] = '%s - неправильная мѣтка времени.';
$Definition['ValidateUrl'] = 'Поле %s не является валидным URL.';
$Definition['ValidateUrlStringRelaxed'] = '%s не могутъ содержать косыя черты, кавычки, или символы тэговъ.';
$Definition['ValidateUsername'] = 'Имя пользователя можетъ быть отъ 3 до 20 символовъ, и должно содержать только буквы латинскаго алфавита, цифры и символъ подчеркіанія.';
$Definition['ValidateVersion'] = '%s отображаетъ невѣрный номеръ версіи. Правильный номеръ смотри въ функціи version_compare() на php.';
$Definition['Value'] = 'Значеніе';
$Definition['Vanilla'] = 'Ванилла';
$Definition['Vanilla Statistics'] = 'Настройки статистики';
$Definition['Vanilla Statistics Plugin'] = 'Плагинъ статистики';
$Definition['Verified'] = 'Провѣренный';
$Definition['Verifying your credentials...'] = 'Провѣрка вашихъ учетныхъ данныхъ...';
$Definition['via %s'] = 'съ %s';
$Definition['Video embedding has been disabled.'] = 'Video embedding has been disabled. URLs will not translate to their embedded equivalent.';
$Definition['View'] = 'Просмотръ';
$Definition['View Badge'] = 'Посмотрѣть значекъ';
$Definition['Viewing'] = 'Просматриваемые -ыя';
$Definition['Views'] = 'Посѣщеній';
$Definition['Visible'] = 'Видимый';
$Definition['Visits'] = 'Посѣщеній';
$Definition['Visit Site'] = 'Перейти на сайтъ';
$Definition['Vote'] = 'Голосовать';
$Definition['Vote (action)'] = 'Голосовать';
$Definition['Vote Down'] = '↓';
$Definition['Votes'] = 'Оцѣнка';
$Definition['Vote Up'] = '↑';
$Definition['Voting for the idea is %s.'] = 'За идею проголосовало %s.';

$Definition['wall'] = 'Стѣна';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Хотите принять участіе въ этомъ обсужденіи? Нажмите одну изъ этихъ:';
$Definition['Warn'] = 'Предупрежденіе';
$Definition['Warn %s'] = 'Предупредить %s';
$Definition['Warned for'] = 'Предупреждены за';
$Definition['Warning'] = 'Вниманіе!';
$Definition['Warning Level %s'] = 'Уровень предупреждения: %s';
$Definition['Warnings'] = 'Предупрежденія';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} предупрежденъ {WarnUserID,User} за {Points,plural,%s points}.';
$Definition['WarningTitleFormat.Notice'] = '{InsertUserID,User} предупредилъ {WarnUserID,User} за {Points,plural,%s points} (just a notice).';
$Definition['was'] = 'было';
$Definition['We\'ve received a request to change your password.'] = 'Мы получили запрос на смену вашего пароля в %s. Если вы не делали этот запрос, пожалуйста, проигнорируйте это письмо.';
$Definition['Website'] = 'Вебсайтъ';
$Definition['weekday.letter.1'] = 'пн';
$Definition['weekday.letter.2'] = 'вт';
$Definition['weekday.letter.3'] = 'ср';
$Definition['weekday.letter.4'] = 'чт';
$Definition['weekday.letter.5'] = 'пт';
$Definition['weekday.letter.6'] = 'сб';
$Definition['weekday.letter.7'] = 'вс';
$Definition['weekday.long.1'] = 'понедельник';
$Definition['weekday.long.2'] = 'вторник';
$Definition['weekday.long.3'] = 'среда';
$Definition['weekday.long.4'] = 'четверг';
$Definition['weekday.long.5'] = 'пятница';
$Definition['weekday.long.6'] = 'суббота';
$Definition['weekday.long.7'] = 'воскресенье';
$Definition['weekday.short.1'] = 'пн';
$Definition['weekday.short.2'] = 'вт';
$Definition['weekday.short.3'] = 'ср';
$Definition['weekday.short.4'] = 'чт';
$Definition['weekday.short.5'] = 'пт';
$Definition['weekday.short.6'] = 'сб';
$Definition['weekday.short.7'] = 'вс';
$Definition['weeks'] = 'недѣли';
$Definition['Welcome Aboard!'] = 'Добро пожаловать къ намъ!';
$Definition['were'] = 'гдѣ';
$Definition['Where do you want to announce this discussion?'] = 'Гдѣ вы хотите объявить эту дискуссію?';
$Definition['Who\'s Online'] = 'Кто сейчасъ на сайтѣ?';
$Definition['Who\'s Online in this Category'] = 'Кто в этом разделе сейчас онлайн';
$Definition['Who\'s Online in this Discussion'] = 'Кто в этой дискуссии сейчас онлайн';
$Definition['Whoops!'] = 'Ой!';
$Definition['Why are you Banning this user?'] = 'Почему вы баните этого пользователя?';
$Definition['Why do you want to join?'] = 'Почему вы хотите зарегистрироваться?';
$Definition['Write a comment'] = 'Написать комментарій';
$Definition['Write Comment'] = 'Комментировать';
$Definition['Write something about yourself...'] = 'Написать что-нибудь о себѣ...';
$Definition['WTF'] = 'Шозанахъ';

$Definition['Yes'] = 'Да';
$Definition['You'] = 'вы';
$Definition['you'] = 'вы';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">You\'ve asked questions that now have answers</a>. Make sure you accept/reject the answers.';
$Definition['You\'ve been Jailed.'] = 'Вы были заключены подъ стражу.';
$Definition['You\'ve been warned.'] = 'Вы предупреждены.';
$Definition['You already have an account here.'] = 'У васъ здѣсь уже есть учетную запись';
$Definition['You are about to ban {User.UserID,user}.'] = 'Вы собираетесь забанить {User.UserID,user}.';
$Definition['You are about to unban {User.UserID,user}.'] = 'Вы собираетесь разбанить {User.UserID,user}.';
$Definition['You are connected as %s through %s.'] = 'Вы подключитесь %s черезъ %s.';
$Definition['You are connected through %2$s.'] = 'Вы подключены черезъ %2$s.';
$Definition['You are currently only viewing categories that you follow.'] = 'Вы просматриваете только тѣ категоріи, на которыя подписаны.';
$Definition['You are currently viewing all categories.'] = 'Вы просматриваете все категоріи';
$Definition['You are editing %s\'s signature'] = 'Вы отредактировали подпись %s';
$Definition['You are jailed.'] = 'Вы в тюрьме.';
$Definition['You are now leaving %1$s. Click the link to continue to %2$s.'] = 'Вы покидаете %1$s. Нажмите на ссылку, чтобы перейти к %2$sю';
$Definition['You are now signed in.'] = 'Теперь вы вошли';
$Definition['You are only allowed {maxImages,plural,%s image,%s images}.'] = 'Вам разрешается только {maxImages,plural,%s изображение,%s изображений}.';
$Definition['You can either ask a question or start a discussion.'] = 'Вы можете задать вопросъ или начать новую тему. Выберите, что вы хотите сдѣлать.';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Вы можете слѣдить за отдѣльными категоріями и получать увѣдомленія о всѣхъ сообщеніяхъ въ нихъ.';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Вы не можете редактировать изображеніе въ профилѣ';
$Definition['You can only specify up to %s tags.'] = 'Вы можете указать до %s мѣтокъ.';
$Definition['You can remove or ban this member from the group.'] = 'You can remove or ban this member from the group. Banned members won\'t be able to join the group again.';
$Definition['You can use HTML in your signature.'] = 'Вы можете применять <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">простой HTML</a></b> в вашей подписи.';
$Definition['You don\'t have permission to do that.'] = 'У васъ недостаточно правъ для просмотра этой страницы.';
$Definition['You don\'t have permission to use a signature.'] = 'У вас нет прав на добавление подписей';
$Definition['You do not have any %s yet.'] = 'У васъ еще нѣтъ %s.';
$Definition['You do not have any bookmarks.'] = 'У васъ нѣтъ ни одной закладки.';
$Definition['You do not have any conversations.'] = 'Вы необщительны.';
$Definition['You do not have any drafts.'] = 'У васъ нѣтъ ни одного черновика.';
$Definition['You do not have any notifications yet.'] = 'У васъ нѣтъ сообщеній.';
$Definition['You do not have enough invitations left.'] = 'У васъ не хватаетъ приглашеній.';
$Definition['You do not have permission to edit all of the posts you are trying to merge.'] = 'У вас недостаточно прав, чтобы редактировать публикации, которые вы пытаетесь объединить.';
$Definition['You do not have permission to write new comments.'] = 'Вы не имѣете права комментировать.';
$Definition['YouEarnedBadge'] = 'You earned this badge';
$Definition['You have answered questions'] = 'У Васъ есть вопросы <a href="{/discussions/mine?qna=Answered,url}">съ отвѣтами</a>. Одобрите или отклоните ихъ.';
$Definition['You have been approved for membership.'] = 'Ваша заявка в группу была одобрена.';
$Definition['You have entered an invalid discussion title'] = 'Вы ввели невѣрный заголовокъ обсужденія';
$Definition['You haven\'t joined any groups yet.'] = 'Вы еще не присоединились ни к одной группе.';
$Definition['You haven\'t read this yet.'] = 'Вы еще не читали это.';
$Definition['You have not started any discussions.'] = 'Вы еще не начали какихъ-либо обсужденій.';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Вы написали %1$s сообщеній за %2$s секундъ. Въ цѣляхъ борьбы со спамомъ вы заблокированы на %3$s секундъ, по прошествіи которыхъ вы снова сможете публиковать сообщенія.';
$Definition['You have selected %1$s.'] = 'Вы выбрали %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Вы выбрали %1$s въ этой темѣ';
$Definition['You have successfully connected to {Title}.'] = 'Вы успешно подключились к {Title}.';
$Definition['You have successfully registered for an account at {Title}.'] = 'Вы успешно зарегистрировали аккаунт в {Title}.';
$Definition['You have to select at least 2 discussions to merge.'] = 'Вы должны выбрать по крайней мѣрѣ два обсужденія для сліянія.';
$Definition['You must agree to the terms of service.'] = 'Вы должны подтвердить правила использованія форума.';
$Definition['You must be at least %d years old to register.'] = 'Для регистрации вам должно быть как минимум %d лет.';
$Definition['You must be signed in.'] = 'Вы должны авторизоваться.';
$Definition['You must confirm you have received consent to register.'] = 'Вы должны подтвердить получение вами разрешения на регистрацию.';
$Definition['You need to confirm your email address.'] = 'Вамъ нужно подтвердить email адресъ. Для того, чтобы повторно послать письмо активаціи, нажмите <a href="/entry/emailconfirmrequest">здѣсь</a>.';
$Definition['You need to confirm your email address before you can continue.'] = 'Вам нужно подтвердить свой адрес эл. почты перед тем, как продолжить.';
$Definition['You need to sign in before you can do this.'] = 'Вы должны войти въ систему прежде, чѣмъ вы можете это сдѣлать.';
$Definition['your'] = 'ваше';
$Definition['Your application for this group was denied.'] = 'Ваша заявка на вступление в эту группу была отклонена.';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Спасибо. Ваша заявка будетъ разсмотрѣна администраторомъ. Вы будете увѣдомлены по электронной почтѣ, если ваша заявка будетъ одобрена.';
$Definition['Your changes have been saved.'] = 'Ваши измѣненія сохранены.';
$Definition['Your changes have been saved successfully.'] = 'Ваши измѣненія были успѣшно сохранены.';
$Definition['Your changes were saved.'] = 'Ваши измѣненія сохранены.';
$Definition['Your changes were saved successfully.'] = 'Ваши измѣненія были успѣшно сохранены.';
$Definition['Your complaint has been registered.'] = 'Ваше обращение зарегистрировано';
$Definition['Your email doesn\'t need confirmation.'] = 'Ваш адрес почты не нуждается в подтверждении';
$Definition['Your email has been successfully confirmed.'] = 'Вашъ email былъ успѣшно подтвержденъ.';
$Definition['Your invitation has been sent.'] = 'Ваше приглашеніе было отправлено.';
$Definition['Your old password was incorrect.'] = 'Невѣрно введенъ старый пароль';
$Definition['Your password has been changed.'] = 'Вашъ пароль былъ измѣненъ.';
$Definition['Your password must be at least %d characters long.'] = 'Количество символов в вашем пароле должно быть не менее %d.';
$Definition['Your password reset token has expired.'] = 'Ваш маркер сброса пароля устарел. Попробуйте использовать форму сброса пароля снова.';
$Definition['Your picture has been removed.'] = 'Ваша фотографія была удалена.';
$Definition['Your post will appear once it\'s been approved.'] = 'Ваше сообщеніе появится послѣ модераціи.';
$Definition['Your preferences have been saved.'] = 'Ваши настройки были сохранены.';
$Definition['Your private conversations with other members.'] = 'Ваши приватные разговоры съ другими членами.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Ваше имя при регистраціи: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'Ссылка для подтвержденія выслана вамъ на почту, пожалуйста провѣрьте.';
$Definition['Your settings have been saved.'] = 'Ваши настройки были сохранены.';
$Definition['Your settings have been saved successfully.'] = 'Ваши настройки были успѣшно сохранены.';
$Definition['Your warning was added.'] = 'Ваше предупрежденіе было добавлено.';
$Definition['You were added to a conversation.'] = '{InsertUserID,user} добавилъ {NotifyUserID,you} къ <a href="{Url,htmlencode}">бесѣдѣ</a>.';
