<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '** Rabhadh: Ma chuireas tu am feart seo an sàs dh’ fhaodadh e mearachdan Javascript adhbhrachadh air an làrach agad.**';

$Definition['About.DisableStatistics'] = 'If you must disable this data reporting for some business reason, you can do so by adding the following line to your installation\'s configuration file: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'It is vitally important to the life of this free, open-source software that we accurately measure the reach and effectiveness of Vanilla. We ask that you please do not disable the reporting of this data.';
$Definition['AboutCommentEmbedding'] = 'Vanilla can be used as a drop-in replacement for your blog\'s native commenting system. As a matter of fact, it can be used to add comments to any page on the web.';
$Definition['AboutEmbedding'] = 'Embedding allows all or part of your community to be embedded into other applications & web pages.';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Faigh chun fhòram coimhearsnachd agad le bhith a ’briogadh air a’ cheangal “Làrach Tadhail” aig mullach na duilleige seo, no le <a href={/,url}>bhith a ’ cliogadh an seo</a> . Is e am fòram coimhearsnachd na chì an luchd-cleachdaidh agus an luchd-ceannach agad nuair a thadhlas iad air <a href="{/,url,domain}">{/, url, domain}</a> .';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Cuir crìochan ri tomhasan luchdachadh suas ìomhaighean ann an còmhraidhean agus beachdan.';
$Definition['AddonProblems'] = '<h2>Problems?</h2><p>If something goes wrong with an addon and you can\'t use your site, you can disable them manually by editing:</p>%s';
$Definition['AddressBarColorDescription'] = 'Bidh cuid de bhrobhsairean a ’toirt taic do dhath airson a’ bhàr seòlaidh. Fòn-làimhe a-mhàin.';
$Definition['Alert users if they click external link.'] = 'Cuir fios gu luchd-cleachdaidh ma bhriogas iad air ceangal ann am post a bheir air falbh iad bhon fhòram. Cha tèid rabhadh a thoirt do luchd-cleachdaidh nuair a bhios iad a ’leantainn cheanglaichean a tha a’ freagairt ri Fearann earbsach';
$Definition['Alignment'] = 'Co-thaobhadh';
$Definition['Alignment (Mobile)'] = 'Co-thaobhadh (gluasadach)';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Leig le luchd-cleachdaidh le cead %s na avatars aca fhèin atharrachadh bho na duilleagan pròifil aca ann am Vanilla.';
$Definition['Anonymize IP Addresses'] = 'Cuir seòlaidhean IP gun urra';
$Definition['ApplicationHelp'] = 'Applications allow you to add large groups of functionality to your site.<br />Once an application has been added to your %s folder, you can enable or disable it here.';
$Definition['Apply Layout'] = 'Cuir a-steach cruth';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'A bheil thu cinnteach gu bheil thu airson an cuspair seo a dhubhadh às? Thèid a dhubhadh às gu maireannach.';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'Feumar dreuchd le seòrsa bunaiteach "neo-dhearbhaichte" gus dearbhadh post-d a chleachdadh.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Sàbhail gu fèin-ghluasadach dreachan de chòmhraidhean, cheistean, bheachdan agus bheachdan neo-fhoillsichte.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Thèid avatars a lùghdachadh ma thèid iad thairis air an àirde seo.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Thèid avatars a lùghdachadh ma thèid iad thairis air an leud seo.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Thèid òrdagan a shàbhaladh aig avatars aig a ’mheud seo.';

$Definition['Background'] = 'Cùl-fhiosrachadh';
$Definition['Background Image'] = 'Ìomhaigh cùl-fhiosrachaidh';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Bi cruthachail! Feuch ri do rangannan ainmeachadh às deidh rudan air a bheil a ’choimhearsnachd a’ bruidhinn.';
$Definition['Bordered'] = 'Crìochan';
$Definition['Bordered (Unified)'] = 'Bordered (Aonaichte)';
$Definition['Borderless'] = 'Gun chrìochan';
$Definition['Border Radius'] = 'Radius nan Crìochan';
$Definition['Brand Color'] = 'Dath Brand';
$Definition['Buttons'] = 'Putanan';
$Definition['Buttons & Inputs'] = 'Putanan & Toraidhean';
$Definition['Button Type'] = 'Seòrsa Putan';

$Definition['Center Aligned'] = 'Ionad air a cho-thaobhadh';
$Definition['Changes to the set day will take affect the following week.'] = 'Bheir atharrachaidhean air an latha shuidhichte buaidh air an ath sheachdain.';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Bidh atharrachaidhean a ’buntainn ri avatars a tha air ùr luchdachadh suas a-mhàin.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Atharraich na meudan gu bheil ìomhaighean avatar air an sàbhaladh aig.';
$Definition['Change the way your community works with plugins.'] = 'Change the way your community works with plugins. We\'ve bundled popular plugins with the software, and there are more available online.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Bidh bogsaichean-seicidh a ’leigeil le admins gnìomhan baidse a dhèanamh air grunn chòmhraidhean no bheachdan aig an aon àm.';
$Definition['Check out our %s'] = 'Thoir sùil air an %s againn';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Thoir sùil air an <0> sgrìobhainn againn</0> , no faighnich don <1> choimhearsnachd eòlaichean againn</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla is the simplest, most powerful community platform in the world. It\'s super-duper easy to use. Start with this introductory video and continue with the steps below. Enjoy!';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Tagh cuspair airson an fho-choimhearsnachd seo. <0> Leugh tuilleadh </0>';
$Definition['Choose Image'] = 'Tagh Ìomhaigh';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'You can select a custom hash algorithm to sign your requests. The hash algorithm must also be used in your client library. Choose md5 if you\'re not sure what to choose.';
$Definition['Choose the order items are sorted.'] = 'Tagh na nithean òrdugh air an rèiteachadh.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Tagh an duilleag a bu chòir dha daoine fhaicinn nuair a thadhlas iad air <0 />';
$Definition['Choose the preferred layout for lists of categories.'] = 'Tagh an cruth as fheàrr leat airson liostaichean de roinnean.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Tagh an cruth as fheàrr leat airson liostaichean de roinnean. Faodaidh tu an Tiled Layout a dheasachadh.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Tagh an cruth as fheàrr leat airson liostaichean de chòmhraidhean.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Tagh an cruth as fheàrr leat airson liostaichean de chòmhraidhean. Faodaidh tu an Bun-stèidh a dheasachadh.';
$Definition['Color Overlay'] = 'Ath-chòmhdach dath';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Is e Cuspairean Custom na cuspairean a chruthaich thu. Faodaidh tu deasachadh, ath-ainmeachadh no leth-bhreac dhiubh a dhèanamh.';

$Definition['Dark'] = 'Dorcha';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Define who can upload and manage files on the <a href="%s">Roles & Permissions</a> page.';
$Definition['Deleting forever cannot be undone.'] = 'Deleting is a good way to keep your forum clean.';
$Definition['Digest Settings'] = 'Roghainnean geàrr-chunntas';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Cuir à comas an obair-lann “New Embed System” air an <0>Duilleag Vanilla Labs</0>';

$Definition['EditContentTimeout.Notes'] = 'If a user is in a role that has permission to edit content, those permissions will override this.';
$Definition['Edits to this theme apply to:'] = 'Tha deasachaidhean air a ’chuspair seo a’ buntainn ri:';
$Definition['Email digests will be sent on the selected day every week.'] = 'Thèid geàrr-chunntasan post-d a chuir air an latha taghte gach seachdain.';
$Definition['Email sent from the application will be addressed from this email address'] = 'Thèid post-d a chuirear bhon tagradh a sheòladh bhon t-seòladh post-d seo';
$Definition['Email sent from the application will be addressed from this name'] = 'Thèid post-d a chuirear bhon tagradh a sheòladh bhon ainm seo';
$Definition['Email Settings'] = 'Roghainnean post-d';
$Definition['Embed Settings'] = 'Cuir a-steach Settings';
$Definition['Enable and test out the latest Vanilla features.'] = 'Dèan comas agus deuchainn air na feartan Vanilla as ùire.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'A ’comasachadh deasachadh adhartach de phuist ann an grunn chruthan, nam measg WYSIWYG, HTML sìmplidh, Markdown, agus BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Dèan comas don neach-deasachaidh cruth cruth gnàthaichte a chuir an sàs airson na duilleagan coimhearsnachd agad. Cleachd an deasaiche ùr againn gus susbaint a nochdadh a’ cleachdadh ar catalog de widgets a tha rim faighinn.';
$Definition['Enter a descriptive name.'] = 'Enter a descriptive name for the pocket. This name will not show up anywhere except when managing your pockets here so it is only used to help you remember the pocket.';
$Definition['Enter a short name for the site.'] = 'Enter a short name for the site. This is displayed on the signin buttons.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Every edit or deletion is recorded here. Use ‘Restore’ to undo any change.';
$Definition['Everyone who signs up gets a profile page.'] = 'Bidh a h-uile duine a chlàraicheas airson do choimhearsnachd a ’faighinn duilleag ìomhaigh phoblach far an urrainn dhaibh dealbh dhiubh fhèin a luchdachadh suas, na roghainnean pròifil aca a riaghladh, agus sùil a chumail air rudan fionnar a tha a’ dol air adhart sa choimhearsnachd. Bu chòir dhut <a href="{/profile,url}">do phròifil a ghnàthachadh a-nis</a> .';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect allows users to sign in using their Facebook account. <b>You must register your application with Facebook for this plugin to work.</b>';
$Definition['Font'] = 'Cruth-clò';
$Definition['Font Name'] = 'Ainm Font';
$Definition['Font URL'] = 'URL clò';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Mar eisimpleir, faodaidh tu casg a chuir air a h-uile neach-cleachdaidh le seòlaidhean puist-d bho "example.com" le bhith a ’cur casg seòrsa post-d leis an luach" *@example.com ".';
$Definition['Foundation Layout'] = 'Cruth Bunait';
$Definition['Full Anonymization'] = 'Anonymization slàn';
$Definition['FullAnonymization.Description'] = 'Bidh <strong>Full Anonymization</strong> a’ dol an àite a h-uile seòladh IP le 0.0.0.0 gu h-èifeachdach a’ diùltadh cothrom don tagradh obair le seòlaidhean IP. Chan obraich riaghailtean casg IP idir sa chùis seo.';
$Definition['Full Bleed'] = 'Bleed Làn';

$Definition['Garden.Import.Complete.Description'] = 'You have successfully completed an import.
   Click <b>Finished</b> when you are ready.';
$Definition['Garden.Import.Continue.Description'] = 'Tha e coltach gu bheil thu ann am meadhan in-mhalairt. Tagh aon de na roghainnean a leanas.';
$Definition['Garden.Import.InputInstructions'] = 'Enter the email and password of the admin user from the data being imported.';
$Definition['Garden.Privacy.IPs.Description'] = 'Mar as trice bidh seòlaidhean IP luchd-cleachdaidh air an cruinneachadh airson riaghailtean casg fèin-ghluasadach, measadh agus adhbharan casg spama. Le bhith a’ comasachadh IP Anonymization gun urra a h-uile seòladh IP a chaidh a leantainn air an làrach airson adhbhar sam bith, agus lughdaichidh e èifeachdas nan innealan sin. Chan eil atharrachaidhean air an t-suidheachadh seo ath-ghnìomhach.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit cead na avatars aca fhèin atharrachadh bho na duilleagan pròifil aca ann am Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'You have specifically disabled Vanilla Statistics in your configuration file.';
$Definition['Garden.StatisticsLocal.Explain'] = 'This forum appears to be running in a test environment, or is otherwise reporting a private IP. By default, forums running on private IPs are not tracked.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'If you\'re sure your forum is accessible from the internet you can force it to report statistics here:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'Your config.php file appears to be read-only. This means that Vanilla will be unable to automatically register your forum\'s InstallationID and InstallationSecret.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'To solve this problem, assign file mode 777 to your conf/config.php file.';
$Definition['Global Styles'] = 'Stoidhlichean Cruinne';

$Definition['Heads Up!'] = 'Cinn suas!';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Seo na h-ìrean as urrainn do luchd-cleachdaidh a choileanadh air an làrach agad. Faodaidh tu na h-ìrean sin a ghnàthachadh agus eadhon feadhainn ùra a chur ris. Seo beagan mholaidhean.';

$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Mura tadhail neach-cleachdaidh air an làrach taobh a-staigh na h-ùine seo thèid an soidhnigeadh a-mach gu fèin-ghluasadach.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Ma tha e air a chomasachadh, thèid susbaint iomlan nan dreuchdan a chuir ann am brathan post-d gu luchd-cleachdaidh.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Ma tha thu ùr do HTML agus / no CSS, seo cuid de chlasaichean-oideachaidh gus do thòiseachadh:';
$Definition['If you have an old theme'] = 'Ma tha seann chuspair agad agus gu feum thu cuspair deasg agus gluasadach air leth a shuidheachadh faodaidh tu sin a dhèanamh leis an t-seann UI cuspaireil.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Ma tha thu airson do fhòram a stèidheachadh no beachdan Vanilla a chleachdadh anns a ’bhlog agad feumaidh tu an toirt a-steach. Mura h-eil thu a ’cleachdadh greimeachadh tha sinn a’ moladh an suidheachadh seo fhàgail.';
$Definition['Image (Mobile)'] = 'Ìomhaigh (Fòn-làimhe)';
$Definition['In additon to the widgets there are also'] = 'A bharrachd air na widgets tha <0> Stoidhlichean Cruinne ann cuideachd </0> . Gus stoidhlichean cruinne a dheasachadh cliog àite sam bith eile air an duilleag, mar an teacsa seo.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Amalachadh duilleagan & co-phàirtean bunaiteach a-steach don chuspair agad';
$Definition['Internationalization & Localization'] = 'Eadar-nàiseantachd & Ionadail';
$Definition['Invalid URL'] = 'URL mì-dhligheach';
$Definition['Invitation email failed to send: %'] = 'Ged a chaidh an cuireadh a chruthachadh gu soirbheachail, cha do chuir am post-d fios. Thug an frithealaiche cunntas air a ’mhearachd a leanas: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'When you use registration by invitation users will have a link called <a href="%s" class="Popup">My Invitations</a> on their profile pages.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Is e deagh bheachd a th ’ann an àireamh as motha de charactaran a tha ceadaichte ann am post a chumail sìos gu meud reusanta.';

$Definition['Layout Editor'] = 'Deasaiche cruth-clò';
$Definition['Learn about custom routing.'] = 'Ionnsaich mu dheidhinn gnàthachadh àbhaisteach.';
$Definition['Left Aligned'] = 'Clì air a cho-thaobhadh';
$Definition['Light'] = 'Solas';
$Definition['Links'] = 'Ceanglaichean';
$Definition['Locales allow you to support other languages on your site.'] = 'Leigidh àiteachan-fuirich leat taic a thoirt do chànanan eile air an làrach agad. Dèan comas agus cuir à comas locales a tha thu airson a dhèanamh an seo.';
$Definition['Lockout Time (seconds)'] = 'Ùine glasaidh (diogan)';
$Definition['LogoDescription'] = 'Tha suaicheantas a ’bhratach a’ nochdadh aig mullach na làraich agad.';
$Definition['LogoDisclaimer'] = 'Cha bhith na cuspairean a chaidh a dhèanamh le deasaiche a ’chuspair agus cuid de chuspairean gnàthaichte a’ cleachdadh an t-suidheachaidh seo.';
$Definition['Looking for the Old Embed System?'] = 'A \'coimhead airson an Old Embed System?';

$Definition['Make sure you click View Page'] = 'Make sure you click <a href="%s">View Page</a> to see what your categories page looks like after saving.';
$Definition['Managing Users'] = 'A ’riaghladh luchd-cleachdaidh';
$Definition['Messages can appear anywhere in your application.'] = 'Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.';
$Definition['MobileLogoDescription'] = 'Bidh suaicheantas bratach gluasadach a ’nochdadh aig mullach na làraich agad.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Leigidh cuspairean gluasadach dhut sealladh is faireachdainn na làraich agad atharrachadh air innealan nas lugha.';
$Definition['Most communities stick to positive reactions to encourage participation.'] = 'Bidh a’ mhòr-chuid de choimhearsnachdan a’ cumail ri beachdan adhartach gus com-pàirteachadh a bhrosnachadh.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Sealbhaichidh an Deasaiche Cruth ùr an cuspair a chaidh a shuidheachadh san Stoidhle Stoidhle agad (deasaiche cuspair gu foirmeil). <1> Faigh a-mach tuilleadh</1>';
$Definition['Need more help?'] = 'A bheil feum agad air barrachd cuideachaidh?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Thèid roinnean neadachaidh nas doimhne na an doimhneachd seo a chur ann an liosta làn-choma.';
$Definition['New Embed System'] = 'Siostam leabachaidh ùr';
$Definition['New Quick Links'] = 'Ceanglaichean sgiobalta ùra';
$Definition['New Search Page'] = 'Duilleag sgrùdaidh ùr';
$Definition['No Anonymization'] = 'Gun Anonymization';
$Definition['Not getting what you expect when you preview your theme?'] = 'Gun a bhith a ’faighinn na tha thu a’ dùileachadh nuair a bheir thu ro-shealladh air a ’chuspair agad?';
$Definition['No unconfirmed role available for email confirmation.'] = 'Feumaidh an làrach dreuchd le seòrsa bunaiteach "neo-dhaingnichte" gus dearbhadh post-d a chleachdadh. Feuch an cuir thu fear ris gus an t-suidheachadh seo a chomasachadh.';

$Definition['Old Theming UI'] = 'UI seann chuspair';
$Definition['Once enabled, only members will see inside your community.'] = 'Aon uair ‘s gu bheil e air a chomasachadh, chan fhaic ach buill taobh a-staigh na coimhearsnachd agad.';
$Definition['OrgDescription'] = 'Tha ainm na buidhne agad air a chleachdadh airson SEO microdata agus JSON + LD';
$Definition['Outline'] = 'Dealbh a-muigh';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Faodaidh frith-bhuaidhean neo-àbhaisteach a bhith aig seallaidhean no cuspairean cuspaireil agus chan eilear gan ro-shealladh.';

$Definition['Partial Anonymization'] = 'Anonymization ann am pàirt';
$Definition['PartialAnonymization.Description'] = 'Chan eil <strong>Partal Anonymization</strong> gun urra ach an octet mu dheireadh den t-seòladh IP. Mar eisimpleir bhiodh 254.230.05.153 gu bhith na 254.230.05.0. Bheir seo beagan gun urra fhad ‘s a tha e fhathast a’ leigeil le riaghailtean casg IP a bhith ag obair.';
$Definition['Password.MinLength'] = 'Fad caractar as ìsle a tha ceadaichte airson faclan-faire luchd-cleachdaidh air duilleagan cruthaich agus ath-shuidheachadh faclan-faire.';
$Definition['PluginHelp'] = 'Plugins allow you to add functionality to your site.<br />Once a plugin has been added to your %s folder, you can enable or disable it here.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'The pocket is displayed between each discussion on the main discussion list. Since discussions are usually in <li>..</li> tags, you\'ll need to wrap your pocket in those tags too.';
$Definition['Preset'] = 'Ro-shuidhichte';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Prevent spam on your forum by limiting the number of discussions & comments that users can post within a given period of time.';
$Definition['Primary Button'] = 'Putan Bun-sgoile';
$Definition['Primary Buttons'] = 'Putanan Bun-sgoile';

$Definition['Quicklinks'] = 'Ceanglaichean luath';
$Definition['Quick Links is a default component on community pages.'] = 'Tha Quick Links na phàirt bunaiteach air duilleagan coimhearsnachd. Dèan comas air a ’phàirt ùr Ceanglaichean Luath againn gus ceanglaichean bhon chlàr seo a chur ris, a dheasachadh no a fhalach a’ cleachdadh an deasaiche cuspair againn.';

$Definition['Reactions Documentation'] = 'Sgrìobhainnean ath-bheachdan';
$Definition['Recommended dimensions are about 400px by 300px or smaller with similar ratio.'] = 'Tha na tomhasan a thathar a’ moladh timcheall air 400px le 300px no nas lugha le co-mheas coltach ris.';
$Definition['Recommend special ranks for admins and mods.'] = 'Is e deagh bheachd a th ’ann rangannan sònraichte a bhith agad airson luchd-riaghlaidh agus luchd-rianachd gus am faic do choimhearsnachd gu furasta cò a tha os cionn.';
$Definition['Recommend starting with five ranks.'] = 'Chan eil thu airson cus rangannan a bhith agad. Tha sinn a ’moladh tòiseachadh le còig. Faodaidh tu barrachd a chuir ris ma tha a ’choimhearsnachd agad gu math mòr.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Thoir air falbh ceanglaichean deasbaid is roinnean bho chlàran-bìdh. Suidhich duilleagan deasbaid is roinn-seòrsa airson a thilleadh cha deach duilleag 404 a lorg.';
$Definition['Requires “Flag” reaction permission.'] = 'Feumaidh cead freagairt “Bratach”.';
$Definition['Requires “Negative” reaction permission.'] = 'Feumaidh e cead freagairt “àicheil”.';
$Definition['Requires “Positive” reaction permission.'] = 'Feumaidh e cead freagairt “adhartach”.';
$Definition['Restoring your selection removes the items from this list.'] = 'When you restore, the items are removed from this list and put back into the site.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Cleachd an roghainn a leanas gus luachan a thoirt don Deasaiche Rich. Cha bhuin seo ach ma tha an cruth bunaiteach "Rich".';
$Definition['Routes are used to redirect users.'] = 'Bithear a ’cleachdadh slighean gus luchd-cleachdaidh ath-stiùireadh a rèir an URL a chaidh iarraidh.';

$Definition['Secondary Button'] = 'Putan Àrd-sgoile';
$Definition['Secondary Buttons'] = 'Putanan Àrd-sgoile';
$Definition['Security.Hsts.HTTPSWarning'] = 'Rabhadh: Na cuir an comas am feart seo ach ma tha thu cinnteach gu bheil na subdomains agad uile air an rèiteachadh airson HTTPS le teisteanasan dligheach.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Nuair a tha e air a chomasachadh, tha an riaghailt seo a ’buntainn ri fo-roinnean na làraich agad cuideachd.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Tha sinn a ’moladh tòiseachadh le aois as àirde de 1 seachdain agus an uairsin a mheudachadh gu 1 mìos agus 1 bliadhna aon uair‘ s gum faic thu an làrach agad ag obair mar a bhiodh dùil.';
$Definition['Security.Hsts.SubmitWarning'] = 'Rabhadh: Tha e math taic a thoirt do ro-luchdachadh HSTS mar chleachdadh as fheàrr. Ach, feumaidh tu an làrach agad a chuir a-steach gu hstspreload.org gus dèanamh cinnteach gu bheil e air a luchdachadh ro-làimh gu soirbheachail (ie gus an làn dhìon fhaighinn airson an rèiteachadh a tha san amharc).';
$Definition['See the documentation'] = 'Faic an Sgrìobhainnean';
$Definition['Select the default type for this role, if any.'] = 'Tagh an seòrsa bunaiteach airson na dreuchd seo, ma tha gin ann.';
$Definition['Session Timeout'] = 'Ùine an t-Seisein';
$Definition['Shadowed'] = 'Faileas';
$Definition['ShareImageDescription'] = 'Nuair a bhios cuideigin a ’roinn ceangal bhon làrach agad bidh sinn a’ feuchainn ri ìomhaigh fhaighinn bhon duilleag. Mura h-eil ìomhaigh air an duilleag cleachdaidh sinn an ìomhaigh seo na àite. Bu chòir don ìomhaigh a bhith co-dhiù 50 × 50, ach tha sinn a ’moladh 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Turn this option on to show all possible pocket locations. Turning on this option will only show the locations to users that can manage pockets.';
$Definition['SignIn.LockoutTime'] = 'An ùine a tha neach-cleachdaidh air a bhacadh bho bhith a’ logadh a-steach às deidh dha a bhith nas àirde na an àireamh de dh’ oidhirpean logadh a-steach.';
$Definition['Solid'] = 'Soladach';
$Definition['Some browsers support a color for the address bar.'] = 'Bidh cuid de bhrobhsairean a’ cur taic ri dath airson a’ bhàr seòlaidh.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Chan eil cuid de chuspairean nas sine a’ toirt taic do làn chomas deasachaidh. Gus faicinn dè an taic a tha aig cuspair, faodaidh tu gluasad thairis air an ainm aige gus faicinn far an tig deasachaidhean gu buil.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Is dòcha gu feumar cuid de chuspairean ùrachadh gus obrachadh le roinn a leanas. Faodaidh tu am feart a dhì-cheadachadh fhad ‘s a bhios tu ag ùrachadh do chuspair.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Aig amannan bidh thu airson an làrach Vanilla agad fhighe a-steach do làrach eile. Tha siostam freumhaichte Vanilla a’ tabhann dòigh furasta air sin. Tha malairtean coileanaidh ann nuair a bhios tu a’ cleachdadh làrach freumhaichte, mar sin thoir sùil air na sgrìobhainnean airson roghainnean eile agus cùisean cleachdaidh air leth.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Cuingealachadh sònraichte: Chan fhaod ach luchd-cleachdaidh le cead Garden.Curation.Manage an ath-bhualadh seo a chleachdadh.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Sònraich maids pàirt no làn nuair a chruthaicheas tu casg.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Spend a little time thinking about how you describe your site here. Giving your site a meaningful title and concise description could help your position in search engines.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Spruce suas na puist-d agad le bhith a ’cur suaicheantas agus a’ gnàthachadh nan dathan.';
$Definition['Start the first discussion.'] = 'Thoir air am ball a dhol air adhart anns a ’choimhearsnachd agad le <a href="{/post/discussion,url}">bhith a’ tòiseachadh a ’chiad deasbad a-</a> nis.';
$Definition['Subcommunities'] = 'Fo-choimhearsnachdan';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Tha tagadh a ’leigeil le luchd-cleachdaidh tag a chuir ri còmhraidhean a thòisicheas iad gus am bi iad nas ruigsinneach.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Tha teamplaidean nan cuspairean àbhaisteach. Gus an gnàthachadh, feumaidh tu leth-bhreac a chruthachadh.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB Feumaidh an deuchainn-lann <0 /> a bhith air a dhealbhadh gus a bhith a rèir do chuspair gnàthaichte. Faodar seo a dhèanamh a ’cleachdadh an deasaiche cuspair ùr againn. <1> Faigh a-mach tuilleadh.</1>';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'The banner title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages. Also, keep in mind some themes may also hide this title.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Tha am foirm clàraidh bunaiteach ag iarraidh</strong> air luchd-cleachdaidh ùr teacsa a chopaigeadh bho ìomhaigh CAPTCHA gus spammers a chumail a-mach às an làrach. Feumaidh tu cunntas aig <a href="http://recaptcha.net/">recaptcha.net</a> . Tha soidhnigeadh AN-ASGAIDH agus furasta. Nuair a tha thu air clàradh, till air ais an seo agus cuir a-steach na roghainnean a leanas:';
$Definition['The location of the authentication endpoint.'] = 'Suidheachadh ceann-uidhe an dearbhaidh.';
$Definition['ThemeHelp'] = 'Themes allow you to change the look & feel of your site.<br />Once a theme has been added to your %s folder, you can enable it here.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Tha ro-shealladh cuspair air a chuingealachadh ri bhith a ’taisbeanadh teamplaid agus css a’ chuspair.';
$Definition['Theming Guide'] = 'Stiùireadh Cuspair';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Bidh an suaicheantas gluasadach a’ nochdadh aig mullach na làraich agad. Cha bhith cuspairean air an dèanamh le deasaiche nan cuspairean agus cuid de chuspairean gnàthaichte a’ cleachdadh an t-suidheachaidh seo.';
$Definition['The New Embed System'] = 'An siostam freumhaichte ùr';
$Definition['The new embed system has improved performance.'] = 'Tha an siostam freumhaichte ùr air coileanadh a leasachadh, giùlan scrollaidh nas fheàrr, agus giùlan nas cunbhalaiche na an t-seann fhear. An-dràsta chan eil taic ri beachdan agus freumhachadh wordpress san t-siostam ùr Embed.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Tha dà sheòrsa putan san tagradh: bun-sgoil agus àrd-sgoil.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Bidh tuairisgeul na làraich mar as trice a’ nochdadh ann an einnseanan luirg. Bu chòir dhut feuchainn ri tuairisgeul a bhith agad a tha 100-150 caractar a dh’fhaid.';
$Definition['The text of the pocket.'] = 'Enter the text of the pocket. This will be output exactly as you type it so make sure that you enter valid HTML.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Nochdaidh an ìomhaigh suathaidh nuair a chomharraicheas tu làrach-lìn air scrion dachaigh inneal gluasadach. Mar as trice tha iad sin 152 piogsail.';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla Statistics turns your forum\'s dashboard into an analytics reporting tool, allowing you to review activity on your forum over specific time periods. You can <a href="http://vanillaforums.org/docs/vanillastatistics">read more about Vanilla Statistics</a> in our documentation.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'Bidh iad ag obair dìreach mar chuspairean cunbhalach. Aon uair ‘s gu bheil aon air a chur ris a’ phasgan cuspairean, faodaidh tu a chomasachadh an seo.';
$Definition['This is a style guide of your theme.'] = 'Seo stiùireadh stoidhle den chuspair agad. Tha eisimpleirean ann de na h-eileamaidean lèirsinneach a chaidh a chleachdadh air feadh an tagraidh. Faodaidh tu briogadh air na diofar widgets leithid am <0> Title Bar </0> no <1> Bratach </1> gus na togalaichean aca a dheasachadh anns a ’phanal taobh.';
$Definition['This is the administrative dashboard for your new community.'] = 'Is e seo am prògram rianachd airson do choimhearsnachd ùr. Thoir sùil air na roghainnean rèiteachaidh chun taobh. Às an sin, faodaidh tu rèiteachadh mar a tha do choimhearsnachd ag obair. <b>Gu gnàthach, chan fhaod ach luchd-cleachdaidh san dreuchd “Rianadair” am pàirt seo den choimhearsnachd agad fhaicinn.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Seo far an urrainn dhut feartan, duilleagan & co-phàirtean ùra Vanilla a chomasachadh agus fheuchainn a-mach.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Cha ghabh an obair-lann seo a chur à comas a chionn \'s gu bheil cruth gnàthaichte ga chur an sàs.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Chan urrainnear an obair-lann seo a chiorramachadh leis gu bheil e riatanach a rèir a ’chuspair làithreach.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Nochdaidh an suaicheantas seo aig mullach na làraich agad. Cha bhith cuspairean air an dèanamh le deasaiche nan cuspairean agus cuid de chuspairean gnàthaichte a’ cleachdadh an t-suidheachaidh seo.';
$Definition['This may be used to include content such as organization name and address in all outgoing emails.'] = 'Faodar seo a chleachdadh gus susbaint leithid ainm agus seòladh buidhne a ghabhail a-steach anns a h-uile post-d a tha a’ dol a-mach.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'This option shows/hides the locations where pockets can go, but only for users that have permission to add/edit pockets. Try showing the locations and then visit your site.';
$Definition['This page lists the endpoints of your API.'] = 'Tha an duilleag seo a ’liostadh puingean crìochnachaidh an API agad. Cliog air endpoints airson tuilleadh fiosrachaidh. Faodaidh tu gairmean beò a dhèanamh chun API bhon duilleag seo no taobh a-muigh a ’cleachdadh comharra ruigsinneachd.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Is e fiosrachadh pearsanta a tha san dreuchd seo. Chan fhaic ach luchd-cleachdaidh le cead fiosrachadh pearsanta fhaicinn.';
$Definition['This setting loads the page before executing Javascript.'] = 'Bidh an suidheachadh seo a ’luchdachadh na duilleige mus cuir thu Javascript an gnìomh a dh’ fhaodadh do SEO adhartachadh. <br> <strong>** Rabhadh: Faodaidh comasachadh an fheart seo mearachdan Javascript adhbhrachadh air an làrach agad. **</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Bidh an suidheachadh seo a’ luchdachadh na duilleige mus cuir thu Javascript an gnìomh a leasaicheas do SEO.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Chan urrainnear an cuspair seo a dhubhadh às oir is e an cuspair a tha ann an-dràsta.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Nochdaidh an tiotal seo air bratach na làraich agad agus ann am bàr tiotal do bhrobhsair. Ma thèid suaicheantas a luchdachadh suas, thèid e an àite an tiotail seo air duilleagan fòram mu choinneamh luchd-cleachdaidh. Cuideachd, cumaibh cuimhne gum faodadh cuid de chuspairean an tiotal seo fhalach.';
$Definition['Tiled Layout'] = 'Cruth leacach';
$Definition['Title Bar'] = 'Bàr tiotal';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'Cus seòlaidhean! Cuiridh sinn suas gu seòlaidhean %s anns a ’bhad.';
$Definition['TouchIconDescription'] = 'Bidh an ìomhaigh suathaidh a ’nochdadh nuair a chuireas tu comharra-lìn air làrach-lìn air sgàilean dachaigh inneal Apple. Mar as trice is e seo 152 piogsail. Bidh Apple a ’cur oiseanan cruinn agus buaidh solais gu fèin-ghluasadach.';
$Definition['Transparent'] = 'Follaiseach';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect allows users to sign in using their Twitter account. <b>You must register your application with Twitter for this plugin to work.</b>';

$Definition['Usercards'] = 'Cairtean cleachdaiche';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Leigidh cairtean-cleachdaidh leat dealbh aithghearr fhaighinn de fhiosrachadh neach-cleachdaidh. Nuair a bhios tu a ’coimhead air puist agus bùird stiùiridh, cliog air an ainm-cleachdaidh gus cairt fhaicinn a’ sealltainn fiosrachadh pròifil bunaiteach an luchd-cleachdaidh gun a bhith a ’gluasad air falbh bhon duilleag. Dèan comas air an fheart seo gus cleachdaidhean a chuir ris a ’chuspair àbhaisteach agad.';
$Definition['User inputs are based on the global background and text colors.'] = 'Tha inntrig luchd-cleachdaidh stèidhichte air cùl-fhiosrachadh cruinneil agus dathan teacsa.';
$Definition['User Profile'] = 'Pròifil cleachdaiche';
$Definition['Users may sign into your site using their Twitter account.'] = 'Faodaidh luchd-cleachdaidh clàradh a-steach don làrach agad a ’cleachdadh an cunntas Twitter aca.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Cleachd am putan aig mullach na duilleige gus riaghailt casg a chruthachadh.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Use the WordPress plugin to set up Vanilla Comments on your blog, or use the universal code to set up Vanilla Comments on any other platform.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Tha seirbheis sgrùdaidh ùr Vanilla an seo mu dheireadh. Dèan comas air an duilleag sgrùdaidh ùr againn UI gus faighinn gu na feartan sgrùdaidh as ùire leithid Rannsachadh Ball, seòrsachadh rannsachaidh agus soilleireachadh teirmean.';
$Definition['Vanilla Labs'] = 'Laban Vanilla';
$Definition['Verify and restore'] = 'Dearbhaich agus cuir air ais';
$Definition['VerifyUser'] = 'Thoir sùil air a ’bhogsa ri taobh an neach-cleachdaidh gus an comharrachadh mar <b>Dearbhaichte</b> gus nach bi na puist aca air an comharrachadh mar spama a-rithist. Bidh seo cuideachd a ’toirt air ais na dreuchdan a tha iad a’ feitheamh.';
$Definition['Video tutorial on finding &amp; managing users'] = 'Video tutorial on finding & managing users';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Video tutorial on managing roles & permissions';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Rabhadh: Faodaidh comasachadh an fheart seo mearachdan Javascript adhbhrachadh air do làrach.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Rabhadh</b> : Chan eil rèiteachadh an fhrithealaiche agad a ’toirt taic do luchdachadh dàta luath. Ma tha thu a ’toirt a-steach faidhle glè mhòr (ex. Còrr is 200,000 beachd) is dòcha gum bi thu airson beachdachadh air an rèiteachadh agad atharrachadh. Cliog an <a href="http://vanillaforums.com/porter">seo</a> airson tuilleadh fiosrachaidh.';
$Definition['Warning: This is for advanced users.'] = '<b>Warning</b>: This is for advanced users and requires that you make additional changes to your web server. This is usually only available if you have dedicated or vps hosting. Do not attempt this if you do not know what you are doing.';
$Definition['Welcome to Labs!'] = 'Fàilte gu Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Fàilte gu UI cuspaireil Vanilla. Tha an duilleag seo a’ liostadh na cuspairean a tha rim faighinn, agus a’ leigeil leat an lethbhreacadh no an deasachadh.';
$Definition['Welcome To Your Theme'] = 'Fàilte don chuspair agad';
$Definition['We recommend enabling 1–3 reactions at a time to avoid overwhelming users.'] = 'Tha sinn a’ moladh a bhith comasach air ath-bheachdan 1-3 a chomasachadh aig aon àm gus cus luchd-cleachdaidh a sheachnadh.';
$Definition['When enabled, users may choose to receive notifications from the community'] = 'Nuair a bhios e comasach, faodaidh luchd-cleachdaidh roghnachadh fiosan fhaighinn bhon choimhearsnachd';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Nuair a bhios e air a chomasachadh, faodaidh tu toraidhean a riaghladh, agus fo-choimhearsnachdan a chuir còmhla leis na toraidhean sin.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Nuair a bhios cuideigin a ’roinn ceangal bhon làrach agad bidh sinn a’ feuchainn ri ìomhaigh fhaighinn bhon duilleag. Mura h-eil ìomhaigh air an duilleag cleachdaidh sinn an ìomhaigh seo na àite. Bu chòir don ìomhaigh a bhith co-dhiù 50 × 50, ach tha sinn a ’moladh 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Nuair a thaghas tu Full Bleed, tha do chùl-raon follaiseach.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Co-dhiù an tèid no nach tèid na raointean pròifil a-staigh a ghabhail a-steach sa bhileag-lìn seo.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Co-dhiù an tèid no nach tèid na raointean pròifil prìobhaideach a ghabhail a-steach sa bhileag-lìn seo.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Tha thu gu bhith a ’cur a-steach roghainn cruth ùr. Faodar seo a ghnàthachadh agus ro-shealladh le bhith a ’cleachdadh an Deasaiche Cuspair againn. <0> Ionnsaich tuilleadh</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Faodaidh tu casg a chuir air a h-uile neach-cleachdaidh le seòlaidhean IP ro-leasaichte le "111.111.111" le bhith a ’cur casg seòrsa IP ris an luach" 111.111.111. * ".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Faodaidh tu seòlaidhean IP, seòlaidhean puist-d agus ainmean-cleachdaidh a thoirmeasg.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Faodaidh tu taghadh bho aon de na diofar stoidhlichean a tha an cuspair seo a ’tabhann.';
$Definition['You can configure some values differently for different screensizes.'] = 'Faodaidh tu cuid de luachan a rèiteachadh gu eadar-dhealaichte airson scrionaichean eadar-dhealaichte.';
$Definition['You can place files in your /uploads folder.'] = 'Ma tha am faidhle agad ro mhòr airson a luchdachadh suas gu dìreach air an duilleag seo faodaidh tu a chur sa phasgan / luchdaich suas agad. Dèan cinnteach gu bheil ainm an fhaidhle a ’tòiseachadh leis an fhacal <b>às-mhalairt</b> agus a’ crìochnachadh le aon de <b>.txt, .gz</b> .';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Faodaidh tu fad post as ìsle a shònrachadh gus dreuchdan goirid a bhrosnachadh.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Faodaidh tu Font Custom a luchdachadh suas san t-siostam cuspaireil agad. Dìreach dèan lethbhreac & pasg air an URL san raon.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Feumaidh tu fearann an url url a chur ri <0> Fearann ceadaichte </0> ann an rèiteachadh na làraich. <1> Ionnsaich tuilleadh mu chlàran àbhaisteach. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Thèid an cuspair gluasadach agad a chiorramachadh. Gus diofar chuspairean gluasadach is deasg a shuidheachadh, cleachd an seann UI cuspaireil.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Tha ainm na buidhne agad air a chleachdadh airson SEO microdata agus JSON + LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Bidh favicon na làraich agad a’ nochdadh ann am bàr tiotal a’ bhrobhsair agad. Thèid a lughdachadh gu h-iomchaidh.';
