<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s принял %4$s приглашение.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s изменил %4$s полномочия.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s обновил(а) фотографию на странице:';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s прокомментировал %4$s %8$s.';
$Definition['%1$s created an account for %4$s.'] = '%1$s создал аккаунт для %4$s.';
$Definition['%1$s joined.'] = '%1$s — теперь участник нашего форума.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s упомянул %3$s в %8$s';
$Definition['%1$s on %2$s'] = '%1$s на %2$s';
$Definition['%1$s signed in.'] = '%1$s вошёл.';
$Definition['%1$s to %2$s'] = 'от %1$s до %2$s';
$Definition['%1$s to %2$s of %3$s'] = 'от %1$s до %2$s из %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s обновил %6$s профиль.
';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s был добавлен в группу "%2$s"';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s был был удален из группы "%2$s"';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s был перенесен из группы "%2$s" в группу "%4$s"';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s написал на %4$s %5$s.';
$Definition['%3$s approved %2$s membership application.'] = 'Участие пользователя %2$s одобрил %3$s.';
$Definition['%3$s created an account for %1$s.'] = '%3$s создал учетную запись для %1$s.';
$Definition['%s$1 to %s$2'] = 'от %s$1 до %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = 'от %s$1 до %s$2 из %s$3';
$Definition['%s (Current)'] = '%s (текущее)';
$Definition['%s Agrees'] = '%s согласных';
$Definition['%s and %s others'] = '%s и %s других';
$Definition['%s and you'] = '%s и вы';
$Definition['%s Awesomes'] = '%s впечатленний';
$Definition['%s by %s'] = '%s по %s';
$Definition['%s changed %s\'s permissions.'] = '%s изменил настройки доступа';
$Definition['%s Comment'] = '%s комментарий';
$Definition['%s comment'] = 'Комментариев: %s';
$Definition['%s comment html'] = '%s комментарий';
$Definition['%s Comments'] = '%s комментариев';
$Definition['%s comments'] = 'Комментариев: %s';
$Definition['%s comments html'] = 'комментариев: %s';
$Definition['%s Connect'] = '%s Соеденен';
$Definition['%s day'] = '%s день';
$Definition['%s days'] = '%s дней';
$Definition['%s deleted this conversation.'] = '%s удалил(а) этот диалог.';
$Definition['%s discussion'] = '%s дискуссия';
$Definition['%s discussion html'] = '%s обсуждение';
$Definition['%s discussions'] = 'Дискуссий: %s';
$Definition['%s discussions html'] = '%s обсуждений';
$Definition['%s has been Jailed.'] = '%s был арестован.';
$Definition['%s has created an account for you at %s.'] = '%s создал для вас аккаунт в %s.';
$Definition['%s has invited you to join %s.'] = '%s пригласил вас вступить в %s.';
$Definition['%s has left this conversation.'] = '%s покинул(а) этот диалог.';
$Definition['%s has reset your password at %s.'] = '%s сбросил ваш пароль в %s.';
$Definition['%s hour'] = '%s час';
$Definition['%s hours'] = '%s часы';
$Definition['%s Insightfuls'] = '%s проницаний';
$Definition['%s is jailed.'] = '%s в тюрьме';
$Definition['%s level deep'] = 'Уровень глубины: %s';
$Definition['%s levels deep'] = 'Уровень глубины: %s';
$Definition['%s Likes'] = '%s лайков';
$Definition['%s LOLs'] = '%s ЛОЛов';
$Definition['%s member'] = '%s участник';
$Definition['%s members'] = 'Участники: %s';
$Definition['%s mentioned %s in a %s.'] = '%s упомянул вас в отзыве';
$Definition['%s message'] = '%s сообщение';
$Definition['%s messages'] = 'сообщения: %s ';
$Definition['%s minute'] = '%s минут';
$Definition['%s minutes'] = '%s минут';
$Definition['%s month'] = '%s месяц';
$Definition['%s months'] = '%s месяцев';
$Definition['%s New'] = '%s новое';
$Definition['%s new'] = 'новых: %s';
$Definition['%s new comment since you last read this.'] = '%s новый комментарий с момента вашего последнего просмотра.';
$Definition['%s new comments since you last read this.'] = 'Опубликованы новые комментарии с момента вашего последнего просмотра в количестве %s шт.';
$Definition['%s New Plural'] = 'Новые можества: %s';
$Definition['%s new plural'] = 'новых: %s';
$Definition['%s Not Found'] = '%s Не найдено';
$Definition['%s not found.'] = 'Не найдено: %s.';
$Definition['%s of %s'] = '%s → %s ';
$Definition['%s other'] = '%s другое';
$Definition['%s others'] = '%s других';
$Definition['%s Point'] = '%s балл';
$Definition['%s point'] = '%s балл';
$Definition['%s Points'] = 'Баллы: %s';
$Definition['%s points'] = 'баллы: %s';
$Definition['%s posts'] = 'публикаций: %s';
$Definition['%s result'] = '%s результат';
$Definition['%s results'] = '%s результаты';
$Definition['%s said'] = '%s сказали';
$Definition['%s said:'] = '%s написал:';
$Definition['%s Settings'] = '%s Настройки';
$Definition['%s tag(s) found.'] = '%s тэг(ов) найдено.';
$Definition['%s tags in the system'] = '%s тэгов в системе';
$Definition['%s Up Votes'] = '%s проголосовавших';
$Definition['%s user'] = '%s пользователь';
$Definition['%s users'] = '%s пользователей';
$Definition['%s view'] = '%s просмотр';
$Definition['%s view html'] = '%s просмотр';
$Definition['%s viewing'] = '%s просматривающих';
$Definition['%s views'] = 'Просмотров: %s';
$Definition['%s views html'] = 'просмотры: %s';
$Definition['%s votes'] = '%s проголосовало';
$Definition['%s was removed from the %s and added to the %s'] = '%s был удален из %s и добавлен в %s';
$Definition['%s week'] = '%s неделя';
$Definition['%s weeks'] = '%s недели';
$Definition['%s WTFs'] = '%s Чтоза#!';
$Definition['%s year'] = '%s год';
$Definition['%s years'] = '%s года';

$Definition['&laquo; hide previous quotes'] = '&laquo; скрыть предыдущие ценовые предложения';
$Definition['&raquo; show previous quotes'] = '&raquo; показать предыдущие ценовые предложения';

$Definition['(All)'] = '(Все)';
$Definition['(empty message)'] = '(пустое сообщение)';
$Definition['(Spoiler)'] = '(Спойлер)';

$Definition['+%s Guests'] = '+%s гостей';

$Definition[' - Page %s'] = '- Страница %s';

$Definition['1 message'] = 'Одно сообщение';

$Definition['<General Error>'] = '<Общая ошибка>';

$Definition['[%1$s] Membership Approved'] = '[%1$s] участников одобрено';
$Definition['[%s] Welcome Aboard!'] = 'Добро пожаловать на форум %s!';
$Definition['[Deleted User]'] = '[Пользователь удален]';

$Definition['About'] = 'Подробная информация';
$Definition['About %s users'] = 'Около %s пользователей ';
$Definition['AboutToDelete'] = 'Вы собираетесь удалить %s.';
$Definition['AboutToDeleteSelectedDiscussions'] = 'Вы собираетесь удалить %1$s из %2$s выбранных обсуждений.';
$Definition['Abuse'] = 'Жалоба';
$Definition['Accept'] = 'Одобрить';
$Definition['Accepted'] = 'Принято';
$Definition['Accept this answer.'] = 'Это верный ответ.';
$Definition['Access the Site'] = 'Доступ к сайту';
$Definition['Account Options'] = 'Опции аккаунта';
$Definition['Actions'] = 'Действия';
$Definition['Activate'] = 'Активированный';
$Definition['Active'] = 'Активно';
$Definition['Active Users'] = 'Активные пользователи';
$Definition['Activity'] = 'Активность';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s принято %4$s %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s комментирует вашу %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s комментирует вашу %8$s.';
$Definition['Activity.Comment'] = 'Комментировать';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s упомянули %3$s в %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s упомянули %3$s в %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s отправил вам %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s отправил вам %8$s.';
$Definition['Activity.Join.FullHeadline'] = 'теперь %1$s участник(ца) форума.';
$Definition['Activity.Join.ProfileHeadline'] = 'теперь %1$s участник(ца) форума';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s обновил фотографию %6$s на странице. ';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s обновил(а) фотографию на странице:';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s отвечено %4$s %8$s.';
$Definition['Add'] = 'Добавить';
$Definition['Add %s'] = 'Добавить %s';
$Definition['Add a Comment'] = 'Добавить комментарий';
$Definition['Add a Message'] = 'Добавить сообщение';
$Definition['Add an explanation'] = 'Добавить объяснение';
$Definition['Add another poll option ...'] = 'Добавить другой вариант ответа';
$Definition['Add a Profile Picture'] = 'Добавить фотографию';
$Definition['Add a time?'] = '
        Добавить время?

';
$Definition['Add a Warning'] = 'Добавить предупреждение';
$Definition['Add Badge'] = 'Добавить значек';
$Definition['Add Comment'] = 'Добавить комментарий';
$Definition['Add Cost'] = 'Добавить цену';
$Definition['Add Image'] = 'Добавить картинку';
$Definition['Add Message'] = 'Добавить сообщение';
$Definition['Add Note'] = 'Добавить заметку';
$Definition['Add People to this Conversation'] = 'Добавить собеседника в диалог';
$Definition['Add Route'] = 'Добавить перенаправление';
$Definition['Admin'] = 'Админ';
$Definition['Administrator'] = 'Администратор';
$Definition['Administrator Activity'] = 'Активность администраторов';
$Definition['Administrator and moderator'] = 'Администратор и модератор';
$Definition['administrators'] = 'администраторы';
$Definition['Advanced'] = 'Дополнительно';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'Произошла ошибка при обработке запроса. <br /> Сервер выдал следующее сообщение: %s';
$Definition['Agree'] = 'Согласен';
$Definition['Alert'] = 'Тревога';
$Definition['Align center'] = 'Выровнять по центру';
$Definition['Align left'] = 'Выровнять по левому краю';
$Definition['Align right'] = 'Выровнять по правому краю';
$Definition['All'] = 'Все';
$Definition['All %s'] = 'Все %s';
$Definition['All %s...'] = 'Все %s...';
$Definition['All Bookmarks'] = 'Все закладки';
$Definition['All Categories'] = 'Все разделы';
$Definition['all categories'] = 'Все разделы';
$Definition['All Conversations'] = 'Все диалоги';
$Definition['All Discussions'] = 'Все дискуссии';
$Definition['All discussions marked as viewed.'] = 'Все дискуссии отмечены как просмотренные.';
$Definition['All Events'] = 'Все события';
$Definition['All Members'] = '
        Все участники

';
$Definition['All members'] = 'Все участники';
$Definition['All Notifications'] = 'Все уведомления';
$Definition['Allow'] = 'Одобрить';
$Definition['Allow other members to see your email?'] = 'Показывать пользователям ваш email?';
$Definition['All Time Leaders'] = 'Лидеры за все время';
$Definition['Already Offered'] = 'Ранее предложенные';
$Definition['Already Warned'] = 'Уже предупрежден';
$Definition['Also banned for the following:'] = 'Был заблокирован за следующее: ';
$Definition['A message has been sent to your email address with password reset instructions.'] = 'На ваш email выслано письмо с инструкцией по смене пароля';
$Definition['Analytics'] = 'Аналитика';
$Definition['Ancient Membership'] = 'У истоков форума';
$Definition['An invitation has already been sent to the email you entered.'] = 'Инвайт был отправлен на тот Email, который вы ввели';
$Definition['Announce'] = 'Анонсирование';
$Definition['Announce...'] = 'Анонс';
$Definition['Announcement'] = 'Анонс';
$Definition['Announcements'] = 'Анонсы';
$Definition['Announce this discussion'] = 'Анонсировать эту дискуссию';
$Definition['Answer'] = 'Ответ';
$Definition['answer'] = 'ответ';
$Definition['Answers'] = 'Ответы';
$Definition['answers'] = 'ответы';
$Definition['Appearance'] = 'Внешний вид';
$Definition['Applicant'] = 'Кандидат';
$Definition['Applicants'] = 'Ожидают одобрения';
$Definition['Applicants & Invitations'] = 'Кандидаты и Приглашения';
$Definition['Apply'] = 'Включить';
$Definition['Apply Changes'] = 'Сохранить настройки';
$Definition['Apply for Membership'] = 'Регистрация';
$Definition['Apply for membership'] = 'Подать заявку на участие';
$Definition['Approve'] = 'Утвердить';
$Definition['Approve Applicant'] = 'Утвердить';
$Definition['Approved'] = 'Утверждено';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Вы точно хотите выполнить это действие?';
$Definition['Are you attending this event?'] = '
        Вы собираетесь на это мероприятие?

';
$Definition['Are you sure you want to delete this %s?'] = 'Вы уверены, что %s должна быть удалена?';
$Definition['Are you sure you want to do that?'] = 'Вы уверены в своих действиях?';
$Definition['Are you sure you want to do this?'] = 'Вы уверены в своих действиях?';
$Definition['Are you sure you want to join this group?'] = 'Вы уверены, что хотите присоединиться к этой группе?';
$Definition['Are you sure you want to leave this conversation?'] = 'Вы уверены, что хотите покинуть этот диалог?';
$Definition['Are you sure you want to leave this group?'] = 'Вы уверены, что хотите выйти из этой группы?';
$Definition['Are you sure you wish to continue?'] = 'Вы уверены, что хотите продолжить?
';
$Definition['Ask a Question'] = 'Задать вопрос';
$Definition['Ask Question'] = 'Отправить';
$Definition['Attach a file'] = 'Прикрепить файл';
$Definition['Attach image/file'] = 'Прикрепить изображение/файл';
$Definition['Attachments'] = 'Прикреплённые файлы';
$Definition['Attach this warning to the %s.'] = 'Прикрепить это предупреждение к %s.';
$Definition['AttemptingSignOut'] = 'Вы пытаетесь выйти. Вы уверены, что хотите %s?';
$Definition['Attending'] = '
        Посещает

';
$Definition['Attending (%s)'] = 'Посетят (%s)';
$Definition['Authenticate URL'] = 'Проверить URL';
$Definition['Authentication'] = 'Авторизация';
$Definition['Author'] = 'Автор';
$Definition['available'] = 'доступно';
$Definition['Awaiting Moderation'] = 'Ожидает модерации';
$Definition['Awesome'] = 'Потрясающий';

$Definition['Back to Discussions'] = 'Вернуться к просмотру тем';
$Definition['Back to Profile'] = 'Вернуться в профиль';
$Definition['Badge'] = 'Значек';
$Definition['Badge404'] = 'Значек не найден.';
$Definition['Badges'] = 'Значки';
$Definition['BadgesModuleTitle'] = 'Значки';
$Definition['BadgesNobody'] = 'Никто еще не был награжден этим значком.';
$Definition['Ban'] = 'Бан';
$Definition['Ban.Action'] = 'Бан';
$Definition['Banned'] = 'Заблокирован';
$Definition['Banned for being abusive.'] = 'Заблокирован за оскорбления.';
$Definition['Banned for spamming.'] = 'Заблокирован за спам.';
$Definition['Banned for the following:'] = 'Заблокирован за следующее:';
$Definition['Banned users can no longer access the site.'] = 'Заблокированные пользователи не имеют доступа к сайту.';
$Definition['Banner'] = 'Шапка сайта';
$Definition['BanReason.1'] = 'Заблокирован менеджером сообщества.';
$Definition['BanReason.2'] = 'Заблокирован по IP адресу, электронной почте или никнейму.';
$Definition['BanReason.4'] = 'Временно забанен менеджером сообщества.';
$Definition['BanReason.8'] = 'Заблокирован за предупреждения.';
$Definition['Ban User'] = 'Забанить пользователя';
$Definition['Ban Value'] = 'Значение бана';
$Definition['Basic'] = 'По умолчанию';
$Definition['Best Answer'] = 'Лучший ответ';
$Definition['Best Answers'] = 'Лучшие ответы';
$Definition['Best Of'] = 'Лучшее';
$Definition['Best Of...'] = 'Лучшее...';
$Definition['Blank Discussion Topic'] = 'Пустая топик дискуссии';
$Definition['Blank Message'] = 'Пустое сообщение';
$Definition['Blog'] = 'Блог';
$Definition['Blogs'] = 'Блоги';
$Definition['Body'] = 'текст сообщения';
$Definition['Bold'] = 'Жирный шрифт';
$Definition['Bookmark'] = 'Добавить в закладки';
$Definition['bookmarked discussion'] = 'отмеченные обсуждения';
$Definition['Bookmarked Discussions'] = 'Отмеченные дискуссии';
$Definition['Bookmarks'] = 'Закладки';
$Definition['bookmarks'] = 'закладки';
$Definition['Browse Groups'] = 'Обзор групп';
$Definition['Browse popular groups.'] = 'Обзор популярных групп.';
$Definition['By'] = 'От';
$Definition['by'] = 'от';
$Definition['By %s'] = 'От %s';
$Definition['by %s'] = 'от %s';
$Definition['by Date'] = 'по Дате';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Загружая изображение, вы автоматически подтверждаете, что имеете право распространять загружаемое изображение и не нарушаете авторские права правообладателя.';

$Definition['Can\'t post as often.'] = 'Не может создавать дискуссии';
$Definition['Can\'t post discussions.'] = 'Не может создавать дискуссии';
$Definition['Cancel'] = 'Отмена';
$Definition['Casual'] = 'Повседневный';
$Definition['Categories'] = 'Разделы';
$Definition['CategoriesShowFollowed'] = 'Показать только мои отслеживаемые разделы';
$Definition['CategoriesShowUnfollowed'] = 'Показать скрытые разделы';
$Definition['CategoriesViewingAll'] = 'Вы просматриваете все разделы.';
$Definition['CategoriesViewingFollowed'] = 'Вы просматриваете только собственные отслеживаемые разделы.';
$Definition['Category'] = 'Раздел';
$Definition['Category Filter'] = 'Фильтр разделов';
$Definition['CategoryID'] = 'Раздел';
$Definition['Category Management'] = 'Менеджер разделов';
$Definition['Category marked as viewed.'] = 'Раздел отмечен как просмотренный.';
$Definition['Category Notifications'] = 'Уведомления раздела';
$Definition['Category to Use'] = 'Используемый раздел';
$Definition['Change'] = 'Изменить';
$Definition['Change Icon'] = 'Изменить иконку';
$Definition['Change language'] = 'Изменить язык';
$Definition['Change My Password'] = 'Изменить мой пароль';
$Definition['Change My Picture'] = 'Изменить моё изображение';
$Definition['Change Password'] = 'Изменение пароля';
$Definition['Change Picture'] = 'Изменение изображения';
$Definition['Check all roles that apply to this user:'] = 'Проверьте все группы, в которых может состоять этот пользователь:';
$Definition['Check it out'] = 'Перейдите к материалу';
$Definition['Child Categories'] = 'Дочерние разделы';
$Definition['Child Categories:'] = 'Дочерние разделы:';
$Definition['Choose a name to identify yourself on the site.'] = 'Выберите имя для идентификации себя на сайте';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Выберите дискуссию, в которую будут объединены все комментарии:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Выберите, хотите ли вы задать вопрос или начать дискуссию.';
$Definition['Clear'] = 'Очистить';
$Definition['clear'] = 'очистить';
$Definition['Clear %s'] = 'Очистить %s';
$Definition['Clear Conversation History'] = 'Очистить историю диалога';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Кликните <a href="%s">здесь</a> чтобы вернуться к дискуссии.';
$Definition['Click accept or reject beside an answer.'] = 'Кликните "Одобрить" или "Отклонить" для того, чтобы ответить на вопрос.';
$Definition['clicking here'] = 'кликнув сюда';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Нажмите %s рядом с дискуссией, чтобы добавить её в закладки.';
$Definition['Click to re-attach'] = 'Кликните, чтобы прикрепить заново';
$Definition['Close'] = 'Закрыть';
$Definition['Closed'] = 'Закрыто';
$Definition['Close this discussion'] = 'Закрыть эту дискуссию';
$Definition['Color'] = 'Цвет';
$Definition['Combo Breaker'] = 'Комбо выключатель';
$Definition['Comment'] = 'Комментарий';
$Definition['comment'] = 'комментарий';
$Definition['Comment As ...'] = 'Комментировать как ...';
$Definition['Comment by %s'] = 'Комментарий от %s';
$Definition['Comment in'] = 'Раздел:';
$Definition['Commenting as %1$s (%2$s)'] = 'Комментируя, как %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Комментирование запрещено.';
$Definition['Comments'] = 'Комментарии';
$Definition['comments'] = 'комментарии';
$Definition['Comments are between {UserID,you}.'] = 'Комментарии между {UserID,you}.';
$Definition['Community'] = 'Сообщество';
$Definition['Community Guidelines'] = 'Принципы сообщества';
$Definition['Completed'] = 'Завершено';
$Definition['Completely delete the warning.'] = 'Полностью удалить предупреждение.';
$Definition['Confirm'] = 'Подтверждение';
$Definition['Confirmed email address'] = 'Подтвержденный email адрес';
$Definition['Confirm Email'] = 'Подтвердите email';
$Definition['Confirm My Email Address'] = 'Подтвердить мой адрес эл. почты';
$Definition['Confirm Password'] = 'Подтвердите пароль';
$Definition['Confirm Your Email Address'] = 'Подтвердите свой адрес эл. почты';
$Definition['Connect'] = 'Соединение';
$Definition['ConnectAccountExists'] = 'У вас здесь уже есть учетная запись.';
$Definition['ConnectChooseName'] = 'Выберите имя под которым вы будете известны на сайте. ';
$Definition['ConnectCreateAccount'] = 'Добавить информацию &amp; Создать аккаунт';
$Definition['Connected'] = 'Подключено';
$Definition['Connected With: {ProviderName}'] = 'Подключение через: {ProviderName}';
$Definition['ConnectExistingPassword'] = 'Введите ваш текущий пароль.';
$Definition['Connecting...'] = 'Подключение...';
$Definition['Connection'] = 'Подключение';
$Definition['ConnectLeaveBlank'] = 'Оставить пустым в том случае если вы не подключаетесь к существующей учетной записи.';
$Definition['ConnectName'] = 'Ник';
$Definition['ConnectRegisteredName'] = 'Ваше имя учетной записи: <strong>%s</strong>';
$Definition['Connect your profile to social networks.'] = 'Соединить профиль с социальными сетями, чтобы быть в курсе активности и делиться вашей активностью с друзьями и подписчиками.';
$Definition['Contact Us'] = 'Связаться с Нами';
$Definition['Continue'] = 'Продолжить';
$Definition['conversation'] = 'диалог';
$Definition['Copy'] = 'Копировать';
$Definition['Core'] = 'Ядро';
$Definition['Created'] = 'Создано';
$Definition['Create Discussions'] = 'Создать дискуссию';
$Definition['Created on %s'] = 'Создано: %s';
$Definition['Create One.'] = 'Зарегистрируйтесь!';
$Definition['Current'] = 'Текущий';
$Definition['Currently: '] = 'Сейчас';
$Definition['Custom Information'] = 'Особая информация';
$Definition['Customize'] = 'Выделяйся';
$Definition['customize your profile now'] = 'настройки профиля';
$Definition['Customize your Public Profile'] = 'Изменение вашего профиля';
$Definition['Custom Profile Fields'] = 'Произвольные поля аккаунта';
$Definition['Custom Profile Field Settings'] = 'Настройка особых полей профиля';

$Definition['Dashboard'] = 'Консоль';
$Definition['Dashboard Home'] = 'Главная страница консоли';
$Definition['Dashboard Summaries'] = 'Сводка консоли';
$Definition['Date'] = 'Дата';
$Definition['Date.DefaultDateTimeFormat'] = '%d.%m.%Y %H:%M';
$Definition['Date.DefaultDayFormat'] = '%e %b';
$Definition['Date.DefaultFormat'] = '%d.%m.%Y';
$Definition['Date.DefaultTimeFormat'] = '%H:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Date. Expects \'mm/dd/yyyy\'.'] = '
        Требуемый формат даты "мм/дд/гггг".

';
$Definition['Date Added'] = 'Дата добавления';
$Definition['Date Examples'] = 'Примеры: Понедельник, сегодня, на прошлой неделе, 26 марта, 3/26/04';
$Definition['Date within'] = 'Дата в течение';
$Definition['days'] = 'дней';
$Definition['Decline'] = 'Отклонить';
$Definition['Declined'] = 'Отклонено';
$Definition['Default'] = 'По умолчанию';
$Definition['default'] = 'по умолчанию';
$Definition['Default Status'] = 'Статус по умолчанию';
$Definition['Define Thumbnail'] = 'Кликните и обозначьте на изображении область, которая станет вашей миниатюрой.';
$Definition['Delete'] = 'Удаление';
$Definition['Delete %s'] = 'Удалить %s';
$Definition['Delete Account'] = 'Удалить аккаунт';
$Definition['Delete Content'] = 'Удалить контент';
$Definition['Delete Conversation'] = 'Удалить диалог';
$Definition['Deleted'] = 'Удалено';
$Definition['Delete Discussion'] = 'Удалить дискуссию';
$Definition['Delete Forever'] = 'Удалить навсегда';
$Definition['Delete Group'] = 'Удалить группу';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Удалить пользователя и содержимое его профиля. Это может вызвать некоторую путаницу, так как на некоторые удаляемые сообщения могут быть ответы, которые повиснут в воздухе. Хорошо подходит для удаления спама.';
$Definition['Delete User Content'] = 'Удалить контент пользователя';
$Definition['Delete User Forever'] = 'Удалить пользователя навсегда';
$Definition['Deny'] = 'Запретить';
$Definition['Deny Applicant'] = 'Запретить';
$Definition['Description'] = 'Описание';
$Definition['Did this answer the question?'] = 'Это ответ на вопрос?';
$Definition['Disable'] = 'Выключить';
$Definition['Disabled'] = 'Выключено';
$Definition['Disagree'] = 'Не согласиться';
$Definition['Discussion'] = 'Дискуссия';
$Definition['discussion'] = 'дискуссия';
$Definition['Discussion Board'] = 'Дискуссионный клуб';
$Definition['Discussions'] = 'Дискуссии';
$Definition['discussions'] = 'обсуждения';
$Definition['Discussions Page'] = 'Страница дискуссий';
$Definition['Discussion Title'] = 'Заголовок дискуссии';
$Definition['Dislike'] = 'Не одобрять';
$Definition['Dismiss'] = 'Деанонсировать';
$Definition['Documentation'] = 'Документация';
$Definition['Don\'t announce.'] = 'Не анонсировать.';
$Definition['Don\'t fold quotes'] = 'Не скрывайте цитаты';
$Definition['Don\'t have an account? %s'] = 'Нет аккаунта? %s';
$Definition['Download'] = 'Загрузить';
$Definition['Download the sounds as MP3'] = 'Скачать аудио в виде MP3';
$Definition['Do you want to expire or delete this warning?'] = 'Вы хотите отметить это предупреждение как устаревшее или удалить?';
$Definition['Draft saved at %s'] = 'Черновик сохранен %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Выделите и измените размер вашего аватара.';
$Definition['Drop image/file'] = 'Поместить изображение/файл';

$Definition['Earned'] = 'Заработанно';
$Definition['Edit'] = 'Редактирование';
$Definition['edit'] = 'редактирование';
$Definition['Edit %s'] = 'Редактировать %s';
$Definition['Edit Account'] = 'Редактировать аккаунт';
$Definition['Edit Comment'] = 'Редактировать комментарий';
$Definition['Edit Discussion'] = 'Редактировать дискуссию';
$Definition['edited %s'] = 'отредактировано %s';
$Definition['Edited %s by %s.'] = 'Отредактировано %s по %s.';
$Definition['Editing'] = 'Редактирование';
$Definition['Edit My Account'] = 'Редактировать мой аккаунт';
$Definition['Edit My Profile'] = 'Редактировать профиль';
$Definition['Edit My Thumbnail'] = 'Изменить мой аватар';
$Definition['editor.BBCodeHelpText'] = 'Вы можете использовать <a href="https://ru.wikipedia.org/wiki/BBCode" target="_new">BBCode</a> в вашей публикации.';
$Definition['editor.HtmlHelpText'] = 'Вы можете использовать <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Simple HTML</a> в вашей публикации.';
$Definition['editor.MarkdownHelpText'] = 'Вы можете использовать <a href="https://ru.wikipedia.org/wiki/Markdown" target="_new">Markdown</a> в вашей публикации.';
$Definition['editor.TextHelpText'] = 'Вы используете простой текст в вашей публикации.';
$Definition['editor.WysiwygHelpText'] = 'Вы используете <a href="https://ru.wikipedia.org/wiki/WYSIWYG" target="_new">WYSIWYG</a> в вашей публикации.';
$Definition['Edit Preferences'] = 'Изменить настройки';
$Definition['Edit Profile'] = 'Редактировать профиль';
$Definition['Edit Tag'] = 'Редактировать тэг';
$Definition['Edit Thumbnail'] = 'Редактирование аватара';
$Definition['Eighth Anniversary'] = 'Восьмая годовщина';
$Definition['Email'] = 'Электронная почта';
$Definition['Email/Username'] = 'Почта или Логин';
$Definition['EmailConfirmEmail'] = 'Вам необходимо подтвердить Ваш email. 
Для подтверждения нажмите на ссылку ниже: {/entry/emailconfirm,exurl,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailFooter'] = '
Удачного дня!';
$Definition['EmailHeader'] = 'Здравствуйте, {User.Name}!
';
$Definition['EmailInvitation'] = 'Привет!

%1$s приглашает присоединиться к сообществу сайта %2$s. Если желаете сделать это, перейдите по этой ссылке:
%3$s';
$Definition['EmailMembershipApproved'] = 'Привет %1$s!

Вы были приняты в сообщество! Вы можете войти сейчас по этой ссылке:
%2$s';
$Definition['EmailNotification'] = '%1$s

Для просмотра перейдите по ссылке:
%2$s

Всего вам хорошего!';
$Definition['Email Notifications'] = 'Уведомления по Email';
$Definition['Email Or Username'] = 'Имя пользователя или email';
$Definition['EmailPassword'] = '%2$s сбросил ваш пароль на сайте %3$s.

Вот ваши данные:
Email: %6$s
Пароль: %5$s

Адрес сайте: %4$s';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Использовать в качестве отправителя следующий адрес электронной почты:';
$Definition['Email Source'] = 'Электронная почта';
$Definition['EmailStoryNotification'] = '%1$s
%3$s
---
Для просмотра перейдите по ссылке:
%2$s

Всего вам хорошего!';
$Definition['Email Unavailable'] = 'Почта недоступна';
$Definition['Email visible to other users'] = 'Email виден другим пользователям';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Читайте полный рассказ здесь</a></p><div class="ClearFix"></div></div>';
$Definition['EmbeddedNoBodyFormat'] = '{Url}';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Image}<strong>{Title}</strong>
<p>{Excerpt}</p>
<p><a href="{Url}">Читайте полный рассказ здесь</a></p><div class="ClearFix"></div></div>';
$Definition['Emoji'] = 'Эмодзи';
$Definition['Enable'] = 'Включить';
$Definition['Enabled'] = 'Включено';
$Definition['End time?'] = '
        Время завершения?

';
$Definition['English'] = 'Английский';
$Definition['Enter your Email address'] = 'Адрес вашей почты';
$Definition['Enter your email address'] = 'Введите ваш email адрес';
$Definition['Enter your Email address or username'] = 'Введите ваш Email или логин';
$Definition['Enter Your OpenID Url'] = 'Введите ваш OpenID адрес';
$Definition['Enter your search term.'] = 'Введите ваш критерий поиска.';
$Definition['Erase User Content'] = 'Стереть контент пользователя';
$Definition['Error'] = 'Ошибка';
$Definition['ErrorBadInvitationCode'] = 'Ошибка: неверный код приглашения';
$Definition['ErrorCredentials'] = 'К сожалению, нет доступа к этой учетной записи';
$Definition['ErrorPermission'] = 'Простите, доступ ограничен.';
$Definition['ErrorPluginDisableRequired'] = 'Вы не можете отключить плагин {0}, так как плагин зависит от {1}.';
$Definition['ErrorPluginEnableRequired'] = 'Прежде чем включить этот плагин, необходимо включить плагин: {0}.';
$Definition['ErrorPluginVersionMatch'] = 'Активированный {0} плагин (версии {1}) не отвечает условиям, необходимым версии ({2}).';
$Definition['ErrorRecordNotFound'] = 'Запрошеная запись не найдена';
$Definition['ErrorTermsOfService'] = 'Вы должны согласиться с условиями использования.';
$Definition['Event'] = 'Событие';
$Definition['Event Details'] = '
        Детали мероприятия

';
$Definition['Events'] = 'События';
$Definition['everyone'] = 'все';
$Definition['Everything'] = 'Всё';
$Definition['Expired'] = 'Истекло';
$Definition['Expires'] = 'Истекает';
$Definition['expires %s'] = 'истекает: %s';

$Definition['Failed to delete group.'] = 'Не удалось удалить группу.';
$Definition['Failed to find discussion for commenting.'] = 'Не удалось найти дискуссию для комментариев.';
$Definition['Failed to load the poll.'] = 'Ошибка загрузки опроса';
$Definition['Feedback'] = 'Обратная связь';
$Definition['Female'] = 'Женский';
$Definition['Fifth Anniversary'] = 'Пятая годовщина';
$Definition['FileName'] = 'Имя файла';
$Definition['Filename'] = 'Название файла';
$Definition['FileSize'] = 'Размер файла';
$Definition['File Size'] = 'Размер файла';
$Definition['Find your account information below.'] = 'Ниже представлена информация вашего аккаунта.';
$Definition['First Anniversary'] = 'Первая годовщина';
$Definition['First Comment'] = 'Первый комментарий';
$Definition['Flag'] = 'Сообщить модератору';
$Definition['Folder'] = 'Папка';
$Definition['Folders'] = ' Папки';
$Definition['Follow'] = 'Подписаться';
$Definition['Follow %s'] = 'Следить %s';
$Definition['Followed by %d people'] = '%d подписчиков';
$Definition['Followed by %d person'] = 'Подписан %d человек';
$Definition['followed categories'] = 'Отслеживаемые разделы';
$Definition['Following %d people'] = 'Следит за %d людми';
$Definition['Following %d person'] = 'Наблюдается %d пользователями';
$Definition['FollowOnly'] = 'Проследуйте по ссылке ниже, чтобы проверить:';
$Definition['Follows'] = 'Следят';
$Definition['For a stronger password, increase its length or combine upper and lowercase letters, digits, and symbols.'] = 'Чтобы сделать пароль более надежным, увеличьте его длину или комбинируйте буквы верхнего и нижнего регистра, цифры и символы.';
$Definition['Forgot?'] = 'Забыли?';
$Definition['Forgot your password?'] = 'Забыли ваш пароль?';
$Definition['Format'] = 'Формат';
$Definition['Format his'] = 'его';
$Definition['Format their'] = 'их';
$Definition['Format You'] = 'вы';
$Definition['Format you'] = 'я';
$Definition['Format Your'] = 'ваш';
$Definition['Forum'] = 'Форум';
$Definition['Forums'] = 'Форумы';
$Definition['Forum Signature Settings'] = 'Настройки подписей для форума';
$Definition['Fourth Anniversary'] = 'Четвертая годовщина';
$Definition['Friends'] = 'Друзья';
$Definition['From'] = '
        От

';
$Definition['Full Site'] = 'Полная версия сайта';

$Definition['Garden.Email.SupportAddress'] = 'Email поддержки';
$Definition['Garden.Email.SupportName'] = 'Название поддержки';
$Definition['Garden.Registration.DefaultRoles'] = 'по-умолчанию';
$Definition['Garden.Title'] = 'Заголовок баннера';
$Definition['Gender'] = 'Пол';
$Definition['General'] = 'Новости';
$Definition['Generate import SQL only'] = 'Генерировать только импорт SQL';
$Definition['Generate Password'] = 'Генерировать пароль';
$Definition['Get an audio challenge'] = 'Получить звуковой вызов';
$Definition['Get a new challenge'] = 'Получить вызов';
$Definition['Get a visual challenge'] = 'Получить визуальный вызов';
$Definition['Give'] = 'Выдать';
$Definition['Give a Badge to %s'] = 'Выдать значек %s';
$Definition['Give Badge'] = 'Выдать значек';
$Definition['Given'] = 'Выданный';
$Definition['Go'] = '&rarr;';
$Definition['Group'] = 'Группа';
$Definition['group'] = 'группа';
$Definition['GroupEmptyAnnouncements'] = 'Когда-то сюда попадут важные вещи.';
$Definition['GroupEmptyDiscussions'] = 'Ужасно тихо здесь, правда?';
$Definition['GroupEmptyEvents'] = 'Эх, никаких событий не намечается.';
$Definition['Group Icon'] = 'Иконка группы';
$Definition['Group Info'] = 'Группа информация';
$Definition['Group Leaders'] = 'Лидеры';
$Definition['Group Members'] = 'Пользователи';
$Definition['GroupMembersEmpty'] = 'Никто еще не присоединился. Расскажите о нас!';
$Definition['Group Options'] = 'Опции Группа';
$Definition['Groups'] = 'Группы';
$Definition['groups'] = 'группы';
$Definition['Guest'] = 'Гость';
$Definition['GuestModule.Message'] = 'Похоже, вы здесь новенький. Чтобы принять участие, нажмите одну из кнопок ниже!';
$Definition['Guests'] = 'гостей';

$Definition['Hang on a sec while we sign you out.'] = 'Подождите секунду, пока мы подпишем вас';
$Definition['Have a great day!'] = 'Приятного вам дня!';
$Definition['he'] = 'он';
$Definition['Heading'] = 'Заголовок';
$Definition['Heading %s'] = 'Заголовок %s';
$Definition['HeadlineFormat.AcceptAnswer'] = '{ActivityUserID} принял ответ {NotifyUserID}.';
$Definition['HeadlineFormat.Answer'] = '{ActivityUserID,user} ответил(а) на ваш вопрос: <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Badge'] = '{ActivityUserID,You} удостоились <a href="{Url,html}">{Data.Name,text}</a> значка.';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} заблокировал пользователя {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} оставил комментарий в <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.ConversationMessage'] = '{ActivityUserID,User} отправил вам <a href="{Url,html}">сообщение</a>';
$Definition['HeadlineFormat.Discussion'] = '{ActivityUserID,user} начал новую дискуссию. <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.Mention'] = '{ActivityUserID,user} упомянул вас в <a href="{Url,html}">{Data.Name,text}</a>';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,user} изменил картинку профиля {ActivityUserID,user}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} на сайте.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,user} разбанил пользователя {ActivityUserID,user}.';
$Definition['HeadlineFormat.Warning'] = '{ActivityUserID,user} предупредил {RegardingUserID,user}.';
$Definition['Hello!'] = 'Здравствуйте!';
$Definition['Hello %s!'] = 'Здравствуйте, %s!';
$Definition['Hello {User.Name}!'] = 'Здравствуйте, {User.Name}!';
$Definition['Help'] = 'Помощь';
$Definition['her'] = 'её';
$Definition['Hide'] = 'Скрыть';
$Definition['Hide my online status from other members'] = 'Скрыть моё присутствие от других пользователей';
$Definition['Hide previous quotes'] = '&laquo; скрыть предыдущие ценовые предложения';
$Definition['Hide signatures?'] = 'Скрыть подписи?';
$Definition['Hide signatures always'] = 'Не показывать подписи';
$Definition['Hide signatures on my mobile device'] = 'Скрывать подпись на мобильных устройствах';
$Definition['his'] = 'его';
$Definition['Home'] = 'Начало';
$Definition['hours'] = 'час(ов)';
$Definition['How can we help you?'] = 'Как мы можем вам помочь?';
$Definition['Howdy, Stranger!'] = 'Привет, незнакомец!';
$Definition['How long do you want this warning to last?'] = 'На какой срок вынести предупреждение?';
$Definition['How many levels deep should we start folding up quote trees?'] = 'На сколько уровней в глубину позволять встраивать цитаты?';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Соглашаюсь с <a id="TermsOfService" class="Popup" target="terms" href="%s">правилами</a> форума';
$Definition['Icon'] = 'Иконка';
$Definition['I confirm that I have received consent to join this community.'] = 'Так как я не достиг возраста %d лет, я подтверждаю, что получил согласие присоединиться к этому сообществу.';
$Definition['Idea'] = 'Идея';
$Definition['idea'] = 'идея';
$Definition['Ideas'] = 'Идеи';
$Definition['ideas'] = 'идеи';
$Definition['Idea Status'] = 'Статус идеи';
$Definition['Idea Statuses'] = 'Статусы идей';
$Definition['Ideation'] = 'Формирование идеи';
$Definition['Ignore'] = 'Игнорировать';
$Definition['Ignore List'] = 'Список игнора';
$Definition['Ignore Someone'] = 'Игнорировать кого-либо';
$Definition['Image'] = 'Изображение';
$Definition['images'] = 'изображения';
$Definition['Images not allowed'] = 'Изображения запрещены';
$Definition['Images will be scaled to a maximum height of {maxImageHeight}px.'] = 'Изображения будут отрегулированы до максимальной высоты {maxImageHeight}px';
$Definition['Image URL'] = 'URL изображения';
$Definition['in'] = 'Раздел:';
$Definition['In <b>%s.</b>'] = 'В <b>%s</b>.';
$Definition['In <b>%s</b> and recent discussions.'] = 'В <b>%s</b> и свежие дискуссии.';
$Definition['Inbox'] = 'Переписка';
$Definition['Incorrect. Try again.'] = 'Не правильно. Повторите.';
$Definition['Indent'] = 'Абзац';
$Definition['In Progress'] = 'В процессе';
$Definition['In recent discussions.'] = 'В недавних обсуждениях.';
$Definition['In Review'] = 'На рассмотрении';
$Definition['In seconds'] = 'В секундах';
$Definition['Inserted'] = 'Вставлено';
$Definition['Insert Image'] = 'Вставить картинку';
$Definition['Insightful'] = 'Проницательно';
$Definition['Internal'] = 'Внутренний';
$Definition['In this Conversation'] = 'Участники диалога';
$Definition['Invalid CSRF token.'] = 'Недопустимый маркер CSRF. Пожалуйста, попробуйте еще раз.';
$Definition['Invalid password.'] = 'Введенный неверный пароль. Имейте ввиду, что пароли чувствительны к регистру.';
$Definition['Invalid photo URL.'] = 'Неверный URL фото.';
$Definition['Invitation'] = 'По приглашению';
$Definition['Invitations'] = 'Приглашения';
$Definition['Invite'] = 'Приглашение';
$Definition['Invited on %s'] = 'Приглашен %s';
$Definition['InviteErrorPermission'] = 'Простите, доступ ограничен.';
$Definition['Invite Friends'] = 'Пригласить друзей';
$Definition['Invite friends'] = 'Пригласить друзей';
$Definition['Invite Members'] = 'Пригласить участников';
$Definition['Invite one or more people to join this group.'] = '
        Пригласите в эту группу одного или нескольких человек.

';
$Definition['IPAddress'] = 'IP адрес';
$Definition['IP Address'] = 'IP адрес';
$Definition['I remember now!'] = 'Ой, вспомнил!';
$Definition['Italic'] = 'Курсив';
$Definition['Item'] = 'Сообщение';
$Definition['item'] = 'Вклад';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'Похоже, вы новенький! Присоединяйтесь к нам, кликнув одну из кнопок ниже!';

$Definition['Jail'] = 'Тюрьма';
$Definition['Jailed users have reduced abilities.'] = 'Заключенные пользователи ограниченны в возможностях.';
$Definition['Join'] = 'Вступить';
$Definition['Join %s'] = 'Присоединиться %s';
$Definition['Join Date'] = 'Дата вступления';
$Definition['Joined'] = 'Присоединился';
$Definition['Joined %s'] = 'Регистрация %s';
$Definition['Join this Community Now'] = 'Вступить в это сообщество';
$Definition['Join this Group'] = 'Присоединиться к этой группе';
$Definition['Join this group to view its content.'] = 'Вступите в группу, чтобы просматривать ее содержимое.';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Удалить пользователя, но оставить весь его контент.';
$Definition['Just expire the warning.'] = 'Просто истекает предупреждение.';
$Definition['Just you!'] = 'Только ты!';

$Definition['Keep me signed in'] = 'Запомнить меня!';
$Definition['Keep User Content'] = 'Оставить контент пользователя';

$Definition['Label'] = 'Ярлык';
$Definition['Last Active'] = 'Был на сайте';
$Definition['Last IP'] = 'Последний IP';
$Definition['lasts %s'] = 'срок %s';
$Definition['Last Updated'] = 'Последнее изменение';
$Definition['Latest %1$s'] = 'Последний %1$s';
$Definition['Latest Post'] = 'Последняя публикация';
$Definition['Leaders'] = 'Лидеры';
$Definition['Learn more about %s'] = 'Узнать больше о %s';
$Definition['Leave %s'] = 'Покинуть %s';
$Definition['Leave a Comment'] = 'Оставить комментарий';
$Definition['Leave a comment'] = 'Комментировать';
$Definition['Leave a redirect link.'] = 'Оставить редирект. ';
$Definition['Leave blank unless connecting to an existing account.'] = 'Если вы не подключаетесь к существующему аккаунту, оставьте поле пустым.';
$Definition['Leave Comments'] = 'Комментировать';
$Definition['Leave Conversation'] = 'Покинуть диалог';
$Definition['Leave Group'] = 'Покинуть группу';
$Definition['Leaving'] = 'Выход';
$Definition['Length'] = 'Длина';
$Definition['Level %s'] = 'Уровень %s';
$Definition['Like'] = 'Лайк';
$Definition['Link to content:'] = 'Ссылка на контент:';
$Definition['Locale'] = 'Локаль';
$Definition['Log'] = 'Журнал';
$Definition['log'] = 'журнал';
$Definition['Login with Facebook'] = 'Войти с Facebook';
$Definition['LOL'] = 'ЛОЛ';

$Definition['Major'] = 'Значительная';
$Definition['Make %s'] = 'Выдать роль: %s';
$Definition['Make Leader'] = 'В лидеры';
$Definition['Make me invisible? (Will not show you on the list)'] = 'Сделатьcя невидимым? (Не выдавать присутствие на сайте).';
$Definition['Make this poll anonymous (user votes are not made public).'] = 'Сделать этот опрос анонимный (голоса пользователей не публикуются).';
$Definition['Male'] = 'Мужской';
$Definition['Manage Members'] = 'Управление участниками';
$Definition['Mark All Viewed'] = 'Отметить всё как прочитанное';
$Definition['Mark as Troll'] = 'Это тролль.';
$Definition['Mark Category Viewed'] = 'Отметить раздел как просмотренный';
$Definition['Marking as spam cannot be undone.'] = 'Сообщения, помечаемые как спам, будут безвозвратно удалены. Удаление является хорошим способом содержать форум в чистоте.';
$Definition['Mark Read'] = '<span title="Отметить посты в этой категории прочитанными">Прочитано</span>';
$Definition['Maybe'] = '
        Возможно

';
$Definition['Maybe (%s)'] = 'Возможно (%s)';
$Definition['Media'] = 'Загрузка файлов';
$Definition['Member'] = 'Участник';
$Definition['Member Count'] = 'Пользователи';
$Definition['Members'] = 'Пользователи';
$Definition['Merge'] = 'Объединение';
$Definition['Merge Discussions'] = 'Объединить дискуссии';
$Definition['Message'] = 'Сообщение';
$Definition['message'] = 'сообщение';
$Definition['Messages'] = 'Сообщения';
$Definition['messages'] = 'сообщения';
$Definition['Message to User'] = 'Сообщение пользователю';
$Definition['Minor'] = 'Незначительная';
$Definition['minutes'] = 'мин.';
$Definition['Moderate'] = 'Модерирование';
$Definition['Moderation'] = 'Модерирование';
$Definition['Moderation Queue'] = 'Очередь модерации';
$Definition['Moderator'] = 'Модератор';
$Definition['Moderator Activity'] = 'Активность модераторов';
$Definition['Moderators'] = 'Модераторы';
$Definition['moderators'] = 'модераторы';
$Definition['month.letter.1'] = 'Ж';
$Definition['month.letter.2'] = 'Ф';
$Definition['month.letter.3'] = 'М';
$Definition['month.letter.4'] = 'А';
$Definition['month.letter.5'] = 'М';
$Definition['month.letter.6'] = 'Ж';
$Definition['month.letter.7'] = 'Ж';
$Definition['month.letter.8'] = 'А';
$Definition['month.letter.9'] = 'С';
$Definition['month.letter.10'] = 'О';
$Definition['month.letter.11'] = 'Н';
$Definition['month.letter.12'] = 'Д';
$Definition['month.long.1'] = 'Январь';
$Definition['month.long.2'] = 'Февраль';
$Definition['month.long.3'] = 'Март';
$Definition['month.long.4'] = 'Апрель';
$Definition['month.long.5'] = 'Май';
$Definition['month.long.6'] = 'Июнь';
$Definition['month.long.7'] = 'Июль';
$Definition['month.long.8'] = 'Август';
$Definition['month.long.9'] = 'Сентябрь';
$Definition['month.long.10'] = 'Октябрь';
$Definition['month.long.11'] = 'Ноябрь';
$Definition['month.long.12'] = 'Декабрь';
$Definition['month.short.1'] = 'Янв';
$Definition['month.short.2'] = 'Фев';
$Definition['month.short.3'] = 'Мар';
$Definition['month.short.4'] = 'Апр';
$Definition['month.short.5'] = 'Май';
$Definition['month.short.6'] = 'Июнь';
$Definition['month.short.7'] = 'Июль';
$Definition['month.short.8'] = 'Авг';
$Definition['month.short.9'] = 'Сент';
$Definition['month.short.10'] = 'Окт';
$Definition['month.short.11'] = 'Нояб';
$Definition['month.short.12'] = 'Дек';
$Definition['months'] = 'месяцев';
$Definition['More'] = 'Ещё';
$Definition['More About %s'] = 'Подробнее о %s';
$Definition['More Comments'] = 'Больше комментариев';
$Definition['More Discussions'] = 'Еще дискуссии';
$Definition['More Information'] = 'Больше информации';
$Definition['More Results'] = 'Больше результатов';
$Definition['More…'] = 'Еще...';
$Definition['Most Recent'] = 'Самый свежий';
$Definition['Most recent:'] = 'Самый свежий:';
$Definition['Most recent: %1$s by %2$s'] = 'Последний: %1$s от %2$s';
$Definition['Most recent by %1$s'] = 'Последний от %1$s';
$Definition['Most Recent Comment'] = 'Последний комментарий';
$Definition['Most recent discussion'] = 'Последняя дискуссия';
$Definition['Move'] = 'Переместить';
$Definition['Mute'] = 'Отключить уведомления';
$Definition['MyBadgesModuleTitle'] = 'Мои значки';
$Definition['My Bookmarks'] = 'Закладки';
$Definition['My Discussions'] = 'Мои дискуссии';
$Definition['My Drafts'] = 'Черновики';
$Definition['My Forums'] = 'Мои форумы';
$Definition['My Groups'] = 'Мои группы';
$Definition['My Preferences'] = 'Мои настройки';
$Definition['My Signature'] = 'Моя подпись';

$Definition['n/a'] = 'Нет данных';
$Definition['Name'] = 'Имя';
$Definition['Name Dropper'] = 'Неймдроппер';
$Definition['Name of the Event'] = '
        Название мероприятия

';
$Definition['Name the Group'] = 'Название группы';
$Definition['Name Unavailable'] = 'Имя недоступно';
$Definition['new'] = 'новая';
$Definition['New %s'] = 'Новый %s';
$Definition['New Announcement'] = '
        Новое объявление

';
$Definition['New Conversation'] = 'Новое письмо';
$Definition['New Discussion'] = 'Создать дискуссию';
$Definition['new discussion'] = 'новая';
$Definition['New Event'] = 'Новое событие';
$Definition['New Group'] = 'Новая группа';
$Definition['New Groups'] = 'Новые группы';
$Definition['New Icon'] = 'Новая иконка';
$Definition['New Idea'] = 'Новая идея';
$Definition['New Message'] = 'Написать письмо';
$Definition['New Password'] = 'Новый пароль';
$Definition['New Poll'] = 'Новый опрос';
$Definition['Next'] = 'Далее';
$Definition['Ninth Anniversary'] = 'Девятая годовщина';
$Definition['No'] = 'Нет';
$Definition['NoBadgesEarned'] = 'Совсем скоро&hellip;';
$Definition['No badges yet.'] = 'Нет значков';
$Definition['Nobody has confirmed their attendance yet.'] = '
        Еще никто не подтвердил свое участие.

';
$Definition['Nobody has declined the invitation so far.'] = '
        Пока еще никто не отклонил приглашение.

';
$Definition['Nobody is on the fence right now.'] = '
        Пока никого здесь нет.

';
$Definition['No default roles.'] = 'Группа по умолчанию настроена неправильно. Кликните сюда: %s, чтобы исправить это.';
$Definition['No discussions were found.'] = 'Не найдено ни одной дискуссии.';
$Definition['No items tagged with %s.'] = 'Ничего не отмечено тэгом %s.';
$Definition['None'] = 'Нет';
$Definition['NoPermissionToDeleteDiscussions'] = 'У вас нет разрешения удалить %1$s из выбранных обсуждений.';
$Definition['No results for \'%s\''] = 'Нет результатов для \'%s\'';
$Definition['No Roles'] = 'Нет ролей';
$Definition['Not Attending (%s)'] = 'Не посетят (%s)';
$Definition['Not Authorized (401)'] = 'Не авторизированы (401)';
$Definition['Notes'] = 'Примечание';
$Definition['Not Found (404)'] = 'Не найдено (ошибка 404)';
$Definition['Notice'] = 'Извещение';
$Definition['Notification'] = 'Уведомление';
$Definition['Notification Preferences'] = 'Настройки уведомлений';
$Definition['Notifications'] = 'Уведомления';
$Definition['Notifictions'] = 'Уведомления';
$Definition['Notify'] = 'Уведомлять';
$Definition['Notify me of private messages.'] = 'Уведомлять о новых личных сообщениях.';
$Definition['Notify me when a badge is requested.'] = 'Уведомлять, когда запрашивается значок.';
$Definition['Notify me when a comment is flagged.'] = 'Уведомлять, когда о комментарии сообщили модератору.';
$Definition['Notify me when I am added to private conversations.'] = 'Уведомлять, когда меня приглашают к приватному диалогу.';
$Definition['Notify me when my ideas\' statuses change.'] = 'Сообщать мне об изменениях статуса моих идей.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Уведомить меня, когда кто-то комментирует обсуждения, в которых я участвую.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Уведомлять о комментариях в дискуссиях из моих закладок.';
$Definition['Notify me when people comment on my discussions.'] = 'Уведомлять о новых комментариях в моих дискуссиях.';
$Definition['Notify me when people mention me.'] = 'Уведомлять, когда люди упоминают меня.';
$Definition['Notify me when people mention me in comments.'] = 'Уведомлять, когда меня упоминают в комментариях.';
$Definition['Notify me when people reply to my wall comments.'] = 'Уведомлять об ответах на моей стене.';
$Definition['Notify me when people write on my wall.'] = 'Уведомлять о новых надписях на моей стене.';
$Definition['Notify me when there is event activity.'] = 'Уведомить меня об активности в Событии.';
$Definition['Notify me when there is group activity.'] = 'Уведомить меня об активности Группы.';
$Definition['Notify me when the status changes on an idea I\'ve voted on.'] = 'Сообщать мне об изменении статуса идеи, за которую я голосовал.';
$Definition['Not much happening here, yet.'] = 'Зафиксированных событий не обнаружено.';
$Definition['Not Verified'] = 'Не подтверждён';

$Definition[' now.'] = 'сейчас';

$Definition['Null Date'] = '-';

$Definition['of'] = 'из';
$Definition['Off'] = 'Выкл';
$Definition['Off Topic'] = 'Оффтоп';
$Definition['OK'] = 'ОК';
$Definition['Okay'] = 'ОК';
$Definition['OldPassword'] = 'Старый пароль';
$Definition['Old Password'] = 'Старый пароль';
$Definition['On'] = 'На';
$Definition['on'] = 'на';
$Definition['Online Preferences'] = 'Настройки конфиденциальности';
$Definition['Only show followed categories'] = 'Показать только те разделы, на которые я подписан.';
$Definition['Open'] = 'Открыть';
$Definition['OpenID Settings'] = 'Настройки OpenID';
$Definition['Optional'] = 'Опционально';
$Definition['Optional Description'] = 'Дополнительное описание';
$Definition['Options'] = 'Настройки';
$Definition['or'] = 'или';
$Definition['Ordered list'] = 'Упорядоченный список';
$Definition['Organize discussion categories'] = 'Сортировка разделов дискуссий';
$Definition['Organizer'] = '
        Организатор

';
$Definition['Organize your Categories'] = 'Сортировка ваших разделов';
$Definition['Original'] = 'Оригинал';
$Definition['Or you can...'] = 'Или...';
$Definition['Other'] = 'Другое';
$Definition['Other Records'] = 'Другие записи';
$Definition['Outdent'] = 'Выступ';
$Definition['Owner'] = 'Владелец';

$Definition['Page'] = 'Страница';
$Definition['page'] = 'страница';
$Definition['Page %1$s of %2$s'] = 'Страница %1$s из %2$s';
$Definition['Page %s'] = 'Страница %s';
$Definition['PageDetailsMessage'] = '%1$s для %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s для %2$s из %3$s';
$Definition['Page Not Found'] = 'Страница не найдена';
$Definition['Participated'] = 'Темы со мной';
$Definition['Participated Discussions'] = 'Дискуссии с моим участием';
$Definition['ParticipatedHomepageTitle'] = 'Дискуссии с участием';
$Definition['Password'] = 'Пароль';
$Definition['Password Contains Username'] = 'Содержит имя пользователя';
$Definition['Password Good'] = 'Хороший';
$Definition['Password Ok'] = 'Ок';
$Definition['PasswordRequest'] = 'Hallo %1$s,

Кто-то просит сбросить %2$s пароль. Если это были вы, пройдите по ссылке ниже:
%3$s

В противном случае, просто проигнорируйте это письмо

Всего хорошего!';
$Definition['Passwords don\'t match'] = 'Пароль не подходит';
$Definition['Password Strong'] = 'Сильный';
$Definition['Password Too Short'] = 'Слишком короткий';
$Definition['Password Very Weak'] = 'Очень слабый';
$Definition['Password Weak'] = 'Слабый';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Вставить URL изображения для быстрого прикрепления.';
$Definition['Pending'] = 'В ожидании';
$Definition['Permalink'] = '#';
$Definition['permalink'] = 'ссылка';
$Definition['Permanent (301)'] = 'Перемещено (301)';
$Definition['PermissionErrorMessage'] = 'У вас недостаточно прав для просмотра этой страницы.';
$Definition['PermissionErrorTitle'] = 'Проблема с доступом';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Вы должны иметь права модератора, чтобы сделать это.';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Вы должны иметь права администратора, чтобы сделать это.';
$Definition['PermissionRequired.Javascript'] = 'Вам нужно включить javascript, чтобы сделать это.';
$Definition['Photogenic'] = 'Фотогеничный';
$Definition['Picture'] = 'Изображение';
$Definition['Pin'] = 'Прикрепить';
$Definition['Pinned'] = 'Закрепленные';
$Definition['Play the sound again'] = 'Проиграть звук снова';
$Definition['Please join my group.'] = 'Пожалуйста, присоединяйтесь к моей <a href="{Url,html}">группе</a>.
';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Пожалуйста, подождите пока вы будете перенаправленны. Если в течении 10 секун ничего не произошло, кликните <a href="%s">тут</a>.';
$Definition['Points'] = 'Очки';
$Definition['Poll'] = 'Голосование';
$Definition['poll'] = 'Голосование';
$Definition['Poll Options'] = 'Опции опроса';
$Definition['Poll Question'] = 'Предмет опроса';
$Definition['Polls'] = 'Опросы';
$Definition['polls'] = 'Опросы';
$Definition['Popular'] = 'Популярные';
$Definition['Popular Discussions'] = 'Популярные дискуссии';
$Definition['Popular Groups'] = 'Популярные группы';
$Definition['Popular Tags'] = 'Популярные тэги';
$Definition['Popup'] = 'Всплывающее окно';
$Definition['Position'] = 'Позиция';
$Definition['Post'] = 'Опубликовать';
$Definition['post'] = 'публикация';
$Definition['Post Comment'] = 'Опубликовать комментарий';
$Definition['Post Discussion'] = 'Опубликовать дискуссию';
$Definition['Post edited by %1$s at %2$s'] = 'Публикацию отредактировал %1$s в %2$s';
$Definition['Posts'] = 'Публикации';
$Definition['Posts.Plural: %s'] = 'Публикаций: %s';
$Definition['Posts.Singular: %s'] = 'Публикаций: %s';
$Definition['Posts: %s'] = 'Публикаций: %s';
$Definition['Post this anonymously'] = 'Опубликовать это анонимно';
$Definition['Powered by %s'] = 'Работает на %s';
$Definition['Powered by Vanilla'] = 'Создано Vanilla';
$Definition['PreferenceBadgeEmail'] = 'Уведомлять, когда я получаю значок.';
$Definition['PreferenceBadgePopup'] = 'Уведомлять, когда я получаю значок.';
$Definition['Preferences'] = 'Настройки';
$Definition['Preview'] = 'Предпросмотр';
$Definition['Previous'] = 'Назад';
$Definition['Privacy'] = 'Конфиденциальность';
$Definition['Privacy Settings'] = 'Настройки приватности';
$Definition['Private'] = 'Личное';
$Definition['Private group.'] = 'Любой может видеть группу, но только участники могут видеть ее содержимое. Люди должны подать заявку или быть приглашенными, чтобы присоединиться.';
$Definition['Private Note for Moderators'] = 'Скрытая заметка для модератора';
$Definition['Problem with credentials.'] = 'Проблема с учетными данными.';
$Definition['Proceed'] = 'Продолжить';
$Definition['Profile'] = 'Профиль';
$Definition['Profile Fields'] = 'Поля профиля';
$Definition['Profile  Fields'] = 'Поля профиля';
$Definition['ProfileFieldsCustomDescription'] = 'Эти поля могут быть использованы для вывода произвольной информации в профиле. Вы можете указать такие данные, как "Семейное положение", "Skype", или "Любимый динозавр". Будьте изобретательны!';
$Definition['Profile Page'] = 'Страница профиля';
$Definition['Profile Picture'] = 'Личная картинка';
$Definition['Profiles'] = 'Профили';
$Definition['Progress on an idea you voted on!'] = 'У идеи, за которую вы голосовали, есть прогресс!';
$Definition['Promote'] = 'Рекламировать';
$Definition['Public'] = 'Публичный';
$Definition['Public group.'] = 'Любой может видеть группу и ее содержимое. Любой может присоединиться.';

$Definition['Q&A'] = 'ВиО';
$Definition['Q&A Accepted'] = 'Отвечено ✓';
$Definition['Q&A Answered'] = 'Отвечено';
$Definition['Q&A Options'] = 'Настройки Вопросов и Ответов';
$Definition['Q&A Question'] = 'Вопрос';
$Definition['QnA Accepted Answer'] = 'Ответ ✓';
$Definition['QnA Rejected Answer'] = 'Отклоненный ответ';
$Definition['Question'] = 'Вопрос';
$Definition['question'] = 'вопрос';
$Definition['Questions'] = 'Вопросы';
$Definition['questions'] = 'вопросы';
$Definition['Question Title'] = 'Заголовок вопроса';
$Definition['Quote'] = 'Цитата';
$Definition['Quote Folding'] = 'Встраивание цитат';
$Definition['Quote on'] = 'на';
$Definition['Quote Settings'] = 'Настройки цитат';
$Definition['Quote wrote'] = 'написал';

$Definition['Rank'] = 'Рейтинг';
$Definition['Ranks.ActivityFormat'] = '{ActivityUserID,user} {ActivityUserID,plural,повышен,повышены} до ранга {Data.Name,plaintext}.';
$Definition['Ranks.NotificationFormat'] = 'Поздравляем! Вас произвели в ранг {Data.Name,plaintext}.';
$Definition['Re: %s'] = 'Ответ: %s';
$Definition['React'] = 'Отреагировать';
$Definition['Reaction'] = 'Реакция';
$Definition['Reactions'] = 'Реакции';
$Definition['Read the full story here'] = 'Прочтите полный текст здесь';
$Definition['Real Name'] = 'Настоящее имя';
$Definition['Reason'] = 'Причина';
$Definition['Reason (optional)'] = 'Причина (опционально)';
$Definition['reCAPTCHA has not been set up by the site administrator in registration settings. This is required to register.'] = ' reCAPTCHA не была установлена в настройках регистрации администратором сайта. Это необходимо для регистрации.';
$Definition['Recent'] = 'Последнее';
$Definition['Recent Activity'] = 'Последняя активность';
$Definition['Recent Admin Activity'] = 'Последние действия администратора';
$Definition['Recent Discussions'] = 'Свежие дискуссии';
$Definition['Recent Events'] = 'Последние события';
$Definition['recently'] = 'свежее';
$Definition['Recent Moderator Activity'] = 'Последние действия модератора';
$Definition['Recent Tutorials'] = 'Свежие руководства';
$Definition['Recipients'] = 'Получатели';
$Definition['RecipientUserID'] = 'ID получателя';
$Definition['Redirecting...'] = 'Перенаправление...';
$Definition['Refetch Page'] = 'Перезагрузить страницу';
$Definition['Register'] = 'Регистрация';
$Definition['Register IP'] = 'Исходный IP';
$Definition['Register with %s'] = 'Регистрация';
$Definition['Registration  Fields'] = 'Поля регистрации';
$Definition['Registration URL'] = 'Ссылка для регистрации';
$Definition['Reject'] = 'Отклонить';
$Definition['Reject this answer.'] = 'Этот ответ не подходит.';
$Definition['Remember me'] = 'Запомнить меня';
$Definition['Remember me on this computer'] = 'Запомнить на этом компьютере';
$Definition['Remote Configuration'] = 'Удаленная настройка';
$Definition['Remove'] = 'Удалить';
$Definition['Remove %s'] = 'Удалить %s';
$Definition['Removed by'] = 'Удалено';
$Definition['Remove file'] = 'Удалить файл';
$Definition['Remove from %s'] = 'Удалить из %s';
$Definition['Remove Icon'] = 'Удалить иконку';
$Definition['Remove Invitation'] = 'Удалить приглашение';
$Definition['Remove My Picture'] = 'Удалить мое изображение';
$Definition['Remove Picture'] = 'Удалить изображение';
$Definition['Remove Warning'] = 'Удалить предупреждение';
$Definition['Rename Forum'] = 'Переименовать форум';
$Definition['Reopen'] = 'Открыть';
$Definition['Replies'] = 'Ответов';
$Definition['Reply'] = 'Ответить';
$Definition['ReplyOnly'] = 'Для подписки вы можете ответить непосредственно на это письмо. Отправлено от {/,exurl}.';
$Definition['ReplyOrFollow'] = 'Ответьте непосредственно на это письмо или проследуйте по ссылке ниже, чтобы проверить:';
$Definition['Report'] = 'Репорт';
$Definition['Report %s'] = 'Репорт: %s';
$Definition['Reported'] = 'Сообщается';
$Definition['Reported by: '] = 'Упрекнул: ';
$Definition['Reported Posts'] = 'Репорты';
$Definition['Report Notes'] = 'Примечание';
$Definition['Report Reason'] = 'Причина';
$Definition['Reputation'] = 'Репутация';
$Definition['Request a new password'] = 'Выслать новый пароль';
$Definition['Request a new password →'] = 'Запросить новый пароль →';
$Definition['Request another password reset.'] = 'Запросите ещё один сброс пароля.';
$Definition['Reset Password'] = 'Сбросить пароль';
$Definition['Reset Your Password'] = 'Сброс пароля';
$Definition['Restore'] = 'Восстановить';
$Definition['Restored'] = 'Восстановлено';
$Definition['Return to %s'] = 'Назад к %s';
$Definition['reverse'] = 'отменить';
$Definition['Revoke'] = 'Аннулировать';
$Definition['Revoked'] = 'Отменено';
$Definition['Revoked badge.'] = 'Аннулировать знак';
$Definition['role'] = 'группа';
$Definition['RoleID'] = 'группа';
$Definition['Roles'] = 'Группы';
$Definition['roles'] = 'роли';
$Definition['RSS Feed'] = 'RSS-лента';
$Definition['RSVP'] = 'Ответить';

$Definition['Save'] = 'Сохранить';
$Definition['Save Comment'] = 'Сохранить исправления';
$Definition['Saved'] = 'Сохранено.';
$Definition['Save Draft'] = 'В черновик';
$Definition['Save Poll'] = 'Сохранить опрос';
$Definition['Save Preferences'] = 'Сохранить настройки';
$Definition['Save your password'] = 'Сохранить пароль';
$Definition['Search'] = 'Поиск';
$Definition['Search %s'] = 'Поиск %s';
$Definition['search archived'] = 'поиск в архиве';
$Definition['SearchBoxPlaceHolder'] = 'Поиск';
$Definition['Search for a tag.'] = 'Поиск тэга или его части.';
$Definition['Search groups members'] = 'Поиск по участникам';
$Definition['Search results for \'%s\''] = 'Результаты поиска по \'%s\'';
$Definition['search subcategories'] = 'поиск подразделов';
$Definition['Second Anniversary'] = 'Вторая годовщина';
$Definition['Secret'] = 'Секрет';
$Definition['Sections'] = 'Секции';
$Definition['Security Check'] = 'Проверка безопасности';
$Definition['Select a %s'] = 'Выбрать %s';
$Definition['Select a category...'] = 'Выбрать категорию...';
$Definition['Select a community.'] = 'Выберите сообщество.';
$Definition['Select an image on your computer (2mb max)'] = 'Выберите изображение на вашем компьютере (максимум 2Мб).';
$Definition['Select one of the following avatars:'] = 'Выберите один из следующих аватаров:';
$Definition['Send'] = 'Отправить';
$Definition['Send a New Message'] = 'Отправить новое сообщение';
$Definition['Send Message'] = 'Отправить сообщение';
$Definition['Send Report'] = 'Отправить отчет';
$Definition['Send report'] = 'Отправить отчет';
$Definition['sep and'] = 'и';
$Definition['Set a New Warning Level'] = 'Установить новый уровень предупреждений';
$Definition['Set A Password'] = 'Установить пароль';
$Definition['Setting'] = 'Настройка';
$Definition['Settings'] = 'Настройки';
$Definition['Seventh Anniversary'] = 'Седьмая годовщина';
$Definition['Severity'] = 'Степень';
$Definition['Share'] = 'Поделиться';
$Definition['Shared Accounts'] = 'Общие учетные записи';
$Definition['she'] = 'она';
$Definition['Shown only on mobile'] = 'Показывать только на мобильных устройствах';
$Definition['Show previous quotes'] = '&raquo; показать предыдущие ценовые предложения';
$Definition['Show unfollowed categories'] = 'Показать неотслеживаемые разделы';
$Definition['Sign-In URL'] = 'URL входа';
$Definition['Sign-Out URL'] = 'URL выхода';
$Definition['Signature'] = 'Подпись';
$Definition['Signature Code'] = 'Подпись';
$Definition['Signature hidden.'] = 'Подпись скрыта';
$Definition['Signature invalid.'] = 'Подпись недействительна.';
$Definition['Signatures'] = 'Подписи';
$Definition['Signatures can be up to {maxLength} characters long.'] = 'Максимальное количество символов в подписи: {maxLength}.';
$Definition['Signature Settings'] = 'Настройки подписи';
$Definition['SignIn'] = 'Вход';
$Definition['Sign In'] = 'Войти';
$Definition['SigningOut'] = 'Подождите пока система завершит вашу сессию.';
$Definition['Sign In Now'] = 'Войти сейчас';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Войдите</a> или <a href="{RegisterUrl,html}">Зарегистрируйтесь</a> чтобы комментировать.';
$Definition['Sign in to vote!'] = 'Войдите, чтобы голосовать!';
$Definition['Sign In with %s'] = 'Войти через %s';
$Definition['Sign In with Disqus'] = 'Войти через Disqus';
$Definition['Sign In with Facebook'] = 'Войти через Facebook';
$Definition['Sign In with Google'] = 'Войти с помощью Google';
$Definition['Sign In with OpenID'] = 'Войти с помощью OpenID';
$Definition['Sign In with Twitter'] = 'Войти с помощью Twitter';
$Definition['Sign Out'] = 'Выйти';
$Definition['sign out'] = 'Выйти';
$Definition['Sign Up'] = 'Регистрация';
$Definition['Sink'] = 'Опускать';
$Definition['Sink this discussion'] = 'Не поднимать в топ дискуссию';
$Definition['Site'] = 'Сайт';
$Definition['Sitemap Settings'] = 'Настройки карты сайта';
$Definition['Sites'] = 'Сайты';
$Definition['Sixth Anniversary'] = 'Шестая годовщина';
$Definition['Social'] = 'Социальное';
$Definition['somebody'] = 'кто-то';
$Definition['Some Code'] = 'А сюда идет перевод.';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Кто-то ответил на ваш вопрос. Вы должны принять или отклонить ответ.';
$Definition['sorted by'] = 'отсортировано';
$Definition['Source'] = 'Источник';
$Definition['Source:'] = 'Исходный:';
$Definition['Source Code'] = 'Код';
$Definition['Spam'] = 'Спам';
$Definition['Spam Queue'] = 'Очередь спама';
$Definition['Split'] = 'Разделить';
$Definition['Split Comments'] = 'Разделить комментарии';
$Definition['Spoiler'] = 'Спойлер';
$Definition['Spoof User'] = 'Эмулировать этот аккаунт';
$Definition['Start'] = 'Старт';
$Definition['Start a Group'] = 'Создать группу';
$Definition['Start a New Conversation'] = 'Новое сообщение (3)';
$Definition['Start a New Discussion'] = 'Создать дискуссию';
$Definition['Start Conversation'] = 'Инициировать диалог';
$Definition['Started By'] = 'Начал';
$Definition['Started by'] = '
        Автор

';
$Definition['Started by %1$s'] = 'Автор: %1$s';
$Definition['Start your First Discussion'] = 'Создайте вашу первую дискуссию';
$Definition['Status'] = 'Статус';
$Definition['status'] = 'статус';
$Definition['Status: %s'] = 'Статус: %s';
$Definition['Statuses'] = 'Статусы';
$Definition['statuses'] = 'статусы';
$Definition['Stop following'] = 'Отписаться';
$Definition['Strikethrough'] = 'Перечеркивание';
$Definition['Strip images out of signatures'] = 'Удалять изображения из подписей';
$Definition['Strip images out of signatures?'] = 'Удалить изображения из подписей?';
$Definition['Subject'] = 'Тема';
$Definition['Subscriber'] = 'Подписчик';
$Definition['Success'] = 'Успешно';
$Definition['Suggested Value'] = 'Предлагаемое значение';
$Definition['System'] = 'Система';

$Definition['Tagged'] = 'Тэги темы';
$Definition['Tagged with '] = 'Отмечено тэгами: ';
$Definition['Tagged with "%s"'] = 'С тегом "%s"';
$Definition['Tagging'] = 'Тэгирование';
$Definition['TagHint'] = '
        Введите текст здесь...

';
$Definition['Tag Name'] = 'Имя тэга';
$Definition['Tags'] = 'Тэги';
$Definition['tags'] = 'тэги';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Тэги это ключевые слова, которые пользователи назначают дискуссиям, для удобства нахождения и объединения похожих дискуссий.';
$Definition['Take Action'] = 'Принять меры';
$Definition['Take Action:'] = 'Выберите действие:';
$Definition['Target'] = 'Расположение';
$Definition['Tell the user why you\'re warning them'] = 'Скажите пользователю, почему вы его предупреждаете';
$Definition['Tell us why you want to join!'] = 'Расскажите, почему вы решили присоединиться к нам!';
$Definition['Tenth Anniversary'] = 'Десятая годовщина';
$Definition['Terms'] = 'Условия';
$Definition['TermsOfService'] = 'Условия использования';
$Definition['Terms of Service'] = 'Условия использования';
$Definition['TermsOfServiceText'] = '<p>1. Модерация форума. На форуме отсутствует предварительная фильтрация сообщений. Все сообщения пользователей прочитываются модератором форума. В случае нарушения пользователем правил форума, пользователь получает предупреждение или отлучается от предоставленных ранее прав. Администрация форума не несёт ответственности за информацию, размещённую пользователями.<br>
2. Незнание правил. На форуме запрещена публикация информации, противоречащей данным правилам. Незнание правил не освобождает от ответственности.
В частности, запрещена публикация информации, которая:
а) заведомо является ложью и/или клеветой;
б) неточна, оскорбительна, вульгарна, внушает ненависть, содержит угрозы, непристойности, грубость;
в) сексуально ориентирована, вторгается в личную жизнь других людей;
г) нарушает законы.
Система записывает IP-адреса пользователей, и Администрация форума сохраняет за собой право раскрывать их в случае жалоб или юридических действий, ставших следствием публикации сообщения на этом сайте. Также Администрация имеет право удалить любую информацию на этом сайте и отменить регистрацию любого пользователя без объяснения причин. Чтобы пользоваться форумом, вам должно быть хотя бы 13 лет.<br>
3. Публикация информации третьими лицами. Ответственность за информацию, размещённую от лица пользователя, несёт только сам пользователь. Администрация рекомендуeт не допускать использования ваших учётных данных третьими лицами.<br>
4. Аватара. В качестве аватары разрешается использовать любое изображение, не содержащее кровавых сцен, сцен насилия, порнографии. Запрещается использовать аватары, уже используемые другими участниками форума.<br>
5. Реклама. На форуме пользователям запрещено заниматься рекламой, в том числе размещать частные объявления.<br>
6. Новые темы. Приветствуется создание интересных тем.<br>
7. Сознательность. Поощряется своевременное оповещение Администрации о нарушении правил форума.</p>';
$Definition['Test'] = 'Тест';
$Definition['Testing'] = 'Тестирование';
$Definition['Text'] = 'Текст';
$Definition['Text  Max  Length'] = 'Текст  Макс.  Длина';
$Definition['Thank You!'] = 'Спасибо!';
$Definition['The %s has been deleted.'] = '%s был удален.';
$Definition['The %s has been flagged for moderation.'] = '%s помечено для проверки модератором.';
$Definition['The %s you were looking for could not be found.'] = 'Запрошенный элемент %s не может быть найден.';
$Definition['the category'] = 'раздел';
$Definition['The connection data has not been verified.'] = 'Данные соединения не были проверены.';
$Definition['The content you were looking for has been deleted.'] = 'Контент, который вы искали, был удален.';
$Definition['The conversation has been cleared.'] = 'Диалог был очищен.';
$Definition['The CSRF token is invalid.'] = 'CSRF токен некорректен.';
$Definition['The email you entered is in use by another member.'] = 'Этот адрес электронной почты используется другим участником.';
$Definition['The email you have entered is already related to an existing account.'] = 'Этот Email уже привязан к существующему акаунту.';
$Definition['The file failed to upload.'] = 'Невозможно загрузить файл.';
$Definition['their'] = 'их';
$Definition['The name you entered is already in use by another member.'] = 'Этот имя пользователя уже занято, придумайте другой.';
$Definition['The page you were looking for could not be found.'] = 'Страница, которую вы ищете, не существует.';
$Definition['The quote had to be converted from %s to %s.'] = 'Цитата должны была быть преобразована из %s в %s. Некоторое форматирование могло быть потеряно.';
$Definition['There\'s already a %s with the name %s.'] = 'Уже существует %1$s с именем %2$s.';
$Definition['There aren\'t any groups yet.'] = 'Еще нет групп.';
$Definition['There are no tags in the system yet.'] = 'В системе ещё нет ни одного тэга.';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'Код проверки введен не верно. Если вам не понятны символы на картинке, нажмите пиктограмму "две стрелки по кругу", чтобы загрузить другие';
$Definition['The reCAPTCHA was not completed correctly. Please try again.'] = ' reCAPTCHA была выполнена некорректно. Пожалуйста, попробуйте еще раз.';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Уже существует учетная запись с таким же именем пользователя (%1$s) или такой же почтой (%2$s). Вы можете создать новую учетную запись или ввести учетные данные уже существующей учетной записи на форуме.';
$Definition['The response was not in the correct format.'] = 'Ответ был в неправильном формате.';
$Definition['There was an error connecting to Disqus'] = 'Произошла ошибка при подключении к Disqus';
$Definition['There was an error connecting to Facebook'] = 'Произошла ошибка при подключении к Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Произошла ошибка при загрузке файла. Скорее всего файл слишком большой.';
$Definition['These tags are reserved and cannot be used: %s'] = 'Эти метки заняты и не могут быть использованы: %s';
$Definition['The site is currently undergoing maintenance.'] = 'Сайт в настоящее время проходит техническое обслуживание.';
$Definition['The status for "%s" has changed to %s.'] = 'Статус "%s" сменился на %s.';
$Definition['The uploaded file was too big (max %s).'] = 'Загруженный файл был слишком большой (максимум %s).';
$Definition['The user has already been warned for this %s.'] = 'Пользователь уже предупрежден об этом %s.';
$Definition['The user isn\'t banned.'] = 'Пользователь не забанен или забанен посредством другой функции.';
$Definition['they'] = 'они';
$Definition['Third Anniversary'] = 'Трехлетие';
$Definition['This answer was %s.'] = 'Этот ответ был %s';
$Definition['This answer was Accepted.'] = 'Этот ответ подошёл.';
$Definition['This discussion has been closed.'] = 'Дискуссия закрыта.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Эта дискуссия была связана с неопознанным внешним источником.';
$Definition['This discussion was created from comments split from: %s.'] = 'Эта дискуссия создана из комментариев, извлеченных из: %s.';
$Definition['This discussion was merged into %s'] = 'Эта дискусси была объединена с %s';
$Definition['This image has been inserted into the body of text.'] = 'Это изображение было вставлено в текст.';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Изображение было уменьшено. Нажмите для увеличения.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Это приватный опрос: никто не будет видеть что вы голосовали.';
$Definition['This is a public poll: others will see what you voted for.'] = 'Это общественный опрос: другие будут видеть что вы голосовали.';
$Definition['This is a system account and does not represent a real person.'] = 'Это технический пользователь';
$Definition['This Month\'s Leaders'] = 'Лидеры текущего месяца';
$Definition['This question\'s answer has been accepted.'] = 'Ответ на этот вопрос был принят.';
$Definition['This user has been verified as a non-spammer.'] = 'Этот пользователь не спамер';
$Definition['This user has not been verified as a non-spammer.'] = 'Пользователь не был проверен на спамерство.';
$Definition['This user has not commented yet.'] = 'Этот пользователь ничего не комментировал.';
$Definition['This user has not made any discussions yet.'] = 'Этот пользователь не создал ни одной дискуссии.';
$Definition['This user is also banned for other reasons and may stay banned.'] = 'Этот пользователь также забанен по другой причине и может остаться забаненым.';
$Definition['This user is verified as a non-spammer'] = 'Этот пользователь не спамер';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Желаете удалить предупреждение? Его срок истёк. ';
$Definition['This Week\'s Leaders'] = 'Лидеры текущей недели';
$Definition['Thumbnail'] = 'Миниатюра';
$Definition['Title'] = 'Заголовок';
$Definition['To'] = '
        На имя

';
$Definition['Toggle full page'] = 'Переключить оконный режим';
$Definition['Toggle HTML view'] = 'Переключить на просмотр HTML';
$Definition['Toggle lights'] = 'Световое переключение';
$Definition['Topic'] = 'Тема';
$Definition['Topics'] = 'Темы';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'Для того, чтобы послать другое письмо активации, кликните <a href="%s">здесь</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'Для использования системы reCAPTCHA вы должны получить API ключ на сайте %s';
$Definition['Transport error: %s'] = 'Произошла ошибка при обработке запроса <br /> сервер вернул следующее сообщение: %s';
$Definition['Troll'] = 'Троль';
$Definition['Try Again'] = 'Повторите';
$Definition['Turn ON'] = 'Включить';
$Definition['Twitter Settings'] = 'Настройки входа через Twitter';
$Definition['Type'] = 'Тип';
$Definition['Type the text:'] = 'Введите текст:';
$Definition['Type what you hear:'] = 'Введите, то что слышите:';

$Definition['Unable to send message, %s is ignoring you.'] = 'Невозможно послать сообщение, %s игнорирует вас.';
$Definition['Unannounce'] = 'Деанонсировать';
$Definition['Unanswered'] = 'Вопросы без ответа';
$Definition['Unanswered Questions'] = 'Вопросы без ответа';
$Definition['unavailable'] = 'недоступно';
$Definition['Unban'] = 'Реабилитировать';
$Definition['Unban User'] = 'Реабилитировать пользователя';
$Definition['Unbookmark'] = 'Убрать из закладок';
$Definition['Undefined discussion body.'] = 'Не определено тело дискуссии.';
$Definition['Undefined discussion subject.'] = 'Не указан предмет дискуссии.';
$Definition['Undefined foreign content'] = 'Неопознанный внешний контент';
$Definition['Undo Follow'] = 'Отписаться';
$Definition['Unfollow'] = 'Отписаться';
$Definition['Unhide'] = 'Показать';
$Definition['Unignore'] = 'Убрать из списка игнора';
$Definition['UniqueID'] = 'Уникальный ID';
$Definition['Unknown'] = 'Неизвестно';
$Definition['unknown'] = 'неизвестно';
$Definition['Unknown client: %s.'] = 'Неизвестный клиент: %s.';
$Definition['Unmute'] = 'Включить уведомления';
$Definition['Unordered list'] = 'Неупорядоченный список';
$Definition['Unpin'] = 'Снять отметку';
$Definition['Unread'] = 'Непрочитанно';
$Definition['Unread Discussions'] = 'Непрочитанные дискуссии';
$Definition['Unsink'] = 'Приподнять';
$Definition['Unspecified'] = 'Не определён';
$Definition['Upcoming Events'] = 'Предстоящие события';
$Definition['Update'] = 'Обновление';
$Definition['Updated badge'] = 'Обновленный значек';
$Definition['Upload'] = 'Загрузить';
$Definition['Uploading...'] = 'Загрузка...';
$Definition['Upload New Icon'] = 'Загрузить новую иконку';
$Definition['Upload New Picture'] = 'Загрузить новую фотографию';
$Definition['Url'] = 'URL';
$Definition['UrlCode'] = 'Код ссылки';
$Definition['Use My Current Password'] = 'Использовать мой текущий пароль';
$Definition['User'] = 'Пользователь';
$Definition['User "%s" does not exist.'] = 'Пользователь "%s" не существует.';
$Definition['Username'] = 'Имя пользователя';
$Definition['Username already exists.'] = 'Это имя пользователя уже существует';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Имя пользователя может содержать только буквы, цифры и знак подчеркивания.';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'Имена пользователей могут содержать только буквы, цифры и знаки подчеркивания и должны быть в диапазоне от 3 до 20 символов.';
$Definition['UsernameError'] = 'Имена пользователей могут содержать только буквы, цифры и знаки подчёркивания и должны быть в диапазоне от 3 до 20 символов.';
$Definition['Username or email'] = 'Имя пользователя или почта';
$Definition['User not found.'] = 'К сожалению, невозможно было найти ни одной учетной записи, связанной с Email/именем пользователя, который вы ввели.';
$Definition['Users'] = 'Пользователи';
$Definition['Users Count'] = 'Число пользователей';
$Definition['Use up to {maxImages,plural,%s image, %s images}.'] = 'Вы можете использовать до {maxImages,plural,%s изображения, %s изображений}.';

$Definition['ValidateBanned'] = '%s не доступно.';
$Definition['ValidateBoolean'] = '%s - неправильный ответ';
$Definition['ValidateConnection'] = 'При указанных параметрах не может быть установлено соеденение с базой данных. База данных отдает следующие ошибки: <code>%s</code>';
$Definition['ValidateDate'] = '%s - неправильная дата.';
$Definition['ValidateDecimal'] = '%s - неверная дробь.';
$Definition['ValidateEmail'] = '%s некорректный адрес почты.';
$Definition['ValidateEnum'] = '%s неправильно.';
$Definition['ValidateFormat'] = 'Вам запрещается вводить сырой HTML.';
$Definition['ValidateInteger'] = '%s - не целое число (целое число).';
$Definition['ValidateIntegerArray'] = '%s список номеров должен быть разделен запятыми.';
$Definition['ValidateLength'] = '%1$s в %2$s символов слишком длинно.';
$Definition['ValidateMatch'] = 'Поля "%s" не совпадают.';
$Definition['ValidateMinimumAge'] = 'Вам недостаточно лет, чтобы присоединиться к этому сообществу. ';
$Definition['ValidateMinLength'] = '%1$s короче на %2$s символ(ов), чем нужно.';
$Definition['ValidateMinLengthPlural'] = '%1$s короче на %2$s символов, чем нужно.';
$Definition['ValidateMinLengthSingular'] = '%1$s на %2$s символ короче, чем нужно';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Вы должны выбрать хотя бы один %s.';
$Definition['ValidateRegex'] = '%s не является корректным.';
$Definition['ValidateRequired'] = 'Вы не заполнили поле %s.';
$Definition['ValidateRequiredArray'] = 'Вы должны выбрать хотя бы один %s.';
$Definition['ValidateString'] = '%s не является допустимой строкой.';
$Definition['ValidateTag'] = 'Тэги не могут содержать пробелы.';
$Definition['ValidateTime'] = '%s - неверное время.';
$Definition['ValidateTimestamp'] = '%s - неправильная метка времени.';
$Definition['ValidateUrl'] = 'Поле %s не является валидным URL.';
$Definition['ValidateUrlStringRelaxed'] = '%s не могут содержать косые черты, кавычки, или символы тэгов.';
$Definition['ValidateUsername'] = 'Имя пользователя может быть от 3 до 20 символов, и должно содержать только буквы латинского алфавита, цифры и символ подчеркиания.';
$Definition['ValidateVersion'] = '%s отображает неверный номер версии. Правильный номер смотри в функции version_compare() на php.';
$Definition['Value'] = 'Значение';
$Definition['Vanilla Statistics'] = 'Настройки статистики';
$Definition['Vanilla Statistics Plugin'] = 'Плагин статистики';
$Definition['Verified'] = 'Проверенный';
$Definition['Verifying your credentials...'] = 'Проверка ваших учетных данных...';
$Definition['via %s'] = 'с %s';
$Definition['Video embedding has been disabled.'] = 'Встраивание видео было отключено. URL-адрес не будет преобразован в эквивалент для встраивания.';
$Definition['View'] = 'Просмотр';
$Definition['View Badge'] = 'Посмотреть значек';
$Definition['Viewing'] = 'Просмотр';
$Definition['Views'] = 'Визитов';
$Definition['Visible'] = 'Видимый';
$Definition['Visits'] = 'Посещений';
$Definition['Visit Site'] = 'Перейти на сайт';
$Definition['Vote'] = 'Голосовать';
$Definition['Vote (action)'] = 'Голосовать';
$Definition['Vote Down'] = 'Против';
$Definition['Votes'] = 'Рейтинг';
$Definition['Vote Up'] = 'За';
$Definition['Voting for the idea is %s.'] = 'За идею проголосовало %s.';

$Definition['wall'] = 'Стена';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Хотите принять участие в этой дискуссии? Нажмите одну из этих:';
$Definition['Warn'] = 'Предупреждение';
$Definition['Warn %s'] = 'Предупредить %s';
$Definition['Warned for'] = 'Предупреждение за';
$Definition['Warning'] = 'Предупреждение';
$Definition['Warning Level %s'] = 'Уровень предупреждения: %s';
$Definition['Warnings'] = 'Предупреждения';
$Definition['WarningTitleFormat'] = '{InsertUserID,User} предупредил {WarnUserID,User} за {Points,plural,%s points}.';
$Definition['WarningTitleFormat.Notice'] = '{InsertUserID,User} предупредил {WarnUserID,User} за {Points,plural,%s points} (просто уведомление).';
$Definition['was'] = 'был';
$Definition['We\'ve received a request to change your password.'] = 'Мы получили запрос на смену вашего пароля в %s. Если вы не делали этот запрос, пожалуйста, проигнорируйте это письмо.';
$Definition['Website'] = 'Вебсайт';
$Definition['weekday.letter.1'] = 'М';
$Definition['weekday.letter.2'] = 'Т';
$Definition['weekday.letter.3'] = 'В';
$Definition['weekday.letter.4'] = 'Т';
$Definition['weekday.letter.5'] = 'Ф';
$Definition['weekday.letter.6'] = 'С';
$Definition['weekday.letter.7'] = 'С';
$Definition['weekday.long.1'] = 'Понедельник';
$Definition['weekday.long.2'] = 'Вторник';
$Definition['weekday.long.3'] = 'Среда';
$Definition['weekday.long.4'] = 'Четверг';
$Definition['weekday.long.5'] = 'Пятница';
$Definition['weekday.long.6'] = 'Суббота';
$Definition['weekday.long.7'] = 'Воскресенье';
$Definition['weekday.short.1'] = 'Пнд';
$Definition['weekday.short.2'] = 'Втр';
$Definition['weekday.short.3'] = 'Ср';
$Definition['weekday.short.4'] = 'Чтв';
$Definition['weekday.short.5'] = 'Птн';
$Definition['weekday.short.6'] = 'Суб';
$Definition['weekday.short.7'] = 'Воскр';
$Definition['weeks'] = 'недели';
$Definition['Welcome Aboard!'] = 'Добро пожаловать к нам!';
$Definition['were'] = 'где';
$Definition['What\'s This?'] = 'Что это?';
$Definition['What to search'] = 'Что искать';
$Definition['When'] = '
        Когда

';
$Definition['Where'] = '
        Где

';
$Definition['Where do you want to announce this discussion?'] = 'Где вы хотите анонсировать эту дискуссию?';
$Definition['Who\'s going?'] = '
        Кто собирается?

';
$Definition['Who\'s Online'] = 'Кто сейчас на сайте?';
$Definition['Who\'s Online in this Category'] = 'Кто в этом разделе сейчас онлайн';
$Definition['Who\'s Online in this Discussion'] = 'Кто в этой дискуссии сейчас онлайн';
$Definition['Whoops!'] = 'Ой!';
$Definition['Whoops! You\'ll need to register before you can email our site.'] = 'Упс! Вам необходимо зарегистрироваться прежде чем вы сможете отправить письмо на наш сайт.';
$Definition['Why are you Banning this user?'] = 'За что вы решили забанить этого пользователя?';
$Definition['Why do you want to join?'] = 'Почему вы хотите зарегистрироваться?';
$Definition['Would you like to accept the invitation to join this group?'] = '
        Хотите принять приглашение присоединиться к этой группе?';
$Definition['Write a comment'] = 'Написать комментарий';
$Definition['Write Comment'] = 'Комментировать';
$Definition['Write something about yourself...'] = 'Написать что-нибудь о себе...';
$Definition['WTF'] = 'Чтоза#!';

$Definition['Yes'] = 'Да';
$Definition['You'] = 'вы';
$Definition['you'] = 'вы';
$Definition['You\'re banned from joining this group.'] = 'Вам запрещено вступать в эту группу.';
$Definition['You\'ve already created the maximum number of groups.'] = 'Вы уже создали максимальное количество групп.';
$Definition['You\'ve applied to join this group.'] = 'Вы подали заявку на вступление в группу.';
$Definition['You\'ve asked questions that have now been answered'] = '<a href="{/discussions/mine?qna=Answered,url}">Вы задали вопросы, на которые имеются ответы</a> Убедитесь, что вы принимаете/отвергаете ответы.';
$Definition['You\'ve been invited to join {Name}.'] = 'Вас пригласили присоединиться к {Name}.';
$Definition['You\'ve been Jailed.'] = 'Вы были заключены в тюрьму.';
$Definition['You\'ve been warned.'] = 'Вы предупреждены.';
$Definition['You already have an account here.'] = 'У вас здесь уже есть аккаунт';
$Definition['You are about to ban {User.UserID,user}.'] = 'Вы собираетесь забанить {User.UserID,user}.';
$Definition['You are about to move %1$s of the %2$s of the selected discussions.'] = 'Вы собираетесь переместить %1$s из %2$s из выбранных обсуждений.';
$Definition['You are about to move %s.'] = 'Элемент перемещения: %s';
$Definition['You are about to unban {User.UserID,user}.'] = 'Вы собираетесь реабилитировать {User.UserID,user}.';
$Definition['You are allowed to create %s groups.'] = 'Вы имеете право создавать %s группы.';
$Definition['You are already a member of this group.'] = 'Вы уже являетесь участником этой группы.';
$Definition['You are connected as %s through %s.'] = 'Вы подключитесь %s через %s.';
$Definition['You are connected through %2$s.'] = 'Вы подключены через %2$s.';
$Definition['You are currently only viewing categories that you follow.'] = 'Вы сейчас видите только свои отслеживаемые разделы.';
$Definition['You are currently viewing all categories.'] = 'Вы просматриваете все разделы.';
$Definition['You are editing %s\'s signature'] = 'Вы редактируете подпись %s';
$Definition['You are jailed.'] = 'Вы в тюрьме.';
$Definition['You are limited to %s recipient.'] = 'Вы ограничены  %s получателем.';
$Definition['You are limited to %s recipients.'] = 'Вы ограничены количеством получателей:  %s.';
$Definition['You aren\'t a %s of this group.'] = 'Вы не являетесь %s этой группы.';
$Definition['You aren\'t allowed to %s this group.'] = 'Вы не допускаетесь к %s этой группы.';
$Definition['You are now leaving %1$s. Click the link to continue to %2$s.'] = 'Вы покидаете %1$s. Нажмите на ссылку, чтобы перейти к %2$sю';
$Definition['You are now signed in.'] = 'Теперь вы вошли';
$Definition['You are only allowed {maxImages,plural,%s image,%s images}.'] = 'Вам разрешается только {maxImages,plural,%s изображение,%s изображений}.';
$Definition['You can\'t leave the group you started.'] = 'Вы не можете выйти из группы, которую открыли.';
$Definition['You can either ask a question or start a discussion.'] = 'Вы можете задать вопрос или начать новую дискуссию. Выберите, что вы хотите.';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Вы можете отслеживать отдельные разделы и получать уведомления обо всех сообщениях в них.';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Вы не можете редактировать изображение в профиле';
$Definition['You cannot edit the thumbnail of another member.'] = 'Вы не можете редактировать миниатюры других пользователей!';
$Definition['You cannot remove an invitation that has been accepted.'] = 'Вы не можете удалить приглашение, которое было принято.';
$Definition['You can only specify up to %s tags.'] = 'Вы можете указать до %s тэгов.';
$Definition['You can remove or ban this member from the group.'] = 'Вы можете удалить или забанить пользователя группы. Забаненные участники не смогут снова присоединиться к группе.';
$Definition['You can use HTML in your signature.'] = 'Вы можете применять <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">простой HTML</a></b> в вашей подписи.';
$Definition['You don\'t have permission to do that.'] = 'У вас нет прав делать это.';
$Definition['You don\'t have permission to use a signature.'] = 'У вас нет прав на добавление подписей';
$Definition['You do not have any %s yet.'] = 'Пусто: у вас еще нет %s.';
$Definition['You do not have any bookmarks.'] = 'У вас нет ни одной закладки.';
$Definition['You do not have any conversations.'] = 'У вас нет никаких диалогов.';
$Definition['You do not have any drafts.'] = 'У вас нет ни одного черновика.';
$Definition['You do not have any notifications yet.'] = 'Пока никаких уведомлений.';
$Definition['You do not have enough invitations left.'] = 'У вас недостаточно приглашений.';
$Definition['You do not have permission to edit all of the posts you are trying to merge.'] = 'У вас недостаточно прав, чтобы редактировать публикации, которые вы пытаетесь объединить.';
$Definition['You do not have permission to move %1$s of the selected discussions.'] = 'У вас нет разрешения переместить %1$s из выбранных обсуждений.';
$Definition['You do not have permission to view other profiles.'] = 'Вы не имеете соответствующих прав для просмотра чужих профилей.';
$Definition['You do not have permission to write new comments.'] = 'У вас нет прав комментировать.';
$Definition['YouEarnedBadge'] = 'Вы заработали этот значок';
$Definition['You have answered questions'] = 'Вы ответили на вопросы';
$Definition['You have been approved for membership.'] = 'Ваша заявка в группу была одобрена.';
$Definition['You have entered an invalid discussion title'] = 'Вы ввели неверный заголовок дискуссии';
$Definition['You haven\'t joined any groups yet.'] = 'Вы еще не присоединились ни к одной группе.';
$Definition['You haven\'t read this yet.'] = 'Вы ещё не читали это.';
$Definition['You have not started any discussions.'] = 'Вы еще не начали ни одной дискуссии.';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Вы написали %1$s сообщений за %2$s секунд. В целях борьбы со спамом вы заблокированы на %3$s секунд, по прошествии которых вы снова сможете публиковать сообщения.';
$Definition['You have selected %1$s.'] = 'Вы выбрали %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Вы выбрали %1$s в этой дискуссии.';
$Definition['You have successfully connected to {Title}.'] = 'Вы успешно подключились к {Title}.';
$Definition['You have successfully registered for an account at {Title}.'] = 'Вы успешно зарегистрировали аккаунт в {Title}.';
$Definition['You have to select at least 2 discussions to merge.'] = 'Вы должны выбрать хотя бы 2 дискуссии для объединения.';
$Definition['You must agree to the terms of service.'] = 'Вы должны подтвердить правила использования форума.';
$Definition['You must be at least %d years old to register.'] = 'Для регистрации вам должно быть как минимум %d лет.';
$Definition['You must be signed in.'] = 'Вы должны авторизоваться.';
$Definition['You must confirm you have received consent to register.'] = 'Вы должны подтвердить получение вами разрешения на регистрацию.';
$Definition['You need to confirm your email address.'] = 'Вам нужно подтвердить email адрес. Для того, чтобы повторно послать письмо активации, нажмите <a href="/entry/emailconfirmrequest">здесь</a>.';
$Definition['You need to confirm your email address before you can continue.'] = 'Вам нужно подтвердить свой адрес эл. почты перед тем, как продолжить.';
$Definition['You need to sign in before you can do this.'] = 'Вы должны войти в систему прежде, чем вы можете это сделать.';
$Definition['your'] = 'ваше';
$Definition['Your application for this group was denied.'] = 'Ваша заявка на вступление в эту группу была отклонена.';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Спасибо. Ваша заявка будет рассмотрена администратором. Вы будете уведомлены по электронной почте, если ваша заявка будет одобрена.';
$Definition['Your changes have been saved.'] = 'Ваши изменения сохранены.';
$Definition['Your changes have been saved successfully.'] = 'Ваши изменения были успешно сохранены.';
$Definition['Your changes were saved.'] = 'Ваши изменения сохранены.';
$Definition['Your changes were saved successfully.'] = 'Ваши изменения были успешно сохранены.';
$Definition['Your complaint has been registered.'] = 'Ваше обращение зарегистрировано';
$Definition['Your email has been successfully confirmed.'] = 'Ваш email был успешно подтверждён.';
$Definition['Your invitation has been sent.'] = 'Ваше приглашение было отправлено.';
$Definition['Your old password was incorrect.'] = 'Неверно введен старый пароль';
$Definition['Your password has been changed.'] = 'Ваш пароль был изменен.';
$Definition['Your password must be at least %d characters long.'] = 'Количество символов в вашем пароле должно быть не менее %d.';
$Definition['Your password reset token has expired.'] = 'Ваш маркер сброса пароля устарел. Попробуйте использовать форму сброса пароля снова.';
$Definition['Your picture has been removed.'] = 'Ваша фотография была удалена.';
$Definition['Your post will appear once it\'s been approved.'] = 'Ваше сообщение появится после одобрения.';
$Definition['Your preferences have been saved.'] = 'Ваши настройки были сохранены.';
$Definition['Your private conversations with other members.'] = 'Ваши приватные диалоги с другими пользователями.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Ваше имя пользователя при регистрации: <strong>%s</strong>';
$Definition['Your request has been sent.'] = 'Ссылка для подтверждения выслана вам на почту, пожалуйста проверьте.';
$Definition['Your settings have been saved.'] = 'Ваши настройки были сохранены.';
$Definition['Your settings have been saved successfully.'] = 'Ваши настройки были успешно сохранены.';
$Definition['Your status for this event is now: <b>%s</b>'] = 'Сейчас ваш статус в этом событии: <b>%s</v>';
$Definition['Your warning was added.'] = 'Ваше предупреждение было опубликовано.';
$Definition['You were added to a conversation.'] = '{InsertUserID,user} добавил(а) {NotifyUserID,you} к <a href="{Url,htmlencode}">диалогу</a>.';
$Definition['You wrote:'] = 'Вы написали:';
