<?php

$Definition['**Warning: Enabling this feature may cause Javascript errors on your site.**'] = '**Advarsel: Aktivering av denne funksjonen kan føre til Javascript-feil på nettstedet ditt.**';

$Definition['<strong>Heads Up!</strong> Deleting a role can result in users not having access to the application.'] = '<strong>Vent litt!</strong> Å slette en rolle kan føre til at brukerne ikke får tilgang til applikasjonen.';
$Definition['<strong>Heads Up!</strong> Moving discussions into a replacement category can result in discussions vanishing (or appearing) if the replacement category has different permissions than the category being deleted.'] = '<strong>Vent litt!</strong> Å flytte diskujoner til en erstatningskategori kan føre til at diskusjoner forsvinner (eller vises), hvis erstatningskategorien har andre tillatelser enn kategorien som slettes.';

$Definition['About.DisableStatistics'] = 'Hvis du må deaktivere datarapporteringen av forretningsmessige grunner, kan du gjøre dette ved å legge til følgende linje i installasjonens konfigureringsfil: <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Det er viktig for eksistensen av denne gratis programvaren med åpen kildekode, at vi måler rekkevidden og effektiviteten til Vanilla nøyaktig. Vi ber deg om at du ikke deaktiverer rapporteringen av disse dataene.';
$Definition['AboutCommentEmbedding'] = 'Vanilla kan brukes som erstatning for bloggens innebygde kommentarsystem. Den kan faktisk brukes til å legge til kommentarer på enhver side på nettet.';
$Definition['AboutEmbedding'] = 'Innbygging gjør at hele eller deler av nettsamfunnet ditt kan bygges inn i andre applikasjoner og nettsteder.';
$Definition['About Vanilla Statistics'] = 'Om Vanilla Statistics';
$Definition['Access your community forum by clicking the "Visit Site" link.'] = 'Få tilgang til samfunnsforumet ditt ved å klikke lenken "Besøk side" øverst på siden, eller ved å <a href={/,url}>klikke her</a>. Samfunnsforumet er det alle brukerne og kundene dine kommer til å se når de besøker <a href="{/,url,domain}">{/,url,domain}</a>.';
$Definition['Add limits to image upload dimensions in discussions and comments.'] = 'Legg til dimensjonsgrenser på  opplastede bilder i diskusjoner og kommentarer.';
$Definition['AddonProblems'] = '<h2>Problemer?</h2><p>Hvis noe går galt med et tillegg og du ikke kan bruke nettstedet ditt, kan du deaktivere dem manuelt ved å redigere:</p>%s';
$Definition['AddressBarColorDescription'] = 'Noen nettlesere støtter en farge på adresselinjen. Bare mobil.';
$Definition['Alert users if they click external link.'] = 'Varsle brukere hvis de klikker på en kobling i et innlegg som vil føre dem bort fra forumet. Brukere vil ikke bli advart når de følger koblinger som samsvarer med et pålitelig domene';
$Definition['Alignment'] = 'Justering';
$Definition['Alignment (Mobile)'] = 'Justering (mobil)';
$Definition['All categories listed with a selection of 5 recent discussions under each'] = 'Alle kategorier er listet opp med et utvalg av fem nylige diskusjoner under hver';
$Definition['Allow links to be transformed'] = 'La koblinger transformeres til innebygde representasjoner i diskusjoner og kommentarer. For eksempel vil en YouTube-kobling forvandles til en innebygd video.';
$Definition['Allow users with the %s permission to change their own avatars from their profile pages in Vanilla.'] = 'Tillat brukere med %s tillatelse til å endre sine egne avatarer fra sine profilsider i Vanilla.';
$Definition['ApplicationHelp'] = 'Applikasjoner lar deg legge store grupper med funksjonalitet til nettstedet ditt.<br />Når en  applikasjon er lagt til i %s mappen din, kan du aktivere eller deaktivere den her.';
$Definition['Apply Layout'] = 'Bruk layout';
$Definition['Are you sure want to delete this theme? It will be permanently deleted.'] = 'Er du sikker på at du vil slette dette temaet? Det blir slettet permanent.';
$Definition['Are you sure you\'ve entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>'] = 'Er du sikker på at du har oppgitt det riktige vertsnavnet for  databasen? Kanskje du skrev det feil? Databasen rapporterte: <code>%s</code>';
$Definition['A role with default type "unconfirmed" is required to use email confirmation.'] = 'En rolle med standard typen "ubekreftet" er nødvendig for å kunne bruke e-postbekreftelse.';
$Definition['Automatically save drafts of unpublished discussions, questions, ideas and comments.'] = 'Lagre automatisk utkast av upubliserte diskusjoner, spørsmål, ideer og kommentarer.';
$Definition['Avatars will be scaled down if they exceed this height.'] = 'Avatarer skaleres ned hvis de overskrider denne høyden.';
$Definition['Avatars will be scaled down if they exceed this width.'] = 'Avatarer skaleres ned hvis de overskrider denne bredden.';
$Definition['Avatars will have their thumbnails saved at this size.'] = 'Avatarer vil ha miniatyrbildene lagret i denne størrelsen.';

$Definition['Background'] = 'Bakgrunn';
$Definition['Background Image'] = 'Bakgrunnsbilde';
$Definition['Be creative! Try naming your ranks after things that the community talks about.'] = 'Vær kreativ! Prøv å navngi rekkene etter ting som samfunnet snakker om.';
$Definition['Bordered'] = 'grenser';
$Definition['Bordered (Unified)'] = 'Bordered (Enhet)';
$Definition['Borderless'] = 'uten kanter';
$Definition['Border Radius'] = 'Grensradius';
$Definition['Brand Color'] = 'Merkefarge';
$Definition['Buttons'] = 'knapper';
$Definition['Buttons & Inputs'] = 'Knapper og innganger';
$Definition['Button Type'] = 'Knappetype';
$Definition['By clicking the button below, you will be deleting the user account for %s forever.'] = 'Ved å trykke på knappen under, sletter du brukerkontoen til %s for alltid.';

$Definition['Center Aligned'] = 'Center Allined';
$Definition['Changes will apply to newly uploaded avatars only.'] = 'Endringer vil bare gjelde for nyopplastede avatarer.';
$Definition['Change the sizes that avatar images are saved at.'] = 'Endre størrelsene som avatarbilder blir lagret på.';
$Definition['Change the way your community works with plugins.'] = 'Endre måten nettsamfunnet ditt fungerer med programtillegg. Vi har samlet populære programtillegg med programvaren, og det er flere tilgjengelige på nettet.';
$Definition['Checkboxes allow admins to perform batch actions on a number of discussions or comments at the same time.'] = 'Avmerkingsbokser lar administratorer utføre batchhandlinger på en rekke diskusjoner eller kommentarer samtidig.';
$Definition['Check out our %s'] = 'Ta en titt på %s';
$Definition['Check out our <0>documentation</0>, or ask our <1>community of experts</1>.'] = 'Sjekk ut vår <0>dokumentasjon</0> , eller spør vårt <1>fellesskap av eksperter</1> .';
$Definition['Check out these tutorials to get started using Vanilla'] = 'Vanilla er den enkleste og kraftigste nettsamfunnsplattformen i verden. Den er superenkel å bruke. Start med denne instruksjonsvideoen, og fortsett med trinnene under. Kos deg!';
$Definition['Choose a role that orphaned users will be assigned to:'] = 'Velg en rolle som foreldreløse brukere blir tildelt:';
$Definition['Choose a theme for this subcommunity. <0>Read more</0>'] = 'Velg et tema for dette underfellesskapet. <0> Les mer </0>';
$Definition['Choose Image'] = 'Velg Bilde';
$Definition['Choose md5 if you\'re not sure what to choose.'] = 'Du kan velge en tilpasset hash-algoritme til å signere forespørslene dine. Hash-algoritmen må også brukes i ditt klientbibliotek. Velg md5 hvis du er usikker på hva du skal velge.';
$Definition['Choose the order items are sorted.'] = 'Velg rekkefølgen elementene er sortert.';
$Definition['Choose the page people should see when they visit <0/>'] = 'Velg siden folk skal se når de besøker <0/>';
$Definition['Choose the preferred layout for lists of categories.'] = 'Velg den foretrukne utformingen for lister med kategorier.';
$Definition['Choose the preferred layout for lists of categories. You can edit the Tiled Layout.'] = 'Velg det foretrukne oppsettet for lister over kategorier. Du kan redigere flislagt oppsett.';
$Definition['Choose the preferred layout for lists of discussions.'] = 'Velg den foretrukne utformingen for lister med diskusjoner.';
$Definition['Choose the preferred layout for lists of discussions. You can edit the Foundation Layout.'] = 'Velg det foretrukne oppsettet for lister over diskusjoner. Du kan redigere grunnoppsettet.';
$Definition['Color Overlay'] = 'Fargeoverlegg';
$Definition['Continue Import'] = 'Fortsett importering';
$Definition['Could not parse import file. The problem is near line %s.'] = 'Kunne ikke analysere importfil. Problemet er nær linjen %s.';
$Definition['Create a localization CSV'] = 'Lag en plasserings-CSV';
$Definition['Custom Themes are the themes you created. You can edit, rename or make a copy of them.'] = 'Tilpassede temaer er temaene du opprettet. Du kan redigere, gi nytt navn eller lage en kopi av dem.';

$Definition['Dark'] = 'Mørk';
$Definition['Define who can upload files on the Roles & Permissions page.'] = 'Definer hvem som kan laste opp og administrere filer på siden for  <a href="%s">Roller og tillatelser</a>.';
$Definition['Define your forum homepage, upload your logo, and more...'] = 'Definer forumets hjemmeside, last opp logoen din, og mer ...';
$Definition['Deleting a role can result in users not having access to the application.'] = 'Å slette en rolle kan føre til at brukere ikke får tilgang til applikasjonen.';
$Definition['Deleting forever cannot be undone.'] = 'Sletting er en bra måte å holde forumet ditt rent på.';
$Definition['Disable Google Sign In'] = 'Deaktiver Google-pålogging';
$Definition['Disable OpenID'] = 'Deaktiver OpenID';
$Definition['Disable the "New Embed System" lab on the <0>Vanilla Labs Page</0>'] = 'Deaktiver "New Embed System"-laben på <0>Vanilla Labs-siden</0>';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Diskusjonskategorier brukes for å hjelpe brukerne til å organisere sine diskusjoner på en måte som er meningsfull for nettsamfunnet.';
$Definition['Don\'t embed your forum admin dashboard (pop it out to full-screen)'] = 'Ikke bygg inn kontrollpanelet for administrering av forumet (vid det heller ut på fullskjerm) ';
$Definition['Don\'t use too many reactions.'] = 'Ikke bruk for mange reaksjoner. Du vil ikke gi brukerne informasjon overbelastning.';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Dra og slipp kategoriene nedenfor for å sortere og ordne dem.';

$Definition['EditContentTimeout.Notes'] = 'Hvis en bruker er i en rolle som har tillatelse til å redigere innhold, overstyrer disse tillatelsene dette.';
$Definition['Edit Route'] = 'Rediger rute';
$Definition['Edits to this theme apply to:'] = 'Redigeringer til dette temaet gjelder for:';
$Definition['Embed Settings'] = 'Innebyggingsinnstillinger';
$Definition['Embed your community forum into your website to increase engagement...'] = 'Bygg forumet ditt inn på nettstedet for å øke engasjementet ...';
$Definition['Enable and test out the latest Vanilla features.'] = 'Aktiver og test de siste Vanilla -funksjonene.';
$Definition['Enables advanced editing of posts in several formats, including WYSIWYG, simple HTML, Markdown, and BBCode.'] = 'Gjør det mulig avansert redigering av innlegg i flere formater, inkludert WYSIWYG, enkel HTML, Markdown og BBCode.';
$Definition['Enable the Layout Editor to apply a custom layout for your community pages. Use our new editor to feature content using our catalogue of available widgets.'] = 'Aktiver Layout Editor for å bruke et tilpasset oppsett for fellesskapssidene dine. Bruk vår nye editor til å vise innhold ved å bruke vår katalog over tilgjengelige widgets.';
$Definition['Enter a descriptive name.'] = 'Skriv inn et beskrivende navn på lommen. Dette navnet vises ikke noe sted, bortsett fra når man administrerer lommene, så det brukes bare for å hjelpe deg med å huske lommen.';
$Definition['Enter a short name for the site.'] = 'Oppgi et kort navn på nettstedet. Dette vises på påloggingsknappene.';
$Definition['Enter the address of your Wordpress Blog and we\'ll take it from there.'] = 'Skriv inn adressen til Wordpress-bloggen din, og så tar vi det videre derfra.';
$Definition['Enter the connection settings for your sphinx server below.'] = 'Skriv inn tilkoblingsinnstillingene for Sphinx-serveren din under.';
$Definition['Every edit or deletion is recorded here. Use &lsquo;Restore&rsquo; to undo any change.'] = 'Hver redigering eller sletting spilles inn her. Bruk ‘Gjenopprett’ for å angre eventuelle endringer.';
$Definition['Everyone who signs up gets a profile page.'] = 'Alle som registrerer seg i samfunnet ditt får en offentlig profilside der de kan laste opp et bilde av seg selv, administrere profilinnstillinger, og spore kule ting som skjer i samfunnet. Du burde <a href="{/profile,url}">tilpasse profilen din nå</a>.';
$Definition['Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.'] = 'Hver eneste bruker må få minst én rolle. Roller brukes for å bestemme hva brukere har lov til å gjøre.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect lar brukerne logge inn ved å bruke Facebook-kontoene sine. <b>Du må registrere applikasjonen din hos Facebook for at dette programtillegget skal fungere.</b>';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = 'Mislyktes med å koble databasen sammen med brukernavnet og passordet du oppga. Skrev du dem feil? Databasen rapporterte: <code>%s</code>';
$Definition['Font Name'] = 'Skriftnavn';
$Definition['Font URL'] = 'Skrift-URL';
$Definition['Force the dashboard to only be accessible through this url <em>(not recommended)</em>'] = 'Tving kontrollpanelet til kun å være tilgjengelig via denne url-en <em>(ikke anbefalt)</em>';
$Definition['For example, you can ban all users with emails addresses from "example.com" by adding an email-type ban with the value "*@example.com".'] = 'Du kan for eksempel blokkere alle brukere med e-postadresser fra "eksempel.no" ved å legge til blokkering for e-post-typer med verdien "*@eksempel.no".';
$Definition['For SEO purposes, search engine crawlers are excluded from being forced to view the forum in the remote url.'] = 'Søkeroboter ekskluderes, av SEO-grunner, fra å være tvunget til å se forumet i den eksterne url-en.';
$Definition['Foundation Layout'] = 'Fundamentoppsett';
$Definition['Full Bleed'] = 'Full blødning';

$Definition['Garden.Import.Complete.Description'] = 'Importeringen var vellykket.
   Klikk <b>Ferdig</b> når du er klar.';
$Definition['Garden.Import.Continue.Description'] = 'Det ser ut som om du er i midten av en import. Velg ett av følgende alternativer.';
$Definition['Garden.Import.InputInstructions'] = 'Oppgi e-post og passord for administrativ bruker av dataen som importeres.';
$Definition['Garden.Profiles.Edit permission to change their own avatars from their profile pages in Vanilla.'] = 'Garden.Profiles.Edit tillatelse til å endre sine egne avatarer fra profilsidene deres i Vanilla.';
$Definition['Garden.StatisticsDisabled'] = 'Du har spesifikt deaktivert Vanilla Statistics i konfigurasjonsfilen din.';
$Definition['Garden.StatisticsLocal.Explain'] = 'Det virker som om dette forumet kjøres i et testmiljø, eller at det på annet vis rapporterer inn en privat IP. Standard er at forum som kjøres fra private IP-er ikke spores.';
$Definition['Garden.StatisticsLocal.Resolve'] = 'Hvis du er sikker på at forumet ditt er tilgjengelig på internett, kan du tvinge det til å innrapportere statistikker her:';
$Definition['Garden.StatisticsReadonly.Explain'] = 'config.php-filen din virker å være skrivebeskyttet. Dette vil si at Vanilla ikke automatisk vil være i stand til å registrere forumets InstallationID og InstallationSecret.';
$Definition['Garden.StatisticsReadonly.Resolve'] = 'For å løse dette problemet, overfør filmodus 777 til din conf/config.php-fil.';
$Definition['Global Styles'] = 'Globale stiler';

$Definition['Heads Up!'] = 'Følg med!';
$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Øy! Dette er en spesiell rolle som ikke tillater aktive sessions. Av denne grunn har tillatelse valgene vært begrenset til "Se" tillatelser. Dvs. Kun "Se" og ikke "Skriv". ';
$Definition['Here are all of the reactions you can use on your site.'] = 'Her er alle reaksjonene du kan bruke på nettstedet ditt.';
$Definition['Here are the ranks that users can achieve on your site.'] = 'Her er rekkene som brukere kan oppnå på nettstedet ditt. Du kan tilpasse disse rekkene og til og med legge til nye. Her er noen tips.';

$Definition['If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Hvis en bannerlogo lastes opp, erstatter den bannertittelen på forumsidene rettet mot brukerne.';
$Definition['If a user does not visit the site within this time period they will be automatically signed out.'] = 'Hvis en bruker ikke besøker nettstedet innen denne tidsperioden, logges de automatisk av.';
$Definition['If enabled, the full content of posts will be sent in email notifications to users.'] = 'Hvis dette er aktivert, vil hele innholdet i innleggene bli sendt i e-postvarsler til brukerne.';
$Definition['If you are new to HTML and/or CSS, here are some tutorials to get you started:'] = 'Hvis du er ukjent med HTML og / eller CSS, her er noen opplæringsprogrammer for å komme i gang:';
$Definition['If you have an old theme'] = 'Hvis du har et gammelt tema og trenger å angi et eget desktop- og mobiltema, kan du gjøre det med det gamle tema-brukergrensesnittet.';
$Definition['If you want to decrease the warning level then remove a warning.'] = 'Hvis du vil senke advarselsnivået, fjerner du en advarsel.';
$Definition['If you want to embed your forum, enable embedding.'] = 'Hvis du vil legge inn forumet ditt eller bruke Vanilas kommentarer i bloggen din, må du aktivere innebygging. Hvis du ikke bruker innebygging, anbefaler vi at du slår denne innstillingen av.';
$Definition['Image (Mobile)'] = 'Bilde (mobil)';
$Definition['Import'] = 'Importer';
$Definition['Importing to Vanilla'] = 'Importerer til Vanilla';
$Definition['In additon to the widgets there are also'] = 'I tillegg til widgetene er det også <0> Global Styles </0> . For å redigere globale stiler, klikk andre steder på siden, for eksempel denne teksten.';
$Definition['Integrate Foundation Pages & Components Into Your Theme'] = 'Integrer grunnleggende sider og komponenter i temaet ditt';
$Definition['Internationalization & Localization'] = 'Internasjonalisering og lokalisering';
$Definition['Invalid URL'] = 'ugyldig URL';
$Definition['Invitation email failed to send: %'] = 'Selv om invitasjonen ble opprettet, lyktes ikke e-posten å sende. Serveren rapporterte følgende feil: %s';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Når du bruker registrering ved invitasjon, vil brukerne ha en lenke som kalles <a href="%s" class="Popup">Mine invitasjoner</a> på profilsidene sine.';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = 'Det virker som om databasen du spesifiserte ikke finnes ennå. Har du laget den nå? Skrev du navnet feil? Databasen rapporterte: <code>%s</code>';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Det er en god idé å holde maks antall tillatte tegn i en kommentar nede på et fornuftig nivå.';
$Definition['It is a good idea to keep the maximum number of characters allowed in a post down to a reasonable size.'] = 'Det er lurt å holde maksimalt antall tillatte tegn i et innlegg nede til en fornuftig størrelse.';

$Definition['Kick-start your community and increase user engagement.'] = 'Spark i gang nettsamfunnet ditt og øk brukerengasjementet.';

$Definition['Learn about custom routing.'] = 'Lær om egendefinert routing.';
$Definition['Learn how to completely change your forum\'s look and feel: upload your logo, set your homepage, choose a theme and customize it.'] = 'Lær deg hvordan du fullstendig endrer utseendet og opplevelsen på forumet ditt: last opp logoen din, bestem hjemmeside, velg et tema og juster det.';
$Definition['Learn how to use the basic functionality of your forum.'] = 'Lær deg hvordan du bruker den grunnleggende funksjonaliteten på forumet ditt.';
$Definition['Left Aligned'] = 'Venstrejustert';
$Definition['Light'] = 'Lys';
$Definition['Links'] = 'lenker';
$Definition['Locales allow you to support other languages on your site.'] = 'Localer lar deg støtte andre språk på siden din. Aktiver og deaktiver localer du ønsker å gjøre tilgjengelig her.';
$Definition['LogoDescription'] = 'Bannerlogoen viser seg på toppen av nettstedet ditt.';
$Definition['LogoDisclaimer'] = 'Temaer laget med temaredigereren og noen tilpassede temaer bruker ikke denne innstillingen.';
$Definition['Looking for the Old Embed System?'] = 'Leter du etter det gamle innebyggingssystemet?';

$Definition['Make sure you click View Page'] = 'Sørg for at du klikker på <a href="%s">Se side</a> for å se hvordan kategorisiden din ser ut etter lagring.';
$Definition['Manage Routes'] = 'Administrer ruter';
$Definition['Managing Users'] = 'Administrere brukere';
$Definition['Marking things as NOT spam will put them back in your forum.'] = 'Å markere ting som IKKE-søppel legger dem tilbake igjen i forumet ditt.';
$Definition['Marking things as not spam will put them back in your forum.'] = 'Å markere ting som ikke-søppel legger dem tilbake igjen i forumet ditt.';
$Definition['Messages can appear anywhere in your application.'] = 'Meldinger kan vises hvor som helst på siden din, og kan brukes for å informere brukere om nyheter og eventer. Denne siden brukes for å organisere dine beskjeder ved å dra de opp eller ned.';
$Definition['MobileLogoDescription'] = 'Mobil bannerlogo vises øverst på nettstedet ditt.';
$Definition['Mobile themes allow you to change the look and feel of your site on smaller devices.'] = 'Mobiltemaer lar deg endre utseendet og følelsen på nettstedet ditt på mindre enheter.';

$Definition['N.B. The new Layout Editor will inherit the theme set in your Style Guide (formally theme editor). <1>Find out more</1>'] = 'NB Den nye layoutredigereren vil arve temaet som er satt i stilguiden din (formelt temaredigering). <1>Finn ut mer</1>';
$Definition['Need more help?'] = 'Trenger du mer hjelp?';
$Definition['Nested categories deeper than this depth will be placed in a comma-delimited list.'] = 'Innrede kategorier dypere enn denne dybden vil bli plassert i en kommaavgrenset liste.';
$Definition['New Embed System'] = 'Nytt innebygd system';
$Definition['New Quick Links'] = 'Nye hurtigkoblinger';
$Definition['New Search Page'] = 'Ny søkeside';
$Definition['Not getting what you expect when you preview your theme?'] = 'Får du ikke det du forventer når du forhåndsviser temaet?';
$Definition['Notify me when people comment on my addons.'] = 'Varsle meg når folk kommenterer tilleggene mine.';
$Definition['No unconfirmed role available for email confirmation.'] = 'Nettstedet trenger en rolle med standard typen "ubekreftet" for å bruke e-postbekreftelse. Vennligst legg til en for å aktivere denne innstillingen.';

$Definition['Old Theming UI'] = 'Gammelt temagrensesnitt';
$Definition['Once enabled, only members will see inside your community.'] = 'Når dette er aktivert, er det bare medlemmer som ser i samfunnet ditt.';
$Definition['OrgDescription'] = 'Din organisasjons navn brukes for SEO-mikrodata og JSON+LD';
$Definition['Outline'] = 'Disposisjon';
$Definition['Overridden views or themehooks can have unintended side effects and are not previewed.'] = 'Overrømte visninger eller temahooks kan ha utilsiktede bivirkninger og forhåndsvises ikke.';

$Definition['Password.MinLength'] = 'Minimum tegnlengde tillatt for brukerpassord på passordopprettings- og tilbakestillingssider.';
$Definition['Please choose an authenticator to configure.'] = 'Vennligst velg en autentisering å konfigurere.';
$Definition['PluginHelp'] = 'Programtilleggene lar deg legge til funksjonalitet på nettstedet ditt.<br />Når et programtillegg er lagt til i %s mappen din, kan du aktivere eller deaktivere det her.';
$Definition['Pockets.BetweenDiscussions.Description'] = 'Lommen vises mellom hver diskusjon i hovedlisten for diskusjoner. Ettersom diskusjonene vanligvis er i <li>..</li>-tagger, må du pakke lommen inn i disse taggene også.';
$Definition['Pockets allow you to add free-form HTML to various places around the application.'] = 'Lommer lar deg legge til frie HTML-er på ulike plasser rundt applikasjonen.';
$Definition['Preset'] = 'Forhåndsinnstilt';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Unngå søppel på forumet ditt ved å begrense antallet diskusjoner & kommentarer brukerne kan poste innenfor en gitt tidsperiode.';
$Definition['Primary Button'] = 'Primær knapp';
$Definition['Primary Buttons'] = 'Primære knapper';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Hurtigstartveiledning for å lage temaer til Vanilla';
$Definition['Quick Links is a default component on community pages.'] = 'Hurtigkoblinger er en standardkomponent på fellesskapssider. Aktiver vår nye hurtigkoblingskomponent for å legge til, redigere eller skjule lenker fra denne menyen ved hjelp av temaredigereren.';

$Definition['Ready-made Vanilla Comments Plugin for WordPress'] = 'Klargjort programtillegg for Vanilla Comments til WordPress';
$Definition['Ready-made Vanilla Forum Plugin for WordPress'] = 'Klargjort programtillegg for Vanilla Forum hos WordPress';
$Definition['Realtime progress bars: %s'] = 'Fremdriftsfelt i sanntid: %s';
$Definition['Recommend special ranks for admins and mods.'] = 'Det er lurt å ha spesielle rekker for moderatorer og administratorer, slik at samfunnet ditt enkelt kan se hvem som har ansvaret.';
$Definition['Recommend starting with five ranks.'] = 'Du vil ikke ha for mange rekker. Vi anbefaler å starte med fem. Du kan legge til mer hvis samfunnet ditt er veldig stort.';
$Definition['Remove discussion and categories links from menus. Set discussion and category related pages to return not found page 404.'] = 'Fjern diskusjons- og kategorikoblinger fra menyene. Angi diskusjons- og kategorirelaterte sider til å returnere ikke funnet side 404.';
$Definition['Requires “Flag” reaction permission.'] = 'Krever “Flagg” reaksjonstillatelse.';
$Definition['Requires “Negative” reaction permission.'] = 'Krever “negativ” reaksjonstillatelse.';
$Definition['Requires “Positive” reaction permission.'] = 'Krever "Positiv" reaksjonstillatelse.';
$Definition['Restoring your selection removes the items from this list.'] = 'Når du gjenoppretter, fjernes elementene fra listene og settes tilbake igjen på nettstedet.';
$Definition['RichEditor.QuoteEnable.Notes'] = 'Bruk følgende alternativ for å aktivere sitater for den rike tekstbehandleren. Dette vil kun gjelde hvis standard tekstbehandler er "Rik"';
$Definition['Route Expression'] = 'Ruteuttrykk';
$Definition['Routes are used to redirect users.'] = 'Router brukes for å videresende brukere avhengig av den forespurte URL-en.';

$Definition['Search for users by name or enter the name of a role to see all users with that role.'] = 'Søk etter brukere etter navn eller skriv inn navnet på en rolle for å se alle brukerne med den rollen.';
$Definition['Secondary Button'] = 'Sekundær knapp';
$Definition['Secondary Buttons'] = 'Sekundærknapper';
$Definition['Security.Hsts.HTTPSWarning'] = 'Advarsel: Aktiver denne egenskapen kun når du er sikker på at alle subdomenene dine er konfigurert for HTTPS med gyldige sertifikater.';
$Definition['Security.Hsts.IncludeSubDomains'] = 'Når aktivert, gjelder denne regelen også for alle subdomenene til nettstedet ditt.';
$Definition['Security.Hsts.MaxAgeRecommendation'] = 'Vi anbefaler å begynne med en maksalder på en uke, så øke den til en måned og deretter til en gang per år så snart du ser at nettstedet ditt fungerer som forventet.';
$Definition['Security.Hsts.SubmitWarning'] = 'Advarsel: Det er flott å støtte HSTS-forhåndslasting som beste praksis. Du må imidlertid sende inn nettstedet ditt til hstspreload.org for å sikre at det er skikkelig forhåndslastet (for å oppnå full beskyttelse for den aktuelle konfigurasjonen).';
$Definition['See the documentation'] = 'Se dokumentasjonen';
$Definition['Select the default type for this role, if any.'] = 'Velg standardtype for denne rollen, hvis noen.';
$Definition['Select the import source'] = 'Velg importkilden';
$Definition['Serialized column "%s" failed to be unserialized.'] = 'Serialisert kolonne "%s" mislyktes i å bli userialized.';
$Definition['Session Timeout'] = 'Tidsavbrudd for økten';
$Definition['Shadowed'] = 'Skygget';
$Definition['ShareImageDescription'] = 'Når noen deler en lenke fra nettstedet ditt, prøver vi å ta et bilde fra siden. Hvis det ikke er et bilde på siden, bruker vi dette bildet i stedet. Bildet skal være minst 50 × 50, men vi anbefaler 200 × 200.';
$Definition['Show all possible pocket locations.'] = 'Skru på dette alternativet for å vise alle mulige plasseringer for lommer. Å slå på dette alternativet vil bare vise plasseringene til brukere som kan administrere lommer.';
$Definition['Solid'] = 'Fast';
$Definition['Some browsers support a color for the address bar.'] = 'Noen nettlesere støtter en farge for adressefeltet.';
$Definition['Some older themes don\'t support full editing capability.'] = 'Noen eldre temaer støtter ikke full redigeringsevne. For å se hva et tema støtter, kan du holde musepekeren over navnet for å se hvor endringer vil tre i kraft.';
$Definition['Some themes may need to be updated to work with category following. You can disable the feature while you update your theme.'] = 'Noen temaer må kanskje oppdateres for å fungere med følgende kategori. Du kan deaktivere funksjonen mens du oppdaterer temaet.';
$Definition['Sometimes you want to embed your Vanilla site'] = 'Noen ganger vil du legge inn Vanilla-nettstedet ditt på et annet nettsted. Vanillas embed-system tilbyr en enkel måte til det. Det er ytelsesavveininger når du bruker et innebygd nettsted, så sjekk dokumentasjonen for alternativer og ideelle brukstilfeller.';
$Definition['Special restriction: Only users with permission Garden.Curation.Manage may use this reaction.'] = 'Spesiell begrensning: Bare brukere med tillatelse Garden.Curation.Manage kan bruke denne reaksjonen.';
$Definition['Specify a partial or full match when creating a ban.'] = 'Spesifiser en delvis eller full match når du etablerer en blokkering.';
$Definition['Spend a little time thinking about how you describe your site here.'] = 'Bruk litt tid på å tenke på hvordan du vil beskrive nettstedet ditt. Å gi nettstedet ditt en meningsfull tittel og konsis beskrivelse, kan hjelpe plasseringen det gis hos søkemotorer.';
$Definition['Spruce up your emails by adding a logo and customizing the colors.'] = 'Pynt e-postene dine ved å legge til en logo og tilpasse fargene.';
$Definition['Start Import'] = 'Start importering';
$Definition['Start the first discussion.'] = 'Få ballen i gang i samfunnet ditt ved å <a href="{/post/discussion,url}">starte den første diskusjonen</a> nå.';

$Definition['Tagging allows users to add a tag to discussions they start in order to make them more discoverable. '] = 'Merking lar brukere legge til en tag til diskusjoner de starter for å gjøre dem mer oppdagelige.';
$Definition['Templates are the standard themes. To customize them, you have to create a copy.'] = 'Maler er standardtemaene. For å tilpasse dem, må du lage en kopi.';
$Definition['The %s Authenticator does not have any custom configuration options.'] = '%s-autentikatoren har ingen tilpassede konfigureringsalternativ.';
$Definition['The <0/> lab needs to be configured to match your custom theme.'] = 'NB <0/> laben må konfigureres for å matche ditt tilpassede tema. Dette kan gjøres ved hjelp av vår nye temaredigerer. <1> Finn ut mer.</1>';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'Tillegget kunne ikke aktiveres, fordi det genererte en fatal feil: <pre>%s</pre>';
$Definition['The addon has already been downloaded.'] = 'Tillegget er allerede lastet ned.';
$Definition['The banner logo appears at the top of your forum.'] = 'Banner-logo vises øverst på toppen av forumet ditt.';
$Definition['The banner title appears on the top-left of every page.'] = 'Bannertittelen viser seg oppe til venstre på hver side.';
$Definition['The banner title appears on your site\'s banner and in your browser\'s title bar.'] = 'Bannertittelen vises på nettstedets banner og nettleserens tittelfelt. Det bør være kortere enn 20 tegn. Hvis en bannerlogo lastes opp, vil den erstatte bannertittelen på forumsider rettet mot brukerne. Tenk også over at enkelte temaer kan skjule denne tittelen.';
$Definition['The basic registration form requires new users to copy text from a CAPTCHA image.'] = '<strong>Det grunnleggende registreringskjemaet krever</strong> at nye brukere kopierer tekst fra et CAPTCHA-bilde for å holde spammere vekk fra siden. Du trenger en konto hos <a href="http://recaptcha.net/">recaptcha.net</a>. Registrering er GRATIS og lettvint. Etter at du har registrert deg, kom tilbake hit og oppgi de følgende innstillingene:';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = 'Brukeren av databasen som du spesifiserte, har ikke tilgang til databasen. Har du opprettet databasen nå? Databasen som er rapportert: <code>%s</code>';
$Definition['The following structure changes are required for your database.'] = 'Følgende strukturendringer er nødvendige for databasen din.';
$Definition['The import file does not contain any data.'] = 'Importfilen inneholder ingen data.';
$Definition['The import file is not in the correct format.'] = 'Importfilen er ikke i riktig format.';
$Definition['The location of the authentication endpoint.'] = 'Plasseringen av autentiseringens endepunkt.';
$Definition['ThemeHelp'] = 'Temaer lar deg endre utseendet og følelsen på nettstedet ditt. <br /> Når et tema er lagt til i mappen %s, kan du aktivere det her.';
$Definition['Theme preview is limited to displaying the theme\'s template and css.'] = 'Forhåndsvisning av tema er begrenset til å vise tematets mal og css.';
$Definition['Theming Guide'] = 'Temaguide';
$Definition['The mobile logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Mobillogoen vises øverst på nettstedet ditt. Temaer laget med temaredigering og enkelte tilpassede temaer bruker ikke denne innstillingen.';
$Definition['The New Embed System'] = 'Det nye innebygde systemet';
$Definition['The new embed system has improved performance.'] = 'Det nye innebygde systemet har forbedret ytelse, forbedret rulleadferd og mer konsistent oppførsel enn det gamle. For øyeblikket støttes ikke innbygging av kommentarer og wordpress i New Embed System.';
$Definition['The Password Authenticator does not have any custom configuration options. '] = 'Passord-autentiseringen har ikke noen egendefinerte konfigurerings instillinger.';
$Definition['There are no database structure changes required. There may, however, be data changes.'] = 'Ingen endringer i databasestrukturen kreves. Det kan uansett oppstå dataendringer.';
$Definition['There are two types of buttons in the application: primary and secondary.'] = 'Det er to typer knapper i applikasjonen: primær og sekundær.';
$Definition['The route was saved successfully.'] = 'Ruten ble lagret.';
$Definition['The site description usually appears in search engines. You should try having a description that is 100-150 characters long.'] = 'Områdebeskrivelsen vises vanligvis i søkemotorer. Du bør prøve å ha en beskrivelse som er 100-150 tegn lang.';
$Definition['The text of the pocket.'] = 'Skriv inn teksten til lommen. Dette vil vises nøyaktig slik du skriver det, så sørg for at du skriver inn en gyldig HTML.';
$Definition['The touch icon appears when you bookmark a website on the homescreen of a mobile device. These are usually 152 pixels.'] = 'Berøringsikonet vises når du bokmerker et nettsted på startskjermen til en mobilenhet. Disse er vanligvis 152 piksler.';
$Definition['The user table was not in the import file.'] = 'Brukertabellen fantes ikke i importfilen.';
$Definition['The Vanilla 2 Exporter'] = 'Vanilla 2 Exporter';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Vanilla Statistics gjør forumets kontrollpanel om til et rapporterende analyseverktøy, som lar deg gjennomgå aktiviteten på forumet ditt i bestemte tidsperioder. Du kan <a href="http://vanillaforums.org/docs/vanillastatistics">lese mer om Vanilla Statistics</a> i dokumentasjonen vår.';
$Definition['They work just like regular themes. Once one has been added to the themes folder, you can enable it here.'] = 'De fungerer akkurat som vanlige temaer. Når en er lagt til i temamappen, kan du aktivere den her.';
$Definition['This is a style guide of your theme.'] = 'Dette er en stilguide for temaet ditt. Den har eksempler på de visuelle elementene som brukes i hele applikasjonen. Du kan klikke på de forskjellige widgetene, for eksempel <0> tittellinjen </0> eller <1> Banner </1> for å redigere egenskapene i sidepanelet.';
$Definition['This is the administrative dashboard for your new community.'] = 'Dette er administrasjonspanelet for det nye samfunnet ditt. Sjekk konfigurasjonsvalgene på siden. Derfra kan du konfigurerer hvordan samfunnet ditt fungerer. <b>Som standard kan kun  brukere i "administrator"-rollen se denne delen av samfunnet ditt.</b>';
$Definition['This is where you can enable and test out new Vanilla features, pages & components.'] = 'Det er her du kan aktivere og teste nye Vanilla -funksjoner, sider og komponenter.';
$Definition['This lab cannot be disabled because a custom layout is applied.'] = 'Denne prøven kan ikke deaktiveres fordi en tilpasset layout er brukt.';
$Definition['This lab cannot be disabled because it is required by the current theme.'] = 'Denne laben kan ikke deaktiveres fordi den kreves av det gjeldende temaet.';
$Definition['This logo appears at the top of your site. Themes made with the theme editor and some custom themes don\'t use this setting.'] = 'Denne logoen vises øverst på nettstedet ditt. Temaer laget med temaredigering og enkelte tilpassede temaer bruker ikke denne innstillingen.';
$Definition['This option shows/hides the locations where pockets can go.'] = 'Dette alternativet viser/skjuler plasseringene der lommene kan plasseres, men bare for brukere som har tillatelse til å legge til / redigere lommer. Prøv å vise plasseringene, og besøk deretter nettstedet ditt.';
$Definition['This page lists the endpoints of your API.'] = 'Denne siden viser sluttpunktene til API-en din. Klikk på sluttpunkter for mer informasjon. Du kan ringe direkte til API fra denne siden eller eksternt ved hjelp av et tilgangstoken.';
$Definition['This role is personal info. Only users with permission to view personal info will see it.'] = 'Denne rollen er personlig info. Bare brukere med tillatelse til å se personlig informasjon vil se den.';
$Definition['This setting loads the page before executing Javascript.'] = 'Denne innstillingen laster siden før Javascript settes i gang, noe som kan forbedre din SEO.<br><strong>**Advarsel: Aktivering av denne funksjonen kan føre til feil med Javascript på siden din.**</strong>';
$Definition['This setting loads the page before executing Javascript which can improve your SEO.'] = 'Denne innstillingen laster inn siden før Javascript kjøres, noe som kan forbedre SEO-en din.';
$Definition['This theme cannot be deleted because it is the currently applied theme.'] = 'Dette temaet kan ikke slettes fordi det er det som er i bruk for tiden.';
$Definition['This title appears on your site\'s banner and in your browser\'s title bar. It should be less than 20 characters. If a logo is uploaded, it will replace this title on user-facing forum pages. Also, keep in mind some themes may hide this title.'] = 'Denne tittelen vises på nettstedets banner og i nettleserens tittellinje. Det skal være mindre enn 20 tegn. Hvis en logo lastes opp, vil den erstatte denne tittelen på brukervendte forumsider. Husk også at noen temaer kan skjule denne tittelen.';
$Definition['Tiled Layout'] = 'Flislagt oppsett';
$Definition['Title Bar'] = 'Tittellinje';
$Definition['To embed your Vanilla forum into your web site, use the following code.'] = 'For å bygge ditt Vanilla-forum inn på nettstedet, bruk følgende kode.';
$Definition['Too many addresses! We\'ll send up to %s addresses at once.'] = 'For mange adresser! Vi kan sende til maks. %s adresser samtidig.';
$Definition['To prevent abuse, some tools automatically hide content and list it here until it is manually approved by a moderator.'] = 'For å unngå misbruk, skjuler enkelte verktøy innhold automatisk, og lister det opp her inntil det godkjennes manuelt av en operatør.';
$Definition['TouchIconDescription'] = 'Berøringsikonet vises når du bokmerker et nettsted på startskjermen til en Apple-enhet. Disse er vanligvis 152 piksler. Apple tilfører avrundede hjørner og lyseffekt automatisk.';
$Definition['Transparent'] = 'Gjennomsiktig';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect lar brukerne logge på ved bruk av Twitter-kontoene sine. <b>Du må registrere kontoen din hos Twitter for at dette programtillegget skal fungere.</b>';

$Definition['Usercards'] = 'Brukerkort';
$Definition['Usercards allow you to get a quick in-line snapshot of a user\'s information.'] = 'Brukerkort lar deg få et raskt in-line øyeblikksbilde av en brukers informasjon. Når du ser på innlegg og poengoversikter, klikker du på brukernavnet for å se et kort som viser brukerens grunnleggende profilinformasjon uten å måtte navigere bort fra siden. Aktiver denne funksjonen for å legge til brukerkort til ditt egendefinerte tema.';
$Definition['User inputs are based on the global background and text colors.'] = 'Brukerinnganger er basert på den globale bakgrunns- og tekstfargen.';
$Definition['User Profile'] = 'Brukerprofil';
$Definition['Users may sign into your site using their Twitter account.'] = 'Brukere kan logge seg på nettstedet ditt ved å bruke sin Twitter-konto.';
$Definition['Use the button at the top of the page to create a ban rule.'] = 'Bruk knappen øverst på siden for å lage en forbudsregel.';
$Definition['Use the plugin for WordPress or our universal code for any other platform'] = 'Bruk programtillegget for å sette opp Vanilla Comments på bloggen din, eller bruk universalkoden for å sette opp Vanilla Comments på hvilken som helst annen plattform.';

$Definition['Vanilla\'s new search service is finally here.'] = 'Vanillas nye søketjeneste er endelig her. Aktiver vårt nye brukergrensesnitt for søkeside for å få tilgang til de nyeste søkefunksjonene som medlemssøk, søkesortering og utheving av termer.';
$Definition['Vanilla Export: %s, Source: %s'] = 'Vanilla-eksport: %s, Kilde: %s';
$Definition['Vanilla Statistics are currently disabled'] = 'Vanilla Statistics er deaktivert for øyeblikket';
$Definition['Verify and restore'] = 'Bekreft og gjenopprett';
$Definition['VerifyUser'] = 'Merk av i boksen ved siden av brukeren for å merke dem som <b>bekreftet,</b> slik at innleggene deres ikke blir merket som søppelpost igjen. Dette vil også gjenopprette alle deres ventende innlegg.';
$Definition['Video tutorial on advanced settings'] = 'Opplæringsvideo om avanserte innstillinger';
$Definition['Video tutorial on finding &amp; managing users'] = 'Opplæringsvideo om å finne & administrere brukere';
$Definition['Video tutorial on managing appearance'] = 'Opplæringsvideo om administrering av utseende';
$Definition['Video tutorial on managing categories'] = 'Opplæringsvideo om administrering av kategorier';
$Definition['Video tutorial on managing roles &amp; permissions'] = 'Opplæringsvideo om administrerende roller & tillatelser';
$Definition['Video tutorial on user registration'] = 'Opplæringsvideo om brukerregistrering';

$Definition['Warning: Enabling this feature may cause Javascript errors on your site.'] = 'Advarsel: Aktivering av denne funksjonen kan forårsake Javascript-feil på nettstedet ditt.';
$Definition['Warning: Loading tables can be slow.'] = '<b>Advarsel</b> : <b>Serverkonfigurasjonen</b> din støtter ikke rask datainnlasting. Hvis du importerer en veldig stor fil (eks. Over 200 000 kommentarer), kan det være lurt å vurdere å endre konfigurasjonen. Klikk <a href="http://vanillaforums.com/porter">her</a> for mer informasjon.';
$Definition['Warning: This is for advanced users.'] = '<b>Advarsel</b>: Denne er for avanserte brukere og krever at du gjør ytterligere endringer på nettserveren din. Denne er vanligvis bare tilgjengelig hvis du har dedikert eller VPS-hosting. Ikke forsøk dette hvis du ikke vet hva du driver med.';
$Definition['Welcome to Labs!'] = 'Velkommen til Labs!';
$Definition['Welcome to Vanilla\'s theming UI.'] = 'Velkommen til Vanillas tema-brukergrensesnitt. Denne siden viser alle tilgjengelige temaer, og lar deg kopiere eller redigere dem.';
$Definition['Welcome To Your Theme'] = 'Velkommen til ditt tema';
$Definition['We recommend mostly positive reactions to encourage participation.'] = 'Vi anbefaler for det meste positive reaksjoner for å oppmuntre til deltakelse.';
$Definition['When enabled, you can manage products, and group subcommunities by those products.'] = 'Når dette er aktivert, kan du administrere produkter og gruppere underkommuner etter disse produktene.';
$Definition['When someone shares a link from your site we try and grab an image from the page. If there isn\'t an image on the page then we\'ll use this image instead. The image should be at least 50×50, but we recommend 200×200.'] = 'Når noen deler en lenke fra nettstedet ditt, prøver vi å ta et bilde fra siden. Hvis det ikke er et bilde på siden, bruker vi dette bildet i stedet. Bildet skal være minst 50 × 50, men vi anbefaler 200 × 200.';
$Definition['When you select Full Bleed, your background is transparent.'] = 'Når du velger Full blødning, er bakgrunnen din gjennomsiktig.';
$Definition['Whether or not the internal profile fields will be included in this webhook.'] = 'Hvorvidt de interne profilfeltene vil bli inkludert i denne webhooken.';
$Definition['Whether or not the private profile fields will be included in this webhook.'] = 'Hvorvidt de private profilfeltene vil bli inkludert i denne webhooken.';
$Definition['Which reactions you use really depends on your community.'] = 'Hvilke reaksjoner du bruker, avhenger av samfunnet ditt, men vi anbefaler at du husker et par poeng.';

$Definition['You are about to apply a new layout option. This can be customized and previewed using our Theme Editor. <0>Learn more</0>.'] = 'Du er i ferd med å bruke et nytt layoutalternativ. Dette kan tilpasses og forhåndsvises ved hjelp av temaredigereren. <0> Finn ut mer</0> .';
$Definition['You can ban all users with an IP addresses prefixed with "111.111.111" by adding an IP-type ban with the value "111.111.111.*".'] = 'Du kan blokkere alle brukere med en IP-adresse som begynner med "111.111.111" ved å legge til blokkering for IP-adressetyper med verdien "111.111.111.*".';
$Definition['You can ban IP addresses, email addresses and usernames.'] = 'Du kan blokkere IP-adresser, e-postadresser og brukernavn.';
$Definition['You can choose from one of the different styles this theme offers.'] = 'Du kan velge mellom en av de forskjellige stilene dette temaet tilbyr.';
$Definition['You can configure some values differently for different screensizes.'] = 'Du kan konfigurere noen verdier på en annen måte for forskjellige skjermbilder.';
$Definition['You can connect to multiple sites that support jsConnect.'] = 'Du kan koble til flere sider som støtter jsConnect.';
$Definition['You can place files in your /uploads folder.'] = 'Hvis filen din er for stor til å laste opp direkte til denne siden, kan du plassere den i mappen din / opplastinger. Kontroller at filnavnet begynner med ordet <b>eksporter</b> og slutter med en av <b>.txt, .gz</b>.';
$Definition['You can specify a minimum post length to discourage short posts.'] = 'Du kan spesifisere en minste innleggslengde for å motvirke korte innlegg.';
$Definition['You can upload a Custom Font in your Theming System. Just copy & paste the URL in the field.'] = 'Du kan laste opp en egendefinert skrift i ditt temasystem. Bare kopier og lim inn URL-en i feltet.';
$Definition['You must select a file to import.'] = 'Du må velge en fil som skal importeres.';
$Definition['You need to add the font url’s domain to <0>AllowedDomains</0>, in the site\'s configuration. <1>Learn more about custom fonts.</1>.'] = 'Du må legge til url-domenet til <0> Tillatte domener </0> i nettstedets konfigurasjon. <1> Lær mer om tilpassede skrifter. </1>';
$Definition['Your mobile theme will be disabled.'] = 'Mobiltemaet ditt blir deaktivert. Hvis du vil angi forskjellige mobil- og stasjonære temaer, bruker du det gamle tema-brukergrensesnittet.';
$Definition['Your organization name is used for SEO microdata and JSON+LD'] = 'Din organisasjons navn brukes for SEO-mikrodata og JSON+LD';
$Definition['Your site\'s favicon appears in your browser\'s title bar. It will be scaled down appropriately.'] = 'Favikonet til siden din vises i din nettlesers tittellinje. Det vil skaleres ned til å passe.';
