<?php

$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s aksepterte invitasjon fra %4$s.';
$Definition['%1$s changed %4$s permissions.'] = '%1$s endret rettighetene til %4$s.';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s endret profilbildet til %6$s.';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s kommenterte %4$s sin %8$s .';
$Definition['%1$s created an account for %4$s.'] = '%1$s laget en konto for %4$s.';
$Definition['%1$s joined.'] = '%1$s registrerte seg.';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s nevnte %3$s i en %8$s.';
$Definition['%1$s on %2$s'] = '%1$s på %2$s';
$Definition['%1$s signed in.'] = '%1$s logget inn.';
$Definition['%1$s to %2$s'] = '%1$s til %2$s';
$Definition['%1$s to %2$s of %3$s'] = '%1$s til %2$s av %3$s';
$Definition['%1$s updated %6$s profile.'] = '%1$s oppdaterte profilen til %6$s.';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s ble lagt til %2$s sin %3$s  .';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s ble fjernet fra %2$s sin %3$s  .';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s ble fjernet fra %2$s %3$s og lagt til %4$s %5$s.';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s skrev på %5$s %4$s.';
$Definition['%3$s approved %2$s membership application.'] = '%3$s validerte medlemskap for %2$s.';
$Definition['%3$s created an account for %1$s.'] = '%3$s laget konto for %1$s.';
$Definition['%s$1 to %s$2'] = '%s$1 til %s$2';
$Definition['%s$1 to %s$2 of %s$3'] = '%s$1 til %s$2 av %s$3';
$Definition['%s (Current)'] = '%s (Nåværende)';
$Definition['%s Agrees'] = '%s Er enig';
$Definition['%s and you'] = '%s og deg';
$Definition['%s Awesomes'] = '%s Kjempebra';
$Definition['%s changed %s\'s permissions.'] = '%s endret %s\'s rettigheter.';
$Definition['%s Comment'] = '%s Kommentar';
$Definition['%s comment'] = '%s kommentar';
$Definition['%s Comments'] = '%s sine kommentarer.';
$Definition['%s comments'] = '%s sine kommentarer.';
$Definition['%s Connect'] = '%s Koble til';
$Definition['%s deleted this conversation.'] = '%s slettet denne samtalen.';
$Definition['%s discussion'] = '%s diskusjon';
$Definition['%s discussions'] = '%s diskusjoner';
$Definition['%s has left this conversation.'] = '%s har forlatt denne samtalen.';
$Definition['%s hour'] = '%s time';
$Definition['%s hours'] = '%s timer';
$Definition['%s Insightfuls'] = '%s Innsiktsfull';
$Definition['%s level deep'] = '%s dybdenivå';
$Definition['%s Likes'] = '%s Liker';
$Definition['%s member'] = '%s medlem';
$Definition['%s mentioned %s in a %s.'] = '%s nevnte %s i en %s.';
$Definition['%s message'] = '%s melding';
$Definition['%s messages'] = '%s meldinger';
$Definition['%s minute'] = '%s minutt';
$Definition['%s minutes'] = '%s minutter';
$Definition['%s month'] = '%s måned';
$Definition['%s months'] = '%s måneder';
$Definition['%s New'] = '%s Ny';
$Definition['%s new'] = '%s ny';
$Definition['%s new comment since you last read this.'] = '%s nye kommentar siden du sist leste dette. ';
$Definition['%s new comments since you last read this.'] = '%s nye kommentarer siden du leste dette sist.';
$Definition['%s New Plural'] = '%s Nytt flertall';
$Definition['%s new plural'] = '%s ny';
$Definition['%s Not Found'] = '%s Ikke funnet';
$Definition['%s Point'] = '%s poeng';
$Definition['%s point'] = '%s poeng';
$Definition['%s Points'] = '%s poeng';
$Definition['%s points'] = '%s poeng';
$Definition['%s result'] = '%s resultat';
$Definition['%s said'] = '%s sa';
$Definition['%s said:'] = '%s sa:';
$Definition['%s tag(s) found.'] = '%s tagg(er) funnet.';
$Definition['%s Up Votes'] = '%s Stemmer opp';
$Definition['%s view'] = '%s visning';
$Definition['%s views'] = '%s visninger';
$Definition['%s votes'] = '%s stemmer';
$Definition['%s was removed from the %s and added to the %s'] = '%s ble fjernet fra %s og lagt til %s';
$Definition['%s week'] = '%s uke';
$Definition['%s year'] = '%s år';
$Definition['%s years'] = '%s år';

$Definition['(All)'] = '(Alle)';

$Definition[' - Page %s'] = ' - Side %s';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Medlemskap godkjent';
$Definition['[%s] Welcome Aboard!'] = '[%s] Velkommen til forumet!';

$Definition['About'] = 'Info';
$Definition['Account Options'] = 'Kontoalternativer';
$Definition['Activate'] = 'Aktiver';
$Definition['Active'] = 'Aktiv';
$Definition['Active Users'] = 'Aktive brukere';
$Definition['Activity'] = 'Aktivitet';
$Definition['Activity.AnswerAccepted.FullHeadline'] = '%1$s aksepterte %4$s %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s kommenterte på din %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s kommenterte på din %8$s.';
$Definition['Activity.Comment'] = 'Kommentar';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s nevnte %3$s i en %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s nevnte %3$s i en %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s sendte deg %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s sendte deg %8$s.';
$Definition['Activity.Join.FullHeadline'] = '%1$s registrerte seg.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s registrerte seg.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s endret profilbildet til %6$s.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s endret profilbildet til %6$s.';
$Definition['Activity.QuestionAnswer.FullHeadline'] = '%1$s svarte %4$s %8$s.';
$Definition['Add'] = 'Legg til';
$Definition['Add a Comment'] = 'Legg til en kommentar';
$Definition['Add a Message'] = 'Legg til en melding';
$Definition['Add another poll option ...'] = 'Legg til et annet avstemmingsalternativ';
$Definition['Add a Profile Picture'] = 'Legg til profilbilde';
$Definition['Add a Warning'] = 'Legg til advarsel';
$Definition['Add Badge'] = 'Legg til merke';
$Definition['Add Comment'] = 'Legg til kommentar';
$Definition['Add Cost'] = 'Legg til kostnad';
$Definition['Add Image'] = 'Legg til bilde';
$Definition['Add Message'] = 'Legg til melding';
$Definition['Add Note'] = 'Legg til notat';
$Definition['Add People to this Conversation'] = 'Legg til personer i denne samtalen';
$Definition['Add Route'] = 'Legg til rute';
$Definition['Administrator Activity'] = 'Administrator-aktivitet';
$Definition['administrators'] = 'administratorer';
$Definition['Advanced Stuff'] = 'Avanserte saker';
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = 'En fatal feil har skjedd mens forumet prøvde å gjennomføre forespørselen.<br />Serveren ga følgende respons før den begikk seppuku - %s';
$Definition['Agree'] = 'Godta';
$Definition['Alert'] = 'Advarsel';
$Definition['All %s'] = 'Alle %s';
$Definition['All Bookmarks'] = 'Alle bokmerker';
$Definition['All Categories'] = 'Alle kategorier';
$Definition['all categories'] = 'alle kategorier';
$Definition['All Conversations'] = 'Alle samtaler';
$Definition['All Discussions'] = 'Alle diskusjoner';
$Definition['Allow'] = 'Godta';
$Definition['Allow other members to see your email?'] = 'Tillat andre brukere å se min e-post adresse?';
$Definition['All Time Leaders'] = 'Beste ledere';
$Definition['Ancient Membership'] = 'Eldgammelt medlemsskap ';
$Definition['An invitation has already been sent to the email you entered.'] = 'En invitasjon har allerede blitt sendt til denne e-post adressen.';
$Definition['Announce'] = 'Kunngjør';
$Definition['Announce...'] = 'Annonser...';
$Definition['Announcement'] = 'Annonsering';
$Definition['Announcements'] = 'Annonseringer';
$Definition['Announce this discussion'] = 'Kunngjør diskusjon';
$Definition['Answer'] = 'Svar';
$Definition['answer'] = 'svar';
$Definition['Answers'] = 'Svar';
$Definition['Applicant'] = 'Søker rolle';
$Definition['Applicants'] = 'Søker';
$Definition['Applicants & Invitations'] = 'Søkere &invitasjoner';
$Definition['Apply Changes'] = 'Bruk endringer';
$Definition['Apply for Membership'] = 'Registrer deg';
$Definition['Apply for membership'] = 'Registrer deg';
$Definition['Approve'] = 'Godkjenn';
$Definition['Approve Applicant'] = 'Godkjenn';
$Definition['Are you ABSOLUTELY sure you want to take this action?'] = 'Er du HELT sikker på at du ønsker å utføre denne handlingen?';
$Definition['Are you sure you want to delete this %s?'] = 'Er du sikker på at du ønsker å slette dette %s?';
$Definition['Are you sure you want to do that?'] = 'Sikker på dette?';
$Definition['Are you sure you want to do this?'] = 'Er du sikker på at du ønsker å gjøre dette?';
$Definition['Are you sure you want to join this group?'] = 'Er du sikker på at du ønsker å bli med denne gruppen?';
$Definition['Are you sure you want to leave this group?'] = 'Er du sikker på at du ønsker å forlate denne gruppen?';
$Definition['Are you sure you wish to continue?'] = 'Er du sikker på at du ønsker å fortsette?';
$Definition['Ask a Question'] = 'Still et spørsmål';
$Definition['Ask Question'] = 'Publiser diskusjon';
$Definition['Attach a file'] = 'Legg til en fil';
$Definition['Attachments'] = 'Vedlegg';
$Definition['Attach this warning to the %s.'] = 'Legg ved denne advarselen til %s. ';
$Definition['AttemptingSignOut'] = 'Du forsøker å logge deg inn. Er du sikker på at du ønsker å %s?';
$Definition['Authenticate URL'] = 'Verifiser URL';
$Definition['Author'] = 'Forfatter';
$Definition['available'] = 'tilgjengelig';
$Definition['Awaiting Moderation'] = 'Venter på moderering';
$Definition['Awesome'] = 'Herlig';

$Definition['Back to Discussions'] = 'Tilbake til diskusjonen.';
$Definition['Back to Profile'] = 'Tilbake til profil';
$Definition['Badge'] = 'Merke';
$Definition['Badge404'] = 'Merke ikke funnet. ';
$Definition['Badges'] = 'Merker';
$Definition['BadgesModuleTitle'] = 'Merker';
$Definition['BadgesNobody'] = 'Ingen har fått dette merket ennå. ';
$Definition['Ban'] = 'Bortvis';
$Definition['Ban.Action'] = 'Bortvis ';
$Definition['Banned'] = 'BÆNNA';
$Definition['Banned for being abusive.'] = 'Bortvist for grovt språk. ';
$Definition['Banned for spamming.'] = 'Bortvist for spamming';
$Definition['Banned users can no longer access the site.'] = 'Bortviste brukere har ikke lenger tilgang til siden. ';
$Definition['Banner'] = 'Fane';
$Definition['Ban User'] = 'Bortvis bruker';
$Definition['Ban Value'] = 'Forby verdi';
$Definition['Best Answer'] = 'Beste svar';
$Definition['Best Answers'] = 'Beste svar';
$Definition['Best Of'] = 'De beste';
$Definition['Best Of...'] = 'De beste...';
$Definition['Blank Discussion Topic'] = 'Tomt diskusjonsemne';
$Definition['Blank Message'] = 'Tom melding';
$Definition['Blog'] = 'Blogg';
$Definition['Blogs'] = 'Blogger';
$Definition['Body'] = 'Gruppe';
$Definition['Bold'] = 'Uthevet';
$Definition['Bookmark'] = 'Legg til bokmerke';
$Definition['Bookmarked Discussions'] = 'Bokmerkede diskusjoner';
$Definition['Bookmarks'] = 'Bokmerker';
$Definition['bookmarks'] = 'bokmerker';
$Definition['By'] = 'Av';
$Definition['by'] = 'av';
$Definition['by Date'] = 'etter dato';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Ved å laste opp en fil bekrefter du at du har rett til å distribuere dette bildet og at det ikke bryter vilkårene for bruk.';

$Definition['Cancel'] = 'Annuller';
$Definition['Categories'] = 'Kategorier';
$Definition['CategoriesShowFollowed'] = 'Klikk her for å se kategorier du følger';
$Definition['CategoriesShowUnfollowed'] = 'Klikk her for å se kategorier du ikke følger';
$Definition['CategoriesViewingAll'] = 'Du ser nå alle kategoriene på forumet.';
$Definition['CategoriesViewingFollowed'] = 'Du ser nå bare kategoriene du følger på forumet.';
$Definition['Category'] = 'Kategori';
$Definition['Category Filter'] = 'Kategorifilter';
$Definition['CategoryID'] = 'Kategori';
$Definition['Category Management'] = 'Behandle kategorier';
$Definition['Category Notifications'] = 'Kategorivarsling';
$Definition['Category to Use'] = 'Kategori å bruke';
$Definition['Change'] = 'Endre';
$Definition['Change language'] = 'Endre språk';
$Definition['Change My Password'] = 'Endre mitt passord';
$Definition['Change My Picture'] = 'Endre bildet mitt';
$Definition['Change Password'] = 'Endre passord';
$Definition['Change Picture'] = 'Endre bilde';
$Definition['Check all roles that apply to this user:'] = 'Velg alle roller som gjelder for denne brukeren:';
$Definition['Child Categories'] = 'Barnekategorier';
$Definition['Child Categories:'] = 'Barnekategorier:';
$Definition['Choose a name to identify yourself on the site.'] = 'ConnectChooseName';
$Definition['Choose the main discussion into which all comments will be merged:'] = 'Velg hoveddiskusjon hvor alle kommentarene blir samlet:';
$Definition['Choose whether you want to ask a question or start a discussion.'] = 'Velg hvorvidt du ønsker å stille et spørsmål for å starte en diskusjon. ';
$Definition['Clear'] = 'Rens innhold';
$Definition['clear'] = 'slett';
$Definition['Clear Conversation History'] = 'Slett samtalehistorikk';
$Definition['Click <a href="%s">here</a> to go back to the discussion.'] = 'Klikk <a href="%s">her</a> for å gå tilbake til diskusjonen. ';
$Definition['Click accept or reject beside an answer.'] = 'Klikk aksepter eller avvis ved siden av et svar. ';
$Definition['clicking here'] = 'klikke her';
$Definition['Click the %s beside discussions to bookmark them.'] = 'Klikk %s sidediskusjonen for å bokmerke dem. ';
$Definition['Close'] = 'Lukk';
$Definition['Closed'] = 'Lukket';
$Definition['Close this discussion'] = 'Lukk denne diskusjonen';
$Definition['Color'] = 'Farge';
$Definition['Comment'] = 'Kommentar';
$Definition['comment'] = 'kommenter';
$Definition['Comment As ...'] = 'Kommenter som...';
$Definition['Comment by %s'] = 'Kommentarer av %s';
$Definition['Comment in'] = 'i';
$Definition['Commenting as %1$s (%2$s)'] = 'Kommenterer som  %1$s <span class="SignOutWrap">(%2$s)</span>';
$Definition['Commenting not allowed.'] = 'Kommentering ikke tillatt';
$Definition['Comments'] = 'Kommentarer';
$Definition['comments'] = 'kommentarer';
$Definition['Comments are between {UserID,you}.'] = 'Kommentarer er mellom {Bruker-ID, deg}. ';
$Definition['Community'] = 'Samfunn';
$Definition['Community Guidelines'] = 'Retningslinjer for samfunn';
$Definition['Completely delete the warning.'] = 'Slett hele advarselen';
$Definition['Confirm'] = 'Godkjenn';
$Definition['Confirm Email'] = 'Bekreft e-post';
$Definition['Confirm Password'] = 'Godkjenn passord';
$Definition['Connect'] = 'Koble';
$Definition['ConnectCreateAccount'] = 'Legg til info &amp; Opprett konto';
$Definition['Connected'] = 'Koblet til';
$Definition['ConnectExistingPassword'] = 'Skriv inn ditt eksisterende kontopassord. ';
$Definition['Connecting...'] = 'Kobler til...';
$Definition['Connection'] = 'Tilkobling';
$Definition['ConnectName'] = 'Brukernavn';
$Definition['Contact Us'] = 'Kontakt oss';
$Definition['conversation'] = 'samtale';
$Definition['Core'] = 'Kjerne';
$Definition['Created'] = 'Opprettet';
$Definition['Create Discussions'] = 'Opprett diskusjoner';
$Definition['Create One.'] = 'Lag en.';
$Definition['Current'] = 'Nåværende';
$Definition['Currently: '] = 'Nå:';
$Definition['Custom Information'] = 'Tilpasset informasjon';
$Definition['Customize'] = 'Tilpass';
$Definition['customize your profile now'] = 'spesialtilpass profilen din nå';
$Definition['Customize your Public Profile'] = 'Tilpass din offentlig profil. ';
$Definition['Custom Profile Fields'] = 'Tilpassete profilfelt';
$Definition['Custom Profile Field Settings'] = 'Spesialtilpassete innstillinger for profilfelt';

$Definition['Dashboard'] = 'Administrasjon';
$Definition['Dashboard Home'] = 'Dashboard hjem';
$Definition['Dashboard Summaries'] = 'Dashboard-sammendrag';
$Definition['Date'] = 'Applied On';
$Definition['Date Added'] = 'Dato lagt til';
$Definition['Date Examples'] = 'Eksempler: Mandag, i dag, forrige uke, 26.mars.04';
$Definition['Date within'] = 'Dato innenfor';
$Definition['days'] = 'dager';
$Definition['Define Thumbnail'] = 'Klikk og dra over bildet for å definere ditt thumbnail-bilde.';
$Definition['Delete'] = 'Slett';
$Definition['Delete %s'] = 'Slett %s';
$Definition['Delete Account'] = 'Slett konto';
$Definition['Delete Conversation'] = 'Slett samtale';
$Definition['Delete Discussion'] = 'Slett diskusjon';
$Definition['Delete Group'] = 'Slett gruppe';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Slett brukeren og hele brukerens innhold. Dette vil gjøre at diskusjoner vil bli usammenhengende, slik at det virker som folk svarer på innhold som ikke er der. Dette er en flott mulighet til å fjerne spam-innhold. ';
$Definition['Delete User Content'] = 'Slett brukerinnhold';
$Definition['Delete User Forever'] = 'Slett bruker for alltid';
$Definition['Deny'] = 'Nekt';
$Definition['Deny Applicant'] = 'Nekt';
$Definition['Did this answer the question?'] = 'Besvarte dette spørsmålet?';
$Definition['Disagree'] = 'Uenig';
$Definition['Discussion'] = 'Diskusjon';
$Definition['discussion'] = 'diskusjon';
$Definition['Discussion Board'] = 'Diskusjonspanel';
$Definition['Discussions'] = 'Diskusjoner';
$Definition['discussions'] = 'diskusjoner';
$Definition['Discussions Page'] = 'Diskusjonsside';
$Definition['Discussion Title'] = 'Diskusjonstittel';
$Definition['Dislike'] = 'Mislike';
$Definition['Dismiss'] = 'Annulér';
$Definition['Don\'t announce.'] = 'Ikke annonser';
$Definition['Don\'t fold quotes'] = 'Ikke gjem sitater';
$Definition['Don\'t have an account? %s'] = 'Har du ikke konto? %s';
$Definition['Do you want to expire or delete this warning?'] = 'Ønsker du å slette eller la advarselen utløpe?';
$Definition['Draft saved at %s'] = 'Utkast lagret på %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Dra rundt og endre størrelsen på plassen nedenfor for å definere ikonet.';

$Definition['Earned'] = 'Tjent';
$Definition['Edit'] = 'Rediger';
$Definition['Edit Account'] = 'Rediger konto';
$Definition['Edit Comment'] = 'Rediger kommentar';
$Definition['Edit Discussion'] = 'Rediger Diskusjon';
$Definition['edited %s'] = 'redigerte %s';
$Definition['Edit My Account'] = 'Rediger min konto';
$Definition['Edit My Profile'] = 'Rediger min profil';
$Definition['Edit My Thumbnail'] = 'Rediger ikon';
$Definition['editor.BBCodeHelpText'] = 'Du kan bruke <a href="http://en.wikipedia.org/wiki/BBCode" target="_new">BBCode</a> i innlegget ditt. ';
$Definition['editor.HtmlHelpText'] = 'Du kan bruke <a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">enkel html</a> i innlegget ditt. ';
$Definition['editor.MarkdownHelpText'] = 'Du kan bruke <a href="http://en.wikipedia.org/wiki/Markdown" target="_new">Markdown </a> i innlegget ditt. ';
$Definition['editor.TextHelpText'] = 'Du bruker klartekst i innlegget ditt. ';
$Definition['editor.WysiwygHelpText'] = 'Du bruker <a href="https://en.wikipedia.org/wiki/WYSIWYG" target="_new">Wysiwyg</a> i innlegget ditt. ';
$Definition['Edit Preferences'] = 'Rediger preferanser';
$Definition['Edit Profile'] = 'Rediger profil';
$Definition['Edit Tag'] = 'Rediger tagg';
$Definition['Edit Thumbnail'] = 'Rediger thumbnail';
$Definition['Eighth Anniversary'] = 'Åtte års jubileum';
$Definition['Email'] = 'E-post';
$Definition['Email/Username'] = 'Epost/brukernavn';
$Definition['EmailConfirmEmail'] = 'Du må bekrefte e-postadressen din før du kan fortsette. Vennligst bekreft e-postadressen din ved å trykke på følgende lenke: ';
$Definition['EmailFooter'] = '
Ha en super dag!';
$Definition['EmailHeader'] = 'Hei {User.Name}!
';
$Definition['EmailInvitation'] = 'Hei! 

%1$s har invitert deg til å bli med i/på %2$s. Hvis du vil bli med, kan du gjøre det ved å klikke på denne lenken: 

%3$s';
$Definition['EmailNotification'] = '%1$s 

Følg lenken under for å ta en titt: 
%2$s

Ha en fin dag!';
$Definition['Email Notifications'] = 'E-post varsler';
$Definition['Email Or Username'] = 'E-post eller brukernavn';
$Definition['EmailPassword'] = '%2$s har endret ditt passord på %3$s. Dine innloggingsreferanser er nå: 

E-post: %6$s
Passord: %5$s
Url: %4$s';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'E-post sendt fra applikasjonen vil bli adressert fra følgende navn og adresse';
$Definition['Email Source'] = 'E-post';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Følg lenken under for å ta en titt:
%2$s

Ha en fin dag!';
$Definition['Email Unavailable'] = 'Email utilgjengelig';
$Definition['Email visible to other users'] = 'E-post adresse er synlig for andre brukere.';
$Definition['EmailWelcome'] = '%2$s har opprettet en konto for deg på %3$s. Dine innloggingsreferanser er: 

E-post: %6$s
Passord: %5$s
Url: %4$s';
$Definition['EmailWelcomeConnect'] = 'Tilkoblingen til {Tittel} var vellykket. Her er din informasjon: 

Brukernavn: {User.Name}
Koblet til: {ProviderName}

Du kan få tilgang til siden på {/,exurl,domain}.';
$Definition['EmailWelcomeRegister'] = 'Du har registrert deg hos {Title}. Her er din påloggingsinformasjon:

  Brukernavn: {User.Name}
  Epost: {User.Email}

Du finner forumet på {/,exurl,domain}.';
$Definition['EmbeddedDiscussionFormat'] = '<div class="EmbeddedContent">Bilde}<strong>{Tittel}</strong>
<p>{Utdrag}</p>
<p><a href="{Url}">Les hele historien her</a></p><div class="ClearFix"></div></div>
';
$Definition['EmbededDiscussionFormat'] = '<div class="EmbeddedContent">{Bilde}<strong>{Tittel}</strong>
<p>{Utdrag}</p>
<p><a href="{Url}">Les hele historien her</a></p><div class="ClearFix"></div></div>';
$Definition['English'] = 'Engelsk';
$Definition['Enter your Email address'] = 'Skriv inn din e-post adresse';
$Definition['Enter your email address'] = 'Oppgi din epostadresse';
$Definition['Enter your Email address or username'] = 'Skriv inn epost-adresse eller brukernavn';
$Definition['Erase User Content'] = 'Slett brukerinnhold';
$Definition['Error'] = 'Feil';
$Definition['ErrorBadInvitationCode'] = 'Feil: ikke gyldig invitasjons-kode.';
$Definition['ErrorCredentials'] = 'Beklager, vi kan ikke finne noen konto som er relatert til eposten/brukernavnet og passordet du oppga.';
$Definition['ErrorPermission'] = 'Beklager, tilgang nektet.';
$Definition['ErrorPluginDisableRequired'] = 'Du kan ikke deaktivere programtillegget {0} fordi programtillegget {1} krever det for å fungere. ';
$Definition['ErrorPluginEnableRequired'] = 'Dette programtillegget krever at programtillegget {0} deaktiveres før det kan aktivere seg selv.';
$Definition['ErrorPluginVersionMatch'] = 'Den aktiverte {0} programtillegget (versjon {1}) oppfylte ikke versjonskravene ({2}).';
$Definition['ErrorRecordNotFound'] = 'Det forespurte opptaket ble ikke funnet.';
$Definition['ErrorTermsOfService'] = 'Du må akseptere betingelsene.';
$Definition['Event'] = 'Arrangement';
$Definition['Events'] = 'Arrangement';
$Definition['everyone'] = 'alle';
$Definition['Everything'] = 'Alt';
$Definition['Expired'] = 'Utløpt';
$Definition['Expires'] = 'Utløper';

$Definition['Failed to delete group.'] = 'Greide ikke å slette gruppe. ';
$Definition['Failed to find discussion for commenting.'] = 'Mislyktes med å finne diskusjon for å kommentere.';
$Definition['Failed to load the poll.'] = 'Kunne ikke laste avstemningen. ';
$Definition['Feedback'] = 'Tilbakemeldinger';
$Definition['Female'] = 'Kvinne';
$Definition['Fifth Anniversary'] = 'Femårsjubileum';
$Definition['FileName'] = 'Filnavn';
$Definition['Filename'] = 'Filenavn';
$Definition['FileSize'] = 'Filstørrelse';
$Definition['File Size'] = 'Filstørrelse';
$Definition['First Anniversary'] = 'Årsjubileum';
$Definition['First Comment'] = 'Første kommentar';
$Definition['Flag'] = 'Flagge';
$Definition['Follow %s'] = 'Følg %s';
$Definition['Followed by %d people'] = 'Fulgt av %d personer';
$Definition['Followed by %d person'] = 'Fulgt av %d person';
$Definition['followed categories'] = 'kategorier du følger';
$Definition['Following %d people'] = 'Følger %d personer';
$Definition['Following %d person'] = 'Følger %d person';
$Definition['Follows'] = 'Følgere';
$Definition['Forgot?'] = 'Glemt?';
$Definition['Forgot your password?'] = 'Glemt passord?';
$Definition['Format his'] = 'hans';
$Definition['Format their'] = 'deres';
$Definition['Format You'] = 'Du';
$Definition['Format you'] = 'du';
$Definition['Format Your'] = 'Din';
$Definition['Forums'] = 'Forumer';
$Definition['Fourth Anniversary'] = 'Fireårsjubileum';
$Definition['Friends'] = 'Venner';
$Definition['Full Site'] = 'Hele siden';

$Definition['Garden.Email.SupportAddress'] = 'Brukerstøtte e-post';
$Definition['Garden.Email.SupportName'] = 'Brukerstøtte navn';
$Definition['Garden.Title'] = 'Banner-tittel';
$Definition['Gender'] = 'Kjønn';
$Definition['General'] = 'Generelt';
$Definition['Generate import SQL only'] = 'Generer import kun SQL';
$Definition['Generate Password'] = 'Generer passord';
$Definition['Give'] = 'Gi';
$Definition['Give a Badge to %s'] = 'Gi et merke til %s';
$Definition['Give Badge'] = 'Gi merke';
$Definition['Given'] = 'Gitt';
$Definition['Go'] = 'Søk';
$Definition['Group'] = 'Gruppe';
$Definition['group'] = 'gruppe';
$Definition['GroupEmptyAnnouncements'] = 'Viktige saker vil skje her en dag. ';
$Definition['GroupEmptyDiscussions'] = 'Fryktelig stille her inne, er det &rsquo; ikke?';
$Definition['GroupEmptyEvents'] = 'Søren, ingen kommende arrangement. ';
$Definition['Group Info'] = 'Gruppeinfo';
$Definition['Group Leaders'] = 'Ledere';
$Definition['Group Members'] = 'Medlemmer';
$Definition['GroupMembersEmpty'] = 'Ingen har blitt med ennå. Spre ordet!';
$Definition['Groups'] = 'Grupper';
$Definition['groups'] = 'grupper';
$Definition['Guest'] = 'Gjest';
$Definition['GuestModule.Message'] = 'For å engasjere deg på denne siden, klikk på en av disse knappene:';

$Definition['Hang on a sec while we sign you out.'] = 'Slapp av et par sekunder mens vi logger deg av.';
$Definition['he'] = 'han';
$Definition['HeadlineFormat.Ban'] = '{RegardingUserID,You} utestengte {ActivityUserID,you}.';
$Definition['HeadlineFormat.Comment'] = '{ActivityUserID,user} kommenterte på <a href="{Url,html}">{Data.Name,text}</a>
';
$Definition['HeadlineFormat.PictureChange.ForUser'] = '{RegardingUserID,You} endret profilbildet for {ActivityUserID,you}.';
$Definition['HeadlineFormat.Registration'] = '{ActivityUserID,You} ble med som deltaker.';
$Definition['HeadlineFormat.Unban'] = '{RegardingUserID,You} opphevet utestengelsen for {ActivityUserID,you}.';
$Definition['her'] = 'hennes';
$Definition['Hide my online status from other members'] = 'Skjul min pålogningsstatus for andre medlemmer';
$Definition['Hide signatures?'] = 'Gjemme signaturer? ';
$Definition['Hide signatures always'] = 'Alltid skjul signatur';
$Definition['Hide signatures on my mobile device'] = 'Skjul signatur på mobilenhet';
$Definition['his'] = 'hans';
$Definition['Home'] = 'Hjem';
$Definition['hours'] = 'timer';
$Definition['Howdy, Stranger!'] = 'Velkommen!';
$Definition['How long do you want this warning to last?'] = 'Hvor lenge vil du at denne varslingen skal vare?';
$Definition['How many levels deep should we start folding up quote trees?'] = 'Når skal vi begynne å gjemme sitatstrær? ';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Jeg aksepterer <a id="TermsOfService" class="Popup" target="terms" href="%s">betingelsene.</a>';
$Definition['Icon'] = 'Ikon';
$Definition['Ignore'] = 'Ignorer';
$Definition['Ignore List'] = 'Ignorer-liste';
$Definition['Ignore Someone'] = 'Ignorer noen';
$Definition['Image'] = 'Bilde';
$Definition['Image URL'] = 'Bilde-URL';
$Definition['in'] = 'i';
$Definition['In <b>%s.</b>'] = 'I <b>%s.</b>';
$Definition['Inbox'] = 'Innboks';
$Definition['Indent'] = 'Innrykk';
$Definition['In recent discussions.'] = 'I nylige diskusjoner. ';
$Definition['Insert Image'] = 'Sett inn bilde';
$Definition['Internal'] = 'Internt';
$Definition['In this Conversation'] = 'I denne samtalen';
$Definition['Invalid password.'] = 'Passordet du skrev var feil. Husk å skille mellom små og store bokstaver når du skriver passordet. ';
$Definition['Invite'] = 'Invitér';
$Definition['InviteErrorPermission'] = 'Beklager, tilgang nektet.';
$Definition['Invite Friends'] = 'Inviter venner';
$Definition['Invite friends'] = 'Inviter venner';
$Definition['IP Address'] = 'IP-adresse';
$Definition['IPAddress'] = 'IP-adresse';
$Definition['I remember now!'] = 'Nå husker jeg det!';
$Definition['Italic'] = 'kursiv';
$Definition['Item'] = 'Ban Item';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = 'For å engasjere deg på denne siden, klikk på en av disse knappene:';

$Definition['Jail'] = 'Fengsel';
$Definition['Joined'] = 'Registrert dato';
$Definition['Joined %s'] = 'Ble med %s';
$Definition['Join this Group'] = 'Bli med i denne gruppen';
$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Bare slett brukeropptaket, og bevar alt brukerinnhold.';
$Definition['Just expire the warning.'] = 'Bare la advarselen utløpe.';

$Definition['Keep me signed in'] = 'Hold meg innlogget';
$Definition['Keep User Content'] = 'UserKeep';

$Definition['Last Active'] = 'Sist aktiv';
$Definition['Last IP'] = 'Siste IP adresse';
$Definition['lasts %s'] = 'varer %s';
$Definition['Latest %1$s'] = 'Siste %1$s';
$Definition['Latest Post'] = 'Siste innlegg';
$Definition['Leaders'] = 'Ledere';
$Definition['Leave a Comment'] = 'Legg igjen en kommentar';
$Definition['Leave a comment'] = 'Legg igjen en kommentar';
$Definition['Leave blank unless connecting to an exising account.'] = 'ConnectLeaveBlank';
$Definition['Leave Comments'] = 'Legg igjen kommentarer';
$Definition['Leave Group'] = 'Forlat gruppen';
$Definition['Length'] = 'Lengde';
$Definition['Level %s'] = 'Nivå %s';
$Definition['Like'] = 'Liker';
$Definition['Link to content:'] = 'Lenke til innhold:';
$Definition['Log'] = 'Logg';

$Definition['Major'] = 'Større';
$Definition['Male'] = 'Mann';
$Definition['Mark All Viewed'] = 'Marker alle som sett';
$Definition['Mark as Troll'] = 'Merk som troll';
$Definition['Marking as spam cannot be undone.'] = 'Markerer du noe som SPAM vil det bli slettet for alltid. Sletting er en god måte å holde forumet ditt rent på. ';
$Definition['Mark Read'] = 'Marker som lest';
$Definition['Member Count'] = 'Medlemmer';
$Definition['Members'] = 'Medlem';
$Definition['Merge'] = 'Fusjonere';
$Definition['Merge Discussions'] = 'Fusjonere diskusjoner ';
$Definition['Message'] = 'Melding';
$Definition['message'] = 'melding';
$Definition['Messages'] = 'Meldinger';
$Definition['messages'] = 'meldinger';
$Definition['Message to User'] = 'Melding til bruker';
$Definition['Minor'] = 'Mindre';
$Definition['Moderation'] = 'Moderering';
$Definition['Moderation Queue'] = 'Modereringskø';
$Definition['Moderator Activity'] = 'Moderator-aktivitet';
$Definition['moderators'] = 'moderatorer';
$Definition['months'] = 'måneder';
$Definition['More'] = 'Mer';
$Definition['More About %s'] = 'Mer om %s';
$Definition['More Comments'] = 'Flere kommentarer';
$Definition['More Discussions'] = 'Flere diskusjoner';
$Definition['More Information'] = 'Mer informasjon';
$Definition['More Results'] = 'Flere resultater';
$Definition['More…'] = 'Mer...';
$Definition['Most Recent'] = 'Siste';
$Definition['Most recent:'] = 'Siste:';
$Definition['Most recent by %1$s'] = 'Nyeste av %1$s';
$Definition['Most Recent Comment'] = 'Siste kommentar';
$Definition['MyBadgesModuleTitle'] = 'Mine skilt';
$Definition['My Bookmarks'] = 'Mine bokmerker';
$Definition['My Discussions'] = 'Mine diskusjoner';
$Definition['My Drafts'] = 'Mine kladder';
$Definition['My Groups'] = 'Mine grupper';
$Definition['My Preferences'] = 'Mine instillinger';

$Definition['Name'] = 'Badge Name';
$Definition['Name the Group'] = 'Sett navn på gruppen';
$Definition['Name Unavailable'] = 'Navn ikke tilgjengelig.';
$Definition['new'] = 'ny';
$Definition['New %s'] = 'Ny %s';
$Definition['New Conversation'] = 'Ny samtale';
$Definition['New Discussion'] = 'Ny diskusjon';
$Definition['new discussion'] = 'ny';
$Definition['New Event'] = 'Nytt arrangement';
$Definition['New Group'] = 'Ny gruppe';
$Definition['New Groups'] = 'Nye grupper';
$Definition['New Message'] = 'Ny samtale';
$Definition['New Password'] = 'Nytt passord';
$Definition['Ninth Anniversary'] = 'Niårsjubileum';
$Definition['No badges yet.'] = 'Ingen skilt enda. ';
$Definition['No discussions were found.'] = 'Ingen diskusjoner ble funnet.';
$Definition['No results for \'%s\''] = 'Ingen resultater for \'%s\'';
$Definition['Not Authorized (401)'] = 'Ikke autorisert (401)';
$Definition['Not Found (404)'] = 'Ikke funnet (404)';
$Definition['Notice'] = 'Varsel';
$Definition['Notification'] = 'Varsling';
$Definition['Notification Preferences'] = 'Varslingsinnstillinger';
$Definition['Notifications'] = 'Varsler';
$Definition['Notifictions'] = 'Varsler';
$Definition['Notify'] = 'Varsle';
$Definition['Notify me of private messages.'] = 'Send meg varsel dersom jeg får en privat melding.';
$Definition['Notify me when a badge is requested.'] = 'Varsle meg når et merke bes om. ';
$Definition['Notify me when a comment is flagged.'] = 'Gi meg beskjed når en kommentar blir flagget.';
$Definition['Notify me when I am added to private conversations.'] = 'Send meg varsel dersom jeg blir lagt til en privat samtale.';
$Definition['Notify me when people comment on discussions I\'ve participated in.'] = 'Varsle meg når folk kommenterer på diskusjoner jeg har deltatt i. ';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Send meg varsel dersom kommenterer i en av mine bokmerkede diskusjoner';
$Definition['Notify me when people comment on my discussions.'] = 'Send meg varsel dersom noen kommenterer i en av mine diskusjoner.';
$Definition['Notify me when people mention me.'] = 'Varsle meg når noen nevner meg.';
$Definition['Notify me when people mention me in comments.'] = 'Send meg varsel dersom noen nevner meg i kommentarer';
$Definition['Notify me when people reply to my wall comments.'] = 'Send meg varsel når noen skriver svar på mine kommentarer';
$Definition['Notify me when people write on my wall.'] = 'Send meg varsel når noen skriver på veggen min';
$Definition['Not much happening here, yet.'] = 'Skjer ikkje så mye hær...';
$Definition['Not Verified'] = 'Ikke verifisert';

$Definition[' now.'] = ' nå.';

$Definition['of'] = 'av';
$Definition['Okay'] = 'Ok';
$Definition['Old Password'] = 'Gammelt passord';
$Definition['OldPassword'] = 'Gammelt passord';
$Definition['on'] = 'på';
$Definition['Online Preferences'] = 'Nettpreferanser';
$Definition['Only show followed categories'] = 'Klikk her for å se kategorier du følger';
$Definition['OpenID Settings'] = 'ÅpenID innstillinger';
$Definition['Optional Description'] = 'Valgfri beskrivelse';
$Definition['Options'] = 'Instillinger';
$Definition['or'] = 'eller';
$Definition['Ordered list'] = 'Liste over bestillinger';
$Definition['Organize discussion categories'] = 'Organiser diskusjonskategorier';
$Definition['Organize your Categories'] = 'Organiser dine kategorier';
$Definition['Or you can...'] = 'Eller så kan du...';
$Definition['Other Records'] = 'Andre arkiv';
$Definition['Outdent'] = 'Innrykk';
$Definition['Owner'] = 'Eier';

$Definition['PageDetailsMessage'] = '%1$s til %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s til %2$s av %3$s';
$Definition['Page Not Found'] = 'Siden ble ikke funnet';
$Definition['Participated'] = 'Deltok';
$Definition['ParticipatedHomepageTitle'] = 'Deltatte diskusjoner';
$Definition['Password'] = 'Passord';
$Definition['PasswordRequest'] = 'Noen har bedt om å tilbakestille passordet ditt på %2$s. For å tilbakestille passord, følg denne lenken: 

%3$s

Hvis du ikke har bedt om dette, se bort fra denne e-posten. 

';
$Definition['Passwords don\'t match'] = 'Passordene stemmer ikke overens med hverandre.';
$Definition['Paste the URL of an image to quickly embed it.'] = 'Lim inn URL-en til et bilde for å integrere det raskt.';
$Definition['Permalink'] = 'Permalenke';
$Definition['permalink'] = 'permalenke';
$Definition['Permanent (301)'] = 'permanent (301)';
$Definition['PermissionErrorMessage'] = 'Du har dessverre ikke tilgang til å gjøre dette.';
$Definition['PermissionErrorTitle'] = 'Problem med tilgang';
$Definition['PermissionRequired.Garden.Moderation.Manage'] = 'Du må være en moderator for å gjøre dette. ';
$Definition['PermissionRequired.Garden.Settings.Manage'] = 'Du må være en administrator for å gjøre dette. ';
$Definition['PermissionRequired.Javascript'] = 'Du må aktivere javascript for å gjøre dette. ';
$Definition['Photogenic'] = 'Fotogen';
$Definition['Picture'] = 'Bilde';
$Definition['Pinned'] = 'Festet';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Vennligst vent mens du omdirigeres. Hvis du ikke omdirigeres, klikk
<a href="%s">her</a>.';
$Definition['Popular'] = 'Populær';
$Definition['Popular Groups'] = 'Populære grupper';
$Definition['Popular Tags'] = 'Populære emneord';
$Definition['Position'] = 'Posisjon';
$Definition['Post'] = 'Innlegg';
$Definition['Post Comment'] = 'Publiser kommentar';
$Definition['Post Discussion'] = 'Publiser diskusjon';
$Definition['Post edited by %1$s at %2$s'] = 'Innlegg redigert av %1$s ved %2$s';
$Definition['Posts'] = 'Innlegg';
$Definition['Posts.Plural: %s'] = 'Innlegg: %s';
$Definition['Posts.Singular: %s'] = 'Innlegg: %s';
$Definition['Posts: %s'] = 'Innlegg: %s';
$Definition['Post this anonymously'] = 'Legg ut dette anonymt ';
$Definition['Powered by %s'] = 'Dette forumet kjører %s';
$Definition['Powered by Vanilla'] = 'Levert av Vanilla';
$Definition['PreferenceBadgeEmail'] = 'Varsle meg når jeg får et merke. ';
$Definition['PreferenceBadgePopup'] = 'Varsle meg når jeg får et merke. ';
$Definition['Preview'] = 'Forhåndsvis';
$Definition['Previous'] = 'Forrige';
$Definition['Privacy'] = 'Personvern';
$Definition['Privacy Settings'] = 'Personvernsinstillinger';
$Definition['Private'] = 'Privat';
$Definition['Private group.'] = 'Alle kan se gruppen, men kun medlemmer kan se innholdet i gruppen. Personer må søke eller bli invitert med. ';
$Definition['Private Note for Moderators'] = 'Privat melding til moderatorer';
$Definition['Problem with credentials.'] = 'Problem med referanser.';
$Definition['Proceed'] = 'Fortsett';
$Definition['Profile'] = 'Profil';
$Definition['ProfileFieldsCustomDescription'] = 'Bruk disse feltene til å lage egendefinert profilinformasjon. Du kan oppgi ting som "Sivilstatus", "Skype", eller "Yndlingsdinosaur". Vær kreativ!';
$Definition['Profile Page'] = 'Profilside';
$Definition['Profile Picture'] = 'Profilbilde';
$Definition['Profiles'] = 'Profiler';
$Definition['Promote'] = 'Promotere';
$Definition['Public'] = 'Offentlig';
$Definition['Public group.'] = 'Alle kan se gruppen og dets innhold. Alle kan bli med';

$Definition['Q&A Accepted'] = 'Besvart ✓';
$Definition['Q&A Answered'] = 'Besvart';
$Definition['Q&A Options'] = 'Q&A-alternativer';
$Definition['Q&A Question'] = 'Spørsmål';
$Definition['QnA Accepted Answer'] = 'Besvart ✓';
$Definition['Question'] = 'Spørsmål';
$Definition['question'] = 'spørsmål';
$Definition['Question Title'] = 'Diskusjonstittel';
$Definition['Quote'] = 'Sitat';
$Definition['Quote Folding'] = 'Sitatbretting';
$Definition['Quote on'] = 'på';
$Definition['Quote Settings'] = 'Sitatinnstillinger';
$Definition['Quote wrote'] = 'skrev';

$Definition['Rank'] = 'Rangering';
$Definition['Ranks.ActivityFormat'] = '{AktivitetBruker-ID, bruker} {AktivitetBruker-ID, flertall, ble, ble} forfremmet til
{Data.Navn,klartekst}.';
$Definition['Ranks.NotificationFormat'] = 'Gratulerer! Du har blitt forfremmet til {Data.Navn, klartekst}.';
$Definition['Re: %s'] = 'Re:%s';
$Definition['Reason'] = 'Årsak';
$Definition['Reason (optional)'] = 'Årsak (valgfritt)';
$Definition['Recent Activity'] = 'Siste aktiviteter';
$Definition['Recent Discussions'] = 'Siste diskusjoner';
$Definition['recently'] = 'nylig';
$Definition['Recent Moderator Activity'] = 'Nylig moderator aktivitet';
$Definition['Recent Tutorials'] = 'Nylige instruksjoner';
$Definition['Recipients'] = 'Mottakere';
$Definition['RecipientUserID'] = 'mottakere';
$Definition['Redirecting...'] = 'Omdirigerer...';
$Definition['Refetch Page'] = 'Hent side på nytt';
$Definition['Register'] = 'Registrer deg';
$Definition['Register IP'] = 'Registrer IP';
$Definition['Register with %s'] = 'Registrer deg';
$Definition['Registration URL'] = 'URL-registrering ';
$Definition['Reject'] = 'Avvis';
$Definition['Reject this answer.'] = 'Avvis dette svaret';
$Definition['Remember me'] = 'Husk meg';
$Definition['Remember me on this computer'] = 'Husk meg på denne maskinen';
$Definition['Remote Configuration'] = 'Fjernkonfigurasjon';
$Definition['Remove'] = 'Fjern';
$Definition['Removed by'] = 'Fjernet av';
$Definition['Remove from %s'] = 'Fjern fra %s';
$Definition['Remove Invitation'] = 'Fjern invitasjon';
$Definition['Remove My Picture'] = 'Fjern bildet mitt';
$Definition['Remove Picture'] = 'Fjern bilde';
$Definition['Remove Warning'] = 'Fjern advarsel';
$Definition['Rename Forum'] = 'Gi forumet nytt navn';
$Definition['Reopen'] = 'Gjenåpne';
$Definition['Replies'] = 'Svar';
$Definition['Reply'] = 'Svar';
$Definition['Report'] = 'Rapport';
$Definition['Report %s'] = 'Rapporter %s';
$Definition['Reported by: '] = 'Rapportert av:';
$Definition['Reported Posts'] = 'Rapporterte innlegg';
$Definition['Report Notes'] = 'Notater';
$Definition['Report Reason'] = 'Årsak';
$Definition['Request a new password'] = 'Be om nytt passord';
$Definition['Request a new password →'] = 'Be om nytt passord →';
$Definition['Reset Password'] = 'Nullstill passord';
$Definition['reverse'] = 'reverser';
$Definition['Revoke'] = 'Tilbakekall';
$Definition['Revoked badge.'] = 'Tilbakekalt merke.';
$Definition['role'] = 'rolle';
$Definition['RoleID'] = 'rolle';
$Definition['Roles'] = 'Roller';
$Definition['roles'] = 'roller';

$Definition['Save'] = 'Lagre';
$Definition['Save Comment'] = 'Lagre kommentar';
$Definition['Save Draft'] = 'Lagre utkast';
$Definition['Save Poll'] = 'Lagre poll';
$Definition['Save Preferences'] = 'Lagre instillinger';
$Definition['Save your password'] = 'Lagre passordet ditt';
$Definition['Search'] = 'Søk';
$Definition['Search %s'] = 'Søk %s';
$Definition['search archived'] = 'søk arkivert';
$Definition['SearchBoxPlaceHolder'] = 'Søk';
$Definition['Search for a tag.'] = 'Søk etter hele eller deler av en etikett. ';
$Definition['Search results for \'%s\''] = 'Resultater for \'%s\'';
$Definition['search subcategories'] = 'søk underkategorier';
$Definition['Second Anniversary'] = 'Toårsjubileum';
$Definition['Secret'] = 'Hemmelig';
$Definition['Sections'] = 'Deler';
$Definition['Security Check'] = 'Sikkerhetssjekk';
$Definition['Select an image on your computer (2mb max)'] = 'Velg et bilde på din datamaskin (max. 2MB).';
$Definition['Select one of the following avatars:'] = 'Velg en av følgende avatarer:';
$Definition['Send a New Message'] = 'Send en ny melding. ';
$Definition['Send Message'] = 'Send melding';
$Definition['Send Report'] = 'Send rapport';
$Definition['Send report'] = 'Send rapport';
$Definition['sep and'] = 'og';
$Definition['Set a New Warning Level'] = 'Sett nytt advarselsnivå';
$Definition['Set A Password'] = 'Lag et passord';
$Definition['Setting'] = 'Innstilling';
$Definition['Settings'] = 'Instillinger';
$Definition['Seventh Anniversary'] = 'Syvårsjubileum';
$Definition['Severity'] = 'Strenghet';
$Definition['Share'] = 'Del';
$Definition['Shared Accounts'] = 'Delte kontoer';
$Definition['she'] = 'henne';
$Definition['Shown only on mobile'] = 'Vis kun på mobil';
$Definition['Show unfollowed categories'] = 'Vis kategorier som ikke følges';
$Definition['Sign-In URL'] = 'Innloggings-URL';
$Definition['Sign-Out URL'] = 'Utloggings-URL';
$Definition['Signature Code'] = 'Signaturkode';
$Definition['Signature invalid.'] = 'Ugyldig signatur.';
$Definition['Signatures'] = 'Signaturer';
$Definition['Signature Settings'] = 'Signaturinnstillinger';
$Definition['Sign In'] = 'Logg inn';
$Definition['SignIn'] = 'Logg inn';
$Definition['SigningOut'] = 'Slapp av et par sekunder mens vi logger deg av.';
$Definition['Sign In or Register to Comment.'] = '<a href="{SignInUrl,html}"{Popup}>Logg inn</a> eller <a href="{RegisterUrl,html}">Registrer deg</a> for å kommentere. ';
$Definition['Sign in to vote!'] = 'Logg inn for å stemme!';
$Definition['Sign In with %s'] = 'Logg inn med %s';
$Definition['Sign In with Disqus'] = 'Logg inn med Disqus';
$Definition['Sign In with Facebook'] = 'Logg på med Facebook';
$Definition['Sign In with Google'] = 'Logg inn med Google';
$Definition['Sign In with OpenID'] = 'Logg inn med OpenID';
$Definition['Sign In with Twitter'] = 'Logg inn med Twitter';
$Definition['Sign Out'] = 'Logg av';
$Definition['sign out'] = 'logg ut';
$Definition['Sign Up'] = 'Registrer deg';
$Definition['Sink'] = 'Senk';
$Definition['Sink this discussion'] = 'Senk denne diskusjonen';
$Definition['Sitemap Settings'] = 'Sidekart-innstillinger';
$Definition['Sixth Anniversary'] = 'Seksårsjubileum';
$Definition['Social'] = 'Sosiale medier';
$Definition['somebody'] = 'noen';
$Definition['Someone\'s answered your question. You need to accept/reject the answer.'] = 'Noen har besvart spørsmålet ditt. Du trenger å akseptere/avvise svaret. ';
$Definition['sorted by'] = 'sortert etter';
$Definition['Source:'] = 'Kilde:';
$Definition['Source Code'] = 'Kode';
$Definition['Spam Queue'] = 'Spam-kø';
$Definition['Split'] = 'Deling';
$Definition['Split Comments'] = 'Delte kommentarer';
$Definition['Spoof User'] = 'Lur bruker';
$Definition['Start a New Conversation'] = 'Start en ny samtale';
$Definition['Start a New Discussion'] = 'Lag en ny tråd';
$Definition['Start Conversation'] = 'Start samtale';
$Definition['Started By'] = 'Startet av';
$Definition['Started by %1$s'] = 'Startet av %1$s';
$Definition['Start your First Discussion'] = 'Start din første diskusjon';
$Definition['Stop following'] = 'Slutt å følge';
$Definition['Strikethrough'] = 'Gjennomstreking';
$Definition['Strip images out of signatures'] = 'Fjerne bilder fra signaturer';
$Definition['Strip images out of signatures?'] = 'Rens signaturer for bilder?';
$Definition['Subject'] = 'Emne';
$Definition['Suggested Value'] = 'Foreslått verdi';

$Definition['Tagged'] = 'Merket';
$Definition['Tagged with '] = 'Merket med';
$Definition['Tagged with "%s"'] = 'Merket med "%s"';
$Definition['Tagging'] = 'Merking';
$Definition['Tag Name'] = 'Etikettenavn';
$Definition['Tags'] = 'Etiketter';
$Definition['tags'] = 'etiketter';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Etiketter er nøkkelord brukere kan gi diskusjoner for å hjelpe med å kategorisere spørsmålet deres med andre lignende spørsmål. ';
$Definition['Take Action'] = 'Foreta handling';
$Definition['Take Action:'] = 'Foreta handling:';
$Definition['Target'] = 'Mål';
$Definition['Tell the user why you\'re warning them'] = 'Fortell bruker hvorfor du advarer dem';
$Definition['Tell us why you want to join!'] = 'Fortell oss hvorfor du ønsker å bli med!';
$Definition['Tenth Anniversary'] = 'Tiårsjubileum';
$Definition['Terms'] = 'Betingelser';
$Definition['TermsOfService'] = 'Betingelsene';
$Definition['Terms of Service'] = 'Betingelsene';
$Definition['TermsOfServiceText'] = '
   <p>You agree, through your use of this service, that you will not use this
   community to post any material which is knowingly false and/or defamatory,
   inaccurate, abusive, vulgar, hateful, harassing, obscene, profane, sexually
   oriented, threatening, invasive of a person\'s privacy, or otherwise violative
   of any law. You agree not to post any copyrighted material unless the
   copyright is owned by you.</p>
   
   <p>We at this community also reserve the right to reveal your identity (or
   whatever information we know about you) in the event of a complaint or legal
   action arising from any message posted by you. We log all internet protocol
   addresses accessing this web site.</p>
   
   <p>Please note that advertisements, chain letters, pyramid schemes, and
   solicitations are inappropriate on this community.</p>
   
   <p>We reserve the right to remove any content for any reason or no reason at
   all. We reserve the right to terminate any membership for any reason or no
   reason at all.</p>
   
   <p>You must be at least 13 years of age to use this service.</p>
';
$Definition['Text  Max  Length'] = 'Maksimal lengde på tekst';
$Definition['the category'] = 'kategorien';
$Definition['The conversation has been cleared.'] = 'Samtalen har blitt slettet. ';
$Definition['The email you entered in use by another member.'] = 'e-post adressen er allerede i bruk.';
$Definition['The email you have entered is already related to an existing account.'] = 'E-post adressen du har skrevet inn er allerede i bruk av noen på dette forumet';
$Definition['The file failed to upload.'] = 'Filen ble ikke lastet opp. ';
$Definition['their'] = 'deres';
$Definition['The name you entered is already in use by another member.'] = 'Dette brukernavnet er allerede i bruk.';
$Definition['The page you were looking for could not be found.'] = 'Siden du ser etter finnes ikke, vennligst sjekk adressen på nytt.';
$Definition['The quote had to be converted from %s to %s.'] = 'Sitatet måtte konverteres fra %s til %s. Noe formatering kan ha gått tapt. ';
$Definition['There are no tags in the system yet.'] = 'Det er ingen etiketter i systemet ennå. ';
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'reCAPTCHA koden ble ikke skrevet inn korrekt.';
$Definition['There is already an account with the same username (%1$s) or email (%2$s) as you. You can either create a new account, or you can enter the credentials for your existing forum account.'] = 'Det finnes allerede en konto med samme brukernavn (%1$s) eller e-mail (%2$s) som deg. Du kan enten opprette en ny konto, eller du kan skrive inn berettigelsesbeviset for din eksisterende forumkonto. ';
$Definition['The response was not in the correct format.'] = 'Svaret var ikke i korrekt format. ';
$Definition['There was an error connecting to Disqus'] = 'Det oppstod en feil ved tilkobling til Disqus';
$Definition['There was an error connecting to Facebook'] = 'Det oppstod en feil ved tilkobling til Facebook';
$Definition['There was an error uploading the file. It is most likely because the file is too large.'] = 'Det oppstod en feil ved opplasting av filen. Det skjedde mest sannsynlig fordi filen er for stor. ';
$Definition['The site is currently undergoing maintenance.'] = 'Siden gjennomgår for tiden vedlikeholdsarbeid. ';
$Definition['The uploaded file was too big (max %s).'] = 'Filen du lastet opp var for stor (maks %s). ';
$Definition['they'] = 'de';
$Definition['Third Anniversary'] = 'Treårsjubileum';
$Definition['This answer was %s.'] = 'Dette svaret var %s. ';
$Definition['This answer was Accepted.'] = 'Dette svaret ble akseptert';
$Definition['This discussion has been closed.'] = 'Denne diskusjonen er lukket.';
$Definition['This discussion is related to an undefined foriegn content source.'] = 'Denne diskusjonen er relatert til en udefinert fremmed innholdskilde. ';
$Definition['This discussion was created from comments split from: %s.'] = 'Denne diskusjonen ble opprettet fra kommentarer delt fra: %s. ';
$Definition['This discussion was merged into %s'] = 'Diskusjonen ble flettet sammen til %s';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Størrelsen på dette bildet har blitt endret for å passe inn på side. Klikk for å forstørre.';
$Definition['This is a private poll: no-one will see what you voted for.'] = 'Dette er en privat poll: ingen vil se hva du har stemt på. ';
$Definition['This is a public poll: others will see what you voted for.'] = 'Dette er en offentlig poll: andre vil kunne se hva du stemte på. ';
$Definition['This is a system account and does not represent a real person.'] = 'Dette er en systemkonto og representerer ikke en ekte person. ';
$Definition['This Month\'s Leaders'] = 'Denne månedens ledere';
$Definition['This question\'s answer has been accepted.'] = 'Dette spørsmålets svar har blitt akseptert. ';
$Definition['This user has been verified as a non-spammer.'] = 'Denne brukeren er verifisert som en non-spammer.';
$Definition['This user has not been verified as a non-spammer.'] = 'Brukeren har ikke blitt verifisert som en ikke-spammer. ';
$Definition['This user has not commented yet.'] = 'Denne brukeren har ikke kommentert ennå. ';
$Definition['This user has not made any discussions yet.'] = 'Denne brukeren har ikke diskutert ennå. ';
$Definition['This user is verified as a non-spammer'] = 'Denne brukeren er verifisert som en ikke-spammer';
$Definition['This warning has expired. Do you want to completely delete it?'] = 'Advarselen har utløpt. Ønsker du å slette den helt?';
$Definition['This Week\'s Leaders'] = 'Denne ukes ledere';
$Definition['Thumbnail'] = 'Ikon';
$Definition['Title'] = 'Tittel';
$Definition['Toggle full page'] = 'Flikk hele siden';
$Definition['Toggle HTML view'] = 'Bytt HTML-visning';
$Definition['Toggle lights'] = 'Flikk lys';
$Definition['Topic'] = 'Emne';
$Definition['Topics'] = 'Emner';
$Definition['To send another confirmation email click <a href="%s">here</a>.'] = 'For å sende en til bekreftelse på e-mail klikk <a href="%s">her</a>.';
$Definition['To use reCAPTCHA you must get an API key from %s'] = 'For å bruke reCAPTCHA må du få en API-nøkkel fra %s';
$Definition['Transport error: %s'] = 'En fatal feil har skjedd mens forumet prøvde å gjennomføre forespørselen.<br />Serveren ga følgende respons før den begikk seppuku - %s';
$Definition['Turn ON'] = 'Skru PÅ';
$Definition['Twitter Settings'] = 'Twitter-innstillinger';
$Definition['Type'] = 'Condition Type';

$Definition['Unable to send message, %s is ignoring you.'] = 'Klarer ikke å sende melding, %s ignorerer deg. ';
$Definition['Unannounce'] = 'Fjern kunngjøring';
$Definition['Unanswered'] = 'Ubesvart';
$Definition['Unanswered Questions'] = 'Ubesvart';
$Definition['unavailable'] = 'utilgjengelig';
$Definition['Unban User'] = 'Avslutt bortvising av bruker';
$Definition['Unbookmark'] = 'Slett bokmerke';
$Definition['Undefined discussion body.'] = 'Udefinert diskusjonsgruppe. ';
$Definition['Undefined discussion subject.'] = 'Udefinert diskusjonsemne. ';
$Definition['Undefined foreign content'] = 'Udefinert fremmed innhold';
$Definition['Undo Follow'] = 'Angre følging';
$Definition['Unfollow'] = 'Slutt å følge';
$Definition['Unhide'] = 'Ikke skjul';
$Definition['Unignore'] = 'Ikke ignorer';
$Definition['UniqueID'] = 'Unik ID';
$Definition['Unknown'] = 'Ukjent';
$Definition['Unknown client: %s.'] = 'Ukjent klient: %s.';
$Definition['Unordered list'] = 'Uordnet liste';
$Definition['Unread'] = 'Ulest';
$Definition['Unread Discussions'] = 'Uleste diskusjoner';
$Definition['Unsink'] = 'Hev';
$Definition['Unspecified'] = 'Uspesifisert';
$Definition['Upcoming Events'] = 'Kommende arrangement';
$Definition['Update'] = 'Oppdater';
$Definition['Updated badge'] = 'Oppdatert merke';
$Definition['Upload'] = 'Last opp';
$Definition['Uploading...'] = 'Laster opp...';
$Definition['UrlCode'] = 'Url-kode';
$Definition['Use My Current Password'] = 'Bruk mitt nåværende passord';
$Definition['User "%s" does not exist.'] = 'Bruker "%s" eksisterer ikke. ';
$Definition['Username'] = 'Brukernavn';
$Definition['Username can only contain letters, numbers, and underscores.'] = 'Brukernavn kan kun inneholde bokstaver, tall og understreker.';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = 'Brukernavnet kan bare inneholde bokstaver, tall, understrek og må være mellom 3 og 20 tegn.';
$Definition['UsernameError'] = 'Brukernavnet kan bare inneholde bokstaver, tall, understrek og må være mellom 3 og 20 tegn.';
$Definition['Username or email'] = 'Brukernavn eller e-mail';
$Definition['User not found.'] = 'Beklager, ingen konto tilknyttet e-mailen/brukernavnet du skrev inn ble funnet. ';
$Definition['Users Count'] = 'Brukertelling';

$Definition['ValidateBanned'] = 'Den %s er ikke tillatt.';
$Definition['ValidateBoolean'] = '%s er ikke en gyldig boolsk.  ';
$Definition['ValidateConnection'] = 'Tilkoblingsparametrene du spesifiserte klarte ikke å åpne en kobling til datanasen. Databasen rapporterte følgende feil: <code>%s</code>';
$Definition['ValidateDate'] = '%s er ikke en gyldig dato. ';
$Definition['ValidateDecimal'] = '%s er ikke en gyldig desimal.';
$Definition['ValidateEmail'] = '%s ser ikke ut til å være gyldig. ';
$Definition['ValidateEnum'] = '%s er ikke gyldig. ';
$Definition['ValidateFormat'] = 'Du har ikke lov til å legge ut ren html. ';
$Definition['ValidateInteger'] = '%s er ikke et gyldig heltall.';
$Definition['ValidateIntegerArray'] = '%s må være en kommaavgrenset liste av siffer.';
$Definition['ValidateLength'] = '%1$s is %2$s tegn for langt.';
$Definition['ValidateMatch'] = 'Feltene %s stemmer ikke overens.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Du må velge minst en %s. ';
$Definition['ValidateRegex'] = '%s virker ikke å være i korrekt format. ';
$Definition['ValidateRequired'] = '%s er påkrevd';
$Definition['ValidateRequiredArray'] = 'Du må velge minst en %s. ';
$Definition['ValidateTag'] = 'Etiketter kan ikke inneholde mellomrom. ';
$Definition['ValidateTime'] = '%s er ikke en gyldig tid. ';
$Definition['ValidateTimestamp'] = '%s er ikke et gyldig tidsstempel. ';
$Definition['ValidateUrlStringRelaxed'] = '%s kan ikke inneholde skråstreker, sitater eller etikettetegn. ';
$Definition['ValidateUsername'] = 'Brukernavn må være 3-20 tegn og bestå av bokstaver, tall og understreker. ';
$Definition['ValidateVersion'] = '%s feltet er ikke et gyldig versjonsnummer. Se php-versjonen_sammenlign()funksjon for eksempler på gyldige versjonnummere. ';
$Definition['Value'] = 'Condition Expression';
$Definition['Vanilla Statistics'] = 'Vanilla-statistikk';
$Definition['Vanilla Statistics Plugin'] = 'Vanilla Statistics programtillegg';
$Definition['Verified'] = 'Bekreftet';
$Definition['Verifying your credentials...'] = 'Verifiserer berettigelsesbevis..';
$Definition['Video embedding has been disabled.'] = 'Videoinnkapsling har blitt deaktivert. URL-er vil ikke overføres til sine innkapslete ekvivalenter.';
$Definition['View Badge'] = 'Se merke';
$Definition['Viewing'] = 'Viser';
$Definition['Views'] = 'Visninger';
$Definition['Visible'] = 'Synlig';
$Definition['Visits'] = 'Antall besøk';
$Definition['Visit Site'] = '← Besøk siden';
$Definition['Vote'] = 'Stem';
$Definition['Vote Down'] = 'Stem ned';
$Definition['Votes'] = 'Stemmer';
$Definition['Vote Up'] = 'Stem opp';

$Definition['wall'] = 'vegg';
$Definition['Want to take part in this discussion? Click one of these:'] = 'Ønsker du å delta i denne diskusjonen? Trykk på en av disse knappene:';
$Definition['Warn'] = 'Advar';
$Definition['Warn %s'] = 'Advarsel %s';
$Definition['Warned for'] = 'Advart for';
$Definition['Warning'] = 'Advarsel';
$Definition['Warnings'] = 'Advarsler';
$Definition['WarningTitleFormat'] = '{Sett innBruker-ID, Bruker} advarte {AdvarBruker-ID, bruker} for {Poeng, flertall, %s poeng}. ';
$Definition['WarningTitleFormat.Notice'] = '{Sett innBruker-ID, Bruker} advarte {AdvarBruker-ID, bruker} for {Poeng, flertall,%s poeng} (bare en melding).  ';
$Definition['was'] = 'var';
$Definition['Website'] = 'Nettside';
$Definition['weeks'] = 'uker';
$Definition['Welcome Aboard!'] = 'Velkommen ombord!';
$Definition['were'] = 'var';
$Definition['What\'s This?'] = 'Hva er dette?';
$Definition['What to search'] = 'Hva skal du søke etter';
$Definition['Where do you want to announce this discussion?'] = 'Hvor ønsker du å annonsere denne diskusjonen?';
$Definition['Who\'s Online'] = 'Hvem er online';
$Definition['Whos Online'] = 'Hvem er online';
$Definition['Why are you Banning this user?'] = 'Hvorfor vil du bortvise denne brukeren?';
$Definition['Write a comment'] = 'Skriv en kommentar';
$Definition['Write Comment'] = 'kommentér';
$Definition['Write something about yourself...'] = 'Skriv noe om deg selv...';

$Definition['Yes'] = 'Ja';
$Definition['You'] = 'Du';
$Definition['you'] = 'du';
$Definition['You\'ve been Jailed.'] = 'Du har blitt fengslet. ';
$Definition['You already have an account here.'] = 'ConnectAccountExists';
$Definition['You are about to ban {User.UserID,user}.'] = 'Du er i ferd med å bortvise {Bruker.Bruker-ID, bruker}. ';
$Definition['You are about to unban {User.UserID,user}.'] = 'Du er i ferd med å oppheve bortvisning av {Bruker.Bruker-ID, bruker}. ';
$Definition['You are allowed to create %s groups.'] = 'Du har lov til å opprette %s grupper. ';
$Definition['You are connected as %s through %s.'] = 'Du er tilkoblet som %s gjennom %s. ';
$Definition['You are connected through %2$s.'] = 'Du er tilkoblet gjennom %2$s.';
$Definition['You are currently only viewing categories that you follow.'] = 'Du ser nå bare kategoriene du følger på forumet.';
$Definition['You are currently viewing all categories.'] = 'Du ser nå alle kategoriene på forumet.';
$Definition['You are editing %s\'s signature'] = 'Du redigerer %s`s signatur. ';
$Definition['You are limited to %s recipient.'] = 'Du er begrenset til %s mottaker. ';
$Definition['You are limited to %s recipients.'] = 'Du er begrenset til %s mottakere. ';
$Definition['You can\'t leave the group you started.'] = 'Du kan ikke forlate gruppen du startet. ';
$Definition['You can either ask a question or start a discussion.'] = 'Du kan enten stille et spørsmål eller starte en diskusjon. Velg hva du ønsker å gjøre under. ';
$Definition['You can follow individual categories and be notified of all posts within them.'] = 'Du kan følge hver enkelt kategori og få varslinger om nye poster innen kategorien.';
$Definition['You cannot edit the thumbnail of an externally linked profile picture.'] = 'Du kan ikke redigere miniatyrvisningen av en profilbilde med ekstern lenke. ';
$Definition['You can only specify up to %s tags.'] = 'Du kan kun spesifisere opptil %s etiketter. ';
$Definition['You can remove or ban this member from the group.'] = 'Du kan fjerne eller bortvise dette medlemmet fra gruppen. Bortviste medlemmer vil ikke kunne bli med i gruppen igjen. ';
$Definition['You can use HTML in your signature.'] = 'Du kan bruke <b><a href="http://htmlguide.drgrog.com/cheatsheet.php" target="_new">Ren html</a></b> i signaturen din. ';
$Definition['You don\'t have permission to do that.'] = 'Du har dessverre ikke tilgang til å gjøre dette.';
$Definition['You do not have any %s yet.'] = 'Du har ikke noen %s ennå. ';
$Definition['You do not have any bookmarks.'] = 'Du har ingen bokmerker';
$Definition['You do not have any conversations.'] = 'Du har ingen samtaler';
$Definition['You do not have any drafts.'] = 'Du har ingen kladder';
$Definition['You do not have any notifications yet.'] = 'Du har ingen varslinger enda.';
$Definition['You do not have enough invitations left.'] = '0 invitasjoner igjen.';
$Definition['You do not have permission to write new comments.'] = 'Du har ikke tillatelse til å skrive nye kommentarer. ';
$Definition['YouEarnedBadge'] = 'Du fikk dette merket';
$Definition['You have answered questions'] = 'Du har besvart spørsmål';
$Definition['You have entered an invalid discussion title'] = 'Du har skrevet inn en ugyldig diskusjonstittel. ';
$Definition['You haven\'t read this yet.'] = 'Du har ikke lest dette ennå.';
$Definition['You have not started any discussions.'] = 'Du har ikke startet noen diskusjoner';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = 'Ro deg ned, du har postet %1$s ganger innenfor %2$s sekunder... vent %3$s før du poster igjen.';
$Definition['You have selected %1$s.'] = 'Du har valgt %1$s.';
$Definition['You have selected %1$s in this discussion.'] = 'Du har valgt %1$s i denne diskusjonen. ';
$Definition['You have to select at least 2 discussions to merge.'] = 'Du må velge minst 2 diskusjoner å slå sammen. ';
$Definition['You must agree to the terms of service.'] = 'Du må akseptere betingelsene.';
$Definition['You need to confirm your email address.'] = 'Du må bekrefte e-postadressen. Klikk <a href="{/entry/emailconfirmrequest,url}">her</a> for å sende bekreftelseseposten på nytt.';
$Definition['You need to sign in before you can do this.'] = 'Du må logge deg inn før du kan gjøre dette. ';
$Definition['your'] = 'din';
$Definition['Your changes have been saved.'] = 'Dine endringer har blitt lagret';
$Definition['Your changes have been saved successfully.'] = 'Lagringen av dine endringer var vellykket.';
$Definition['Your changes were saved.'] = 'Endringene dine har blitt lagret. ';
$Definition['Your email has been successfully confirmed.'] = 'E-postadressen din har blitt bekreftet.';
$Definition['Your invitation has been sent.'] = 'Din invitasjon har blitt sendt!';
$Definition['Your old password was incorrect.'] = 'Ugyldig passord.';
$Definition['Your password has been changed.'] = 'Passordet ditt har blitt endret.';
$Definition['Your picture has been removed.'] = 'Bildet ditt har blitt fjernet.';
$Definition['Your post will appear once it\'s been approved.'] = 'Ditt innlegg vil vises så snart det er godkjent. ';
$Definition['Your preferences have been saved.'] = 'Dine instillinger har blitt lagret.';
$Definition['Your private conversations with other members.'] = 'Dine private samtaler med andre medlemmer. ';
$Definition['Your registered username: <strong>%s</strong>'] = 'ConnectRegisteredName';
$Definition['Your request has been sent.'] = 'Din forespørsel er sendt. Sjekk e-mailen din for flere instruksjoner. ';
$Definition['Your settings have been saved.'] = 'Dine innstillinger har blitt lagret. ';
$Definition['Your settings have been saved successfully.'] = 'Lagringen av innstillingene dine var vellykket. ';
$Definition['Your warning was added.'] = 'Din advarsel ble lagt til';

$Definition[' You should '] = ' Du bør';

$Definition['You were added to a conversation.'] = '{Sett innBruker-ID, bruker} lagt til {VarsleBruker-ID, deg} til en <a href="{Url,htmlencode}">samtale</a>.';

$Definition['↳ No results for \'%s\''] = '↳ Ingen resultater for `%s`';
$Definition['↳ Search results for \'%s\''] = '↳ Søkeresultater for `%s`';
$Definition['↳ Show All'] = '↳ Vis alle';
